### PR TITLE
[Fastlane.Swift] Fix `OptionalConfigValue` for `Any`-based types.

### LINKED ISSUE #18654: [Fastlane.Swift] cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<Any?>'
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

As from version `2.182.0` I'm getting a number of 
`cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'`
errors. I'm using a swift Fastfile.

##### Command executed

Running any lane.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> $ bundle exec fastlane registerDevices

[✔] 🚀
[17:08:34]: loading manifest: /Users/afvhb/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/fastlane-2.182.0/fastlane/swift/upgrade_manifest.json
[17:08:35]: It looks like your `FastlaneSwiftRunner` project is not up-to-date
[17:08:35]: If you don't update it, fastlane could fail
[17:08:35]: We can try to automatically update it for you, usually this works 🎈 🐐
[17:08:35]: Should we try to upgrade just your `FastlaneSwiftRunner` project? (y/n)
y
[17:08:36]: Updated your FastlaneSwiftRunner project with the newest runner code
[17:08:36]: Resolving Swift Package Manager dependencies...
[17:08:36]: $ xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[17:08:37]: ▸ 2021-05-07 17:08:37.021 xcodebuild[87589:5237129] [MT] DVTPlugInManager: Required plug-in compatibility UUID F56A1938-53DE-493D-9D64-87EE6C415E4D for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
[17:08:37]: ▸ Command line invocation:
[17:08:37]: ▸     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[17:08:37]: ▸ User defaults from command line:
[17:08:37]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[17:08:38]: ▸ resolved source packages:
[17:08:38]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
2021-05-07 17:08:38.891 xcodebuild[87602:5237468] [MT] DVTPlugInManager: Required plug-in compatibility UUID F56A1938-53DE-493D-9D64-87EE6C415E4D for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
[17:08:40]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' build | tee /Users/afvhb/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
2021-05-07 17:08:40.577 xcodebuild[87611:5237722] [MT] DVTPlugInManager: Required plug-in compatibility UUID F56A1938-53DE-493D-9D64-87EE6C415E4D for GraphQL.ideplugin (com.apollographql.xcode.graphql) not present
▸ Compiling MatchfileProtocol.swift
▸ Compiling ScanfileProtocol.swift
▸ Compiling ScreengrabfileProtocol.swift
▸ Compiling GymfileProtocol.swift
▸ Compiling SnapshotfileProtocol.swift
▸ Compiling DeliverfileProtocol.swift
▸ Compiling PrecheckfileProtocol.swift
▸ Compiling Fastlane.swift
▸ Compiling Snapshotfile.swift
▸ Compiling LaneFileProtocol.swift
▸ Compiling Fastfile.swift

❌  /.../fastlane/Fastfile.swift:25:38: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<Any?>'

                        incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
                                                          ^

❌  /.../fastlane/Fastfile.swift:38:16: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        apiKeyPath: apiKeyPath,
                                    ^

❌  /.../fastlane/Fastfile.swift:40:18: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        gitUserEmail: gitUserEmail)
                                      ^

❌  /.../fastlane/Fastfile.swift:44:34: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
                                               ^

❌  /.../fastlane/Fastfile.swift:55:38: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<Any?>'

                        incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
                                                          ^

❌  /.../fastlane/Fastfile.swift:68:16: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        apiKeyPath: apiKeyPath,
                                    ^

❌  /.../fastlane/Fastfile.swift:70:18: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        gitUserEmail: gitUserEmail)
                                      ^

❌  /.../fastlane/Fastfile.swift:73:34: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
                                               ^

❌  /.../fastlane/Fastfile.swift:84:38: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<Any?>'

                        incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
                                                          ^

❌  /.../fastlane/Fastfile.swift:97:16: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        apiKeyPath: apiKeyPath,
                                    ^

❌  /.../fastlane/Fastfile.swift:99:18: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        gitUserEmail: gitUserEmail)
                                      ^

❌  /.../fastlane/Fastfile.swift:102:34: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
                                               ^

❌  /.../fastlane/Fastfile.swift:123:66: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                registerDevices(devicesFile: "./fastlane/devices", apiKeyPath: apiKeyPath)
                                                                               ^

❌  /.../fastlane/Fastfile.swift:127:16: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        apiKeyPath: apiKeyPath,
                                    ^

❌  /.../fastlane/Fastfile.swift:129:18: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        gitUserEmail: gitUserEmail,
                                      ^

❌  /.../fastlane/Fastfile.swift:135:16: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        apiKeyPath: apiKeyPath,
                                    ^

❌  /.../fastlane/Fastfile.swift:137:18: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

                        gitUserEmail: gitUserEmail,
                                      ^

▸ Compiling main.swift
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /.../fastlane/Fastfile.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
[17:08:46]: Exit status: 65
+-----------+-----------------+
|        Lane Context         |
+-----------+-----------------+
| LANE_NAME | registerDevices |
+-----------+-----------------+
[17:08:46]: Exit status: 65
[17:08:46]: fastlane finished with errors

[!] Exit status: 65
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 11.3.1                                                   |
| Ruby                        | 2.7.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.31.1                                       |
| Installation Source         | ~/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | macOS 11.3.1 (20E241)                                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 12.5                                                     |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {

	let gitUrl = "git@github.com:whatever-company/elium-ios-code-signing.git"
	let gitUserEmail = "alexis.bronchart@gmail.com"
	let apiKeyPath = environmentVariable(get: "APPSTORE_API_KEY_PATH")

	func testFlightEliumLane() {
		desc("Push a new Elium build to TestFlight")

		cocoapods(repoUpdate: true)

		let buildNumber = environmentVariable(get: "BITRISE_BUILD_NUMBER")

		if buildNumber != "" {
			incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
		} else {
			incrementBuildNumber(xcodeproj: "EliumMobile.xcodeproj")
		}

		match(
			type: "appstore",
			readonly: true,
			appIdentifier: [
				"com.elium.EliumMobile", 
				"com.elium.EliumMobile.ShareExtension", 
				"com.elium.EliumMobile.NotificationService", 
				"com.elium.EliumMobile.Widgets"],
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail)

		buildApp(workspace: "EliumMobile.xcworkspace", scheme: "Elium.release")
		
		uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
	}

	func testFlightWhatevrLane() {
		desc("Push a new whatevr build to TestFlight")

		cocoapods(repoUpdate: true)

		let buildNumber = environmentVariable(get: "BITRISE_BUILD_NUMBER")

		if buildNumber != "" {
			incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
		} else {
			incrementBuildNumber(xcodeproj: "EliumMobile.xcodeproj")
		}

		match(
			type: "appstore",
			readonly: true,
			appIdentifier: [
				"com.elium.EliumMobile.whatevr", 
				"com.elium.EliumMobile.whatevr.ShareExtension", 
				"com.elium.EliumMobile.whatevr.NotificationService", 
				"com.elium.EliumMobile.whatevr.Widgets"],
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail)

		buildApp(workspace: "EliumMobile.xcworkspace", scheme: "whatevr.release")
		uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
	}

	func testFlightBnpparibaspfLane() {
		desc("Push a new SEED by Elium build to TestFlight")

		cocoapods(repoUpdate: true)

		let buildNumber = environmentVariable(get: "BITRISE_BUILD_NUMBER")

		if buildNumber != "" {
			incrementBuildNumber(buildNumber: "\(buildNumber)", xcodeproj: "EliumMobile.xcodeproj")
		} else {
			incrementBuildNumber(xcodeproj: "EliumMobile.xcodeproj")
		}

		match(
			type: "appstore",
			readonly: true,
			appIdentifier: [
				"com.elium.EliumMobile.bnpparibas-pf",
				"com.elium.EliumMobile.bnpparibas-pf.ShareExtension", 
				"com.elium.EliumMobile.bnpparibas-pf.NotificationService",
				"com.elium.EliumMobile.bnpparibas-pf.Widgets"],
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail)

		buildApp(workspace: "EliumMobile.xcworkspace", scheme: "bnpparibas-pf.release")
		uploadToTestflight(apiKeyPath: apiKeyPath, skipWaitingForBuildProcessing: true)
	}

	func registerDevicesLane() {
		desc("Registers the devices from the devices file to the dev portal")

		let appIDs = [
			"com.elium.EliumMobile", 
			"com.elium.EliumMobile.ShareExtension", 
			"com.elium.EliumMobile.NotificationService",
			"com.elium.EliumMobile.Widgets",
			"com.elium.EliumMobile.whatevr", 
			"com.elium.EliumMobile.whatevr.ShareExtension", 
			"com.elium.EliumMobile.whatevr.NotificationService",
			"com.elium.EliumMobile.whatevr.Widgets",
			"com.elium.EliumMobile.bnpparibas-pf",
			"com.elium.EliumMobile.bnpparibas-pf.ShareExtension", 
			"com.elium.EliumMobile.bnpparibas-pf.NotificationService",
			"com.elium.EliumMobile.bnpparibas-pf.Widgets"
		]

		registerDevices(devicesFile: "./fastlane/devices", apiKeyPath: apiKeyPath)
		match(
			type: "appstore", 
			appIdentifier: appIDs,
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail,
			forceForNewDevices: true, 
			verbose: true)
		match(
			type: "development", 
			appIdentifier: appIDs,
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail,
			forceForNewDevices: true, 
			verbose: true)
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.182.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.1.4        |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| concurrent-ruby               | 1.1.8        |
| i18n                          | 1.8.10       |
| minitest                      | 5.14.4       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.9        |
| activesupport                 | 5.2.6        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| httpclient                    | 2.8.3        |
| json                          | 2.5.1        |
| algoliasearch                 | 1.27.5       |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.452.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| netrc                         | 0.11.0       |
| ffi                           | 1.15.0       |
| ethon                         | 0.14.0       |
| typhoeus                      | 1.4.0        |
| cocoapods-core                | 1.10.1       |
| cocoapods-deintegrate         | 1.0.4        |
| cocoapods-downloader          | 1.4.0        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-trunk               | 1.5.0        |
| cocoapods-try                 | 1.2.0        |
| colored2                      | 3.1.2        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.3.1        |
| gh_inspector                  | 1.1.3        |
| molinillo                     | 0.6.6        |
| ruby-macho                    | 1.4.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| cocoapods                     | 1.10.1       |
| colored                       | 1.2          |
| highline                      | 2.0.3        |
| commander                     | 4.6.0        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.81.0       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.2       |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-05-07**
</details>
 </pre>
</details>

### Fastfile.swift

<details>
<pre>

import Foundation

class Fastfile: LaneFile {

	let gitUrl = "git@github.com:.../machintruc.git"
	let gitUserEmail = "..."
	let apiKeyPath = environmentVariable(get: "APPSTORE_API_KEY_PATH")

	func registerDevicesLane() {
		desc("Registers the devices from the devices file to the dev portal")

		let appIDs = [
			"com.machintruc", 
			"com.machintruc.ShareExtension", 
			"com.machintruc.Widgets"
		]

		registerDevices(devicesFile: "./fastlane/devices", apiKeyPath: apiKeyPath)
		match(
			type: "appstore", 
			appIdentifier: appIDs,
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail,
			forceForNewDevices: true, 
			verbose: true)
		match(
			type: "development", 
			appIdentifier: appIDs,
			apiKeyPath: apiKeyPath,
			gitUrl: gitUrl,
			gitUserEmail: gitUserEmail,
			forceForNewDevices: true, 
			verbose: true)
	}
}
 </pre>
</details>

### PR DESCRIPTION
**Pull request by minuscorp**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
`OptionalConfigValue` does not provide an `ExpressibleBy` interface for `Any?` parameters, so they have to be filtered out afterwards.
Fixes #18654

### Description
`OptionalConfigItem` does not apply to `Any` types to avoid a breaking compatibility against past releases. This PR resolves the issue.

### Testing Steps
1. Install the following branch:
```ruby
gem 'fastlane', :branch => 'https://github.com/minuscorp/fastlane/fix-configvalue-with-any-type'
```
2. Use an action with an `Any` value:
```swift
incrementBuildNumber(buildNumber: <#T##Any?#>)
```
3. Check that the value is being passed when it is not `nil`.
4. 🚀

### CODE REVIEW

File: fastlane/lib/fastlane/swift_fastlane_function.rb [hunk 1]
```diff
@@ -325,7 +326,7 @@ def implementation
         implm += "let args: [RubyCommand.Argument] = []\n"
       else
         implm += "let args = [#{args.group_by { |h| h[:name] }.keys.join(",\n")}]\n"
-        implm += ".compactMap { $0 }\n"
+        implm += ".compactMap { $0?.nilify(when: { $0.value == nil }) }\n"
```
Comment (ainame) [inline fastlane/lib/fastlane/swift_fastlane_function.rb:329]:
```suggestion
        implm += ".filter { $0?.value != nil } \n"
```

What about this? Isn't this simpler?

**Review by ainame — APPROVED** [review]
Had a minor suggestion to make it simpler but LGTM

File: fastlane/lib/fastlane/swift_fastlane_function.rb (hunk 1 above)
Comment (minuscorp) [reply fastlane/lib/fastlane/swift_fastlane_function.rb:329]: 🤦‍♂️ I'm an idiot

Comment (minuscorp) [reply fastlane/lib/fastlane/swift_fastlane_function.rb]: Wasn't exactly doing that, but gave me the idea to get rid of the `nilify` method ❤️

**Review by joshdholtz — CHANGES_REQUESTED** [review]
I tried doing `incrementBuildNumber(buildNumber: 5)` but I got 👇 

```sh
value of protocol type 'Any' cannot conform to 'ExpressibleByIntegerLiteral'; only struct/enum/class types can conform to protocols
```

Am I doing something wrong? 😇

**Comment by minuscorp** [comment]
But it works fine with you for float and string values?🤔

**Comment by RyuX51** [comment]
I tried the `fix-configvalue-with-any-types` branch and I'm getting

```
▸ Compiling Fastfile.swift

❌  .../Fastfile.swift:22:21: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

      echo(message: "Unknown parameter value \(bumpType)")
                    ^


** BUILD FAILED **
```

for the following code:
```
  func betaLane(withOptions options: [String: String]?) {

    let bumpType = options?["bumpType"]

    if !["major", "minor", "patch"].contains(bumpType) {
      echo(message: "Unknown parameter value \(bumpType)")
      return
    }
```

If I do without string interpolation it works fine. Thanks.

Since I'm coming from [18654](https://github.com/fastlane/fastlane/issues/18654), I'll just drop this here.

**Comment by minuscorp** [comment]
@RyuX51 could you check that your issue is solved now?

**Comment by RyuX51** [comment]
@minuscorp I'm sorry, `c1b9cf1`still behaves the same.

**Comment by minuscorp** [comment]
`bumpType` is `String` or `String?`?

**Comment by RyuX51** [comment]
It's `String`, but this isn't the problem. For example

```echo(message: "Unknown " + "parameter")```

and

```echo(message: "Unknown \("parameter")")```

also lead to the same error whereas

```echo(message: "Unknown parameter")```

is just fine.

**Comment by minuscorp** [comment]
I just tested using 

```swift
let string = "Foo"

echo("Message \(string)")
```
Working🤔

**Comment by RyuX51** [comment]
@minuscorp

```Using fastlane 2.182.0 from https://github.com/minuscorp/fastlane (at fix-configvalue-with-any-types@c1b9cf1)```

So this should be the right commit, right?

```
▸ Compiling Fastfile.swift

❌  /Users/mario/Repository/VJeton/fastlane/Fastfile.swift:24:12: missing argument label 'message:' in call

      echo("Message \(string)")
           ^



❌  /Users/mario/Repository/VJeton/fastlane/Fastfile.swift:24:12: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

      echo("Message \(string)")
           ^


** BUILD FAILED **
```

And when I add the `message:` it's again:

```
▸ Compiling Fastfile.swift

❌  /Users/mario/Repository/VJeton/fastlane/Fastfile.swift:24:21: cannot convert value of type 'String' to expected argument type 'OptionalConfigValue<String?>'

      echo(message: "Message \(string)")
                    ^


** BUILD FAILED **
```

**Comment by minuscorp** [comment]
Pretty confusing to me 😔 
image

**Comment by RyuX51** [comment]
@minuscorp Even `echo(message: String("Message"))` fails for me. 🤷‍♂️

**Comment by minuscorp** [comment]
I'd reset the repo and try to run the `generate_swift_api` lane before going further, maybe something in the project it's corrupted😞

**Comment by minuscorp** [comment]
@joshdholtz Can you replicate the issue or it is working fine for you?🤔

**Comment by minuscorp** [comment]
Any news @RyuX51 regarding the issue with interpolation?

**Comment by RyuX51** [comment]
@minuscorp Well, I haven't investigated further. I just set up a new project where I wanted to try a Fastlane.swift for the first time. The fact that I get this error while wanting to show a value in an informational output is not really a blocker for me. This problem just sounded a lot like what you are fixing here is related, and I just wanted to let you know. Since you can't even replicate the bug, I don't want to concern you with that.

**Comment by joshdholtz** [comment]
@minuscorp I’m still getting…

```sh
value of protocol type 'Any' cannot conform to 'ExpressibleByUnicodeScalarLiteral'; only struct/enum/class types can conform to protocols
```

when my `Fastlane.swift` file looks like…

```swift
incrementBuildNumber(buildNumber: "5")
```

Are you not getting that same thing? 🤔

**Comment by minuscorp** [comment]
@joshdholtz indeed, I removed all conformances to `Optional`,  as it seems to not accept `Any` meta value, differently from `AnyObject` which it could conform to those extensions. Fixed and tested:

```swift
incrementBuildNumber(buildNumber: 1.0, xcodeproj: "asd")
incrementBuildNumber(buildNumber: "1.0")
incrementBuildNumber(buildNumber: 1)
```

**Review by joshdholtz — APPROVED** [review]
This works for me! ❤️ LGTM

Merge whenever you are ready
