### PR TITLE
[match] Better Windows (and Linux) support

### LINKED ISSUE #13965: [match] fails with `readonly: true` for type, that doesn't exist in Git repo
```
sync_code_signing(
      git_url: "...",
      type: "appstore",
      app_identifier: "...",
      readonly: true
)
```

This results in an exception when type `appstore` is not present as a folder in the git repo:

```
λ bundle exec fastlane certificates
[✔] 🚀

[19:01:17]: ------------------------------
[19:01:17]: --- Step: default_platform ---
[19:01:17]: ------------------------------
[19:01:17]: Driving the lane 'ios certificates' 🚀
[19:01:17]: -------------------------------
[19:01:17]: --- Step: sync_code_signing ---
[19:01:17]: -------------------------------
[19:01:19]: Successfully loaded 'C:/Projects/Remote Fastlane/fastlane-remote/fastlane/Matchfile' 📄

+---------+------------------------------------------------------------------------------------+
|                         Detected Values from './fastlane/Matchfile'                          |
+---------+------------------------------------------------------------------------------------+
| git_url | ...  |
| type    | development                                                                        |
+---------+------------------------------------------------------------------------------------+


+-----------------------+------------------------------------------------------------------------------------+
|                                         Summary for match 2.111.0                                          |
+-----------------------+------------------------------------------------------------------------------------+
| git_url               | ...  |
| type                  | appstore                                                                           |
| app_identifier        | ["tools.fastlane.iosapp"]                                                          |
| readonly              | true                                                                               |
| git_branch            | master                                                                             |
| storage_mode          | git                                                                                |
| keychain_name         | login.keychain                                                                     |
| verbose               | false                                                                              |
| force                 | false                                                                              |
| skip_confirmation     | false                                                                              |
| shallow_clone         | false                                                                              |
| clone_branch_directly | false                                                                              |
| force_for_new_devices | false                                                                              |
| skip_docs             | false                                                                              |
| platform              | ios                                                                                |
+-----------------------+------------------------------------------------------------------------------------+

[19:01:19]: Cloning remote git repo...
[19:01:19]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[19:01:21]: 🔓  Successfully decrypted certificates repo
[19:01:21]: Skipping installation of certificate as it would not work on this operating system.

+-------------------+--------------------------------------------------+
|                        Installed Certificate                         |
+-------------------+--------------------------------------------------+
| User ID           | 4Z338HBBX3                                       |
| Common Name       | iPhone Distribution: Jan Piotrowski (4Z338HBBX3) |
| Organisation Unit | 4Z338HBBX3                                       |
| Organisation      | Jan Piotrowski                                   |
| Country           | US                                               |
| Start Datetime    | 2018-11-18 21:34:21 UTC                          |
| End Datetime      | 2019-11-18 21:34:21 UTC                          |
+-------------------+--------------------------------------------------+

+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | ios              |
| PLATFORM_NAME    | ios              |
| LANE_NAME        | ios certificates |
+------------------+------------------+
[19:01:21]: No such file or directory @ dir_initialize - C:/Users/Jan/AppData/Local/Temp/d20181220-6612-1tp4o54/profiles/appstore

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 💥   | sync_code_signing | 4           |
+------+-------------------+-------------+

[19:01:21]: fastlane finished with errors

[19:01:21]: Error accessing file, this might be due to fastlane's directory handling
[19:01:21]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details


#######################################################################
# fastlane 2.112.0 is available. You are on 2.111.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.112.0 Improvements and spaceship fixes
* [spaceship] fix Spaceship not returning AdHoc profile (#13945) via Riad Krim
* [spaceship] replace post_for_testflight_review with new public API (#13919) via Josh Holtz
* [deliver] default html generator to current dir (#13920) via Josh Holtz
* [core] remove leftover launch and completion analytics from UpdateChecker (#13918) via Jan Piotrowski
* [action] new action ensure_bundle_exec to enforce use of bundler (#13866) via Rishabh Tayal

Please update using `bundle update fastlane`
C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:236:in `open': No such file or directory @ dir_initialize - C:/Users/Jan/AppData/Local/Temp/d20181220-6612-1tp4o54/profiles/appstore (Errno::ENOENT)
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:236:in `entries'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:236:in `fetch_provisioning_profile'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:95:in `block (2 levels) in run'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:94:in `loop'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:94:in `block in run'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:93:in `each'
        from C:/Projects/Fastlane/fastlane/match/lib/match/runner.rb:93:in `run'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/sync_code_signing.rb:12:in `run'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        from Fastfile:28:in `block (2 levels) in parsing_binding'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from C:/Projects/Fastlane/fastlane/bin/fastlane:23:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
```

(Line #s may be out of whack as this is a local clone I am currently working on)

### PR DESCRIPTION
**Pull request by janpio**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
`match`/`sync_code_signing` doesn't work on Windows (and Linux) right now.

### Description
This PR improves the support by fixing quite a few bugs and moving Mac only code behind `if`s.

- Fix the `git` commands to clone the match git repo
- Fix the reading of certificate information
- Use `openssl` as a fallback when decoding provisioning profiles if not on Mac (and `security` does not exist)
- Skip the installation of certificate, key and provisioning profile into the Keychain if not on Mac
- Add a new `output_path` option where certificate, key and provisionig profile are saved to (which is necessary on non Mac machines, as there is no import into the non existing Keychain where one could export those manually)
- Fix a general crash when running match (with readonly) for types that are not in storage yet (closes #13965)
- Fix encryption/openssl test so this can actually fail on Windows where this currently is broken: Change encryption/openssl test to work on real provisioningprofile (binary data) + properly read files so comparison can work
- Fix encryption (on Windows)
- Skip sigh certificate verification on non-Mac

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: fastlane_core/lib/fastlane_core/helper.rb [hunk 1]
```diff
@@ -299,6 +299,22 @@ def self.zip_directory(path, output_path, contents_only: false, overwrite: false
       Helper.backticks(command, print: print)
     end
 
+    # Executes the provided block after adjusting the ENV to have the
+    # provided keys and values set as defined in hash. After the block
+    # completes, restores the ENV to its previous state.
+    def self.with_env_values(hash, &block)
```
Comment (snatchev) [inline fastlane_core/lib/fastlane_core/helper.rb]: Nice!

Comment (janpio) [reply fastlane_core/lib/fastlane_core/helper.rb]: Oh, I fully stole that from the screengrab `spec_helper`:
https://github.com/fastlane/fastlane/blob/89da896d167f8c7ec33c05601ffe37a182e788d1/screengrab/spec/spec_helper.rb#L1-L23 
So all credit to @mfurtak 🎁

File: match/lib/match/runner.rb [hunk 2]
```diff
@@ -236,10 +250,16 @@ def fetch_provisioning_profile(params: nil, certificate_id: nil, app_identifier:
...
 
-      installed_profile = FastlaneCore::ProvisioningProfile.install(profile, keychain_path)
+      if Helper.mac?
+        installed_profile = FastlaneCore::ProvisioningProfile.install(profile, keychain_path)
+      end
       parsed = FastlaneCore::ProvisioningProfile.parse(profile, keychain_path)
       uuid = parsed["UUID"]
 
+      if params[:export_path]
+        FileUtils.cp(profile, params[:export_path])
```
Comment (joshdholtz) [inline match/lib/match/runner.rb]: Do we want to do a `FileUtils.mkdir_p(params[:export_path])` here? There is a good chance a user might put a directory that doesn't exist 🙃 Either this or we need to verify on the `ConfigItem` that the path exists.

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This looks super good 🙌 Left some comments on some minor things but everything seems to check out ✅ 

I think we need a rebase in here too 🙃

File: match/lib/match/runner.rb (hunk 2 above)
Comment (janpio) [reply match/lib/match/runner.rb]: Do we have any similar options for other actions where we could "steal" the behavior for consistency? I actually forgot to finish the `ConfigItem` here to be honest, because I couldn't think of where to look for how this could/should work.

File: match/lib/match/runner.rb [hunk 3]
```diff
@@ -202,7 +212,9 @@ def fetch_provisioning_profile(params: nil, certificate_id: nil, app_identifier:
       profile_name = names.join("_").gsub("*", '\*') # this is important, as it shouldn't be a wildcard
       base_dir = File.join(prefixed_working_directory(working_directory), "profiles", prov_type.to_s)
       profiles = Dir[File.join(base_dir, "#{profile_name}.mobileprovision")]
-      keychain_path = FastlaneCore::Helper.keychain_path(params[:keychain_name]) unless params[:keychain_name].nil?
+      if Helper.mac?
+        keychain_path = FastlaneCore::Helper.keychain_path(params[:keychain_name]) unless params[:keychain_name].nil?
```
[the remark this answers is not in the document]
Comment (janpio) [reply match/lib/match/runner.rb]: `keychain_path` does not exist on non-Mac, so it being nil is correct.
`device_count_different?` has `keychain_path` as default `nil` anyway, so this should be fine, correct?

File: match/lib/match/runner.rb [hunk 4]
```diff
@@ -220,11 +232,13 @@ def fetch_provisioning_profile(params: nil, certificate_id: nil, app_identifier:
 
       if profile.nil? || params[:force]
         if params[:readonly]
-          all_profiles = Dir.entries(base_dir).reject { |f| f.start_with?(".") }
           UI.error("No matching provisioning profiles found for '#{profile_name}'")
           UI.error("A new one cannot be created because you enabled `readonly`")
-          UI.error("Provisioning profiles in your repo for type `#{prov_type}`:")
-          all_profiles.each { |p| UI.error("- '#{p}'") }
+          if Dir.exist?(base_dir)
```
[the remark this answers is not in the document]
Comment (janpio) [reply match/lib/match/runner.rb]: > What is the reasonging why `base_dir`wouldn't exist here?

When you run `match` the first time for a specific `prov_type` (appstore, development, adhoc, enterprise) the folder referenced in `base_dir` does not exist yet, so we can't list its entries.

> Is this the fix for #13965? If so, can we get a comment here saying that 😇

Indeed, I mentioned the issue in the commit so it gets closed when this is merged.

Should I mention the issue in the comment or the reason behind `base_dir` being possible empty?

```suggestion
           if Dir.exist?(base_dir) # folder for `prov_type` does not exist on first match use for that type
```

File: match/lib/match/runner.rb (hunk 2 above)
Comment (janpio) [reply match/lib/match/runner.rb]: `cert`, `pem` and `sigh` all have an `output_path` option, so I renamed this one here as well. I also copied how those other actions create the directory at the beginning of `run` (only this time only if the param is supplied, as for the others it has a default value).

File: match/lib/match/runner.rb (hunk 3 above)
[the remark this answers is not in the document]
Comment (janpio) [reply match/lib/match/runner.rb]: ping

**Review by joshdholtz — APPROVED** [review]
@janpio This looks good and works good! Sorry about taking so long to get this through 😔
