### PR TITLE
Fix nil path crash in changelog_from_git_commits action

### LINKED ISSUE #12497: Upgrading to 2.95 breaks changelog_from_git_commits
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.95.0`
- Last working version: `2.94.0`

### Regression Description

Simply put, fails with:

    TypeError: [!] no implicit conversion of nil into String

Looks related to #10358 but it's not happening in `match`, I'm invoking `changelog_from_git_commits`.

##### Complete output when running fastlane, including the stack trace and command used

I can't share the full output for privacy, but if this is not enough I can share more snippets on request.

<details>
  <pre>
TypeError: [!] no implicit conversion of nil into String
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:32:in `chdir'
  /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.95.0/fastlane/lib/fastlane/actions/changelog_from_git_commits.rb:32:in `run'
</pre>
</details>

### Environment

<details>
  <pre>
### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.4 (17E202)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

</pre>
</details>

### PR DESCRIPTION
**Pull request by RishabhTayal**
fixes: https://github.com/fastlane/fastlane/issues/12497.

**Note:**
I don't think the solution implemented in this PR is right. However it solves the crash issue. 

The `path` param should not be `nil` in the first place because we are setting the `default_value` for the param. Need to figure out why it is setting `nil` value for `path`.

### CODE REVIEW

**Comment by RishabhTayal** [comment]
Closing this PR since it's not a valid bug.

File: fastlane/lib/fastlane/actions/changelog_from_git_commits.rb [hunk 1]
```diff
@@ -28,6 +28,10 @@ def self.run(params)
         if params[:include_merges] == false
           merge_commit_filtering = :exclude_merges
         end
+        
+        if params[:path] == nil
+          params[:path] = './'
+        end
```
Comment (revolter) [inline fastlane/lib/fastlane/actions/changelog_from_git_commits.rb]: Would `params[:path] = '.' unless params[:path]` work too?

**Comment by RishabhTayal** [comment]
@revolter It's ready to review now.

**Review by revolter — APPROVED** [review]
Good to go 🚀
