### PR TITLE
[action] slather: Change binaryFile data type from Bool to optional String

### LINKED ISSUE #14674: [action] slather: [Bug][Swift][Fastfile.swift] binaryFile parameter type is Bool - unable to pass file path
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The Ruby edition of Fastlane allows the Slather action to take a string for the binary_file property.  By doing so, this points Slather in the right direction for code coverage.

The Swift edition of Fastlane has Slather's binaryFile as a data type of Bool.  When set to true, "--binary-file" added to the command line but there's no way to specify the binary file to point to.  Slather fails due to the missing --binary-file command line value.  In the example provided, the error indicates the xcode project was not supplied on the command line due to --binary-file being added and the xcode project being the next value directly after it.  Slather consumes the value as the --binary-file value.  

Expected:  Fastlane.swift accepts a binaryFile as a String? data type.  Once the data changes, the Fastfile can specify the binaryFile path and it gets passed to the command line properly.

Per the Slather code, https://github.com/SlatherOrg/slather/blob/master/lib/slather/command/coverage_command.rb, --binary-file is expecting a string value, not a Boolean.

Example:
When `binaryFile = true`:
`slather coverage [...] --binary-file ChumBox.xcodeproj`

When `binaryFile = "path/to/binary"`:
`slather coverage [...] --binary-file "path/to/binary" ChumBox.xcodeproj`

Proposed fix:  Update `binaryFile: Bool = false` to `binaryFile: String?` in Fastlane.swift.  

##### Command executed

bundle exec fastlane codeCoverage

The codeCoverage lane sets up properties and then runs slather(...)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundle exec fastlane codeCoverage
[✔] 🚀
[17:36:30]: loading manifest: /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/swift/upgrade_manifest.json
[17:36:31]: FastlaneSwiftRunner project is up-to-date
[17:36:31]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[17:36:32]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' | tee /Users/bauer015/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[17:36:36]: $ ./fastlane/FastlaneRunner lane codeCoverage swiftServerPort 2000 > /dev/null
[17:36:36]: JOB_NAME = Optional("")
[17:36:36]: -----------------
[17:36:36]: --- Step: pwd ---
[17:36:36]: -----------------
[17:36:36]: $ pwd
[17:36:36]: ▸ /Users/bauer015/code/ios/news-ios-framework-chumbox
[17:36:36]: /Users/bauer015/code/ios/news-ios-framework-chumbox
[17:36:36]: ---------------------
[17:36:36]: --- Step: slather ---
[17:36:36]: ---------------------
[17:36:36]: $ slather coverage --cobertura-xml --build-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/buildOutput --output-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/output --verbose --input-format profdata --scheme ChumBox --workspace ChumBox --binary-file ChumBox.xcodeproj
[17:36:37]: ▸ /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:106:in `project': Must provide an xcodeproj either via the 'slather [SUBCOMMAND] [PROJECT].xcodeproj' command or through .slather.yml (StandardError)
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:65:in `setup_build_directory'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:42:in `execute'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
[17:36:37]: ▸ from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/bin/slather:17:in `<top (required)>'
[17:36:37]: ▸ from /usr/local/bin/slather:22:in `load'
[17:36:37]: ▸ from /usr/local/bin/slather:22:in `<main>'
[17:36:37]: ▸ Slathering...
+-----------+--------------+
|       Lane Context       |
+-----------+--------------+
| LANE_NAME | codeCoverage |
+-----------+--------------+
[17:36:37]: Exit status of command 'slather coverage --cobertura-xml --build-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/buildOutput --output-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/output --verbose --input-format profdata --scheme ChumBox --workspace ChumBox --binary-file ChumBox.xcodeproj' was 1 instead of 0.
/Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:106:in `project': Must provide an xcodeproj either via the 'slather [SUBCOMMAND] [PROJECT].xcodeproj' command or through .slather.yml (StandardError)
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:65:in `setup_build_directory'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:42:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/bin/slather:17:in `<top (required)>'
    from /usr/local/bin/slather:22:in `load'
    from /usr/local/bin/slather:22:in `<main>'
Slathering...
+------+---------+-------------+
|       fastlane summary       |
+------+---------+-------------+
| Step | Action  | Time (in s) |
+------+---------+-------------+
| 1    | pwd     | 0           |
| 💥   | slather | 0           |
+------+---------+-------------+
[17:36:37]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneShellError: [!] Exit status of command 'slather coverage --cobertura-xml --build-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/buildOutput --output-directory /Users/bauer015/code/ios/news-ios-framework-chumbox/output --verbose --input-format profdata --scheme ChumBox --workspace ChumBox --binary-file ChumBox.xcodeproj' was 1 instead of 0.
/Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:106:in `project': Must provide an xcodeproj either via the 'slather [SUBCOMMAND] [PROJECT].xcodeproj' command or through .slather.yml (StandardError)
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:65:in `setup_build_directory'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/lib/slather/command/coverage_command.rb:42:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/subcommand/execution.rb:18:in `execute'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:66:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/clamp-1.3.0/lib/clamp/command.rb:140:in `run'
    from /Library/Ruby/Gems/2.3.0/gems/slather-2.4.7/bin/slather:17:in `<top (required)>'
    from /usr/local/bin/slather:22:in `load'
    from /usr/local/bin/slather:22:in `<main>'
Slathering...
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
  /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/forwardable.rb:202:in `sh'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/slather.rb:52:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:181:in `execute_action_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:176:in `process_action_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:123:in `handle_action_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:86:in `parse_and_execute_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/swift_lane_manager.rb:231:in `block in start_socket_thread'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>
### Stack
| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D42)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |
### System Locale
| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |
### fastlane files:
**No Fastfile found**
**No Appfile found**
### fastlane gems
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.121.1 | ✅ Up-To-Date  |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 2.0.1        |
| io-console                | 0.4.5        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.1.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.11.1     |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| clamp                     | 1.3.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.7.2        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.64.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.4       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.11.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2019.0331  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| json                      | 2.2.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.5.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.1        |
| tty-spinner               | 0.9.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.3       |
| slather                   | 2.4.7        |
</details>
*generated on:* **2019-04-24**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by rsbauer**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Slather --binary-file takes a string parameter defining the binary file path to analyze per Slather's documentation here: https://github.com/SlatherOrg/slather/blob/master/lib/slather/command/coverage_command.rb

Fastlane.swift expects binaryFile to be a boolean, with the default value set to false.  Setting to true adds the Slather command line --binary-file but does not include a binary file as a parameter.  Instead, Slather will consume the next space delimited value as the --binary-file value.

slather.rb updated so Fastlane.swift is generated with the changed data type.

### Description

Changes Slather `binary-file` data type from a Boolean to an optional string allowing the user to provide a binary file path and resolves the Slather command issue.

Fixes #14674

### CODE REVIEW

File: fastlane/swift/Fastlane.swift [hunk 1]
```diff
@@ -3250,7 +3250,7 @@ func slather(buildDirectory: String? = nil,
              verbose: Bool? = nil,
              useBundleExec: Bool = false,
              binaryBasename: Bool = false,
-             binaryFile: Bool = false,
+             binaryFile: String?,
```
Comment (janpio) [inline fastlane/swift/Fastlane.swift]: This unfortunately will be overwritten as the whole file is generated from slather.rb.

My guess: is_string: true, in line 259 of slather.rb would result in what you want to have here. (But really just a guess, I don't even know how this is generated)

Comment (rsbauer) [reply fastlane/swift/Fastlane.swift]: The file is checked in though so I figure at least the checked in version should match the generated one.  Is this ok or would it be preferred this file stay untouched?

Comment (janpio) [reply fastlane/swift/Fastlane.swift]: Looking at the file history there, it is generated during the release process. So you could change it here in the PR, but it would be overwritten on release anyway.

Comment (rsbauer) [reply fastlane/swift/Fastlane.swift]: Got it!  I'll put Fastlane.swift back to how it is.  Sorry, I must of missed the documentation on this.

Comment (janpio) [reply fastlane/swift/Fastlane.swift]: Very possible that doesn'T exist, as all the Swift stuff is in beta and only semi supported.

Comment (rsbauer) [reply fastlane/swift/Fastlane.swift]: Groovy!  Let me know if anything else is needed.

**Comment by janpio** [comment]
This changes the default state of `binary-file`, from `false` to empty (I guess?), correct? Will this break the action for people that are currently using it? Nobody should be using it with `true` right now, only not at all or with a path, correct?

**Comment by rsbauer** [comment]
In the Ruby Fastfile flavor, I think `binary-file` works due to a happy accident.  It defaults to false which suppresses "--binary-file" in the Slather command.  When a user provides a value for "binary_file", the string value does get passed along to the Slather command (I use this property in other Ruby based Fastfiles).  I suspect because the string value results in a Boolean true maybe, but I'm not too familiar with Ruby.  

In the Swift world, the compiler type checks the variable types before executing the code and picks up on this error.  The `false` suppresses the "--binary-file" which is great, but when set to `true`, it adds "--binary-file" to the command line but no value so the Slather code consumes the next value on the command line as the binary-file which usually results in an error.  

If people are leaving this as the default value, there should be no change or impact.

If people were already providing a string, which I've tested, it'll be fine.  The string gets applied properly to the command line.

If people are applying `false` from a Ruby Fastfile, this I'll need to test.  I suspect one of two things:
1.  Ruby will throw an error trying to pass a Boolean to a string value.  This would throw a Ruby error.
2.  Ruby doesn't throw an error and converts `false` to "false".  In this case, the Slather command will be grammatically correct, but won't likely won't find a valid binary named "false".  This would throw a Slather error saying it couldn't find a binary.

I'll investigate this weekend which of the two cases will happen under this change.  In the meantime, would this be a show stopper?  Is there an alternative that would be better?  (say naming a new property, although this could cause confusion)

**Comment by janpio** [comment]
If `false` really is a problem, we can probably catch it and replace it with the new default of an empty string / nothing / nil / whatever the new default in ruby land is. Then this should be backwards compatible, shouldn't it?

**Comment by rsbauer** [comment]
This sounds like it'll need a bit of digging and probably a unit test or a few.  Let me investigate tonight and this weekend.

**Comment by rsbauer** [comment]
@janpio: I've added another commit.  This doesn't feel right though (feels hacky) so these last 2 commits are for discussion.  Technically, the commits check for true/false on binary_file when the action == "slather" and removes the key from the arguments hash.  It works, but feels like there may be a better/preferred solution (or a better spot to put this check in, such as within slather.rb and have runner.rb call out to the action to verify/validate.  

Feedback would be most welcome!

**Comment by janpio** [comment]
Ayy, indeed very hacky. 

I think there is a way to "verify" the params of an action that is automatically executed, and that possibly can manipulate them (`verify_block` it is, looking for that in the codebase should give you an idea). 

If not, the special handling of `binary_file` should definitely be done in the action .rb file in another way.

**Comment by rsbauer** [comment]
From testing, `arguments = ConfigurationHelper.parse(class_ref, arguments.first)` is called before the `verify_block` on `binary_file` is called which throws an error and halts execution.  `verify_block` doesn't have a chance to work it's magic.  

It's looking like option 2 is needed.  I can take a crack at it but I'm neither a Ruby developer or Fastlane code base expert (I was hoping just to change a Boolean to a string).  Any thoughts or guidance would be great!

**Comment by janpio** [comment]
What error does it throw?

**Comment by rsbauer** [comment]
It's throwing the FalseClass (TrueClass) is not of type StringClass (or something like that - I don't have the error in front of me at the moment).

An alternative solution, again, not ideal:

I added `skip_type_validation: true` to the ConfigItem for `binary_file`.  This allows ConfigurationHelper do it's thing.  Then is slather.rb, under `def self.validate_params!(params)`, I was able to add a check if Boolean there and clean it up.  I don't think this is all that great since the code is disabling type checking for `binary_file`.  It is a tad bit better since all this can be contained within slather.rb, but still a bit hacky.  I can post a PR if you'd like to see this change.

**Comment by rsbauer** [comment]
Here's the exact error:
```
You passed invalid parameters to 'slather'.
Check out the error below and available options by running `fastlane action slather`
'binary_file' value must be a String! Found FalseClass instead.
```

**Comment by janpio** [comment]
> I added `skip_type_validation: true` to the ConfigItem for `binary_file`. This allows ConfigurationHelper do it's thing. Then is slather.rb, under `def self.validate_params!(params)`, I was able to add a check if Boolean there and clean it up. I don't think this is all that great since the code is disabling type checking for `binary_file`. It is a tad bit better since all this can be contained within slather.rb, but still a bit hacky. I can post a PR if you'd like to see this change.

That sounds pretty much what I would have expected - as we change the type of the param, the usual checking has to be disabled and we have to handle that ourselves. It's not pretty, but should probably be fine. 

Can we maybe just handle `false` by changing it and then trigger the validation manually?

**Comment by rsbauer** [comment]
Added a commit to revert runner.rb and added backwards compatibility for slather binary_file validation.

**Comment by janpio** [comment]
Nice! Looks good to me now, hope someone else from the committers actually knows a bit about slather and can properly review this.

**Comment by rsbauer** [comment]
@janpio Thank you for reviewing and your help!

File: fastlane/lib/fastlane/actions/slather.rb [hunk 2]
```diff
@@ -75,6 +75,17 @@ def self.validate_params!(params)
...
+        # for backwards compatibility when :binary_file type was Boolean
+        if params[:binary_file] == true || params[:binary_file] == false
+          params[:binary_file] = nil
+        end
+
+        # :binary_file validation was skipped for backwards compatibility with Boolean. If a
+        # Boolean was passed in, it has now been removed. Revalidate :binary_file
+        binary_file_options = available_options.find { |a| a.key == :binary_file }
+        binary_file_options.skip_type_validation = false
+        binary_file_options.verify!(params[:binary_file])
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/slather.rb]: Manually changing `skip_type_validation` and calling `verify!` here kind of spooks me a bit but I guess it makes sense in this case 🙃

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@rsbauer This looks good! One thing I think I'd like to see added would be a test case added to `slather_spec.rb` for the `true`/`false` case (the current test actually handles string). I don't have access to edit your fork otherwise I could add this test case for you (which you can give me if you'd like) 😇

File: fastlane/lib/fastlane/actions/slather.rb (hunk 2 above)
Comment (janpio) [reply fastlane/lib/fastlane/actions/slather.rb]: I had the same feeling, but after thinking a bit this seems the best way to actually be able to update the option to the new type, handle possible old usages, and still make sure the data is properly verified, true? Or did we overcomplicate things?

(A few more comments might be useful that link back to this PR, if future someone wonder wtf is going on here)

Comment (rsbauer) [reply fastlane/lib/fastlane/actions/slather.rb]: I'm not a fan of skipping the validation either.  But I don't see anywhere where slather.rb can do parameter house cleaning before the validation takes place without modifying runner.rb.  I'm not familiar enough with the Fastlane code base (or Ruby) to provide any recommendations.  But putting slather specific code in runner.rb felt wrong.

Comment (rsbauer) [reply fastlane/lib/fastlane/actions/slather.rb]: @joshdholtz : Just sent you an invite to my fork.  If it's something you're able to add quickly, awesome and much appreciated!  Otherwise, I can take a look at it later tonight.  I definitely agree there should be some tests around this.

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/slather.rb]: Ah, thanks! I think there is actually just a check box you could have selected on the right side of this pull request that allows all/any maintainers to edit too 🙃 https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Comment (rsbauer) [reply fastlane/lib/fastlane/actions/slather.rb]: I see it's checked now.  Not sure if you had worked your magic or if it was already checked.  Let me know if I need to click/check on anything else...

Comment (rsbauer) [reply fastlane/lib/fastlane/actions/slather.rb]: Unit test for true and false added.

**Review by joshdholtz — APPROVED** [review]
This looks good! Thanks for adding those tests 😊
