### PR TITLE
Timeout and retry `xcodebuild -showBuildSettings`

### LINKED ISSUE #4059: Scan hangs when getting build settings
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Scan hangs when getting the build settings:

```
xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
```

A couple things to note:
 - I thought that it was related to https://github.com/fastlane/fastlane/issues/1844 since it was the last command showing up in the logs, but after looking at the stacktrace when I force quite `fastlane`, it seems that it's actually hanging on `showBuildSettings`.
 - I can reproduce the freeze by running the `-showBuildSettings` command manually, though it only happens one time out of five, something like that.
 - It happens consistently when running in a CI environment (circleci 7.3)
 - It started happening after I removed all files in the App target from the AppTests target. Instead, I now have `@testable import App` everywhere. This change required to modify my Podfile to have different pods for the AppTests target (see below)
 - DerivedData is relative to my project directory.

##### Complete output when running fastlane, including the stack trace and command used

Please note that I modified fastlane_core's sources to show the build settings command, which is why it shows up in the logs. If I hadn't, only the `-list` command would appear.

```
ldiqual@ldiqual-mbp ~/S/App-ios-test1> bundle exec fastlane test --verbose
/Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
INFO [2016-04-04 15:18:48.74]: ---------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: opt_out_usage ---
INFO [2016-04-04 15:18:48.74]: ---------------------------
INFO [2016-04-04 15:18:48.74]: Disabled upload of used actions
INFO [2016-04-04 15:18:48.74]: -------------------------------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: Verifying required fastlane version ---
INFO [2016-04-04 15:18:48.74]: -------------------------------------------------
INFO [2016-04-04 15:18:48.74]: fastlane version valid
INFO [2016-04-04 15:18:48.74]: ------------------------------
INFO [2016-04-04 15:18:48.74]: --- Step: default_platform ---
INFO [2016-04-04 15:18:48.74]: ------------------------------
INFO [2016-04-04 15:18:48.91]: Driving the lane 'ios test' 🚀
INFO [2016-04-04 15:18:48.91]: ------------------
INFO [2016-04-04 15:18:48.91]: --- Step: scan ---
INFO [2016-04-04 15:18:48.91]: ------------------
WARN [2016-04-04 15:18:48.93]: xcrun xcodebuild -list -workspace './App.xcworkspace'
2016-04-04 15:18:50.261 xcodebuild[94625:3349109] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:18:50.265 xcodebuild[94625:3349109] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
INFO [2016-04-04 15:18:51.94]: $ xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
2016-04-04 15:18:52.174 xcodebuild[94629:3349189] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:18:52.176 xcodebuild[94629:3349189] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
^C/Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/helper.rb:51:in ``': Interrupt
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/helper.rb:51:in `backticks'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:203:in `build_settings'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:168:in `mac?'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/project.rb:180:in `ios?'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/detect_values.rb:23:in `set_additional_default_values'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan.rb:27:in `config='
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/scan-0.5.2/lib/scan/manager.rb:4:in `work'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/actions/scan.rb:10:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
    from Fastfile:16:in `block (2 levels) in parsing_binding'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
    from /Users/ldiqual/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
    from /Users/ldiqual/.rbenv/versions/2.3.0/bin/fastlane:23:in `load'
    from /Users/ldiqual/.rbenv/versions/2.3.0/bin/fastlane:23:in `<main>'
```

```
ldiqual@ldiqual-mbp ~/S/App-ios-test1> xcrun xcodebuild -showBuildSettings -workspace './App.xcworkspace' -scheme 'AppTests'
2016-04-04 15:31:51.235 xcodebuild[94673:3360581] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2016-04-04 15:31:51.238 xcodebuild[94673:3360581] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FixCode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Build settings for action build and target AppTests:
```

Note that the command above doesn't exit (1 time out of 5), I have to force kill it.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
opt_out_usage
fastlane_version "1.49.0"
default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan(scheme: "AppTests")
  end
end
```

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Common' do

    target 'App'

    target 'AppTests' do
        pod 'SomePod'
    end

    pod 'SomeOtherPod'
end
```

### Environment

fastlane 1.70.0
Bundler + rbenv
ruby 2.3.0
xcode 7.3
cocoapods 1.0.0.beta.6

### PR DESCRIPTION
**Pull request by fcy**
As it may hang forever.

Fixes #4059

### CODE REVIEW

**Comment by fcy** [comment]
@asfalcone FYI

File: fastlane_core/lib/fastlane_core/project.rb [hunk 1]
```diff
@@ -303,5 +303,67 @@ def parsed_info
     def automated_scheme_selection?
       !!ENV["AUTOMATED_SCHEME_SELECTION"]
     end
+
+    def backticks(command, print: true, timeout: false, retries: 0)
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: This seems like a duplicate of what we have in `fastlane_core`, right?

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Do you mean the `Helper.backticks`? If yes, this is a private version that adds timeout and retry mainly because in [this PR](https://github.com/fastlane/fastlane/pull/4492) it was suggested that having this locally to the one spot it is currently needed would be better.

I think the approach there is better because it adds this functionality to whomever needs it but I decided to open a simplified version to discuss it.

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: I have renamed this method to avoid the confusion.

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Oh actually I think you referring to `Project.run_command` which has timeout but can't retry. I'll refactor this.

**Comment by fcy** [comment]
From this [comment](https://github.com/fastlane/fastlane/pull/5188#discussion_r68113906):

> Oh actually I think you referring to Project.run_command which has timeout but can't retry. I'll refactor this.

My proposal there is to add the functionality to retry to `run_command`, so move the implementation of the private `retryable_exec` to `run_command` with a default timeout of zero and default retry of zero too. Another benefit is that it would stop using [the dangerous `Timeout`](http://jvns.ca/blog/2015/11/27/why-rubys-timeout-is-dangerous-and-thread-dot-raise-is-terrifying/).

I'll make these changes if you guys think this is the correct approach.

**Comment by KrauseFx** [comment]
I'm not a big fan of having this extra method just for this. It feels like we're not fixing the underlying error, but just try to work around it. I'd love to find a cleaner solution that works for everyone 👍

**Comment by fcy** [comment]
Just to be sure, is the problem the private method that is only used for the `-showBuildSettings`? Or the fact that `xcodebuild` works when we retry to same command?

I can fix the first one by adding support to retry to `run_command`, and two more environment variables to customize it: `FASTLANE_XCODE_BUILD_SETTINGS_TIMEOUT`, and `FASTLANE_XCODE_BUILD_SETTINGS_RETRIES`, just like the existing `FASTLANE_XCODE_LIST_TIMEOUT`.

The second problem is about deciding when Fastlane tries to work around Xcode and when it gives up. In my opinion part of what makes Fastlane so amazing is how reliable and easy it makes using Xcode from the command line.

I'd love to contribute more, just let me know in clear words what is expected. I won't be offended or anything like it by any of the choices.

**Comment by neonichu** [comment]
@fcy it would be great if you could implement `retryable_exec` so that it wraps the current `Helper.backticks` functionality, instead of duplicating it.

**Comment by fcy** [comment]
@neonichu @KrauseFx please take another look. I update `run_command` to also use the existing `Helper.backticks` and added the ability to retry. Along with two new environment variables to control timeout and number of retries for the `xcodebuild -showBuildSettings`.

**Comment by neonichu** [comment]
LGTM, could you update the environment vars to something like `FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT`, just making `XCODEBUILD` one word.

**Comment by fcy** [comment]
I definitely can.

But for some reason that I still don't understand this new version this work as well as the old one. I'm using it in my CI and the build started hanging on `xcodebuild -list` which wasn't even a problem before. What is even more strange is that `xcodebuild -list` already was in the `Timeout.timeout` function but it is not timing out anymore. The only difference inside the `Timeout.timeout` block is that it uses `Helper.backticks` instead of `` `command` ``.

I'm going to make the changes to the env vars, rebase, and try reverting the `timeout` back to just to see if it is related.

**Comment by fcy** [comment]
Changes are done and it is battled tested in our CI, it works as flawlessly as PR #4492.

`Timeout.timeout` does not work when using `Helper.backticks` it just doesn't timeout and let the build hanging. Reverting back to `` `#{command}` `` fixed the issue and it now times-out and retries as expected.

Let me know if you prefer that I squashed the 3 commits before merging.

**Comment by fcy** [comment]
Anything else I could do here? This has been running on our CI for the past week without any problems, it solved the issue.

**Comment by larslockefeer** [comment]
We were seeing the same issue, [applying the patch of this PR on top of the currently released fastlane version](https://github.com/larslockefeer/fastlane/tree/travis-fix) solved the issue for us as well.

**Comment by andyshephard** [comment]
Will this be merged anytime soon? Experiencing issue w/ Bitrise CI that this PR would fix (potentially)

**Comment by fcy** [comment]
I have merged master into here to update it. In case other are using this branch I'm not rewriting the commit history with rebases.

**Comment by revile** [comment]
Any progress on getting this merged? Running tests via fastlane is _very_ unreliable at the moment.

**Comment by KrauseFx** [comment]
Hey everyone, really sorry for the delay on this. As you know, we can't reliably reproduce this issue unfortunately, however I'll take a look at the code, and make sure everything makes sense, has enough documentation, and doesn't break anything 👍

File: fastlane_core/lib/fastlane_core/project.rb [hunk 2]
```diff
@@ -301,13 +312,33 @@ def self.xcode_list_timeout
...
+      (ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] || 3).to_i
+    end
+
+    # @internal to module
+    # runs the specified command and kills it if timeouts, optionally retries before killing
+    # @raises Timeout::Error if timeout is passed after all retry attempts
     # @returns the output
-    # Note: currently affected by fastlane/fastlane_core#102
-    def self.run_command(command, timeout: 0)
+    # Note: - currently affected by fastlane/fastlane_core#102
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: This was probably migrated to fastlane/fastlane?

File: fastlane_core/lib/fastlane_core/project.rb [hunk 3]
```diff
@@ -301,13 +312,33 @@ def self.xcode_list_timeout
...
+    #       - retry feature added to solve fastlane#4059
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Can you include the full URLs here instead?

File: fastlane_core/lib/fastlane_core/project.rb [hunk 4]
```diff
@@ -301,13 +312,33 @@ def self.xcode_list_timeout
...
+    def self.run_command(command, timeout: 0, retries: 0)
       require 'timeout'
-      @raw = Timeout.timeout(timeout) { `#{command}`.to_s }
+
+      tries = 1
+      begin
+        return Timeout.timeout(timeout) { `#{command}`.to_s }
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Could we call `Helper.backticks` here instead? This way the command and its result will be printed out to the user

File: fastlane_core/lib/fastlane_core/project.rb [hunk 5]
```diff
@@ -301,13 +312,33 @@ def self.xcode_list_timeout
...
+      rescue Timeout::Error
+        raise if tries >= retries
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Let's add the following here
```ruby
UI.verbose("Command timed out, trying again...")
```

File: fastlane_core/lib/fastlane_core/project.rb (hunk 4 above)
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Let's also change this to be multi line, using `do .. end`

File: fastlane_core/lib/fastlane_core/project.rb [hunk 6]
```diff
@@ -216,7 +216,18 @@ def build_xcodebuild_showbuildsettings_command
     def build_settings(key: nil, optional: true)
       unless @build_settings
         command = build_xcodebuild_showbuildsettings_command
-        @build_settings = Helper.backticks(command, print: false)
+        UI.important(command) unless self.xcodebuild_list_silent
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: If we have https://github.com/fastlane/fastlane/pull/5188/files?diff=split#r76524918, we can remove this, right?

File: fastlane_core/lib/fastlane_core/project.rb (hunk 4 above)
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: And you can add `self.xcodebuild_list_silent` here too, by using `Helper.backticks(command, print: !self.xcodebuild_list_silent)`

**Comment by KrauseFx** [comment]
This looks great, thanks for your contribution @fcy. I added some comments that need to be addressed. The comments in the code should be a bit more clear on why this is necessary (maybe link to radar numbers if you have them). 

If you feel like you don't have the time to update the PR, just let me know and I can take over from here 👍 

Thanks again for working on this! :)

File: fastlane_core/lib/fastlane_core/project.rb (hunk 4 above)
Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: My original implementation used it, on unit tests it worked just fine but in real life using `Helper.backticks` made the `Timeout` useless. It just don't retry nor times out ever, it is like the `Timeout.timeout` call didn't even exist.

Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: But `Helper.backticks` is just using backticks: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/helper.rb#L15-L20

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Yes I noticed, I can't say I know enough Ruby to understand it. Feels totally "wat?". 

Everything I read said to just not use `Timeout` (links in older comments here) but that means not using backticks. Actually not using `Timeout` was my first implementation, which was based on #4492. I changed it just because the core team didn't seem to agree with that approach.

Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Alright, if you say it doesn't work with Helper.backticks, I'm ok with leaving it like this, however please do print out the command and the command output, similar to https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/helper.rb#L15-L20

How did you test to see that this really doesn't work?

**Comment by KrauseFx** [comment]
Let me know when you had the time to update the PR and I'll do another review

File: fastlane_core/lib/fastlane_core/project.rb (hunk 4 above)
Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: I will 👍 

---

I use Bundler to manage the tools we use (CocoaPods, Fastlane, and Danger), basically I just put the git branch I want to use for Fastlane. I was successfully using $4492 when I decided to create a simplified PR using the same implementation it did but totally compartmentalized to `project.rb` this is the progress of changes:

1. #4492, worked
2. #4492 applied to `project.rb`, worked
3. [early feedback](https://github.com/fastlane/fastlane/pull/5188#issuecomment-229654362) asked to use `Helper.backticks`, retries stopped working and the build hand just like Fastene in master
4. Went back to the original backticks in `project.rb` instead of `Helper.backticks`, and it worked again (literally nothing else changed)

All these I put to run on our CI which makes the problem happen more often (probably because of the many times the build runs).

**Comment by fcy** [comment]
@KrauseFx just pushed the [changes](https://github.com/fastlane/fastlane/pull/5188/commits/c5eb32618aed6bc8b276f891351c925d4b3f1e25). I'll update our `Gemfile` to run it on Monday.

File: fastlane_core/lib/fastlane_core/project.rb [hunk 7]
```diff
@@ -301,13 +310,42 @@ def self.xcode_list_timeout
...
+    def self.run_command(command, timeout: 0, retries: 0, print: true)
       require 'timeout'
-      @raw = Timeout.timeout(timeout) { `#{command}`.to_s }
+
+      UI.command(command) if print
+
+      tries = 1
+      begin
+        Timeout.timeout(timeout) do
+          result = `#{command}`.to_s # Using Helper.backticks doesn't work. Timeout don't times out and the command hangs forever
```
Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: @KrauseFx I don't know what this means 😳

**Comment by KrauseFx** [comment]
Hey @fcy, the tests are failing, seems like it's accessing a variable that doesn't exist

**Comment by fcy** [comment]
>however please do print out the command and the command output, similar to https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/helper.rb#L15-L20

There is a huge addition to the logs by printing the output too, IMO we should just print the command not the output. Check the gist to see the difference: https://gist.github.com/fcy/2cbc57e2876870cee97ac5bf0e5e9dfd

**Comment by fcy** [comment]
@KrauseFx fixed the undeclared variable and I went ahead and removed the command output. Let me know if you think we should still print it even though it is really verbose.

Everything is working fine on our CI.

One last request, if when you merge it could you please use Squash and Merge 😁. I'm itching with all the commits in this PR but I decided that not breaking people's `Gemfile.lock` was worth it.

**Comment by KrauseFx** [comment]
Thanks. No worries about squashing, we do that 👍

File: fastlane_core/lib/fastlane_core/project.rb (hunk 7 above)
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Oh, the variable is created in the scope of `timeout`, so it won't be available to `return`

Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: Instead you can just return from here directly, right/

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: 👍

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Do you prefer the return here? In the new code I created the variable in an outside scope. The only reason I didn't return here was because of the printing the output, I didn't want that to be part of the `retry`.

Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/project.rb]: I'm ok either way I think

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Also now that I'm thinking about it, does returning from within a closure returns from the method? 🤔 (In Swift it doesn't)

Comment (fcy) [inline fastlane_core/lib/fastlane_core/project.rb]: Ok cool. I'll leave the way it is now, makes more sense to me.

**Comment by mfurtak** [comment]
Cool, thanks very much for this contribution! 🚀  Let's merge this, and I'll follow up with a PR to adjust some small details 👍

**Comment by mfurtak** [comment]
Hi all, this has been released as part of [`fastlane_core` 0.51.0](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.51.0) 🚀 

Thanks very much for your help! Please let us know how it looks 👍

**Comment by mfurtak** [comment]
To test the latest release, please run `[sudo] gem update fastlane_core` or if you have a `Gemfile`, `bundle update`

**Comment by mfurtak** [comment]
Hi all, [`gym` 1.9.0](https://github.com/fastlane/fastlane/releases/tag/gym/1.9.0) 💪 and [`scan` 0.12.0](https://github.com/fastlane/fastlane/releases/tag/scan/0.12.0) 🔍 have been released to pick up these `fastlane_core` improvements.

To get updated and try them out, please run `[sudo] gem update gym scan` :rocket:
