### PR TITLE
[sign] fix sigh not using custom keychain path

### LINKED ISSUE #14453: Cert doesn't use custom keychain to find certificate
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Cert checker supports custom keychain via `in_keychain` parameter:
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/cert_checker.rb#L9

This is however not used from cert:

https://github.com/fastlane/fastlane/blob/master/cert/lib/cert/runner.rb#L15
https://github.com/fastlane/fastlane/blob/master/cert/lib/cert/runner.rb#L95

The result of this is that if you pass custom keychain to cert and already have certificate and key imported, cert is not able to find them and it either:
- fails because of certificate limit
- creates new certificate

### PR DESCRIPTION
**Pull request by jcavar**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This fixes https://github.com/fastlane/fastlane/issues/14453

### CODE REVIEW

File: cert/spec/runner_spec.rb [hunk 1]
```diff
@@ -95,7 +101,7 @@
       end
 
       let(:generate) do
-        options = { output_path: temp, filename: filename }
+        options = { output_path: temp, filename: filename, keychain_path: "." }
```
Comment (jcavar) [inline cert/spec/runner_spec.rb]: This is workaround for tests failing on Ubuntu machine. Default argument value for `keychain_path` (`~/Library/Keychains/login.keychain`) is not valid on Ubuntu.

I am not sure if and how cert works on Ubuntu and workarounds keychain? I think concept of macOS keychain is not available on Ubuntu (`security` command doesn't work)?

Comment (joshdholtz) [reply cert/spec/runner_spec.rb]: We probably don't want this as a work around just for Ubuntu tests because this means that if anybody tries to run `cert` in Ubuntu without passing a `keychain_path` of `"."`, it will probably fail in real life 😬

We might want to do a check for macOS somewhere instead? I think @janpio might have a better suggestion here since he has more of the non-macOS experience 😇

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Might want to find a proper solution to fixing the tests in Ubuntu 🤔

File: cert/spec/runner_spec.rb (hunk 1 above)
Comment (jcavar) [reply cert/spec/runner_spec.rb]: I am open for suggestions. However, `keychain_path` has default value and is not optional argument. So it seems to me that `cert` hasn't been working properly on Ubuntu anyway.

It is true that this change pushed `Cert.config[:keychain_path]` up in code path which triggered exception earlier. So it might break some of existing code.

Is there a way to do `Cert.config[:keychain_path]` so that it doesn't raise error if `keychain_path` is not valid? Or check if it is valid somehow?

Comment (janpio) [reply cert/spec/runner_spec.rb]: `cert` is probably broken on Ubuntu outside of the tests if there is no special handling for "keychain doesn't actually exist on non-macOS" yet. So I am good with working with `.` here, although a comment might not be a bad idea. One day we might want to get it to work there, and this might be a valuable pointer.

Comment (getaaron) [reply cert/spec/runner_spec.rb]: What about skipping the tests `unless FastlaneCore::Helper.mac?`?

Comment (janpio) [reply cert/spec/runner_spec.rb]: The tests are actually passing, so no need to skip. The test is not _really_ testing all the functionality. The real solution here is to go in deeper and make sure all the keychain stuff is limited to macOS - but that is quite a lot of work and outside the scope of this PR.

**Review by joshdholtz — APPROVED** [review]
Thanks for adding that comment! This is good for me then 😊
