### PR TITLE
[supply] Upload Rejects releases with empty version_codes

### LINKED ISSUE #17086: [supply] undefined method `map' for nil:NilClass on "draft" tracks
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

1. Create a **draft** version in alpha track
2. Run command
3. How to handle this error?

##### Command executed

    track = "alpha"
    version_code = google_play_track_version_codes(track: track).sort.last
    upload_to_play_store(
        track: track,
        metadata_path: "./metadata",
        skip_upload_apk: true,
        skip_upload_aab: true,
        version_code: version_code,
      )
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>2020-08-24T13:36:14.2459390Z bundler: failed to load command: fastlane (/Users/Agent/.gems/bin/fastlane)
2020-08-24T13:36:14.2462270Z NoMethodError: [31m[!] undefined method `map' for nil:NilClass[0m
2020-08-24T13:36:14.2463700Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `block in fetch_track_and_release!'
2020-08-24T13:36:14.2465220Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `select'
2020-08-24T13:36:14.2466520Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:114:in `fetch_track_and_release!'
2020-08-24T13:36:14.2467930Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:84:in `block in perform_upload_meta'
2020-08-24T13:36:14.2468920Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:81:in `each'
2020-08-24T13:36:14.2469750Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:81:in `perform_upload_meta'
2020-08-24T13:36:14.2470670Z   /Users/Agent/.gems/gems/fastlane-2.154.0/supply/lib/supply/uploader.rb:32:in `perform_upload'
2020-08-24T13:36:14.2471650Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:33:in `run'
2020-08-24T13:36:14.2472530Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
2020-08-24T13:36:14.2473480Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
2020-08-24T13:36:14.2474340Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
2020-08-24T13:36:14.2475760Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
2020-08-24T13:36:14.2476630Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
2020-08-24T13:36:14.2477460Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
2020-08-24T13:36:14.2478310Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
2020-08-24T13:36:14.2479080Z   Fastfile:36:in `block (2 levels) in parsing_binding'
2020-08-24T13:36:14.2479780Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane.rb:33:in `call'
2020-08-24T13:36:14.2480560Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
2020-08-24T13:36:14.2481410Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
2020-08-24T13:36:14.2482200Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
2020-08-24T13:36:14.2482990Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
2020-08-24T13:36:14.2483890Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
2020-08-24T13:36:14.2485120Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
2020-08-24T13:36:14.2486040Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-08-24T13:36:14.2487050Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-08-24T13:36:14.2488010Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-08-24T13:36:14.2488940Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-08-24T13:36:14.2489910Z   /Users/Agent/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-08-24T13:36:14.2490780Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
2020-08-24T13:36:14.2491610Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
2020-08-24T13:36:14.2492520Z   /Users/Agent/.gems/gems/fastlane-2.154.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
2020-08-24T13:36:14.2493310Z   /Users/Agent/.gems/gems/fastlane-2.154.0/bin/fastlane:23:in `<top (required)>'
2020-08-24T13:36:14.2493940Z   /Users/Agent/.gems/bin/fastlane:23:in `load'
2020-08-24T13:36:14.2494620Z   /Users/Agent/.gems/bin/fastlane:23:in `<top (required)>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.6                                     |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.26.2                          |
| Installation Source         | /usr/local/lib/ruby/gems/2.7.0/bin/fastlane |
| Host                        | Mac OS X 10.15.6 (19G2021)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.7.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.6                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Upload sort of (changelogs|metadata|screenshots|all) to the Google Play"
  lane :upload do |options|
    track = "alpha"
    version_code = google_play_track_version_codes(track: track).sort.last
    params = {
      track: track,
      metadata_path: "./metadata",
      skip_upload_apk: true,
      skip_upload_aab: true,
      version_code: version_code,
      validate_only: true,
    }
    case options[:method]
    when nil, "all"
      upload_to_play_store(params)
    when "changelogs", "metadata", "screenshots"
      upload_to_play_store(
        params.merge({
          skip_upload_changelogs: options[:method] != "changelogs",
          skip_upload_metadata: options[:method] != "metadata",
          skip_upload_images: options[:method] != "screenshots",
          skip_upload_screenshots: options[:method] != "screenshots",
        })
      )
    else
      raise "unknown method \"#{options[:method]}\""
    end
  end

  error do |lane, exception|
    if ENV["SLACK_URL"]
      slack(
        message: exception.to_s,
        success: false
      )
    end
  end

end

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.156.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| rake                      | 13.0.1       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.356.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| coderay                   | 1.1.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.6.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.0.0        |
| excon                     | 0.76.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.27.0       |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| plist                     | 3.5.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| method_source             | 1.0.0        |
| pry                       | 0.13.1       |
</details>

*generated on:* **2020-08-25**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by tauanlemos**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

I was getting an error of undefined method `map` for nil on the method `fetch_track_and_release` on the uploader. There was [This issue](https://github.com/fastlane/fastlane/issues/17086) with the same problem but it was closed. 

Resolves #17086 

### Description

Adds a small defensive programming, filtering out releases with nil or empty version_codes

### CODE REVIEW

**Comment by tauanlemos** [comment]
@googlebot I signed it!

**Review by hcadioli — APPROVED** [review]

File: supply/lib/supply/uploader.rb [hunk 1]
```diff
@@ -110,6 +110,7 @@ def fetch_track_and_release!(track, version_code, status = nil)
       track = tracks.first
       releases = track.releases
 
+      releases = releases.reject { |r| r.version_codes.nil? || r.version_codes.empty? } if version_code
       releases = releases.select { |r| r.status == status } if status
       releases = releases.select { |r| r.version_codes.map(&:to_s).include?(version_code.to_s) } if version_code
```
Comment (rogerluan) [inline supply/lib/supply/uploader.rb:115]: How about this, instead? It'd more optimized I think:
```suggestion
      releases = releases.select { |r| r.version_codes&.map(&:to_s).include?(version_code.to_s) } if version_code
```

File: supply/lib/supply/uploader.rb [hunk 2]
```diff
@@ -110,6 +110,7 @@ def fetch_track_and_release!(track, version_code, status = nil)
       track = tracks.first
       releases = track.releases
 
+      releases = releases.reject { |r| r.version_codes.nil? || r.version_codes.empty? } if version_code
```
Comment (rogerluan) [inline supply/lib/supply/uploader.rb:113]: And then this can be gone:
```suggestion
```

**Review by rogerluan — COMMENTED** [review]
First of all, welcome to _fastlane_, @tauanlemos ! 

You're right, a little bit of defensive programming wouldn't hurt here :) specially because this was proven to be a pain point for you and other users.

I left a suggestion though, I think it's cleaner and avoids looping through the array of releases one more time unnecessarily 🙏 But I'm a beginner in ruby, not even sure if this will work 🙈 

Let me know your thoughts! And thanks for your contribution! 🚀

File: supply/lib/supply/uploader.rb (hunk 1 above)
Comment (tauanlemos) [reply supply/lib/supply/uploader.rb:115]: I tried this and it throws another error due to the `include?` method. `releases = releases.select { |r| r.version_codes&.map(&:to_s)&.include?(version_code.to_s) } if version_code` fixes the problem

Comment (tauanlemos) [reply supply/lib/supply/uploader.rb:115]: But these changes are not compatible with target ruby version. Rubocop complains:

`supply/lib/supply/uploader.rb:115:55: E: unexpected token error
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
      releases = releases.select { |r| r.version_codes&.map(&:to_s)&.include?(version_code.to_s) } if version_code

supply/lib/supply/uploader.rb:115:68: E: unexpected token error
(Using Ruby 2.0 parser; configure using TargetRubyVersion parameter, under AllCops)
      releases = releases.select { |r| r.version_codes&.map(&:to_s)&.include?(version_code.to_s) } if version_code`

Comment (joshdholtz) [reply supply/lib/supply/uploader.rb:115]: One of these days we'll be able to use all of the fun stuff 😊

Comment (joshdholtz) [inline supply/lib/supply/uploader.rb:115]:
```suggestion
      releases = releases.select { |r| (r.version_codes || []).map(&:to_s).include?(version_code.to_s) } if version_code
```

Could we also do this instead of introducing that new line of code? 🤔

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One small thought!

**Review by rogerluan — APPROVED** [review]
🚀

**Review by joshdholtz — APPROVED** [review]
Perfect! Thanks for catching this and making the update ❤️  Really appreciate the contribution!
