### PR TITLE
Fix version selection with import_from_git

### LINKED ISSUE #11252: import_from_git is not importing the correct version
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I've created a private repository called `fastlane-lanes`, which contains a bunch of lanes that I intent to use across multiple projects. However, when i try to specify which version to use using (e.g. `~> 1.0.0`), it seems that versions are sorted alphabetically, rather than by number, i.e. versions are sorted like this:

* `1.0.0`
* `1.0.1`
* `1.0.10` ⬅️  ⚠️
* `1.0.11` ⬅️  ⚠️
* `1.0.2`
* `1.0.3`
* `1.0.4`
* `1.0.5`
* `1.0.6`
* `1.0.7`
* `1.0.8`
* `1.0.9`

This causes the "newest" release to be `1.0.9` rather than `1.0.11`. I do not know if this is the case for minor and major, since I did not test this. But i suspect that it works the same. I'm importing the lanes like this:

```
import_from_git(
    url: "git@github.com:my-org/fastlane-lanes.git",
    version: "~> 1.0.0"
)
```

### Captured Output

Command Used: `install`
<details><summary>Output/Log</summary>

```

DEBUG [2017-12-18 16:10:07.72]: Checking if there are any plugins that should be loaded...
DEBUG [2017-12-18 16:10:07.72]: Loading 'fastlane-plugin-upgrade_super_old_xcode_project' plugin
INFO [2017-12-18 16:10:07.77]: gem 'fastlane-plugin-upgrade_super_old_xcode_project' is already installed
DEBUG [2017-12-18 16:10:07.78]: Loading 'fastlane-plugin-ftp' plugin
INFO [2017-12-18 16:10:07.83]: gem 'fastlane-plugin-ftp' is already installed
+-------------------------------------------------+---------+---------------------------------+
|                                        Used plugins                                         |
+-------------------------------------------------+---------+---------------------------------+
| Plugin                                          | Version | Action                          |
+-------------------------------------------------+---------+---------------------------------+
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | upgrade_super_old_xcode_project |
| fastlane-plugin-ftp                             | 0.1.3   | ftp                             |
+-------------------------------------------------+---------+---------------------------------+

Successfully loaded Appfile at path '/Users/niklas/Documents/git/my-project/fastlane/Appfile'
- app_identifier: 'com.example.myapp'
- apple_id: 'me@my-org.com'
- team_id: 'my-teamid'
-------
INFO [2017-12-18 16:10:08.02]: -------------------------------------------------
INFO [2017-12-18 16:10:08.02]: --- Step: Verifying required fastlane version ---
INFO [2017-12-18 16:10:08.02]: -------------------------------------------------
INFO [2017-12-18 16:10:08.02]: Your fastlane version 2.70.0 matches the minimum requirement of 2.64.0  ✅
INFO [2017-12-18 16:10:08.05]: ------------------------------
INFO [2017-12-18 16:10:08.05]: --- Step: default_platform ---
INFO [2017-12-18 16:10:08.05]: ------------------------------
INFO [2017-12-18 16:10:08.05]: -----------------------------
INFO [2017-12-18 16:10:08.05]: --- Step: import_from_git ---
INFO [2017-12-18 16:10:08.05]: -----------------------------
INFO [2017-12-18 16:10:08.08]: Cloning remote git repo...
INFO [2017-12-18 16:10:08.08]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:my-org/fastlane-lanes.git' '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' --depth 1 -n 
INFO [2017-12-18 16:10:08.09]: ▸ Cloning into '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git'...
INFO [2017-12-18 16:10:13.07]: Fetching remote git tags...
INFO [2017-12-18 16:10:13.07]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && GIT_TERMINAL_PROMPT=0 git fetch --all --tags -q
INFO [2017-12-18 16:10:14.98]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git tag -l
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.0
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.10
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.11
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.2
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.3
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.6
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.7
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.8
INFO [2017-12-18 16:10:14.99]: ▸ 1.0.9
INFO [2017-12-18 16:10:14.99]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git checkout 1.0.9 'fastlane/Fastfile'
INFO [2017-12-18 16:10:15.01]: $ cd '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git' && git checkout 1.0.9 'fastlane/actions'
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/build_ember.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/build_ios.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/correct_ember_project.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/correct_xcode_project.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/generate_changelog.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/livereload_client.rb'.
INFO [2017-12-18 16:10:16.46]: Successfully loaded custom action '/var/folders/jd/nl_3vr_n3_n0w7njmkkgvkbh0000gn/T/fl_clone20171218-43694-13e4gtd/fastlane-lanes.git/fastlane/actions/livereload_server.rb'.
INFO [2017-12-18 16:10:16.51]: -------------------------------------------------
INFO [2017-12-18 16:10:16.51]: --- Step: Verifying required fastlane version ---
INFO [2017-12-18 16:10:16.51]: -------------------------------------------------
INFO [2017-12-18 16:10:16.51]: Your fastlane version 2.70.0 matches the minimum requirement of 2.64.0  ✅
INFO [2017-12-18 16:10:16.54]: ------------------------------
INFO [2017-12-18 16:10:16.54]: --- Step: default_platform ---
INFO [2017-12-18 16:10:16.54]: ------------------------------
INFO [2017-12-18 16:10:16.71]: Driving the lane 'ios install' 🚀
INFO [2017-12-18 16:10:16.74]: -------------------------------
INFO [2017-12-18 16:10:16.74]: --- Step: install_on_device ---
INFO [2017-12-18 16:10:16.74]: -------------------------------
INFO [2017-12-18 16:10:16.74]: $ ios-deploy --bundle /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa
INFO [2017-12-18 16:10:16.76]: ▸ [....] Waiting for iOS device to be connected
INFO [2017-12-18 16:10:16.77]: ▸ [....] Using 3218dc86753d7d632d4bf5fa8e150e7373a1f75c (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'My iPhone'.
INFO [2017-12-18 16:10:16.77]: ▸ ------ Install phase ------
INFO [2017-12-18 16:10:16.77]: ▸ [  0%] Found 3218dc86753d7d632d4bf5fa8e150e7373a1f75c (N71mAP, iPhone 6s, iphoneos, arm64) a.k.a. 'My iPhone' connected through USB, beginning install
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying META-INF/ to device
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying META-INF/com.apple.ZipMetadata.plist to device
INFO [2017-12-18 16:10:17.02]: ▸ [  5%] Copying Payload/ to device
··· (I've excluded the rest of the build due to privacy issues) ···
INFO [2017-12-18 16:10:17.80]: ▸ [ 52%] CreatingStagingDirectory
INFO [2017-12-18 16:10:17.80]: ▸ [ 57%] ExtractingPackage
INFO [2017-12-18 16:10:17.80]: ▸ [ 60%] InspectingPackage
INFO [2017-12-18 16:10:17.82]: ▸ [ 60%] TakingInstallLock
INFO [2017-12-18 16:10:17.84]: ▸ [ 65%] PreflightingApplication
INFO [2017-12-18 16:10:17.85]: ▸ [ 65%] InstallingEmbeddedProfile
INFO [2017-12-18 16:10:17.86]: ▸ [ 70%] VerifyingApplication
INFO [2017-12-18 16:10:19.52]: ▸ [ 75%] CreatingContainer
INFO [2017-12-18 16:10:19.53]: ▸ [ 80%] InstallingApplication
INFO [2017-12-18 16:10:19.56]: ▸ [ 85%] PostflightingApplication
INFO [2017-12-18 16:10:19.56]: ▸ [ 90%] SandboxingApplication
INFO [2017-12-18 16:10:19.61]: ▸ [ 95%] GeneratingApplicationMap
INFO [2017-12-18 16:10:19.74]: ▸ [100%] Installed package /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa
INFO [2017-12-18 16:10:19.74]: Deployed /Users/niklas/Documents/git/my-project/fastlane/../.tmp/app.ipa to device!
INFO [2017-12-18 16:10:19.74]: Successfully generated documentation at path '/Users/niklas/Documents/git/my-project/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | Verifying required fastlane version | 0           |
| 4    | default_platform                    | 0           |
| 5    | import_from_git                     | 8           |
| 6    | install_on_device                   | 3           |
+------+-------------------------------------+-------------+

DEBUG [2017-12-18 16:10:19.75]: All plugins are up to date
INFO [2017-12-18 16:10:19.75]: fastlane.tools finished successfully 🎉
DEBUG [2017-12-18 16:10:19.75]: All plugins are up to date


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G1036)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0g  2 Nov 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.64.0"

default_platform :ios

import_from_git(
    url: "git@github.com:my-org/fastlane-lanes.git",
    version: "~> 1.0.0"
)

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.myapp" # The bundle identifier of your app
apple_id "me@my-org.com" # Your Apple email address

team_id "my-teamid" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                          | Version | Update-Status |
| ----------------------------------------------- | ------- | ------------- |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2   | ✅ Up-To-Date  |
| fastlane-plugin-ftp                             | 0.1.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                             | Version      |
| ----------------------------------------------- | ------------ |
| did_you_mean                                    | 1.1.0        |
| executable-hooks                                | 1.3.2        |
| bundler-unload                                  | 1.0.2        |
| rubygems-bundler                                | 1.4.4        |
| bundler                                         | 1.16.0       |
| io-console                                      | 0.4.6        |
| CFPropertyList                                  | 2.3.6        |
| public_suffix                                   | 2.0.5        |
| addressable                                     | 2.5.2        |
| babosa                                          | 1.0.2        |
| claide                                          | 1.0.2        |
| colored                                         | 1.2          |
| colored2                                        | 3.1.2        |
| highline                                        | 1.7.10       |
| commander-fastlane                              | 4.4.5        |
| commonjs                                        | 0.2.7        |
| declarative                                     | 0.0.10       |
| declarative-option                              | 0.1.0        |
| unf_ext                                         | 0.0.7.4      |
| unf                                             | 0.1.4        |
| domain_name                                     | 0.5.20170404 |
| dotenv                                          | 2.2.1        |
| excon                                           | 0.60.0       |
| multipart-post                                  | 2.0.0        |
| faraday                                         | 0.13.1       |
| http-cookie                                     | 1.0.3        |
| faraday-cookie_jar                              | 0.0.6        |
| faraday_middleware                              | 0.12.2       |
| fastimage                                       | 2.1.0        |
| gh_inspector                                    | 1.0.3        |
| jwt                                             | 2.1.0        |
| little-plugger                                  | 1.1.4        |
| multi_json                                      | 1.12.2       |
| logging                                         | 2.2.2        |
| memoist                                         | 0.16.0       |
| os                                              | 0.9.6        |
| signet                                          | 0.8.1        |
| googleauth                                      | 0.6.2        |
| httpclient                                      | 2.8.3        |
| mime-types-data                                 | 3.2016.0521  |
| mime-types                                      | 3.1          |
| uber                                            | 0.1.0        |
| representable                                   | 3.0.4        |
| retriable                                       | 3.1.1        |
| google-api-client                               | 0.13.6       |
| json                                            | 2.1.0        |
| mini_magick                                     | 4.5.1        |
| multi_xml                                       | 0.6.0        |
| plist                                           | 3.4.0        |
| rubyzip                                         | 1.2.1        |
| security                                        | 0.1.3        |
| slack-notifier                                  | 1.5.1        |
| terminal-notifier                               | 1.8.0        |
| unicode-display_width                           | 1.3.0        |
| terminal-table                                  | 1.8.0        |
| tty-screen                                      | 0.6.3        |
| word_wrap                                       | 1.0.0        |
| nanaimo                                         | 0.2.3        |
| xcodeproj                                       | 1.5.4        |
| rouge                                           | 2.0.7        |
| xcpretty                                        | 0.2.8        |
| xcpretty-travis-formatter                       | 1.0.0        |
| fastlane-plugin-ftp                             | 0.1.3        |
| fastlane-plugin-upgrade_super_old_xcode_project | 0.0.2        |
| libv8                                           | 3.16.14.19   |
| mini_portile2                                   | 2.3.0        |
| nokogiri                                        | 1.8.1        |
| ref                                             | 2.0.0        |
| therubyracer                                    | 0.12.3       |
</details>

*generated on:* **2017-12-18**
</details>

### PR DESCRIPTION
**Pull request by jdee**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

`checkout_param_twiddle_wakka`, we hardly knew ye.

Fix #11252.

Use RubyGems API for tag resolution in `import_from_git`. This also now allows things like:

```Ruby
import_from_git(url: repo_url, version: [">= 1.1.0", "< 1.7.0"])
```

Which can be a bit more specific than an optimistic match.

### Description

Use `Gem::Requirement` and `Gem::Version` to determine which tags match a version. The `version` param is passed directly to the [Gem::Version.new](http://docs.seattlerb.org/rubygems/Gem/Requirement.html) method. Pass a string or an array.

Removed all the "Version helpers" methods except `fetch_remote_tags`, which was simplified and corrected as well.

### CODE REVIEW

File: fastlane/lib/fastlane/fast_file.rb [hunk 1]
```diff
@@ -1,3 +1,26 @@
...
+end
+
+module Gem
+  class Version
+    def self.from_tag(tag)
+      new tag.version_number_from_tag
+    end
+
+    def self.tag_correct?(tag)
+      correct? tag.version_number_from_tag
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Small nit pick,  let's surround method parameters with `(`

File: fastlane/lib/fastlane/fast_file.rb [hunk 2]
```diff
@@ -1,3 +1,26 @@
...
+  # to generate a Gem::Version from a tag.
+  def version_number_from_tag
+    sub(/^v/, "")
+  end
+end
+
+module Gem
+  class Version
+    def self.from_tag(tag)
+      new tag.version_number_from_tag
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Same here, missing `(`

File: fastlane/lib/fastlane/fast_file.rb [hunk 3]
```diff
@@ -1,3 +1,26 @@
+require "rubygems"
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Is this gem installed on every system?

File: fastlane/lib/fastlane/fast_file.rb [hunk 4]
```diff
@@ -1,3 +1,26 @@
...
+
+class String
+  # Gem::Version.new barfs on things like "v0.1.0", which is the style
+  # generated by the rake release task. Just strip off any initial v
+  # to generate a Gem::Version from a tag.
+  def version_number_from_tag
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Let's prefix the method with `fastlane_` to avoid name conflicts with other libraries.

**Review by KrauseFx — APPROVED** [review]
This is so beautiful, thank you for looking into this @jdee, I added a few smaller comments, then it's ready to be merged from my side. 
🚀

**Comment by NiklasWebnuts** [comment]
Woa! That's some speedy reactions! Great work guys 🚀

File: fastlane/lib/fastlane/fast_file.rb (hunk 3 above)
Comment (jdee) [reply fastlane/lib/fastlane/fast_file.rb]: A few thoughts.

1. This is actually not a gem, but part of the Ruby library. And you always get RubyGems when you install Ruby. (You just don't get the Bundler until you install it _from_ RubyGems.) In an RVM-based install, it's located here, e.g.:

```bash
-rw-r--r--  1 jdee  staff  36192 Sep  9 22:23 /Users/jdee/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb
```

2. This `require` may not be necessary.

```bash
[jdee@Jimmy-Dees-MacBookPro settings-bundle (master)]$ irb
2.4.2 :001 > Gem::Version.new "0.1.0" # no require
 => #<Gem::Version "0.1.0"> 
```

3. It seems safest to require this, given general require-related concerns (cc: @milch). But it probably doesn't make much difference and could potentially be omitted.

**Comment by jdee** [comment]
One strange thing in testing. I was using this to test:

```Ruby
import_from_git(
  path: "fastlane/Fastfile.internal",
  url: "https://github.com/jdee/fastlane-plugin-maintenance",
  version: "~> 0.2.0"
)
```

If I run `fastlane lanes`, I can see the lanes from the imported file, but not the `desc` for each lane. However, if I copy the file into my local repo and just use `import` instead of `import_from_git`, I do see the `desc`s:

**import_from_git:**

```
----- fastlane release

----- fastlane install

----- fastlane tests

----- fastlane run_rubocop

----- fastlane rubocop_update
```

**import:**

```
----- fastlane release
Release plugin to RubyGems

----- fastlane install
Install plugin gem in $GEM_HOME

----- fastlane tests
Run rspec and rubocop

----- fastlane run_rubocop
Run rubocop

----- fastlane rubocop_update
Update rubocop
```

It's the same import in both cases though.

File: fastlane/lib/fastlane/fast_file.rb (hunk 3 above)
Comment (KrauseFx) [reply fastlane/lib/fastlane/fast_file.rb]: Sounds good to me 👍

File: fastlane/lib/fastlane/fast_file.rb [hunk 5]
```diff
@@ -1,3 +1,26 @@
...
+  # generated by the rake release task. Just strip off any initial v
+  # to generate a Gem::Version from a tag.
+  def fastlane_version_number_from_tag
+    sub(/^v/, "")
+  end
+end
+
+module Gem
+  class Version
+    def self.from_tag(tag)
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Sorry, missed that on the first run, we'll also need to prefix this method with `fastlane_`

File: fastlane/lib/fastlane/fast_file.rb [hunk 6]
```diff
@@ -1,3 +1,26 @@
+require "rubygems"
+
+class String
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fast_file.rb]: Those extensions should probably be moved somewhere else (not `fast_file.rb`), we have a `core_ext` directory where we can put it. One file per class 👍

File: fastlane/lib/fastlane/fast_file.rb (hunk 5 above)
Comment (jdee) [reply fastlane/lib/fastlane/fast_file.rb]: That makes for an ugly API. For example, what does `fastlane_from_tag` mean? Am I--creating a `fastlane` from a tag? But it's just as well not to put these in these classes, so I have a better idea. Commit incoming.

File: fastlane_core/lib/fastlane_core/tag_version.rb [hunk 7]
```diff
@@ -0,0 +1,24 @@
+require "rubygems"
+
+module FastlaneCore
+  # Utility class to construct a Gem::Version from a tag.
```
Comment (jdee) [inline fastlane_core/lib/fastlane_core/tag_version.rb]: I think this is a pretty reasonable way to encapsulate this tag stuff in a reusable way. It seems like this might not be the only time you'd want to parse tags as versions using RubyGems. I'm out of time for this until this evening. I can add some tests for this class later.

File: fastlane/lib/fastlane/fast_file.rb (hunk 3 above)
Comment (jdee) [reply fastlane/lib/fastlane/fast_file.rb]: Also `require "rubygems"` already occurs in a number of source files:

```
[jdee@Jimmy-Dees-MacBookPro fastlane (wakka-wakka)]$ find . -type f -name '*.rb' -exec grep -l 'require.*rubygems' {} \;
./fastlane_core/lib/fastlane_core/tag_version.rb
./fastlane/spec/plugins_specs/plugin_generator_spec.rb
./fastlane/lib/fastlane/fast_file.rb
./fastlane/lib/fastlane/fastlane_require.rb
./fastlane/lib/fastlane/actions/update_fastlane.rb
./fastlane/lib/fastlane/actions/xcversion.rb
```

**Review by KrauseFx — APPROVED** [review]
Beautiful, the best PR 📯

File: fastlane/lib/fastlane/fast_file.rb (hunk 3 above)
Comment (milch) [reply fastlane/lib/fastlane/fast_file.rb]: What is it actually used for? Only the `Gem::Version` class? If so it might be possible to do a more specific `require`, e.g. `require  'rubygems/version'` or something like that

File: fastlane_core/lib/fastlane_core/tag_version.rb [hunk 8]
```diff
@@ -0,0 +1,24 @@
...
+    class << self
+      def correct?(tag)
+        superclass.correct?(version_number_from_tag(tag))
+      end
+
+      # Gem::Version.new barfs on things like "v0.1.0", which is the style
+      # generated by the rake release task. Just strip off any initial v
+      # to generate a Gem::Version from a tag.
+      def version_number_from_tag(tag)
+        tag.sub(/^v/, "")
```
Comment (milch) [inline fastlane_core/lib/fastlane_core/tag_version.rb]: If the only things that work are versions of the form `1.0` or `1.2.3.4.5` it might be a good idea to strip away everything else. Something like `tag.sub(/\D*((?:\d\.?)+)\D*/, '\1')` might more accurately extract only the version number independently of what else is in that line

File: fastlane/lib/fastlane/fast_file.rb (hunk 3 above)
Comment (jdee) [reply fastlane/lib/fastlane/fast_file.rb]: Yeah, I had that thought. `require "rubygems/requirement"` in fast_file.rb and `require "rubygems/version"` in tag_version.rb.

File: fastlane_core/lib/fastlane_core/tag_version.rb (hunk 8 above)
Comment (jdee) [reply fastlane_core/lib/fastlane_core/tag_version.rb]: RubyGems allows things like 1.3.0-beta.1, and 1.3.0-beta.2 > 1.3.0-beta.1.

```
[jdee@Jimmy-Dees-MacBookPro ~]$ irb
2.4.2 :001 > v1 = Gem::Version.new "1.3.0-beta.1"
 => #<Gem::Version "1.3.0.pre.beta.1"> 
2.4.2 :002 > v2 = Gem::Version.new "1.3.0-beta.2"
 => #<Gem::Version "1.3.0.pre.beta.2"> 
2.4.2 :003 > v2 <=> v1
 => 1 
```

I'm afraid that doing finer parsing here will be brittle and essentially rebuild bits of RubyGems. This method exists because RubyGems does not directly accept tags generated by the rake release task (from the Bundler, I believe).

In fact, I have a feeling that the reason this originally involved custom parsing might be because someone didn't want to be limited to whatever is supported by RubyGems (or didn't think of using RubyGems for non-Ruby version checking). After all lots of repos that use Fastlane are not Ruby repos and may have somewhat different versioning systems. But the option is either use something standard like RubyGems or, as @KrauseFx said somewhere, reinvent the wheel.

If a more general wheel ever did become necessary, this TagVersion class at least gives us a place to reinvent it.

**Comment by jdee** [comment]
I got busy and haven't written tests. I should be able to get those in tonight some time. I know a new release is being prepared. If this is fairly urgent for @NiklasWebnuts, we can perhaps squeeze this into the next release (or do another hotfix). Otherwise, I'll finish cleaning this up and get it into the next release.

Another thing I thought (for a later PR): I noticed that this action clones the repo into a temporary directory every time it runs. If the repo is large, this will take time. It's already not very fast. One thing we could do is add a parameter like `clone_path` or `checkout_path` that lets you clone things into a persistent location. If we find a repo already at that location, we can just `git pull --tags` instead of a fresh clone. For GitHub repos, we can even use the GitHub API first to see if there are any new tags, since `git pull` can be a bit slow.

**Comment by jdee** [comment]
Tests have been added for `TagVersion`. I'll merge tomorrow unless @milch or anyone else has any more thoughts or concerns.

**Comment by milch** [comment]
Nope, I'm totally fine with this! Feel free to merge
