### PR TITLE
[pilot] fix testflight distribution for multiplatform app bundles (ios/tvos)

### LINKED ISSUE #14033: Unable to distribute to testflight builds
### Question Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Question Subject
Error when distributing testflight builds via pilot. 

#### Question Description
We started seeing these errors in our CI pipe line a couple weeks ago that says we are unable to update the change log. But seems like there is something else going on here. 
As we haven't made any changes to our fastlane scripts, anyone else having issues like this starting a couple weeks ago?

Here's are verbose log:

```
ERROR [2019-01-07 17:11:12.56]: fastlane finished with errors
Traceback (most recent call last):
	24: from /Users/chwon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
	23: from /Users/chwon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	22: from /Users/chwon/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `<main>'
	21: from /Users/chwon/.rvm/gems/ruby-2.5.1/bin/fastlane:23:in `load'
	20: from /Users/chwon/.rvm/gems/ruby-2.5.1@global/gems/fastlane-2.113.0/bin/fastlane:23:in `<top (required)>'
	19: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	18: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	17: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	16: from /Users/chwon/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	15: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	14: from /Users/chwon/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	13: from /Users/chwon/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	12: from /Users/chwon/.rvm/gems/ruby-2.5.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	11: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	10: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	 9: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	 8: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	 7: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	 6: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	 5: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	 4: from ../../Common/fastlane/Fastfile:382:in `block (2 levels) in parsing_binding'
	 3: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/pilot/lib/pilot/build_manager.rb:88:in `distribute'
	 2: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/pilot/lib/pilot/build_manager.rb:92:in `rescue in distribute'
	 1: from /Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/chwon/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/fastlane-2.113.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Could not set changelog:


<html> (FastlaneCore::Interface::FastlaneError)
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /v2/providers/302756/apps/1382945144/builds/37665298. Reason:
<pre>    ERROR-1: Enter a demo account user name, or deselect "A demo account is required to use all the features of the app."; ERROR-1: Enter demo account password, or deselect "A demo account is required to use all the features of the app."</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

Other jobs failed with this error: The build is not in state for internal testing. - Build is not in internal testing state.

```
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/connect_api/client.rb:84:in `handle_response': [!] The build is not in state for internal testing. - Build is not in internal testing state. (Spaceship::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/connect_api/client.rb:66:in `post_for_testflight_review'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/spaceship/lib/spaceship/test_flight/build.rb:223:in `submit_for_testflight_review!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/pilot/lib/pilot/build_manager.rb:183:in `distribute_build'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/pilot/lib/pilot/build_manager.rb:108:in `distribute'
	from ../../Common/fastlane/Fastfile:382:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.112.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by tmm1**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

fixes https://github.com/fastlane/fastlane/issues/14033#issuecomment-497156408
cc @joshdholtz 

### Description

previously if you had a tvos+ios app and uploaded two ipas with the same version, you could only use fastlane to release one of them to testflight.

### Description (from @joshdholtz commits)
- Removed the use of `Fastlane::ConnectAPI::BuildDelivery` from `FastlaneCore::BuildWatcher` since `BuidDelivery` is only a web session (non-official App Store Connect API) endpoint / model
  - Small side effect is that a `Fastlane::ConnectAPI::Build` won't show up instantly (see attached screenshots)
- `FastlaneCore::BuildWatcher` watches specifically for a platform now and will now show the platform of the app being waited on
  - Will also raise error if multiple builds are returned from API call because that shouldn't happen
- `Fastlane::ConnectAPI::Build.all` now has a `platform` keyword which will filter builds (after fetched from API) for platform
  - This is done after fetch because there is not a great way to filter the platform in the request. Only way would be to first fetch a `Fastlane::ConnectAPI::PreReleaseVersion` and pass that up in the filter 😬
- ⚠️ The platform enums that are used by App Store Connect (`IOS`, `TV_OS`, `MAC_OS`, and `WATCH_OS`) are different than the enums that _fastlane_ has been using (`ios`, `osx`, and `appletvos`) so there is some mapping that needs to be done

Screen Shot 2019-07-08 at 6 25 54 AM
Screen Shot 2019-07-08 at 6 26 31 AM

### CODE REVIEW

**Comment by tmm1** [comment]
I tested this with a new build and I was able to release both ios and tvos builds to testflight independently.

Some tests are failing and I could use help to fix them.

File: spaceship/lib/spaceship/test_flight/build_trains.rb [hunk 1]
```diff
@@ -19,6 +19,13 @@ def self.all(app_id: nil, platform: nil, retry_count: 3)
       included = []
       cursor = nil
 
+      prerelease_platform = case platform
+                            when "appletvos"
+                              "TV_OS"
+                            else
+                              "IOS"
+                            end
```
Comment (tmm1) [inline spaceship/lib/spaceship/test_flight/build_trains.rb]: If someone has watchos or macos apps it would be helpful to know what codes are used by the api

File: pilot/lib/pilot/build_manager.rb [hunk 2]
```diff
@@ -128,7 +128,7 @@ def list(options)
 
     def update_beta_app_meta(options, build)
       # App Store Connect API build id
-      build_id = build.find_app_store_connect_build["id"]
+      build_id = build.id
```
Comment (tmm1) [inline pilot/lib/pilot/build_manager.rb]: Looks like @joshdholtz fixed this in a different way in https://github.com/fastlane/fastlane/commit/7b2d9ab0847d02f60966f2084120efc447f41d04#diff-fb9d332b3e3b1f3dfb3c5968c4f0c218L131

File: spaceship/lib/spaceship/test_flight/build.rb [hunk 3]
```diff
@@ -217,8 +217,7 @@ def submit_for_testflight_review!
         return if ready_to_test?
         return if approved?
 
-        build = find_app_store_connect_build
-        Spaceship::ConnectAPI::Base.client.post_beta_app_review_submissions(build_id: build["id"])
+        Spaceship::ConnectAPI::Base.client.post_beta_app_review_submissions(build_id: id)
```
Comment (tmm1) [inline spaceship/lib/spaceship/test_flight/build.rb]: This also looks unused now as of https://github.com/fastlane/fastlane/commit/7b2d9ab0847d02f60966f2084120efc447f41d04#diff-fb9d332b3e3b1f3dfb3c5968c4f0c218R300

**Comment by snatchev** [comment]
Hi @tmm1, thank you for this contribution! It looks like this PR was touching on some spaceship methods that migrated over to the AppStoreConnect API which got merged in recently.

Could you resolve the merge conflict and test if it works? After that, I can certainly help fix up any failing specs or other things to review. Sorry about not addressing this PR sooner. The AppStoreConnect API was a big release.

**Comment by tmm1** [comment]
@snatchev Thanks. I went ahead and fixed conflicts again.

**Review by joshdholtz — COMMENTED** [review]
@tmm1 Thanks for handling those merge conflicts! This change might not actually do anything anymore though 😔 A few months ago we started making the migration over to the official App Store Connect API with our new `Spaceship::ConnectAPI` module so ever reference to anything in the `Spaceship::TestFlight` module was removed.

So the changes in `to_testflight_buid`, `find_app_store_connect_build`, and `self.all` don't get used anymore within `pilot`/`upload_to_testflight`.

Were you able to verify that you were able to still upload for multi-platform app bundles? 😇

**Comment by nikitaame** [comment]
@tmm1 thanks for putting in this fix, hoping it works! Also having the same issue with multiplatform app bundles only releasing one of the platforms successfully. Let me know if there's any way I can help

**Comment by tmm1** [comment]
I have not tested this since I merged. I'll try it again now, but when I tested a few days ago some changes were still required.

@nikitaame Are you still experiencing the issue with fastlane 2.126.0?

**Comment by joshdholtz** [comment]
I don't have a multi-platform app setup to test this out on but I can get one setup myself. I just figured it would be quicker to see if you were able to see if things were fixed in `2.126.0` 🙃

**Comment by nikitaame** [comment]
@joshdholtz, right now on 2.124.0 because 2.125.0 was breaking even worse. Will trying out 2.126.0 now and report back, thank you!

**Comment by nikitaame** [comment]
@joshdholtz will it be possible to still distribute an already uploaded build using `upload_to_testflight`. Similarly to the current `Pilot::BuildManager.new.distribute(options)`? 

Right now the processing of our builds can take a significant amount of time, so we use `skip_waiting_for_processing` to free up our build machines to make other builds and then later release them at scheduled time after the completion of the job.

**Comment by tmm1** [comment]
@joshdholtz Would appreciate if you can spin up a multi-platform app and do some testing.

I'm running into a lot of weird problems with 2.126.0.. I use pilot to upload the tvos and ios ipas (both of which have the same version/buildnumber), but it seems only one ever shows up on the AppStore connect portal and my fastlane script gets stuck. I'm not quite sure if this is a fastlane regression or something's going on with AppStore Connect today- but I can't get to the distribute step to see if that part is working.

**Comment by tmm1** [comment]
Okay on my third try both builds uploaded correctly. So it seems that AppStore Connect is being flaky today.

Will see if the distribute code works as expected with both ipas now...

**Comment by tmm1** [comment]
Alright, I confirmed that this is still broken in 2.126.0. I'm calling `pilot distribute --app_platform appletvos && pilot distribute --app_platform ios`:
```
[15:37:54]: Login to App Store Connect
[15:37:55]: Login successful
[15:40:04]: Successfully set the beta_app_feedback_email and/or beta_app_description
[15:40:05]: Successfully set the changelog for build
[15:40:05]: Distributing new build to testers: 2019 - 6.25.2200
[15:40:08]: Successfully distributed build to External testers 🚀

[15:40:10]: Login to App Store Connect
[15:40:11]: Login successful
[15:42:45]: Successfully set the beta_app_feedback_email and/or beta_app_description
[15:42:45]: Successfully set the changelog for build
[15:42:45]: Distributing new build to testers: 2019 - 6.25.2200
[15:42:45]: Build 2019 - 6.25.2200 already submitted for review
[15:42:46]: Successfully distributed build to External testers 🚀
```

Strangely the distribute process is now also taking 2-3 minutes. But you can see the second invocation says "already submitted for review" because it picks the wrong platform build.

**Comment by tmm1** [comment]
> So the changes in `to_testflight_buid`, `find_app_store_connect_build`, and `self.all` don't get used anymore within `pilot`/`upload_to_testflight`.

`all` is still used here:

https://github.com/fastlane/fastlane/blob/6b7251d7346f3e2e1014dacb0640ba43dcb94f0a/pilot/lib/pilot/build_manager.rb#L103

And since `platform` is not passed in there, it always picks the wrong build.

**Comment by nikitaame** [comment]
Trying to use 2.126.0 I'm actually getting:
`/Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/client.rb:126:in `handle_response': [!] The request could not be completed because: (Spaceship::InternalServerError)
	Server error got 500
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/client.rb:87:in `get'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/response.rb:26:in `next_page'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/response.rb:39:in `block in next_pages'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/response.rb:38:in `loop'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/response.rb:38:in `next_pages'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/response.rb:51:in `all_pages'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/spaceship/lib/spaceship/connect_api/models/build.rb:105:in `all'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/pilot/lib/pilot/build_manager.rb:103:in `distribute'
	from ../../Common/fastlane/Fastfile:406:in `block (2 levels) in parsing_binding'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/ameln002/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.126.0/bin/fastlane:23:in `<top (required)>'
	from /Users/ameln002/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/ameln002/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
`

**Comment by nikitaame** [comment]
@tmm1 are you sure your solution works? I was trying to use your changes and ran into:
```Users/ameln002/Desktop/fastlane-fix-testflight-multiplatform/spaceship/lib/spaceship/connect_api/models/build.rb:115:in `all': [!] unknown keyword: platform (ArgumentError)```
```from /Users/ameln002/Desktop/fastlane-fix-testflight-multiplatform/pilot/lib/pilot/build_manager.rb:103:in `distribute'```

**Comment by joshdholtz** [comment]
@tmm1 @nikitaame Heyyyy 👋 I created a new iOS and tvOS app on my personal iOS developer team and I'm working on testing (and fixing things if needed) today so that we can get this issue closed out 💪

**Comment by joshdholtz** [comment]
Got this working! I got some cleanup today and a bit more testing but we good 💯

**Comment by joshdholtz** [comment]
This is ready for review!

**Comment by tmm1** [comment]
Diff looks good to me. Thanks so much for tackling this!

File: spaceship/lib/spaceship/connect_api.rb [hunk 4]
```diff
@@ -43,5 +43,30 @@ class << self
     class << self
       attr_reader :token
     end
+
```
Comment (snatchev) [inline spaceship/lib/spaceship/connect_api.rb]: Would be nice to have an explanation of why this exists and when to use it.

**Review by snatchev — APPROVED** [review]

**Comment by nikitaame** [comment]
Hey @tmm1 I think you still need to sign the CLA?

**Comment by joshdholtz** [comment]
@nikitaame We are good! That's just because I committed too and the bot gets confused 😊 Just waiting for these last tests to run then merging 💪
