### PR TITLE
Add -p param to oclint action to fix file relative paths

### LINKED ISSUE #3797: oclint action missing -p parameter and compile_commands.json fails on file relative paths
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

- oclint action missing -p parameter
It cause oclint fails when compile_commands.json is not in parent hierarchy of first input file.

- compile_commands.json fails on file relative paths 
"file" attribute, retrieved from compile_commands.json, may be not absolute.
The full path need to be generated using also the "directory" attribute, in this case we need to concat the directory + file attribute
i.e. xcpretty generates compile_commands.json with directory and file name to be concat.

##### Complete output when running fastlane, including the stack trace and command used

this xcpretty [compile_commands.json](https://github.com/fastlane/fastlane/files/177835/compile_commands_1.txt) (doesn't work with current version)

this xctool [compile_commands.json](https://github.com/fastlane/fastlane/files/177831/compile_commands.txt) (works with current version)

### PR DESCRIPTION
**Pull request by lubbo**
oclint action missing -p parameter and compile_commands.json fails on file relative paths

### CODE REVIEW

File: fastlane/lib/fastlane/actions/oclint.rb [hunk 1]
```diff
@@ -23,7 +23,11 @@ def self.run(params)
         select_regex = params[:select_regex] if params[:select_regex] # Overwrite deprecated select_reqex
         exclude_regex = params[:exclude_regex]
 
-        files = JSON.parse(File.read(compile_commands)).map { |compile_command| compile_command['file'] }
+        files = JSON.parse(File.read(compile_commands)).map do |compile_command|
+          file = compile_command['file']
+          File.exist?(file) ? file : compile_command['directory'] + '/' + file
```
Comment (mfurtak) [inline fastlane/lib/fastlane/actions/oclint.rb]: Rather than building your own string path, use:
``` ruby
File.join(compile_command['directory'], file)
```
:+1:

Comment (mfurtak) [inline fastlane/lib/fastlane/actions/oclint.rb]: From your example data, I think you would get a path like:

/Users/radbuilder/Documents/Test/App_Apps_ios/staticlib/**StaticLibShared/StaticLibShared**/ClassStaticLibShared.m

Is that doubling of the **StaticLibShared** part right?

**Comment by nfalco79** [comment]
good suggestion for File.join(...) (we are not ruby programmers :P, we patch some actions to fastlane works)

and yes, the path is correct.
Our workspace directory structure is

```
App_App_ios
|-app
|-framework
|-staticlib
|--StaticLibShared
   |--StaticLibShared
      |--ClassStaticLibShared.h
      |--ClassStaticLibShared.m
      |--StaticLibShared.h
      |--StaticLibShared.m
   |--StaticLibShared.xcodeproj
   |--ClassStaticLibShared.plist
   |--StaticLibShared.plist
|--StaticLibUsingFramework
workspace.xcworkspace
```

File: fastlane/lib/fastlane/actions/oclint.rb (hunk 1 above)
Comment (nfalco79) [inline fastlane/lib/fastlane/actions/oclint.rb]: good suggestion for File.join(...) (we are not ruby programmers :P, we patch some actions to fastlane works)

and yes, the path is correct.
Our workspace directory structure is

```
App_App_ios
|-app
|-framework
|-staticlib
|--StaticLibShared
   |--StaticLibShared
      |--ClassStaticLibShared.h
      |--ClassStaticLibShared.m
      |--StaticLibShared.h
      |--StaticLibShared.m
   |--StaticLibShared.xcodeproj
   |--ClassStaticLibShared.plist
   |--StaticLibShared.plist
|--StaticLibUsingFramework
workspace.xcworkspace

```

Comment (mfurtak) [inline fastlane/lib/fastlane/actions/oclint.rb]: Great - just wanted to check! :+1:

Comment (nfalco79) [inline fastlane/lib/fastlane/actions/oclint.rb]: we make other commit that fit hound violation `expect(result).to match(%r{cd .* && oclint -report-type=html -o=oclint_report.html -p .*?compile_commands\.json \".*})` and your suggestion after all will be green green maybe you prefer we create a new PR to have a clean commit history instead tentative?

**Comment by mfurtak** [comment]
@nfalco79 It's OK if you want to add another commit to this PR to fix what you just described.

Right before we decide to merge, we will ask you to squash all current commits into one. Does that work for you?

**Comment by mfurtak** [comment]
Arg - Hound and local rubocop are arguing over what the correct syntax is 😖 

Please use whichever regular expression syntax makes rubocop pass locally (run `bundle exec rubocop`), and we'll ignore the Hound comments about it :+1:

**Comment by lubbo** [comment]
We obtained all green but after git squash CircleCI fails....

**Comment by nfalco79** [comment]
What's happen now? Unclear log

**Comment by nfalco79** [comment]
maybe some problem to checkout a branch has diverged after squash?

**Comment by i2amsam** [comment]
We are investigating CI failures on all the branches right now, looks like CircleCI has changed something.

**Comment by i2amsam** [comment]
@lubbo @nfalco79 

We had an issue with CI earlier, you’ll need to bring in a fix so the tests will pass on CI, please run:
```
git cherry-pick f6a7d2100b639c27ecd70c51f59f3542b9dc5cea
```
and push again to update this request.

**Comment by lubbo** [comment]
All green!

**Comment by mfurtak** [comment]
Great, thanks for the contribution! :+1:
