### PR TITLE
List produce enable_services options in config item (deprecating enabled_features)

### LINKED ISSUE #9209: [produce] unclear option enabled_features
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The usage information lists
```
 -P, --enabled_features [VALUE] Array with Spaceship App Features (PRODUCE_ENABLED_FEATURES)
```
but none information is given whatsoever what the possible values are and how the syntax should look like to pass them. 

##### Complete output when running fastlane, including the stack trace and command used

```
$  bundle exec fastlane produce -h
  produce

  CLI for 'produce'

  Commands: (* default)
    associate_group    Associate with a group, which is created if needed or simply located otherwise
    create           * Creates a new app on iTunes Connect and the Apple Developer Portal
    disable_services   Disable specific Application Services for a specific app on the Apple Developer Portal
    enable_services    Enable specific Application Services for a specific app on the Apple Developer Portal
    group              Ensure that a specific App Group exists
    help               Display global or [command] help documentation

  Global Options:
    --verbose             
    -h, --help           Display help documentation 
    -v, --version        Display version information 

  Options for create:
    -u, --username STRING Your Apple ID Username (PRODUCE_USERNAME)
    -a, --app_identifier STRING App Identifier (Bundle ID, e.g. com.krausefx.app) (PRODUCE_APP_IDENTIFIER)
    -e, --bundle_identifier_suffix STRING App Identifier Suffix (Ignored if App Identifier does not ends with .*) (PRODUCE_APP_IDENTIFIER_SUFFIX)
    -q, --app_name STRING App Name (PRODUCE_APP_NAME)
    -z, --app_version STRING Initial version number (e.g. '1.0') (PRODUCE_VERSION)
    -y, --sku STRING     SKU Number (e.g. '1234') (PRODUCE_SKU)
    -j, --platform STRING The platform to use (optional) (PRODUCE_PLATFORM)
    -m, --language STRING Primary Language (e.g. 'English', 'German') (PRODUCE_LANGUAGE)
    -c, --company_name STRING The name of your company. Only required if it's the first app you create (PRODUCE_COMPANY_NAME)
    -i, --skip_itc [VALUE] Skip the creation of the app on iTunes Connect (PRODUCE_SKIP_ITC)
    -P, --enabled_features [VALUE] Array with Spaceship App Features (PRODUCE_ENABLED_FEATURES)
    -d, --skip_devcenter [VALUE] Skip the creation of the app on the Apple Developer Portal (PRODUCE_SKIP_DEVCENTER)
    -b, --team_id STRING The ID of your Developer Portal team if you're in multiple teams (PRODUCE_TEAM_ID)
    -l, --team_name STRING The name of your Developer Portal team if you're in multiple teams (PRODUCE_TEAM_NAME)
    -k, --itc_team_id [VALUE] The ID of your iTunes Connect team if you're in multiple teams (PRODUCE_ITC_TEAM_ID)
    -p, --itc_team_name STRING The name of your iTunes Connect team if you're in multiple teams (PRODUCE_ITC_TEAM_NAME)
  
  Author:
    Felix Krause <produce@krausefx.com>
  
  Website:
    https://fastlane.tools
  
  GitHub:
    https://github.com/fastlane/produce
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                         |
| --------------------------- | ----------------------------------------------------------------------------- |
| OS                          | 10.12.4                                                                       |
| Ruby                        | 2.3.1                                                                         |
| Bundler?                    | true                                                                          |
| Git                         | git version 2.12.2                                                            |
| Installation Source         | ~/Projects/customer/kaufhof/gkh-ios-app/Vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                                                     |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.1/lib                                                      |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                                                    |
| Is contained                | false                                                                         |
| Is homebrew                 | false                                                                         |
| Is installed via Fabric.app | false                                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                   |
| Xcode Version               | 8.3.2                                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US       | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.31.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.5        |
| rake                      | 10.4.2       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| aws-sigv4                 | 1.0.0        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.8.5        |
| aws-sdk-resources         | 2.8.5        |
| aws-sdk                   | 2.8.5        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| credentials_manager       | 1.0.0        |
| houston                   | 2.2.4        |
| xcode-install             | 2.1.1        |
</details>

*generated on:* **2017-05-18**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #9209 

## Problem
The `enabled_features` command was not self documented enough to show how to properly use. Keys were given but not values and did not explain how to use for either CLI or Fastfile. Using via CLI was "technically" not even supported due to `enabled_features` needing to be a hash. Also, the command `fastlane produce enabled_services` already existed which did a similar thing but had different naming patterns. 

## Solution
The solution was to add documentation to the config item to show what the accepted keys and values are along with hiding the `enabled_features` from showing up when `fastlane produce --help` is being run
- Added `display_in_shell` as `FastlaneCore::ConfigItem` param
  - Some "hash" config items aren't meant to be entered in via CLI
- In `produce`...
  - Deprecating `enabled_features` in favor of `enable_services` to be consistent with `fastlane produce enable_services` command
  - Created constants for service values
  - Created a list of valid service keys and values that are displayed in `fastlane action produce`

```sh
| enabled_features         | [DEPRECATED!] Please use `enable_services`  | PRODUCE_ENABLED_FEATURES      | {}         |
|                          | instead - Array with Spaceship App Services |                               |            |
| enable_services          | Array with Spaceship App Services (e.g.     | PRODUCE_ENABLE_SERVICES       | {}         |
|                          | app_group: (on|off), apple_pay: (on|off),   |                               |            |
|                          | associated_domains: (on|off),               |                               |            |
|                          | data_protection:                            |                               |            |
|                          | (complete|unlessopen|untilfirstauth),       |                               |            |
|                          | game_center: (on|off), health_kit:          |                               |            |
|                          | (on|off), home_kit: (on|off),               |                               |            |
|                          | wireless_accessory: (on|off), icloud:       |                               |            |
|                          | (legacy|cloudkit), in_app_purchase:         |                               |            |
|                          | (on|off), inter_app_audio: (on|off),        |                               |            |
|                          | passbook: (on|off), push_notification:      |                               |            |
|                          | (on|off), siri_kit: (on|off),               |                               |            |
|                          | vpn_configuration: (on|off))                |                               |            |
```

### CODE REVIEW

**Comment by mfurtak** [comment]
Is there any place in code where we have values for these defined? It'd be nice if we could compute this list from an authoritative place, so we don't have to worry about it getting out-of-date.

File: produce/lib/produce/options.rb [hunk 1]
```diff
@@ -69,7 +69,7 @@ def self.available_options
         FastlaneCore::ConfigItem.new(key: :enabled_features,
                                      short_option: "-P",
                                      env_name: "PRODUCE_ENABLED_FEATURES",
-                                     description: "Array with Spaceship App Features",
+                                     description: "Array with Spaceship App Features (e.g. app_group,apple_pay, associated_domains, data_protection, game_center, health_kit, home_kit, wireless_accessory, icloud, in_app_purchase, inter_app_audio, passbook, push_notification, siri_kit, vpn_configuration)",
```
Comment (taquitos) [inline produce/lib/produce/options.rb]: Needs space between these two: `app_group,apple_pay`

File: fastlane_core/lib/fastlane_core/configuration/config_item.rb [hunk 2]
```diff
@@ -55,7 +58,8 @@ class ConfigItem
     # @param conflict_block an optional block which is called when options conflict happens
     # @param deprecated (String) Set if the option is deprecated. A deprecated option should be optional and is made optional if the parameter isn't set, and fails otherwise
     # @param sensitive (Boolean) Set if the variable is sensitive, such as a password or API token, to prevent echoing when prompted for the parameter
-    def initialize(key: nil, env_name: nil, description: nil, short_option: nil, default_value: nil, verify_block: nil, is_string: true, type: nil, optional: nil, conflicting_options: nil, conflict_block: nil, deprecated: nil, sensitive: nil)
+    # @param display_in_shell (Boolean) Set if the variable can be used from shell
+    def initialize(key: nil, env_name: nil, description: nil, short_option: nil, default_value: nil, verify_block: nil, is_string: true, type: nil, optional: nil, conflicting_options: nil, conflict_block: nil, deprecated: nil, sensitive: nil, display_in_shell: nil)
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/configuration/config_item.rb]: Wohoo, so many, can we split those up in one key/value per line?

File: fastlane_core/lib/fastlane_core/configuration/config_item.rb [hunk 3]
```diff
@@ -100,6 +106,7 @@ def initialize(key: nil, env_name: nil, description: nil, short_option: nil, def
       @deprecated = deprecated
       @sensitive = sensitive
       @allow_shell_conversion = (type == :shell_string)
+      @display_in_shell = display_in_shell
```
Comment (KrauseFx) [inline fastlane_core/lib/fastlane_core/configuration/config_item.rb]: Can we merge this with line 92 to be in one line?

**Review by KrauseFx — APPROVED** [review]
Great work on this, I added 2 comments that should be addressed before merging 👍

**Comment by joshdholtz** [comment]
@hjanuschka Do you mind taking a look at this too since you originally created this `enabled_features` feature? 😇

**Review by hjanuschka — APPROVED** [review]
@joshdholtz awesome work, i like the new `display_in_shell` option. PR LGTM 💯

**Review by KrauseFx — CHANGES_REQUESTED** [review]
One little change I requested

File: fastlane_core/lib/fastlane_core/configuration/config_item.rb (hunk 3 above)
Comment (joshdholtz) [inline fastlane_core/lib/fastlane_core/configuration/config_item.rb]: @KrauseFx It was pretty ugly to combine into one line so I changed the default value in the method definition to `true` 😇  I think this was the cleanest way of doing it?

**Review by KrauseFx — APPROVED** [review]
