### PR TITLE
[screengrab] fix screengrab folder name

### LINKED ISSUE #15653: Screengrab 2.0 not grabbing screenshots
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Screengrab is generating screenshots but can't extract them from the device.

I can see the screenshots in the device explorer, and I get the following log during execution:
```
2019-11-14 12:02:35.382 938-991/[APP_BUNDLE] D/Screengrab: Using screenshot storage directory: /data/user/0/[APP_BUNDLE]/files/[APP_BUNDLE]/screengrab/en-US/images/screenshots
2019-11-14 12:02:35.566 938-991/[APP_BUNDLE] D/Screengrab: Captured screenshot "onboarding.png"
```

So it works ok but at the end, I get the following the following error:
```
[12:32:23]: Pulling captured screenshots from the device
[12:32:24]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
```

##### Command executed
```
fastlane screengrab
```

##### Complete output when running fastlane, including the stack trace and command used
<details><summary>Output</summary><pre>
[12:32:03]: Successfully loaded '/Users/benoit/git/android/android-app/Screengrabfile' 📄

+-----------------------------+--------------------------------------+
|              Detected Values from './Screengrabfile'               |
+-----------------------------+--------------------------------------+
| app_package_name            | [APP_BUNDLE]     |
| use_tests_in_packages       | ["[APP_BUNDLE].screen  |
|                             | shots.scene"]                        |
| app_apk_path                | app/build/outputs/apk/debug/app-deb  |
|                             | ug.apk                               |
| tests_apk_path              | app/build/outputs/apk/androidTest/d  |
|                             | ebug/app-debug-androidTest.apk       |
| locales                     | ["en-US"]                            |
| clear_previous_screenshots  | true                                 |
| skip_open_summary           | true                                 |
| launch_arguments            | ["screenshot true"]                  |
| test_instrumentation_runner | [APP_BUNDLE].TestAppl  |
|                             | icationTestRunner                    |
+-----------------------------+--------------------------------------+

+-----------------------------+--------------------------------------+
|                   Summary for screengrab 2.135.2                   |
+-----------------------------+--------------------------------------+
| tests_package_name          | [APP_BUNDLE].debug.te  |
|                             | st                                   |
| locales                     | ["en-US"]                            |
| clear_previous_screenshots  | true                                 |
| output_directory            | fastlane/metadata/android            |
| skip_open_summary           | true                                 |
| app_package_name            | [APP_BUNDLE].debug     |
| use_tests_in_packages       | ["[APP_BUNDLE].screen  |
|                             | shots.scene"]                        |
| launch_arguments            | ["screenshot true"]                  |
| test_instrumentation_runner | [APP_BUNDLE].TestAppl  |
|                             | icationTestRunner                    |
| ending_locale               | en-US                                |
| app_apk_path                | app/build/outputs/apk/debug/app-deb  |
|                             | ug.apk                               |
| tests_apk_path              | app/build/outputs/apk/androidTest/d  |
|                             | ebug/app-debug-androidTest.apk       |
| device_type                 | phone                                |
| exit_on_test_failure        | true                                 |
| reinstall_app               | false                                |
+-----------------------------+--------------------------------------+

[12:32:03]: Clearing phoneScreenshots within fastlane/metadata/android
[12:32:03]: $ /Users/benoit/android/platform-tools/adb devices -l
[12:32:03]: ▸ List of devices attached
[12:32:03]: ▸ emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[12:32:03]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[12:32:03]: ▸ /sdcard
[12:32:03]: Cleaning screenshots on device
[12:32:03]: Validating app APK
[12:32:03]: $ /Users/benoit/android/build-tools/29.0.2/aapt dump permissions app/build/outputs/apk/debug/app-debug.apk
[12:32:03]: ▸ package: [APP_BUNDLE].debug
[12:32:03]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[12:32:03]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[12:32:03]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[12:32:03]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[12:32:03]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[12:32:03]: ▸ uses-permission: name='android.permission.SET_ANIMATION_SCALE'
[12:32:03]: ▸ uses-permission: name='android.permission.FOREGROUND_SERVICE'
[12:32:03]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[12:32:03]: ▸ uses-permission: name='android.permission.INTERNET'
[12:32:03]: ▸ uses-permission: name='android.permission.VIBRATE'
[12:32:03]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[12:32:03]: ▸ uses-permission: name='com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE'
[12:32:03]: ▸ uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
[12:32:03]: Installing app APK
[12:32:03]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/debug/app-debug.apk
[12:32:03]: ▸ Performing Push Install
[12:32:04]: ▸ app/build/outputs/apk/debug/app-debug.apk: 1 file pushed. 152.5 MB/s (17008855 bytes in 0.106s)
[12:32:04]: ▸ 	pkg: /data/local/tmp/app-debug.apk
[12:32:18]: ▸ Success
[12:32:18]: Installing tests APK
[12:32:18]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 install -t -r app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
[12:32:18]: ▸ Performing Push Install
[12:32:18]: ▸ app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk: 1 file pushed. 68.9 MB/s (6080262 bytes in 0.084s)
[12:32:18]: ▸ 	pkg: /data/local/tmp/app-debug-androidTest.apk
[12:32:21]: ▸ Success
[12:32:21]: Granting the permission necessary to change locales on the device
[12:32:21]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell pm grant [APP_BUNDLE].debug android.permission.CHANGE_CONFIGURATION
[12:32:21]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell getprop ro.build.version.sdk
[12:32:21]: ▸ 23
[12:32:21]: Granting the permissions necessary to access device external storage
[12:32:21]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell pm grant [APP_BUNDLE].debug android.permission.WRITE_EXTERNAL_STORAGE
[12:32:21]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell pm grant [APP_BUNDLE].debug android.permission.READ_EXTERNAL_STORAGE
[12:32:21]: Running tests for locale: en-US
[12:32:21]: $ /Users/benoit/android/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
-e package [APP_BUNDLE].screenshots.scene \
-e screenshot true \
[APP_BUNDLE].test/[APP_BUNDLE].TestApplicationTestRunner
[12:32:23]: ▸ [APP_BUNDLE].screenshots.scene.OnboardingScreenshot:.
[12:32:23]: ▸ Time: 1.386
[12:32:23]: ▸ OK (1 test)
[12:32:23]: Pulling captured screenshots from the device
[12:32:24]: Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

[!] No screenshots were detected 📷❌
</pre></details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.6 (18G95)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.135.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.17.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| jwt                       | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| multi_json                | 1.12.1       |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.1.0        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-11-14**
</details>

### LINKED ISSUE #16050: [Regression] 2.142.0 messed up metadata folder structure
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.142.0`]
- Last working version: [e.g. `2.141.0`]

### Regression Description

Running `bundle exec fastlane screengrab`, with `locales(['en-US', 'de-DE', 'nl-NL'])` I expect the following folder structure to be generated

```
metadata/android/de-DE/images/phoneScreenshots/*.png
metadata/android/en-US/images/phoneScreenshots/*.png
metadata/android/nl-NL/images/phoneScreenshots/*.png
```
Instead I get
```
metadata/android/de-DE/images/de-DE/images/phoneScreenshots/*.png
metadata/android/de-DE/images/nl-NL/images/phoneScreenshots/*.png
metadata/android/en-US/images/de-DE/images/phoneScreenshots/*.png
metadata/android/en-US/images/en-US/images/phoneScreenshots/*.png
metadata/android/en-US/images/nl-NL/images/phoneScreenshots/*.png
metadata/android/nl-NL/images/nl-NL/images/phoneScreenshots/*.png
```

Adding more locales in Screengrabfile adds an increasing amount of excess folders.

This also breaks the screenshots.html. It just shows a blank screen. Seems to be caused by changes in PR https://github.com/fastlane/fastlane/pull/15994

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>➜  xxx git:(feature/fastlane-screenshots) ✗ bundle exec fastlane screengrab
[⠼] 🚀 /Users/timcastelijns/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/faraday_middleware-0.13.1/lib/faraday_middleware/response_middleware.rb:14: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead
[✔] 🚀
[11:30:00]: Successfully loaded '/Users/timcastelijns/git/xxx/fastlane/Screengrabfile' 📄

+----------------------------+----------------------------------+
|       Detected Values from './fastlane/Screengrabfile'        |
+----------------------------+----------------------------------+
| locales                    | ["en-US", "de-DE", "nl-NL"]      |
| app_package_name           | com.xxx          |
| use_tests_in_packages      | ["com.xxx.screengrab"] |
| clear_previous_screenshots | true                             |
+----------------------------+----------------------------------+

+-----------------------------+------------------------------------------+
|                     Summary for screengrab 2.142.0                     |
+-----------------------------+------------------------------------------+
| tests_package_name          | com.xxx.debug.test             |
| android_home                | /Users/timcastelijns/Library/Android/sdk |
| locales                     | ["en-US", "de-DE", "nl-NL"]              |
| clear_previous_screenshots  | true                                     |
| output_directory            | fastlane/metadata/android                |
| skip_open_summary           | false                                    |
| app_package_name            | com.xxx.debug                  |
| use_tests_in_packages       | ["com.xxx.screengrab"]         |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner  |
| ending_locale               | en-US                                    |
| use_adb_root                | false                                    |
| device_type                 | phone                                    |
| exit_on_test_failure        | true                                     |
| reinstall_app               | false                                    |
| use_timestamp_suffix        | true                                     |
+-----------------------------+------------------------------------------+

[11:30:00]: Clearing phoneScreenshots within fastlane/metadata/android
[11:30:00]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell echo \$EXTERNAL_STORAGE
[11:30:00]: ▸ /sdcard
[11:30:00]: Cleaning screenshots on device
[11:30:00]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell rm -rf /sdcard/com.xxx.debug/screengrab
ls: /data/data/com.xxx.debug/app_screengrab: Permission denied
[11:30:00]: Exit status: 1
/Users/timcastelijns/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/timcastelijns/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.142.0/fastlane_core/lib/fastlane_core/ui/errors/fastlane_error.rb:9: warning: The called method `initialize' is defined here
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/en-US/images/screenshots: Permission denied
[11:30:00]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/de-DE/images/screenshots: Permission denied
[11:30:00]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/nl-NL/images/screenshots: Permission denied
[11:30:01]: Exit status: 1
[11:30:01]: To not be asked about this value, you can specify it using 'app_apk_path'
[11:30:01]: Select your debug app APK
/Users/timcastelijns/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
1. app/build/outputs/apk/androidTest/debug/app.apk
2. app/build/outputs/apk/debug/app.apk
?  2
[11:30:45]: To not be asked about this value, you can specify it using 'tests_apk_path'
[11:30:45]: Select your debug tests APK
/Users/timcastelijns/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/highline-1.7.10/lib/highline.rb:624: warning: Using the last argument as keyword parameters is deprecated
1. app/build/outputs/apk/androidTest/debug/app.apk
2. app/build/outputs/apk/debug/app.apk
?  1
[11:30:47]: Validating app APK
[11:30:47]: $ /Users/timcastelijns/Library/Android/sdk/build-tools/29.0.2/aapt dump permissions app/build/outputs/apk/debug/app.apk
[11:30:47]: ▸ package: com.xxx.debug
[11:30:47]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[11:30:47]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[11:30:47]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[11:30:47]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[11:30:47]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[11:30:47]: ▸ uses-permission: name='android.permission.INTERNET'
[11:30:47]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[11:30:47]: ▸ uses-permission: name='android.permission.BLUETOOTH'
[11:30:47]: ▸ uses-permission: name='android.permission.BLUETOOTH_ADMIN'
[11:30:47]: ▸ uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
[11:30:47]: ▸ uses-permission: name='android.permission.FOREGROUND_SERVICE'
[11:30:47]: ▸ uses-permission: name='android.permission.ACCESS_WIFI_STATE'
[11:30:47]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[11:30:47]: Installing app APK
[11:30:47]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 install -t -r app/build/outputs/apk/debug/app.apk
[11:30:47]: ▸ Performing Streamed Install
[11:30:50]: ▸ Success
[11:30:50]: Installing tests APK
[11:30:50]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 install -t -r app/build/outputs/apk/androidTest/debug/app.apk
[11:30:50]: ▸ Performing Streamed Install
[11:30:51]: ▸ Success
[11:30:51]: Granting the permission necessary to change locales on the device
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell pm grant com.xxx.debug android.permission.CHANGE_CONFIGURATION
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell getprop ro.build.version.sdk
[11:30:51]: ▸ 29
[11:30:51]: Granting the permissions necessary to access device external storage
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell pm grant com.xxx.debug android.permission.WRITE_EXTERNAL_STORAGE
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell pm grant com.xxx.debug android.permission.READ_EXTERNAL_STORAGE
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell getprop ro.build.version.sdk
[11:30:51]: ▸ 29
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/build-tools/29.0.2/aapt dump badging app/build/outputs/apk/debug/app.apk
[11:30:51]: ▸ package: name='com.xxx.debug' versionCode='5' versionName='0.9.1-dev-81e3' compileSdkVersion='29' compileSdkVersionCodename='10'
[11:30:51]: ▸ sdkVersion:'24'
[11:30:51]: ▸ targetSdkVersion:'29'
[11:30:51]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[11:30:51]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[11:30:51]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[11:30:51]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[11:30:51]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[11:30:51]: ▸ uses-permission: name='android.permission.INTERNET'
[11:30:51]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[11:30:51]: ▸ uses-permission: name='android.permission.BLUETOOTH'
[11:30:51]: ▸ uses-permission: name='android.permission.BLUETOOTH_ADMIN'
[11:30:51]: ▸ uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
[11:30:51]: ▸ uses-permission: name='android.permission.FOREGROUND_SERVICE'
[11:30:51]: ▸ uses-permission: name='android.permission.ACCESS_WIFI_STATE'
[11:30:51]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[11:30:51]: ▸ application-label:'xxx'
[11:30:51]: ▸ application-label-af:'xxx'
[11:30:51]: ▸ application-label-am:'xxx'
[11:30:51]: ▸ application-label-ar:'xxx'
[11:30:51]: ▸ application-label-as:'xxx'
[11:30:51]: ▸ application-label-az:'xxx'
[11:30:51]: ▸ application-label-be:'xxx'
[11:30:51]: ▸ application-label-bg:'xxx'
[11:30:51]: ▸ application-label-bn:'xxx'
[11:30:51]: ▸ application-label-bs:'xxx'
[11:30:51]: ▸ application-label-ca:'xxx'
[11:30:51]: ▸ application-label-cs:'xxx'
[11:30:51]: ▸ application-label-da:'xxx'
[11:30:51]: ▸ application-label-de:'xxx'
[11:30:51]: ▸ application-label-el:'xxx'
[11:30:51]: ▸ application-label-en-AU:'xxx'
[11:30:51]: ▸ application-label-en-CA:'xxx'
[11:30:51]: ▸ application-label-en-GB:'xxx'
[11:30:51]: ▸ application-label-en-IE:'xxx'
[11:30:51]: ▸ application-label-en-IN:'xxx'
[11:30:51]: ▸ application-label-en-XC:'[[xxx]]'
[11:30:51]: ▸ application-label-en-ZZ:'[[xxx]]'
[11:30:51]: ▸ application-label-es:'xxx'
[11:30:51]: ▸ application-label-es-CL:'xxx'
[11:30:51]: ▸ application-label-es-CO:'xxx'
[11:30:51]: ▸ application-label-es-CR:'xxx'
[11:30:51]: ▸ application-label-es-ES:'xxx'
[11:30:51]: ▸ application-label-es-MX:'xxx'
[11:30:51]: ▸ application-label-es-PA:'xxx'
[11:30:51]: ▸ application-label-es-PE:'xxx'
[11:30:51]: ▸ application-label-es-US:'xxx'
[11:30:51]: ▸ application-label-et:'xxx'
[11:30:51]: ▸ application-label-eu:'xxx'
[11:30:51]: ▸ application-label-fa:'xxx'
[11:30:51]: ▸ application-label-fi:'xxx'
[11:30:51]: ▸ application-label-fr:'xxx'
[11:30:51]: ▸ application-label-fr-CA:'xxx'
[11:30:51]: ▸ application-label-gl:'xxx'
[11:30:51]: ▸ application-label-gu:'xxx'
[11:30:51]: ▸ application-label-hi:'xxx'
[11:30:51]: ▸ application-label-hr:'xxx'
[11:30:51]: ▸ application-label-hu:'xxx'
[11:30:51]: ▸ application-label-hy:'xxx'
[11:30:51]: ▸ application-label-in:'xxx'
[11:30:51]: ▸ application-label-is:'xxx'
[11:30:51]: ▸ application-label-is-IS:'xxx'
[11:30:51]: ▸ application-label-it:'xxx'
[11:30:51]: ▸ application-label-iw:'xxx'
[11:30:51]: ▸ application-label-ja:'xxx'
[11:30:51]: ▸ application-label-ka:'xxx'
[11:30:51]: ▸ application-label-kk:'xxx'
[11:30:51]: ▸ application-label-km:'xxx'
[11:30:51]: ▸ application-label-kn:'xxx'
[11:30:51]: ▸ application-label-ko:'xxx'
[11:30:51]: ▸ application-label-ky:'xxx'
[11:30:51]: ▸ application-label-lo:'xxx'
[11:30:51]: ▸ application-label-lt:'xxx'
[11:30:51]: ▸ application-label-lv:'xxx'
[11:30:51]: ▸ application-label-mk:'xxx'
[11:30:51]: ▸ application-label-ml:'xxx'
[11:30:51]: ▸ application-label-mn:'xxx'
[11:30:51]: ▸ application-label-mr:'xxx'
[11:30:51]: ▸ application-label-ms:'xxx'
[11:30:51]: ▸ application-label-my:'xxx'
[11:30:51]: ▸ application-label-nb:'xxx'
[11:30:51]: ▸ application-label-ne:'xxx'
[11:30:51]: ▸ application-label-nl:'xxx'
[11:30:51]: ▸ application-label-no:'xxx'
[11:30:51]: ▸ application-label-or:'xxx'
[11:30:51]: ▸ application-label-pa:'xxx'
[11:30:51]: ▸ application-label-pl:'xxx'
[11:30:51]: ▸ application-label-pt:'xxx'
[11:30:51]: ▸ application-label-pt-BR:'xxx'
[11:30:51]: ▸ application-label-pt-PT:'xxx'
[11:30:51]: ▸ application-label-ro:'xxx'
[11:30:51]: ▸ application-label-ru:'xxx'
[11:30:51]: ▸ application-label-si:'xxx'
[11:30:51]: ▸ application-label-sk:'xxx'
[11:30:51]: ▸ application-label-sl:'xxx'
[11:30:51]: ▸ application-label-sq:'xxx'
[11:30:51]: ▸ application-label-sr:'xxx'
[11:30:51]: ▸ application-label-sr-Latn:'xxx'
[11:30:51]: ▸ application-label-sv:'xxx'
[11:30:51]: ▸ application-label-sw:'xxx'
[11:30:51]: ▸ application-label-ta:'xxx'
[11:30:51]: ▸ application-label-te:'xxx'
[11:30:51]: ▸ application-label-th:'xxx'
[11:30:51]: ▸ application-label-tl:'xxx'
[11:30:51]: ▸ application-label-tr:'xxx'
[11:30:51]: ▸ application-label-uk:'xxx'
[11:30:51]: ▸ application-label-ur:'xxx'
[11:30:51]: ▸ application-label-uz:'xxx'
[11:30:51]: ▸ application-label-vi:'xxx'
[11:30:51]: ▸ application-label-zh-CN:'xxx'
[11:30:51]: ▸ application-label-zh-HK:'xxx'
[11:30:51]: ▸ application-label-zh-TW:'xxx'
[11:30:51]: ▸ application-label-zu:'xxx'
[11:30:51]: ▸ application-icon-120:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-160:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-240:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-320:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-480:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-640:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-icon-65534:'res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application: label='xxx' icon='res/mipmap-anydpi-v26/ic_launcher.xml'
[11:30:51]: ▸ application-debuggable
[11:30:51]: ▸ launchable-activity: name='com.xxx.MainActivity'  label='' icon=''
[11:30:51]: ▸ feature-group: label=''
[11:30:51]: ▸   uses-feature: name='android.hardware.bluetooth'
[11:30:51]: ▸   uses-implied-feature: name='android.hardware.bluetooth' reason='requested android.permission.BLUETOOTH permission, requested android.permission.BLUETOOTH_ADMIN permission, and targetSdkVersion > 4'
[11:30:51]: ▸   uses-feature: name='android.hardware.faketouch'
[11:30:51]: ▸   uses-implied-feature: name='android.hardware.faketouch' reason='default feature for all apps'
[11:30:51]: ▸   uses-feature: name='android.hardware.location'
[11:30:51]: ▸   uses-implied-feature: name='android.hardware.location' reason='requested android.permission.ACCESS_FINE_LOCATION permission'
[11:30:51]: ▸   uses-feature: name='android.hardware.screen.portrait'
[11:30:51]: ▸   uses-implied-feature: name='android.hardware.screen.portrait' reason='one or more activities have specified a portrait orientation'
[11:30:51]: ▸   uses-feature: name='android.hardware.wifi'
[11:30:51]: ▸   uses-implied-feature: name='android.hardware.wifi' reason='requested android.permission.ACCESS_WIFI_STATE permission'
[11:30:51]: ▸ main
[11:30:51]: ▸ other-activities
[11:30:51]: ▸ other-receivers
[11:30:51]: ▸ other-services
[11:30:51]: ▸ supports-screens: 'small' 'normal' 'large' 'xlarge'
[11:30:51]: ▸ supports-any-density: 'true'
[11:30:51]: ▸ locales: '--_--' 'af' 'am' 'ar' 'as' 'az' 'be' 'bg' 'bn' 'bs' 'ca' 'cs' 'da' 'de' 'el' 'en-AU' 'en-CA' 'en-GB' 'en-IE' 'en-IN' 'en-XC' 'en-ZZ' 'es' 'es-CL' 'es-CO' 'es-CR' 'es-ES' 'es-MX' 'es-PA' 'es-PE' 'es-US' 'et' 'eu' 'fa' 'fi' 'fr' 'fr-CA' 'gl' 'gu' 'hi' 'hr' 'hu' 'hy' 'in' 'is' 'is-IS' 'it' 'iw' 'ja' 'ka' 'kk' 'km' 'kn' 'ko' 'ky' 'lo' 'lt' 'lv' 'mk' 'ml' 'mn' 'mr' 'ms' 'my' 'nb' 'ne' 'nl' 'no' 'or' 'pa' 'pl' 'pt' 'pt-BR' 'pt-PT' 'ro' 'ru' 'si' 'sk' 'sl' 'sq' 'sr' 'sr-Latn' 'sv' 'sw' 'ta' 'te' 'th' 'tl' 'tr' 'uk' 'ur' 'uz' 'vi' 'zh-CN' 'zh-HK' 'zh-TW' 'zu'
[11:30:51]: ▸ densities: '120' '160' '240' '320' '480' '640' '65534'
[11:30:51]: ▸ native-code: 'arm64-v8a' 'armeabi' 'armeabi-v7a' 'mips' 'mips64' 'x86' 'x86_64'
[11:30:51]: Running tests for locale: en-US
[11:30:51]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell am instrument --no-window-animation -w \
-e testLocale en_US \
-e endingLocale en_US \
-e appendTimestamp true \
-e package com.xxx.screengrab \
com.xxx.debug.test/androidx.test.runner.AndroidJUnitRunner
[11:30:57]: ▸ com.xxx.screengrab.BasicScreenTest:.
[11:30:57]: ▸ Time: 2.788
[11:30:57]: ▸ OK (1 test)
[11:30:57]: Pulling captured screenshots for locale en-US from the device
[11:30:57]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 pull /sdcard/com.xxx.debug/screengrab /var/folders/9w/qkjs37fx0jb6h2jgf78k8nq00000gp/T/d20200219-60338-11jv2r6
ls: /data/data/com.xxx.debug/app_screengrab: Permission denied
[11:30:57]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/en-US/images/screenshots: Permission denied
[11:30:57]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/de-DE/images/screenshots: Permission denied
[11:30:57]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/nl-NL/images/screenshots: Permission denied
[11:30:57]: Exit status: 1
[11:30:57]: Screenshots copied to fastlane/metadata/android/en-US/images/en-US/images/phoneScreenshots
[11:30:57]: Running tests for locale: de-DE
[11:30:57]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell am instrument --no-window-animation -w \
-e testLocale de_DE \
-e endingLocale en_US \
-e appendTimestamp true \
-e package com.xxx.screengrab \
com.xxx.debug.test/androidx.test.runner.AndroidJUnitRunner
[11:31:05]: ▸ com.xxx.screengrab.BasicScreenTest:.
[11:31:05]: ▸ Time: 4.805
[11:31:05]: ▸ OK (1 test)
[11:31:05]: Pulling captured screenshots for locale de-DE from the device
[11:31:06]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 pull /sdcard/com.xxx.debug/screengrab /var/folders/9w/qkjs37fx0jb6h2jgf78k8nq00000gp/T/d20200219-60338-14t7pk7
ls: /data/data/com.xxx.debug/app_screengrab: Permission denied
[11:31:06]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/en-US/images/screenshots: Permission denied
[11:31:06]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/de-DE/images/screenshots: Permission denied
[11:31:06]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/nl-NL/images/screenshots: Permission denied
[11:31:06]: Exit status: 1
[11:31:06]: Screenshots copied to fastlane/metadata/android/de-DE/images/de-DE/images/phoneScreenshots
[11:31:06]: Screenshots copied to fastlane/metadata/android/en-US/images/de-DE/images/phoneScreenshots
[11:31:06]: Running tests for locale: nl-NL
[11:31:06]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 shell am instrument --no-window-animation -w \
-e testLocale nl_NL \
-e endingLocale en_US \
-e appendTimestamp true \
-e package com.xxx.screengrab \
com.xxx.debug.test/androidx.test.runner.AndroidJUnitRunner
[11:31:14]: ▸ com.xxx.screengrab.BasicScreenTest:.
[11:31:14]: ▸ Time: 3.641
[11:31:14]: ▸ OK (1 test)
[11:31:15]: Pulling captured screenshots for locale nl-NL from the device
[11:31:15]: $ /Users/timcastelijns/Library/Android/sdk/platform-tools/adb -s 8B5X140E5 pull /sdcard/com.xxx.debug/screengrab /var/folders/9w/qkjs37fx0jb6h2jgf78k8nq00000gp/T/d20200219-60338-1um9ldk
ls: /data/data/com.xxx.debug/app_screengrab: Permission denied
[11:31:15]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/en-US/images/screenshots: Permission denied
[11:31:15]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/de-DE/images/screenshots: Permission denied
[11:31:15]: Exit status: 1
ls: /data/user/0/com.xxx.debug/files/com.xxx.debug/screengrab/nl-NL/images/screenshots: Permission denied
[11:31:15]: Exit status: 1
[11:31:15]: Screenshots copied to fastlane/metadata/android/de-DE/images/nl-NL/images/phoneScreenshots
[11:31:15]: Screenshots copied to fastlane/metadata/android/nl-NL/images/nl-NL/images/phoneScreenshots
[11:31:15]: Screenshots copied to fastlane/metadata/android/en-US/images/nl-NL/images/phoneScreenshots
[11:31:15]: Generating HTML Report
[11:31:15]: Successfully created HTML file with an overview of all the screenshots: '/Users/timcastelijns/git/xxx/fastlane/metadata/android/screenshots.html'
[11:31:15]: Captured 6 new screenshots! 📷✨</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.2                                     |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.1                          |
| Installation Source         | ~/.rbenv/versions/2.7.0/bin/fastlane        |
| Host                        | Mac OS X 10.15.2 (19C57)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do

    gradle(
      task: 'clean'
    )

    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )

    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )

    copy_artifacts(
      artifacts: ['app/build/outputs/apk/debug/*.apk'],
      target_path: 'app/build/outputs/apk/debug/screengrab/'
    )

    copy_artifacts(
      artifacts: ['app/build/outputs/apk/androidTest/debug/*.apk'],
      target_path: 'app/build/outputs/apk/androidTest/debug/screengrab/'
    )

  end

  desc "Move/rename APKs for Screengrabfile"
  lane :rename_apks do

    sh("find ../app/build/outputs/apk/debug/screengrab -name '*.apk' -exec mv '{}' ../app/build/outputs/apk/debug/screengrab/app.apk \\;")
    sh("find ../app/build/outputs/apk/androidTest/debug/screengrab -name '*.apk' -exec mv '{}' ../app/build/outputs/apk/androidTest/debug/screengrab/app.apk \\;")

  end

  desc "Rebuild APKs and generate screenshots"
  lane :screenshots do

    build_for_screengrab

    #rename_apks

    screengrab

  end

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file("") # Path to the json secret file - Follow https://docs.fastlane.tools/actions/supply/#setup to get one
package_name("com.xxx.debug") # e.g. com.krausefx.app

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.142.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| bundler                   | 2.1.4        |
| uri                       | 0.10.0       |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.4.1        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.72.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.17.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.0.1        |
| signet                    | 0.12.0       |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.25.1       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2020-02-19**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by plastiv**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes https://github.com/fastlane/fastlane/issues/15653#issuecomment-562642978
Fixes #16050

### Description

screengrab companion java library doesn't write to `app_screengrab` folder, but ruby part still tries to read screenshots from there. 

### Testing Steps

https://github.com/fastlane/fastlane/issues/15653#issuecomment-592065897

### CODE REVIEW

**Comment by plastiv** [comment]
@googlebot I signed it!

**Comment by janpio** [comment]
Did this work before?
If so, can you pinpoint when this broke?

**Comment by joshdholtz** [comment]
Ah, weird! I THINK I see what is going on but running on Android tests to see 🤔

File: screengrab/lib/screengrab/runner.rb [hunk 1]
```diff
@@ -146,7 +146,7 @@ def determine_internal_screenshots_paths(app_package_name, locales)
         "/data/user/0/#{app_package_name}/files/#{app_package_name}/screengrab/#{locale}/images/screenshots"
       end
```
Comment (joshdholtz) [inline screengrab/lib/screengrab/runner.rb]:
```suggestion
        [
          "/data/user/0/#{app_package_name}/files/#{app_package_name}/screengrab/#{locale}/images/screenshots",
          
          # https://github.com/fastlane/fastlane/issues/15653#issuecomment-578541663
          "/data/data/#{app_package_name}/files/#{app_package_name}/screengrab/#{locale}/images/screenshots"
        ]
      end.flatten
```

File: screengrab/lib/screengrab/runner.rb [hunk 2]
```diff
@@ -146,7 +146,7 @@ def determine_internal_screenshots_paths(app_package_name, locales)
...
 
-      return ["/data/data/#{app_package_name}/app_screengrab"] + locale_paths
+      return ["/data/data/#{app_package_name}/screengrab"] + locale_paths
```
Comment (joshdholtz) [inline screengrab/lib/screengrab/runner.rb]:
```suggestion
      return ["/data/data/#{app_package_name}/app_screengrab"]+
                  ["/data/data/#{app_package_name}/screengrab"]+
                  locale_paths
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Can we do something like this?! 😊 This should address another comment in that issue about seeing things in `/data/data` and not in `/data/user/0`

**Comment by joshdholtz** [comment]
@plastiv Left some requested changes for you! I tried to make these changes myself and push to this branch but it doesn't look like I have access to do that for some reason 🙃

File: screengrab/lib/screengrab/runner.rb (hunk 1 above)
Comment (plastiv) [reply screengrab/lib/screengrab/runner.rb]: Thank you for you time taking to review my PR!

I have checked suggested changes locally and it seems to me this creates duplicates in resolved path. Since `determine_internal_screenshots_paths` unconditionally is called with array of locales. And test run for second locale resolves both first and second locale paths as valid. Example output from emulator 29;google_apis;x86_64:

```shell
21:15:30]: Running tests for locale: de-DE
[21:15:30]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale de_DE \
-e endingLocale en_US \
-e appendTimestamp true \
-e package screenshot.mocked \
de.flixbus.app.debug.test/de.meinfernbus.internal.FlixAndroidTestRunner
[21:15:59]: ▸ screenshot.mocked.RidesScreenShooter:.
[21:16:03]: ▸ screenshot.mocked.SearchScreenShooter:.
[21:16:07]: ▸ screenshot.mocked.TicketScreenShooter:.
[21:16:07]: ▸ Time: 31.46
[21:16:07]: ▸ OK (3 tests)
[21:16:08]: Pulling captured screenshots for locale de-DE from the device
ls: /sdcard/de.flixbus.app.debug/screengrab: No such file or directory
[21:16:08]: Exit status: 1
ls: /data/data/de.flixbus.app.debug/app_screengrab: No such file or directory
[21:16:08]: Exit status: 1
ls: /data/data/de.flixbus.app.debug/screengrab: No such file or directory
[21:16:08]: Exit status: 1
[21:16:08]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/user/0/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/de-DE/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-o2knv3
[21:16:08]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/data/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/de-DE/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-o2knv3
ls: /data/user/0/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/cs-CZ/images/screenshots: No such file or directory
[21:16:08]: Exit status: 1
ls: /data/data/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/cs-CZ/images/screenshots: No such file or directory
[21:16:08]: Exit status: 1
[21:16:08]: Screenshots copied to screenshots/de-DE/images/phoneScreenshots
[21:16:08]: Running tests for locale: cs-CZ
[21:16:08]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale cs_CZ \
-e endingLocale en_US \
-e appendTimestamp true \
-e package screenshot.mocked \
de.flixbus.app.debug.test/de.meinfernbus.internal.FlixAndroidTestRunner
[21:16:33]: ▸ screenshot.mocked.RidesScreenShooter:.
[21:16:36]: ▸ screenshot.mocked.SearchScreenShooter:.
[21:16:39]: ▸ screenshot.mocked.TicketScreenShooter:.
[21:16:39]: ▸ Time: 16.567
[21:16:39]: ▸ OK (3 tests)
[21:16:39]: Pulling captured screenshots for locale cs-CZ from the device
ls: /sdcard/de.flixbus.app.debug/screengrab: No such file or directory
[21:16:39]: Exit status: 1
ls: /data/data/de.flixbus.app.debug/app_screengrab: No such file or directory
[21:16:40]: Exit status: 1
ls: /data/data/de.flixbus.app.debug/screengrab: No such file or directory
[21:16:40]: Exit status: 1
[21:16:40]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/user/0/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/de-DE/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-7tlqen
[21:16:40]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/data/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/de-DE/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-7tlqen
[21:16:40]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/user/0/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/cs-CZ/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-7tlqen
[21:16:40]: $ /usr/local/share/android-sdk/platform-tools/adb -s emulator-5554 pull /data/data/de.flixbus.app.debug/files/de.flixbus.app.debug/screengrab/cs-CZ/images/screenshots /var/folders/ww/cgv63frx1c5fdzpn183d67wc0000gn/T/d20200303-4970-7tlqen
[21:16:40]: Screenshots copied to screenshots/cs-CZ/images/phoneScreenshots
```
(check last 5 lines. fastlane pulls both de-DE and cs-CZ into screenshots/cs-CZ/images folder)

Comment (joshdholtz) [reply screengrab/lib/screengrab/runner.rb]: Ahhh, this is another issue that we are trying to solve! So this is a good thing you saw this in a way 😊 I'm going to see if I can replicate this on my side 🤔

**Comment by joshdholtz** [comment]
@plastiv Can you add... 

```rb
next unless path.include?(locale)
```

inside of the `pull_screenshots_from_device` method? Like in the following screenshot...

Screen Shot 2020-03-04 at 10 42 08 AM

This should fix it 😊

**Comment by plastiv** [comment]
> @plastiv Can you add...

Thank you for a detail patch description. I have added requested change and checked locally. It seemed to solve my issue with duplicated folders ✅ 

I have just read the suggested [git flow to address patches](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md#after-the-review) after I have rebased already. I will create commit-by-commit separately next time.

**Review by joshdholtz — APPROVED** [review]
@plastiv Thanks so much for making these fixes! Really appreciate it ❤️ Hope to see you back here 😊
