### PR TITLE
Clarify the filename of Feature Graphic

### LINKED ISSUE #11262: 'fastlane supply init' does not create a directory for Google Play Feature Graphic
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When setting up Supply, it's clear where to put phoneScreenshots, sevenInchScreenshots, etc. because the folder names are descriptive.

However, while Supply references copying "your feature graphics into 'metadata/android/en-US/images/', there's no folder for the 1024x500 Feature image, nor an indication of what I might name it.

So, I don't know how to add a Feature Graphic to Fastlane, and I believe the `fastlane supply init` command could use an update to clarify how to do that.

##### Complete output when running fastlane, including the stack trace and command used

```
[16:05:27]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:05:28]: To not be asked about this value, you can specify it using 'json_key'
[16:05:28]: The service account json file used to authenticate with Google:android/fastlane/Google Play Android Developer-a9e51a0eebdb.json
[16:05:47]: To not be asked about this value, you can specify it using 'package_name'
[16:05:47]: The package name of the application to use: com.twominuterevolution.mobile2mr
[16:05:57]: Writing to metadata/en-US/title.txt...
[16:05:57]: Writing to metadata/en-US/short_description.txt...
[16:05:57]: Writing to metadata/en-US/full_description.txt...
[16:05:57]: Writing to metadata/en-US/video.txt...
[16:05:57]: Due to a limitation of the Google Play API, there is no way for `supply` to download your existing screenshots. Please copy your screenshots into `metadata/android/en-US/images/`
[16:05:57]: Due to a limitation of the Google Play API, there is no way for `supply` to download your existing feature graphics. Please copy your feature graphics into `metadata/android/en-US/images/`
[16:05:57]: Downloading icon for en-US...
[16:05:57]: Downloading promoGraphic for en-US...
[16:05:57]: Downloading tvBanner for en-US...
[16:05:58]: Successfully stored metadata in 'metadata'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.70.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.1       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2017-12-18**
</details>

### PR DESCRIPTION
**Pull request by lukewlms**
Currently it's unclear from the warning message where Feature Graphic should actually be saved to.  This change fixes that.

(This fixes https://github.com/fastlane/fastlane/issues/11262.)

(This change assumes Feature Graphic is always a .png - if that's not the case then this needs to be tweaked.)

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

File: supply/lib/supply/setup.rb [hunk 1]
```diff
@@ -44,7 +44,7 @@ def download_images(listing)
       IMAGES_TYPES.each do |image_type|
         if ['featureGraphic'].include?(image_type)
           # we don't get all files in full resolution :(
-          UI.message("Due to a limitation of the Google Play API, there is no way for `supply` to download your existing feature graphics. Please copy your feature graphics into `metadata/android/en-US/images/`")
```
Comment (janpio) [inline supply/lib/supply/setup.rb]: Do you know why it said "graphics" here? This makes me a bit sceptical if the change in error message is such a good idea...

Comment (janpio) [reply supply/lib/supply/setup.rb]: Looked into it.

File: supply/lib/supply/setup.rb [hunk 2]
```diff
@@ -44,7 +44,7 @@ def download_images(listing)
...
+          UI.message("Due to a limitation of the Google Play API, there is no way for `supply` to download your existing feature graphic. Please copy your feature graphic to `metadata/android/en-US/images/featureGraphic.png`")
```
Comment (janpio) [inline supply/lib/supply/setup.rb]: The `en-US` only matches sometimes here and should probably be dynamified in a future PR, right?

**Comment by lukewlms** [comment]
@googlebot I signed it

File: supply/lib/supply/setup.rb (hunk 2 above)
Comment (lukewlms) [reply supply/lib/supply/setup.rb]: Seems like yes - though I think it's fairly clear that if I have other supported lang then I'd put it in a different folder.

File: supply/lib/supply/setup.rb (hunk 1 above)
Comment (lukewlms) [reply supply/lib/supply/setup.rb]: @janpio  Also, I shortened to 'graphic' because the Play Store only allows one graphic to be active.

image

Comment (janpio) [reply supply/lib/supply/setup.rb]: Ah, maybe because it is available in every language?

**Review by janpio — APPROVED** [review]

File: supply/lib/supply/setup.rb (hunk 2 above)
Comment (janpio) [reply supply/lib/supply/setup.rb]: Oh, I wrote an issue about that in the past: https://github.com/fastlane/fastlane/issues/9962 ;)
