### PR TITLE
[action] fix app_store_build_number and latest_testflight_build_number when no version given

### LINKED ISSUE #14845: undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x00007fb398a54670> (NoMethodError)
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.125.0`
- Last working version: not sure

### Regression Description

`latest_testflight_build_number` has stopped working. Throws this:

```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:47:in `get_build_number': [!] undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x00007fb398a54670> (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:11:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:11:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
Exited with code 1
```

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #14845 on more time 😊

### Description
- Need to support when `live:false` and `version: nil`
- Cleaned code up a bit to make it easier to follow with early and explicit returns
- Clearer `UI` messages when version is specified and when nil

#### Example
```
[15:18:39]: --------------------------------------------
[15:18:39]: --- Step: latest_testflight_build_number ---
[15:18:39]: --------------------------------------------
[15:18:40]: Login to App Store Connect (me@joshholtz.com)
[15:18:47]: Login successful
[15:18:48]: Fetching the latest build number for any version
[15:18:49]: Latest upload for version 1.1 is build: 259
[15:18:49]: any version value: 259
[15:18:49]: --------------------------------------------
[15:18:49]: --- Step: latest_testflight_build_number ---
[15:18:49]: --------------------------------------------
[15:18:49]: Login to App Store Connect (me@joshholtz.com)
[15:18:51]: Login successful
[15:18:52]: Fetching the latest build number for version 1.1
[15:18:52]: Latest upload for version 1.1 is build: 259
[15:18:52]: version 1.1 value: 259
[15:18:52]: --------------------------------------------
[15:18:52]: --- Step: latest_testflight_build_number ---
[15:18:52]: --------------------------------------------
[15:18:52]: Login to App Store Connect (me@joshholtz.com)
[15:18:54]: Login successful
[15:18:55]: Fetching the latest build number for version 1.4
[15:18:55]: Latest upload for version 1.4 is build: 230
[15:18:55]: version 1.4 value: 230
```

### CODE REVIEW

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 1]
```diff
@@ -32,36 +32,42 @@ def self.get_build_number(params)
...
           version_number = params[:version]
 
-          # Get version number from latest pre-release if no version number given
+          # Used for determining how to display the optional version number
+          version_number_message = version_number.nil? ? "any version" : "version #{version_number}"
+
+          # Create filter for get_builds with optional version number
+          filter = { app: app.apple_id }
           if version_number
-            UI.message("Fetching the latest build number for version #{version_number}")
```
Comment (snatchev) [inline fastlane/lib/fastlane/actions/app_store_build_number.rb]: we have two checks for `version_number.nil?` (here and line 41) could we consolidate?

**Review by minuscorp — APPROVED** [review]
🚀

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 2]
```diff
@@ -32,36 +32,42 @@ def self.get_build_number(params)
...
+
+          UI.message("Fetching the latest build number for #{version_number_message}")
+
+          # Get latest build for optional version number and return build number if found
+          client = Spaceship::ConnectAPI::Base.client
+          build = client.get_builds(filter: filter, sort: "-version", includes: "preReleaseVersion", limit: 1).first
+          if build
+            build_nr = build.version
+            UI.message("Latest upload for version #{build.app_version} is build: #{build_nr}")
+            return build_nr
```
Comment (snatchev) [inline fastlane/lib/fastlane/actions/app_store_build_number.rb]: This lookup feels like it could be moved into a little private method. It seems useful and self-contained.

**Review by snatchev — APPROVED** [review]
LGTM, with some optional suggestions.
