### PR TITLE
[frameit] Add double quotes to path in StringParser.encoding_type

### LINKED ISSUE #14451: Frameit is not correctly detecting title.strings and keyword.strings
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'd liek to generate framed screenshots for my app. Everything works almost correctly. However FrameIt is not able to read title.strings and keywords.strings. I get the following error message:

`Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded`

Both files are correctly encoded in UTF-16BE. I did some digging and I think the issues is with function encoding_type in StringsParser. It **does not correctly escape the path** if there are **spaces** present. Therefore the returned value is actually an error message about file not found. This leads to not detecting correct encoding and it fallbacks to calling iconv, which in the end returns empty content.

I will be happy to make a PR to fix this ;)

Edit: I already made a PR for this issue ;)

##### Command executed

bundle exec fastlane frameit --verbose

##### Complete output when running fastlane, including the stack trace and command used

```
[✔] 🚀
INFO [2019-03-22 12:25:41.25]: Using device frames version 'latest'
DEBUG [2019-03-22 12:25:41.25]: Parsing config file '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/Framefile.json'
ERROR [2019-03-22 12:25:41.26]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:41.26]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠋] Framing screenshot './iPhone 8-0Launch.png' DEBUG [2019-03-22 12:25:41.27]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠦] Framing screenshot './iPhone 8-0Launch.png' ERROR [2019-03-22 12:25:41.97]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/keyword.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:41.97]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
[⠧] Framing screenshot './iPhone 8-0Launch.png' ERROR [2019-03-22 12:25:41.97]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:41.98]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠋] Framing screenshot './iPhone 8-0Launch.png' ERROR [2019-03-22 12:25:42.31]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:42.31]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
DEBUG [2019-03-22 12:25:42.31]: Using /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/./fonts/sf-ui-display-medium.otf as font the title of ./iPhone 8-0Launch.png
DEBUG [2019-03-22 12:25:42.31]: Adding text 'Default title'
[✔] Framing screenshot './iPhone 8-0Launch.png'
INFO [2019-03-22 12:25:44.79]: Added frame: '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/iPhone 8-0Launch_framed.png'
DEBUG [2019-03-22 12:25:44.79]: Parsing config file '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/Framefile.json'
ERROR [2019-03-22 12:25:44.80]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:44.80]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠋] Framing screenshot './iPhone X-0Launch.png' DEBUG [2019-03-22 12:25:44.81]: Looking for Apple iPhone XS Space Gray and found 1 template(s)
[⠸] Framing screenshot './iPhone X-0Launch.png' ERROR [2019-03-22 12:25:46.23]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/keyword.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:46.23]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
[⠼] Framing screenshot './iPhone X-0Launch.png' ERROR [2019-03-22 12:25:46.25]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:46.25]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠸] Framing screenshot './iPhone X-0Launch.png' ERROR [2019-03-22 12:25:47.17]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:47.17]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
DEBUG [2019-03-22 12:25:47.17]: Using /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/./fonts/sf-ui-display-medium.otf as font the title of ./iPhone X-0Launch.png
DEBUG [2019-03-22 12:25:47.17]: Adding text 'Default title'
[✔] Framing screenshot './iPhone X-0Launch.png'
INFO [2019-03-22 12:25:52.54]: Added frame: '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/iPhone X-0Launch_framed.png'
DEBUG [2019-03-22 12:25:52.54]: Parsing config file '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/Framefile.json'
ERROR [2019-03-22 12:25:52.55]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:52.55]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠋] Framing screenshot './iPad Pro (12.9-inch)-0Launch.png' DEBUG [2019-03-22 12:25:52.56]: Looking for Apple iPad Pro Space Gray and found 1 template(s)
[⠏] Framing screenshot './iPad Pro (12.9-inch)-0Launch.png' ERROR [2019-03-22 12:25:54.52]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/keyword.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:54.52]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
ERROR [2019-03-22 12:25:54.53]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:54.53]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
[⠇] Framing screenshot './iPad Pro (12.9-inch)-0Launch.png' ERROR [2019-03-22 12:25:56.44]: Empty parsing result for /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/title.strings. Please make sure the file is valid and UTF16 Big-endian encoded
DEBUG [2019-03-22 12:25:56.44]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
DEBUG [2019-03-22 12:25:56.44]: Using /Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/./fonts/sf-ui-display-medium.otf as font the title of ./iPad Pro (12.9-inch)-0Launch.png
DEBUG [2019-03-22 12:25:56.44]: Adding text 'Default title'
[✔] Framing screenshot './iPad Pro (12.9-inch)-0Launch.png'
INFO [2019-03-22 12:26:06.93]: Added frame: '/Users/kacper/workspace/one_second_videos/One Second Videos/fastlane/screenshots/en-US/iPad Pro (12.9-inch)-0Launch_framed.png'

### PR DESCRIPTION
**Pull request by kacperd**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
It fixes #14451

### Description
I added double quotes in StringParser.encoding_type to enable proper encoding detection from files which contain spaces in their file paths.

### CODE REVIEW

**Comment by kacperd** [comment]
I signed it!

File: frameit/lib/frameit/strings_parser.rb [hunk 1]
```diff
@@ -40,7 +40,7 @@ def self.parse(path)
     end
 
     def self.encoding_type(path)
-      `file --mime-encoding #{path}`.downcase
+      `file --mime-encoding "#{path}"`.downcase
```
Comment (janpio) [inline frameit/lib/frameit/strings_parser.rb]: A better way to achieve this in a cross platform way would be to use `.shellescape` on the string: http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html#method-c-shellescape This is also how the rest of fastlane makes path shell safe.

**Review by janpio — CHANGES_REQUESTED** [review]
Let's use `.shellescape`

**Review by joshdholtz — APPROVED** [review]
@kacperd Thanks for finding this! ❤️
