### PR TITLE
[fastlane] warn user during load_plugins when failure to find action

### LINKED ISSUE #15: [0.1.4] No actions found in Plugin version.
Hi! Looks like when installing plugins, no actions are found in the latest version (0.1.4 at the time of writing) of `firebase_app_distribution`.

Fixing version to `0.1.2`:

image

With version `0.1.4`:

image

### LINKED ISSUE #15506: `firebase_app_distribution` plugin doesn't work in macOS Catalina
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'd like to try to use `firebase_app_distribution` plugin with Fastlane.
So I executed `fastlane add_plugin firebase_app_distribution` and use with `fastlane firebase_app_distribution` command.
But, failed with error.

##### Command executed

```sh
fastlane add_plugin firebase_app_distribution
[✔] 🚀 
[11:11:34]: fastlane detected a Gemfile in the current directory
[11:11:34]: however it seems like you don't use `bundle exec`
[11:11:34]: to launch fastlane faster, please use
[11:11:34]: 
[11:11:34]: $ bundle exec fastlane add_plugin firebase_app_distribution
[11:11:34]: 
[11:11:34]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:11:35]: Plugin 'fastlane-plugin-firebase_app_distribution' was added to './fastlane/Pluginfile'
[11:11:35]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
Installing plugin dependencies...
Successfully installed plugins
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
fastlane firebase_app_distribution
[✔] 🚀 
[11:12:46]: fastlane detected a Gemfile in the current directory
[11:12:46]: however it seems like you don't use `bundle exec`
[11:12:46]: to launch fastlane faster, please use
[11:12:46]: 
[11:12:46]: $ bundle exec fastlane firebase_app_distribution
[11:12:46]: 
[11:12:46]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:12:47]: Error loading plugin 'fastlane-plugin-firebase_app_distribution': cannot load such file -- fastlane/plugin/firebase_app_distribution
[11:12:47]: It seems like you wanted to load some plugins, however they couldn't be loaded
[11:12:47]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-------------------------------------------+-----------+------------------+
|                               Used plugins                               |
+-------------------------------------------+-----------+------------------+
| Plugin                                    | Version   | Action           |
+-------------------------------------------+-----------+------------------+
| fastlane-plugin-firebase_app_distribution | undefined | No actions found |
+-------------------------------------------+-----------+------------------+
[11:12:47]: ----------------------------------------
[11:12:47]: --- Step: Verifying fastlane version ---
[11:12:47]: ----------------------------------------
[11:12:47]: Your fastlane version 2.134.0 matches the minimum requirement of 2.119.0  ✅
[11:12:47]: ------------------------------
[11:12:47]: --- Step: default_platform ---
[11:12:47]: ------------------------------
+------------------+-----+
|      Lane Context      |
+------------------+-----+
| DEFAULT_PLATFORM | ios |
+------------------+-----+
[11:12:47]: Could not find lane 'ios firebase_app_distribution'. Available lanes: ios version, ios deploy, ios test, ios beta, ios release, ios dsyms
+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
+------+----------------------------+-------------+
Looking for related GitHub issues on fastlane/fastlane...
➡️  Malformed version number string undefined
    https://github.com/fastlane/fastlane/issues/14663 [closed] 1 💬
    23 Jun 2019
➡️  Sign in with the app-specific password you generated
    https://github.com/fastlane/fastlane/issues/7380 [closed] 5 💬
    22 Aug 2017
🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
    20: from /usr/local/bin/fastlane:23:in `<main>'
    19: from /usr/local/bin/fastlane:23:in `load'
    18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
    17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
    16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
    15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
    14: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
    13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
    12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
    11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
    10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
     9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
     8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
     7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:76:in `cruise_lane'
     6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager_base.rb:20:in `finish_fastlane'
     5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
     4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
     3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
     2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
     1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize': Malformed version number string undefined (ArgumentError)
    20: from /usr/local/bin/fastlane:23:in `<main>'
    19: from /usr/local/bin/fastlane:23:in `load'
    18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
    17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
    16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
    15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
    14: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
    13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
    12: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
    11: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
    10: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
     9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
     8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
     7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:76:in `cruise_lane'
     6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager_base.rb:20:in `finish_fastlane'
     5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
     4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
     3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
     2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
     1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize': [!] Malformed version number string undefined (ArgumentError)
    11: from /usr/local/bin/fastlane:23:in `<main>'
    10: from /usr/local/bin/fastlane:23:in `load'
     9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
     8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
     7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:53:in `start'
     6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:43:in `ensure in start'
     5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `show_update_status'
     4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:26:in `each'
     3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:29:in `block in show_update_status'
     2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
     1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:203:in `new'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/version.rb:212:in `initialize': Malformed version number string undefined (ArgumentError)

  </pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15                                                          |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15 (19A583)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.0                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.119.0"

appVersion = "3.0.0"
xcodeproj = "Type.xcodeproj"
buildNumber = `git log --oneline | wc -l`.strip


default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    #carthage
  end

  lane :version do |options|
    version_number = options[:version] || appVersion
    increment_version_number(version_number: version_number, xcodeproj: xcodeproj)
    increment_build_number(build_number: buildNumber, xcodeproj: xcodeproj)
  end

  lane :deploy do |options|
    commit_message = `git log --format=%B -n 1 HEAD`.strip
    ipa_path = options[:ipa_path]
    app_id = options[:app_id] || "1:22804013810:ios:ee16d150e1ffecd2"
    groups = options[:groups] || "開発者"
    firebase_cli_path = options[:firebase_cli_path] || "/usr/local/lib/node_modules/firebase-tools/lib/bin/firebase.js"

    firebase_app_distribution(
        app: app_id,
        groups: groups,
        release_notes: commit_message,
        ipa_path: ipa_path,
        firebase_cli_path: firebase_cli_path
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Type") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    # gym(scheme: "Type") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  lane :dsyms do |options|
    version_number = options[:version] || get_info_plist_value(path: 'Type/Info.plist', key: "CFBundleShortVersionString")
    app_identifier = "me.fromkk.Type"
    download_dsyms(
      version: version_number,
      app_identifier: app_identifier
    )
    upload_symbols_to_crashlytics(
      gsp_path: "Type/Resources/GoogleService-Info.plist"
    )
    clean_build_artifacts
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "me.fromkk.Type" # The bundle identifier of your app
apple_id "iueokakkun@gmail.com" # Your Apple email address

team_id "K84E4S7G4C" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.134.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-badge | 1.3.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.12.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.1        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.67.0       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 0.17.0       |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 2.0.2        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.6        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.3          |
| memoist                   | 0.16.0       |
| os                        | 1.0.1        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.1        |
| json                      | 2.2.0        |
| mime-types-data           | 3.2019.1009  |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| google-cloud-env          | 1.2.1        |
| google-cloud-core         | 1.3.2        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| curb                      | 0.9.10       |
| badge                     | 0.11.0       |
| fastlane-plugin-badge     | 1.3.0        |
</details>

*generated on:* **2019-10-16**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes https://github.com/fastlane/fastlane/issues/15506
Fixes https://github.com/fastlane-community/fastlane-plugin-firebase_app_distribution/issues/15

And bonus fix for failing CI with https://github.com/Homebrew/brew/issues/6112#issuecomment-520950707

### Motivation and Context
Give users some more help when plugins fail to load without an actions

### Description
- Add a message with a link to new doc that also explains
- Also added a new optional parameter onto `load_plugins` to prevent the setting of `ENV["FASTLANE_ENV_PRINTER"]` which was causing test failures due to the environment variables never being cleared out

Screen Shot 2019-10-22 at 2 54 43 PM

### CODE REVIEW

File: fastlane/lib/fastlane/environment_printer.rb [hunk 1]
```diff
@@ -50,11 +50,11 @@ def self.print_date
     end
 
     def self.print_loaded_plugins
-      ENV["FASTLANE_ENV_PRINTER"] = "enabled"
```
Comment (snatchev) [inline fastlane/lib/fastlane/environment_printer.rb]: Is this env var now deprecated / unused?

**Review by snatchev — APPROVED** [review]
LGTM. Just 1 question about the env var. If its deprecated, isn't there a env var registry somewhere we need to update as well?

File: fastlane/lib/fastlane/environment_printer.rb (hunk 1 above)
Comment (joshdholtz) [reply fastlane/lib/fastlane/environment_printer.rb]: This ENV var wasn't used by anything external at all 😬 Its only use being used as a parameter of sorts 😔
