### PR TITLE
Preventing actions called from another action to show in summary

### LINKED ISSUE #4546: Incorrect time in summary when using other_action
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When calling an action from another action using `other_action` (https://github.com/fastlane/fastlane/pull/4441), the inner action shows in the summary, in a way that you'd think that it took the time of the inner action + the action itself (see example).

I see two ways of solving it:
1. Don't show actions called from another action in the summary. When an action needs to call another, that's an implementation detail and the user of the action shouldn't need to know about it.
2. Change the summary to allow nested levels of actions. Something like this:

```
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods_if_needed                 | 62          |
|      |    > cocoapods                      | 51          |
+------+-------------------------------------+-------------+
```

However this could become ugly, as you could have several levels of actions calling others (although not usual).

I think option 1 is the way to go.
##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane pod_install

...
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods                           | 51          |
| 8    | cocoapods_if_needed                 | 62          |
+------+-------------------------------------+-------------+
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
fastlane_version "1.86.1"

default_platform :ios

platform :ios do
  desc "Runs pod install if needed"
  lane :pod_install do
    cocoapods_if_needed
  end
end
```

`cocoapods_if_needed.rb`:

``` ruby
module Fastlane
  module Actions
    class CocoapodsIfNeededAction < Action

      def self.needs_to_run_pod_install
        begin
          !FileUtils.compare_file('Podfile.lock', 'Pods/Manifest.lock')
        rescue  Exception => e
          true
        end
      end

      def self.run(params)
        if needs_to_run_pod_install
          sh 'bundle exec pod repo update'

          other_action.cocoapods
        else
          UI.message "🍫  Skipping pod install because Pods seems updated".blue
        end
      end

      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
        "Runs pod repo update and pod install if needed"
      end

      def self.details
        "Checks if the sandbox is in sync with the Podfile.lock. If not, runs pod repo " \
        "update and then pod install"
      end

      def self.available_options
        []
      end

      def self.authors
        ["marcelofabri"]
      end

      def self.is_supported?(platform)
        true
      end
    end
  end
end
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.86.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yep

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

### PR DESCRIPTION
**Pull request by marcelofabri**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [x] Run `rspec` for all tools you modified
- [x] Run `rubocop -a` to ensure the code style is valid
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

This should fix #4546. We probably should add at least a test to make sure we don't have regressions on this, but just wanted to see it the implementation makes sense first.

Just to make clear, this hides the "inner actions" from the summary:

```
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods_if_needed                 | 98          |
+------+-------------------------------------+-------------+
```

You can compare to the behavior before this PR below:

```
$ fastlane pod_install

...
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods                           | 51          |
| 8    | cocoapods_if_needed                 | 62          |
+------+-------------------------------------+-------------+
```

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @marcelofabri, sorry for the late reply on this, and thanks for your pull request. I don't think we can merge the pull request as it is now. We'd need some more documentation in the code, and also tests covering this change. 
Is that something you could do?

**Comment by marcelofabri** [comment]
No worries! Where exactly do you want to see more docs? In `trigger_action_by_name` header?

Also, can you point me to where this is being tested or how could I add tests for this? (Since it needs to capture the summary output)

**Comment by ohwutup** [comment]
Hey @marcelofabri - Apologies for the delay here- I think a good place to write a test for this would be in `fastlane_runner_spec.rb`. And Regarding adding more docs to the code, I think if you put a little comment above `trigger_action_by_name`'s definition about what the `from_action` param is doing, it might be helpful. Thanks! 🐙

**Comment by marcelofabri** [comment]
@ohwutup I've rebased this and added a comment in the header, but I'm still having trouble on how to test this without mocking the whole stack. Are there any integration tests? Maybe this would  be better tested in that way.

**Comment by marcelofabri** [comment]
@ohwutup So, I took another look and found `action_spec`. I was able to add tests there in e4ff4d6a. I'm not sure if it's the best approach, but the new tests do fail without 52bfe29 and pass with it. 🎉

File: fastlane/lib/fastlane/runner.rb [hunk 1]
```diff
@@ -109,7 +109,9 @@ def find_alias(action_name)
 
     # This is being called from `method_missing` from the Fastfile
     # It's also used when an action is called from another action
-    def trigger_action_by_name(method_sym, custom_dir, *arguments)
+    # @param from_action Indicates if this action is being trigged by another action.
+    #                    If so, it won't show up in summary.
+    def trigger_action_by_name(method_sym, custom_dir, from_action, *arguments)
```
Comment (milch) [inline fastlane/lib/fastlane/runner.rb]: In the past we've had trouble with adding parameters to existing functions breaking people's setups, so could you give this a default value please? e.g. `def trigger_action_by_name(method_sym, custom_dir, from_action: false, *arguments)`

**Review by milch — CHANGES_REQUESTED** [review]

File: fastlane/lib/fastlane/runner.rb (hunk 1 above)
Comment (marcelofabri) [inline fastlane/lib/fastlane/runner.rb]: Sure, although I'd say that this method shouldn't really be called by end users 😅

Comment (marcelofabri) [inline fastlane/lib/fastlane/runner.rb]: Actually, it seems that this is not valid syntax because of the `*arguments` later 😬

Comment (milch) [inline fastlane/lib/fastlane/runner.rb]: > Sure, although I'd say that this method shouldn't really be called by end users 😅

That's never stopped someone from doing things before 😉 

> Actually, it seems that this is not valid syntax because of the *arguments later 😬

Damn, you're right. I just double checked that you changed all occurences of trigger_action_by_name, so we should be good.

**Review by milch — APPROVED** [review]
