### PR TITLE
[supply] Fix #28995 and `release_status` vs `rollout` parameters

### LINKED ISSUE #28995: Fastlane Error on Rollout command : Google Api Error: Invalid request - Only one completed release is allowed.
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [✅ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [✅ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [✅ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I have updated by today (Dec, 11th 2024) the Fastlane version to 2.26.0, my script for rolling out my apps was not changes since a year ago, but after updating it was return this error :

```
fastlane finished with errors
[!] Google Api Error: Invalid request - Only one completed release is allowed.
[08:07:25]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
```

My app was not on Fully rollout/released yet (still staged at 30p) 
somehow it pointed out the error on fastfile as per image below, but i have not any code changes since a year ago, the script is also still working yesterday.
Screenshot 2024-12-11 at 16 50 23

so then, after debugging by couple of hours, i tried revert back / downgrade to Fastlane 2.25.0, and my script was working normally!

Screenshot 2024-12-11 at 16 56 16

##### Command executed

here is the command that i execute : 
`$ bundle exec --gemfile=$CI_PROJECT_DIR/fastlane/Gemfile fastlane prod_rollout rollout:"0.60"`

##### Complete output when running fastlane, including the stack trace and command used
As mentioned above
`$ bundle exec --gemfile=$CI_PROJECT_DIR/fastlane/Gemfile fastlane prod_rollout rollout:"0.60"`

```[07:57:41]: Called from Fastfile at line 25
[07:57:41]: 
[07:57:41]:     23:	  lane :prod_rollout do |options|
[07:57:41]:     24:	    rollout = options[:rollout].to_s
[07:57:41]:  => 25:	    supply(track: 'production', rollout: rollout, skip_upload_aab: 'true',  skip_upload_apk: 'true')
[07:57:41]:     26:	  end
[07:57:41]:     27:	
[07:57:41]: 
[07:57:41]: Google Api Error: Invalid request - Only one completed release is allowed.
```

[!] Google Api Error: Invalid request - Only one completed release is allowed.
[08:07:25]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 15.1.1                                      |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.5 (Apple Git-154)          |
| Installation Source         | ~/.rbenv/versions/3.1.2/bin/fastlane        |
| Host                        | macOS 15.1.1 (24B91)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.2/lib                 |
| OpenSSL Version             | OpenSSL 3.2.0 23 Nov 2023                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 16.1                                        |
| Swift Version               | 6.0.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Version Production"
  lane :version_prod do
    google_play_track_release_names(track: 'production')
  end

  desc "Update Beta rollout"
  lane :prod_rollout do |options|
    rollout = options[:rollout].to_s
    supply(track: 'production', rollout: rollout, skip_upload_aab: 'true',  skip_upload_apk: 'true')
  end


end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple Developer Portal username


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

json_key_file("fastlane/credentials.json")
package_name("com.gojek.resto")
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.226.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-cookie_jar              | 0.0.7        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| digest-crc                      | 0.6.5        |
| google-cloud-storage            | 1.47.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.0        |
| set                             | 1.0.2        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.10.1       |
| aws-partitions                  | 1.1000.0     |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.211.0      |
| aws-sdk-kms                     | 1.95.0       |
| aws-sdk-s3                      | 1.169.0      |
| bundler                         | 2.3.7        |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| rexml                           | 3.3.9        |
| CFPropertyList                  | 3.0.7        |
| excon                           | 0.112.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.2        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.7        |
| fastimage                       | 2.3.1        |
| jwt                             | 2.9.3        |
| signet                          | 0.19.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| rake                            | 13.2.1       |
| json                            | 2.7.5        |
| mini_magick                     | 4.13.2       |
| optparse                        | 0.5.0        |
| plist                           | 3.7.1        |
| unicode-display_width           | 2.6.0        |
| nanaimo                         | 0.4.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.27.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.6.2        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.4.1        |
| timeout                         | 0.2.0        |
| stringio                        | 3.1.2        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.8.0        |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| ostruct                         | 0.5.2        |
| yaml                            | 0.2.0        |
| psych                           | 5.2.1        |
</details>

*generated on:* **2024-12-12**
</details>

### PR DESCRIPTION
**Pull request by AliSoftware**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] ~~I've updated the documentation if necessary.~~
- [x] I've added or updated relevant unit tests.

### Motivation and Context

After I introduced [this change](https://github.com/fastlane/fastlane/pull/28960/files#diff-97356a4e0e18355c574a489a006bb0caccb0bfe74f62a6fca7fbce037b4f67a2R138-R142) to _supply_ in `2.226.0`, this broke the behavior for some users in https://github.com/fastlane/fastlane/issues/28995.

This is because when they provided a `rollout:` parameter with an <1.0 value, but didn't provide an explicit `release_status:` parameter (and it thus defaulted to `'completed'`), the new implementation made the API call with `release_status: 'completed', user_fraction: rollout` instead of using `inProgress` implicitly for rollout values <1.0

<details><summary>The before/after and history of past implementations</summary>
Before https://github.com/fastlane/fastlane/issues/28995, it was ok to not change the `release.status` of the existing track and status that was fetched by the API to be modified by `#update_rollout`, because before that PR we only fetched releases that were in `inProgress` state, so we were guaranteed that the `status` property of those `release` objects we got back already had the `release.status = 'inProgress'`, and all the old implementation was doing was thus to update that `release.status` to `'completed'` only if a value of `rollout: '1.0'` was provided, leaving the value unchanged to `'inProgress'` otherwise.

But after https://github.com/fastlane/fastlane/issues/28995 landed, the `release` objects we got back from the API could be either `inProgress` or `draft`. This is why that part of the implementation / logic was changed to make sure the provided value for the `release_status` parameter was applied, so that it could be changed from `draft` to `inProgress` and vice-versa too if that's what the caller explicitly asked. But that implementation failed to account for the fact that the `release_status` parameter (`ConfigItem`) of _supply_ had a default value of `'completed'` which means that if the user didn't provide a `release_status` parameter explicitly, the new code would attempt to set it to `'completed'` even if `rollout:` was provided with a <1.0 value.
</details>

### Description

This new implementation was written by writing the Unit Tests (rspecs) first, to write down all the possible use cases that we could encounter with regards to combinations of `release_status`/`rollout` parameter pairs and write down the expectation we have for each of those cases. Then I adjusted the implementation to make sure those tests passed (TDD FTW!)

Here's the various use cases covered by the unit tests and the behavior we implemented:

| `rollout` parameter | `release_status` parameter | `user_fraction` sent to API[^1] | `release.status` sent to API |
|-------------------|---------------------------|-------------------------|-------------------------|
| `nil` | `DRAFT` | `nil` | `DRAFT` |
| `nil` | `IN_PROGRESS` | - | Error: "You need to provide a rollout value when release_status is set to 'inProgress'" |
| `nil` | `COMPLETED` | `nil` | `COMPLETED` |
| `0.5` | `DRAFT` | `nil`[^1] | `DRAFT` |
| `0.5` | `IN_PROGRESS` | `0.5` | `IN_PROGRESS` |
| `0.5` | `COMPLETED` | `0.5` | `IN_PROGRESS`[^2] |
| `1.0` | `DRAFT` | `nil`[^1] | `DRAFT` |
| `1.0` | `IN_PROGRESS` | `nil`[^1] | `COMPLETED`[^3] |
| `1.0` | `COMPLETED` | `nil`[^1] | `COMPLETED` |

[^1]: [The `user_fraction` parameter is only expected by the API if `status` is `inProgress` or `halted`](https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/AndroidpublisherV3/TrackRelease.html#user_fraction-instance_method)
[^2]: We intentionally force the status sent to the API to be `'inProgress'` even if the user called the action with `'completed'`, because the `rollout` parameter was explicitly passed with value `1.0`
[^3]: We intentionally force the status sent to the API to be `'completed'` even if the user called the action with `'inProgress'`, because the `rollout` parameter was explicitly passed but with a value <1.0

### Testing Steps

 - Point your `Gemfile` to the branch of this PR
 - Call `upload_to_play_store` in your `Fastfile` with the usual parameters you'd call it with, but testing the different use cases provided in the table above for `rollout` and `release_status`

In particular, it'd be nice if some of you could test those calls while your tracks in Google Play are in different states, like the track already containing a release but being in draft, or a track containing a release which has started rollout but not at 100% yet, multiple releases in draft in the same track, …

---

cc @Noorrama @sreejithbnaick @lberaldodev @GiebelGobbler @mcfarljw — who chimed in on the original issue #28995

### CODE REVIEW

File: supply/spec/uploader_spec.rb [hunk 1]
```diff
@@ -453,5 +453,152 @@ def ==(other)
...
+        end
+
+        context 'when release_status is IN_PROGRESS' do
+          include_examples 'updates track with correct status and rollout',
+            rollout: 1.0,
+            release_status: Supply::ReleaseStatus::IN_PROGRESS,
+            # We want to ensure the implementation forces status of COMPLETED when explicit rollout = 1.0 is provided
+            expected_status: Supply::ReleaseStatus::COMPLETED,
+            expected_user_fraction: nil
+        end
```
Comment (AliSoftware) [inline supply/spec/uploader_spec.rb:572]: This should cover the case / request from @mcfarljw in https://github.com/fastlane/fastlane/issues/28995#issuecomment-2703668199

File: supply/spec/uploader_spec.rb [hunk 2]
```diff
@@ -453,5 +453,152 @@ def ==(other)
...
+
+        context 'when release_status is COMPLETED' do
+          include_examples 'updates track with correct status and rollout',
+            rollout: 0.5,
+            release_status: Supply::ReleaseStatus::COMPLETED,
+            # We want to ensure the implementation forces status of IN_PROGRESS when explicit rollout < 1.0 is provided
+            expected_status: Supply::ReleaseStatus::IN_PROGRESS,
+            expected_user_fraction: 0.5
+        end
```
Comment (AliSoftware) [inline supply/spec/uploader_spec.rb:553]: This is the particular case reported in #28995 we want to fix

File: supply/spec/uploader_spec.rb [hunk 3]
```diff
@@ -453,5 +453,152 @@ def ==(other)
...
+      end
+
+      context 'when rollout is 0.5' do
+        context 'when release_status is DRAFT' do
+          include_examples 'updates track with correct status and rollout',
+            rollout: 0.5,
+            release_status: Supply::ReleaseStatus::DRAFT,
+            expected_status: Supply::ReleaseStatus::DRAFT,
+            expected_user_fraction: 0.5
+        end
```
Comment (AliSoftware) [inline supply/spec/uploader_spec.rb:536]: Tbh I'm actually not sure this is valid. Does Google Play allow you to set a rollout value to a release that is in Draft state? (e.g. so that when you turn that draft into an actual release by setting its status to `inProgress` later, it'd use that rollout value previously set)?

if anyone knows, or has some opportunity to test with a real-life example, I'm interested.

**Review by mollyIV — APPROVED** [review]
TDD FTW! 🚀
