### PR TITLE
Fix scan default_device_ios

### LINKED ISSUE #5638: Scan selects invalid simulator ID
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Scan fails to select the correct device and errors.

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+------------------------+
|            Summary for scan 0.10.1             |
+-----------------------+------------------------+
| scheme                | z                  |
| device                | iPhone 6               |
| workspace             | z.xcworkspace      |
| clean                 | false                  |
| code_coverage         | false                  |
| address_sanitizer     | false                  |
| skip_build            | false                  |
| output_directory      | ./fastlane/test_output |
| output_types          | html,junit             |
| buildlog_path         | ~/Library/Logs/scan    |
| open_report           | false                  |
| skip_slack            | false                  |
| slack_only_on_failure | false                  |
| use_clang_report_name | false                  |
+-----------------------+------------------------+

[10:06:31]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace z.xcworkspace -scheme z -destination 'platform=iOS Simulator,id=25F884E6-2F44-4FBA-AF71-F3E86B45E5A2' build test | tee '/Users/vagrant/Library/Logs/scan/z-z.log' | xcpretty 
[10:06:31]: ▸ Loading...
[10:06:33]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[10:06:33]: ▸ { platform:iOS Simulator, id:25F884E6-2F44-4FBA-AF71-F3E86B45E5A2 }
[10:06:33]: ▸ Available destinations for the "z" scheme:
[10:06:33]: ▸ { platform:iOS Simulator, id:92D5F36B-0C20-4A28-ACAC-C8B1BDF2D5D1, OS:9.3, name:iPad 2 }
[10:06:33]: ▸ { platform:iOS Simulator, id:269BE30E-3F3F-4088-AD29-E1B063BE1BF7, OS:9.3, name:iPad Air }
[10:06:33]: ▸ { platform:iOS Simulator, id:C7079943-86D1-45B5-A2DC-DCCC9BB3CF1B, OS:9.3, name:iPad Air 2 }
[10:06:33]: ▸ { platform:iOS Simulator, id:7A5DA408-3CAA-4286-B966-3CC5624F23A7, OS:9.3, name:iPad Pro }
[10:06:33]: ▸ { platform:iOS Simulator, id:396800A2-AE9D-4978-8FBD-00B9B9F98088, OS:9.3, name:iPad Retina }
[10:06:33]: ▸ { platform:iOS Simulator, id:39C2AB2C-B88A-423C-A3A8-FCFA36B2D751, OS:9.3, name:iPhone 4s }
[10:06:33]: ▸ { platform:iOS Simulator, id:44FF5AF8-69F2-4E8A-AEFF-E388C1EBF288, OS:9.3, name:iPhone 5 }
[10:06:33]: ▸ { platform:iOS Simulator, id:9A0F825E-23DC-4BC7-B737-A32B19D21F89, OS:9.3, name:iPhone 5s }
[10:06:33]: ▸ { platform:iOS Simulator, id:242C2D3D-4DB6-4811-8948-D23D2B2E9F09, OS:9.3, name:iPhone 6 }
[10:06:33]: ▸ { platform:iOS Simulator, id:EB4351BC-8313-4C9B-9D6E-C54E7DE71353, OS:9.3, name:iPhone 6 Plus }
[10:06:33]: ▸ { platform:iOS Simulator, id:6740E3BD-D0C3-49B1-87D4-4FCF7F342356, OS:9.3, name:iPhone 6s }
[10:06:33]: ▸ { platform:iOS Simulator, id:67795F57-6F10-4802-9B2C-8BD70C010182, OS:9.3, name:iPhone 6s Plus }
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, id:25F884E6-2F44-4FBA-AF71-F3E86B45E5A2 }
[10:06:33]: Exit status: 70
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
    scan(scheme: the_scheme,
         device: 'iPhone 6',
         workspace: the_workspace)
```

Scan is selecting

> -- iOS 8.1 -- iPhone 6 (25F884E6-2F44-4FBA-AF71-F3E86B45E5A2)

instead of:

> -- iOS 9.3 -- iPhone 6 (242C2D3D-4DB6-4811-8948-D23D2B2E9F09)

- https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/osx-xcode-7.3.log#L133

### Environment

fastlane version (run `fastlane -v`):

```
fastlane -v
fastlane 1.99.0
```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

### PR DESCRIPTION
**Pull request by bootstraponline**
The old logic allowed 'iPhone 6' to match on 'iPhone 6 8.1' even when
the Xcode target required 9.3 or better.

Fix #5638

### CODE REVIEW

**Comment by mfurtak** [comment]
Looks good - thanks for the fix! 👍

File: scan/lib/scan/detect_values.rb [hunk 1]
```diff
@@ -39,11 +39,16 @@ def self.filter_simulators(simulators, deployment_target)
     def self.default_device_ios
       devices = Scan.config[:devices] || Array(Scan.config[:device]) # important to use Array(nil) for when the value is nil
       found_devices = []
+      xcode_target = Scan.project.build_settings(key: "IPHONEOS_DEPLOYMENT_TARGET")
```
Comment (Hansteo) [inline scan/lib/scan/detect_values.rb]: IPHONEOS_DEPLOYMENT_TARGET

**Comment by ivanbruel** [comment]
This seems to be an issue when paired with a Workspace and a Tests only target, where `Scan.project.build_settings(key: "IPHONEOS_DEPLOYMENT_TARGET")` seems to be returning nil and crashing the execution.

```/Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `include?': [!] no implicit conversion of nil into String (TypeError)
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `block in default_device_ios'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `each'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `default_device_ios'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/detect_values.rb:23:in `set_additional_default_values'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan.rb:27:in `config='
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/manager.rb:4:in `work'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/commands_generator.rb:41:in `block (2 levels) in run'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/commands_generator.rb:60:in `run'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/scan-0.11.3/lib/scan/commands_generator.rb:14:in `start'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:48:in `take_off'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
       	from /Users/ivanbruel/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by bootstraponline** [comment]
Oh, ouch. I didn't realize the target could be nil. The code should be updated like this:


```ruby
lookup_device = lookup_device + " " + xcode_target if xcode_target && !has_version
```

**Comment by bootstraponline** [comment]
I submitted https://github.com/fastlane/fastlane/pull/5966 which should resolve the error.
