### PR TITLE
Escape single quotes in frameit title strings

### LINKED ISSUE #4851: Frameit fails on screenshots with apostrophes in the title
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit fails on screenshots with apostrophes in the title

##### Complete output when running fastlane, including the stack trace and command used

`frameit silver --verbose`:
```
DEBUG [2016-05-25 14:22:55.58]: Looking for iPhone-6s-Plus-Silver-vertical and found 1
DEBUG [2016-05-25 14:22:55.58]: Looking for iPhone-6s-Plus-Silver-vertical and found 1
DEBUG [2016-05-25 14:22:55.58]: Parsing config file '/Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/Framefile.json'
DEBUG [2016-05-25 14:22:58.01]: Falling back to default text as there was nothing specified in the .strings file
DEBUG [2016-05-25 14:22:58.49]: Using /Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/./Gotham-Medium.otf as font the title of ./fr-FR/iPhone6sPlus-04interviews.png
DEBUG [2016-05-25 14:22:58.49]: Adding text 'Consultez vos demandes d'entretien ouvertes\net agissez'
ERROR [2016-05-25 14:22:59.33]: `mogrify -font /Users/dwhitlow/workspace/ios-hired/fastlane/screenshots/./Gotham-Medium.otf -gravity Center -pointsize 107 -draw text 0,0 'Consultez vos demandes d'entretien ouvertes
et agissez' -fill  /var/folders/0q/37wvffr17yx6l9jr94s5p5vr0000gn/T/mini_magick20160525-18033-1nbwo87.png` failed with error:
mogrify: non-conforming drawing primitive definition `entretien' @ error/draw.c/DrawImage/3169.

ERROR [2016-05-25 14:22:59.33]: Backtrace:
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/shell.rb:18:in `run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:92:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/tool.rb:40:in `new'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:504:in `mogrify'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/mini_magick-4.5.1/lib/mini_magick/image.rb:384:in `combine_options'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:244:in `block in build_title_images'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:226:in `each'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:226:in `build_title_images'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:165:in `put_title_into_background'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:102:in `complex_framing'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/editor.rb:17:in `frame!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/screenshot.rb:76:in `frame!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:34:in `block in run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:26:in `each'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/runner.rb:26:in `run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:46:in `block (2 levels) in run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.44.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
  /Users/dwhitlow/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:61:in `run'
  /Users/dwhitlow/workspace/fastlane/frameit/lib/frameit/commands_generator.rb:12:in `start'
  /Users/dwhitlow/workspace/fastlane/frameit/bin/frameit:7:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Framefile.json:
```
{
    "default": {
        "title": {
            "font": "./Gotham-Medium.otf"
        },
        "background": "./background.png",
        "padding": 50
    },
    "data": [
        {
            "filter": "list"
        },
        {
            "filter": "profile"
        },
        {
            "filter": "request_interview"
        },
        {
            "filter": "interviews"
        },
        {
            "filter": "conversation"
        }
    ]
}
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.91.0
frameit 2.6.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

### PR DESCRIPTION
**Pull request by dwhitlow**
Fixes #4851

### CODE REVIEW

File: frameit/lib/frameit/editor.rb [hunk 1]
```diff
@@ -239,6 +239,7 @@ def build_title_images(max_width, max_height)
         UI.verbose("Adding text '#{text}'")
 
         text.gsub! '\n', "\n"
+        text.gsub!(/(?<!\\)(')/) { |s| "\\#{s}" }
```
Comment (KrauseFx) [inline frameit/lib/frameit/editor.rb]: This looks kind of complex, could you give some example replacements in the code base so that future us know why this is added and what it should do?

**Comment by ohwutup** [comment]
Hey @dwhitlow, just wanted to bump this up to see if you had a chance to get some examples of how this works? Thanks!!

**Comment by dwhitlow** [comment]
Hey @ohwutup, got back from vacation recently and have been catching up on some things, but I haven't forgotten about this PR.

**Comment by dwhitlow** [comment]
So is there a way to run specific spec files or just the spec files for a specific project?
`bundle exec rake test_all` takes quite a while, and trying to run rspec directly always fails no matter how I attempt to run it:
```
±  |frameit-escape-single-quotes ✓| → bundle exec rspec /Users/dwhitlow/workspace/fastlane/frameit/spec/strings_parser_spec.rb
bundler: failed to load command: rspec (/Users/dwhitlow/.rbenv/versions/2.3.0/bin/rspec)
LoadError: cannot load such file -- spec_helper
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
  /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
  /Users/dwhitlow/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
  /Users/dwhitlow/.rbenv/versions/2.3.0/bin/rspec:23:in `<top (required)>'
```

**Comment by KrauseFx** [comment]
The tests are passing fine on the CI, so don't worry too much. However it would be great if you could address https://github.com/fastlane/fastlane/pull/4849#discussion_r65469945 👍

**Comment by dwhitlow** [comment]
@KrauseFx I was working on adding those tests now, which is why I was asking on how to run individual tests rather than the entire suite at once ;)

**Comment by dwhitlow** [comment]
Added a test to demonstrate the issue this fixes. Is there a more convenient way to only run frameit tests? So far, I've been modifying the top level Rakefile to only include frameit in GEMS.

**Comment by dwhitlow** [comment]
Looks like the test is failing in CircleCI because it wasn't configured to install dependencies.

**Comment by KrauseFx** [comment]
I don't think bundling the font + the license is a good idea, especially just for tests.

**Comment by dwhitlow** [comment]
Fair enough. I'll try and shim out the ImageMagick bit which should fix both issues.

**Comment by dwhitlow** [comment]
Any word on running individual tests/specfiles?

**Comment by ohwutup** [comment]
Hey @dwhitlow, you should be able to run `rspec path/to/spec:line_number` to test just one file or one test

**Comment by dwhitlow** [comment]
@ohwutup Running rspec causes the spec files to fail because spec_helper wasn't included. Am I missing some sort of configuration step?
```
±  |frameit-escape-single-quotes ✓| → rspec /Users/dwhitlow/workspace/fastlane/frameit/spec/screenshot_spec.rb
/Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- spec_helper (LoadError)
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `block in requires='
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `each'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1295:in `requires='
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `each'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/configuration_options.rb:21:in `configure'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:105:in `setup'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in `run'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in `run'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rspec-core-3.4.4/exe/rspec:4:in `<top (required)>'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/bin/rspec:23:in `load'
	from /Users/dwhitlow/.rbenv/versions/2.3.0/bin/rspec:23:in `<main>'
```

Shimmed out the MiniMagick/ImageMagick dependency and also added a test to confirm that already-escaped apostrophes are ignored.

**Comment by ohwutup** [comment]
Oh, yeah. That is something weird with rspec. if you `cd frameit` and then do it you should be all set.

**Comment by dwhitlow** [comment]
Thanks for the help! For some reason I tried at the project root and in frameit/rspec but never in frameit/. Stubbed out a few more method calls to keep ImageMagick from being invoked. Should be ready to go now.

**Comment by dwhitlow** [comment]
Looks like all tests are passing now but the CI build is still marked as failing. Can somebody try rerunning the build?

**Comment by ohwutup** [comment]
Thanks for making that happen @dwhitlow ! We have updated `danger` recently, if you could just rebase on master and then force push, that should kick things into gear!

**Comment by dwhitlow** [comment]
@ohwutup all set!

**Comment by ohwutup** [comment]
Thanks @dwhitlow ! Do you think there is any way for you to run these tests without requiring assets be checked in to source control per @KrauseFx's comment? https://github.com/fastlane/fastlane/pull/4849#issuecomment-227311552

**Comment by dwhitlow** [comment]
@ohwutup @KrauseFx's comment concerned a font and its license file I was including to run this as an integration test. I already removed them when I shimmed out the MiniMagick calls.

**Comment by dwhitlow** [comment]
@ohwutup ping?

**Comment by ohwutup** [comment]
Thanks for the PR @dwhitlow ! 🚀 💯
