### PR TITLE
[supply] always return empty array for tracks

### LINKED ISSUE #13076: Fastlane finished with errors when trying to retrieve track version codes from google play store
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Fastlane finished with errors when trying to retrieve track version codes from google play store. About 6 hours ago fastlane starts finish with error on different google play accounts and different build machines (linux and macOS). Looks like google doesn't return 404 error for empty tracks.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>/var/lib/gems/2.3.0/gems/fastlane-2.101.1/supply/lib/supply/reader.rb:10:in `track_version_codes': [!] undefined method `empty?' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/google_play_track_version_codes.rb:23:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:39:in `block (2 levels) in parsing_binding'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /var/lib/gems/2.3.0/gems/fastlane-2.101.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                        |
| Ruby                        | 2.3.1                                                           |
| Bundler?                    | false                                                           |
| Git                         | git version 2.7.4                                               |
| Installation Source         | /usr/local/bin/fastlane                                         |
| Host                        | Ubuntu 16.04.5 LTS debian_based stretch/sid (4.4.0-112-generic) |
| Ruby Lib Dir                | /usr/lib                                                        |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                      |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.101.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.21.2       |
| emoji_regex               | 0.1.1        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2018-08-09**
</details>

### PR DESCRIPTION
**Pull request by formatCvt**
Return empty array when result.version_codes is nil. 
Fix issue #13076

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This PR will fix #13076 

### Description
Looks like google doesn't return 404 error for empty tracks and we should return empty array for empty tracks.

### CODE REVIEW

File: supply/lib/supply/client.rb [hunk 1]
```diff
@@ -298,7 +298,7 @@ def track_version_codes(track)
           current_edit.id,
           track
         )
-        return result.version_codes
+        return result.version_codes.nil? ? [] : result.version_codes
```
Comment (tmm1) [inline supply/lib/supply/client.rb]: This can be `result.version_codes || []`

Comment (joshdholtz) [reply supply/lib/supply/client.rb]: I agree with this ^ Can you make this change? I will then click the merge button 😊

**Review by joshdholtz — CHANGES_REQUESTED** [review]

**Comment by tmm1** [comment]
@joshdholtz ping?

**Review by joshdholtz — APPROVED** [review]
Looks great! Thanks for doing this 😊
