### PR TITLE
[deliver][download_metadata] give precedence to generate metadata from edit version instead of live version

### LINKED ISSUE #17568: deliver download_metadata skips name/subtitle of pre-release versions
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`deliver download_metadata` fails to update (at least) `name` and `subtitle` from a pre-release version. `keywords` are updated correctly, but it's possible that other metadata isn't updated either. The corresponding files are written to, but contain data of the live version.

##### Command executed

`bundle exec fastlane deliver download_metadata`

##### Complete output when running fastlane, including the stack trace and command used

<details>
<summary>List of updated metadata files</summary>

```
[17:59:04]: Writing to './fastlane/metadata/en-US/name.txt'
[17:59:04]: Writing to './fastlane/metadata/en-US/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/en-US/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/vi/name.txt'
[17:59:04]: Writing to './fastlane/metadata/vi/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/vi/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/vi/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-BR/name.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-BR/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-BR/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-BR/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/fi/name.txt'
[17:59:04]: Writing to './fastlane/metadata/fi/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/fi/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/fi/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/hu/name.txt'
[17:59:04]: Writing to './fastlane/metadata/hu/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/hu/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/hu/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/hr/name.txt'
[17:59:04]: Writing to './fastlane/metadata/hr/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/hr/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/hr/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/id/name.txt'
[17:59:04]: Writing to './fastlane/metadata/id/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/id/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/id/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-FR/name.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-FR/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-FR/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-FR/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/de-DE/name.txt'
[17:59:04]: Writing to './fastlane/metadata/de-DE/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/de-DE/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/de-DE/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-PT/name.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-PT/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-PT/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/pt-PT/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/pl/name.txt'
[17:59:04]: Writing to './fastlane/metadata/pl/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/pl/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/pl/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ms/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ms/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ms/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ms/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ru/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ru/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ru/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ru/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-CA/name.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-CA/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-CA/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/fr-CA/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/cs/name.txt'
[17:59:04]: Writing to './fastlane/metadata/cs/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/cs/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/cs/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/hi/name.txt'
[17:59:04]: Writing to './fastlane/metadata/hi/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/hi/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/hi/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/he/name.txt'
[17:59:04]: Writing to './fastlane/metadata/he/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/he/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/he/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/tr/name.txt'
[17:59:04]: Writing to './fastlane/metadata/tr/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/tr/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/tr/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ar-SA/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ar-SA/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ar-SA/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ar-SA/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/sk/name.txt'
[17:59:04]: Writing to './fastlane/metadata/sk/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/sk/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/sk/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/en-GB/name.txt'
[17:59:04]: Writing to './fastlane/metadata/en-GB/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/en-GB/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/en-GB/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hans/name.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hans/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hans/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hans/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ro/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ro/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ro/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ro/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ca/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ca/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ca/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ca/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ja/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ja/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ja/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ja/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/sv/name.txt'
[17:59:04]: Writing to './fastlane/metadata/sv/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/sv/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/sv/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/it/name.txt'
[17:59:04]: Writing to './fastlane/metadata/it/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/it/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/it/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/uk/name.txt'
[17:59:04]: Writing to './fastlane/metadata/uk/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/uk/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/uk/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/nl-NL/name.txt'
[17:59:04]: Writing to './fastlane/metadata/nl-NL/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/nl-NL/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/nl-NL/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/ko/name.txt'
[17:59:04]: Writing to './fastlane/metadata/ko/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/ko/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/ko/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hant/name.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hant/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hant/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/zh-Hant/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/en-AU/name.txt'
[17:59:04]: Writing to './fastlane/metadata/en-AU/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/en-AU/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/en-AU/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/es-ES/name.txt'
[17:59:04]: Writing to './fastlane/metadata/es-ES/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/es-ES/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/es-ES/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/el/name.txt'
[17:59:04]: Writing to './fastlane/metadata/el/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/el/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/el/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/th/name.txt'
[17:59:04]: Writing to './fastlane/metadata/th/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/th/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/th/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/es-MX/name.txt'
[17:59:04]: Writing to './fastlane/metadata/es-MX/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/es-MX/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/es-MX/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/en-CA/name.txt'
[17:59:04]: Writing to './fastlane/metadata/en-CA/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/en-CA/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/en-CA/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/no/name.txt'
[17:59:04]: Writing to './fastlane/metadata/no/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/no/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/no/apple_tv_privacy_policy.txt'
[17:59:04]: Writing to './fastlane/metadata/da/name.txt'
[17:59:04]: Writing to './fastlane/metadata/da/subtitle.txt'
[17:59:04]: Writing to './fastlane/metadata/da/privacy_url.txt'
[17:59:04]: Writing to './fastlane/metadata/da/apple_tv_privacy_policy.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/description.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/sk/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/description.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-AU/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/description.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hi/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ko/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/description.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/uk/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/description.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-BR/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ms/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ja/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/no/description.txt'
[17:59:07]: Writing to './fastlane/metadata/no/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/no/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/no/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/no/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/no/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/id/description.txt'
[17:59:07]: Writing to './fastlane/metadata/id/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/id/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/id/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/id/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/id/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/th/description.txt'
[17:59:07]: Writing to './fastlane/metadata/th/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/th/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/th/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/th/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/th/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ru/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/description.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/es-ES/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ar-SA/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/description.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-FR/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/description.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/nl-NL/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/description.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pt-PT/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/it/description.txt'
[17:59:07]: Writing to './fastlane/metadata/it/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/it/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/it/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/it/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/it/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/description.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hr/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/description.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/es-MX/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/description.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fi/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/description.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/de-DE/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/description.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/fr-CA/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/el/description.txt'
[17:59:07]: Writing to './fastlane/metadata/el/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/el/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/el/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/el/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/el/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/description.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hans/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/description.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/sv/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ca/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/description.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/vi/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/description.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/hu/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/description.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/zh-Hant/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/description.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/pl/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/he/description.txt'
[17:59:07]: Writing to './fastlane/metadata/he/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/he/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/he/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/he/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/he/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/description.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/tr/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/description.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-US/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/description.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-CA/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/description.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/cs/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/da/description.txt'
[17:59:07]: Writing to './fastlane/metadata/da/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/da/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/da/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/da/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/da/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/description.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/ro/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/description.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/keywords.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/release_notes.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/support_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/marketing_url.txt'
[17:59:07]: Writing to './fastlane/metadata/en-GB/promotional_text.txt'
[17:59:07]: Writing to './fastlane/metadata/primary_category.txt'
[17:59:07]: Writing to './fastlane/metadata/secondary_category.txt'
[17:59:07]: Writing to './fastlane/metadata/primary_first_sub_category.txt'
[17:59:07]: Writing to './fastlane/metadata/primary_second_sub_category.txt'
[17:59:07]: Writing to './fastlane/metadata/secondary_first_sub_category.txt'
[17:59:07]: Writing to './fastlane/metadata/secondary_second_sub_category.txt'
[17:59:07]: Writing to './fastlane/metadata/copyright.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/first_name.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/last_name.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/phone_number.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/email_address.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/demo_user.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/demo_password.txt'
[17:59:08]: Writing to './fastlane/metadata/review_information/notes.txt'
```
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #17568
There's a good context into the problem here: https://github.com/fastlane/fastlane/issues/17568#issuecomment-744423393

### Description
Given the fact that `deliver` has a `use_live_version` option and another `edit_live` option and both default to `false`, seems like looking up the live version and then the edit version was wrong. So I inverted this condition and, if anyone run into issues, they can use the `use_live_version` to force using the live version instead.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-download-metadata-from-edit-version"
```

### CODE REVIEW

**Comment by rogerluan** [comment]
😥 once again, tests are failing in the CI but they're all green locally. I don't have visibility into what's failing in the CI 😞

File: deliver/lib/deliver/setup.rb [hunk 1]
```diff
@@ -60,9 +60,13 @@ def deliverfile_path
       end
     end
 
-    def generate_metadata_files(app, version, path)
+    def generate_metadata_files(app, version, path, options)
       # App info localizations
-      app_info = app.fetch_live_app_info || app.fetch_edit_app_info
+      if options[:use_live_version]
+        app_info = app.fetch_live_app_info
```
Comment (joshdholtz) [inline deliver/lib/deliver/setup.rb:66]: I think we want to display an error if `app.fetch_live_app_info` returns `nil` 🤔  Thoughts?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One small thought!

File: deliver/lib/deliver/setup.rb (hunk 1 above)
Comment (rogerluan) [reply deliver/lib/deliver/setup.rb:66]: I couldn't agree more - nice thought! Otherwise it would just throw a mysterious crash below just like it used to 🙈  I'll update it 🙌

**Review by joshdholtz — APPROVED** [review]
🔥 Thanks for doing this!! ❤️ s like always!
