### PR TITLE
[Fastlane.Swift] Fix onError not being called

### LINKED ISSUE #17482: [Fastlane.Swift] `onError` never called.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently, the method `onError` isn't implemented in `LaneFileProtocol` so that we can't handle errors, for example during `deliver`.
If any lane fails, there is no way to handle the failure.

##### Command executed

Any lane, for example:

`fastlane deliver`

Related: https://github.com/fastlane/fastlane/issues/12381

### PR DESCRIPTION
**Pull request by minuscorp**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #17482

### Description
This fix an issue that never was initially implemented, the `onError` method call was never implemented, now it does. 

### Testing Steps
1. Checkout and install this fastlane version: `https://github.com/minuscorp/fastlane/tree/swift-on-error-call-fix`
2. Create a failing lane like for example:
```swift
func testLane() {
  sh(command: "exit -1")
}
```
3. Define and override the `onError` method and **don't forget to call the `super`** _(if you don't call the `super`, `afterAll` will be called)_:
image
4. Check that `onError` is being called but `afterAll` doesn't (because an error occurred).

### CODE REVIEW

File: fastlane/swift/SocketResponse.swift [hunk 1]
```diff
@@ -35,12 +35,16 @@ struct SocketResponse {
                 return
 
             } else if status == "failure" {
-                guard let failureInformation = statusDictionary["failure_information"] as? [String] else {
+                guard
+                  let failureInformation = statusDictionary["failure_information"] as? [String],
+                  let failureClass = statusDictionary["failure_class"] as? String?,
+                  let failureMessage = statusDictionary["failure_message"] as? String?
```
Comment (joshdholtz) [inline fastlane/swift/SocketResponse.swift:41]: `failureClass` and `failureMessage` are optional in the num. Do these really need to be in the `guard`? 🤔

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One small question!

File: fastlane/swift/SocketResponse.swift (hunk 1 above)
Comment (minuscorp) [reply fastlane/swift/SocketResponse.swift:41]: Is the most straightforward way to assign them into a optional variable to use them afterwards instead of searching them into the dictionary in the following lines and make the cast there, just a way of making the information more readable, but the other approach is as valid as the current one. Just a matter of readability for short. But I can change it if you want 😄

File: fastlane/swift/LaneFileProtocol.swift [hunk 2]
```diff
@@ -17,20 +17,20 @@ public protocol LaneFileProtocol: class {
...
     func beforeAll(with _: String) {} // No-op by default
     func afterAll(with _: String) {} // No-op by default
-    func onError(currentLane _: String, errorInfo _: String) {} // No-op by default
     func recordLaneDescriptions() {} // No-op by default
 }
 
 @objcMembers
 open class LaneFile: NSObject, LaneFileProtocol {
     private(set) static var fastfileInstance: LaneFile?
+    private static var onErrorCalled: [String: Bool] = [:]
```
Comment (andemengo) [inline fastlane/swift/LaneFileProtocol.swift:33]: Just to understand better, why we use a `[String: Bool]`?
I notice that we associate only `true` and never `false`. Maybe a `Set<String>` or an `Array<String>` could be a more indicated structure?

```suggestion
    private static var onErrorCalled: Set<String> = []
```

File: fastlane/swift/LaneFileProtocol.swift [hunk 3]
```diff
@@ -39,6 +39,10 @@ open class LaneFile: NSObject, LaneFileProtocol {
     private static func trimLaneWithOptionsFromName(laneName: String) -> String {
         return String(laneName.prefix(laneName.count - 12))
     }
+  
+    public func onError(currentLane: String, errorInfo: String, errorClass: String?, errorMessage: String?) {
+      LaneFile.onErrorCalled[currentLane] = true
```
Comment (andemengo) [inline fastlane/swift/LaneFileProtocol.swift:44]: If we decided to use a `Set` for example this will become:

```suggestion
      LaneFile.onErrorCalled.insert(currentLane)
```

File: fastlane/swift/LaneFileProtocol.swift [hunk 4]
```diff
@@ -137,7 +141,9 @@ open class LaneFile: NSObject, LaneFileProtocol {
         _ = fastfileInstance.perform(NSSelectorFromString(laneMethod), with: parameters)
 
         // Call only on success.
-        fastfileInstance.afterAll(with: lane)
+        if !(Self.onErrorCalled[lane] ?? false) {
```
Comment (andemengo) [inline fastlane/swift/LaneFileProtocol.swift:144]: If we decided to use a `Set` for example this will become:

```suggestion
        if !(Self.onErrorCalled.contains(lane)) {
```

File: fastlane/swift/LaneFileProtocol.swift [hunk 5]
```diff
@@ -17,20 +17,20 @@ public protocol LaneFileProtocol: class {
...
     func afterAll(with lane: String)
-    func onError(currentLane: String, errorInfo: String)
+    func onError(currentLane: String, errorInfo: String, errorClass: String?, errorMessage: String?)
 }
 
 public extension LaneFileProtocol {
     var fastlaneVersion: String { return "" } // Defaults to "" because that means any is fine
     func beforeAll(with _: String) {} // No-op by default
     func afterAll(with _: String) {} // No-op by default
-    func onError(currentLane _: String, errorInfo _: String) {} // No-op by default
```
Comment (andemengo) [inline fastlane/swift/LaneFileProtocol.swift:27]: Why this default public implementation was deleted?

**Review by andemengo — COMMENTED** [review]
Thanks for working on the issue that I've opened a few month ago! 👏 
I just want to understand better some motivation behind the data structure used. 🤔

File: fastlane/swift/LaneFileProtocol.swift (hunk 5 above)
Comment (minuscorp) [reply fastlane/swift/LaneFileProtocol.swift:27]: It is now living in the `LaneFile` superclass which it will record the called lanes to avoid `afterAll` being called unnecessarily. Also, for some reason even if the Fastfile overloaded the protocol's implementation, it gets called anyway and ignoring the new implementation (couldn't figure out why exactly).

I'll address the changes you mention once I test that they're working properly, thanks for the feedback! ❤️❤️

File: fastlane/swift/LaneFileProtocol.swift (hunk 2 above)
Comment (minuscorp) [reply fastlane/swift/LaneFileProtocol.swift:33]: The approach for a dictionary is mostly wise in terms of optimization, as reading in a dictionary takes O(1) whereas in an array or set it takes O(N). Not that the performance will be an issue here, but it was just pure instinct.

Comment (andemengo) [reply fastlane/swift/LaneFileProtocol.swift:33]: I totally agree with the optimization point; array isn't the best solution, so that I suggested `Set`.
Also `Set` has `O(1)` reading / writing complexity and since in the dictionary we only add `true` values for lanes, it could make sense to semplificate the structure and the future validation operations and checks. ;)

Comment (minuscorp) [reply fastlane/swift/LaneFileProtocol.swift:33]: You're completely right! I thought array and set shared same complexity, so your approach is much better than the dictionary for the reasons you mentioned. I'll address this once I get energy to pick the laptop in the weekend😂.

**Comment by minuscorp** [comment]
cc: @andemengo Just finished pushing the review comments 😄

File: fastlane/swift/SocketClient.swift [hunk 6]
```diff
@@ -302,8 +302,9 @@ extension SocketClient: StreamDelegate {
                 self.closeSession(sendAbort: false)
             }
 
-        case let .failure(failureInformation):
-            socketDelegate?.commandExecuted(serverResponse: .serverError) {
+        case let .failure(failureInformation, failureClass, failureMessage):
+          LaneFile.fastfileInstance?.onError(currentLane: ArgumentProcessor(args: CommandLine.arguments).currentLane, errorInfo: failureInformation.joined(), errorClass: failureClass, errorMessage: failureMessage)
+          socketDelegate?.commandExecuted(serverResponse: .serverError) {
```
Comment (rogerluan) [inline fastlane/swift/SocketClient.swift:307]: Looks like the indentation here is wrong (for Swift)? 🙈 👀

**Review by rogerluan — APPROVED** [review]
Good stuff!! So glad to see this implemented after so long 🤩

File: fastlane/swift/SocketClient.swift (hunk 6 above)
Comment (minuscorp) [reply fastlane/swift/SocketClient.swift:307]: 🤔 maybe, anyway, there's a linter once this is merged so I don't think it is much trouble. In fact I think this is the xcode indentation that is slightly different than Swiftformat's one. Should I change it?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@minuscorp Thanks so much for adding support for this! I had no idea this wasn’t implemented 😱 I did run into one error when I tried to run the `puts` action from within the `onError`. It ended up hanging after printing “Ho” 😬 Is this a user error on my side? Or is this something that would still need to get fixed 🤔 

```swift

import Foundation

class Fastfile: LaneFile {
        func testLane() {
          desc("Description of what the lane does")
    puts(message: "Hey")
    sh(command: "exit -1")
        }

  override public func onError(currentLane: String, errorInfo: String, errorClass: String?, errorMessage: String?) {
    super.onError(currentLane: currentLane, errorInfo: errorInfo, errorClass: errorClass, errorMessage: errorMessage)

    puts(message: "Ho")
  }
}
```

**Comment by minuscorp** [comment]
At this point of the execution, the socket is already closed due to an error (whichever error it is) so adding more Ruby actions won't work at that point, just Swift code instead, this is how the socket is implemented underneath so I'm not quite sure that I can recover the connection after an error in the execution TBH. 😕

**Comment by joshdholtz** [comment]
@minuscorp Ahhhhhhh, that makes sense! Thanks for explaining that 😊

**Review by joshdholtz — APPROVED** [review]
This looks great to me! Thanks for adding this in 🙌
