### PR TITLE
Output changelog in changelog_from_git_commits.

### LINKED ISSUE #4863: It would be nice if changelog_from_git_commits output the changelog so that I can verify it in Jenkins while waiting for iTC to process the build.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
...
[09:34:36]: --- Step: changelog_from_git_commits ---
[09:34:36]: ----------------------------------------
[09:34:36]: Collecting the last 10 Git commits
...
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
...
changelog = changelog_from_git_commits(commits_count: 10, pretty: '• %s', merge_commit_filtering: 'exclude_merges')
...
```

### Environment

fastlane version (run `fastlane -v`): 1.91.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

### PR DESCRIPTION
**Pull request by hiltonc**
fixes #4863

### CODE REVIEW

**Comment by hiltonc** [comment]
fixes #4863

File: fastlane/lib/fastlane/actions/changelog_from_git_commits.rb [hunk 1]
```diff
@@ -37,6 +37,10 @@ def self.run(params)
         changelog = changelog.gsub("\n\n", "\n") if changelog # as there are duplicate newlines
         Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
 
+        puts ""
+        puts changelog
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/changelog_from_git_commits.rb]: To print out text, use `UI.message` instead

**Comment by KrauseFx** [comment]
This looks good to me, please address my comment, then we can merge 👍 Thanks for your contribution

File: fastlane/lib/fastlane/actions/changelog_from_git_commits.rb (hunk 1 above)
Comment (hiltonc) [inline fastlane/lib/fastlane/actions/changelog_from_git_commits.rb]: I initially tried that, but because changelog is typically multiline, I think it would look weird:

```
[09:34:35]: • Commit message
• Commit message
• Commit message
• Commit message
```

I'm happy make that change though if you'd prefer it.

Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/changelog_from_git_commits.rb]: Ah, very good point, thanks for letting me know, let's leave it like this then 👍

**Comment by KrauseFx** [comment]
Thanks, this will be in the next fastlane release 🚀

**Comment by hiltonc** [comment]
Thanks!
