### PR TITLE
[Regression][fastlane_core][deliver] Fix deliver is unable to automatically select the latest build and submit it for review

### LINKED ISSUE #18680: Deliver is unable to automatically select the latest build and submit it for review when `app_version` and `ipa` parameters are not set.
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.181.0`
- Last working version: `2.180.1`

### Regression Description

It is not possible to submit app for review without setting `app_version` or `ipa` parameters for `deliver`as the latest build is not selected automatically anymore.

#### Details

There are 2 possibilities to select a build for for review in `SubmitForReview` [https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb#L185-L203](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb#L185-L203), either
- by setting `build_number` or
- by letting `BuildWatcher` to automatically select the latest build.

When we try to automatically select the build without passing `app_version` and ipa file (from which `app_version` and `build_number` could be fetched in `wait_for_build_processing_to_be_complete`), `BuildWatcher` cannot find a build, sleeps and retries indefinitely.
It happens, because `matching_build` method has no `versions` that could be used to query ConnectApi for the latest build.
[https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/build_watcher.rb#L79](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/build_watcher.rb#L79)

```ruby
versions = [watched_app_version, watched_app_version_alternate].compact

version_matches = versions.map do |version|
  match = VersionMatches.new
  match.version = version
  match.builds = Spaceship::ConnectAPI::Build.all(
    app_id: app_id,
    version: version,
    build_number: watched_build_version,
    platform: platform
  )

  match
end.flatten
```
#### Expected behavior:
Latest processed build automatically selected and submitted for review

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>

  +----------------------------------------------------------------------------+----------------------------------------+
  |                                               deliver 2.182.0 Summary                                               |
  +----------------------------------------------------------------------------+----------------------------------------+
  | app_identifier                                                             | REDACTED                               |
  | app_rating_config_path                                                     | REDACTED                               |
  | automatic_release                                                          | false                                  |
  | dev_portal_team_id                                                         | REDACTED                               |
  | force                                                                      | false                                  |
  | itc_provider                                                               | REDACTED                               |
  | metadata_path                                                              | REDACTED                               |
  | overwrite_screenshots                                                      | false                                  |
  | phased_release                                                             | false                                  |
  | price_tier                                                                 | 0                                      |
  | reject_if_possible                                                         | false                                  |
  | run_precheck_before_submit                                                 | false                                  |
  | screenshots_path                                                           | REDACTED                               |
  | skip_app_version_update                                                    | true                                   |
  | skip_binary_upload                                                         | true                                   |
  | skip_metadata                                                              | true                                   |
  | skip_screenshots                                                           | true                                   |
  | submission_information.add_id_info_uses_idfa                               | REDACTED                                   |
  | submission_information.add_id_info_serves_ads                              | REDACTED                                  |
  | submission_information.add_id_info_tracks_install                          | REDACTED                                  |
  | submission_information.add_id_info_tracks_action                           | REDACTED                                   |
  | submission_information.add_id_info_limits_tracking                         | REDACTED                                   |
  | submission_information.content_rights_contains_third_party_content         | REDACTED                                   |
  | submission_information.content_rights_has_rights                           | REDACTED                                   |
  | submission_information.export_compliance_platform                          | ios                                    |
  | submission_information.export_compliance_compliance_required               | REDACTED                                   |
  | submission_information.export_compliance_is_exempt                         | REDACTED                                   |
  | submission_information.export_compliance_uses_encryption                   | REDACTED                                   |
  | submission_information.export_compliance_contains_proprietary_cryptography | REDACTED                                   |
  | submission_information.export_compliance_contains_third_party_cryptography | REDACTED                                   |
  | submission_information.export_compliance_available_on_french_store         | REDACTED                                  |
  | submission_information.export_compliance_encryption_updated                | REDACTED                                   |
  | submit_for_review                                                          | true                                   |
  | team_id                                                                    | REDACTED                               |
  | username                                                                   | REDACTED                               |
  | platform                                                                   | ios                                    |
  | edit_live                                                                  | false                                  |
  | use_live_version                                                           | false                                  |
  | reset_ratings                                                              | false                                  |
  | precheck_default_rule_level                                                | warn                                   |
  | ignore_language_directory_validation                                       | false                                  |
  | precheck_include_in_app_purchases                                          | true                                   |
  +----------------------------------------------------------------------------+----------------------------------------+

  [14:29:49]: Price Tier unchanged (tier 0)
  [14:29:49]: Selecting the latest build...
  [14:29:49]: Waiting for processing on... app_id: REDACTED, app_version: , build_version: , platform: IOS
  [14:29:49]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
  [14:29:49]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
  [14:30:04]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
  [14:30:19]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)

</pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 11.3                                                     |
| Ruby                        | 2.6.3                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.30.1                                       |
| Installation Source         | ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | macOS 11.3 (20E232)                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                              |
| OpenSSL Version             | OpenSSL 1.1.1b  26 Feb 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 12.3                                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.182.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 1.11.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.3.0        |
| bundler                       | 2.0.2        |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.454.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.114.0      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.94.1       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 2.0.3        |
| commander                     | 4.6.0        |
| declarative                   | 0.0.20       |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.81.0       |
| faraday-excon                 | 1.1.0        |
| faraday-net_http              | 1.0.1        |
| faraday-net_http_persistent   | 1.1.0        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.4.1        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.3        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.2       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.1.0        |
| trailblazer-option            | 0.1.1        |
| uber                          | 0.1.0        |
| representable                 | 3.1.1        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.5        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.3.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
| fastlane-plugin-appcenter     | 1.11.0       |
</details>

*generated on:* **2021-05-12**
</details>

### PR DESCRIPTION
**Pull request by lucgrabowski**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Deliver is unable to automatically select the latest build and submit it for review. 
Resolves #18680

### Description

Request for the latest build will be made in `matching_build` method when `select_latest` is true even if `app_version` is missing. There will be a crash if `app_version` is missing and `select_latest` is false to not loop indefinitely.
Tested by successfully submitting a build for review without setting `app_version`.

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/build_watcher.rb [hunk 1]
```diff
@@ -78,6 +78,17 @@ def matching_build(watched_app_version: nil, watched_build_version: nil, app_id:
         watched_app_version_alternate = alternate_version(watched_app_version)
         versions = [watched_app_version, watched_app_version_alternate].compact
 
+        if versions.empty?
+          if select_latest
+            UI.message("Watched build version should not be present when there is no app version to watch") unless watched_build_version.nil?
+            UI.message("Searching for the latest build")
+            versions = [nil]
+          else
+            error_message = "FastlaneCore::BuildWatcher has no app version to watch"
```
Comment (minuscorp) [inline fastlane_core/lib/fastlane_core/build_watcher.rb:87]: Maybe here is more convenient to raise the error instead of hardcoding the message

Comment (lucgrabowski) [reply fastlane_core/lib/fastlane_core/build_watcher.rb:87]: Would it be fine to raise `FastlaneCore::Interface::FastlaneError` with
`UI.user_error!("There is no app version to watch")`?

Comment (minuscorp) [reply fastlane_core/lib/fastlane_core/build_watcher.rb:87]: I mean if the error has done relation with build watcher you can always instantiate and raise that particular exception don't you?

Comment (lucgrabowski) [reply fastlane_core/lib/fastlane_core/build_watcher.rb:87]: Sure, I'll add a `BuildWatcherError` and I'll also update raising error when more than 1 matching build is found in line 113.

**Review by joshdholtz — APPROVED** [review]
Doh, sorry about breaking this! Thanks so much for fixing this and updating the spec ❤️ Really appreciate the contribution!

**Comment by lucgrabowski** [comment]
Thanks for merging and thanks for the great work you do 🎉 , especially for 🚀 ConnectApi changes from the last year.
