### PR TITLE
[snapshot] Add support for concurrent simulators with Xcode 9

### LINKED ISSUE #9579: fastlane snapshot fails in XCode 9 beta 2
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am getting this error when I try to use `fastlane snapshot`: `No such file or directory @ rb_sysopen - /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Logs/Test/Attachments/Screenshot_44966137-D5A3-4DAE-9151-97EC8A873D0B.png`. Looking at that `Attachments` directory, it exists but is empty.

```
iMac:manabi-reader alex$ fastlane snapshot
[12:30:55]: Successfully loaded '/Users/alex/src/manabi-reader/Snapfile' 📄

+-----------------+-----------------+
| Detected Values from './Snapfile' |
+-----------------+-----------------+
| devices         | ["iPhone 6"]    |
| languages       | ["en-US"]       |
| scheme          | ManabiReader    |
+-----------------+-----------------+

[12:30:55]: $ xcodebuild -list -project ./ManabiReader.xcodeproj
[12:30:55]: $ xcodebuild -showBuildSettings -scheme ManabiReader -project ./ManabiReader.xcodeproj

+----------------------------+--------------------------------------+
|                    Summary for snapshot 2.41.0                    |
+----------------------------+--------------------------------------+
| devices                    | ["iPhone 6"]                         |
| languages                  | ["en-US"]                            |
| scheme                     | ManabiReader                         |
| project                    | ./ManabiReader.xcodeproj             |
| output_directory           | /Users/alex/src/manabi-reader/fastl  |
|                            | ane/screenshots                      |
| launch_arguments           | [""]                                 |
| output_simulator_logs      | false                                |
| skip_open_summary          | false                                |
| skip_helper_version_check  | false                                |
| clear_previous_screenshots | false                                |
| reinstall_app              | false                                |
| erase_simulator            | false                                |
| localize_simulator         | false                                |
| app_identifier             | io.manabi.ManabiReader               |
| buildlog_path              | ~/Library/Logs/snapshot              |
| clean                      | false                                |
| number_of_retries          | 1                                    |
| stop_after_first_error     | false                                |
| xcode_path                 | /Applications/Xcode-beta.app         |
+----------------------------+--------------------------------------+

[12:30:57]: Building and running project - this might take some time...
[12:30:57]: snapshot run 1 of 1
[12:31:01]: Patching '/Users/alex/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[12:31:02]: ------------------------
[12:31:02]: --- iPhone 6 - en-US ---
[12:31:02]: ------------------------
[12:31:02]: $ set -o pipefail && xcodebuild -scheme ManabiReader -project ./ManabiReader.xcodeproj -derivedDataPath '/var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd' -destination 'platform=iOS Simulator,id=0B87F5E6-5578-4EC9-B1C8-7DE5F8D391B1,OS=11.0' FASTLANE_SNAPSHOT=YES build test | tee /Users/alex/Library/Logs/snapshot/ManabiReader-ManabiReader.log | xcpretty
[12:31:02]: ▸ Loading...
[12:31:03]: ▸ Building mecab/mecab [Debug]
[12:31:03]: ▸ Check Dependencies
[12:31:03]: ▸ Compiling dictionary_compiler.cpp
[12:31:04]: ▸ Compiling learner_tagger.cpp
[12:31:04]: ▸ Compiling feature_index.cpp
[12:31:04]: ▸ Compiling mecab-dict-gen.cpp
[12:31:04]: ▸ Compiling eval.cpp
[12:31:04]: ▸ Compiling utils.cpp
[12:31:04]: ▸ Compiling param.cpp
[12:31:04]: ▸ Compiling learner.cpp
[12:31:05]: ▸ Compiling mecab.cpp
[12:31:05]: ▸ Compiling iconv_utils.cpp
[12:31:05]: ▸ Compiling libmecab.cpp
[12:31:05]: ▸ Compiling tokenizer.cpp
[12:31:05]: ▸ Compiling writer.cpp
[12:31:05]: ▸ Compiling dictionary_rewriter.cpp
[12:31:05]: ▸ Compiling dictionary.cpp
[12:31:06]: ▸ Compiling string_buffer.cpp
[12:31:06]: ▸ Compiling viterbi.cpp
[12:31:06]: ▸ Compiling tagger.cpp
[12:31:06]: ▸ Compiling context_id.cpp
[12:31:06]: ▸ Compiling mecab-system-eval.cpp
[12:31:06]: ▸ Compiling char_property.cpp
[12:31:07]: ▸ Compiling mecab-cost-train.cpp
[12:31:07]: ▸ Compiling lbfgs.cpp
[12:31:07]: ▸ Compiling nbest_generator.cpp
[12:31:07]: ▸ Compiling dictionary_generator.cpp
[12:31:07]: ▸ Compiling mecab-test-gen.cpp
[12:31:07]: ▸ Compiling mecab-dict-index.cpp
[12:31:07]: ▸ Compiling connector.cpp
[12:31:07]: ▸ Building library libmecab.a
[12:31:07]: ▸ Building ManabiReader/ManabiReader [Debug]
[12:31:07]: ▸ Check Dependencies
[12:31:09]: ▸ Compiling JapaneseSegmentData.swift
[12:31:12]: ▸ Compiling HomeTableViewController.swift
[12:31:12]: ▸ Compiling FeedSpecificContentTransformations.swift
[12:31:12]: ▸ Compiling ManabiReadabilityViewController.swift
[12:31:12]: ▸ Compiling HistoryRecord.swift
[12:31:12]: ▸ Compiling ArticleListViewController.swift
[12:31:12]: ▸ Compiling LookupPopoverBackgroundView.swift
[12:31:12]: ▸ Compiling Bookmark.swift
[12:31:12]: ▸ Compiling RemoteConfiguration.swift
[12:31:12]: ▸ Compiling BookmarkController.swift
[12:31:12]: ▸ Compiling CategoriesController.swift
[12:31:12]: ▸ Compiling CategoryTableCell.swift
[12:31:12]: ▸ Compiling AppDelegate.swift
[12:31:12]: ▸ Compiling RubyLabel.swift
[12:31:12]: ▸ Compiling LookupViewController.swift
[12:31:13]: ▸ Compiling BookmarksViewController.swift
[12:31:13]: ▸ Compiling UIButton+Styles.swift
[12:31:13]: ▸ Compiling JMDictRealmPopulator.swift
[12:31:13]: ▸ Compiling HomeTableCustomURLCell.swift
[12:31:13]: ▸ Compiling Feed.swift
[12:31:13]: ▸ Compiling BookmarksAndHistoryViewController.swift
[12:31:13]: ▸ Compiling RubyText.swift
[12:31:13]: ▸ Compiling CategoryTableViewController.swift
[12:31:13]: ▸ Compiling UIFont+Manabi.swift
[12:31:13]: ▸ Compiling FeedTableCell.swift
[12:31:13]: ▸ Compiling HTMLImageFinder.swift
[12:31:14]: ▸ Compiling String+Capitalizatoin.swift
[12:31:14]: ▸ Compiling FeedEntry.swift
[12:31:14]: ▸ Compiling AlertConveniences.swift
[12:31:14]: ▸ Compiling UIColor+Manabi.swift
[12:31:14]: ▸ Compiling FeedTableViewController.swift
[12:31:14]: ▸ Compiling Category.swift
[12:31:14]: ▸ Compiling ReaderViewController.swift
[12:31:14]: ▸ Compiling HistoryRecordController.swift
[12:31:14]: ▸ Compiling JMDictEntry.swift
[12:31:14]: ▸ Compiling OnboardingTips.swift
[12:31:14]: ▸ Compiling JMDict.swift
[12:31:15]: ▸ Compiling String+FindReplace.swift
[12:31:15]: ▸ Compiling HomeTableCategoryCell.swift
[12:31:15]: ▸ Compiling ArticleListCell.swift
[12:31:15]: ▸ Compiling HistoryViewController.swift
[12:31:15]: ▸ Compiling ManabiReadabilityContentProcessor.swift
[12:31:15]: ▸ Compiling MeCabNode.m
[12:31:16]: ▸ Compiling MeCabUtil.m
[12:31:17]: ▸ Linking ManabiReader
[12:31:17]: ▸ Copying Carthage/Build/iOS/Realm.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/Cache.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/RealmSwift.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/Yams.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/Result.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/SwiftHash.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/Muon.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/CDAlertView.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/JASON.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/SwiftSoup.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/UAProgressView.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/SDWebImage.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/Shimmer.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/SwiftReadability.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/FeedKit.framework
[12:31:17]: ▸ Copying Carthage/Build/iOS/SnapKit.framework
[12:31:17]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Realm.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Cache.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/RealmSwift.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Yams.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Result.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/SwiftHash.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Muon.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/CDAlertView.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/JASON.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/SwiftSoup.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/UAProgressView.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/SDWebImage.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/Shimmer.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/SwiftReadability.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/FeedKit.framework
[12:31:18]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app/Frameworks/SnapKit.framework
[12:31:18]: ▸ Copying ManabiReader/Klee.ttc
[12:31:18]: ▸ Copying ManabiReader/jmdict.realm
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-HeavyItalic.ttf
[12:31:18]: ▸ Copying ManabiReader/jquery-3.2.1.min.js
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/rewrite.def
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/unk.dic
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/dicrc
[12:31:18]: ▸ Copying Settings.bundle
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Bold.ttf
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Light.ttf
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Italic.ttf
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/sys.dic
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-BoldItalic.ttf
[12:31:18]: ▸ Copying ManabiReader/manabi_readability.js
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-BlackItalic.ttf
[12:31:18]: ▸ Copying ManabiReader/manabi_readability.css
[12:31:18]: ▸ Copying Vendor/mecab-ios/libobjc/mecabrc
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Heavy.ttf
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/pos-id.def
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/right-id.def
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/left-id.def
[12:31:18]: ▸ Copying ManabiReader/manabi-reader.yml
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/matrix.bin
[12:31:18]: ▸ Copying ManabiReader/sample.html
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Regular.ttf
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-Black.ttf
[12:31:18]: ▸ Copying Vendor/mecab-ios/ipadic/char.bin
[12:31:18]: ▸ Copying ManabiReader/Lato/Lato-LightItalic.ttf
[12:31:18]: ▸ Compiling LaunchScreen.storyboard
[12:31:19]: ▸ Compiling Main.storyboard
[12:31:20]: ▸ Processing Info.plist
[12:31:20]: ▸ Generating 'ManabiReader.app.dSYM'
[12:31:21]: ▸ Running script 'Run Script'
[12:31:22]: ▸ Running script 'Run Script'
[12:31:23]: Running Tests: ▸ Touching ManabiReader.app
[12:31:23]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReader.app
[12:31:26]: ▸ Build Succeeded
[12:31:26]: ▸ 2017-06-25 12:31:26.343 xcodebuild[91160:13360981] [MT] IDETestOperationsObserverDebug: (A4B5AFE9-C8C8-4FB1-934B-06ED04A6CFE0) Beginning test session ManabiReaderScreenshotUITests-A4B5AFE9-C8C8-4FB1-934B-06ED04A6CFE0 at 2017-06-25 12:31:26.343 with Xcode 9M137d on target <DVTiPhoneSimulator: 0x7f8b3cb23e60> {
[12:31:26]: ▸ SimDevice: iPhone 6 (0B87F5E6-5578-4EC9-B1C8-7DE5F8D391B1, iOS 11.0, Booted)
[12:31:26]: ▸ } (11.0 (15A5304f))
[12:31:26]: ▸ 2017-06-25 12:31:26.343 xcodebuild[91160:13361335]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[12:31:26]: ▸ /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-A417359B-69F0-498A-9011-014D397E8CDF/ManabiReaderScreenshotUITests-80C27ADE-5098-40CE-91A2-F6BAED1E16E7/Session-ManabiReaderScreenshotUITests-2017-06-25_123126-6FL4hF.log
[12:31:26]: ▸ Building mecab/mecab [Debug]
[12:31:26]: ▸ Check Dependencies
[12:31:26]: ▸ Building ManabiReader/ManabiReader [Debug]
[12:31:26]: ▸ Check Dependencies
[12:31:26]: ▸ Running script 'Run Script'
[12:31:28]: ▸ Running script 'Run Script'
[12:31:28]: ▸ Building ManabiReader/ManabiReaderScreenshotUITests [Debug]
[12:31:28]: ▸ Check Dependencies
[12:31:28]: ▸ Processing Info.plist
[12:31:28]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework
[12:31:28]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework
[12:31:28]: ▸ Preprocessing /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents/XCTRunner.app/Info.plist
[12:31:28]: ▸ Compiling ManabiReaderScreenshotUITests.swift
[12:31:31]: ▸ Compiling SnapshotHelper.swift
[12:31:32]: ▸ Linking ManabiReaderScreenshotUITests
[12:31:33]: Running Tests: ▸ Touching ManabiReaderScreenshotUITests.xctest
[12:31:33]: ▸ Signing /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Build/Products/Debug-iphonesimulator/ManabiReaderScreenshotUITests-Runner.app/PlugIns/ManabiReaderScreenshotUITests.xctest
[12:31:51]: ▸ Test Succeeded
[12:31:51]: ▸ All tests
[12:31:51]: ▸ Test Suite ManabiReaderScreenshotUITests.xctest started
[12:31:51]: ▸ ManabiReaderScreenshotUITests
[12:31:51]: ▸ ✓ testScreenshots (12.426 seconds)
[12:31:51]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 12.426 (12.427) seconds
[12:31:51]: ▸
[12:31:51]: Collecting screenshots...
[12:31:51]: Found 2 screenshots...
[12:31:51]: Copying '/Users/alex/src/manabi-reader/fastlane/screenshots/en-US/iPhone6-0Home-d41d8cd98f00b204e9800998ecf8427e.png'...
[12:31:51]: No such file or directory @ rb_sysopen - /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Logs/Test/Attachments/Screenshot_7FE0A303-7FDA-400D-BFBC-472ED8602B43.png
[12:31:51]: Tests failed, re-trying 1 out of 2 times
[12:31:55]: Patching '/Users/alex/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[12:31:56]: ------------------------
[12:31:56]: --- iPhone 6 - en-US ---
[12:31:56]: ------------------------
[12:31:56]: $ set -o pipefail && xcodebuild -scheme ManabiReader -project ./ManabiReader.xcodeproj -derivedDataPath '/var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd' -destination 'platform=iOS Simulator,id=0B87F5E6-5578-4EC9-B1C8-7DE5F8D391B1,OS=11.0' FASTLANE_SNAPSHOT=YES build test | tee /Users/alex/Library/Logs/snapshot/ManabiReader-ManabiReader.log | xcpretty
[12:31:56]: ▸ Loading...
[12:31:57]: ▸ Building mecab/mecab [Debug]
[12:31:57]: ▸ Check Dependencies
[12:31:57]: ▸ Building ManabiReader/ManabiReader [Debug]
[12:31:57]: ▸ Check Dependencies
[12:31:57]: ▸ Running script 'Run Script'
[12:31:59]: ▸ Running script 'Run Script'
[12:31:59]: ▸ Build Succeeded
[12:31:59]: ▸ 2017-06-25 12:31:59.326 xcodebuild[91752:13367350] [MT] IDETestOperationsObserverDebug: (F010A5EC-C872-4A94-9B6C-8A58803725F8) Beginning test session ManabiReaderScreenshotUITests-F010A5EC-C872-4A94-9B6C-8A58803725F8 at 2017-06-25 12:31:59.326 with Xcode 9M137d on target <DVTiPhoneSimulator: 0x7f9963ca2fe0> {
[12:31:59]: ▸ SimDevice: iPhone 6 (0B87F5E6-5578-4EC9-B1C8-7DE5F8D391B1, iOS 11.0, Booted)
[12:31:59]: ▸ } (11.0 (15A5304f))
[12:31:59]: ▸ 2017-06-25 12:31:59.326 xcodebuild[91752:13367475]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[12:31:59]: ▸ /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/com.apple.dt.XCTest/IDETestRunSession-8A1D34A8-A98A-4EEA-868E-0088885E3042/ManabiReaderScreenshotUITests-64A67D79-F4FC-432D-8CDA-729F62006A6D/Session-ManabiReaderScreenshotUITests-2017-06-25_123159-tQZGhM.log
[12:31:59]: ▸ Building mecab/mecab [Debug]
[12:31:59]: ▸ Check Dependencies
[12:31:59]: ▸ Building ManabiReader/ManabiReader [Debug]
[12:31:59]: ▸ Check Dependencies
[12:31:59]: ▸ Running script 'Run Script'
[12:32:01]: ▸ Running script 'Run Script'
[12:32:01]: ▸ Building ManabiReader/ManabiReaderScreenshotUITests [Debug]
[12:32:01]: ▸ Check Dependencies
[12:32:23]: ▸ Test Succeeded
[12:32:23]: ▸ All tests
[12:32:23]: ▸ Test Suite ManabiReaderScreenshotUITests.xctest started
[12:32:23]: ▸ ManabiReaderScreenshotUITests
[12:32:23]: ▸ ✓ testScreenshots (12.487 seconds)
[12:32:23]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 12.487 (12.488) seconds
[12:32:23]: ▸
[12:32:23]: Collecting screenshots...
[12:32:23]: Found 2 screenshots...
[12:32:23]: Copying '/Users/alex/src/manabi-reader/fastlane/screenshots/en-US/iPhone6-0Home-d41d8cd98f00b204e9800998ecf8427e.png'...
[12:32:23]: No such file or directory @ rb_sysopen - /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Logs/Test/Attachments/Screenshot_44966137-D5A3-4DAE-9151-97EC8A873D0B.png

+----------+-------+
| snapshot results |
+----------+-------+
| Device   | en-US |
+----------+-------+
| iPhone 6 |  ❌   |
+----------+-------+


[!] No such file or directory @ rb_sysopen - /var/folders/d5/n8dq_3l90yj6_vdkbw05xgcw0000gn/T/snapshot_derived20170625-91091-l3cipd/Logs/Test/Attachments/Screenshot_44966137-D5A3-4DAE-9151-97EC8A873D0B.png
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.5                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.1                               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F2073)                       |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.41.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "ManabiReader") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    snapshot
    gym(scheme: "ManabiReader") # Build your app - more options available
    deliver(force: true)
    frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.manabi.ManabiReader" # The bundle identifier of your app
apple_id "alex.ehlke@gmail.com" # Your Apple email address

team_id "8Y769YTXHF" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-25**
</details>
```

### PR DESCRIPTION
**Pull request by ohayon**
This PR adds support for the new XCUISnapshot API in Xcdoe 9 and running more than one simulator for screenshot generation at once
- [x] only launch 1 sim per cpu -1 (unless there is only 1 cpu) available
- [x] ensure all devices are added for xcode 9
- [x] handle OS version for devices for destination flags

**All test cases we need to check**

- [x] works in xcode 8 with 1 device
- [x] works in xcode 8 with 2 devices
- [x] works in xcode 8 with 1 lang 1 device
- [x] works in xcode 8 with 2 lang 1 device
- [x] works in xcode 8 with 1 lang 2 device
- [x] works in xcode 8 with 2 lang 2 device

- [x] works in xcode 9 with 1 device
- [x] works in xcode 9 with 2 devices
- [x] works in xcode 9 with 1 lang 1 device
- [x] works in xcode 9 with 2 lang 1 device
- [x] works in xcode 9 with 1 lang 2 device
- [x] works in xcode 9 with 2 lang 2 device
- [x] add_media(device_type, media_type, paths) work with concurrent sims

note: this will also fix: https://github.com/fastlane/fastlane/issues/9579

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">You modified <code>SnapshotHelper.swift</code>, make sure to update the version number at the bottom of the file to notify users about the new helper file.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: snapshot/lib/snapshot/collector.rb [hunk 1]
```diff
@@ -26,18 +27,21 @@ def self.fetch_screenshots(output, dir_name, device_type, launch_arguments_index
         FileUtils.mkdir_p(language_folder)
 
         device_name = device_type.delete(" ")
+        # TODO: ASK FELIX ABOUT THIS!
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/collector.rb]: Hu?

File: snapshot/lib/assets/SnapshotHelper.swift [hunk 2]
```diff
@@ -7,7 +7,7 @@
 //
 
 // -----------------------------------------------------
-// IMPORTANT: When modifying this file, make sure to
```
Comment (KrauseFx) [inline snapshot/lib/assets/SnapshotHelper.swift]: With this file being modified, will we be able to support both Xcode 8 and Xcode 9 in parallel?

File: snapshot/lib/snapshot/collector.rb [hunk 3]
```diff
@@ -30,7 +30,7 @@ def self.fetch_screenshots(output, dir_name, device_type, launch_arguments_index
         filename = to_store[index]
 
         device_name = device_type.delete(" ")
-        # TODO: ASK FELIX ABOUT THIS!
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/collector.rb]: 😂

Comment (KrauseFx) [inline snapshot/lib/snapshot/collector.rb]: best commit message also cc @b3ll

File: fastlane.gemspec [hunk 4]
```diff
@@ -64,6 +64,7 @@ Gem::Specification.new do |spec|
   spec.add_dependency 'bundler', '>= 1.12.0', '< 2.0.0' # Used for fastlane plugins
   spec.add_dependency 'faraday', '~> 0.9' # Used for deploygate, hockey and testfairy actions
   spec.add_dependency 'faraday_middleware', '~> 0.9' # same as faraday
+  spec.add_dependency 'os', '~> 0.9' # Used to get CPU count for Xcode 9 multiple sim support
```
Comment (KrauseFx) [inline fastlane.gemspec]: Do we need this dependency? Would there be an easy way for us to get this working without it?

File: snapshot/lib/snapshot/reports_generator.rb [hunk 5]
```diff
@@ -37,9 +37,9 @@ def generate
       system("open '#{export_path}'") unless Snapshot.config[:skip_open_summary]
     end
 
-    def available_devices
+    def xcode_8_and_below_device_name_mappings
```
Comment (ohayon) [inline snapshot/lib/snapshot/reports_generator.rb]: ❤️

File: fastlane.gemspec (hunk 4 above)
Comment (KrauseFx) [inline fastlane.gemspec]: ^

File: snapshot/lib/assets/SnapshotHelper.swift [hunk 6]
```diff
@@ -33,19 +33,26 @@ func snapshot(_ name: String, waitForLoadingIndicator: Bool = true) {
...
 open class Snapshot: NSObject {
+    static var app: XCUIApplication!
+    static var cacheDirectory: URL!
+    static var screenshotsDirectory: URL? {
+        return cacheDirectory.appendingPathComponent("screenshots", isDirectory: true)
+    }
 
     open class func setupSnapshot(_ app: XCUIApplication) {
+        guard let cacheDir = pathPrefix else {
+            print("Problem locating the fastlane cache directory")
```
Comment (KrauseFx) [inline snapshot/lib/assets/SnapshotHelper.swift]: Can we print out more information on how to resolve this?

File: snapshot/lib/assets/SnapshotHelper.swift [hunk 7]
```diff
@@ -110,7 +109,14 @@ open class Snapshot: NSObject {
...
             XCUIApplication().typeKey(XCUIKeyboardKeySecondaryFn, modifierFlags: [])
         #else
-            XCUIDevice.shared().orientation = .unknown
+            let screenshot = app.windows.firstMatch.screenshot()
+            guard let simulator = ProcessInfo().environment["SIMULATOR_DEVICE_NAME"], let screenshotsDir = screenshotsDirectory else { return }
+            let path = screenshotsDir.appendingPathComponent("\(simulator)-\(name).png")
+            do {
+                try screenshot.pngRepresentation.write(to: path)
+            } catch {
+                print("Problem writing screenshot: \(name) to \(path)")
```
Comment (KrauseFx) [inline snapshot/lib/assets/SnapshotHelper.swift]: Can we print the actual error message here to make it easier for people to resolve the problem?

File: snapshot/lib/snapshot.rb [hunk 8]
```diff
@@ -6,12 +6,16 @@
...
 require 'snapshot/test_command_generator'
+require 'snapshot/test_command_generator_xcode_8'
 require 'snapshot/error_handler'
 require 'snapshot/collector'
 require 'snapshot/options'
 require 'snapshot/update'
 require 'snapshot/fixes/simulator_zoom_fix'
 require 'snapshot/fixes/hardware_keyboard_fix'
+require 'snapshot/simulator_launchers/launcher_configuration'
+require 'snapshot/simulator_launchers/simulator_launcher'
```
Comment (KrauseFx) [inline snapshot/lib/snapshot.rb]: Sounds like 🚀 launcher, I love it

File: snapshot/lib/snapshot/collector.rb [hunk 9]
```diff
@@ -7,8 +7,15 @@ def self.fetch_screenshots(output, dir_name, device_type, launch_arguments_index
       containing = File.join(TestCommandGenerator.derived_data_path, "Logs", "Test")
       attachments_path = File.join(containing, "Attachments")
 
-      to_store = attachments(containing)
-      matches = output.scan(/snapshot: (.*)/)
+      language_folder = File.join(Snapshot.config[:output_directory], dir_name)
+      FileUtils.mkdir_p(language_folder)
+
+      if Snapshot.config[:simultaneous] || Helper.xcode_at_least?(9)
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/collector.rb]: I don't understand that `||`, what if it's Xcode 8, but `simultaneous` is true? Can this ever be the case?

File: snapshot/lib/snapshot/collector.rb [hunk 10]
```diff
@@ -7,8 +7,15 @@ def self.fetch_screenshots(output, dir_name, device_type, launch_arguments_index
...
+        return collect_screenshots_for_language_folder(language_folder)
+      else
+        to_store = attachments(containing)
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/collector.rb]: Maybe add a few lines of comment on why this `if else` block exists, and how the plist format has changes with this release

File: snapshot/lib/snapshot/options.rb [hunk 11]
```diff
@@ -181,7 +181,17 @@ def self.available_options
...
-                                     is_string: false)
+                                     is_string: false),
+        FastlaneCore::ConfigItem.new(key: :simultaneous,
+                                     env_name: "SNAPSHOT_EXECUTE_TESTS_SIMULTANEOUSLY",
+                                     description: "Take snapshots on multiple devices at once",
+                                     default_value: false,
+                                     is_string: false,
+                                     verify_block: proc do |value|
+                                       if value && !Helper.xcode_at_least?('9.0')
+                                         UI.user_error('Executing snapshot on multiple simulators at once is only supported in Xcode 9 and higher.')
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/options.rb]: Let's remove the `.` at the end of `user_error!`

ok, this line answers my other question, but then the other `if` statement is more confusing even I think

File: snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+    attr_accessor :number_of_retries
+    attr_accessor :stop_after_first_error
+    attr_accessor :output_simulator_logs
+
+    # runner
+    attr_accessor :launch_args_set
+    attr_accessor :output_directory
+
+    def initialize(snapshot_config: nil)
+      @languages = snapshot_config[:languages]
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb]: omg.... what is this, Java?

Just joking, it looks nice, but we could also use some Ruby magic if we wanted to, something along the lines of iterating over all values in `snapshot_config` and then calling the setter for `self` for each of the keys. But this is fine too, it's more explicit

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb [hunk 13]
```diff
@@ -0,0 +1,74 @@
+require 'snapshot/simulator_launchers/simulator_launcher_base'
+
+module Snapshot
+  class SimulatorLauncher < SimulatorLauncherBase
+    def default_number_of_simultaneous_simulators
+      cpu_count = OS.cpu_count
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: This will need some comments, I can imagine why we do this, but it would be good to have it documented here

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb [hunk 14]
```diff
@@ -0,0 +1,129 @@
...
+      prepare_simulators_for_launch(language: language, locale: locale)
+    end
+
+    def prepare_simulators_for_launch(language: nil, locale: nil)
+      # Kill and shutdown all currently running simulators so that the following settings
+      # changes will be picked up when they are started again.
+      Snapshot.kill_simulator # because of https://github.com/fastlane/snapshot/issues/337
+      `xcrun simctl shutdown booted &> /dev/null`
+
+      Fixes::SimulatorZoomFix.patch
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb]: It might be worth evaluating if we still need those workarounds, probably not in the scope of this PR, but something to keep in mind.

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb [hunk 15]
```diff
@@ -0,0 +1,107 @@
...
+        }
+      ]
+
+      FastlaneCore::CommandExecutor.execute(command: command,
+                                          print_all: true,
+                                      print_command: true,
+                                             prefix: prefix_hash,
+                                            loading: "Loading...",
+                                              error: proc do |output, return_code|
+                                                ErrorHandler.handle_test_error(output, return_code)
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb]: I know this probably like this before, but it might be worth moving this into its own function for better readability 👍

File: snapshot/lib/snapshot/test_command_generator_base.rb [hunk 16]
```diff
@@ -0,0 +1,94 @@
+module Snapshot
+  class TestCommandGeneratorBase
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/test_command_generator_base.rb]: I love this 😍

File: snapshot/lib/snapshot/test_command_generator_base.rb [hunk 17]
```diff
@@ -0,0 +1,94 @@
...
+      def initialize
+        not_implemented(__method__)
+      end
+
+      def pipe(device_type, language, locale)
+        not_implemented(__method__)
+      end
+
+      def destination(device_name)
+        not_implemented(__method__)
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/test_command_generator_base.rb]: ❤️

File: snapshot/lib/snapshot/test_command_generator_xcode_8.rb [hunk 18]
```diff
@@ -0,0 +1,63 @@
...
+        return ["-destination 'platform=macOS'"] if device_name =~ /^Mac/
+
+        # if device_name is nil, use the config and get all devices
+        os = device_name =~ /^Apple TV/ ? "tvOS" : "iOS"
+        os_version = Snapshot.config[:ios_version] || Snapshot::LatestOsVersion.version(os)
+
+        device = find_device(device_name, os_version)
+        if device.nil?
+          UI.user_error!("No device found named '#{device_name}' for version '#{os_version}'")
+          return
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/test_command_generator_xcode_8.rb]: Unreachable code detected. `user_error!` will raise an exception

File: snapshot/lib/snapshot/test_command_generator_xcode_8.rb [hunk 19]
```diff
@@ -0,0 +1,63 @@
+require 'snapshot/test_command_generator_base'
+
+module Snapshot
+  # Responsible for building the fully working xcodebuild command
+  class TestCommandGeneratorXcode8 < TestCommandGeneratorBase
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/test_command_generator_xcode_8.rb]: Maybe some comments here and in the other classes explaining the differences between how it works with Xcode 8 and Xcode 9

File: snapshot/spec/test_command_generator_xcode_8_spec.rb [hunk 20]
```diff
@@ -0,0 +1,257 @@
+describe Snapshot do
+  describe Snapshot::TestCommandGeneratorXcode8 do
```
Comment (KrauseFx) [inline snapshot/spec/test_command_generator_xcode_8_spec.rb]: Beautiful ❤️

**Review by KrauseFx — COMMENTED** [review]
That is an awesome PR, great work @ohayon and @taquitos, I did a quick review over the changes, I love it. 

This seems such a big change, so having a slow rollout might be a good idea, which we can easily have by launching this as soon as we merged, before Xcode 9 is out. This way we can make sure Xcode 8 keeps working as expected, and then slowly more and more people will start using Xcode 9 👍 

Let's evaluate if it's worth adding another dependency, ideally we can do it without it :) 

I didn't do any actual testing, just a review of the code.

💯 🚀 ✨

**Comment by taquitos** [comment]
@KrauseFx 
>Let's evaluate if it's worth adding another dependency
Before I added `os` I searched through the Gemfile.lock to see if we had it transitively included due to another gem, and we did 🍾 so for right now, I think it's 👌 
We could get access to this info in another way, like copying the relevant 30 lines or so from that gem 🙃

File: snapshot/lib/assets/SnapshotHelper.swift (hunk 2 above)
Comment (taquitos) [inline snapshot/lib/assets/SnapshotHelper.swift]: The version is bumped up in this file, and there's a new `SnapshotHelperXcode8.swift`. I think when you run _snapshot_ for after updating _fastlane_ it will point you to the next `SnapshotHelperXcode8.swift`... I think, we need to test it 🍵

File: fastlane.gemspec (hunk 4 above)
Comment (taquitos) [inline fastlane.gemspec]: Before I added os I searched through the Gemfile.lock to see if we had it transitively included due to another gem, and we did 🍾 so for right now, I think it's 👌
We could get access to this info in another way, like copying the relevant 30 lines or so from that gem 🙃

File: snapshot/lib/snapshot/collector.rb (hunk 9 above)
Comment (taquitos) [inline snapshot/lib/snapshot/collector.rb]: This still needs to be broken down a little more because it doesn't make a ton of sense

File: snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb (hunk 12 above)
Comment (taquitos) [inline snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb]: I was thinking about that... that's not too magical? 🤣 

Java Beans are the best [ducks behind table]

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb (hunk 13 above)
Comment (taquitos) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: I agree, we haven't linked it up yet, but that's good to call out. We did some testing and having too many sims causes serious perf issues.

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb (hunk 14 above)
Comment (taquitos) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb]: Agreed, we can follow up in another patch.

File: snapshot/lib/snapshot/collector.rb (hunk 9 above)
Comment (ohayon) [inline snapshot/lib/snapshot/collector.rb]: Yeah, this is really just going to be if Xcode is at least 9, the simultaneous part doesn't matter so much anymore.

File: snapshot/lib/snapshot/test_command_generator.rb [hunk 21]
```diff
@@ -4,15 +4,15 @@ module Snapshot
...
         parts = prefix
         parts << "xcodebuild"
         parts += options
-        parts += destination(device_type)
+        parts += destination(devices)
         parts += build_settings
         parts += actions
         parts += suffix
-        parts += pipe(device_type, language, locale)
+        # parts += pipe(devices, language, locale)
```
Comment (ohayon) [inline snapshot/lib/snapshot/test_command_generator.rb]: I commented this out for now, we'll need to figure out how to handle logging.

File: snapshot/lib/snapshot/test_command_generator.rb [hunk 22]
```diff
@@ -58,11 +58,11 @@ def verify_devices_share_os(devices)
         return devices.count == 1
       end
 
-      def xcodebuild_log_path(device_type: nil, language: nil, locale: nil)
+      def xcodebuild_log_path(devices: nil, language: nil, locale: nil)
         name_components = [Snapshot.project.app_name, Snapshot.config[:scheme]]
```
Comment (ohayon) [inline snapshot/lib/snapshot/test_command_generator.rb]: Currently this is working, but the second execution (if there are more simulators than cores on the machine) will overwrite the first execution's logs. Thinking maybe we should concatenate these, but because of the `:namespace_log_files` param that is checked below, that throws a bit of a wrench into that.

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb [hunk 23]
```diff
@@ -75,4 +75,30 @@ def launch_simultaneously(devices, language, locale, launch_arguments)
...
+    end
+
+    def self.cpu_count
+      @cpu_count ||=
+        case RUBY_PLATFORM
+        when /darwin9/
+          `hwprefs cpu_count`.to_i
+        when /darwin10/
+          (hwprefs_available? ? `hwprefs thread_count` : `sysctl -n hw.physicalcpu_max`).to_i
+        when /linux/
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: Does it make sense to include those if snapshot only works on macOS?

File: snapshot/lib/snapshot/options.rb [hunk 24]
```diff
@@ -182,16 +182,11 @@ def self.available_options
                                      description: "Separate the log files per device and per language",
                                      optional: true,
                                      is_string: false),
-        FastlaneCore::ConfigItem.new(key: :simultaneous,
-                                     env_name: "SNAPSHOT_EXECUTE_TESTS_SIMULTANEOUSLY",
-                                     description: "Take snapshots on multiple devices at once",
+        FastlaneCore::ConfigItem.new(key: :serialized_executions,
```
Comment (taquitos) [inline snapshot/lib/snapshot/options.rb]: how about `non_concurrent_simulators` I think `serialized` is a bit confusing.
Also this property is about disabling something, so I like how `non_concurrent_simulators` sounds like it is disabling a feature.

File: snapshot/lib/snapshot/options.rb [hunk 25]
```diff
@@ -182,16 +182,11 @@ def self.available_options
...
+                                     env_name: "SNAPSHOT_EXECUTE_SERIALIZED_TESTS",
```
Comment (taquitos) [inline snapshot/lib/snapshot/options.rb]: so this would be `SNAPSHOT_NON_CONCURRENT_SIMULATORS`

File: snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb [hunk 26]
```diff
@@ -21,6 +21,9 @@ class SimulatorLauncherConfiguration
     attr_accessor :launch_args_set
     attr_accessor :output_directory
 
+    # xcode 9
+    attr_accessor :serialized_executions
```
Comment (taquitos) [inline snapshot/lib/snapshot/simulator_launchers/launcher_configuration.rb]: and I'd want to change this name here too, maybe make it a method `non_concurrent_simulators?`

File: snapshot/lib/snapshot/options.rb [hunk 27]
```diff
@@ -181,6 +181,11 @@ def self.available_options
                                      env_name: "SNAPSHOT_NAMESPACE_LOG_FILES",
                                      description: "Separate the log files per device and per language",
                                      optional: true,
+                                     is_string: false),
+        FastlaneCore::ConfigItem.new(key: :concurrent_simulators,
+                                     env_name: "SNAPSHOT_EXECUTE_CONCURRENT_SIMULATORS",
+                                     description: "Take snapshots on multiple simulators concurrently",
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/options.rb]: Maybe add a note to the `description` that this only works on Xcode 9 and above?

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb [hunk 28]
```diff
@@ -0,0 +1,140 @@
+require 'snapshot/simulator_launchers/simulator_launcher_base'
+
+module Snapshot
+  class SimulatorLauncher < SimulatorLauncherBase
+    def default_number_of_simultaneous_simulators
```
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: Maybe we can add a comment here on why we do this? Would be good for future reference

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb (hunk 23 above)
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: ☝️ 👍

Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher.rb]: We could `UI.user_error!` if it's not macOS at this point (if we don't already to that at _snapshot_ somewhere)

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb (hunk 15 above)
Comment (KrauseFx) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb]: ☝️ optional, but something to maybe consider :)

**Review by KrauseFx — APPROVED** [review]
Awesome PR, great work @ohayon 👍  A few smaller comments, none of them blocking 😃

**Comment by KrauseFx** [comment]
screen shot 2017-08-16 at 5 52 29 pm

I tried running the most recent code from this branch, with the Xcode Beta 4 (I know, not the most recent, but I'm on a bus right now). It seems like the UI Tests failed from the snapshot example project, which is fine, but I'm a little confused on how I can find out what failed, where can I find the half-done screenshots, and where do I see the log? Did it fail on all the devices, or just some? 

Not sure if that's related to the Xcode Beta I'm using, or if it's a user error on my side :)

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb (hunk 15 above)
Comment (ohayon) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_xcode_8.rb]: Do you mean to extract the error block? Or the full call to `FastlaneCore::CommandExecutor`?

**Review by taquitos — APPROVED** [review]
Yesssss

File: snapshot/lib/snapshot/runner.rb [hunk 29]
```diff
@@ -95,15 +95,14 @@ def self.path_to_helper_file_from_gem
...
       asset_path = self.class.path_to_helper_file_from_gem
       regex_to_use = Helper.xcode_at_least?("9.0") ? /\n.*SnapshotHelperVersion \[.+\]/ : /\n.*SnapshotHelperXcode8Version \[.+\]/
 
       bundled_helper = File.read(asset_path)
       current_version = bundled_helper.match(regex_to_use)[0]
 
-      ## Something like "// SnapshotHelperVersion [1.2]", but be relaxed about whitespace
-      current_version.gsub(%r{^//\w*}, '').strip
+      # Something like "// SnapshotHelperVersion [1.2]", but be relaxed about whitespace
+      return current_version.gsub(%r{^//\w*}, '').strip
```
Comment (taquitos) [inline snapshot/lib/snapshot/runner.rb]: returns are the best 🥅      ⚽️ 🐐

File: snapshot/lib/snapshot/update.rb [hunk 30]
```diff
@@ -21,7 +21,7 @@ def update
       paths.each do |path|
         UI.message "Updating '#{path}'..."
         input_path = Snapshot::Runner.path_to_helper_file_from_gem
-        File.write(path, File.read(input_path)) #File.read("#{Snapshot::ROOT}/lib/assets/SnapshotHelper.swift"))
+        File.write(path, File.read(input_path)) # File.read("#{Snapshot::ROOT}/lib/assets/SnapshotHelper.swift"))
```
Comment (taquitos) [inline snapshot/lib/snapshot/update.rb]: Spaces are pretty cool too

**Comment by casz** [comment]
Poor googlebot 💜

**Comment by fishcharlie** [comment]
I don’t see any documentation about this. How can I enable this or use it?
