### PR TITLE
Use new TestFlight API to find testers by full-text search

### LINKED ISSUE #9973: pilot find/remove fails with "undefined method `admin?' for nil:NilClass"
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My iTunes Connect account has an `App Manager` role, when I try to use pilot to manage testers, it always fails with the same error:

>PS: I can use this account to manage (search/add/remove) my testers on the iTunes Connect Web, and that's what I do all the time. 

The command I use:

```
fastlane pilot find someont@test.com -a com.xxx.xxx -u <my account>

or

fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account>
```

And the error message:

```
undefined method `admin?' for nil:NilClass

[!] Some operations failed: undefined method `admin?' for nil:NilClass
```

The `--capture_output` argument seems doesn't exist:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --capture_output

invalid option: --capture_output
```

So I use `--verbose` option:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --verbose
```

And the verbose output is here:

```
ERROR [2017-08-07 09:54:39.09]: undefined method `admin?' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: undefined method `admin?' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version                    | Update-Status |
| -------- | -------------------------- | ------------- |
| fastlane | 2.51.0.beta.20170807010003 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-08-07**
</details>

Thank you very much for any help!

### PR DESCRIPTION
**Pull request by taquitos**
The original way we were finding testers was by trying to grab all testers and then filter them. Turns out, the API doesn't return all testers anymore, just a max of 40. 

BUT

We have a new full-text search API to play with, and we can pass in email addresses 🎉 
This PR changes TestFlight::Tester.find to .search and uses the new api.
Should fix #9973

### CODE REVIEW

File: spaceship/lib/spaceship/test_flight/tester.rb [hunk 1]
```diff
@@ -20,11 +20,13 @@ def self.all(app_id: nil)
...
-    # @return (Spaceship::TestFlight::Tester) Returns the tester matching the parameter
-    #   as either the Tester id or email
-    # @param email (String) (required): Value used to filter the tester, case insensitive
-    def self.find(app_id: nil, email: nil)
-      self.all(app_id: app_id).find { |tester| tester.email == email }
+    # @return (Spaceship::TestFlight::Tester) Returns the testers matching the parameter.
+    # ITC searchs all fields, and is full text. The search results are the union of all words in the search text
+    # @param text (String) (required): Value used to filter the tester, case insensitive
+    def self.search(app_id: nil, text: nil)
+      testers_matching_email = client.search_for_tester_in_app(app_id: app_id, text: text).map { |data| self.new(data) }
```
Comment (mpirri) [inline spaceship/lib/spaceship/test_flight/tester.rb]: Name `testers_matching_email` should probably be `testers_matching_text`, since we are searching on any text match?

File: spaceship/lib/spaceship/test_flight/tester.rb [hunk 2]
```diff
@@ -20,11 +20,13 @@ def self.all(app_id: nil)
       client.testers_for_app(app_id: app_id).map { |data| self.new(data) }
     end
 
-    # @return (Spaceship::TestFlight::Tester) Returns the tester matching the parameter
-    #   as either the Tester id or email
-    # @param email (String) (required): Value used to filter the tester, case insensitive
-    def self.find(app_id: nil, email: nil)
```
Comment (mpirri) [inline spaceship/lib/spaceship/test_flight/tester.rb]: Do we want to deprecate this method name and point it at the new method to keep this from breaking other `spaceship` users?

File: pilot/lib/pilot/tester_manager.rb [hunk 3]
```diff
@@ -67,7 +67,14 @@ def remove_tester(options)
         # If no groups are passed to options, remove the tester from the app-level,
         # otherwise remove the tester from the groups specified.
         if config[:groups].nil? && tester.kind_of?(Spaceship::Tunes::Tester::External)
-          test_flight_tester = Spaceship::TestFlight::Tester.find(app_id: app.apple_id, email: tester.email)
+          test_flight_testers = Spaceship::TestFlight::Tester.search(app_id: app.apple_id, text: tester.email)
```
Comment (mpirri) [inline pilot/lib/pilot/tester_manager.rb]: Is there any chance that a field other than email might match on an email address?  I'm guessing no, since the structure is pretty simple, but it would kind of suck if we removed the wrong tester because of a false-positive.  (one possible work around could be just to filter the found list of testers on found_tester.email = tester.email or something?) . I might be making something out of nothing here, though.

File: spaceship/lib/spaceship/test_flight/tester.rb (hunk 2 above)
Comment (taquitos) [inline spaceship/lib/spaceship/test_flight/tester.rb]: good point!

File: spaceship/lib/spaceship/test_flight/tester.rb (hunk 1 above)
Comment (taquitos) [inline spaceship/lib/spaceship/test_flight/tester.rb]: 💯

File: pilot/lib/pilot/tester_manager.rb (hunk 3 above)
Comment (taquitos) [inline pilot/lib/pilot/tester_manager.rb]: Yes, this could totally happen. I was thinking we should rely on the caller to understand this (which is why I renamed it search, and added the comment about it being full-text). That being said... one thing I could do is add another optional param for "is_exact_email_match" or something like that, so it does that filtering you mention.

File: spaceship/lib/spaceship/test_flight/client.rb [hunk 4]
```diff
@@ -112,6 +112,14 @@ def delete_tester_from_app(app_id: nil, tester_id: nil)
...
     end
 
+    def search_for_tester_in_app(app_id: nil, text: nil)
+      assert_required_params(__method__, binding)
+      text = CGI.escape(text)
+      url = "providers/#{team_id}/apps/#{app_id}/testers?order=asc&search=#{text}&sort=status"
+      response = request(:get, url)
+      handle_response(response)
+    end
+
```
Comment (snatchev) [inline spaceship/lib/spaceship/test_flight/client.rb]: Can we get a spec that `search_for_tester_in_app` calls the expected URL with params? ☺️ 

https://github.com/fastlane/fastlane/blob/master/spaceship/spec/test_flight/client_spec.rb#L169

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Spaceship::TestFlight::Client#search_for_tester_in_app executes the request | <a href='https://github.com/fastlane/fastlane/blob/0b57a64631e27decac26c7a57b63d9ca957fe3bc/./spaceship/spec/test_flight/client_spec.rb'>client_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: pilot/lib/pilot/tester_manager.rb (hunk 3 above)
Comment (mpirri) [inline pilot/lib/pilot/tester_manager.rb]: True, but the `search` method is at the `spaceship` level, while this is in `pilot` (and the parameter here is "email", not a more generic "test").  So, it seems cool for `pilot` to use `search` to look for text matches for the email, but `pilot` should probably assert that it is an email match before doing the removal, no?

Comment (taquitos) [inline pilot/lib/pilot/tester_manager.rb]: Yeah, I was relying on the fall through logic to catch matches that are > 1, but you make a good point. I just updated it so pass in the `is_email_exact_match` params as `true` to get this behavior.

File: spaceship/lib/spaceship/test_flight/client.rb (hunk 4 above)
Comment (taquitos) [inline spaceship/lib/spaceship/test_flight/client.rb]: @snatchev youGotItDude.gif, updated!

**Review by mpirri — APPROVED** [review]
👍
