### PR TITLE
[fastlane] fix FastlaneCore::BuildWatcher from erroring on multiple builds found

### LINKED ISSUE #15007: [Pilot] FastlaneCore::BuildWatcher found more than 1 matching build
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.127.0`]
- Last working version: [e.g. `2.126.0`]

### Regression Description
After a successful gym and read_changelog, starting the pilot command job failed 

##### Complete output when running fastlane, including the stack trace and command used
After 
```
INFO [2019-07-10 17:53:30.37]: [32m-----------------------------------------------------[0m
INFO [2019-07-10 17:53:30.37]: [32mSuccessfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.[0m
INFO [2019-07-10 17:53:30.37]: [32m-----------------------------------------------------[0m
INFO [2019-07-10 17:53:30.38]: [32mSuccessfully uploaded the new binary to App Store Connect[0m
fastlane got error
> FastlaneCore::BuildWatcher found more than 1 matching build
```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.4                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1 (Apple Git-117)          |
| Installation Source         | ~/.rbenv/versions/2.4.2/bin/fastlane        |
| Host                        | Mac OS X 10.14.4 (18E226)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.2/lib                 |
| OpenSSL Version             | OpenSSL 1.1.0i  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

<details>
  <pre>### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.127.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.4   | ✅ Up-To-Date  |
| fastlane-plugin-changelog  | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.1.0        |
| slack-notifier             | 2.3.2        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| terminal-table             | 1.8.0        |
| CFPropertyList             | 3.0.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| public_suffix              | 2.0.5        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.6        |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 1.0.0        |
| bundler                    | 1.17.1       |
| jwt                        | 2.1.0        |
| tty-cursor                 | 0.7.0        |
| tty-spinner                | 0.9.1        |
| tty-screen                 | 0.7.0        |
| faraday                    | 0.15.4       |
| openssl                    | 2.0.5        |
| json                       | 2.2.0        |
| excon                      | 0.64.0       |
| rubyzip                    | 1.2.3        |
| plist                      | 3.5.0        |
| atomos                     | 0.1.3        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.10.0       |
| faraday_middleware         | 0.13.1       |
| multi_json                 | 1.13.1       |
| signet                     | 0.11.0       |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.1.0        |
| google-cloud-core          | 1.3.0        |
| digest-crc                 | 0.4.1        |
| google-cloud-storage       | 1.16.0       |
| memoist                    | 0.16.0       |
| googleauth                 | 0.6.7        |
| fastimage                  | 2.1.5        |
| io-console                 | 0.4.6        |
| unicode-display_width      | 1.6.0        |
| dotenv                     | 2.7.2        |
| addressable                | 2.6.0        |
| os                         | 1.0.1        |
| psych                      | 2.2.2        |
| retriable                  | 3.1.2        |
| mime-types                 | 3.2.2        |
| mime-types-data            | 3.2019.0331  |
| fastlane-plugin-versioning | 0.3.4        |
| fastlane-plugin-changelog  | 0.15.0       |
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #15007

### Motivation and Context
Prevent `FastlaneCore::BuildWatcher` from raising error that there were multiple builds being watched

### Description
1. Turns out this issue was from `app_version = train_version` being set in the wrong place so `app_version` was getting nil-ed 🙄 
2. Made a more descriptive error if (for some reason) the fetching of builds does return more than 1 build
3. Added output to show what build watcher is watching

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/build_watcher.rb [hunk 1]
```diff
@@ -10,14 +10,17 @@ def wait_for_build_processing_to_be_complete(app_id: nil, platform: nil, train_v
...
         end
-        app_version = train_version
 
         # Warn about strict_build_watch being removed in the future
         if strict_build_watch
           UI.deprecated(":strict_build_watch is no longer a used argument on FastlaneCore::BuildWatcher.")
         end
 
+        platform = Spaceship::ConnectAPI::Platform.map(platform) if platform
+        UI.message("Waiting for processing on... app_id: #{app_id}, app_version: #{app_version}, build_version: #{build_version}, platform: #{platform}")
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/build_watcher.rb]: If I understood line 21 correctly, this could be missing `platform` if `platform` isn't defined before already. Might that be a problem?

File: fastlane_core/spec/build_watcher_spec.rb [hunk 2]
```diff
@@ -2,111 +2,22 @@
 
 describe FastlaneCore::BuildWatcher do
   context '.wait_for_build_processing_to_be_complete' do
-    let(:processing_build) do
```
Comment (janpio) [inline fastlane_core/spec/build_watcher_spec.rb]: why is this (and following removed lines) not needed any more?

Comment (joshdholtz) [reply fastlane_core/spec/build_watcher_spec.rb]: This was a duplicate that should have deleted a while ago when build watcher changed over from using `Spaceship::TestFlight` to `Spaceship::ConnectAPI`

File: fastlane_core/lib/fastlane_core/build_watcher.rb (hunk 1 above)
Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/build_watcher.rb]: This _could_ potentially? 🤔 We weren't explicitly erroring out on no platform before. Not sure if we should be now but this message and the error message of multiple builds _should_ be a good indication that `platform` is needed **if** someone is calling this manually (outside of `pilot`)

**Review by janpio — APPROVED** [review]
Moving of `app_version = train_version` makes sense, additional error message as well and better fallback output is nice.

File: fastlane_core/lib/fastlane_core/build_watcher.rb (hunk 1 above)
Comment (janpio) [reply fastlane_core/lib/fastlane_core/build_watcher.rb]: ah yeah, we were using the same code to set and use `platform` before - so this should not break anything.
