### PR TITLE
[deliver] fetch live app info if no edit info is present, fixing scenario of having both macOS and iOS apps present

### LINKED ISSUE #17321: [!] Cannot update languages - could not find an editable info - when trying to upload metadata
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm trying to upload metadata (what's new texts) for my iOS app. Previously it worked fine, but now it throws the following error: "[!] Cannot update languages - could not find an editable info". 
Probably it may be related to macOS app I have:
image

##### Command executed

fastlane deliver --force -u *** -a *** --skip_binary_upload true -i xxx.ipa -j ios -m /xxx/metadata --skip_screenshots true --phased_release

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
2020-09-25T13:13:10.1736880Z [command]fastlane deliver --force -u xxx -a xxx --skip_binary_upload true -i xxx.ipa -j ios -m /Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata --skip_screenshots true --phased_release
2020-09-25T13:13:13.4232470Z [16:13:13]: ‌Get started using a Gemfile for fastlane https:&#x2F;&#x2F;docs.fastlane.tools&#x2F;getting-started&#x2F;ios&#x2F;setup&#x2F;#use-a-gemfile‌
2020-09-25T13:13:15.0449350Z [16:13:15]: Login to App Store Connect (***)
2020-09-25T13:13:17.8127640Z [16:13:17]: Login successful
2020-09-25T13:13:22.6996440Z 
2020-09-25T13:13:22.7070940Z +--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2020-09-25T13:13:22.7088420Z |                                                                                          deliver 2.160.0 Summary                                                                                           |
2020-09-25T13:13:22.7105130Z +--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2020-09-25T13:13:22.7121640Z | force                                | true                                                                                                                                                                |
2020-09-25T13:13:22.7135530Z | username                             | ***                                                                                                                                      |
2020-09-25T13:13:22.7152160Z | app_identifier                       | ***                                                                                                                                        |
2020-09-25T13:13:22.7168670Z | skip_binary_upload                   | true                                                                                                                                                                |
2020-09-25T13:13:22.7187270Z | ipa                                  | ***.ipa |
2020-09-25T13:13:22.7208880Z | platform                             | ios                                                                                                                                                                 |
2020-09-25T13:13:22.7229620Z | metadata_path                        | /Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata                                                                                                            |
2020-09-25T13:13:22.7247480Z | skip_screenshots                     | true                                                                                                                                                                |
2020-09-25T13:13:22.7264490Z | phased_release                       | true                                                                                                                                                                |
2020-09-25T13:13:22.7279200Z | screenshots_path                     | ./screenshots                                                                                                                                                       |
2020-09-25T13:13:22.7293890Z | app_version                          | 2.35.0                                                                                                                                                              |
2020-09-25T13:13:22.7309000Z | edit_live                            | false                                                                                                                                                               |
2020-09-25T13:13:22.7323700Z | use_live_version                     | false                                                                                                                                                               |
2020-09-25T13:13:22.7336400Z | skip_metadata                        | false                                                                                                                                                               |
2020-09-25T13:13:22.7349020Z | skip_app_version_update              | false                                                                                                                                                               |
2020-09-25T13:13:22.7361610Z | overwrite_screenshots                | false                                                                                                                                                               |
2020-09-25T13:13:22.7374210Z | submit_for_review                    | false                                                                                                                                                               |
2020-09-25T13:13:22.7386820Z | reject_if_possible                   | false                                                                                                                                                               |
2020-09-25T13:13:22.7405230Z | automatic_release                    | false                                                                                                                                                               |
2020-09-25T13:13:22.7430450Z | reset_ratings                        | false                                                                                                                                                               |
2020-09-25T13:13:22.7450790Z | run_precheck_before_submit           | true                                                                                                                                                                |
2020-09-25T13:13:22.7468380Z | precheck_default_rule_level          | warn                                                                                                                                                                |
2020-09-25T13:13:22.7484640Z | ignore_language_directory_validation | false                                                                                                                                                               |
2020-09-25T13:13:22.7499430Z | precheck_include_in_app_purchases    | true                                                                                                                                                                |
2020-09-25T13:13:22.7518310Z +--------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2020-09-25T13:13:22.7529740Z 
2020-09-25T13:13:22.7545490Z [16:13:22]: Making sure the latest version on App Store Connect matches '2.35.0'...
2020-09-25T13:13:23.3209700Z [16:13:23]: '2.35.0' is the latest version on App Store Connect
2020-09-25T13:13:23.3236320Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/ar-SA/release_notes.txt'...
2020-09-25T13:13:23.3259980Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/de-DE/release_notes.txt'...
2020-09-25T13:13:23.3282050Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/en-AU/release_notes.txt'...
2020-09-25T13:13:23.3302820Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/en-GB/release_notes.txt'...
2020-09-25T13:13:23.3322940Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/en-US/release_notes.txt'...
2020-09-25T13:13:23.3342830Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/es-ES/release_notes.txt'...
2020-09-25T13:13:23.3361980Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/es-MX/release_notes.txt'...
2020-09-25T13:13:23.3380960Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/fr-FR/release_notes.txt'...
2020-09-25T13:13:23.3399070Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/id/release_notes.txt'...
2020-09-25T13:13:23.3417070Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/it/release_notes.txt'...
2020-09-25T13:13:23.3435150Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/ja/release_notes.txt'...
2020-09-25T13:13:23.3453160Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/ko/release_notes.txt'...
2020-09-25T13:13:23.3471470Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/pt-BR/release_notes.txt'...
2020-09-25T13:13:23.3489620Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/ru/release_notes.txt'...
2020-09-25T13:13:23.3507660Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/tr/release_notes.txt'...
2020-09-25T13:13:23.3525700Z [16:13:23]: Loading '/Users/jenkins/TFS/deployment_agent/_work/r13/a/metadata/uk/release_notes.txt'...
2020-09-25T13:13:25.4524020Z [16:13:25]: Cannot find edit app info... Retrying after 10 seconds (remaining: 4)
2020-09-25T13:13:36.3000560Z [16:13:36]: Cannot find edit app info... Retrying after 10 seconds (remaining: 3)
2020-09-25T13:13:47.3957290Z [16:13:47]: Cannot find edit app info... Retrying after 10 seconds (remaining: 2)
2020-09-25T13:13:58.5352910Z [16:13:58]: Cannot find edit app info... Retrying after 10 seconds (remaining: 1)
2020-09-25T13:14:09.3336970Z [16:14:09]: Cannot find edit app info... Retrying after 10 seconds (remaining: 0)
2020-09-25T13:14:19.3433860Z 
2020-09-25T13:14:19.3461320Z [!] Cannot update languages - could not find an editable info
</pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 10.15.6                                            |
| Ruby                        | 2.5.3                                              |
| Bundler?                    | false                                              |
| Git                         | git version 2.21.1 (Apple Git-122.3)               |
| Installation Source         | ~/.rvm/gems/ruby-2.5.3/bin/fastlane                |
| Host                        | Mac OS X 10.15.6 (19G2021)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.5.3/lib                       |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                        |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-11.3.1.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| executable-hooks          | 1.6.0        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.5        |
| bundler                   | 1.16.6       |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.75.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.17.1       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.5        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| unf_ext                   | 0.0.7.7      |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.6        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.1        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.3        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.345.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-25**
</details>
 </pre>
</details>

### LINKED ISSUE #21003: Unable to update macOS app metadata while iOS app is in Pending Developer Release: Cannot update languages - could not find an editable info
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

* We're about to publish a macOS app to App Store alongside our iOS app.
* fastlane fails when trying to update macOS app metadata when there's an iOS app in
  non-editable state (such as *Pending Developer Release* – see the screenshot below).
    * Note that I'm only trying to update macOS app specific metadata, not shared metadata like 
      App Store listing name, so iOS app being in non-editable state should not be blocking updates.
* There is a number of [similar issues reported already](https://github.com/fastlane/fastlane/issues?q=is%3Aissue+is%3Aclosed+could+not+find+an+editable+info+), and one of them suggests a fix:
  https://github.com/fastlane/fastlane/issues/17321.
    * The fix is to fetch both edit and live app infos when verifying available info languages.
    * I've applied that fix on top of 2.211.0 tag (see my changes [here](https://github.com/ayoy/fastlane/commit/019a2442407a069a8329a7ecb80d2d4bf154e4d9)) and I can confirm that it solves the issue for me.

If the fix looks acceptable, I'd be happy to submit a pull request. Thanks for looking into it!

Screenshot 2023-01-21 at 11 09 24

##### Command executed

    bundle exec fastlane deliver run --force \
      --platform osx \
      --skip_binary_upload true \
      --skip_screenshots true \
      --submit_for_review false \
      --skip_metadata false \
      --automatic_release false \
      --username **** \
      --app_identifier ****

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[✔] 🚀
[11:08:39]: Successfully loaded '/Users/***/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| platform              | osx                   |
+-----------------------+-----------------------+

[11:08:39]: Login to App Store Connect (****)
Available session is not valid any more. Continuing with normal login.
[11:08:43]: Login successful

+--------------------------------------+---------------------------+
|                     deliver 2.211.0 Summary                      |
+--------------------------------------+---------------------------+
| force                                | true                      |
| platform                             | osx                       |
| skip_binary_upload                   | true                      |
| skip_screenshots                     | true                      |
| submit_for_review                    | false                     |
| skip_metadata                        | false                     |
| automatic_release                    | false                     |
| username                             | ****   |
| app_identifier                       | **** |
| screenshots_path                     | ./fastlane/screenshots    |
| metadata_path                        | ./fastlane/metadata       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_app_version_update              | false                     |
| overwrite_screenshots                | false                     |
| sync_screenshots                     | false                     |
| verify_only                          | false                     |
| reject_if_possible                   | false                     |
| phased_release                       | false                     |
| reset_ratings                        | false                     |
| run_precheck_before_submit           | true                      |
| precheck_default_rule_level          | warn                      |
| ignore_language_directory_validation | false                     |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

[11:08:45]: Loading './fastlane/metadata/default/release_notes.txt'...
[11:08:45]: Loading './fastlane/metadata/en-US/description.txt'...
[11:08:45]: Loading './fastlane/metadata/en-US/keywords.txt'...
[11:08:45]: Loading './fastlane/metadata/en-US/support_url.txt'...
[11:08:45]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[11:08:45]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[11:08:45]: Loading './fastlane/metadata/copyright.txt'...
[11:08:45]: Detected languages: ["en-US", "default"]
[11:08:47]: Cannot find edit app info... Retrying after 10 seconds (remaining: 4)
[11:08:58]: Cannot find edit app info... Retrying after 10 seconds (remaining: 3)
[11:09:09]: Cannot find edit app info... Retrying after 10 seconds (remaining: 2)
[11:09:20]: Cannot find edit app info... Retrying after 10 seconds (remaining: 1)
[11:09:33]: Cannot find edit app info... Retrying after 10 seconds (remaining: 0)

[!] Cannot update languages - could not find an editable info
  </pre>
</details>

### Environment

Note that I've removed Fastfile and Appfile from _fastlane env_ output because I'm using deliver
straight off the command line. Let me know if you need to see these files anyway.

<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.1                                                       |
| Ruby                        | 3.0.4                                                      |
| Bundler?                    | true                                                       |
| Git                         | git version 2.36.0                                         |
| Installation Source         | ~/***/vendor/bundle/ruby/3.0.0/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.0.4/lib                               |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                                 |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode-14.2.0.app/Contents/Developer/         |
| Xcode Version               | 14.2                                                       |
| Swift Version               | 5.7.2                                                      |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| pathname                        | 0.1.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.696.0      |
| aws-sigv4                       | 1.5.2        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.169.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.118.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.3.26       |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.97.2       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.6.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.5        |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.44.0       |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2023-01-21**
</details>
  </pre>
</details>

### PR DESCRIPTION
**Pull request by loremattei**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When an app has an iOS and a macOS implementation, Deliver fails to upload one of the apps if the other one is under review:
- ASC returns no edit_app_info if one of the app is submitted for review and this makes Deliver fail. 
- Uploading only platform specific info for the other platform is actually a valid operation in ASC. Deliver fails because it can't fetch edit_app_info data, not because it can't upload the new data.  
- Since uploading only platform specific info is a valid flow in ASC, Deliver should allow to perform it. 

Resolves #17321
Resolves #21003

### Description

This PR updates `update_metadata` so that it fetches `live_app_info` if it can't find `edit_app_info`. 
- If no app is under review, edit_app_info will be fetched, so no changes from the current behaviour for most cases. 
- If one platform is under review, fetching `live_app_info` as a backup solution will allow the upload flow to continue. The flow will succeed if the user uploads only platform specific metadata, or fail later if they try to upload something that can't be modified in this state. 

### Testing Steps

_To test this specific scenario:_
1. Create an app with an iOS and a macOS implementation.
2. Submit a new version of the iOS app for review. 
3. When the iOS app is _waiting for review_, upload metadata (you can also try and upload binary and screenshots as well, but the issue is specific to metadata, so no need to do it) for a new version of the macOS app: 
```
bundle exec fastlane deliver run --force \
  --platform osx \
  --skip_binary_upload true \
  --skip_screenshots true \
  --submit_for_review false \
  --skip_metadata false \
  --automatic_release false \
  --username <your username> \
  --app_identifier <your app identifier>
```
and verify that it works. 

_Minimum regression testing:_
1. Test that upload a single iOS app still works. 
2. Test that  trying to upload new metadata for an app/platform that has been submitted for review fails.

### CODE REVIEW

**Comment by rogerluan** [comment]
Hi @loremattei 👋 could you merge `master` into your branch (or rebase it)? There was a fix to our CI that is in `master` that should make your PR pass all checks 🙏 

Thank you!

**Comment by loremattei** [comment]
Thanks @rogerluan! I rebased and now CI checks are all green :-)

**Review by rogerluan — CHANGES_REQUESTED** [review]
Hi @loremattei 😊 Thanks for fixing this! 

Could you add comments to the code explaining why we fallback to the live version, and why it is ok to use the live version? This edge case of having both iOS + macOS apps is not straightforward to understand when reading the code 😅

Also, could you test the case where all apps (macOS + iOS) are in non-edit mode? What message is it shown to the user? 🤔 If no useful error message is displayed, are we able to handle this scenario in our code and display a more user-friendly message?

**Comment by loremattei** [comment]
Hi @rogerluan! 
Thanks for the feedback! Good points!
I've added some comments to the code. 

I think there are different cases where all apps (macOS + iOS) are in non-edit mode and the failure likely depends on the requested flow (i.e. on the options). As long as the fetch step passes, the failure depends on whether the requested action is allowed. 

I've tested the case where no apps is in edit mode and the user tries to upload new metadata without passing any specific version as it looked the one which could be troublesome  and it returns `Failed to upload metadata: The provided entity includes an attribute with a value that has already been used - The version number has been previously used.` which looks pretty explanatory.

**Review by rogerluan — CHANGES_REQUESTED** [review]
Thanks for adding those comments! 🙌 

However, I don't think this message:

>The provided entity includes an attribute with a value that has already been used - The version number has been previously used.

is intuitive enough 😬 working with _fastlane_ for a few years and knowing the specific jargon Apple's APIs use, I kinda understand why it's failing, but not what I need to do to fix it, or what's wrong, if it's an issue on my side or not, etc... now if this was presented to a user with less experience, they'd probably be lost 😢 

Any chances we can catch this error and provide a custom-generated message to the user? Either before the request is actually made (validate before sending), or after (handling the error)?

If we can find a hook to do that, then a good message candidate would be e.g.:

> Unable to upload metadata: It seems that the app you're attempting to upload metadata for isn't currently in an editable state across any platform. Please ensure that the app you're working with falls into one of these states: Prepare for Submission, Developer Rejected, Rejected, Metadata Rejected, Waiting for Review, or Invalid Binary.

This would be a helpful and user-friendly message, which is what I'd expect as a user 😃 

The challenge isn't the message though, it's finding the right hook to add this to 🙈

**Comment by loremattei** [comment]
Thanks @rogerluan!

> I don't think this message is intuitive enough

I see what you mean and I agree with your proposal. My point was mostly that we are not introducing any big regression here as the current error message ("Cannot update languages - could not find an editable info") is not drastically more intuitive when users don't have any app in an editable state.

Anyway, I'm happy to try and improve this solution. I took a deeper look at the API and I think I've found a suitable approach, but I'll need some more time to figure it our properly. I'll be back asap.

**Comment by rogerluan** [comment]
>the current error message ("Cannot update languages - could not find an editable info") is not drastically more intuitive when users don't have any app in an editable state.

Fully agree 💯 😅 the point isn't which custom message we show though, but the fact that we show a custom one, instead of the API's response. If we replace `Cannot update languages - could not find an editable info` with a 🌷, how can we show 🌷 to user, on error? That's the challenge here I think, since we pretty much removed the hook that we were using to display such message.

I hope your approach works 🙌  looking forward to reviewing it!

**Comment by loremattei** [comment]
@rogerluan I updated this branch with a first draft. I haven't fully tested it yet, but I wanted to validate the idea with you before committing more time to it. 

While investigating better the API and the current Fastlane implementation, I found that Version info handling per platform is already working correctly and the problem is with App Info. App Info can't be actually edited when one platform is under review, so I think the correct behaviour in that scenario is that the upload fails if the user tries to update App Info, but succeeds otherwise. 

The current implementation of `update_metadata.rb` always tries to fetch App Info in `verify_available_info_languages`, even if it doesn't need it later. `fetch_edit_app_info` fails if one platform has been submitted, as expected given that it's platform independent. 

I think that the right solution here is to only execute `verify_available_info_languages` if the user is trying to update App Info.

The rest of `update_metadata.rb` already handles the case where `fetch_edit_app_info` returns nil without failing, so it looks like the only point that need to be fixed is `verify_available_info_languages`.

Wdyt? Does this solution look correct to you and worth more investigation and testing?

File: deliver/lib/deliver/upload_metadata.rb [hunk 1]
```diff
@@ -462,14 +451,18 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
       end
     end
 
+    # Checking if the metadata to update includes App Info
+    def is_updating_app_info(options)
+      LOCALISED_APP_VALUES.keys.each do |key|
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:456]: It seems like "app info" consists of the following info:

https://github.com/fastlane/fastlane/blob/ab9fb3249adaddf6c05655891b4d280415dfc84e/spaceship/lib/spaceship/connect_api/models/app_info.rb#L7-L17

So I think this code should include `LOCALISED_APP_VALUES` (like you did) but also the `NON_LOCALISED_APP_VALUES`, which's everything related to 'categories'. Or am I missing something?

File: deliver/lib/deliver/upload_metadata.rb [hunk 2]
```diff
@@ -462,14 +451,18 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+        return true unless options[key].nil?
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:457]: What kind of info does `options` contain? By reading your explanation in the PR it seems like this would contain the info that the user is trying to upload/update, but apparently this is just _deliver_'s options passed by the user, which could be these:

image

But the user can also update those app store values by modifying the text files in their metadata folder. Idk if _deliver_ already takes those properties into consideration, checks if they need to be updated (i.e. compare local metadata files against what's in the app store connect) 🤔 this would need to be checked

File: deliver/lib/deliver/upload_metadata.rb [hunk 3]
```diff
@@ -462,14 +451,18 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
       end
     end
 
+    # Checking if the metadata to update includes App Info
+    def is_updating_app_info(options)
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:455]: This function could look more Ruby-y 😊 simply:

```ruby
def updating_app_info?(options)
  LOCALISED_APP_VALUES.keys.any? { |key| options[key] }
end
```

`updating_app_info?` is the Ruby naming convention for functions that return boolean values (instead of e.g. `is…(…)`) 😃

**Review by rogerluan — CHANGES_REQUESTED** [review]
Love these findings @loremattei !! I think you're definitely on the right track now, but there are some open questions that need more digging so we can cover scenarios where users aren't explicitly passing those arguments 😬 

Good stuff so far! 🙌

File: deliver/lib/deliver/upload_metadata.rb (hunk 1 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:471]: @rogerluan you are right, though the result is used only to enable localizations. 
The `upload` function fetches again edit info later for the not localised app values and it also handles an empty answer[ without failing](https://github.com/fastlane/fastlane/blob/ab9fb3249adaddf6c05655891b4d280415dfc84e/deliver/lib/deliver/upload_metadata.rb#L225).

I think there's an opportunity to refactor some of this code to make it clearer and more coherent, but it's probably worth it to validate this solution before making bigger changes. 

I've updated the name to clarify that it only refers to localised values.

File: deliver/lib/deliver/upload_metadata.rb (hunk 2 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb]: Yep, it contains the info the user is trying to upload, including the ones from text files. It uploads them in [load_from_filesystem](https://github.com/fastlane/fastlane/blob/ab9fb3249adaddf6c05655891b4d280415dfc84e/deliver/lib/deliver/upload_metadata.rb#L524) which is [called before upload](https://github.com/fastlane/fastlane/blob/ab9fb3249adaddf6c05655891b4d280415dfc84e/deliver/lib/deliver/runner.rb#L143). 
I've also tested it locally. 

It doesn't compare local data against what's in the App Store Connect tho, so I've added this to the function.

File: deliver/lib/deliver/upload_metadata.rb (hunk 3 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb]: Thanks! Clearly, I'm not a ruby-ist :-)

**Comment by loremattei** [comment]
@rogerluan this should be ready for another look. 
I've tested it in a few scenarios and it looks good, though there are actually a bunch of different ones that are possible given all the options that fastlane offers 😅

File: deliver/lib/deliver/upload_metadata.rb (hunk 3 above)
Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb]: I just know a thing or two! Always happy to share knowledge and help others ❤️

File: deliver/lib/deliver/upload_metadata.rb [hunk 4]
```diff
@@ -451,6 +459,42 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+        current = options[key]
+        next unless current
+
+        unless current.kind_of?(Hash)
+          UI.error("Error with provided '#{key}'. Must be a hash, the key being the language.")
+          next
+        end
+
+        current.each do |language, value|
+          next unless value.to_s.length > 0
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:481]: I think this line is redundant (given the next 2 LOC):

```suggestion
```

Unless I'm missing something

File: deliver/lib/deliver/upload_metadata.rb [hunk 5]
```diff
@@ -451,6 +459,42 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+          app_info_locale = localizations.find { |l| l.locale == language }
+          next if app_info_locale.nil?
+
+          current_value = app_info_locale.public_send(key.to_sym)
+
+          return true if current_value != strip_value
+        end
+      end
+
+      UI.important('No changes to localised App Info detected. Skipping upload.')
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:494]: Should this be an important message? 😮 it will print as a warning-like message in the console, asking for the reader's attention 🤔 

I think this is a quite common user path, not necessarily one that needs attention, perhaps just a `UI.message` would do. WDYT?

File: deliver/lib/deliver/upload_metadata.rb [hunk 6]
```diff
@@ -89,7 +89,7 @@ def upload(options)
       enabled_languages = detect_languages(options)
 
       app_store_version_localizations = verify_available_version_languages!(options, app, enabled_languages) unless options[:edit_live]
-      app_info_localizations = verify_available_info_languages!(options, app, enabled_languages) unless options[:edit_live]
+      app_info_localizations = verify_available_info_languages!(options, app, enabled_languages) unless options[:edit_live] || !updating_localised_app_info?(options, app)
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:92]: Now this code will first fetch `edit || live`, and then if there are no changes to app info localizations, good. But if there are, it will call `verify_available_info_languages` and will fetch `edit` app info again, which's not necessary since we just fetched it. Do you think this is something we could easily improve? E.g. by fetching them once and passing them as parameters where needed :)

Sometimes extra fetches can significantly hit fastlane's performance, so we try to keep the requests as lean as possible 🙏

File: deliver/spec/upload_metadata_spec.rb
Comment (rogerluan) [inline deliver/spec/upload_metadata_spec.rb:1]: Could you add specs that cover the exact use case you're aiming to fix by this PR? That is, an app with both iOS and macOS versions, in specific app store states 🙏

**Review by rogerluan — CHANGES_REQUESTED** [review]
Good job you did here so far! 🙌 Your algo looks solid to me!
Just left some questions and minor suggestions :) but I think we could use some more rspecs 👀

File: deliver/lib/deliver/upload_metadata.rb [hunk 7]
```diff
@@ -211,15 +211,17 @@ def upload(options)
...
+          if attributes
+            UI.message("Uploading metadata to App Store Connect for localized info '#{app_info_localization.locale}'")
+            app_info_localization.update(attributes: attributes)
+          end
         end
+        app_info_worker.batch_enqueue(app_info_localizations)
+        app_info_worker.start
       end
-      app_info_worker.batch_enqueue(app_info_localizations)
-      app_info_worker.start
```
[the remark this answers is not in the document]
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:222]: `app_info_localizations` can be null now. If it's null, app_info_worker won't be created. This is the last part of the block above.

File: deliver/lib/deliver/upload_metadata.rb [hunk 8]
```diff
@@ -451,6 +459,42 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+        return false
+      end
+      localizations = app_info.get_app_info_localizations
+
+      LOCALISED_APP_VALUES.keys.each do |key|
+        current = options[key]
+        next unless current
+
+        unless current.kind_of?(Hash)
+          UI.error("Error with provided '#{key}'. Must be a hash, the key being the language.")
```
[the remark this answers is not in the document]
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:476]: Yep, I think it's fine to just avoid processing the current one and move ahead to the next. If it's not a hash, it's not something we need to analyse here. 
I don't exactly know why there can be something that's not an hash in options, but I found this check in other parts of the code (e.g. [here](https://github.com/fastlane/fastlane/blob/8c1fc739a65b0dff06f434e9de958a9f4c5f418c/deliver/lib/deliver/upload_metadata.rb#L134)) and followed the same approach.

File: deliver/lib/deliver/upload_metadata.rb (hunk 4 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:481]: Good call!

File: deliver/lib/deliver/upload_metadata.rb (hunk 5 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:493]: Yes, this makes sense to me

File: deliver/lib/deliver/upload_metadata.rb (hunk 6 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:92]: Thanks. Makes sense. 
I moved the call out of the functions and passed it as a parameter. There was already another call at that level to `fetch_app_info` that felt redundant to me at this point. 
Please, let me know if you see any reason to refetch at that point. I didn't.

File: deliver/spec/upload_metadata_spec.rb
Comment (loremattei) [reply deliver/spec/upload_metadata_spec.rb:1]: @rogerluan I'm not sure this is what we want to test. All the platform info actually comes within the version info, not app info. 
The fact that edit_app_info are null in some specific cases with two platforms is related to how App Store works, but it doesn't look like we gain anything by mocking it here. 

I think it's useful to test the cases we are handling here from the point of view of the API we use, so testing the behaviour when edit_app_info is null and 1. users don't add any app info, 2. users add app info that are equal to the ones already in the App Store, 3. users add app info that are different from what's already in the App Store. 

I've added those. Let me know if this makes sense to you.

File: deliver/lib/deliver/upload_metadata.rb (hunk 7 above)
[the remark this answers is not in the document]
Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb:222]: Ahh makes sense 🙏

File: deliver/spec/upload_metadata_spec.rb [hunk 9]
```diff
@@ -419,6 +422,86 @@ def create_metadata(path, text)
...
+        # Get app info
+        expect(uploader).to receive(:fetch_edit_app_info).and_return(app_info)
+        expect(app).to receive(:fetch_live_app_info).and_return(live_app_info)
+        expect(live_app_info).to receive(:get_app_info_localizations).and_return([app_info_localization_en])
+
+        # Get versions
+        expect(app).to receive(:get_edit_app_store_version).and_return(version)
+        expect(version).to receive(:get_app_store_version_localizations).and_return([version_localization_en])
+
+        # Get app info localization English (Used to compare with data to upload)
```
Comment (rogerluan) [inline deliver/spec/upload_metadata_spec.rb:496]:
```suggestion
        # Get app info localization in English (used to compare with data to upload)
```

File: deliver/spec/upload_metadata_spec.rb [hunk 10]
```diff
@@ -419,6 +422,86 @@ def create_metadata(path, text)
...
+        expect(app_info_localization_en).to receive(:name).and_return("App name")
+
+        # Fail because app info can't be updated
+        expect(FastlaneCore::UI).to receive(:user_error!).with("Cannot update languages - could not find an editable info").and_call_original
+
+        # Get app info localization English (Used to compare with data to upload)
```
Comment (rogerluan) [inline deliver/spec/upload_metadata_spec.rb:502]:
```suggestion
        # Get app info localization in English (used to compare with data to upload)
```

**Review by rogerluan — COMMENTED** [review]
Latest changes look good @loremattei ! just left a some feedbacks and a question 😊 once those are addressed I think this will be clear from my side! Good hustle! 💪

**Comment by rogerluan** [comment]
This PR could use a second pair of 👀 as it touches a critical code path 🙇  @AliSoftware @getaaron

**Comment by loremattei** [comment]
Thank you for all your support with this @rogerluan!

File: deliver/lib/deliver/upload_metadata.rb [hunk 11]
```diff
@@ -451,10 +459,43 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
-    def verify_available_info_languages!(options, app, languages)
-      app_info = fetch_edit_app_info(app)
+    # Checking if the metadata to update includes localised App Info
+    def updating_localised_app_info?(options, app, app_info)
+      app_info ||= fetch_live_app_info(app)
+      unless app_info
+        UI.important("Can't find edit or live App info. Skipping upload.")
+        return false
+      end
+      localizations = app_info.get_app_info_localizations
```
Comment (AliSoftware) [inline deliver/lib/deliver/upload_metadata.rb:469]: [Unrelated to this PR]

@rogerluan we definitively need to improve our YARD doc on many of our model methods. This isn't clear at all from the definition of the `AppInfo#get_app_info_localizations` what that method is supposed to return, which makes it harder to read code that uses it like here and why Lore needed to use `localizations.find` below.

_(After some digging, the answer is that it returns `Array<Spaceship::ConnectAPI::AppInfo>`; which makes sense in retrospect I guess, but was't obvious to me at first sight, and RubyMine isn't able to deduce it automatically)_

File: deliver/lib/deliver/upload_metadata.rb [hunk 12]
```diff
@@ -451,10 +459,43 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+          app_info_locale = localizations.find { |l| l.locale == language }
+          next if app_info_locale.nil?
+
+          current_value = app_info_locale.public_send(key.to_sym)
+
+          return true if current_value != strip_value
+        end
+      end
+
+      UI.message('No changes to localised App Info detected. Skipping upload.')
```
Comment (AliSoftware) [inline deliver/lib/deliver/upload_metadata.rb:493]: 💄  Same type of nitpicking about US vs UK spelling 🙃 
```suggestion
      UI.message('No changes to localized App Info detected. Skipping upload.')
```

File: deliver/spec/upload_metadata_spec.rb [hunk 13]
```diff
@@ -257,11 +261,17 @@ def create_metadata(path, text)
...
+          # Get number of versions (used for if whats_new should be sent)
           expect(Spaceship::ConnectAPI).to receive(:get_app_store_versions).and_return(app_store_versions)
 
           expect(version).to receive(:update).with(attributes: {})
 
+          # Get app info
+          expect(app_info).to receive(:get_app_info_localizations).and_return([app_info_localization_en])
+
+          # Get app info localization English (Used to compare with data to upload)
+          expect(app_info_localization_en).to receive(:name).and_return("")
```
Comment (AliSoftware) [inline deliver/spec/upload_metadata_spec.rb:273]: 💭  `rubocop` might complain if you use double-quotes while you don't need any interpolation

```suggestion
          expect(app_info_localization_en).to receive(:name).and_return('')
```

💡  Also, might make it cleared and easier to understand the logic of the spec to provide a dummy name instead?

```suggestion
          expect(app_info_localization_en).to receive(:name).and_return('Old App Name')
```

File: deliver/lib/deliver/upload_metadata.rb [hunk 14]
```diff
@@ -451,10 +459,43 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+      return false
+    end
+
+    # Finding languages to enable
+    def verify_available_info_languages!(options, app, app_info, languages)
       unless app_info
         UI.user_error!("Cannot update languages - could not find an editable info")
```
Comment (AliSoftware) [inline deliver/lib/deliver/upload_metadata.rb:500]: A bit outside of the scope of this PR, but while we're updating the code around that logic, I feel we could use message that could be a tad more helpful. Wdyt?

```suggestion
        UI.user_error!("Cannot update languages - could not find an editable version. Verify that your app is in one of the editable state in App Store Connect")
```

**Review by AliSoftware — APPROVED** [review]
Hey Lorenzo! Small world 😄  Fancy seeing you here!

The changes in your PR make sense to me, all looking good, thanks for the contribution! 👍 

I just left some nitpicky suggestions about wording, but nothing blocking 🙂

File: deliver/lib/deliver/upload_metadata.rb [hunk 15]
```diff
@@ -451,10 +459,43 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
       end
     end
 
-    # Finding languages to enable
-    def verify_available_info_languages!(options, app, languages)
-      app_info = fetch_edit_app_info(app)
+    # Checking if the metadata to update includes localised App Info
+    def updating_localised_app_info?(options, app, app_info)
+      app_info ||= fetch_live_app_info(app)
```
Comment (AliSoftware) [inline deliver/lib/deliver/upload_metadata.rb:464]: Wait, after browsing the codebase a bit, I just discovered that [`Spaceship::ConnectAPI::App` has an `fetch_latest_app_info` method](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/app.rb#L150-L154) in addition to [the more-specific `fetch_edit_app_info` and `fetch_live_app_info` ones that filter the results according to the app state](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/connect_api/models/app.rb#L116-L148).

I wonder if it wouldn't make sense to use that `fetch_latest_app_info directly then, instead of doing the fallback manually here? 🤔 Though maybe that wouldn't have the same fallback behavior as the one you're using here… 🤔  wdyt?

File: deliver/lib/deliver/upload_metadata.rb (hunk 14 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb]: Good point! 
I wonder if "version" would be confusing, as in this case the user may have an editable version (on one platform), but not editable App info (e.g. because the other platform is under review).
I used your wording, but switched 'version' to 'App info'.
Let me know if it doesn't look good to you.

File: deliver/lib/deliver/upload_metadata.rb (hunk 15 above)
Comment (loremattei) [reply deliver/lib/deliver/upload_metadata.rb:464]: Good catch! I wasn't aware of that API. But, if I understand it right, this is equivalent (though a better solution) to my initial approach of using `fetch_edit_app_info(app) || fetch_live_app_info(app)` which had the problem that it was then difficult to properly give feedback to the user and to understand when we could progress and when it's better to fail here. 
We added manual fallback to address this problem. 
Does it make sense to you?

**Comment by loremattei** [comment]
Hey @AliSoftware !
How are you doing? Great to see you!
Thanks for your feedback. I made the changes you suggested and left a comment about the last one. Let me know what you think!

File: deliver/lib/deliver/upload_metadata.rb (hunk 15 above)
Comment (AliSoftware) [reply deliver/lib/deliver/upload_metadata.rb:464]: Yeah good point. That's also what I feared and why I asked about if it'd provide the same fallback behavior and all.

Better to give us the occasion to provide nicer error reporting to our users I think, and thus to keep your implementation to be able to distinguish both cases 👍

**Comment by loremattei** [comment]
@rogerluan I think I've done everything requested here. Please, let me know if there's anything I need to do to move this forward :-)

File: deliver/lib/deliver/upload_metadata.rb [hunk 16]
```diff
@@ -490,14 +490,14 @@ def updating_localised_app_info?(options, app, app_info)
...
-      UI.message('No changes to localised App Info detected. Skipping upload.')
+      UI.message('No changes to localized App Info detected. Skipping upload.')
       return false
     end
 
     # Finding languages to enable
     def verify_available_info_languages!(options, app, app_info, languages)
       unless app_info
-        UI.user_error!("Cannot update languages - could not find an editable info")
+        UI.user_error!("Cannot update languages - could not find an editable App info. Verify that your app is in one of the editable states in App Store Connect")
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:500]:
```suggestion
        UI.user_error!("Cannot update languages - could not find an editable app info. Verify that your app is in one of the editable states in App Store Connect")
```

File: deliver/spec/upload_metadata_spec.rb [hunk 17]
```diff
@@ -494,10 +491,10 @@ def create_metadata(path, text)
         expect(version).to receive(:get_app_store_version_localizations).and_return([version_localization_en])
 
         # Get app info localization in English (used to compare with data to upload)
-        expect(app_info_localization_en).to receive(:name).and_return("App name")
+        expect(app_info_localization_en).to receive(:name).and_return('App name')
 
         # Fail because app info can't be updated
-        expect(FastlaneCore::UI).to receive(:user_error!).with("Cannot update languages - could not find an editable info").and_call_original
+        expect(FastlaneCore::UI).to receive(:user_error!).with('Cannot update languages - could not find an editable App info. Verify that your app is in one of the editable states in App Store Connect').and_call_original
```
Comment (rogerluan) [inline deliver/spec/upload_metadata_spec.rb:497]:
```suggestion
        expect(FastlaneCore::UI).to receive(:user_error!).with('Cannot update languages - could not find an editable app info. Verify that your app is in one of the editable states in App Store Connect').and_call_original
```

File: deliver/spec/upload_metadata_spec.rb (hunk 13 above)
Comment (rogerluan) [reply deliver/spec/upload_metadata_spec.rb]: >💭  rubocop might complain if you use double-quotes while you don't need any interpolation

The rubocop rules we have in _fastlane_ explicitly allows both `"` and `'` to be used 😅

File: deliver/lib/deliver/upload_metadata.rb (hunk 14 above)
Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb]: I'd use either quoted an capitalized `'App Info'` or simple nouns (thus all lowercase) `app info` @loremattei 😊

**Review by rogerluan — APPROVED** [review]
💪 LGTM!

File: deliver/lib/deliver/upload_metadata.rb (hunk 14 above)
Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb]: I've pushed a commit to change to `'App Info'` so we can move forward with this PR, I hope you don't mind 😊

Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb]: One last thing! What do you guys think about the message I suggested [earlier](https://github.com/fastlane/fastlane/pull/21472#pullrequestreview-1599443550)? User-friendlier and more specific?

What I suggested earlier:

>Unable to upload metadata: It seems that the app you're attempting to upload metadata for isn't currently in an editable state across any platform. Please ensure that the app you're working with falls into one of these states: Prepare for Submission, Developer Rejected, Rejected, Metadata Rejected, Waiting for Review, or Invalid Binary.

What I think we could use now, after the latest changes to the logic:

>Unable to upload metadata: It seems that the app you're attempting to upload metadata for isn't currently in an editable state. Please ensure that the app you're working with falls into one of these states: Prepare for Submission, Developer Rejected, Rejected, Metadata Rejected, Waiting for Review, or Invalid Binary.

Comment (rogerluan) [reply deliver/lib/deliver/upload_metadata.rb]: One last thing! What do you guys think about the message I suggested [earlier](https://github.com/fastlane/fastlane/pull/21472#pullrequestreview-1599443550)? User-friendlier and more specific?

What I suggested earlier:

>Unable to upload metadata: It seems that the app you're attempting to upload metadata for isn't currently in an editable state across any platform. Please ensure that the app you're working with falls into one of these states: Prepare for Submission, Developer Rejected, Rejected, Metadata Rejected, Waiting for Review, or Invalid Binary.

What I think we could use now, after the latest changes to the logic:

>Unable to upload metadata: It seems that the app you're attempting to upload metadata for isn't currently in an editable state. Please ensure that the app you're working with falls into one of these states: Prepare for Submission, Developer Rejected, Rejected, Metadata Rejected, Waiting for Review, or Invalid Binary.

@loremattei @AliSoftware

File: deliver/spec/upload_metadata_spec.rb [hunk 18]
```diff
@@ -412,6 +422,83 @@ def create_metadata(path, text)
...
+
+        # Get versions
+        expect(app).to receive(:get_edit_app_store_version).and_return(version)
+        expect(version).to receive(:get_app_store_version_localizations).and_return([version_localization_en])
+
+        # Get app info localization in English (used to compare with data to upload)
+        expect(app_info_localization_en).to receive(:name).and_return('App name')
+
+        # Fail because app info can't be updated
+        expect(FastlaneCore::UI).to receive(:user_error!).with('Cannot update languages - could not find an editable 'App Info'. Verify that your app is in one of the editable states in App Store Connect').and_call_original
```
Comment (rogerluan) [inline deliver/spec/upload_metadata_spec.rb:497]:
```suggestion
        expect(FastlaneCore::UI).to receive(:user_error!).with("Cannot update languages - could not find an editable 'App Info'. Verify that your app is in one of the editable states in App Store Connect").and_call_original
```

File: deliver/spec/upload_metadata_spec.rb (hunk 13 above)
Comment (AliSoftware) [reply deliver/spec/upload_metadata_spec.rb]: TIL!

File: deliver/lib/deliver/upload_metadata.rb (hunk 14 above)
Comment (AliSoftware) [reply deliver/lib/deliver/upload_metadata.rb]: WFM 👍

**Comment by loremattei** [comment]
Hey @rogerluan 👋 Is there anything I can do to move this forward?

**Comment by rogerluan** [comment]
Thanks for the ping! Gonna merge this in, but it will only be released whenever we have the next release cut off 🙇

**Comment by loremattei** [comment]
Thanks @rogerluan! Sounds great! Looking forward for it :-)

File: deliver/lib/deliver/upload_metadata.rb [hunk 19]
```diff
@@ -451,12 +459,45 @@ def retry_if_nil(message, tries: 5, wait_time: 10)
...
+          app_info_locale = localizations.find { |l| l.locale == language }
+          next if app_info_locale.nil?
+
+          current_value = app_info_locale.public_send(key.to_sym)
+
+          return true if current_value != strip_value
+        end
+      end
+
+      UI.message('No changes to localized App Info detected. Skipping upload.')
```
Comment (owjsub) [inline deliver/lib/deliver/upload_metadata.rb:493]: This occurs when attempting to edit an iOS or tvOS privacy url. Is there a way we can force upload so that we can edit the privacy url even though none of the other localized app info will change? See related issue https://github.com/fastlane/fastlane/issues/21654
