### PR TITLE
TestFairy option checking only checked for symbols, not strings

### LINKED ISSUE #9226: problem parsing options array for TestFairy
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm using Fastlane to distribute my ios and android apps via TestFairy. However I'm failing to pass the options and metrics parameters as they fail during validation.
This is my fastfile contents:

```
fastlane_version "2.32.0"

default_platform :ios

platform :ios do
  before_all do
     ENV["SLACK_URL"] = "..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new QA Build to Test Fairy"

  lane :qa do
    match(
      force_for_new_devices: true,
      readonly: true,
      type: "adhoc",
      git_url: "..."
    )

    increment_build_number(xcodeproj: 'cleganeguard.xcodeproj')

    cocoapods

    gym(scheme: "cleganeguard-qa")

    testfairy(
      api_key: "...",
      testers_groups: ["development"],
      notify: "off",
      auto_update: "off",
      symbols_file: Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH],
      options: [ "shake"]
    )

    #slack(message: "Successfully deployed new QA Build to TestFairy!")
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
### Captured Output
```

Command Used: `qa`
<details><summary>Output/Log</summary>


DEBUG [2017-05-19 16:48:31.25]: Checking if there are any plugins that should be loaded...
INFO [2017-05-19 16:48:31.26]: -------------------------------------------------
INFO [2017-05-19 16:48:31.26]: --- Step: Verifying required fastlane version ---
INFO [2017-05-19 16:48:31.26]: -------------------------------------------------
INFO [2017-05-19 16:48:31.26]: Your fastlane version 2.32.0 matches the minimum requirement of 2.28.8  ✅
INFO [2017-05-19 16:48:31.26]: ------------------------------
INFO [2017-05-19 16:48:31.26]: --- Step: default_platform ---
INFO [2017-05-19 16:48:31.26]: ------------------------------
INFO [2017-05-19 16:48:31.26]: Driving the lane 'ios qa' 🚀
INFO [2017-05-19 16:48:31.26]: -------------------
INFO [2017-05-19 16:48:31.26]: --- Step: match ---
INFO [2017-05-19 16:48:31.26]: -------------------
Successfully loaded Appfile at path '/Users/Franco/Projects/clegane-guard/ios/fastlane/Appfile'
- app_identifier: 'com.keenvil.clegane'
- apple_id: 'mobile.operator@keenvil.com'
- team_id: '7428HDK64H'
-------
INFO [2017-05-19 16:48:31.28]: Successfully loaded '/Users/Franco/Projects/clegane-guard/ios/fastlane/Matchfile' 📄

+----------------+-----------------------------+
| Detected Values from './fastlane/Matchfile'  |
+----------------+-----------------------------+
| app_identifier | com.keenvil.ironthrone      |
| username       | mobile.operator@keenvil.com |
+----------------+-----------------------------+

DEBUG [2017-05-19 16:48:31.28]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+------------------------------------+
|                  Summary for match 2.32.0                  |
+-----------------------+------------------------------------+
| force_for_new_devices | true                               |
| readonly              | true                               |
| type                  | adhoc                              |
| git_url               | git@github.com:keenvil/braavos.git |
| app_identifier        | com.keenvil.ironthrone             |
| username              | mobile.operator@keenvil.com        |
| git_branch            | master                             |
| keychain_name         | login.keychain                     |
| team_id               | 7428HDK64H                         |
| verbose               | false                              |
| force                 | false                              |
| skip_confirmation     | false                              |
| shallow_clone         | false                              |
| clone_branch_directly | false                              |
| skip_docs             | false                              |
| platform              | ios                                |
+-----------------------+------------------------------------+

INFO [2017-05-19 16:48:31.28]: Cloning remote git repo...
INFO [2017-05-19 16:48:31.28]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-05-19 16:48:31.28]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:keenvil/braavos.git' '/var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/d20170519-72905-1vchx8e'
INFO [2017-05-19 16:48:31.30]: ▸ Cloning into '/var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/d20170519-72905-1vchx8e'...
INFO [2017-05-19 16:48:33.72]: ▸ remote: Counting objects: 156, done.[K
INFO [2017-05-19 16:48:33.87]: ▸ remote: Compressing objects: 100% (58/58), done.[K
INFO [2017-05-19 16:48:34.53]: ▸ remote: Total 156 (delta 2), reused 62 (delta 2), pack-reused 93[K
INFO [2017-05-19 16:48:34.53]: ▸ Receiving objects: 100% (156/156), 349.99 KiB | 512.00 KiB/s, done.
INFO [2017-05-19 16:48:34.53]: ▸ Resolving deltas: 100% (7/7), done.
INFO [2017-05-19 16:48:34.71]: ▸ Checking connectivity... done.
INFO [2017-05-19 16:48:34.78]: 🔓  Decrypted 'K9TX586DRR.cer'
INFO [2017-05-19 16:48:34.83]: 🔓  Decrypted 'JB32NG3UGF.cer'
INFO [2017-05-19 16:48:34.87]: 🔓  Decrypted 'K9TX586DRR.p12'
INFO [2017-05-19 16:48:34.92]: 🔓  Decrypted 'JB32NG3UGF.p12'
INFO [2017-05-19 16:48:34.97]: 🔓  Decrypted 'AdHoc_com.keenvil.clegane.mobileprovision'
INFO [2017-05-19 16:48:35.03]: 🔓  Decrypted 'AdHoc_com.keenvil.ironthrone.mobileprovision'
INFO [2017-05-19 16:48:35.08]: 🔓  Decrypted 'AppStore_com.keenvil.clegane.mobileprovision'
INFO [2017-05-19 16:48:35.13]: 🔓  Decrypted 'AppStore_com.keenvil.guard.mobileprovision'
INFO [2017-05-19 16:48:35.17]: 🔓  Decrypted 'AppStore_com.keenvil.guard.sentinel.mobileprovision'
INFO [2017-05-19 16:48:35.22]: 🔓  Decrypted 'AppStore_com.keenvil.ironthrone.mobileprovision'
INFO [2017-05-19 16:48:35.27]: 🔓  Decrypted 'AppStore_com.keenvil.sentinel.mobileprovision'
INFO [2017-05-19 16:48:35.31]: 🔓  Decrypted 'Development_com.keenvil.ironthrone.mobileprovision'
INFO [2017-05-19 16:48:35.31]: 🔓  Successfully decrypted certificates repo
INFO [2017-05-19 16:48:35.31]: Installing certificate...
INFO [2017-05-19 16:48:35.31]: $ security list-keychains -d user
INFO [2017-05-19 16:48:35.33]: ▸     "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.33]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/Franco/Library/Keychains/login.keychain-db
INFO [2017-05-19 16:48:35.36]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.36]: ▸ version: 512
INFO [2017-05-19 16:48:35.36]: ▸ class: 0x80001000 
INFO [2017-05-19 16:48:35.36]: ▸ attributes:
INFO [2017-05-19 16:48:35.36]: ▸     "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-05-19 16:48:35.36]: ▸     "cenc"<uint32>=0x00000003 
INFO [2017-05-19 16:48:35.36]: ▸     "ctyp"<uint32>=0x00000001 
INFO [2017-05-19 16:48:35.36]: ▸     "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-05-19 16:48:35.36]: ▸     "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"
INFO [2017-05-19 16:48:35.36]: ▸     "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"
INFO [2017-05-19 16:48:35.36]: ▸     "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"
INFO [2017-05-19 16:48:35.36]: ▸     "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"
INFO [2017-05-19 16:48:35.36]: ▸     "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"
DEBUG [2017-05-19 16:48:35.59]: Certificate 'JB32NG3UGF.cer' is already installed on this machine
INFO [2017-05-19 16:48:35.59]: $ security import /var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/d20170519-72905-1vchx8e/certs/distribution/JB32NG3UGF.p12 -k '/Users/Franco/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security
INFO [2017-05-19 16:48:35.67]: $ security set-key-partition-list -S apple-tool:,apple: -k "" /Users/Franco/Library/Keychains/login.keychain-db
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="<key>"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0xE9B9B9BB1DFE03CC203D3EB20128EA7E6AA5C4EE  "\351\271\271\273\035\376\003\314 =>\262\001(\352~j\245\304\356"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0xE288999755A6A270622C637076F1C1E8A9F04C9D  "\342\210\231\227U\246\242pb,cpv\361\301\350\251\360L\235"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0xA632140AC99E93101D1988A7F68A727B35A1644A  "\2462\024\012\311\236\223\020\035\031\210\247\366\212r{5\241dJ"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x865F0A1A4CC4F186045B4EF6B669ABC5CDA87ECF  "\206_\012\032L\304\361\206\004[N\366\266i\253\305\315\250~\317"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x2F92D7D42FF1BDC95DC4B95AC1B65BE1347D9066  "/\222\327\324/\361\275\311]\304\271Z\301\266[\3414}\220f"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="Apple ID franco.monsalvo@gmail.com key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x79EADF02C8E71603F1600CDA3533627026EC3397  "y\352\337\002\310\347\026\003\361`\014\33253bp&\3543\227"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x88465901DF3C9125AA94835698FA050A67FC2858  "\210FY\001\337<\221%\252\224\203V\230\372\005\012g\374(X"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0xC63FD03DA8A9B872DDFE0B0D8E0CB681BC89FA38  "\306?\320=\250\251\270r\335\376\013\015\216\014\266\201\274\211\3728"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x5B959EE646460CC31870388C08A801B861783DC4  "[\225\236\346FF\014\303\030p8\214\010\250\001\270ax=\304"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x0CEE06BD1B43B7B631FF31543464D4C2AEADC67B  "\014\356\006\275\033C\267\2661\3771T4d\324\302\256\255\306{"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0x67F127DFB794BDD9A3AC1DD97EECB9BEA59D91C6  "g\361'\337\267\224\275\331\243\254\035\331~\354\271\276\245\235\221\306"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.79]: ▸ version: 512
INFO [2017-05-19 16:48:35.79]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸ attributes:
INFO [2017-05-19 16:48:35.79]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x00000006 <blob>=0xAA9D44A83C8C27292BB31443C6B55E3D8D143E24  "\252\235D\250<\214')+\263\024C\306\265^=\215\024>$"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.79]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.79]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.79]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xD4F3D9B83FCE1C9F803817F239BDEB7DBF874E00  "\324\363\331\270?\316\034\237\2008\027\3629\275\353}\277\207N\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x0886578F18C11BC5B1203DD9EFDE3EF095FA93FF  "\010\206W\217\030\301\033\305\261 =\331\357\336>\360\225\372\223\377"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xB55E63CDCC1EE59F8F3F975B225E6CFCF6E726B0  "\265^c\315\314\036\345\237\217?\227["^l\374\366\347&\260"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x21DB0DBC20FF6B1FA2D90E9F81789897EA1BFEED  "!\333\015\274 \377k\037\242\331\016\237\201x\230\227\352\033\376\355"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x2C29E1A38B9BF72A383B06277996AD8F2AC713FA  ",)\341\243\213\233\367*8;\006'y\226\255\217*\307\023\372"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x63FB3934E6AC1E4781E705D9798BAE4E7A5823F1  "c\37394\346\254\036G\201\347\005\331y\213\256NzX#\361"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x5F096586EFB43A9816BC2CB1C7ABCC5C32BD0E51  "_\011e\206\357\264:\230\026\274,\261\307\253\314\1342\275\016Q"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x7128A7EF9C424C9E6EED898CDF6F30086A6841F7  "q(\247\357\234BL\236n\355\211\214\337o0\010jhA\367"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x0038BE8189952BD2F36206FB8B1728C9BEEB10A2  "\0008\276\201\211\225+\322\363b\006\373\213\027(\311\276\353\020\242"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xB57768F51AD3E86C509CFD3E03CDB59CF075A501  "\265wh\365\032\323\350lP\234\375>\003\315\265\234\360u\245\001"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x9E1510583CE68EEA318B776456750D745D9C243F  "\236\025\020X<\346\216\3521\213wdVu\015t]\234$?"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xBD42C70F189530372B5CD16FA62337851F4BAC7A  "\275B\307\017\030\22507+\134\321o\246#7\205\037K\254z"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xF997C8F58FB4D1D6DCC72B443E469894155F844E  "\371\227\310\365\217\264\321\326\334\307+D>F\230\224\025_\204N"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x872F3C430881E7B76855EEFEAD25725729ACCE7A  "\207/<C\010\201\347\267hU\356\376\255%rW)\254\316z"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0x538EA979FFBFF70B5F12C18D711D6813EF7193D0  "S\216\251y\377\277\367\013_\022\301\215q\035h\023\357q\223\320"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xB7AE820356C8FEE757E660073D593201DD1B1E3C  "\267\256\202\003V\310\376\347W\346`\007=Y2\001\335\033\036<"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.80]: ▸ version: 512
INFO [2017-05-19 16:48:35.80]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸ attributes:
INFO [2017-05-19 16:48:35.80]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000006 <blob>=0xED1F10C7E29672AF7A3DEDC061DD2BE5FA283A63  "\355\037\020\307\342\226r\257z=\355\300a\335+\345\372(:c"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.80]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.80]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.80]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x5F177684A5D9E61266B594DA49DBC53DC0680317  "_\027v\204\245\331\346\022f\265\224\332I\333\305=\300h\003\027"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="Keenvil CA"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x46E394CBD4A0871F6BFFD3DCA05267615D692A42  "F\343\224\313\324\240\207\037k\377\323\334\240Rga]i*B"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x6FACA32033C0EF0B46FB02B9244BDF9819569489  "o\254\243 3\300\357\013F\373\002\271$K\337\230\031V\224\211"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x890EC57D0536DD3D06E2310D7B6EDBF2A703D71D  "\211\016\305}\0056\335=\006\3421\015{n\333\362\247\003\327\035"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x5F00BB8C62F56A77A82778A4BBB79294BEC0F9A3  "_\000\273\214b\365jw\250'x\244\273\267\222\224\276\300\371\243"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x503DEAE1AC66B53F0672EE042A3E9C3FB223D22C  "P=\352\341\254f\265?\006r\356\004*>\234?\262#\322,"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="Franco Monsalvo"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0xD42E78D4252CB318F4644B13DCE434ED43E17EBF  "\324.x\324%,\263\030\364dK\023\334\3444\355C\341~\277"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000800 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Signing Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x6D7D46AAA476E71BEB069982867198A3CF34728D  "m}F\252\244v\347\033\353\006\231\202\206q\230\243\3174r\215"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x00000049  "\000\000\000I"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000100 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="iMessage Encryption Key"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0x7F455DBAE312BC6988D72DE244EC0EC0927D701E  "\177E]\272\343\022\274i\210\327-\342D\354\016\300\222}p\036"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000500 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸ keychain: "/Users/Franco/Library/Keychains/login.keychain-db"
INFO [2017-05-19 16:48:35.81]: ▸ version: 512
INFO [2017-05-19 16:48:35.81]: ▸ class: 0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸ attributes:
INFO [2017-05-19 16:48:35.81]: ▸     0x00000000 <uint32>=0x0000000F 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000001 <blob>="<key>"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000002 <blob>=<NULL>
INFO [2017-05-19 16:48:35.81]: ▸     0x00000003 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000004 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000005 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000006 <blob>=0xB0CEC6BC60D54D2ACE94C7A6DB75DB00A651E8E3  "\260\316\306\274`\325M*\316\224\307\246\333u\333\000\246Q\350\343"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000007 <blob>="com.readdle.smartemail.notification.rsa_v2.publicKey"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
INFO [2017-05-19 16:48:35.81]: ▸     0x00000009 <uint32>=0x0000002A  "\000\000\000*"
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000A <uint32>=0x00000400 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000B <uint32>=0x00000400 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000C <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000D <blob>=0x0000000000000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000E <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000000F <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000010 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000011 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000012 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000013 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000014 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000015 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000016 <uint32>=0x00000001 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000017 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000018 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x00000019 <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: ▸     0x0000001A <uint32>=0x00000000 
INFO [2017-05-19 16:48:35.81]: $ openssl x509 -inform der -in /var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/d20170519-72905-1vchx8e/certs/distribution/JB32NG3UGF.cer -subject -dates -noout &
INFO [2017-05-19 16:48:35.83]: ▸ subject= /UID=7428HDK64H/CN=iPhone Distribution: myCommunity Ltd (7428HDK64H)/OU=7428HDK64H/O=myCommunity Ltd/C=US
INFO [2017-05-19 16:48:35.83]: ▸ notBefore=Apr 10 19:03:48 2017 GMT
INFO [2017-05-19 16:48:35.83]: ▸ notAfter=Apr 10 19:03:48 2018 GMT

+-------------------+---------------------------------------------------+
|                         Installed Certificate                         |
+-------------------+---------------------------------------------------+
| User ID           | 7428HDK64H                                        |
| Common Name       | iPhone Distribution: myCommunity Ltd (7428HDK64H) |
| Organisation Unit | 7428HDK64H                                        |
| Organisation      | myCommunity Ltd                                   |
| Country           | US                                                |
| Start Datetime    | Apr 10 19:03:48 2017 GMT                          |
| End Datetime      | Apr 10 19:03:48 2018 GMT                          |
+-------------------+---------------------------------------------------+

INFO [2017-05-19 16:48:35.83]: Installing provisioning profile...
WARN [2017-05-19 16:48:35.94]: Setting environment variable 'sigh_com.keenvil.ironthrone_adhoc' to '93f353b3-925b-4540-b218-7f25f889d6bb'
WARN [2017-05-19 16:48:35.94]: Setting environment variable 'sigh_com.keenvil.ironthrone_adhoc_team-id' to '7428HDK64H'
WARN [2017-05-19 16:48:35.94]: Setting environment variable 'sigh_com.keenvil.ironthrone_adhoc_profile-name' to 'match AdHoc com.keenvil.ironthrone'
WARN [2017-05-19 16:48:35.94]: Setting environment variable 'sigh_com.keenvil.ironthrone_adhoc_profile-path' to '/Users/Franco/Library/MobileDevice/Provisioning Profiles/93f353b3-925b-4540-b218-7f25f889d6bb.mobileprovision'

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | com.keenvil.ironthron  |
|                     |                        | e                      |
| Type                |                        | adhoc                  |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_com.keenvil.iron  | 93f353b3-925b-4540-b2  |
|                     | throne_adhoc           | 18-7f25f889d6bb        |
| Profile Name        | sigh_com.keenvil.iron  | match AdHoc            |
|                     | throne_adhoc_profile-  | com.keenvil.ironthron  |
|                     | name                   | e                      |
| Profile Path        | sigh_com.keenvil.iron  | /Users/Franco/Library  |
|                     | throne_adhoc_profile-  | /MobileDevice/Provisi  |
|                     | path                   | oning                  |
|                     |                        | Profiles/93f353b3-925  |
|                     |                        | b-4540-b218-7f25f889d  |
|                     |                        | 6bb.mobileprovision    |
| Development Team ID | sigh_com.keenvil.iron  | 7428HDK64H             |
|                     | throne_adhoc_team-id   |                        |
+---------------------+------------------------+------------------------+

INFO [2017-05-19 16:48:35.94]: All required keys, certificates and provisioning profiles are installed 🙌
INFO [2017-05-19 16:48:35.95]: Setting Provisioning Profile type to 'ad-hoc'
INFO [2017-05-19 16:48:35.96]: ------------------------------------
INFO [2017-05-19 16:48:35.96]: --- Step: increment_build_number ---
INFO [2017-05-19 16:48:35.96]: ------------------------------------
INFO [2017-05-19 16:48:35.96]: $ cd /Users/Franco/Projects/clegane-guard/ios && agvtool next-version -all && cd -
INFO [2017-05-19 16:48:36.76]: ▸ Setting version of project cleganeguard to:
INFO [2017-05-19 16:48:36.76]: ▸ 16.
INFO [2017-05-19 16:48:36.78]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2017-05-19 16:48:36.80]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2017-05-19 16:48:36.83]: ▸ Updated CFBundleVersion in "cleganeguard.xcodeproj/../cleganeguard-tvOS/Info.plist" to 16
INFO [2017-05-19 16:48:36.85]: ▸ Updated CFBundleVersion in "cleganeguard.xcodeproj/../cleganeguard-tvOSTests/Info.plist" to 16
INFO [2017-05-19 16:48:36.87]: ▸ Updated CFBundleVersion in "cleganeguard.xcodeproj/../cleganeguard/Info.plist" to 16
INFO [2017-05-19 16:48:36.89]: ▸ Updated CFBundleVersion in "cleganeguard.xcodeproj/../cleganeguardTests/Info.plist" to 16
INFO [2017-05-19 16:48:36.89]: ▸ /Users/Franco/Projects/clegane-guard/ios
INFO [2017-05-19 16:48:37.61]: -----------------------
INFO [2017-05-19 16:48:37.61]: --- Step: cocoapods ---
INFO [2017-05-19 16:48:37.61]: -----------------------
INFO [2017-05-19 16:48:37.87]: gem 'cocoapods' is already installed
INFO [2017-05-19 16:48:37.87]: $ pod install
INFO [2017-05-19 16:48:39.82]: ▸ Analyzing dependencies
INFO [2017-05-19 16:48:39.82]: ▸ Downloading dependencies
INFO [2017-05-19 16:48:39.82]: ▸ Using PPBlinkID (2.7.1)
INFO [2017-05-19 16:48:39.82]: ▸ Generating Pods project
INFO [2017-05-19 16:48:39.82]: ▸ Integrating client project
INFO [2017-05-19 16:48:40.97]: ▸ Sending stats
INFO [2017-05-19 16:48:40.97]: ▸ Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
INFO [2017-05-19 16:48:41.01]: -----------------
INFO [2017-05-19 16:48:41.01]: --- Step: gym ---
INFO [2017-05-19 16:48:41.01]: -----------------
INFO [2017-05-19 16:48:41.57]: $ xcodebuild -list -workspace ./cleganeguard.xcworkspace
INFO [2017-05-19 16:48:43.30]: $ xcodebuild -showBuildSettings -workspace ./cleganeguard.xcworkspace -scheme cleganeguard-qa

+----------------------+--------------------------------------+
|                   Summary for gym 2.32.0                    |
+----------------------+--------------------------------------+
| scheme               | cleganeguard-qa                      |
| export_method        | ad-hoc                               |
| workspace            | ./cleganeguard.xcworkspace           |
| destination          | generic/platform=iOS                 |
| output_name          | cleganeguard                         |
| build_path           | /Users/Franco/Library/Developer/Xco  |
|                      | de/Archives/2017-05-19               |
| clean                | false                                |
| output_directory     | .                                    |
| silent               | false                                |
| skip_package_ipa     | false                                |
| use_legacy_build_api | false                                |
| buildlog_path        | ~/Library/Logs/gym                   |
| xcode_path           | /Applications/Xcode.app              |
+----------------------+--------------------------------------+

+--------------------------------------+----------------------+
|                   Generated Build Command                   |
+--------------------------------------+----------------------+
| Option                               | Value                |
+--------------------------------------+----------------------+
| set -o pipefail &&                   |                      |
| xcodebuild                           |                      |
| -workspace                           |                      |
| ./cleganeguard.xcworkspace           |                      |
| -scheme cleganeguard-qa              |                      |
| -destination                         | generic/platform=iOS |
| -archivePath                         |                      |
| /Users/Franco/Library/Developer/Xco  |                      |
| de/Archives/2017-05-19/cleganeguard  |                      |
| \ 2017-05-19\ 16.48.45.xcarchive     |                      |
| archive                              |                      |
| | tee                                |                      |
| /Users/Franco/Library/Logs/gym/cleg  |                      |
| aneguard-cleganeguard-qa.log         |                      |
| | xcpretty                           |                      |
+--------------------------------------+----------------------+
INFO [2017-05-19 16:48:45.86]: $ set -o pipefail && xcodebuild -workspace ./cleganeguard.xcworkspace -scheme cleganeguard-qa -destination 'generic/platform=iOS' -archivePath /Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard\ 2017-05-19\ 16.48.45.xcarchive archive | tee /Users/Franco/Library/Logs/gym/cleganeguard-cleganeguard-qa.log | xcpretty
INFO [2017-05-19 16:48:47.76]: ▸ Building React/yoga [Release]
INFO [2017-05-19 16:48:47.77]: ▸ Check Dependencies
INFO [2017-05-19 16:48:47.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/yoga/yoga/YGEnums.h
INFO [2017-05-19 16:48:47.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/yoga/yoga/YGMacros.h
INFO [2017-05-19 16:48:47.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.h
INFO [2017-05-19 16:48:47.80]: ▸ Compiling YGNodeList.c
INFO [2017-05-19 16:48:48.09]: ▸ Compiling Yoga.c
INFO [2017-05-19 16:48:49.74]: ▸ Compiling YGNodeList.c
INFO [2017-05-19 16:48:49.74]: ▸ Compiling Yoga.c
INFO [2017-05-19 16:48:49.75]: ▸ Building library libyoga.a
INFO [2017-05-19 16:48:49.76]: ▸ Building library libyoga.a
INFO [2017-05-19 16:48:49.90]: ▸ Building React/jschelpers [Release]
INFO [2017-05-19 16:48:49.90]: ▸ Check Dependencies
INFO [2017-05-19 16:48:49.91]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/jschelpers/JavaScriptCore.h
INFO [2017-05-19 16:48:49.91]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/jschelpers/JSCWrapper.h
INFO [2017-05-19 16:48:49.91]: ▸ Compiling JSCWrapper.cpp
INFO [2017-05-19 16:48:50.38]: ▸ Compiling JSCWrapper.cpp
INFO [2017-05-19 16:48:50.39]: ▸ Building library libjschelpers.a
INFO [2017-05-19 16:48:50.39]: ▸ Building library libjschelpers.a
INFO [2017-05-19 16:48:50.45]: ▸ Building React/cxxreact [Release]
INFO [2017-05-19 16:48:50.45]: ▸ Check Dependencies
INFO [2017-05-19 16:48:50.46]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/ReactCommon/cxxreact/JSBundleType.h
INFO [2017-05-19 16:48:50.46]: ▸ Compiling JSBundleType.cpp
INFO [2017-05-19 16:48:50.88]: ▸ Compiling JSBundleType.cpp
INFO [2017-05-19 16:48:50.88]: ▸ Building library libcxxreact.a
INFO [2017-05-19 16:48:50.89]: ▸ Building library libcxxreact.a
INFO [2017-05-19 16:48:50.94]: ▸ Building React/React [Release]
INFO [2017-05-19 16:48:50.94]: ▸ Check Dependencies
INFO [2017-05-19 16:48:50.95]: ▸ Running script 'Start Packager'
INFO [2017-05-19 16:48:51.02]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/Image/RCTImageLoader.h
INFO [2017-05-19 16:48:51.02]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/Image/RCTImageStoreManager.h
INFO [2017-05-19 16:48:51.02]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/LinkingIOS/RCTLinkingManager.h
INFO [2017-05-19 16:48:51.02]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/Image/RCTResizeMode.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/Network/RCTNetworking.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native/Libraries/Network/RCTNetworkTask.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTAssert.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTBridge.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTBridge+Private.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTBridgeDelegate.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTBridgeMethod.h
INFO [2017-05-19 16:48:51.03]: ▸ Copying Base/RCTBridgeModule.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTBundleURLProvider.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTDefines.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTConvert.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTDisplayLink.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTErrorCustomizer.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTErrorInfo.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTEventDispatcher.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTFrameUpdate.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTImageSource.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTInvalidating.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTJavaScriptExecutor.h
INFO [2017-05-19 16:48:51.04]: ▸ Copying Base/RCTJavaScriptLoader.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTJSStackFrame.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTKeyCommands.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTLog.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTModuleData.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTMultipartDataTask.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTModuleMethod.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTMultipartStreamReader.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTNullability.h
INFO [2017-05-19 16:48:51.05]: ▸ Copying Base/RCTParserUtils.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTPerformanceLogger.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTPlatform.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTRootView.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTRootViewDelegate.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTTouchEvent.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTURLRequestDelegate.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTTouchHandler.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTURLRequestHandler.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTUtils.h
INFO [2017-05-19 16:48:51.06]: ▸ Copying Base/RCTWebSocketObserverProtocol.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Executors/RCTJSCErrorHandling.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/JSCSamplingProfiler.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Executors/RCTJSCExecutor.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTAccessibilityManager.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTAlertManager.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTAppState.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTAsyncLocalStorage.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTClipboard.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTDevLoadingView.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTDevMenu.h
INFO [2017-05-19 16:48:51.07]: ▸ Copying Modules/RCTEventEmitter.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTExceptionsManager.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTI18nUtil.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTI18nManager.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTKeyboardObserver.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTRedBox.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTSourceCode.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTStatusBarManager.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTTiming.h
INFO [2017-05-19 16:48:51.08]: ▸ Copying Modules/RCTUIManager.h
INFO [2017-05-19 16:48:51.09]: ▸ Copying Profiler/RCTFPSGraph.h
INFO [2017-05-19 16:48:51.09]: ▸ Copying Profiler/RCTJSCProfiler.h
INFO [2017-05-19 16:48:51.09]: ▸ Copying Profiler/RCTMacros.h
INFO [2017-05-19 16:48:51.10]: ▸ Copying Profiler/RCTProfile.h
INFO [2017-05-19 16:48:51.10]: ▸ Copying Views/RCTActivityIndicatorView.h
INFO [2017-05-19 16:48:51.10]: ▸ Copying Views/RCTActivityIndicatorViewManager.h
INFO [2017-05-19 16:48:51.10]: ▸ Copying Views/RCTAnimationType.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTAutoInsetsProtocol.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTBorderDrawing.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTBorderStyle.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTComponent.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTComponentData.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTConvert+CoreLocation.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTConvert+MapKit.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTDatePicker.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTDatePickerManager.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTFont.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTMap.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTMapAnnotation.h
INFO [2017-05-19 16:48:51.11]: ▸ Copying Views/RCTMapManager.h
INFO [2017-05-19 16:48:51.12]: ▸ Copying Views/RCTModalHostView.h
INFO [2017-05-19 16:48:51.12]: ▸ Copying Views/RCTMapOverlay.h
INFO [2017-05-19 16:48:51.12]: ▸ Copying Views/RCTModalHostViewController.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTModalHostViewManager.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTNavigator.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTNavigatorManager.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTNavItem.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTNavItemManager.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTPicker.h
INFO [2017-05-19 16:48:51.13]: ▸ Copying Views/RCTPickerManager.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTPointerEvents.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTProgressViewManager.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTRefreshControl.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTScrollableProtocol.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTRefreshControlManager.h
INFO [2017-05-19 16:48:51.16]: ▸ Copying Views/RCTRootShadowView.h
INFO [2017-05-19 16:48:51.17]: ▸ Copying Views/RCTScrollView.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTScrollViewManager.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTSegmentedControlManager.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTShadowView.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTSegmentedControl.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTSlider.h
INFO [2017-05-19 16:48:51.18]: ▸ Copying Views/RCTSliderManager.h
INFO [2017-05-19 16:48:51.19]: ▸ Copying Views/RCTSwitch.h
INFO [2017-05-19 16:48:51.19]: ▸ Copying Views/RCTSwitchManager.h
INFO [2017-05-19 16:48:51.19]: ▸ Copying Views/RCTTabBar.h
INFO [2017-05-19 16:48:51.19]: ▸ Copying Views/RCTTabBarItem.h
INFO [2017-05-19 16:48:51.19]: ▸ Copying Views/RCTTabBarItemManager.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTTabBarManager.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTTextDecorationLineType.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTView.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTViewControllerProtocol.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTViewManager.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTWebViewManager.h
INFO [2017-05-19 16:48:51.20]: ▸ Copying Views/RCTWebView.h
INFO [2017-05-19 16:48:51.21]: ▸ Copying Views/RCTWrapperViewController.h
INFO [2017-05-19 16:48:51.21]: ▸ Copying Views/UIView+Private.h
INFO [2017-05-19 16:48:51.21]: ▸ Copying Views/UIView+React.h
INFO [2017-05-19 16:48:51.21]: ▸ Compiling RCTConvert+MapKit.m
INFO [2017-05-19 16:48:51.42]: ▸ Compiling RCTStatusBarManager.m
INFO [2017-05-19 16:48:51.44]: ▸ Compiling RCTSourceCode.m
INFO [2017-05-19 16:48:51.44]: ▸ Compiling RCTJSCProfiler.m
INFO [2017-05-19 16:48:51.45]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:66:39: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:48:51.45]: ▸ void RCTJSCProfilerStart(JSContextRef ctx)
INFO [2017-05-19 16:48:51.45]: ▸                                       ^
INFO [2017-05-19 16:48:51.45]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:89:43: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:48:51.45]: ▸ NSString *RCTJSCProfilerStop(JSContextRef ctx)
INFO [2017-05-19 16:48:51.45]: ▸                                           ^
INFO [2017-05-19 16:48:51.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:115:45: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:48:51.46]: ▸ BOOL RCTJSCProfilerIsProfiling(JSContextRef ctx)
INFO [2017-05-19 16:48:51.46]: ▸                                             ^
INFO [2017-05-19 16:48:51.46]: ▸ Compiling RCTMultipartStreamReader.m
INFO [2017-05-19 16:48:51.46]: ▸ Compiling RCTDatePicker.m
INFO [2017-05-19 16:48:51.59]: ▸ Compiling RCTFrameUpdate.m
INFO [2017-05-19 16:48:51.59]: ▸ Compiling RCTAlertManager.m
INFO [2017-05-19 16:48:51.74]: ▸ Compiling RCTI18nUtil.m
INFO [2017-05-19 16:48:51.75]: ▸ Compiling RCTJSStackFrame.m
INFO [2017-05-19 16:48:51.75]: ▸ Compiling RCTConvert.m
INFO [2017-05-19 16:48:52.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTConvert.m:344:1: implicit conversion loses integer precision: 'unsigned long long' to 'UIDataDetectorTypes' (aka 'enum UIDataDetectorTypes') [-Wshorten-64-to-32]
INFO [2017-05-19 16:48:52.59]: ▸ RCT_MULTI_ENUM_CONVERTER(UIDataDetectorTypes, (@{
INFO [2017-05-19 16:48:52.59]: ▸ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:48:52.59]: ▸ Compiling RCTSegmentedControl.m
INFO [2017-05-19 16:48:52.59]: ▸ Compiling RCTRootView.m
INFO [2017-05-19 16:48:52.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTRootView.m:414:24: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
INFO [2017-05-19 16:48:52.59]: ▸ [_bridge.uiManager setFrame:frame forView:self];
INFO [2017-05-19 16:48:52.59]: ▸   ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:48:52.59]: ▸ Compiling RCTExceptionsManager.m
INFO [2017-05-19 16:48:52.59]: ▸ Compiling RCTMapAnnotation.m
INFO [2017-05-19 16:48:52.59]: ▸ Compiling RCTDevMenu.mm
INFO [2017-05-19 16:48:53.71]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:763:29: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.71]: ▸ - (void)addItem:(NSString *)title handler:(dispatch_block_t)handler {}
INFO [2017-05-19 16:48:53.71]: ▸ ^
INFO [2017-05-19 16:48:53.71]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:763:61: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.71]: ▸ - (void)addItem:(NSString *)title handler:(dispatch_block_t)handler {}
INFO [2017-05-19 16:48:53.72]: ▸                             ^
INFO [2017-05-19 16:48:53.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:764:31: unused parameter 'item' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.72]: ▸ - (void)addItem:(RCTDevMenu *)item {}
INFO [2017-05-19 16:48:53.72]: ▸                                                             ^
INFO [2017-05-19 16:48:53.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:771:49: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.72]: ▸ + (instancetype)buttonItemWithTitle:(NSString *)title handler:(void(^)(void))handler {return nil;}
INFO [2017-05-19 16:48:53.72]: ▸                               ^
INFO [2017-05-19 16:48:53.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:771:78: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.72]: ▸ + (instancetype)buttonItemWithTitle:(NSString *)title handler:(void(^)(void))handler {return nil;}
INFO [2017-05-19 16:48:53.72]: ▸                                                 ^
INFO [2017-05-19 16:48:53.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:772:47: unused parameter 'key' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.72]: ▸ + (instancetype)toggleItemWithKey:(NSString *)key
INFO [2017-05-19 16:48:53.72]: ▸                                                                              ^
INFO [2017-05-19 16:48:53.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:773:47: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.73]: ▸ title:(NSString *)title
INFO [2017-05-19 16:48:53.73]: ▸                                               ^
INFO [2017-05-19 16:48:53.73]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:774:47: unused parameter 'selectedTitle' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.73]: ▸ selectedTitle:(NSString *)selectedTitle
INFO [2017-05-19 16:48:53.73]: ▸                                               ^
INFO [2017-05-19 16:48:53.73]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:775:59: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:48:53.73]: ▸ handler:(void(^)(BOOL selected))handler {return nil;}
INFO [2017-05-19 16:48:53.73]: ▸                                               ^
INFO [2017-05-19 16:48:53.73]: ▸ Compiling RCTRootShadowView.m
INFO [2017-05-19 16:48:53.73]: ▸ Compiling RCTModuleMethod.m
INFO [2017-05-19 16:48:53.73]: ▸ Compiling RCTMultipartDataTask.m
INFO [2017-05-19 16:48:53.73]: ▸ Compiling RCTBorderDrawing.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTAssert.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTSlider.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTAsyncLocalStorage.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTProgressViewManager.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTFPSGraph.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTSwitch.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTDisplayLink.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTSwitchManager.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTActivityIndicatorViewManager.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTViewManager.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTImageSource.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTDatePickerManager.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTEventEmitter.m
INFO [2017-05-19 16:48:53.74]: ▸ Compiling RCTJavaScriptLoader.mm
INFO [2017-05-19 16:48:55.08]: ▸ Compiling RCTPerfMonitor.m
INFO [2017-05-19 16:48:55.08]: ▸ Compiling RCTFont.mm
INFO [2017-05-19 16:48:55.08]: ▸ Compiling RCTScrollViewManager.m
INFO [2017-05-19 16:48:55.08]: ▸ Compiling RCTTabBarManager.m
INFO [2017-05-19 16:48:55.08]: ▸ Compiling JSCSamplingProfiler.m
INFO [2017-05-19 16:48:55.09]: ▸ Compiling RCTWrapperViewController.m
INFO [2017-05-19 16:48:55.09]: ▸ Compiling RCTScrollView.m
INFO [2017-05-19 16:48:55.09]: ▸ Compiling RCTReloadCommand.m
INFO [2017-05-19 16:48:55.09]: ▸ Compiling RCTAccessibilityManager.m
INFO [2017-05-19 16:48:55.09]: ▸ Compiling RCTJSCErrorHandling.mm
INFO [2017-05-19 16:48:55.28]: ▸ Compiling RCTDevLoadingView.m
INFO [2017-05-19 16:48:55.28]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevLoadingView.m:162:26: unused parameter 'enabled' [-Wunused-parameter]
INFO [2017-05-19 16:48:55.28]: ▸ + (void)setEnabled:(BOOL)enabled { }
INFO [2017-05-19 16:48:55.28]: ▸                                                           ^
INFO [2017-05-19 16:48:55.28]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevLoadingView.m:163:46: unused parameter 'progress' [-Wunused-parameter]
INFO [2017-05-19 16:48:55.28]: ▸ - (void)updateProgress:(RCTLoadingProgress *)progress {}
INFO [2017-05-19 16:48:55.28]: ▸                          ^
INFO [2017-05-19 16:48:55.28]: ▸ Compiling RCTTiming.m
INFO [2017-05-19 16:48:55.28]: ▸ Compiling RCTAppState.m
INFO [2017-05-19 16:48:55.28]: ▸ Compiling RCTJSCExecutor.mm
INFO [2017-05-19 16:48:57.43]: ▸ Compiling RCTBatchedBridge.m
INFO [2017-05-19 16:48:57.43]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:737:6: code will never be executed [-Wunreachable-code]
INFO [2017-05-19 16:48:57.43]: ▸ [self enqueueJSCall:@"RCTLog"
INFO [2017-05-19 16:48:57.43]: ▸                                              ^
INFO [2017-05-19 16:48:57.43]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:813:14: unused variable 'length' [-Wunused-variable]
INFO [2017-05-19 16:48:57.43]: ▸ JSValue *length = result[@"length"];
INFO [2017-05-19 16:48:57.43]: ▸      ^~~~
INFO [2017-05-19 16:48:57.43]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:1082:43: unused parameter 'callback' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.43]: ▸ - (void)stopProfiling:(void (^)(NSData *))callback
INFO [2017-05-19 16:48:57.43]: ▸              ^
INFO [2017-05-19 16:48:57.43]: ▸ Compiling UIView+React.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTSliderManager.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTClipboard.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTModuleData.mm
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTPerformanceLogger.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTTouchHandler.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTErrorInfo.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTLog.mm
INFO [2017-05-19 16:48:57.44]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTLog.mm:188:29: unused function 'nativeStackFrameRegex' [-Wunused-function]
INFO [2017-05-19 16:48:57.44]: ▸ static NSRegularExpression *nativeStackFrameRegex()
INFO [2017-05-19 16:48:57.44]: ▸                                           ^
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTNavItemManager.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTParserUtils.m
INFO [2017-05-19 16:48:57.44]: ▸ Compiling RCTView.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTPlatform.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTMapOverlay.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTKeyboardObserver.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTI18nManager.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTConvert+CoreLocation.m
INFO [2017-05-19 16:48:57.45]: ▸ Compiling RCTTabBarItemManager.m
INFO [2017-05-19 16:48:57.46]: ▸ Compiling RCTKeyCommands.m
INFO [2017-05-19 16:48:57.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:368:49: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.46]: ▸ - (void)registerKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:48:57.46]: ▸                             ^
INFO [2017-05-19 16:48:57.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:369:57: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.46]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:48:57.46]: ▸                                                 ^
INFO [2017-05-19 16:48:57.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:370:63: unused parameter 'block' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.46]: ▸ action:(void (^)(UIKeyCommand *))block {}
INFO [2017-05-19 16:48:57.46]: ▸                                                         ^
INFO [2017-05-19 16:48:57.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:372:51: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.46]: ▸ - (void)unregisterKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:48:57.46]: ▸                                                               ^
INFO [2017-05-19 16:48:57.46]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:373:59: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.47]: ▸ modifierFlags:(UIKeyModifierFlags)flags {}
INFO [2017-05-19 16:48:57.47]: ▸                                                   ^
INFO [2017-05-19 16:48:57.47]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:375:52: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.47]: ▸ - (BOOL)isKeyCommandRegisteredForInput:(NSString *)input
INFO [2017-05-19 16:48:57.47]: ▸                                                           ^
INFO [2017-05-19 16:48:57.48]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:376:60: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.48]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:48:57.48]: ▸                                                    ^
INFO [2017-05-19 16:48:57.48]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:381:60: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.48]: ▸ - (void)registerDoublePressKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:48:57.48]: ▸                                                            ^
INFO [2017-05-19 16:48:57.48]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:382:57: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.48]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:48:57.48]: ▸                                                            ^
INFO [2017-05-19 16:48:57.48]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:383:63: unused parameter 'block' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.48]: ▸ action:(void (^)(UIKeyCommand *))block {}
INFO [2017-05-19 16:48:57.48]: ▸                                                         ^
INFO [2017-05-19 16:48:57.48]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:385:62: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.48]: ▸ - (void)unregisterDoublePressKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:48:57.49]: ▸                                                               ^
INFO [2017-05-19 16:48:57.49]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:386:59: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.49]: ▸ modifierFlags:(UIKeyModifierFlags)flags {}
INFO [2017-05-19 16:48:57.49]: ▸                                                              ^
INFO [2017-05-19 16:48:57.49]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:388:63: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.49]: ▸ - (BOOL)isDoublePressKeyCommandRegisteredForInput:(NSString *)input
INFO [2017-05-19 16:48:57.49]: ▸                                                           ^
INFO [2017-05-19 16:48:57.49]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:389:60: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:48:57.49]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:48:57.49]: ▸                                                               ^
INFO [2017-05-19 16:48:57.50]: ▸ Compiling RCTUtils.m
INFO [2017-05-19 16:48:57.93]: ▸ Compiling RCTMapManager.m
INFO [2017-05-19 16:48:57.93]: ▸ Compiling RCTRefreshControl.m
INFO [2017-05-19 16:48:57.93]: ▸ Compiling RCTWebView.m
INFO [2017-05-19 16:48:57.93]: ▸ Compiling RCTBridge.m
INFO [2017-05-19 16:48:57.93]: ▸ Compiling RCTWebViewManager.m
INFO [2017-05-19 16:48:58.09]: ▸ Compiling RCTPicker.m
INFO [2017-05-19 16:48:58.09]: ▸ Compiling RCTTabBarItem.m
INFO [2017-05-19 16:48:58.09]: ▸ Compiling RCTModalHostView.m
INFO [2017-05-19 16:48:58.21]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTModalHostView.m:59:24: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
INFO [2017-05-19 16:48:58.21]: ▸ [_bridge.uiManager setFrame:newBounds forView:_reactSubview];
INFO [2017-05-19 16:48:58.21]: ▸                                                            ^
INFO [2017-05-19 16:48:58.21]: ▸ Compiling RCTShadowView.m
INFO [2017-05-19 16:48:58.72]: ▸ Compiling RCTSegmentedControlManager.m
INFO [2017-05-19 16:48:58.72]: ▸ Compiling RCTPickerManager.m
INFO [2017-05-19 16:48:58.72]: ▸ Compiling RCTRefreshControlManager.m
INFO [2017-05-19 16:48:58.72]: ▸ Compiling RCTBundleURLProvider.m
INFO [2017-05-19 16:48:58.73]: ▸ Compiling RCTActivityIndicatorView.m
INFO [2017-05-19 16:48:58.73]: ▸ Compiling RCTNavigator.m
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTNavigator.m:602:59: unused parameter 'wrapperViewController' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ - (void)wrapperViewController:(RCTWrapperViewController *)wrapperViewController
INFO [2017-05-19 16:48:58.81]: ▸ ^
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTNavigator.m:603:57: unused parameter 'navigationController' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ didMoveToNavigationController:(UINavigationController *)navigationController
INFO [2017-05-19 16:48:58.81]: ▸                                                           ^
INFO [2017-05-19 16:48:58.81]: ▸ Compiling RCTTabBar.m
INFO [2017-05-19 16:48:58.81]: ▸ Compiling RCTRedBox.m
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:476:57: unused parameter 'errorCustomizer' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ - (void)registerErrorCustomizer:(id<RCTErrorCustomizer>)errorCustomizer {}
INFO [2017-05-19 16:48:58.81]: ▸                                                         ^
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:477:30: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ - (void)showError:(NSError *)message {}
INFO [2017-05-19 16:48:58.81]: ▸                                                         ^
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:478:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ - (void)showErrorMessage:(NSString *)message {}
INFO [2017-05-19 16:48:58.81]: ▸                              ^
INFO [2017-05-19 16:48:58.81]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:479:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.81]: ▸ - (void)showErrorMessage:(NSString *)message withDetails:(NSString *)details {}
INFO [2017-05-19 16:48:58.81]: ▸                                      ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:479:70: unused parameter 'details' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.82]: ▸ - (void)showErrorMessage:(NSString *)message withDetails:(NSString *)details {}
INFO [2017-05-19 16:48:58.82]: ▸                                      ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:480:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.82]: ▸ - (void)showErrorMessage:(NSString *)message withRawStack:(NSString *)rawStack {}
INFO [2017-05-19 16:48:58.82]: ▸                                                                      ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:480:71: unused parameter 'rawStack' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.82]: ▸ - (void)showErrorMessage:(NSString *)message withRawStack:(NSString *)rawStack {}
INFO [2017-05-19 16:48:58.82]: ▸                                      ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:481:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.82]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:48:58.82]: ▸                                                                       ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:481:83: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.82]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:48:58.82]: ▸                                      ^
INFO [2017-05-19 16:48:58.82]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:482:40: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.83]: ▸ - (void)updateErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:48:58.83]: ▸                                                                                   ^
INFO [2017-05-19 16:48:58.83]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:482:85: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.83]: ▸ - (void)updateErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:48:58.83]: ▸                                        ^
INFO [2017-05-19 16:48:58.83]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.83]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:48:58.83]: ▸                                                                                     ^
INFO [2017-05-19 16:48:58.83]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:83: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.83]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:48:58.83]: ▸                                      ^
INFO [2017-05-19 16:48:58.83]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:104: unused parameter 'isUpdate' [-Wunused-parameter]
INFO [2017-05-19 16:48:58.83]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:48:58.83]: ▸                                                                                   ^
INFO [2017-05-19 16:48:58.83]: ▸ Compiling RCTModalHostViewController.m
INFO [2017-05-19 16:48:58.83]: ▸ Compiling RCTMap.m
INFO [2017-05-19 16:48:59.02]: ▸ Compiling RCTNavItem.m
INFO [2017-05-19 16:48:59.02]: ▸ Compiling RCTEventDispatcher.m
INFO [2017-05-19 16:48:59.02]: ▸ Compiling RCTModalHostViewManager.m
INFO [2017-05-19 16:48:59.03]: ▸ Compiling RCTUIManager.m
INFO [2017-05-19 16:49:00.70]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTUIManager.m:239:28: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:00.70]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"didUpdateContentSizeMultiplier"
INFO [2017-05-19 16:49:00.71]: ▸                                                                                                        ^
INFO [2017-05-19 16:49:00.71]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTUIManager.m:387:11: unused variable 'existingView' [-Wunused-variable]
INFO [2017-05-19 16:49:00.71]: ▸ UIView *existingView = _viewRegistry[reactTag];
INFO [2017-05-19 16:49:00.71]: ▸ ^
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTTouchEvent.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTProfile.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTConvert+Transform.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTNavigatorManager.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTComponentData.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTConvert+MapKit.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTStatusBarManager.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTSourceCode.m
INFO [2017-05-19 16:49:00.71]: ▸ Compiling RCTJSCProfiler.m
INFO [2017-05-19 16:49:00.71]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:66:39: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:49:00.71]: ▸ void RCTJSCProfilerStart(JSContextRef ctx)
INFO [2017-05-19 16:49:00.71]: ▸           ^
INFO [2017-05-19 16:49:00.71]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:89:43: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:49:00.71]: ▸ NSString *RCTJSCProfilerStop(JSContextRef ctx)
INFO [2017-05-19 16:49:00.71]: ▸                                       ^
INFO [2017-05-19 16:49:00.72]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Profiler/RCTJSCProfiler.m:115:45: unused parameter 'ctx' [-Wunused-parameter]
INFO [2017-05-19 16:49:00.72]: ▸ BOOL RCTJSCProfilerIsProfiling(JSContextRef ctx)
INFO [2017-05-19 16:49:00.72]: ▸                                           ^
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTMultipartStreamReader.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTDatePicker.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTFrameUpdate.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTAlertManager.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTI18nUtil.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTJSStackFrame.m
INFO [2017-05-19 16:49:00.72]: ▸ Compiling RCTConvert.m
INFO [2017-05-19 16:49:00.88]: ▸ Compiling RCTSegmentedControl.m
INFO [2017-05-19 16:49:00.89]: ▸ Compiling RCTRootView.m
INFO [2017-05-19 16:49:00.89]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTRootView.m:414:24: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:00.89]: ▸ [_bridge.uiManager setFrame:frame forView:self];
INFO [2017-05-19 16:49:00.89]: ▸                                             ^
INFO [2017-05-19 16:49:00.89]: ▸ Compiling RCTExceptionsManager.m
INFO [2017-05-19 16:49:00.89]: ▸ Compiling RCTMapAnnotation.m
INFO [2017-05-19 16:49:00.89]: ▸ Compiling RCTDevMenu.mm
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:763:29: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ - (void)addItem:(NSString *)title handler:(dispatch_block_t)handler {}
INFO [2017-05-19 16:49:02.01]: ▸ ^
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:763:61: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ - (void)addItem:(NSString *)title handler:(dispatch_block_t)handler {}
INFO [2017-05-19 16:49:02.01]: ▸                             ^
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:764:31: unused parameter 'item' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ - (void)addItem:(RCTDevMenu *)item {}
INFO [2017-05-19 16:49:02.01]: ▸                                                             ^
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:771:49: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ + (instancetype)buttonItemWithTitle:(NSString *)title handler:(void(^)(void))handler {return nil;}
INFO [2017-05-19 16:49:02.01]: ▸                               ^
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:771:78: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ + (instancetype)buttonItemWithTitle:(NSString *)title handler:(void(^)(void))handler {return nil;}
INFO [2017-05-19 16:49:02.01]: ▸                                                 ^
INFO [2017-05-19 16:49:02.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:772:47: unused parameter 'key' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.01]: ▸ + (instancetype)toggleItemWithKey:(NSString *)key
INFO [2017-05-19 16:49:02.01]: ▸                                                                              ^
INFO [2017-05-19 16:49:02.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:773:47: unused parameter 'title' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.02]: ▸ title:(NSString *)title
INFO [2017-05-19 16:49:02.02]: ▸                                               ^
INFO [2017-05-19 16:49:02.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:774:47: unused parameter 'selectedTitle' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.02]: ▸ selectedTitle:(NSString *)selectedTitle
INFO [2017-05-19 16:49:02.02]: ▸                                               ^
INFO [2017-05-19 16:49:02.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevMenu.mm:775:59: unused parameter 'handler' [-Wunused-parameter]
INFO [2017-05-19 16:49:02.02]: ▸ handler:(void(^)(BOOL selected))handler {return nil;}
INFO [2017-05-19 16:49:02.02]: ▸                                               ^
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTRootShadowView.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTModuleMethod.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTMultipartDataTask.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTBorderDrawing.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTAssert.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTSlider.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTAsyncLocalStorage.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTProgressViewManager.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTFPSGraph.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTSwitch.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTDisplayLink.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTSwitchManager.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTActivityIndicatorViewManager.m
INFO [2017-05-19 16:49:02.02]: ▸ Compiling RCTViewManager.m
INFO [2017-05-19 16:49:02.11]: ▸ Compiling RCTImageSource.m
INFO [2017-05-19 16:49:02.11]: ▸ Compiling RCTDatePickerManager.m
INFO [2017-05-19 16:49:02.11]: ▸ Compiling RCTEventEmitter.m
INFO [2017-05-19 16:49:02.11]: ▸ Compiling RCTJavaScriptLoader.mm
INFO [2017-05-19 16:49:03.40]: ▸ Compiling RCTPerfMonitor.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTFont.mm
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTScrollViewManager.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTTabBarManager.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling JSCSamplingProfiler.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTWrapperViewController.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTScrollView.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTReloadCommand.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTAccessibilityManager.m
INFO [2017-05-19 16:49:03.41]: ▸ Compiling RCTJSCErrorHandling.mm
INFO [2017-05-19 16:49:03.65]: ▸ Compiling RCTDevLoadingView.m
INFO [2017-05-19 16:49:03.65]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevLoadingView.m:162:26: unused parameter 'enabled' [-Wunused-parameter]
INFO [2017-05-19 16:49:03.65]: ▸ + (void)setEnabled:(BOOL)enabled { }
INFO [2017-05-19 16:49:03.65]: ▸                                                           ^
INFO [2017-05-19 16:49:03.65]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTDevLoadingView.m:163:46: unused parameter 'progress' [-Wunused-parameter]
INFO [2017-05-19 16:49:03.65]: ▸ - (void)updateProgress:(RCTLoadingProgress *)progress {}
INFO [2017-05-19 16:49:03.65]: ▸                          ^
INFO [2017-05-19 16:49:03.66]: ▸ Compiling RCTTiming.m
INFO [2017-05-19 16:49:03.66]: ▸ Compiling RCTAppState.m
INFO [2017-05-19 16:49:03.66]: ▸ Compiling RCTJSCExecutor.mm
INFO [2017-05-19 16:49:05.52]: ▸ Compiling RCTBatchedBridge.m
INFO [2017-05-19 16:49:05.52]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:737:6: code will never be executed [-Wunreachable-code]
INFO [2017-05-19 16:49:05.52]: ▸ [self enqueueJSCall:@"RCTLog"
INFO [2017-05-19 16:49:05.52]: ▸                                              ^
INFO [2017-05-19 16:49:05.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:813:14: unused variable 'length' [-Wunused-variable]
INFO [2017-05-19 16:49:05.53]: ▸ JSValue *length = result[@"length"];
INFO [2017-05-19 16:49:05.53]: ▸      ^~~~
INFO [2017-05-19 16:49:05.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTBatchedBridge.m:1082:43: unused parameter 'callback' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.53]: ▸ - (void)stopProfiling:(void (^)(NSData *))callback
INFO [2017-05-19 16:49:05.53]: ▸              ^
INFO [2017-05-19 16:49:05.53]: ▸ Compiling UIView+React.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTSliderManager.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTClipboard.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTModuleData.mm
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTPerformanceLogger.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTTouchHandler.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTErrorInfo.m
INFO [2017-05-19 16:49:05.53]: ▸ Compiling RCTLog.mm
INFO [2017-05-19 16:49:05.74]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTLog.mm:188:29: unused function 'nativeStackFrameRegex' [-Wunused-function]
INFO [2017-05-19 16:49:05.74]: ▸ static NSRegularExpression *nativeStackFrameRegex()
INFO [2017-05-19 16:49:05.74]: ▸                                           ^
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTNavItemManager.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTParserUtils.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTView.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTPlatform.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTMapOverlay.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTKeyboardObserver.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTI18nManager.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTConvert+CoreLocation.m
INFO [2017-05-19 16:49:05.74]: ▸ Compiling RCTTabBarItemManager.m
INFO [2017-05-19 16:49:05.75]: ▸ Compiling RCTKeyCommands.m
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:368:49: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.75]: ▸ - (void)registerKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:49:05.75]: ▸                             ^
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:369:57: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.75]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:49:05.75]: ▸                                                 ^
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:370:63: unused parameter 'block' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.75]: ▸ action:(void (^)(UIKeyCommand *))block {}
INFO [2017-05-19 16:49:05.75]: ▸                                                         ^
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:372:51: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.75]: ▸ - (void)unregisterKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:49:05.75]: ▸                                                               ^
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:373:59: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.75]: ▸ modifierFlags:(UIKeyModifierFlags)flags {}
INFO [2017-05-19 16:49:05.75]: ▸                                                   ^
INFO [2017-05-19 16:49:05.75]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:375:52: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ - (BOOL)isKeyCommandRegisteredForInput:(NSString *)input
INFO [2017-05-19 16:49:05.76]: ▸                                                           ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:376:60: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:49:05.76]: ▸                                                    ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:381:60: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ - (void)registerDoublePressKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:49:05.76]: ▸                                                            ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:382:57: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:49:05.76]: ▸                                                            ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:383:63: unused parameter 'block' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ action:(void (^)(UIKeyCommand *))block {}
INFO [2017-05-19 16:49:05.76]: ▸                                                         ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:385:62: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.76]: ▸ - (void)unregisterDoublePressKeyCommandWithInput:(NSString *)input
INFO [2017-05-19 16:49:05.76]: ▸                                                               ^
INFO [2017-05-19 16:49:05.76]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:386:59: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.77]: ▸ modifierFlags:(UIKeyModifierFlags)flags {}
INFO [2017-05-19 16:49:05.77]: ▸                                                              ^
INFO [2017-05-19 16:49:05.77]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:388:63: unused parameter 'input' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.77]: ▸ - (BOOL)isDoublePressKeyCommandRegisteredForInput:(NSString *)input
INFO [2017-05-19 16:49:05.77]: ▸                                                           ^
INFO [2017-05-19 16:49:05.77]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Base/RCTKeyCommands.m:389:60: unused parameter 'flags' [-Wunused-parameter]
INFO [2017-05-19 16:49:05.77]: ▸ modifierFlags:(UIKeyModifierFlags)flags
INFO [2017-05-19 16:49:05.77]: ▸                                                               ^
INFO [2017-05-19 16:49:05.77]: ▸ Compiling RCTUtils.m
INFO [2017-05-19 16:49:06.13]: ▸ Compiling RCTMapManager.m
INFO [2017-05-19 16:49:06.13]: ▸ Compiling RCTRefreshControl.m
INFO [2017-05-19 16:49:06.14]: ▸ Compiling RCTWebView.m
INFO [2017-05-19 16:49:06.14]: ▸ Compiling RCTBridge.m
INFO [2017-05-19 16:49:06.14]: ▸ Compiling RCTWebViewManager.m
INFO [2017-05-19 16:49:06.33]: ▸ Compiling RCTPicker.m
INFO [2017-05-19 16:49:06.33]: ▸ Compiling RCTTabBarItem.m
INFO [2017-05-19 16:49:06.34]: ▸ Compiling RCTModalHostView.m
INFO [2017-05-19 16:49:06.41]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTModalHostView.m:59:24: 'setFrame:forView:' is deprecated: Use `setSize:forView:` or `setIntrinsicContentSize:forView:` instead. [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:06.41]: ▸ [_bridge.uiManager setFrame:newBounds forView:_reactSubview];
INFO [2017-05-19 16:49:06.41]: ▸                                                            ^
INFO [2017-05-19 16:49:06.41]: ▸ Compiling RCTShadowView.m
INFO [2017-05-19 16:49:06.96]: ▸ Compiling RCTSegmentedControlManager.m
INFO [2017-05-19 16:49:06.96]: ▸ Compiling RCTPickerManager.m
INFO [2017-05-19 16:49:06.96]: ▸ Compiling RCTRefreshControlManager.m
INFO [2017-05-19 16:49:06.96]: ▸ Compiling RCTBundleURLProvider.m
INFO [2017-05-19 16:49:06.97]: ▸ Compiling RCTActivityIndicatorView.m
INFO [2017-05-19 16:49:06.97]: ▸ Compiling RCTNavigator.m
INFO [2017-05-19 16:49:07.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTNavigator.m:602:59: unused parameter 'wrapperViewController' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.01]: ▸ - (void)wrapperViewController:(RCTWrapperViewController *)wrapperViewController
INFO [2017-05-19 16:49:07.01]: ▸ ^
INFO [2017-05-19 16:49:07.01]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Views/RCTNavigator.m:603:57: unused parameter 'navigationController' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.01]: ▸ didMoveToNavigationController:(UINavigationController *)navigationController
INFO [2017-05-19 16:49:07.01]: ▸                                                           ^
INFO [2017-05-19 16:49:07.02]: ▸ Compiling RCTTabBar.m
INFO [2017-05-19 16:49:07.02]: ▸ Compiling RCTRedBox.m
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:476:57: unused parameter 'errorCustomizer' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)registerErrorCustomizer:(id<RCTErrorCustomizer>)errorCustomizer {}
INFO [2017-05-19 16:49:07.02]: ▸                                                         ^
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:477:30: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)showError:(NSError *)message {}
INFO [2017-05-19 16:49:07.02]: ▸                                                         ^
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:478:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)showErrorMessage:(NSString *)message {}
INFO [2017-05-19 16:49:07.02]: ▸                              ^
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:479:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)showErrorMessage:(NSString *)message withDetails:(NSString *)details {}
INFO [2017-05-19 16:49:07.02]: ▸                                      ^
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:479:70: unused parameter 'details' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)showErrorMessage:(NSString *)message withDetails:(NSString *)details {}
INFO [2017-05-19 16:49:07.02]: ▸                                      ^
INFO [2017-05-19 16:49:07.02]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:480:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.02]: ▸ - (void)showErrorMessage:(NSString *)message withRawStack:(NSString *)rawStack {}
INFO [2017-05-19 16:49:07.02]: ▸                                                                      ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:480:71: unused parameter 'rawStack' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)showErrorMessage:(NSString *)message withRawStack:(NSString *)rawStack {}
INFO [2017-05-19 16:49:07.03]: ▸                                      ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:481:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:49:07.03]: ▸                                                                       ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:481:83: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:49:07.03]: ▸                                      ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:482:40: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)updateErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:49:07.03]: ▸                                                                                   ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:482:85: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)updateErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack {}
INFO [2017-05-19 16:49:07.03]: ▸                                        ^
INFO [2017-05-19 16:49:07.03]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:38: unused parameter 'message' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.03]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:49:07.03]: ▸                                                                                     ^
INFO [2017-05-19 16:49:07.04]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:83: unused parameter 'stack' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.04]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:49:07.04]: ▸                                      ^
INFO [2017-05-19 16:49:07.04]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTRedBox.m:483:104: unused parameter 'isUpdate' [-Wunused-parameter]
INFO [2017-05-19 16:49:07.04]: ▸ - (void)showErrorMessage:(NSString *)message withStack:(NSArray<NSDictionary *> *)stack isUpdate:(BOOL)isUpdate {}
INFO [2017-05-19 16:49:07.04]: ▸                                                                                   ^
INFO [2017-05-19 16:49:07.04]: ▸ Compiling RCTModalHostViewController.m
INFO [2017-05-19 16:49:07.04]: ▸ Compiling RCTMap.m
INFO [2017-05-19 16:49:07.26]: ▸ Compiling RCTNavItem.m
INFO [2017-05-19 16:49:07.26]: ▸ Compiling RCTEventDispatcher.m
INFO [2017-05-19 16:49:07.26]: ▸ Compiling RCTModalHostViewManager.m
INFO [2017-05-19 16:49:07.26]: ▸ Compiling RCTUIManager.m
INFO [2017-05-19 16:49:08.16]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTUIManager.m:239:28: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:08.16]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"didUpdateContentSizeMultiplier"
INFO [2017-05-19 16:49:08.16]: ▸                                                                                                        ^
INFO [2017-05-19 16:49:08.16]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native/React/Modules/RCTUIManager.m:387:11: unused variable 'existingView' [-Wunused-variable]
INFO [2017-05-19 16:49:08.16]: ▸ UIView *existingView = _viewRegistry[reactTag];
INFO [2017-05-19 16:49:08.16]: ▸ ^
INFO [2017-05-19 16:49:08.16]: ▸ Compiling RCTTouchEvent.m
INFO [2017-05-19 16:49:08.16]: ▸ Compiling RCTProfile.m
INFO [2017-05-19 16:49:08.16]: ▸ Compiling RCTConvert+Transform.m
INFO [2017-05-19 16:49:08.16]: ▸ Compiling RCTComponentData.m
INFO [2017-05-19 16:49:08.16]: ▸ Compiling RCTNavigatorManager.m
INFO [2017-05-19 16:49:08.18]: ▸ Building library libReact.a
INFO [2017-05-19 16:49:08.27]: ▸ Building library libReact.a
INFO [2017-05-19 16:49:08.56]: ▸ Running script 'Include RCTJSCProfiler'
INFO [2017-05-19 16:49:10.43]: ▸ Building RCTText/RCTText [Release]
INFO [2017-05-19 16:49:10.43]: ▸ Check Dependencies
INFO [2017-05-19 16:49:12.18]: ▸ Building library libRCTText.a
INFO [2017-05-19 16:49:12.19]: ▸ Building library libRCTText.a
INFO [2017-05-19 16:49:12.47]: ▸ Building ReactNativeConfig/ReactNativeConfig [Release]
INFO [2017-05-19 16:49:12.47]: ▸ Check Dependencies
INFO [2017-05-19 16:49:12.48]: ▸ Running script 'Run Script'
INFO [2017-05-19 16:49:12.75]: ▸ Compiling ReactNativeConfig.m
INFO [2017-05-19 16:49:12.86]: ▸ Compiling ReactNativeConfig.m
INFO [2017-05-19 16:49:12.86]: ▸ Building library libReactNativeConfig.a
INFO [2017-05-19 16:49:12.87]: ▸ Building library libReactNativeConfig.a
INFO [2017-05-19 16:49:12.88]: ▸ Copying ReactNativeConfig/ReactNativeConfig.h
INFO [2017-05-19 16:49:12.92]: ▸ Building SMXCrashlytics/SMXCrashlytics [Release]
INFO [2017-05-19 16:49:12.92]: ▸ Check Dependencies
INFO [2017-05-19 16:49:12.94]: ▸ Compiling SMXCrashlytics.m
INFO [2017-05-19 16:49:13.17]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:8:18: incompatible integer to pointer conversion initializing 'NSInteger *const' (aka 'int *const') with an expression of type 'int' [-Wint-conversion]
INFO [2017-05-19 16:49:13.17]: ▸ NSInteger *const DefaultCode = 100;
INFO [2017-05-19 16:49:13.17]: ▸           ^
INFO [2017-05-19 16:49:13.17]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:28:14: incompatible integer to pointer conversion assigning to 'NSInteger *' (aka 'int *') from 'int' [-Wint-conversion]
INFO [2017-05-19 16:49:13.17]: ▸ code = [(NSNumber *)codeObject intValue];
INFO [2017-05-19 16:49:13.17]: ▸                  ^             ~~~
INFO [2017-05-19 16:49:13.17]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:36:60: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'int *') to parameter of type 'NSInteger' (aka 'int'); dereference with * [-Wint-conversion]
INFO [2017-05-19 16:49:13.18]: ▸ NSError *error2 = [NSError errorWithDomain:domain code:code userInfo:error];
INFO [2017-05-19 16:49:13.18]: ▸              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:13.18]: ▸ Compiling SMXAnswers.m
INFO [2017-05-19 16:49:13.19]: ▸ Compiling SMXCrashlytics_vers.c
INFO [2017-05-19 16:49:13.19]: ▸ Compiling SMXCrashlytics.m
INFO [2017-05-19 16:49:13.19]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:8:18: incompatible integer to pointer conversion initializing 'NSInteger *const' (aka 'long *const') with an expression of type 'int' [-Wint-conversion]
INFO [2017-05-19 16:49:13.19]: ▸ NSInteger *const DefaultCode = 100;
INFO [2017-05-19 16:49:13.19]: ▸                                                                       ^
INFO [2017-05-19 16:49:13.19]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:28:14: incompatible integer to pointer conversion assigning to 'NSInteger *' (aka 'long *') from 'int' [-Wint-conversion]
INFO [2017-05-19 16:49:13.20]: ▸ code = [(NSNumber *)codeObject intValue];
INFO [2017-05-19 16:49:13.20]: ▸                  ^             ~~~
INFO [2017-05-19 16:49:13.20]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-fabric/ios/SMXCrashlytics/SMXCrashlytics.m:36:60: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'NSInteger' (aka 'long'); dereference with * [-Wint-conversion]
INFO [2017-05-19 16:49:13.20]: ▸ NSError *error2 = [NSError errorWithDomain:domain code:code userInfo:error];
INFO [2017-05-19 16:49:13.20]: ▸              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:13.20]: ▸ Compiling SMXAnswers.m
INFO [2017-05-19 16:49:13.22]: ▸ Compiling SMXCrashlytics_vers.c
INFO [2017-05-19 16:49:13.22]: ▸ Building library libSMXCrashlytics.a
INFO [2017-05-19 16:49:13.23]: ▸ Building library libSMXCrashlytics.a
INFO [2017-05-19 16:49:13.31]: ▸ Building RCTAnimation/RCTAnimation [Release]
INFO [2017-05-19 16:49:13.31]: ▸ Check Dependencies
INFO [2017-05-19 16:49:13.32]: ▸ Compiling RCTFrameAnimation.m
INFO [2017-05-19 16:49:13.50]: ▸ Compiling RCTSpringAnimation.m
INFO [2017-05-19 16:49:13.63]: ▸ Compiling RCTValueAnimatedNode.m
INFO [2017-05-19 16:49:13.63]: ▸ Compiling RCTModuloAnimatedNode.m
INFO [2017-05-19 16:49:13.63]: ▸ Compiling RCTDiffClampAnimatedNode.m
INFO [2017-05-19 16:49:13.63]: ▸ Compiling RCTEventAnimation.m
INFO [2017-05-19 16:49:13.64]: ▸ Compiling RCTStyleAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTMultiplicationAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTPropsAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTInterpolationAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTAdditionAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTDivisionAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTTransformAnimatedNode.m
INFO [2017-05-19 16:49:14.13]: ▸ Compiling RCTFrameAnimation.m
INFO [2017-05-19 16:49:14.17]: ▸ Compiling RCTSpringAnimation.m
INFO [2017-05-19 16:49:14.38]: ▸ Compiling RCTValueAnimatedNode.m
INFO [2017-05-19 16:49:14.39]: ▸ Compiling RCTModuloAnimatedNode.m
INFO [2017-05-19 16:49:14.39]: ▸ Compiling RCTDiffClampAnimatedNode.m
INFO [2017-05-19 16:49:14.39]: ▸ Compiling RCTEventAnimation.m
INFO [2017-05-19 16:49:14.39]: ▸ Compiling RCTStyleAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTMultiplicationAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTPropsAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTInterpolationAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTAdditionAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTDivisionAnimatedNode.m
INFO [2017-05-19 16:49:14.75]: ▸ Compiling RCTTransformAnimatedNode.m
INFO [2017-05-19 16:49:14.76]: ▸ Building library libRCTAnimation.a
INFO [2017-05-19 16:49:14.77]: ▸ Building library libRCTAnimation.a
INFO [2017-05-19 16:49:15.08]: ▸ Building RCTNetwork/RCTNetwork [Release]
INFO [2017-05-19 16:49:15.08]: ▸ Check Dependencies
INFO [2017-05-19 16:49:16.89]: ▸ Building library libRCTNetwork.a
INFO [2017-05-19 16:49:16.90]: ▸ Building library libRCTNetwork.a
INFO [2017-05-19 16:49:17.07]: ▸ Building RCTGeolocation/RCTGeolocation [Release]
INFO [2017-05-19 16:49:17.07]: ▸ Check Dependencies
INFO [2017-05-19 16:49:17.29]: ▸ Building library libRCTGeolocation.a
INFO [2017-05-19 16:49:17.29]: ▸ Building library libRCTGeolocation.a
INFO [2017-05-19 16:49:17.35]: ▸ Building RCTLinking/RCTLinking [Release]
INFO [2017-05-19 16:49:17.35]: ▸ Check Dependencies
INFO [2017-05-19 16:49:17.49]: ▸ Building library libRCTLinking.a
INFO [2017-05-19 16:49:17.49]: ▸ Building library libRCTLinking.a
INFO [2017-05-19 16:49:17.55]: ▸ Building RCTCamera/RCTCamera [Release]
INFO [2017-05-19 16:49:17.55]: ▸ Check Dependencies
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:62:10: comparison of address of 'AVMetadataObjectTypeInterleaved2of5Code' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.57]: ▸ if (&AVMetadataObjectTypeInterleaved2of5Code != NULL) {
INFO [2017-05-19 16:49:18.57]: ▸                                                                       ^
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:66:9: comparison of address of 'AVMetadataObjectTypeITF14Code' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.57]: ▸ if(&AVMetadataObjectTypeITF14Code != NULL){
INFO [2017-05-19 16:49:18.57]: ▸          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:70:9: comparison of address of 'AVMetadataObjectTypeDataMatrixCode' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.57]: ▸ if(&AVMetadataObjectTypeDataMatrixCode != NULL){
INFO [2017-05-19 16:49:18.57]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:238:20: incompatible integer to pointer conversion assigning to 'NSInteger *' (aka 'int *') from 'NSInteger' (aka 'int') [-Wint-conversion]
INFO [2017-05-19 16:49:18.57]: ▸ self.flashMode = [RCTConvert NSInteger:json];
INFO [2017-05-19 16:49:18.57]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:251:57: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'int *') to parameter of type 'AVCaptureFlashMode' (aka 'enum AVCaptureFlashMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.57]: ▸ if (device.hasFlash && [device isFlashModeSupported:self.flashMode])
INFO [2017-05-19 16:49:18.57]: ▸                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:18.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:256:34: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'int *') to parameter of type 'AVCaptureFlashMode' (aka 'enum AVCaptureFlashMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.57]: ▸ [device setFlashMode:self.flashMode];
INFO [2017-05-19 16:49:18.57]: ▸                                                  ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:269:16: incompatible integer to pointer conversion initializing 'NSInteger *' (aka 'int *') with an expression of type 'NSInteger' (aka 'int') [-Wint-conversion]
INFO [2017-05-19 16:49:18.58]: ▸ NSInteger *torchMode = [RCTConvert NSInteger:json];
INFO [2017-05-19 16:49:18.58]: ▸                                         ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:278:27: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'int *') to parameter of type 'AVCaptureTorchMode' (aka 'enum AVCaptureTorchMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.58]: ▸ [device setTorchMode: torchMode];
INFO [2017-05-19 16:49:18.58]: ▸                ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:614:24: variable 'rotatedCGImage' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
INFO [2017-05-19 16:49:18.58]: ▸ } else if (metadataOrientation == 3) {
INFO [2017-05-19 16:49:18.58]: ▸                                         ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:903:38: 'sendAppEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.58]: ▸ [self.bridge.eventDispatcher sendAppEventWithName:@"CameraBarCodeRead" body:event];
INFO [2017-05-19 16:49:18.58]: ▸                                    ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:1009:38: 'sendInputEventWithName:body:' is deprecated: Use RCTDirectEventBlock or RCTBubblingEventBlock instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.58]: ▸ [self.bridge.eventDispatcher sendInputEventWithName:@"zoomChanged" body:event];
INFO [2017-05-19 16:49:18.58]: ▸ ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:96:1: method possibly missing a [super insertReactSubview:atIndex:] call [-Wobjc-missing-super-calls]
INFO [2017-05-19 16:49:18.58]: ▸ }
INFO [2017-05-19 16:49:18.58]: ▸ ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:102:1: method possibly missing a [super removeReactSubview:] call [-Wobjc-missing-super-calls]
INFO [2017-05-19 16:49:18.58]: ▸ }
INFO [2017-05-19 16:49:18.58]: ▸ ^
INFO [2017-05-19 16:49:18.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:151:38: 'sendInputEventWithName:body:' is deprecated: Use RCTDirectEventBlock or RCTBubblingEventBlock instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.59]: ▸ [self.bridge.eventDispatcher sendInputEventWithName:@"focusChanged" body:event];
INFO [2017-05-19 16:49:18.59]: ▸ ^
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:62:10: comparison of address of 'AVMetadataObjectTypeInterleaved2of5Code' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.66]: ▸ if (&AVMetadataObjectTypeInterleaved2of5Code != NULL) {
INFO [2017-05-19 16:49:18.66]: ▸ ^
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:66:9: comparison of address of 'AVMetadataObjectTypeITF14Code' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.66]: ▸ if(&AVMetadataObjectTypeITF14Code != NULL){
INFO [2017-05-19 16:49:18.66]: ▸          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:70:9: comparison of address of 'AVMetadataObjectTypeDataMatrixCode' not equal to a null pointer is always true [-Wtautological-pointer-compare]
INFO [2017-05-19 16:49:18.66]: ▸ if(&AVMetadataObjectTypeDataMatrixCode != NULL){
INFO [2017-05-19 16:49:18.66]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:238:20: incompatible integer to pointer conversion assigning to 'NSInteger *' (aka 'long *') from 'NSInteger' (aka 'long') [-Wint-conversion]
INFO [2017-05-19 16:49:18.66]: ▸ self.flashMode = [RCTConvert NSInteger:json];
INFO [2017-05-19 16:49:18.66]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:251:57: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'AVCaptureFlashMode' (aka 'enum AVCaptureFlashMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.66]: ▸ if (device.hasFlash && [device isFlashModeSupported:self.flashMode])
INFO [2017-05-19 16:49:18.66]: ▸                    ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:256:34: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'AVCaptureFlashMode' (aka 'enum AVCaptureFlashMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.66]: ▸ [device setFlashMode:self.flashMode];
INFO [2017-05-19 16:49:18.66]: ▸                                                  ^
INFO [2017-05-19 16:49:18.66]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:269:16: incompatible integer to pointer conversion initializing 'NSInteger *' (aka 'long *') with an expression of type 'NSInteger' (aka 'long') [-Wint-conversion]
INFO [2017-05-19 16:49:18.66]: ▸ NSInteger *torchMode = [RCTConvert NSInteger:json];
INFO [2017-05-19 16:49:18.66]: ▸                                         ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:278:27: incompatible pointer to integer conversion sending 'NSInteger *' (aka 'long *') to parameter of type 'AVCaptureTorchMode' (aka 'enum AVCaptureTorchMode') [-Wint-conversion]
INFO [2017-05-19 16:49:18.67]: ▸ [device setTorchMode: torchMode];
INFO [2017-05-19 16:49:18.67]: ▸                ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:614:24: variable 'rotatedCGImage' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized]
INFO [2017-05-19 16:49:18.67]: ▸ } else if (metadataOrientation == 3) {
INFO [2017-05-19 16:49:18.67]: ▸                                         ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:903:38: 'sendAppEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.67]: ▸ [self.bridge.eventDispatcher sendAppEventWithName:@"CameraBarCodeRead" body:event];
INFO [2017-05-19 16:49:18.67]: ▸                                    ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCameraManager.m:1009:38: 'sendInputEventWithName:body:' is deprecated: Use RCTDirectEventBlock or RCTBubblingEventBlock instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.67]: ▸ [self.bridge.eventDispatcher sendInputEventWithName:@"zoomChanged" body:event];
INFO [2017-05-19 16:49:18.67]: ▸ ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:96:1: method possibly missing a [super insertReactSubview:atIndex:] call [-Wobjc-missing-super-calls]
INFO [2017-05-19 16:49:18.67]: ▸ }
INFO [2017-05-19 16:49:18.67]: ▸ ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:102:1: method possibly missing a [super removeReactSubview:] call [-Wobjc-missing-super-calls]
INFO [2017-05-19 16:49:18.67]: ▸ }
INFO [2017-05-19 16:49:18.67]: ▸ ^
INFO [2017-05-19 16:49:18.67]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-camera/ios/RCTCamera.m:151:38: 'sendInputEventWithName:body:' is deprecated: Use RCTDirectEventBlock or RCTBubblingEventBlock instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:18.67]: ▸ [self.bridge.eventDispatcher sendInputEventWithName:@"focusChanged" body:event];
INFO [2017-05-19 16:49:18.68]: ▸ ^
INFO [2017-05-19 16:49:18.68]: ▸ Building library libRCTCamera.a
INFO [2017-05-19 16:49:18.68]: ▸ Building library libRCTCamera.a
INFO [2017-05-19 16:49:18.82]: ▸ Building RCTWebSocket/RCTWebSocket [Release]
INFO [2017-05-19 16:49:18.82]: ▸ Check Dependencies
INFO [2017-05-19 16:49:19.54]: ▸ Building library libRCTWebSocket.a
INFO [2017-05-19 16:49:19.55]: ▸ Building library libRCTWebSocket.a
INFO [2017-05-19 16:49:19.66]: ▸ Building BlinkIDReactNative/BlinkIDReactNative [Release]
INFO [2017-05-19 16:49:19.67]: ▸ Check Dependencies
INFO [2017-05-19 16:49:19.68]: ▸ Compiling BlinkIDReactNative.mm
INFO [2017-05-19 16:49:21.12]: ▸ Compiling BlinkIDReactNative.mm
INFO [2017-05-19 16:49:21.13]: ▸ Building library libBlinkIDReactNative.a
INFO [2017-05-19 16:49:21.14]: ▸ Building library libBlinkIDReactNative.a
INFO [2017-05-19 16:49:21.15]: ▸ Copying BlinkIDReactNative/BlinkIDReactNative.h
INFO [2017-05-19 16:49:21.21]: ▸ Building RCTVibration/RCTVibration [Release]
INFO [2017-05-19 16:49:21.21]: ▸ Check Dependencies
INFO [2017-05-19 16:49:21.29]: ▸ Building library libRCTVibration.a
INFO [2017-05-19 16:49:21.30]: ▸ Building library libRCTVibration.a
INFO [2017-05-19 16:49:21.34]: ▸ Building RCTImage/RCTImage [Release]
INFO [2017-05-19 16:49:21.34]: ▸ Check Dependencies
INFO [2017-05-19 16:49:21.35]: ▸ Copying RCTImageUtils.h
INFO [2017-05-19 16:49:22.91]: ▸ Building library libRCTImage.a
INFO [2017-05-19 16:49:22.92]: ▸ Building library libRCTImage.a
INFO [2017-05-19 16:49:23.16]: ▸ Building RNNotifications/RNNotifications [Release]
INFO [2017-05-19 16:49:23.16]: ▸ Check Dependencies
INFO [2017-05-19 16:49:23.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:6:23: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.53]: ▸ @property NSDictionary* openedRemoteNotification;
INFO [2017-05-19 16:49:23.53]: ▸         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:23.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.53]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.53]: ▸                       ^
INFO [2017-05-19 16:49:23.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:71: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.53]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.53]: ▸                                  ^
INFO [2017-05-19 16:49:23.53]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:115: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.54]: ▸                                                                       ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:12:40: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)postNotification:(NSDictionary *)notification;
INFO [2017-05-19 16:49:23.54]: ▸                                                                                                                   ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:52: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.54]: ▸                                        ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:36: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.54]: ▸                                                    ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:58: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.54]: ▸                                    ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:42: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.54]: ▸                                                          ^
INFO [2017-05-19 16:49:23.54]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:17:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.54]: ▸ - (void)completeAction:(NSString *)completionKey;
INFO [2017-05-19 16:49:23.55]: ▸                                          ^
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:358:114: format specifies type 'int' but the argument has type 'long' [-Wformat]
INFO [2017-05-19 16:49:23.55]: ▸ NSString* completionKey = [NSString stringWithFormat:@"%@.%@", identifier, [NSString stringWithFormat:@"%d", (long)[[NSDate date] timeIntervalSince1970]]];
INFO [2017-05-19 16:49:23.55]: ▸                                  ^
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:388:30: assigning to 'id<PKPushRegistryDelegate> _Nullable' from incompatible type 'id<UIApplicationDelegate> _Nullable'
INFO [2017-05-19 16:49:23.55]: ▸ pushKitRegistry.delegate = [[UIApplication sharedApplication] delegate];
INFO [2017-05-19 16:49:23.55]: ▸                                                                                                             ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:409:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.55]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationsRegistered" body:notification.userInfo];
INFO [2017-05-19 16:49:23.55]: ▸                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:414:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.55]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationsRegistrationFailed" body:notification.userInfo];
INFO [2017-05-19 16:49:23.55]: ▸ ^
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:419:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.55]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"pushKitRegistered" body:notification.userInfo];
INFO [2017-05-19 16:49:23.55]: ▸ ^
INFO [2017-05-19 16:49:23.55]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:424:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.55]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationReceivedForeground" body:notification.userInfo];
INFO [2017-05-19 16:49:23.55]: ▸ ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:429:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.56]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationReceivedBackground" body:notification.userInfo];
INFO [2017-05-19 16:49:23.56]: ▸ ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:434:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.56]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationOpened" body:notification.userInfo];
INFO [2017-05-19 16:49:23.56]: ▸ ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:439:30: 'sendAppEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.56]: ▸ [_bridge.eventDispatcher sendAppEventWithName:@"notificationActionReceived" body:notification.userInfo];
INFO [2017-05-19 16:49:23.56]: ▸ ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:461:11: format string is not a string literal (potentially insecure) [-Wformat-security]
INFO [2017-05-19 16:49:23.56]: ▸ NSLog(message);
INFO [2017-05-19 16:49:23.56]: ▸ ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:520:32: incompatible pointer types assigning to 'NSDictionary * _Nullable' from 'NSMutableArray *' [-Wincompatible-pointer-types]
INFO [2017-05-19 16:49:23.56]: ▸ localNotification.userInfo = userInfo;
INFO [2017-05-19 16:49:23.56]: ▸           ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:6:23: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.56]: ▸ @property NSDictionary* openedRemoteNotification;
INFO [2017-05-19 16:49:23.56]: ▸                                ^ ~~~~~~~~
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.56]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.56]: ▸                       ^
INFO [2017-05-19 16:49:23.56]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:71: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.57]: ▸                                  ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:115: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.57]: ▸                                                                       ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:12:40: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)postNotification:(NSDictionary *)notification;
INFO [2017-05-19 16:49:23.57]: ▸                                                                                                                   ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:52: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.57]: ▸                                        ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:36: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.57]: ▸                                                    ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:58: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.57]: ▸                                    ^
INFO [2017-05-19 16:49:23.57]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:42: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.57]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.58]: ▸                                                          ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:17:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ - (void)completeAction:(NSString *)completionKey;
INFO [2017-05-19 16:49:23.58]: ▸                                          ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:6:23: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ @property NSDictionary* openedRemoteNotification;
INFO [2017-05-19 16:49:23.58]: ▸                                  ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.58]: ▸                       ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:71: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.58]: ▸                                  ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:115: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.58]: ▸                                                                       ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:12:40: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.58]: ▸ - (void)postNotification:(NSDictionary *)notification;
INFO [2017-05-19 16:49:23.58]: ▸                                                                                                                   ^
INFO [2017-05-19 16:49:23.58]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:52: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.59]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.59]: ▸                                        ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:36: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.59]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.59]: ▸                                                    ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:58: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.59]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.59]: ▸                                    ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:42: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.59]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.59]: ▸                                                          ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:17:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.59]: ▸ - (void)completeAction:(NSString *)completionKey;
INFO [2017-05-19 16:49:23.59]: ▸                                          ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:358:114: format specifies type 'int' but the argument has type 'long' [-Wformat]
INFO [2017-05-19 16:49:23.59]: ▸ NSString* completionKey = [NSString stringWithFormat:@"%@.%@", identifier, [NSString stringWithFormat:@"%d", (long)[[NSDate date] timeIntervalSince1970]]];
INFO [2017-05-19 16:49:23.59]: ▸                                  ^
INFO [2017-05-19 16:49:23.59]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:388:30: assigning to 'id<PKPushRegistryDelegate> _Nullable' from incompatible type 'id<UIApplicationDelegate> _Nullable'
INFO [2017-05-19 16:49:23.59]: ▸ pushKitRegistry.delegate = [[UIApplication sharedApplication] delegate];
INFO [2017-05-19 16:49:23.59]: ▸                                                                                                             ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:409:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationsRegistered" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸                              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:414:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"remoteNotificationsRegistrationFailed" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:419:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"pushKitRegistered" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:424:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationReceivedForeground" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:429:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationReceivedBackground" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:434:30: 'sendDeviceEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendDeviceEventWithName:@"notificationOpened" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:439:30: 'sendAppEventWithName:body:' is deprecated: Subclass RCTEventEmitter instead [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:23.60]: ▸ [_bridge.eventDispatcher sendAppEventWithName:@"notificationActionReceived" body:notification.userInfo];
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:461:11: format string is not a string literal (potentially insecure) [-Wformat-security]
INFO [2017-05-19 16:49:23.60]: ▸ NSLog(message);
INFO [2017-05-19 16:49:23.60]: ▸ ^
INFO [2017-05-19 16:49:23.60]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotifications.m:520:32: incompatible pointer types assigning to 'NSDictionary * _Nullable' from 'NSMutableArray *' [-Wincompatible-pointer-types]
INFO [2017-05-19 16:49:23.60]: ▸ localNotification.userInfo = userInfo;
INFO [2017-05-19 16:49:23.61]: ▸           ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:6:23: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ @property NSDictionary* openedRemoteNotification;
INFO [2017-05-19 16:49:23.61]: ▸                                ^ ~~~~~~~~
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.61]: ▸                       ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:71: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.61]: ▸                                  ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:11:115: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)postAction:(NSDictionary *)action withCompletionKey:(NSString *)completionKey andCompletionHandler:(void (^)())completionHandler;
INFO [2017-05-19 16:49:23.61]: ▸                                                                       ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:12:40: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)postNotification:(NSDictionary *)notification;
INFO [2017-05-19 16:49:23.61]: ▸                                                                                                                   ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:52: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.61]: ▸                                        ^
INFO [2017-05-19 16:49:23.61]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:14:36: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.61]: ▸ - (void)consumeActionsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.61]: ▸                                                    ^
INFO [2017-05-19 16:49:23.62]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:58: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.62]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.62]: ▸                                    ^
INFO [2017-05-19 16:49:23.62]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:15:42: block pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.62]: ▸ - (void)consumeNotificationsQueue:(void (^)(NSDictionary *))block;
INFO [2017-05-19 16:49:23.62]: ▸                                                          ^
INFO [2017-05-19 16:49:23.62]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/node_modules/react-native-notifications/RNNotifications/RNNotificationsBridgeQueue.h:17:34: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
INFO [2017-05-19 16:49:23.62]: ▸ - (void)completeAction:(NSString *)completionKey;
INFO [2017-05-19 16:49:23.62]: ▸                                          ^
INFO [2017-05-19 16:49:23.62]: ▸ Building library libRNNotifications.a
INFO [2017-05-19 16:49:23.62]: ▸ Building library libRNNotifications.a
INFO [2017-05-19 16:49:23.65]: ▸ Building RNDeviceInfo/RNDeviceInfo [Release]
INFO [2017-05-19 16:49:23.65]: ▸ Check Dependencies
INFO [2017-05-19 16:49:23.66]: ▸ Compiling RNDeviceInfo.m
INFO [2017-05-19 16:49:23.86]: ▸ Compiling DeviceUID.m
INFO [2017-05-19 16:49:23.86]: ▸ Compiling DeviceUID.m
INFO [2017-05-19 16:49:23.86]: ▸ Compiling RNDeviceInfo.m
INFO [2017-05-19 16:49:23.86]: ▸ Building library libRNDeviceInfo.a
INFO [2017-05-19 16:49:23.87]: ▸ Building library libRNDeviceInfo.a
INFO [2017-05-19 16:49:23.88]: ▸ Copying RNDeviceInfo/RNDeviceInfo.h
INFO [2017-05-19 16:49:23.94]: ▸ Building Pods/Pods-cleganeguard [Release]
INFO [2017-05-19 16:49:23.94]: ▸ Check Dependencies
INFO [2017-05-19 16:49:23.95]: ▸ Compiling Pods-cleganeguard-dummy.m
INFO [2017-05-19 16:49:24.05]: ▸ Compiling Pods-cleganeguard-dummy.m
INFO [2017-05-19 16:49:24.05]: ▸ Building library libPods-cleganeguard.a
INFO [2017-05-19 16:49:24.06]: ▸ Building library libPods-cleganeguard.a
INFO [2017-05-19 16:49:24.08]: ▸ Building RCTSettings/RCTSettings [Release]
INFO [2017-05-19 16:49:24.09]: ▸ Check Dependencies
INFO [2017-05-19 16:49:24.23]: ▸ Building library libRCTSettings.a
INFO [2017-05-19 16:49:24.23]: ▸ Building library libRCTSettings.a
INFO [2017-05-19 16:49:24.29]: ▸ Building RCTActionSheet/RCTActionSheet [Release]
INFO [2017-05-19 16:49:24.29]: ▸ Check Dependencies
INFO [2017-05-19 16:49:24.47]: ▸ Building library libRCTActionSheet.a
INFO [2017-05-19 16:49:24.48]: ▸ Building library libRCTActionSheet.a
INFO [2017-05-19 16:49:24.53]: ▸ Building RCTUserDefaults/RCTUserDefaults [Release]
INFO [2017-05-19 16:49:24.53]: ▸ Check Dependencies
INFO [2017-05-19 16:49:24.66]: ▸ Building library libRCTUserDefaults.a
INFO [2017-05-19 16:49:24.67]: ▸ Building library libRCTUserDefaults.a
INFO [2017-05-19 16:49:24.72]: ▸ Building RNVectorIcons/RNVectorIcons [Release]
INFO [2017-05-19 16:49:24.73]: ▸ Check Dependencies
INFO [2017-05-19 16:49:24.74]: ▸ Compiling RNVectorIconsManager.m
INFO [2017-05-19 16:49:24.86]: ▸ Compiling RNVectorIconsManager.m
INFO [2017-05-19 16:49:24.86]: ▸ Building library libRNVectorIcons.a
INFO [2017-05-19 16:49:24.87]: ▸ Building library libRNVectorIcons.a
INFO [2017-05-19 16:49:24.92]: ▸ Building cleganeguard/cleganeguard [Release]
INFO [2017-05-19 16:49:24.92]: ▸ Check Dependencies
INFO [2017-05-19 16:49:24.92]: ▸ Preprocessing cleganeguard/Info.plist
INFO [2017-05-19 16:49:24.96]: ▸ Running script '[CP] Check Pods Manifest.lock'
INFO [2017-05-19 16:49:25.00]: ▸ Compiling AppDelegate.m
INFO [2017-05-19 16:49:25.20]: ▸ Compiling main.m
INFO [2017-05-19 16:49:25.20]: ▸ Compiling RCTTestFairyBridge.m
INFO [2017-05-19 16:49:25.34]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/ios/ios/RCTTestFairyBridge.m:21:14: 'setCorrelationId:' is deprecated: Please refer to setUser: [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:25.34]: ▸ [TestFairy setCorrelationId:correlationId];
INFO [2017-05-19 16:49:25.34]: ▸                                  ^
INFO [2017-05-19 16:49:25.34]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/ios/ios/RCTTestFairyBridge.m:27:15: 'identify:traits:' is deprecated: Please refer to setAttribute: [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:25.34]: ▸ [TestFairy identify:correlationId traits:traits];
INFO [2017-05-19 16:49:25.34]: ▸ ^
INFO [2017-05-19 16:49:25.34]: ▸ Compiling cleganeguard_vers.c
INFO [2017-05-19 16:49:25.35]: ▸ Compiling AppDelegate.m
INFO [2017-05-19 16:49:25.35]: ▸ Compiling main.m
INFO [2017-05-19 16:49:25.35]: ▸ Compiling RCTTestFairyBridge.m
INFO [2017-05-19 16:49:25.41]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/ios/ios/RCTTestFairyBridge.m:21:14: 'setCorrelationId:' is deprecated: Please refer to setUser: [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:25.41]: ▸ [TestFairy setCorrelationId:correlationId];
INFO [2017-05-19 16:49:25.41]: ▸ ^
INFO [2017-05-19 16:49:25.41]: ▸ ⚠️  /Users/Franco/Projects/clegane-guard/ios/ios/RCTTestFairyBridge.m:27:15: 'identify:traits:' is deprecated: Please refer to setAttribute: [-Wdeprecated-declarations]
INFO [2017-05-19 16:49:25.41]: ▸ [TestFairy identify:correlationId traits:traits];
INFO [2017-05-19 16:49:25.41]: ▸ ^
INFO [2017-05-19 16:49:25.41]: ▸ Compiling cleganeguard_vers.c
INFO [2017-05-19 16:49:25.42]: ▸ Linking cleganeguard
INFO [2017-05-19 16:49:39.29]: ▸ Linking cleganeguard
INFO [2017-05-19 16:49:39.79]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/rasti/src/assets/fonts/Montserrat-Regular.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/Entypo.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/rasti/src/assets/fonts/Montserrat-Bold.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/EvilIcons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/Foundation.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/FontAwesome.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying Settings.bundle
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/Ionicons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/MaterialCommunityIcons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/MaterialIcons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying ios/upload-dsym.sh
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/Octicons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/SimpleLineIcons.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/react-native-vector-icons/Fonts/Zocial.ttf
INFO [2017-05-19 16:49:39.80]: ▸ Copying /Users/Franco/Projects/clegane-guard/node_modules/valyrian/dist/fonts/valyrian.ttf
INFO [2017-05-19 16:49:39.81]: ▸ Compiling LaunchScreen.xib
INFO [2017-05-19 16:49:43.83]: ▸ Processing Preprocessed-Info.plist
INFO [2017-05-19 16:49:43.83]: ▸ Generating 'cleganeguard.app.dSYM'
INFO [2017-05-19 16:49:44.35]: ▸ Running script 'Bundle React Native code and images'
INFO [2017-05-19 16:49:50.51]: ▸ the transform cache was reset.
INFO [2017-05-19 16:50:46.99]: ▸ Running script 'Execute Crashlytics'
INFO [2017-05-19 16:50:47.07]: ▸ Running script '[CP] Embed Pods Frameworks'
INFO [2017-05-19 16:50:47.11]: ▸ Running script '[CP] Copy Pods Resources'
INFO [2017-05-19 16:50:47.87]: ▸ Touching cleganeguard.app
INFO [2017-05-19 16:50:47.88]: ▸ Signing /Users/Franco/Library/Developer/Xcode/DerivedData/cleganeguard-cxxijhwcokhwfyarbjtgkargerwt/Build/Intermediates/ArchiveIntermediates/cleganeguard-qa/InstallationBuildProductsLocation/Applications/cleganeguard.app
INFO [2017-05-19 16:50:49.80]: ▸ Touching cleganeguard.app.dSYM
INFO [2017-05-19 16:50:50.14]: ▸ Archive Succeeded
DEBUG [2017-05-19 16:50:50.43]: Stored the archive in: /Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard 2017-05-19 16.48.45.xcarchive
WARN [2017-05-19 16:50:50.44]: Generated plist file with the following values:
INFO [2017-05-19 16:50:50.44]: ▸ -----------------------------------------
INFO [2017-05-19 16:50:50.44]: ▸ {
INFO [2017-05-19 16:50:50.44]: ▸   "method": "ad-hoc"
INFO [2017-05-19 16:50:50.44]: ▸ }
INFO [2017-05-19 16:50:50.44]: ▸ -----------------------------------------
INFO [2017-05-19 16:50:50.44]: This results in the following plist file:
INFO [2017-05-19 16:50:50.44]: ▸ -----------------------------------------
INFO [2017-05-19 16:50:50.44]: ▸ <?xml version="1.0" encoding="UTF-8"?>
INFO [2017-05-19 16:50:50.44]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
INFO [2017-05-19 16:50:50.44]: ▸ <plist version="1.0">
INFO [2017-05-19 16:50:50.44]: ▸ <dict>
INFO [2017-05-19 16:50:50.44]: ▸ 	<key>method</key>
INFO [2017-05-19 16:50:50.44]: ▸ 	<string>ad-hoc</string>
INFO [2017-05-19 16:50:50.44]: ▸ </dict>
INFO [2017-05-19 16:50:50.44]: ▸ </plist>
INFO [2017-05-19 16:50:50.44]: ▸ -----------------------------------------
+--------------------------------------+--------------------------------------+
|                          Generated Package Command                          |
+--------------------------------------+--------------------------------------+
| Option                               | Value                                |
+--------------------------------------+--------------------------------------+
| /usr/bin/xcrun                       |                                      |
| /Users/Franco/.rvm/gems/ruby-2.3.0/  |                                      |
| gems/fastlane-2.32.0/gym/lib/assets  |                                      |
| /wrap_xcodebuild/xcbuild-safe.sh     |                                      |
| -exportArchive                       |                                      |
| -exportOptionsPlist                  | /var/folders/_v/v6ttknjn45s_kpvty5g  |
|                                      | 3z3r00000gn/T/gym_config20170519-72  |
|                                      | 905-j7axil.plist                     |
| -archivePath                         |                                      |
| /Users/Franco/Library/Developer/Xco  |                                      |
| de/Archives/2017-05-19/cleganeguard  |                                      |
| \ 2017-05-19\ 16.48.45.xcarchive     |                                      |
| -exportPath                          | /var/folders/_v/v6ttknjn45s_kpvty5g  |
|                                      | 3z3r00000gn/T/gym_output20170519-72  |
|                                      | 905-1yspemp                          |
+--------------------------------------+--------------------------------------+
INFO [2017-05-19 16:50:50.45]: $ /usr/bin/xcrun /Users/Franco/.rvm/gems/ruby-2.3.0/gems/fastlane-2.32.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/gym_config20170519-72905-j7axil.plist' -archivePath /Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard\ 2017-05-19\ 16.48.45.xcarchive -exportPath '/var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/gym_output20170519-72905-1yspemp' 
INFO [2017-05-19 16:50:50.71]: ▸ RVM detected, forcing to use system ruby
INFO [2017-05-19 16:50:51.01]: ▸ Now using system ruby.
INFO [2017-05-19 16:50:51.04]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/gym_config20170519-72905-j7axil.plist -archivePath '/Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard 2017-05-19 16.48.45.xcarchive' -exportPath /var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/gym_output20170519-72905-1yspemp
INFO [2017-05-19 16:50:52.09]: ▸ 2017-05-19 16:50:52.093 xcodebuild[75103:3442067] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/cleganeguard-qa_2017-05-19_16-50-52.092.xcdistributionlogs'.
INFO [2017-05-19 16:50:52.30]: ▸ 1.2.840.113635.100.1.61
INFO [2017-05-19 16:50:52.32]: ▸ 1.2.840.113635.100.1.61
INFO [2017-05-19 16:50:52.34]: ▸ 1.2.840.113635.100.1.61
INFO [2017-05-19 16:50:52.35]: ▸ 1.2.840.113635.100.1.61
INFO [2017-05-19 16:51:04.98]: ▸ Exported cleganeguard 2017-05-19 16.48.45.xcarchive to: /var/folders/_v/v6ttknjn45s_kpvty5g3z3r00000gn/T/gym_output20170519-72905-1yspemp
INFO [2017-05-19 16:51:04.98]: ▸ ** EXPORT SUCCEEDED **
INFO [2017-05-19 16:51:05.18]: ▸ + shell_session_update
INFO [2017-05-19 16:51:05.18]: ▸ /Users/Franco/.rvm/gems/ruby-2.3.0/gems/fastlane-2.32.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 62: shell_session_update: command not found
INFO [2017-05-19 16:51:05.19]: Compressing 1 dSYM(s)
INFO [2017-05-19 16:51:05.19]: $ cd '/Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard 2017-05-19 16.48.45.xcarchive/dSYMs' && zip -r '/Users/Franco/Projects/clegane-guard/ios/cleganeguard.app.dSYM.zip' *.dSYM
INFO [2017-05-19 16:51:05.60]: ▸ updating: cleganeguard.app.dSYM/ (stored 0%)
INFO [2017-05-19 16:51:05.60]: ▸ updating: cleganeguard.app.dSYM/Contents/ (stored 0%)
INFO [2017-05-19 16:51:05.60]: ▸ updating: cleganeguard.app.dSYM/Contents/Info.plist (deflated 52%)
INFO [2017-05-19 16:51:05.61]: ▸ updating: cleganeguard.app.dSYM/Contents/Resources/ (stored 0%)
INFO [2017-05-19 16:51:05.61]: ▸ updating: cleganeguard.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
INFO [2017-05-19 16:51:05.61]: ▸ updating: cleganeguard.app.dSYM/Contents/Resources/DWARF/cleganeguard (deflated 74%)

INFO [2017-05-19 16:51:05.61]: Successfully exported and compressed dSYM file
INFO [2017-05-19 16:51:05.61]: Successfully exported and signed the ipa file:
INFO [2017-05-19 16:51:05.61]: /Users/Franco/Projects/clegane-guard/ios/cleganeguard.ipa
INFO [2017-05-19 16:51:05.61]: -----------------------
INFO [2017-05-19 16:51:05.61]: --- Step: testfairy ---
INFO [2017-05-19 16:51:05.61]: -----------------------
INFO [2017-05-19 16:51:05.61]: Starting with ipa upload to TestFairy...
WARN [2017-05-19 16:51:07.17]: Lane Context:
INFO [2017-05-19 16:51:07.17]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios qa", :SIGH_PROFILE_TYPE=>"ad-hoc", :BUILD_NUMBER=>"16", :IPA_OUTPUT_PATH=>"/Users/Franco/Projects/clegane-guard/ios/cleganeguard.ipa", :DSYM_OUTPUT_PATH=>"/Users/Franco/Projects/clegane-guard/ios/cleganeguard.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/Franco/Library/Developer/Xcode/Archives/2017-05-19/cleganeguard 2017-05-19 16.48.45.xcarchive"}
ERROR [2017-05-19 16:51:07.17]: Unknown option: shake
INFO [2017-05-19 16:51:07.17]: Successfully generated documentation at path '/Users/Franco/Projects/clegane-guard/ios/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | match                  | 4           |
| 4    | increment_build_numbe  | 1           |
|      | r                      |             |
| 5    | cocoapods              | 3           |
| 6    | gym                    | 144         |
| 💥   | testfairy              | 0           |
+------+------------------------+-------------+

ERROR [2017-05-19 16:51:07.19]: fastlane finished with errors




</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.8"

default_platform :ios

platform :ios do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Test Fairy"

  lane :qa do
    match(
      force_for_new_devices: true,
      readonly: true,
      type: "adhoc",
      git_url: "..."
    )

    increment_build_number(xcodeproj: 'cleganeguard.xcodeproj')

    cocoapods

    gym(scheme: "cleganeguard-qa")

    testfairy(
      api_key: "...",
      testers_groups: ["development"],
      notify: "off",
      auto_update: "off",
      symbols_file: Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH],
      options: [ 'shake' ]
    )

    #slack(message: "Successfully deployed new QA Buildto TestFairy!")
  end

  desc "Submit a new Beta Build to Testfairy"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    match(
      force_for_new_devices: true,
      type: "adhoc",
      git_url: "git@github.com:keenvil/braavos.git"
    )

    increment_build_number(xcodeproj: 'cleganeguard.xcodeproj')

    gym(scheme: "cleganeguard-beta")

    testfairy(
      api_key: "...",
      testers_groups: ["development", "product"],
      notify: "on",
      auto_update: "on"
    )

    slack(message: "Successfully deployed new Beta version to TestFairy!")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
#    slack(
#     message: exception.message,
#     success: false
#    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

</details>

<details><summary>`./fastlane/Appfile`</summary>

ruby
app_identifier "com.keenvil.clegane" # The bundle identifier of your app
apple_id "mobile.operator@keenvil.com" # Your Apple email address

team_id "" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.32.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-05-19**
</details>
```

### PR DESCRIPTION
**Pull request by taquitos**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid

### Motivation and Context
fixes https://github.com/fastlane/fastlane/issues/9226
Checks the options array items as strings instead of just symbols

### CODE REVIEW

File: fastlane/lib/fastlane/actions/testfairy.rb [hunk 1]
```diff
@@ -48,10 +48,10 @@ def self.run(params)
 
         options_to_client = lambda do |options|
           options.map do |option|
-            case option
-            when :shake, :anonymous
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/testfairy.rb]: Having symbols in the `where` block is actually more beautiful than the strings. I'd probably do it the other way around and do `option.to_sym` and then have `:shake` and `:anonymous` there.

Comment (taquitos) [inline fastlane/lib/fastlane/actions/testfairy.rb]: Ohh, interesting, yeah. 👍

**Comment by taquitos** [comment]
Alright google bot, I signed it!

**Comment by taquitos** [comment]
Omg googlebot, can I get a break? I signed it! Again!

**Review by KrauseFx — APPROVED** [review]
📮
