### PR TITLE
[action] Fix increment_build_number precondition issue

### LINKED ISSUE #14357: increment_build_number precondition check issue
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
[`increment_build_number`](https://docs.fastlane.tools/actions/increment_build_number/#increment_build_number) can be called with and without `build_number` parameter. In [increment_build_number.rb:33](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_build_number.rb#L33) there's a check if Apple Generic Versioning is enabled, but this is only relevant if no build number is provided, as only in this case Apple Generic Versioning is being used. If `agvtool` is executed with a build number as parameter this number is just being using and inserted in the plist files. So the expectation should be that line 33 is only executed if no build number is provided, otherwise the tool will not work properly.
Workaround for that issue is to set `CURRENT_PROJECT_VERSION` to 1 (or any other number).

##### Command executed
`increment_build_number(
     build_number: "75"
)`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.
Apple Generic Versioning is not enabled in this project.
Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html</pre>
</details>

### Environment

<details>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.6.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | ~/.rbenv/versions/2.6.1/bin/fastlane        |
| Host                        | Mac OS X 10.14.3 (18D109)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.117.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.8.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| bundler                   | 1.17.3       |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2019-03-07**
</details>

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

> increment_build_number can be called with and without build_number parameter.  In [increment_build_number.rb:33](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_build_number.rb#L33) there's a check if Apple Generic Versioning is enabled, but this is only relevant if no build number is provided, as only in this case Apple Generic Versioning is being used.

closes https://github.com/fastlane/fastlane/issues/14357

### Description

* Fixed precondition when `build_number` parameter is set and Apple Generic Versioning  is disabled.
* Added new unit test: pass a custom build number to the tool when Apple Generic Versioning  is disabled. 
* Modified existing unit tests: there's no need to call `agvtool what-version` anymore when `build_number` is passed as parameter (Apple Generic Versioning can be disabled anyway). 
* Updated `build_number` parameter documentation. 

Unit tests + manual testing. Below the results for the project with disabled Apple Generic Versioning 👇 

Screenshot 2019-03-16 at 12 44 40

🙇 🙇

### CODE REVIEW

File: fastlane/lib/fastlane/actions/increment_build_number.rb [hunk 1]
```diff
@@ -62,7 +62,7 @@ def self.available_options
         [
           FastlaneCore::ConfigItem.new(key: :build_number,
                                        env_name: "FL_BUILD_NUMBER_BUILD_NUMBER",
-                                       description: "Change to a specific version",
+                                       description: "Change to a specific version. When you provide this parameter, enabled Apple Generic Versioning is not required",
```
Comment (janpio) [inline fastlane/lib/fastlane/actions/increment_build_number.rb]:
```suggestion
                                       description: "Change to a specific version. When you provide this parameter, Apple Generic Versioning does not have to be enabled",
```

Comment (mollyIV) [reply fastlane/lib/fastlane/actions/increment_build_number.rb]: @janpio done 💪

**Review by janpio — APPROVED** [review]
This looks good to me - but someone with more experience with AGV should have another look before merging this.

File: fastlane/lib/fastlane/actions/increment_build_number.rb [hunk 2]
```diff
@@ -47,7 +47,7 @@ def self.run(params)
         end
 
         # Store the new number in the shared hash
-        build_number = Actions.sh("#{command_prefix} agvtool what-version", log: false).split("\n").last.strip
+        build_number = params[:build_number] ? params[:build_number].to_s.strip : Actions.sh("#{command_prefix} agvtool what-version", log: false).split("\n").last.strip
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/increment_build_number.rb]: Can we find a way to clean this line up a bit? Its a little bit long 🙃 Maybe something like...

```suggestion
        build_number = params[:build_number].to_s.strip
        build_number = Actions.sh("#{command_prefix} agvtool what-version", log: false).split("\n").last.strip if build_number.to_s == ""
```
⚠️ NOTE: I did not test this ^^^

File: fastlane/lib/fastlane/actions/increment_build_number.rb [hunk 3]
```diff
@@ -31,7 +31,7 @@ def self.run(params)
         # Attention: This is NOT the version number - but the build number
 
         agv_enabled = system([command_prefix, 'agvtool what-version', command_suffix].join(' '))
-        raise "Apple Generic Versioning is not enabled." unless agv_enabled
+        raise "Apple Generic Versioning is not enabled." unless agv_enabled || params[:build_number]
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/increment_build_number.rb]: Could we possible change this to an `if` instead of an `unless`? I always struggle with `unless` statements that use `||` and `&&` 😝

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Some small requested changes otherwise this is 👍

**Comment by mollyIV** [comment]
👋 Thanks for the suggestions @joshdholtz 💪 

All fixed 👍 could you please have a 👀 
🙇

File: fastlane/lib/fastlane/actions/increment_build_number.rb (hunk 2 above)
Comment (mollyIV) [reply fastlane/lib/fastlane/actions/increment_build_number.rb]: Works as expected, thanks! 💪

File: fastlane/lib/fastlane/actions/increment_build_number.rb (hunk 3 above)
Comment (mollyIV) [reply fastlane/lib/fastlane/actions/increment_build_number.rb]: Changed to `raise "Apple Generic Versioning is not enabled." if agv_disabled && params[:build_number].nil?` - hopefully it's a bit more clear 🙂

**Review by joshdholtz — APPROVED** [review]
This looks great! Thanks again for another awesome contribution ❤️
