### PR TITLE
Fix fastlane_require edgecases, fixes #6951

### LINKED ISSUE #6951: fastlane_require 'posix/spawn' Unable to resolve dependency
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane require fails on posix spawn. The gem is called `posix-spawn`.

```
fastlane_require 'posix/spawn'
```

```
 `add_always_install': [!] Unable to resolve dependency: user requested 'posix/spawn (>= 0)' (Gem::UnsatisfiableDependencyError)
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12.1                                            |
| Ruby                | 2.3.1                                              |
| Bundler?            | false                                              |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.1                                                |
| Git                 | git version 2.10.1                                 |
| Installation Source | /Users/user/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                         |
| Ruby Lib Dir        | /Users/user/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
---

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| colored                   | 1.2          |
| babosa                    | 1.0.2        |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.12.5       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.11       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| growl                     | 1.0.3        |
| io-console                | 0.4.6        |
| excon                     | 0.54.0       |
| plist                     | 3.2.0        |
| xcodeproj                 | 1.3.1        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2016-11-10**
</details>

### PR DESCRIPTION
**Pull request by milch**
Related: #6951

Fixes:

- Built-in gems like `yaml` are not found
- Correctly finds and installs gems like `posix/spawn` that have a different title

### CODE REVIEW

File: fastlane/lib/fastlane/fastlane_require.rb [hunk 1]
```diff
@@ -16,18 +15,42 @@ def install_gem_if_needed(gem_name: nil, require_gem: true)
...
-        UI.success("Successfully installed '#{gem_name}' to '#{bundle_path}'")
+        installer.install_gem(spec_name, Gem::Requirement.default)
+        UI.success("Successfully installed '#{gem_name}'")
         require gem_require_name if require_gem
       end
 
       def gem_installed?(name, req = Gem::Requirement.default)
+        # We fork and try to load a gem with that name in the child process so we
+        # don't actually load anything we don't want to load
+        # This is just to test if the gem is already preinstalled, e.g. YAML
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/fastlane_require.rb]: Could you also link to the original issue if it comes from an issue?

**Review by KrauseFx — APPROVED** [review]

File: fastlane/lib/fastlane/fastlane_require.rb (hunk 1 above)
Comment (milch) [inline fastlane/lib/fastlane/fastlane_require.rb]: Done 👍

**Comment by janpio** [comment]
Is there a way to test this? 

As expected `fork` is not available on Windows and I will have to mess with this code a bit - but of course don't want to break too much stuff along the way. Which is not that simple as I currently don't fully understand it :/

**Comment by milch** [comment]
I think the best way to do that would be to put the contents of the fork into a separate file that we can simply shell out to. That should work on Windows, and it shouldn't be too hard to separate this out since there's only one parameter that's passed into the fork (`name`).

**Comment by janpio** [comment]
Sorry, I don't understand. Is this a reply to my first question if this can be tested or a solution for how to get this to work on Windows?

I was wondering how I could test the code that was added to `gem_installed` as I don't really understand when this code is actually run and needed. (I now know how to avoid `fork` on Windows and other unsupported OSes, so that part is covered)
