### PR TITLE
[frameit] Fix for issue #11585 to prevent too large text

### LINKED ISSUE #11585: frameit not shrinking text for multiline titles
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After an update to my app is re-ran my `create_screenshots` lane, which generated my screenshots and then ran `frameit`. However, the newly generated image do not seem to be reducing the size of the text of the title, causing the text to be clipped. I see this across multiple iOS devices and computers performing `frameit`. Below is an example from a 9.7" iPad, followed by the original screenshot.

ipad pro 9 7-inch -3actionextension_framed

ipad pro 9 7-inch -3actionextension

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane add_device_frames
[18:23:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[18:23:56]: ----------------------------------------
[18:23:56]: --- Step: Verifying fastlane version ---
[18:23:56]: ----------------------------------------
[18:23:56]: Your fastlane version 2.76.0 matches the minimum requirement of 1.48.0  ✅
[18:23:56]: ------------------------------
[18:23:56]: --- Step: default_platform ---
[18:23:56]: ------------------------------
[18:23:56]: Driving the lane 'ios add_device_frames' 🚀
[18:23:56]: ---------------------
[18:23:56]: --- Step: frameit ---
[18:23:56]: ---------------------
[18:23:56]: Framing screenshots at path fastlane/screenshots/ (via frameit)
[18:23:56]: Using device frames version 'latest'
[18:23:56]: Framing screenshot './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Unknown device type for size iOS-iPad-10.5 for path './default/iPad Pro (10.5-inch)-3ActionExtension.png'
[18:23:56]: Couldn't find template for screenshot type 'Apple true Space Gray'
[18:23:56]: Please run `fastlane frameit download_frames` to download the latest frames
[18:23:56]: Framing screenshot './default/iPad Pro (12.9-inch)-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:11]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPad Pro (12.9-inch)-3ActionExtension_framed.png'
[18:24:11]: Framing screenshot './default/iPad Pro (9.7-inch)-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:19]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPad Pro (9.7-inch)-3ActionExtension_framed.png'
[18:24:19]: Framing screenshot './default/iPhone 4s-3ActionExtension.png'
[18:24:19]: Unfortunately 3.5" device frames were discontinued. Skipping screen './default/iPhone 4s-3ActionExtension.png'
[18:24:19]: Looked for: 'Apple iPhone 4 Space Gray.png'
[18:24:19]: Framing screenshot './default/iPhone 8 Plus-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:27]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone 8 Plus-3ActionExtension_framed.png'
[18:24:27]: Framing screenshot './default/iPhone 8-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:30]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone 8-3ActionExtension_framed.png'
[18:24:30]: Framing screenshot './default/iPhone SE-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:32]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone SE-3ActionExtension_framed.png'
[18:24:32]: Framing screenshot './default/iPhone X-3ActionExtension.png'
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
Forced orientation:
[18:24:39]: Added frame: '/Users/josephduffy/Library/Mobile Documents/com~apple~CloudDocs/Files/Projects/Yetii/Scanula/fastlane/screenshots/default/iPhone X-3ActionExtension_framed.png'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying fastlane  | 0           |
|      | version             |             |
| 2    | default_platform    | 0           |
| 3    | frameit             | 42          |
+------+---------------------+-------------+

[18:24:39]: fastlane.tools finished successfully 🎉
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.48.0"

default_platform :ios

platform :ios do

  desc "Generate and frame screenshots for the App Store"
  lane :create_screenshots do
    snapshot(skip_open_summary: true, devices: ["iPhone 4s"])
    snapshot(skip_open_summary: true)
    add_device_frames
  end

  lane :add_device_frames do
    frameit(path: "fastlane/screenshots/")
  end

  desc "Submit a new build to TestFlight"
  lane :beta do
    match(type: "appstore")
    gym
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :submit do
    match(type: "appstore")
    gym
    deliver
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "redacted"
apple_id "redacted@redacted.com"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.5       |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-01-16**

In case it's also relevant, here's the output of `magick --version` (it is my understanding that `frameit` utilises imagemagick):

```
Version: ImageMagick 7.0.7-21 Q16 x86_64 2018-01-08 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

</details>

### PR DESCRIPTION
**Pull request by funnel20**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This fixes #11585:
* The solution is to also observe the vertical space for the non-stacked option and reduce the text image height when it doesn't fit. Currently only exceeding of the horizontal space results in resizing of the text.
* ~~Added a `UI.message` as a hint to use parameter `font_scale_factor` when vertical resizing is applied.~~
* Renamed variable `smaller` to `image_scale_factor`.
* Corrected the equation for the horizontal scale factor, so the exact padding value is respected.
* Added a `UI.user_error` when parameter `font_scale_factor` = 0, as it should be larger.
* Removed several local variables, which are overcomplicating the code. Example: `title_width = title.width`
* ~~As result of this cleanup, the amount of lines could be reduced with 3, while it passes Rubocop for Metrics/ClassLength. Therefor the comment to disable this Class test is removed.~~
* Suppressed the annoying "Forced orientation: " from the console output when `orientation` is nil.

### Description

The major change to fix this issue is the resizing in `put_title_into_background()` .
Instead of only observing the scale `ratio` for the horizontal direction, I have added a ratio for the vertical direction.
So 2 parameters are calculated: `ratio_horizontal` (existing) and `ratio_vertical`.
When either is larger than 1, scaling will be applied to the maximum of the 2.

The other code changes are done for better readability. Variable names are improved (e.g. `smaller` to `image_scale_factor`) and several internal confusing (and redundant) variables are deleted, such as: `title_width = title.width`.

### CODE REVIEW

File: frameit/lib/frameit/editor.rb [hunk 1]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
       resize_text(title)
       resize_text(keyword)
 
-      title_width = title.width
-      keyword_width = keyword.width
-
-      vertical_padding = vertical_frame_padding
-      keyword_top_space = vertical_padding
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: Didn't this line indicate that the vertical frame padding was _also_ used as the "keyword top space" (which probably means margin-top for the keyword I guess?)

Comment (janpio) [reply frameit/lib/frameit/editor.rb]: What I mean: Using the "vertical_frame_padding" in line 244 doesn't make too much sense, but adding a "keyword margin" or something does make sense. So having some code that makes sure that these two values are identical only looks useless in the first moment, but not when trying to understand what all this code means.

Comment (janpio) [reply frameit/lib/frameit/editor.rb]: Same for the `vertical_frame_padding` variable/method by the way: It is used to get a number, but the number is not used as `frame_padding` any more.

Comment (janpio) [reply frameit/lib/frameit/editor.rb]: (Could it be that you are calling this method over and over right now?)

Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: You're absolutely right. This proofs:
1. my lack of Ruby experience; I can't even discern a variable from a method.
2. there is no proper naming convention in this Class to create that discern.

I'm used to other languages (such as Java, Obj-C, C#) where there is a syntax difference between calling a variable and a method (often by parenthesis in method calls).
So it doesn't help that this Editor Class has a variety of methods with names that imply a property/variable, such as `vertical_frame_padding`. 

I'm taught that a method name always contains a verb. Such as "get_padding", "move_frame_into_container", etc.

Q: Are there any code guidelines and naming conventions for the Fastlane project (or Ruby in general)?

Indeed method `vertical_frame_padding` (and others) are often called in this Class. That's unnecessary and increases computation time, especially since it are often intense File I/O calls to fetch config data from the Framefile.

As this code review comment editor doesn't show the Advanced Editing menu, I'll create a new comment which does so....

**Comment by funnel20** [comment]
Continued discussion of https://github.com/fastlane/fastlane/pull/11624#discussion_r162806816:

I want to:

- Increase the readability of the code
- Reduce computation time

The Editor class many times calls `fetch_config[paramater]` even for the same `parameter`. This Class runs in a loop for every screenshot. So if there are a lot of screenshots (210 in one of our projects) `fetch_config[paramater]` is called thousands of times.
While these few config parameters are static for the complete frameit run.
When other Classes want to access a config parameter they have to implement it again; duplicate of code.

I propose the following ideas:

- Move all required config parameters as read-only properties to a dedicated Class. Like new _Config_ or existing _ConfigParser_. Ideally the properties get the same name as the parameters in the Framefile.
- When that class initialises only once, the parameters are fetched from file.
- Initial values are set when the parameter is not defined. This removes the error-prone situation as this is handled now deep in a non-related class, like setting the default value 0.1 of font_scale_factor in Editor.
- Even the derived parameters (like both horizontal and vertical padding from parameter `padding`) are defined as properties.
- Every class can use the same and once initialised properties over and over again, without any negative computation time effects.

**Benefits**

- [x] Config parameters are initialised only once. This reduces calculation time.
- [x] Derivatives of parameters (like both horizontal and vertical padding from parameter `padding`) are only parsed once and not per class base.
- [x] Central management of config parameters and their default values.
- [x] Removes a lot of code from Editor class.

What do you think?

File: frameit/lib/frameit/editor.rb (hunk 1 above)
Comment (janpio) [reply frameit/lib/frameit/editor.rb]: I have no idea, I am confused by the variable/method thing myself. A few commits ago

**Comment by janpio** [comment]
Feel free to open a new issue for that, this is clearly out of scope for this PR here. I am not really sure there is any reason to make code faster as this hasn't been a complaint - but from the view of "good code" this of course all makes sense. But as usual, I don't really know enough about ruby and fastlane itself to comment on that - other people will have to do that.

File: frameit/lib/frameit/editor.rb (hunk 1 above)
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: I made some measurements, each call to method `vertical_frame_padding` requires 6 to 15 microseconds (e.g. 0.000011 s).
Its called 5 times per screenshot. So the computation time isn't really significant.

What do you want for now?
Do you want me to restore the local params?
I prefer to leave this PR as is, as it fixes issue #11585 which is confirmed by @JosephDuffy.
I will open a new issue to improve the code, which we can do in cooperation with some Ruby experts from the Team.

Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: NB: Measurements were done on a MacBook Pro (Retina, 13-inch, Early 2015) with 2,7 GHz Intel Core i5 and 16 GB RAM.

**Comment by janpio** [comment]
As this PR is clearly useful, what do you think about getting it merged before #11648 is tackled? Undoing just some of your changes should make it good to merge. I will go through the lines and comment "undo" where I think it would be better to go back to the previous code.

File: frameit/lib/frameit/editor.rb [hunk 2]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
       resize_text(title)
       resize_text(keyword)
 
-      title_width = title.width
-      keyword_width = keyword.width
-
-      vertical_padding = vertical_frame_padding
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb (hunk 1 above)
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 3]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
...
-      keyword_top_space = vertical_padding
-
       spacing_between_title_and_keyword = (title.height / 2)
-      title_top_space = vertical_padding + keyword.height + spacing_between_title_and_keyword
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 4]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
...
-      title_left_space = (background.width / 2.0 - title_width / 2.0).round
-      keyword_left_space = (background.width / 2.0 - keyword_width / 2.0).round
+      title_top_space = vertical_frame_padding + keyword.height + spacing_between_title_and_keyword
+      title_left_space = (background.width / 2.0 - title.width / 2.0).round
+      keyword_left_space = (background.width / 2.0 - keyword.width / 2.0).round
 
-      self.space_to_device += title.height + keyword.height + spacing_between_title_and_keyword + vertical_padding
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 5]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
...
+      self.space_to_device += title.height + keyword.height + spacing_between_title_and_keyword + vertical_frame_padding
       title_below_image = fetch_config['title_below_image']
       # keyword
       background = background.composite(keyword, "png") do |c|
         c.compose("Over")
-        c.geometry("+#{keyword_left_space}+#{keyword_top_space}") unless title_below_image
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 6]
```diff
@@ -233,27 +231,20 @@ def put_title_into_background_stacked(background, title, keyword)
...
-        c.geometry("+#{keyword_left_space}+#{background.height - space_to_device + keyword_top_space}") if title_below_image
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 7]
```diff
@@ -277,26 +268,29 @@ def put_title_into_background(background, stack_title)
...
+        UI.verbose("Text for image #{self.screenshot.path} is quite long, reducing font size by #{(100 * (1.0 - image_scale_factor)).round(1)}%")
+        # When the height is reduced more than the width, show a hint to use 'font_scale_factor':
+        UI.message("Hint: Your text height is reduced to fit, probably you use multi-line text. Please consider to use parameter 'font_scale_factor' in your Framefile.json with a value larger than #{fetch_config['font_scale_factor'] || 0.1}. This will create more space #{title_below_image ? 'below' : 'above'} the device frame.") if ratio_vertical > ratio_horizontal
+
+        title.resize("#{(image_scale_factor * title.width).round}x")
+        keyword.resize("#{(image_scale_factor * keyword.width).round}x") if keyword
+        sum_width *= image_scale_factor
       end
 
-      vertical_padding = vertical_frame_padding
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 8]
```diff
@@ -277,26 +268,29 @@ def put_title_into_background(background, stack_title)
...
-      top_space = vertical_padding + (actual_font_size - title.height) / 2
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/editor.rb [hunk 9]
```diff
@@ -277,26 +268,29 @@ def put_title_into_background(background, stack_title)
...
+      top_space = vertical_frame_padding + (actual_font_size - title.height) / 2
       left_space = (background.width / 2.0 - sum_width / 2.0).round
-      title_below_image = fetch_config['title_below_image']
 
-      self.space_to_device += actual_font_size + vertical_padding
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: undo

File: frameit/lib/frameit/screenshot.rb [hunk 10]
```diff
@@ -88,8 +88,6 @@ def frame_orientation
         orientation = block.call(filename)
         valid = [:landscape_left, :landscape_right, :portrait, nil]
         UI.user_error("orientation_block must return #{valid[0..-2].join(', ')} or nil") unless valid.include?(orientation)
-
-        puts("Forced orientation: #{orientation}")
```
Comment (janpio) [inline frameit/lib/frameit/screenshot.rb]: Strictly speaking unrelated change. Is this ok @milch?

**Review by janpio — CHANGES_REQUESTED** [review]
marked all the changes to be undone to get a - I think - mergeable PR

File: frameit/lib/frameit/screenshot.rb (hunk 10 above)
Comment (milch) [reply frameit/lib/frameit/screenshot.rb]: Yeah sure, this can be removed if you think it makes sense

Comment (funnel20) [reply frameit/lib/frameit/screenshot.rb]: I see 5 of these lines in my Terminal per screenshot where `orientation` is nil. So instead of removing it, it can also be extended with an if condition:

```puts("Forced orientation: #{orientation}") unless orientation == nil```

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: I expect you only refer to `vertical_padding = vertical_frame_padding`, not the `...width` parameters above?

**Comment by funnel20** [comment]
@janpio Your requested changes are submitted. Can you verify?

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (janpio) [reply frameit/lib/frameit/editor.rb]: yep, only that exact line - no idea why Github shows those as well...

**Review by janpio — APPROVED** [review]

File: frameit/lib/frameit/editor.rb (hunk 7 above)
Comment (janpio) [reply frameit/lib/frameit/editor.rb]: you re-added the line below with a comment, so this is fine.

File: frameit/lib/frameit/screenshot.rb (hunk 10 above)
Comment (janpio) [reply frameit/lib/frameit/screenshot.rb]: You added this out the `unless`, which should be fine.

**Comment by janpio** [comment]
Yep, looking good now.

I would like to have an additional review from someone else before merging though.

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: Yeah, I added the comment to explain why using it. And to identify it for #11648

File: frameit/lib/frameit/editor.rb [hunk 11]
```diff
@@ -277,24 +271,28 @@ def put_title_into_background(background, stack_title)
...
+      image_scale_factor = 1.0 # default
+      ratio_horizontal = sum_width / (image.width.to_f - horizontal_frame_padding * 2) # The fraction of the text images compared to the left and right padding
+      ratio_vertical = title.height.to_f / actual_font_size # The fraction of the actual height of the images compared to the available space
+      if ratio_horizontal > 1.0 || ratio_vertical > 1.0
+        # If either is too large, resize with the maximum ratio:
+        image_scale_factor = (1.0 / [ratio_horizontal, ratio_vertical].max)
+
+        UI.verbose("Text for image #{self.screenshot.path} is quite long, reducing font size by #{(100 * (1.0 - image_scale_factor)).round(1)}%")
+        # When the height is reduced more than the width, show a hint to use 'font_scale_factor':
+        UI.message("Hint: Your text height is reduced to fit, probably you use multi-line text. Please consider to use parameter 'font_scale_factor' in your Framefile.json with a value larger than #{fetch_config['font_scale_factor'] || 0.1}. This will create more space #{title_below_image ? 'below' : 'above'} the device frame.") if ratio_vertical > ratio_horizontal
```
[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: Do you mean the hint is annoying, or the fact that the screenshot gets a reduced font size?

[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: Or both 🤒

[the remark this answers is not in the document]
Comment (JosephDuffy) [reply frameit/lib/frameit/editor.rb]: Scaling the text makes sense; I want the text to fit within the image. I think if the user is explicitly putting in a line break either they either:

 - Will be using all-multiline labels, at which point the message isn't really helping; or
 - Will be using mixed single- and multi-line labels, which will cause the height of the text to change between screenshots

In the latter case, it could be argued it's useful to be notified of the scaling, but I think this is an edge case and mentioning `font_scale_factor` (this is the only documented place it gets mentioned?) would only "fix" the issue for the multi-line labels, and would break the single-line labels.

[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: Do I understand correctly that you're OK by only removing the hint?

[the remark this answers is not in the document]
Comment (JosephDuffy) [reply frameit/lib/frameit/editor.rb]: Yes, I think removing the hint would be good :)

File: frameit/lib/frameit/screenshot.rb [hunk 12]
```diff
@@ -88,10 +88,10 @@ def frame_orientation
...
       end
 
+      puts("Forced orientation: #{orientation}") unless orientation.nil?
```
[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/screenshot.rb]: Please look at the original code, this was already in.
First I removed the whole line, as it seems to be a debug log and polluting console output.
But I restored it and added the non-null condition.

File: frameit/lib/frameit/editor.rb (hunk 11 above)
[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/editor.rb]: OK, I'll make another commit.

File: frameit/lib/frameit/screenshot.rb (hunk 12 above)
[the remark this answers is not in the document]
Comment (janpio) [reply frameit/lib/frameit/screenshot.rb]: @lacostej would the correct way to be to replace it with `UI.message(...)`?

[the remark this answers is not in the document]
Comment (funnel20) [reply frameit/lib/frameit/screenshot.rb]: 'puts' and 'print' really imply debugging.
Indeed `UI.message()` seems to be more appropriate to write Terminal output.

But what is the benefit of this statement? It echos a setting from the config. And 5 times per screenshot. That's why I removed the complete line in my first commit.

**Comment by funnel20** [comment]
@janpio Latest change is committed. Ready to merge?

**Comment by janpio** [comment]
yep, your code is good (afaik).

**Comment by funnel20** [comment]
Great, than I can work on the other Frameit topics

**Comment by janpio** [comment]
Remember: Use a branch this time ;)

**Comment by funnel20** [comment]
👍
I'll start with a new fork, and will create a branch for each topic.
