### PR TITLE
[nexus_upload] Add support for Nexus 3

### LINKED ISSUE #12336: nexus_upload does not support Nexus 3 upload
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The action `nexus_upload` does not support Nexus 3 upload as decribed in [docs](https://support.sonatype.com/hc/en-us/articles/115006744008-How-can-I-programmatically-upload-an-artifact-into-Nexus-3-). The action should be improved to support latest Nexus 3 version or/and renamed to something like `nexus2_upload`. In addition the output gets following message `[13:35:20]: fastlane.tools finished successfully 🎉` even the `curl` execution fails.

##### Complete output when running fastlane, including the stack trace and command used

<details>
<pre>
$ fastlane ios deploy
[✔] 🚀 
[13:35:19]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[13:35:20]: ----------------------------------------
[13:35:20]: --- Step: Verifying fastlane version ---
[13:35:20]: ----------------------------------------
[13:35:20]: Your fastlane version 2.89.0 matches the minimum requirement of 2.50.0  ✅
[13:35:20]: ------------------------------
[13:35:20]: --- Step: default_platform ---
[13:35:20]: ------------------------------
[13:35:20]: Driving the lane 'ios deploy' 🚀
[13:35:20]: Lane deploy started.
[13:35:20]: --------------------------
[13:35:20]: --- Step: nexus_upload ---
[13:35:20]: --------------------------
[13:35:20]: $ curl --verbose -F p=zip -F hasPom=false -F r=releases -F g=com.organisation.app.Project -F a=Project -F v=0.0.1 -F c=test -F e=ipa -F file=@/Users/user/projects/ios/Project/product/Project.ipa -u user:password http://urlnexus:8081/nexus/service/local/artifact/maven/content
[13:35:20]: ▸ % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[13:35:20]: ▸ Dload  Upload   Total   Spent    Left  Speed
[13:35:20]: ▸ 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 1.1.1.1...
[13:35:20]: ▸ * TCP_NODELAY set
[13:35:20]: ▸ * Connected to urlnexus (1.1.1.1) port 8081 (#0)
[13:35:20]: ▸ * Server auth using Basic with user 'user'
[13:35:20]: ▸ > POST /nexus/service/local/artifact/maven/content HTTP/1.1
[13:35:20]: ▸ > Host: urlnexus:8081
[13:35:20]: ▸ > Authorization: Basic XYZ==
[13:35:20]: ▸ > User-Agent: curl/7.54.0
[13:35:20]: ▸ > Accept: */*
[13:35:20]: ▸ > Content-Length: 5370243
[13:35:20]: ▸ > Expect: 100-continue
[13:35:20]: ▸ > Content-Type: multipart/form-data; boundary=------------------------d59f99470ia0093d
[13:35:20]: ▸ >
[13:35:20]: ▸ < HTTP/1.1 405 HTTP method POST is not supported by this URL
[13:35:20]: ▸ < Date: Wed, 18 Apr 2018 11:35:19 GMT
[13:35:20]: ▸ < Server: Nexus/3.4.0-02 (OSS)
[13:35:20]: ▸ < X-Frame-Options: SAMEORIGIN
[13:35:20]: ▸ < X-Content-Type-Options: nosniff
[13:35:20]: ▸ < Pragma: no-cache
[13:35:20]: ▸ < Cache-Control: post-check=0, pre-check=0
[13:35:20]: ▸ < Expires: 0
[13:35:20]: ▸ < Content-Type: text/html
[13:35:20]: ▸ < Content-Length: 1888
[13:35:20]: ▸ < Connection: close
[13:35:20]: ▸ <
[13:35:20]: ▸ { [1888 bytes data]
[13:35:20]: ▸ 0 5246k  100  1888    0     0   227k      0 --:--:-- --:--:-- --:--:--  230k
[13:35:20]: ▸ * Closing connection 0
[13:35:20]: ▸ <!DOCTYPE html>
[13:35:20]: ▸ <html>
[13:35:20]: ▸ <head>
[13:35:20]: ▸ <title>405 - Nexus Repository Manager</title>
[13:35:20]: ▸ <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
[13:35:20]: ▸ 
[13:35:20]: ▸ <link rel="icon" type="image/png" href="http://urlnexus:8081/favicon-32x32.png?3.4.0-02" sizes="32x32">
[13:35:20]: ▸ <link rel="mask-icon" href="http://urlnexus:8081/safari-pinned-tab.svg?3.4.0-02" color="#5bbad5">
[13:35:20]: ▸ <link rel="icon" type="image/png" href="http://urlnexus:8081/favicon-16x16.png?3.4.0-02" sizes="16x16">
[13:35:20]: ▸ <link rel="shortcut icon" href="http://urlnexus:8081/favicon.ico?3.4.0-02">
[13:35:20]: ▸ <meta name="msapplication-TileImage" content="http://urlnexus:8081/mstile-144x144.png?3.4.0-02">
[13:35:20]: ▸ <meta name="msapplication-TileColor" content="#00a300">
[13:35:20]: ▸ <link rel="stylesheet" type="text/css" href="http://urlnexus:8081/static/css/nexus-content.css?3.4.0-02"/>
[13:35:20]: ▸ </head>
[13:35:20]: ▸ <body>
[13:35:20]: ▸ <div class="nexus-header">
[13:35:20]: ▸ <a href="http://urlnexus:8081">
[13:35:20]: ▸ <div class="product-logo">
[13:35:20]: ▸ 
[13:35:20]: ▸ </div>
[13:35:20]: ▸ <div class="product-id">
[13:35:20]: ▸ <div class="product-id__line-1">
[13:35:20]: ▸ <span class="product-name">Nexus Repository Manager</span>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ <div class="product-id__line-2">
[13:35:20]: ▸ <span class="product-spec">OSS 3.4.0-02</span>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ </a>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ <div class="nexus-body">
[13:35:20]: ▸ <div class="content-header">
[13:35:20]: ▸ 
[13:35:20]: ▸ <span class="title">Error 405</span>
[13:35:20]: ▸ <span class="description">Method Not Allowed</span>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ <div class="content-body">
[13:35:20]: ▸ <div class="content-section">
[13:35:20]: ▸ HTTP method POST is not supported by this URL
[13:35:20]: ▸ </div>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ </div>
[13:35:20]: ▸ </body>
[13:35:20]: ▸ </html>
[13:35:20]: Lane deploy completed successfully.

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | nexus_upload               | 0           |
+------+----------------------------+-------------+

[13:35:20]: fastlane.tools finished successfully 🎉

#######################################################################
# fastlane 2.92.1 is available. You are on 2.89.0.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################

2.92.1 Fix for crash when using match enterprise
* Revert "[match] Correct how match handles enterprise adhoc" (#12328) via Josh Holtz

2.92.0 Improvements and Fixes
* Don't allow spaces in IPA file name being uploaded to ITC (#12321) via Josh Holtz
* [match] Correct how match handles enterprise adhoc (#12281) via Josh Holtz
* [cert] Add option in cert for giving a specific output filename (#12048) via j2shnz
* [swift] Fixed laneContext() returning dictionary in Fastlane.swift (#12313) via Josh Holtz
* [spaceship] Add preorder to availability (#12311) via Josh Holtz
* [deliver] Fix force output files on trade_representative_contact_information (#12290) via Yusuke Arakawa

2.91.0 Improvements and Fix For Crash
* Fix fastlane crash when running a lane (#12298) via Iulian Onofrei
* [pilot]remove emoji from changelog (#12191) via Koen Punt
* Fix incorrect action deprecation notes and details formatting in docs and terminal (#12287) via Iulian Onofrei
* [adb] Pick up ANDROID_SDK_ROOT environment variable (#12198) via Adam Cohen-Rose

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem install fastlane`
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.4                                     |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.1                          |
| Installation Source         | ~/.gem/bin/fastlane                         |
| Host                        | Mac OS X 10.13.4 (17E199)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.2_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
#
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
#
# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# The bundle identifier of the app
app_identifier ENV["APP_IDENTIFIERS"]

# Shared Apple Developer Portal account
apple_id ENV["APPLE_ID"]

# Apple Developer Portal team
team_name ENV["TEAM_NAME"]

# Developer Portal Team ID
team_id ENV["TEAM_ID"]

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.89.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| excon                     | 0.62.0       |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| openssl                   | 2.1.0        |
| io-console                | 0.4.6        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.2        |
</details>

*generated on:* **2018-04-18**
</details>
</pre>
</details>

### PR DESCRIPTION
**Pull request by mdio**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This adds support for uploading artifacts to Nexus 3 and fixes #12336.

I successfully ran the changes against our in house hosted Nexus 3 OSS repository.

### Description
As the endpoint used for Nexus 2 [has been removed in Nexus 3](https://issues.sonatype.org/browse/NEXUS-7763) I had to switch to a different one which expects the parameters in the URL.
Since I don't have a Nexus 2 repository at hand to test, I didn't feel confident enough to move the Nexus 2 code to that endpoint.

### CODE REVIEW

File: fastlane/lib/fastlane/actions/nexus_upload.rb [hunk 1]
```diff
@@ -14,7 +14,23 @@ def self.run(params)
       end
 
       def self.upload_url(params)
-        "#{params[:endpoint]}#{params[:mount_path]}/service/local/artifact/maven/content".shellescape
+        url = "#{params[:endpoint]}#{params[:mount_path]}"
+
+        if params[:nexus_version] == 2
+          url << "/service/local/artifact/maven/content"
+        else
+          file_extension = File.expand_path(params[:file]).split('.').last.shellescape
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/nexus_upload.rb]: You should be able to do something like this extend 😊 - `File.extname(params[:file])`

File: fastlane/lib/fastlane/actions/nexus_upload.rb [hunk 2]
```diff
@@ -107,7 +128,7 @@ def self.available_options
                                        optional: false),
           FastlaneCore::ConfigItem.new(key: :mount_path,
                                        env_name: "FL_NEXUS_MOUNT_PATH",
-                                       description: "Nexus mount path",
+                                       description: "Nexus mount path (note: Nexus 3 instances have this configured as empty by default)",
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/nexus_upload.rb]: Can we remove the `note: ` on this?

Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/nexus_upload.rb]: Can we remove the `note: ` before the Nexus 3 part?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Few small nit picks but this looks really great! Thanks for doing this 😊 Can you also sign the CLA?

File: fastlane/lib/fastlane/actions/nexus_upload.rb (hunk 1 above)
Comment (mdio) [reply fastlane/lib/fastlane/actions/nexus_upload.rb]: Thank you! I will try that.

File: fastlane/lib/fastlane/actions/nexus_upload.rb (hunk 2 above)
Comment (mdio) [reply fastlane/lib/fastlane/actions/nexus_upload.rb]: Sure.

**Comment by mdio** [comment]
Thank you for taking the time to review my PR and for your suggestions.

I will commit the changes on Monday.
Regarding the CLA: I have initiated the process in my company and hope that this will also be done by Monday.

**Comment by mdio** [comment]
@joshdholtz JFYI: There's some progress on the CLA and I'm confident it will be signed tomorrow (latest 16:00 UTC).

**Comment by mdio** [comment]
The CLA should be signed now.

**Comment by mdio** [comment]
I signed it!

**Comment by joshdholtz** [comment]
@mdio No problem! Thanks for the update 😊

**Comment by mdio** [comment]
I signed it!

**Comment by mdio** [comment]
@googlebot I signed it!

**Comment by mdio** [comment]
@joshdholtz CLA is finally signed. Sorry for the delay.

**Review by joshdholtz — APPROVED** [review]
Thanks so much for doing this! ❤️ You are 💯

**Comment by mdio** [comment]
Thank you for your time. :)
