### PR TITLE
[scan] Use pre-2.34.0 strategy if temp junit output is missing

### LINKED ISSUE #9268: [Regression] Scan failing on reading junit_report temp file as of v2.34.0
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When attempting to run Scan it is failing with an error complaining of not being able to find some JUnit log file. We don't use JUnit as part of our project so this was particularly surprising.  I've attached the bottom few pages of Fastlane's output below. 

It would be my guess that the issue is related to this PR https://github.com/fastlane/fastlane/pull/7365.  But I can't pretend to understand enough of what is going on right now to know for sure. 

```
+----------------------------+-------------------------------------------------------------------------------------+
|                                                   Lane Context                                                   |
+----------------------------+-------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                                 |
| PLATFORM_NAME              | ios                                                                                 |
| LANE_NAME                  | ios runUnitTests                                                                    |
| SCAN_DERIVED_DATA_PATH     | /Users/mobile/.jenkins/workspace/CI - Trade Me iOS Pull Requests/iosapp/derivedData |
| SCAN_GENERATED_PLIST_FILES | []                                                                                  |
| SCAN_GENERATED_PLIST_FILE  |                                                                                     |
+----------------------------+-------------------------------------------------------------------------------------+
[12:16:45]: No such file or directory @ rb_sysopen - /var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/junit_report20170525-86740-19nw7dm

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | update_fastlane                                               | 4           |
| 4    | import_from_git                                               | 4           |
| 5    | Switch to ios configure lane                                  | 0           |
| 6    | Switch to ios setup lane                                      | 0           |
| 7    | bundle_install                                                | 0           |
| 8    | setup_jenkins                                                 | 0           |
| 9    | clean_build_artifacts                                         | 0           |
| 10   | clear_derived_data                                            | 0           |
| 11   | update_cache                                                  | 0           |
| 12   | xcode_select                                                  | 0           |
| 💥   | scan                                                          | 459         |
| 14   | xcodebuild -project ../*.xcodeproj -showBuildSettings 2>/dev/ | 3           |
| 15   | slack                                                         | 1           |
+------+---------------------------------------------------------------+-------------+

[12:16:45]: fastlane finished with errors

[12:16:45]: Error accessing file, this might be due to fastlane's directory handling
[12:16:45]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:84:in `read': No such file or directory @ rb_sysopen - /var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/junit_report20170525-86740-19nw7dm (Errno::ENOENT)
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:84:in `test_results'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:49:in `handle_results'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/runner.rb:9:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/scan/lib/scan/manager.rb:14:in `work'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/scan.rb:22:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from ../../../../../../../var/folders/dp/qgbyxqt10mxbjw6gg2p72vbw0000gn/T/fl_clone20170525-86740-wfvzbb/fastlane.git/fastlane/SharedFastfile:37:in `block (2 levels) in parsing_binding'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/mobile/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.35.0/bin/fastlane:20:in `<top (required)>'
	from /Users/mobile/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/mobile/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.18.0"

default_platform :ios

import_from_git(url: 'https://tmstash/scm/bt/fastlane.git', path: 'fastlane/SharedFastfile')

platform :ios do

  before_all do
    configure
    setup
    
    if Helper.is_ci?
      update_cache(
        url: 'https://api.trademe.co.nz/v1/Categories.json',
        data_path: 'TradeMeMain/Resources/Data/categories.json',
        plist_path: 'TradeMeMain/Resources/Data/eTags.plist')

      xcode_select "/Applications/Xcode.app"
    end
  end

  private_lane :configure do |options|
    ENV["TM_TEAM"] = "central-testers"
    ENV["TM_UNIT_TEST_SCHEME"] = "TradeMeMain Tests"
    ENV["TM_UI_TEST_SCHEME"] = "TradeMeUITests"
    ENV["TM_SCHEME"] = "TradeMeMain"
  end

  # You can define as many lanes as you want

  after_all do |lane|
  end
end

# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nz.co.trademe.trademe" # The bundle identifier of your app

# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-badge   | 0.8.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.12.5       |
| json                      | 2.0.4        |
| io-console                | 0.4.5        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| faraday                   | 0.12.0.1     |
| faraday_middleware        | 0.11.0.1     |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.28       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| colored2                  | 3.1.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| fastlane-plugin-appicon   | 0.6.0        |
| curb                      | 0.9.3        |
| badge                     | 0.8.4        |
| fastlane-plugin-badge     | 0.8.2        |
</details>

*generated on:* **2017-05-25**
</details>

### PR DESCRIPTION
**Pull request by keatongreve**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes #9268.
Edit 1: Also fixes an issue reported in the comments, where paths were not wrapped in single quotes, causing issues for paths with spaces in them.

### Description
The fix I implemented in #7365 was to optimize the runtime of `scan` by consolidating all instances of `xcpretty --report #{report} --output #{output}`. One of the `xcpretty` calls is a temp file we use to generate the test output table (# of tests and # of failures). In the case of the issue above, the user's temp file is apparently missing.

The solution is to add a backup plan: If the temp_junit_report file is not found, just rerun
`cat #{xcodebuild_log_file} | xcpretty --report junit ...`
for a new file. This is basically just re-adding the logic from before my fix. Again, `cat` will be slow for large xcodebuild logs, but I suppose we have no other choice at this point.

### Reviewer notes
Since I made a change involving a big indentation (class methods > instance methods), I recommend reading without whitespace changes: https://github.com/fastlane/fastlane/pull/9276/files?w=1.

### CODE REVIEW

File: scan/lib/scan/runner.rb [hunk 1]
```diff
@@ -80,8 +80,16 @@ def handle_results(tests_exit_status)
     end
 
     def test_results
-      return "" unless Scan.cache[:temp_junit_report]
```
Comment (keatongreve) [inline scan/lib/scan/runner.rb]: Still trying to decide if `return ""` is a necessary path in this method now.

Based on the old code ([source](https://github.com/fastlane/fastlane/blob/a1d5794c0189b3a12a45ae6bb60f3eb245473e21/scan/lib/scan/runner.rb)), the original implementation was not concerned with `output_file` being missing or its output being bad, which makes sense to me.

**Review by KrauseFx — APPROVED** [review]
Awesome, thanks for submitting a follow-up PR 👍

**Comment by taquitos** [comment]
@keatongreve is there a way to add a spec for the case when "temp junit output is missing"? I saw you updated the other tests, but I didn't notice this case being checked yet.

File: scan/lib/scan/runner.rb [hunk 2]
```diff
@@ -80,8 +84,16 @@ def handle_results(tests_exit_status)
...
-      File.read(Scan.cache[:temp_junit_report])
+      temp_junit_report = Scan.cache[:temp_junit_report]
+      return File.read(temp_junit_report) if temp_junit_report && File.file?(temp_junit_report)
```
Comment (lacostej) [inline scan/lib/scan/runner.rb]: Here we would generate the file for each call to `test_results`.

What are the code paths that lead to the file not being there?

Why can't we reuse the `XCPrettyReporterOptionsGenerator`?

File: scan/lib/scan/xcpretty_reporter_options_generator.rb [hunk 3]
```diff
@@ -55,7 +55,8 @@ def generate_reporter_options
       # adds another junit reporter in case the user does not specify one
       # this will be used to generate a results table and then discarded
       require 'tempfile'
-      Scan.cache[:temp_junit_report] = Tempfile.new("junit_report").path
+      @temp_junit_report = Tempfile.new("junit_report")
```
Comment (lacostej) [inline scan/lib/scan/xcpretty_reporter_options_generator.rb]: Isn't there still a risk of garbage collection?

```
....pipe                                       # instantiates the XCPrettyReporterOptionsGenerator
   ...generate_reporter_options # instantiate the TempFile
# garbage collection possible before the use of the pipe ?
```

File: scan/lib/scan/runner.rb (hunk 2 above)
Comment (keatongreve) [inline scan/lib/scan/runner.rb]: 1. `test_results` is only called once per run of scan, so I think that is fine.
2. We believe the garbage collection is causing the tempfile to be deleted before this code is hit.
3. There really isn't a reason, I just thought that writing out the whole `cat #{file} | xcpretty --report junit --output ...` was much more straightforward.

File: scan/lib/scan/xcpretty_reporter_options_generator.rb (hunk 3 above)
Comment (keatongreve) [inline scan/lib/scan/xcpretty_reporter_options_generator.rb]: I'm not really sure what you mean by pipe here?

Here was my thought for why we're okay regarding garbage collection.
```
Scan::Runner has an instance of TestCommandGenerator
TestCommandGenerator has an instance of XCPrettyReporterOptionsGenerator
XCPrettyReporterOptionsGenerator has an instance of Tempfile
```

Comment (keatongreve) [inline scan/lib/scan/xcpretty_reporter_options_generator.rb]: I haven't been able to reproduce the file being deleted via garbage collection, if you have any suggestions on how to test that, that would really help.

File: scan/lib/scan/runner.rb (hunk 2 above)
Comment (keatongreve) [inline scan/lib/scan/runner.rb]: Also regarding point 2, https://github.com/fastlane/fastlane/issues/9285 points out that when using `output_style: raw`, we return early before appending the `--report --output` parts (intentionally). [source](https://github.com/fastlane/fastlane/blob/2.35.0/scan/lib/scan/test_command_generator.rb#L81). This means that when using `output_style: raw`, we have no choice to use the pre 2.34.0 method of generating a test results table using `cat` instead of my optimization.

Comment (lacostej) [inline scan/lib/scan/runner.rb]: 1. yes. For now :)
2. for troubleshooting GC, we could try adding extra finalizers `ObjectSpace.define_finalizer(a, proc {|id| puts "Finalizer one on #{id}" })`
3. alternatively we could let the Runner create the temp file and pass it down to the call stack (or pass an object whose responsibility is to allocate the Tempfile). But the lifecyle of that object would be explicit in the run function for example. And no need to make all those other changes.

File: scan/lib/scan/xcpretty_reporter_options_generator.rb (hunk 3 above)
Comment (lacostej) [inline scan/lib/scan/xcpretty_reporter_options_generator.rb]: maybe using finalizers? see comment in `Runner`

Comment (lacostej) [inline scan/lib/scan/xcpretty_reporter_options_generator.rb]: I find it very convoluted to have to keep references all the way because we have to track a resource that is allocated down the call stack. I prefer when resources lifecycle is more explicit.

File: scan/lib/scan/runner.rb (hunk 2 above)
Comment (lacostej) [inline scan/lib/scan/runner.rb]: good catch of the `output_style: raw`

**Comment by KrauseFx** [comment]
Awesome, thanks @keatongreve 👍
