### PR TITLE
[sigh] fix download_all to also use App Store Connect API Key

### LINKED ISSUE #17357: api_key_path doesn't work with sigh download_all
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When running the download_all command for sigh the api_key_path parameter appears to be ignored. It will prompt me for my Apple ID or use the one referenced in my Appfile. I would expect it to use the api_key to carry out the command.

On a side note, it would be convenient if there was a parameter for the `sigh` action or even another action to do download_all without having to run it using the `sh` action.

##### Command executed
`bundle exec fastlane sigh download_all --api_key_path /Path/To/My/Key.json`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>MOBILE025:btMobileApp ryan.zulkoski$ bundle exec fastlane sigh download_all --api_key_path /Users/ryan.zulkoski/Downloads/XXXXXXXXXX.json
[✔] 🚀 
[16:15:47]: To not be asked about this value, you can specify it using 'username'
[16:15:47]: Your Apple ID Username: </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.7                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.24.3 (Apple Git-128)          |
| Installation Source         | ~/.rbenv/versions/2.6.3/bin/fastlane        |
| Host                        | Mac OS X 10.15.7 (19H2)                     |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.3/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.0.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.162.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.2.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| slack-notifier                            | 2.3.2        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| terminal-notifier                         | 2.0.0        |
| terminal-table                            | 1.8.0        |
| plist                                     | 3.5.0        |
| CFPropertyList                            | 3.0.2        |
| addressable                               | 2.7.0        |
| multipart-post                            | 2.0.0        |
| word_wrap                                 | 1.0.0        |
| babosa                                    | 1.0.3        |
| colored                                   | 1.2          |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| excon                                     | 0.76.0       |
| faraday                                   | 1.0.1        |
| faraday_middleware                        | 1.0.0        |
| gh_inspector                              | 1.1.3        |
| rubyzip                                   | 2.3.0        |
| security                                  | 0.1.3        |
| xcpretty-travis-formatter                 | 1.0.0        |
| bundler                                   | 2.1.4        |
| uber                                      | 0.1.0        |
| declarative-option                        | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| mini_mime                                 | 1.0.2        |
| memoist                                   | 0.16.2       |
| signet                                    | 0.14.0       |
| googleauth                                | 0.13.1       |
| httpclient                                | 2.8.3        |
| google-api-client                         | 0.38.0       |
| nanaimo                                   | 0.3.0        |
| colored2                                  | 3.1.2        |
| claide                                    | 1.0.3        |
| atomos                                    | 0.1.3        |
| xcodeproj                                 | 1.18.0       |
| unicode-display_width                     | 1.7.0        |
| public_suffix                             | 4.0.6        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| unf_ext                                   | 0.0.7.7      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.7        |
| fastimage                                 | 2.2.0        |
| json                                      | 2.3.1        |
| mini_magick                               | 4.10.1       |
| dotenv                                    | 2.7.6        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.8        |
| jwt                                       | 2.2.2        |
| declarative                               | 0.0.20       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.1        |
| rake                                      | 13.0.1       |
| digest-crc                                | 0.6.1        |
| google-cloud-errors                       | 1.0.1        |
| google-cloud-env                          | 1.3.3        |
| google-cloud-core                         | 1.5.0        |
| google-cloud-storage                      | 1.29.0       |
| emoji_regex                               | 3.0.0        |
| aws-eventstream                           | 1.1.0        |
| aws-sigv4                                 | 1.2.2        |
| aws-partitions                            | 1.379.0      |
| jmespath                                  | 1.4.0        |
| aws-sdk-core                              | 3.109.0      |
| aws-sdk-kms                               | 1.39.0       |
| aws-sdk-s3                                | 1.82.0       |
| forwardable                               | 1.2.0        |
| logger                                    | 1.3.0        |
| stringio                                  | 0.0.2        |
| ipaddr                                    | 1.2.2        |
| openssl                                   | 2.1.2        |
| ostruct                                   | 0.1.0        |
| strscan                                   | 1.0.0        |
| date                                      | 2.0.0        |
| fileutils                                 | 1.1.0        |
| etc                                       | 1.0.1        |
| io-console                                | 0.4.7        |
| zlib                                      | 1.0.0        |
| rexml                                     | 3.1.9        |
| psych                                     | 3.1.0        |
| mutex_m                                   | 0.1.0        |
| webrick                                   | 1.4.2        |
| fastlane-plugin-firebase_app_distribution | 0.2.3        |
</details>

*generated on:* **2020-10-01**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #17357

### Description
Forgot to add api key auth into sigh’s download_all 🤷‍♂️

### CODE REVIEW

File: sigh/lib/sigh/download_all.rb [hunk 1]
```diff
@@ -9,10 +9,16 @@ module Sigh
   class DownloadAll
     # Download all valid provisioning profiles
     def download_all(download_xcode_profiles: false)
-      UI.message("Starting login with user '#{Sigh.config[:username]}'")
-      Spaceship.login(Sigh.config[:username], nil)
-      Spaceship.select_team
-      UI.message("Successfully logged in")
+      if (token = api_token)
```
Comment (rogerluan) [inline sigh/lib/sigh/download_all.rb:12]: Is this the equivalent to `if let variable = variable` in Swift? :epicwin: this is awesome haha

**Review by rogerluan — APPROVED** [review]
💯

File: sigh/lib/sigh/download_all.rb (hunk 1 above)
Comment (joshdholtz) [reply sigh/lib/sigh/download_all.rb:12]: @rogerluan Essentially!  I don’t like using it a lot but it works well here 😇
