### PR TITLE
[match] fix change password to add files and fix breaking change on cert import

### LINKED ISSUE #13963: Errors with fastlane match change_password
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Trying to change the password of our match git repo as described here https://docs.fastlane.tools/actions/match/:

```fastlane match change_password```

I am guided through setting a new password and confirming it, and then entering the url of the git repo. However, it fails to successfully push the changes to the git repo.

I see the following error:

>  Neither files_to_commit nor files_to_delete were provided to the save_changes! method call

Googling that result hasn't turned up anything.

Note that I have the MATCH_PASSWORD environment variable set to the old password. If I remove the environment variable, I get a "bad decrypt. couldn't decrypt the repo" error. I've also removed anything match related from my keychain.

I have also tried running this from both inside and outside a directory that has a fastlane enabled project it in. Same result.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>fastlane match change_password
[✔] 🚀 
[12:26:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:26:26]: New passphrase for Git Repo: ************
[12:26:31]: Type passphrase again: ************
[12:26:32]: To not be asked about this value, you can specify it using 'git_url'
[12:26:32]: URL to the git repo containing all the certificates: git@bitbucket.org:XXXXXX/XXXXXXXXXXX.git
[12:26:35]: Cloning remote git repo...
[12:26:35]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:26:40]: 🔓  Successfully decrypted certificates repo
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:26:40]: 🔒  Successfully encrypted certificates repo

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.5.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.20.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.3_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.112.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.16.2       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| CFPropertyList            | 3.0.0        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.7.0        |
| unicode-display_width     | 1.4.0        |
| plist                     | 3.4.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| json                      | 2.1.0        |
| multi_json                | 1.13.1       |
| dotenv                    | 2.5.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| os                        | 1.0.0        |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| openssl                   | 2.1.2        |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.9.1        |
| ipaddr                    | 1.2.0        |
| psych                     | 3.0.2        |
</details>

*generated on:* **2018-12-20**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #13963
Fixes #13967 (an unintentional breaking change) 

## Fix #13963: for change password
`fastlane match change_password` got broken where no `files_to_commit` where being passed into `storage.save_changes!`. Added a fix where `encryption.encrypt_files` and `encryption.decrypt_files` returns all the files that were encrypted/decrypted so that file list could be used by implementations like `change_password` to use when calling `storage.save_changes!`

## Fix #13967: for breaking change when importing a cert
When working on this change I discovered a recent breaking change that was injected in #13967. The fix for this PR was 💯 (as a password **is** request to to set the partition list to prevent the UI permission modal from being popped up when using a newly imported cert for signing)...

But if no keychain password was a given a `UI.user_error!` was being thrown. A lot of users (including myself) rely on the login keychain when importing these and rely on not passing in a password (as we are already logged in). This `UI.user_error!` was preventing all of my existing implementations from working.

Even though this `UI.user_error!` was technically the correct way to implement this, this could cause havoc when users would upgrade to this newest version (as if code signing isn't already a nightmare 😝 ). So instead of erroring out this whole process, I added a change that would use `UI.error` to inform the user when exactly was failing, why, and how to fix it. This could eventually be replaced with a more specific doc link that explains this but this _should_ do for now 🤔 

### Example Output
```sh
[14:13:01]: Installing certificate...
[14:13:02]:
[14:13:02]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/josh/Library/Keychains/login.keychain-db`
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
[14:13:02]:
[14:13:02]: Please look at the following docs to see how to set a keychain password:
[14:13:02]:  - https://docs.fastlane.tools/actions/sync_code_signing
[14:13:02]:  - https://docs.fastlane.tools/actions/get_certificates
```

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/keychain_importer.rb [hunk 1]
```diff
@@ -8,28 +8,37 @@ def self.import_file(path, keychain_path, keychain_password: "", certificate_pas
...
+      UI.important("🐌 Configuring imported item for code signing (this could take a while if you have a lot of items in your keychain)...")
       if Helper.backticks('security -h | grep set-key-partition-list', print: false).length > 0
         command = "security set-key-partition-list"
         command << " -S apple-tool:,apple:"
         command << " -k #{keychain_password.to_s.shellescape}"
         command << " #{keychain_path.shellescape}"
 
         Open3.popen3(command) do |stdin, stdout, stderr, thrd|
+          # Need to read stdout even if not showing using UI.command_output
+          # The execution would sometimes hang for large keychain item list if the output of security `set-key-partition-list` not read
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/keychain_importer.rb]: grammar

File: fastlane_core/lib/fastlane_core/keychain_importer.rb [hunk 2]
```diff
@@ -8,28 +8,37 @@ def self.import_file(path, keychain_path, keychain_password: "", certificate_pas
...
+
           if output
             UI.command(command)
-            UI.command_output(stdout.read)
+            UI.command_output(command_output)
           end
 
           unless thrd.value.success?
-            UI.user_error!("Could not configure key to bypass permission popup:\n#{stderr.read}")
+            UI.error("Could not configure imported keychain item (certificate) to prevent UI permission popup when signing:\n#{stderr.read.to_s.strip}")
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/keychain_importer.rb]: Empty line here first so that it gets offset from the previous output a bit?

**Review by janpio — APPROVED** [review]
👍

**Review by snatchev — COMMENTED** [review]
Looks good to me!

File: fastlane_core/lib/fastlane_core/keychain_importer.rb [hunk 3]
```diff
@@ -19,17 +19,22 @@ def self.import_file(path, keychain_path, keychain_password: "", certificate_pas
       if Helper.backticks('security -h | grep set-key-partition-list', print: false).length > 0
         command = "security set-key-partition-list"
         command << " -S apple-tool:,apple:"
+        command << " -l 'Imported Private Key'"
```
Comment (nakhbari) [inline fastlane_core/lib/fastlane_core/keychain_importer.rb]: could you explain this additional param?

**Review by nakhbari — APPROVED** [review]
LGTM + question for curiosity

File: fastlane_core/lib/fastlane_core/keychain_importer.rb (hunk 3 above)
Comment (snatchev) [reply fastlane_core/lib/fastlane_core/keychain_importer.rb]: Before the `set-key-partition-list` operation would apply to all keys in the keychain, potentially taking lots of time (see https://github.com/fastlane/fastlane/issues/12291#issuecomment-383595648) if the user has lots of keys.

The `-l` parameter will filter the operation to keys that match the supplied "label". As far as I know, that label "Imported Private Key" is applied by the previous step in the import.

**Comment by koxon** [comment]
This fix doens't resolve the issue
> [18:30:26]: ▸ [!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call

I looped through many Teams nuking all their certs. One over two nuke throws this error.
However, it looks like the changes are taken correctly.

I correctly have different git branch for each of my team.

Looks like it's not blocking but I wanted to report it

**Comment by janpio** [comment]
Please create a new issue that links to this PR, otherwise this will get lost. Thanks!
