### PR TITLE
frameit: fix show_complete_frame=false, improve speed

### LINKED ISSUE #8300: Frameit: show_complete_frame = false not respected since version 2.15.0
On frameit in fastlane 2.14.2, screenshots are framed correctly with part of the device frame shown.

On frameit in fastlane 2.15.0 and up, screenshots are framed with entire frame, despite option show_complete_frame = false. The frame overlaps the title.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.8.1                           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.15.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-19**
</details>

### PR DESCRIPTION
**Pull request by futuretap**
fixes #8300;
now the screenshot resizing completely happens in complex_framing and the screenshot is only resized once (instead of 3 times worst case), resulting in a 20% speed improvement (for show_complete_frame = true) and potentially a quality improvement because resizing multiple times degrades quality;
added parameter validation for `show_complete_frame.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

File: frameit/lib/frameit/editor.rb [hunk 1]
```diff
@@ -117,9 +117,19 @@ def complex_framing
...
-        if @image.height > frame_height
-          @image.resize "x#{frame_height.to_i}"
+
+        if fetch_config['show_complete_frame']
+          # calculate the final size of the screenshot to resize in one go
+          # it may be limited either by the width or height of the frame
+          image_aspect_ratio = @image.width.to_f / @image.height.to_f
+          image_width = [frame_width, @image.width].min
+          image_height = [frame_height, image_width / image_aspect_ratio].min
+          image_width = image_height * image_aspect_ratio
```
Comment (mfurtak) [inline frameit/lib/frameit/editor.rb]: I don't immediately get it: why is the height calculated from the width, and the width calculated from the height, here?

Comment (futuretap) [inline frameit/lib/frameit/editor.rb]: We want to calculate the final frame for a given outer/limiting frame and an aspect ratio. Now we have two cases:
1) The `frame_width` is the limiting factor. Then `image_width / image_aspect_ratio` is < `frame_height`. In this case, line 127 is not needed.
2) The `frame_height` is the limiting factor. Then `image_height` == `frame_height` and `image_width / image_aspect_ratio` is larger than that. In this case, `image_width` must be smaller than `frame_width` by calculating it back from the `image_height` and the aspect ratio.

Does that make sense?

Comment (mfurtak) [inline frameit/lib/frameit/editor.rb]:
```ruby
# Use the scaling factor from whichever dimension needs the least scaling
scale = [frame_width.to_f / @image.width.to_f, frame_height.to_f / @image.height.to_f].min
new_width = @image.width * scale
new_height = @image.height * scale
```

Something like the above is a bit easier for me to follow. Would that work here?

**Review by mfurtak — APPROVED** [review]

**Comment by mfurtak** [comment]
Let's get this fix out 👍
