### PR TITLE
[snapshot] add additional ipad classifiers.

### LINKED ISSUE #6822: Snapshot html summary with multiple iPads broken
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using snapshot for multiple iPads, all of those iPads are summed in one "iPad" in the summary html. Not like the iPhones that are grouped by device, the iPad screenshots sum up all in the same row.

##### Complete output when running fastlane, including the stack trace and command used
All runs fine here, the generated HTML is broken as you see below. All the iPads are grouped within the same `<tr>`

<details><summary>GENERATED HTML</summary>

```
<!DOCTYPE html>
<html>
  <head>
    <title>fastlane/snapshot</title>
    <meta charset="UTF-8">
    <style type="text/css">
      * {
        font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        font-weight: 300;
      }
      .language {

      }
      .deviceName {
        display: block;
        font-size: 30px;
        padding-bottom: 24px;
        padding-top: 45px;
      }
      .screenshot {
        cursor: pointer;
        border: 1px #EEE solid;
        z-index: 0;
      }
      th {
        text-align: left;
      }
      td {
        text-align: center;
        min-width: 200px;
      }
      #overlay {
        position:fixed;
        top:0;
        left:0;
        background:rgba(0,0,0,0.8);
        z-index:5;
        width:100%;
        height:100%;
        display:none;
        cursor: zoom-out;
        text-align: center;
      }
      #imageDisplay {
        height: auto;
        width: auto;
        z-index: 10;
        cursor: pointer;
      }
      #imageInfo {
        background: none repeat scroll 0 0 rgba(0, 0, 0, 0.2);
        border-radius: 5px;
        color: white;
        margin: 20px;
        padding: 10px;
        position: absolute;
        right: 0;
        top: 0;
        width: 250px;
        z-index: -1;
      }
      #imageInfo:hover {
        z-index: 20;
      }
    </style>
  </head>
  <body>
    
    
    


    
      <h1 class="language">en-US</h1>
      <hr>
      <table>
        
          <tr>
            <th colspan="42">
              <span class="deviceName">iPad</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="1" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="2" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="3" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="4" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="5" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="6" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="7" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="8" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="9" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="10" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="11" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="12" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="13" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPad2-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPad2-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="14" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="15" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="16" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="17" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="18" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="19" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="20" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="21" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="22" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="23" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="24" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="25" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="26" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="27" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadAir2-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadAir2-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="28" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="29" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="30" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="31" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="32" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="33" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="34" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="35" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="36" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="37" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="38" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="39" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="40" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="41" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPadPro(12.9-inch)-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPadPro(12.9-inch)-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPad"
                data-counter="42" />
                </a>
              </td>
            
          </tr>
        
          <tr>
            <th colspan="14">
              <span class="deviceName">iPhone5 (4-Inch)</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="43" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="44" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="45" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="46" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="47" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="48" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="49" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="50" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="51" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="52" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="53" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="54" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="55" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone5-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone5-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone5 (4-Inch)"
                data-counter="56" />
                </a>
              </td>
            
          </tr>
        
          <tr>
            <th colspan="14">
              <span class="deviceName">iPhone6 (4.7-Inch)</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="57" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="58" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="59" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="60" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="61" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="62" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="63" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="64" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="65" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="66" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="67" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="68" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="69" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6 (4.7-Inch)"
                data-counter="70" />
                </a>
              </td>
            
          </tr>
        
          <tr>
            <th colspan="14">
              <span class="deviceName">iPhone6Plus (5.5-Inch)</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="71" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="72" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="73" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="74" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="75" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="76" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="77" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="78" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="79" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="80" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="81" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="82" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="83" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone6Plus-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone6Plus-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone6Plus (5.5-Inch)"
                data-counter="84" />
                </a>
              </td>
            
          </tr>
        
          <tr>
            <th colspan="14">
              <span class="deviceName">iPhone7 (4.7-Inch)</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="85" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="86" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="87" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="88" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="89" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="90" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="91" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="92" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="93" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="94" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="95" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="96" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="97" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7 (4.7-Inch)"
                data-counter="98" />
                </a>
              </td>
            
          </tr>
        
          <tr>
            <th colspan="14">
              <span class="deviceName">iPhone7Plus (5.5-Inch)</span>
            </th>
          </tr>
          <tr>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-00_00_Splash.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-00_00_Splash.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="99" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-01_00_SETTINGS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-01_00_SETTINGS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="100" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_00_KE_Open.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_00_KE_Open.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="101" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_CRASH.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_CRASH.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="102" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_HIHAT.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_HIHAT.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="103" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_KICK.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_KICK.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="104" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_RIDE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_RIDE.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="105" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_SNARE.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_SNARE.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="106" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_TOM1.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_TOM1.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="107" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_TOM2.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_TOM2.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="108" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-02_01_KE_TOM3.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-02_01_KE_TOM3.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="109" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-03_00_KS_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-03_00_KS_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="110" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-04_00_PA_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-04_00_PA_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="111" />
                </a>
              </td>
            
              
              <td>
                
                
                <a href="./en-US/iPhone7Plus-05_00_TT_OPEN.png" target="_blank" class="screenshotLink">
                  <img class="screenshot"
                         src="./en-US/iPhone7Plus-05_00_TT_OPEN.png"
                       style="width: 100%;"
                         alt="en-US iPhone7Plus (5.5-Inch)"
                data-counter="112" />
                </a>
              </td>
            
          </tr>
        
      </table>
    
      <div id="overlay">
        <img id="imageDisplay" src="" alt="" />
        <div id="imageInfo"></div>
      </div>
      <script type="text/javascript">
        var overlay        = document.getElementById('overlay');
        var imageDisplay   = document.getElementById('imageDisplay');
        var imageInfo      = document.getElementById('imageInfo');
        var screenshotLink = document.getElementsByClassName('screenshotLink');

        function doClick(el) {
          if (document.createEvent) {
            var evObj = document.createEvent('MouseEvents', true);
            evObj.initMouseEvent("click", false, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
            el.dispatchEvent(evObj);
          } else if (document.createEventObject) { //IE
            var evObj = document.createEventObject();
            el.fireEvent('onclick', evObj);
          }
        }

        for (index = 0; index < screenshotLink.length; ++index) {
          screenshotLink[index].addEventListener('click', function(e) {
            e.preventDefault();
            
            var img = e.target;
            if (e.target.tagName == 'A') {
              img = e.target.children[0];
            }
            
            // beautify
            var tmpImg = new Image();
            tmpImg.src = img.src;
            imageDisplay.style.height     = 'auto';
            imageDisplay.style.width     = 'auto';
            if (window.innerHeight < tmpImg.height) {
              imageDisplay.style.height = document.documentElement.clientHeight+'px';
            } else if (window.innerWidth < tmpImg.width) {
              imageDisplay.style.width = document.documentElement.clientWidth;+'px';
            } else {
              imageDisplay.style.paddingTop = parseInt((window.innerHeight - tmpImg.height) / 2)+'px';
            }

            imageDisplay.src             = img.src;
            imageDisplay.alt             = img.alt;
            imageDisplay.dataset.counter = img.dataset.counter;
            
            imageInfo.innerHTML          = '<h3>'+img.alt+'</h3>';
            imageInfo.innerHTML         += decodeURI(img.src.split("/").pop());
            imageInfo.innerHTML         += '<br />'+tmpImg.height+'&times;'+tmpImg.width+'px';
                    
            overlay.style.display        = "block";
          });
        }
        
        imageDisplay.addEventListener('click', function(e) {
          e.stopPropagation(); // !
          
          overlay.style.display = "none";
          
          img_counter = parseInt(e.target.dataset.counter) + 1;
          try {
            link = document.body.querySelector('img[data-counter="'+img_counter+'"]').parentNode;
          } catch (e) {
            try {
              link = document.body.querySelector('img[data-counter="0"]').parentNode;
            } catch (e) {
              return false;
            }
          }
          doClick(link);
        });

        overlay.addEventListener('click', function(e) {
          overlay.style.display = "none";
        })
        
      function keyPressed(e) {
        e = e || window.event;
        var charCode = e.keyCode || e.which;
        switch(charCode) {
          case 27: // Esc
            overlay.style.display = "none";
            break;
          case 34: // right-arrow, Page Down, keypad right, ...
          case 39:
          case 54:
          case 102:
            e.preventDefault();
            doClick(imageDisplay);
            break;
          case 33: // left-arrow, Page Up, keypad right, ...
          case 37:
          case 52:
          case 100:
            e.preventDefault();
            document.getElementById('imageDisplay').dataset.counter -= 2; // hacky
            doClick(imageDisplay);
            break;
         }
      };
      document.body.addEventListener('keydown', keyPressed);
      </script>
  </body>
</html>
```
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.6                                          |
| Ruby                | 2.3.0                                            |
| Bundler?            | false                                            |
| Xcode Path          | /Applications/Xcode 8.0.app/Contents/Developer/  |
| Xcode Version       | 8.0                                              |
| Git                 | git version 2.8.4 (Apple Git-73)                 |
| Installation Source | /Users/mlostek/.rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                       |
| Ruby Lib Dir        | /Users/mlostek/.rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                       |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :ios do

   # SCREENSHOTS
  desc "Make and upload screenshots"
    lane :screenshots do
      version = get_version_number()
      sh "rm -rf screenshots"
      snapshot(output_directory: "./fastlane/screenshots/#{version}")
  end
       

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXX" # The bundle identifier of your app
apple_id "XXX" # Your Apple email address

team_id "XXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.1  | 🚫 Update availaible |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.2   |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| io-console                | 0.4.6   |
| highline                  | 1.7.8   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| multipart-post            | 2.0.0   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.12.1  |
| colored                   | 1.2     |
| commander                 | 4.4.0   |
| babosa                    | 1.0.2   |
| rubyzip                   | 1.1.7   |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.53.0  |
| multi_xml                 | 0.5.5   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7   |
| excon                     | 0.54.0  |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.1.1   |
| xcodeproj                 | 1.4.0   |
</details>

*generated on:* **2016-11-01**
</details>

### PR DESCRIPTION
**Pull request by hjanuschka**
fixes: https://github.com/fastlane/fastlane/issues/6822

proof:
bildschirmfoto 2016-12-18 um 23 00 36

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
Looks great, thanks!!  🚀

File: snapshot/lib/snapshot/reports_generator.rb [hunk 1]
```diff
@@ -53,6 +53,10 @@ def available_devices
         'iPhone6' => "iPhone6 (4.7-Inch)",
         'iPhone5' => "iPhone5 (4-Inch)",
         'iPhone4' => "iPhone4 (3.5-Inch)",
+        'iPad2' => "iPad2",
+        'iPadAir2' => 'iPad Air 2',
+        'iPadPro(12.9-inch)' => 'iPad Air Pro (12.9 inch)',
```
Comment (JustinJiaDev) [inline snapshot/lib/snapshot/reports_generator.rb]: I'm just wondering, what is iPad Air Pro?

Comment (hjanuschka) [inline snapshot/lib/snapshot/reports_generator.rb]: @JustinJiaDev good point, i think it was a copy&paste error 😢
