### PR TITLE
[snapshot] Delete simulators based on versions

### LINKED ISSUE #10174: [snapshot] reset_simulators: Can't reset 11.0 sims using Xcode 9 environment
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`fastlane snapshot reset_simulators --ios 11.0 --verbose` and get 
```
INFO [2017-08-29 11:52:07.32]: $ xcrun simctl list devices
INFO [2017-08-29 11:52:07.40]: ▸ == Devices ==
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 7.1 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 8.1 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 8.4 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 9.0 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 9.3 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 10.3 --
INFO [2017-08-29 11:52:07.40]: ▸ -- iOS 11.0 --
INFO [2017-08-29 11:52:07.40]: ▸ -- tvOS 11.0 --
INFO [2017-08-29 11:52:07.40]: ▸ -- watchOS 4.0 --
INFO [2017-08-29 11:52:07.55]: $ xcrun simctl list devices
INFO [2017-08-29 11:52:07.61]: ▸ == Devices ==
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 7.1 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 8.1 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 8.4 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 9.0 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 9.3 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 10.3 --
INFO [2017-08-29 11:52:07.61]: ▸ -- iOS 11.0 --
INFO [2017-08-29 11:52:07.61]: ▸ -- tvOS 11.0 --
INFO [2017-08-29 11:52:07.61]: ▸ -- watchOS 4.0 --
```
Simulator got deleted, but not create.

`xcode-select -p` and got
`/Applications/Xcode-beta.app/Contents/Developer`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.3.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.8.1                                |
| Installation Source         | ~/.rbenv/versions/2.3.4/bin/fastlane             |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.4/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.54.2"

default_platform :ios

platform :ios do
  before_all do

    xcode_select "/Applications/Xcode-9.0.app"
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods unless Helper.is_ci? # circle ci already run pod install, and in circleci currently have problem with this command

    if Helper.is_ci?
      increment_build_number(build_number: ENV['CIRCLE_BUILD_NUM'])
    end
    
    ENV['KEYCHAIN_NAME'] = "TempKeychain.keychain"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "staging for uat"
  lane :staging do
    import_certificates
    sigh

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "Rocky Staging")
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    import_certificates
    sigh(adhoc: true)

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    # # Fabric generated this lane for deployment to Crashlytics Beta
    # # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Rocky Staging', export_method: 'ad-hoc')

    crashlytics(
      crashlytics_path: "./Pods/Crashlytics",
      api_token: ENV["FABRIC_API_TOKEN"],
      build_secret: ENV["FABRIC_BUILD_SECRET"],
      notifications: true,
      groups: 'testers'
    )
  end

  desc "integration for internal test"
  lane :integration do
    import_certificates
    sigh

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "Rocky Integration")
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "production"
  lane :production do      
    import_production_certificates
    sigh

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "Rocky Production")
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)  
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  def import_certificates
    return unless Helper.is_ci? # As in my local machine I don't need to import the certificates, only run if it's in the CI

    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/distribution.p12",
      certificate_password: ENV['CERT_PASSWORD'],
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/ios_distribution.cer",
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

    # Sierra changes
    Helper.backticks("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_PASSWORD"]} #{ENV['KEYCHAIN_NAME']}")    
  end

  def import_production_certificates
    return unless Helper.is_ci? # As in my local machine I don't need to import the certificates, only run if it's in the CI

    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/production_distribution.p12",
      certificate_password: ENV['PRODUCTION_CERT_PASSWORD'],
      keychain_name: ENV["EYCHAIN_NAME"]
    )

    import_certificate(
      certificate_path: "fastlane/certificates/production_distribution.cer",
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

    # Sierra changes
    Helper.backticks("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_PASSWORD"]} #{ENV['KEYCHAIN_NAME']}")
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "com.oozou.rocky" # The bundle identifier of your app
# apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name "Oozou Limited"
team_id "BA36Y82DMA"

# To select a team for iTunes Connect use
itc_team_name "Oozou Limited"
itc_team_id "16134"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

for_lane :staging do
  app_identifier "com.oozou.rocky.staging"
end

for_lane :beta do
  app_identifier "com.oozou.rocky"
end

for_lane :production do
  team_name "LINE COMPANY (THAILAND) COMPANY LIMITED"
  team_id "W5H4R7GVBZ"

  itc_team_name "LINE COMPANY (THAILAND) COMPANY LIMITED"
  itc_team_id "117742454"

  app_identifier "com.linemobile.th"
end

for_lane :integration do
  app_identifier "com.oozou.rocky.integration"
end```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| faraday_middleware        | 0.12.2       |
| bundler                   | 1.15.3       |
| unicode-display_width     | 1.3.0        |
</details>


*generated on:* **2017-08-29**
</details>

### PR DESCRIPTION
**Pull request by jetersen**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Would be better to have the option to delete on specific version.
Also fixes #10174

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/device_manager.rb [hunk 1]
```diff
@@ -180,6 +180,13 @@ def reset
         `xcrun simctl erase #{self.udid}`
         return
       end
+
+      def delete
+        UI.message("Deleting #{self}")
```
Comment (casz) [inline fastlane_core/lib/fastlane_core/device_manager.rb]: This is not printing, do not know why 😕

**Comment by ohayon** [comment]
Hey @casz this looks awesome, just one little question: have you tested this against Xcode 8 and 9? We are going to have to make some changes to the way Xcode 9 does simulator management because of some other issues, so I'm curious if this implementation is working in an Xcode 9 environment? Thanks!

File: fastlane_core/lib/fastlane_core/device_manager.rb (hunk 1 above)
Comment (ohayon) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: Can you try `UI.important("Deleting #{self}")`?

**Comment by casz** [comment]
@ohayon no I did not because of #10174 but I would be happy to try and fix it.

Should I go the JSON route or try and fix the regex is my question.

**Comment by casz** [comment]
Found a good regex that works for both xcode 8 and 9.

`(.*)\s\(\d.*(com\.apple[^)\s]*)`

File: fastlane_core/lib/fastlane_core/device_manager.rb (hunk 1 above)
Comment (casz) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: I was not unpacking the ios_versions... silly me 👍

**Comment by casz** [comment]
This fixes #10174

**Comment by casz** [comment]
@ohayon 🚢 it?

> We are going to have to make some changes to the way Xcode 9 does simulator management because of some other issues

Or should we look at the other issues you mentioned?

**Comment by casz** [comment]
Oh I forgot to think about tvOS and watchOS, let me see :)

File: snapshot/lib/snapshot/reset_simulators.rb [hunk 2]
```diff
@@ -18,9 +18,17 @@ def self.clear_everything!(ios_versions, force = false)
       if ios_versions
         ios_versions.each do |version|
           FastlaneCore::Simulator.delete_all_by_version(os_version: version)
+          FastlaneCore::SimulatorTV.delete_all_by_version(os_version: version)
+        end
+        if version.include?('11')
```
Comment (casz) [inline snapshot/lib/snapshot/reset_simulators.rb]: Could not think of a better way to handle it, so I left it. In hope of suggestion!

Comment (casz) [reply snapshot/lib/snapshot/reset_simulators.rb]: Also tvOS does not always match ios version.
Perhaps I should just create more options on the reset_simulators command?

Comment (casz) [reply snapshot/lib/snapshot/reset_simulators.rb]: Well, I think it is unwarrented since again Simulator handles this better.
Delete All doesn't touch the unavailable. While the code prior to my changes did.

**Comment by casz** [comment]
Perhaps we should leave an option open to delete unavailable simulators?

**Comment by casz** [comment]
@ohayon Anyone think I can help with?

**Comment by casz** [comment]
@ohayon this is really needed with xcode 9 GM seed. Should I seperate the regex fix? for a quick hotfix?

**Comment by casz** [comment]
How I locally fixed our simulators with this.
```git clone https://github.com/casz/fastlane.git
                    cd fastlane
                    git checkout fix_delete_sims_on_version
                    bundle install
                    DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer/ bundle exec fastlane snapshot reset_simulators -i 10.3 --force
                    DEVELOPER_DIR=/Applications/Xcode-9.app/Contents/Developer/ bundle exec fastlane snapshot reset_simulators -i 11.0 --force```

File: fastlane_core/lib/fastlane_core/device_manager.rb [hunk 3]
```diff
@@ -180,6 +180,13 @@ def reset
...
+        `xcrun simctl shutdown #{self.udid}` if self.state == "Booted"
```
Comment (ohayon) [inline fastlane_core/lib/fastlane_core/device_manager.rb]: Is this necessary to check if the state is `Booted`? Can we just call shutdown regardless of state just in case something changes with states, we wont break of that string changes?

Comment (casz) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: I agree :)

File: fastlane_core/lib/fastlane_core/device_manager.rb [hunk 4]
```diff
@@ -180,6 +180,12 @@ def reset
         `xcrun simctl erase #{self.udid}`
         return
       end
+
+      def delete
+        UI.message("Deleting #{self}")
+        `xcrun simctl delete #{self.udid}`
```
Comment (ohayon) [inline fastlane_core/lib/fastlane_core/device_manager.rb]: Sorry for the back and forth here @casz! But do we still need to make sure it is shut down? In my last comment I just meant that I dont think we needed the check for if it's booted. Sorry if I wasnt clear there. Does that make sense? Have you tested this while simulators are running?

Comment (casz) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: I tried with simulators on, and they do get killed, but Yes, again it makes sense to actually still call shutdown properly. I simply misunderstood you 👍

Comment (casz) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: `An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164):
Unable to shutdown device in current state: Shutdown`

When a machine is already shutdown

Comment (casz) [reply fastlane_core/lib/fastlane_core/device_manager.rb]: A nice shutdown is better, if you just delete it. and have xcode running it gets unhappy with error 👍

File: fastlane_core/lib/fastlane_core/device_manager.rb [hunk 5]
```diff
@@ -183,7 +183,7 @@ def reset
 
       def delete
         UI.message("Deleting #{self}")
-        `xcrun simctl shutdown #{self.udid}` if self.state == "Booted"
+        `xcrun simctl shutdown #{self.udid}` unless self.state == "Shutdown"
```
Comment (casz) [inline fastlane_core/lib/fastlane_core/device_manager.rb]: This way we won't fail if state 'Shutdown' is changed

**Comment by casz** [comment]
Changed the statement to `unless state == 'Shutdown'` to avoid throwing too many errors when already shutdown.
`An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=164): Unable to shutdown device in current state: Shutdown`

**Comment by ohayon** [comment]
This is awesome, thanks @casz !! Just one more favor to ask you, is there any chance you would want to write a test or two for this new code so we can know when it is failing in the future?

**Comment by casz** [comment]
@ohayon I would love to 👍

 just for the runtimes types with static output files for xcode 8 and 9?

Doubt I'd be able to create a test for deleting.

**Comment by ohayon** [comment]
Yeah that would be great. I just took a look at the `reset_simulators_spec` and I think it would be great to be testing the new format that is being output and just so we have a reference for what is expected. 💯

File: snapshot/lib/snapshot/reset_simulators.rb [hunk 6]
```diff
@@ -80,6 +91,10 @@ def self.devices
       result.select { |parsed| parsed.length == 3 } # we don't care about those headers
     end
 
+    def self.runtimes
+      all_runtime_type = Helper.backticks('xcrun simctl list runtimes', print: FastlaneCore::Globals.verbose?).scan(/(.*)\s\(\d.*(com\.apple[^)\s]*)/)
```
Comment (casz) [inline snapshot/lib/snapshot/reset_simulators.rb]: Don't know if it should be it's own method but otherwise I couldn't see how I should get the test to work.

File: snapshot/lib/snapshot/reset_simulators.rb [hunk 7]
```diff
@@ -80,6 +91,10 @@ def self.devices
       result.select { |parsed| parsed.length == 3 } # we don't care about those headers
     end
 
+    def self.runtimes
+      Helper.backticks('xcrun simctl list runtimes', print: FastlaneCore::Globals.verbose?).scan(/(.*)\s\(\d.*(com\.apple[^)\s]*)/)
```
Comment (casz) [inline snapshot/lib/snapshot/reset_simulators.rb]: Don't know if it should be it's own method but otherwise I couldn't see how I should get the test to work.

**Comment by casz** [comment]
@ohayon Anything else?

File: snapshot/lib/snapshot/reset_simulators.rb [hunk 8]
```diff
@@ -26,7 +26,7 @@ def self.clear_everything!(ios_versions, force = false)
       FastlaneCore::SimulatorTV.delete_all
       FastlaneCore::SimulatorWatch.delete_all
 
-      all_runtime_type = `xcrun simctl list runtimes`.scan(/(.*)\s\(\d.*(com\.apple[^)\s]*)/)
+      all_runtime_type = runtimes()
```
Comment (ohayon) [inline snapshot/lib/snapshot/reset_simulators.rb]: I dont think we need the parens here.

**Review by ohayon — APPROVED** [review]
This looks great @casz! I think we can merge as is, and if you have any time to add some tests that take in the version and make sure that only those are being deleted that would be sweet too! Thanks for this and going through all the iterations!! 🚀  💯

**Comment by ohayon** [comment]
Hey @casz, i just noticed that it looks like if ios_versions are there, that we still go ahead and delete the watch and tvOS simulators, is that intended behavior? It feels like something we should only do in the `else` case there right?

**Comment by casz** [comment]
Problem is iOS version doesn't match up with watch or tv.

So I was left just deleting as previously.
Or adding new parameters for watch and TV.

There is also the case of wanting to delete all unavailable devices since that's what I wanted to protect against in the first place.

**Comment by casz** [comment]
At least for now it works for xcode 8 and xcode 9 simctl
If you want me to do a follow up PR, fixing the rest. I'd be happy to 👍

**Comment by casz** [comment]
At least for now it works for xcode 8 and xcode 9 simctl
@ohayon If you want me to do a follow up PR, fixing the rest. I'd be happy to 👍

**Comment by casz** [comment]
Sorry, I left it out.
The `else` case would require that you also have if else for recreating the watch devices and also watch+phone pair.

**Comment by ohayon** [comment]
Awesome. Thanks for all that info. I guess let's leave it for now and see how things play out. Thanks again for this change! 🚀
