### PR TITLE
Remove deprecated attributes from apps requests

### LINKED ISSUE #21125: Listing apps fails, due to the recent pricing update on App Store?
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I run the action `app_store_build_number`, it fails with an error response from Connect API: `The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.`

<details>
<summary><code>fastlane summary</code> and stack trace</summary>

```
+------+----------------------------------+-------------+
|                   fastlane summary                    |
+------+----------------------------------+-------------+
| Step | Action                           | Time (in s) |
+------+----------------------------------+-------------+
| 1    | Switch to get_apple_api_key lane | 0           |
| 2    | app_store_connect_api_key        | 0           |
| 💥   | app_store_build_number           | 0           |
+------+----------------------------------+-------------+

[14:47:58]: fastlane finished with errors
bundler: failed to load command: fastlane (/Users/distiller/project/vendor/bundle/ruby/3.0.0/bin/fastlane)
/Users/distiller/.rbenv/versions/3.0.5/bin/bundle: \e[31m[!] The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.\e[0m (Spaceship::UnexpectedResponse)
/Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:204:in `handle_response': The request cannot be fulfilled because of the state of another resource. - The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'. (Spaceship::UnexpectedResponse)
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/api_client.rb:113:in `get'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/testflight/testflight.rb:22:in `get_apps'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/3.0.0/forwardable.rb:238:in `get_apps'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:75:in `all'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/spaceship/lib/spaceship/connect_api/models/app.rb:81:in `find'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:53:in `get_build_info'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:23:in `get_build_version_and_number'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:12:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfiles/ReleaseFastfile.rb:96:in `block in parsing_binding'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/gems/fastlane-2.212.1/bin/fastlane:23:in `<top (required)>'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `load'
	from /Users/distiller/project/vendor/bundle/ruby/3.0.0/bin/fastlane:25:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:483:in `exec'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/cli.rb:25:in `start'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/exe/bundle:48:in `block in <top (required)>'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/distiller/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/bundler-2.3.13/exe/bundle:36:in `<top (required)>'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/bundle:23:in `load'
	from /Users/distiller/.rbenv/versions/3.0.5/bin/bundle:23:in `<main>'

Exited with code exit status 1
```

</details>

As far as I look over the stack trace, I suppose it's caused by the recent pricing change on App Store and the related Connect API update.
https://developer.apple.com/news/releases/?id=03092023b

The `prices` attribute included in `ESSENTIAL_INCLUDES`:
https://github.com/fastlane/fastlane/blob/e55138d9dc769654897cf95701accc698d8edb01/spaceship/lib/spaceship/connect_api/models/app.rb#L60-L63

... looks now marked as deprecated.
https://developer.apple.com/documentation/appstoreconnectapi/app/relationships

### Environment

```
gem "fastlane", "2.212.1"
```

<details><summary>✅ fastlane environment ✅</summary>

This is my local environment and it might be not so meaningful as the error above happened on my CI environment

### Stack

| Key                         | Value                                                                       |
| --------------------------- | --------------------------------------------------------------------------- |
| OS                          | 13.1                                                                        |
| Ruby                        | 3.0.3                                                                       |
| Bundler?                    | true                                                                        |
| Git                         | git version 2.39.2                                                          |
| Installation Source         | *hidden* |
| Host                        | macOS 13.1 (22C65)                                                          |
| Ruby Lib Dir                | ~/.rbenv/versions/3.0.3/lib                                                 |
| OpenSSL Version             | OpenSSL 1.1.1q  5 Jul 2022                                                  |
| Is contained                | false                                                                       |
| Is homebrew                 | false                                                                       |
| Is installed via Fabric.app | false                                                                       |
| Xcode Path                  | /Applications/Xcode-14.2.0.app/Contents/Developer/                          |
| Xcode Version               | 14.2                                                                        |
| Swift Version               | 5.7.2                                                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import "Fastfiles/HelperFastfile.rb"
import "Fastfiles/ReleaseFastfile.rb"
import "Fastfiles/SandboxFastfile.rb"
import "Fastfiles/AppDistributionFastfile.rb"
import "Fastfiles/LicenseFastfile.rb"

before_all do
  ENV['TZ'] = 'Asia/Tokyo'
  ENV["REPO"] = "abema/abema-ios"
  ENV["SLACK_URL"] = ENV["SLACK_GENERAL_WEBHOOK"]
  ENV["SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA"] = "true"
  ENV["FASTLANE_IS_INTERACTIVE"] = "false"
  ENV["CI"]= "1"
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.5.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.5.0        |
| bundler                                   | 2.3.13       |
| pathname                                  | 0.1.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.5        |
| CFPropertyList                            | 3.0.6        |
| concurrent-ruby                           | 1.2.0        |
| i18n                                      | 1.12.0       |
| minitest                                  | 5.17.0       |
| tzinfo                                    | 2.0.6        |
| zeitwerk                                  | 2.6.6        |
| activesupport                             | 6.1.7.2      |
| public_suffix                             | 4.0.7        |
| addressable                               | 2.8.1        |
| httpclient                                | 2.8.3        |
| json                                      | 2.6.3        |
| algoliasearch                             | 1.27.5       |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.716.0      |
| aws-sigv4                                 | 1.5.2        |
| jmespath                                  | 1.6.2        |
| aws-sdk-core                              | 3.170.0      |
| aws-sdk-kms                               | 1.62.0       |
| aws-sdk-s3                                | 1.119.1      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.1.0        |
| colored2                                  | 3.1.2        |
| cork                                      | 0.3.0        |
| nap                                       | 1.1.0        |
| open4                                     | 1.3.4        |
| claide-plugins                            | 0.9.2        |
| fuzzy_match                               | 2.0.4        |
| netrc                                     | 0.11.0       |
| ffi                                       | 1.15.5       |
| ethon                                     | 0.15.0       |
| typhoeus                                  | 1.4.0        |
| cocoapods-core                            | 1.11.3       |
| cocoapods-deintegrate                     | 1.0.5        |
| cocoapods-downloader                      | 1.6.3        |
| cocoapods-plugins                         | 1.0.0        |
| cocoapods-search                          | 1.0.1        |
| cocoapods-trunk                           | 1.6.0        |
| cocoapods-try                             | 1.2.0        |
| escape                                    | 0.0.4        |
| fourflusher                               | 2.3.1        |
| gh_inspector                              | 1.1.3        |
| molinillo                                 | 0.8.0        |
| ruby-macho                                | 2.5.1        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.22.0       |
| cocoapods                                 | 1.11.3       |
| colored                                   | 1.2          |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.0.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.3       |
| faraday-http-cache                        | 2.4.1        |
| rchardet                                  | 1.8.0        |
| git                                       | 1.13.1       |
| kramdown                                  | 2.4.0        |
| kramdown-parser-gfm                       | 1.1.0        |
| no_proxy_fix                              | 0.1.2        |
| sawyer                                    | 0.9.2        |
| octokit                                   | 5.6.1        |
| unicode-display_width                     | 1.8.0        |
| terminal-table                            | 1.8.0        |
| danger                                    | 9.2.0        |
| danger-plugin-api                         | 1.0.0        |
| danger-swiftformat                        | 0.8.1        |
| xcresult                                  | 0.2.1        |
| danger-xcode_summary                      | 1.2.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.4        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.99.0       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.6        |
| jwt                                       | 2.7.0        |
| memoist                                   | 0.16.2       |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.17.0       |
| googleauth                                | 1.3.0        |
| mini_mime                                 | 1.1.2        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.8.1        |
| google-apis-core                          | 0.11.0       |
| google-apis-androidpublisher_v3           | 0.34.0       |
| google-apis-playcustomapp_v1              | 0.13.0       |
| google-apis-iamcredentials_v1             | 0.17.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.0        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.44.0       |
| mini_magick                               | 4.12.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.7.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.10       |
| terminal-notifier                         | 2.0.0        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| fastlane-plugin-firebase_app_distribution | 0.5.0        |
</details>

*generated on:* **2023-03-10**
</details>

### PR DESCRIPTION
**Pull request by giginet**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

closes #21125

This PR fixes this issue.
[Listing apps fails, due to the recent pricing update on App Store? · Issue #21125 · fastlane/fastlane](https://github.com/fastlane/fastlane/issues/21125)

### Description

Since App Store Connect API 2.3([released on March 2023](https://developer.apple.com/news/releases/?id=03092023b)), `App.prices` has been deprecated. 
https://developer.apple.com/documentation/appstoreconnectapi/app/relationships/prices

After this version, the following 409 error is returned when requested with including`prices` attributes.

```
The resource 'appPrices' cannot be viewed, created or updated. Please view and create 'manualPrices' using the resource 'appPriceSchedules'.
```

However, `prices` are always included as an essential attribute.

This PR removes `prices` from `ESSENTIAL_INCLUDES`.

### Testing Steps

1. Enable scheduled prices for your app on AppStore Connect
2. Execute the following lane

```ruby
lane :app_version do
  app_store_connect_api_key 
  app_store_build_number
end
```

### Discussion

This PR is just a hotfix. We need to support the new price API to fetch prices.

The current response mock is old. So we have to update this to follow the latest API spec.
https://github.com/fastlane/fastlane/blob/0c06ab0d8049b1c4012dc5305b190c7f5f825de1/spaceship/spec/connect_api/fixtures/testflight/apps.json#L113

### CODE REVIEW

File: spaceship/lib/spaceship/connect_api/models/app.rb [hunk 1]
```diff
@@ -54,12 +54,12 @@ module EducationDiscountType
         "contentRightsDeclaration" => "content_rights_declaration",
 
         "appStoreVersions" => "app_store_versions",
+        # This attribute is already deprecated. It will be removed in a future release.
         "prices" => "prices"
```
Comment (giginet) [inline spaceship/lib/spaceship/connect_api/models/app.rb:58]: I have no idea whether we can drop this attribute.

We have to support a latest API

**Comment by tukestolo** [comment]
please guys can you speed up this ? 🙏

**Review by SteveKennedy — APPROVED** [review]

File: spaceship/lib/spaceship/connect_api/models/app.rb (hunk 1 above)
Comment (android-leha) [reply spaceship/lib/spaceship/connect_api/models/app.rb:58]: As I see, old applications continue working with old attributes, so it is better to leave it, for backward compatibility.

**Comment by SteveKennedy** [comment]
This item seems like a complete show stopper for any CI/CD process using Fastlane to deploy to Apple.

None of the workarounds suggested up to this point work any more.

**Comment by giginet** [comment]
As discussed on #21125, this patch is not enough to support all changed APIs (e.g. `upload_price_tier`).

This patch works correctly for a specific use case. However, we need to support the latest API to fix all issues.
But it takes a much time to implement this.

@joshdholtz How do you think about these issues?

**Review by joshdholtz — APPROVED** [review]
Thanks for the fix! ❤️

File: spaceship/lib/spaceship/connect_api/models/app.rb (hunk 1 above)
Comment (vincentisambart) [reply spaceship/lib/spaceship/connect_api/models/app.rb:58]: I disagree, this attribute should be removed as with this PR's changes it will always end up being `nil`. Part of the code seeing the `nil` might think this app has no price even though it might have prices set up in App Store Connect, ending up with confusion like in #21213.
Not having the attribute would catch possible misuses.

Comment (vincentisambart) [reply spaceship/lib/spaceship/connect_api/models/app.rb:58]: Sorry, I might have misunderstood part of the code, as it seems app data can come from different locations, some with or without prices. The current state is pretty confusing 😅
