### PR TITLE
[supply] add new SUPPLY_UPLOAD_MAX_RETRIES env var to attempt to solve failed Google API calls

### LINKED ISSUE #21507: Google Api Error: Unauthorized - Request is missing required authentication credential when trying to do a Google Play release
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

We have a problem that started 2 days ago with publishing Google Play releases.
When running the `release_playstore` lane that use `supply` Google APIs return `Google Api Error: Unauthorized - Request is missing required authentication credential.`
We have checked the service account key and it is valid and does not have an expiry date. Can someone experienced take a look at this problem. The assumption is Google made changes to the way API requests need to be done.

##### Command executed

```
lane :release_playstore do
  identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  supply(
     package_name: identifier,
     metadata_path: "fastlane/metadata/android/#{identifier}",
)
end
```

##### Complete output when running fastlane, including the stack trace and command used
```
| release_status                     | completed                                                          |
| track                              | beta                                                               |
| json_key                           | /home/vsts/work/_temp/fastlane-serviceaccount.json                 |
| aab                                | /home/vsts/work/1/xxx-Android-Production/xxx-release.aab |
| skip_upload_apk                    | false                                                              |
| skip_upload_aab                    | false                                                              |
| skip_upload_metadata               | false                                                              |
| skip_upload_changelogs             | false                                                              |
| skip_upload_images                 | false                                                              |
| skip_upload_screenshots            | false                                                              |
| track_promote_release_status       | completed                                                          |
| validate_only                      | false                                                              |
| check_superseded_tracks            | false                                                              |
| timeout                            | 300                                                                |
| deactivate_on_promote              | true                                                               |
| changes_not_sent_for_review        | false                                                              |
| rescue_changes_not_sent_for_review | true                                                               |
| ack_bundle_installation_warning    | false                                                              |
+------------------------------------+--------------------------------------------------------------------+

[09:28:36]: Preparing aab at path '/home/vsts/work/1/golive-Android-Production/xxx-release.aab' for upload...
[09:29:02]: Updating track 'beta'...
[09:29:03]: Preparing to upload for language 'de-DE'...
[09:29:04]: Updating changelog for '14551' and language 'de-DE' to default changelog...
[09:29:04]: Preparing to upload for language 'en-US'...
[09:29:04]: Uploading image file fastlane/metadata/android/xxx/en-US/images/featureGraphic.png...
[09:29:07]: Uploading image file fastlane/metadata/android/xxx/en-US/images/icon.png...
[09:29:10]: Uploading screenshot fastlane/metadata/android/xxx/en-US/images/phoneScreenshots/1_en-US.png...
+---------------+---------------------------+
|               Lane Context                |
+---------------+---------------------------+
| ENVIRONMENT   | xxx                    |
| PLATFORM_NAME | android                   |
| LANE_NAME     | android release_playstore |
+---------------+---------------------------+
[09:29:12]: Google Api Error: Unauthorized - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

+------+---------------+-------------+
|          fastlane summary          |
+------+---------------+-------------+
| Step | Action        | Time (in s) |
+------+---------------+-------------+
| 1    | opt_out_usage | 0           |
| 💥   | supply        | 37          |
+------+---------------+-------------+
[09:29:12]: fastlane finished with errors

[!] Google Api Error: Unauthorized - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context

Somewhat fixes #21507

Applying the patch made by @AliSoftware mentioned https://github.com/fastlane/fastlane/issues/21507#issuecomment-1721417442

### Description

Added new `SUPPLY_UPLOAD_MAX_RETRIES` env variable to retry failed Google API requests to attempt to "fix" uploads from erroring

```sh
SUPPLY_UPLOAD_MAX_RETRIES=5 fastlane your_lane
```

### CODE REVIEW

File: supply/spec/client_spec.rb [hunk 1]
```diff
@@ -8,23 +8,47 @@
...
+      end
+
+      it "with 5 retries" do
+        stub_const("ENV", { 'SUPPLY_UPLOAD_MAX_RETRIES' => 5 })
+
+        stub_request(:post, "https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/test-app/edits/1/listings/en-US/icon").
+          to_return(status: 403, body: '{"error":{"message":"Ensure project settings are enabled."}}', headers: { 'Content-Type' => 'application/json' })
+
+        expect(UI).to receive(:error).with("Google Api Error: Invalid request - Ensure project settings are enabled. - Retrying...").exactly(5).times
+        expect(UI).to receive(:user_error!).with("Google Api Error: Invalid request - Ensure project settings are enabled.").once
```
Comment (AliSoftware) [inline supply/spec/client_spec.rb:38]: One thing that I got bitten by in the past is that when you stub `UI.user_error!` with `expect` or `allow`, that means that the original method won't be called… which means that it won't `raise`.

All that means that the caller of `call_google_api`, in your case `client.upload_image`, won't be interrupted by the `Fastlane::Error` raised by `user_error!` in the context of running tests, while it will in the real world. Depending on the implementation of `client.upload_image(…)`, that could have side effects if that implementation counts on the fact that `call_google_api` can raise to stop early and not run the rest of the code of that method on error, as that would mean that the fact that we stubbed `user_error!` would make the method under test behave differently in test environment vs in reality.

I think the easiest way to solve this would be to replace your `expect(UI).to receive(:user_error!)` with wrapping your call to `client.upload_image` within `expect { … }.to raise_error(Fastlane::Error, "Google Api Error: Invalid request – Ensure project settings are enabled."`. That way you'd let `user_error!` raise and interrupt the code of `upload_image` mid-air even in the context of testing.

Comment (joshdholtz) [reply supply/spec/client_spec.rb:38]: @AliSoftware That expect on `UI.user_error!` was already there 🤷 But... would be adding `.and_call_original` work? 🤔

Comment (AliSoftware) [reply supply/spec/client_spec.rb:38]: Well that would, except that I _think_ `rubocop` might suggest you to only call `.and_call_original` on `allow(…)`, not on `expect(…)`

So you could `allow(UI).to receive(:user_error!).with(…).and_call_original`… but if you do that and even if you wanted to still keep the `expect(UI).to receive(:user_error!).once` to assert on it only being called once and not more, you'll still need to wrap your `client.upload_image` within `expect { … }.to raise_error(…)` to avoid the test from crashing on the raised error and instead catch (and assert) it.

So at this point since you'll still need the `expect { … } .to raise_error`, I'm not sure that `and_call_original` adds much value, instead of not stubbing `UI.user_error!` at all?

**Review by AliSoftware — APPROVED** [review]
@joshdholtz I hope you don't mind, I've pushed a commit to apply the suggested change I was talking about for the spec 🙂

**Comment by joshdholtz** [comment]
@AliSoftware Thank you! I was at the lake yesterday and didn't have my computer on me. Just getting up with the family now so will get this merged and a new release made 💪
