### PR TITLE
[action] download_dsyms: fix downloading the latest build

### LINKED ISSUE #14091: download_dsyms(version: 'latest') not able to download latest build
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`download_dsyms(version: 'latest')` was not able to download the dSYMs of the latest build, even though they were available.
```
[13:46:09]: Looking for latest version...
[13:46:14]: Looking for dSYM files for com.cookpad v1903.0.0 (19.3.1.0)
[13:46:15]: No dSYM files found on App Store Connect - this usually happens when no recompiling has happened yet
```

The latest build was `v1903.1.0 (19.3.1.0)` and was released on the App Store. Before that we had submitted `v1903.0.0 (19.3.0.0)` but rejected it before it went through review.
There was no `v1903.0.0 (19.3.1.0)` build.

So 2 problems:
- The build fastlane tried to select (v1903.0.0) was not the latest.
- The version number fastlane tried to use was not the one for the build it tried to use.

FYI @giginet

### PR DESCRIPTION
**Pull request by vincentisambart**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes #14091

### Description
- Do not use the first candidate build but the latest one (the one with the most recent `upload_date`).
- Take the build number from the build and not from the version.

Cc @giginet

### CODE REVIEW

**Review by giginet — APPROVED** [review]
👍

File: fastlane/lib/fastlane/actions/download_dsyms.rb [hunk 1]
```diff
@@ -35,8 +35,15 @@ def self.run(params)
...
           UI.user_error!("Could not find latest version for your app, please try setting a specific version") if latest_version.version.nil?
 
-          version = get_version(latest_version)
-          build_number = latest_version.build_version
+          latest_candidate_build = latest_version.candidate_builds.max_by(&:upload_date)
+          if latest_candidate_build.nil?
+            version = latest_version.version
+            build_number = latest_version.build_version
+          else
+            # The build_version of a candidate build does not always match the one in latest_version so get the version and build number from the same place.
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/download_dsyms.rb]: ^ Good comment 👍

**Review by joshdholtz — APPROVED** [review]
Looks great! Thanks for the contribution ❤️
