### PR TITLE
[Fastlane.swift] fixes issues with running on Apple Silicon #18502

### LINKED ISSUE #18502: Swift fastlane does not run on Apple Silicon
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I try to run fastlane in Swift on Apple Silicone machine natively it fails on running. When I run the same command through Rosetta 2 (`arch -x86_64`) or on Intel machine, it works fine. 

I've tried it running it on macOS system Ruby (`ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.arm64e-darwin20]`) and on latest Ruby 2.7 (`ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]`) but with no luck.

##### Command executed
`bundle exec fastlane custom`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
% bundle exec fastlane custom 
[✔] 🚀 
[15:35:42]: loading manifest: /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/swift/upgrade_manifest.json
[15:35:42]: FastlaneSwiftRunner project is up-to-date
[15:35:42]: Resolving Swift Package Manager dependencies...
[15:35:42]: $ xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:35:42]: ▸ objc[59172]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x204ed0188) and ?? (0x1161a02b8). One of the two will be used. Which one is undefined.
[15:35:42]: ▸ objc[59172]: Class AMSupportURLSession is implemented in both ?? (0x204ed01d8) and ?? (0x1161a0308). One of the two will be used. Which one is undefined.
[15:35:42]: ▸ Command line invocation:
[15:35:42]: ▸     /Applications/Xcode-12.4.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
[15:35:42]: ▸ resolved source packages: 
[15:35:42]: $ xcodebuild -showBuildSettings -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj
objc[59178]: Class AMSupportURLConnectionDelegate is implemented in both ?? (0x204ed0188) and ?? (0x117d9c2b8). One of the two will be used. Which one is undefined.
objc[59178]: Class AMSupportURLSession is implemented in both ?? (0x204ed01d8) and ?? (0x117d9c308). One of the two will be used. Which one is undefined.
[15:35:43]: $ set -o pipefail && xcodebuild -scheme FastlaneRunner -project ./fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj -destination 'generic/platform=macOS' build | tee /Users/builder/Library/Logs/gym/App-FastlaneRunner.log | xcpretty
[15:35:52]: $ ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
[15:35:52]: ▸ sh: line 1: 59261 Killed: 9               ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
#<Thread:0x000000014921cc18 /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/swift_lane_manager.rb:96 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	4: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/swift_lane_manager.rb:97:in `block in cruise_swift_lane_in_thread'
	3: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	2: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	1: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Exit status of command './fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null' was 137 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: line 1: 59261 Killed: 9               ./fastlane/FastlaneRunner lane custom swiftServerPort 2000 > /dev/null
#<Thread:0x000000014925c598 /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/swift_lane_manager.rb:220 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	5: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:147:in `listen'
	2: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
	1: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `block in listen'
/Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:148:in `accept': execution expired (Timeout::Error)
	5: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'
	4: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
	3: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:146:in `listen'
	2: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane/lib/fastlane/server/socket_server.rb:151:in `rescue in listen'
	1: from /Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/builder/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.179.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down (FastlaneCore::Interface::FastlaneError)
+-----------+--------+
|    Lane Context    |
+-----------+--------+
| LANE_NAME | custom |
+-----------+--------+
[15:35:57]: fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
[15:35:57]: fastlane finished with errors

[!] fastlane failed to receive a connection from the FastlaneRunner binary after 5 seconds, shutting down
 </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 11.2.3                                           |
| Ruby                        | 2.7.2                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.24.3 (Apple Git-128)               |
| Installation Source         | ~/.rbenv/versions/2.7.2/bin/fastlane             |
| Host                        | macOS 11.2.3 (20D91)                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.2/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-12.4.app/Contents/Developer/ |
| Xcode Version               | 12.4                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// This file contains the fastlane.tools configuration
// You can find the documentation at https://docs.fastlane.tools
//
// For a list of all available actions, check out
//
//     https://docs.fastlane.tools/actions
//

import Foundation

class Fastfile: LaneFile {
	func customLane() {
	desc("Description of what the lane does")
		// add actions here: https://docs.fastlane.tools/actions
	}
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.179.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.4.0        |
| bundler                       | 2.2.15       |
| uri                           | 0.10.0       |
| rake                          | 13.0.3       |
| CFPropertyList                | 3.0.3        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| artifactory                   | 3.0.15       |
| atomos                        | 0.1.3        |
| aws-eventstream               | 1.1.1        |
| aws-partitions                | 1.440.0      |
| aws-sigv4                     | 1.2.3        |
| jmespath                      | 1.4.0        |
| aws-sdk-core                  | 3.113.1      |
| aws-sdk-kms                   | 1.43.0       |
| aws-sdk-s3                    | 1.93.0       |
| babosa                        | 1.0.4        |
| claide                        | 1.0.3        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| digest-crc                    | 0.6.3        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| dotenv                        | 2.7.6        |
| emoji_regex                   | 3.2.2        |
| excon                         | 0.79.0       |
| faraday-net_http              | 1.0.1        |
| multipart-post                | 2.0.0        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.3        |
| gh_inspector                  | 1.1.3        |
| jwt                           | 2.2.2        |
| memoist                       | 0.16.2       |
| multi_json                    | 1.15.0       |
| os                            | 1.1.1        |
| signet                        | 0.15.0       |
| googleauth                    | 0.16.1       |
| httpclient                    | 2.8.3        |
| mini_mime                     | 1.0.3        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| google-api-client             | 0.38.0       |
| rexml                         | 3.2.4        |
| webrick                       | 1.7.0        |
| google-apis-core              | 0.3.0        |
| google-apis-iamcredentials_v1 | 0.2.0        |
| google-apis-storage_v1        | 0.3.0        |
| google-cloud-env              | 1.5.0        |
| google-cloud-errors           | 1.1.0        |
| google-cloud-core             | 1.6.0        |
| google-cloud-storage          | 1.31.0       |
| json                          | 2.5.1        |
| mini_magick                   | 4.11.0       |
| naturally                     | 2.2.1        |
| plist                         | 3.6.0        |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| simctl                        | 1.6.8        |
| slack-notifier                | 2.3.2        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| xcpretty-travis-formatter     | 1.0.1        |
</details>

*generated on:* **2021-04-02**
</details>

### PR DESCRIPTION
**Pull request by kikeenrique**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Swift fastlane does not run on Apple Silicon, it crashes due to unsigned binary and also next due to a data race condition.

### Description

*  ~Update code to swift 5~
* Enable binary code signing, required for M1.
* Fix data race
* Modify copy binary phase, that copies the binary signed.
* Added verbose option to allow output to be seen if needed when swift fastlane binary is launched.

I created a swift fastlane fresh project, adding next lane on fastlane/Fastfile.swift to test basic functionality.
```
class Fastfile: LaneFile {
	func customLane() {
        desc("Description of what the lane does")
        print("test if output is printed somewhere")
        sh(command: "echo hola", log: false)
        sh(command: "echo hola", log: true)
        sh(command: "ls -la", log: true)
	}
}
```

### Testing Steps

I would add some tests for swift fastlane executing basic actions on M1 host, as I did, but I lack some knowledge on fastlane on how to do it.

### CODE REVIEW

**Comment by kikeenrique** [comment]
If any help is needed on reviewing I'm open to a video meeting 😀

File: fastlane/lib/fastlane/swift_lane_manager.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def self.cruise_lane(lane, parameters = nil, env = nil, disable_runner_upgrades:
         # wait on socket_thread to be in ready state, then start the runner thread
         self.cruise_swift_lane_in_thread(lane, parameters, swift_server_port)
 
-        socket_thread.join
+        socket_thread.value
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/swift_lane_manager.rb:36]: Do you know why this change was needed? Just curious 😊

**Review by joshdholtz — COMMENTED** [review]
This looks really good! I think I just have one question on this code 😊 

I'm going to do a bit more testing and see if I can get another review but this is 💯

**Comment by minuscorp** [comment]
I don't have an M1 to test with :(

File: fastlane/lib/fastlane/swift_lane_manager.rb (hunk 1 above)
Comment (kikeenrique) [reply fastlane/lib/fastlane/swift_lane_manager.rb:36]: I added it to not just wait, but also get the output from the thread.
On verbose mode, it allows output from the runner thread, so you can see traces and ease feedback from fastlane swift thread.
You could see the change isolated [here](https://github.com/fastlane/fastlane/pull/19555/commits/1e15cdcffecea2e7de09689d5d91d0b30a2db647) with the  other verbose control flag changes.

**Comment by kikeenrique** [comment]
> I don't have an M1 to test with :(

It's a pity that GitHub actions doesn't have still M1 builders (https://github.com/actions/virtual-environments/issues/2187).
I wonder if any other CI service does.

**Review by rogerluan — CHANGES_REQUESTED** [review]
I have some minor formatting suggestions that I've posted below @kikeenrique, but when I tested this PR, I faced some issues.

My setup:

1. `mkdir fastlane-test && cd fastlane-test`
2. Created a Gemfile and put this content inside of it:

```rb
source 'https://rubygems.org'

gem "fastlane" # Notice that I was pointing to the latest version of fastlane, and not your PR
```

3. `bundle install`
4. `bundle exec fastlane swift init`
5. Go through the installation steps accepting all default config

Then I got this error:

image

Which's probably expected - it's probably what this PR aims to fix, right? 😄 Since I'm running on M1 and pointing _fastlane_ to the latest release.

So then I modified my Gemfile to point to your repo and branch:

```rb
source 'https://rubygems.org'

gem "fastlane", :git => "https://github.com/kikeenrique/fastlane.git", :branch => "18502"
```

And ran `bundle exec fastlane custom` again, and got the following:

image
image

PS: Click the picture to enlarge them 🙏 

Then I ran `bundle exec fastlane custom` again, and the error changes:

image

No idea what was causing that. But I thought I may have corrupted the files, so I deleted the `fastlane` directory that `bundle exec fastlane swift init` had created, and set it up again:

1. `bundle exec fastlane swift init`
2. `bundle exec fastlane custom`

And then it worked just fine:

image

I double checked that the steps I just posted are reproducible (I did everything twice again and obtained the same results).

@kikeenrique @joshdholtz any idea how we can prevent this from happening? It looks like a terrible UX if this will be a breaking release for Fastlane.Swift users 😬 

Also tagging @minuscorp in here, the real Fastlane.Swift bad ass 🙇

**Comment by kikeenrique** [comment]
I will take a look at this upgrade problems, I don't know why that happened.
The kill that you got before resetting fastlane directory smells to problems with signing on M1. 
At a first sight, both problems look like the Xcode project didn't get fully upgraded, as I said, I will look further into this.

_As a side note, I've experienced in the past problems in macOS when signing files with same name and overwriting them again with a copy. I read in Apple forums that it was a macOS cache problem that sometimes maybe fixed moving files instead of copying._

**Comment by kikeenrique** [comment]
> I will take a look at this upgrade problems, I don't know why that happened. The kill that you got before resetting fastlane directory smells to problems with signing on M1. At a first sight, both problems look like the Xcode project didn't get fully upgraded, as I said, I will look further into this.
> 
I can confirm it, the second batch does not update FastlaneSwiftRunner.xcodeproj, which is needed, as this PR fixes those problems. That explains the swift 4 compilation error and the kill due to the signing problem.
```
bundle exec fastlane swift init
bundle exec fastlane custom
```
I need to review how to enforce that file to be upgraded.

File: fastlane/swift/SocketClient.swift [hunk 2]
```diff
@@ -79,8 +79,8 @@ class SocketClient: NSObject {
             self.inputStream.delegate = self
             self.outputStream.delegate = self
 
-            self.inputStream.schedule(in: .main, forMode: .defaultRunLoopMode)
-            self.outputStream.schedule(in: .main, forMode: .defaultRunLoopMode)
+            self.inputStream.schedule(in: .main, forMode: RunLoop.Mode.default)
+            self.outputStream.schedule(in: .main, forMode: RunLoop.Mode.default)
```
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/SocketClient.swift:83]: I can't recall correctly if this is implemented yet in the Swift version we're using, but if it is, go ahead!

File: fastlane/swift/Runner.swift [hunk 3]
```diff
@@ -22,14 +22,47 @@ func desc(_: String) {
...
+
 class Runner {
     private var thread: Thread!
     private var socketClient: SocketClient!
     private let dispatchGroup = DispatchGroup()
     private var returnValue: String? // lol, so safe
     private var currentlyExecutingCommand: RubyCommandable?
     private var shouldLeaveDispatchGroupDuringDisconnect = false
-    private var executeNext: [String: Bool] = [:]
+    private var executeNext: AtomicDictionary<String, Bool> = AtomicDictionary()
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:65]: there shouldn't be any need of an atomic usage here, because all reads and writes of the dictionary are made inside a `DispatchGroup`, so no two callers can access to that method at once, that way we preserve the lock and the order of the operations.

**Review by minuscorp — CHANGES_REQUESTED** [review]
I'm not quite sure of many of the changes, the bump to Swift 5 is a pretty big breaking change in the first place. Secondly, there're changes that in design should be unneeded.

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (kikeenrique) [reply fastlane/swift/Runner.swift:65]: There was a crash with that code, check my comments previous to adding this part of the fix: https://github.com/fastlane/fastlane/issues/18502#issuecomment-949980464

File: fastlane/swift/main.swift [hunk 4]
```diff
@@ -38,7 +38,7 @@ class MainProcess {
 let process = MainProcess()
 process.startFastlaneThread()
 
-while !process.doneRunningLane, RunLoop.current.run(mode: RunLoopMode.defaultRunLoopMode, before: Date(timeIntervalSinceNow: 2)) {
+while !process.doneRunningLane, RunLoop.current.run(mode: RunLoop.Mode.default, before: Date(timeIntervalSinceNow: 2)) {
```
[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/swift/main.swift:41]: But we're upgrading to Swift 5 in this PR 🤔 ?

File: fastlane/lib/fastlane/swift_fastlane_api_generator.rb [hunk 5]
```diff
@@ -367,7 +367,7 @@ def generate_tool_protocol(tool_swift_function: nil)
       protocol_content_array = []
       protocol_name = tool_swift_function.protocol_name
 
-      protocol_content_array << "public protocol #{protocol_name}: class {"
+      protocol_content_array << "public protocol #{protocol_name}: AnyObject {"
```
[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/lib/fastlane/swift_fastlane_api_generator.rb:370]: This change is pretty safe though AFAIK, is it not? It's a mere formality

File: Package.swift [hunk 6]
```diff
@@ -18,6 +18,6 @@ let package = Package(
             exclude: ["Actions.swift", "Plugins.swift", "main.swift", "formatting", "FastlaneSwiftRunner"]
         ),
     ],
-    swiftLanguageVersions: [4]
+    swiftLanguageVersions: [5]
```
[the remark this answers is not in the document]
Comment (minuscorp) [reply Package.swift:21]: @rogerluan here we're bumping the minimum Swift version for SPM

File: fastlane/swift/Runner.swift [hunk 7]
```diff
@@ -22,14 +22,47 @@ func desc(_: String) {
     // no-op, this is handled in fastlane/lane_list.rb
 }
 
+class AtomicDictionary<Key: Hashable, Value> {
+    private let lockQueue = DispatchQueue(label: "tools.fastlane.serial.queue")
```
[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/swift/Runner.swift:26]: 😮 I had no idea

File: fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj [hunk 8]
```diff
@@ -394,20 +398,22 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				CLANG_ENABLE_MODULES = YES;
+				CODE_SIGN_IDENTITY = "-";
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/../Frameworks @loader_path/../Frameworks";
 				PRODUCT_NAME = "$(TARGET_NAME)";
 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
-				SWIFT_VERSION = 4.0;
+				SWIFT_VERSION = 5.0;
```
Comment (minuscorp) [inline fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj:405]: 😢

File: fastlane/swift/main.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/swift/main.swift:41]: Nevermind, just read your comments below.
Can I understand why the desire to keep it compatible with Swift 4? Is it so users are able to use Fastlane.Swift on older versions of Xcode?

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (minuscorp) [reply fastlane/swift/Runner.swift:65]: I read that crash but I don't see how it is related to the `DispatchGroup` being broken. Not that the introduced code is so breaking, but I just don't see any relationship. Again, I don't have a M1 machine so I can't see the traceback from Xcode about that method crashing.

File: fastlane/swift/main.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/main.swift:41]: That's the main reason, I mean, I could've bumped to Swift 5 a time ago but It seemed correct to me not to introduce  a breaking change like this without knowing if people would be affected for that. Also, the initial implementation was written in Swift 4 so I respected that.

[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/swift/main.swift:41]: Makes sense!

[the remark this answers is not in the document]
Comment (rogerluan) [reply fastlane/swift/main.swift:41]: Just gonna leave this here: Swift 5 toolchain was first introduced in Xcode 10.2, which was officially released on March 25 2019
Perhaps it wouldn't be much of an issue in practice, but I see your point @minuscorp 👍 

We should probably include info like this in fastlane's analytics gathering (including how many people (or %) actually use Fastlane.Swift 🤔 )

[the remark this answers is not in the document]
Comment (kikeenrique) [reply fastlane/swift/main.swift:41]: I see your point. I can change it back to swift 4.
But I think it's a good time to do it, swift 5 was introduced 2019/03, at it seems it will have a longer support cycle.
I sincerely don't see the point in preserving backwards compatibility to swift 4 for fastlane, which is usually used to deliver to the App Store, which enforced you to use Xcode 12 and iOS 14 SDK et al.
Besides upgrading swift 4 to swift 5 is not usually painful.

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (kikeenrique) [reply fastlane/swift/Runner.swift:26]: I don't think it's such a performance killer in these comparison -> https://trycombine.com/posts/performance-actor-queue-lock-benchmark/, do you have a source?
Also, I've read that using os_unfair_lock_s is not recommended in swift -> https://swiftrocks.com/thread-safety-in-swift.html
I would suggest addressing the performance improvement in another PR, as at the moment this just doesn't work at all on M1.

File: fastlane/swift/main.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/main.swift:41]: Not that it is painful or that I'm not aware how deprecated it is, just saying that I'd prefer to first solve this issue in Swift 4 without any breaking changes and do a later PR to upgrade to Swift 5.
I think it is better to do one thing at a time, because this is not a complete migration of everything and I'd prefer to take a deeper look into it.

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/Runner.swift:26]: https://gist.github.com/steipete/36350a8a60693d440954b95ea6cbbafc

[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/Runner.swift:26]: > Note: @tclementdev has kindly shared with me that's not a good idea to use this lock in Swift because the ampersand in Swift actually copies the lock instead of referencing it, and this can cause an infinite number of problems. I'll keep this section because I think it's interesting knowledge, but I'll spoil a bit and say that this is not the solution to the problem and you should probably not use it.

Again, this is not entirely right, `os_unfair_lock` needs to be a reference where it can be read as a memory reference, that's why the `&`. Like an `inout`, it is not copied, it is just modified inside their lock and unlock methods.

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (kikeenrique) [reply fastlane/swift/Runner.swift:65]: I've unapplied AtomicDictionary commit to get a screenshot with the crash and the trace by the ThreadSanitizer. Just in case it helps any better.
Screenshot 2021-12-01 at 15 28 50

Comment (minuscorp) [reply fastlane/swift/Runner.swift:65]: We should figure out why there're being two concurrent accesses to that method in first place I think it might be the root of the problem🤔

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (tclementdev) [reply fastlane/swift/Runner.swift:26]: Nope, you cannot use an ampersand for this. The ampersand is *not* an address-of operator like in C. Please see [this](https://developer.apple.com/forums/thread/674633) and [this](https://github.com/apple/swift-evolution/blob/master/proposals/0282-atomics.md#interaction-with-implicit-pointer-conversions), and [this](http://www.russbishop.net/the-law).

As for the dispatch queue, it is ok as a less-performant lock if you only call `sync()` on it.

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (tclementdev) [reply fastlane/swift/Runner.swift:65]: If I may, are you thinking of `DispatchSemaphore` instead of `DispatchGroup`? I am not sure how `DispatchGroup` protects against concurrent access here (entering a group is not a wait operation).

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/Runner.swift:26]: From the Apple documentation:

> because the lock implementation relies on the address of the lock value and owning process.

Which is the instance of the `os_unfair_lock`. I've said that it needs to be a mutable pointer to the instance because it has to be passed by reference to the lock and unlock methods. I know what `&` means in Swift 😄 I just was trying to give a fast explanation of why it has preference on our systems to be used as a performant locking system. Here there're like 1 call at a time, he can use whatever he wants. I don't want to enlarge this discussion to the OS level to see which abstraction is faster. Just said the side effects of the `DispatchQueue` and the tests that demonstrate that my suggestion was the fastests in the benchmarks.

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (minuscorp) [reply fastlane/swift/Runner.swift:65]: I don't think that it was added as a exclusion zone but more for a balancing calls method (I'm not the author of the whole implementation, I'm just the maintainer but I don't have an M1 to help here), maybe this doesn't do anything at all, but if iirc, this was needed for synchronizing with other parts of the code.

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (tclementdev) [reply fastlane/swift/Runner.swift:26]: Never mind then, I'm still confused by your previous message, I thought you were saying the ampersand was ok to use with `os_unfair_lock` so I felt obligated to chime in, sorry if I misread.

[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/Runner.swift:26]: Not that it is ok, just that it's needed for the lock to work 🤷‍♂️

[the remark this answers is not in the document]
Comment (tclementdev) [reply fastlane/swift/Runner.swift:26]: Wait what? No. Then please do read the links I provided above. For locks/atomics one must use `UnsafeMutablePointer` to allocate a stable pointer to stable memory and always use that pointer. Using the ampersand will not work right for locks/atomics.

[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/swift/Runner.swift:26]: I let me and my team use them wrong for a long time😓 shame on me

[the remark this answers is not in the document]
Comment (tclementdev) [reply fastlane/swift/Runner.swift:26]: Unfortunately a very easy mistake to make.

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (kikeenrique) [reply fastlane/swift/Runner.swift:65]: Here it's the reason of the data race:

- waitWithPolling is retaining/reading  executeNext in one thread
- commandExecuted is writing executeNext in other thread

Screenshot 2021-12-02 at 01 19 07

Screenshot 2021-12-02 at 01 10 51

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (kikeenrique) [reply fastlane/swift/Runner.swift:26]: As a proof of concept, I tested both os_unfair_lock  versions. 

- UnfairWrongDictionary crashes the same way that without an AtomicDictionary.
- UnfairDictionary works properly as AtomicDictionary does.
Screenshot 2021-12-02 at 01 41 01
Screenshot 2021-12-02 at 01 40 54

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (minuscorp) [reply fastlane/swift/Runner.swift:65]: To not block the current running thread (so you can poll it) the wait is being performed in another thread, yes, that's correct.

File: fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj (hunk 8 above)
Comment (kikeenrique) [reply fastlane/swift/FastlaneSwiftRunner/FastlaneSwiftRunner.xcodeproj/project.pbxproj]: I've pushed new changed that preverse swift 4.0

File: fastlane/swift/Runner.swift (hunk 7 above)
[the remark this answers is not in the document]
Comment (kikeenrique) [reply fastlane/swift/Runner.swift]: I've pushed new changes that use os_unfair_lock_s

File: Package.swift (hunk 6 above)
[the remark this answers is not in the document]
Comment (kikeenrique) [reply Package.swift]: I've pushed new changes that preserve swift 4.0

**Comment by kikeenrique** [comment]
I've pushed new changes that:
* use os_unfair_lock_s
* preserve swift 4.0

I still don't know how to force the upgrade of FastlaneSwiftRunner.xcodeproj (the problem that @rogerluan [comment here](https://github.com/fastlane/fastlane/pull/19555#pullrequestreview-819621259)). 
Project needs to be updated with the new config and build phase in order to sign and copy the FastlaneRunner binary every time the project needs to be rebuild.

File: fastlane/swift/Runner.swift [hunk 9]
```diff
@@ -22,36 +22,42 @@ func desc(_: String) {
     // no-op, this is handled in fastlane/lane_list.rb
 }
 
-class AtomicDictionary<Key: Hashable, Value> {
-    private let lockQueue = DispatchQueue(label: "tools.fastlane.serial.queue")
+class UnfairDictionary<Key: Hashable, Value> {
```
Comment (rogerluan) [inline fastlane/swift/Runner.swift:25]: I'd keep the name as `AtomicDictionary` :) It's more user friendly and describes clearly what this class does. The underlying technology powering the atomic behavior isn't important to users of `AtomicDictionary` IMO

**Review by rogerluan — COMMENTED** [review]
Just a nitpick on the class name 🙇

File: fastlane/swift/Runner.swift (hunk 9 above)
Comment (kikeenrique) [reply fastlane/swift/Runner.swift]: Done 🚀

**Comment by rogerluan** [comment]
>I still don't know how to force the upgrade of FastlaneSwiftRunner.xcodeproj

@minuscorp are you familiar with this part of the code?

**Comment by minuscorp** [comment]
I need to take a deeper look into the script and see if I can help, in blind in this case

File: fastlane/swift/Runner.swift [hunk 10]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+    init() {
+        unfairLock = UnsafeMutablePointer<os_unfair_lock>.allocate(capacity: 1)
+        unfairLock.initialize(to: os_unfair_lock())
+        storage = [:]
+    }
+
+    deinit {
+        unfairLock.deallocate()
+    }
+
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:38]:
```suggestion
subscript(_ key: Key) -> Value? {
    get {
        get(key)
    }
    set {
        set(key, value: newValue)
    }
}
```

File: fastlane/swift/Runner.swift [hunk 11]
```diff
@@ -38,7 +77,7 @@ class Runner {
 
         let secondsToWait = DispatchTimeInterval.seconds(SocketClient.defaultCommandTimeoutSeconds)
         // swiftformat:disable:next redundantSelf
-        let timeoutResult = Self.waitWithPolling(self.executeNext[command.id], toEventually: { $0 == true }, timeout: SocketClient.defaultCommandTimeoutSeconds)
+        let timeoutResult = Self.waitWithPolling(self.executeNext.get(command.id), toEventually: { $0 == true }, timeout: SocketClient.defaultCommandTimeoutSeconds)
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:80]:
```suggestion
        let timeoutResult = Self.waitWithPolling(self.executeNext[command.id], toEventually: { $0 == true }, timeout: SocketClient.defaultCommandTimeoutSeconds)
```

File: fastlane/swift/Runner.swift [hunk 12]
```diff
@@ -160,10 +199,10 @@ extension Runner: SocketClientDelegateProtocol {
             if let command = currentlyExecutingCommand as? RubyCommand {
                 if let closureArgumentValue = closureArgumentValue, !closureArgumentValue.isEmpty {
                     command.performCallback(callbackArg: closureArgumentValue, socket: socketClient) {
-                        self.executeNext[command.id] = true
+                        self.executeNext.set(command.id, value: true)
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:202]:
```suggestion
                        self.executeNext[command.id] = true
```

File: fastlane/swift/Runner.swift [hunk 13]
```diff
@@ -160,10 +199,10 @@ extension Runner: SocketClientDelegateProtocol {
...
                     }
                 } else {
-                    executeNext[command.id] = true
+                    executeNext.set(command.id, value: true)
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:205]:
```suggestion
                    executeNext[command.id] = true
```

File: fastlane/swift/Runner.swift [hunk 14]
```diff
@@ -172,14 +211,14 @@ extension Runner: SocketClientDelegateProtocol {
             verbose(message: "server acknowledged a cancel request")
             dispatchGroup.leave()
             if let command = currentlyExecutingCommand as? RubyCommand {
-                executeNext[command.id] = true
+                executeNext.set(command.id, value: true)
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:214]:
```suggestion
                executeNext[command.id] = true
```

File: fastlane/swift/Runner.swift [hunk 15]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+        unfairLock = UnsafeMutablePointer<os_unfair_lock>.allocate(capacity: 1)
+        unfairLock.initialize(to: os_unfair_lock())
+        storage = [:]
+    }
+
+    deinit {
+        unfairLock.deallocate()
+    }
+
+    func get(_ key: Key) -> Value? {
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:39]:
```suggestion
    private func get(_ key: Key) -> Value? {
```

File: fastlane/swift/Runner.swift [hunk 16]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+        os_unfair_lock_lock(unfairLock)
+        defer { os_unfair_lock_unlock(unfairLock) }
+        return storage[key]
+    }
+
+    func set(_ key: Key, value: Value) {
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:45]:
```suggestion
    private func set(_ key: Key, value: Value) {
```

File: fastlane/swift/Runner.swift (hunk 10 above)
Comment (minuscorp) [inline fastlane/swift/Runner.swift:38]:
```suggestion
subscript(_ key: Key) -> Value? {
    get {
        get(key)
    }
    set(newValue) {
        set(key, value: newValue)
    }
}
```

File: fastlane/swift/Runner.swift (hunk 15 above)
Comment (minuscorp) [inline fastlane/swift/Runner.swift:39]:
```suggestion
   private func get(_ key: Key) -> Value? {
```

File: fastlane/swift/Runner.swift (hunk 16 above)
Comment (minuscorp) [inline fastlane/swift/Runner.swift:45]:
```suggestion
    private func set(_ key: Key, value: Value) {
```

File: fastlane/swift/Runner.swift [hunk 17]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+        storage[key] = value
+    }
+
+    func removeValue(forKey key: Key) {
+        os_unfair_lock_lock(unfairLock)
+        defer { os_unfair_lock_unlock(unfairLock) }
+        _ = storage.removeValue(forKey: key)
+    }
+
+    var allValues: [Key: Value] {
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:57]: Is this used?

File: fastlane/swift/Runner.swift [hunk 18]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+        return storage[key]
+    }
+
+    func set(_ key: Key, value: Value) {
+        os_unfair_lock_lock(unfairLock)
+        defer { os_unfair_lock_unlock(unfairLock) }
+        storage[key] = value
+    }
+
+    func removeValue(forKey key: Key) {
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:51]:
```suggestion
    @discardableResult
    func removeValue(forKey key: Key) {
```

File: fastlane/swift/Runner.swift [hunk 19]
```diff
@@ -22,14 +22,53 @@ func desc(_: String) {
...
+        os_unfair_lock_lock(unfairLock)
+        defer { os_unfair_lock_unlock(unfairLock) }
+        _ = storage.removeValue(forKey: key)
```
Comment (minuscorp) [inline fastlane/swift/Runner.swift:54]:
```suggestion
        return storage.removeValue(forKey: key)
```

File: fastlane/swift/Runner.swift (hunk 3 above)
Comment (minuscorp) [reply fastlane/swift/Runner.swift:71]:
```suggestion
    private var executeNext: AtomicDictionary<String, Bool> = .init()
```

**Review by minuscorp — CHANGES_REQUESTED** [review]
Minor code style changes

**Comment by kikeenrique** [comment]
I've already committed all subscript suggestions.

Also, I've reviewed the files updating mechanism in SwiftRunnerUpgrader. It's designed to update the Xcode project when a swift file or group is updated or added using xcodeproj. But nothing else in the project would be updated. No flags, build phases, etc. And this PR modifies the build phase that updates the binary and sets the flag CODE_SIGN_IDENTITY.

A possible solution could update the project with a raw copy would be, but all small files updates and checks in SwiftRunnerUpgrader would make no sense then.
At the same time, it would mean overwriting a project that may have been modified by fastlane users, something that it's not declared in readme (https://github.com/fastlane/fastlane/blob/master/fastlane/swift/FastlaneSwiftRunner/README.txt).

Another solution would be to add more intelligence using xcodeproj. I'm going to test if this solution is feasible.

**Comment by kikeenrique** [comment]
BTW, there is a CI check failing:
`"error: 'os_unfair_lock' is only available in macOS 10.12 or newer"`
Options for this to be fixed?

**Comment by rogerluan** [comment]
> BTW, there is a CI check failing:
> `"error: 'os_unfair_lock' is only available in macOS 10.12 or newer"`
> Options for this to be fixed?

Have you tried specifying macOS 10.12 in `Package.swift` `platform` field?

**Comment by kikeenrique** [comment]
> > BTW, there is a CI check failing:
> > `"error: 'os_unfair_lock' is only available in macOS 10.12 or newer"`
> > Options for this to be fixed?
> 
> Have you tried specifying macOS 10.12 in `Package.swift` `platform` field?

I think it's not related to Package.swift, but with FastlaneSwiftRunner.xcodeproj.
Hm, Xcode 13 shows me a 10.12 as Deployment Info by default, with no build error, but I guess Xcode 12 would show something lower, that's why it fails.

**Comment by minuscorp** [comment]
There're two build steps, one for the xcproj and one for the package so you can see which one is failing😁

**Comment by kikeenrique** [comment]
> There're two build steps, one for the xcproj and one for the package so you can see which one is failing😁

Indeed,  @rogerluan was right, it's Package.swift failing. FastlaneSwiftRunner.xcodeproj has 10.12 set as deployment at project level.

**Comment by kikeenrique** [comment]
> > There're two build steps, one for the xcproj and one for the package so you can see which one is failing😁
> 
> Indeed, @rogerluan was right, it's Package.swift failing. FastlaneSwiftRunner.xcodeproj has 10.12 set as deployment at project level.

FYI, it does not exist a platform field on [swift-tools-version:4.0](https://github.com/apple/swift-package-manager/blob/swift-4.0-branch/Documentation/PackageDescriptionV4.md), nor anything similar to set a deployment version.

Using a _available_ wrapping the Package definition results in the same compilation warnings.
```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

var package: Package? = nil

if #available(macOS 10.12, *) {
    package = Package(
        name: "Fastlane",
        products: [
            .library(name: "Fastlane", targets: ["Fastlane"])
        ],
        dependencies: [
            .package(url: "https://github.com/kareman/SwiftShell", .upToNextMajor(from: "5.1.0"))
        ],
        targets: [
            .target(
                name: "Fastlane",
                dependencies: ["SwiftShell"],
                path: "./fastlane/swift",
                exclude: ["Actions.swift", "Plugins.swift", "main.swift", "formatting", "FastlaneSwiftRunner"]
            ),
        ],
        swiftLanguageVersions: [4]
    )

} else {

}

```

**Comment by minuscorp** [comment]
So two options, rollback to `DispatchQueue` or use the old `OSSpinLock` on versions lowers than macOS 10.12 with two private methods called lock and unlock that use `if #available ...` to choose from one lock or the other one, same for the initializer. Whichever you're more into, I'm curious about the second one 🌝

**Comment by kikeenrique** [comment]
> I've already committed all subscript suggestions.
> 
> Also, I've reviewed the files updating mechanism in SwiftRunnerUpgrader. It's designed to update the Xcode project when a swift file or group is updated or added using xcodeproj. But nothing else in the project would be updated. No flags, build phases, etc. And this PR modifies the build phase that updates the binary and sets the flag CODE_SIGN_IDENTITY.
> 
> A possible solution could update the project with a raw copy would be, but all small files updates and checks in SwiftRunnerUpgrader would make no sense then. At the same time, it would mean overwriting a project that may have been modified by fastlane users, something that it's not declared in readme (https://github.com/fastlane/fastlane/blob/master/fastlane/swift/FastlaneSwiftRunner/README.txt).
> 
> Another solution would be to add more intelligence using xcodeproj. I'm going to test if this solution is feasible.

Based on my improved ruby skills and on using [xcodeproj doc](https://www.rubydoc.info/gems/xcodeproj), I've been able to integrate the required steps to only upgrade the Xcode project build phase and flags needed. 
So the upgrade mechanism will make its magic.

**Comment by kikeenrique** [comment]
> So two options, rollback to `DispatchQueue` or use the old `OSSpinLock` on versions lowers than macOS 10.12 with two private methods called lock and unlock that use `if #available ...` to choose from one lock or the other one, same for the initializer. Whichever you're more into, I'm curious about the second one 🌝
> 
> Edit: or just https://github.com/mattgallagher/CwlUtils/blob/0bfc4587d01cfc796b6c7e118fc631333dd8ab33/Sources/CwlUtils/CwlMutex.swift#L60-L105 and carry on, it is already implemented 😆

What if the swift-tools-version is updated to 5.0?
It would keep deployment set to 10.12(FastlaneSwiftRunner.xcodeproj already has this deployment) and swift 4. 
It looks like this:
```
// swift-tools-version:5.0
// The swift-tools-version declares the minimum version of Swift required to build this package.
import PackageDescription

let package = Package(
    name: "Fastlane",
    platforms: [.macOS(.v10_12)],
    products: [
        .library(name: "Fastlane", targets: ["Fastlane"])
    ],
    dependencies: [
        .package(url: "https://github.com/kareman/SwiftShell", .upToNextMajor(from: "5.1.0"))
    ],
    targets: [
        .target(
            name: "Fastlane",
            dependencies: ["SwiftShell"],
            path: "./fastlane/swift",
            exclude: ["Actions.swift", "Plugins.swift", "main.swift", "formatting", "FastlaneSwiftRunner"]
        ),
    ],
    swiftLanguageVersions: [.v4]
)
 

```

**Comment by minuscorp** [comment]
That you'd need the Swift5 toolchain for the SPM users but I think most of them will have it. Nobody used SPM with Swift 4

**Comment by kikeenrique** [comment]
A sum up, after addressing reviewer comments and suggestions.

- FastlaneSwiftRunner.xcodeproj preserves code in swift 4 and deployment in macOS 10.12 
- Package.swift now requires swift-tools-version 5.0, to enforce deployment in macOS 10.12 (current CI passes)
- FastlaneSwiftRunner.xcodeproj now signs FastlaneRunner binary, required for M1.
- FastlaneSwiftRunner.xcodeproj _script phase_ for updating binary now is a _copy phase_ that signs binary.
- Swift project upgrade now handles modifications in FastlaneSwiftRunner.xcodeproj, which previously would requiere a reset (as @rogerluan [reproduced in his first review](https://github.com/fastlane/fastlane/pull/19555#pullrequestreview-819621259) ) .
- Fixed data race in FastlaneRunner implementing an Atomic variable based on os_unfair_lock_s.
- Added verbose option to allow output to be seen if needed when swift fastlane binary is launched.

I think it's in good shape, although missing some more testing.

Any other suggestions?
- I have one regarding M1 machines, as circleci nor GitHub does yet provide any. I would suggest asking [www.macstadium.com](https://www.macstadium.com/opensource/members) for a M1 machine to test or review PR as they host and also [support some different integrations](https://www.macstadium.com/tools), such as a [GitHub action](https://github.com/macstadium/orka-integrations/tree/master/GitHub).

**Comment by minuscorp** [comment]
Question, can you compile the SPM package in Swift 4 mode with the changed tools version?

**Comment by kikeenrique** [comment]
> Question, can you compile the SPM package in Swift 4 mode with the changed tools version?

Yes, it's possible. I've tested 2 options:
* Xcode project with SPM dependency. Builds with Swift version 4.
Screenshot 2021-12-15 at 10 03 41
Screenshot 2021-12-15 at 10 03 29

* Swift Package. For building, it's needed tools version 5.0 to enforce deployment for macOS 10.12. I wonder if there is any way to set deployment in version 4.0 because I didn't found any solution:
Screenshot 2021-12-15 at 10 12 31
Screenshot 2021-12-15 at 10 04 43

**Comment by minuscorp** [comment]
But I mean a just `swift build` with the Swift 4 toolchain, that would fail if I'm not wrong.

**Comment by minuscorp** [comment]
I have a solution for the SPM part to not to break current tool set but I need a day or two, I have a ton of work right now😞

**Comment by kikeenrique** [comment]
> But I mean a just swift build with the Swift 4 toolchain, that would fail if I'm not wrong.

 ```
Myexec$  cat Package.swift
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "fastlaneRunner",
    products: [
        .executable(name: "fastlaneRunner", targets: ["fastlaneRunner"])
    ],
    dependencies: [
        .package(url: "https://github.com/kikeenrique/fastlane/", .branchItem("18502"))
    ],
    targets: [
        .target(
            name: "fastlaneRunner",
            dependencies: ["Fastlane"],
            path: "Sources/Myexec"
        )
    ],
    swiftLanguageVersions: [4]

)
 Myexec$  swift build
error: the executable 'fastlaneRunner' requires macos 10.10, but depends on the product 'Fastlane' which requires macos 10.12; consider changing the executable 'fastlaneRunner' to require macos 10.12 or later, or the product 'Fastlane' to require macos 10.10 or earlier.
```

> I have a solution for the SPM part to not to break current tool set but I need a day or two, I have a ton of work right now😞

Do you have a hint? Maybe I can take a look.

**Comment by minuscorp** [comment]
Oh yeah, this is what I didn't wanted to happen. I'll try to make a PR to your fork during the weekend to preserve the old toolchain for a bit more.

**Comment by kikeenrique** [comment]
> Oh yeah, this is what I didn't wanted to happen. I'll try to make a PR to your fork during the weekend to preserve the old toolchain for a bit more.

To preserve swift-tools-version 4 and try to finish this PR, shall I go back to implement: 
1.  DispatchQueue for all
2. DispatchQueue for 10.10 until 10.12 and os_unfair_lock for newer than 10.12

Which one do you prefer?

**Comment by minuscorp** [comment]
I prefer 2. Just make a protocol so lock, unlock and creation of the lock are common for both versions and then encapsulate into a `@available(macOS, obsoleted: 10.12)` and the other one `@available(macOS, 10.12)`. Sorry I hadn't time to do this the past weekend 😔

**Comment by kikeenrique** [comment]
> I prefer 2. Just make a protocol so lock, unlock and creation of the lock are common for both versions and then encapsulate into a `@available(macOS, obsoleted: 10.12)` and the other one `@available(macOS, 10.12)`. Sorry I hadn't time to do this the past weekend 😔 . Use `OSSpinLock` for before 10.12 instead of `DispatchQueue`

Done. I've had a small fight 🥷with generics and protocols, but I guess I've achieved the main purpose.
Take a look. 
I hope 🤞this gets finally to and end🎻🎶.

File: fastlane/swift/Runner.swift [hunk 20]
```diff
@@ -65,14 +73,80 @@ class AtomicDictionary<Key: Hashable, Value> {
...
     private let dispatchGroup = DispatchGroup()
     private var returnValue: String? // lol, so safe
     private var currentlyExecutingCommand: RubyCommandable?
     private var shouldLeaveDispatchGroupDuringDisconnect = false
-    private var executeNext: AtomicDictionary<String, Bool> = AtomicDictionary()
+    private var executeNext: AtomicDictionaryProtocol = {
+        if #available(macOS 10.12, *) {
+            return UnfairLockAtomicDictionaryStringBool()
+        }
+        else {
```
Comment (rogerluan) [inline fastlane/swift/Runner.swift:146]:
```suggestion
        } else {
```

😅

**Comment by minuscorp** [comment]
Can I get permissions to push into this PR? @kikeenrique @joshdholtz so I can fix a bit how the Swift part is done and close this asap, I cannot do it from the suggestions part because is too much code to add.

**Comment by kikeenrique** [comment]
> Can I get permissions to push into this PR? @kikeenrique @joshdholtz so I can fix a bit how the Swift part is done and close this asap, I cannot do it from the suggestions part because is too much code to add.

I think you should have permission
Screenshot 2021-12-22 at 13 09 12

**Comment by minuscorp** [comment]
I'd need my personal laptop for this because the company one's is completely closed to connect to github, give time til' 5pm

**Comment by minuscorp** [comment]
Should be fine by now, it was pretty tricky because of generic protocols and specialization tables in Swift tbh, but it is working, we can use any kind of data we want for both locks and add more with just three lines of code, take a look @kikeenrique. Ready to merge on my side @joshdholtz.

**Review by minuscorp — APPROVED** [review]
🚀

**Comment by kikeenrique** [comment]
I'm sorry but it's still not ready to go. It crashes again.
Backtrace in text mode:
```
worker thread (2)#0	0x000000018aa1d9b8 in __pthread_kill ()
#1	0x000000018aa50eb0 in pthread_kill ()
#2	0x000000018a98e314 in abort ()
#3	0x000000018aa0db50 in abort_message ()
#4	0x000000018a9fef64 in demangling_terminate_handler() ()
#5	0x000000018a8f6140 in _objc_terminate() ()
#6	0x000000018aa0cee4 in std::__terminate(void (*)()) ()
#7	0x000000018aa0fc5c in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) ()
#8	0x000000018aa0fc08 in __cxa_throw ()
#9	0x000000018a8ed8dc in objc_exception_throw ()
#10	0x000000018ac2f1a0 in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#11	0x000000018aafc360 in ___forwarding___ ()
#12	0x000000018aafbbe0 in _CF_forwarding_prep_0 ()
#13	0x0000000197b46348 in Dictionary._Variant.subscript.getter ()
#14	0x000000010435d7dc in closure #1 in AtomicDictionary.get(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:118
#15	0x000000010435d818 in partial apply for closure #1 in AtomicDictionary.get(_:) ()
#16	0x000000010435cbac in SyncProtocol.sync<τ_0_0>(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:42
#17	0x000000010435d6e0 in AtomicDictionary.get(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:117
#18	0x000000010435e0bc in protocol witness for DictionaryProtocol.get(_:) in conformance AtomicDictionary<τ_0_0, τ_0_1> ()
#19	0x000000010435c31c in DictionaryProtocol.subscript.getter at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:24
#20	0x00000001042a9cac in implicit closure #1 in Runner.executeCommand(_:) ()
#21	0x00000001042ae604 in partial apply for implicit closure #1 in Runner.executeCommand(_:) ()
#22	0x00000001042a9cf8 in thunk for @escaping @callee_guaranteed () -> (@unowned Bool?, @error @owned Error) ()
#23	0x00000001042ae668 in partial apply for thunk for @escaping @callee_guaranteed () -> (@unowned Bool?, @error @owned Error) ()
#24	0x00000001042aab5c in closure #1 in memoizedClosure #1 <τ_0_0><τ_1_0>(_:) in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:64
#25	0x00000001042af368 in partial apply for closure #1 in memoizedClosure #1 <τ_0_0><τ_1_0>(_:) in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) ()
#26	0x00000001042aa0c0 in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:80
#27	0x00000001042a97ac in Runner.executeCommand(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:43
#28	0x000000010432ee44 in sh(command:log:errorCallback:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Fastlane.swift:9719
#29	0x000000010429f3cc in Fastfile.customLane() at /Users/enrgar/Developer/tools/fastlane-test/fastlane/Fastfile.swift:15
#30	0x000000010429f410 in @objc Fastfile.customLane() ()
#31	0x0000000104299c84 in static LaneFile.runLane(from:named:with:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/LaneFileProtocol.swift:141
#32	0x00000001042b1b50 in MainProcess.connectToFastlaneAndRunLane() at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/main.swift:23
#33	0x00000001042b1bf0 in @objc MainProcess.connectToFastlaneAndRunLane() ()
#34	0x000000018b9e82e8 in __NSThread__start__ ()
#35	0x000000018aa51240 in _pthread_start ()
Thread#0	0x000000018ab9c1b8 in __exceptionPreprocess ()
#1	0x000000018a8ed7b8 in objc_exception_throw ()
#2	0x000000018ac2f1a0 in -[NSObject(NSObject) doesNotRecognizeSelector:] ()
#3	0x000000018aafc360 in ___forwarding___ ()
#4	0x000000018aafbbe0 in _CF_forwarding_prep_0 ()
#5	0x0000000197b46348 in Dictionary._Variant.subscript.getter ()
#6	0x000000010435d7dc in closure #1 in AtomicDictionary.get(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:118
#7	0x000000010435d818 in partial apply for closure #1 in AtomicDictionary.get(_:) ()
#8	0x000000010435cbac in SyncProtocol.sync<τ_0_0>(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:42
#9	0x000000010435d6e0 in AtomicDictionary.get(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:117
#10	0x000000010435e0bc in protocol witness for DictionaryProtocol.get(_:) in conformance AtomicDictionary<τ_0_0, τ_0_1> ()
#11	0x000000010435c31c in DictionaryProtocol.subscript.getter at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Atomic.swift:24
#12	0x00000001042a9cac in implicit closure #1 in Runner.executeCommand(_:) ()
#13	0x00000001042ae604 in partial apply for implicit closure #1 in Runner.executeCommand(_:) ()
#14	0x00000001042a9cf8 in thunk for @escaping @callee_guaranteed () -> (@unowned Bool?, @error @owned Error) ()
#15	0x00000001042ae668 in partial apply for thunk for @escaping @callee_guaranteed () -> (@unowned Bool?, @error @owned Error) ()
#16	0x00000001042aab5c in closure #1 in memoizedClosure #1 <τ_0_0><τ_1_0>(_:) in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:64
#17	0x00000001042af368 in partial apply for closure #1 in memoizedClosure #1 <τ_0_0><τ_1_0>(_:) in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) ()
#18	0x00000001042aa0c0 in static Runner.waitWithPolling<τ_0_0>(_:toEventually:timeout:pollingInterval:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:80
#19	0x00000001042a97ac in Runner.executeCommand(_:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Runner.swift:43
#20	0x000000010432ee44 in sh(command:log:errorCallback:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/Fastlane.swift:9719
#21	0x000000010429f3cc in Fastfile.customLane() at /Users/enrgar/Developer/tools/fastlane-test/fastlane/Fastfile.swift:15
#22	0x000000010429f410 in @objc Fastfile.customLane() ()
#23	0x0000000104299c84 in static LaneFile.runLane(from:named:with:) at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/LaneFileProtocol.swift:141
#24	0x00000001042b1b50 in MainProcess.connectToFastlaneAndRunLane() at /Users/enrgar/Developer/tools/fastlane-test/fastlane/swift/main.swift:23
#25	0x00000001042b1bf0 in @objc MainProcess.connectToFastlaneAndRunLane() ()
#26	0x000000018b9e82e8 in __NSThread__start__ ()
#27	0x000000018aa51240 in _pthread_start ()
#28	0x000000018aa4c024 in thread_start ()

```
Backtrace in picture mode:

Screenshot 2021-12-23 at 22 30 55

I've also added the new Atomic.swift file to the upgrade_manifest.json.  In a future PR I would like to try to add more tests to catch upgrade problems like this.

**Comment by minuscorp** [comment]
Does it run through the locks correctly? Just for checking, in x86_64 it works well in every situation I've tested, still no M1  😓

**Comment by minuscorp** [comment]
One last try before Christmas, specializing protocol extensions don't care to subclasses that match the requirements, as Swift works nowadays, when they retire Self protocol restrictions it'd be easy, again, it'll be not available for us for a time I guess 🤷‍♂️ . Take a look and tell me it finally works fine!

**Comment by kikeenrique** [comment]
Latest commit fixed the crash. 🎉

**Comment by minuscorp** [comment]
Not the implementation, I wanted but what I could with the time I had, I'll try to fix the code in a better way 😅

**Comment by kikeenrique** [comment]
@rogerluan @joshdholtz Although I can see a 🔴_Merging is blocked_ message due to requested changes, I think everything is ready to be merged at least on my side and @minuscorp, so whenever you're ready it can go to 🚀🌕.

**Comment by minuscorp** [comment]
I've made a bit of cleanup of pretty hacky code. More readable and extensible for other types. Approved but test it beforehand.

**Comment by kikeenrique** [comment]
> I've made a bit of cleanup of pretty hacky code. More readable and extensible for other types. Approved but test it beforehand.

Related to testing, I've created another [PR 19755](https://github.com/fastlane/fastlane/pull/19755) with the test I've using to test this PR.
I've added it in other PR in order to discuss it independently and don't add more delay in this PR.

**Comment by Robin-Gupta1** [comment]
Hey guys can we please fix this issue as it is causing a lot of problems for us while working with Fastlane swift? We have waited for more than 3 months for this issue to be resolved and now this PR is sitting ideal for more than a week without any activites. Please help us.

**Review by rogerluan — APPROVED** [review]
Code LGTM :)

**Comment by hiragram** [comment]
👀 🚀 ❓

**Comment by khaptonstall** [comment]
@kikeenrique My team just started running into issues that should be resolved once this is released, thanks for submitting a fix! It looks like this has been open for quite some time. Is there an estimate on when this might get merged? What's currently blocking it?

**Comment by kikeenrique** [comment]
> @kikeenrique My team just started running into issues that should be resolved once this is released, thanks for submitting a fix! It looks like this has been open for quite some time. Is there an estimate on when this might get merged? What's currently blocking it?

At this point I think is just a matter of official maintainers availability to merge it (we all are volunteers with a life 🌱), as it has already been approved by reviewers.

**Comment by roisg** [comment]
Is there an approximate timeline for this to be merged and released? Does anyone know how much time would usually take for an approved request to be released?

Thank you very much for the great effort.

**Comment by dgilbert-foreflight** [comment]
👀 🚀 ❓

**Comment by joshdholtz** [comment]
Getting this merged and released in new version tonight!

**Review by joshdholtz — APPROVED** [review]
This looks amazing! Great work, team 🥰  I will get this out in tonight's release 💪
