### PR TITLE
[xcodes] fix issue where `xcodes` action wouldn't accept beta versions of Xcode

### LINKED ISSUE #21369: xcodes does not allow "15.0 Beta 5" as version
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
xcodes does not allow "15.0 Beta 2" as version

##### Command executed
```ruby
xcodes(
  version: "15.0 Beta 2",
  select_for_current_build_only: true
)
```

##### Complete output when running fastlane, including the stack trace and command used

[✔] 🚀 
+---------------------------+---------+---------------------------------------------------------------------------+
|                                                  Used plugins                                                   |
+---------------------------+---------+---------------------------------------------------------------------------+
| Plugin                    | Version | Action                                                                    |
+---------------------------+---------+---------------------------------------------------------------------------+
| fastlane-plugin-appcenter | 2.1.0   | appcenter_codepush_release_react, appcenter_fetch_devices,                |
|                           |         | appcenter_fetch_version_number, appcenter_upload                          |
| fastlane-plugin-sentry    | 1.15.0  | sentry_check_cli_installed, sentry_create_deploy, sentry_create_release,  |
|                           |         | sentry_finalize_release, sentry_set_commits, sentry_upload_dif,           |
|                           |         | sentry_upload_dsym, sentry_upload_file, sentry_upload_proguard,           |
|                           |         | sentry_upload_sourcemap                                                   |
| fastlane-plugin-lizard    | 1.3.3   | lizard                                                                    |
+---------------------------+---------+---------------------------------------------------------------------------+

[11:21:48]: 15.0 Beta 2
[11:21:48]: Error setting value '15.0 Beta 2' for option 'version'
[11:21:48]: You passed invalid parameters to 'xcodes'.
[11:21:48]: Check out the error below and available options by running `fastlane action xcodes`

```[!] The requirement '15.0 Beta 2' is not a valid RubyGems style requirement```

### Environment

</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.213.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-appcenter | 2.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry    | 1.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-lizard    | 1.3.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.7.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.4        |
| multipart-post                  | 2.3.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.7        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| simctl                          | 1.6.10       |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.5.2        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-apis-androidpublisher_v3 | 0.42.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.1        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.768.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.173.0      |
| aws-sdk-kms                     | 1.64.0       |
| aws-sdk-s3                      | 1.122.0      |
| set                             | 1.0.2        |
| bundler                         | 2.4.15       |
| jwt                             | 2.7.1        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.12.1       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.2        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
| fastlane-plugin-appcenter       | 2.1.0        |
| csv                             | 3.2.5        |
| fastlane-plugin-sentry          | 1.15.0       |
| coderay                         | 1.1.3        |
| method_source                   | 1.0.0        |
| pry                             | 0.14.2       |
| fastlane-plugin-lizard          | 1.3.3        |
</details>

### PR DESCRIPTION
**Pull request by apps4everyone**
Checklist

- [x]  I've run bundle exec rspec from the root directory to see all new and existing tests pass
- [x]  I've followed the fastlane code style and run bundle exec rubocop -a to ensure the code style is valid
- [x]  I see several green ci/circleci builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x]  I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x]  I've updated the documentation if necessary.

Motivation and Context

Try to fix #21369 xcodes does not allow "15.0 Beta 5" as version.

### CODE REVIEW

**Comment by apps4everyone** [comment]
Hey, sorry for asking directly for some help and review about the issue https://github.com/fastlane/fastlane/issues/21369 With `xcodes` it is currently not possible to test any Beta version  of Xcode.

@snatchev @milch @ainame @joshdholtz maybe some PR feedback would be great. thx

**Comment by milch** [comment]
I see that the problem is that we added the `xcodes` action after the previous Xcode beta period, so this is probably the first time anyone has tried to use a beta version with it. It seems that at the time the assumption was made that `xcodes` would accept ruby-style version strings, but it looks like it uses a more complex pattern that probably doesn't make sense to replicate here: https://github.com/XcodesOrg/xcodes/blob/main/Sources/XcodesKit/Version%2BXcode.swift#L22

File: fastlane/lib/fastlane/helper/xcodes_helper.rb [hunk 1]
```diff
@@ -18,9 +18,6 @@ def self.find_xcodes_binary_path
       module Verify
         def self.requirement(req)
           UI.user_error!("Version must be specified") if req.nil? || req.to_s.strip.size == 0
```
Comment (milch) [inline fastlane/lib/fastlane/helper/xcodes_helper.rb:20]: The `requirement` method was only used in this one place: the `verify_block` in the `xcodes` action, as far as I can tell. I think if we are to remove it, it would probably make sense to remove the whole thing and have it as an inline block in the action's ruby file, which matches other `verify_block` methods. This one was probably pulled out because it was a bit longer and using a rescue block, but generally 1-2 line verification methods are inline.

**Review by milch — COMMENTED** [review]
Thank you for your contribution! 🚀

File: fastlane/lib/fastlane/helper/xcodes_helper.rb (hunk 1 above)
Comment (apps4everyone) [reply fastlane/lib/fastlane/helper/xcodes_helper.rb:20]: it is still used in two places, therefore I left as it was for reuse

Screenshot 2023-08-05 at 21 23 04

Comment (milch) [reply fastlane/lib/fastlane/helper/xcodes_helper.rb:20]: Hmm, I see. So shouldn't `xcversion` continue to use the old validation?

Comment (apps4everyone) [reply fastlane/lib/fastlane/helper/xcodes_helper.rb:20]: I would rather let xcodes or xcversion let decide to throw an error, fastlane should only pre check for empty strings

**Comment by apps4everyone** [comment]
@rogerluan maybe you have 5 mins? What's missing or what I can do to get here more feedback? Thank you

File: fastlane/lib/fastlane/helper/xcodes_helper.rb (hunk 1 above)
Comment (rogerluan) [reply fastlane/lib/fastlane/helper/xcodes_helper.rb:20]: I think I agree with @apps4everyone, the underlying tools will error out if the user enter an invalid version. I think that checking just for string validity (empty/whitespaces) is what makes more sense here 👌

**Review by rogerluan — APPROVED** [review]
Good catch @apps4everyone, thanks for fixing this 🙏 

I was the author of the `xcodes` action and I agree this is a better approach 🙌 

This PR LGTM

**Comment by apps4everyone** [comment]
Thx for the review @rogerluan, is there any release planned the next days? Would like to test with Xcode 15 before the release next weeks. thx

**Comment by rogerluan** [comment]
No planned release for the time being. You can still test it by modifying your Gemfile, e.g.:

```ruby
gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'master'
```

And running `bundle install` to apply the changes.

**Comment by apps4everyone** [comment]
thx, will test with that

**Comment by apps4everyone** [comment]
work's with master 🎉
