### PR TITLE
Escape HipChat room name

### LINKED ISSUE #10178: HipChat room name not being escaped
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
If you try to send a message to a HipChat room using who includes characters in the name that need to be escaped the action fails. Example:

```ruby
hipchat(
  message: "All test passed!",
  channel: "Room name",
  success: true
)
```

##### Complete output when running fastlane, including the stack trace and command used
```
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios test |
+------------------+----------+
[16:02:50]: bad URI(is not URI?): https://api.hipchat.com/v2/room/Room name/notification

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | hipchat                             | 0           |
+------+-------------------------------------+-------------+

[16:02:50]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
~/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:67:in `split': [!] bad URI(is not URI?): https://api.hipchat.com/v2/room/Room name/notification (URI::InvalidURIError)
    from ~/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
    from ~/.rbenv/versions/2.4.0/lib/ruby/2.4.0/uri/common.rb:231:in `parse'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/hipchat.rb:61:in `run'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
    from Fastfile:30:in `block (2 levels) in parsing_binding'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane.rb:33:in `call'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
    from ~/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.54.3/bin/fastlane:20:in `<top (required)>'
    from ~/.rbenv/versions/2.4.0/bin/fastlane:22:in `load'
    from ~/.rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-08-29**
</details>

### PR DESCRIPTION
**Pull request by tkanzakic**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes #10178 

### Description
The channel is being escaped before building the HipChat API URL for sending message to a specific user, but this was not true for messages sent to rooms.

### CODE REVIEW

**Comment by tkanzakic** [comment]
I signed it!

File: fastlane/lib/fastlane/actions/hipchat.rb [hunk 1]
```diff
@@ -46,19 +46,19 @@ def self.run(options)
           end
         else
           ########## running on V2 ##########
+          escaped_channel = URI.unescape(channel) == channel ? URI.escape(channel) : channel
```
Comment (ohayon) [inline fastlane/lib/fastlane/actions/hipchat.rb]: Do you think we could simply use `channel.shellescape`?

**Review by ohayon — COMMENTED** [review]
Hey @tkanzakic! This is a great change! Thanks for the contribution. Just one comment above to see if we can make that line a bit more simple?

Thanks again! 🚀

File: fastlane/lib/fastlane/actions/hipchat.rb (hunk 1 above)
Comment (tkanzakic) [reply fastlane/lib/fastlane/actions/hipchat.rb]: Hi @ohayon, many thanks for your review, it is a big pleasure for me to contribute to the project. 

About your comment, `channel.shellescape` encode the string to be a valid shell resource and in this case we need a string encoded to be a valid URL resource, in "code words":

```ruby
require 'shellwords'
require 'uri'

channel = "Room name"
print(channel.shellescape) # prints "Room\\ name"
print(URI.escape(channel)) # prints "Room%20name"
```

The complexity of the line is because encoding an already encoded string produce a new value:

```ruby
print(URI.escape(URI.escape(channel))) # prints "Room%2520name"
```

for that reason we first verify if the `channel` string is already encoded or not.

Comment (ohayon) [reply fastlane/lib/fastlane/actions/hipchat.rb]: Got it! Thanks for the explanation, that makes good sense. Do you think you could just add a little comment to make it a bit more clear and then we can get this merged in? 🚀  🐙

Comment (tkanzakic) [reply fastlane/lib/fastlane/actions/hipchat.rb]: Done!

**Review by ohayon — APPROVED** [review]

**Comment by ohayon** [comment]
Thanks @tkanzakic !! Great first contribution! Welcome to the _fastlane_ community! 🚀

**Comment by tkanzakic** [comment]
@ohayon awesome, thanks!
