### PR TITLE
[match] fix recursion when MATCH_PASSWORD is not set

### LINKED ISSUE #17524: [match] Endless loop on CI when MATCH_PASSWORD cannot be found
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Screen Shot 2020-10-29 at 1 20 19 PM

##### Command executed
   match(type: "appstore",
          app_identifier: app_identifier,
          generate_apple_certs: true,
          force: true,
          profile_name: profile_name)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [13:14:05]: Neither the MATCH_PASSWORD environment variable nor the local keychain contained a password.
[13:14:05]: Bailing out instead of asking for a password, since this is non-interactive mode.
[13:14:05]: Couldn't decrypt the repo, please make sure you enter the right password!
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain. </pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.0 (Apple Git-122.2)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.165.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| signet                    | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| nanaimo                   | 0.3.0        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.19.0       |
| public_suffix             | 4.0.6        |
| tty-screen                | 0.8.1        |
| babosa                    | 1.0.4        |
| excon                     | 0.78.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.1.0        |
| faraday-cookie_jar        | 0.0.7        |
| fastimage                 | 2.2.0        |
| json                      | 2.3.1        |
| dotenv                    | 2.7.6        |
| jwt                       | 2.2.2        |
| declarative               | 0.0.20       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.14.0       |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.4.0        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.2.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-partitions            | 1.388.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.1       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #17524

### Description

From my understanding, looks like the recursive call is there to retry in case the password was present in Keychain, but outdated/wrong. However, it should only retry if there's a password to be retried 🤓 in this case, in the `MATCH_PASSWORD` env var.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-fix-match-recursion"
```

### CODE REVIEW

File: match/lib/match/encryption/openssl.rb [hunk 1]
```diff
@@ -50,7 +50,8 @@ def decrypt_files
             UI.error("Couldn't decrypt the repo, please make sure you enter the right password!")
             UI.user_error!("Invalid password passed via 'MATCH_PASSWORD'") if ENV["MATCH_PASSWORD"]
             clear_password
-            self.decrypt_files # call itself
+            # After clearing the password from Keychain, retry if MATCH_PASSWORD is set
+            self.decrypt_files if ENV["MATCH_PASSWORD"]
```
Comment (joshdholtz) [inline match/lib/match/encryption/openssl.rb:54]: This _does_ seem like it would work here but I think catching it here is more about an incorrect password 🤔 

I think we want instead want to see fetch the password outside of begin/rescue so the `UI.user_error!` when in a non-interactive doesn’t get caught here

1. I would also renamed `def password` to `def fetch_password!` here - https://github.com/fastlane/fastlane/blob/master/match/lib/match/encryption/openssl.rb#L86-L105
  - The exclamation point being important since this can throw when in non-interative
2. At the start of the `decrypt_files` method, we would then to `password = fetch_password!` so that I can throw if non-interactive before getting into the begin/rescue and causing recursion 

Let me know if you have any questions!

**Review by joshdholtz — CHANGES_REQUESTED** [review]
I think this works but got some ideas to make this code just clearer in general 😊

File: match/lib/match/encryption/openssl.rb (hunk 1 above)
Comment (rogerluan) [reply match/lib/match/encryption/openssl.rb:54]: Great feedback! I'll pick this up again when I can! 🙏

Comment (rogerluan) [reply match/lib/match/encryption/openssl.rb]: Addressed @joshdholtz , let me know if that's what you pictured 😊

**Comment by rogerluan** [comment]
Specs failed on the previous commit, idk what happened cuz everything passes here, but I just merged latest master into this branch to see if it fails again 🤔

**Comment by rogerluan** [comment]
Specs are still failing 😕 I thought [this](https://github.com/fastlane/fastlane/pull/17738#issuecomment-739296837) had happened in this branch as well, but I just ran `bundle exec rspec` and it didn't point out any other failures. 😞

**Comment by rogerluan** [comment]
I don't have visibility into what's failing, I need help to solve the failing specs 😬

File: match/lib/match/encryption/openssl.rb [hunk 2]
```diff
@@ -50,7 +52,7 @@ def decrypt_files
             UI.error("Couldn't decrypt the repo, please make sure you enter the right password!")
             UI.user_error!("Invalid password passed via 'MATCH_PASSWORD'") if ENV["MATCH_PASSWORD"]
             clear_password
-            self.decrypt_files # call itself
+            self.decrypt_files
```
Comment (rogerluan) [inline match/lib/match/encryption/openssl.rb:55]:
```suggestion
            self.decrypt_files # Call itself
```

**Comment by joshdholtz** [comment]
@googlebot I consent.

File: match/spec/commands_generator_spec.rb [hunk 3]
```diff
@@ -89,6 +89,7 @@ def expect_githelper_clone_with(git_url, shallow_clone, git_branch)
     end
 
     it "can use the git_url short flag from tool options" do
+      stub_const('ENV', {'MATCH_PASSWORD' => ''})
```
Comment (rogerluan) [inline match/spec/commands_generator_spec.rb]: @joshdholtz could you tell why this was error'ing in CI and not locally in my machine when running `bundle exec rspec`? And how did you come to this fix? 🤯 😅

Comment (joshdholtz) [reply match/spec/commands_generator_spec.rb]: @rogerluan CircleCI gets really weird sometimes and just needs a restart 🤷‍♂️

**Review by joshdholtz — APPROVED** [review]
Looks good! Thanks for making this fix ❤️
