### PR TITLE
[deliver] add retry when fetching edit app version and edit app info

### LINKED ISSUE #16991: Cannot update languages - could not find an editable version for 'IOS'
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

1. Started with `fastlane deliver init` for new project.
2. After `fastlane deliver --force` and partial progress I gets:

**[!] Cannot update languages - could not find an editable version for 'IOS'**

Let's a full log below:
```

[17:47:07]: Login to App Store Connect (...)
[17:47:10]: Login successful

+--------------------------------------+---------------------------+
|                     deliver 2.154.0 Summary                      |
+--------------------------------------+---------------------------+
| force                                | true                      |
| screenshots_path                     | ./fastlane/screenshots    |
| metadata_path                        | ./fastlane/metadata       |
| username                             | ... |
| app_identifier                       | ...     |
| platform                             | ios                       |
| edit_live                            | false                     |
| use_live_version                     | false                     |
| skip_binary_upload                   | false                     |
| skip_screenshots                     | false                     |
| skip_metadata                        | false                     |
| skip_app_version_update              | false                     |
| overwrite_screenshots                | false                     |
| submit_for_review                    | false                     |
| reject_if_possible                   | false                     |
| automatic_release                    | false                     |
| phased_release                       | false                     |
| reset_ratings                        | false                     |
| team_id                              | ...                   |
| dev_portal_team_id                   | ...                |
| run_precheck_before_submit           | true                      |
| precheck_default_rule_level          | warn                      |
| ignore_language_directory_validation | false                     |
| precheck_include_in_app_purchases    | true                      |
+--------------------------------------+---------------------------+

[17:47:15]: Loading './fastlane/metadata/en-US/description.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/keywords.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/support_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/name.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[17:47:15]: Loading './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'...
[17:47:15]: Loading './fastlane/metadata/copyright.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_category.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:47:15]: Loading './fastlane/metadata/review_information/notes.txt'...

[!] Cannot update languages - could not find an editable version for 'IOS'
```

AppStoreConnect app language is en-US.

Thanks in advance,
Maciej

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
</pre>
</details>

### Environment

<details>
  <pre> 
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.154.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.4.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.9.5        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-core         | 1.4.1        |
| google-cloud-storage      | 1.25.0       |
| CFPropertyList            | 3.0.2        |
| excon                     | 0.76.0       |
| fastimage                 | 2.2.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| declarative               | 0.0.20       |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.0.1        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| google-cloud-env          | 1.3.3        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| emoji_regex               | 3.0.0        |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.1        |
| aws-partitions            | 1.350.0      |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.104.3      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.75.0       |
| forwardable               | 1.3.1        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.4.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-08-04**

</pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #16991

### Description
- Add 5 retries (with 10 second sleep) to fetching edit app version and edit app info
- Big diff in tests is because of indenting a whole section 🤷‍♂️ 

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-deliver-add-retry-fetching-edit-versions"
```

### CODE REVIEW

**Review by rogerluan — APPROVED** [review]
Logic looks good 👍 
Just a quick question: there are other places in fastlane where we retry after an ever-increasing amount of time (e.g. retry 5 times, first waiting for 5 seconds, then 10, then 20, etc... - fake example values). Why wasn't this same approach used here? (I don't think it's needed, but I'm just wondering why in some places we'd need that increasing timeout)

**Comment by joshdholtz** [comment]
@rogerluan We could totally do that here if we wanted but my gut here is that just one try of 10 seconds will be enough. This probably works on the web because using users interfaces are slow. We are doing things programmatically so we are probably too fast for the API 🤷‍♂️

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

File: deliver/lib/deliver/options.rb [hunk 1]
```diff
@@ -129,7 +145,7 @@ def self.available_options
                                      default_value: false),
         FastlaneCore::ConfigItem.new(key: :skip_app_version_update,
                                      env_name: "DELIVER_SKIP_APP_VERSION_UPDATE",
-                                     description: "Don't update app version for submission",
+                                     description: "Don’t create or update the app version that is being prepared for submission",
```
Comment (rogerluan) [inline deliver/lib/deliver/options.rb:148]: 👌

**Review by rogerluan — APPROVED** [review]

File: deliver/lib/deliver/options.rb [hunk 2]
```diff
@@ -12,6 +12,22 @@ def self.available_options
...
+                                     env_name: "DELIVER_API_KEY_PATH",
+                                     description: "Path to your App Store Connect API key JSON file",
+                                     optional: true,
+                                     conflicting_options: [:username],
+                                     verify_block: proc do |value|
+                                       UI.user_error!("Couldn't find API key JSON file at path '#{value}'") unless File.exist?(value)
+                                     end),
+        FastlaneCore::ConfigItem.new(key: :api_key,
+                                     env_name: "DELIVER_API_KEY",
+                                     description: "Path to your App Store Connect API key JSON file",
```
Comment (rogerluan) [inline deliver/lib/deliver/options.rb:25]:
```suggestion
                                     description: "Your App Store Connect API key",
```

This

**Review by rogerluan — CHANGES_REQUESTED** [review]

File: deliver/lib/deliver/options.rb (hunk 2 above)
Comment (joshdholtz) [reply deliver/lib/deliver/options.rb:25]: Ah, good catch!
