### PR TITLE
Looking for a member by email doesn't work if we only have AppleId

### LINKED ISSUE #9973: pilot find/remove fails with "undefined method `admin?' for nil:NilClass"
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My iTunes Connect account has an `App Manager` role, when I try to use pilot to manage testers, it always fails with the same error:

>PS: I can use this account to manage (search/add/remove) my testers on the iTunes Connect Web, and that's what I do all the time. 

The command I use:

```
fastlane pilot find someont@test.com -a com.xxx.xxx -u <my account>

or

fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account>
```

And the error message:

```
undefined method `admin?' for nil:NilClass

[!] Some operations failed: undefined method `admin?' for nil:NilClass
```

The `--capture_output` argument seems doesn't exist:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --capture_output

invalid option: --capture_output
```

So I use `--verbose` option:

```
fastlane pilot remove someont@test.com -a com.xxx.xxx -u <my account> --verbose
```

And the verbose output is here:

```
ERROR [2017-08-07 09:54:39.09]: undefined method `admin?' for nil:NilClass
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: undefined method `admin?' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.51.0.beta.20170807010003/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version                    | Update-Status |
| -------- | -------------------------- | ------------- |
| fastlane | 2.51.0.beta.20170807010003 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-08-07**
</details>

Thank you very much for any help!

### PR DESCRIPTION
**Pull request by taquitos**
There is a very good chance this fixes #9973 
We've been mostly using client.user string, which is a "username" (AppleID), but... usernames could be email or non-email. You can no longer create a username that isn't an email, but for a number of years, you could. 
This means, if you search for a member using the currently logged-in user, you'd be searching using an AppleID, so if you compare AppleID to email, it can fail. 
Now, we hold both the AppleID and the email address associated with it.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Pilot::TesterManager Manages adding/removing/displaying testers when app manager asks to create new tester in the default group creates a new tester and adds it to the default group | <a href='https://github.com/fastlane/fastlane/blob/4436dea907a97898e4af02c2457070a5871b0d96/./pilot/spec/tester_manager_spec.rb'>tester_manager_spec.rb</a>|
Pilot::TesterManager Manages adding/removing/displaying testers when admin asks to create new tester in the default group creates a new tester and adds it to the default group | <a href='https://github.com/fastlane/fastlane/blob/4436dea907a97898e4af02c2457070a5871b0d96/./pilot/spec/tester_manager_spec.rb'>tester_manager_spec.rb</a>|
Pilot::TesterManager Manages adding/removing/displaying testers when asked to add an existing internal tester to a specific existing custom group adds the tester to the custom group | <a href='https://github.com/fastlane/fastlane/blob/4436dea907a97898e4af02c2457070a5871b0d96/./pilot/spec/tester_manager_spec.rb'>tester_manager_spec.rb</a>|
Pilot::TesterManager Manages adding/removing/displaying testers when external tester is removed without providing app removes the tester without error | <a href='https://github.com/fastlane/fastlane/blob/4436dea907a97898e4af02c2457070a5871b0d96/./pilot/spec/tester_manager_spec.rb'>tester_manager_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by taquitos** [comment]
Thank you @fastlane-bot-helper, I don't know how I missed this ❤️ ❤️ ❤️

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Tests have failed, see below for more information.</td>
    </tr>
  </tbody>
</table>

### Tests: 

Name | File|
--- | ---|
Fastlane Fastlane::FastFile Unlock keychain Integration set default keychain | <a href='https://github.com/fastlane/fastlane/blob/114afe7451c7b79dda24bd483741765bebf82f02/./fastlane/spec/actions_specs/unlock_keychain_spec.rb'>unlock_keychain_spec.rb</a>|


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: pilot/lib/pilot/tester_manager.rb [hunk 1]
```diff
@@ -126,8 +127,20 @@ def find_app_tester(email: nil, app: nil)
...
     end
 
+    def find_current_user
+      current_user_email = Spaceship::Tunes.client.user_email
+      current_user_apple_id = Spaceship::Tunes.client.user
+
+      current_user = Spaceship::Members.find(current_user_email)
+      unless current_user
+        UI.user_error!("Unable to find a member for AppleID: #{current_user_apple_id}, email: #{current_user_email}")
+        return nil
```
Comment (ohayon) [inline pilot/lib/pilot/tester_manager.rb]: I think this `return` is superfluous because the `user_error!` is going to bail out of this method. ⛵️

**Review by ohayon — DISMISSED** [review]
Looks great! Just one little comment about a `return` statement, but otherwise 💯

File: pilot/lib/pilot/tester_manager.rb (hunk 1 above)
Comment (taquitos) [inline pilot/lib/pilot/tester_manager.rb]: I agree, my thinking is: "What if we inject a different implementation that doesn't actually cause us to bail?" in that case, I'd rather signal my intention and make sure nothing else runs... just in case. What do you think? Is that overkill?

Comment (ohayon) [inline pilot/lib/pilot/tester_manager.rb]: Eh... mixed feelings, I think the likelihood of us changing the implementation of `user_error` to not crash is slim to none, that being said, anything is possible! So I could be convinced either way 🤷‍♂️

**Review by ohayon — APPROVED** [review]
UGH!!!! I HAVE TO APPROVE THIS AGAIN! :trollface:
