### PR TITLE
Fix duplicate output in CommandExecutor.execute() when command fails

### LINKED ISSUE #29550: Duplicate output in CommandExecutor.execute() when command fails
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
CommandExecutor.execute() prints full command output twice when status code != 0 and print_all argument set to true.

It pollutes logs making `grep` and manual search for an error rows harder.

In particular, _run_tests_ action calls `execute(print_all: true, ...)` under the hood. As result, an extra copy of xcodebuild command output being printed, and it is tend to be large text.

De-duplication logic seems to be common for all commands. We don't have to print output twice on error in general.

##### Command executed

As simple example you may declare:
```ruby
lane :debug_output_duplication do
  FastlaneCore::CommandExecutor.execute(
    command: 'echo "potentially large output"; exit 42',
    print_all: true
  )
end
```

And call:
```sh
bundle exec fastlane debug_output_duplication
```

##### Command output

Notice doubled `potentially large output`:
```sh
[✔] 🚀
+--------------------------------------------------------------------------+
|                               Used plugins                               |
+-----------------------------+---------+----------------------------------+
| Plugin                      | Version | Action                           |
+-----------------------------+---------+----------------------------------+
| fastlane-plugin-ruby        | 0.1.3   | rspec, rubocop                   |
| fastlane-plugin-clubmate    | 0.1.0   | clubmate                         |
| fastlane-plugin-slack_train | 0.2.0   | slack_train, slack_train_crash,  |
|                             |         | slack_train_start                |
+-----------------------------+---------+----------------------------------+

[13:58:27]: Driving the lane 'debug_output_duplication' 🚀
[13:58:27]: $ echo "potentially large output"; exit 42
[13:58:27]: ▸ potentially large output
potentially large output
[13:58:27]: Exit status: 42
[13:58:27]: -------------------------------
[13:58:27]: --- Step: slack_train_crash ---
[13:58:27]: -------------------------------
+------------------------------------------+
|               Lane Context               |
+---------------+--------------------------+
| PLATFORM_NAME |                          |
| LANE_NAME     | debug_output_duplication |
+---------------+--------------------------+
[13:58:28]: Called from Fastfile at line 14
[13:58:28]: ```
[13:58:28]:     12:
[13:58:28]:     13:	lane :debug_output_duplication do
[13:58:28]:  => 14:	  FastlaneCore::CommandExecutor.execute(
[13:58:28]:     15:	    command: 'echo "potentially large output"; exit 42',
[13:58:28]:     16:	    print_all: true
[13:58:28]: ```
[13:58:28]: Exit status: 42

+----------------------------------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | slack_train_crash | 0           |
+------+-------------------+-------------+

[13:58:28]: fastlane finished with errors

[!] Exit status: 42
```

### PR DESCRIPTION
**Pull request by amidaleet**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves [29550](https://github.com/fastlane/fastlane/issues/29550)

The `run_tests` action calls `execute(print_all: true, ...)`. And `execute()` is always printing full command output if status code is unsuccessful.
It adds large amount of unnecessary duplicated rows into logs, xcodebuild output is huge.

De-duplication logic seems to be common for all commands. We don't have to print output twice on error in general.

### Description

Wrapped output print in simple unless condition at `FastlaneCore::CommandExecutor.execute()`.
Checks if output was printed from code above.

### Testing Steps

Run commands like:
```ruby
FastlaneCore::CommandExecutor.execute(command: 'echo "potentially large output"; exit 42', print_all: true)
FastlaneCore::CommandExecutor.execute(command: 'echo "potentially large output"; exit 42', print_all: false)

FastlaneCore::CommandExecutor.execute(command: 'echo "potentially large output"; exit 0', print_all: true)
FastlaneCore::CommandExecutor.execute(command: 'echo "potentially large output"; exit 0', print_all: false)
```

### CODE REVIEW

**Comment by amidaleet** [comment]
Fixed error block call, rebased branch

**Comment by amidaleet** [comment]
Covered `puts(o)` and `error` block behaviour with new tests.

As PR have not been reviewed yet, pushed amend commit.

**Comment by amidaleet** [comment]
Finally, fixed tests on Windows running agent. Related use cases are seems to be covered now.

File: fastlane_core/spec/command_executor_spec.rb [hunk 1]
```diff
@@ -68,6 +72,77 @@
...
+        expect do
+          FastlaneCore::CommandExecutor.execute(
+            command: failing_command,
+            print_all: true,
+            error: proc do |_error_output| end
+          )
+        end.not_to output(failing_command_output).to_stdout
+      end
+
+      it "prints output to stdout ony ones when status != 0 and output was not already printed" do
```
Comment (revolter) [inline fastlane_core/spec/command_executor_spec.rb:90]:
```suggestion
      it "prints output to stdout only once when status != 0 and output was not already printed" do
```

File: fastlane_core/lib/fastlane_core/command_executor.rb [hunk 2]
```diff
@@ -77,8 +77,13 @@ def execute(command: nil, print_all: false, print_command: true, error: nil, pre
...
         # Exit status for build command, should be 0 if build succeeded
         if status != 0
-          o = output.join("\n")
-          puts(o) unless suppress_output # the user has the right to see the raw output
+          o = String.new
+          is_output_already_printed = print_all && !suppress_output
+          if !is_output_already_printed || !error.nil?
+            o = output.join("\n")
+          end
+          puts(o) unless is_output_already_printed
```
Comment (revolter) [inline fastlane_core/lib/fastlane_core/command_executor.rb:85]: Do you also think that this reads a bit easier:
```suggestion
          is_output_already_printed = print_all && !suppress_output
          if is_output_already_printed && error.nil?
            o = ""
          else
            o = output.join("\n")
          end
          puts(o)
```
? 🤔

**Review by revolter — COMMENTED** [review]
Kinda hard to wrap my head around the changes 🤔 Left a potential improvement question

File: fastlane_core/lib/fastlane_core/command_executor.rb (hunk 2 above)
Comment (amidaleet) [reply fastlane_core/lib/fastlane_core/command_executor.rb:85]: This change breaks behaviour. Will print output twice if is_output_already_printed is false while error block given.

Test `does not print output to stdout when status != 0 and output was already printed` covers this case.

Should add `unless` condition to last row:
```ruby
is_output_already_printed = print_all && !suppress_output
if is_output_already_printed && error.nil?
  o = ""
else
  o = output.join("\n")
end
puts(o) unless is_output_already_printed
```

Comment (revolter) [reply fastlane_core/lib/fastlane_core/command_executor.rb:85]: Oh, right, I removed that by mistake. I updated my suggestion. So, does it make sense to you as well?

Comment (amidaleet) [reply fastlane_core/lib/fastlane_core/command_executor.rb:85]: Yeah, will apply it

Should I commit each suggestion separately or collect all edits in 1 new commit?

Comment (revolter) [reply fastlane_core/lib/fastlane_core/command_executor.rb:85]: However you feel more comfortable, as we squash merge the PRs

**Review by revolter — CHANGES_REQUESTED** [review]
Sorry for insisting, but what still makes the logic a bit harder to read for me is the fact that the empty string is actually never used.

As such, could you please try replacing the entire contents of the wrapper `if` check with:
```ruby
is_output_already_printed = print_all && !suppress_output

o = output.join("\n")

puts(o) unless is_output_already_printed

UI.error("Exit status: #{status}")

if error
  error.call(o, status)
else
  UI.user_error!("Exit status: #{status}")
end
```
?

**Comment by amidaleet** [comment]
> Sorry for insisting, but what still makes the logic a bit harder to read for me is the fact that the empty string is actually never used.
> 
> As such, could you please try replacing the entire contents of the wrapper `if` check with:
> 
> ```ruby
> is_output_already_printed = print_all && !suppress_output
> 
> o = output.join("\n")
> 
> puts(o) unless is_output_already_printed
> 
> UI.error("Exit status: #{status}")
> 
> if error
>   error.call(o, status)
> else
>   UI.user_error!("Exit status: #{status}")
> end
> ```
> 
> ?

Fine by me

Actually computed `o = output.join("\n")` may not be used later (if error is nil), but it is unrelated to the Issue. I do not expect significant performance impact in real life scenario even for millions rows

I cannot see reason why output is Array and not String in the first place, `o` may be computed with `output.concat(line, "\n")` as command outputs. May be change that? Or this somehow worse?

**Comment by revolter** [comment]
> Actually computed `o = output.join("\n")` may not be used later (if error is nil), but it is unrelated to the Issue. I do not expect significant performance impact in real life scenario even for millions rows

True, but it was happening before these changes as well, and I feel like optimizing the code for the `join` to happen only when needed would make the code less readable, so I'd favor readability over performance in this case.

> I cannot see reason why output is Array and not String in the first place

I don't know either, and I didn't check the rest of the code.

> `o` may be computed with `output.concat(line, "\n")` as command outputs. May be change that? Or this somehow worse?

I would say to leave the concatenation as it is for this PR 🤔

**Comment by revolter** [comment]
I see what you mean with the `output` being an array, and I still think that that change pollutes this PR too much.

And, personally, I also prefer collecting lines of text in an array and then convert them to a string at the end, when needed 🤔

**Review by revolter — APPROVED** [review]
Now we have a nice and short diff 👌🏻 ❤️

Really appreciate that you also added tests for it 💪🏻

**Comment by amidaleet** [comment]
Out of curiosity I measured 1 million short rows output with Array vs String .concat().

String consistently faster, in my trivial sample:
- String – 32s
- Array – 35s

3s spent to `join()` may feel insignificant. 
But if huge Xcode testing schemes are being used (as in my projects) shell output is much longer and strings far larger.
So simple type change may save plenty of time per each CI/CD run

Maybe I will fill another Issue and PR later for performance improvement

**Comment by revolter** [comment]
> Out of curiosity I measured 1 million short rows output with Array vs String .concat().
> 
> String consistently faster, in my trivial sample:
> 
> * String – 32s
> * Array – 35s
> 
> 3s spent to `join()` may feel insignificant. But if huge Xcode testing schemes are being used (as in my projects) shell output is much longer and strings are far larger. So simple type change may save plenty of time per each CI/CD run

Wow, amaziiing, good job 👏🏻

> Maybe I will fill another Issue and PR later for performance improvement

That would be great ❤️ The issue is not required, though, from what I know 🤔

**Review by mollyIV — APPROVED** [review]
Thanks a lot for making the change and working through it to make everything easier to read!

This duplicated output showed up every time I looked at unit test failure logs. It made it pretty painful to scroll through and find the actual cause of the error. Really glad to see this cleaned up!

**Comment by amidaleet** [comment]
After precise measurements `String.concat()` change effect appears to be not so great.
But it is still minor improvement.

[Submitted PR](https://github.com/fastlane/fastlane/pull/29554)
