### PR TITLE
Fix download_dsyms.rb ‘latest’

### LINKED ISSUE #10255: dowload_dsyms with version: 'latest' does not download from the latest version
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
The lane download_dsyms with the parameter (version:"latest") is trying to download the dsyms for the previous version of my app that is available on the App Store, and not the version I just uploaded to iTC. The version that I have on the App Store is version 172.0.0.2002 and does not have bitcode enabled. I am enabling bitcode for the first time on version 173.0.0.2002. When I run the refresh_dsyms lane, it attempts to download dsyms for version 172.0.0.2002. My build with version 173.0.0.2002 is already uploaded to iTC, but I have not submitted it for review yet. I have verified that the I can download the dsyms for version 173.0.0.2002 from iTC through the "Download dSYM" link.

me$ fastlane refresh_dsyms
[12:25:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:25:07]: -------------------------------------------------
[12:25:07]: --- Step: Verifying required fastlane version ---
[12:25:07]: -------------------------------------------------
[12:25:07]: Your fastlane version 2.55.0 matches the minimum requirement of 2.55.0  ✅
[12:25:07]: ------------------------------
[12:25:07]: --- Step: default_platform ---
[12:25:07]: ------------------------------
[12:25:07]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[12:25:07]: Driving the lane 'refresh_dsyms' 🚀
[12:25:07]: ----------------------------
[12:25:07]: --- Step: download_dsyms ---
[12:25:07]: ----------------------------
[12:25:07]: Login to iTunes Connect (redacted)
[12:25:08]: Login successful
[12:25:11]: Looking for dSYM files for com.redacted.redacted v172.0.0.2002 (172.0.0.2002)
[12:25:12]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet

### PR DESCRIPTION
**Pull request by humblehacker**
When `version` is set to `latest`, the following changes apply
• choose the edit version before the live version, since the edit version will be newer
• nil out `version` since `AppVersion.version` will not necessarily match any version in a `BuildTrain`
• return immediately if a `build_number` is found, since there will only be one dSYM for a given build number

Closes #10255

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Comment by humblehacker** [comment]
I signed it!

**Comment by humblehacker** [comment]
I'm unable to run rspec tests due to issue #9177

File: fastlane/lib/fastlane/actions/download_dsyms.rb [hunk 1]
```diff
@@ -28,9 +28,9 @@ def self.run(params)
 
         # Set version if it is latest
         if version == 'latest'
-          # Try to grab the live version first, else fallback to edit version
-          latest_version = app.live_version(platform: platform) || app.edit_version(platform: platform)
-          version = latest_version.version
+          # Try to grab the edit version first, else fallback to live version
+          latest_version = app.edit_version(platform: platform) || app.live_version(platform: platform)
+          version = nil
```
Comment (ohayon) [inline fastlane/lib/fastlane/actions/download_dsyms.rb]: Is there a reason for setting this to nil?

Comment (humblehacker) [reply fastlane/lib/fastlane/actions/download_dsyms.rb]: Yes, the reason is in my commit message:

> nil out version since AppVersion.version will not necessarily match any version in a BuildTrain

Comment (humblehacker) [reply fastlane/lib/fastlane/actions/download_dsyms.rb]: Just in case that's not clear, if I understand correctly, AppVersion.version corresponds with the version number set in iTunes Connect, which is user settable and does not have to match the version number in the IPA.  For example, for necessary but irrelevant reasons, our versions are 6.12 and 1006.12.

**Review by ohayon — APPROVED** [review]
Thanks for this @humblehacker !! Welcome to the _fastlane_ community 🚀 !
