### PR TITLE
Log SSH output as it is received

### LINKED ISSUE #4504: SSH will not show console logs in runtime
### Issue Description

Using ssh will work fine, but instead of showing the console logs in runtime it will show them only when job is done. You cannot see the progress of the ssh through logs.
Using regular ssh to that machine using terminal do show the console logs with the progress.

##### Complete output when running fastlane, including the stack trace and command used

Command used: ssh

```
ssh(
    	host: "10.8.1.29",
    	username: "local",
	    password: "password",
		commands:
			[
				"cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py \"" + build_info['build_url'] + "\" ios"
			],
    )
```

As you can see in the next output, only after the process finished (15 min later) and successfully executed, only then it will show the terminal logs:

```
[11:41:46]: [SSH COMMAND]: cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py "https://rink.hockeyapp.net/api/2/apps/92d18ec4382b424eb2a2/app_versions/73?format=ipa&pltoken=b34hy535bhe5hy&avtoken=erth356h236h356hy6" ios
[11:55:50]: Succesfully executed 1 commands on host: 10.8.1.29
[11:55:50]: 
########### 
 File class object
File class object
File class object
File class object
File class object
start test
device connected
...
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
ssh(
    	host: "10.8.1.29",
    	username: "local",
	    password: "password",
		commands:
			[
				"cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py \"" + build_info['build_url'] + "\" ios"
			],
    )
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0 (also tried on 1.84.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? n

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? n

### PR DESCRIPTION
**Pull request by ravron**
This diff fixes #4504. 
- Log SSH output as it is received
- Use the proper `UI` methods to print the various messages
- Properly pluralize "command" when only one command has been run
- Add a couple of comments

### CODE REVIEW

**Comment by nmayafit** [comment]
@ravron I just checked and still get the same result (no logs during ssh connection open).
I also added log:true in order to bypass the default, still the same.
This is the ssh I can see:
+------------+--------------------------------+-----------------+
|                              ssh                              |
+------------+--------------------------------+-----------------+
| Key        | Description                    | Env Var         |
+------------+--------------------------------+-----------------+
| * username | Username                       | FL_SSH_USERNAME |
|   password | Password                       | FL_SSH_PASSWORD |
| * host     | Hostname                       | FL_SSH_HOST     |
|   port     | Port (default: '22')           | FL_SSH_PORT     |
|   commands | Commands                       | FL_SSH_COMMANDS |
|   log      | Log Commands (default: 'true') | FL_SSH_LOG      |
+------------+--------------------------------+-----------------+

**Comment by ravron** [comment]
@nmayafit Thanks for taking a look. You don't appear to be running the code in this PR: the help that you pasted into your comment shows the description of the `log` flag as "Log Commands," but as you can see in the [changed files][1], I've changed that string to "Log commands and output." This is a definite indicator that you're not running the proper version of the code. 

[1]: https://github.com/fastlane/fastlane/pull/4662/files#diff-68eeba9b78e919246e85d9dc81156b54R126

**Comment by nmayafit** [comment]
Sorry, I guess something I'm doing is wrong (new to this).
I cloned and ran bundle install.
What should I do in order to install your PR on my machine?

**Comment by ravron** [comment]
You'll need to also run `rake install` in the `fastlane_core` directory, I believe, before you're running the proper version.

**Comment by nmayafit** [comment]
Did it. Still sits on 1.81.0 version of fastlane.

**Comment by ravron** [comment]
Then perhaps try the other option. In the checked-out PR directory, run `./fastlane/bin/fastlane action ssh`. You should see the updated help information, the one with "Log commands and output." If you do, then go to your project directory and run fastlane like usual, but use the binary from the first step instead of your installed version of fastlane. So it will be something like this:

```
cd path/to/ios/project
/Users/nmayafit/path/to/fastlane/fastlane/bin/fastlane <action>
```
where that second one is replaced with the real path to the binary.

**Comment by nmayafit** [comment]
ok. Just did it with the regular `sudo gem install -n /usr/local/bin /Users/nmayafit/GITs/Miscellaneous/Fastlane/fastlane/pkg/fastlane-1.89.0.gem `

All working fine and logs are shown. THANKS YOU @ravron for all the dev and support!!!

File: fastlane/lib/fastlane/actions/ssh.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ module SharedValues
     end
 
     class SshAction < Action
-      def self.ssh_exec!(ssh, command)
+      def self.ssh_exec!(ssh, command, log)
```
Comment (ohwutup) [inline fastlane/lib/fastlane/actions/ssh.rb]: Should `log` have a default value of `nil` here so that it won't break other/older calls to this method that do not pass in a `log` parameter?

**Comment by ohwutup** [comment]
Hey @ravron thanks for the PR. I think this a good fix and would like to merge it in. I just left one comment above, and also have one question: We need to be very conscious of what is being printed out to stdout so as to avoid printing any sensitive information. Is there a case where this will log API keys/secrets or passwords or any other sensitive data?

File: fastlane/lib/fastlane/actions/ssh.rb (hunk 1 above)
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/ssh.rb]: Yeah it would be great to have a default value here

Comment (ravron) [inline fastlane/lib/fastlane/actions/ssh.rb]: Happy to do that, but I'm not sure I understand – the only call site for `ssh_exec` that I can find is in `ssh.rb`, which has been changed to use `params[:log]`. Who would be calling `ssh_exec`, and how? 

This might be another Ruby thing I don't yet get, so humor me. :)

**Comment by ravron** [comment]
@ohwutup Thanks for the feedback! I've left a response to your inline comment – let me know what I'm missing. As far as PII or other secrets, that depends entirely on what command the user runs with ssh. If they `cat ~/.ssh/id_rsa`, then yes, this will log their private SSH key! But this has just the same risk as the `sh` fastlane action.

File: fastlane/lib/fastlane/actions/ssh.rb (hunk 1 above)
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/ssh.rb]: Yeah, I guess it's true that it's just being called from its own action, however you never know what people do, basically it's all about https://xkcd.com/1172/

Comment (ravron) [inline fastlane/lib/fastlane/actions/ssh.rb]: Fair enough. This is [fixed][1].

[1]: https://github.com/fastlane/fastlane/pull/4662/commits/f390e5dcca9028fe75dd6474835810bb84612780

**Comment by ohwutup** [comment]
Thanks for adding that default value @ravron ! Last request: would you mind squashing up the commit and then we are good to 🚀

**Comment by ravron** [comment]
@ohwutup Happy to squash if you like, but I thought that wasn't necessary anymore? [Github now allows admins to set a squash policy for PRs][1], and [fastlane's own contributor instructions were recently modified to remove that requirement][2]. I specifically didn't squash because it seemed easier not to, given that it doesn't seem to be required anymore.

All that said, happy to go ahead and do it if you like. Let me know :)

[1]: https://github.com/blog/2141-squash-your-commits
[2]: https://github.com/fastlane/fastlane/commit/a5f5153fd9abf349b692251180b981b4e30a55e9

**Comment by ohwutup** [comment]
@ravron done- admittedly I never read the announcement to see where the squash button was. 😑  Thanks for all the work and making that change! 🚀
