### PR TITLE
[deliver][pilot] use altool instead of using iTMSTransporter for Xcode 14

### LINKED ISSUE #20371: Unable to upload to testflight using Xcode 14 beta
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When trying to use `upload_to_testflight` with XCode 14 BEta, fastlane reports the following error:
```
[!] Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.
```

##### Command executed
`bundle exec fastlane run upload_to_testflight`

##### Relevant output when running fastlane, including the stack trace and command used

<details>
  <pre> 

[15:58:37]: Ready to upload new build to TestFlight (App: xxxx)...
Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.
[15:58:38]: Going to upload updated app to App Store Connect
[15:58:38]: This might take a few minutes. Please don't interrupt the script.

[!] Could not find transporter at /Applications/Xcode-beta.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation.

</pre>
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 13.0                                             |
| Ruby                        | 3.1.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.32.1 (Apple Git-133)               |
| Installation Source         | ~/.rbenv/versions/3.1.1/bin/fastlane             |
| Host                        | macOS 13.0 (22A5266r)                            |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.1/lib                      |
| OpenSSL Version             | OpenSSL 1.1.1n  15 Mar 2022                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 14.0                                             |
| Swift Version               | 5.7                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.2.31       |
| pathname                        | 0.2.0        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.598.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.1      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.4.1        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-06-09**
</details>

### PR DESCRIPTION
**Pull request by freddi-kit**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #20371 

ITMSTransporter is officially removed from Xcode 14 beta and now it is only available on Transporter.app. 
Apple recommends to use altool instead.

#### Implemlemented
- Use altool if fastlane tries to upload ipa from Xcode 14

#### Tested
- deliver and pilot action

### Testing Steps
- Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "altool-upload"
```

I tested by pure project with below fastfile

```rb
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xcode_select("/Applications/Xcode_14.app")
    # add actions here: https://docs.fastlane.tools/actions
    build_app(
      scheme: "EmptyTestApp",
      configuration: "Release",
      export_options: {
        provisioningProfiles: {
          "com.freddi.testapp.EmptyTestApp" => "release",
        },
      },
      silent: true,
      clean: true
    )
    deliver(
      submit_for_review: false,
      automatic_release: false,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )
    # pilot(
    #  username: "test@test.com"
    # )
  end
end
```

# TODOs (In other PR)
 - [ ] Add https://github.com/fastlane/fastlane/pull/20631#issuecomment-1244812069 when you have time
 - [ ] Add unit test about provider id parser when @freddi-kit have time
 - [ ] https://github.com/fastlane/fastlane/pull/20631#discussion_r970908801
 - [ ] Investigate about [that hide_output logic that… might be inverted?](https://github.com/fastlane/fastlane/pull/20631/files#r965624132)… but if so, would be the case for all transporters, and not specific to the one you added here — hence a separate and low-priority PR
 - [ ] Celebrate! 🎉

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 1]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+        UI.message("Application Loader output above ^")
+        UI.error(@errors.join("\n"))
+      end
+
+      yield(@all_lines) if block_given?
+      return exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil)
+      use_jwt = !jwt.to_s.empty?
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: if jwt is `nil`. this will be a crash. lile

```suggestion
      use_jwt = !jwt.nil? && !jwt.empty?
```

Or you may use `#present?` on ActiveSupport.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 2]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+        additional_upload_parameters,
+        "-k 100000"
+      ].compact.join(' ')
+    end
+
+    def additional_upload_parameters
+      env_deliver_additional_params = ENV["DELIVER_ALTOOL_ADDITIONAL_UPLOAD_PARAMETERS"]
+      if env_deliver_additional_params.to_s.strip.empty?
+        return nil
+      end
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:260]: It will be crash. Care nil values

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 3]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+
+      return env_deliver_additional_params.to_s.strip
+    end
+
+    def file_upload_option(source)
+      return "-f #{source.shellescape}"
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:266]:
```suggestion
      "-f #{source.shellescape}"
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 4]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+    end
+
+    def handle_error(password)
+      UI.error("Could not download/upload from App Store Connect!")
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:270]: You can use `user_error!` to exit process.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 5]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+    end
+
+    def displayable_errors
+      @errors.map { |error| "[Application Loader Error Output]: #{error}" }.join("\n").gsub!(/"/, "")
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:274]: Use `message` to display.
https://ruby-doc.org/core-2.6/Exception.html#method-i-message

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 6]
```diff
@@ -490,7 +613,14 @@ def initialize(user = nil, password = nil, use_shell_script = false, provider_sh
 
       @jwt = jwt
 
-      @transporter_executor = use_shell_script ? ShellScriptTransporterExecutor.new : JavaTransporterExecutor.new
+      if !use_shell_script && upload && !Helper.user_defined_itms_path? && Helper.mac? && Helper.xcode_at_least?(14)
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:616]: Can you place these conditions on another instance method? lile `should_use_altool?`

**Review by giginet — CHANGES_REQUESTED** [review]
Care nils in some situations and Could you add test cases?

File: deliver/lib/deliver/runner.rb [hunk 7]
```diff
@@ -216,15 +216,15 @@ def upload_binary
...
+        result = transporter.upload(package_path: package_path, asset_path: ipa_path, platform: platform)
       when "osx"
         package_path = FastlaneCore::PkgUploadPackageBuilder.new.generate(
           app_id: Deliver.cache[:app].id,
           pkg_path: pkg_path,
           package_path: "/tmp",
           platform: platform
         )
-        result = transporter.upload(package_path: package_path, asset_path: pkg_path)
+        result = transporter.upload(package_path: package_path, asset_path: pkg_pat, platform: "macos")
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply deliver/lib/deliver/runner.rb:227]: since altool needs a option `-t` and it accepts `ios`, `macos` or `appletvos`. `osx` cannot be passed so I convert it here. but it may be better to do it inside build command construction function. let me fix it

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 8]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+      if Helper.test?
+        yield(nil) if block_given?
+        return command
+      end
+
+      @errors = []
+      @warnings = []
+      @all_lines = []
+
+      if hide_output
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:199]: it should be correct to keep same behavior with original TransporterExecutor
https://github.com/fastlane/fastlane/blob/39c919efbff110b90e4217501f4ec541b6ff8a5f/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L45-L49

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 1 above)
Comment (giginet) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: Sorry, I misunderstood. `nil.to_s` returns `''` 🤔

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 9]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+        end
+        UI.message("Application Loader output above ^")
+        UI.error(@errors.join("\n"))
+      end
+
+      yield(@all_lines) if block_given?
+      return exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil)
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:241]: yes, it will be accessed from parent class as `ShellScriptTransporterExecutor` and `JavaTransporterExecutor`

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 10]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+
+      if hide_output
+        # Show a one time message instead
+        UI.success("Waiting for App Store Connect transporter to be finished.")
+        UI.success("Application Loader progress... this might take a few minutes...")
+      end
+
+      begin
+        exit_status = FastlaneCore::FastlanePty.spawn(command) do |command_stdout, command_stdin, pid|
+          begin
```
[the remark this answers is not in the document]
Comment (giginet) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:207]: Sorry, it's good

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 4 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:270]: We must not exit process here as other implemented handle_error function in `ShellScriptTransporterExecutor` and `JavaTransporterExecutor` (I think)

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 5 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:274]: this `error` is string which is obtained from output from `altool`, not Exception.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 6 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: done!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 2 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:256]: if my understanding is correct, it has no safe because the function used only below code and it is filtered by `compact`.

https://github.com/fastlane/fastlane/blob/0f2a3d4e596d9b8d344a5b68270ab03d3daba0ab/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L239-L249

But if you think that it is better to make caller not being care it, I agree and I can fix it as "", What do you think?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 11]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+      unless exit_status.zero?
+        @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure."
+      end
+
+      if @warnings.count > 0
+        UI.important(@warnings.join("\n"))
+      end
+
+      if @errors.count > 0 && @all_lines.count > 0
+        # Print out the last 18 lines, this is key for non-verbose mode
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:225]: I found good way so please wait a moment

[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:225]: Ah, sorry I think this line should be leave it as is, because the main purpose is providing altool's command output itself and regex is already done at here

https://github.com/fastlane/fastlane/blob/0f2a3d4e596d9b8d344a5b68270ab03d3daba0ab/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L282-L283

[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:225]:
```
2022-09-09 16:12:21.904 Has version info conflict: YES, Previous version info: 15
2022-09-09 16:12:21.905 *** Error: Error uploading '***.ipa'.
2022-09-09 16:12:21.905 *** Error: The provided entity includes an attribute with a value that has already been used The bundle version must be higher than the previously uploaded version: ‘15’. (ID: ***) (-19232)
 {
    NSLocalizedDescription = "The provided entity includes an attribute with a value that has already been used";
    NSLocalizedFailureReason = "The bundle version must be higher than the previously uploaded version: ***";
    "original_server_error" =     {
        code = "ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE";
        detail = "The bundle version must be higher than the previously uploaded version.";
        id = "***";
        meta =         {
            previousBundleVersion = 15;
        };
        source =         {
            pointer = "/data/attributes/cfBundleVersion";
        };
        status = 409;
        title = "The provided entity includes an attribute with a value that has already been used";
    };
    previousBundleVersion = 15;
}
```

This is a sample and I found I may can improve around error, let me fix it

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 12]
```diff
@@ -657,6 +787,12 @@ def provider_ids
 
     TWO_FACTOR_ENV_VARIABLE = "FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"
 
+    # Returns whether altool should be used or ItunesTransporter should be used
+    def should_use_altool(upload, use_shell_script)
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:791]: In Ruby convention, methods return boolean should end with `?`. like `should_use_altool?`

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 2 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:256]: done https://github.com/fastlane/fastlane/pull/20631/commits/d6755514d85ba28a28f2dedbf43a30670d093b28

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 12 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: done! 
5bd7d3f

File: pilot/lib/pilot/build_manager.rb [hunk 13]
```diff
@@ -47,7 +47,7 @@ def upload(options)
       end
 
       transporter = transporter_for_selected_team(options)
-      result = transporter.upload(package_path: package_path, asset_path: asset_path)
+      result = transporter.upload(package_path: package_path, asset_path: asset_path, platform: platform == "osx" ? "macos" : platform)
```
Comment (freddi-kit) [inline pilot/lib/pilot/build_manager.rb:50]:
```suggestion
      result = transporter.upload(package_path: package_path, asset_path: asset_path, platform: platform)
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 14]
```diff
@@ -180,9 +180,123 @@ def additional_upload_parameters
...
+      yield(@all_lines) if block_given?
+      exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil, api_key = nil)
+      [
+        ("API_PRIVATE_KEYS_DIR=#{api_key[:key_filepath]}" if api_key),
+        "xcrun altool",
+        "--upload-app",
+        ("-u #{username.shellescape}" unless api_key),
```
Comment (crazymanish) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: Hi @freddi-kit 

Nice work! i am just testing this PR and it got crashed in this line `shellescape` 
Also, the username is indeed nil in my case because i am using API-Key inside pilot so technially this line should not even execute. i think, maybe we are not passing the api_key correct way in this method....

```ruby
3: from /Users/distiller/project/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-ed28c906445c/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
	 2: from /Users/distiller/project/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-ed28c906445c/pilot/lib/pilot/build_manager.rb:50:in `upload'
	 1: from /Users/distiller/project/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-ed28c906445c/fastlane_core/lib/fastlane_core/itunes_transporter.rb:697:in `upload'
/Users/distiller/project/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-ed28c906445c/fastlane_core/lib/fastlane_core/itunes_transporter.rb:242:in `build_upload_command': undefined method `shellescape' for nil:NilClass (NoMethodError)

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 15]
```diff
@@ -568,9 +690,11 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
 
       password_placeholder = @jwt.nil? ? 'YourPassword' : nil
       jwt_placeholder = @jwt.nil? ? nil : 'YourJWT'
+      api_key_plaseholder = nil unless @api_key.nil?
```
Comment (crazymanish) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:693]:
```suggestion
      api_key_placeholder = nil unless @api_key.nil?
```

please fix this spell in other places too...

**Review by crazymanish — CHANGES_REQUESTED** [review]
Nice work @freddi-kit please see the attached crash when i am using this PR using **pilot+api_key** 
I also updated this PR description to test this PR by others and provide us valuable feedbacks 

i will test and review more...

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 14 above)
Comment (crazymanish) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: btw, `pilot + username(apple-id), password` is working well 🚀

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: Oh Thank you for reviewing!

in my environment, pilot+api_key works. and here is my example Fastfile.
How is mine and your Fastfile different?

```ruby
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xcode_select("/Applications/Xcode_14 beta 6.app")
    api_key = app_store_connect_api_key(
      key_id: "XXXXXX",
      issuer_id: "XXX-XXX-XXXX",
      key_filepath: "./AuthKey_XXXX.p8",
      duration: 1200,
      in_house: false
    )    
    
    pilot(api_key: api_key)
  end
end
```

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: Ah... sorry I may found there is a issue to check password is available or not, please wait a moment

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: I noticed this is simple issue comes from my less experience Ruby 🙇 I can fix it soon

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 16]
```diff
@@ -180,9 +180,123 @@ def additional_upload_parameters
...
+        UI.error(@errors.join("\n"))
+      end
+
+      yield(@all_lines) if block_given?
+      exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil, api_key = nil)
+      [
+        ("API_PRIVATE_KEYS_DIR=#{api_key[:key_filepath]}" if api_key),
```
Comment (crazymanish) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:239]: - we are expecting `key_filepath` which will break all the CI because app_store_connect_api_key action supports api key_content inside the ENV variable `(the content of the .p8 file)` also instead of passing the .p8 file-path. 
- Please see the last part of this document https://docs.fastlane.tools/app-store-connect-api/
- i think, we should file a way to handle that scenario also. maybe we need to create .p8 file 🙈
- for example: **app_store_connect_api_key** accepts the `key_content` instead of `p8 file-path`
```ruby
default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    xcode_select("/Applications/Xcode_14 beta 6.app")
    api_key = app_store_connect_api_key(
      key_id: "XXXXXX",
      issuer_id: "XXX-XXX-XXXX",
      key_content: "-----BEGIN PRIVATE KEY-----\nXXXXXXX\nXXXXXX\nXXXXXXXX\nXXX\n-----END PRIVATE KEY-----",
      duration: 1200,
      in_house: false
    )    
    
    pilot(api_key: api_key)
  end
end

**Review by crazymanish — CHANGES_REQUESTED** [review]
Found one more issue, it is failing when we use **key_content** inside `app_store_connect_api_key` action instead of using the p8 file-path

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 14 above)
Comment (crazymanish) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:242]: thank you very much for putting in all the hard work! 🌟

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/711eb3cd3835eb6068a7b2a4bc29680c6650b7ab fixed, could you try it?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 16 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Ah... I missed this case, thank you!

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: > i think, we should find a way to handle that scenario also. maybe we need to create .p8 file from key_content 🙈

yes! it is solution for this case, let me do so

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: I noticed key_filepath is not existed and i need to do other way, I'll push commit soon

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/747178f1ed4cd5866a218f2eecfedfb1dd68d119 fixed

File: fake testers_file_path [hunk 17]
```diff
@@ -0,0 +1 @@
+First,Last,Email,Groups,Installed Version,Install Date
```
Comment (rogerluan) [inline fake testers_file_path:1]: Was this file uploaded by mistake? Do we need it?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 18]
```diff
@@ -489,8 +604,16 @@ def initialize(user = nil, password = nil, use_shell_script = false, provider_sh
       end
 
       @jwt = jwt
+      @api_key = api_key
+
+      if should_use_altool?(upload, use_shell_script)
+        UI.verbose("Use altool as transporter.")
```
Comment (rogerluan) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:610]: Maybe `Using` makes more sense here:

```suggestion
        UI.verbose("Using altool as transporter.")
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 19]
```diff
@@ -489,8 +604,16 @@ def initialize(user = nil, password = nil, use_shell_script = false, provider_sh
...
+        @transporter_executor = AltoolTransporterExecutor.new
+      else
+        UI.verbose("Use iTMSTransporter as transporter")
```
Comment (rogerluan) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:613]:
```suggestion
        UI.verbose("Using iTMSTransporter as transporter.")
```

**Review by rogerluan — CHANGES_REQUESTED** [review]
Minor comments :) Otherwise LGTM!

File: fake testers_file_path (hunk 17 above)
Comment (crazymanish) [reply fake testers_file_path]: fixed! it is autogenerated file by unit tests. i will be it properly in separate PR https://github.com/fastlane/fastlane/pull/20631/commits/13afc8ccf98878de690b5568ea33de7a3c226dae

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 20]
```diff
@@ -489,8 +604,16 @@ def initialize(user = nil, password = nil, use_shell_script = false, provider_sh
...
       @jwt = jwt
+      @api_key = api_key
+
+      if should_use_altool?(upload, use_shell_script)
+        UI.verbose("Using altool as transporter.")
+        @transporter_executor = AltoolTransporterExecutor.new
+      else
+        UI.verbose("Using iTMSTransporter as transporter.")
+        @transporter_executor = use_shell_script ? ShellScriptTransporterExecutor.new : JavaTransporterExecutor.new
+      end
```
Comment (crazymanish) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:615]: i just notice that `itunes_transporter_spec.rb` is failing in Xcode16. our Fastlane CircleCI is still using Xcode13 to run the unit-tests and thats why failed to report about it.

Adding steps to reproduce it: 
- Step1: Select Xcode16 `sudo xcode-select -s /Applications/Xcode16.app`
- Step2: Run unit-test `bundle exec rspec fastlane/fastlane_core/spec/itunes_transporter_spec.rb`


i am working on fixing these unit-tests to speed-up and to make this PR ready to merge in master branch asap.
Thank you again for all the hard-work! @freddi-kit ❤️

**Review by crazymanish — CHANGES_REQUESTED** [review]

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 21]
```diff
@@ -569,14 +692,32 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
...
+      use_api_key = !@api_key.nil?
+      api_key_placeholder = nil unless use_api_key
+      api_key_placeholder = { key_id: "YourKeyID", issuer_id: "YourIssuerID" } if use_api_key
+
+      if use_api_key
+        # Specified p8 needs to be generated to call altool
+        tmp_p8_file_path = File.join(Dir.tmpdir, "AuthKey_#{@api_key[:key_id]}.p8")
+        p8 = File.open(tmp_p8_file_path, "w")
+        p8.write(@api_key[:key])
+        p8.close
```
Comment (crazymanish) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:705]: **Question:** **if the API-key is Base64 encoded** then i think, we need to decode it first before writing it into the file? 

- Example: [Base64 API-Key example-link](https://github.com/fastlane/fastlane/blob/master/spaceship/spec/connect_api/fixtures/asc_key_base64.json)
- Please see this param https://github.com/fastlane/fastlane/blob/78488dddef57c9d6afbd9a6c04967dcc9c61858b/fastlane/lib/fastlane/actions/app_store_connect_api_key.rb#L74-L76
- i think, we need to add similar logic like below https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/spaceship/lib/spaceship/connect_api/token.rb#L64-L66

**Review by crazymanish — APPROVED** [review]
I have added one final question about when API-Key content will be Base64-encoded inside the `app_store_connect_api_key` action. 

The rest of this PR looks very good to me! 
Once again, thank you very much for this awesome contribution @freddi-kit 🚀

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 20 above)
Comment (crazymanish) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:615]: - Fixed failing `itunes_transporter_spec.rb` unit tests https://github.com/fastlane/fastlane/pull/20631/commits/d36bf23402b6d4c6b4681fc73f355a7b6819f95e
- Fixed failing `helper_spec.rb` unit tests https://github.com/fastlane/fastlane/pull/20631/commits/e4e44ac18ed8a8b959d7383d157dd2e065087c02

**Comment by freddi-kit** [comment]
Oh, sorry. I attended a iOS conference in japan, so i had no time to fix them. Thank you for fixing comments!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 21 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:705]: Ah, it is true, we need to convert it from base64, let me fix soon

**Comment by mflint** [comment]
I switched to using your branch @freddi-kit, and successfully submitted my iOS16/Xcode14 build. Thank-you! ❤️

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 21 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/4f677a6e6e99134ee6ca603b85d2dac582e4a1be Please check it and test just for case 🙇

**Review by crazymanish — APPROVED** [review]
This PR is 🔥  🔥  🔥  🔥 


To me, this PR is good to go 🚀 
Thank you again for this awesome PR and for handling all possible scenarios! 👏

**Comment by freddi-kit** [comment]
Thank you too!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 20 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:615]: Thank you so much! 🙇

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 22]
```diff
@@ -180,9 +180,124 @@ def additional_upload_parameters
...
+        @errors << ex.to_s
+      end
+
+      @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
+
+      UI.important(@warnings.join("\n")) unless @warnings.empty?
+
+      if @errors.count > 0 && @all_lines.count > 0
+        # Print out the last 18 lines, this is key for non-verbose mode
+        @all_lines.last(18).each do |line|
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:226]: Are we sure this will always be the last 18 lines? What if there are other metadata in the JSON printed in `altool`'s log that makes in take more or less lines, depending on the type of error and the `original_server_error`, or if the `NSLocalizedDescription`, `NSLocalizedFailureReason`, and/or `title` ends up being some multiline text depending on the error you encounter?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 23]
```diff
@@ -180,9 +180,124 @@ def additional_upload_parameters
...
+          UI.important("[altool] #{line}")
+        end
+        UI.message("Application Loader output above ^")
+        UI.error(@errors.join("\n"))
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:230]: Same nitpick as above regarding `UI.error` prefixing the message with timestamps and this `.join("\n")` thus making the first line with prefix different from the other errors in the array.

```suggestion
        @errors.each { |error| UI.error(error) }
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 24]
```diff
@@ -180,9 +180,124 @@ def additional_upload_parameters
...
+    end
+
+    private
+
+    def file_upload_option(source)
+      "-f #{source.shellescape}"
+    end
+
+    def platform_option(platform)
+      "-t #{platform == 'osx' ? 'macox' : platform}"
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: Typo?
```suggestion
      "-t #{platform == 'osx' ? 'macosx' : platform}"
```

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: Btw, since that typo didn't make the test suite fail… maybe that's a sign that we need to add some test case (aka _spec_ example) to our test suite for it? 🤔

**Review by AliSoftware — COMMENTED** [review]
Thanks for working on this! ❤️ 🙇 

💄  Disclaimer: I only reviewed the diff directly on GitHub — i.e. didn't actually try to run it to test and validate the changes. So this review is mostly small codestyle/nitpicks 😅 

📝  Found a typo for `macox` -> `macosx` though, which not only will probably need fixing before merging, but might highlight that we might want to add some unit tests for this method and use case 🙃

File: fake testers_file_path (hunk 17 above)
Comment (AliSoftware) [reply fake testers_file_path]: Shouldn't the unit tests generate such files in a temporary dir instead on generating them at the repo root? 🤔 

Though I think that file is not generated by any test that you added in this PR, but has instead always been generated there, by another test that was already there even before your PR, right? In that case, fixing that is outside the scope of this PR; but maybe something to keep in mind for a later fix? 🤷

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 24 above)
Comment (crazymanish) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: also, this brings to point that are we really sure we need to make it `macosx` from `osx`? 

Apple's official document is saying `osx` should be enough which means we don't require this condition at all, right? maybe @freddi-kit knows? 👀 
https://help.apple.com/itc/apploader/#/apdATD1E53-D1E1A1303-D1E53A1126


Screenshot 2022-09-10 at 21 18 16


> maybe that's a sign that we need to add some test case (aka spec example) to our test suite for it? 🤔

i agree!

Comment (crazymanish) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: and when i m running `xcrun altool --help` in terminal then Apple is saying it should be `macos` 🙈 
so should we use `osx` or `macosx` or `macos`? 😅🤔 

To be honest, i have no mac-app to upload and verify about it...

Screenshot 2022-09-10 at 21 35 09

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: This should be macos and it is my mistake 🙇 let me fix it

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:278]: > To be honest, i have no mac-app to upload and verify about it...

I just tested with new empty mac os app and it success to upload.

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/9988e33aecedff313164c4a441f80760a95d42f6 fixed

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 25]
```diff
@@ -180,9 +180,124 @@ def additional_upload_parameters
...
+
+      begin
+        exit_status = FastlaneCore::FastlanePty.spawn(command) do |command_stdout, command_stdin, pid|
+          begin
+            command_stdout.each do |line|
+              @all_lines << line
+              parse_line(line, hide_output) # this is where the parsing happens
+            end
+          end
+        end
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:213]: I followed https://github.com/fastlane/fastlane/blob/9988e33aecedff313164c4a441f80760a95d42f6/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L51-59 to make it same format. However, as you said, it should be okay to remove first begin

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 26]
```diff
@@ -180,9 +180,124 @@ def additional_upload_parameters
...
+      rescue => ex
+        # FastlanePty adds exit_status on to StandardError so every error will have a status code
+        exit_status = ex.exit_status
+        @errors << ex.to_s
+      end
+
+      @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
+
+      UI.important(@warnings.join("\n")) unless @warnings.empty?
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:220]: > And as a bonus you would not have to test for @warnings.empty? since the each loop would just never iterate if the array is empty 🙃

Ah, yes, currently there is no change to parse warning here, so maybe it would be better to remove this line

[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/44bf7aaf775a90cf9e02101bc070167653fe2bc4 fixed!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 22 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:221]: > Are we sure this will always be the last 18 lines?

Honestly, I'm not sure 😅 . I only encountered and know `original_server_error ` error and it `almost` 18 line to show JSON.

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:221]: What about detecting the first line with `*** Error:` in it, and print all the lines from that one to the end?

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:221]: Or alternatively, detecting each line starting with `/[0-9 .:-]* \*\*\* Error:/`, and for each one, accumulate all the following lines *not* starting with a timestamp like `/[0-9 .:-]*/` — to pick up all lines from that error… up to the next timestamped log line, if any 🤔

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: https://github.com/fastlane/fastlane/pull/20631/commits/01a58737a9a805b3d8034a63f8c94d7725a992e0 
I wanna propose this improvement. This will shows the lines until `***Error` shown. If `***Error` cannot be found (it is super very rare case since `@errors.count > 0 && @all_lines.count > 0`), shows last 20 line

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Sample is like below

```
[08:25:51]: This might take a few minutes. Please don't interrupt the script.
[08:25:55]: [altool] 2022-09-11 08:25:55.615 *** Error: Error uploading '/xxx.pkg'.

[08:25:55]: [altool] 2022-09-11 08:25:55.615 *** Error: The provided entity includes an attribute with a value that has already been used The bundle version must be higher than the previously uploaded version: ‘3’. (ID: xxx) (-19232)

[08:25:55]: [altool]  {

[08:25:55]: [altool]     NSLocalizedDescription = "The provided entity includes an attribute with a value that has already been used";

[08:25:55]: [altool]     NSLocalizedFailureReason = "The bundle version must be higher than the previously uploaded version: \U20183\U2019. (ID: xxx)";

[08:25:55]: [altool]     "original_server_error" =     {

[08:25:55]: [altool]         code = "ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE";

[08:25:55]: [altool]         detail = "The bundle version must be higher than the previously uploaded version.";

[08:25:55]: [altool]         id = "xxx";

[08:25:55]: [altool]         meta =         {

[08:25:55]: [altool]             previousBundleVersion = 3;

[08:25:55]: [altool]         };

[08:25:55]: [altool]         source =         {

[08:25:55]: [altool]             pointer = "/data/attributes/cfBundleVersion";

[08:25:55]: [altool]         };

[08:25:55]: [altool]         status = 409;

[08:25:55]: [altool]         title = "The provided entity includes an attribute with a value that has already been used";

[08:25:55]: [altool]     };

[08:25:55]: [altool]     previousBundleVersion = 3;

[08:25:55]: [altool] }
```

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Other sample is below which has less line log

```
[08:23:17]: This might take a few minutes. Please don't interrupt the script.
[08:23:32]: [altool] 2022-09-11 08:23:32.551 *** Error: Error uploading '/xxx.pkg'.

[08:23:32]: [altool] 2022-09-11 08:23:32.552 *** Error: Asset validation failed The product archive is invalid. The Info.plist must contain a LSApplicationCategoryType key, whose value is the UTI for a valid category. For more details, see "Submitting your Mac apps to the App Store". (ID: xxx) (90242)

[08:23:32]: [altool]  {

[08:23:32]: [altool]     NSLocalizedDescription = "Asset validation failed";

[08:23:32]: [altool]     NSLocalizedFailureReason = "The product archive is invalid. The Info.plist must contain a LSApplicationCategoryType key, whose value is the UTI for a valid category. For more details, see \"Submitting your Mac apps to the App Store\". (ID: xxx)";

[08:23:32]: [altool]     "original_server_error" =     {

[08:23:32]: [altool]         code = "STATE_ERROR.VALIDATION_ERROR.90242";

[08:23:32]: [altool]         detail = "The product archive is invalid. The Info.plist must contain a LSApplicationCategoryType key, whose value is the UTI for a valid category. For more details, see \"Submitting your Mac apps to the App Store\".";

[08:23:32]: [altool]         id = "xxxx";

[08:23:32]: [altool]         status = 409;

[08:23:32]: [altool]         title = "Asset validation failed";

[08:23:32]: [altool]     };

[08:23:32]: [altool] }

```

**Comment by freddi-kit** [comment]
retest

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 22 above)
Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: I like the idea 👍

Note that in terms of implementation you can do some optimisations, like using `@all_lines.rindex { … }` to find the index of the last line matching the regex (instead of using `each_index { … }.last`.
(Or you might be able to use `drop_while` or similar? Though that one might not get you the last occurrence)

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Ohhhh! I need to learn more about Ruby, Thank you. Let me fix

I feel that `rindex` is suitable for my case since needs to check from bottom

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: fixed! https://github.com/fastlane/fastlane/pull/20631/commits/7490c5c0742d7e3eba540b3a7b61c9a4f70bffda Thank you so much!

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Another tip: you can [index arrays using ranges and negative indices](https://ruby-doc.org/core-3.1.2/Array.html#method-i-5B-5D) like `arr[-20..-1]` for example (equivalent to `last(20)`) or `arr[error_line..-1]` (to get lines from index `error_line` to the end of the array)

I think using that instead of `last(…your long condition + math…)` would make the code more readable.

So this would become something like `@all_lines[(error_line || -20)..-1].each do … end`

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: ohhh.. cool!

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Also you should add those example messages you commented above … as unit tests 🙂

**Comment by freddi-kit** [comment]
https://app.circleci.com/pipelines/github/fastlane/fastlane/4804/workflows/4df0f63b-f972-4b42-baa4-49d6ba50742f/jobs/84938 

Xcode 11 test starts failing and i think it is not related to mine one. Xcode14 may brake simulator env. Could anyone help checking it? 🙇

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 22 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: good. let me add it later 🙇 (Sorry I'm busy from now so it will be later)

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: No worries, and thanks already for handling all this 👍

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 27]
```diff
@@ -180,9 +180,122 @@ def additional_upload_parameters
...
+      ].compact.join(' ')
+    end
+
+    def additional_upload_parameters
+      env_deliver_additional_params = ENV["DELIVER_ALTOOL_ADDITIONAL_UPLOAD_PARAMETERS"]
+      if env_deliver_additional_params.to_s.strip.empty?
+        return nil
+      end
+
+      return env_deliver_additional_params.to_s.strip
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:258]: [nits]

```suggestion
      env_deliver_additional_params.to_s.strip
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 28]
```diff
@@ -569,14 +690,33 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
...
+      api_key_placeholder = nil unless use_api_key
+      api_key_placeholder = { key_id: "YourKeyID", issuer_id: "YourIssuerID" } if use_api_key
+
+      if use_api_key
+        # Specified p8 needs to be generated to call altool
+        tmp_p8_file_path = File.join(Dir.tmpdir, "AuthKey_#{@api_key[:key_id]}.p8")
+        p8 = File.open(tmp_p8_file_path, "w")
+        key_content = @api_key[:is_key_content_base64] ? Base64.decode64(@api_key[:key]) : @api_key[:key]
+        p8.write(key_content)
+        p8.close
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:704]: [nits] you can use block

```ruby
File.open() do |p8|
end
```

File: fastlane_core/spec/helper_spec.rb [hunk 29]
```diff
@@ -178,7 +180,13 @@
       context "#itms_path" do
         it "default", requires_xcode: true do
           stub_const('ENV', { 'FASTLANE_ITUNES_TRANSPORTER_PATH' => nil })
-          expect(FastlaneCore::Helper.itms_path).to match(/itms/)
+
+          if FastlaneCore::Helper.xcode_at_least?("14")
+            expect(FastlaneCore::UI).to receive(:user_error!).with(/Could not find transporter/)
+            FastlaneCore::Helper.itms_path
```
Comment (giginet) [inline fastlane_core/spec/helper_spec.rb:186]: What means this line?

**Review by giginet — APPROVED** [review]
LGTM without minor fixes. 
Thanks very much fo your effort!

File: fastlane_core/spec/helper_spec.rb (hunk 29 above)
Comment (freddi-kit) [reply fastlane_core/spec/helper_spec.rb:186]: For this https://github.com/fastlane/fastlane/pull/20631#discussion_r967653482 (I think, because i did not commit it)

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 28 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: done!

File: fastlane_core/spec/helper_spec.rb (hunk 29 above)
Comment (crazymanish) [reply fastlane_core/spec/helper_spec.rb:186]: This is testing the expected behaviour when fetching itms_path in Xcode14
please see: https://github.com/fastlane/fastlane/blob/ff41f3556f1baf8e700477e50f65be728780aa94/fastlane_core/lib/fastlane_core/helper.rb#L244

Screenshot 2022-09-11 at 09 00 19

**Comment by crazymanish** [comment]
> https://app.circleci.com/pipelines/github/fastlane/fastlane/4804/workflows/4df0f63b-f972-4b42-baa4-49d6ba50742f/jobs/84938
> 
> Xcode 11 test starts failing and i think it is not related to mine one. Xcode14 may brake simulator env. Could anyone help checking it? 🙇

this looks unrelated to this PR, i will have a look today 👀

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 30]
```diff
@@ -569,14 +690,33 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
...
-      command = @transporter_executor.build_upload_command(@user, @password, actual_dir, @provider_short_name, @jwt)
-      UI.verbose(@transporter_executor.build_upload_command(@user, password_placeholder, actual_dir, @provider_short_name, jwt_placeholder))
+      # Handle AppStore Connect API
+      use_api_key = !@api_key.nil?
+      api_key_placeholder = nil unless use_api_key
+      api_key_placeholder = { key_id: "YourKeyID", issuer_id: "YourIssuerID" } if use_api_key
+
+      if use_api_key
+        # Specified p8 needs to be generated to call altool
+        tmp_p8_file_path = File.join(Dir.tmpdir, "AuthKey_#{@api_key[:key_id]}.p8")
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:700]: I'd suggest to instead use `Dir.mktmpdir` to create an intermediate and guaranteed-unique temporary folder and generate the key file inside it. Or use `TempFile` to create the file.

(PS: In either case you can provide a prefix (like `deliver-`) to use for the autogenerate unique filename which could help identify it on disk… even though it'll get deleted soon after so it doesn't really matter)

If you go that route you'll have to declare `tmp_p8_file_path = nil` before the `begin`, then set it to a value on this line, so that you'll be able to use the same `tmp_p8_file_path` value in your `ensure` block to delete it.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 31]
```diff
@@ -569,14 +690,33 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
...
       begin
         result = @transporter_executor.execute(command, ItunesTransporter.hide_transporter_output?)
       rescue TransporterRequiresApplicationSpecificPasswordError => ex
         handle_two_step_failure(ex)
         return upload(app_id, dir, package_path: package_path, asset_path: asset_path)
+      ensure
+        if use_api_key
+          tmp_p8_file_path = File.join(Dir.tmpdir, "AuthKey_#{@api_key[:key_id]}.p8")
+          FileUtils.rm_f(tmp_p8_file_path)
+        end
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:719]: If you go with my suggestion above to use the traditional `Dir.mktmpdir` or `TempFile` to create the file, this would become just:

```suggestion
        FileUtils.rm_f(tmp_p8_file_path) unless tmp_p8_file_path.nil?
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 32]
```diff
@@ -180,9 +180,122 @@ def additional_upload_parameters
...
+      end
+
+      yield(@all_lines) if block_given?
+      exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil, api_key = nil)
+      use_api_key = !api_key.nil?
+      [
+        ("API_PRIVATE_KEYS_DIR=#{Dir.tmpdir}" if use_api_key),
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:238]: Of course if you decide to go with my suggestion of using `TempFile` to generate the temporary p8 file, you'll have to adjust this to pass `File.dirname(tmp_p8_file_path)` there

**Review by rogerluan — APPROVED** [review]
I'm so proud of everyone that is contributing in this PR ❤️  amazing team work!! Keep it up everyone!
This PR LGTM now 😊

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 28 above)
Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Actually you can even just use a one-liner that will open/create the file, write to it, and close it all in one go: `File.write(tmp_p8_file_path, key_content)`

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 33]
```diff
@@ -569,14 +690,33 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
       password_placeholder = @jwt.nil? ? 'YourPassword' : nil
       jwt_placeholder = @jwt.nil? ? nil : 'YourJWT'
 
-      command = @transporter_executor.build_upload_command(@user, @password, actual_dir, @provider_short_name, @jwt)
-      UI.verbose(@transporter_executor.build_upload_command(@user, password_placeholder, actual_dir, @provider_short_name, jwt_placeholder))
+      # Handle AppStore Connect API
+      use_api_key = !@api_key.nil?
+      api_key_placeholder = nil unless use_api_key
+      api_key_placeholder = { key_id: "YourKeyID", issuer_id: "YourIssuerID" } if use_api_key
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:696]: Code-style nitpick: merging those two lines into a single one using a ternary condition will make this easier to read/reason about imho:

```suggestion
      api_key_placeholder = use_api_key ? { key_id: "YourKeyID", issuer_id: "YourIssuerID" } : nil
```

**Comment by Sherlouk** [comment]
Just jumping in to say this branch has fixed the issue for myself, requiring no extra changes to my configuration.

I'm using ASC API.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 30 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Done! https://github.com/fastlane/fastlane/pull/20631/commits/c82e99a896e5a07978c8d114948ca3ee6c88ef3b

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 34]
```diff
@@ -569,14 +690,32 @@ def upload(app_id = nil, dir = nil, package_path: nil, asset_path: nil)
...
-      UI.verbose(@transporter_executor.build_upload_command(@user, password_placeholder, actual_dir, @provider_short_name, jwt_placeholder))
+      # Handle AppStore Connect API
+      use_api_key = !@api_key.nil?
+      api_key_placeholder = use_api_key ? { key_id: "YourKeyID", issuer_id: "YourIssuerID" } : nil
+
+      tmp_p8_dir_path = nil
+      if use_api_key
+        tmp_p8_dir_path = Dir.mktmpdir("deliver-")
+        # Specified p8 needs to be generated to call altool
+        File.open(File.join(tmp_p8_dir_path, "AuthKey_#{@api_key[:key_id]}.p8"), "w") do |p8|
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Given the API key might be base64, that we will decode in such case, leading to the possibility that the content written here might contain some binary data, better write to that p8 file using binary option:


```suggestion
        File.open(File.join(tmp_p8_dir_path, "AuthKey_#{@api_key[:key_id]}.p8"), "wb") do |p8|
```

**Comment by freddi-kit** [comment]
I'm working on creating some unit testing so please wait. I'm sorry for taking so long time 🙇

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 35]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+  # Generates commands and executes the altool.
+  class AltoolTransporterExecutor < TransporterExecutor
+    ERROR_REGEX = /.*\*\*\*\sError:\s+(.+)/
+
+    private_constant :ERROR_REGEX
+
+    def execute(command, hide_output)
+      if Helper.test?
+        yield(nil) if block_given?
+        return command
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:192]: I found it is necessary for test case, so I reverted

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 14 above)
Comment (raid5) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: I just switched over to this `altool-upload` branch in my Gemfile and I am still hitting this issue. One difference I notice is that I'm specifying `api_key_path` instead of `api_key`

Comment (leandroalonso) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Hi @freddi-kit! Thank you so much for working on that.

I second @raid5 comment. I believe there's an unhandled case when using `api_key_path` (instead of `api_key`):

> 
>
> fastlane_core/lib/fastlane_core/itunes_transporter.rb:241:in `build_upload_command': undefined method `shellescape' for nil:NilClass (NoMethodError)

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: I just investigated and it is bug, and it requires a little more changes to support it api_key_path. I'm happy if you wait for it 🙇

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Fixed! https://github.com/fastlane/fastlane/pull/20631/commits/22cfcec0f28ac400272b27ccc27de7cbf7ebcc99

**Comment by freddi-kit** [comment]
@AliSoftware @rogerluan @giginet @crazymanish I added some additional case (e.g. api_key_path), could you check current one?

**Comment by freddi-kit** [comment]
@AliSoftware and I added unit test as possible. but I think https://github.com/fastlane/fastlane/pull/20631#discussion_r967717866 may takes long time to do it since I don't have knowledge to mock up `pty`. So Could I do it in other PR?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 32 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: >  instead of passing the actual API key value 

Other API key value is necessary like `key_id` and `issuer_id`, so I wanna you this api_key argument as current actual API key value

**Comment by AliSoftware** [comment]
> @AliSoftware and I added unit test as possible. but I think https://github.com/fastlane/fastlane/pull/20631#discussion_r967717866 may takes long time to do it since I don't have knowledge to mock up `pty`. So Could I do it in other PR?

Sure, separate PR is totally fine by me 👍

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 36]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+  # Generates commands and executes the altool.
+  class AltoolTransporterExecutor < TransporterExecutor
+    ERROR_REGEX = /\*\*\* Error:\s+(.+)/
+
+    private_constant :ERROR_REGEX
+
+    def execute(command, hide_output)
+      if Helper.test?
+        yield(nil) if block_given?
+        return command
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:192]:
```suggestion
        command
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 37]
```diff
@@ -180,9 +180,132 @@ def additional_upload_parameters
...
+        additional_upload_parameters,
+        "-k 100000"
+      ].compact.join(' ')
+    end
+
+    def additional_upload_parameters
+      env_deliver_additional_params = ENV["DELIVER_ALTOOL_ADDITIONAL_UPLOAD_PARAMETERS"]
+      if env_deliver_additional_params.to_s.strip.empty?
+        return nil
+      end
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:266]:
```suggestion
      return nil if env_deliver_additional_params.to_s.strip.empty?
```

File: fastlane_core/spec/helper_spec.rb (hunk 29 above)
Comment (giginet) [reply fastlane_core/spec/helper_spec.rb:186]: Let's use `not_to raise_error` to check `itms_path` to work well.

```ruby
expect { FastlaneCore::Helper.itms_path }.not_to raise_error
```

It helps be clear why we called this property here.

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 38]
```diff
@@ -1107,9 +1126,64 @@ def xcrun_download_command(provider_short_name = nil, jwt: nil)
       end
     end
 
+    describe "with Xcode 14.x installed" do
```
Comment (giginet) [inline fastlane_core/spec/itunes_transporter_spec.rb:1129]: It's better to use `context` to describe situations.

```suggestion
    context "with Xcode 14.x installed" do
```

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 39]
```diff
@@ -1107,9 +1126,64 @@ def xcrun_download_command(provider_short_name = nil, jwt: nil)
...
+      before(:each) do
+        allow(FastlaneCore::Helper).to receive(:xcode_version).and_return('14.0')
+        allow(FastlaneCore::Helper).to receive(:mac?).and_return(true)
+        allow(FastlaneCore::Helper).to receive(:windows?).and_return(false)
+      end
+
+      describe "with username and password" do
```
Comment (giginet) [inline fastlane_core/spec/itunes_transporter_spec.rb:1136]:
```suggestion
      context "with username and password" do
```

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 40]
```diff
@@ -1107,9 +1126,64 @@ def xcrun_download_command(provider_short_name = nil, jwt: nil)
...
+          end
+          describe "upload command generation" do
+            it 'generates a call to altool' do
+              transporter = FastlaneCore::ItunesTransporter.new(email, password, false, 'abcd123', upload: true)
+              expect(transporter.upload('my.app.id', '/tmp', package_path: '/tmp/my.app.id.itmsp', platform: "osx")).to eq(altool_upload_command)
+            end
+          end
+        end
+
+        describe "with user defined itms_path" do
```
Comment (giginet) [inline fastlane_core/spec/itunes_transporter_spec.rb:1150]:
```suggestion
        context "with user defined itms_path" do
```

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 41]
```diff
@@ -1107,9 +1126,64 @@ def xcrun_download_command(provider_short_name = nil, jwt: nil)
...
 
+    describe "with Xcode 14.x installed" do
+      before(:each) do
+        allow(FastlaneCore::Helper).to receive(:xcode_version).and_return('14.0')
+        allow(FastlaneCore::Helper).to receive(:mac?).and_return(true)
+        allow(FastlaneCore::Helper).to receive(:windows?).and_return(false)
+      end
+
+      describe "with username and password" do
+        describe "with default itms_path" do
```
Comment (giginet) [inline fastlane_core/spec/itunes_transporter_spec.rb:1137]:
```suggestion
        context "with default itms_path" do
```

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 42]
```diff
@@ -1107,9 +1126,64 @@ def xcrun_download_command(provider_short_name = nil, jwt: nil)
...
+              expect(transporter.upload('my.app.id', '/tmp', platform: "osx")).to eq(java_upload_command(provider_short_name: 'abcd123', classpath: false))
+            end
+          end
+        end
+
+        after(:each) { ENV.delete("FASTLANE_ITUNES_TRANSPORTER_PATH") }
+      end
+
+      describe "with api_key" do
+        describe "with default itms_path" do
```
Comment (giginet) [inline fastlane_core/spec/itunes_transporter_spec.rb:1167]:
```suggestion
      context "with api_key" do
        context "with default itms_path" do
```

File: pilot/lib/pilot/build_manager.rb [hunk 43]
```diff
@@ -389,15 +389,19 @@ def expire_previous_builds(build)
     def transporter_for_selected_team(options)
       # Use JWT auth
       api_token = Spaceship::ConnectAPI.token
+      api_key = options[:api_key]
+      # Load api key info if user set api_key_path, not api_key
+      api_key = { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 } if api_key.nil? && !options[:api_key_path].nil?
```
Comment (giginet) [inline pilot/lib/pilot/build_manager.rb:394]: You can use `||=` instead to set default value.

```suggestion
      api_key ||= { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
```

Comment (giginet) [reply pilot/lib/pilot/build_manager.rb:394]: [In my opinion] It's better to use `Struct` instead of Hash to describe `api_key`.
However, I'm concerned about the compatibility between existing APIs.

**Review by giginet — APPROVED** [review]
I reviewed some points. however, most of them are minor fixes to improve rspec.
You can refer this article 📖 
https://www.betterspecs.org/

Great Job! @freddi-kit

File: pilot/lib/pilot/build_manager.rb (hunk 43 above)
Comment (AliSoftware) [reply pilot/lib/pilot/build_manager.rb:394]: @giginet I think using `||=` would not have the same behavior here because in the original code there's also a condition on `&& !options[:api_key_path].nil?`

Another alternative to write those lines could also be:
```
api_key = if options[:api_key].nil? && !options[:api_key_path]
  …hash value here…
elsif …
  …
else
  …
end
```
(Though weather that would be more readable than the original code is debatable and a matter of preference)

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 36 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:192]: This cannot be done otherwise it will be problem on the test case. Actually, this function will return `true` or `false` for normal case but this should return command string if test and implicit return cannot be used at the case.

**Comment by rogerluan** [comment]
@freddi-kit I recommend you running `bundle exec rubocop -a` locally before pushing 😉

**Comment by freddi-kit** [comment]
@rogerluan Ops I'm sorry. Because my env cannot rubocop for unknown reason. But let me try to fix since there are many annoying commit from me 🙇🙇🙇

**Comment by freddi-kit** [comment]
Ah, I just noticed ruby 3.0.4 is suitable for developing this project, and 3.1.0 fails rubocop 🙇

File: deliver/lib/deliver/runner.rb [hunk 44]
```diff
@@ -270,25 +270,34 @@ def submit_for_review
...
+    def transporter_for_selected_team(upload: false)
       # Use JWT auth
       api_token = Spaceship::ConnectAPI.token
+      api_key = if options[:api_key].nil? && !options[:api_key_path].nil?
+                  # Load api key info if user set api_key_path, not api_key
+                  { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
+                elsif !options[:api_key].nil?
+                  options[:api_key]
+                else
+                  nil
```
Comment (AliSoftware) [inline deliver/lib/deliver/runner.rb:282]: This is the redundant `else` that the linter is warning your about in [this CI run](https://app.circleci.com/pipelines/github/fastlane/fastlane/4827/workflows/f3ddde11-9de4-4d64-990f-5d70a2184212/jobs/85161?invite=true#step-107-102)

File: pilot/lib/pilot/build_manager.rb [hunk 45]
```diff
@@ -389,15 +389,24 @@ def expire_previous_builds(build)
     def transporter_for_selected_team(options)
       # Use JWT auth
       api_token = Spaceship::ConnectAPI.token
+      api_key = if options[:api_key].nil? && !options[:api_key_path].nil?
+                  # Load api key info if user set api_key_path, not api_key
+                  { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
+                elsif !options[:api_key].nil?
+                  options[:api_key]
+                else
+                  nil
```
Comment (AliSoftware) [inline pilot/lib/pilot/build_manager.rb:398]: This is the redundant `else` that the linter is warning your about in [this CI run](https://app.circleci.com/pipelines/github/fastlane/fastlane/4827/workflows/f3ddde11-9de4-4d64-990f-5d70a2184212/jobs/85161?invite=true#step-107-105)

**Review by AliSoftware — COMMENTED** [review]
@freddi-kit In case you don't solve your issues with running `rubocop` on your machine, here are the violations that the CI run found. Hope that helps 🙂

File: deliver/lib/deliver/runner.rb (hunk 44 above)
Comment (freddi-kit) [reply deliver/lib/deliver/runner.rb]: Oh, Thank you. I success to install 3.0.4 in my machine and applied rubocop. And I also add some original changes in https://github.com/fastlane/fastlane/pull/20631/commits/38f23ee3775e0fdf62c5aee013c6bc9842223ba9

**Review by giginet — APPROVED** [review]
LGTM! I can't wait to merge this PR!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 14 above)
Comment (raid5) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Awesome this works great! I was able to successfully upload to TestFlight now.

**Comment by giginet** [comment]
@AliSoftware Hi. We need your eyes 👀  before merging. Thank you for your effort in reviewing!

**Review by joshdholtz — APPROVED** [review]
This looks good to me! Thank you to @freddi-kit and everyone involved with this 🥰 

Personal life is super crazy right now so I haven't been able to focus as much of time so appreciate all of you! ❤️

**Comment by Lutzifer** [comment]
I just got this message
```
[09:32:10]: Ready to upload new build to TestFlight (App: 1426398023)...
undefined method `build_provider_ids_command' for #<FastlaneCore::AltoolTransporterExecutor:0x000000010bedcec8>

      command = @transporter_executor.build_provider_ids_command(@user, @password, @jwt)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  build_upload_command
```

**Comment by freddi-kit** [comment]
I found there is other case that account has many team id. Let me fix it

**Comment by kielgillard** [comment]
> I found there is other case that account has many team id. Let me fix it

Some heroes don't wear capes, @freddi-kit 😁

File: deliver/lib/deliver/runner.rb [hunk 46]
```diff
@@ -270,25 +270,32 @@ def submit_for_review
...
-    def transporter_for_selected_team
+    def transporter_for_selected_team(upload: false)
       # Use JWT auth
       api_token = Spaceship::ConnectAPI.token
+      api_key = if options[:api_key].nil? && !options[:api_key_path].nil?
+                  # Load api key info if user set api_key_path, not api_key
+                  { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
+                else
+                  options[:api_key]
+                end
```
Comment (AliSoftware) [inline deliver/lib/deliver/runner.rb:281]: I have no idea how the various api token / api key path options work (haven't looked into it in details), but isn't this strange here that we test on `api_key_path` being provided… but don't use its value at all here? Felt strange when I read this code and made me think there was a typo in the condition and option name at first.

Given that the `api_token = Spaceship::ConnectAPI.token` value comes from [those lines in `login` that are the ones using the `options[:api_key_path]`](https://github.com/fastlane/fastlane/blob/38f23ee3775e0fdf62c5aee013c6bc9842223ba9/deliver/lib/deliver/runner.rb#L30-L32), I'm assuming that's why it works in the end… but wouldn't it make more sense and help readability of the code to test `!api_token.nil?` instead of `!options[:api_key_path].nil?` here for consistency (since that's the value we end up using on line 278 after all)?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:198]: This is indeed strange and reads as if this condition was the opposite of what it is supposed to mean. Maybe a bad wording of the variable or whatnot, but in the end it seems that if there's a bug here that would not be just on this new AltoolTransporter implementation, so I'd say that'd be something to look at more globally in a separate PR (i.e. investigate for all transporters, not the one added to this PR) at some point later.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 47]
```diff
@@ -180,9 +180,130 @@ def additional_upload_parameters
...
+        # This is key for non-verbose mode
+
+        # The format of altool's result with error is like below
+        # > *** Error: Error uploading '...'.
+        # > *** Error: ...
+        # > {
+        # >     NSLocalizedDescription = "...",
+        # >     ...
+        # > }
+        # So this line tries to find the line which has "*** Error:" prefix from bottom of log
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:231]: Great explanatory comment there 👍 👌

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 48]
```diff
@@ -180,9 +180,130 @@ def additional_upload_parameters
...
+        end
+        UI.message("Application Loader output above ^")
+        @errors.each { |error| UI.error(error) }
+      end
+
+      yield(@all_lines) if block_given?
+      exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil, api_key = nil)
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:245]: I'd love for this method to use named parameters at some point (`build_upload_command(username:, password:, source: "/tmp", provider_short_name: "", jwt: nil, platform: nil, api_key: nil)` for easier-to-read call sites; but that's just a code-style nitpick and not a blocker at all, and can be ironed out in a separate PR, so no worries.

File: fastlane_core/spec/helper_spec.rb [hunk 49]
```diff
@@ -178,7 +180,13 @@
       context "#itms_path" do
         it "default", requires_xcode: true do
           stub_const('ENV', { 'FASTLANE_ITUNES_TRANSPORTER_PATH' => nil })
-          expect(FastlaneCore::Helper.itms_path).to match(/itms/)
+
+          if FastlaneCore::Helper.xcode_at_least?("14")
+            expect(FastlaneCore::UI).to receive(:user_error!).with(/Could not find transporter/)
+            expect { FastlaneCore::Helper.itms_path }.not_to raise_error
```
Comment (AliSoftware) [inline fastlane_core/spec/helper_spec.rb:186]: 👌

File: pilot/lib/pilot/build_manager.rb [hunk 50]
```diff
@@ -389,15 +389,22 @@ def expire_previous_builds(build)
     def transporter_for_selected_team(options)
       # Use JWT auth
       api_token = Spaceship::ConnectAPI.token
+      api_key = if options[:api_key].nil? && !options[:api_key_path].nil?
+                  # Load api key info if user set api_key_path, not api_key
+                  { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
```
Comment (AliSoftware) [inline pilot/lib/pilot/build_manager.rb:394]: Same question as above regarding testing `options[:api_key_path].nil?` instead of `api_token.nil?`

**Review by AliSoftware — APPROVED** [review]
Only reviewed the code diff once again (i.e. didn't test the code in practice) but looks good now, great work @freddi-kit!

Only nit I left was about consistency on the test of `api_key_path` (see [below](https://github.com/fastlane/fastlane/pull/20631#discussion_r970671832)), but otherwise all looks good and ready to ship! Nice work 👍 👏 

---

TODO, but **in separate PRs later**, as those should not be blockers for this PR:
 - [ ] Add [unit tests around that `altool` output parsing](https://github.com/fastlane/fastlane/pull/20631#issuecomment-1244812069) when you have time
 - [ ] Add unit test about provider id parser when @freddi-kit have time
 - [ ] [Improve `altool` output parsing reliability by switching to using `--output-format json`](https://github.com/fastlane/fastlane/pull/20631#discussion_r970908801)
 - [ ] Investigate about [that `hide_output` logic that… might be inverted?](https://github.com/fastlane/fastlane/pull/20631/files#r965624132)… but if so, would be the case for all transporters, and not specific to the one you added here — hence a separate and low-priority PR
 - [ ] Celebrate! 🎉 

> Some heroes don't wear capes, @freddi-kit 😁

Well said! 😃

**Comment by freddi-kit** [comment]
@Lutzifer https://github.com/fastlane/fastlane/pull/20631/commits/30839b923e855b01d3c6d014f967d15652a78676 fixed, could you check it?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 47 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:231]: Thank you!

**Comment by Lutzifer** [comment]
> @Lutzifer [30839b9](https://github.com/fastlane/fastlane/commit/30839b923e855b01d3c6d014f967d15652a78676) fixed, could you check it?

Thank you, the error is gone now 🎉

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 8 above)
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:198]: Let me check it in other PR. I also interested in the current code 👀

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 48 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:245]: I see, since `build_upload_command`'s style is same with other executer class so it would be kind of refactoring. I think I can do it later PR 🙇

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:245]: Totally 👍  no need to fix this in this PR given the refactoring it will involve indeed. And not that critical if we don't do it anyway to be honest 🙃

**Comment by freddi-kit** [comment]
@AliSoftware could you help adding TODO list below?

- [ ] Add unit test about provider id parser when @freddi-kit  have time

File: deliver/lib/deliver/runner.rb (hunk 46 above)
Comment (freddi-kit) [reply deliver/lib/deliver/runner.rb:281]: > I have no idea how the various api token / api key path options work

Yes. me too. It is very hard for me to understand all 😂 

> but it feels odd here that we test on api_key_path being provided… but don't use its value at all here? (made me think there was a typo in the condition and option name at first tbh).

This represents api_token is provided if user set `api_key_path` option but `api_key_path` no longer used here. I wrote so to solve api_key_path issue which is reported (maybe, my brai focused to write to handle `api_key_path` too much)

> but wouldn't it make more sense and help readability of the code to test !api_token.nil? instead of !options[:api_key_path].nil? here for consistency (since that's the value we end up consuming on line 278 after all)?

I think it looks good idea, let me test here and commit soon

Comment (freddi-kit) [reply deliver/lib/deliver/runner.rb]: fixed! https://github.com/fastlane/fastlane/pull/20631/commits/ab02d6dacb2c2a2b9d8ca82a5dd991a4315fbcb2

**Comment by AliSoftware** [comment]
> @AliSoftware could you help adding TODO list below?

Edited [my comment above](https://github.com/fastlane/fastlane/pull/20631#pullrequestreview-1107282582) to add it 🙂

**Comment by freddi-kit** [comment]
@AliSoftware There are some additional changes to handle https://github.com/fastlane/fastlane/pull/20631#issuecomment-1246363894, could you check these commits?

https://github.com/fastlane/fastlane/pull/20631/files/38f23ee3775e0fdf62c5aee013c6bc9842223ba9..71e57d60cad428d53766a4aac6a9dc4eb2567f39

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 51]
```diff
@@ -572,8 +586,12 @@ def execute(command, hide_output)
   end
 
   class ItunesTransporter
-    # Matches a line in the provider table: "12  Initech Systems Inc     LG89CQY559"
-    PROVIDER_REGEX = /^\d+\s{2,}.+\s{2,}[^\s]+$/
+    # Matches a line in the iTMSTransporter provider table: "12  Initech Systems Inc     LG89CQY559"
+    ITMS_PROVIDER_REGEX = /^\d+\s{2,}.+\s{2,}[^\s]+$/
+    # Matches a line in the altool provider talble's separator
```
Comment (freddi-kit) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:591]:
```suggestion
    # Matches a line in the altool provider table's separator
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 52]
```diff
@@ -252,13 +252,27 @@ def build_upload_command(username, password, source = "/tmp", provider_short_nam
         ("-p #{password.shellescape}" unless use_api_key),
         ("--apiKey #{api_key[:key_id]}" if use_api_key),
         ("--apiIssuer #{api_key[:issuer_id]}" if use_api_key),
+        ("--asc-provider #{provider_short_name}" if !use_api_key && !provider_short_name.to_s.empty?),
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:255]: Not that it really matter, but I'm expecting `rubocop` linter to complain and suggest changing `if !` to `unless` here 🤔 
```suggestion
        ("--asc-provider #{provider_short_name}" unless use_api_key || provider_short_name.to_s.empty?),
```

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 53]
```diff
@@ -572,8 +586,12 @@ def execute(command, hide_output)
...
 
   class ItunesTransporter
-    # Matches a line in the provider table: "12  Initech Systems Inc     LG89CQY559"
-    PROVIDER_REGEX = /^\d+\s{2,}.+\s{2,}[^\s]+$/
+    # Matches a line in the iTMSTransporter provider table: "12  Initech Systems Inc     LG89CQY559"
+    ITMS_PROVIDER_REGEX = /^\d+\s{2,}.+\s{2,}[^\s]+$/
+    # Matches a line in the altool provider table's separator
+    # ------------------- ----------------- ------------------------------------ ----------
+    # Initech Systems Inc LG89CQY559        xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx LG89CQY559
+    ALTOOL_SEPARATOR_PROVIDER_REGEX = /^\-{1,}\s{1}\-{1,}\s{1}\-{1,}\s{1}\-{1,}\s+$/
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:594]: Couldn't we use `--output-format json` when invoking `altool --list-providers` and parse that as JSON instead of text? Would feel more reliable than this if it's possible?

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:594]: > `--output-format json`

wow, I did not know such great option. I lost time by making so complex regex parser ...
Thank you!!!!

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 52 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:255]: rubocop did say nothing about it but i learned unless is better, let me fix it

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 53 above)
Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:594]: Yeah only discovered it 10mn ago by accident too when I wondered if `altool` didn't offer such option and looked at its help page for it. I wonder if it couldn't even help with the regular upload step as well (eg to parse `*** Error` logs etc, in case that json output present those in an easier-to-parse format after all)?

That being said, we could also merge the PR as is to avoid blocking, and open a separate subsequent PR to improve on that if you prefer not spending too much time on this now.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 52 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: done! https://github.com/fastlane/fastlane/pull/20631/commits/cd2c504c7ba16769aadc2dd9ab465a177c263a9b

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 53 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: it can be done easily by https://github.com/fastlane/fastlane/pull/20631/commits/4f4d3eefded04f86147bfa044a9b62fd542d7420, and also let me check how can I improve it in Error case.

Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: > That being said, we could also merge the PR as is to avoid blocking, and open a separate subsequent PR to improve on that if you prefer not spending too much time on this now.

I decided to do it later PR because it makes some other additional changes 🙇 since Xcode 14 is now released, it may be better to merge it as possible

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Good call, works for me 👍 

Updated [checklist above](https://github.com/fastlane/fastlane/pull/20631#pullrequestreview-1107282582) :sigh

**Comment by EvanMasterson** [comment]
> > FWIW I just switched our Gemfile over the head of this branch and re-ran our CI deployment workflow and it worked without any other changes.
> 
> +1 for same experience here, w/ App Store Connect API key in use too. Great work @freddi-kit 👍

+1 working perfectly for us with App Store Connect API key with changelog waiting!

**Comment by lpusok** [comment]
Apple ID auth is working (an account with multiple teams).

**Comment by danilobuerger** [comment]
I just tried with the current commit (`cd2c504c7ba16769aadc2dd9ab465a177c263a9b`) and it errors out.
I am setting an ENV var with
```
{
  "key_id": "",
  "issuer_id": "",
  "key": ""
}
``` 
and then using it in fastlane like so:
```
testflight(
  app_identifier: "myappidentifier",
  skip_waiting_for_build_processing: true,
  api_key: ENV["myenvvar"]
)
```
I am getting the following error:
```
[altool] *** Error: Unable to upload archive. You must specify both '--apiKey' and '--apiIssuer'. (-1011)
[altool]  {
[altool]     NSLocalizedDescription = "Unable to upload archive.";
[altool]     NSLocalizedFailureReason = "You must specify both '--apiKey' and '--apiIssuer'.";
[altool] }
Application Loader output above ^
The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
Could not download/upload from App Store Connect!
```
this worked before as is with fastlane, nothing changed expect switching the fastlane gem and using xcode 14.

**Comment by freddi-kit** [comment]
@danilobuerger Fixed, could you help checking it?

**Comment by danilobuerger** [comment]
@freddi-kit works now, thanks!

**Comment by freddi-kit** [comment]
Test is failed on not related place (and I confirmed rspec has no problem). How can I re-run test?

**Comment by freddi-kit** [comment]
I wish I covered all cases I need to check now ... 😭

**Comment by freddi-kit** [comment]
@AliSoftware https://github.com/fastlane/fastlane/pull/20631/files/cd2c504c7ba16769aadc2dd9ab465a177c263a9b..599ab2bdf4f013df049f3ac0ef92e175a91ddfdb I added addtional code to handle https://github.com/fastlane/fastlane/pull/20631#issuecomment-1247198719, please review it if you have time 🙇

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 54]
```diff
@@ -648,15 +812,37 @@ def provider_ids
...
         handle_two_step_failure(ex)
         return provider_ids
+      ensure
+        if use_api_key
+          FileUtils.rm_rf(api_key[:key_dir]) unless api_key.nil?
+        end
       end
 
-      lines.map { |line| provider_pair(line) }.compact.to_h
+      @is_altool ? parse_altool_provider_info(lines) : parse_itsm_provider_info(lines)
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:821]: It seems to be strange that `ITunesTransporter` knows `is_altool`.
These parser methods should be an abstraction.

How about these changes?

- Remove `is_atool` instance variable.
- Implement `privider_ids` to each executors
    - Just call it of each executor here
- Move `parse_itsm_provider_info` to the base class or Executor class. Call them internally.

**Review by giginet — COMMENTED** [review]
I think you can abstract each executor. See line commands for detail.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 54 above)
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: done! https://github.com/fastlane/fastlane/pull/20631/commits/8be9c7ec4703cc3eb28ae9172a07fd558b9577cf

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 55]
```diff
@@ -180,9 +180,145 @@ def additional_upload_parameters
...
+        end
+        UI.message("Application Loader output above ^")
+        @errors.each { |error| UI.error(error) }
+      end
+
+      yield(@all_lines) if block_given?
+      exit_status.zero?
+    end
+
+    def build_upload_command(username, password, source = "/tmp", provider_short_name = "", jwt = nil, platform = nil, api_key = nil)
```
[the remark this answers is not in the document]
Comment (freddi-kit) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:274]: done! https://github.com/fastlane/fastlane/pull/20631/commits/8e7d6f3349ad56c112444df7f84d86831d73b64a

**Comment by Zandor300** [comment]
This PR works perfectly fine when I build and deploy using it. Can't all these last polish/edge case things be done in a separate PR so this one can be merged and released?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 56]
```diff
@@ -180,9 +209,166 @@ def additional_upload_parameters
...
+        ("-u #{username.shellescape}" unless use_api_key),
+        ("-p #{password.shellescape}" unless use_api_key),
+        ("--apiKey #{api_key[:key_id]}" if use_api_key),
+        ("--apiIssuer #{api_key[:issuer_id]}" if use_api_key),
+        "--output-format json"
+      ].compact.join(' ')
+    end
+
+    def build_download_command(username, password, apple_id, destination = "/tmp", provider_short_name = "", jwt = nil)
+      raise "This feature has not been implemented yet with altool for Xcode 14"
```
Comment (giginet) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:307]: 👍

**Review by giginet — APPROVED** [review]
Nice abstraction! LGTM.

@AliSoftware If you don't have any concerns yet. I'm going to merge this PR.
Could you retake a look to approve?
Thank you for all!

**Comment by EvanMasterson** [comment]
Upon this being merged, how long typically until a new version of Fastlane is released, say 2.209.2?

**Comment by giginet** [comment]
@EvanMasterson  We'll release the newest ASAP.

File: deliver/lib/deliver/runner.rb [hunk 57]
```diff
@@ -276,8 +276,8 @@ def transporter_for_selected_team(upload: false)
       api_key = if options[:api_key].nil? && !api_token.nil?
                   # Load api key info if user set api_key_path, not api_key
                   { key_id: api_token.key_id, issuer_id: api_token.issuer_id, key: api_token.key_raw, is_key_content_base64: api_token.is_key_content_base64 }
-                else
-                  options[:api_key]
+                elsif !options[:api_key].nil?
+                  options[:api_key].transform_keys(&:to_sym)
```
Comment (AliSoftware) [inline deliver/lib/deliver/runner.rb:280]: 👌 Nice and clean solution to handle ENV-provided values 👍

**Review by AliSoftware — APPROVED** [review]
> @AliSoftware If you don't have any concerns yet. I'm going to merge this PR.
Could you retake a look to approve?

@giginet It seems I'm having computer and network issues this morning (thanks, last night storm…) that makes it tricky for me to re-review this one last time on my end at this moment; but I say let's merge this indeed, ship a new version ASAP, and address all the remaining refinements in a separate PR 👍

**Comment by freddi-kit** [comment]
Thank you all! (Review, Feedback and comments!)

**Comment by AliSoftware** [comment]
> TODO
>
> - [x] Celebrate 🎉

**Comment by azilbershtein** [comment]
@freddi-kit Thanks and Great job!
One issue I got into is this: (I'm using master on my Gemfile)
bundler: failed to load command: fastlane (~/vendor/bundle/ruby/2.7.0/bin/fastlane)
~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/itunes_transporter.rb:876:in `api_key_with_p8_file_path': \e[31m[!] private method `clone' called for #<Hash:0x00007f9338ab0108>\e[0m (NoMethodError)

I'm using the pilot method with api_key
{key: "****, "issuer_id": ***, "key_id: **}
Did anyone get this error?

**Comment by freddi-kit** [comment]
Oh, than you for reporting 🙇 Let me investigate it @azilbershtein

**Comment by freddi-kit** [comment]
@azilbershtein could you share me detailed stack trace?

**Comment by azilbershtein** [comment]
`bundler: failed to load command: fastlane (~/vendor/bundle/ruby/2.7.0/bin/fastlane)
[599](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L599)~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/itunes_transporter.rb:876:in `api_key_with_p8_file_path': \e[31m[!] private method `clone' called for #<Hash:0x00007f9338ab0108>\e[0m (NoMethodError)
[600](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L600)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/itunes_transporter.rb:769:in `upload'
[601](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L601)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/pilot/lib/pilot/build_manager.rb:50:in `upload'
[602](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L602)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
[603](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L603)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
[604](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L604)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
[605](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L605)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
[606](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L606)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:229:in `chdir'
[607](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L607)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
[608](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L608)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[609](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L609)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[610](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L610)	from Fastfile:107:in `block (2 levels) in parsing_binding'
[611](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L611)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/lane.rb:33:in `call'
[612](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L612)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[613](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L613)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[614](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L614)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:45:in `execute'
[615](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L615)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
[616](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L616)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[617](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L617)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
[618](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L618)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[619](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L619)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[620](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L620)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[621](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L621)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
[622](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L622)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[623](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L623)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
[624](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L624)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
[625](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L625)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
[626](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L626)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/bin/fastlane:23:in `<top (required)>'
[627](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L627)	from ~/vendor/bundle/ruby/2.7.0/bin/fastlane:25:in `load'
[628](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L628)	from ~/vendor/bundle/ruby/2.7.0/bin/fastlane:25:in `<top (required)>'
[629](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L629)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `load'
[630](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L630)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
[631](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L631)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:28:in `run'
[632](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L632)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:494:in `exec'
[633](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L633)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[634](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L634)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[635](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L635)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[636](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L636)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:30:in `dispatch'
[637](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L637)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[638](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L638)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:24:in `start'
[639](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L639)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/exe/bundle:49:in `block in <top (required)>'
[640](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L640)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
[641](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L641)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/exe/bundle:37:in `<top (required)>'
[642](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L642)	from /usr/local/opt/ruby@2.7/bin/bundle:23:in `load'
[643](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L643)	from /usr/local/opt/ruby@2.7/bin/bundle:23:in `<main>'
[644](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L644)~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/itunes_transporter.rb:876:in `api_key_with_p8_file_path': private method `clone' called for #<Hash:0x00007f9338ab0108> (NoMethodError)
[645](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L645)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/itunes_transporter.rb:769:in `upload'
[646](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L646)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/pilot/lib/pilot/build_manager.rb:50:in `upload'
[647](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L647)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
[648](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L648)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
[649](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L649)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
[650](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L650)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
[651](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L651)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:229:in `chdir'
[652](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L652)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
[653](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L653)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
[654](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L654)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
[655](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L655)	from Fastfile:107:in `block (2 levels) in parsing_binding'
[656](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L656)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/lane.rb:33:in `call'
[657](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L657)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[658](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L658)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[659](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L659)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/runner.rb:45:in `execute'
[660](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L660)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
[661](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L661)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
[662](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L662)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
[663](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L663)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
[664](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L664)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
[665](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L665)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
[666](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L666)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
[667](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L667)	from ~/vendor/bundle/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
[668](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L668)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
[669](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L669)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
[670](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L670)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
[671](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L671)	from ~/vendor/bundle/ruby/2.7.0/bundler/gems/fastlane-b4070a8d9a70/bin/fastlane:23:in `<top (required)>'
[672](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L672)	from ~/vendor/bundle/ruby/2.7.0/bin/fastlane:25:in `load'
[673](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L673)	from ~/vendor/bundle/ruby/2.7.0/bin/fastlane:25:in `<top (required)>'
[674](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L674)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `load'
[675](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L675)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
[676](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L676)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli/exec.rb:28:in `run'
[677](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L677)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:494:in `exec'
[678](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L678)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
[679](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L679)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
[680](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L680)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
[681](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L681)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:30:in `dispatch'
[682](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L682)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
[683](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L683)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/cli.rb:24:in `start'
[684](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L684)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/exe/bundle:49:in `block in <top (required)>'
[685](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L685)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
[686](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L686)	from /usr/local/Cellar/ruby@2.7/2.7.6_1/lib/ruby/gems/2.7.0/gems/bundler-2.2.4/exe/bundle:37:in `<top (required)>'
[687](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L687)	from /usr/local/opt/ruby@2.7/bin/bundle:23:in `load'
[688](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L688)	from /usr/local/opt/ruby@2.7/bin/bundle:23:in `<main>'
[689](https://gitlab.com/chegginc/learning-services/mobile/ios/sox/ios-chegg/-/jobs/3032569275#L689)make: *** [upload-to-store] Error 1`

**Comment by freddi-kit** [comment]
@azilbershtein could you share me the detail Fastfile around `upload_to_testflight `

**Comment by azilbershtein** [comment]
@freddi-kit  Thanks!

    json_api_key = JSON.parse(api_key, symbolize_names: true)
 
   #The json_api_key is the format of {key: "****, "issuer_id": ***, "key_id: **}

    pilot(
      api_key: json_api_key,
      app_identifier: BUNDLE_IDENTIFIER_APPSTORE,
      apple_id: APP_ID,
      ipa: ipa_path,
      team_id: TEAM_ID,
      team_name: TEAM_NAME,
      dev_portal_team_id: DEV_PORTAL_TEAM_ID,
      notify_external_testers: false,
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )

**Comment by AliSoftware** [comment]
Since we don't need a deep copy of the `Hash` — as [we're only adding a key at the root level of the Hash and not changing anything at deeper levels](https://github.com/fastlane/fastlane/pull/20631/files#diff-e4392686971e0801abe75321cc8a4c90eb2f2c971734d8cc88b0ac5fef5ee12dR876-R877) — I think we could consider replacing `.clone` with `.dup` (which does a shallow-copy, but it's ok in our case) on [this line](https://github.com/fastlane/fastlane/pull/20631/files#diff-e4392686971e0801abe75321cc8a4c90eb2f2c971734d8cc88b0ac5fef5ee12dR876) which seems to be the culprit.

That being said, I'd expect `some_hash.clone` to work and to be a private method, so not sure why it crashes here and I'd still be curious to understand why it does in that particular case. But maybe `dup` (which seems more common in ruby?) hopefully won't crash like `clone` does, so it might be worth a try.

**Comment by freddi-kit** [comment]
@azilbershtein 

```ruby
gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "altool-upload"
```

could you try this branch? I updated fixing recommended by https://github.com/fastlane/fastlane/pull/20631#issuecomment-1248022225

**Comment by Kiruel** [comment]
Hi ! I just use your branch and got the same result:

<details>
  <summary>Logs</summary>
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [!] Could not find transporter at /Applications/Xcode.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation. (FastlaneCore::Interface::FastlaneError)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/helper.rb:244:in `itms_path'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:447:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:576:in `upload'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/build_manager.rb:50:in `upload'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:123:in `block (2 levels) in parsing_binding'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Could not find transporter at /Applications/Xcode.app/Contents/Developer/. Please make sure you set the correct path to your Xcode installation. (FastlaneCore::Interface::FastlaneError)
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/helper.rb:244:in `itms_path'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:447:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:576:in `upload'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/pilot/lib/pilot/build_manager.rb:50:in `upload'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:123:in `block (2 levels) in parsing_binding'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.209.1/bin/fastlane:23:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:31:in `dispatch'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
        from /usr/local/bin/bundle:23:in `load'
        from /usr/local/bin/bundle:23:in `<main>'
</details>

**Comment by freddi-kit** [comment]
@Kiruel it is not same result. It looks fastlane tries to find old transporter and it fails

**Comment by freddi-kit** [comment]
@Kiruel please wait for official gem update.

**Comment by freddi-kit** [comment]
@Kiruel  please try official rubygem 2.210.0 version instead of master/freddi-kit branch

**Comment by azilbershtein** [comment]
@freddi-kit It works with 
gem "fastlane", :git => "https://github.com/freddi-kit/fastlane.git", :branch => "pilot-apikey-dup"
Thank you!

**Comment by freddi-kit** [comment]
@azilbershtein cool, let me create patch later

**Comment by Kiruel** [comment]
I will test in couple hours a new version with the new fastlane version. Just a question the `api_key_path` works on this version ?

**Comment by Kiruel** [comment]
Amazing job thanks @freddi-kit :) !

**Comment by vadimbelyaev** [comment]
Just tested my CI pipeline with Fastlane 2.210.0 and Xcode 14, it all worked like a charm, no configuration changes needed. Truly amazing work, thanks you @freddi-kit and all the contributors! 🚀
