### PR TITLE
[pilot + spaceship] temporary workaround for remove bulid trains API call and replace beta group API calls

### LINKED ISSUE #14521: [spaceship, pilot] Getting "410 gone"
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Managed to upload ipa to testflight but getting 410 when waiting for the build to be processed. Noticed that `pilot builds` also fails.

##### Command executed

`fastlane pilot builds`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> $ fastlane pilot builds
[✔] 🚀
[14:20:45]: fastlane detected a Gemfile in the current directory
[14:20:45]: however it seems like you don't use `bundle exec`
[14:20:45]: to launch fastlane faster, please use
[14:20:45]:
[14:20:45]: $ bundle exec fastlane pilot builds
[14:20:45]:
[14:20:45]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:20:46]: Login to App Store Connect (engineering@shoguninc.com)
[14:20:49]: Login successful

Looking for related GitHub issues on fastlane/fastlane...

/Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:321:in `handle_response': [!] <html> (Spaceship::UnexpectedResponse)
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 410 Gone</title>
</head>
<body><h2>HTTP ERROR 410</h2>
<p>Problem accessing /v2/providers/118458784/apps/1383073333/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
</body>
</html>

	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/client.rb:31:in `get_build_trains'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build_trains.rb:16:in `all'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:110:in `all'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/test_flight/build.rb:121:in `all_processing_builds'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/spaceship/lib/spaceship/tunes/application.rb:321:in `all_processing_builds'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:111:in `list'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:90:in `block (2 levels) in run'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:166:in `run'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/pilot/lib/pilot/commands_generator.rb:18:in `start'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/gems/fastlane-2.119.0/bin/fastlane:23:in `<top (required)>'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /Users/stefano/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
 </pre>
</details>

### LINKED ISSUE #14540: latest_testflight_build_number
### Issue Description
latest_testflight_build_number
Use action (latest_testflight_build_number), I can't get the right build_number. It aways 1

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.4                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.20.1 (Apple Git-117)                             |
| Installation Source         | /usr/bin/fastlane                                              |
| Host                        | Mac OS X 10.14.4 (18E226)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.5                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.2                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import_from_git(url: 'git@gitlab.corp.cootek.com:pgd_portfolio/sdk/ios/fastlane-for-release.git', branch: 'master')


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ios.step.tracker.stepcounter.caloriecounter.pedometer") # The bundle identifier of your app

apple_id("muse@fekagame.com")
#apple_id("theo.chen@cootek.cn")

itc_team_id("119138503") # App Store Connect Team ID
team_id("NG76ZL6YRF") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.119.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-pgyer | 0.2.2   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| CFPropertyList            | 3.0.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.8.2        |
| unicode-display_width     | 1.5.0        |
| plist                     | 3.5.0        |
| addressable               | 2.6.0        |
| tty-cursor                | 0.6.1        |
| json                      | 2.2.0        |
| dotenv                    | 2.7.2        |
| faraday_middleware        | 0.13.1       |
| mime-types-data           | 3.2019.0331  |
| digest-crc                | 0.4.1        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| google-cloud-storage      | 1.16.0       |
| emoji_regex               | 1.0.1        |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| psych                     | 2.1.0.1      |
| fastlane-plugin-pgyer     | 0.2.2        |
</details>

*generated on:* **2019-04-09**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #14521 
Fixes #14540

### Motivation and Context
We lost a legacy API call today 🙏
```
<p>Problem accessing /v2/providers/xxxx/apps/xxxxx/platforms/ios/trains. Reason:
<pre>    Gone</pre></p>
```

This caused `pilot` to break when distributing and when also calling `fastlane pilot builds`

### Description
This temporary fix is super gross.

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: fastlane_core/lib/fastlane_core/build_watcher.rb [hunk 1]
```diff
@@ -42,24 +42,30 @@ def watching_build(app_id: nil, platform: nil)
...
 
       def matching_build(watched_train_version: nil, watched_build_version: nil, app_id: nil, platform: nil)
-        matched_builds = Spaceship::TestFlight::Build.builds_for_train(app_id: app_id, platform: platform, train_version: watched_train_version, retry_count: 2)
-        matched_builds.find { |build| build.build_version == watched_build_version }
+        client = Spaceship::ConnectAPI::Base.client
+        build_deliveries = client.get_build_deliveries(filter: { app: app_id, cfBundleVersion: watched_build_version}, limit: 1)
+
+        # Actually only show processed builds
+        matched_builds = Spaceship::TestFlight::Build.all(app_id: app_id, platform: platform)
+        matched_build = matched_builds.find { |build| build.build_version.to_s == watched_build_version.to_s }
```
Comment (snatchev) [inline fastlane_core/lib/fastlane_core/build_watcher.rb]: Can this be done by a single API request?

File: spaceship/lib/spaceship/connect_api/client.rb [hunk 2]
```diff
@@ -274,12 +287,12 @@ def post_beta_app_review_submissions(build_id: nil)
...
           req.headers['Content-Type'] = 'application/json'
         end
-        handle_response(response)
+        handle_response(response, only_data: only_data)
       end
 
       protected
 
-      def handle_response(response)
+      def handle_response(response, only_data: true)
```
Comment (snatchev) [inline spaceship/lib/spaceship/connect_api/client.rb]: I would create a new method, maybe `handle_data_response`, which uses `handle_data` underneath. Let's try not to change any of the existing method signatures such as `post_beta_build_localizations`

File: spaceship/lib/spaceship/test_flight/build_trains.rb [hunk 3]
```diff
@@ -13,12 +13,76 @@ class BuildTrains < Base
     # See `Spaceship::TestFlight::Build#reload`
 
     def self.all(app_id: nil, platform: nil, retry_count: 3)
-      data = client.get_build_trains(app_id: app_id, platform: platform)
-      trains = {}
+      client = Spaceship::ConnectAPI::Base.client
```
Comment (snatchev) [inline spaceship/lib/spaceship/test_flight/build_trains.rb]: If this is temporary, is our plan to eventually remove the entire model or just this new code-path? If we would like to remove a code-path, can all of this be extracted into its own method so that later it can be removed easier?

**Review by snatchev — CHANGES_REQUESTED** [review]

File: spaceship/lib/spaceship/test_flight/build_trains.rb [hunk 4]
```diff
@@ -13,12 +13,76 @@ class BuildTrains < Base
...
+
+      builds = []
+      included = []
+      cursor = nil
+
+      loop do 
+        builds_resp = client.get_builds(filter: { app: app_id, processingState: "VALID,PROCESSING,FAILED,INVALID"}, limit: 100, sort: "uploadedDate", includes: "buildBetaDetail,betaBuildMetrics,preReleaseVersion,app", cursor: cursor, only_data: false)
```
Comment (snatchev) [inline spaceship/lib/spaceship/test_flight/build_trains.rb]: I see here that `only_data` is set to `false`. Lets make this its own method on the client. Maybe
`client.get_builds_for_build_trains( ... )` or something like that?

File: fastlane_core/lib/fastlane_core/build_watcher.rb (hunk 1 above)
Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/build_watcher.rb]: Actually.... I can hit `get_build_deliveries` and if it returns something than no need to call `Spaceship::TestFlight::Build.all` 🤔

File: spaceship/lib/spaceship/test_flight/build_trains.rb [hunk 5]
```diff
@@ -13,12 +13,76 @@ class BuildTrains < Base
...
+        builds += builds_resp["data"]
+        included += builds_resp["included"]
```
Comment (keith) [inline spaceship/lib/spaceship/test_flight/build_trains.rb]: If you don't have any builds for a given app id, this ends up crashing because the included field appears to not be included in the response:

```
  /Users/ksmiley/.gem/ruby/2.6.0/bundler/gems/fastlane-f0dbe188ade9/spaceship/lib/spaceship/test_flight/build_trains.rb:25:in `+'
  /Users/ksmiley/.gem/ruby/2.6.0/bundler/gems/fastlane-f0dbe188ade9/spaceship/lib/spaceship/test_flight/build_trains.rb:25:in `block in all'
  /Users/ksmiley/.gem/ruby/2.6.0/bundler/gems/fastlane-f0dbe188ade9/spaceship/lib/spaceship/test_flight/build_trains.rb:22:in `loop'
  /Users/ksmiley/.gem/ruby/2.6.0/bundler/gems/fastlane-f0dbe188ade9/spaceship/lib/spaceship/test_flight/build_trains.rb:22:in `all'
```

File: spaceship/lib/spaceship/test_flight/build_trains.rb (hunk 3 above)
Comment (joshdholtz) [reply spaceship/lib/spaceship/test_flight/build_trains.rb]: I think we are going to remove these models if possible 😬

File: fastlane_core/lib/fastlane_core/build_watcher.rb [hunk 6]
```diff
@@ -34,32 +27,30 @@ def wait_for_build_processing_to_be_complete(app_id: nil, platform: nil, train_v
...
-        matched_builds = Spaceship::TestFlight::Build.builds_for_train(app_id: app_id, platform: platform, train_version: watched_train_version, retry_count: 2)
-        matched_builds.find { |build| build.build_version == watched_build_version }
+        # Get build deliveries (newly uploaded processing builds)
+        client = Spaceship::ConnectAPI::Base.client
+        build_deliveries = client.get_build_deliveries(filter: { app: app_id, cfBundleShortVersionString: watched_train_version, cfBundleVersion: watched_build_version }, limit: 1)
+        build_delivery = build_deliveries.first
+
+        # Get processed builds when no longer in build deliveries
+        unless build_delivery
+          matched_builds = Spaceship::TestFlight::Build.all(app_id: app_id, platform: platform)
```
[the remark this answers is not in the document]
Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/build_watcher.rb]: I _think_ I'd like to leave this alone for now until we get our reworked `Spaceship::ConectAPI` module with models in it? I don't want this to stay like this for long but this will need to get reworked in the future anyway so I think I'd prefer to leave it like it is since it "works" 😬😬😬😬😬😬

**Comment by joshdholtz** [comment]
@snatchev Made some of the changes that you mentioned in the review! I think a lot of this will get reworked when we improved `Spaceship::ConnectAPI` and actually have models. Thoughts on if this is good to go? Or should some of that other stuff get reworked still before our next reworked? 😇

**Comment by joshdholtz** [comment]
Going to merge this a prep a new release! What we got right now can go out to the public since it fixes a lot of currently broken things. We will fix improve `Spaceship::ConnectAPI` and come back and clean the rest of this up 🙈

**Comment by rajivshah3** [comment]
Thanks for fixing this so quickly!
