### PR TITLE
[screengrab] check if package is already installed before uninstalling

### LINKED ISSUE #9825: Screengrab: `reinstall_app true` causes failure on Android >= API 25 without app installed
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

* `reinstall_app true` in Screengrabfile.
* Create fresh Android API 25 or 26 emulator (app is not installed).
* screengrab will fail due to IllegalArgumentException for the unknown package.

Running screengrab with emulators running API <25 works fine, but 25 and 26 fail.

The `adb uninstall` behavior has changed:

API <=24:
```
adb uninstall package.doesnt.exist

Exception occurred while dumping:
java.lang.IllegalArgumentException: Unknown package: package.doesnt.exist
	at com.android.server.pm.Settings.isOrphaned(Settings.java:4134)
	at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:18105)
	at com.android.server.pm.PackageManagerService.deletePackage(PackageManagerService.java:15522)
	at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:888)
	at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:792)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:118)
	at android.os.ShellCommand.exec(ShellCommand.java:94)
	at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:18363)
	at android.os.Binder.shellCommand(Binder.java:468)
	at android.os.Binder.onTransact(Binder.java:367)
	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2387)
	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3031)
	at android.os.Binder.execTransact(Binder.java:565)
```

API 25/26:
```
adb uninstall package.doesnt.exist
Failure [DELETE_FAILED_INTERNAL_ERROR]
```

The IllegalArgumentException and error response is an Android issue, but screengrab needs to handle it. Either first checking if the package is installed, or allowing the command to fail.

```
[12:38:33]: Validating app APK
[12:38:33]: $ /Users/user/Library/Android/sdk/build-tools/26.0.0/aapt dump permissions app/build/outputs/apk/app-screenshot-debug.apk
[12:38:33]: ▸ package: com.package.screens
[12:38:33]: ▸ uses-permission: name='android.permission.DISABLE_KEYGUARD'
[12:38:33]: ▸ uses-permission: name='android.permission.WAKE_LOCK'
[12:38:33]: ▸ uses-permission: name='android.permission.WRITE_EXTERNAL_STORAGE'
[12:38:33]: ▸ uses-permission: name='android.permission.READ_EXTERNAL_STORAGE'
[12:38:33]: ▸ uses-permission: name='android.permission.CHANGE_CONFIGURATION'
[12:38:33]: ▸ uses-permission: name='android.permission.BLUETOOTH_ADMIN'
[12:38:33]: ▸ uses-permission: name='android.permission.INTERNET'
[12:38:33]: ▸ uses-permission: name='android.permission.ACCESS_NETWORK_STATE'
[12:38:33]: ▸ uses-permission: name='android.permission.BLUETOOTH'
[12:38:33]: ▸ uses-permission: name='android.permission.RECEIVE_BOOT_COMPLETED'
[12:38:33]: ▸ uses-permission: name='com.google.android.c2dm.permission.RECEIVE'
[12:38:33]: ▸ permission: com.package.screens.permission.C2D_MESSAGE
[12:38:33]: ▸ uses-permission: name='com.package.screens.permission.C2D_MESSAGE'
[12:38:33]: ▸ uses-permission: name='android.permission.ACCESS_COARSE_LOCATION'
[12:38:33]: ▸ uses-permission: name='android.permission.ACCESS_FINE_LOCATION'
[12:38:33]: Uninstalling app APK
[12:38:33]: $ adb -s emulator-5556 uninstall com.package.screens
[12:38:34]: ▸ Exception occurred while executing:
[12:38:34]: ▸ java.lang.IllegalArgumentException: Unknown package: com.package.screens
[12:38:34]: ▸ at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:20603)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17759)
[12:38:34]: ▸ at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:896)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
[12:38:34]: ▸ at android.os.ShellCommand.exec(ShellCommand.java:96)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:20893)
[12:38:34]: ▸ at android.os.Binder.shellCommand(Binder.java:573)
[12:38:34]: ▸ at android.os.Binder.onTransact(Binder.java:473)
[12:38:34]: ▸ at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2638)
[12:38:34]: ▸ at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3466)
[12:38:34]: ▸ at android.os.Binder.execTransact(Binder.java:674)

Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.package.screens
at com.android.server.pm.Settings.isOrphaned(Settings.java:4400)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:20603)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17759)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:896)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:912)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:134)
at android.os.ShellCommand.exec(ShellCommand.java:96)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:20893)
at android.os.Binder.shellCommand(Binder.java:573)
at android.os.Binder.onTransact(Binder.java:473)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2638)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3466)
at android.os.Binder.execTransact(Binder.java:674)
[12:38:34]: Exit status: 255

[!] Exit status: 255

  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/action.rb:98:in `sh'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-automated_test_emulator_run-1.5.1/lib/fastlane/plugin/automated_test_emulator_run/actions/automated_test_emulator_run_action.rb:178:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:47:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-automated_test_emulator_run | 1.5.1   | ✅ Up-To-Date  |

### PR DESCRIPTION
**Pull request by joeboyscout04**
…to prevent error on later versions of Android.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #9825  by checking if app is installed before attempting to uninstall. 

### Description

Run `adb -s #{device_serial} shell pm list packages #{app_package_name}"` to determine packages on the device, and then check to make sure the package exists before uninstalling. 
Based on suggestions in comments of #9825 

Tested against a physical device that has the issue on newer Android devices (Nexus 5, Android 8.1.0).  Also tested on older Android device (Android 5.x).  

Thanks!

### CODE REVIEW

**Comment by joeboyscout04** [comment]
I signed it!

**Review by vanniktech — APPROVED** [review]

File: screengrab/lib/screengrab/runner.rb [hunk 1]
```diff
@@ -235,7 +235,14 @@ def run_tests(device_serial, app_apk_path, tests_apk_path, test_classes_to_use,
 
       @config[:locales].each do |locale|
         if @config[:reinstall_app]
-          uninstall_apks(device_serial, @config[:app_package_name], @config[:tests_package_name])
```
Comment (janpio) [inline screengrab/lib/screengrab/runner.rb]: Is it safe _not_ to do the same check for `tests_package_name`?

File: screengrab/lib/screengrab/runner.rb [hunk 2]
```diff
@@ -195,15 +195,23 @@ def install_apks(device_serial, app_apk_path, tests_apk_path)
...
-                      print_command: true)
+      packages = run_adb_command("adb -s #{device_serial} shell pm list packages #{app_package_name}",
+                                 print_all: true,
+                                 print_command: true)
 
-      UI.message('Uninstalling tests APK')
-      run_adb_command("adb -s #{device_serial} uninstall #{tests_package_name}",
-                      print_all: true,
-                      print_command: true)
+      if packages =~ /#{app_package_name}/
```
Comment (janpio) [inline screengrab/lib/screengrab/runner.rb]: Hm, couldn't this false positive if the `app_package_name` is part of `tests_package_name` (e.g. suffix `.test`)?

Comment (janpio) [reply screengrab/lib/screengrab/runner.rb]: We have an `AdbHelper` class that could be used to house a new `installed_packages` that returns a list of package names that are installed instead of 1 big string. Would that make sense?

Comment (janpio) [reply screengrab/lib/screengrab/runner.rb]: @joeboyscout04?

Comment (joeboyscout04) [reply screengrab/lib/screengrab/runner.rb]: It's a great suggestion, sorry I've been away on vacation and holidays until this week. Hopefully will get some time to look at it soon.

**Review by joshdholtz — DISMISSED** [review]
Would you also be able to write some tests around this as well? I'm on sure exactly what `adb -s #{device_serial} shell pm list packages #{app_package_name}` returns in output so it would be good to have some tests that show a sample of that for stability and future maintenance 👌

File: screengrab/lib/screengrab/runner.rb (hunk 2 above)
Comment (joeboyscout04) [reply screengrab/lib/screengrab/runner.rb]: @janpio I finally got a few free minutes to take another look at this.  I didn't utilize the AdbHelper since it isn't present in the `runner.rb` yet and it didn't feel right introducing it just for this change.  It probably could be part of a future refactoring.

**Comment by joeboyscout04** [comment]
Implemented suggestions to create separate function for `installed_packages` and return an array of all the installed packages instead of a string, plus added some unit tests.

File: screengrab/lib/screengrab/runner.rb (hunk 2 above)
Comment (janpio) [reply screengrab/lib/screengrab/runner.rb]: Ok, although it would have been fine to introduce the connection to the Helper for that 👍

**Review by janpio — COMMENTED** [review]
Changes look good!

**Review by Ahmed-Emad — APPROVED** [review]

**Review by janpio — APPROVED** [review]
