### PR TITLE
[fastlane_core] install all Apple WWDR Intermediate Certificates

### LINKED ISSUE #20509: [Regression] Code signing failed with error errSecInternalComponent
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.208.0`
- Last working version: `2.206.0`

### Regression Description

On the same CI environment, we see following error when using 2.208.0, but not when using 2.206.0

```
Warning: unable to build chain to self-signed root for signer "iPhone Distribution: Automattic, Inc."
/usr/local/var/buildkite-agent/builds/builder/automattic/wordpress-ios/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/WordPress Alpha/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/WordPressTodayWidget.appex: errSecInternalComponent
Command CodeSign failed with a nonzero exit code
```

_I think_, the issue might be caused by [this PR](https://github.com/fastlane/fastlane/pull/20448), which changed where to install the WWDR certificate—it might be the Login keychain or a random keychain that's set as the default keychain.

We uses `setup_ci` action in our Fastfile, which creates a `fastlane_tmp_keychain` and sets it as the default keychain. Maybe this is the reason why code-sign was "unable to build chain to self-signed root", since the WWDR certifcate is not in Login or System keychain?

### Environment

https://github.com/wordpress-mobile/WordPress-iOS/tree/trunk/fastlane

### PR DESCRIPTION
**Pull request by crazytonyli**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #20509

### Description

Short summary: install all Apple WWDR "Intermediate Certificates", rather than only [a specific one](https://github.com/fastlane/fastlane/blob/1e45f926121d91b0410e2345d7ce6860622937f6/fastlane_core/lib/fastlane_core/cert_checker.rb#L96) which is "G6" currently.

https://github.com/fastlane/fastlane/pull/20448 changed which WWDRCA certificates that fastlane installs. As you can see in [this diff](https://github.com/fastlane/fastlane/pull/20448/files#diff-605d869e313da5ef9f0c402845a4911eed5f8afc4ef45382210f237fceae498aL92), fastlane used to install "G1" and "G3" certificates (these names are taken from https://www.apple.com/certificateauthority/), but now fastlane (2.208.0 to be specific) only installs "G6". This change caused a code signing issue in the app I work on. I reported this regression in https://github.com/fastlane/fastlane/issues/20509 (Initially I incorrectly suspected that the cause was the certificates installation keychain which was also changed in the PR mentioned before).

After some investigation, I found the root cause is missing the right WWDRCA certificate—[simply changing G6 to G3](https://github.com/fastlane/fastlane/commit/8f8f8cb1b7a8dfb371000e8c3b41f6623924b561) worked in my case.

I don't really know how Xcode's CodeSign looks up the certificates, I also don't know whether installing another certificate works for all cases (maybe in some other case, Xcode wants G2? I don't know...). But installing _all_ "Intermediate Certificates" that are listed on [this Apple website](https://www.apple.com/certificateauthority/) shouldn't be harmful. And that's what I've implemented in this PR. This PR doesn't introduce breaking changes—G6 certificate is still installed, along with a bunch of other similar certificates.

### Testing Steps

Pull down this PR code, navigate to the project directory, run below command, all WWDRCA certificates should be installed to the default keychain.
```
bundle exec ruby -e "require 'shellwords'; require 'fastlane_core/cert_checker'; puts FastlaneCore::CertChecker.install_missing_wwdr_certificates"
```

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 1]
```diff
@@ -81,19 +81,45 @@ def self.list_available_developer_id_installer(in_keychain: nil)
...
+      installed_certs.map do |pem|
+        OpenSSL::X509::Certificate.new(pem).subject.to_a.find { |part| part[0] == 'OU' }[1]
+      end
+    end
 
-      certs = response.split("\n")
-      certs.include?(certificate_hash)
+    def self.install_missing_wwdr_certificates
+      # Install all Worldwide Developer Relations Intermediate Certificates listed here: https://www.apple.com/certificateauthority/
+      missing = ['Apple Worldwide Developer Relations', 'Apple Certification Authority', 'G3', 'G4', 'G5', 'G6'] - installed_wwdr_certificates
```
Comment (milch) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:107]: Can the names of the certificates go into a constant at the top of the file?

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 2]
```diff
@@ -81,19 +81,45 @@ def self.list_available_developer_id_installer(in_keychain: nil)
...
+        else
+          installed_certs.last << line
+        end
+      end
 
-      keychain = wwdr_keychain
-      response = Helper.backticks("security find-certificate -a -c '#{certificate_name}' -Z #{keychain.shellescape} | grep ^SHA-256", print: FastlaneCore::Globals.verbose?)
+      # Get 'organisational unit' of the installed WWDRCA certificates
+      installed_certs.map do |pem|
+        OpenSSL::X509::Certificate.new(pem).subject.to_a.find { |part| part[0] == 'OU' }[1]
```
Comment (milch) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:101]: I love how Apple inconsistently uses which field they put what information in 😅 I wonder if it would make more sense to look at the SHA of the certificates though, since that should always be consistent... so even if Apple releases a G7 tomorrow that uses `Apple Certification Authority` as the `OU`, this code would continue to work as expected.

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 3]
```diff
@@ -81,19 +81,45 @@ def self.list_available_developer_id_installer(in_keychain: nil)
       `#{commands.join(' ')}`
     end
 
-    def self.wwdr_certificate_installed?
-      certificate_name = "Apple Worldwide Developer Relations Certification Authority"
-      certificate_hash = "SHA-256 hash: BDD4ED6E74691F0C2BFD01BE0296197AF1379E0418E2D300EFA9C3BEF642CA30"
+    def self.installed_wwdr_certificates
+      certificate_name = "Apple Worldwide Developer Relations"
```
Comment (rogerluan) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:85]: Same here IMO (re: constant name)

**Review by rogerluan — APPROVED** [review]
Other than @milch 's comments, LGTM!

**Comment by getaaron** [comment]
@crazytonyli happy to merge this, I agree about the constants suggestion. Do you want to do that in this PR or should I merge it now and you can do it as a follow-up refactor?

File: fastlane_core/lib/fastlane_core/cert_checker.rb (hunk 2 above)
Comment (crazytonyli) [reply fastlane_core/lib/fastlane_core/cert_checker.rb]: Addressed in https://github.com/fastlane/fastlane/pull/20537/commits/6c5d2b916956f20ea76aadcfdffc70c2ed0464f4

**Comment by crazytonyli** [comment]
@getaaron I've address the review comments in https://github.com/fastlane/fastlane/pull/20537/commits/6c5d2b916956f20ea76aadcfdffc70c2ed0464f4

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 4]
```diff
@@ -3,6 +3,40 @@
...
+    alias: 'G5',
+    sha256: '53fd008278e5a595fe1e908ae9c5e5675f26243264a5a6438c023e3ce2870760',
+    url: 'https://www.apple.com/certificateauthority/AppleWWDRCAG5.cer'
+  },
+  {
+    alias: 'G6',
+    sha256: 'bdd4ed6e74691f0c2bfd01be0296197af1379e0418e2d300efa9c3bef642ca30',
+    url: 'https://www.apple.com/certificateauthority/AppleWWDRCAG6.cer'
+  }
+]
```
Comment (joshdholtz) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:38]: This is 😍

**Review by joshdholtz — APPROVED** [review]
This is beautiful! Will get this shipped out right now 💪

**Comment by getaaron** [comment]
Niiiiice

**Comment by rogerluan** [comment]
Beautiful!!
