### PR TITLE
[core] bubble up FastlanePty exit status in FastlanePtyError

### LINKED ISSUE #13305: itunes_transporter.rb doesn't handle failures during upload very well any more
Seems since the rework of `itunes_transporter.rb` for Windows compat the error message or stack trace you get when something fails during upload is not optimal any more.

Examples:

https://github.com/fastlane/fastlane/issues/13284#issue-357034799
```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
```

https://github.com/fastlane/fastlane/issues/13281#issuecomment-418806266
```
[11:45:17]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:45:24]: Login to App Store Connect (********)
[11:45:37]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.103.1 Summary                           |
+--------------------------------------+--------------------------------------+
| ipa                                  | **********                           |
| force                                | true                                 |
| skip_screenshots                     | true                                 |
| skip_metadata                        | true                                 |
| username                             | **********                           |
| app_identifier                       | **********                           |
|                                      | iphone                               |
| run_precheck_before_submit           | false                                |
| screenshots_path                     | ./screenshots                        |
| metadata_path                        | ./metadata                           |
| app_version                          | 999999                               |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | false                                |
| skip_app_version_update              | false                                |
| overwrite_screenshots                | false                                |
| submit_for_review                    | false                                |
| reject_if_possible                   | false                                |
| automatic_release                    | false                                |
| phased_release                       | false                                |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

[11:45:45]: Making sure the latest version on App Store Connect matches '999999' from the ipa file...
[11:45:49]: '999999' is the latest version on App Store Connect
[11:45:57]: Uploading binary to App Store Connect
[11:46:49]: Going to upload updated app to App Store Connect
[11:46:49]: This might take a few minutes. Please don't interrupt the script.
[11:46:58]: [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[11:46:58]: Transporter transfer failed.
[11:46:58]:
[11:46:58]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)

Looking for related GitHub issues on fastlane/fastlane...

➡️  AGV enabled check fails
    https://github.com/fastlane/fastlane/issues/9506 [closed] 33 💬
    04 Oct 2017

➡️  The App Name you entered has already been used.
    https://github.com/fastlane/fastlane/issues/8079 [closed] 6 💬
    03 May 2017

➡️  pilot crashes on upload
    https://github.com/fastlane/fastlane/issues/4821 [closed] 24 💬
    28 Jan 2017

and 3 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60zero%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/runner.rb:160:in `upload_binary'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/runner.rb:42:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
	from /Users/jhoon/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jhoon/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

https://github.com/fastlane/fastlane/issues/13284#issuecomment-419014887
```
[15:32:54]: [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
[15:32:54]: Transporter transfer failed.
[15:32:54]:
[15:32:54]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
...
/Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
	from /Users/zolotyx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:128:in `chdir'
	from /Users/zolotyx/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:128:in `cd'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:24:in `block (2 levels) in parsing_binding'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `load'
	from /Users/zolotyx/.rvm/gems/ruby-2.3.1/bin/fastlane:23:in `<main>'
```

https://github.com/fastlane/fastlane/issues/13284#issuecomment-419028920
``` 
[17:22:47]: fastlane detected a Gemfile in the current directory
[17:22:47]: however it seems like you don't use `bundle exec`
[17:22:47]: to launch fastlane faster, please use
[17:22:47]: 
[17:22:47]: $ bundle exec fastlane upload_testflight ipa:myapp.ipa account_type:account # this a custom lane called upload_testflight
[17:22:47]: 
[17:22:47]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:22:48]: ----------------------------------------
[17:22:48]: --- Step: Verifying fastlane version ---
[17:22:48]: ----------------------------------------
[17:22:48]: Your fastlane version 2.103.1 matches the minimum requirement of 1.106.1  ✅
[17:22:48]: ------------------------------
[17:22:48]: --- Step: default_platform ---
[17:22:48]: ------------------------------
[17:22:48]: Driving the lane 'ios upload_testflight' 🚀
[17:22:48]: -------------------
[17:22:48]: --- Step: pilot ---
[17:22:48]: -------------------
[17:22:49]: Login to App Store Connect (xxx@xxx.com)
[17:22:52]: Login successful
[17:22:53]: Ready to upload new build to TestFlight (App: xxxx)...
[17:22:55]: Going to upload updated app to App Store Connect
[17:22:55]: This might take a few minutes. Please don't interrupt the script.
[17:24:03]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '1721' for version number '1.21.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
[17:24:03]: Transporter transfer failed.
[17:24:03]: 
[17:24:03]: ERROR ITMS-90189: "Redundant Binary Upload. You've already uploaded a build with build number '1721' for version number '1.21.1'. Make sure you increment the build string before you upload your app to App Store Connect. Learn more in Xcode Help (http://help.apple.com/xcode/mac/current/#/devba7f53ad4)."
+------------------+-----------------------+
|               Lane Context               |
+------------------+-----------------------+
| DEFAULT_PLATFORM | ios                   |
| PLATFORM_NAME    | ios                   |
| LANE_NAME        | ios upload_testflight |
+------------------+-----------------------+

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 💥   | pilot                      | 74          |
+------+----------------------------+-------------+

[17:24:03]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Regression] Build Fails with an Invalid 2 step response Error
    https://github.com/fastlane/fastlane/issues/13281 [closed] 31 💬
    10 hours ago

➡️  AGV enabled check fails
    https://github.com/fastlane/fastlane/issues/9506 [closed] 33 💬
    04 Oct 2017

➡️  The App Name you entered has already been used.
    https://github.com/fastlane/fastlane/issues/8079 [closed] 6 💬
    03 May 2017

and 4 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60zero%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:120:in `chdir'
	from /usr/local/Cellar/ruby/2.4.2_1/lib/ruby/2.4.0/fileutils.rb:120:in `cd'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:41:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### LINKED ISSUE #13321: [Regression] Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `1.203.0`
- Last working version: `1.102.0`

### Regression Description

Prior to the update, whenever 2FA was enabled, fastlane deliver CLI would ask for the app-specific password if it wasn't specified as an environment variable. 

After the update, it just crashes.

Found a workaround, which is setting the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` environment variable, but would like this to work as before because, you know, regression.

(Side note: we provide WLs, so we manage hundreds of apps on different accounts, we figured it was easier to run these generated commands than to create a config file for each one, though this could change, it's just that there are still manual processes we need to manage)

@janpio Sorry, I just got the opportunity to reproduce this again, but here is the output with `--verbose`. Also `--capture_output` doesn't work whenever I run `fastlane deliver` directly from the command line, but there's the `fastlane env`. Hope this gets solved soon!

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre><code>
ThisComputer:~ jhoon$ fastlane deliver --ipa "/path/to.ipa" -f --skip_screenshots --skip_metadata -u this@email.com -a the.bundle.id -x false --verbose
[08:20:24]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2018-09-07 08:20:29.86]: Login to App Store Connect (this@email.com)
Loading session from '/Users/jhoon/.fastlane/spaceship/this@email.com/cookie'
Looking for App Store Connect Team with ID 111111111
INFO [2018-09-07 08:20:39.43]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.103.1 Summary                           |
+--------------------------------------+--------------------------------------+
| ipa                                  | /path/to.ipa                         |
| force                                | true                                 |
| skip_screenshots                     | true                                 |
| skip_metadata                        | true                                 |
| username                             | this@email.com                       |
| app_identifier                       | the.bundle.id                        |
| run_precheck_before_submit           | false                                |
| screenshots_path                     | ./.fastlane/screenshots              |
| metadata_path                        | ./.fastlane/metadata                 |
| app_version                          | 99999999                             |
| platform                             | ios                                  |
| edit_live                            | false                                |
| use_live_version                     | false                                |
| skip_binary_upload                   | false                                |
| skip_app_version_update              | false                                |
| overwrite_screenshots                | false                                |
| submit_for_review                    | false                                |
| reject_if_possible                   | false                                |
| automatic_release                    | false                                |
| phased_release                       | false                                |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validatio  | false                                |
| n                                    |                                      |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

INFO [2018-09-07 08:20:44.95]: Making sure the latest version on App Store Connect matches '99999999' from the ipa file...
INFO [2018-09-07 08:20:49.23]: '99999999' is the latest version on App Store Connect
INFO [2018-09-07 08:20:55.28]: Uploading binary to App Store Connect
INFO [2018-09-07 08:21:37.52]: Wrote XML data to '/tmp/1231231230.itmsp'
INFO [2018-09-07 08:21:37.62]: Going to upload updated app to App Store Connect
INFO [2018-09-07 08:21:37.62]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2018-09-07 08:21:37.75]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar -m upload -u this@email.com -p YourPassword -f /tmp/1231231230.itmsp -t Signiant -k 100000 2>&1
DEBUG [2018-09-07 08:21:43.99]: [Transporter]: INFO: Transporter is searching for updated software components.
DEBUG [2018-09-07 08:21:44.51]: [Transporter]: INFO: Transporter is up-to-date.
DEBUG [2018-09-07 08:21:44.70]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2018-09-07 08:21:44.70]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2018-09-07 08:21:45.06]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2018-09-07 08:21:45.06]: [Transporter]: DEBUG: Saving configuration to local path: /Users/jhoon/.itmstransporter/Defaults.properties
DEBUG [2018-09-07 08:21:45.06]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.8]
DEBUG [2018-09-07 08:21:45.06]: [Transporter]: INFO: OS identifier: Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 08:21:45.07]: [Transporter]: INFO: Memory: [JVM] 807M free, 981M total, 981M max [System] (Physical) 435M free, 16384M total (Swap) 1228M free, 5120M total
DEBUG [2018-09-07 08:21:45.07]: [Transporter]: INFO: Upload mode selected.
DEBUG [2018-09-07 08:21:45.08]: [Transporter]: INFO: Examining the package at: /tmp/1231231230.itmsp
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: DEBUG:   dbddd2519108eea1146e69968adf55d1d3a77d4e24a7960c3b7d04f97afc76cd.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2018-09-07 08:21:45.09]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2018-09-07 08:21:45.11]: [Transporter]: INFO: Performing authentication of package 1231231230.itmsp ...
DEBUG [2018-09-07 08:21:45.12]: [Transporter]: DBG-X: Memory: [JVM] 797M free, 981M total, 981M max [System] (Physical) 423M free, 16384M total (Swap) 1228M free, 5120M total
DEBUG [2018-09-07 08:21:45.12]: [Transporter]: DBG-X: Memory: [JVM] 797M free, 981M total, 981M max [System] (Physical) 423M free, 16384M total (Swap) 1228M free, 5120M total
DEBUG [2018-09-07 08:21:45.12]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T08:21:45-05:00
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.580771413
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u this@email.com -p **hidden value** -f /tmp/1231231230.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter Username = this@email.com
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 08:21:45.13]: [Transporter]: INFO: id = 20180907082145-132
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X:   parameter Errors = [Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)]
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X:   parameter ErrorCode = -22938
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X:   parameter ErrorMessage = Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2018-09-07 08:21:46.65]: [Transporter Error Output]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
DEBUG [2018-09-07 08:21:46.65]: [Transporter]: DBG-X: The error code is: -22938
ERROR [2018-09-07 08:21:46.79]: Transporter transfer failed.
WARN [2018-09-07 08:21:46.79]:
ERROR [2018-09-07 08:21:46.79]: Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `zero?' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60zero%3F%27%20for%20nil+repo:fastlane/fastlane
➡️  [Regression] raise NoMethodError in 2.103.0 when I'm trying to upload ipa with new AppStoreConnect API
    https://github.com/fastlane/fastlane/issues/13284 [open] 12 💬
    a day ago

➡️  itunes_transporter.rb doesn't handle failures during upload very well any more
    https://github.com/fastlane/fastlane/issues/13305 [open] 2 💬
    18 hours ago

➡️  [Regression] Build Fails with an Invalid 2 step response Error
    https://github.com/fastlane/fastlane/issues/13281 [closed] 31 💬
    a day ago

and 6 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60zero%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/runner.rb:160:in `upload_binary'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/runner.rb:42:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:79:in `block (2 levels) in run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:182:in `run'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/deliver/lib/deliver/commands_generator.rb:17:in `start'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:100:in `take_off'
	from /Users/jhoon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
	from /Users/jhoon/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jhoon/.fastlane/bin/bundle/bin/fastlane:22:in `\<main\>'
</code></pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.15.2 (Apple Git-101.1)        |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.9.1        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.8       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
</details>

*generated on:* **2018-09-07**
</details> 
  
  
_**Edit:** I was careless with the identifying info, edited that out!_

### LINKED ISSUE #13323: `fastlane beta` never finishes, but with different internal errors
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I run `fastlane beta` I get to the Transporter step and during upload, I'm hit with one of a handful of different errors. None of my 6 (or so) attempts that have made it this far in the process have succeeded.

##### Complete output when running fastlane, including the stack trace and command used

https://gist.github.com/jyurek/3681588c1b1b562e56da78acc319902b -- github yelled at me that this was too long

I've also gotten this error. Log truncated to just the upload step.

<details>
<pre>
INFO [2018-09-07 10:32:21.74]: ----------------------------------
INFO [2018-09-07 10:32:21.74]: --- Step: upload_to_testflight ---
INFO [2018-09-07 10:32:21.74]: ----------------------------------
INFO [2018-09-07 10:32:21.99]: Login to App Store Connect (jyurek@gmail.com)
Loading session from '/Users/jyurek/.fastlane/spaceship/jyurek@gmail.com/cookie'
Looking for App Store Connect Team with ID 118505367
INFO [2018-09-07 10:32:23.79]: Login successful
DEBUG [2018-09-07 10:32:23.79]: App identifier (com.myclient.surgeon)
INFO [2018-09-07 10:32:24.48]: Ready to upload new build to TestFlight (App: 1434743526)...
DEBUG [2018-09-07 10:32:24.48]: App Platform (ios)
INFO [2018-09-07 10:32:24.79]: Wrote XML data to '/var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp'
INFO [2018-09-07 10:32:24.79]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
INFO [2018-09-07 10:32:24.79]: Going to upload updated app to App Store Connect
INFO [2018-09-07 10:32:24.79]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2018-09-07 10:32:24.91]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar -m upload -u jyurek@gmail.com -p YourPassword -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000 2>&1
DEBUG [2018-09-07 10:32:27.66]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
DEBUG [2018-09-07 10:32:27.81]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2018-09-07 10:32:27.81]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2018-09-07 10:32:27.89]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2018-09-07 10:32:27.89]: [Transporter]: DEBUG: Saving configuration to local path: /Users/jyurek/.itmstransporter/Defaults.properties
DEBUG [2018-09-07 10:32:27.89]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.8]
DEBUG [2018-09-07 10:32:27.89]: [Transporter]: INFO: OS identifier: Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:32:27.90]: [Transporter]: INFO: Memory: [JVM] 812M free, 981M total, 981M max [System] (Physical) 694M free, 16384M total (Swap) 1196M free, 6144M total
DEBUG [2018-09-07 10:32:27.90]: [Transporter]: INFO: Upload mode selected.
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: INFO: Examining the package at: /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: DEBUG:   eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2018-09-07 10:32:27.91]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2018-09-07 10:32:27.96]: [Transporter]: INFO: Performing authentication of package 1434743526.itmsp ...
DEBUG [2018-09-07 10:32:27.96]: [Transporter]: DBG-X: Memory: [JVM] 797M free, 981M total, 981M max [System] (Physical) 681M free, 16384M total (Swap) 1196M free, 6144M total
DEBUG [2018-09-07 10:32:27.96]: [Transporter]: DBG-X: Memory: [JVM] 797M free, 981M total, 981M max [System] (Physical) 680M free, 16384M total (Swap) 1196M free, 6144M total
DEBUG [2018-09-07 10:32:27.97]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:32:27-04:00
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.293623085
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:32:27.98]: [Transporter]: INFO: id = 20180907103227-258
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter TxHeaders = {jenga=true}
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter SessionExpiration = 2018-09-11T14:32:28.359Z
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter SessionId = CNGoDBIQx+4w0/7TQTSJIOipCs/5tg==
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X: Deflated 484 bytes to 424
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2018-09-07 10:32:28.49]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Files = [eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, metadata.xml]
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter MetadataChecksum = 31d6328bfab0d91309db43c2f4db1404
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter PackageName = 1434743526.itmsp
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter PackageSize = 47641357
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:32:28-04:00
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:32:28.50]: [Transporter]: INFO: id = 20180907103228-950
DEBUG [2018-09-07 10:32:30.31]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:32:30.31]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:32:30.31]: [Transporter]: DBG-X:   parameter SessionExpiration = 2018-09-11T14:32:29.076Z
DEBUG [2018-09-07 10:32:30.31]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
DEBUG [2018-09-07 10:32:30.31]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa]
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, ShouldDescribeAsset=true, UTI=com.apple.ipa}]
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter CPUToken = 37f90cdf-98c8-45cf-b673-e3823e2fd2fb/1536330749917
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter Checksums = {eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa=7f03de342cac16b148d8125076f6e0bf}
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter FileSizes = {eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa=47640873}
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: DBG-X:   parameter ProviderNameForToken = YNCH98TY65
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa].  These are the files that will be uploaded.
DEBUG [2018-09-07 10:32:30.32]: [Transporter]: INFO: Starting media analysis of assets
DEBUG [2018-09-07 10:32:30.65]: [Transporter]: DEBUG: Handling asset: filename=eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa,uti=com.apple.ipa,role=source,describe=true
DEBUG [2018-09-07 10:32:30.65]: [Transporter]: DEBUG: Using container type tool name and version: iOS App Describer:1.25
DEBUG [2018-09-07 10:32:30.65]: [Transporter]: DEBUG: Using path: /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp/eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa
DEBUG [2018-09-07 10:32:33.61]: [Transporter]: DBG-X: description length:0
DEBUG [2018-09-07 10:32:33.61]: [Transporter]: DBG-X: Asset description:
DEBUG [2018-09-07 10:32:33.61]: [Transporter]: DEBUG: Asset successfully described: com.apple.jingle.leghorn.software.AbstractSoftwareDescriber$1@36dce7ed
DEBUG [2018-09-07 10:32:33.75]: [Transporter]: DBG-X: Deflated 629 bytes to 385
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: INFO: Asset media analysis has completed
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X: Memory: [JVM] 896M free, 981M total, 981M max [System] (Physical) 592M free, 16384M total (Swap) 1196M free, 6144M total
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X: Using operation named: lookupTransportDiagnostic
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:32:33-04:00
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:32:33.76]: [Transporter]: INFO: id = 20180907103233-616
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X:   parameter AsperaLoggingLevel = OFF
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = OFF
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X:   parameter SessionExpiration = 2018-09-11T14:32:34.824Z
DEBUG [2018-09-07 10:32:43.34]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-09-07 10:32:43.39]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2018-09-07 10:32:43.40]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2018-09-07 10:32:43.40]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2018-09-07 10:32:43.40]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2018-09-07 10:32:43.41]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
DEBUG [2018-09-07 10:32:43.41]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:43.44]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2018-09-07 10:32:43.44]: [Transporter]: INFO: Processing URL list: mxwan://sgr602.apple.com:44001/
DEBUG [2018-09-07 10:32:43.45]: [Transporter]: INFO: Trying UDP sgr602.apple.com/17.110.248.102:44001...
DEBUG [2018-09-07 10:32:44.61]: [Transporter]: INFO: Connected to UDP sgr602.apple.com/17.110.248.102:44001
DEBUG [2018-09-07 10:32:44.80]: [Transporter]: INFO: Authenticating
DEBUG [2018-09-07 10:32:46.00]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2018-09-07 10:32:46.00]: [Transporter]: INFO: Setting up data streams
DEBUG [2018-09-07 10:32:46.88]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
DEBUG [2018-09-07 10:32:46.88]: [Transporter]: INFO: Connected using WAN accelerator
DEBUG [2018-09-07 10:32:47.09]: [Transporter]: INFO:      File: caae8132-6ad6-43a1-ad60-3b4f1b74dde22993365999856983633.txt 11/11, 100% completed
DEBUG [2018-09-07 10:32:47.12]: [Transporter]: DBG-X: The status for the file, caae8132-6ad6-43a1-ad60-3b4f1b74dde22993365999856983633.txt, is TRANSFERRED.
DEBUG [2018-09-07 10:32:47.37]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:48.43]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:48.58]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:48.58]: [Transporter]: DEBUG: An error has occurred during the upload.
DEBUG [2018-09-07 10:32:48.67]: [Transporter]: DEBUG: An exception has occurred: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:48.67]: [Transporter]: DEBUG: Transfer warning: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:48.67]: [Transporter]: DEBUG: Received failed transfer notification; aborting
DEBUG [2018-09-07 10:32:48.67]: [Transporter]: INFO: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:48.75]: [Transporter]: INFO: The Signiant transport is encountering difficulties with the upload. This may be caused by a firewall or network configuration preventing access.
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
DEBUG [2018-09-07 10:32:48.76]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:48.78]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2018-09-07 10:32:48.78]: [Transporter]: INFO: Processing URL list: mxwan://sgr404.apple.com:44001/
DEBUG [2018-09-07 10:32:48.78]: [Transporter]: INFO: Trying UDP sgr404.apple.com/17.172.190.104:44001...
DEBUG [2018-09-07 10:32:49.82]: [Transporter]: INFO: Connected to UDP sgr404.apple.com/17.172.190.104:44001
DEBUG [2018-09-07 10:32:49.88]: [Transporter]: INFO: Authenticating
DEBUG [2018-09-07 10:32:50.23]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2018-09-07 10:32:50.23]: [Transporter]: INFO: Setting up data streams
DEBUG [2018-09-07 10:32:50.64]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
DEBUG [2018-09-07 10:32:50.65]: [Transporter]: INFO: Connected using WAN accelerator
DEBUG [2018-09-07 10:32:50.75]: [Transporter]: INFO:      File: e0cfbbde-f405-469b-bde1-42d97c2e4f89961857263166554227.txt 11/11, 100% completed
DEBUG [2018-09-07 10:32:50.76]: [Transporter]: DBG-X: The status for the file, e0cfbbde-f405-469b-bde1-42d97c2e4f89961857263166554227.txt, is TRANSFERRED.
DEBUG [2018-09-07 10:32:50.88]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:51.93]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:52.04]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:52.04]: [Transporter]: DEBUG: An error has occurred during the upload.
DEBUG [2018-09-07 10:32:52.10]: [Transporter]: DEBUG: An exception has occurred: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:52.10]: [Transporter]: DEBUG: Transfer warning: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:52.10]: [Transporter]: DEBUG: Received failed transfer notification; aborting
DEBUG [2018-09-07 10:32:52.10]: [Transporter]: INFO: Scheduling automatic restart in 1 minute
DEBUG [2018-09-07 10:32:52.24]: [Transporter]: INFO: The Signiant transport is encountering difficulties with the upload. This may be caused by a firewall or network configuration preventing access.
DEBUG [2018-09-07 10:32:52.24]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2018-09-07 10:32:52.25]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2018-09-07 10:32:52.25]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2018-09-07 10:32:52.25]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2018-09-07 10:32:52.25]: [Transporter]: INFO: Transfer engine: 10.6.0.59156
DEBUG [2018-09-07 10:32:52.25]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:52.28]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2018-09-07 10:32:52.28]: [Transporter]: INFO: Processing URL list: mxwan://sgr804.apple.com:44001/
DEBUG [2018-09-07 10:32:52.28]: [Transporter]: INFO: Trying UDP sgr804.apple.com/17.133.233.104:44001...
DEBUG [2018-09-07 10:32:53.37]: [Transporter]: INFO: Connected to UDP sgr804.apple.com/17.133.233.104:44001
DEBUG [2018-09-07 10:32:53.55]: [Transporter]: INFO: Authenticating
DEBUG [2018-09-07 10:32:54.19]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2018-09-07 10:32:54.19]: [Transporter]: INFO: Setting up data streams
DEBUG [2018-09-07 10:32:55.04]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
DEBUG [2018-09-07 10:32:55.04]: [Transporter]: INFO: Connected using WAN accelerator
DEBUG [2018-09-07 10:32:55.23]: [Transporter]: INFO:      File: 5b4d0579-edcc-4b41-b13d-623f550df2d57169381700725516165.txt 11/11, 100% completed
DEBUG [2018-09-07 10:32:55.26]: [Transporter]: DBG-X: The status for the file, 5b4d0579-edcc-4b41-b13d-623f550df2d57169381700725516165.txt, is TRANSFERRED.
DEBUG [2018-09-07 10:32:55.56]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:55.63]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:32:55.70]: [Transporter]: DEBUG: Using token file path /Users/jyurek/.itmstransporter/UploadTokens/Trumpet_YNCH98TY65_1434743526.itmsp.token
DEBUG [2018-09-07 10:32:55.70]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
DEBUG [2018-09-07 10:32:55.70]: [Transporter]: DEBUG: Token exists, examining
DEBUG [2018-09-07 10:32:55.81]: [Transporter]: DEBUG: Token pid: 62642, found process = false; my pid: 74344
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DEBUG: Reusing existing token: 80288804-a6e0-4df2-9c8b-5d1d0987f085/1536328103901
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DEBUG: Set token: 80288804-a6e0-4df2-9c8b-5d1d0987f085/1536328103901
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X: Memory: [JVM] 922M free, 981M total, 981M max [System] (Physical) 389M free, 16384M total (Swap) 1196M free, 6144M total
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X: Deflated 484 bytes to 424
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X: Using operation named: validateAssets
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:32:55.91]: [Transporter]: DBG-X:   parameter CPUToken = 80288804-a6e0-4df2-9c8b-5d1d0987f085/1536328103901
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter Files = [eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, metadata.xml]
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter MetadataChecksum = 31d6328bfab0d91309db43c2f4db1404
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter PackageName = 1434743526.itmsp
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter PackageSize = 47641357
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:32:55-04:00
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter StreamingInfoList = [com.apple.transporter.streaming.StreamableFile@65327f5]
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter Transport = Signiant
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:32:55.92]: [Transporter]: INFO: id = 20180907103255-465
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter SessionExpiration = 2018-09-11T14:32:56.986Z
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter TransportUser = transporter
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter ResumeFlag = false
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter FilesToUpload = [metadata.xml, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa]
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter AssetsToDescribe = [{Role=source, Filename=eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, ShouldDescribeAsset=true, UTI=com.apple.ipa}]
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter CPUToken = 9babe1b2-b951-4d1e-9c60-86d45e151c26/1536330781256
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter SigniantLoggingLevel = INFO
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter FileSizes = {eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa=47640873}
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter TransportPort = 44001
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter TransportHosts = [sgr603.apple.com]
DEBUG [2018-09-07 10:34:19.99]: [Transporter]: DBG-X:   parameter MinimumFileSizeThresholdForCheckum = 104857600
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionFormat = binary
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter SoftwareMediaDescriptionThresholds = {in-app-purchase-content={extensions=[pkg], size=100000000}, ccats={extensions=[pdf], size=100000000}, product-archive={extensions=[pkg], size=100000000}, developer-id-package={extensions=[zip, pkg, dmg], size=100000000}, bundle={extensions=[zip, ipa], size=100000000}, large-icon={extensions=[jpg, png, jpeg], size=100000000}}
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter ProviderName = YNCH98TY65
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter Checksums = {eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa=7f03de342cac16b148d8125076f6e0bf}
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter TransportPath = sgr6_pod1/transporter/content/transporter/YNCH98TY65
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter NewPackageName = 1434743526-20180907073339-108.itmsp
DEBUG [2018-09-07 10:34:20.00]: [Transporter]: DBG-X:   parameter ProviderNameForToken = YNCH98TY65
DEBUG [2018-09-07 10:34:20.01]: [Transporter]: DBG-X: Existing token found, cleaning up
DEBUG [2018-09-07 10:34:20.01]: [Transporter]: DBG-X: Unlocking token at path /Users/jyurek/.itmstransporter/UploadTokens/Trumpet_YNCH98TY65_1434743526.itmsp.token
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DBG-X: Releasing token file lock
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DEBUG: Using token file path /Users/jyurek/.itmstransporter/UploadTokens/Trumpet_YNCH98TY65_1434743526.itmsp.token
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DEBUG: Attempting exclusive file lock on token file
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DEBUG: Set token: 9babe1b2-b951-4d1e-9c60-86d45e151c26/1536330781256
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: The list of files requested for upload by Apple is: [metadata.xml, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa].  These are the files that will be uploaded.
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: Done performing authentication.
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: The asset replacement verification check is disabled.
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: Checking the file size of the files: [eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa]
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DBG-X:  Checking the size of file: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: Done checking the file sizes.
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: INFO: Checking the md5 checksum of the files: [eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa]
DEBUG [2018-09-07 10:34:20.02]: [Transporter]: DBG-X:  Checking the MD5 checksum of file: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Done checking the md5 checksum.
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Preparing to upload package 1434743526.itmsp ...
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Determining which files should be uploaded ...
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Valid local files will be checked:
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Remote files uploaded:
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DBG-X: Examining working file: metadata.xml
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Adding file to be uploaded: metadata.xml
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DBG-X: Examining working file: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Adding file to be uploaded: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Finished determining which files should be uploaded.
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DBG-X: ITMSPackage: files to be uploaded:
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Starting to upload the package's files (1434743526.itmsp) ...
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Resetting sizes for progress logging
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Computing total size of files to upload ...
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DBG-X:   adding file for % complete logging: metadata.xml , size: 484
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DBG-X:   adding file for % complete logging: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa , size: 47640873
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: DEBUG: Setting total size of files for upload to: 47641357
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Done computing total size of files to upload.
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Signiant TransferEngine build 10.6.0.59156
DEBUG [2018-09-07 10:34:20.18]: [Transporter]: INFO: Using Signiant UDP transport
DEBUG [2018-09-07 10:34:20.19]: [Transporter]: DBG-X: Setting the target rate to 15000001 bytes per second.
DEBUG [2018-09-07 10:34:20.19]: [Transporter]: DBG-X: Setting the throttle to 12500000 bytes per second.
DEBUG [2018-09-07 10:34:20.19]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:34:20.19]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTING
DEBUG [2018-09-07 10:34:20.20]: [Transporter]: INFO: Processing URL list: mxwan://sgr604.apple.com:44001/
DEBUG [2018-09-07 10:34:20.20]: [Transporter]: INFO: Trying UDP sgr604.apple.com/17.110.248.104:44001...
DEBUG [2018-09-07 10:34:21.29]: [Transporter]: INFO: Connected to UDP sgr604.apple.com/17.110.248.104:44001
DEBUG [2018-09-07 10:34:21.45]: [Transporter]: INFO: Authenticating
DEBUG [2018-09-07 10:34:22.04]: [Transporter]: INFO: The Signiant transfer engine's status is AWAITING_DATA_STREAMS
DEBUG [2018-09-07 10:34:22.04]: [Transporter]: INFO: Setting up data streams
DEBUG [2018-09-07 10:34:22.86]: [Transporter]: INFO: The Signiant transfer engine's status is CONNECTED
DEBUG [2018-09-07 10:34:22.86]: [Transporter]: INFO: Connected using WAN accelerator
DEBUG [2018-09-07 10:34:23.06]: [Transporter]: INFO:      File: metadata.xml 484/484, 100% completed
DEBUG [2018-09-07 10:34:23.06]: [Transporter]: DBG-X: Memory: [JVM] 812M free, 981M total, 981M max [System] (Physical) 365M free, 16384M total (Swap) 1292M free, 6144M total
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X: Using operation named: assignTransportPodToUpload
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter CPUToken = 9babe1b2-b951-4d1e-9c60-86d45e151c26/1536330781256
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter NewPackageName = 1434743526-20180907073339-108.itmsp
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter Pod = McCarran Signiant 2
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:34:23-04:00
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 2.887207476
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter Transport = Signiant
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: INFO: id = 20180907103423-535
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: DBG-X: The status for the file, metadata.xml, is TRANSFERRED.
DEBUG [2018-09-07 10:34:23.07]: [Transporter]: INFO: Package upload progress: 0% completed
DEBUG [2018-09-07 10:34:23.69]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:34:23.69]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:34:23.69]: [Transporter]: DBG-X:   parameter SessionExpiration = 2018-09-11T14:34:23.311Z
DEBUG [2018-09-07 10:34:23.69]: [Transporter]: DBG-X:   parameter Success = true
DEBUG [2018-09-07 10:34:23.69]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2018-09-07 10:34:23.70]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 963800/47640873, 2% completed
DEBUG [2018-09-07 10:34:23.70]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 1911800/47640873, 4% completed
DEBUG [2018-09-07 10:34:23.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 2385800/47640873, 5% completed
DEBUG [2018-09-07 10:34:23.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 2859800/47640873, 6% completed
DEBUG [2018-09-07 10:34:23.75]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 3349600/47640873, 7% completed
DEBUG [2018-09-07 10:34:23.82]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 4297600/47640873, 9% completed
DEBUG [2018-09-07 10:34:23.88]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 4771600/47640873, 10% completed
DEBUG [2018-09-07 10:34:23.92]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 5245600/47640873, 11% completed
DEBUG [2018-09-07 10:34:24.06]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 6193600/47640873, 13% completed
DEBUG [2018-09-07 10:34:24.15]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 6683400/47640873, 14% completed
DEBUG [2018-09-07 10:34:24.26]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 7157400/47640873, 15% completed
DEBUG [2018-09-07 10:34:24.40]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 7631400/47640873, 16% completed
DEBUG [2018-09-07 10:34:24.70]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 8105400/47640873, 17% completed
DEBUG [2018-09-07 10:34:24.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 8579400/47640873, 18% completed
DEBUG [2018-09-07 10:34:24.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 9053400/47640873, 19% completed
DEBUG [2018-09-07 10:34:24.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 9543200/47640873, 20% completed
DEBUG [2018-09-07 10:34:24.88]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 10017200/47640873, 21% completed
DEBUG [2018-09-07 10:34:24.88]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 10491200/47640873, 22% completed
DEBUG [2018-09-07 10:34:25.01]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 10965200/47640873, 23% completed
DEBUG [2018-09-07 10:34:25.05]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 11439200/47640873, 24% completed
DEBUG [2018-09-07 10:34:25.17]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 11913200/47640873, 25% completed
DEBUG [2018-09-07 10:34:25.30]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 12877000/47640873, 27% completed
DEBUG [2018-09-07 10:34:25.53]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 13351000/47640873, 28% completed
DEBUG [2018-09-07 10:34:25.54]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 14299000/47640873, 30% completed
DEBUG [2018-09-07 10:34:25.56]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 14773000/47640873, 31% completed
DEBUG [2018-09-07 10:34:25.83]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 15736800/47640873, 33% completed
DEBUG [2018-09-07 10:34:26.10]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 16210800/47640873, 34% completed
DEBUG [2018-09-07 10:34:26.11]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 17158800/47640873, 36% completed
DEBUG [2018-09-07 10:34:26.11]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 17632800/47640873, 37% completed
DEBUG [2018-09-07 10:34:26.29]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 18580800/47640873, 39% completed
DEBUG [2018-09-07 10:34:26.60]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 19070600/47640873, 40% completed
DEBUG [2018-09-07 10:34:26.61]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 19544600/47640873, 41% completed
DEBUG [2018-09-07 10:34:26.61]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 20492600/47640873, 43% completed
DEBUG [2018-09-07 10:34:26.65]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 20966600/47640873, 44% completed
DEBUG [2018-09-07 10:34:26.88]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 21930400/47640873, 46% completed
DEBUG [2018-09-07 10:34:27.00]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 22404400/47640873, 47% completed
DEBUG [2018-09-07 10:34:27.07]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 23352400/47640873, 49% completed
DEBUG [2018-09-07 10:34:27.19]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 23826400/47640873, 50% completed
DEBUG [2018-09-07 10:34:27.35]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 24774400/47640873, 52% completed
DEBUG [2018-09-07 10:34:27.70]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 25738200/47640873, 54% completed
DEBUG [2018-09-07 10:34:27.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 26212200/47640873, 55% completed
DEBUG [2018-09-07 10:34:27.71]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 27160200/47640873, 57% completed
DEBUG [2018-09-07 10:34:27.82]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 28108200/47640873, 59% completed
DEBUG [2018-09-07 10:34:27.89]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 28598000/47640873, 60% completed
DEBUG [2018-09-07 10:34:27.94]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 29072000/47640873, 61% completed
DEBUG [2018-09-07 10:34:28.12]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 30020000/47640873, 63% completed
DEBUG [2018-09-07 10:34:28.64]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 30968000/47640873, 65% completed
DEBUG [2018-09-07 10:34:28.64]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 31457800/47640873, 66% completed
DEBUG [2018-09-07 10:34:28.64]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 31931800/47640873, 67% completed
DEBUG [2018-09-07 10:34:28.65]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 32405800/47640873, 68% completed
DEBUG [2018-09-07 10:34:28.99]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 33353800/47640873, 70% completed
DEBUG [2018-09-07 10:34:28.99]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 34301800/47640873, 72% completed
DEBUG [2018-09-07 10:34:29.36]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 34791600/47640873, 73% completed
DEBUG [2018-09-07 10:34:29.37]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 35265600/47640873, 74% completed
DEBUG [2018-09-07 10:34:29.37]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 36213600/47640873, 76% completed
DEBUG [2018-09-07 10:34:29.60]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 37161600/47640873, 78% completed
DEBUG [2018-09-07 10:34:29.67]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 37651400/47640873, 79% completed
DEBUG [2018-09-07 10:34:29.84]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 38125400/47640873, 80% completed
DEBUG [2018-09-07 10:34:29.88]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 38599400/47640873, 81% completed
DEBUG [2018-09-07 10:34:30.00]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 39547400/47640873, 83% completed
DEBUG [2018-09-07 10:34:30.20]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 40495400/47640873, 85% completed
DEBUG [2018-09-07 10:34:30.20]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 40985200/47640873, 86% completed
DEBUG [2018-09-07 10:34:30.23]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 41459200/47640873, 87% completed
DEBUG [2018-09-07 10:34:30.43]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 42407200/47640873, 89% completed
DEBUG [2018-09-07 10:34:30.58]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 43355200/47640873, 91% completed
DEBUG [2018-09-07 10:34:30.67]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 43845000/47640873, 92% completed
DEBUG [2018-09-07 10:34:30.74]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 44319000/47640873, 93% completed
DEBUG [2018-09-07 10:34:30.83]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 45267000/47640873, 95% completed
DEBUG [2018-09-07 10:34:31.02]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 46215000/47640873, 97% completed
DEBUG [2018-09-07 10:34:31.14]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 46689000/47640873, 98% completed
DEBUG [2018-09-07 10:34:31.25]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 47178800/47640873, 99% completed
DEBUG [2018-09-07 10:34:31.35]: [Transporter]: INFO:      File: eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa 47640873/47640873, 100% completed
DEBUG [2018-09-07 10:34:31.46]: [Transporter]: DBG-X: The status for the file, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, is TRANSFERRED.
DEBUG [2018-09-07 10:34:31.46]: [Transporter]: INFO: Package upload progress: 100% completed
DEBUG [2018-09-07 10:34:31.76]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:34:31.87]: [Transporter]: INFO: The Signiant transfer engine's status is DISCONNECTED
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: INFO: The file, metadata.xml, was uploaded successfully.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: INFO: The file, eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, was uploaded successfully.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: INFO: The status for the upload is SUCCESSFUL.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: INFO: The package's files (1434743526.itmsp) uploaded successfully.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: INFO: Done performing upload.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: DBG-X: The transfer time for the package 1434743526.itmsp was 11857 milliseconds.
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: DBG-X: Throughput information for 1434743526.itmsp: 0 minutes, 11.86 seconds, 45.43MB, 3.83MB/sec
DEBUG [2018-09-07 10:34:32.05]: [Transporter]: DBG-X: Deflated 479 bytes to 348
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X: Memory: [JVM] 933M free, 981M total, 981M max [System] (Physical) 315M free, 16384M total (Swap) 1292M free, 6144M total
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X: Using operation named: uploadDoneWithArguments
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter CPUToken = 9babe1b2-b951-4d1e-9c60-86d45e151c26/1536330781256
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{CalculationTime=155, FileLastModified=1536330744000, Filename=eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, FileSize=47640873, CalculatedChecksum=7f03de342cac16b148d8125076f6e0bf}]
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter FileSizeInfo = {eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa=47640873, metadata.xml=484}
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter NewPackageName = 1434743526-20180907073339-108.itmsp
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 47641357
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter PackagePathWithoutBase = sgr6_pod1/transporter/content/transporter/YNCH98TY65
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter StatisticsArray = [{duration=0.293623085, method=clientApplication.start, count=1}, {duration=0.521754413, method=authenticateForSession, count=1}, {duration=1.817776492, method=validateMetadata, count=1}, {duration=2.796573186, method=SWINFO, count=1}, {duration=9.581439056, method=lookupTransportDiagnostic, count=1}, {duration=84.076758592, method=validateAssets, count=1}, {duration=3.6863E-4, method=createTransportPod, count=1}, {duration=2.887207476, method=upload-SigniantTransport, count=1}, {duration=0.62658524, method=assignTransportPodToUpload, count=1}, {duration=0.04916501045227051, method=SWINFO.codesign_allocate, count=1}, {duration=0.011186957359313965, method=SWINFO.dwarfdump, count=1}, {duration=1.1626473665237427, method=SWINFO.file, count=204}, {duration=0.004494071006774902, method=SWINFO.lipo, count=1}, {duration=0.27852606773376465, method=SWINFO.expand-package, count=1}, {duration=0.10771000385284424, method=SWINFO.ipatool, count=1}]
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:34:32-04:00
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter TransferTime = 11857
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter Transport = Signiant
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:34:32.06]: [Transporter]: INFO: id = 20180907103432-786
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X:   parameter Errors = [Unable to process upload done request at this time due to a general error (1018)]
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X:   parameter ErrorCode = 1018
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X:   parameter ErrorMessage = Unable to process upload done request at this time due to a general error (1018)
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2018-09-07 10:35:19.71]: [Transporter Error Output]: Unable to process upload done request at this time due to a general error (1018)
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: The error code is: 1018
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: Deflated 479 bytes to 348
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: Memory: [JVM] 921M free, 981M total, 981M max [System] (Physical) 229M free, 16384M total (Swap) 1324M free, 6144M total
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: Using operation named: uploadFailedWithArguments
DEBUG [2018-09-07 10:35:19.71]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.6
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter CPUToken = 9babe1b2-b951-4d1e-9c60-86d45e151c26/1536330781256
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter ClientChecksumInfo = [{CalculationTime=155, FileLastModified=1536330744000, Filename=eaf23c8c853504ebf9ceae924fe973501a246437029101f144fc3a257b037f81.ipa, FileSize=47640873, CalculatedChecksum=7f03de342cac16b148d8125076f6e0bf}]
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter ExtraTransportLogCompressed = (suppressed)
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter NewPackageName = 1434743526-20180907073339-108.itmsp
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter NumberBytesTransferred = 47641357
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter StatisticsArray = [{duration=0.293623085, method=clientApplication.start, count=1}, {duration=0.521754413, method=authenticateForSession, count=1}, {duration=1.817776492, method=validateMetadata, count=1}, {duration=2.796573186, method=SWINFO, count=1}, {duration=9.581439056, method=lookupTransportDiagnostic, count=1}, {duration=84.076758592, method=validateAssets, count=1}, {duration=3.6863E-4, method=createTransportPod, count=1}, {duration=2.887207476, method=upload-SigniantTransport, count=1}, {duration=0.62658524, method=assignTransportPodToUpload, count=1}, {duration=47.654383045, method=uploadDoneWithArguments, count=1}, {duration=0.04916501045227051, method=SWINFO.codesign_allocate, count=1}, {duration=0.011186957359313965, method=SWINFO.dwarfdump, count=1}, {duration=1.1626473665237427, method=SWINFO.file, count=204}, {duration=0.004494071006774902, method=SWINFO.lipo, count=1}, {duration=0.27852606773376465, method=SWINFO.expand-package, count=1}, {duration=0.10771000385284424, method=SWINFO.ipatool, count=1}]
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2018-09-07T10:35:19-04:00
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter TransferTime = 11857
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter Transport = Signiant
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter TransportLogCompressed = (suppressed)
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u jyurek@gmail.com -p **hidden value** -f /var/folders/fp/9fg64xhn27x4ftd7fb5lfnxc0000gn/T/d20180907-71292-1wxa0gp/1434743526.itmsp -t Signiant -k 100000
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter Username = jyurek@gmail.com
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter Version = 1.9.8
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2018-09-07 10:35:19.72]: [Transporter]: INFO: id = 20180907103519-663
DEBUG [2018-09-07 10:35:45.39]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2018-09-07 10:35:45.39]: [Transporter]: DBG-X:   parameter Errors = [Unable to process uploadFailed request at this time due to a general error (1043)]
DEBUG [2018-09-07 10:35:45.40]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2018-09-07 10:35:45.40]: [Transporter]: DBG-X:   parameter ErrorCode = 1043
DEBUG [2018-09-07 10:35:45.40]: [Transporter]: DBG-X:   parameter ErrorMessage = Unable to process uploadFailed request at this time due to a general error (1043)
DEBUG [2018-09-07 10:35:45.40]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2018-09-07 10:35:45.40]: [Transporter Error Output]: Unable to process uploadFailed request at this time due to a general error (1043)
DEBUG [2018-09-07 10:35:45.40]: [Transporter]: DBG-X: The error code is: 1043
ERROR [2018-09-07 10:35:45.53]: Transporter transfer failed.
WARN [2018-09-07 10:35:45.53]:
ERROR [2018-09-07 10:35:45.53]: Unable to process upload done request at this time due to a general error (1018)
Unable to process uploadFailed request at this time due to a general error (1043)
WARN [2018-09-07 10:35:45.62]: Lane Context:
INFO [2018-09-07 10:35:45.62]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"14", :IPA_OUTPUT_PATH=>"/Users/jyurek/Development/myclient-iviewer/ios/MyClient.ipa", :DSYM_OUTPUT_PATH=>"/Users/jyurek/Development/myclient-iviewer/ios/MyClient.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/jyurek/Library/Developer/Xcode/Archives/2018-09-07/MyClient 2018-09-07 10.30.06.xcarchive"}
INFO [2018-09-07 10:35:45.62]: Successfully generated documentation at path '/Users/jyurek/Development/myclient-iviewer/ios/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | increment_build_numbe  | 0           |
|      | r                      |             |
| 3    | build_app              | 138         |
| 💥   | upload_to_testflight   | 203         |
+------+------------------------+-------------+

ERROR [2018-09-07 10:35:45.63]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `zero?' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60zero%3F%27%20for%20nil+repo:fastlane/fastlane
➡️  [Regression] raise NoMethodError in 2.103.0 when I'm trying to upload ipa with new AppStoreConnect API
    https://github.com/fastlane/fastlane/issues/13284 [open] 12 💬
    a day ago

➡️  itunes_transporter.rb doesn't handle failures during upload very well any more
    https://github.com/fastlane/fastlane/issues/13305 [open] 2 💬
    20 hours ago

➡️  [Regression] Sign in with the app-specific password you generated. If you forgot the app-specific password or need to create a new one, go to appleid.apple.com (-22938)
    https://github.com/fastlane/fastlane/issues/13321 [open] 1 💬
    38 minutes ago

and 7 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60zero%3F%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:67:in `execute': [!] undefined method `zero?' for nil:NilClass (NoMethodError)
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:287:in `block in execute'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `chdir'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:127:in `cd'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:286:in `execute'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/itunes_transporter.rb:380:in `upload'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/pilot/lib/pilot/build_manager.rb:38:in `upload'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
        from Fastfile:24:in `block (2 levels) in parsing_binding'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
        from /Users/jyurek/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.103.1/bin/fastlane:20:in `<top (required)>'
        from /Users/jyurek/.fastlane/bin/bundle/bin/fastlane:22:in `load'
        from /Users/jyurek/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
1 350s trumpet 2.5.1 ~/Development/myclient-iviewer/ios (jy-fastlane ✏ ) $

</pre></details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "my-app-specific-password"
    increment_build_number(xcodeproj: "MyClient.xcodeproj")
    build_app(scheme: "MyClient")
    upload_to_testflight
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.myclient.surgeon") # The bundle identifier of your app
apple_id("jyurek@gmail.com") # Your Apple email address

itc_team_id("118505367") # App Store Connect Team ID
team_id("YNCH98TY65") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.103.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.4       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| rubyzip                   | 1.2.2        |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.3        |
</details>

*generated on:* **2018-09-07**
</details>
</pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #13305
Fixes #13321
Fixes #13323

## Problem
The `$?.exitstatus` was recently changed to being returned from `FastlanePty.spawn`. If an error got raised from within `FastlanePty.spawn`, the exit status would not be returned. This would make the exit status variable that was expected to return actually end up being `nil` which would cause things to 💥 

## Solution
`FastlanePty.spawn` now wraps all exceptions in a `FastlanePtyError` which has a `exit_status` attributes which can be used by any of the callers.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]

**Comment by KrauseFx** [comment]
I couldn't find this: where was the regression introduced? Let's get a release for this out today 🚀

**Comment by joshdholtz** [comment]
@KrauseFx Was already planning on cutting a release this afternoon after this gets merged in 😉 

And here is the PR for reference - https://github.com/fastlane/fastlane/pull/13155

File: fastlane_core/lib/fastlane_core/fastlane_pty.rb [hunk 1]
```diff
@@ -31,6 +40,11 @@ def self.spawn(command)
         command_stdout.close
         p.value.exitstatus
       end
+    rescue StandardError => e
+      # Wrapping any error in FastlanePtyError to allow
+      # callers to see and use $?.exitstatus that
+      # would usually get returned
+      raise FastlanePtyError.new(e, $?.exitstatus)
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/fastlane_pty.rb]: Is `$?.exitstatus` actually set here? Above it uses and returns `p.value.exitstatus`...

Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/fastlane_pty.rb]: Ah, I guess this only supports the exit status with `PTY.spawn` but not with `Open3` 🤔 I can do a follow up PR

Comment (janpio) [reply fastlane_core/lib/fastlane_core/fastlane_pty.rb]: I am not sure how Open3 bubbles up the exit status... will have to look into it - and best create a test to confirm ;)

**Comment by janpio** [comment]
@KrauseFx @joshdholtz This is the actual PR and change that introduced the problem: https://github.com/fastlane/fastlane/pull/12995/files#diff-43ae8cabd94e685bf6289c43ba59b129

The problem is that in the case `FastlanePty.spawn` fails, it can't return that status. And testing cases of it failing is pretty hard, especially as there are thousands of different possible reasons - and only in 1 specific one (if the password is wrong and it suggests using the app specific password) it makes it worse for users as we have some special handling to retry with a manual prompt - which the crash of course made impossible :/

File: fastlane_core/lib/fastlane_core/command_executor.rb [hunk 2]
```diff
@@ -63,7 +63,8 @@ def execute(command: nil, print_all: false, print_command: true, error: nil, pre
               UI.command_output(line)
             end
           end
-        rescue => ex
+        rescue FastlaneCore::FastlanePtyError => ex
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/command_executor.rb]: Doesn't this change it, so only this specific exception is caught? What about all others?

File: fastlane_core/lib/fastlane_core/fastlane_pty.rb [hunk 3]
```diff
@@ -31,6 +40,11 @@ def self.spawn(command)
         command_stdout.close
         p.value.exitstatus
       end
+    rescue StandardError => e
```
Comment (janpio) [inline fastlane_core/lib/fastlane_core/fastlane_pty.rb]: `StandardError` means all Exceptions that can happen?

Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/fastlane_pty.rb]: Yup yup! This will catch everything that could happen

Comment (janpio) [reply fastlane_core/lib/fastlane_core/fastlane_pty.rb]: TIL Mother of all errors, so to speak.
