### PR TITLE
[register_device] fix regression that was causing a crash when creating a device that already exists

### LINKED ISSUE #17591: register_device crashes when device already exists
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Running register_device with a device that already exists in the Apple team causes fastlane to crash. This appears to have just started happening recently (upgraded from 2.161.0 to 2.166.0). I would expect register_device to handle a 409 Conflict by ignoring it, or maybe an option as to whether a Conflict should be ignored or crash?

##### Command executed

fastlane run register_device

##### Complete output when running fastlane, including the stack trace and command used

<details>
Running 'fastlane run register_device name:TestDevice udid:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx username:"xxxxx@xxxxxxxxxxxxx.com" team_id:"XXXXXXXXXX"'...Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
-----------------------------
--- Step: register_device ---
-----------------------------
Login to App Store Connect (onboard@mobileupsoftware.com)
Login successful
{
"errors" : [ {
"id" : "bef36781-0ef9-4302-b23a-a53433a1d16f",
"status" : "409",
"code" : "ENTITY_ERROR",
"title" : "There is a problem with the request entity",
"detail" : "A device with number 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' already exists on this team."
} ]
}

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Failed to register new device (name: TestDevice, platform: IOS, UDID: 7e0895d87c25a5e7b8aa8c4f1a2b9ee9792f39aa) (FastlaneCore::Interface::FastlaneCrash)
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/register_device.rb:33:in `rescue in run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/register_device.rb:29:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
from /usr/local/bin/fastlane:23:in `load'
from /usr/local/bin/fastlane:23:in `<main>'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `handle_response': { (Spaceship::UnexpectedResponse)
"errors" : [ {
"id" : "bef36781-0ef9-4302-b23a-a53433a1d16f",
"status" : "409",
"code" : "ENTITY_ERROR",
"title" : "There is a problem with the request entity",
"detail" : "A device with number '7e0895d87c25a5e7b8aa8c4f1a2b9ee9792f39aa' already exists on this team."
} ]
}
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:73:in `proxy_post'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/provisioning/client.rb:37:in `post'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/provisioning/provisioning.rb:88:in `post_device'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `post_device'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/spaceship/lib/spaceship/connect_api/models/device.rb:53:in `create'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/register_device.rb:30:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
from /usr/local/bin/fastlane:23:in `load'
from /usr/local/bin/fastlane:23:in `<main>'
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.4                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.26.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.4 (19E266)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.15.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.73.0       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday                   | 1.0.1        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.0        |
| googleauth                | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.1        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.5.1        |
| google-cloud-storage      | 1.26.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.295.0      |
| aws-eventstream           | 1.0.3        |
| aws-sigv4                 | 1.1.1        |
| aws-sdk-core              | 3.93.0       |
| aws-sdk-kms               | 1.30.0       |
| aws-sdk-s3                | 1.61.2       |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-11-11**
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This PR resolves a regression introduced in https://github.com/fastlane/fastlane/pull/17426 
It resolves #17591 and also this user's issue https://github.com/fastlane/fastlane/issues/17429#issuecomment-714302084 (they're the same).

### Description
The root cause of this issue is that since https://github.com/fastlane/fastlane/pull/17426 the new `ConnectAPI`'s "create device" method doesn't check if there's an existing device for the given UDID like the `Portal`'s one used to. This PR adds that verification, and adds tests around it.

I couldn't figure out how to create tests for the "create" method 🙇‍♂️🤔 so I wrote tests only for the new function I created.

### Testing Steps
To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-fix-register-device-existing-device"
```

Then run `bundle exec fastlane run register_device` passing a UDID that is already registered.

### CODE REVIEW

File: spaceship/lib/spaceship/connect_api/models/device.rb [hunk 1]
```diff
@@ -54,8 +54,26 @@ def self.all(client: nil, filter: {}, includes: nil, limit: nil, sort: nil)
...
+        end
+      end
+
       def self.create(client: nil, name: nil, platform: nil, udid: nil)
         client ||= Spaceship::ConnectAPI
+        
+        # Find the device by UDID and return it in case it already exists
+        existing = self.find_by_udid(udid, client: client, platform: platform)
+        if existing
+          UI.verbose("UDID '#{udid}' already exists - Skipping its creation...")
```
Comment (rogerluan) [inline spaceship/lib/spaceship/connect_api/models/device.rb:73]: This line uses `UI`, which is not accessible without importing the module.

1) Idk which module to import, or how 😅 need advise here 😬 
2) This leads me to think that a model class shouldn't have UI-related logic probably... 🤔 however I wouldn't like to give up on this handy log. Not sure how to proceed here, as I'm not familiar with architecture in ruby projects 😅 

Any help is appreciated! Right now `rubocop` is failing because of this line

File: spaceship/lib/spaceship/connect_api/models/device.rb [hunk 2]
```diff
@@ -54,8 +54,26 @@ def self.all(client: nil, filter: {}, includes: nil, limit: nil, sort: nil)
...
         client ||= Spaceship::ConnectAPI
+
+        # Find the device by UDID and return it in case it already exists
+        existing = self.find_by_udid(udid, client: client, platform: platform)
+        if existing
+          UI.verbose("UDID '#{udid}' already exists - Skipping its creation...")
+          return existing
+        end
+
         resp = client.post_device(name: name, platform: platform, udid: udid)
```
Comment (crooke) [inline spaceship/lib/spaceship/connect_api/models/device.rb:77]: So I don't know a lot about fastlane's inner workings or best practices, but could another approach be to check/catch if this POST request returns a 409 Conflict and simply ignore it (well, maybe log a message that the device already exists like you're doing above), since it would mean the device already exists. Just thinking that might be a simpler solution and shave off some time from the register_device operation.

File: spaceship/lib/spaceship/connect_api/models/device.rb (hunk 1 above)
Comment (crooke) [reply spaceship/lib/spaceship/connect_api/models/device.rb:73]: Can you use `puts` instead? I think my experience level is similar to yours in this domain though :)

Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/device.rb:73]: I could yeah, but that'd mean it would always be printed, as opposed to using the `UI` logging utilities 😅 logging utilities are great to filter out noisy information, and also provide nice coloring to the output logs

File: spaceship/lib/spaceship/connect_api/models/device.rb (hunk 2 above)
Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/device.rb:77]: I copied the same approach used in the old (now deprecated) method that did the same thing using the iTunes undocumented APIs: instead of recovering from an error after sending the request, it fails the request early before sending it to the server. The server could still return a 409 if a) the local check fails or b) if the request is invalid for other reasons, but I think that's okay

File: spaceship/lib/spaceship/connect_api/models/device.rb (hunk 1 above)
Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/device.rb:73]: I'm removing it
```suggestion
```

File: spaceship/lib/spaceship/connect_api/models/device.rb [hunk 3]
```diff
@@ -54,8 +54,25 @@ def self.all(client: nil, filter: {}, includes: nil, limit: nil, sort: nil)
...
+      end
+
       def self.create(client: nil, name: nil, platform: nil, udid: nil)
         client ||= Spaceship::ConnectAPI
+
+        # Find the device by UDID and return it in case it already exists
+        existing = self.find_by_udid(udid, client: client, platform: platform)
+        if existing
+          return existing
+        end
```
Comment (rogerluan) [inline spaceship/lib/spaceship/connect_api/models/device.rb:74]:
```suggestion
        return existing if existing
```

**Review by crooke — APPROVED** [review]

**Comment by crooke** [comment]
@rogerluan I tested this branch and it works. Thanks! Can this be merged now or is there anything I can do to help?

**Comment by rogerluan** [comment]
Hey @crooke, thanks for testing this branch and confirming it works! The only thing left is a final ✅ from @joshdholtz 🙏  thanks for your understanding!

File: spaceship/lib/spaceship/connect_api/models/device.rb [hunk 4]
```diff
@@ -54,8 +54,23 @@ def self.all(client: nil, filter: {}, includes: nil, limit: nil, sort: nil)
...
+      end
+
       def self.create(client: nil, name: nil, platform: nil, udid: nil)
         client ||= Spaceship::ConnectAPI
+
+        # Find the device by UDID and return it in case it already exists
+        existing = self.find_by_udid(udid, client: client, platform: platform)
+        return existing if existing
+
```
Comment (joshdholtz) [inline spaceship/lib/spaceship/connect_api/models/device.rb:73]: I think this works but I'm a little bit unsure about making use an existing one 🤔  Especially if this is fixing an action.

I think this "find or create" should be handled in `register_device`. Either that or there should be a method on this model called `find_or_create` just so that is more clear 😊 

Thoughts?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One thought on the making the "find or create" more clear 😊

File: spaceship/lib/spaceship/connect_api/models/device.rb (hunk 4 above)
Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/device.rb:73]: I agree! Single responsibility principle.

Right now we're using this method in 2 places, so instead of duplicating this logic in each of them, I'll create this `find_or_create` function as you suggested 😊

Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/device.rb]: Done! Lmk your thoughts 🤗

**Review by joshdholtz — APPROVED** [review]
This is great! Thanks for fixing this 😊
