### PR TITLE
[match] fix error with universal provisioning filter ("'UNIVERSAL' is not a valid filter value")

### LINKED ISSUE #29497: A parameter has an invalid value - 'UNIVERSAL' is not a valid filter value. Expected one of: IOS, MAC_OS
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Can't create provisioning profiles because fastlane is sending invalid parameters.

##### Command executed

`fastlane match(type: appstore)`

##### Complete output when running fastlane, including the stack trace and command used

Image

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 15.3.2                                                     |
| Ruby                        | 3.4.2                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.39.5 (Apple Git-154)                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.227.0/libexec/bin/fastlane |
| Host                        | macOS 15.3.2 (24D81)                                       |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.4.2/lib                        |
| OpenSSL Version             | OpenSSL 3.4.1 11 Feb 2025                                  |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 16.2                                                       |
| Swift Version               | 6.0.3                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'net/http'
require 'uri'
require 'json'

def update_config(key, value)
  church_header = ENV['CHURCH_HEADER']
  uri = URI.parse("https://cluster.apollos.app/api/config/#{church_header}")
  http = Net::HTTP.new(uri.host, uri.port)
  http.use_ssl = true if uri.scheme == 'https'

  request = Net::HTTP::Post.new(uri.request_uri)
  request['Content-Type'] = 'application/json'
  request['x-api-key'] = ENV['APOLLOS_API_KEY']

  request.body = { key: key, value: value }.to_json

  response = http.request(request)
  return unless response.code != '200'

  UI.user_error!("Failed to update config: #{response.code} #{response.message}")
end

def modify_env(key, value)
  env_file = '../.env'
  variable_found = false

  # Read the .env file into an array of lines
  env_lines = File.readlines(env_file)

  # Iterate through each line to find and modify the variable
  env_lines.map! do |line|
    if line.start_with?("#{key}=")
      variable_found = true
      "#{key}=#{value}\n" # Modify the existing variable
    else
      line
    end
  end

  # If the variable was not found, add it to the end of the file
  env_lines << "#{key}=#{value}\n" unless variable_found

  # Write the updated lines back to the .env file
  File.open(env_file, 'w') do |f|
    f.puts(env_lines)
  end
end

platform :ios do
  desc 'Sets up new app'
  lane :setup do
    produce(platforms: %w[ios tvos],
            # TODO: make sure this can work retroactively for Apps that already exist
            # or else we'll have to run seperate enable_services sh commands for existing apps
            # see deprecated ./scripts/setup.sh for details
            enable_services: { push_notification: 'on', app_group: 'on', associated_domains: 'on' })
    produce(app_identifier: "#{ENV['PRODUCE_APP_IDENTIFIER']}.OneSignalNotificationServiceExtension",
            app_name: 'Apollos Onesignal Extension', skip_itc: true, enable_services: { app_group: 'on' })
    # I wish Fastlane had a native way to do this :/
    sh("fastlane produce group -g \"group.#{ENV['PRODUCE_APP_IDENTIFIER']}.onesignal\" -n \"OneSignal Group\"")
    sh("fastlane produce associate_group \"group.#{ENV['PRODUCE_APP_IDENTIFIER']}.onesignal\"")
    sh("fastlane produce associate_group -a \"#{ENV['PRODUCE_APP_IDENTIFIER']}.OneSignalNotificationServiceExtension\" \"group.#{ENV['PRODUCE_APP_IDENTIFIER']}.onesignal\"")
    privacy
    certs
    notifications
  end

  desc 'Sets up Onesignal App'
  lane :notifications do
    pem(output_path: './fastlane', pem_name: 'apollos', force: true)
    onesignal(apns_p12: './fastlane/apollos.p12')
    app_id = lane_context[SharedValues::ONE_SIGNAL_APP_ID]
    modify_env('ONE_SIGNAL_APP_ID', app_id)
    update_config('ONE_SIGNAL.APP_ID', app_id)

    # TODO: OneSignal API changed and broke this
    auth_key = lane_context[SharedValues::ONE_SIGNAL_APP_AUTH_KEY]
    UI.user_error!('Failed to get auth key, set ONE_SIGNAL.REST_KEY manually!') if auth_key.nil? || auth_key.empty?
    update_config('ONE_SIGNAL.REST_KEY', auth_key)
  end

  desc 'Generates new certs/profiles and adds them to Match repo'
  lane :certs do
    match(type: 'appstore')
  end

  desc 'Renews expired certs/profiles and adds them to Match repo'
  lane :renew_certs do
    begin
      match(type: 'appstore', readonly: true, verbose: true)
    rescue StandardError => e
      UI.message(e)
    end
    match_nuke(type: 'appstore')
    match(type: 'appstore')
  end

  desc 'Prepares for running gym deploy'
  lane :prepare_gym do
    type = 'appstore'
    match(type: type, readonly: true)
    update_code_signing_settings(
      path: Dir.glob('ios/*.xcodeproj', base: '../').first,
      code_sign_identity: 'iPhone Distribution'
    )
    update_project_provisioning(
      xcodeproj: Dir.glob('ios/*.xcodeproj', base: '../').first,
      profile: ENV["sigh_#{ENV['FASTLANE_APP_IDENTIFIER']}_#{type}_profile-path"]
    )
    update_project_provisioning(
      xcodeproj: Dir.glob('ios/*.xcodeproj', base: '../').first,
      profile: ENV["sigh_#{ENV['FASTLANE_APP_IDENTIFIER']}.OneSignalNotificationServiceExtension_#{type}_profile-path"],
      target_filter: '.*OneSignal.*'
    )
  end

  desc 'Sets app privacy details'
  lane :privacy do
    upload_app_privacy_details_to_app_store(json_path: './fastlane/app-privacy-details.json')
  end

  desc 'Deploys a build to internal testflight or pushes internal to open beta or production'
  lane :deploy do
    track = ENV['TRACK'] || 'internal'
    UI.user_error!('Production deployment not ready!') if track == 'production' and ENV['PRODUCTION_READY'] != 'true'
    if ENV['DESIRED_VERSION'] && !ENV['DESIRED_VERSION'].empty?
      version = ENV['DESIRED_VERSION']
    else
      begin
        app_store_build_number
        live_version = lane_context[SharedValues::LATEST_VERSION]
        UI.message("Latest live version: #{live_version}")
      rescue StandardError => e
        UI.user_error!("Failed to get live version from App Store: #{e}") if e.to_s.include? 'agreement'
        UI.message("Failed to get live version from App Store: #{e}")
        live_version = nil
      end
      if live_version
        UI.message('Incrementing live version')
        increment_version_number(version_number: live_version)
        version = increment_version_number
      else
        version = '1.0.0'
      end
    end
    UI.message("Deploying version: #{version}")

    setup_ci
    UI.user_error!('ONE_SIGNAL_APP_ID is not set') if ENV['ONE_SIGNAL_APP_ID'].nil? || ENV['ONE_SIGNAL_APP_ID'].empty?
    prepare_gym
    increment_build_number(build_number: Time.now.to_i.to_s)
    increment_version_number(version_number: version)
    gym(export_method: 'app-store')

    if version == '1.0.0'
      UI.message('Set pricing, press enter...')
      $stdin.gets
    end

    if track == 'internal'
      testflight(skip_waiting_for_build_processing: false)
    elsif track == 'beta'
      testflight(
        distribute_external: true,
        groups: 'Beta Testers',
        app_platform: 'ios'
      )
    elsif track == 'production'
      deliver(
        overwrite_screenshots: true,
        submit_for_review: true,
        automatic_release: false,
        submission_information: {
          "add_id_info_uses_idfa": false,
          "content_rights_contains_third_party_content": false
        },
        reject_if_possible: true,
        run_precheck_before_submit: false,
        platform: 'ios',
        # https://github.com/fastlane/fastlane/issues/21819
        # price_tier: 0, This one is still manual for now
        app_rating_config_path: './fastlane/app-rating-config.json',
        force: true
      )
    end
  end
end

platform :android do
  desc 'Sets up new app'
  lane :setup do
    notifications
  end

  desc 'Sets up Onesignal App'
  lane :notifications do
    onesignal(fcm_json: './fastlane/fcm.json')
    app_id = lane_context[SharedValues::ONE_SIGNAL_APP_ID]
    update_config('ONE_SIGNAL.APP_ID', app_id)
    modify_env('ONE_SIGNAL_APP_ID', app_id)

    # TODO: OneSignal API changed and broke this
    auth_key = lane_context[SharedValues::ONE_SIGNAL_APP_AUTH_KEY]
    UI.user_error!('Failed to get auth key, set ONE_SIGNAL.REST_KEY manually!') if auth_key.nil? || auth_key.empty?
    update_config('ONE_SIGNAL.REST_KEY', auth_key)
  end

  desc 'Deploy an Android app'
  lane :deploy do
    validate_play_store_json_key
    track = ENV['TRACK'] || 'internal'
    # Set the Android version offset if it's not already set
    build_code_offset = ENV['ANDROID_BUILD_CODE_OFFSET'] || 0

    if ENV['DESIRED_VERSION'] && !ENV['DESIRED_VERSION'].empty?
      version = ENV['DESIRED_VERSION']
    else
      begin
        live_version = google_play_track_release_names[0]
        UI.message("Latest live version: #{live_version}")
      rescue StandardError => e
        UI.user_error!("Failed to get live version from Google Play: #{e}") if e.to_s.include? 'permission'
        UI.message("Failed to get live version from Google Play: #{e}")
        live_version = nil
      end

      if live_version
        semver_regex = /(\d+(?:\.\d+){0,2})/
        UI.message('Incrementing live version')
        versions = live_version.scan(semver_regex).flatten
        UI.user_error!('Version is not in the correct format!') unless versions
        # find semver version and increment patch
        # if version is 4 we want to increment to 4.0.1
        # if version is 4.1 we want to increment to 4.1.1
        # so the last two sections should be optional when finding the regex
        #
        # if we find two matches, we want to take the
        # first one closest to a real semver
        # it could be 100 (1.0.0) or 1.0.0 (100)
        semver_version = versions.find { |v| v.split('.').length == 3 }
        unless semver_version
          major_minor_version = versions.find { |v| v.split('.').length == 2 }
          semver_version = major_minor_version + '.0' if major_minor_version
        end
        semver_version ||= versions[0] + '.0.0'

        # now increment the patch
        components = semver_version.split('.').map(&:to_i)
        components[-1] += 1
        version = components.join('.')
      else
        UI.user_error!('Failed to get live version from Google Play. use DESIRED_VERSION=1.0.0 to create a new app manually.')
      end
    end
    UI.message("Deploying version: #{version}")
    # TODO: put back when onesignal API bug is fixed
    # notifications
    if version == '1.0.0'
      UI.message('Upload FCM to OneSignal, press enter...')
      $stdin.gets
    end

    date_in_hrs = Time.now.to_i / 3600
    mobile_version_offset = 1_000_000

    codes_to_keep = []
    if version != '1.0.0'
      begin
        earliest = Time.new(2020, 1, 1).to_i / 3600
        version_codes = google_play_track_version_codes(track: track)
        codes_as_timestamps = version_codes.map { |code| code.to_i - build_code_offset.to_i - mobile_version_offset }
        non_apollos_mobile_codes = codes_as_timestamps.select do |timestamp|
          timestamp < earliest or timestamp > date_in_hrs
        end
        codes_to_keep = non_apollos_mobile_codes.map do |timestamp|
          timestamp + build_code_offset.to_i + mobile_version_offset
        end
      rescue StandardError => e
        UI.user_error!("Failed to get version codes: #{e}") if e.to_s.include? 'permission'
        UI.message("Failed to get version codes: #{e}")
        codes_to_keep = []
      end
      UI.message("Keeping version codes: #{codes_to_keep}")
    end

    version_code = date_in_hrs + mobile_version_offset + build_code_offset.to_i
    build_gradle_file = '../android/app/build.gradle'
    gradle_file = File.read(build_gradle_file)
    gradle_file = gradle_file.gsub(/versionCode \d+\s*$/, "versionCode #{version_code}")
    gradle_file = gradle_file.gsub(/versionName ".*"\s*$/, "versionName \"#{version}\"")
    File.open(build_gradle_file, 'w') { |file| file.puts gradle_file }

    # Build the Android App
    gradle(task: 'clean', project_dir: 'android')
    gradle(
      task: 'bundle',
      build_type: 'Release',
      project_dir: 'android',
      properties: {
        'android.injected.signing.store.file' => ENV['KEYSTORE_FILE'],
        'android.injected.signing.store.password' => ENV['KEYSTORE_PASSWORD'],
        'android.injected.signing.key.alias' => ENV['KEY_ALIAS'],
        'android.injected.signing.key.password' => ENV['KEY_PASSWORD']
      }
    )

    UI.user_error!('Production deployment not ready!') if track == 'production' and ENV['PRODUCTION_READY'] != 'true'
    if version == '1.0.0'
      UI.message('Upload AAB, finish dashboard steps, promote to production, press enter...')
      loop do
        $stdin.gets
        begin
          google_play_track_version_codes(track: track)
        rescue StandardError => e
          UI.message("#{e}")
          UI.message('Try again and press enter...')
          next
        end
        break
      end
    end
    supply(
      track: track,
      version_codes_to_retain: codes_to_keep,
      skip_upload_aab: version == '1.0.0',
      skip_upload_changelogs: version == '1.0.0',
      changes_not_sent_for_review: true,
      aab: 'android/app/build/outputs/bundle/release/app-release.aab'
    )
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.227.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.7.0        |
| did_you_mean                    | 2.0.0        |
| syntax_suggest                  | 2.0.2        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| aws-eventstream                 | 1.3.2        |
| aws-partitions                  | 1.1065.0     |
| aws-sigv4                       | 1.11.0       |
| base64                          | 0.2.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.220.1      |
| aws-sdk-kms                     | 1.99.0       |
| aws-sdk-s3                      | 1.182.0      |
| babosa                          | 1.0.4        |
| bundler                         | 2.6.3        |
| rexml                           | 3.4.1        |
| nkf                             | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.1.0        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.8        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.4.0        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.10.1       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| mutex_m                         | 0.3.0        |
| httpclient                      | 2.9.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.5.0        |
| google-cloud-core               | 1.8.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.7.0        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.9.1        |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.6.0        |
| plist                           | 3.7.2        |
| rubyzip                         | 2.4.1        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.1        |
| forwardable                     | 1.3.3        |
| logger                          | 1.6.4        |
| pathname                        | 0.4.0        |
| shellwords                      | 0.2.2        |
| cgi                             | 0.4.1        |
| date                            | 3.4.1        |
| timeout                         | 0.4.3        |
| stringio                        | 3.1.2        |
| securerandom                    | 0.4.1        |
| uri                             | 1.0.2        |
| ipaddr                          | 1.2.7        |
| openssl                         | 3.3.0        |
| digest                          | 3.2.0        |
| io-nonblock                     | 0.3.1        |
| zlib                            | 3.2.1        |
| resolv                          | 0.6.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.4.1        |
| open-uri                        | 0.5.0        |
| net-http                        | 0.6.0        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.4        |
| strscan                         | 3.1.2        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.8.0        |
| tempfile                        | 0.3.1        |
| delegate                        | 0.4.0        |
| fileutils                       | 1.7.3        |
| tmpdir                          | 0.3.1        |
| singleton                       | 0.3.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.6.2        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.1        |
| yaml                            | 0.4.0        |
| psych                           | 5.2.2        |
</details>

*generated on:* **2025-03-18**
</details>
 </pre>
</details>

### PR DESCRIPTION
**Pull request by redreceipt**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Closes #29497

### Description

Removes `UNIVERSAL` device filter

### CODE REVIEW

**Comment by maria456cd** [comment]
This PR description is excellent: it clearly states all necessary checks were completed (tests, code style, CI), references the related issue, and concisely describes the change ("Removes UNIVERSAL device filter"). Adding a brief rationale for the removal would be a minor improvement. 
[Stuff Your Kindled Day in 2025](https://www.stuffyourkindledays.com)

**Review by madclouds — APPROVED** [review]

**Review by sidorchukandrew — APPROVED** [review]

**Review by jantony-ps — APPROVED** [review]

**Review by bawahakim — APPROVED** [review]

**Comment by bawahakim** [comment]
@KrauseFx Any chance this can be merged in and released ASAP? As currently it breaks the iOS build flow for many :)

**Review by sanieldalib — APPROVED** [review]

**Comment by emirerdo** [comment]
We need this fix ASAP as our pipeline is completely blocked due to this issue.

**Comment by bawahakim** [comment]
For those waiting for this to be merged and released, we temporarily are building fastlane and using that custom binary instead of the published package. 

Thanks to @redreceipt for the fixes!

Steps how we achieved it:
1. Ensure you have a suitable ruby version. We installed rbenv and installed ruby `3.3.0` (`3.4.2` caused some issues)
2. Clone https://github.com/redreceipt/fastlane and cd into it
3. Cherry pick `aff685e3241abef52bd79d21ce6df3f014d45b5b` and `18344d4b852c7c41a579db7eacf1c91752bdcde6` (both fixes were needed)
4. Run `bundle install` (may need to install bundler)
5. Run `bundle exec rake build`
6. Run `gem install pkg/fastlane-2.227.0.gem` (may be a different version)

Now you have a local custom version of fastlane :partying_face:

Disclaimer: I have 0 experience in ruby/gem, just followed some instructions to get this up and running

**Review by sergei-mikhailovskii-idf — APPROVED** [review]

**Comment by denysbaralei** [comment]
please review

**Comment by ajeetfancode** [comment]
please merge this!!!

**Review by viktor-savchik-idf — APPROVED** [review]

**Review by ajeetfancode — APPROVED** [review]

**Comment by suside** [comment]
Hey @redreceipt thanks for the bugfix but is there any chance you could fix the unit tests please?

```ruby
  1) Match Match::Portal::Fetcher devices fetches devices
     Failure/Error: portal_devices = sut.devices(platform: 'ios')
       #<Spaceship::ConnectAPI::Device (class)> received :all with unexpected arguments
         expected: ({:client=>anything, :filter=>{:platform=>"IOS,UNIVERSAL", :status=>"ENABLED"}})
              got: ({:client=>nil, :filter=>{:platform=>"IOS", :status=>"ENABLED"}})
       Diff:
       @@ -1,3 +1,2 @@
       -[{:client=>anything,
       -  :filter=>{:platform=>"IOS,UNIVERSAL", :status=>"ENABLED"}}]
       +[{:client=>nil, :filter=>{:platform=>"IOS", :status=>"ENABLED"}}]
        Please stub a default value first if message might be received with other args as well. 
     # ./spaceship/lib/spaceship/connect_api/models/device.rb:117:in `devices_for_platform'
     # ./match/lib/match/portal_fetcher.rb:53:in `devices'
     # ./match/spec/portal_fetcher_spec.rb:83:in `block (4 levels) in <top (required)>'

**Comment by HiddeRpl** [comment]
> Hey @redreceipt thanks for the bugfix but is there any chance you could fix the unit tests please?
> 
> ```ruby
>   1) Match Match::Portal::Fetcher devices fetches devices
>      Failure/Error: portal_devices = sut.devices(platform: 'ios')
>        #<Spaceship::ConnectAPI::Device (class)> received :all with unexpected arguments
>          expected: ({:client=>anything, :filter=>{:platform=>"IOS,UNIVERSAL", :status=>"ENABLED"}})
>               got: ({:client=>nil, :filter=>{:platform=>"IOS", :status=>"ENABLED"}})
>        Diff:
>        @@ -1,3 +1,2 @@
>        -[{:client=>anything,
>        -  :filter=>{:platform=>"IOS,UNIVERSAL", :status=>"ENABLED"}}]
>        +[{:client=>nil, :filter=>{:platform=>"IOS", :status=>"ENABLED"}}]
>         Please stub a default value first if message might be received with other args as well. 
>      # ./spaceship/lib/spaceship/connect_api/models/device.rb:117:in `devices_for_platform'
>      # ./match/lib/match/portal_fetcher.rb:53:in `devices'
>      # ./match/spec/portal_fetcher_spec.rb:83:in `block (4 levels) in <top (required)>'
> ```

And also the linter

```
spaceship/lib/spaceship/connect_api/models/device.rb:80:26: C: [Correctable] Style/TrailingCommaInArrayLiteral: Avoid comma after the last item of an array.
          device_platform,
                         ^
```

**Comment by ajeetfancode** [comment]
I have updated the lint issue and test cases related to this PR, please merge the below PR. I have added both the patches(patch-2, patch3) as suggested by @redreceipt. If @redreceipt updates this PR with the test-case and lint fix, feel free to ignore my PR.
@KrauseFx 
https://github.com/fastlane/fastlane/pull/29509

**Comment by prabhakarj13** [comment]
Please merge the fix

**Review by ankurs-fancode — APPROVED** [review]

**Review by shivatalwar — APPROVED** [review]

File: spaceship/lib/spaceship/connect_api/models/device.rb [hunk 1]
```diff
@@ -78,7 +78,6 @@ def self.devices_for_platform(platform: nil, include_mac_in_profiles: false, cli
 
         device_platforms = [
           device_platform,
```
Comment (redreceipt) [inline spaceship/lib/spaceship/connect_api/models/device.rb:80]:
```suggestion
          device_platform
```

File: match/spec/portal_fetcher_spec.rb [hunk 2]
```diff
@@ -18,7 +18,7 @@
 
     let(:default_device_all_params) do
       {
-        filter: { platform: 'IOS,UNIVERSAL', status: 'ENABLED' },
+        filter: { platform: 'IOS', status: 'ENABLED' },
         client: anything
```
Comment (redreceipt) [inline match/spec/portal_fetcher_spec.rb:22]:
```suggestion
        client: nil
```

**Comment by redreceipt** [comment]
sorry everyone, tests and lint fixed (I think)

**Comment by ajeetfancode** [comment]
Let get this merged now

**Review by junedfc — APPROVED** [review]

**Comment by ecexplorer** [comment]
Apple must also be making changes. Without any workarounds or changes, we're able to deploy to App Store.

**Comment by amitTopdocOrg** [comment]
let's release this

**Comment by ajeetfancode** [comment]
Till the time this is merged, if anyone is looking for a workaround then update you gemfile and do a `bundle install`.
This worked for me.
changes you need:
`gem "fastlane",:git => 'git@github.com:ajeetfancode/fastlane.git',:branch => 'universalDevice'`

**Review by amitTopdocOrg — APPROVED** [review]

**Review by oscar-balandran — APPROVED** [review]

**Comment by mabdullahsaeed** [comment]
please merge this and release a new version

**Review by ethancookeyouitv — APPROVED** [review]

**Review by bbellp — APPROVED** [review]

**Review by rogerluan — APPROVED** [review]
Merging this in given the amount of approvals and vouches the community has given it — thanks everyone who contributed testing this! ☺️ 

Will deploy this later today!

**Comment by the-white-cat** [comment]
fastlane: stable 2.227.2 issue still exists while performing match :(

**Comment by sportunity-selectie** [comment]
I still have this issue in 2.227.2 also :-(

**Comment by dakshatsuraasa** [comment]
Sill the same issue!

**Comment by gholias** [comment]
The problem is back today
``` A parameter has an invalid value - 'UNIVERSAL' is not a valid filter value. Expected one of: IOS, MAC_OS```

Im using `2.227.2`

**Comment by GasGas94** [comment]
Dears, is anyone investigating this issue? Is there any word on when it will be fixed?

**Comment by newtween** [comment]
@GasGas94 Unfortunately the [commit](https://github.com/fastlane/fastlane/pull/29561) that fixes the problem was closed without comment

**Comment by GasGas94** [comment]
@newtween Got it...so how long do we have to wait now based on your experience?

**Comment by alex-mironov** [comment]
Still getting the same issue on 2.227.2
```
🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/Users/gitlab/builds/.../vendor/ruby/ruby/3.3.0/bin/fastlane)
/Users/.../vendor/ruby/ruby/3.3.0/gems/fastlane-2.227.2/spaceship/lib/spaceship/connect_api/api_client.rb:223:in `handle_response': [!] The provided entity includes an unknown attribute - 'templateName' is not an attribute on the resource 'profiles' - /data/attributes/templateName (Spaceship::UnexpectedResponse)
```
