### PR TITLE
Handle non UTF-8 metadata more gracefully

### LINKED ISSUE #1967: Error with posting data with 0x00FA character
<table>
      <tr>
        <td>
          
        </td>
        <td>
          Original issue by @chrisvire - Imported from <a href='https://github.com/fastlane/supply/issues/26'>fastlane/supply#26</a>
        </td>
      </tr>
    </table>

We are trying to post a full description with accented u (0x00FA).

https://dl.dropboxusercontent.com/u/4049729/github/supply/full_description.txt

However, supply fails when google-api-client tries to encode as US-ASCII (even though it is trying to load metadata for language 'es-419').  Do I need to create the file differently?

```
[17:59:26]: Loading metadata for language 'es-419'...
/var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:342:in `encode': "\xFA" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:342:in `to_json'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:342:in `serialize_body'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client/request.rb:93:in `initialize'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:556:in `new'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:556:in `generate_request'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:621:in `execute!'
	from /var/lib/gems/2.0.0/gems/google-api-client-0.8.6/lib/google/api_client.rb:679:in `execute'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/client.rb:180:in `update_listing_for_language'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/listing.rb:25:in `save'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/uploader.rb:36:in `upload_metadata'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/uploader.rb:16:in `block in perform_upload'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/uploader.rb:11:in `foreach'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/uploader.rb:11:in `perform_upload'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/commands_generator.rb:37:in `block (2 levels) in run'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /var/lib/gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/commands_generator.rb:55:in `run'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/lib/supply/commands_generator.rb:15:in `start'
	from /var/lib/gems/2.0.0/gems/supply-0.2.2/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by asfalcone**
Fixes #1967 by writing data as UTF-8 and giving a better error message when trying to upload data that is not saved as UTF-8.

### CODE REVIEW

File: supply/lib/supply/uploader.rb [hunk 1]
```diff
@@ -50,7 +50,12 @@ def upload_metadata(language, listing)
         path = File.join(metadata_path, language, "#{key}.txt")
         listing.send("#{key}=".to_sym, File.read(path)) if File.exist?(path)
       end
-      listing.save
+      begin
+        listing.save
```
Comment (i2amsam) [inline supply/lib/supply/uploader.rb]: Can we add a test?

**Comment by i2amsam** [comment]
Looks good, it'd be nice to add a test too to prevent regression.

**Comment by i2amsam** [comment]
LGTM
