### PR TITLE
Fix pty not fully flushing output and causing flaky tests #21792

### LINKED ISSUE #21792: fastlane_core/spec/command_executor_spec.rb:12 is flaky
```
  1) FastlaneCore FastlaneCore::CommandExecutor execute executes a simple command successfully
     Failure/Error: expect(result).to eq('foo')
     
       expected: "foo"
            got: ""
     
       (compared using ==)
     # ./fastlane_core/spec/command_executor_spec.rb:12:in `block (5 levels) in <top (required)>'
     # ./.bundle/ruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) FastlaneCore FastlaneCore::CommandExecutor execute executes a simple command successfully
     Failure/Error: expect(result).to eq('foo')
     
       expected: "foo"
            got: ""
     
       (compared using ==)
     # ./fastlane_core/spec/command_executor_spec.rb:12:in `block (5 levels) in <top (required)>'
     # ./.bundle/ruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  3) FastlaneCore FastlaneCore::CommandExecutor execute executes a simple command successfully
     Failure/Error: expect(result).to eq('foo')
     
       expected: "foo"
            got: ""
     
       (compared using ==)
     # ./fastlane_core/spec/command_executor_spec.rb:12:in `block (5 levels) in <top (required)>'
     # ./.bundle/ruby/3.1.0/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 53.7 seconds (files took 2.1 seconds to load)
10000 examples, 3 failures
```

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by lacostej**
See #21792 

Does it also fail on CI?

### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #21792

command execution randomly fails in CI due to the output being not consistently flushed

### Description

After investigating many solutions, the only type of workaround was to force the PTY to flush the outputs by adding a second empty command to run. In fact, just adding a `;` at the end of the command seems to be enough.

### Testing Steps

Look at #21792 for many experiments and ways to reproduce the issue.

### CODE REVIEW

**Comment by lacostej** [comment]
Here's one example of the issue I am trying to uncover being triggered.

https://app.circleci.com/pipelines/github/fastlane/fastlane?branch=pull%2F21799
https://app.circleci.com/pipelines/github/fastlane/fastlane/6110/workflows/6f6fa7ff-6f2e-4fc1-8664-bb17b55b0a15/jobs/95892/tests#failed-test-0

The current PR is just trying to show the issue but hits a `ulimit` issue. I'll first try to reproduce it here.

**Comment by lacostej** [comment]
Well not sure why the tests suddenly failed in circle for no apparent reason. Looks like a general build issue on circle. Adding some doc to the pty class to trigger a new build.

**Comment by iBotPeaches** [comment]
Those failures look crazy, like CircleCI lost connection with all runners at once.

You can rerun jobs on detail page.

Screenshot_20251202-053945

File: fastlane_core/spec/command_executor_spec.rb [hunk 1]
```diff
@@ -98,7 +111,9 @@
             print_all: false,
             error: nil
           )
-        end.to output(failing_command_output).to_stdout.and(raise_error)
+        end.to output(failing_command_output).to_stdout.and(raise_error(FastlaneCore::Interface::FastlaneError) do |error|
```
Comment (lacostej) [inline fastlane_core/spec/command_executor_spec.rb:114]: this was just a warning from rubocop that I felt could be fixed here. Unrelated to the issue.

File: fastlane_core/spec/fastlane_pty_spec.rb [hunk 2]
```diff
@@ -14,9 +14,15 @@
       end
 
       it 'doesn t return -1 if an exception was raised in the block in PTY.spawn' do
+        status = double("ProcessStatus")
+        allow(status).to receive(:exitstatus) { 0 }
```
Comment (lacostej) [inline fastlane_core/spec/fastlane_pty_spec.rb:18]: changing the implementation made this fail and return status code that was -1 on my machine but 1 on others. This is also specific to the command and to the timing of the parsing error vs the execution of the command.

So we make this test a bit less dependent on all these factors to control the way it will be managed by our stack.

File: fastlane_core/spec/command_executor_spec.rb [hunk 3]
```diff
@@ -16,22 +16,30 @@
...
       it 'handles reading which throws a EIO exception', requires_pty: true do
-        fake_std_in = [
+        fake_std_in_lines = [
           "a_filename\n"
         ]
-        expect(fake_std_in).to receive(:each).and_yield(*fake_std_in).and_raise(Errno::EIO)
+        fake_std_in = double("stdin")
+        expect(fake_std_in).to receive(:each).and_yield(*fake_std_in_lines).and_raise(Errno::EIO)
+
+        #expect(fake_std_in).to receive(:each).and_yield(*fake_std_in).and_raise(Errno::EIO)
```
Comment (iBotPeaches) [inline fastlane_core/spec/command_executor_spec.rb]: commented out chunk here

**Review by iBotPeaches — APPROVED** [review]
The difference of the exit code slightly worried me, but I checked the areas in codebase and all are `!= 0` so should be fine.

I found one explicit check for `-1`, but also seems like a workaround that a regular `1` would be handled with.

+1

**Review by iBotPeaches — APPROVED** [review]
no more flake - LGTM

**Comment by lacostej** [comment]
I've been burned by the failed match encryption format upgrade that I made in 220 that caused a lot of issues (e.g. #21973) for users.

I wonder if we should build in a little inbuilt mechanism for people to disable the extra ";" in case it causes issues for them for special commands. Given that this is an issue we seem to only experience for really fast commands, randomly affecting a few tests there and there. Really annoying for us but probably very little chance of hitting this in real life.

We could for example do something like
```
command = ENV['FASTLANE_EXEC_ORIGINAL_COMMAND'].nil? ? "#{original_command};" : original_command
```

I could add some tests to cover that case.

Alternatively we could only enable this during our tests as well.

**Comment by iBotPeaches** [comment]
Hmm that is a very good point. I like that ENV that defaults to off that we throw on in test suite, since I haven't seen a complaint about this in real usage - only tests.

**Comment by iBotPeaches** [comment]
Guess PTY doesn't exist on Windows - learn something new every day.

**Comment by iBotPeaches** [comment]
> CircleCI failed to run this build, check your config. Try re-running the build and if this issue persists, open a [Support ticket](https://support.circleci.com/hc/en-us). Detail: The task agent failed to run exited with code: run failed: exit status 1. This error indicates a fatal agent failure, typically due to resource exhaustion or API connectivity issues. If using VPN (like OpenVPN), see: https://support.circleci.com/hc/en-us/articles/360049397051-How-to-set-up-a-VPN-connection-during-builds-#openvpn. Try a larger resource class to test for resource exhaustion

lol what luck.

Screenshot 2025-12-03 at 11 56 03 AM

**Review by iBotPeaches — APPROVED** [review]
Reviewed latest changes
