### PR TITLE
Version bump to 2.74.0

### LINKED ISSUE #11395: fastlane deliver error with ruby 2.5.0
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
fastlane deliver error

##### Complete output when running fastlane, including the stack trace and command used
run

> fastlane deliver --skip_screenshots

get

> [⠋] 🚀 /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/user_interaction.rb:334: warning: constant ::Data is deprecated

> ...
> Loading './metadata/review_information/notes.txt'...

> Traceback (most recent call last):
> 	18: from /Users/user/.rbenv/versions/2.5.0/bin/fastlane:23:in `<main>'
> 	17: from /Users/user/.rbenv/versions/2.5.0/bin/fastlane:23:in `load'
> 	16: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/bin/fastlane:20:in `<top (required)>'
> 	15: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/fastlane/lib/fastlane/cli_tools_distributor.rb:83:in `take_off'
> 	14: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/commands_generator.rb:12:in `start'
> 	13: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/commands_generator.rb:177:in `run'
> 	12: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
> 	11: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
> 	10: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
> 	 9: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
> 	 8: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
> 	 7: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/commands_generator.rb:74:in `block (2 levels) in run'
> 	 6: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/runner.rb:25:in `run'
> 	 5: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/runner.rb:106:in `upload_metadata'
> 	 4: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/runner.rb:162:in `validate_html'
> 	 3: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/html_generator.rb:10:in `run'
> 	 2: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.72.0/deliver/lib/deliver/html_generator.rb:44:in `render'
> 	 1: from /Users/user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `result'
> /Users/user/.rbenv/versions/2.5.0/lib/ruby/2.5.0/erb.rb:885:in `eval': **(erb):265: syntax error, unexpected ')', expecting end-of-input (SyntaxError)
> );  if @options[:trade_represe...
> ^**

### Environment

[⠋] 🚀 /Users/user/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.5/lib/commander/user_interaction.rb:334: warning: constant ::Data is deprecated
[✔] 🚀 
[12:12:07]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[12:12:07]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.2                                     |
| Ruby                        | 2.5.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.14.3 (Apple Git-98)           |
| Installation Source         | ~/.rbenv/versions/2.5.0/bin/fastlane        |
| Host                        | Mac OS X 10.13.2 (17C88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.5.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2n  7 Dec 2017                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.72.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.60.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.0.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| bundler                   | 1.16.1       |
| date                      | 1.0.0        |
| fileutils                 | 1.0.2        |
| ipaddr                    | 1.2.0        |
| openssl                   | 2.1.0        |
</details>

*generated on:* **2018-01-03**
</details>

### PR DESCRIPTION
**Pull request by KrauseFx**
Auto-generated by fastlane 🤖

**Changes since release '2.73.0':**

* Bump slack-notifier Gem Dependency (#11446) via Joe Masilotti
* Improve fastlane Fastfile (#11455) via Jan Piotrowski
* Fix missing Boolean import in snapshot (#11450) via Manu Wallner
* Require fixes and optimizations (#11244) via Manu Wallner
* [snapshot] Add test-without-building capability (#11404) via igor-makarov
* deliver: work-around ruby 2.5.0 ERB compatibility (fixes #11395) (#11436) via Jerome Lacoste
* fastlane/rspec: make test pass on ruby 2.5.0 (#11437) via Jerome Lacoste
* Enable cancelling of running lanes (#11419) via Joshua Liebowitz

### CODE REVIEW

File: fastlane/swift/Gymfile.swift [hunk 1]
```diff
@@ -11,4 +11,4 @@ class Gymfile: GymfileProtocol {
 
 
 
-// Generated with fastlane 2.72.0
+// Generated with fastlane 2.73.0
```
Comment (lacostej) [inline fastlane/swift/Gymfile.swift]: are those meant to always be one version behind?

**Review by janpio — APPROVED** [review]

File: fastlane/swift/Gymfile.swift (hunk 1 above)
Comment (lacostej) [reply fastlane/swift/Gymfile.swift]: Sent https://github.com/fastlane/fastlane/pull/11467 for this.
