### PR TITLE
[spaceship] Explicitly allow to continue 2FA in non-interactive mode

### LINKED ISSUE #18094: `fastlane spaceauth` is failing with `2FA can only be performed in interactive mode`
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.172.0
- Last working version: 2.170.0

### Regression Description

We have a `node` program that update Apple session periodically using `fastlane spaceauth`. The 2FA code is written to the `stdin` of the child process. Thus the streams are not tty. This recent change: https://github.com/fastlane/fastlane/pull/17854 forces the command to run only in interactive shell which breaks our pipeline. As there are ways to send input to interactive program running in non-interactive shell and ways to check whether the shell is interactive or not before executing a program, it doesn't seem appropriate to force users to use `spaceauth` only in interactive shell.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>"/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/two_step_or_factor_client.rb:7:in `handle_two_step_or_factor': \u001b[31m[!] 2FA can only be performed in interactive mode\u001b[0m (RuntimeError)
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:500:in `send_shared_login_request'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:793:in `do_login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:390:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/client.rb:352:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/spaceauth_runner.rb:18:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:44:in `block (2 levels) in run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:50:in `run'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/spaceship/lib/spaceship/commands_generator.rb:14:in `start'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/fastlane/lib/fastlane/cli_tools_distributor.rb:114:in `take_off'
\tfrom /usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.172.0/bin/fastlane:23:in `<top (required)>'
\tfrom /usr/local/bin/fastlane:23:in `load'
\tfrom /usr/local/bin/fastlane:23:in `<main>`</pre>
</details>

### Environment

<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | debian_based 9.13                                        |
| Ruby                        | 2.5.7                                                    |
| Bundler?                    | false                                                    |
| Git                         | git version 2.11.0                                       |
| Installation Source         | /usr/local/bin/fastlane                                  |
| Host                        | Debian GNU/Linux 9 debian_based 9.13 (4.19.121-linuxkit) |
| Ruby Lib Dir                | /usr/local/lib                                           |
| OpenSSL Version             | OpenSSL 1.1.0l  10 Sep 2019                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.172.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.2.0        |
| slack-notifier                | 2.3.2        |
| atomos                        | 0.1.3        |
| CFPropertyList                | 3.0.3        |
| claide                        | 1.0.3        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.3.0        |
| xcodeproj                     | 1.19.0       |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.3.0        |
| terminal-notifier             | 2.0.0        |
| unicode-display_width         | 1.7.0        |
| terminal-table                | 1.8.0        |
| plist                         | 3.6.0        |
| public_suffix                 | 4.0.6        |
| addressable                   | 2.7.0        |
| multipart-post                | 2.0.0        |
| word_wrap                     | 1.0.0        |
| tty-screen                    | 0.8.1        |
| tty-cursor                    | 0.7.1        |
| tty-spinner                   | 0.9.3        |
| artifactory                   | 3.0.15       |
| babosa                        | 1.0.4        |
| colored                       | 1.2          |
| highline                      | 1.7.10       |
| commander-fastlane            | 4.4.6        |
| excon                         | 0.78.1       |
| faraday-net_http              | 1.0.1        |
| ruby2_keywords                | 0.0.4        |
| faraday                       | 1.3.0        |
| unf_ext                       | 0.0.7.7      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20190701 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.7        |
| faraday_middleware            | 1.0.0        |
| fastimage                     | 2.2.1        |
| gh_inspector                  | 1.1.3        |
| json                          | 2.1.0        |
| mini_magick                   | 4.11.0       |
| rubyzip                       | 2.3.0        |
| security                      | 0.1.3        |
| xcpretty-travis-formatter     | 1.0.1        |
| dotenv                        | 2.7.6        |
| bundler                       | 2.2.6        |
| naturally                     | 2.2.1        |
| simctl                        | 1.6.8        |
| jwt                           | 2.2.2        |
| uber                          | 0.1.0        |
| declarative                   | 0.0.20       |
| declarative-option            | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.1.2        |
| mini_mime                     | 1.0.2        |
| multi_json                    | 1.15.0       |
| signet                        | 0.14.0       |
| memoist                       | 0.16.2       |
| os                            | 1.1.1        |
| googleauth                    | 0.14.0       |
| httpclient                    | 2.8.3        |
| google-api-client             | 0.38.0       |
| google-cloud-env              | 1.4.0        |
| google-cloud-errors           | 1.0.1        |
| google-cloud-core             | 1.5.0        |
| rexml                         | 3.2.4        |
| webrick                       | 1.4.2        |
| google-apis-core              | 0.2.1        |
| google-apis-iamcredentials_v1 | 0.1.0        |
| google-apis-storage_v1        | 0.1.0        |
| rake                          | 12.3.0       |
| digest-crc                    | 0.6.3        |
| google-cloud-storage          | 1.30.0       |
| emoji_regex                   | 3.2.1        |
| jmespath                      | 1.4.0        |
| aws-partitions                | 1.418.0      |
| aws-eventstream               | 1.1.0        |
| aws-sigv4                     | 1.2.2        |
| aws-sdk-core                  | 3.111.2      |
| aws-sdk-kms                   | 1.41.0       |
| aws-sdk-s3                    | 1.87.0       |
| date                          | 1.0.0        |
| stringio                      | 0.0.1        |
| zlib                          | 1.0.0        |
| openssl                       | 2.1.2        |
| strscan                       | 1.0.0        |
| fileutils                     | 1.0.2        |
| etc                           | 1.0.0        |
| io-console                    | 0.4.6        |
| ipaddr                        | 1.2.0        |
| psych                         | 3.0.2        |
</details>

*generated on:* **2021-02-02**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by kohtenko**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves: https://github.com/fastlane/fastlane/issues/18094
### Description
Add an opportunity to explicitly allow running 2FA in non-interactive mode.
Updated documentation https://github.com/fastlane/docs/pull/1019

### Testing Steps
run in non-interactive mode
```
$ export SPACESHIP_ALLOW_NON_INTERACTIVE_2FA='true'
$ bundle exec fastlane spaceauth
```

### CODE REVIEW

**Comment by garylai** [comment]
I think it is better to have it the other way around: i.e. to have `SPACESHIP_ALLOW_ONLY_INTERACTIVE_2FA` so that the check is 
```
ENV["SPACESHIP_ALLOW_ONLY_INTERACTIVE_2FA"] == "true" && ENV["FASTLANE_IS_INTERACTIVE"] == "false"
```
In this way, the exisiting behaviour is preserved so it is not a breaking change anymore.

**Comment by kohtenko** [comment]
Agree, apparently there's a lot of people relying on this, so making the change non-breaking in this PR and updating the docs accordingly.

**Comment by twocountriestrus** [comment]
Especial

**Comment by nasaleanhorea** [comment]
Could someone please review the @kohtenko PR , Azure CIs are currently blocked by this error

**Review by joshdholtz — APPROVED** [review]
This makes sense! My apologies on breaking this 😔 I will get this out in a new version tonight 💪

**Comment by juanmalm** [comment]
Hi @joshdholtz ! Do you have an ETA for that version? 👼

**Comment by joshdholtz** [comment]
@juanmalm Sometime this afternoon! There were a few other things I wanted to throw in this version 😇

File: spaceship/lib/spaceship/two_step_or_factor_client.rb [hunk 1]
```diff
@@ -4,7 +4,7 @@
 module Spaceship
   class Client
     def handle_two_step_or_factor(response)
-      raise "2FA can only be performed in interactive mode" if ENV["FASTLANE_IS_INTERACTIVE"] == "false"
+      raise "2FA can only be performed in interactive mode" if ENV["SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA"] == "true" && ENV["FASTLANE_IS_INTERACTIVE"] == "false"
```
Comment (sp-ricard-valverde) [inline spaceship/lib/spaceship/two_step_or_factor_client.rb:7]: Sorry to get back to a merged PR but I thinks there's a condition which is not quite right:

What happens if you have `FASTLANE_IS_INTERACTIVE=false` so you should skip inmediately this assertion but you have defined this new `SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA=false` ? You are running in non-interactive but it will raise the non-interactive error.

I think the condition evaluation should be swapped so `SPACESHIP_ONLY_ALLOW_INTERACTIVE_2FA` value makes no effect if running interactive.

Comment (kohtenko) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:7]: I don't understand the concern. The only way this exception is thrown is if both ENV variables are set to the `true` and `false` respectively. If you don't set either it will go over the exception and execute as if it's interactive.

Comment (joshdholtz) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:7]: `FASTLANE_IS_INTERACTIVE` is actually set by _fastlane_ and not the user. It is set in the `Fastlane::CLIToolsDistributor`. The `Spaceship` module does not have access to fastlane stuff so this is used as a way for them to talk when `fastlane spaceauth` is used.

So this gets set automatically by _fastlane_ when in a non-interactive state

Comment (sp-ricard-valverde) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:7]: My bad guys, I don't know what I was thinking. You are totally right.

Comment (joshdholtz) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:7]: Np np! It's not the most straight forward thing 😇 I appreciate you bringing up your concerns though ❤️

**Comment by iliao58** [comment]
@joshdholtz how is this different from `SPACESHIP_SKIP_2FA_UPGRADE` ? we already set `SPACESHIP_SKIP_2FA_UPGRADE`, do we also need to set these new flags?

**Comment by joshdholtz** [comment]
@iliao58 You shouldn't need to! This is for some special cases when running _fastlane_'s `fastlane spaceauth` in a non-interactive mode (like a CI or shelled through another tool).

So you shouldn't need it unless you know you need it 😇 (I think 🤷‍♂️ )
