### PR TITLE
Fix supply uploading screenshot html

### LINKED ISSUE #9292: Avoid uploading screenshots.html when running fastlane supply
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After doing lots of screenshots on lots of terminals with lots of locales, we tried to deploy the screenshots using `fastlane supply`. After 15 minutes uploading things, it crashes cos it doesn't know what to do with `screenshots.html`, the report that fastlane screengrab generates to report the screenshots taken. The key point is that supply could be smart enough to ignore sending that file to Google Play.

The error launched by fastlane:
`/Users/roc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:211:in `check_status': [!] unsupportedListingLanguage: Listing language screenshots.html is not supported. (Google::Apis::ClientError)`

Thanks for your work! :+1:

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #9292 

`all_languages` was searching meta directory for all folders **AND** files. This fix now filters `all_languages` only for directories

### CODE REVIEW

File: supply/lib/supply/uploader.rb [hunk 1]
```diff
@@ -162,8 +162,12 @@ def update_track(apk_version_codes)
       end
     end
 
+    # returns only language directories from metadata_path
     def all_languages
-      Dir.foreach(metadata_path).sort { |x, y| x <=> y }
+      Dir.entries(metadata_path)
```
Comment (KrauseFx) [inline supply/lib/supply/uploader.rb]: Does this change have any side? Would that break potential setups?

**Review by mfurtak — APPROVED** [review]
Looks good. Thanks for the fix 👍

File: supply/lib/supply/uploader.rb (hunk 1 above)
Comment (joshdholtz) [inline supply/lib/supply/uploader.rb]: @KrauseFx This _should not_ have any negative side effect. The existing setup was already breaking since this was picking up an HTML file 😉

Comment (rocboronat) [inline supply/lib/supply/uploader.rb]: :+1:
