### PR TITLE
[regression][create-keychain] allow `timeout: 0` to specify "no time-out"

### LINKED ISSUE #18892: create_keychain broken
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: [2.185.1 ]
- Last working version: [2.185.10]

### Regression Description
The change in the version changed the options from:

- is_string is slowly being replaced by type to make the docs clearer, options safer, and Swift generation more correct.

How ever in create_keychain this affected the timeout value, as per the DOCS:

timeout | timeout interval in seconds. Set&nbsp;false&nbsp;if you want to specify "no time-out" | 300
-- | -- | --

How ever timeout is now an Int NOT a Bool so you CANNOT set it to "false" anymore

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.4                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.31.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.4 (20F71)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.5                                                           |
| Swift Version               | 5.4                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### LINKED ISSUE #18936: Undisclosed breaking change in create_keychain in minor version 2.185.1
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.185.1
- Last working version: 2.185.0

### Regression Description
Up until now, we used the following code to create a temporary keychain for our iOS build process:
```
create_keychain(
      name: name,
      password: 'temppassword',
      unlock: true,
      timeout: false
)
```
This `false` boolean value for the `timeout` argument is actually still listed as a valid value in the doc (https://docs.fastlane.tools/actions/create_keychain/)

The thing is, with the changes in type validation from the last minor release, this is not working anymore, as only Integer values are allowed.

I'd argue that such a change should not have made it to a minor release in the first place, but even more problematic is having it not listed anywhere else than in the actual commit where it was changed (https://github.com/fastlane/fastlane/commit/e5f3371d59f1dacf55bec11078e9ad6c8924d764).

Anyways, just letting you know so you can make sure people running into this issue can easily find the info, as this took me a while to figure out, it doesn't seem to have been reported elsewhere yet.

### PR DESCRIPTION
**Pull request by crazymanish**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- Resolves: https://github.com/fastlane/fastlane/issues/18892 https://github.com/fastlane/fastlane/issues/18936
- Regression PR: https://github.com/fastlane/fastlane/pull/18857
- Regression PR broke the `create_keychain` action to allow `timeout: false` to specify "no time-out"

### Description
- In this PR, now we will allow `timeout: 0` to specify "no time-out" 
- Added the unit test to ensure that this will not break in the future

### Testing Steps
- `bundle exec rspec fastlane/spec/actions_specs/create_keychain_spec.rb`

### CODE REVIEW

File: fastlane/lib/fastlane/actions/create_keychain.rb [hunk 1]
```diff
@@ -126,8 +126,8 @@ def self.available_options
                                        type: Boolean,
                                        default_value: false),
           FastlaneCore::ConfigItem.new(key: :timeout,
-                                       description: 'timeout interval in seconds',
-                                       type: Integer,
+                                       description: 'timeout interval in seconds. Set `false` if you want to specify "no time-out"',
+                                       skip_type_validation: true, # allow integers & Bool->`false` for "no timeout"
```
Comment (minuscorp) [inline fastlane/lib/fastlane/actions/create_keychain.rb:130]: Would it allow String values that are converted into int values or it will crash unexpectedly?

**Review by minuscorp — APPROVED** [review]
Looks good, a minor comment about the types allowed🙏

File: fastlane/lib/fastlane/actions/create_keychain.rb (hunk 1 above)
Comment (crazymanish) [reply fastlane/lib/fastlane/actions/create_keychain.rb:130]: Thank you for your review! It will allow and it will not crash, please see this https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/create_keychain.rb#L50

- `timeout: "5000"` & `timeout: 5000` both are equalivent and valid without any crash! 
- `timeout: false` then it will ignore `-t` param

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/create_keychain.rb:130]: I _believe_ no timeout will work if you set `0` as the value 🤔 `0` is also seen as falsey so the `-t` parameter will get skipped. I think we keep this as a `type: Integer` and update the description to say something like `Set `0` if you want to specify “no timeout”`.

I’m pretty sure `0` is a common value to set for no timeout in other libraries/dependencies 🤷‍♂️ 

Thoughts? 😊

**Review by joshdholtz — CHANGES_REQUESTED** [review]

File: fastlane/lib/fastlane/actions/create_keychain.rb (hunk 1 above)
Comment (crazymanish) [reply fastlane/lib/fastlane/actions/create_keychain.rb:130]: Thank you very much for this suggestion, on it right away!

File: fastlane/spec/actions_specs/create_keychain_spec.rb [hunk 2]
```diff
@@ -134,6 +134,28 @@
...
+            })
+          end").runner.execute(:test)
+
+          expect(result.size).to eq(4)
+          expect(result[0]).to eq('security create-keychain -p testpassword ~/Library/Keychains/test.keychain')
+
+          expect(result[1]).to eq('security unlock-keychain -p testpassword ~/Library/Keychains/test.keychain')
+
+          expect(result[2]).to start_with('security set-keychain-settings')
+          expect(result[2]).to_not(include('-t'))
```
Comment (crazymanish) [inline fastlane/spec/actions_specs/create_keychain_spec.rb:153]: this unit-test ensuing that `it "works with 'timeout: 0' to specify 'no timeout', skips -t param"`

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you for applying that suggestion 😍

**Comment by bukira** [comment]
is this updated in the docs?

**Comment by crazymanish** [comment]
Docs will update once this PR is release, You will have now two choices:

- either use `timeout: 0` for no timeout or
- use big integer number `timeout: 360000`
