### PR TITLE
[snapshot] wait for simulator to boot before overriding status bar

### LINKED ISSUE #19317: Snapshot: override_status_bar not working
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I'm using the command `override_status_bar(true)` in my Snapfile but it doesn't work at all. The simulator is just showing the normal status bar instead of overriding the values.

I think the issue is that the command to modify the statusbar is executed too early. If I just run it in my terminal I'm getting this error:
  <pre>
$ xcrun simctl status_bar 96038F3E-9905-4BE1-8386-B55B760AA111 override --time 2007-01-09T09:41:00-07:00 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=405):
Unable to lookup in current state: Shutdown
</pre>

This error is just sent to /dev/null when Fastlane runs and therefore hidden (even if --verbose is used).
During the run, I see that the Simulator app starts but no actual simulators are running yet when the `xcrun simctl status_bar` is executed. They would still have the *Shutdown* state.

Fastlane should first complete the build and modify the status bar after `Test Suite FastlaneScreenshots.xctest started` when the simulator has started completely.

##### Command executed
bundle exec fastlane snapshot

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>$  bundle exec fastlane snapshot
[✔] 🚀
[14:22:55]: Successfully loaded '/[..]/fastlane/Snapfile' 📄

+----------------------------+----------------------------------------+
|             Detected Values from './fastlane/Snapfile'              |
+----------------------------+----------------------------------------+
| devices                    | ["iPhone 12 Pro Max", "iPhone 8 Plus"] |
| languages                  | ["en-US"]                              |
| scheme                     | FastlaneScreenshots                    |
| clear_previous_screenshots | true                                   |
| stop_after_first_error     | true                                   |
| concurrent_simulators      | false                                  |
| override_status_bar        | true                                   |
| headless                   | false                                  |
+----------------------------+----------------------------------------+

[14:22:56]: Resolving Swift Package Manager dependencies...
[14:22:56]: $ xcodebuild -resolvePackageDependencies -workspace ./company\ Lab.xcworkspace -scheme FastlaneScreenshots
[14:22:59]: ▸ Command line invocation:
[14:22:59]: ▸     /Applications/Xcode-beta.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace "./ProjectName.xcworkspace" -scheme FastlaneScreenshots
[14:22:59]: ▸ User defaults from command line:
[14:22:59]: ▸     IDEPackageSupportUseBuiltinSCM = YES
[..]

+--------------------------------------+---------------------------------------------------------------------------+
|                                           Summary for snapshot 2.192.0                                           |
+--------------------------------------+---------------------------------------------------------------------------+
| workspace                            | ./ProjectName.xcworkspace                                                 |
| devices                              | ["iPhone 12 Pro Max", "iPhone 8 Plus"]                                    |
| languages                            | ["en-US"]                                                                 |
| launch_arguments                     | [""]                                                                      |
| output_directory                     | /[..]/fastlane/screenshots |
| output_simulator_logs                | false                                                                     |
| skip_open_summary                    | false                                                                     |
| skip_helper_version_check            | false                                                                     |
| clear_previous_screenshots           | true                                                                      |
| reinstall_app                        | false                                                                     |
| erase_simulator                      | false                                                                     |
| headless                             | false                                                                     |
| override_status_bar                  | true                                                                      |
| localize_simulator                   | false                                                                     |
| app_identifier                       | com.company.company-lab                                                   |
| buildlog_path                        | ~/Library/Logs/snapshot                                                   |
| clean                                | false                                                                     |
| scheme                               | FastlaneScreenshots                                                       |
| number_of_retries                    | 1                                                                         |
| stop_after_first_error               | true                                                                      |
| result_bundle                        | false                                                                     |
| concurrent_simulators                | false                                                                     |
| disable_slide_to_type                | false                                                                     |
| skip_package_dependencies_resolution | false                                                                     |
| disable_package_automatic_updates    | false                                                                     |
| use_system_scm                       | false                                                                     |
| xcode_path                           | /Applications/Xcode-beta.app                                              |
+--------------------------------------+---------------------------------------------------------------------------+

[14:23:10]: Clearing previously generated screenshots
[14:23:10]: Building and running project - this might take some time...
[14:23:12]: Patching simulators '/Users/ronnyfenrich/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
Set: Entry, ":DevicePreferences:E8F5E631-5D25-4A07-998B-CFA6F4582E76:ConnectHardwareKeyboard", Does Not Exist
Set: Entry, ":DevicePreferences:8E1AFB50-3278-4F34-B74C-B5EDF7163999:ConnectHardwareKeyboard", Does Not Exist
[14:23:26]: Launch Simulator iPhone 12 Pro Max
[14:23:26]: $ xcrun instruments -w 96038F3E-9905-4BE1-8386-B55B760AA111 &> /dev/null
[14:23:30]: Overriding Status Bar
[14:23:30]: $ xcrun simctl status_bar 96038F3E-9905-4BE1-8386-B55B760AA111 override --time 2007-01-09T09:41:00-07:00 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100 &> /dev/null
[14:23:31]: Running snapshot on: iPhone 12 Pro Max
[14:23:31]: $ set -o pipefail && xcodebuild -workspace ./company\ Lab.xcworkspace -scheme FastlaneScreenshots -derivedDataPath /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy -destination 'platform=iOS Simulator,name=iPhone 12 Pro Max,OS=15.0' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US build test | tee /Users/ronnyfenrich/Library/Logs/snapshot/FastlaneScreenshots-FastlaneScreenshots.log | xcpretty
[14:23:31]: ▸ Loading...
[14:23:44]: ▸     Building targets in manual order is deprecated - choose Dependency Order in scheme settings instead, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current scheme to suppress this warning
[..]

[14:25:09]: Running Tests: ▸ Touching Pods_FastlaneScreenshots.framework (in target 'Pods-FastlaneScreenshots' from project 'Pods')
[14:25:09]: ▸ Running script '[CP] Check Pods Manifest.lock'
[14:25:09]: ▸ Processing Info.plist
[14:25:09]: ▸ Compiling SnapshotHelper.swift
[14:25:19]: ▸ Compiling FastlaneScreenshots.swift
[14:25:20]: ▸ Linking FastlaneScreenshots
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots-Swift.h
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftmodule
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftdoc
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftmodule
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftdoc
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftsourceinfo
[14:25:20]: ▸ Copying /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy/Build/Intermediates.noindex/company\ Lab.build/Debug-iphonesimulator/FastlaneScreenshots.build/Objects-normal/x86_64/FastlaneScreenshots.swiftsourceinfo
[14:25:20]: ▸ Running script '[CP] Embed Pods Frameworks'
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCUnit.framework
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib/libXCTestSwiftSupport.dylib
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTestCore.framework
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCUIAutomation.framework
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework
[14:25:22]: ▸ Copying /Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework
[14:25:22]: Running Tests: ▸ Touching FastlaneScreenshots.xctest (in target 'FastlaneScreenshots' from project 'ProjectName')
[14:25:22]: ▸ Build Succeeded
[14:25:23]: ▸     Building targets in manual order is deprecated - choose Dependency Order in scheme settings instead, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current scheme to suppress this warning
[14:25:23]: ▸ Linking company\
[14:25:24]: ▸ Running script 'Copy Settings Bundle'
[14:25:24]: ▸ Running script 'Run SwiftLint'
[14:25:24]: ▸ Processing Info.plist
[14:25:24]: ▸ Running script 'Run Script (update bundle version)'
[14:25:24]: ▸ Running script '[CP] Embed Pods Frameworks'
[14:25:26]: ▸ Linking FastlaneScreenshots
[14:25:26]: ▸ Running script '[CP] Embed Pods Frameworks'
[14:25:55]: ▸ All tests
[14:25:55]: ▸ Test Suite FastlaneScreenshots.xctest started
[14:25:55]: ▸ FastlaneScreenshots
[14:26:09]: ▸     ✓ testTakeDarkModeScreenshots (14.252 seconds)
[14:26:31]: ▸     ✓ testTakeScreenshots (22.304 seconds)
[14:26:31]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 36.556 (36.560) seconds
[14:26:31]: ▸
[14:26:32]: ▸ 2021-08-31 14:26:32.254 xcodebuild[44512:6040631] [MT] IDETestOperationsObserverDebug: 63.642 elapsed -- Testing started completed.
[14:26:32]: ▸ 2021-08-31 14:26:32.255 xcodebuild[44512:6040631] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[14:26:32]: ▸ 2021-08-31 14:26:32.255 xcodebuild[44512:6040631] [MT] IDETestOperationsObserverDebug: 63.642 sec, +63.642 sec -- end
[14:26:32]: ▸ Test Succeeded
[14:26:39]: Clearing Status Bar Override
[14:26:39]: $ xcrun simctl status_bar 96038F3E-9905-4BE1-8386-B55B760AA111 clear &> /dev/null
[14:26:40]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 12 Pro Max-01FootmapScreen.png'...
[14:26:40]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 12 Pro Max-05FootmapScreenDarkMode.png'...
[14:26:40]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 12 Pro Max-04SessionDetailsScreen.png'...
[14:26:40]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 12 Pro Max-02ManageInsolesScreen.png'...
[14:26:40]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 12 Pro Max-03SessionScreen.png'...
[14:26:41]: Patching simulators '/Users/ronnyfenrich/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[14:26:53]: Launch Simulator iPhone 8 Plus
[14:26:53]: $ xcrun instruments -w E8F5E631-5D25-4A07-998B-CFA6F4582E76 &> /dev/null
[14:26:56]: Overriding Status Bar
[14:26:56]: $ xcrun simctl status_bar E8F5E631-5D25-4A07-998B-CFA6F4582E76 override --time 2007-01-09T09:41:00-07:00 --dataNetwork wifi --wifiMode active --wifiBars 3 --cellularMode active --cellularBars 4 --batteryState charged --batteryLevel 100 &> /dev/null
[14:26:56]: Running snapshot on: iPhone 8 Plus
[14:26:56]: $ set -o pipefail && xcodebuild -workspace ./company\ Lab.xcworkspace -scheme FastlaneScreenshots -derivedDataPath /var/folders/yx/1qtx1kcs7gq7bm5dh_qb03sc0000gp/T/snapshot_derived20210831-44166-1szdvxy -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=15.0' FASTLANE_SNAPSHOT=YES FASTLANE_LANGUAGE=en-US build test | tee -a /Users/ronnyfenrich/Library/Logs/snapshot/FastlaneScreenshots-FastlaneScreenshots.log | xcpretty
[14:26:56]: ▸ Loading...
[14:27:02]: ▸     Building targets in manual order is deprecated - choose Dependency Order in scheme settings instead, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current scheme to suppress this warning
[14:27:02]: ▸ Processing Alamofire-Info.plist
[14:27:02]: ▸ Linking AlamofireNetworkActivityIndicator
[14:27:03]: ▸ Processing AlamofireNetworkActivityIndicator-Info.plist
[14:27:03]: ▸ Running script '[CP] Copy XCFrameworks'
[14:27:03]: ▸ Processing ZIPFoundation-Info.plist
[14:27:03]: ▸ Processing iOSDFULibrary-Info.plist
[14:27:03]: ▸ Linking iOSDFULibrary
[14:27:03]: ▸ Running script '[CP] Copy XCFrameworks'
[14:27:04]: ▸ Processing Pods-ProjectName-Info.plist
[14:27:04]: ▸ Running script '[CP] Check Pods Manifest.lock'
[14:27:04]: ▸ Linking company\
[14:27:04]: ▸ Running script 'Copy Settings Bundle'
[14:27:08]: ▸ Processing Info.plist
[14:27:08]: ▸ Running script 'Run SwiftLint'
[14:27:08]: ▸ Running script 'Run Script (update bundle version)'
[14:27:08]: ▸ Running script '[CP] Embed Pods Frameworks'
[14:27:10]: ▸ Processing Pods-FastlaneScreenshots-Info.plist
[14:27:10]: ▸ Running script '[CP] Check Pods Manifest.lock'
[14:27:10]: ▸ Linking FastlaneScreenshots
[14:27:11]: ▸ Running script '[CP] Embed Pods Frameworks'
[14:27:12]: ▸ Processing Info.plist
[14:27:12]: ▸ Build Succeeded
[14:27:13]: ▸     Building targets in manual order is deprecated - choose Dependency Order in scheme settings instead, or set DISABLE_MANUAL_TARGET_ORDER_BUILD_WARNING in any of the targets in the current scheme to suppress this warning
[14:27:13]: ▸ Linking company\
[14:27:14]: ▸ Running script 'Copy Settings Bundle'
[14:27:14]: ▸ Running script 'Run SwiftLint'
[14:27:14]: ▸ Processing Info.plist
[14:27:14]: ▸ Running script 'Run Script (update bundle version)'
[14:27:15]: ▸ Linking FastlaneScreenshots
[14:27:45]: ▸ All tests
[14:27:45]: ▸ Test Suite FastlaneScreenshots.xctest started
[14:27:45]: ▸ FastlaneScreenshots
[14:27:59]: ▸     ✓ testTakeDarkModeScreenshots (13.587 seconds)
[14:28:21]: ▸     ✓ testTakeScreenshots (22.191 seconds)
[14:28:21]: ▸ 	 Executed 2 tests, with 0 failures (0 unexpected) in 35.778 (35.781) seconds
[14:28:21]: ▸
[14:28:22]: ▸ 2021-08-31 14:28:22.077 xcodebuild[45579:6054354] [MT] IDETestOperationsObserverDebug: 66.101 elapsed -- Testing started completed.
[14:28:22]: ▸ 2021-08-31 14:28:22.077 xcodebuild[45579:6054354] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
[14:28:22]: ▸ 2021-08-31 14:28:22.077 xcodebuild[45579:6054354] [MT] IDETestOperationsObserverDebug: 66.101 sec, +66.101 sec -- end
[14:28:22]: ▸ Test Succeeded
[14:28:29]: Clearing Status Bar Override
[14:28:29]: $ xcrun simctl status_bar E8F5E631-5D25-4A07-998B-CFA6F4582E76 clear &> /dev/null
[14:28:29]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 8 Plus-05FootmapScreenDarkMode.png'...
[14:28:29]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 8 Plus-01FootmapScreen.png'...
[14:28:29]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 8 Plus-04SessionDetailsScreen.png'...
[14:28:29]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 8 Plus-03SessionScreen.png'...
[14:28:29]: Copying '/[..]/fastlane/screenshots/en-US/iPhone 8 Plus-02ManageInsolesScreen.png'...

+-------------------+-------+
|     snapshot results      |
+-------------------+-------+
| Device            | en-US |
+-------------------+-------+
| iPhone 12 Pro Max |  💚   |
| iPhone 8 Plus     |  💚   |
+-------------------+-------+

[14:28:29]: Generating HTML Report
[14:28:30]: Successfully created HTML file with an overview of all the screenshots: '/[..]/fastlane/screenshots/screenshots.html'</pre>
</details>

### Environment
<details>
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.5.2                                                         |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.30.1 (Apple Git-130)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.5.2 (20G95)                                           |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/               |
| Xcode Version               | 13.0                                                           |
| Swift Version               | 5.5                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "Product.xcworkspace", scheme: "FastlaneScreenshots")
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.company.company-lab") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.192.0 | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.2.21       |
| rake                            | 13.0.6       |
| CFPropertyList                  | 3.0.3        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.1        |
| aws-partitions                  | 1.492.0      |
| aws-sigv4                       | 1.2.4        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.119.1      |
| aws-sdk-kms                     | 1.47.0       |
| aws-sdk-s3                      | 1.100.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.2        |
| excon                           | 0.85.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| multipart-post                  | 2.0.0        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.7.1        |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.2.3        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.15.0       |
| googleauth                      | 0.17.0       |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.1        |
| trailblazer-option              | 0.1.1        |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.4.1        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-apis-storage_v1          | 0.6.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2021-08-31**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by JosephDuffy**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
If the simulator is not booted when the status bar is updated it does not do anything and the default status bar is used.

Resolves #19317

### Description
`xcrun instruments` fails with the error "xcrun: error: Failed to locate 'instruments'." This command will boot the simulator if it's not curerntly booted and then wait for it finish booting before terminating.

### Testing Steps
Use `snapshot` while the `override_status_bar` option is `true`.

<details>
<summary>
Some of the tests failed for me, although they do not seem related to this change.
</summary>

```
rspec ./fastlane/spec/actions_specs/app_store_connect_api_key_spec.rb:95 # Fastlane Fastlane::FastFile App Store Connect API Key raise error when no key_filepath or key_content
rspec ./fastlane/spec/actions_specs/import_from_git_spec.rb:162 # Fastlane Fastlane::FastFile import_from_git with caching works with new tags
rspec ./fastlane/spec/actions_specs/import_from_git_spec.rb:200 # Fastlane Fastlane::FastFile import_from_git with caching works with branch
rspec ./match/spec/importer_spec.rb:47 # Match Match::Runner imports a .cert, .p12 and .mobileprovision (iOS provision) into the match repo
rspec ./match/spec/importer_spec.rb:64 # Match Match::Runner imports a .cert, .p12 and .provisionprofile (osx provision) into the match repo
rspec ./match/spec/importer_spec.rb:81 # Match Match::Runner imports a .cert and .p12 without profile into the match repo (backwards compatibility)
rspec ./match/spec/importer_spec.rb:98 # Match Match::Runner imports a .cert and .p12 when the type is set to developer_id
rspec ./pilot/spec/build_manager_spec.rb:661 # Build Manager #transporter_for_selected_team with one team id
rspec ./pilot/spec/build_manager_spec.rb:677 # Build Manager #transporter_for_selected_team with inferred provider id
rspec ./pilot/spec/build_manager_spec.rb:633 # Build Manager #transporter_for_selected_team with itc_provider with nil Spaceship::TunesClient
rspec ./pilot/spec/build_manager_spec.rb:646 # Build Manager #transporter_for_selected_team with itc_provider with nil Spaceship::TunesClient
rspec ./pilot/spec/manager_spec.rb[1:1:2:2:1:1:1] # Pilot Pilot::Manager what happens on 'login' when using web session when username input param is given behaves like performing the spaceship login using username and password by pilot performs the login using username and password
rspec ./pilot/spec/manager_spec.rb[1:1:2:2:2:1:1] # Pilot Pilot::Manager what happens on 'login' when using web session when username input param is not given but found apple_id in AppFile behaves like performing the spaceship login using username and password by pilot performs the login using username and password
rspec ./sigh/spec/runner_spec.rb:142 # Sigh Sigh::Runner#devices_to_use devices for development
rspec ./sigh/spec/runner_spec.rb:152 # Sigh Sigh::Runner#devices_to_use devices for adhoc
```
</details>

### CODE REVIEW

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb [hunk 1]
```diff
@@ -116,7 +116,8 @@ def override_status_bar(device_type, arguments = nil)
       device_udid = TestCommandGenerator.device_udid(device_type)
 
       UI.message("Launch Simulator #{device_type}")
-      Helper.backticks("xcrun instruments -w #{device_udid} &> /dev/null")
+      # Boot the simulator and wait for it to finish booting
+      Helper.backticks("xcrun simctl bootstatus #{device_udid} -b &> /dev/null")
```
Comment (joshdholtz) [inline snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:120]: Do you happen to have any good documentation or explanation on what the difference between these two commands are? I tried to look at the help/man pages and couldn't really find too much h🤷‍♂️

**Review by joshdholtz — COMMENTED** [review]
Just a quick question on the difference between this two subcommands  🙃 This would be ag great fix but just a little bit curious at what this change _actually_ does 😛

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb (hunk 1 above)
Comment (JosephDuffy) [reply snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:120]: With Xcode 12.5.1 as the current Xcode `xcrun instruments` outputs:

```
`instruments` is now deprecated in favor of 'xcrun xctrace' (see `man xctrace` for more information on its replacement)
instruments, version 12.5.1 (64544.132)
usage: instruments [-t template] [-D document] [-l timeLimit] [-w device] [-P package] [[-p pid] | [application [-e variable value] [argument ...]]]
```

`man instruments` describes `-w` as:

```
     -w [hardware device, or simulator name]
              The name or identifier of the hardware device or simulator to target. Should be specified first
```

(you probably found this documentation but I'm adding it for completeness)

The behaviour has either changed or this never worked because using instruments to boot the simulator only boots the simulator (it doesn't wait for it to be ready) and exits with an error:

```
instruments[2650]: Waiting for device to boot...
Instruments Usage Error: No template (-t) specified
instruments, version 12.5.1 (64544.132)
usage: instruments [-t template] [-D document] [-l timeLimit] [-w device] [-P package] [[-p pid] | [application [-e variable value] [argument ...]]]
```

---

`bootstatus` is not listed in `xcrun simctl help` but does have help text available via `xcrun simctl help bootstatus`:

```
Checks device boot status.
Usage: simctl bootstatus <device> [-bcd]
	-b       Boot the device if it isn't already booted.
	-d       Print data migration information, if it's available.
	-c       Continuously monitor boot status through multiple boot/shutdown cycles.

Monitors the specified device and prints boot status information until the device finishes booting. You can safely call this before you attempt to start booting the device.
```

---

I found this quite confusing myself.

Comment (joshdholtz) [reply snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:120]: Oh my goodness! The `xcrun simctl help bootstatus` is the command I need to find but couldn't 😓 Thank you so much for this! It does appear that this never really worked then 😬

Comment (JosephDuffy) [reply snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:120]: It's a bit hidden! 😔 I would love to know if there are any other (hidden) commands available but this is the only one I'm aware of.

**Comment by joshdholtz** [comment]
@JosephDuffy Quick question for you! Is your status bar actually changing like you are expecting it to in your screenshots? I actually can't get this to work for me 😬 What are the options you are using with `snapshot` that you are getting this to work?

**Comment by joshdholtz** [comment]
@JosephDuffy Turns out I was an idiot and somehow deleted my `snapshot()` call from my UI test without knowing 🤦‍♂️

**Review by joshdholtz — APPROVED** [review]
This fix is amazing and seems to fix the issue happening on this discussion 👉 https://github.com/fastlane/fastlane/discussions/17021

Thank you so much for this! Really appreciate it ❤️

**Comment by JosephDuffy** [comment]
Thanks for the quick review and merge Josh!

File: snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb (hunk 1 above)
Comment (stherold) [reply snapshot/lib/snapshot/simulator_launchers/simulator_launcher_base.rb:120]: Thanks for this tipp! This saved me from HOURS of debugging in my screenshotting tool!
