### PR TITLE
Fastlane require format non plugins with dash

### LINKED ISSUE #7502: fastlane_require replaces - with / resulting LoadError: cannot load such file -- aws/sdk
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]
(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have few custom actions that require aws-sdk. When i require using require 'aws-sdk' it works fine but throws a warning 

WARN [2016-12-15 15:44:30.88]: You require a gem, please call `fastlane_require 'aws-sdk'` before to ensure the gem is installed

In order to fix the warning i replaced require 'aws-sdk' with fastlane_require 'aws-sdk' and now it throws an error,

bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
LoadError: cannot load such file -- aws/sdk

while debugging the issue, i see a line 

gem_require_name = gem_name.tr("-", "/") # from "fastlane-plugin-xcversion" to "fastlane/plugin/xcversion" 

in method install_gem_if_needed of lib/fastlane/fastlane_require.rb. This replaces require 'aws-sdk' to 'aws/sdk'.

How can it be fixed?

Stacktrace: 
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
LoadError: cannot load such file -- aws/sdk
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fastlane_require.rb:11:in `require'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fastlane_require.rb:11:in `install_gem_if_needed'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:189:in `fastlane_require'
  Fastfile:4:in `parsing_binding'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:54:in `eval'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:54:in `block in parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:43:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:43:in `parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:33:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane_manager.rb:12:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.57.2/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:292:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:36:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/bin/fastlane:5:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'

Environment:

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.2  | 🚫 Update availaible |
| spaceship           | 0.38.4  | 🚫 Update availaible |
| cert                | 1.4.4   | 🚫 Update availaible |
| deliver             | 1.16.0  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | 🚫 Update availaible |
| sigh                | 1.12.0  | 🚫 Update availaible |
| match               | 0.11.0  | 🚫 Update availaible |
| pem                 | 1.4.0   | 🚫 Update availaible |
| pilot               | 1.12.1  | 🚫 Update availaible |
| produce             | 1.3.2   | 🚫 Update availaible |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | 🚫 Update availaible |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-aws_device_farm | 0.1.6   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.0.0        |
| bundler                         | 1.13.5       |
| io-console                      | 0.4.5        |
| CFPropertyList                  | 2.3.4        |
| i18n                            | 0.7.0        |
| json                            | 1.8.3        |
| minitest                        | 5.10.0       |
| thread_safe                     | 0.3.5        |
| tzinfo                          | 1.2.2        |
| activesupport                   | 4.2.7.1      |
| public_suffix                   | 2.0.4        |
| addressable                     | 2.5.0        |
| aws-sigv4                       | 1.0.0        |
| jmespath                        | 1.3.1        |
| aws-sdk-core                    | 2.6.30       |
| aws-sdk-resources               | 2.6.30       |
| aws-sdk                         | 2.6.30       |
| babosa                          | 1.0.2        |
| fastimage                       | 1.6.8        |
| colored                         | 1.2          |
| highline                        | 1.7.8        |
| commander                       | 4.4.0        |
| security                        | 0.1.3        |
| credentials_manager             | 0.16.2       |
| excon                           | 0.54.0       |
| gh_inspector                    | 1.0.2        |
| multi_json                      | 1.12.1       |
| plist                           | 3.2.0        |
| rubyzip                         | 1.1.7        |
| terminal-table                  | 1.4.5        |
| fastlane_core                   | 0.57.2       |
| mini_magick                     | 4.5.1        |
| badge                           | 0.5.1        |
| multipart-post                  | 2.0.0        |
| faraday                         | 0.10.0       |
| unf_ext                         | 0.0.7.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20161129 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| faraday_middleware              | 0.10.1       |
| multi_xml                       | 0.5.5        |
| claide                          | 1.0.1        |
| dotenv                          | 2.1.1        |
| rouge                           | 1.11.1       |
| xcpretty                        | 0.2.4        |
| net-ssh                         | 3.2.0        |
| net-sftp                        | 2.1.2        |
| krausefx-shenzhen               | 0.14.11      |
| slack-notifier                  | 1.5.1        |
| xcpretty-travis-formatter       | 0.0.4        |
| jwt                             | 1.5.6        |
| little-plugger                  | 1.1.4        |
| logging                         | 2.1.0        |
| memoist                         | 0.15.0       |
| os                              | 0.9.6        |
| signet                          | 0.7.3        |
| googleauth                      | 0.5.1        |
| httpclient                      | 2.8.2.4      |
| hurley                          | 0.2          |
| mime-types-data                 | 3.2016.0521  |
| mime-types                      | 3.1          |
| uber                            | 0.0.15       |
| representable                   | 2.3.0        |
| retriable                       | 2.1.0        |
| google-api-client               | 0.9.20       |
| terminal-notifier               | 1.7.1        |
| word_wrap                       | 1.0.0        |
| xcode-install                   | 2.0.9        |
| nanaimo                         | 0.2.3        |
| xcodeproj                       | 1.4.1        |
| fastlane-plugin-aws_device_farm | 0.1.6        |
</details>

*generated on:* **2016-12-15**

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #7502

`fastlane_require "rest-client"` was formatting `rest-client` as `rest/client` was causing a 💥 

The comment above that logic was saying that replacing of `-` with `/` was specifically for `fastlane-plugin-` so now the logic inside of `fastlane_require` only replaces `-` with `/` if it starts with `fastlane-plugin-` 🚀

### CODE REVIEW

**Review by mfurtak — APPROVED** [review]
👍

**Comment by ohwutup** [comment]
This is awesome! Thanks @joshdholtz !! 🚀

**Review by KrauseFx — COMMENTED** [review]
Nice 👍

File: fastlane/lib/fastlane/fastlane_require.rb [hunk 1]
```diff
@@ -62,6 +62,13 @@ def find_gem_name(user_supplied_name)
 
         return gems.first
       end
+
+      def format_gem_require_name(gem_name)
+        # from "fastlane-plugin-xcversion" to "fastlane/plugin/xcversion"
+        gem_name = gem_name.tr("-", "/") if gem_name.start_with? "fastlane-plugin-"
```
Comment (lacostej) [inline fastlane/lib/fastlane/fastlane_require.rb]: Would replace "fastlane/plugin/" to "fastlane-plugin-" be more portable? E.g. if the plugin name has a dash in it?

Comment (joshdholtz) [inline fastlane/lib/fastlane/fastlane_require.rb]: Ahhh, good call good call - that is probably a lot safer. @ohwutup, i think you mentioned you did work on the initial plugin stuff. Is this a better way of doing it? ^
