### PR TITLE
[deliver] Handle frameit "fonts" directory

### LINKED ISSUE #12375: `Unsupported directory name(s)` when using a fonts directory
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Using a specific directory for custom fonts fastlane displays error: `Unsupported directory name(s) for screenshots / metadata`.

I'm using Frameit to generate the ios app screenshots, in the project there is the following directory: `/ screenshots/fonts/` used for the .ttf files. The error happens due to directory checking and can be bypassed by enabling `ignore_language_directory_validation`.

But I believe that the expected behavior would be to ignore the directory named `fonts`, since that seems to be the one indicated in the [documentation](https://docs.fastlane.tools/actions/frameit/#example) and in the [examples](https://github.com/fastlane/examples/tree/master/MindNode/screenshots).

Error output:
```
[!] Unsupported directory name(s) for screenshots/metadata in '/Users/distiller/project/screenshots': fonts
Valid directory names are: ["da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv", "th", "tr", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]

Enable 'ignore_language_directory_validation' to prevent this validation from happening
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> bundle exec fastlane deploy build_number:"$(cat build_number.txt)"
^D^D[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [⠴] 🚀 [⠦] 🚀 [⠧] 🚀 [✔] 🚀 
[16:26:27]: ------------------------------
[16:26:27]: --- Step: default_platform ---
[16:26:27]: ------------------------------
[16:26:27]: Driving the lane 'ios deploy' 🚀
[16:26:27]: -----------------------------
[16:26:27]: --- Step: setup_circle_ci ---
[16:26:27]: -----------------------------
[16:26:27]: Creating temporary keychain: "fastlane_tmp_keychain".
[16:26:27]: Enabling match readonly mode.
[16:26:27]: -------------------------------------------------
[16:26:27]: --- Step: Switch to ios take_screenshots lane ---
[16:26:27]: -------------------------------------------------
[16:26:27]: Cruising over to lane 'ios take_screenshots' 🚖
[16:26:27]: -------------------------------------
[16:26:27]: --- Step: capture_ios_screenshots ---
[16:26:27]: -------------------------------------
[16:26:29]: Successfully loaded '/Users/distiller/project/fastlane/Snapfile' 📄

+----------------------------+--------------------------------------------------------+
|                     Detected Values from './fastlane/Snapfile'                      |
+----------------------------+--------------------------------------------------------+
| devices                    | ["iPhone X", "iPhone 8", "iPhone 8 Plus", "iPhone SE"] |
| languages                  | ["pt-BR"]                                              |
| scheme                     | Caronae                                                |
| app_identifier             | br.ufrj.caronae                                        |
| output_directory           | ./screenshots                                          |
| localize_simulator         | true                                                   |
| clear_previous_screenshots | true                                                   |
| reinstall_app              | true                                                   |
| workspace                  | ./Caronae.xcworkspace                                  |
+----------------------------+--------------------------------------------------------+

[16:26:58]: $ xcodebuild -showBuildSettings -workspace ./Caronae.xcworkspace -scheme Caronae

+----------------------------+--------------------------------------------------------+
|                             Summary for snapshot 2.93.1                             |
+----------------------------+--------------------------------------------------------+
| output_directory           | /Users/distiller/project/screenshots                   |
| workspace                  | ./Caronae.xcworkspace                                  |
| devices                    | ["iPhone X", "iPhone 8", "iPhone 8 Plus", "iPhone SE"] |
| languages                  | ["pt-BR"]                                              |
| launch_arguments           | [""]                                                   |
| output_simulator_logs      | false                                                  |
| skip_open_summary          | false                                                  |
| skip_helper_version_check  | false                                                  |
| clear_previous_screenshots | true                                                   |
| reinstall_app              | true                                                   |
| erase_simulator            | false                                                  |
| localize_simulator         | true                                                   |
| app_identifier             | br.ufrj.caronae                                        |
| buildlog_path              | /Users/distiller/project/output/buildlogs/snapshot     |
| clean                      | false                                                  |
| scheme                     | Caronae                                                |
| number_of_retries          | 1                                                      |
| stop_after_first_error     | false                                                  |
| concurrent_simulators      | true                                                   |
| xcode_path                 | /Applications/Xcode-9.3.app                            |
+----------------------------+--------------------------------------------------------+

[16:27:01]: Clearing previously generated screenshots
[16:27:01]: Building and running project - this might take some time...
[16:27:03]: Patching simulators '/Users/distiller/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[16:27:07]: Erasing iPhone X...
[16:27:08]: Localizing iPhone X (AppleLocale=pt_BR AppleLanguages=[pt-BR])
[16:27:08]: Erasing iPhone 8...
[16:27:10]: Localizing iPhone 8 (AppleLocale=pt_BR AppleLanguages=[pt-BR])
[16:27:10]: Erasing iPhone 8 Plus...
[16:27:13]: Localizing iPhone 8 Plus (AppleLocale=pt_BR AppleLanguages=[pt-BR])
[16:27:14]: Running snapshot on: iPhone X, iPhone 8, iPhone 8 Plus
[16:27:14]: $ set -o pipefail && xcodebuild -workspace ./Caronae.xcworkspace -scheme Caronae -derivedDataPath '/var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt' -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -destination 'platform=iOS Simulator,name=iPhone 8 Plus,OS=11.3' FASTLANE_SNAPSHOT=YES build test | tee /Users/distiller/project/output/buildlogs/snapshot/Caronae-Caronae.log | xcpretty 
[16:27:14]: ▸ Loading...
[16:27:18]: ▸ Building Pods/AFNetworking [Debug]
[16:27:18]: ▸ Check Dependencies
[16:27:18]: ▸ Processing Info.plist
[16:27:24]: ▸ Compiling AFAutoPurgingImageCache.m
[16:27:24]: ▸ Compiling AFHTTPSessionManager.m
[16:27:25]: ▸ Compiling AFImageDownloader.m
[16:27:25]: ▸ Compiling AFNetworkActivityIndicatorManager.m
[16:27:25]: ▸ Compiling AFNetworking-dummy.m
[16:27:25]: ▸ Compiling AFNetworkReachabilityManager.m
[16:27:25]: ▸ Compiling AFSecurityPolicy.m
[16:27:25]: ▸ Compiling AFURLRequestSerialization.m
[16:27:26]: ▸ Compiling AFURLResponseSerialization.m
[16:27:26]: ▸ Compiling AFURLSessionManager.m
[16:27:26]: ▸ Compiling UIActivityIndicatorView+AFNetworking.m
[16:27:26]: ▸ Compiling UIButton+AFNetworking.m
[16:27:26]: ▸ Compiling UIImageView+AFNetworking.m
[16:27:26]: ▸ Compiling UIProgressView+AFNetworking.m
[16:27:26]: ▸ Compiling UIRefreshControl+AFNetworking.m
[16:27:26]: ▸ Compiling UIWebView+AFNetworking.m
[16:27:26]: ▸ Compiling AFNetworking_vers.c
[16:27:26]: ▸ Linking AFNetworking
[16:27:27]: ▸ Copying AFAutoPurgingImageCache.h
[16:27:27]: ▸ Copying AFHTTPSessionManager.h
[16:27:27]: ▸ Copying AFImageDownloader.h
[16:27:27]: ▸ Copying AFNetworkActivityIndicatorManager.h
[16:27:27]: ▸ Copying AFNetworking-umbrella.h
[16:27:27]: ▸ Copying AFNetworking.h
[16:27:27]: ▸ Copying AFNetworkReachabilityManager.h
[16:27:27]: ▸ Copying AFSecurityPolicy.h
[16:27:27]: ▸ Copying AFURLRequestSerialization.h
[16:27:27]: ▸ Copying AFURLResponseSerialization.h
[16:27:27]: ▸ Copying AFURLSessionManager.h
[16:27:27]: ▸ Copying UIActivityIndicatorView+AFNetworking.h
[16:27:28]: ▸ Copying UIButton+AFNetworking.h
[16:27:28]: ▸ Copying UIImage+AFNetworking.h
[16:27:28]: ▸ Copying UIImageView+AFNetworking.h
[16:27:28]: ▸ Copying UIKit+AFNetworking.h
[16:27:28]: ▸ Copying UIProgressView+AFNetworking.h
[16:27:28]: ▸ Copying UIRefreshControl+AFNetworking.h
[16:27:28]: ▸ Copying UIWebView+AFNetworking.h
[16:27:30]: Running Tests: ▸ Touching AFNetworking.framework
[16:27:30]: ▸ Building Pods/Bolts [Debug]
[16:27:30]: ▸ Check Dependencies
[16:27:30]: ▸ Processing Info.plist
[16:27:30]: ▸ Compiling BFAppLink.m
[16:27:30]: ▸ Compiling BFAppLinkNavigation.m
[16:27:30]: ▸ Compiling BFAppLinkReturnToRefererController.m
[16:27:30]: ▸ Compiling BFAppLinkReturnToRefererView.m
[16:27:30]: ▸ Compiling BFAppLinkTarget.m
[16:27:30]: ▸ Compiling BFCancellationToken.m
[16:27:30]: ▸ Compiling BFCancellationTokenRegistration.m
[16:27:30]: ▸ Compiling BFCancellationTokenSource.m
[16:27:30]: ▸ Compiling BFExecutor.m
[16:27:30]: ▸ Compiling BFMeasurementEvent.m
[16:27:30]: ▸ Compiling BFTask.m
[16:27:30]: ▸ Compiling BFTaskCompletionSource.m
[16:27:30]: ▸ Compiling BFURL.m
[16:27:30]: ▸ Compiling BFWebViewAppLinkResolver.m
[16:27:30]: ▸ Compiling Bolts-dummy.m
[16:27:30]: ▸ Compiling Bolts.m
[16:27:30]: ▸ Compiling Bolts_vers.c
[16:27:30]: ▸ Linking Bolts
[16:27:30]: ▸ Copying BFAppLink.h
[16:27:30]: ▸ Copying BFAppLinkNavigation.h
[16:27:30]: ▸ Copying BFAppLinkResolving.h
[16:27:30]: ▸ Copying BFAppLinkReturnToRefererController.h
[16:27:30]: ▸ Copying BFAppLinkReturnToRefererView.h
[16:27:30]: ▸ Copying BFAppLinkTarget.h
[16:27:30]: ▸ Copying BFCancellationToken.h
[16:27:30]: ▸ Copying BFCancellationTokenRegistration.h
[16:27:30]: ▸ Copying BFCancellationTokenSource.h
[16:27:30]: ▸ Copying BFExecutor.h
[16:27:30]: ▸ Copying BFGeneric.h
[16:27:30]: ▸ Copying BFMeasurementEvent.h
[16:27:30]: ▸ Copying BFTask.h
[16:27:30]: ▸ Copying BFTaskCompletionSource.h
[16:27:30]: ▸ Copying BFURL.h
[16:27:30]: ▸ Copying BFWebViewAppLinkResolver.h
[16:27:30]: ▸ Copying Bolts-umbrella.h
[16:27:30]: ▸ Copying Bolts.h
[16:27:30]: Running Tests: ▸ Touching Bolts.framework
[16:27:30]: ▸ Building Pods/GoogleToolboxForMac [Debug]
[16:27:30]: ▸ Check Dependencies
[16:27:30]: ▸ Processing Info.plist
[16:27:30]: ▸ Compiling GoogleToolboxForMac-dummy.m
[16:27:30]: ▸ Compiling GTMLogger.m
[16:27:30]: ▸ Compiling GTMNSData+zlib.m
[16:27:30]: ▸ Compiling GoogleToolboxForMac_vers.c
[16:27:30]: ▸ Linking GoogleToolboxForMac
[16:27:30]: ▸ Copying GoogleToolboxForMac-umbrella.h
[16:27:30]: ▸ Copying GTMDefines.h
[16:27:30]: ▸ Copying GTMLogger.h
[16:27:30]: ▸ Copying GTMNSData+zlib.h
[16:27:30]: Running Tests: ▸ Touching GoogleToolboxForMac.framework
[16:27:30]: ▸ Building Pods/ActionSheetPicker-3.0 [Debug]
[16:27:30]: ▸ Check Dependencies
[16:27:30]: ▸ Processing Info.plist
[16:27:30]: ▸ Compiling ActionSheetCustomPicker.m
[16:27:30]: ▸ Compiling ActionSheetDatePicker.m
[16:27:30]: ▸ Compiling AbstractActionSheetPicker.m
[16:27:30]: ▸ Compiling ActionSheetDistancePicker.m
[16:27:30]: ▸ Compiling ActionSheetLocalePicker.m
[16:27:30]: ▸ Compiling ActionSheetMultipleStringPicker.m
[16:27:30]: ▸ Compiling ActionSheetPicker-3.0-dummy.m
[16:27:30]: ▸ Compiling ActionSheetStringPicker.m
[16:27:30]: ▸ Compiling DistancePickerView.m
[16:27:30]: ▸ Compiling SWActionSheet.m
[16:27:30]: ▸ Compiling ActionSheetPicker_3_0_vers.c
[16:27:30]: ▸ Linking ActionSheetPicker_3_0
[16:27:30]: ▸ Copying AbstractActionSheetPicker.h
[16:27:30]: ▸ Copying ActionSheetCustomPicker.h
[16:27:30]: ▸ Copying ActionSheetCustomPickerDelegate.h
[16:27:30]: ▸ Copying ActionSheetDatePicker.h
[16:27:31]: ▸ Copying ActionSheetDistancePicker.h
[16:27:31]: ▸ Copying ActionSheetLocalePicker.h
[16:27:31]: ▸ Copying ActionSheetMultipleStringPicker.h
[16:27:31]: ▸ Copying ActionSheetPicker-3.0-umbrella.h
[16:27:31]: ▸ Copying ActionSheetPicker.h
[16:27:31]: ▸ Copying ActionSheetStringPicker.h
[16:27:31]: ▸ Copying DistancePickerView.h
[16:27:31]: ▸ Copying SWActionSheet.h
[16:27:31]: Running Tests: ▸ Touching ActionSheetPicker_3_0.framework
[16:27:31]: ▸ Building Pods/InputMask [Debug]
[16:27:31]: ▸ Check Dependencies
[16:27:31]: ▸ Processing Info.plist
[16:27:31]: ▸ Compiling CaretString.swift
[16:27:33]: ▸ Compiling CaretStringIterator.swift
[16:27:33]: ▸ Compiling Compiler.swift
[16:27:33]: ▸ Compiling EOLState.swift
[16:27:33]: ▸ Compiling FixedState.swift
[16:27:33]: ▸ Compiling FormatSanitizer.swift
[16:27:34]: ▸ Compiling FreeState.swift
[16:27:34]: ▸ Compiling InterfaceBuilderSupport.swift
[16:27:34]: ▸ Compiling Mask.swift
[16:27:34]: ▸ Compiling MaskedTextFieldDelegate.swift
[16:27:35]: ▸ Compiling Next.swift
[16:27:35]: ▸ Compiling NSCharacterSet.swift
[16:27:35]: ▸ Compiling OptionalValueState.swift
[16:27:35]: ▸ Compiling PolyMaskTextFieldDelegate.swift
[16:27:35]: ▸ Compiling State.swift
[16:27:35]: ▸ Compiling String.swift
[16:27:35]: ▸ Compiling ValueState.swift
[16:27:36]: ▸ Compiling InputMask-dummy.m
[16:27:36]: ▸ Compiling InputMask_vers.c
[16:27:36]: ▸ Linking InputMask
[16:27:42]: ▸ Copying InputMask-umbrella.h
[16:27:42]: ▸ Copying InputMask.h
[16:27:42]: Running Tests: ▸ Touching InputMask.framework
[16:27:42]: ▸ Building Pods/JSQSystemSoundPlayer [Debug]
[16:27:42]: ▸ Check Dependencies
[16:27:42]: ▸ Processing Info.plist
[16:27:42]: ▸ Compiling JSQSystemSoundPlayer-dummy.m
[16:27:42]: ▸ Compiling JSQSystemSoundPlayer.m
[16:27:42]: ▸ Compiling JSQSystemSoundPlayer_vers.c
[16:27:42]: ▸ Linking JSQSystemSoundPlayer
[16:27:42]: ▸ Copying JSQSystemSoundPlayer-umbrella.h
[16:27:42]: ▸ Copying JSQSystemSoundPlayer.h
[16:27:42]: Running Tests: ▸ Touching JSQSystemSoundPlayer.framework
[16:27:42]: ▸ Building Pods/FBSDKCoreKit [Debug]
[16:27:42]: ▸ Check Dependencies
[16:27:42]: ▸ Processing Info.plist
[16:27:42]: ▸ Compiling _FBSDKTemporaryErrorRecoveryAttempter.m
[16:27:42]: ▸ Compiling FBSDKAccessToken.m
[16:27:42]: ▸ Compiling FBSDKAccessTokenCache.m
[16:27:42]: ▸ Compiling FBSDKAccessTokenCacheV3.m
[16:27:42]: ▸ Compiling FBSDKAccessTokenCacheV3_17.m
[16:27:42]: ▸ Compiling FBSDKAccessTokenCacheV3_21.m
[16:27:42]: ▸ Compiling FBSDKAccessTokenCacheV4.m
[16:27:42]: ▸ Compiling FBSDKAppEvents.m
[16:27:42]: ▸ Compiling FBSDKAppEventsDeviceInfo.m
[16:27:42]: ▸ Compiling FBSDKAppEventsState.m
[16:27:42]: ▸ Compiling FBSDKAppEventsStateManager.m
[16:27:42]: ▸ Compiling FBSDKAppEventsUtility.m
[16:27:42]: ▸ Compiling FBSDKApplicationDelegate.m
[16:27:42]: ▸ Compiling FBSDKAppLinkResolver.m
[16:27:42]: ▸ Compiling FBSDKAppLinkUtility.m
[16:27:42]: ▸ Compiling FBSDKAudioResourceLoader.m
[16:27:42]: ▸ Compiling FBSDKBase64.m
[16:27:42]: ▸ Compiling FBSDKBoltsMeasurementEventListener.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPICrypto.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPIProtocolNativeV1.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPIProtocolWebV1.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPIProtocolWebV2.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPIRequest.m
[16:27:42]: ▸ Compiling FBSDKBridgeAPIResponse.m
[16:27:42]: ▸ Compiling FBSDKButton.m
[16:27:42]: ▸ Compiling FBSDKCloseIcon.m
[16:27:42]: ▸ Compiling FBSDKColor.m
[16:27:42]: ▸ Compiling FBSDKConstants.m
[16:27:42]: ▸ Compiling FBSDKContainerViewController.m
[16:27:42]: ▸ Compiling FBSDKCoreKit-dummy.m
[16:27:42]: ▸ Compiling FBSDKCrypto.m
[16:27:42]: ▸ Compiling FBSDKDeviceRequestsHelper.m
[16:27:42]: ▸ Compiling FBSDKDialogConfiguration.m
[16:27:42]: ▸ Compiling FBSDKDynamicFrameworkLoader.m
[16:27:42]: ▸ Compiling FBSDKError.m
[16:27:42]: ▸ Compiling FBSDKErrorConfiguration.m
[16:27:42]: ▸ Compiling FBSDKErrorRecoveryAttempter.m
[16:27:42]: ▸ Compiling FBSDKErrorRecoveryConfiguration.m
[16:27:42]: ▸ Compiling FBSDKGraphErrorRecoveryProcessor.m
[16:27:42]: ▸ Compiling FBSDKGraphRequest.m
[16:27:42]: ▸ Compiling FBSDKGraphRequestBody.m
[16:27:42]: ▸ Compiling FBSDKGraphRequestConnection.m
[16:27:42]: ▸ Compiling FBSDKGraphRequestDataAttachment.m
[16:27:42]: ▸ Compiling FBSDKGraphRequestMetadata.m
[16:27:42]: ▸ Compiling FBSDKGraphRequestPiggybackManager.m
[16:27:42]: ▸ Compiling FBSDKIcon.m
[16:27:42]: ▸ Compiling FBSDKImageDownloader.m
[16:27:42]: ▸ Compiling FBSDKInternalUtility.m
[16:27:42]: ▸ Compiling FBSDKKeychainStore.m
[16:27:42]: ▸ Compiling FBSDKKeychainStoreViaBundleID.m
[16:27:42]: ▸ Compiling FBSDKLogger.m
[16:27:42]: ▸ Compiling FBSDKLogo.m
[16:27:42]: ▸ Compiling FBSDKMaleSilhouetteIcon.m
[16:27:42]: ▸ Compiling FBSDKMath.m
[16:27:42]: ▸ Compiling FBSDKMonotonicTime.m
[16:27:42]: ▸ Compiling FBSDKPaymentObserver.m
[16:27:42]: ▸ Compiling FBSDKProfile.m
[16:27:42]: ▸ Compiling FBSDKProfilePictureView.m
[16:27:42]: ▸ Compiling FBSDKServerConfiguration.m
[16:27:42]: ▸ Compiling FBSDKServerConfigurationManager.m
[16:27:42]: ▸ Compiling FBSDKSettings.m
[16:27:42]: ▸ Compiling FBSDKSystemAccountStoreAdapter.m
[16:27:42]: ▸ Compiling FBSDKTestUsersManager.m
[16:27:42]: ▸ Compiling FBSDKTimeSpentData.m
[16:27:42]: ▸ Compiling FBSDKTriStateBOOL.m
[16:27:42]: ▸ Compiling FBSDKTypeUtility.m
[16:27:42]: ▸ Compiling FBSDKURLConnection.m
[16:27:42]: ▸ Compiling FBSDKURLSessionTask.m
[16:27:42]: ▸ Compiling FBSDKUtility.m
[16:27:42]: ▸ Compiling FBSDKViewImpressionTracker.m
[16:27:42]: ▸ Compiling FBSDKWebDialog.m
[16:27:42]: ▸ Compiling FBSDKWebDialogView.m
[16:27:42]: ▸ Compiling FBSDKCoreKit_vers.c
[16:27:42]: ▸ Linking FBSDKCoreKit
[16:27:42]: ▸ Copying FBSDKAccessToken.h
[16:27:42]: ▸ Copying FBSDKAppEvents.h
[16:27:42]: ▸ Copying FBSDKApplicationDelegate.h
[16:27:42]: ▸ Copying FBSDKAppLinkResolver.h
[16:27:42]: ▸ Copying FBSDKAppLinkUtility.h
[16:27:42]: ▸ Copying FBSDKButton.h
[16:27:42]: ▸ Copying FBSDKConstants.h
[16:27:42]: ▸ Copying FBSDKCopying.h
[16:27:42]: ▸ Copying FBSDKCoreKit-umbrella.h
[16:27:42]: ▸ Copying FBSDKCoreKit.h
[16:27:42]: ▸ Copying FBSDKGraphErrorRecoveryProcessor.h
[16:27:42]: ▸ Copying FBSDKGraphRequest.h
[16:27:42]: ▸ Copying FBSDKGraphRequestConnection.h
[16:27:42]: ▸ Copying FBSDKGraphRequestDataAttachment.h
[16:27:42]: ▸ Copying FBSDKMacros.h
[16:27:42]: ▸ Copying FBSDKMutableCopying.h
[16:27:42]: ▸ Copying FBSDKProfile.h
[16:27:42]: ▸ Copying FBSDKProfilePictureView.h
[16:27:42]: ▸ Copying FBSDKSettings.h
[16:27:42]: ▸ Copying FBSDKTestUsersManager.h
[16:27:42]: ▸ Copying FBSDKUtility.h
[16:27:42]: ▸ Copying FBSDKCoreKit/FacebookSDKStrings.bundle
[16:27:42]: Running Tests: ▸ Touching FBSDKCoreKit.framework
[16:27:42]: ▸ Building Pods/JSQMessagesViewController [Debug]
[16:27:42]: ▸ Check Dependencies
[16:27:42]: ▸ Compiling JSQAudioMediaItem.m
[16:27:42]: ▸ Compiling JSQAudioMediaViewAttributes.m
[16:27:42]: ▸ Compiling JSQLocationMediaItem.m
[16:27:42]: ▸ Compiling JSQMediaItem.m
[16:27:42]: ▸ Compiling JSQMessage.m
[16:27:42]: ▸ Compiling JSQMessagesAvatarImage.m
[16:27:42]: ▸ Compiling JSQMessagesAvatarImageFactory.m
[16:27:42]: ▸ Compiling JSQMessagesBubbleImage.m
[16:27:42]: ▸ Compiling JSQMessagesBubbleImageFactory.m
[16:27:42]: ▸ Compiling JSQMessagesBubblesSizeCalculator.m
[16:27:42]: ▸ Compiling JSQMessagesCellTextView.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionView.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewCell.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewCellIncoming.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewCellOutgoing.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewFlowLayout.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewFlowLayoutInvalidationContext.m
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewLayoutAttributes.m
[16:27:42]: ▸ Compiling JSQMessagesComposerTextView.m
[16:27:42]: ▸ Compiling JSQMessagesInputToolbar.m
[16:27:42]: ▸ Compiling JSQMessagesKeyboardController.m
[16:27:42]: ▸ Compiling JSQMessagesLabel.m
[16:27:42]: ▸ Compiling JSQMessagesLoadEarlierHeaderView.m
[16:27:42]: ▸ Compiling JSQMessagesMediaPlaceholderView.m
[16:27:42]: ▸ Compiling JSQMessagesMediaViewBubbleImageMasker.m
[16:27:42]: ▸ Compiling JSQMessagesTimestampFormatter.m
[16:27:42]: ▸ Compiling JSQMessagesToolbarButtonFactory.m
[16:27:42]: ▸ Compiling JSQMessagesToolbarContentView.m
[16:27:42]: ▸ Compiling JSQMessagesTypingIndicatorFooterView.m
[16:27:42]: ▸ Compiling JSQMessagesViewController-dummy.m
[16:27:42]: ▸ Compiling JSQMessagesViewController.m
[16:27:42]: ▸ Compiling JSQPhotoMediaItem.m
[16:27:42]: ▸ Compiling JSQSystemSoundPlayer+JSQMessages.m
[16:27:42]: ▸ Compiling JSQVideoMediaItem.m
[16:27:42]: ▸ Compiling NSBundle+JSQMessages.m
[16:27:42]: ▸ Compiling NSString+JSQMessages.m
[16:27:42]: ▸ Compiling UIColor+JSQMessages.m
[16:27:42]: ▸ Compiling UIDevice+JSQMessages.m
[16:27:42]: ▸ Compiling UIImage+JSQMessages.m
[16:27:42]: ▸ Compiling UIView+JSQMessages.m
[16:27:42]: ▸ Compiling JSQMessagesViewController_vers.c
[16:27:42]: ▸ Linking JSQMessagesViewController
[16:27:42]: ▸ Copying JSQAudioMediaViewAttributes.h
[16:27:42]: ▸ Copying JSQLocationMediaItem.h
[16:27:42]: ▸ Copying JSQMediaItem.h
[16:27:42]: ▸ Copying JSQMessage.h
[16:27:42]: ▸ Copying JSQMessageAvatarImageDataSource.h
[16:27:42]: ▸ Copying JSQMessageBubbleImageDataSource.h
[16:27:42]: ▸ Copying JSQMessageData.h
[16:27:42]: ▸ Copying JSQMessageMediaData.h
[16:27:42]: ▸ Copying JSQMessages.h
[16:27:42]: ▸ Copying JSQAudioMediaItem.h
[16:27:42]: ▸ Copying JSQMessagesAvatarImage.h
[16:27:42]: ▸ Copying JSQMessagesAvatarImageFactory.h
[16:27:42]: ▸ Copying JSQMessagesBubbleImage.h
[16:27:42]: ▸ Copying JSQMessagesBubbleImageFactory.h
[16:27:42]: ▸ Copying JSQMessagesBubbleSizeCalculating.h
[16:27:42]: ▸ Copying JSQMessagesBubblesSizeCalculator.h
[16:27:42]: ▸ Copying JSQMessagesCellTextView.h
[16:27:42]: ▸ Copying JSQMessagesCollectionView.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewCell.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewCellIncoming.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewCellOutgoing.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewDataSource.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewDelegateFlowLayout.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewFlowLayout.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewFlowLayoutInvalidationContext.h
[16:27:42]: ▸ Copying JSQMessagesCollectionViewLayoutAttributes.h
[16:27:42]: ▸ Copying JSQMessagesComposerTextView.h
[16:27:42]: ▸ Copying JSQMessagesInputToolbar.h
[16:27:42]: ▸ Copying JSQMessagesKeyboardController.h
[16:27:42]: ▸ Copying JSQMessagesLabel.h
[16:27:42]: ▸ Copying JSQMessagesLoadEarlierHeaderView.h
[16:27:42]: ▸ Copying JSQMessagesMediaPlaceholderView.h
[16:27:42]: ▸ Copying JSQMessagesMediaViewBubbleImageMasker.h
[16:27:42]: ▸ Copying JSQMessagesTimestampFormatter.h
[16:27:42]: ▸ Copying JSQMessagesToolbarButtonFactory.h
[16:27:42]: ▸ Copying JSQMessagesToolbarContentView.h
[16:27:42]: ▸ Copying JSQMessagesTypingIndicatorFooterView.h
[16:27:42]: ▸ Copying JSQMessagesViewController-umbrella.h
[16:27:42]: ▸ Copying JSQMessagesViewController.h
[16:27:42]: ▸ Copying JSQPhotoMediaItem.h
[16:27:42]: ▸ Copying JSQSystemSoundPlayer+JSQMessages.h
[16:27:42]: ▸ Copying JSQVideoMediaItem.h
[16:27:42]: ▸ Copying NSBundle+JSQMessages.h
[16:27:42]: ▸ Copying NSString+JSQMessages.h
[16:27:42]: ▸ Copying UIColor+JSQMessages.h
[16:27:42]: ▸ Copying UIDevice+JSQMessages.h
[16:27:42]: ▸ Copying UIImage+JSQMessages.h
[16:27:42]: ▸ Copying UIView+JSQMessages.h
[16:27:42]: ▸ Copying JSQMessagesViewController/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewCellOutgoing.xib
[16:27:42]: ▸ Compiling JSQMessagesLoadEarlierHeaderView.xib
[16:27:42]: ▸ Compiling JSQMessagesToolbarContentView.xib
[16:27:42]: ▸ Compiling JSQMessagesTypingIndicatorFooterView.xib
[16:27:42]: ▸ Compiling JSQMessagesCollectionViewCellIncoming.xib
[16:27:42]: ▸ Compiling JSQMessagesViewController.xib
[16:27:42]: ▸ Processing Info.plist
[16:27:42]: Running Tests: ▸ Touching JSQMessagesViewController.framework
[16:27:42]: ▸ Building Pods/MIBadgeButton-Swift [Debug]
[16:27:42]: ▸ Check Dependencies
[16:27:42]: ▸ Processing Info.plist
[16:27:42]: ▸ Compiling MIBadgeButton.swift
[16:27:42]: ▸ Compiling MIBadgeButton-Swift-dummy.m
[16:27:42]: ▸ Compiling MIBadgeButton_Swift_vers.c
[16:27:42]: ▸ Linking MIBadgeButton_Swift
[16:27:42]: ▸ Copying MIBadgeButton-Swift-umbrella.h
[16:27:42]: Running Tests: ▸ Touching MIBadgeButton_Swift.framework
[16:27:42]: ▸ Building Pods/ObjectMapper [Debug]
[16:27:42]: ▸ Check Dependencies
[16:27:42]: ▸ Processing Info.plist
[16:27:42]: ▸ Compiling CustomDateFormatTransform.swift
[16:27:42]: ▸ Compiling DataTransform.swift
[16:27:42]: ▸ Compiling DateFormatterTransform.swift
[16:27:42]: ▸ Compiling DateTransform.swift
[16:27:42]: ▸ Compiling DictionaryTransform.swift
[16:27:42]: ▸ Compiling EnumOperators.swift
[16:27:42]: ▸ Compiling EnumTransform.swift
[16:27:42]: ▸ Compiling FromJSON.swift
[16:27:42]: ▸ Compiling HexColorTransform.swift
[16:27:42]: ▸ Compiling ImmutableMappable.swift
[16:27:42]: ▸ Compiling IntegerOperators.swift
[16:27:42]: ▸ Compiling ISO8601DateTransform.swift
[16:27:42]: ▸ Compiling Map.swift
[16:27:42]: ▸ Compiling MapError.swift
[16:27:42]: ▸ Compiling Mappable.swift
[16:27:42]: ▸ Compiling Mapper.swift
[16:27:42]: ▸ Compiling NSDecimalNumberTransform.swift
[16:27:42]: ▸ Compiling Operators.swift
[16:27:42]: ▸ Compiling ToJSON.swift
[16:27:42]: ▸ Compiling TransformOf.swift
[16:27:42]: ▸ Compiling TransformOperators.swift
[16:27:42]: ▸ Compiling TransformType.swift
[16:27:42]: ▸ Compiling URLTransform.swift
[16:27:42]: ▸ Compiling ObjectMapper-dummy.m
[16:27:42]: ▸ Compiling ObjectMapper_vers.c
[16:27:47]: ▸ Linking ObjectMapper
[16:27:50]: ▸ Copying ObjectMapper-umbrella.h
[16:27:57]: Running Tests: ▸ Touching ObjectMapper.framework
[16:27:57]: ▸ Building Pods/Realm [Debug]
[16:27:57]: ▸ Check Dependencies
[16:27:57]: ▸ Processing Info.plist
[16:27:57]: ▸ Compiling binding_callback_thread_observer.cpp
[16:27:57]: ▸ Compiling collection_change_builder.cpp
[16:27:57]: ▸ Compiling collection_notifications.cpp
[16:27:57]: ▸ Compiling collection_notifier.cpp
[16:27:57]: ▸ Compiling external_commit_helper.cpp
[16:27:57]: ▸ Compiling index_set.cpp
[16:27:57]: ▸ Compiling keychain_helper.cpp
[16:27:57]: ▸ Compiling list.cpp
[16:27:57]: ▸ Compiling list_notifier.cpp
[16:27:57]: ▸ Compiling network_reachability_observer.cpp
[16:27:57]: ▸ Compiling NSError+RLMSync.m
[16:27:57]: ▸ Compiling object.cpp
[16:27:57]: ▸ Compiling object_notifier.cpp
[16:27:57]: ▸ Compiling object_schema.cpp
[16:27:57]: ▸ Compiling object_store.cpp
[16:27:57]: ▸ Compiling partial_sync.cpp
[16:28:00]: ▸ Compiling placeholder.cpp
[16:28:00]: ▸ Compiling primitive_list_notifier.cpp
[16:28:00]: ▸ Compiling Realm-dummy.m
[16:28:00]: ▸ Compiling realm_coordinator.cpp
[16:28:02]: ▸ Compiling results.cpp
[16:28:02]: ▸ Compiling results_notifier.cpp
[16:28:02]: ▸ Compiling RLMAccessor.mm
[16:28:05]: ▸ Compiling RLMAnalytics.mm
[16:28:05]: ▸ Compiling RLMArray.mm
[16:28:06]: ▸ Compiling RLMClassInfo.mm
[16:28:07]: ▸ Compiling RLMCollection.mm
[16:28:09]: ▸ Compiling RLMConstants.m
[16:28:09]: ▸ Compiling RLMJSONModels.m
[16:28:09]: ▸ Compiling RLMListBase.mm
[16:28:10]: ▸ Compiling RLMManagedArray.mm
[16:28:12]: ▸ Compiling RLMMigration.mm
[16:28:13]: ▸ Compiling RLMNetworkClient.mm
[16:28:14]: ▸ Compiling RLMObject.mm
[16:28:14]: ▸ Compiling RLMObjectBase.mm
[16:28:18]: ▸ Compiling RLMObjectSchema.mm
[16:28:18]: ▸ Compiling RLMObjectStore.mm
[16:28:19]: ▸ Compiling RLMObservation.mm
[16:28:19]: ▸ Compiling RLMOptionalBase.mm
[16:28:19]: ▸ Compiling RLMPredicateUtil.mm
[16:28:19]: ▸ Compiling RLMProperty.mm
[16:28:21]: ▸ Compiling RLMQueryUtil.mm
[16:28:27]: ▸ Compiling RLMRealm+Sync.mm
[16:28:27]: ▸ Compiling RLMRealm.mm
[16:28:27]: ▸ Compiling RLMRealmConfiguration+Sync.mm
[16:28:27]: ▸ Compiling RLMRealmConfiguration.mm
[16:28:28]: ▸ Compiling RLMRealmUtil.mm
[16:28:28]: ▸ Compiling RLMResults.mm
[16:28:31]: ▸ Compiling RLMSchema.mm
[16:28:31]: ▸ Compiling RLMSwiftSupport.m
[16:28:31]: ▸ Compiling RLMSyncConfiguration.mm
[16:28:33]: ▸ Compiling RLMSyncCredentials.m
[16:28:33]: ▸ Compiling RLMSyncManager.mm
[16:28:33]: ▸ Compiling RLMSyncPermission.mm
[16:28:35]: ▸ Compiling RLMSyncPermissionResults.mm
[16:28:36]: ▸ Compiling RLMSyncSession.mm
[16:28:39]: ▸ Compiling RLMSyncSessionRefreshHandle.mm
[16:28:39]: ▸ Compiling RLMSyncSubscription.mm
[16:28:39]: ▸ Compiling RLMSyncUser.mm
[16:28:43]: ▸ Compiling RLMSyncUtil.mm
[16:28:43]: ▸ Compiling RLMThreadSafeReference.mm
[16:28:43]: ▸ Compiling RLMUpdateChecker.mm
[16:28:43]: ▸ Compiling RLMUtil.mm
[16:28:45]: ▸ Compiling schema.cpp
[16:28:45]: ▸ Compiling shared_realm.cpp
[16:28:48]: ▸ Compiling sync_config.cpp
[16:28:48]: ▸ Compiling sync_file.cpp
[16:28:48]: ▸ Compiling sync_manager.cpp
[16:28:51]: ▸ Compiling sync_metadata.cpp
[16:28:51]: ▸ Compiling sync_permission.cpp
[16:28:54]: ▸ Compiling sync_session.cpp
[16:28:55]: ▸ Compiling sync_user.cpp
[16:28:55]: ▸ Compiling system_configuration.cpp
[16:28:55]: ▸ Compiling thread_safe_reference.cpp
[16:28:55]: ▸ Compiling transact_log_handler.cpp
[16:28:59]: ▸ Compiling uuid.cpp
[16:28:59]: ▸ Compiling weak_realm_notifier.cpp
[16:28:59]: ▸ Compiling work_queue.cpp
[16:28:59]: ▸ Compiling Realm_vers.c
[16:28:59]: ▸ Linking Realm
[16:29:01]: ▸ Copying Realm/include/RLMAccessor.h
[16:29:01]: ▸ Copying Realm/include/RLMArray_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMCollection_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMListBase.h
[16:29:01]: ▸ Copying Realm/include/RLMMigration_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMObject_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMObjectBase_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMObjectSchema_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMObjectStore.h
[16:29:01]: ▸ Copying Realm/include/RLMOptionalBase.h
[16:29:01]: ▸ Copying Realm/include/RLMProperty_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMRealm_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMRealmConfiguration_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMResults_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMSchema_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMSyncConfiguration_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMSyncManager_Private.h
[16:29:01]: ▸ Copying Realm/include/RLMSyncUtil_Private.h
[16:29:01]: ▸ Copying Realm/include/NSError+RLMSync.h
[16:29:01]: ▸ Copying Realm/include/Realm.h
[16:29:01]: ▸ Copying Realm/include/RLMArray.h
[16:29:01]: ▸ Copying Realm/include/RLMCollection.h
[16:29:01]: ▸ Copying Realm/include/RLMConstants.h
[16:29:01]: ▸ Copying Realm/include/RLMListBase.h
[16:29:01]: ▸ Copying Realm/include/RLMMigration.h
[16:29:02]: ▸ Copying Realm/include/RLMObject.h
[16:29:02]: ▸ Copying Realm/include/RLMObjectBase.h
[16:29:02]: ▸ Copying Realm/include/RLMObjectBase_Dynamic.h
[16:29:02]: ▸ Copying Realm/include/RLMObjectSchema.h
[16:29:02]: ▸ Copying Realm/include/RLMOptionalBase.h
[16:29:02]: ▸ Copying Realm/include/RLMPlatform.h
[16:29:02]: ▸ Copying Realm/include/RLMProperty.h
[16:29:02]: ▸ Copying Realm/include/RLMRealm+Sync.h
[16:29:02]: ▸ Copying Realm/include/RLMRealm.h
[16:29:02]: ▸ Copying Realm/include/RLMRealm_Dynamic.h
[16:29:02]: ▸ Copying Realm/include/RLMRealmConfiguration+Sync.h
[16:29:02]: ▸ Copying Realm/include/RLMRealmConfiguration.h
[16:29:02]: ▸ Copying Realm/include/RLMResults.h
[16:29:02]: ▸ Copying Realm/include/RLMSchema.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncConfiguration.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncCredentials.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncManager.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncPermission.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncSession.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncSubscription.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncUser.h
[16:29:02]: ▸ Copying Realm/include/RLMSyncUtil.h
[16:29:02]: ▸ Copying Realm/include/RLMThreadSafeReference.h
[16:29:02]: Running Tests: ▸ Touching Realm.framework
[16:29:02]: ▸ Building Pods/Protobuf [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling Any.pbobjc.m
[16:29:02]: ▸ Compiling Api.pbobjc.m
[16:29:02]: ▸ Compiling Duration.pbobjc.m
[16:29:02]: ▸ Compiling Empty.pbobjc.m
[16:29:02]: ▸ Compiling FieldMask.pbobjc.m
[16:29:02]: ▸ Compiling GPBArray.m
[16:29:02]: ▸ Compiling GPBCodedInputStream.m
[16:29:02]: ▸ Compiling GPBCodedOutputStream.m
[16:29:02]: ▸ Compiling GPBDescriptor.m
[16:29:02]: ▸ Compiling GPBDictionary.m
[16:29:02]: ▸ Compiling GPBExtensionInternals.m
[16:29:02]: ▸ Compiling GPBExtensionRegistry.m
[16:29:02]: ▸ Compiling GPBMessage.m
[16:29:02]: ▸ Compiling GPBRootObject.m
[16:29:02]: ▸ Compiling GPBUnknownField.m
[16:29:02]: ▸ Compiling GPBUnknownFieldSet.m
[16:29:02]: ▸ Compiling GPBUtilities.m
[16:29:02]: ▸ Compiling GPBWellKnownTypes.m
[16:29:02]: ▸ Compiling GPBWireFormat.m
[16:29:02]: ▸ Compiling Protobuf-dummy.m
[16:29:02]: ▸ Compiling SourceContext.pbobjc.m
[16:29:02]: ▸ Compiling Struct.pbobjc.m
[16:29:02]: ▸ Compiling Timestamp.pbobjc.m
[16:29:02]: ▸ Compiling Type.pbobjc.m
[16:29:02]: ▸ Compiling Wrappers.pbobjc.m
[16:29:02]: ▸ Compiling Protobuf_vers.c
[16:29:02]: ▸ Linking Protobuf
[16:29:02]: ▸ Copying Any.pbobjc.h
[16:29:02]: ▸ Copying Api.pbobjc.h
[16:29:02]: ▸ Copying Duration.pbobjc.h
[16:29:02]: ▸ Copying Empty.pbobjc.h
[16:29:02]: ▸ Copying FieldMask.pbobjc.h
[16:29:02]: ▸ Copying GPBArray.h
[16:29:02]: ▸ Copying GPBArray_PackagePrivate.h
[16:29:02]: ▸ Copying GPBBootstrap.h
[16:29:02]: ▸ Copying GPBCodedInputStream.h
[16:29:02]: ▸ Copying GPBCodedInputStream_PackagePrivate.h
[16:29:02]: ▸ Copying GPBCodedOutputStream.h
[16:29:02]: ▸ Copying GPBCodedOutputStream_PackagePrivate.h
[16:29:02]: ▸ Copying GPBDescriptor.h
[16:29:02]: ▸ Copying GPBDescriptor_PackagePrivate.h
[16:29:02]: ▸ Copying GPBDictionary.h
[16:29:02]: ▸ Copying GPBDictionary_PackagePrivate.h
[16:29:02]: ▸ Copying GPBExtensionInternals.h
[16:29:02]: ▸ Copying GPBExtensionRegistry.h
[16:29:02]: ▸ Copying GPBMessage.h
[16:29:02]: ▸ Copying GPBMessage_PackagePrivate.h
[16:29:02]: ▸ Copying GPBProtocolBuffers.h
[16:29:02]: ▸ Copying GPBProtocolBuffers_RuntimeSupport.h
[16:29:02]: ▸ Copying GPBRootObject.h
[16:29:02]: ▸ Copying GPBRootObject_PackagePrivate.h
[16:29:02]: ▸ Copying GPBRuntimeTypes.h
[16:29:02]: ▸ Copying GPBUnknownField.h
[16:29:02]: ▸ Copying GPBUnknownField_PackagePrivate.h
[16:29:02]: ▸ Copying GPBUnknownFieldSet.h
[16:29:02]: ▸ Copying GPBUnknownFieldSet_PackagePrivate.h
[16:29:02]: ▸ Copying GPBUtilities.h
[16:29:02]: ▸ Copying GPBUtilities_PackagePrivate.h
[16:29:02]: ▸ Copying GPBWellKnownTypes.h
[16:29:02]: ▸ Copying GPBWireFormat.h
[16:29:02]: ▸ Copying Protobuf-umbrella.h
[16:29:02]: ▸ Copying SourceContext.pbobjc.h
[16:29:02]: ▸ Copying Struct.pbobjc.h
[16:29:02]: ▸ Copying Timestamp.pbobjc.h
[16:29:02]: ▸ Copying Type.pbobjc.h
[16:29:02]: ▸ Copying Wrappers.pbobjc.h
[16:29:02]: Running Tests: ▸ Touching Protobuf.framework
[16:29:02]: ▸ Building Pods/FBSDKLoginKit [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling _FBSDKLoginRecoveryAttempter.m
[16:29:02]: ▸ Compiling FBSDKLoginButton.m
[16:29:02]: ▸ Compiling FBSDKLoginCompletion.m
[16:29:02]: ▸ Compiling FBSDKLoginConstants.m
[16:29:02]: ▸ Compiling FBSDKLoginError.m
[16:29:02]: ▸ Compiling FBSDKLoginKit-dummy.m
[16:29:02]: ▸ Compiling FBSDKLoginManager.m
[16:29:02]: ▸ Compiling FBSDKLoginManagerLogger.m
[16:29:02]: ▸ Compiling FBSDKLoginManagerLoginResult.m
[16:29:02]: ▸ Compiling FBSDKLoginTooltipView.m
[16:29:02]: ▸ Compiling FBSDKLoginUtility.m
[16:29:02]: ▸ Compiling FBSDKTooltipView.m
[16:29:02]: ▸ Compiling FBSDKLoginKit_vers.c
[16:29:02]: ▸ Linking FBSDKLoginKit
[16:29:02]: ▸ Copying FBSDKLoginButton.h
[16:29:02]: ▸ Copying FBSDKLoginConstants.h
[16:29:02]: ▸ Copying FBSDKLoginKit-umbrella.h
[16:29:02]: ▸ Copying FBSDKLoginKit.h
[16:29:02]: ▸ Copying FBSDKLoginManager.h
[16:29:02]: ▸ Copying FBSDKLoginManagerLoginResult.h
[16:29:02]: ▸ Copying FBSDKLoginTooltipView.h
[16:29:02]: ▸ Copying FBSDKTooltipView.h
[16:29:02]: Running Tests: ▸ Touching FBSDKLoginKit.framework
[16:29:02]: ▸ Building Pods/RBBAnimation [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling NSValue+PlatformIndependence.m
[16:29:02]: ▸ Compiling RBBAnimation-dummy.m
[16:29:02]: ▸ Compiling RBBAnimation.m
[16:29:02]: ▸ Compiling RBBBlockBasedArray.m
[16:29:02]: ▸ Compiling RBBCubicBezier.m
[16:29:02]: ▸ Compiling RBBCustomAnimation.m
[16:29:02]: ▸ Compiling RBBEasingFunction.m
[16:29:02]: ▸ Compiling RBBLinearInterpolation.m
[16:29:02]: ▸ Compiling RBBSpringAnimation.m
[16:29:02]: ▸ Compiling RBBTweenAnimation.m
[16:29:02]: ▸ Compiling UIColor+PlatformIndependence.m
[16:29:02]: ▸ Compiling RBBAnimation_vers.c
[16:29:02]: ▸ Linking RBBAnimation
[16:29:02]: ▸ Copying NSValue+PlatformIndependence.h
[16:29:02]: ▸ Copying RBBAnimation-umbrella.h
[16:29:02]: ▸ Copying RBBAnimation.h
[16:29:02]: ▸ Copying RBBBlockBasedArray.h
[16:29:02]: ▸ Copying RBBCubicBezier.h
[16:29:02]: ▸ Copying RBBCustomAnimation.h
[16:29:02]: ▸ Copying RBBEasingFunction.h
[16:29:02]: ▸ Copying RBBLinearInterpolation.h
[16:29:02]: ▸ Copying RBBSpringAnimation.h
[16:29:02]: ▸ Copying RBBTweenAnimation.h
[16:29:02]: ▸ Copying UIColor+PlatformIndependence.h
[16:29:02]: Running Tests: ▸ Touching RBBAnimation.framework
[16:29:02]: ▸ Building Pods/SDCAutoLayout [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling SDCAutoLayout-dummy.m
[16:29:02]: ▸ Compiling UIView+SDCAutoLayout.m
[16:29:02]: ▸ Compiling SDCAutoLayout_vers.c
[16:29:02]: ▸ Linking SDCAutoLayout
[16:29:02]: ▸ Copying SDCAutoLayout-umbrella.h
[16:29:02]: ▸ Copying UIView+SDCAutoLayout.h
[16:29:02]: Running Tests: ▸ Touching SDCAutoLayout.framework
[16:29:02]: ▸ Building Pods/SDWebImage [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling NSButton+WebCache.m
[16:29:02]: ▸ Compiling NSData+ImageContentType.m
[16:29:02]: ▸ Compiling NSImage+WebCache.m
[16:29:02]: ▸ Compiling SDAnimatedImageRep.m
[16:29:02]: ▸ Compiling SDImageCache.m
[16:29:02]: ▸ Compiling SDImageCacheConfig.m
[16:29:02]: ▸ Compiling SDWebImage-dummy.m
[16:29:02]: ▸ Compiling SDWebImageCoder.m
[16:29:02]: ▸ Compiling SDWebImageCoderHelper.m
[16:29:02]: ▸ Compiling SDWebImageCodersManager.m
[16:29:02]: ▸ Compiling SDWebImageCompat.m
[16:29:02]: ▸ Compiling SDWebImageDownloader.m
[16:29:02]: ▸ Compiling SDWebImageDownloaderOperation.m
[16:29:02]: ▸ Compiling SDWebImageFrame.m
[16:29:02]: ▸ Compiling SDWebImageGIFCoder.m
[16:29:02]: ▸ Compiling SDWebImageImageIOCoder.m
[16:29:02]: ▸ Compiling SDWebImageManager.m
[16:29:02]: ▸ Compiling SDWebImagePrefetcher.m
[16:29:02]: ▸ Compiling SDWebImageTransition.m
[16:29:02]: ▸ Compiling UIButton+WebCache.m
[16:29:02]: ▸ Compiling UIImage+ForceDecode.m
[16:29:02]: ▸ Compiling UIImage+GIF.m
[16:29:02]: ▸ Compiling UIImage+MultiFormat.m
[16:29:02]: ▸ Compiling UIImageView+HighlightedWebCache.m
[16:29:02]: ▸ Compiling UIImageView+WebCache.m
[16:29:02]: ▸ Compiling UIView+WebCache.m
[16:29:02]: ▸ Compiling UIView+WebCacheOperation.m
[16:29:02]: ▸ Compiling SDWebImage_vers.c
[16:29:02]: ▸ Linking SDWebImage
[16:29:02]: ▸ Copying NSButton+WebCache.h
[16:29:02]: ▸ Copying NSData+ImageContentType.h
[16:29:02]: ▸ Copying NSImage+WebCache.h
[16:29:02]: ▸ Copying SDAnimatedImageRep.h
[16:29:02]: ▸ Copying SDImageCache.h
[16:29:02]: ▸ Copying SDImageCacheConfig.h
[16:29:02]: ▸ Copying SDWebImage-umbrella.h
[16:29:02]: ▸ Copying SDWebImageCoder.h
[16:29:02]: ▸ Copying SDWebImageCoderHelper.h
[16:29:02]: ▸ Copying SDWebImageCodersManager.h
[16:29:02]: ▸ Copying SDWebImageCompat.h
[16:29:02]: ▸ Copying SDWebImageDownloader.h
[16:29:02]: ▸ Copying SDWebImageDownloaderOperation.h
[16:29:02]: ▸ Copying SDWebImageFrame.h
[16:29:02]: ▸ Copying SDWebImageGIFCoder.h
[16:29:02]: ▸ Copying SDWebImageImageIOCoder.h
[16:29:02]: ▸ Copying SDWebImageManager.h
[16:29:02]: ▸ Copying SDWebImageOperation.h
[16:29:02]: ▸ Copying SDWebImagePrefetcher.h
[16:29:02]: ▸ Copying SDWebImageTransition.h
[16:29:02]: ▸ Copying UIButton+WebCache.h
[16:29:02]: ▸ Copying UIImage+ForceDecode.h
[16:29:02]: ▸ Copying UIImage+GIF.h
[16:29:02]: ▸ Copying UIImage+MultiFormat.h
[16:29:02]: ▸ Copying UIImageView+HighlightedWebCache.h
[16:29:02]: ▸ Copying UIImageView+WebCache.h
[16:29:02]: ▸ Copying UIView+WebCache.h
[16:29:02]: ▸ Copying UIView+WebCacheOperation.h
[16:29:02]: Running Tests: ▸ Touching SDWebImage.framework
[16:29:02]: ▸ Building Pods/SDCAlertView [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling SDCAlertAction.m
[16:29:02]: ▸ Compiling SDCAlertCollectionViewCell.m
[16:29:02]: ▸ Compiling SDCAlertController.m
[16:29:02]: ▸ Compiling SDCAlertControllerCollectionViewFlowLayout.m
[16:29:02]: ▸ Compiling SDCAlertControllerDefaultVisualStyle.m
[16:29:02]: ▸ Compiling SDCAlertControllerScrollView.m
[16:29:02]: ▸ Compiling SDCAlertControllerTextFieldViewController.m
[16:29:02]: ▸ Compiling SDCAlertControllerTransition.m
[16:29:02]: ▸ Compiling SDCAlertControllerView.m
[16:29:02]: ▸ Compiling SDCAlertLabel.m
[16:29:02]: ▸ Compiling SDCAlertPresentationController.m
[16:29:02]: ▸ Compiling SDCAlertTextFieldTableViewCell.m
[16:29:02]: ▸ Compiling SDCAlertView-dummy.m
[16:29:02]: ▸ Compiling SDCAlertView.m
[16:29:02]: ▸ Compiling SDCAlertViewBackgroundView.m
[16:29:02]: ▸ Compiling SDCAlertViewContentView.m
[16:29:02]: ▸ Compiling SDCAlertViewController.m
[16:29:02]: ▸ Compiling SDCAlertViewCoordinator.m
[16:29:02]: ▸ Compiling SDCIntrinsicallySizedView.m
[16:29:02]: ▸ Compiling UIView+Parallax.m
[16:29:02]: ▸ Compiling UIViewController+Current.m
[16:29:02]: ▸ Compiling SDCAlertView_vers.c
[16:29:02]: ▸ Linking SDCAlertView
[16:29:02]: ▸ Copying SDCAlertCollectionViewCell.h
[16:29:02]: ▸ Copying SDCAlertController.h
[16:29:02]: ▸ Copying SDCAlertControllerCollectionViewFlowLayout.h
[16:29:02]: ▸ Copying SDCAlertControllerDefaultVisualStyle.h
[16:29:02]: ▸ Copying SDCAlertControllerScrollView.h
[16:29:02]: ▸ Copying SDCAlertControllerTextFieldViewController.h
[16:29:02]: ▸ Copying SDCAlertControllerTransition.h
[16:29:02]: ▸ Copying SDCAlertControllerView.h
[16:29:02]: ▸ Copying SDCAlertControllerVisualStyle.h
[16:29:02]: ▸ Copying SDCAlertLabel.h
[16:29:02]: ▸ Copying SDCAlertPresentationController.h
[16:29:02]: ▸ Copying SDCAlertTextFieldTableViewCell.h
[16:29:02]: ▸ Copying SDCAlertView-umbrella.h
[16:29:02]: ▸ Copying SDCAlertView.h
[16:29:02]: ▸ Copying SDCAlertViewBackgroundView.h
[16:29:02]: ▸ Copying SDCAlertViewContentView.h
[16:29:02]: ▸ Copying SDCAlertViewController.h
[16:29:02]: ▸ Copying SDCAlertViewCoordinator.h
[16:29:02]: ▸ Copying SDCAlertViewTransitioning.h
[16:29:02]: ▸ Copying SDCIntrinsicallySizedView.h
[16:29:02]: ▸ Copying UIView+Parallax.h
[16:29:02]: ▸ Copying UIViewController+Current.h
[16:29:02]: Running Tests: ▸ Touching SDCAlertView.framework
[16:29:02]: ▸ Building Pods/SVProgressHUD [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling SVIndefiniteAnimatedView.m
[16:29:02]: ▸ Compiling SVProgressAnimatedView.m
[16:29:02]: ▸ Compiling SVProgressHUD-dummy.m
[16:29:02]: ▸ Compiling SVProgressHUD.m
[16:29:02]: ▸ Compiling SVRadialGradientLayer.m
[16:29:02]: ▸ Compiling SVProgressHUD_vers.c
[16:29:02]: ▸ Linking SVProgressHUD
[16:29:02]: ▸ Copying SVIndefiniteAnimatedView.h
[16:29:02]: ▸ Copying SVProgressAnimatedView.h
[16:29:02]: ▸ Copying SVProgressHUD-umbrella.h
[16:29:02]: ▸ Copying SVProgressHUD.h
[16:29:02]: ▸ Copying SVRadialGradientLayer.h
[16:29:02]: ▸ Copying SVProgressHUD/SVProgressHUD/SVProgressHUD.bundle
[16:29:02]: Running Tests: ▸ Touching SVProgressHUD.framework
[16:29:02]: ▸ Building Pods/SimpleKeychain [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling A0SimpleKeychain+KeyPair.m
[16:29:02]: ▸ Compiling A0SimpleKeychain.m
[16:29:02]: ▸ Compiling SimpleKeychain-dummy.m
[16:29:02]: ▸ Compiling SimpleKeychain_vers.c
[16:29:02]: ▸ Linking SimpleKeychain
[16:29:02]: ▸ Copying A0SimpleKeychain+KeyPair.h
[16:29:02]: ▸ Copying A0SimpleKeychain.h
[16:29:02]: ▸ Copying SimpleKeychain-umbrella.h
[16:29:02]: ▸ Copying SimpleKeychain.h
[16:29:02]: Running Tests: ▸ Touching SimpleKeychain.framework
[16:29:02]: ▸ Building Pods/SwiftMessages-SwiftMessages [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Compiling CardView.xib
[16:29:02]: ▸ Compiling CenteredView.xib
[16:29:02]: ▸ Compiling MessageView.xib
[16:29:02]: ▸ Compiling MessageViewIOS8.xib
[16:29:02]: ▸ Compiling StatusLine.xib
[16:29:02]: ▸ Compiling TabView.xib
[16:29:02]: ▸ Processing ResourceBundle-SwiftMessages-Info.plist
[16:29:02]: Running Tests: ▸ Touching SwiftMessages.bundle
[16:29:02]: ▸ Building Pods/TPKeyboardAvoiding [Debug]
[16:29:02]: ▸ Check Dependencies
[16:29:02]: ▸ Processing Info.plist
[16:29:02]: ▸ Compiling TPKeyboardAvoiding-dummy.m
[16:29:02]: ▸ Compiling TPKeyboardAvoidingCollectionView.m
[16:29:02]: ▸ Compiling TPKeyboardAvoidingScrollView.m
[16:29:02]: ▸ Compiling TPKeyboardAvoidingTableView.m
[16:29:02]: ▸ Compiling UIScrollView+TPKeyboardAvoidingAdditions.m
[16:29:02]: ▸ Compiling TPKeyboardAvoiding_vers.c
[16:29:02]: ▸ Linking TPKeyboardAvoiding
[16:29:02]: ▸ Copying TPKeyboardAvoiding-umbrella.h
[16:29:02]: ▸ Copying TPKeyboardAvoidingCollectionView.h
[16:29:02]: ▸ Copying TPKeyboardAvoidingScrollView.h
[16:29:02]: ▸ Copying TPKeyboardAvoidingTableView.h
[16:29:02]: ▸ Copying UIScrollView+TPKeyboardAvoidingAdditions.h
[16:29:05]: Running Tests: ▸ Touching TPKeyboardAvoiding.framework
[16:29:05]: ▸ Building Pods/UIScrollView-InfiniteScroll [Debug]
[16:29:05]: ▸ Check Dependencies
[16:29:05]: ▸ Processing Info.plist
[16:29:05]: ▸ Compiling UIScrollView+InfiniteScroll.m
[16:29:05]: ▸ Compiling UIScrollView-InfiniteScroll-dummy.m
[16:29:06]: ▸ Compiling UIScrollView_InfiniteScroll_vers.c
[16:29:06]: ▸ Linking UIScrollView_InfiniteScroll
[16:29:06]: ▸ Copying UIScrollView+InfiniteScroll.h
[16:29:06]: ▸ Copying UIScrollView-InfiniteScroll-umbrella.h
[16:29:06]: Running Tests: ▸ Touching UIScrollView_InfiniteScroll.framework
[16:29:06]: ▸ Building Pods/SwiftMessages [Debug]
[16:29:06]: ▸ Check Dependencies
[16:29:06]: ▸ Processing Info.plist
[16:29:06]: ▸ Compiling AccessibleMessage.swift
[16:29:06]: ▸ Compiling Animator.swift
[16:29:06]: ▸ Compiling Array+Utils.swift
[16:29:06]: ▸ Compiling BackgroundViewable.swift
[16:29:06]: ▸ Compiling BaseView.swift
[16:29:06]: ▸ Compiling Error.swift
[16:29:06]: ▸ Compiling Identifiable.swift
[16:29:06]: ▸ Compiling MarginAdjustable+Animation.swift
[16:29:06]: ▸ Compiling MarginAdjustable.swift
[16:29:06]: ▸ Compiling MaskingView.swift
[16:29:06]: ▸ Compiling MessageView.swift
[16:29:06]: ▸ Compiling NSBundle+Utils.swift
[16:29:06]: ▸ Compiling PassthroughView.swift
[16:29:06]: ▸ Compiling PassthroughWindow.swift
[16:29:06]: ▸ Compiling PhysicsAnimation.swift
[16:29:06]: ▸ Compiling PhysicsPanHandler.swift
[16:29:06]: ▸ Compiling Presenter.swift
[16:29:06]: ▸ Compiling SwiftMessages.swift
[16:29:06]: ▸ Compiling Theme.swift
[16:29:06]: ▸ Compiling TopBottomAnimation.swift
[16:29:06]: ▸ Compiling UIViewController+Utils.swift
[16:29:06]: ▸ Compiling Weak.swift
[16:29:06]: ▸ Compiling WindowViewController.swift
[16:29:06]: ▸ Compiling SwiftMessages-dummy.m
[16:29:06]: ▸ Compiling SwiftMessages_vers.c
[16:29:06]: ▸ Linking SwiftMessages
[16:29:06]: ▸ Copying /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/SwiftMessages/SwiftMessages.bundle
[16:29:06]: ▸ Copying SwiftMessages-umbrella.h
[16:29:06]: Running Tests: ▸ Touching SwiftMessages.framework
[16:29:06]: ▸ Building Pods/RealmSwift [Debug]
[16:29:06]: ▸ Check Dependencies
[16:29:06]: ▸ Processing Info.plist
[16:29:06]: ▸ Compiling Aliases.swift
[16:29:07]: ▸ Compiling Error.swift
[16:29:07]: ▸ Compiling LinkingObjects.swift
[16:29:07]: ▸ Compiling List.swift
[16:29:08]: ▸ Compiling Migration.swift
[16:29:08]: ▸ Compiling Object.swift
[16:29:08]: ▸ Compiling ObjectiveCSupport.swift
[16:29:08]: ▸ Compiling ObjectSchema.swift
[16:29:08]: ▸ Compiling Optional.swift
[16:29:08]: ▸ Compiling Property.swift
[16:29:08]: ▸ Compiling Realm.swift
[16:29:09]: ▸ Compiling RealmCollection.swift
[16:29:09]: ▸ Compiling RealmConfiguration.swift
[16:29:09]: ▸ Compiling Results.swift
[16:29:09]: ▸ Compiling Schema.swift
[16:29:09]: ▸ Compiling SortDescriptor.swift
[16:29:09]: ▸ Compiling SwiftVersion.swift
[16:29:09]: ▸ Compiling Sync.swift
[16:29:10]: ▸ Compiling ThreadSafeReference.swift
[16:29:10]: ▸ Compiling Util.swift
[16:29:11]: ▸ Compiling RealmSwift-dummy.m
[16:29:11]: ▸ Compiling RealmSwift_vers.c
[16:29:11]: ▸ Linking RealmSwift
[16:29:11]: ▸ Copying RealmSwift-umbrella.h
[16:29:11]: Running Tests: ▸ Touching RealmSwift.framework
[16:29:11]: ▸ Building Pods/UITextView+Placeholder [Debug]
[16:29:11]: ▸ Check Dependencies
[16:29:11]: ▸ Processing Info.plist
[16:29:11]: ▸ Compiling UITextView+Placeholder-dummy.m
[16:29:11]: ▸ Compiling UITextView+Placeholder.m
[16:29:11]: ▸ Compiling UITextView_Placeholder_vers.c
[16:29:11]: ▸ Linking UITextView_Placeholder
[16:29:11]: ▸ Copying UITextView+Placeholder-umbrella.h
[16:29:11]: ▸ Copying UITextView+Placeholder.h
[16:29:11]: Running Tests: ▸ Touching UITextView_Placeholder.framework
[16:29:11]: ▸ Building Pods/nanopb [Debug]
[16:29:11]: ▸ Check Dependencies
[16:29:11]: ▸ Processing Info.plist
[16:29:11]: ▸ Compiling pb_common.c
[16:29:11]: ▸ Compiling pb_encode.c
[16:29:11]: ▸ Compiling pb_decode.c
[16:29:11]: ▸ Compiling nanopb-dummy.m
[16:29:11]: ▸ Compiling nanopb_vers.c
[16:29:11]: ▸ Linking nanopb
[16:29:11]: ▸ Copying nanopb-umbrella.h
[16:29:11]: ▸ Copying pb.h
[16:29:11]: ▸ Copying pb_common.h
[16:29:11]: ▸ Copying pb_decode.h
[16:29:11]: ▸ Copying pb_encode.h
[16:29:11]: Running Tests: ▸ Touching nanopb.framework
[16:29:11]: ▸ Building Pods/ObjectMapper+Realm [Debug]
[16:29:11]: ▸ Check Dependencies
[16:29:11]: ▸ Processing Info.plist
[16:29:11]: ▸ Compiling ListTransform.swift
[16:29:12]: ▸ Compiling ObjectMapper+Realm-dummy.m
[16:29:12]: ▸ Compiling ObjectMapper_Realm_vers.c
[16:29:12]: ▸ Linking ObjectMapper_Realm
[16:29:12]: ▸ Copying ObjectMapper+Realm-umbrella.h
[16:29:12]: Running Tests: ▸ Touching ObjectMapper_Realm.framework
[16:29:12]: ▸ Building Pods/Pods-caronae-ios-Caronae [Debug]
[16:29:12]: ▸ Check Dependencies
[16:29:12]: ▸ Processing Info.plist
[16:29:12]: ▸ Compiling Pods-caronae-ios-Caronae-dummy.m
[16:29:13]: ▸ Compiling Pods_caronae_ios_Caronae_vers.c
[16:29:13]: ▸ Copying Pods-caronae-ios-Caronae-umbrella.h
[16:29:13]: Running Tests: ▸ Touching Pods_caronae_ios_Caronae.framework
[16:29:13]: ▸ Building Caronae/Caronae [Debug]
[16:29:13]: ▸ Check Dependencies
[16:29:13]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:29:13]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:29:17]: ▸ Compiling UserService.swift
[16:29:24]: ▸ Compiling NotificationService.swift
[16:29:24]: ▸ Compiling RidesHistoryViewController.swift
[16:29:24]: ▸ ⚠️  /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/AFNetworking/AFNetworking.framework/Headers/AFNetworkReachabilityManager.h:115:1: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
[16:29:24]: ▸ - (nullable instancetype)init NS_UNAVAILABLE;
[16:29:24]: ▸             ^
[16:29:24]: ▸ Compiling NotificationParser.swift
[16:29:24]: ▸ Compiling AppDelegate.swift
[16:29:24]: ▸ Compiling Ride.swift
[16:29:24]: ▸ Compiling AppDelegate+Notifications.swift
[16:29:24]: ▸ Compiling FalaeViewController.swift
[16:29:24]: ▸ Compiling HubsSelectionViewController.swift
[16:29:24]: ▸ Compiling Date+isInTheFuture.swift
[16:29:24]: ▸ Compiling AppDelegate+Realm.swift
[16:29:24]: ▸ Compiling String+onlyDigits.swift
[16:29:25]: ▸ Compiling Place.swift
[16:29:25]: ▸ Compiling RideListController.swift
[16:29:25]: ▸ Compiling CaronaeAPIHTTPSessionManager.swift
[16:29:25]: ▸ Compiling Message.swift
[16:29:25]: ▸ Compiling RideCell.swift
[16:29:25]: ▸ Compiling SelectionCell.swift
[16:29:25]: ▸ Compiling Campus.swift
[16:29:26]: ▸ Compiling PlaceService.swift
[16:29:26]: ▸ Compiling Date+nextHour.swift
[16:29:26]: ▸ Compiling FilterParameters.swift
[16:29:26]: ▸ Compiling AllRidesViewController.swift
[16:29:27]: ▸ Compiling DateTimeTransform.swift
[16:29:27]: ▸ Compiling PhoneNumberActionSheet.swift
[16:29:27]: ▸ Compiling CaronaeMessageNotification.swift
[16:29:27]: ▸ Compiling CaronaeGradientButton.swift
[16:29:27]: ▸ Compiling UIColor+hex.swift
[16:29:27]: ▸ Compiling CaronaeAPIRequestSerializer.swift
[16:29:27]: ▸ Compiling ProfileViewController.swift
[16:29:28]: ▸ Compiling CaronaeConstants.swift
[16:29:28]: ▸ Compiling MenuViewController.swift
[16:29:28]: ▸ Compiling PaginationState.swift
[16:29:28]: ▸ Compiling ChatService.swift
[16:29:28]: ▸ Compiling WelcomeViewController.swift
[16:29:28]: ▸ Compiling FilterRideViewController.swift
[16:29:28]: ▸ Compiling MyRidesViewController.swift
[16:29:29]: ▸ Compiling RideService.swift
[16:29:29]: ▸ Compiling SearchResultsViewController.swift
[16:29:29]: ▸ Compiling LoginViewController.swift
[16:29:29]: ▸ Compiling CaronaeError.swift
[16:29:29]: ▸ Compiling RideViewController+rideActions.swift
[16:29:30]: ▸ Compiling SearchRideViewController.swift
[16:29:30]: ▸ Compiling UniversalLinkParser.swift
[16:29:30]: ▸ Compiling CaronaeAPIResponseSerializer.swift
[16:29:30]: ▸ Compiling NeighborhoodSelectionViewController.swift
[16:29:30]: ▸ Compiling EditProfileViewController.swift
[16:29:31]: ▸ Compiling UIViewController+isVisible.swift
[16:29:31]: ▸ Compiling User.swift
[16:29:31]: ▸ Compiling RideViewController.swift
[16:29:32]: ▸ Compiling SelectionViewController.swift
[16:29:32]: ▸ Compiling String+validation.swift
[16:29:32]: ▸ Compiling WebViewController.swift
[16:29:32]: ▸ Compiling DeepLinkManager.swift
[16:29:32]: ▸ Compiling Notification.swift
[16:29:32]: ▸ Compiling DeeplinkNavigator.swift
[16:29:32]: ▸ Compiling AppDelegate+Firebase.swift
[16:29:32]: ▸ Compiling CreateRideViewController.swift
[16:29:33]: ▸ Compiling Zone.swift
[16:29:33]: ▸ Compiling Array+compactString.swift
[16:29:33]: ▸ Compiling AuthenticationController.swift
[16:29:33]: ▸ Compiling UIColor+Caronae.swift
[16:29:33]: ▸ Compiling String+capitalizedAfter.swift
[16:29:33]: ▸ Compiling ZoneSelectionInputViewController.swift
[16:29:34]: ▸ Compiling ChatViewController.swift
[16:29:34]: ▸ Compiling FalaeService.swift
[16:29:34]: ▸ Compiling RiderCell.swift
[16:29:35]: ▸ Compiling JoinRequestCell.m
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:29:41]: ▸ ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:29:41]: ▸                                                            ^
[16:29:41]: ▸ Compiling TabBarController.m
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:29:41]: ▸                                                                                                       ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:29:41]: ▸                                                                                                       ^
[16:29:41]: ▸ Compiling UIImageView+crn_setImageWithURL.m
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:29:41]: ▸                                                            ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:29:41]: ▸                                                            ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.m:13:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler {
[16:29:41]: ▸                                                                                                       ^
[16:29:41]: ▸ Compiling CaronaeAlertController.m
[16:29:41]: ▸ ⚠️  /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/SDCAlertView/SDCAlertView.framework/Headers/SDCAlertView.h:92:54: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ @property (nonatomic, copy) void (^didPresentHandler)();
[16:29:41]: ▸                                                            ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:29:41]: ▸                                                      ^
[16:29:41]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.m:19:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:29:41]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler {
[16:29:41]: ▸                                                                                                       ^
[16:29:41]: ▸ Compiling CALayer+UIColor.m
[16:29:41]: ▸ Compiling UIApplication+topViewController.m
[16:29:41]: ▸ Compiling CaronaeTextField.m
[16:29:41]: ▸ Compiling UIWindow+replaceRootViewController.m
[16:29:41]: ▸ Linking Caronae
[16:29:41]: ▸ Copying GoogleService-Info.plist
[16:29:41]: ▸ Compiling ZoneSelectionInput.xib
[16:29:41]: ▸ Compiling WelcomeViewController.xib
[16:29:41]: ▸ Compiling RideCell.xib
[16:29:41]: ▸ Compiling SelectionCell.xib
[16:29:41]: ▸ Compiling RideListController.xib
[16:29:41]: ▸ Copying Caronae/Sounds/beep_beep.wav
[16:29:41]: ▸ Copying Settings.bundle
[16:29:41]: ▸ Compiling JoinRequestCell.xib
[16:29:41]: ▸ Copying Caronae/Sounds/beep.wav
[16:29:41]: ▸ Compiling Login.storyboard
[16:29:42]: ▸ Compiling Main.storyboard
[16:29:51]: ▸ Compiling LaunchScreen.storyboard
[16:29:51]: ▸ Processing Info.plist
[16:29:51]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:29:57]: Running Tests: ▸ Touching Caronae.app
[16:29:57]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/Caronae.app
[16:29:57]: ▸ Build Succeeded
[16:29:58]: ▸ Building Pods/ActionSheetPicker-3.0 [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/Bolts [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/GoogleToolboxForMac [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/AFNetworking [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/InputMask [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/JSQSystemSoundPlayer [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/MIBadgeButton-Swift [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/JSQMessagesViewController [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/FBSDKCoreKit [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/ObjectMapper [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:58]: ▸ Building Pods/Realm [Debug]
[16:29:58]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/Protobuf [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/RBBAnimation [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SDCAutoLayout [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SDWebImage [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/FBSDKLoginKit [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SDCAlertView [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SVProgressHUD [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SimpleKeychain [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SwiftMessages-SwiftMessages [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/UIScrollView-InfiniteScroll [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/TPKeyboardAvoiding [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/UITextView+Placeholder [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/nanopb [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/RealmSwift [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/SwiftMessages [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/ObjectMapper+Realm [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Pods/Pods-caronae-ios-Caronae [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Building Caronae/Caronae [Debug]
[16:29:59]: ▸ Check Dependencies
[16:29:59]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:29:59]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:30:01]: ▸ Processing Info.plist
[16:30:01]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:30:06]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/Caronae.app
[16:30:07]: ▸ Build Succeeded
[16:30:07]: ▸ Building Pods/AFNetworking [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/ActionSheetPicker-3.0 [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/Bolts [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/GoogleToolboxForMac [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/InputMask [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/JSQSystemSoundPlayer [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:07]: ▸ Building Pods/JSQMessagesViewController [Debug]
[16:30:07]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/MIBadgeButton-Swift [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/FBSDKCoreKit [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/ObjectMapper [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/Realm [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/Protobuf [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/RBBAnimation [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SDCAutoLayout [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SDWebImage [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SDCAlertView [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SVProgressHUD [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SimpleKeychain [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SwiftMessages-SwiftMessages [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/TPKeyboardAvoiding [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/FBSDKLoginKit [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/UIScrollView-InfiniteScroll [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/UITextView+Placeholder [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/nanopb [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/SwiftMessages [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/RealmSwift [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/ObjectMapper+Realm [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Pods/Pods-caronae-ios-Caronae [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Building Caronae/Caronae [Debug]
[16:30:08]: ▸ Check Dependencies
[16:30:08]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:30:08]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:30:11]: ▸ Processing Info.plist
[16:30:11]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:30:15]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/Caronae.app
[16:30:16]: ▸ Build Succeeded
[16:30:16]: ▸ 2018-04-24 16:30:16.931 xcodebuild[3081:19027]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[16:30:16]: ▸ /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/com.apple.dt.XCTest/IDETestRunSession-A723FE1D-7AF0-4959-9B8F-4E0E196FA89A/Caronae UITests-2E5C169C-E9F2-401A-B3B0-48A5C7879DD4/Session-Caronae UITests-2018-04-24_163016-tgEfWC.log
[16:30:16]: ▸ 2018-04-24 16:30:16.932 xcodebuild[3081:12762] [MT] IDETestOperationsObserverDebug: (DC19E038-4909-4259-AADE-E21672ED1020) Beginning test session Caronae UITests-DC19E038-4909-4259-AADE-E21672ED1020 at 2018-04-24 16:30:16.931 with Xcode 9E145 on target <DVTiPhoneSimulator: 0x7f92791e0870> {
[16:30:16]: ▸ SimDevice: iPhone X (45ED451F-8183-4FFD-824E-B86E434B4736, iOS 11.3, Booted)
[16:30:16]: ▸ } (11.3 (15E217))
[16:30:17]: ▸ 2018-04-24 16:30:17.392 xcodebuild[3081:20257]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[16:30:17]: ▸ /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/com.apple.dt.XCTest/IDETestRunSession-79E5781B-5C97-42E0-8239-0F1953D3D8C4/Caronae UITests-DEF4A027-148B-4B30-A554-E6B9B382A2CF/Session-Caronae UITests-2018-04-24_163017-gdFNx6.log
[16:30:17]: ▸ 2018-04-24 16:30:17.393 xcodebuild[3081:12762] [MT] IDETestOperationsObserverDebug: (07410547-ABD5-45AD-A515-DD4AEEB05203) Beginning test session Caronae UITests-07410547-ABD5-45AD-A515-DD4AEEB05203 at 2018-04-24 16:30:17.393 with Xcode 9E145 on target <DVTiPhoneSimulator: 0x7f92797e9c50> {
[16:30:17]: ▸ SimDevice: iPhone 8 (48DBE045-D033-4F59-AB6B-927CC5E716CF, iOS 11.3, Shutdown)
[16:30:17]: ▸ } (11.3 (15E217))
[16:30:17]: ▸ 2018-04-24 16:30:17.552 xcodebuild[3081:12768]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[16:30:17]: ▸ /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/com.apple.dt.XCTest/IDETestRunSession-3F9B9824-2B78-4ADA-8BC5-7D948CEFE994/Caronae UITests-27DA136B-2883-4CF5-A925-77D66298C7C1/Session-Caronae UITests-2018-04-24_163017-2XjLcs.log
[16:30:17]: ▸ 2018-04-24 16:30:17.553 xcodebuild[3081:12762] [MT] IDETestOperationsObserverDebug: (50D03A1F-8019-45BE-9C29-22219CC528A8) Beginning test session Caronae UITests-50D03A1F-8019-45BE-9C29-22219CC528A8 at 2018-04-24 16:30:17.552 with Xcode 9E145 on target <DVTiPhoneSimulator: 0x7f92797f2010> {
[16:30:17]: ▸ SimDevice: iPhone 8 Plus (B49F7272-4946-422D-BC2B-8CBF77CBCBDF, iOS 11.3, Booted)
[16:30:17]: ▸ } (11.3 (15E217))
[16:30:24]: ▸ Building Pods/AFNetworking [Tests]
[16:30:24]: ▸ Check Dependencies
[16:30:26]: ▸ Processing Info.plist
[16:30:36]: ▸ Compiling AFAutoPurgingImageCache.m
[16:30:39]: ▸ Compiling AFHTTPSessionManager.m
[16:30:41]: ▸ Compiling AFImageDownloader.m
[16:30:44]: ▸ Compiling AFNetworkActivityIndicatorManager.m
[16:30:45]: ▸ Compiling AFNetworking-dummy.m
[16:30:45]: ▸ Compiling AFNetworkReachabilityManager.m
[16:30:47]: ▸ Compiling AFSecurityPolicy.m
[16:30:48]: ▸ Compiling AFURLRequestSerialization.m
[16:30:50]: ▸ Compiling AFURLResponseSerialization.m
[16:30:50]: ▸ Compiling AFURLSessionManager.m
[16:30:56]: ▸ Compiling UIActivityIndicatorView+AFNetworking.m
[16:30:56]: ▸ Compiling UIButton+AFNetworking.m
[16:30:56]: ▸ Compiling UIImageView+AFNetworking.m
[16:30:56]: ▸ Compiling UIProgressView+AFNetworking.m
[16:30:57]: ▸ Compiling UIRefreshControl+AFNetworking.m
[16:30:57]: ▸ Compiling UIWebView+AFNetworking.m
[16:30:58]: ▸ Compiling AFNetworking_vers.c
[16:30:58]: ▸ Compiling AFAutoPurgingImageCache.m
[16:30:58]: ▸ Compiling AFHTTPSessionManager.m
[16:30:59]: ▸ Compiling AFImageDownloader.m
[16:31:00]: ▸ Compiling AFNetworkActivityIndicatorManager.m
[16:31:00]: ▸ Compiling AFNetworking-dummy.m
[16:31:00]: ▸ Compiling AFNetworkReachabilityManager.m
[16:31:00]: ▸ Compiling AFSecurityPolicy.m
[16:31:00]: ▸ Compiling AFURLRequestSerialization.m
[16:31:03]: ▸ Compiling AFURLResponseSerialization.m
[16:31:03]: ▸ Compiling AFURLSessionManager.m
[16:31:03]: ▸ Compiling UIActivityIndicatorView+AFNetworking.m
[16:31:03]: ▸ Compiling UIButton+AFNetworking.m
[16:31:03]: ▸ Compiling UIImageView+AFNetworking.m
[16:31:03]: ▸ Compiling UIProgressView+AFNetworking.m
[16:31:04]: ▸ Compiling UIRefreshControl+AFNetworking.m
[16:31:04]: ▸ Compiling UIWebView+AFNetworking.m
[16:31:05]: ▸ Compiling AFNetworking_vers.c
[16:31:05]: ▸ Linking AFNetworking
[16:31:05]: ▸ Linking AFNetworking
[16:31:07]: ▸ Generating 'AFNetworking.framework.dSYM'
[16:31:07]: ▸ Copying AFAutoPurgingImageCache.h
[16:31:07]: ▸ Copying AFHTTPSessionManager.h
[16:31:07]: ▸ Copying AFImageDownloader.h
[16:31:07]: ▸ Copying AFNetworkActivityIndicatorManager.h
[16:31:07]: ▸ Copying AFNetworking-umbrella.h
[16:31:07]: ▸ Copying AFNetworking.h
[16:31:07]: ▸ Copying AFNetworkReachabilityManager.h
[16:31:07]: ▸ Copying AFSecurityPolicy.h
[16:31:07]: ▸ Copying AFURLRequestSerialization.h
[16:31:07]: ▸ Copying AFURLResponseSerialization.h
[16:31:07]: ▸ Copying AFURLSessionManager.h
[16:31:07]: ▸ Copying UIActivityIndicatorView+AFNetworking.h
[16:31:07]: ▸ Copying UIButton+AFNetworking.h
[16:31:07]: ▸ Copying UIImage+AFNetworking.h
[16:31:07]: ▸ Copying UIImageView+AFNetworking.h
[16:31:07]: ▸ Copying UIKit+AFNetworking.h
[16:31:07]: ▸ Copying UIProgressView+AFNetworking.h
[16:31:08]: ▸ Copying UIRefreshControl+AFNetworking.h
[16:31:08]: ▸ Copying UIWebView+AFNetworking.h
[16:31:08]: Running Tests: ▸ Touching AFNetworking.framework
[16:31:08]: ▸ Building Pods/ActionSheetPicker-3.0 [Tests]
[16:31:08]: ▸ Check Dependencies
[16:31:08]: ▸ Processing Info.plist
[16:31:08]: ▸ Compiling AbstractActionSheetPicker.m
[16:31:08]: ▸ Compiling ActionSheetCustomPicker.m
[16:31:08]: ▸ Compiling ActionSheetDatePicker.m
[16:31:08]: ▸ Compiling ActionSheetLocalePicker.m
[16:31:08]: ▸ Compiling ActionSheetMultipleStringPicker.m
[16:31:08]: ▸ Compiling ActionSheetDistancePicker.m
[16:31:08]: ▸ Compiling ActionSheetPicker-3.0-dummy.m
[16:31:08]: ▸ Compiling ActionSheetStringPicker.m
[16:31:08]: ▸ Compiling DistancePickerView.m
[16:31:08]: ▸ Compiling SWActionSheet.m
[16:31:08]: ▸ Compiling ActionSheetPicker_3_0_vers.c
[16:31:08]: ▸ Compiling AbstractActionSheetPicker.m
[16:31:08]: ▸ Compiling ActionSheetCustomPicker.m
[16:31:08]: ▸ Compiling ActionSheetDatePicker.m
[16:31:08]: ▸ Compiling ActionSheetDistancePicker.m
[16:31:08]: ▸ Compiling ActionSheetLocalePicker.m
[16:31:08]: ▸ Compiling ActionSheetMultipleStringPicker.m
[16:31:08]: ▸ Compiling ActionSheetPicker-3.0-dummy.m
[16:31:08]: ▸ Compiling ActionSheetStringPicker.m
[16:31:08]: ▸ Compiling DistancePickerView.m
[16:31:08]: ▸ Compiling SWActionSheet.m
[16:31:08]: ▸ Compiling ActionSheetPicker_3_0_vers.c
[16:31:08]: ▸ Linking ActionSheetPicker_3_0
[16:31:08]: ▸ Linking ActionSheetPicker_3_0
[16:31:08]: ▸ Generating 'ActionSheetPicker_3_0.framework.dSYM'
[16:31:08]: ▸ Copying AbstractActionSheetPicker.h
[16:31:08]: ▸ Copying ActionSheetCustomPicker.h
[16:31:08]: ▸ Copying ActionSheetCustomPickerDelegate.h
[16:31:08]: ▸ Copying ActionSheetDatePicker.h
[16:31:08]: ▸ Copying ActionSheetDistancePicker.h
[16:31:08]: ▸ Copying ActionSheetLocalePicker.h
[16:31:08]: ▸ Copying ActionSheetMultipleStringPicker.h
[16:31:08]: ▸ Copying ActionSheetPicker-3.0-umbrella.h
[16:31:08]: ▸ Copying ActionSheetPicker.h
[16:31:08]: ▸ Copying ActionSheetStringPicker.h
[16:31:08]: ▸ Copying DistancePickerView.h
[16:31:08]: ▸ Copying SWActionSheet.h
[16:31:08]: Running Tests: ▸ Touching ActionSheetPicker_3_0.framework
[16:31:08]: ▸ Building Pods/Bolts [Tests]
[16:31:08]: ▸ Check Dependencies
[16:31:08]: ▸ Processing Info.plist
[16:31:08]: ▸ Compiling BFAppLink.m
[16:31:08]: ▸ Compiling BFAppLinkNavigation.m
[16:31:08]: ▸ Compiling BFAppLinkReturnToRefererController.m
[16:31:08]: ▸ Compiling BFAppLinkReturnToRefererView.m
[16:31:08]: ▸ Compiling BFAppLinkTarget.m
[16:31:08]: ▸ Compiling BFCancellationToken.m
[16:31:08]: ▸ Compiling BFCancellationTokenRegistration.m
[16:31:08]: ▸ Compiling BFCancellationTokenSource.m
[16:31:08]: ▸ Compiling BFExecutor.m
[16:31:08]: ▸ Compiling BFMeasurementEvent.m
[16:31:08]: ▸ Compiling BFTask.m
[16:31:08]: ▸ Compiling BFTaskCompletionSource.m
[16:31:08]: ▸ Compiling BFURL.m
[16:31:08]: ▸ Compiling BFWebViewAppLinkResolver.m
[16:31:08]: ▸ Compiling Bolts-dummy.m
[16:31:08]: ▸ Compiling Bolts.m
[16:31:08]: ▸ Compiling Bolts_vers.c
[16:31:08]: ▸ Compiling BFAppLink.m
[16:31:08]: ▸ Compiling BFAppLinkNavigation.m
[16:31:08]: ▸ Compiling BFAppLinkReturnToRefererController.m
[16:31:08]: ▸ Compiling BFAppLinkReturnToRefererView.m
[16:31:08]: ▸ Compiling BFAppLinkTarget.m
[16:31:08]: ▸ Compiling BFCancellationToken.m
[16:31:08]: ▸ Compiling BFCancellationTokenRegistration.m
[16:31:08]: ▸ Compiling BFCancellationTokenSource.m
[16:31:08]: ▸ Compiling BFExecutor.m
[16:31:08]: ▸ Compiling BFMeasurementEvent.m
[16:31:08]: ▸ Compiling BFTask.m
[16:31:08]: ▸ Compiling BFTaskCompletionSource.m
[16:31:08]: ▸ Compiling BFURL.m
[16:31:08]: ▸ Compiling BFWebViewAppLinkResolver.m
[16:31:08]: ▸ Compiling Bolts-dummy.m
[16:31:08]: ▸ Compiling Bolts.m
[16:31:08]: ▸ Compiling Bolts_vers.c
[16:31:08]: ▸ Linking Bolts
[16:31:08]: ▸ Linking Bolts
[16:31:08]: ▸ Generating 'Bolts.framework.dSYM'
[16:31:08]: ▸ Copying BFAppLink.h
[16:31:08]: ▸ Copying BFAppLinkNavigation.h
[16:31:08]: ▸ Copying BFAppLinkResolving.h
[16:31:08]: ▸ Copying BFAppLinkReturnToRefererController.h
[16:31:08]: ▸ Copying BFAppLinkReturnToRefererView.h
[16:31:08]: ▸ Copying BFAppLinkTarget.h
[16:31:08]: ▸ Copying BFCancellationToken.h
[16:31:08]: ▸ Copying BFCancellationTokenRegistration.h
[16:31:08]: ▸ Copying BFCancellationTokenSource.h
[16:31:08]: ▸ Copying BFExecutor.h
[16:31:08]: ▸ Copying BFGeneric.h
[16:31:08]: ▸ Copying BFMeasurementEvent.h
[16:31:08]: ▸ Copying BFTask.h
[16:31:08]: ▸ Copying BFTaskCompletionSource.h
[16:31:08]: ▸ Copying BFURL.h
[16:31:08]: ▸ Copying BFWebViewAppLinkResolver.h
[16:31:08]: ▸ Copying Bolts-umbrella.h
[16:31:08]: ▸ Copying Bolts.h
[16:31:08]: Running Tests: ▸ Touching Bolts.framework
[16:31:08]: ▸ Building Pods/GoogleToolboxForMac [Tests]
[16:31:08]: ▸ Check Dependencies
[16:31:08]: ▸ Processing Info.plist
[16:31:08]: ▸ Compiling GoogleToolboxForMac-dummy.m
[16:31:08]: ▸ Compiling GTMLogger.m
[16:31:08]: ▸ Compiling GTMNSData+zlib.m
[16:31:08]: ▸ Compiling GoogleToolboxForMac_vers.c
[16:31:08]: ▸ Compiling GoogleToolboxForMac-dummy.m
[16:31:08]: ▸ Compiling GTMLogger.m
[16:31:08]: ▸ Compiling GTMNSData+zlib.m
[16:31:08]: ▸ Compiling GoogleToolboxForMac_vers.c
[16:31:08]: ▸ Linking GoogleToolboxForMac
[16:31:08]: ▸ Linking GoogleToolboxForMac
[16:31:08]: ▸ Generating 'GoogleToolboxForMac.framework.dSYM'
[16:31:08]: ▸ Copying GoogleToolboxForMac-umbrella.h
[16:31:08]: ▸ Copying GTMDefines.h
[16:31:08]: ▸ Copying GTMLogger.h
[16:31:08]: ▸ Copying GTMNSData+zlib.h
[16:31:08]: Running Tests: ▸ Touching GoogleToolboxForMac.framework
[16:31:08]: ▸ Building Pods/InputMask [Tests]
[16:31:08]: ▸ Check Dependencies
[16:31:08]: ▸ Processing Info.plist
[16:31:47]: ▸ Compiling InputMask-dummy.m
[16:31:47]: ▸ Compiling InputMask_vers.c
[16:31:47]: ▸ Compiling InputMask-dummy.m
[16:31:47]: ▸ Compiling InputMask_vers.c
[16:31:49]: ▸ Linking InputMask
[16:31:49]: ▸ Linking InputMask
[16:31:50]: ▸ Generating 'InputMask.framework.dSYM'
[16:31:51]: ▸ Copying InputMask-umbrella.h
[16:31:51]: ▸ Copying InputMask.h
[16:31:53]: Running Tests: ▸ Touching InputMask.framework
[16:31:53]: ▸ Building Pods/JSQSystemSoundPlayer [Tests]
[16:31:53]: ▸ Check Dependencies
[16:31:53]: ▸ Processing Info.plist
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer-dummy.m
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer.m
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer_vers.c
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer-dummy.m
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer.m
[16:31:53]: ▸ Compiling JSQSystemSoundPlayer_vers.c
[16:31:53]: ▸ Linking JSQSystemSoundPlayer
[16:31:53]: ▸ Linking JSQSystemSoundPlayer
[16:31:53]: ▸ Generating 'JSQSystemSoundPlayer.framework.dSYM'
[16:31:53]: ▸ Copying JSQSystemSoundPlayer.h
[16:31:53]: ▸ Copying JSQSystemSoundPlayer-umbrella.h
[16:31:53]: Running Tests: ▸ Touching JSQSystemSoundPlayer.framework
[16:31:53]: ▸ Building Pods/MIBadgeButton-Swift [Tests]
[16:31:53]: ▸ Check Dependencies
[16:31:53]: ▸ Processing Info.plist
[16:31:53]: ▸ Compiling MIBadgeButton.swift
[16:31:53]: ▸ Compiling MIBadgeButton.swift
[16:31:53]: ▸ Compiling MIBadgeButton-Swift-dummy.m
[16:31:53]: ▸ Compiling MIBadgeButton_Swift_vers.c
[16:31:53]: ▸ Compiling MIBadgeButton-Swift-dummy.m
[16:31:53]: ▸ Compiling MIBadgeButton_Swift_vers.c
[16:31:53]: ▸ Linking MIBadgeButton_Swift
[16:31:53]: ▸ Linking MIBadgeButton_Swift
[16:31:53]: ▸ Generating 'MIBadgeButton_Swift.framework.dSYM'
[16:31:53]: ▸ Copying MIBadgeButton-Swift-umbrella.h
[16:31:53]: Running Tests: ▸ Touching MIBadgeButton_Swift.framework
[16:31:53]: ▸ Building Pods/FBSDKCoreKit [Tests]
[16:31:53]: ▸ Check Dependencies
[16:31:53]: ▸ Processing Info.plist
[16:31:53]: ▸ Compiling _FBSDKTemporaryErrorRecoveryAttempter.m
[16:31:53]: ▸ Compiling FBSDKAccessToken.m
[16:31:53]: ▸ Compiling FBSDKAccessTokenCache.m
[16:31:53]: ▸ Compiling FBSDKAccessTokenCacheV3.m
[16:31:53]: ▸ Compiling FBSDKAccessTokenCacheV3_17.m
[16:31:53]: ▸ Compiling FBSDKAccessTokenCacheV3_21.m
[16:31:53]: ▸ Compiling FBSDKAccessTokenCacheV4.m
[16:31:53]: ▸ Compiling FBSDKAppEvents.m
[16:31:53]: ▸ Compiling FBSDKAppEventsDeviceInfo.m
[16:31:53]: ▸ Compiling FBSDKAppEventsState.m
[16:31:53]: ▸ Compiling FBSDKAppEventsStateManager.m
[16:31:53]: ▸ Compiling FBSDKAppEventsUtility.m
[16:31:53]: ▸ Compiling FBSDKApplicationDelegate.m
[16:31:53]: ▸ Compiling FBSDKAppLinkResolver.m
[16:31:53]: ▸ Compiling FBSDKAppLinkUtility.m
[16:31:53]: ▸ Compiling FBSDKAudioResourceLoader.m
[16:31:53]: ▸ Compiling FBSDKBase64.m
[16:31:53]: ▸ Compiling FBSDKBoltsMeasurementEventListener.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPICrypto.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPIProtocolNativeV1.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPIProtocolWebV1.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPIProtocolWebV2.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPIRequest.m
[16:31:53]: ▸ Compiling FBSDKBridgeAPIResponse.m
[16:31:53]: ▸ Compiling FBSDKButton.m
[16:31:53]: ▸ Compiling FBSDKCloseIcon.m
[16:31:53]: ▸ Compiling FBSDKColor.m
[16:31:53]: ▸ Compiling FBSDKConstants.m
[16:31:53]: ▸ Compiling FBSDKContainerViewController.m
[16:31:53]: ▸ Compiling FBSDKCoreKit-dummy.m
[16:31:53]: ▸ Compiling FBSDKCrypto.m
[16:31:53]: ▸ Compiling FBSDKDeviceRequestsHelper.m
[16:31:53]: ▸ Compiling FBSDKDialogConfiguration.m
[16:31:53]: ▸ Compiling FBSDKDynamicFrameworkLoader.m
[16:31:53]: ▸ Compiling FBSDKError.m
[16:31:53]: ▸ Compiling FBSDKErrorConfiguration.m
[16:31:53]: ▸ Compiling FBSDKErrorRecoveryAttempter.m
[16:31:53]: ▸ Compiling FBSDKErrorRecoveryConfiguration.m
[16:31:53]: ▸ Compiling FBSDKGraphErrorRecoveryProcessor.m
[16:31:53]: ▸ Compiling FBSDKGraphRequest.m
[16:31:53]: ▸ Compiling FBSDKGraphRequestBody.m
[16:31:53]: ▸ Compiling FBSDKGraphRequestConnection.m
[16:31:53]: ▸ Compiling FBSDKGraphRequestDataAttachment.m
[16:31:53]: ▸ Compiling FBSDKGraphRequestMetadata.m
[16:31:53]: ▸ Compiling FBSDKGraphRequestPiggybackManager.m
[16:31:53]: ▸ Compiling FBSDKIcon.m
[16:31:53]: ▸ Compiling FBSDKImageDownloader.m
[16:31:53]: ▸ Compiling FBSDKInternalUtility.m
[16:31:53]: ▸ Compiling FBSDKKeychainStore.m
[16:31:53]: ▸ Compiling FBSDKKeychainStoreViaBundleID.m
[16:31:53]: ▸ Compiling FBSDKLogger.m
[16:31:53]: ▸ Compiling FBSDKLogo.m
[16:31:53]: ▸ Compiling FBSDKMaleSilhouetteIcon.m
[16:31:53]: ▸ Compiling FBSDKMath.m
[16:31:53]: ▸ Compiling FBSDKMonotonicTime.m
[16:31:53]: ▸ Compiling FBSDKPaymentObserver.m
[16:31:53]: ▸ Compiling FBSDKProfile.m
[16:31:53]: ▸ Compiling FBSDKProfilePictureView.m
[16:31:53]: ▸ Compiling FBSDKServerConfiguration.m
[16:31:53]: ▸ Compiling FBSDKServerConfigurationManager.m
[16:31:53]: ▸ Compiling FBSDKSettings.m
[16:31:53]: ▸ Compiling FBSDKSystemAccountStoreAdapter.m
[16:31:53]: ▸ Compiling FBSDKTestUsersManager.m
[16:31:53]: ▸ Compiling FBSDKTimeSpentData.m
[16:31:53]: ▸ Compiling FBSDKTriStateBOOL.m
[16:31:53]: ▸ Compiling FBSDKTypeUtility.m
[16:31:53]: ▸ Compiling FBSDKURLConnection.m
[16:31:53]: ▸ Compiling FBSDKURLSessionTask.m
[16:31:54]: ▸ Compiling FBSDKUtility.m
[16:31:54]: ▸ Compiling FBSDKViewImpressionTracker.m
[16:31:54]: ▸ Compiling FBSDKWebDialog.m
[16:31:54]: ▸ Compiling FBSDKWebDialogView.m
[16:31:55]: ▸ Compiling FBSDKCoreKit_vers.c
[16:31:55]: ▸ Compiling _FBSDKTemporaryErrorRecoveryAttempter.m
[16:31:55]: ▸ Compiling FBSDKAccessToken.m
[16:31:55]: ▸ Compiling FBSDKAccessTokenCache.m
[16:31:57]: ▸ Compiling FBSDKAccessTokenCacheV3.m
[16:32:00]: ▸ Compiling FBSDKAccessTokenCacheV3_17.m
[16:32:02]: ▸ Compiling FBSDKAccessTokenCacheV3_21.m
[16:32:04]: ▸ Compiling FBSDKAccessTokenCacheV4.m
[16:32:05]: ▸ Compiling FBSDKAppEvents.m
[16:32:06]: ▸ Compiling FBSDKAppEventsDeviceInfo.m
[16:32:07]: ▸ Compiling FBSDKAppEventsState.m
[16:32:08]: ▸ Compiling FBSDKAppEventsStateManager.m
[16:32:08]: ▸ Compiling FBSDKAppEventsUtility.m
[16:32:10]: ▸ Compiling FBSDKApplicationDelegate.m
[16:32:12]: ▸ Compiling FBSDKAppLinkResolver.m
[16:32:13]: ▸ Compiling FBSDKAppLinkUtility.m
[16:32:15]: ▸ Compiling FBSDKAudioResourceLoader.m
[16:32:17]: ▸ Compiling FBSDKBase64.m
[16:32:18]: ▸ Compiling FBSDKBoltsMeasurementEventListener.m
[16:32:18]: ▸ Compiling FBSDKBridgeAPICrypto.m
[16:32:21]: ▸ Compiling FBSDKBridgeAPIProtocolNativeV1.m
[16:32:22]: ▸ Compiling FBSDKBridgeAPIProtocolWebV1.m
[16:32:24]: ▸ Compiling FBSDKBridgeAPIProtocolWebV2.m
[16:32:32]: ▸ Compiling FBSDKBridgeAPIRequest.m
[16:32:33]: ▸ Compiling FBSDKBridgeAPIResponse.m
[16:32:34]: ▸ Compiling FBSDKButton.m
[16:32:35]: ▸ Compiling FBSDKCloseIcon.m
[16:32:36]: ▸ Compiling FBSDKColor.m
[16:32:41]: ▸ Compiling FBSDKConstants.m
[16:32:41]: ▸ Compiling FBSDKContainerViewController.m
[16:32:41]: ▸ Compiling FBSDKCoreKit-dummy.m
[16:32:42]: ▸ Compiling FBSDKCrypto.m
[16:32:43]: ▸ Compiling FBSDKDeviceRequestsHelper.m
[16:32:45]: ▸ Compiling FBSDKDialogConfiguration.m
[16:32:47]: ▸ Compiling FBSDKDynamicFrameworkLoader.m
[16:32:50]: ▸ Compiling FBSDKError.m
[16:32:50]: ▸ Compiling FBSDKErrorConfiguration.m
[16:32:51]: ▸ Compiling FBSDKErrorRecoveryAttempter.m
[16:32:52]: ▸ Compiling FBSDKErrorRecoveryConfiguration.m
[16:32:54]: ▸ Compiling FBSDKGraphErrorRecoveryProcessor.m
[16:32:56]: ▸ Compiling FBSDKGraphRequest.m
[16:32:57]: ▸ Compiling FBSDKGraphRequestBody.m
[16:32:58]: ▸ Compiling FBSDKGraphRequestConnection.m
[16:32:59]: ▸ Compiling FBSDKGraphRequestDataAttachment.m
[16:33:00]: ▸ Compiling FBSDKGraphRequestMetadata.m
[16:33:02]: ▸ Compiling FBSDKGraphRequestPiggybackManager.m
[16:33:06]: ▸ Compiling FBSDKIcon.m
[16:33:09]: ▸ Compiling FBSDKImageDownloader.m
[16:33:10]: ▸ Compiling FBSDKInternalUtility.m
[16:33:13]: ▸ Compiling FBSDKKeychainStore.m
[16:33:13]: ▸ Compiling FBSDKKeychainStoreViaBundleID.m
[16:33:13]: ▸ Compiling FBSDKLogger.m
[16:33:17]: ▸ Compiling FBSDKLogo.m
[16:33:20]: ▸ Compiling FBSDKMaleSilhouetteIcon.m
[16:33:20]: ▸ Compiling FBSDKMath.m
[16:33:20]: ▸ Compiling FBSDKMonotonicTime.m
[16:33:22]: ▸ Compiling FBSDKPaymentObserver.m
[16:33:25]: ▸ Compiling FBSDKProfile.m
[16:33:26]: ▸ Compiling FBSDKProfilePictureView.m
[16:33:27]: ▸ Compiling FBSDKServerConfiguration.m
[16:33:28]: ▸ Compiling FBSDKServerConfigurationManager.m
[16:33:31]: ▸ Compiling FBSDKSettings.m
[16:33:33]: ▸ Compiling FBSDKSystemAccountStoreAdapter.m
[16:33:34]: ▸ Compiling FBSDKTestUsersManager.m
[16:33:34]: ▸ Compiling FBSDKTimeSpentData.m
[16:33:35]: ▸ Compiling FBSDKTriStateBOOL.m
[16:33:36]: ▸ Compiling FBSDKTypeUtility.m
[16:33:37]: ▸ Compiling FBSDKURLConnection.m
[16:33:39]: ▸ Compiling FBSDKURLSessionTask.m
[16:33:40]: ▸ Compiling FBSDKUtility.m
[16:33:43]: ▸ Compiling FBSDKViewImpressionTracker.m
[16:33:45]: ▸ Compiling FBSDKWebDialog.m
[16:33:46]: ▸ Compiling FBSDKWebDialogView.m
[16:33:48]: ▸ Compiling FBSDKCoreKit_vers.c
[16:33:53]: ▸ Linking FBSDKCoreKit
[16:33:55]: ▸ Linking FBSDKCoreKit
[16:34:02]: ▸ Generating 'FBSDKCoreKit.framework.dSYM'
[16:34:07]: ▸ Copying FBSDKAccessToken.h
[16:34:08]: ▸ Copying FBSDKAppEvents.h
[16:34:09]: ▸ Copying FBSDKApplicationDelegate.h
[16:34:11]: ▸ Copying FBSDKAppLinkResolver.h
[16:34:11]: ▸ Copying FBSDKAppLinkUtility.h
[16:34:12]: ▸ Copying FBSDKButton.h
[16:34:14]: ▸ Copying FBSDKConstants.h
[16:34:15]: ▸ Copying FBSDKCopying.h
[16:34:16]: ▸ Copying FBSDKCoreKit-umbrella.h
[16:34:17]: ▸ Copying FBSDKCoreKit.h
[16:34:21]: ▸ Copying FBSDKGraphErrorRecoveryProcessor.h
[16:34:23]: ▸ Copying FBSDKGraphRequest.h
[16:34:23]: ▸ Copying FBSDKGraphRequestConnection.h
[16:34:23]: ▸ Copying FBSDKGraphRequestDataAttachment.h
[16:34:24]: ▸ Copying FBSDKMacros.h
[16:34:28]: ▸ Copying FBSDKMutableCopying.h
[16:34:28]: ▸ Copying FBSDKProfile.h
[16:34:28]: ▸ Copying FBSDKProfilePictureView.h
[16:34:29]: ▸ Copying FBSDKSettings.h
[16:34:29]: ▸ Copying FBSDKTestUsersManager.h
[16:34:31]: ▸ Copying FBSDKUtility.h
[16:34:36]: ▸ Copying FBSDKCoreKit/FacebookSDKStrings.bundle
[16:34:46]: Running Tests: ▸ Touching FBSDKCoreKit.framework
[16:34:48]: ▸ Building Pods/JSQMessagesViewController [Tests]
[16:34:48]: ▸ Check Dependencies
[16:34:48]: ▸ Compiling JSQAudioMediaItem.m
[16:34:48]: ▸ Compiling JSQAudioMediaViewAttributes.m
[16:34:48]: ▸ Compiling JSQLocationMediaItem.m
[16:34:48]: ▸ Compiling JSQMediaItem.m
[16:34:48]: ▸ Compiling JSQMessage.m
[16:34:48]: ▸ Compiling JSQMessagesAvatarImage.m
[16:34:48]: ▸ Compiling JSQMessagesAvatarImageFactory.m
[16:34:48]: ▸ Compiling JSQMessagesBubbleImage.m
[16:34:48]: ▸ Compiling JSQMessagesBubbleImageFactory.m
[16:34:48]: ▸ Compiling JSQMessagesBubblesSizeCalculator.m
[16:34:48]: ▸ Compiling JSQMessagesCellTextView.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionView.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCell.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellIncoming.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellOutgoing.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewFlowLayout.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewFlowLayoutInvalidationContext.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewLayoutAttributes.m
[16:34:48]: ▸ Compiling JSQMessagesComposerTextView.m
[16:34:48]: ▸ Compiling JSQMessagesInputToolbar.m
[16:34:48]: ▸ Compiling JSQMessagesKeyboardController.m
[16:34:48]: ▸ Compiling JSQMessagesLabel.m
[16:34:48]: ▸ Compiling JSQMessagesLoadEarlierHeaderView.m
[16:34:48]: ▸ Compiling JSQMessagesMediaPlaceholderView.m
[16:34:48]: ▸ Compiling JSQMessagesMediaViewBubbleImageMasker.m
[16:34:48]: ▸ Compiling JSQMessagesTimestampFormatter.m
[16:34:48]: ▸ Compiling JSQMessagesToolbarButtonFactory.m
[16:34:48]: ▸ Compiling JSQMessagesToolbarContentView.m
[16:34:48]: ▸ Compiling JSQMessagesTypingIndicatorFooterView.m
[16:34:48]: ▸ Compiling JSQMessagesViewController-dummy.m
[16:34:48]: ▸ Compiling JSQMessagesViewController.m
[16:34:48]: ▸ Compiling JSQPhotoMediaItem.m
[16:34:48]: ▸ Compiling JSQSystemSoundPlayer+JSQMessages.m
[16:34:48]: ▸ Compiling JSQVideoMediaItem.m
[16:34:48]: ▸ Compiling NSBundle+JSQMessages.m
[16:34:48]: ▸ Compiling NSString+JSQMessages.m
[16:34:48]: ▸ Compiling UIColor+JSQMessages.m
[16:34:48]: ▸ Compiling UIDevice+JSQMessages.m
[16:34:48]: ▸ Compiling UIImage+JSQMessages.m
[16:34:48]: ▸ Compiling UIView+JSQMessages.m
[16:34:48]: ▸ Compiling JSQMessagesViewController_vers.c
[16:34:48]: ▸ Compiling JSQAudioMediaItem.m
[16:34:48]: ▸ Compiling JSQAudioMediaViewAttributes.m
[16:34:48]: ▸ Compiling JSQLocationMediaItem.m
[16:34:48]: ▸ Compiling JSQMediaItem.m
[16:34:48]: ▸ Compiling JSQMessage.m
[16:34:48]: ▸ Compiling JSQMessagesAvatarImage.m
[16:34:48]: ▸ Compiling JSQMessagesAvatarImageFactory.m
[16:34:48]: ▸ Compiling JSQMessagesBubbleImage.m
[16:34:48]: ▸ Compiling JSQMessagesBubbleImageFactory.m
[16:34:48]: ▸ Compiling JSQMessagesBubblesSizeCalculator.m
[16:34:48]: ▸ Compiling JSQMessagesCellTextView.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionView.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCell.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellIncoming.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellOutgoing.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewFlowLayout.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewFlowLayoutInvalidationContext.m
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewLayoutAttributes.m
[16:34:48]: ▸ Compiling JSQMessagesComposerTextView.m
[16:34:48]: ▸ Compiling JSQMessagesInputToolbar.m
[16:34:48]: ▸ Compiling JSQMessagesKeyboardController.m
[16:34:48]: ▸ Compiling JSQMessagesLabel.m
[16:34:48]: ▸ Compiling JSQMessagesLoadEarlierHeaderView.m
[16:34:48]: ▸ Compiling JSQMessagesMediaPlaceholderView.m
[16:34:48]: ▸ Compiling JSQMessagesMediaViewBubbleImageMasker.m
[16:34:48]: ▸ Compiling JSQMessagesTimestampFormatter.m
[16:34:48]: ▸ Compiling JSQMessagesToolbarButtonFactory.m
[16:34:48]: ▸ Compiling JSQMessagesToolbarContentView.m
[16:34:48]: ▸ Compiling JSQMessagesTypingIndicatorFooterView.m
[16:34:48]: ▸ Compiling JSQMessagesViewController-dummy.m
[16:34:48]: ▸ Compiling JSQMessagesViewController.m
[16:34:48]: ▸ Compiling JSQPhotoMediaItem.m
[16:34:48]: ▸ Compiling JSQSystemSoundPlayer+JSQMessages.m
[16:34:48]: ▸ Compiling JSQVideoMediaItem.m
[16:34:48]: ▸ Compiling NSBundle+JSQMessages.m
[16:34:48]: ▸ Compiling NSString+JSQMessages.m
[16:34:48]: ▸ Compiling UIColor+JSQMessages.m
[16:34:48]: ▸ Compiling UIDevice+JSQMessages.m
[16:34:48]: ▸ Compiling UIImage+JSQMessages.m
[16:34:48]: ▸ Compiling UIView+JSQMessages.m
[16:34:48]: ▸ Compiling JSQMessagesViewController_vers.c
[16:34:48]: ▸ Linking JSQMessagesViewController
[16:34:48]: ▸ Linking JSQMessagesViewController
[16:34:48]: ▸ Copying JSQAudioMediaItem.h
[16:34:48]: ▸ Copying JSQAudioMediaViewAttributes.h
[16:34:48]: ▸ Copying JSQLocationMediaItem.h
[16:34:48]: ▸ Copying JSQMediaItem.h
[16:34:48]: ▸ Copying JSQMessage.h
[16:34:48]: ▸ Copying JSQMessageAvatarImageDataSource.h
[16:34:48]: ▸ Copying JSQMessageBubbleImageDataSource.h
[16:34:48]: ▸ Copying JSQMessageData.h
[16:34:48]: ▸ Copying JSQMessageMediaData.h
[16:34:48]: ▸ Copying JSQMessages.h
[16:34:48]: ▸ Copying JSQMessagesAvatarImage.h
[16:34:48]: 33m▸ Copying JSQMessagesAvatarImageFactory.h
[16:34:48]: ▸ Copying JSQMessagesBubbleImage.h
[16:34:48]: ▸ Copying JSQMessagesBubbleImageFactory.h
[16:34:48]: ▸ Copying JSQMessagesBubbleSizeCalculating.h
[16:34:48]: ▸ Copying JSQMessagesBubblesSizeCalculator.h
[16:34:48]: ▸ Copying JSQMessagesCellTextView.h
[16:34:48]: ▸ Copying JSQMessagesCollectionView.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewCell.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewCellIncoming.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewCellOutgoing.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewDataSource.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewDelegateFlowLayout.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewFlowLayout.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewFlowLayoutInvalidationContext.h
[16:34:48]: ▸ Copying JSQMessagesCollectionViewLayoutAttributes.h
[16:34:48]: ▸ Copying JSQMessagesComposerTextView.h
[16:34:48]: ▸ Copying JSQMessagesInputToolbar.h
[16:34:48]: ▸ Copying JSQMessagesKeyboardController.h
[16:34:48]: ▸ Copying JSQMessagesLabel.h
[16:34:48]: ▸ Copying JSQMessagesLoadEarlierHeaderView.h
[16:34:48]: ▸ Copying JSQMessagesMediaPlaceholderView.h
[16:34:48]: ▸ Copying JSQMessagesMediaViewBubbleImageMasker.h
[16:34:48]: ▸ Copying JSQMessagesTimestampFormatter.h
[16:34:48]: ▸ Copying JSQMessagesToolbarButtonFactory.h
[16:34:48]: ▸ Copying JSQMessagesToolbarContentView.h
[16:34:48]: ▸ Copying JSQMessagesTypingIndicatorFooterView.h
[16:34:48]: ▸ Copying JSQMessagesViewController-umbrella.h
[16:34:48]: ▸ Copying JSQMessagesViewController.h
[16:34:48]: ▸ Copying JSQPhotoMediaItem.h
[16:34:48]: ▸ Copying JSQSystemSoundPlayer+JSQMessages.h
[16:34:48]: ▸ Copying JSQVideoMediaItem.h
[16:34:48]: ▸ Copying NSBundle+JSQMessages.h
[16:34:48]: ▸ Copying NSString+JSQMessages.h
[16:34:48]: ▸ Copying UIColor+JSQMessages.h
[16:34:48]: ▸ Copying UIDevice+JSQMessages.h
[16:34:48]: ▸ Copying UIImage+JSQMessages.h
[16:34:48]: ▸ Copying UIView+JSQMessages.h
[16:34:48]: ▸ Copying JSQMessagesViewController/JSQMessagesViewController/Assets/JSQMessagesAssets.bundle
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellIncoming.xib
[16:34:48]: ▸ Compiling JSQMessagesCollectionViewCellOutgoing.xib
[16:34:48]: ▸ Compiling JSQMessagesLoadEarlierHeaderView.xib
[16:34:48]: ▸ Compiling JSQMessagesToolbarContentView.xib
[16:34:48]: ▸ Compiling JSQMessagesTypingIndicatorFooterView.xib
[16:34:48]: ▸ Compiling JSQMessagesViewController.xib
[16:34:48]: ▸ Processing Info.plist
[16:34:48]: ▸ Generating 'JSQMessagesViewController.framework.dSYM'
[16:34:48]: Running Tests: ▸ Touching JSQMessagesViewController.framework
[16:34:48]: ▸ Building Pods/ObjectMapper [Tests]
[16:34:48]: ▸ Check Dependencies
[16:34:48]: ▸ Processing Info.plist
[16:34:48]: ▸ Compiling ObjectMapper-dummy.m
[16:34:48]: ▸ Compiling ObjectMapper_vers.c
[16:34:48]: ▸ Compiling ObjectMapper-dummy.m
[16:34:48]: ▸ Compiling ObjectMapper_vers.c
[16:34:48]: ▸ Linking ObjectMapper
[16:34:48]: ▸ Linking ObjectMapper
[16:34:48]: ▸ Generating 'ObjectMapper.framework.dSYM'
[16:34:48]: ▸ Copying ObjectMapper-umbrella.h
[16:34:48]: Running Tests: ▸ Touching ObjectMapper.framework
[16:34:48]: ▸ Building Pods/Realm [Tests]
[16:34:48]: ▸ Check Dependencies
[16:34:48]: ▸ Processing Info.plist
[16:34:48]: ▸ Compiling binding_callback_thread_observer.cpp
[16:34:48]: ▸ Compiling collection_change_builder.cpp
[16:34:48]: ▸ Compiling collection_notifications.cpp
[16:34:48]: ▸ Compiling collection_notifier.cpp
[16:34:48]: ▸ Compiling external_commit_helper.cpp
[16:34:48]: ▸ Compiling index_set.cpp
[16:34:48]: ▸ Compiling keychain_helper.cpp
[16:34:48]: ▸ Compiling list.cpp
[16:34:48]: ▸ Compiling list_notifier.cpp
[16:34:48]: ▸ Compiling network_reachability_observer.cpp
[16:34:48]: ▸ Compiling NSError+RLMSync.m
[16:34:48]: ▸ Compiling object.cpp
[16:34:48]: ▸ Compiling object_notifier.cpp
[16:34:48]: ▸ Compiling object_schema.cpp
[16:34:48]: ▸ Compiling object_store.cpp
[16:34:48]: ▸ Compiling partial_sync.cpp
[16:34:48]: ▸ Compiling placeholder.cpp
[16:34:48]: ▸ Compiling primitive_list_notifier.cpp
[16:34:48]: ▸ Compiling Realm-dummy.m
[16:34:48]: ▸ Compiling realm_coordinator.cpp
[16:34:48]: ▸ Compiling results.cpp
[16:34:48]: ▸ Compiling results_notifier.cpp
[16:34:48]: ▸ Compiling RLMAccessor.mm
[16:34:48]: ▸ Compiling RLMAnalytics.mm
[16:34:48]: ▸ Compiling RLMArray.mm
[16:34:48]: ▸ Compiling RLMClassInfo.mm
[16:34:48]: ▸ Compiling RLMCollection.mm
[16:34:48]: ▸ Compiling RLMConstants.m
[16:34:48]: ▸ Compiling RLMJSONModels.m
[16:34:48]: ▸ Compiling RLMListBase.mm
[16:34:48]: ▸ Compiling RLMManagedArray.mm
[16:34:48]: ▸ Compiling RLMMigration.mm
[16:34:48]: ▸ Compiling RLMNetworkClient.mm
[16:34:48]: ▸ Compiling RLMObject.mm
[16:34:48]: ▸ Compiling RLMObjectBase.mm
[16:34:48]: ▸ Compiling RLMObjectSchema.mm
[16:34:48]: ▸ Compiling RLMObjectStore.mm
[16:34:48]: ▸ Compiling RLMObservation.mm
[16:34:48]: ▸ Compiling RLMOptionalBase.mm
[16:34:48]: ▸ Compiling RLMPredicateUtil.mm
[16:34:48]: ▸ Compiling RLMProperty.mm
[16:34:48]: ▸ Compiling RLMQueryUtil.mm
[16:34:48]: ▸ Compiling RLMRealm+Sync.mm
[16:34:48]: ▸ Compiling RLMRealm.mm
[16:34:48]: ▸ Compiling RLMRealmConfiguration+Sync.mm
[16:34:48]: ▸ Compiling RLMRealmConfiguration.mm
[16:34:48]: ▸ Compiling RLMRealmUtil.mm
[16:34:48]: ▸ Compiling RLMResults.mm
[16:34:48]: ▸ Compiling RLMSchema.mm
[16:34:48]: ▸ Compiling RLMSwiftSupport.m
[16:34:48]: ▸ Compiling RLMSyncConfiguration.mm
[16:34:48]: ▸ Compiling RLMSyncCredentials.m
[16:34:48]: ▸ Compiling RLMSyncManager.mm
[16:34:48]: ▸ Compiling RLMSyncPermission.mm
[16:34:48]: ▸ Compiling RLMSyncPermissionResults.mm
[16:34:48]: ▸ Compiling RLMSyncSession.mm
[16:34:48]: ▸ Compiling RLMSyncSessionRefreshHandle.mm
[16:34:48]: ▸ Compiling RLMSyncSubscription.mm
[16:34:48]: ▸ Compiling RLMSyncUser.mm
[16:34:48]: ▸ Compiling RLMSyncUtil.mm
[16:34:48]: ▸ Compiling RLMThreadSafeReference.mm
[16:34:48]: ▸ Compiling RLMUpdateChecker.mm
[16:34:48]: ▸ Compiling RLMUtil.mm
[16:34:48]: ▸ Compiling schema.cpp
[16:34:48]: ▸ Compiling shared_realm.cpp
[16:34:48]: ▸ Compiling sync_config.cpp
[16:34:48]: ▸ Compiling sync_file.cpp
[16:34:48]: ▸ Compiling sync_manager.cpp
[16:34:48]: ▸ Compiling sync_metadata.cpp
[16:34:48]: ▸ Compiling sync_permission.cpp
[16:34:48]: ▸ Compiling sync_session.cpp
[16:34:48]: ▸ Compiling sync_user.cpp
[16:34:48]: ▸ Compiling system_configuration.cpp
[16:34:48]: ▸ Compiling thread_safe_reference.cpp
[16:34:48]: ▸ Compiling transact_log_handler.cpp
[16:34:48]: ▸ Compiling uuid.cpp
[16:34:48]: ▸ Compiling weak_realm_notifier.cpp
[16:34:48]: ▸ Compiling work_queue.cpp
[16:34:48]: ▸ Compiling Realm_vers.c
[16:34:48]: ▸ Compiling binding_callback_thread_observer.cpp
[16:34:48]: ▸ Compiling collection_change_builder.cpp
[16:34:48]: ▸ Compiling collection_notifications.cpp
[16:34:48]: ▸ Compiling collection_notifier.cpp
[16:34:48]: ▸ Compiling external_commit_helper.cpp
[16:34:48]: ▸ Compiling index_set.cpp
[16:34:48]: ▸ Compiling keychain_helper.cpp
[16:34:48]: ▸ Compiling list.cpp
[16:34:48]: ▸ Compiling list_notifier.cpp
[16:34:48]: ▸ Compiling network_reachability_observer.cpp
[16:34:48]: ▸ Compiling NSError+RLMSync.m
[16:34:48]: ▸ Compiling object.cpp
[16:34:48]: ▸ Compiling object_notifier.cpp
[16:34:48]: ▸ Compiling object_schema.cpp
[16:34:48]: ▸ Compiling object_store.cpp
[16:34:48]: ▸ Compiling partial_sync.cpp
[16:34:48]: ▸ Compiling placeholder.cpp
[16:34:48]: ▸ Compiling primitive_list_notifier.cpp
[16:34:48]: ▸ Compiling Realm-dummy.m
[16:34:48]: ▸ Compiling realm_coordinator.cpp
[16:34:48]: ▸ Compiling results.cpp
[16:34:48]: ▸ Compiling results_notifier.cpp
[16:34:48]: ▸ Compiling RLMAccessor.mm
[16:34:48]: ▸ Compiling RLMAnalytics.mm
[16:34:48]: ▸ Compiling RLMArray.mm
[16:34:48]: ▸ Compiling RLMClassInfo.mm
[16:34:48]: ▸ Compiling RLMCollection.mm
[16:34:48]: ▸ Compiling RLMConstants.m
[16:34:48]: ▸ Compiling RLMJSONModels.m
[16:34:48]: ▸ Compiling RLMListBase.mm
[16:34:48]: ▸ Compiling RLMManagedArray.mm
[16:34:48]: ▸ Compiling RLMMigration.mm
[16:34:48]: ▸ Compiling RLMNetworkClient.mm
[16:34:48]: ▸ Compiling RLMObject.mm
[16:34:48]: ▸ Compiling RLMObjectBase.mm
[16:34:48]: ▸ Compiling RLMObjectSchema.mm
[16:34:48]: ▸ Compiling RLMObjectStore.mm
[16:34:48]: ▸ Compiling RLMObservation.mm
[16:34:48]: ▸ Compiling RLMOptionalBase.mm
[16:34:48]: ▸ Compiling RLMPredicateUtil.mm
[16:34:48]: ▸ Compiling RLMProperty.mm
[16:34:48]: ▸ Compiling RLMQueryUtil.mm
[16:34:59]: ▸ Compiling RLMRealm+Sync.mm
[16:34:59]: ▸ Compiling RLMRealm.mm
[16:34:59]: ▸ Compiling RLMRealmConfiguration+Sync.mm
[16:34:59]: ▸ Compiling RLMRealmConfiguration.mm
[16:34:59]: ▸ Compiling RLMRealmUtil.mm
[16:34:59]: ▸ Compiling RLMResults.mm
[16:34:59]: ▸ Compiling RLMSchema.mm
[16:34:59]: ▸ Compiling RLMSwiftSupport.m
[16:34:59]: ▸ Compiling RLMSyncConfiguration.mm
[16:34:59]: ▸ Compiling RLMSyncCredentials.m
[16:34:59]: ▸ Compiling RLMSyncManager.mm
[16:35:00]: ▸ Compiling RLMSyncPermission.mm
[16:35:01]: ▸ Compiling RLMSyncPermissionResults.mm
[16:35:04]: ▸ Compiling RLMSyncSession.mm
[16:35:05]: ▸ Compiling RLMSyncSessionRefreshHandle.mm
[16:35:06]: ▸ Compiling RLMSyncSubscription.mm
[16:35:06]: ▸ Compiling RLMSyncUser.mm
[16:35:11]: ▸ Compiling RLMSyncUtil.mm
[16:35:11]: ▸ Compiling RLMThreadSafeReference.mm
[16:35:11]: ▸ Compiling RLMUpdateChecker.mm
[16:35:11]: ▸ Compiling RLMUtil.mm
[16:35:13]: ▸ Compiling schema.cpp
[16:35:13]: ▸ Compiling shared_realm.cpp
[16:35:18]: ▸ Compiling sync_config.cpp
[16:35:18]: ▸ Compiling sync_file.cpp
[16:35:18]: ▸ Compiling sync_manager.cpp
[16:35:22]: ▸ Compiling sync_metadata.cpp
[16:35:22]: ▸ Compiling sync_permission.cpp
[16:35:26]: ▸ Compiling sync_session.cpp
[16:35:26]: ▸ Compiling sync_user.cpp
[16:35:26]: ▸ Compiling system_configuration.cpp
[16:35:26]: ▸ Compiling thread_safe_reference.cpp
[16:35:27]: ▸ Compiling transact_log_handler.cpp
[16:35:34]: ▸ Compiling uuid.cpp
[16:35:34]: ▸ Compiling weak_realm_notifier.cpp
[16:35:34]: ▸ Compiling work_queue.cpp
[16:35:34]: ▸ Compiling Realm_vers.c
[16:35:34]: ▸ Linking Realm
[16:35:35]: ▸ Linking Realm
[16:35:36]: ▸ Generating 'Realm.framework.dSYM'
[16:35:46]: ▸ Copying Realm/include/RLMAccessor.h
[16:35:46]: ▸ Copying Realm/include/RLMArray_Private.h
[16:35:46]: ▸ Copying Realm/include/RLMCollection_Private.h
[16:35:46]: ▸ Copying Realm/include/RLMListBase.h
[16:35:46]: ▸ Copying Realm/include/RLMMigration_Private.h
[16:35:46]: ▸ Copying Realm/include/RLMObject_Private.h
[16:35:46]: ▸ Copying Realm/include/RLMObjectBase_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMObjectSchema_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMObjectStore.h
[16:35:47]: ▸ Copying Realm/include/RLMOptionalBase.h
[16:35:47]: ▸ Copying Realm/include/RLMProperty_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMRealm_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMRealmConfiguration_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMResults_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMSchema_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncConfiguration_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncManager_Private.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncUtil_Private.h
[16:35:47]: ▸ Copying Realm/include/NSError+RLMSync.h
[16:35:47]: ▸ Copying Realm/include/Realm.h
[16:35:47]: ▸ Copying Realm/include/RLMArray.h
[16:35:47]: ▸ Copying Realm/include/RLMCollection.h
[16:35:47]: ▸ Copying Realm/include/RLMConstants.h
[16:35:47]: ▸ Copying Realm/include/RLMListBase.h
[16:35:47]: ▸ Copying Realm/include/RLMMigration.h
[16:35:47]: ▸ Copying Realm/include/RLMObject.h
[16:35:47]: ▸ Copying Realm/include/RLMObjectBase.h
[16:35:47]: ▸ Copying Realm/include/RLMObjectBase_Dynamic.h
[16:35:47]: ▸ Copying Realm/include/RLMObjectSchema.h
[16:35:47]: ▸ Copying Realm/include/RLMOptionalBase.h
[16:35:47]: ▸ Copying Realm/include/RLMPlatform.h
[16:35:47]: ▸ Copying Realm/include/RLMProperty.h
[16:35:47]: ▸ Copying Realm/include/RLMRealm+Sync.h
[16:35:47]: ▸ Copying Realm/include/RLMRealm.h
[16:35:47]: ▸ Copying Realm/include/RLMRealm_Dynamic.h
[16:35:47]: ▸ Copying Realm/include/RLMRealmConfiguration+Sync.h
[16:35:47]: ▸ Copying Realm/include/RLMRealmConfiguration.h
[16:35:47]: ▸ Copying Realm/include/RLMResults.h
[16:35:47]: ▸ Copying Realm/include/RLMSchema.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncConfiguration.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncCredentials.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncManager.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncPermission.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncSession.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncSubscription.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncUser.h
[16:35:47]: ▸ Copying Realm/include/RLMSyncUtil.h
[16:35:47]: ▸ Copying Realm/include/RLMThreadSafeReference.h
[16:35:47]: Running Tests: ▸ Touching Realm.framework
[16:35:47]: ▸ Building Pods/Protobuf [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling Any.pbobjc.m
[16:35:47]: ▸ Compiling Api.pbobjc.m
[16:35:47]: ▸ Compiling Duration.pbobjc.m
[16:35:47]: ▸ Compiling Empty.pbobjc.m
[16:35:47]: ▸ Compiling FieldMask.pbobjc.m
[16:35:47]: ▸ Compiling GPBArray.m
[16:35:47]: ▸ Compiling GPBCodedInputStream.m
[16:35:47]: ▸ Compiling GPBCodedOutputStream.m
[16:35:47]: ▸ Compiling GPBDescriptor.m
[16:35:47]: ▸ Compiling GPBDictionary.m
[16:35:47]: ▸ Compiling GPBExtensionInternals.m
[16:35:47]: ▸ Compiling GPBExtensionRegistry.m
[16:35:47]: ▸ Compiling GPBMessage.m
[16:35:47]: ▸ Compiling GPBRootObject.m
[16:35:47]: ▸ Compiling GPBUnknownField.m
[16:35:47]: ▸ Compiling GPBUnknownFieldSet.m
[16:35:47]: ▸ Compiling GPBUtilities.m
[16:35:47]: ▸ Compiling GPBWellKnownTypes.m
[16:35:47]: ▸ Compiling GPBWireFormat.m
[16:35:47]: ▸ Compiling Protobuf-dummy.m
[16:35:47]: ▸ Compiling SourceContext.pbobjc.m
[16:35:47]: ▸ Compiling Struct.pbobjc.m
[16:35:47]: ▸ Compiling Timestamp.pbobjc.m
[16:35:47]: ▸ Compiling Type.pbobjc.m
[16:35:47]: ▸ Compiling Wrappers.pbobjc.m
[16:35:47]: ▸ Compiling Protobuf_vers.c
[16:35:47]: ▸ Compiling Any.pbobjc.m
[16:35:47]: ▸ Compiling Api.pbobjc.m
[16:35:47]: ▸ Compiling Duration.pbobjc.m
[16:35:47]: ▸ Compiling Empty.pbobjc.m
[16:35:47]: ▸ Compiling FieldMask.pbobjc.m
[16:35:47]: ▸ Compiling GPBArray.m
[16:35:47]: ▸ Compiling GPBCodedInputStream.m
[16:35:47]: ▸ Compiling GPBCodedOutputStream.m
[16:35:47]: ▸ Compiling GPBDescriptor.m
[16:35:47]: ▸ Compiling GPBDictionary.m
[16:35:47]: ▸ Compiling GPBExtensionInternals.m
[16:35:47]: ▸ Compiling GPBExtensionRegistry.m
[16:35:47]: ▸ Compiling GPBMessage.m
[16:35:47]: ▸ Compiling GPBRootObject.m
[16:35:47]: ▸ Compiling GPBUnknownField.m
[16:35:47]: ▸ Compiling GPBUnknownFieldSet.m
[16:35:47]: ▸ Compiling GPBUtilities.m
[16:35:47]: ▸ Compiling GPBWellKnownTypes.m
[16:35:47]: ▸ Compiling GPBWireFormat.m
[16:35:47]: ▸ Compiling Protobuf-dummy.m
[16:35:47]: ▸ Compiling SourceContext.pbobjc.m
[16:35:47]: ▸ Compiling Struct.pbobjc.m
[16:35:47]: ▸ Compiling Timestamp.pbobjc.m
[16:35:47]: ▸ Compiling Type.pbobjc.m
[16:35:47]: ▸ Compiling Wrappers.pbobjc.m
[16:35:47]: ▸ Compiling Protobuf_vers.c
[16:35:47]: ▸ Linking Protobuf
[16:35:47]: ▸ Linking Protobuf
[16:35:47]: ▸ Generating 'Protobuf.framework.dSYM'
[16:35:47]: ▸ Copying Any.pbobjc.h
[16:35:47]: ▸ Copying Api.pbobjc.h
[16:35:47]: ▸ Copying Duration.pbobjc.h
[16:35:47]: ▸ Copying Empty.pbobjc.h
[16:35:47]: ▸ Copying FieldMask.pbobjc.h
[16:35:47]: ▸ Copying GPBArray.h
[16:35:47]: ▸ Copying GPBArray_PackagePrivate.h
[16:35:47]: ▸ Copying GPBBootstrap.h
[16:35:47]: ▸ Copying GPBCodedInputStream.h
[16:35:47]: ▸ Copying GPBCodedInputStream_PackagePrivate.h
[16:35:47]: ▸ Copying GPBCodedOutputStream.h
[16:35:47]: ▸ Copying GPBCodedOutputStream_PackagePrivate.h
[16:35:47]: ▸ Copying GPBDescriptor.h
[16:35:47]: ▸ Copying GPBDescriptor_PackagePrivate.h
[16:35:47]: ▸ Copying GPBDictionary.h
[16:35:47]: ▸ Copying GPBDictionary_PackagePrivate.h
[16:35:47]: ▸ Copying GPBExtensionInternals.h
[16:35:47]: ▸ Copying GPBExtensionRegistry.h
[16:35:47]: ▸ Copying GPBMessage.h
[16:35:47]: ▸ Copying GPBMessage_PackagePrivate.h
[16:35:47]: ▸ Copying GPBProtocolBuffers.h
[16:35:47]: ▸ Copying GPBProtocolBuffers_RuntimeSupport.h
[16:35:47]: ▸ Copying GPBRootObject.h
[16:35:47]: ▸ Copying GPBRootObject_PackagePrivate.h
[16:35:47]: ▸ Copying GPBRuntimeTypes.h
[16:35:47]: ▸ Copying GPBUnknownField.h
[16:35:47]: ▸ Copying GPBUnknownField_PackagePrivate.h
[16:35:47]: ▸ Copying GPBUnknownFieldSet.h
[16:35:47]: ▸ Copying GPBUnknownFieldSet_PackagePrivate.h
[16:35:47]: ▸ Copying GPBUtilities.h
[16:35:47]: ▸ Copying GPBUtilities_PackagePrivate.h
[16:35:47]: ▸ Copying GPBWellKnownTypes.h
[16:35:47]: ▸ Copying GPBWireFormat.h
[16:35:47]: ▸ Copying Protobuf-umbrella.h
[16:35:47]: ▸ Copying SourceContext.pbobjc.h
[16:35:47]: ▸ Copying Struct.pbobjc.h
[16:35:47]: ▸ Copying Timestamp.pbobjc.h
[16:35:47]: ▸ Copying Type.pbobjc.h
[16:35:47]: ▸ Copying Wrappers.pbobjc.h
[16:35:47]: Running Tests: ▸ Touching Protobuf.framework
[16:35:47]: ▸ Building Pods/RBBAnimation [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling NSValue+PlatformIndependence.m
[16:35:47]: ▸ Compiling RBBAnimation-dummy.m
[16:35:47]: ▸ Compiling RBBAnimation.m
[16:35:47]: ▸ Compiling RBBBlockBasedArray.m
[16:35:47]: ▸ Compiling RBBCubicBezier.m
[16:35:47]: ▸ Compiling RBBCustomAnimation.m
[16:35:47]: ▸ Compiling RBBEasingFunction.m
[16:35:47]: ▸ Compiling RBBLinearInterpolation.m
[16:35:47]: ▸ Compiling RBBSpringAnimation.m
[16:35:47]: ▸ Compiling RBBTweenAnimation.m
[16:35:47]: ▸ Compiling UIColor+PlatformIndependence.m
[16:35:47]: ▸ Compiling RBBAnimation_vers.c
[16:35:47]: ▸ Compiling NSValue+PlatformIndependence.m
[16:35:47]: ▸ Compiling RBBAnimation-dummy.m
[16:35:47]: ▸ Compiling RBBAnimation.m
[16:35:47]: ▸ Compiling RBBBlockBasedArray.m
[16:35:47]: ▸ Compiling RBBCubicBezier.m
[16:35:47]: ▸ Compiling RBBCustomAnimation.m
[16:35:47]: ▸ Compiling RBBEasingFunction.m
[16:35:47]: ▸ Compiling RBBLinearInterpolation.m
[16:35:47]: ▸ Compiling RBBSpringAnimation.m
[16:35:47]: ▸ Compiling RBBTweenAnimation.m
[16:35:47]: ▸ Compiling UIColor+PlatformIndependence.m
[16:35:47]: ▸ Compiling RBBAnimation_vers.c
[16:35:47]: ▸ Linking RBBAnimation
[16:35:47]: ▸ Linking RBBAnimation
[16:35:47]: ▸ Generating 'RBBAnimation.framework.dSYM'
[16:35:47]: ▸ Copying NSValue+PlatformIndependence.h
[16:35:47]: ▸ Copying RBBAnimation-umbrella.h
[16:35:47]: ▸ Copying RBBAnimation.h
[16:35:47]: ▸ Copying RBBBlockBasedArray.h
[16:35:47]: ▸ Copying RBBCubicBezier.h
[16:35:47]: ▸ Copying RBBCustomAnimation.h
[16:35:47]: ▸ Copying RBBEasingFunction.h
[16:35:47]: ▸ Copying RBBLinearInterpolation.h
[16:35:47]: ▸ Copying RBBSpringAnimation.h
[16:35:47]: ▸ Copying RBBTweenAnimation.h
[16:35:47]: ▸ Copying UIColor+PlatformIndependence.h
[16:35:47]: Running Tests: ▸ Touching RBBAnimation.framework
[16:35:47]: ▸ Building Pods/FBSDKLoginKit [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling _FBSDKLoginRecoveryAttempter.m
[16:35:47]: ▸ Compiling FBSDKLoginButton.m
[16:35:47]: ▸ Compiling FBSDKLoginCompletion.m
[16:35:47]: ▸ Compiling FBSDKLoginConstants.m
[16:35:47]: ▸ Compiling FBSDKLoginError.m
[16:35:47]: ▸ Compiling FBSDKLoginKit-dummy.m
[16:35:47]: ▸ Compiling FBSDKLoginManager.m
[16:35:47]: ▸ Compiling FBSDKLoginManagerLogger.m
[16:35:47]: ▸ Compiling FBSDKLoginManagerLoginResult.m
[16:35:47]: ▸ Compiling FBSDKLoginTooltipView.m
[16:35:47]: ▸ Compiling FBSDKLoginUtility.m
[16:35:47]: ▸ Compiling FBSDKTooltipView.m
[16:35:47]: ▸ Compiling FBSDKLoginKit_vers.c
[16:35:47]: ▸ Compiling _FBSDKLoginRecoveryAttempter.m
[16:35:47]: ▸ Compiling FBSDKLoginButton.m
[16:35:47]: ▸ Compiling FBSDKLoginCompletion.m
[16:35:47]: ▸ Compiling FBSDKLoginConstants.m
[16:35:47]: ▸ Compiling FBSDKLoginError.m
[16:35:47]: ▸ Compiling FBSDKLoginKit-dummy.m
[16:35:47]: ▸ Compiling FBSDKLoginManager.m
[16:35:47]: ▸ Compiling FBSDKLoginManagerLogger.m
[16:35:47]: ▸ Compiling FBSDKLoginManagerLoginResult.m
[16:35:47]: ▸ Compiling FBSDKLoginTooltipView.m
[16:35:47]: ▸ Compiling FBSDKLoginUtility.m
[16:35:47]: ▸ Compiling FBSDKTooltipView.m
[16:35:47]: ▸ Compiling FBSDKLoginKit_vers.c
[16:35:47]: ▸ Linking FBSDKLoginKit
[16:35:47]: ▸ Linking FBSDKLoginKit
[16:35:47]: ▸ Generating 'FBSDKLoginKit.framework.dSYM'
[16:35:47]: ▸ Copying FBSDKLoginButton.h
[16:35:47]: ▸ Copying FBSDKLoginConstants.h
[16:35:47]: ▸ Copying FBSDKLoginKit-umbrella.h
[16:35:47]: ▸ Copying FBSDKLoginKit.h
[16:35:47]: ▸ Copying FBSDKLoginManager.h
[16:35:47]: ▸ Copying FBSDKLoginManagerLoginResult.h
[16:35:47]: ▸ Copying FBSDKLoginTooltipView.h
[16:35:47]: ▸ Copying FBSDKTooltipView.h
[16:35:47]: Running Tests: ▸ Touching FBSDKLoginKit.framework
[16:35:47]: ▸ Building Pods/SDCAutoLayout [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling SDCAutoLayout-dummy.m
[16:35:47]: ▸ Compiling UIView+SDCAutoLayout.m
[16:35:47]: ▸ Compiling SDCAutoLayout_vers.c
[16:35:47]: ▸ Compiling SDCAutoLayout-dummy.m
[16:35:47]: ▸ Compiling UIView+SDCAutoLayout.m
[16:35:47]: ▸ Compiling SDCAutoLayout_vers.c
[16:35:47]: ▸ Linking SDCAutoLayout
[16:35:47]: ▸ Linking SDCAutoLayout
[16:35:47]: ▸ Generating 'SDCAutoLayout.framework.dSYM'
[16:35:47]: ▸ Copying SDCAutoLayout-umbrella.h
[16:35:47]: ▸ Copying UIView+SDCAutoLayout.h
[16:35:47]: Running Tests: ▸ Touching SDCAutoLayout.framework
[16:35:47]: ▸ Building Pods/SDWebImage [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling NSButton+WebCache.m
[16:35:47]: ▸ Compiling NSData+ImageContentType.m
[16:35:47]: ▸ Compiling NSImage+WebCache.m
[16:35:47]: ▸ Compiling SDAnimatedImageRep.m
[16:35:47]: ▸ Compiling SDImageCache.m
[16:35:47]: ▸ Compiling SDImageCacheConfig.m
[16:35:47]: ▸ Compiling SDWebImage-dummy.m
[16:35:47]: ▸ Compiling SDWebImageCoder.m
[16:35:47]: ▸ Compiling SDWebImageCoderHelper.m
[16:35:47]: ▸ Compiling SDWebImageCodersManager.m
[16:35:47]: ▸ Compiling SDWebImageCompat.m
[16:35:47]: ▸ Compiling SDWebImageDownloader.m
[16:35:47]: ▸ Compiling SDWebImageDownloaderOperation.m
[16:35:47]: ▸ Compiling SDWebImageFrame.m
[16:35:47]: ▸ Compiling SDWebImageGIFCoder.m
[16:35:47]: ▸ Compiling SDWebImageImageIOCoder.m
[16:35:47]: ▸ Compiling SDWebImageManager.m
[16:35:47]: ▸ Compiling SDWebImagePrefetcher.m
[16:35:47]: ▸ Compiling SDWebImageTransition.m
[16:35:47]: ▸ Compiling UIButton+WebCache.m
[16:35:47]: ▸ Compiling UIImage+ForceDecode.m
[16:35:47]: ▸ Compiling UIImage+GIF.m
[16:35:47]: ▸ Compiling UIImage+MultiFormat.m
[16:35:47]: ▸ Compiling UIImageView+HighlightedWebCache.m
[16:35:47]: ▸ Compiling UIImageView+WebCache.m
[16:35:47]: ▸ Compiling UIView+WebCache.m
[16:35:47]: ▸ Compiling UIView+WebCacheOperation.m
[16:35:47]: ▸ Compiling SDWebImage_vers.c
[16:35:47]: ▸ Compiling NSButton+WebCache.m
[16:35:47]: ▸ Compiling NSData+ImageContentType.m
[16:35:47]: ▸ Compiling NSImage+WebCache.m
[16:35:47]: ▸ Compiling SDAnimatedImageRep.m
[16:35:47]: ▸ Compiling SDImageCache.m
[16:35:47]: ▸ Compiling SDImageCacheConfig.m
[16:35:47]: ▸ Compiling SDWebImage-dummy.m
[16:35:47]: ▸ Compiling SDWebImageCoder.m
[16:35:47]: ▸ Compiling SDWebImageCoderHelper.m
[16:35:47]: ▸ Compiling SDWebImageCodersManager.m
[16:35:47]: ▸ Compiling SDWebImageCompat.m
[16:35:47]: ▸ Compiling SDWebImageDownloader.m
[16:35:47]: ▸ Compiling SDWebImageDownloaderOperation.m
[16:35:47]: ▸ Compiling SDWebImageFrame.m
[16:35:47]: ▸ Compiling SDWebImageGIFCoder.m
[16:35:47]: ▸ Compiling SDWebImageImageIOCoder.m
[16:35:47]: ▸ Compiling SDWebImageManager.m
[16:35:47]: ▸ Compiling SDWebImagePrefetcher.m
[16:35:47]: ▸ Compiling SDWebImageTransition.m
[16:35:47]: ▸ Compiling UIButton+WebCache.m
[16:35:47]: ▸ Compiling UIImage+ForceDecode.m
[16:35:47]: ▸ Compiling UIImage+GIF.m
[16:35:47]: ▸ Compiling UIImage+MultiFormat.m
[16:35:47]: ▸ Compiling UIImageView+HighlightedWebCache.m
[16:35:47]: ▸ Compiling UIImageView+WebCache.m
[16:35:47]: ▸ Compiling UIView+WebCache.m
[16:35:47]: ▸ Compiling UIView+WebCacheOperation.m
[16:35:47]: ▸ Compiling SDWebImage_vers.c
[16:35:47]: ▸ Linking SDWebImage
[16:35:47]: ▸ Linking SDWebImage
[16:35:47]: ▸ Generating 'SDWebImage.framework.dSYM'
[16:35:47]: ▸ Copying NSButton+WebCache.h
[16:35:47]: ▸ Copying NSData+ImageContentType.h
[16:35:47]: ▸ Copying NSImage+WebCache.h
[16:35:47]: ▸ Copying SDAnimatedImageRep.h
[16:35:47]: ▸ Copying SDImageCache.h
[16:35:47]: ▸ Copying SDImageCacheConfig.h
[16:35:47]: ▸ Copying SDWebImage-umbrella.h
[16:35:47]: ▸ Copying SDWebImageCoder.h
[16:35:47]: ▸ Copying SDWebImageCoderHelper.h
[16:35:47]: ▸ Copying SDWebImageCodersManager.h
[16:35:47]: ▸ Copying SDWebImageCompat.h
[16:35:47]: ▸ Copying SDWebImageDownloader.h
[16:35:47]: ▸ Copying SDWebImageDownloaderOperation.h
[16:35:47]: ▸ Copying SDWebImageFrame.h
[16:35:47]: ▸ Copying SDWebImageGIFCoder.h
[16:35:47]: ▸ Copying SDWebImageImageIOCoder.h
[16:35:47]: ▸ Copying SDWebImageManager.h
[16:35:47]: ▸ Copying SDWebImageOperation.h
[16:35:47]: ▸ Copying SDWebImagePrefetcher.h
[16:35:47]: ▸ Copying SDWebImageTransition.h
[16:35:47]: ▸ Copying UIButton+WebCache.h
[16:35:47]: ▸ Copying UIImage+ForceDecode.h
[16:35:47]: ▸ Copying UIImage+GIF.h
[16:35:47]: ▸ Copying UIImage+MultiFormat.h
[16:35:47]: ▸ Copying UIImageView+HighlightedWebCache.h
[16:35:47]: ▸ Copying UIImageView+WebCache.h
[16:35:47]: ▸ Copying UIView+WebCache.h
[16:35:47]: ▸ Copying UIView+WebCacheOperation.h
[16:35:47]: Running Tests: ▸ Touching SDWebImage.framework
[16:35:47]: ▸ Building Pods/SDCAlertView [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling SDCAlertAction.m
[16:35:47]: ▸ Compiling SDCAlertCollectionViewCell.m
[16:35:47]: ▸ Compiling SDCAlertController.m
[16:35:47]: ▸ Compiling SDCAlertControllerCollectionViewFlowLayout.m
[16:35:47]: ▸ Compiling SDCAlertControllerDefaultVisualStyle.m
[16:35:47]: ▸ Compiling SDCAlertControllerScrollView.m
[16:35:47]: ▸ Compiling SDCAlertControllerTextFieldViewController.m
[16:35:47]: ▸ Compiling SDCAlertControllerTransition.m
[16:35:47]: ▸ Compiling SDCAlertControllerView.m
[16:35:47]: ▸ Compiling SDCAlertLabel.m
[16:35:47]: ▸ Compiling SDCAlertPresentationController.m
[16:35:47]: ▸ Compiling SDCAlertTextFieldTableViewCell.m
[16:35:47]: ▸ Compiling SDCAlertView-dummy.m
[16:35:47]: ▸ Compiling SDCAlertView.m
[16:35:47]: ▸ Compiling SDCAlertViewBackgroundView.m
[16:35:47]: ▸ Compiling SDCAlertViewContentView.m
[16:35:47]: ▸ Compiling SDCAlertViewController.m
[16:35:47]: ▸ Compiling SDCAlertViewCoordinator.m
[16:35:47]: ▸ Compiling SDCIntrinsicallySizedView.m
[16:35:47]: ▸ Compiling UIView+Parallax.m
[16:35:47]: ▸ Compiling UIViewController+Current.m
[16:35:47]: ▸ Compiling SDCAlertView_vers.c
[16:35:47]: ▸ Compiling SDCAlertAction.m
[16:35:47]: ▸ Compiling SDCAlertCollectionViewCell.m
[16:35:47]: ▸ Compiling SDCAlertController.m
[16:35:47]: ▸ Compiling SDCAlertControllerCollectionViewFlowLayout.m
[16:35:47]: ▸ Compiling SDCAlertControllerDefaultVisualStyle.m
[16:35:47]: ▸ Compiling SDCAlertControllerScrollView.m
[16:35:47]: ▸ Compiling SDCAlertControllerTextFieldViewController.m
[16:35:47]: ▸ Compiling SDCAlertControllerTransition.m
[16:35:47]: ▸ Compiling SDCAlertControllerView.m
[16:35:47]: ▸ Compiling SDCAlertLabel.m
[16:35:47]: ▸ Compiling SDCAlertPresentationController.m
[16:35:47]: ▸ Compiling SDCAlertTextFieldTableViewCell.m
[16:35:47]: ▸ Compiling SDCAlertView-dummy.m
[16:35:47]: ▸ Compiling SDCAlertView.m
[16:35:47]: ▸ Compiling SDCAlertViewBackgroundView.m
[16:35:47]: ▸ Compiling SDCAlertViewContentView.m
[16:35:47]: ▸ Compiling SDCAlertViewController.m
[16:35:47]: ▸ Compiling SDCAlertViewCoordinator.m
[16:35:47]: ▸ Compiling SDCIntrinsicallySizedView.m
[16:35:47]: ▸ Compiling UIView+Parallax.m
[16:35:47]: ▸ Compiling UIViewController+Current.m
[16:35:47]: ▸ Compiling SDCAlertView_vers.c
[16:35:47]: ▸ Linking SDCAlertView
[16:35:47]: ▸ Linking SDCAlertView
[16:35:47]: ▸ Generating 'SDCAlertView.framework.dSYM'
[16:35:47]: ▸ Copying SDCAlertCollectionViewCell.h
[16:35:47]: ▸ Copying SDCAlertController.h
[16:35:47]: ▸ Copying SDCAlertControllerCollectionViewFlowLayout.h
[16:35:47]: ▸ Copying SDCAlertControllerDefaultVisualStyle.h
[16:35:47]: ▸ Copying SDCAlertControllerScrollView.h
[16:35:47]: ▸ Copying SDCAlertControllerTextFieldViewController.h
[16:35:47]: ▸ Copying SDCAlertControllerTransition.h
[16:35:47]: ▸ Copying SDCAlertControllerView.h
[16:35:47]: ▸ Copying SDCAlertControllerVisualStyle.h
[16:35:47]: ▸ Copying SDCAlertLabel.h
[16:35:47]: ▸ Copying SDCAlertPresentationController.h
[16:35:47]: ▸ Copying SDCAlertTextFieldTableViewCell.h
[16:35:47]: ▸ Copying SDCAlertView-umbrella.h
[16:35:47]: ▸ Copying SDCAlertView.h
[16:35:47]: ▸ Copying SDCAlertViewBackgroundView.h
[16:35:47]: ▸ Copying SDCAlertViewContentView.h
[16:35:47]: ▸ Copying SDCAlertViewController.h
[16:35:47]: ▸ Copying SDCAlertViewCoordinator.h
[16:35:47]: ▸ Copying SDCAlertViewTransitioning.h
[16:35:47]: ▸ Copying SDCIntrinsicallySizedView.h
[16:35:47]: ▸ Copying UIView+Parallax.h
[16:35:47]: ▸ Copying UIViewController+Current.h
[16:35:47]: Running Tests: ▸ Touching SDCAlertView.framework
[16:35:47]: ▸ Building Pods/SVProgressHUD [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling SVIndefiniteAnimatedView.m
[16:35:47]: ▸ Compiling SVProgressAnimatedView.m
[16:35:47]: ▸ Compiling SVProgressHUD-dummy.m
[16:35:47]: ▸ Compiling SVProgressHUD.m
[16:35:47]: ▸ Compiling SVRadialGradientLayer.m
[16:35:47]: ▸ Compiling SVProgressHUD_vers.c
[16:35:47]: ▸ Compiling SVIndefiniteAnimatedView.m
[16:35:47]: ▸ Compiling SVProgressAnimatedView.m
[16:35:47]: ▸ Compiling SVProgressHUD-dummy.m
[16:35:47]: ▸ Compiling SVProgressHUD.m
[16:35:47]: ▸ Compiling SVRadialGradientLayer.m
[16:35:47]: ▸ Compiling SVProgressHUD_vers.c
[16:35:47]: ▸ Linking SVProgressHUD
[16:35:47]: ▸ Linking SVProgressHUD
[16:35:47]: ▸ Generating 'SVProgressHUD.framework.dSYM'
[16:35:47]: ▸ Copying SVIndefiniteAnimatedView.h
[16:35:47]: ▸ Copying SVProgressAnimatedView.h
[16:35:47]: ▸ Copying SVProgressHUD-umbrella.h
[16:35:47]: ▸ Copying SVProgressHUD.h
[16:35:47]: ▸ Copying SVRadialGradientLayer.h
[16:35:47]: ▸ Copying SVProgressHUD/SVProgressHUD/SVProgressHUD.bundle
[16:35:47]: Running Tests: ▸ Touching SVProgressHUD.framework
[16:35:47]: ▸ Building Pods/SimpleKeychain [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling A0SimpleKeychain+KeyPair.m
[16:35:47]: ▸ Compiling A0SimpleKeychain.m
[16:35:47]: ▸ Compiling SimpleKeychain-dummy.m
[16:35:47]: ▸ Compiling SimpleKeychain_vers.c
[16:35:47]: ▸ Compiling A0SimpleKeychain+KeyPair.m
[16:35:47]: ▸ Compiling A0SimpleKeychain.m
[16:35:47]: ▸ Compiling SimpleKeychain-dummy.m
[16:35:47]: ▸ Compiling SimpleKeychain_vers.c
[16:35:47]: ▸ Linking SimpleKeychain
[16:35:47]: ▸ Linking SimpleKeychain
[16:35:47]: ▸ Generating 'SimpleKeychain.framework.dSYM'
[16:35:47]: ▸ Copying A0SimpleKeychain+KeyPair.h
[16:35:47]: ▸ Copying A0SimpleKeychain.h
[16:35:47]: ▸ Copying SimpleKeychain-umbrella.h
[16:35:47]: ▸ Copying SimpleKeychain.h
[16:35:47]: Running Tests: ▸ Touching SimpleKeychain.framework
[16:35:47]: ▸ Building Pods/SwiftMessages-SwiftMessages [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Compiling CardView.xib
[16:35:47]: ▸ Compiling CenteredView.xib
[16:35:47]: ▸ Compiling MessageView.xib
[16:35:47]: ▸ Compiling MessageViewIOS8.xib
[16:35:47]: ▸ Compiling StatusLine.xib
[16:35:47]: ▸ Compiling TabView.xib
[16:35:47]: ▸ Processing ResourceBundle-SwiftMessages-Info.plist
[16:35:47]: Running Tests: ▸ Touching SwiftMessages.bundle
[16:35:47]: ▸ Building Pods/TPKeyboardAvoiding [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling TPKeyboardAvoiding-dummy.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingCollectionView.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingScrollView.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingTableView.m
[16:35:47]: ▸ Compiling UIScrollView+TPKeyboardAvoidingAdditions.m
[16:35:47]: ▸ Compiling TPKeyboardAvoiding_vers.c
[16:35:47]: ▸ Compiling TPKeyboardAvoiding-dummy.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingCollectionView.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingScrollView.m
[16:35:47]: ▸ Compiling TPKeyboardAvoidingTableView.m
[16:35:47]: ▸ Compiling UIScrollView+TPKeyboardAvoidingAdditions.m
[16:35:47]: ▸ Compiling TPKeyboardAvoiding_vers.c
[16:35:47]: ▸ Linking TPKeyboardAvoiding
[16:35:47]: ▸ Linking TPKeyboardAvoiding
[16:35:47]: ▸ Generating 'TPKeyboardAvoiding.framework.dSYM'
[16:35:47]: ▸ Copying TPKeyboardAvoiding-umbrella.h
[16:35:47]: ▸ Copying TPKeyboardAvoidingCollectionView.h
[16:35:47]: ▸ Copying TPKeyboardAvoidingScrollView.h
[16:35:47]: ▸ Copying TPKeyboardAvoidingTableView.h
[16:35:47]: ▸ Copying UIScrollView+TPKeyboardAvoidingAdditions.h
[16:35:47]: Running Tests: ▸ Touching TPKeyboardAvoiding.framework
[16:35:47]: ▸ Building Pods/UIScrollView-InfiniteScroll [Tests]
[16:35:47]: ▸ Check Dependencies
[16:35:47]: ▸ Processing Info.plist
[16:35:47]: ▸ Compiling UIScrollView+InfiniteScroll.m
[16:35:47]: ▸ Compiling UIScrollView-InfiniteScroll-dummy.m
[16:35:47]: ▸ Compiling UIScrollView_InfiniteScroll_vers.c
[16:35:47]: ▸ Compiling UIScrollView+InfiniteScroll.m
[16:35:47]: ▸ Compiling UIScrollView-InfiniteScroll-dummy.m
[16:35:47]: ▸ Compiling UIScrollView_InfiniteScroll_vers.c
[16:35:47]: ▸ Linking UIScrollView_InfiniteScroll
[16:35:47]: ▸ Linking UIScrollView_InfiniteScroll
[16:35:57]: ▸ Generating 'UIScrollView_InfiniteScroll.framework.dSYM'
[16:35:57]: ▸ Copying UIScrollView+InfiniteScroll.h
[16:35:57]: ▸ Copying UIScrollView-InfiniteScroll-umbrella.h
[16:35:57]: Running Tests: ▸ Touching UIScrollView_InfiniteScroll.framework
[16:35:57]: ▸ Building Pods/SwiftMessages [Tests]
[16:35:57]: ▸ Check Dependencies
[16:35:57]: ▸ Processing Info.plist
[16:35:57]: ▸ Compiling SwiftMessages-dummy.m
[16:35:57]: ▸ Compiling SwiftMessages_vers.c
[16:35:57]: ▸ Compiling SwiftMessages-dummy.m
[16:35:57]: ▸ Compiling SwiftMessages_vers.c
[16:35:57]: ▸ Linking SwiftMessages
[16:35:57]: ▸ Linking SwiftMessages
[16:36:02]: ▸ Generating 'SwiftMessages.framework.dSYM'
[16:36:03]: ▸ Copying /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/SwiftMessages/SwiftMessages.bundle
[16:36:04]: ▸ Copying SwiftMessages-umbrella.h
[16:36:05]: Running Tests: ▸ Touching SwiftMessages.framework
[16:36:05]: ▸ Building Pods/UITextView+Placeholder [Tests]
[16:36:05]: ▸ Check Dependencies
[16:36:05]: ▸ Processing Info.plist
[16:36:05]: ▸ Compiling UITextView+Placeholder-dummy.m
[16:36:05]: ▸ Compiling UITextView+Placeholder.m
[16:36:05]: ▸ Compiling UITextView_Placeholder_vers.c
[16:36:05]: ▸ Compiling UITextView+Placeholder-dummy.m
[16:36:05]: ▸ Compiling UITextView+Placeholder.m
[16:36:05]: ▸ Compiling UITextView_Placeholder_vers.c
[16:36:05]: ▸ Linking UITextView_Placeholder
[16:36:05]: ▸ Linking UITextView_Placeholder
[16:36:05]: ▸ Generating 'UITextView_Placeholder.framework.dSYM'
[16:36:05]: ▸ Copying UITextView+Placeholder-umbrella.h
[16:36:05]: ▸ Copying UITextView+Placeholder.h
[16:36:05]: Running Tests: ▸ Touching UITextView_Placeholder.framework
[16:36:05]: ▸ Building Pods/RealmSwift [Tests]
[16:36:05]: ▸ Check Dependencies
[16:36:05]: ▸ Processing Info.plist
[16:36:07]: ▸ Compiling RealmSwift-dummy.m
[16:36:07]: ▸ Compiling RealmSwift_vers.c
[16:36:07]: ▸ Compiling RealmSwift_vers.c
[16:36:07]: ▸ Compiling RealmSwift-dummy.m
[16:36:07]: ▸ Linking RealmSwift
[16:36:08]: ▸ Linking RealmSwift
[16:36:08]: ▸ Generating 'RealmSwift.framework.dSYM'
[16:36:08]: ▸ Copying RealmSwift-umbrella.h
[16:36:08]: Running Tests: ▸ Touching RealmSwift.framework
[16:36:08]: ▸ Building Pods/nanopb [Tests]
[16:36:08]: ▸ Check Dependencies
[16:36:08]: ▸ Processing Info.plist
[16:36:08]: ▸ Compiling nanopb-dummy.m
[16:36:08]: ▸ Compiling pb_common.c
[16:36:08]: ▸ Compiling pb_decode.c
[16:36:08]: ▸ Compiling pb_encode.c
[16:36:08]: ▸ Compiling nanopb_vers.c
[16:36:08]: ▸ Compiling nanopb-dummy.m
[16:36:08]: ▸ Compiling pb_common.c
[16:36:08]: ▸ Compiling pb_decode.c
[16:36:08]: ▸ Compiling pb_encode.c
[16:36:08]: ▸ Compiling nanopb_vers.c
[16:36:08]: ▸ Linking nanopb
[16:36:08]: ▸ Linking nanopb
[16:36:08]: ▸ Generating 'nanopb.framework.dSYM'
[16:36:08]: ▸ Copying nanopb-umbrella.h
[16:36:08]: ▸ Copying pb.h
[16:36:08]: ▸ Copying pb_common.h
[16:36:08]: ▸ Copying pb_decode.h
[16:36:08]: ▸ Copying pb_encode.h
[16:36:08]: Running Tests: ▸ Touching nanopb.framework
[16:36:08]: ▸ Building Pods/SimulatorStatusMagic [Tests]
[16:36:08]: ▸ Check Dependencies
[16:36:08]: ▸ Processing Info.plist
[16:36:08]: ▸ Compiling SDStatusBarManager.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost10_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost10_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost11_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost8_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost9_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost9_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPre8_3.m
[16:36:08]: ▸ Compiling SimulatorStatusMagic-dummy.m
[16:36:08]: ▸ Compiling SimulatorStatusMagic_vers.c
[16:36:08]: ▸ Compiling SDStatusBarManager.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost10_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost10_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost11_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost8_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost9_0.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPost9_3.m
[16:36:08]: ▸ Compiling SDStatusBarOverriderPre8_3.m
[16:36:08]: ▸ Compiling SimulatorStatusMagic-dummy.m
[16:36:08]: ▸ Compiling SimulatorStatusMagic_vers.c
[16:36:08]: ▸ Linking SimulatorStatusMagic
[16:36:08]: ▸ Linking SimulatorStatusMagic
[16:36:08]: ▸ Generating 'SimulatorStatusMagic.framework.dSYM'
[16:36:08]: ▸ Copying SDStatusBarManager.h
[16:36:08]: ▸ Copying SDStatusBarOverrider.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost10_0.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost10_3.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost11_0.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost9_0.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost8_3.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPost9_3.h
[16:36:08]: ▸ Copying SDStatusBarOverriderPre8_3.h
[16:36:08]: ▸ Copying SimulatorStatusMagic-umbrella.h
[16:36:08]: Running Tests: ▸ Touching SimulatorStatusMagic.framework
[16:36:08]: ▸ Building Pods/ObjectMapper+Realm [Tests]
[16:36:08]: ▸ Check Dependencies
[16:36:08]: ▸ Processing Info.plist
[16:36:08]: ▸ Compiling ListTransform.swift
[16:36:09]: ▸ Compiling ListTransform.swift
[16:36:09]: ▸ Compiling ObjectMapper+Realm-dummy.m
[16:36:09]: ▸ Compiling ObjectMapper_Realm_vers.c
[16:36:09]: ▸ Compiling ObjectMapper+Realm-dummy.m
[16:36:09]: ▸ Compiling ObjectMapper_Realm_vers.c
[16:36:09]: ▸ Linking ObjectMapper_Realm
[16:36:09]: ▸ Linking ObjectMapper_Realm
[16:36:09]: ▸ Generating 'ObjectMapper_Realm.framework.dSYM'
[16:36:09]: ▸ Copying ObjectMapper+Realm-umbrella.h
[16:36:09]: Running Tests: ▸ Touching ObjectMapper_Realm.framework
[16:36:09]: ▸ Building Pods/Pods-caronae-ios-Caronae [Tests]
[16:36:09]: ▸ Check Dependencies
[16:36:09]: ▸ Processing Info.plist
[16:36:09]: ▸ Compiling Pods-caronae-ios-Caronae-dummy.m
[16:36:11]: ▸ Compiling Pods_caronae_ios_Caronae_vers.c
[16:36:11]: ▸ Compiling Pods-caronae-ios-Caronae-dummy.m
[16:36:11]: ▸ Compiling Pods_caronae_ios_Caronae_vers.c
[16:36:11]: ▸ Copying Pods-caronae-ios-Caronae-umbrella.h
[16:36:11]: Running Tests: ▸ Touching Pods_caronae_ios_Caronae.framework
[16:36:11]: ▸ Building Pods/Pods-caronae-ios-Caronae UITests [Tests]
[16:36:11]: ▸ Check Dependencies
[16:36:11]: ▸ Processing Info.plist
[16:36:11]: ▸ Compiling Pods-caronae-ios-Caronae\ UITests-dummy.m
[16:36:11]: ▸ Compiling Pods_caronae_ios_Caronae_UITests_vers.c
[16:36:11]: ▸ Compiling Pods-caronae-ios-Caronae\ UITests-dummy.m
[16:36:12]: ▸ Compiling Pods_caronae_ios_Caronae_UITests_vers.c
[16:36:12]: ▸ Copying Pods-caronae-ios-Caronae\ UITests-umbrella.h
[16:36:12]: Running Tests: ▸ Touching Pods_caronae_ios_Caronae_UITests.framework
[16:36:12]: ▸ Building Caronae/Caronae [Tests]
[16:36:12]: ▸ Check Dependencies
[16:36:12]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:36:12]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:36:12]: ▸ Compiling UserService.swift
[16:36:14]: ▸ ⚠️  /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/AFNetworking/AFNetworking.framework/Headers/AFNetworkReachabilityManager.h:115:1: conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'
[16:36:14]: ▸ - (nullable instancetype)init NS_UNAVAILABLE;
[16:36:14]: ▸             ^
[16:36:14]: ▸ Compiling NotificationService.swift
[16:36:14]: ▸ Compiling RidesHistoryViewController.swift
[16:36:14]: ▸ Compiling NotificationParser.swift
[16:36:14]: ▸ Compiling AppDelegate.swift
[16:36:15]: ▸ Compiling Ride.swift
[16:36:15]: ▸ Compiling AppDelegate+Notifications.swift
[16:36:15]: ▸ Compiling FalaeViewController.swift
[16:36:16]: ▸ Compiling HubsSelectionViewController.swift
[16:36:16]: ▸ Compiling Date+isInTheFuture.swift
[16:36:16]: ▸ Compiling AppDelegate+Realm.swift
[16:36:16]: ▸ Compiling String+onlyDigits.swift
[16:36:16]: ▸ Compiling Place.swift
[16:36:16]: ▸ Compiling RideListController.swift
[16:36:17]: ▸ Compiling CaronaeAPIHTTPSessionManager.swift
[16:36:17]: ▸ Compiling Message.swift
[16:36:17]: ▸ Compiling RideCell.swift
[16:36:17]: ▸ Compiling SelectionCell.swift
[16:36:17]: ▸ Compiling Campus.swift
[16:36:17]: ▸ Compiling PlaceService.swift
[16:36:18]: ▸ Compiling Date+nextHour.swift
[16:36:18]: ▸ Compiling FilterParameters.swift
[16:36:18]: ▸ Compiling AllRidesViewController.swift
[16:36:18]: ▸ Compiling DateTimeTransform.swift
[16:36:18]: ▸ Compiling PhoneNumberActionSheet.swift
[16:36:19]: ▸ Compiling CaronaeMessageNotification.swift
[16:36:19]: ▸ Compiling CaronaeGradientButton.swift
[16:36:19]: ▸ Compiling UIColor+hex.swift
[16:36:19]: ▸ Compiling CaronaeAPIRequestSerializer.swift
[16:36:19]: ▸ Compiling ProfileViewController.swift
[16:36:20]: ▸ Compiling CaronaeConstants.swift
[16:36:20]: ▸ Compiling MenuViewController.swift
[16:36:20]: ▸ Compiling PaginationState.swift
[16:36:20]: ▸ Compiling ChatService.swift
[16:36:20]: ▸ Compiling WelcomeViewController.swift
[16:36:20]: ▸ Compiling FilterRideViewController.swift
[16:36:21]: ▸ Compiling MyRidesViewController.swift
[16:36:21]: ▸ Compiling RideService.swift
[16:36:21]: ▸ Compiling SearchResultsViewController.swift
[16:36:21]: ▸ Compiling LoginViewController.swift
[16:36:21]: ▸ Compiling CaronaeError.swift
[16:36:22]: ▸ Compiling RideViewController+rideActions.swift
[16:36:22]: ▸ Compiling SearchRideViewController.swift
[16:36:22]: ▸ Compiling UniversalLinkParser.swift
[16:36:22]: ▸ Compiling CaronaeAPIResponseSerializer.swift
[16:36:22]: ▸ Compiling NeighborhoodSelectionViewController.swift
[16:36:23]: ▸ Compiling EditProfileViewController.swift
[16:36:24]: ▸ Compiling UIViewController+isVisible.swift
[16:36:24]: ▸ Compiling User.swift
[16:36:24]: ▸ Compiling RideViewController.swift
[16:36:25]: ▸ Compiling SelectionViewController.swift
[16:36:25]: ▸ Compiling String+validation.swift
[16:36:25]: ▸ Compiling WebViewController.swift
[16:36:25]: ▸ Compiling DeepLinkManager.swift
[16:36:25]: ▸ Compiling Notification.swift
[16:36:25]: ▸ Compiling DeeplinkNavigator.swift
[16:36:25]: ▸ Compiling AppDelegate+Firebase.swift
[16:36:25]: ▸ Compiling CreateRideViewController.swift
[16:36:26]: ▸ Compiling Zone.swift
[16:36:26]: ▸ Compiling Array+compactString.swift
[16:36:26]: ▸ Compiling AuthenticationController.swift
[16:36:26]: ▸ Compiling UIColor+Caronae.swift
[16:36:26]: ▸ Compiling String+capitalizedAfter.swift
[16:36:26]: ▸ Compiling ZoneSelectionInputViewController.swift
[16:36:26]: ▸ Compiling ChatViewController.swift
[16:36:27]: ▸ Compiling FalaeService.swift
[16:36:27]: ▸ Compiling RiderCell.swift
[16:36:28]: ▸ Compiling JoinRequestCell.m
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:36:30]: ▸ ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:36:30]: ▸                                                            ^
[16:36:30]: ▸ Compiling TabBarController.m
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:36:30]: ▸                                                                                                       ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:36:30]: ▸                                                                                                       ^
[16:36:30]: ▸ Compiling UIImageView+crn_setImageWithURL.m
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.h:6:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler;
[16:36:30]: ▸                                                            ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:36:30]: ▸                                                            ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Categories/UIImageView+crn_setImageWithURL.m:13:60: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ - (void)crn_setImageWithURL:(NSURL *)url completed:(void(^)())completionHandler {
[16:36:30]: ▸                                                                                                       ^
[16:36:30]: ▸ Compiling CaronaeAlertController.m
[16:36:30]: ▸ ⚠️  /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/SDCAlertView/SDCAlertView.framework/Headers/SDCAlertView.h:92:54: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ @property (nonatomic, copy) void (^didPresentHandler)();
[16:36:30]: ▸                                                            ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.h:6:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler;
[16:36:30]: ▸                                                      ^
[16:36:30]: ▸ ⚠️  /Users/distiller/project/Caronae/Extras/CaronaeAlertController.m:19:103: this block declaration is not a prototype [-Wstrict-prototypes]
[16:36:30]: ▸ + (instancetype)presentOkAlertWithTitle:(NSString *)title message:(NSString *)message handler:(void(^)())handler {
[16:36:30]: ▸                                                                                                       ^
[16:36:30]: ▸ Compiling CALayer+UIColor.m
[16:36:30]: ▸ Compiling UIApplication+topViewController.m
[16:36:30]: ▸ Compiling CaronaeTextField.m
[16:36:30]: ▸ Compiling UIWindow+replaceRootViewController.m
[16:36:30]: ▸ Linking Caronae
[16:36:30]: ▸ Copying GoogleService-Info.plist
[16:36:30]: ▸ Compiling WelcomeViewController.xib
[16:36:31]: ▸ Compiling ZoneSelectionInput.xib
[16:36:31]: ▸ Compiling RideCell.xib
[16:36:31]: ▸ Compiling SelectionCell.xib
[16:36:33]: ▸ Compiling RideListController.xib
[16:36:33]: ▸ Copying Caronae/Sounds/beep_beep.wav
[16:36:33]: ▸ Copying Settings.bundle
[16:36:33]: ▸ Compiling JoinRequestCell.xib
[16:36:33]: ▸ Copying Caronae/Sounds/beep.wav
[16:36:33]: ▸ Compiling Login.storyboard
[16:36:33]: ▸ Compiling Main.storyboard
[16:36:42]: ▸ Compiling LaunchScreen.storyboard
[16:36:42]: ▸ Processing Info.plist
[16:36:42]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:36:48]: Running Tests: ▸ Touching Caronae.app
[16:36:48]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/Caronae.app
[16:36:48]: ▸ Building Caronae/Caronae UITests [Tests]
[16:36:48]: ▸ Check Dependencies
[16:36:48]: ▸ Processing Info.plist
[16:36:48]: ▸ Copying /Applications/Xcode-9.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/PrivateFrameworks/XCTAutomationSupport.framework
[16:36:48]: ▸ Copying /Applications/Xcode-9.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework
[16:36:48]: ▸ Preprocessing /Applications/Xcode-9.3.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Agents/XCTRunner.app/Info.plist
[16:36:48]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:36:48]: ▸ Compiling Caronae_UITests.swift
[16:36:52]: ▸ Compiling SnapshotHelper.swift
[16:36:53]: ▸ Linking Caronae\
[16:36:53]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:36:59]: Running Tests: ▸ Touching Caronae\ UITests.xctest
[16:36:59]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/Caronae\ UITests-Runner.app/PlugIns/Caronae\ UITests.xctest
[16:38:25]: ▸ Test Succeeded
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-0_AllRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-1_CreateRide.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-2_SignIn.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-3_Ride.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-4_MyRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-5_Chat.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-0_AllRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-1_CreateRide.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-2_SignIn.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-3_Ride.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-4_MyRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone 8-5_Chat.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-0_AllRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-1_CreateRide.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-2_SignIn.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-3_Ride.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-4_MyRides.png'...
[16:38:30]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone X-5_Chat.png'...
[16:38:30]: Patching simulators '/Users/distiller/Library/Preferences/com.apple.iphonesimulator.plist' to scale to 100%
[16:38:34]: Erasing iPhone SE...
[16:38:36]: Localizing iPhone SE (AppleLocale=pt_BR AppleLanguages=[pt-BR])
[16:38:36]: Running snapshot on: iPhone SE
[16:38:36]: $ set -o pipefail && xcodebuild -workspace ./Caronae.xcworkspace -scheme Caronae -derivedDataPath '/var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt' -destination 'platform=iOS Simulator,name=iPhone SE,OS=11.3' FASTLANE_SNAPSHOT=YES build test | tee -a /Users/distiller/project/output/buildlogs/snapshot/Caronae-Caronae.log | xcpretty 
[16:38:36]: ▸ Loading...
[16:38:39]: ▸ Building Pods/Bolts [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:39]: ▸ Building Pods/GoogleToolboxForMac [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:39]: ▸ Building Pods/ActionSheetPicker-3.0 [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:39]: ▸ Building Pods/AFNetworking [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:39]: ▸ Building Pods/InputMask [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:39]: ▸ Building Pods/FBSDKCoreKit [Debug]
[16:38:39]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/JSQSystemSoundPlayer [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/MIBadgeButton-Swift [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/JSQMessagesViewController [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/ObjectMapper [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/Realm [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/Protobuf [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/FBSDKLoginKit [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/RBBAnimation [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SDCAutoLayout [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SDWebImage [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SVProgressHUD [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SDCAlertView [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/RealmSwift [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SimpleKeychain [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/ObjectMapper+Realm [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SwiftMessages-SwiftMessages [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/TPKeyboardAvoiding [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/UIScrollView-InfiniteScroll [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/UITextView+Placeholder [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/nanopb [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/SwiftMessages [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Pods/Pods-caronae-ios-Caronae [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Building Caronae/Caronae [Debug]
[16:38:40]: ▸ Check Dependencies
[16:38:40]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:38:40]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:38:43]: ▸ Processing Info.plist
[16:38:43]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:38:47]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Debug-iphonesimulator/Caronae.app
[16:38:48]: ▸ Build Succeeded
[16:38:48]: ▸ 2018-04-24 16:38:48.903 xcodebuild[10346:41205] [MT] IDETestOperationsObserverDebug: (5A978ED4-1366-4A51-BDFE-E69C0C71AA77) Beginning test session Caronae UITests-5A978ED4-1366-4A51-BDFE-E69C0C71AA77 at 2018-04-24 16:38:48.903 with Xcode 9E145 on target <DVTiPhoneSimulator: 0x7f969fff68a0> {
[16:38:48]: ▸ SimDevice: iPhone SE (817A3577-C38B-422B-99A2-C5F9A08BD44E, iOS 11.3, Booting)
[16:38:48]: ▸ } (11.3 (15E217))
[16:38:48]: ▸ 2018-04-24 16:38:48.904 xcodebuild[10346:41210]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[16:38:48]: ▸ /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/com.apple.dt.XCTest/IDETestRunSession-C6BFB4BC-3334-4E40-8204-81F7CAFE86B4/Caronae UITests-309A7C4C-70E1-4F8A-8F3E-78CD30180AD7/Session-Caronae UITests-2018-04-24_163848-R6krID.log
[16:38:50]: ▸ Building Pods/AFNetworking [Tests]
[16:38:50]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/ActionSheetPicker-3.0 [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/Bolts [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/GoogleToolboxForMac [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/InputMask [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/JSQSystemSoundPlayer [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/MIBadgeButton-Swift [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:51]: ▸ Building Pods/JSQMessagesViewController [Tests]
[16:38:51]: ▸ Check Dependencies
[16:38:52]: ▸ Building Pods/FBSDKCoreKit [Tests]
[16:38:52]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/ObjectMapper [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/Realm [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/Protobuf [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/RBBAnimation [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SDCAutoLayout [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SDWebImage [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SVProgressHUD [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SimpleKeychain [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SwiftMessages-SwiftMessages [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SDCAlertView [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SwiftMessages [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/TPKeyboardAvoiding [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/RealmSwift [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/UIScrollView-InfiniteScroll [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/UITextView+Placeholder [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/FBSDKLoginKit [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/nanopb [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/ObjectMapper+Realm [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/SimulatorStatusMagic [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Pods/Pods-caronae-ios-Caronae [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Building Caronae/Caronae [Tests]
[16:38:53]: ▸ Check Dependencies
[16:38:53]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:38:53]: ▸ Running script 'Convert TODOs and FIXMEs to warnings and ERRORs to errors'
[16:38:57]: ▸ Processing Info.plist
[16:38:57]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:39:08]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/Caronae.app
[16:39:09]: ▸ Building Pods/Pods-caronae-ios-Caronae UITests [Tests]
[16:39:09]: ▸ Check Dependencies
[16:39:09]: ▸ Building Caronae/Caronae UITests [Tests]
[16:39:09]: ▸ Check Dependencies
[16:39:09]: ▸ Running script '[CP] Check Pods Manifest.lock'
[16:39:09]: ▸ Running script '[CP] Embed Pods Frameworks'
[16:39:14]: ▸ Signing /var/folders/gk/lkr9pm5x039fx6d3j9r52rv80000gn/T/snapshot_derived20180424-2899-15d6nnt/Build/Products/Tests-iphonesimulator/Caronae\ UITests-Runner.app/PlugIns/Caronae\ UITests.xctest
[16:40:22]: ▸ Test Succeeded
[16:40:26]: ▸ All tests
[16:40:26]: ▸ Test Suite Caronae UITests.xctest started
[16:40:26]: ▸ Caronae_UITests
[16:40:26]: ▸ ✓ testTakeScreenshots (56.109 seconds)
[16:40:26]: ▸ 	 Executed 1 test, with 0 failures (0 unexpected) in 56.109 (56.113) seconds
[16:40:26]: ▸ 
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-0_AllRides.png'...
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-1_CreateRide.png'...
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-2_SignIn.png'...
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-3_Ride.png'...
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-4_MyRides.png'...
[16:40:26]: Copying '/Users/distiller/project/screenshots/pt-BR/iPhone SE-5_Chat.png'...

+---------------+-------+
|   snapshot results    |
+---------------+-------+
| Device        | pt-BR |
+---------------+-------+
| iPhone X      |  💚   |
| iPhone 8      |  💚   |
| iPhone 8 Plus |  💚   |
| iPhone SE     |  💚   |
+---------------+-------+

[16:40:26]: Generating HTML Report
[16:40:26]: Successfully created HTML file with an overview of all the screenshots: '/Users/distiller/project/screenshots/screenshots.html'
[16:40:29]: -------------------------------
[16:40:29]: --- Step: frame_screenshots ---
[16:40:29]: -------------------------------
[16:40:29]: Framing screenshots at path /Users/distiller/project/screenshots (via frameit)
[16:40:29]: Using device frames version 'latest'
[16:40:29]: --------------------------------
[16:40:29]: --- Device frames disclaimer ---
[16:40:29]: --------------------------------
[16:40:29]: All used device frames are available via Facebook Design: http://facebook.design/devices
[16:40:29]: ----------------------------------------
[16:40:29]: While Facebook has redrawn and shares these assets for the benefit
[16:40:29]: of the design community, Facebook does not own any of the underlying
[16:40:29]: product or user interface designs.
[16:40:29]: By accessing these assets, you agree to obtain all necessary permissions
[16:40:29]: from the underlying rights holders and/or adhere to any applicable brand
[16:40:29]: use guidelines before using them.
[16:40:29]: Facebook disclaims all express or implied warranties with respect to these assets, including
[16:40:29]: non-infringement of intellectual property rights.
[16:40:29]: ----------------------------------------
[16:40:29]: Downloading device frames to '/Users/distiller/.fastlane/frameit/latest'
[16:40:29]: Downloading file from 'https://fastlane.github.io/frameit-frames/latest/version.txt' ...
[16:40:30]: Using frame version '1509566139', you can optionally lock that version in your Framefile.json using `device_frame_version`
[16:40:30]: Downloading file from 'https://fastlane.github.io/frameit-frames/latest/files.json' ...
[16:40:30]: Downloading 1 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205c%20Blue.png' ...
[16:40:30]: Downloading 2 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205c%20Green.png' ...
[16:40:30]: Downloading 3 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205c%20Red.png' ...
[16:40:30]: Downloading 4 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205c%20White.png' ...
[16:40:30]: Downloading 5 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205c%20Yellow.png' ...
[16:40:30]: Downloading 6 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205s%20Gold.png' ...
[16:40:31]: Downloading 7 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205s%20Silver.png' ...
[16:40:31]: Downloading 8 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%205s%20Space%20Gray.png' ...
[16:40:31]: Downloading 9 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Gold.png' ...
[16:40:31]: Downloading 10 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Rose%20Gold.png' ...
[16:40:31]: Downloading 11 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Silver.png' ...
[16:40:31]: Downloading 12 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Space%20Gray.png' ...
[16:40:31]: Downloading 13 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Plus%20Gold.png' ...
[16:40:32]: Downloading 14 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Plus%20Rose%20Gold.png' ...
[16:40:32]: Downloading 15 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Plus%20Silver.png' ...
[16:40:32]: Downloading 16 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%206s%20Plus%20Space%20Gray.png' ...
[16:40:32]: Downloading 17 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Gold.png' ...
[16:40:32]: Downloading 18 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Jet%20Black.png' ...
[16:40:33]: Downloading 19 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Matte%20Black.png' ...
[16:40:33]: Downloading 20 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Rose%20Gold.png' ...
[16:40:33]: Downloading 21 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Silver.png' ...
[16:40:33]: Downloading 22 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Plus%20Gold.png' ...
[16:40:33]: Downloading 23 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Plus%20Jet%20Black.png' ...
[16:40:33]: Downloading 24 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Plus%20Matte%20Black.png' ...
[16:40:33]: Downloading 25 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Plus%20Rose%20Gold.png' ...
[16:40:34]: Downloading 26 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%207%20Plus%20Silver.png' ...
[16:40:34]: Downloading 27 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Gold.png' ...
[16:40:34]: Downloading 28 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Silver.png' ...
[16:40:34]: Downloading 29 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Space%20Gray.png' ...
[16:40:34]: Downloading 30 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Plus%20Gold.png' ...
[16:40:34]: Downloading 31 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Plus%20Silver.png' ...
[16:40:34]: Downloading 32 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%208%20Plus%20Space%20Gray.png' ...
[16:40:35]: Downloading 33 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20SE%20Gold.png' ...
[16:40:35]: Downloading 34 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20SE%20Rose%20Gold.png' ...
[16:40:35]: Downloading 35 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20SE%20Silver.png' ...
[16:40:35]: Downloading 36 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20SE%20Space%20Gray.png' ...
[16:40:35]: Downloading 37 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20X%20Silver.png' ...
[16:40:35]: Downloading 38 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPhone%20X%20Space%20Gray.png' ...
[16:40:35]: Downloading 39 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple-Macbook-Gold.png' ...
[16:40:35]: Downloading 40 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple-Macbook-Space-Gray.png' ...
[16:40:36]: Downloading 41 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Air%202%20Gold.png' ...
[16:40:36]: Downloading 42 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Air%202%20Silver.png' ...
[16:40:36]: Downloading 43 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Air%202%20Space%20Gray.png' ...
[16:40:36]: Downloading 44 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Mini%204%20Gold.png' ...
[16:40:36]: Downloading 45 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Mini%204%20Silver.png' ...
[16:40:37]: Downloading 46 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Mini%204%20Space%20Gray.png' ...
[16:40:37]: Downloading 47 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Pro%20Gold.png' ...
[16:40:37]: Downloading 48 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Pro%20Silver.png' ...
[16:40:37]: Downloading 49 of 49 files from 'https://fastlane.github.io/frameit-frames/latest/Apple%20iPad%20Pro%20Space%20Gray.png' ...
[16:40:37]: Downloading file from 'https://fastlane.github.io/frameit-frames/latest/offsets.json' ...
[16:40:37]: Successfully downloaded all required image assets
[16:40:37]: Framing screenshot './pt-BR/iPhone 8 Plus-0_AllRides.png'
[16:40:53]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-0_AllRides_framed.png'
[16:40:53]: Framing screenshot './pt-BR/iPhone 8 Plus-1_CreateRide.png'
[16:41:08]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-1_CreateRide_framed.png'
[16:41:08]: Framing screenshot './pt-BR/iPhone 8 Plus-2_SignIn.png'
[16:41:23]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-2_SignIn_framed.png'
[16:41:23]: Framing screenshot './pt-BR/iPhone 8 Plus-3_Ride.png'
[16:41:38]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-3_Ride_framed.png'
[16:41:38]: Framing screenshot './pt-BR/iPhone 8 Plus-4_MyRides.png'
[16:41:53]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-4_MyRides_framed.png'
[16:41:53]: Framing screenshot './pt-BR/iPhone 8 Plus-5_Chat.png'
[16:42:09]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8 Plus-5_Chat_framed.png'
[16:42:09]: Framing screenshot './pt-BR/iPhone 8-0_AllRides.png'
[16:42:15]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-0_AllRides_framed.png'
[16:42:15]: Framing screenshot './pt-BR/iPhone 8-1_CreateRide.png'
[16:42:21]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-1_CreateRide_framed.png'
[16:42:21]: Framing screenshot './pt-BR/iPhone 8-2_SignIn.png'
[16:42:27]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-2_SignIn_framed.png'
[16:42:27]: Framing screenshot './pt-BR/iPhone 8-3_Ride.png'
[16:42:34]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-3_Ride_framed.png'
[16:42:34]: Framing screenshot './pt-BR/iPhone 8-4_MyRides.png'
[16:42:39]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-4_MyRides_framed.png'
[16:42:39]: Framing screenshot './pt-BR/iPhone 8-5_Chat.png'
[16:42:45]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone 8-5_Chat_framed.png'
[16:42:45]: Framing screenshot './pt-BR/iPhone SE-0_AllRides.png'
[16:42:50]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-0_AllRides_framed.png'
[16:42:50]: Framing screenshot './pt-BR/iPhone SE-1_CreateRide.png'
[16:42:54]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-1_CreateRide_framed.png'
[16:42:54]: Framing screenshot './pt-BR/iPhone SE-2_SignIn.png'
[16:42:58]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-2_SignIn_framed.png'
[16:42:58]: Framing screenshot './pt-BR/iPhone SE-3_Ride.png'
[16:43:03]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-3_Ride_framed.png'
[16:43:03]: Framing screenshot './pt-BR/iPhone SE-4_MyRides.png'
[16:43:07]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-4_MyRides_framed.png'
[16:43:07]: Framing screenshot './pt-BR/iPhone SE-5_Chat.png'
[16:43:11]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone SE-5_Chat_framed.png'
[16:43:11]: Framing screenshot './pt-BR/iPhone X-0_AllRides.png'
[16:43:25]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-0_AllRides_framed.png'
[16:43:25]: Framing screenshot './pt-BR/iPhone X-1_CreateRide.png'
[16:43:40]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-1_CreateRide_framed.png'
[16:43:40]: Framing screenshot './pt-BR/iPhone X-2_SignIn.png'
[16:43:54]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-2_SignIn_framed.png'
[16:43:54]: Framing screenshot './pt-BR/iPhone X-3_Ride.png'
[16:44:08]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-3_Ride_framed.png'
[16:44:08]: Framing screenshot './pt-BR/iPhone X-4_MyRides.png'
[16:44:22]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-4_MyRides_framed.png'
[16:44:22]: Framing screenshot './pt-BR/iPhone X-5_Chat.png'
[16:44:36]: Added frame: '/Users/distiller/project/screenshots/pt-BR/iPhone X-5_Chat_framed.png'
[16:44:36]: Cruising back to lane 'ios deploy' 🚘
[16:44:36]: --------------------------------
[16:44:36]: --- Step: get_version_number ---
[16:44:36]: --------------------------------
[16:44:36]: ---------------------------------
[16:44:36]: --- Step: upload_to_app_store ---
[16:44:36]: ---------------------------------
[16:44:37]: Login to iTunes Connect (circleci@caronae.org)
[16:44:40]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.93.1 Summary                            |
+--------------------------------------+--------------------------------------+
| submit_for_review                    | true                                 |
| force                                | true                                 |
| app_version                          | 1.4.0                                |
| build_number                         | 539                                  |
| screenshots_path                     | /Users/distiller/project/screenshots |
| metadata_path                        | ./fastlane/metadata                  |
| username                             | circleci@caronae.org                 |
| app_identifier                       | br.ufrj.caronae                      |
| edit_live                            | false                                |
| platform                             | ios                                  |
| skip_binary_upload                   | false                                |
| use_live_version                     | false                                |
| skip_screenshots                     | false                                |
| skip_metadata                        | false                                |
| skip_app_version_update              | false                                |
| reject_if_possible                   | false                                |
| automatic_release                    | false                                |
| phased_release                       | false                                |
| team_id                              | 118108962                            |
| dev_portal_team_id                   | 5JHLCV2DBL                           |
| dev_portal_team_name                 | Mario A C Raduan                     |
| overwrite_screenshots                | false                                |
| run_precheck_before_submit           | true                                 |
| precheck_default_rule_level          | warn                                 |
| ignore_language_directory_validation | false                                |
| precheck_include_in_app_purchases    | true                                 |
+--------------------------------------+--------------------------------------+

[16:44:41]: Making sure the latest version on iTunes Connect matches '1.4.0' from the ipa file...
[16:44:42]: '1.4.0' is the latest version on iTunes Connect
+---------------------------+--------------------------------------------------------+
|                                    Lane Context                                    |
+---------------------------+--------------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                    |
| PLATFORM_NAME             | ios                                                    |
| LANE_NAME                 | ios deploy                                             |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/distiller/Library/Keychains/login.keychain-db" |
| SNAPSHOT_SCREENSHOTS_PATH | /Users/distiller/project/screenshots                   |
| VERSION_NUMBER            | 1.4.0                                                  |
+---------------------------+--------------------------------------------------------+
[16:44:43]: Unsupported directory name(s) for screenshots/metadata in '/Users/distiller/project/screenshots': fonts
Valid directory names are: ["da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv", "th", "tr", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]

Enable 'ignore_language_directory_validation' to prevent this validation from happening

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | default_platform                    | 0           |
| 2    | setup_circle_ci                     | 0           |
| 3    | Switch to ios take_screenshots lane | 0           |
| 4    | capture_ios_screenshots             | 841         |
| 5    | frame_screenshots                   | 246         |
| 6    | get_version_number                  | 0           |
| 💥   | upload_to_app_store                 | 6           |
+------+-------------------------------------+-------------+

[16:44:43]: fastlane finished with errors

[!] Unsupported directory name(s) for screenshots/metadata in '/Users/distiller/project/screenshots': fonts
Valid directory names are: ["da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "id", "it", "ja", "ko", "ms", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv", "th", "tr", "vi", "zh-Hans", "zh-Hant", "appleTV", "iMessage", "default"]

Enable 'ignore_language_directory_validation' to prevent this validation from happening
Exited with code 1
 </pre>
</details>

### Environment

I'm using CircleCI and the project is completely opensource, so any info can be found in the repository: https://github.com/caronae/caronae-ios

EDIT:  Adding the output of `fastlane env`

<details>
<pre>
bash-3.2$ fastlane env
[✔] 🚀 
[11:04:16]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:04:17]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.3                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.16.3                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.3 (17D102)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode-9.3.app/Contents/Developer/                |
| Xcode Version               | 9.3                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.88.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.2        |
| CFPropertyList            | 3.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.4        |
| xcodeproj                 | 1.5.7        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.4.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.14.0       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.1        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.1       |
| faraday_middleware        | 0.12.2       |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
</details>

*generated on:* **2018-05-24**
</details>
[11:04:17]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[11:04:17]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
</pre>
</details>

### PR DESCRIPTION
**Pull request by piohhmy**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Frameit [documentation](https://docs.fastlane.tools/actions/frameit/#example) uses a special folder of "fonts" in the screenshots dir to store the custom fonts for framed screenshots.  Previously, Fastlane deliver would output an error if this "fonts" directory was present leaving the user to either 
1) Put the "fonts" directory elsewhere (not consistent with the documentation) or
2) Use the `ignore_language_directory_validation` (removes the safety check provided by deliver)

This fixes #12375

Tested by:
1) Adding an automated test. 
2) Created a sample project with the fonts dir present and ran `fastlane deliver` before and after the change to verify the change works as expected

### Description

This PR adds "fonts" to the set of exception directories for Deliver to ignore when looking for the language folders.

### CODE REVIEW

**Comment by piohhmy** [comment]
I signed it!

File: deliver/lib/deliver/loader.rb [hunk 1]
```diff
@@ -14,10 +14,12 @@ module Loader
 
     SPECIAL_DIR_NAMES = [APPLE_TV_DIR_NAME, IMESSAGE_DIR_NAME, DEFAULT_DIR_NAME].freeze
 
-    # If the user also uses `supply` in the same project, an 'android' folder might exist
+    # Some exception directories may exist from other projects that should not be iterated through
```
Comment (janpio) [inline deliver/lib/deliver/loader.rb]: "other projects"? Other "actions" or "tools" would probably be better.

**Review by janpio — APPROVED** [review]
👍

**Comment by piohhmy** [comment]
Thanks for the code review @janpio!  Anything else to do before this gets merged in?

**Comment by janpio** [comment]
Nope, I initially didn't want to merge this myself - but why bother. You're building on stuff I wrote anyway ;)

🥇 🦄 Congratz on your first PR here! 🦄 🥇
