### PR TITLE
[deliver, pilot] Add provider_public_id option for altool uploads

### LINKED ISSUE #29820: Xcode26.2 altool fails with "Failed to determine the appleID from bundleID" message
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
In Xcode26.2, altool is giving error when I upload a build. Both `appstore` and `pilot` commands are failing with the same error message:

I even tried passing `apple_id` parameter for the commands but it still fails. Only thing that worked is adding the following to the Fastfile but it should only be a temp workaround for now until this issue is fixed.
```
before_all do
  ENV["DELIVER_ALTOOL_ADDITIONAL_UPLOAD_PARAMETERS"] = "--use-old-altool"  
end 
```

##### Command executed
`appstore` and `pilot`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[12:34:26]: Login successful
[12:34:27]: Ready to upload new build to TestFlight (App: `XXX`)...
unexpected character: '}
' at line 1 column 3
[12:34:38]: Going to upload updated app to App Store Connect
[12:34:38]: This might take a few minutes. Please don't interrupt the script.
[12:35:23]: [altool] Running altool at path '/Applications/Xcode262.app/Contents/SharedFrameworks/ContentDelivery.framework/Resources/altool'...
[12:35:23]: [altool] 
[12:35:23]: [altool] 2025-12-19 12:35:23.716 ERROR: [altool.6000031344C0] Failed to determine the appleID from bundleID `XXX` with platform IOS. The server returned unexpected content. (-19237) (12)
[12:35:23]: Application Loader output above ^
[12:35:23]: [altool.6000031344C0] Failed to determine the appleID from bundleID `XXX` with platform IOS. The server returned unexpected content. (-19237) (12)
[12:35:23]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure.
[12:35:23]: Could not download/upload from App Store Connect!
[12:35:23]: Error uploading ipa file: 
 [Application Loader Error Output]: [altool.6000031344C0] Failed to determine the appleID from bundleID `XXX` with platform IOS. The server returned unexpected content. (-19237) (12)
[Application Loader Error Output]: The call to the altool completed with a non-zero exit status: 1. This indicates a failure. </pre>
</details>

### Environment
<details>
  <pre>
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                             |
| --------------------------- | --------------------------------------------------------------------------------- |
| OS                          | 15.7                                                                              |
| Ruby                        | 3.4.4                                                                             |
| Bundler?                    | true                                                                              |
| Git                         | git version 2.50.1 (Apple Git-155)                                                |
| Installation Source         | ~/`XXX`/.bundle/ruby/3.4.0/bin/fastlane |
| Host                        | macOS 15.7 (24G222)                                                               |
| Ruby Lib Dir                | ~/.rbenv/versions/3.4.4/lib                                                       |
| OpenSSL Version             | OpenSSL 3.5.0 8 Apr 2025                                                          |
| Is contained                | false                                                                             |
| Is homebrew                 | false                                                                             |
| Is installed via Fabric.app | false                                                                             |
| Xcode Path                  | /Applications/Xcode262.app/Contents/Developer/                                    |
| Xcode Version               | 26.2                                                                              |
| Swift Version               | 6.2.3                                                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.230.0 | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.7.0        |
| did_you_mean                    | 2.0.0        |
| syntax_suggest                  | 2.0.2        |
| bundler                         | 2.7.2        |
| pathname                        | 0.4.0        |
| rake                            | 13.2.1       |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| rexml                           | 3.3.8        |
| CFPropertyList                  | 3.0.7        |
| abbrev                          | 0.1.2        |
| public_suffix                   | 6.0.2        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.2        |
| aws-partitions                  | 1.1106.0     |
| aws-sigv4                       | 1.11.0       |
| jmespath                        | 1.6.2        |
| logger                          | 1.7.0        |
| aws-sdk-core                    | 3.224.0      |
| aws-sdk-kms                     | 1.101.0      |
| aws-sdk-s3                      | 1.186.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| csv                             | 3.3.5        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.7.0        |
| domain_name                     | 0.6.20240107 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.1.0        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| http-cookie                     | 1.0.8        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.1        |
| fastimage                       | 2.4.0        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.10.1       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.20.0       |
| googleauth                      | 1.8.1        |
| mutex_m                         | 0.3.0        |
| httpclient                      | 2.9.0        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| google-cloud-errors             | 1.5.0        |
| google-cloud-core               | 1.8.0        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.12.0       |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.6.0        |
| plist                           | 3.7.2        |
| rubyzip                         | 2.4.1        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| ostruct                         | 0.6.3        |
</details>

*generated on:* **2025-12-19**
</details>
</pre>
</details>

### PR DESCRIPTION
**Pull request by hasancanakgunduz**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Xcode 26+ altool requires `--provider-public-id` for multi‑provider accounts using username/app‑password auth. We need a dedicated `provider_public_id` option while keeping legacy `--asc-provider` support for older altool and existing `itc_provider` users.  
Reference: https://keith.github.io/xcode-man-pages/altool.1.html

### Description

- Added `provider_public_id` option for altool upload/validate
- Kept legacy `--asc-provider` behavior for backward compatibility
- Switched transporter `build_upload_command`/`build_verify_command` to options hashes to avoid optional‑parameter limits
- Documented `provider_public_id` in Pilot/Deliver options and docs
- Added altool upload spec for `provider_public_id`

### Testing Steps
bundle exec rspec ./fastlane_core/spec/itunes_transporter_spec.rb

fixes: #29820

### CODE REVIEW

**Comment by iBotPeaches** [comment]
thanks for starting this! Looks like some test failures, but as you marked it as draft. I'm sure your on it!

**Comment by hasancanakgunduz** [comment]
@iBotPeaches  Now it should be ready for the review. The only issue is that AppVeyor has failed, but I can’t see why. Thanks in advance for reviewing this.

**Comment by iBotPeaches** [comment]
GitHub having major issues today. I think related to that.

**Comment by hasancanakgunduz** [comment]
> GitHub having major issues today. I think related to that.

It is still failed, do you think I should close this and reopen a new one?

**Comment by assembleMHN** [comment]
Any news to when this will be incuded. Will it just fix the issue or will we need to change our pipeline ?

**Comment by iBotPeaches** [comment]
@assembleMHN - Are you confirming this branch fixed the issue you experienced?

**Comment by hasancanakgunduz** [comment]
> Any news to when this will be incuded. Will it just fix the issue or will we need to change our pipeline ?

@assembleMHN  You will need to pass "provider_public_id" option to your "deliver" and "pilot" commands.

**Comment by iBotPeaches** [comment]
I removed AppVeyor, so if you rebase/merge-master. This should run CI properly now.

File: deliver/lib/deliver/options.rb [hunk 1]
```diff
@@ -323,6 +323,13 @@ def self.available_options
                                      code_gen_sensitive: true,
                                      default_value: CredentialsManager::AppfileConfig.try_fetch_value(:itc_provider),
                                      default_value_dynamic: true),
+        FastlaneCore::ConfigItem.new(key: :provider_public_id,
+                                     env_name: "DELIVER_PROVIDER_PUBLIC_ID",
+                                     description: "The provider public ID to be used with altool (--provider-public-id). This value will override the automatically detected provider value for altool uploads. Required after Xcode 26 when your account is associated with multiple providers and using username/app-password authentication",
+                                     optional: true,
+                                     code_gen_sensitive: true,
+                                     default_value: CredentialsManager::AppfileConfig.try_fetch_value(:provider_public_id),
```
Comment (iBotPeaches) [inline deliver/lib/deliver/options.rb:331]: Will this work out? Have you confirmed loading from Appfile? I don't see `provider_public_id` as a parsable method for this to be understood - https://github.com/fastlane/fastlane/blob/master/credentials_manager/lib/credentials_manager/appfile_config.rb#L89

Comment (hasancanakgunduz) [reply deliver/lib/deliver/options.rb:331]: I made a change to fix this issue, please check it out, thanks

**Review by iBotPeaches — APPROVED** [review]

**Comment by kdbdallas-eshow** [comment]
@iBotPeaches Any idea when a new version of fastlane will be released that includes this change? Apple's deadline for using Xcode26 is coming up fast (April 28, 2026) and need this addition to be able to comply

**Comment by iBotPeaches** [comment]
I hope soon - I'll give the other maintainers a ping. Waiting on some things.

**Comment by velevtzvetlin** [comment]
@kdbdallas-eshow you can update your gemfile to pull from master as a temporary fix
`gem 'fastlane', github: 'fastlane/fastlane', branch: 'master'`

im confirmed master works as i have a mobile app deployment pipeline utilizing fastlane

**Comment by kdbdallas-eshow** [comment]
> @kdbdallas-eshow you can update your gemfile to pull from master as a temporary fix
> 
> `gem 'fastlane', github: 'fastlane/fastlane', branch: 'master'`
> 
> 
> 
> im confirmed master works as i have a mobile app deployment pipeline utilizing fastlane

I did try that and it worked some times. Other attempts would throw other issues. I was thinking it was when new commits were added or something. I will give it another try and if I get the errors report back. Thanks

**Comment by velevtzvetlin** [comment]
@kdbdallas-eshow what issues did you see? thanks for your quick response btw

**Comment by velevtzvetlin** [comment]
@kdbdallas-eshow i locked my fastlane down to the latest commit and im running to builds right now through github runner `macos-15-xlarge` will report back

**Comment by velevtzvetlin** [comment]
@kdbdallas-eshow it appears stable for me
