### PR TITLE
[action][swiftlint] Added support for `--fix mode` option

### LINKED ISSUE #18604: SwiftLint action - Replace autocorrect with --fix
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When running the swiftlint action in 'autocorrect' mode, SwiftLint outputs a warning about that mode being deprecated and that you should use 'swiftlint --fix' instead.

The fix should just require updating the 'swiftlint' action to use --fix instead of autocorrect mode as is done currently.

It doesn't prevent the command running, however, it could stop working in the future if SwiftLint remove it from a new version.

##### Command executed

A fastlane lane that uses the 'swiftlint' action with 'mode' set to 'autocorrect'.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[11:35:09]: -----------------------
[11:35:09]: --- Step: swiftlint ---
[11:35:09]: -----------------------
[11:35:10]: $ Pods/SwiftLint/swiftlint autocorrect
[11:35:10]: ▸ The `swiftlint autocorrect` command is no longer available.
[11:35:10]: ▸ Please use `swiftlint --fix` instead. 
</pre>
</details>

### PR DESCRIPTION
**Pull request by crazymanish**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- Resolves #18604
- Recently, Swiftlint has removed the `autocorrect` mode and introduced `--fix` mode (Please see attached screenshot)

### Description (In this PR)
- Added support for `--fix` mode
- Also, based on the Swiftlint version, autocorrect mode will automatically switch to fix mode & vice-versa.
- Added unit tests.

### Testing Steps
- Download demo Xcode project with Swiftlint lane in Zip [MyApp.zip](https://github.com/fastlane/fastlane/files/6488226/MyApp.zip)
- Run `bundle exec fastlane test` 
or
- Update Gemfile and run `bundle install` with
```
gem "fastlane", :git => "git@github.com:crazymanish/fastlane.git", :branch => "swiftlint-fix-mode-support"
```
- Try below lanes
```ruby
lane :test_swiftlint_in_autocorrect_mode do
    swiftlint(mode: :autocorrect)
end

lane :test_swiftlint_in_fix_mode do
    swiftlint(mode: :fix)    
end
```

### Screenshot
Screenshot 2021-05-15 at 21 30 15

.
.
Screenshot 2021-05-15 at 19 59 09

### CODE REVIEW

File: fastlane/lib/fastlane/actions/swiftlint.rb [hunk 1]
```diff
@@ -89,7 +102,7 @@ def self.available_options
         [
           FastlaneCore::ConfigItem.new(key: :mode,
                                        env_name: "FL_SWIFTLINT_MODE",
-                                       description: "SwiftLint mode: :lint, :autocorrect or :analyze",
+                                       description: "SwiftLint mode: :lint, :fix, :autocorrect or :analyze",
                                        is_string: false,
```
Comment (minuscorp) [inline fastlane/lib/fastlane/actions/swiftlint.rb:93]: You can use `type: Symbol` here and delete `is_string`

**Review by minuscorp — APPROVED** [review]
Minor addition but this is very legit! Thank you for the contribution!

File: fastlane/lib/fastlane/actions/swiftlint.rb (hunk 1 above)
Comment (crazymanish) [reply fastlane/lib/fastlane/actions/swiftlint.rb:93]: Thank you for the review, applied suggestion! 😇

**Comment by lordcodes** [comment]
Looks great, thank you!

File: fastlane/lib/fastlane/actions/swiftlint.rb [hunk 2]
```diff
@@ -11,8 +11,21 @@ def self.run(params)
           UI.user_error!("Your version of swiftlint (#{version}) does not support autocorrect mode.\nUpdate swiftlint using `brew update && brew upgrade swiftlint`")
         end
 
+        if params[:mode] == :autocorrect && version >= Gem::Version.new('0.43.0')
+          UI.deprecated("Your version of swiftlint (#{version}) has deprecated autocorrect mode, please start using fix mode in input param")
+          UI.important("For now, switching swiftlint mode `from :autocorrect to :fix` for you 😇")
+          params[:mode] = :fix
+        end
+
+        if params[:mode] == :fix && version < Gem::Version.new('0.43.0')
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/swiftlint.rb:20]: These two will never happen together so I think it makes sense here to make this an `elsif`
```suggestion
        elsif params[:mode] == :fix && version < Gem::Version.new('0.43.0')
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This looks great! Really love the version checking 😍 Just a few small nit picks otherwise 💯

**Comment by crazymanish** [comment]
> This looks great! Really love the version checking 😍 Just a few small nit picks otherwise 💯

Thank you for your review, applied suggestions! 😇

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thank you so much for all the work on this one ❤️ Really appreciate it!
