### PR TITLE
[spaceship] Fix Apple ID 2FA with SMS

### LINKED ISSUE #21071: Don't ask verification code and access forbiden and apple account block
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I try to log in to the apple account, it asks me for the username and password but not the verification code. The code arrives at the authorized apple devices but the fastlane application does not ask me for it and returns access forbiden.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
   Please enter your Apple ID developer credentials
[11:54:57]: Apple ID Username:
apple@....
[11:56:15]: Logging in...
Password (for apple@...): **************
[11:56:45]: --------------------
[11:56:45]: fastlane init failed
[11:56:45]: --------------------
[11:56:45]: ["The request could not be completed because:", "Access forbidden"] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.1                                                       |
| Ruby                        | 3.1.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.34.1                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.212.0/libexec/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib                  |
| OpenSSL Version             | OpenSSL 3.0.7 1 Nov 2022                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.2                                                       |
| Swift Version               | 5.7.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.26       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.714.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.119.1      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.5        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-02-23**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context

Fixes #21071 

### Description

- Looks like Apple changed the endpoint for submitting 2FA codes
- Any previous sessions that attempted to be used were causing lockout (https://github.com/fastlane/fastlane/issues/21071#issuecomment-1442168994)

- [x] Fix for SMS
- [ ] Fix for Apple device code

_More info coming soon_

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-fix-apple-id-2fa"
```

### CODE REVIEW

File: spaceship/lib/spaceship/two_step_or_factor_client.rb [hunk 1]
```diff
@@ -61,9 +61,17 @@ def handle_two_step_for_device(device_id)
 
       # Send token to server to get a valid session
       r = request(:post) do |req|
-        req.url("https://idmsa.apple.com/appleauth/auth/verify/device/#{device_id}/securitycode")
+        req.url("https://idmsa.apple.com/appleauth/auth/verify/phone/securitycode")
```
Comment (MattKiazyk) [inline spaceship/lib/spaceship/two_step_or_factor_client.rb:64]: So i think the original url was correct, but your body was wrong. 

In Xcodes - https://github.com/RobotsAndPencils/XcodesApp/blob/main/Xcodes/AppleAPI/Sources/AppleAPI/URLRequest%2BApple.swift#L68

Depending on if it's `sms` or `device` it'll send different bodies. 

for SMS: `verify/phone/securitycode`
```
  req.body = {
          "phoneNumber": {
            "id": device_id
          },
          "securityCode": {
            "code" => code.to_s
          },
          "mode": "sms"
```
for trusted device: ``verify/trusteddevice/securitycode`
```
  req.body = {
          "securityCode": {
            "code" => code.to_s
          }
```
That hasn't changed for a while and has been working, but maybe that has changed now 🤷

Comment (joshdholtz) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:64]: Yeah yeah, the body definitely seemed wrong so not really sure how it didn't break sooner 🤷‍♂️ 

But... the new url/updated URL look correct though too, right? This is what proxyman showed me today 👇 

Screenshot 2023-02-23 at 12 21 28 PM

Comment (MattKiazyk) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:64]: My guess is not many people use sms as their 2fa vs a trusted device

that Updated url looks correct for SMS 2FA. For trusted device it's: 

image

Comment (joshdholtz) [reply spaceship/lib/spaceship/two_step_or_factor_client.rb:64]: Ah yeah yeah, we have a separate path for trusted devices that uses that URL and body already 😊

**Comment by joshdholtz** [comment]
Punting on the fix for trusted devices because it seems like that might be an issue on Apple and its not reproducible anymore for me 😔

**Comment by aquacode** [comment]
If I update fastlane using gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-fix-apple-id-2fa" is spaceauth cli to generate session supposed to work now because I get the same errors.

**Comment by andrewheavin** [comment]
@joshdholtz - You'll love this, its now magically working again and I'm running 2.210.1
