### PR TITLE
[resign.sh] only create the archived-expanded-entitlements.xcent file if the version of Xcode < 9.3

### LINKED ISSUE #13684: resign creates an archived-expanded-entitlements.xctent that prevents uploads to AppStore
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The iOS App Store is rejecting an application that was resigned due to the following:

`ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'Development' for key 'com.apple.developer.icloud-container-environment' in 'Payload/Appian.app/Appian' is not supported."`

The only file that has that entry is ` archived-expanded-entitlements.xcent`. This file did not exist in the original signed app built by Xcode 10. This file is being added by [`resign.sh`](
https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh#L826), and as of [Xcode 9.3](https://github.com/fastlane/fastlane/issues/12209), that file is no longer required.

##### Complete output when running fastlane, including the stack trace and command used

This is the output when the attempt to upload the app is made 
<details>
  <pre>
1 package(s) were not uploaded because they had problems:
	/var/folders/7d/_phz8r5n20d6wk5czqv911w80000gn/T/AA042A1B-DAA5-4928-89AC-3EA5B4728DE7/1440851300.itmsp - Error Messages:
		ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'Development' for key 'com.apple.developer.icloud-container-environment' in 'Payload/Resigned.app/Resigned' is not supported."
		ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com.apple.developer.icloud-container-development-container-identifiers' in 'Payload/Resigned.app/Resigned' is not supported."
		ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.icloud-services' in 'Payload/Resigned.app/Resigned' is not supported."
		ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/Resigned.app/Resigned' must be signed with the certificate that is contained in the provisioning profile."
		ERROR ITMS-90211: "Invalid Code Signing Entitlements. The signature for your app bundle contains entitlement values that are not supported. For the com.apple.developer.ubiquity-kvstore-identifier entitlement, the value must start with the prefix provided by Apple in the provisioning profile, followed by characters that are uppercase or lowercase Roman letters [A-Z, a-z], the digits 0 through 9, dot ['.'], or hyphen ['-'], and not contain any wildcard characters. Specifically, value '45XRUNV253.*' for the key 'com.apple.developer.ubiquity-kvstore-identifier' in 'Payload/Resigned.app/Resigned' is not supported."
 </pre>
</details>

### Environment

<details>
  <pre>
Xcode 10.0
  </pre>
</details>

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

As of Xcode 10, the App Store will no longer accept `xcent` files created by extracting the elements from the provisioning profile. Additionally, this file is not necessary. See [this Issue](https://github.com/fastlane/fastlane/issues/13684) for more information.

### Description

Get the Xcode version and use that to determine whether or not we need to create a new xcent file for resigning.

closes #13684

### CODE REVIEW

**Comment by lyndsey-ferguson** [comment]
@ryanprobus, @matt-demers, @kpink224 can you review this?

**Review by ryanprobus — APPROVED** [review]
Looks good!

**Comment by matt-demers** [comment]
Looks good to me

**Review by kpink224 — COMMENTED** [review]
LG just a nit syntax change.

File: sigh/lib/assets/resign.sh [hunk 1]
```diff
@@ -822,7 +826,8 @@ function resign {
         cp -f "$PATCHED_ENTITLEMENTS" "$APP_PATH/archived-expanded-entitlements.xcent"
         /usr/bin/codesign ${VERBOSE} -f -s "$CERTIFICATE" --entitlements "$PATCHED_ENTITLEMENTS" "$APP_PATH"
         checkStatus
-    else
+    elif [[ "${XCODE_VERSION/\.*/}" -lt 10 ]];
+    then
```
[the remark this answers is not in the document]
Comment (lyndsey-ferguson) [reply sigh/lib/assets/resign.sh]: I'd like to keep the same style as above

File: sigh/lib/assets/resign.sh [hunk 2]
```diff
@@ -81,8 +84,7 @@ warning() {
 function checkStatus {
 
     # shellcheck disable=SC2181
-    if [ $? -ne 0 ];
-    then
+    if [ $? -ne 0 ]; then
```
Comment (janpio) [inline sigh/lib/assets/resign.sh]: Specific reason for these unrelated syntax changes?

Comment (lyndsey-ferguson) [reply sigh/lib/assets/resign.sh]: Yes, it was hard to know which style to use so I changed them to match what seemed to be the style that is most in use for this file. That's the second commit so it is easy to review the changes.

**Comment by lyndsey-ferguson** [comment]
@janpio curious, do changes to one file always get prefixed with the filename

**Comment by janpio** [comment]
Nah, but `resign.sh` is kind of "a thing" in the codebase and previous PRs. It is very different to the rest of fastlane's code. I thought that adding it to the title helps to clarify what this PR is about.

**Comment by lyndsey-ferguson** [comment]
I discovered a problem, please refrain from merging

**Comment by lyndsey-ferguson** [comment]
Ok, ready to merge. I fixed the issue, a failure to sign the app binary, and have tested it on an iOS Enterprise app by importing it into my phone.

**Comment by janpio** [comment]
Umm, what was the problem and the change done? Because of the force push it's not visible here :/

**Comment by lyndsey-ferguson** [comment]
The problem was that I had the `if [[ "${XCODE_VERSION/.*/}" -lt 10 ]];` block around the entire block of code that would sign the binary. Thus, the binary was not resigned and the `ipa` bundle was not valid to be uploaded to an iPhone or to the AppStore.

**Review by joshdholtz — APPROVED** [review]
Looks good! Thanks for making this change ❤️

**Comment by lyndsey-ferguson** [comment]
Thank you!
