### PR TITLE
[core] Fix Xcode 26 altool zero exit code confusion.

### LINKED ISSUE #29739: [pilot] Since Xcode 26, fastlane does no longer detect `altool` failures
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Since the new `altool` that shipped in Xcode 26, failures are no longer detected by fastlane.
The script seems to continue as there are no issues.
When using the verbose flag; the error is printed as debug logs.

##### Command executed
```ruby
pilot api_key_path:                      api_key_path,
      skip_submission:                   true,
      skip_waiting_for_build_processing: true,
      app_platform:                      'ios',
      ipa:                               ipa_path
```

Custom fastlane lane executed via commandline, with the verbose option
`fastlane deploy_app config:prd --verbose`

##### Complete output when running fastlane, including the stack trace and command used
```text
DEBUG [2025-10-31 11:34:38.27]: App identifier (<redacted>)
INFO [2025-10-31 11:34:39.05]: Ready to upload new build to TestFlight (App: 118******0)...
DEBUG [2025-10-31 11:34:39.05]: App Platform (ios)
INFO [2025-10-31 11:34:39.63]: Wrote XML data to '/var/folders/2s/r8d30j_n3v55b42k6szcfwdr0000gn/T/d20251031-4694-ei1zj7/1181309300-22f3522e-e794-4621-aa91-ee8eebae8736.itmsp'
DEBUG [2025-10-31 11:34:39.63]: Using altool as transporter.
INFO [2025-10-31 11:34:39.66]: Going to upload updated app to App Store Connect
INFO [2025-10-31 11:34:39.66]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2025-10-31 11:34:39.67]: API_PRIVATE_KEYS_DIR=YourTmpP8KeyDir xcrun altool --upload-app --apiKey YourKeyID --apiIssuer YourIssuerID -t ios -f /var/folders/2s/r8d30j_n3v55b42k6szcfwdr0000gn/T/b0437135-0ffb-4481-817c-177c216cd1e2.ipa -k 100000
DEBUG [2025-10-31 11:34:41.52]: [altool]: Running altool at path '/Applications/Xcode_26.0.1.app/Contents/SharedFrameworks/ContentDelivery.framework/Resources/altool'...

DEBUG [2025-10-31 11:34:41.52]: [altool]: 

DEBUG [2025-10-31 11:34:44.72]: [altool]: 2025-10-31 11:34:44.726 ERROR: [ContentDelivery.Uploader.102BA2C00] The provided entity includes an attribute with a value that has already been used (-19232) The bundle version must be higher than the previously uploaded version: ‘20251031.110341’. (ID: e1ab497b-753b-411c-82f1-22b9bffecf00)

DEBUG [2025-10-31 11:34:44.72]: [altool]:    NSUnderlyingError : The provided entity includes an attribute with a value that has already been used (-19241) The bundle version must be higher than the previously uploaded version.

DEBUG [2025-10-31 11:34:44.72]: [altool]:       status : 409

DEBUG [2025-10-31 11:34:44.72]: [altool]:       detail : The bundle version must be higher than the previously uploaded version.

DEBUG [2025-10-31 11:34:44.72]: [altool]:       source : 

DEBUG [2025-10-31 11:34:44.72]: [altool]:          pointer : /data/attributes/cfBundleVersion

DEBUG [2025-10-31 11:34:44.72]: [altool]:       id : e1ab497b-753b-411c-82f1-22b9bffecf00

DEBUG [2025-10-31 11:34:44.72]: [altool]:       code : ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE

DEBUG [2025-10-31 11:34:44.72]: [altool]:       title : The provided entity includes an attribute with a value that has already been used

DEBUG [2025-10-31 11:34:44.73]: [altool]:       meta : 

DEBUG [2025-10-31 11:34:44.73]: [altool]:          previousBundleVersion : 20251031.110341

DEBUG [2025-10-31 11:34:44.73]: [altool]:    previousBundleVersion : 20251031.110341

DEBUG [2025-10-31 11:34:44.73]: [altool]:    iris-code : ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE

DEBUG [2025-10-31 11:34:44.73]: [altool]: 2025-10-31 11:34:44.727 ERROR: [altool.102BA2C00] Failed to upload package.

DEBUG [2025-10-31 11:34:44.73]: [altool]: Failed to upload archive at '/var/folders/2s/r8d30j_n3v55b42k6szcfwdr0000gn/T/b0437135-0ffb-4481-817c-177c216cd1e2.ipa'.

DEBUG [2025-10-31 11:34:44.73]: [altool]: 2025-10-31 11:34:44.727 ERROR: [altool.102BA2C00] The provided entity includes an attribute with a value that has already been used (-19232) The bundle version must be higher than the previously uploaded version: ‘20251031.110341’. (ID: e1ab497b-753b-411c-82f1-22b9bffecf00)

DEBUG [2025-10-31 11:34:44.73]: [altool]:    NSUnderlyingError : The provided entity includes an attribute with a value that has already been used (-19241) The bundle version must be higher than the previously uploaded version.

DEBUG [2025-10-31 11:34:44.73]: [altool]:       status : 409

DEBUG [2025-10-31 11:34:44.73]: [altool]:       detail : The bundle version must be higher than the previously uploaded version.

DEBUG [2025-10-31 11:34:44.73]: [altool]:       source : 

DEBUG [2025-10-31 11:34:44.73]: [altool]:          pointer : /data/attributes/cfBundleVersion

DEBUG [2025-10-31 11:34:44.73]: [altool]:       id : e1ab497b-753b-411c-82f1-22b9bffecf00

DEBUG [2025-10-31 11:34:44.73]: [altool]:       code : ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE

DEBUG [2025-10-31 11:34:44.73]: [altool]:       title : The provided entity includes an attribute with a value that has already been used

DEBUG [2025-10-31 11:34:44.73]: [altool]:       meta : 

DEBUG [2025-10-31 11:34:44.73]: [altool]:          previousBundleVersion : 20251031.110341

DEBUG [2025-10-31 11:34:44.73]: [altool]:    previousBundleVersion : 20251031.110341

DEBUG [2025-10-31 11:34:44.73]: [altool]:    iris-code : ENTITY_ERROR.ATTRIBUTE.INVALID.DUPLICATE

DEBUG [2025-10-31 11:34:44.73]: [altool]: 

INFO [2025-10-31 11:34:44.74]: -----------------------------------------------------
INFO [2025-10-31 11:34:44.74]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
INFO [2025-10-31 11:34:44.74]: -----------------------------------------------------
INFO [2025-10-31 11:34:44.74]: Successfully uploaded the new binary to App Store Connect
```

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 26.0.1                                             |
| Ruby                        | 3.1.0                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.39.2                                 |
| Installation Source         | ~/.asdf/installs/ruby/3.1.0/bin/fastlane           |
| Host                        | macOS 26.0.1 (25A362)                              |
| Ruby Lib Dir                | ~/.asdf/installs/ruby/3.1.0/lib                    |
| OpenSSL Version             | OpenSSL 3.0.8 7 Feb 2023                           |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-26.0.1.app/Contents/Developer/ |
| Xcode Version               | 26.0.1                                             |
| Swift Version               | 6.2                                                |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
...
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.228.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status      |
| ----------------------------------------- | ------- | ------------------ |
| fastlane-plugin-xcodegen                  | 1.1.0   | ✅ Up-To-Date       |
| fastlane-plugin-swiftformat               | 0.3.0   | ✅ Up-To-Date       |
| fastlane-plugin-firebase_app_distribution | 0.10.0  | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| error_highlight                             | 0.3.0        |
| did_you_mean                                | 1.6.1        |
| bundler                                     | 2.3.4        |
| pathname                                    | 0.2.0        |
| rake                                        | 13.3.0       |
| base64                                      | 0.3.0        |
| nkf                                         | 0.2.0        |
| rexml                                       | 3.4.1        |
| CFPropertyList                              | 3.0.7        |
| public_suffix                               | 6.0.2        |
| addressable                                 | 2.8.7        |
| apfel                                       | 0.0.5        |
| artifactory                                 | 3.0.17       |
| ast                                         | 2.4.2        |
| atomos                                      | 0.1.3        |
| aws-eventstream                             | 1.4.0        |
| aws-partitions                              | 1.1115.0     |
| aws-sigv4                                   | 1.12.1       |
| jmespath                                    | 1.6.2        |
| logger                                      | 1.7.0        |
| aws-sdk-core                                | 3.225.2      |
| aws-sdk-kms                                 | 1.104.0      |
| aws-sdk-s3                                  | 1.189.1      |
| babosa                                      | 1.0.4        |
| claide                                      | 1.1.0        |
| colored2                                    | 3.1.2        |
| cork                                        | 0.3.0        |
| nap                                         | 1.1.0        |
| open4                                       | 1.3.4        |
| claide-plugins                              | 0.9.2        |
| colored                                     | 1.2          |
| colorize                                    | 1.1.0        |
| highline                                    | 2.0.3        |
| commander                                   | 4.6.0        |
| faraday-em_http                             | 1.0.0        |
| faraday-em_synchrony                        | 1.0.0        |
| faraday-excon                               | 1.1.0        |
| faraday-httpclient                          | 1.0.1        |
| multipart-post                              | 2.4.1        |
| faraday-multipart                           | 1.1.0        |
| faraday-net_http                            | 1.0.2        |
| faraday-net_http_persistent                 | 1.2.0        |
| faraday-patron                              | 1.0.0        |
| faraday-rack                                | 1.0.0        |
| faraday-retry                               | 1.0.3        |
| ruby2_keywords                              | 0.0.5        |
| faraday                                     | 1.10.4       |
| faraday-http-cache                          | 2.5.1        |
| rchardet                                    | 1.8.0        |
| git                                         | 1.19.1       |
| kramdown                                    | 2.5.1        |
| kramdown-parser-gfm                         | 1.1.0        |
| sawyer                                      | 0.9.2        |
| octokit                                     | 9.2.0        |
| pstore                                      | 0.1.3        |
| unicode-display_width                       | 2.6.0        |
| terminal-table                              | 3.0.2        |
| danger                                      | 9.5.1        |
| declarative                                 | 0.0.20       |
| digest-crc                                  | 0.7.0        |
| domain_name                                 | 0.6.20240107 |
| dotenv                                      | 2.8.1        |
| emoji_regex                                 | 3.2.3        |
| excon                                       | 0.112.0      |
| facets                                      | 3.1.0        |
| http-cookie                                 | 1.0.8        |
| faraday-cookie_jar                          | 0.0.7        |
| faraday_middleware                          | 1.2.1        |
| fastimage                                   | 2.4.0        |
| sysrandom                                   | 1.0.5        |
| fastlane-sirp                               | 1.0.0        |
| gh_inspector                                | 1.1.3        |
| jwt                                         | 2.10.1       |
| multi_json                                  | 1.15.0       |
| os                                          | 1.1.4        |
| signet                                      | 0.20.0       |
| googleauth                                  | 1.8.1        |
| mutex_m                                     | 0.3.0        |
| httpclient                                  | 2.9.0        |
| mini_mime                                   | 1.1.5        |
| trailblazer-option                          | 0.1.2        |
| uber                                        | 0.1.0        |
| representable                               | 3.2.0        |
| retriable                                   | 3.1.2        |
| google-apis-core                            | 0.11.3       |
| google-apis-androidpublisher_v3             | 0.54.0       |
| google-apis-playcustomapp_v1                | 0.13.0       |
| google-cloud-env                            | 1.6.0        |
| google-apis-iamcredentials_v1               | 0.17.0       |
| google-apis-storage_v1                      | 0.31.0       |
| google-cloud-errors                         | 1.5.0        |
| google-cloud-core                           | 1.8.0        |
| google-cloud-storage                        | 1.47.0       |
| json                                        | 2.12.2       |
| mini_magick                                 | 4.13.2       |
| naturally                                   | 2.2.2        |
| optparse                                    | 0.6.0        |
| plist                                       | 3.7.2        |
| rubyzip                                     | 2.4.1        |
| security                                    | 0.1.5        |
| simctl                                      | 1.6.10       |
| terminal-notifier                           | 2.0.0        |
| tty-screen                                  | 0.8.2        |
| tty-cursor                                  | 0.7.1        |
| tty-spinner                                 | 0.9.3        |
| word_wrap                                   | 1.0.0        |
| nanaimo                                     | 0.3.0        |
| xcodeproj                                   | 1.25.1       |
| rouge                                       | 3.28.0       |
| xcpretty                                    | 0.4.1        |
| xcpretty-travis-formatter                   | 1.0.1        |
| fastlane-plugin-brew                        | 0.1.1        |
| google-apis-firebaseappdistribution_v1      | 0.3.0        |
| google-apis-firebaseappdistribution_v1alpha | 0.2.0        |
| fastlane-plugin-firebase_app_distribution   | 0.10.0       |
| fastlane-plugin-swiftformat                 | 0.3.0        |
| fastlane-plugin-xcodegen                    | 1.1.0        |
| parallel                                    | 1.22.1       |
| parser                                      | 3.1.2.1      |
| rainbow                                     | 3.1.1        |
| regexp_parser                               | 2.5.0        |
| rubocop-ast                                 | 1.21.0       |
| ruby-progressbar                            | 1.11.0       |
| rubocop                                     | 1.36.0       |
| slack-notifier                              | 2.4.0        |
| xcresult                                    | 0.2.2        |
| xcov                                        | 1.8.1        |
</details>

### PR DESCRIPTION
**Pull request by iBotPeaches**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

In #29739 & #29739 we see altool failures not being captured by _fastlane_. This is odd because the logic works purely on the exit code of the tool which suggests altool is not returning semantically valid exit codes.

```
DEBUG [2025-10-31 11:34:44.73]: [altool]: 2025-10-31 11:34:44.727 ERROR: [altool.102BA2C00] The provided entity includes an attribute with a value that has already been used (-19232) The bundle version must be higher than the previously uploaded version: ‘20251031.110341’. (ID: e1ab497b-753b-411c-82f1-22b9bffecf00)
INFO [2025-10-31 11:34:44.74]: -----------------------------------------------------
INFO [2025-10-31 11:34:44.74]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
INFO [2025-10-31 11:34:44.74]: -----------------------------------------------------
```

If we take Xcode 26 and invoke altool sometimes it has a situation where it has an error, but returns a zero exit code.

fixes: #29730 
fixes: #29739 

### Description

The debate with this fix is historically _fastlane_ has only referred to the exit code of the child process (in this case altool) of determining success or fail. Way back in 2016 _fastlane_ actually treated pass/fail based on the detection of errors in captured output. This was changed in https://github.com/fastlane/fastlane/pull/6926 because sometimes tooling emitted errors as it tried a different transport mechanism. Thus _fastlane_ improperly ended execution when the child command was still pushing on.

However, now in 2025 we have Xcode 26 which is doing the opposite problem. Its throwing errors, but returning a 0 exit code. Thankfully though the fixes of 2016 were targeted towards the `iTMSTransporter` which is basically on its way out for the new `altool` transporter. 

This may be [fixed in future](https://github.com/fastlane/fastlane/issues/29698#issuecomment-3329783816) by Apple, because the new altool has its own fair share of issues but for now we need to devise a workaround. So I went back to reading the errors object instead of exit code. If the exit code is non-zero it creates an error so we have coverage to fail a build if no errors exist, but exit code is non-zero.

However, if we see have the same issue that the `iTMSTransporer` had - we may have builds prematurely ended.

### Testing Steps

1. Using a Xcode 26 box and confirming you have the new altool (`Version 26.0.18 (170018)`) and doing an `altool --list-apps` with valid and invalid parameters.
2. Using an Xcode 16 box and confirming you have older altool (`Version 8.303.16303`) and doing an `altool --list-apps` with valid and invalid parameters.
3. Updating spec tests to mock the output difference and exit code difference.

I have not had the luxury of testing an actual Testflight upload yet to confirm this.

### CODE REVIEW

**Comment by iBotPeaches** [comment]
Drafting as I made an implicit requirement on Mac with this change. I was unaware that this tool worked on non-mac. I will revisit my diff.

**Comment by iBotPeaches** [comment]
It now just moves the endpoint to check error count vs exit code.

**Review by lacostej — APPROVED** [review]

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 1]
```diff
@@ -296,7 +297,7 @@ def execute(command, hide_output)
       end
 
       yield(@all_lines) if block_given?
-      exit_status.zero?
+      @errors.empty?
```
Comment (AliSoftware) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:300]: wdyt about using:
```suggestion
      exit_status.zero? && @errors.empty?
```
That way if it's non-zero it considers it a failure in all cases—regardless of if we detected the `ERROR_REGEX` in the output, and it's only if it returns `0` that we check if we saw an error in the output as a workaround for that `altool` bug

Comment (iBotPeaches) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:300]:
```
@errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
```

I thought about that at first, but I saw line 288 automatically sets an error message into the collection if the exit code is non-zero. So I knew the errors object had to have at least one.

Comment (AliSoftware) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:300]: Ah good catch 👍

**Review by AliSoftware — APPROVED** [review]
