### PR TITLE
Fixes issue with `-t DAV` upload parameter not being set in Pilot upload commands

### LINKED ISSUE #13352: Pilot upload fails: iTMSTransporter Could not start delivery: all transports failed diagnostics
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm having some issues with Pilot uploads to App Store Connect. iTMSTransporter reports an error:

```
[iTMSTransporter] Could not start delivery: all transports failed diagnostics
```

The complete error output is below. https://github.com/fastlane/fastlane/issues/11958 has a similar error (the `TransferEngine.java:{line-number}` is different) but the solution to that issue `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"` looks like it's already included in the current version of Fastlane.

Uploading the built IPA with Application Loader directly works fine.

It looks like the network upload might be working since there is a big gap in the log timestamps. Is there any way to crank up the verbosity of the iTMSTransporter logs (via pilot) to figure out what is going on? It looks like `iTMSTransporter` accepts a `-v` option.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[15:33:17]: -------------------
[15:33:17]: --- Step: pilot ---
[15:33:17]: -------------------
[15:33:17]: Login to App Store Connect (redacted)
[15:33:19]: Login successful
[15:33:20]: Ready to upload new build to TestFlight (App: 578424535)...
[15:33:21]: Going to upload updated app to App Store Connect
[15:33:21]: This might take a few minutes. Please don't interrupt the script.
[15:41:44]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[15:41:44]: Transporter transfer failed.
[15:41:44]: 
[15:41:44]: Could not start delivery: all transports failed diagnostics
[15:41:45]: [iTMSTransporter] 	at com.signiant.interactivetransfer.engine.TransferEngine$8.run(TransferEngine.java:4060)

[15:41:45]: [iTMSTransporter] 

[15:41:45]: [iTMSTransporter] [2018-09-12 15:41:44 PDT] <Transport Protocol> DEBUG: Received failed transfer notification; aborting

[15:41:45]: [iTMSTransporter] [2018-09-12 15:41:44 PDT] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[15:41:45]: [iTMSTransporter] [2018-09-12 15:41:44 PDT] <Transport Protocol>  INFO: The Signiant transfer engine's status is DISCONNECTED

[15:41:45]: [iTMSTransporter] [2018-09-12 15:41:44 PDT] <main> ERROR: Could not start delivery: all transports failed diagnostics

[15:41:45]: [iTMSTransporter] 

[15:41:45]: [iTMSTransporter] 

[15:41:45]: [iTMSTransporter] 

[15:41:45]: [iTMSTransporter] Package Summary:

[15:41:45]: [iTMSTransporter]  

[15:41:45]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

[15:41:45]: [iTMSTransporter] 	/var/folders/_c/2qxkxx9s3zs15y_mgqpxl9tm0000gp/T/d20180912-37647-1461dmo/578424535.itmsp - Error Messages:

[15:41:45]: [iTMSTransporter] 		Could not start delivery: all transports failed diagnostics

[15:41:45]: [iTMSTransporter] [2018-09-12 15:41:44 PDT] <main> DBG-X: Returning 1

[15:41:45]: iTunes Transporter output above ^
[15:41:45]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[15:41:45]: Build failed for redacted
[15:41:45]: Completed with summary:
[15:41:45]: redacted: Failed: Error uploading ipa file, for more information see above</pre>
</details>

### Environment

<details>
  <pre>### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.104.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.1        |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| mini_portile2             | 2.3.0        |
| nokogiri                  | 1.8.4        |
| rmagick                   | 2.16.0       |
| xcode-install             | 2.4.4        |
</details>

*generated on:* **2018-09-12**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by robmaceachern**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #13352 (and maybe #13398). Related to #11958

The `-t DAV` parameter was not being set on Pilot upload commands. There was logic to update the `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` environment variable but it was [only being invoked](https://github.com/fastlane/fastlane/blob/9565dafc1d353b576e364195a55239fc685cdbf6/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L382) as part of `execute` _after_ the command was already built.

### Description

These changes add a private `additional_upload_parameters` method to TransporterExecutor which invokes the environment variable workaround each time it's accessed. I've also update the transporter tests to ensure `-t DAV` is set for upload commands.

cc @janpio

### CODE REVIEW

**Comment by robmaceachern** [comment]
I signed it!

**Comment by janpio** [comment]
Ok, before we can think about merging this, we have to understand how this came to be. That code somehow ended up in this state, and it seems important to me in this case to understand how and why.

Also, this is quite a drastic change for _many_ usages here. If this was a problem for more users, we would probably have gotten more issues - do you agree?

**Comment by robmaceachern** [comment]
Here is the change that introduced the `"-t DAV"` workaround in the first place. https://github.com/fastlane/fastlane/commit/20be2e5493c341cf095d3d54beedb6d088363e0b I don't think it ever worked as intended. This PR is only trying to fix what seems like the original intent here.

I can't speak to how many users have experienced this before but there are at least these issues:
#11958 (16 reactions)
#13398 (9 reactions)
#13352
https://github.com/fastlane/fastlane/issues/5683
https://github.com/fastlane-old/deliver/issues/235
https://github.com/fastlane-old/deliver/issues/181

Each issue includes the workaround (manually specifying `ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"`) which will fix the issue. I suspect many users that run into this problem have plugged in the workaround and gone on with their lives :)

We can close this if the manual workaround is good enough for users that do run into these types of problems. I'm not very familiar with the tradeoffs between the various protocols and it's possible this could cause some other problems for users where `Signiant` is working fine. Like I said above, I was only trying to fix what I believed was the original intended behaviour of the transporter code but that behaviour may no longer be desirable.

**Comment by janpio** [comment]
Best would be to understand when it is required and when it is not. But we don't have too much to go on here :/

**Comment by joshdholtz** [comment]
>I don't think it ever worked as intended. This PR is only trying to fix what seems like the original intent here.

^ I think I agree with this 🤔 It does look like the actual transporter command is being generated before this environment variable was being set. So I think this should cover what the original intent was.

I think it might be good to call on @KrauseFx here for this one as he originally implemented #11965 🙃 

@KrauseFx - Is there a specific reason that the setting of `ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"` was done in the `execute` method? (after the command was being generated)

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 1]
```diff
@@ -162,7 +165,7 @@ def build_upload_command(username, password, source = "/tmp", provider_short_nam
         "-u \"#{username}\"",
         "-p #{shell_escaped_password(password)}",
         "-f \"#{source}\"",
-        ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"], # that's here, because the user might overwrite the -t option
+        additional_upload_parameters, # that's here, because the user might overwrite the -t option
         "-t Signiant",
```
Comment (joshdholtz) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb]: This will give two `-t` parameters. Is that going to mess things up? 🤔

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 2]
```diff
@@ -236,7 +239,7 @@ def build_upload_command(username, password, source = "/tmp", provider_short_nam
         "-u #{username.shellescape}",
         "-p #{password.shellescape}",
         "-f #{source.shellescape}",
-        ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"], # that's here, because the user might overwrite the -t option
+        additional_upload_parameters, # that's here, because the user might overwrite the -t option
         '-t Signiant',
```
Comment (joshdholtz) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb]: Same here. This will give two `-t` parameters. Is that going to mess things up? 🤔

**Review by joshdholtz — COMMENTED** [review]
Double `-t` parameters?

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb (hunk 1 above)
Comment (janpio) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb]: No, the first one should take precedence (so the second one does _not_ overwrite the first one)

**Review by KrauseFx — APPROVED** [review]
Hey everyone, thanks for looking into this. Just looking at the code, it makes sense to apply the same default value for the upload parameters unless a user provides their own. This change looks low risk, and makes sense to have a consistent behavior across the _fastlane_ tools 👍 

I'd be ok with merging this, but will give @janpio and @joshdholtz the last say here 🚀

**Review by joshdholtz — APPROVED** [review]
Looks good and works good! Thanks for fixing this ❤️

**Comment by allenhsu** [comment]
FYI, we encountered some problem when uploading ipa after upgrading from 2.104.0 to 2.107.0. After some investigation, we think it may be related to this change. We have some proxy set up in our CI server, with 2.104.0, we can successfully upload ipa's to iTunesConnect/AppStoreConnect. After upgrading to 2.107.0, we failed to upload any ipa, the error message is as below:

```
[16:42:01]: [31m[Transporter Error Output]: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:01]: [31m[Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:01]: [31m[Transporter Error Output]: Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [31mTransporter transfer failed.[0m
[16:42:04]: 
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter SessionExpiration = 2018-10-26T08:42:03.177Z
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter Success = true
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] Package Summary:
[0m
[16:42:04]: [33m[iTMSTransporter]  
[0m
[16:42:04]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[16:42:04]: [33m[iTMSTransporter] 	/tmp/638021335.itmsp - Error Messages:
[0m
[16:42:04]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:04]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:04]: [33m[iTMSTransporter] 		  Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X: Returning 1
[0m
[16:42:04]: iTunes Transporter output above ^
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
```

We reverted to v2.104.0 and it uploads successfully. Maybe it's not a good idea to enable `-t DAV` by default?

**Comment by allenhsu** [comment]
FYI, we encountered some problem when uploading ipa after upgrading from 2.104.0 to 2.107.0. After some investigation, we think it may be related to this change. We have some proxy set up in our CI server, with 2.104.0, we can successfully upload ipa's to iTunesConnect/AppStoreConnect. After upgrading to 2.107.0, we failed to upload any ipa, the error message is as below:

```
[16:42:01]: [31m[Transporter Error Output]: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:01]: [31m[Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:01]: [31m[Transporter Error Output]: Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [31mTransporter transfer failed.[0m
[16:42:04]: 
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter SessionExpiration = 2018-10-26T08:42:03.177Z
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter Success = true
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] Package Summary:
[0m
[16:42:04]: [33m[iTMSTransporter]  
[0m
[16:42:04]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[16:42:04]: [33m[iTMSTransporter] 	/tmp/638021335.itmsp - Error Messages:
[0m
[16:42:04]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:04]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:04]: [33m[iTMSTransporter] 		  Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X: Returning 1
[0m
[16:42:04]: iTunes Transporter output above ^
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
```

We reverted to v2.104.0 and it uploads successfully. Maybe it's not a good idea to enable `-t DAV` by default?

**Comment by allenhsu** [comment]
FYI, we encountered some problem when uploading ipa after upgrading from 2.104.0 to 2.107.0. After some investigation, we think it may be related to this change. We have some proxy set up in our CI server, with 2.104.0, we can successfully upload ipa's to iTunesConnect/AppStoreConnect. After upgrading to 2.107.0, we failed to upload any ipa, the error message is as below:

```
[16:42:01]: [31m[Transporter Error Output]: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:01]: [31m[Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:01]: [31m[Transporter Error Output]: Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [31mTransporter transfer failed.[0m
[16:42:04]: 
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter SessionExpiration = 2018-10-26T08:42:03.177Z
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter Success = true
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] Package Summary:
[0m
[16:42:04]: [33m[iTMSTransporter]  
[0m
[16:42:04]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[16:42:04]: [33m[iTMSTransporter] 	/tmp/638021335.itmsp - Error Messages:
[0m
[16:42:04]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:04]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:04]: [33m[iTMSTransporter] 		  Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X: Returning 1
[0m
[16:42:04]: iTunes Transporter output above ^
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
```

We reverted to v2.104.0 and it uploads successfully. Maybe it's not a good idea to enable `-t DAV` by default?

**Comment by allenhsu** [comment]
FYI, we encountered some problem when uploading ipa after upgrading from 2.104.0 to 2.107.0. After some investigation, we think it may be related to this change. We have some proxy set up in our CI server, with 2.104.0, we can successfully upload ipa's to iTunesConnect/AppStoreConnect. After upgrading to 2.107.0, we failed to upload any ipa, the error message is as below:

```
[16:42:01]: [31m[Transporter Error Output]: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:01]: [31m[Transporter Error Output]: An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:01]: [31m[Transporter Error Output]: Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [31mTransporter transfer failed.[0m
[16:42:04]: 
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter EnableJWTForAllCalls = false
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter SessionExpiration = 2018-10-26T08:42:03.177Z
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter Success = true
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] 
[0m
[16:42:04]: [33m[iTMSTransporter] Package Summary:
[0m
[16:42:04]: [33m[iTMSTransporter]  
[0m
[16:42:04]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
[16:42:04]: [33m[iTMSTransporter] 	/tmp/638021335.itmsp - Error Messages:
[0m
[16:42:04]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
[0m
[16:42:04]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
[16:42:04]: [33m[iTMSTransporter] 		  Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
[0m
[16:42:04]: [33m[iTMSTransporter] [2018-10-22 16:42:04 CST] <main> DBG-X: Returning 1
[0m
[16:42:04]: iTunes Transporter output above ^
[16:42:04]: [31mAn error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /tmp/638021335.itmsp/225e0ae8c5f64b696b98d0b557310b9f1696be80738b9d20e6954ee4da9bf704.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
```

We reverted to v2.104.0 and it uploads successfully. Maybe it's not a good idea to enable `-t DAV` by default?
