### PR TITLE
[deliver][frameit] support the latest devices and resolutions.

### LINKED ISSUE #22030: Deliver does not support 13 inch ipad screen resolution: 2064x2752
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I see the App Store now asks for 13 inch ipad screenshots. I used a iPad Pro M4 with resolution 2064x2752 (which is indicated in appstore connect as valid). However, I do get a error in Fastlane, that the resolution is not supported.
```
Error: ./fastlane/screenshots-lite/th/13 inch-04-FOO.png - Invalid screen size (Actual size is 2064x2752. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
```
The linked website states that this resolution is valid. So I guess it needs to be added to Fastlane.
##
### Command executed

```
upload_to_app_store(app_identifier: "bundle.foo, skip_binary_upload: true, skip_metadata: true, overwrite_screenshots:true, screenshots_path: './fastlane/screenshots-foo', ignore_language_directory_validation: true)


``` 
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[00:23:40]: ------------------------------
[00:23:40]: --- Step: default_platform ---
[00:23:40]: ------------------------------
[00:23:40]: Driving the lane 'ios upload_screenshots_foo' 🚀
[00:23:40]: ---------------------------------
[00:23:40]: --- Step: upload_to_app_store ---
[00:23:40]: ---------------------------------
[00:23:40]: Successfully loaded 'fastlane/Deliverfile' 📄
[00:23:40]: No values defined in './fastlane/Deliverfile'
[00:23:40]: Login to App Store Connect (email@email)
[00:23:42]: Login successful

+--------------------------------------------------------------------+
|                      deliver 2.220.0 Summary                       |
+--------------------------------------+-----------------------------+
| app_identifier                       | bundle.id     |
| skip_binary_upload                   | true                        |
| skip_metadata                        | true                        |
| overwrite_screenshots                | true                        |
| screenshots_path                     | ./fastlane/screenshots-foo |
| ignore_language_directory_validation | true                        |
| metadata_path                        | ./fastlane/metadata         |
| username                             |          |
| platform                             | ios                         |
| edit_live                            | false                       |
| use_live_version                     | false                       |
| skip_screenshots                     | false                       |
| skip_app_version_update              | false                       |
| force                                | false                       |
| screenshot_processing_timeout        | 3600                        |
| sync_screenshots                     | false                       |
| submit_for_review                    | false                       |
| verify_only                          | false                       |
| reject_if_possible                   | false                       |
| version_check_wait_retry_limit       | 7                           |
| phased_release                       | false                       |
| reset_ratings                        | false                       |
| team_id                              |                      |
| dev_portal_team_id                   |                  |
| run_precheck_before_submit           | true                        |
| precheck_default_rule_level          | warn                        |
| precheck_include_in_app_purchases    | true                        |
+--------------------------------------+-----------------------------+

[00:23:43]: 🚫 Invalid screenshots were detected! Here are the reasons:
[00:23:43]: 🚫 Error: ./fastlane/screenshots-foo/zh-Hans/13 inch-01_foo.png - Invalid screen size (Actual size is 2064x2752. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[00:23:43]: 🚫 Error: ./fastlane/screenshots-foo/zh-Hans/13 inch-02_foo.png - Invalid screen size (Actual size is 2064x2752. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
[..]
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.5                                        |
| Ruby                        | 2.7.8                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.39.3 (Apple Git-146)          |
| Installation Source         | ~/.rvm/gems/ruby-2.7.8/bin/fastlane         |
| Host                        | macOS 14.5 (23F79)                          |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.8/lib                |
| OpenSSL Version             | OpenSSL 1.1.1w  11 Sep 2023                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.4                                        |
| Swift Version               | 5.10                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | nl_NL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Update metadata lite"
  lane :update_metadata_lite do 
    upload_to_app_store(metadata_path: "fastlane/metadata-lite",app_identifier:"nl.umito.ios.minipiano",  skip_binary_upload: true, skip_metadata: false, skip_screenshots:true)
  end
end

platform :ios do
  desc "Update metadata pro"
  lane :update_metadata_pro do
    upload_to_app_store(metadata_path: "fastlane/metadata-pro",app_identifier: "nl.umito.ios.minipiano.pro", skip_binary_upload: true, skip_metadata: false, skip_screenshots:true)
  end
end

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    snapshot(app_identifier: "nl.umito.ios.minipiano")
    # system("sips --rotate 90 screenshots/*/*.png")
#    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end
end

platform :ios do
  desc "Upload screenshots"
  lane :upload_screenshots_lite do
    
    upload_to_app_store(app_identifier: "nl.umito.ios.minipiano", skip_binary_upload: true, skip_metadata: true, overwrite_screenshots:true, screenshots_path: './fastlane/screenshots-lite', ignore_language_directory_validation: true)
  end
end



```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id("appledev@umito.nl") # Your Apple email address

itc_team_id("525444") # App Store Connect Team ID
team_id("V69H5Z8LUZ") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.220.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| executable-hooks                | 1.7.1        |
| bundler-unload                  | 1.0.2        |
| rubygems-bundler                | 1.4.5        |
| bundler                         | 2.3.13       |
| rake                            | 13.2.1       |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.7        |
| public_suffix                   | 5.0.5        |
| addressable                     | 2.8.6        |
| artifactory                     | 3.0.17       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.929.0      |
| aws-sigv4                       | 1.8.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.196.1      |
| aws-sdk-kms                     | 1.81.0       |
| aws-sdk-s3                      | 1.151.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20240107 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.110.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.8.1        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.0        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.2        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.5.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.5.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.24.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2024-05-16**
</details></pre>
</details>

### LINKED ISSUE #22267: Deliver 13" iPad screenshots
Hi,

I am trying to upload iPad 13" screenshots using deliver. However, fastlane says the 1320 x 2868 resolution is unknown. 

The alternative resolution 1290 x 2796 get sorted in at iPad Pro 12.9". I would like it to be recognised as 13" resolution.

Is there a roadmap to support these resolutions ?

Thanks
Christian

I am running:
| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.223.1 | ✅ Up-To-Date  |

### LINKED ISSUE #29578: Error: ./screenshots/en-US/8_APP_IPAD_PRO_3GEN_129_8.png - Invalid screen size (Actual size is 2064x2752.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm using fastlane 2.227.2 to automate my iOS release process, I've already got some screenshots of 2046*2752 for iPad, which are already uploaded my App Connect portal, but the fastlane command always fail with error: `Invalid screen size (Actual size is 2064x2752.`

I've tried both APP_IPAD_PRO_3GEN_129 and APP_IPAD_PRO_3GEN_130 but neither of them worked.

I'm really confused why it got failed. What image size is required and which file name pattern is accepted to this?

BTW I found a PR one year ago and it didn't got merged. Is it related? https://github.com/fastlane/fastlane/pull/22066

##### Command executed

`fastlane deliver submit_build -n $(UpdatedBuildNumber) --api_key_path ./api_key.json -a "$(appIdentifier)" --overwrite_screenshots --screenshots_path ./screenshots -k "$(teamId)" --metadata_path ./metadata --precheck_include_in_app_purchases false --force --verbose`

##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2025-05-14 06:41:59.79]: Creating authorization token for App Store Connect API

+--------------------------------------------------------------+
|                   deliver 2.227.2 Summary                    |
+--------------------------------------+-----------------------+
| build_number                         | 100 |
| api_key_path                         | ./api_key.json        |
| app_identifier                       | xxxxx |
| overwrite_screenshots                | true                  |
| screenshots_path                     | ./screenshots         |
| team_id                              | xxxxx|
| metadata_path                        | ./metadata            |
| precheck_include_in_app_purchases    | false                 |
| force                                | true                  |
| submit_for_review                    | true                  |
| platform                             | ios                   |
| edit_live                            | false                 |
| use_live_version                     | false                 |
| skip_binary_upload                   | false                 |
| skip_screenshots                     | false                 |
| skip_metadata                        | false                 |
| skip_app_version_update              | false                 |
| screenshot_processing_timeout        | 3600                  |
| sync_screenshots                     | false                 |
| verify_only                          | false                 |
| reject_if_possible                   | false                 |
| version_check_wait_retry_limit       | 7                     |
| phased_release                       | false                 |
| reset_ratings                        | false                 |
| run_precheck_before_submit           | true                  |
| precheck_default_rule_level          | warn                  |
| ignore_language_directory_validation | false                 |
+--------------------------------------+-----------------------+


WARN [2025-05-14 06:42:01.53]: 🚫 Invalid screenshots were detected! Here are the reasons:
ERROR [2025-05-14 06:42:01.53]: 🚫 Error: ./screenshots/en-US/0_APP_IPAD_PRO_3GEN_129_0.png - Invalid screen size (Actual size is 2064x2752. See the specifications to fix https://help.apple.com/app-store-connect/#/devd274dd925)
```

### PR DESCRIPTION
**Pull request by sirghi**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

There have been complaints for a long time about missing iPad resolutions for the _deliver_ action. E.g. #22030 and #22267.

### Description

In this PR I've cross checked _deliver_ and _spaceship_ devices and resolutions against current Apple specs:
- https://developer.apple.com/help/app-store-connect/reference/app-information/screenshot-specifications/
- https://developer.apple.com/documentation/appstoreconnectapi/screenshotdisplaytype

and systematically added support for all modern variants.

I've also updated the conflict resolution mechanism so that iPad Pro's and tv vs Vision Pro get disambiguated properly according to their file names. About iPads in particular I've taken the approach to only detect the rare 2nd generation by certain heuristics, otherwise fallback to the more widespread 13" model, which also appear the first inside AppStoreConnect. I did my best to tweak the logic in a way so that existing setups don't break.

Also have removed the old `Deliver::AppScreenshot::ScreenSize` class as it was basically a duplicate of `Spaceship::ConnectAPI::AppScreenshotSet::DisplayType`, and made _deliver_ use the latter throughout. The raw values of the old ScreenSize were only used in _frameit_, so have moved it there as a hash.

### Testing Steps

Updated/added relevant tests. They should continue to pass.

---

fixes: #22267 
fixes: #29651
fixes: #22030
fixes: #29632
fixes: #29578

closes: #29742
closes: #29670
closes: #29640
closes: #22066
closes: #22036 
closes: #22288
closes: #29695

### CODE REVIEW

File: deliver/lib/deliver/app_screenshot_validator.rb
Comment (sirghi) [inline deliver/lib/deliver/app_screenshot_validator.rb:1]: Now that screen_size is the same as display_type, I was able merge the 2 validations, and `to_skip` is not relevant anymore

**Comment by iBotPeaches** [comment]
Thanks for pr! We indeed need to get this going again with modern sizes.

So just that I'm following as someone not fimiliar with this aspect. This is purely the logic used for uploading screenshots to an app review?

This helps support newer devices, but doesn't touch the actual frames? Like the frames I see here https://github.com/fastlane/frameit-frames

I ask because I'm trying to learn if there is a difference between deliver aspects as well as framing. This in my understanding is images already made with fastlane needing support for those types.

**Comment by sirghi** [comment]
> Thanks for pr! We indeed need to get this going again with modern sizes.
> 
> So just that I'm following as someone not fimiliar with this aspect. This is purely the logic used for uploading screenshots to an app review?
> 
> This helps support newer devices, but doesn't touch the actual frames? Like the frames I see here https://github.com/fastlane/frameit-frames
> 
> I ask because I'm trying to learn if there is a difference between deliver aspects as well as framing. This in my understanding is images already made with fastlane needing support for those types.

Correct, the changes are around uploading screenshots to AppStoreConnect. I've kept the numbers in frameit intact. And frameit is used to just render a device frame around said screnshots, so it's an optional step before uploading to the Store.

File: deliver/lib/deliver/app_screenshot.rb [hunk 1]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
+      DisplayType::IMESSAGE_APP_IPHONE_55 => DEVICE_RESOLUTIONS[DisplayType::APP_IPHONE_55],
+      DisplayType::IMESSAGE_APP_IPHONE_58 => DEVICE_RESOLUTIONS[DisplayType::APP_IPHONE_58],
+      DisplayType::IMESSAGE_APP_IPHONE_61 => DEVICE_RESOLUTIONS[DisplayType::APP_IPHONE_61],
+      DisplayType::IMESSAGE_APP_IPHONE_65 => DEVICE_RESOLUTIONS[DisplayType::APP_IPHONE_65],
+      DisplayType::IMESSAGE_APP_IPHONE_67 => DEVICE_RESOLUTIONS[DisplayType::APP_IPHONE_67],
+      DisplayType::IMESSAGE_APP_IPAD_97 => DEVICE_RESOLUTIONS[DisplayType::APP_IPAD_97],
+      DisplayType::IMESSAGE_APP_IPAD_105 => DEVICE_RESOLUTIONS[DisplayType::APP_IPAD_105],
+      DisplayType::IMESSAGE_APP_IPAD_PRO_3GEN_11 => DEVICE_RESOLUTIONS[DisplayType::APP_IPAD_PRO_3GEN_11],
+      DisplayType::IMESSAGE_APP_IPAD_PRO_129 => DEVICE_RESOLUTIONS[DisplayType::APP_IPAD_PRO_129],
+      DisplayType::IMESSAGE_APP_IPAD_PRO_3GEN_129 => DEVICE_RESOLUTIONS[DisplayType::APP_IPAD_PRO_129]
```
[the remark this answers is not in the document]
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb]: Indeed you are right. Fixed

**Comment by iBotPeaches** [comment]
Okay I have not used this feature yet, but I see the masses complaining about how this has decayed. So how about this as a plan?

1. We review/fix Copilot feedback until Copilot is happy.
2. We find recent PRs/Issues targeted at this same change and see if their change is included or not.
3. We ask those individuals by drawing attention to this PR to test it, by including a line they can put in their Gemspec to point to this fork.
4. We look to get 2-3 community members proving success with their pipeline.
5. In parallel, I cross check all these dimensions against the website.

File: frameit/lib/frameit/device_types.rb [hunk 2]
```diff
@@ -81,80 +119,80 @@ def self.symbol_to_constant(symbol)
...
+    IPHONE_14_PRO ||= Device.new("iphone-14-pro", "Apple iPhone 14 Pro", 12, [[1178, 2556], [2556, 1178]], 460, Color::PURPLE, Platform::IOS)
+    IPHONE_14_PRO_MAX ||= Device.new("iphone14-pro-max", "Apple iPhone 14 Pro Max", 12, [[1290, 2796], [2796, 1290]], 458, Color::PURPLE, Platform::IOS)
+    IPAD_10_2 ||= Device.new("ipad-10-2", "Apple iPad 10.2", 1, [[1620, 2160], [2160, 1620]], 264, Color::SPACE_GRAY, Platform::IOS)
+    IPAD_AIR_2 ||= Device.new("ipad-air-2", "Apple iPad Air 2", 1, [[1536, 2048], [2048, 1536]], 264, Color::SPACE_GRAY, Platform::IOS, DEVICE_SCREEN_IDS[DisplayType::APP_IPAD_97])
+    IPAD_AIR_2019 ||= Device.new("ipad-air-2019", "Apple iPad Air (2019)", 2, [[1668, 2224], [2224, 1668]], 265, Color::SPACE_GRAY, Platform::IOS)
+    IPAD_MINI_4 ||= Device.new("ipad-mini-4", "Apple iPad Mini 4", 2, [[1536, 2048], [2048, 1536]], 324, Color::SPACE_GRAY)
+    IPAD_MINI_2019 ||= Device.new("ipad-mini-2019", "Apple iPad Mini (2019)", 3, [[1536, 2048], [2048, 1536]], 324, Color::SPACE_GRAY)
+    # iPad Pro 12.9" (2nd gen):
```
[the remark this answers is not in the document]
Comment (sirghi) [reply frameit/lib/frameit/device_types.rb:183]: Expected, it refers to only 2nd gen

**Comment by sirghi** [comment]
Sounds like a plan. 

Can you help out with 4? I'm not really often in these parts. I can ask the people in other similar PR's though.

**Comment by sirghi** [comment]
For anyone wanting to double check that their setup still works with these changes, just replace your _fastline_ line in your Gemfile with:
```ruby
gem "fastlane", git: "https://github.com/sirghi/fastlane.git", branch: "feature/screenshot-sizes"
```

In case you have ruby 3.4.x, you might need the following gems as well:
```ruby
gem "abbrev"
gem "logger"
gem "mutex_m"
gem "ostruct"
gem "csv"
gem "nkf"
```

**Comment by sirghi** [comment]
@iBotPeaches just to confirm:
1. Done
2. Have found these PR's, new and old:
   - #29742
   - #29670
   - #29646
   - #29640
   - #22066
   - #22036
   - #22288
Confirmed that my changes also cover their changes. Also have found these issues:
   - #22030
   - #29651
   - #22267
4. Commented on each of those pointing them to this PR.
5. Pending
6. On yourself

**Comment by iBotPeaches** [comment]
thanks! I'll indeed try and peek this once done with work today. Thanks for knocking out a chunk of this.

**Comment by JulesMoorhouse** [comment]
In reply to your invite to try this on the PR where I've added some things.... https://github.com/fastlane/fastlane/pull/29742
... I tried frameit, but this has an issue...
`Unsupported screen size [2064, 2752] for path.....`

I know you've made some frameit changes, but I guess you haven't touched this.

**Comment by vanniktech** [comment]
@sirghi this is extremely good! Technically, I was able to upload all of the screenshots. 3 of them failed though and didn't upload, then I've gotten these:

```
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
```

I went into the console and uploaded the ones that were missing, by painfully going through all the languages and switching between phone & ipad screenshots but eventually I managed to find the ones that were missing. Somehow this has to be improved - this was always faulty though and is not an introduced behavior with this PR.

After uploading the 3 screenshots I've gotten:

```
[12:49:22]: Failed to upload file after retries... Received 400
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500"
```

And now I'm kinda stuck. The 400 error is new. I checked again online and it seems like some of the screenshots have gotten a proper sorting order, but some haven't. I have gone through all of them once and reordered them manually, but I'm still getting: 

> Waiting for screenshots to appear before uploading. This is unlikely to be recovered unless it's 503 error. error="Server error got 500

Any advice? Would also be helpful to add more logging in case a screenshot hasn't been uploaded correctly, such that you know it's the iPhone 16 German screenshot that is causing problems.


----

Huh okay, just when I hit enter, it went through:

```
[13:00:03]: Server error got 500
[13:00:03]: Server error got 500
[✔] Waiting for all the screenshots to finish being processed...
[13:00:11]: Successfully uploaded all screenshots
[✔] Sorting screenshots uploaded...
[13:00:16]: Successfully uploaded screenshots to App Store Connect
```

So now I can confidently say:

- Sometimes screenshots aren't uploaded correctly and you have to manually add them (this has also been the case before!)
  - Here it would be extremely nice if fastlane would tell us in the logs that the following screenshots could not be added please upload them manually
- However, with this PR even after updating the screenshots manually, the ordering isn't taken care of and therefore it hangs until you re-order (this was never an issue before and might be introduced by the last time I've uploaded images and all the changes from that point of time until right now with this PR)

Huge thanks @sirghi !!

**Comment by JulesMoorhouse** [comment]
@vanniktech normally you re-run your deliver / upload lane to resolve these.

**Comment by iBotPeaches** [comment]
Exciting to see all this testing together. It seems the upload process being flaky and needing retries is probably not introduced by this change. Something for us to work on, but probably not related.

I want to be sure we have all new sizes supported, don't break older sizes and provide an easy base for future changes to occur from the community. I'm cross checking this list still against the Apple documentation for each size.

**Comment by sirghi** [comment]
@JulesMoorhouse yes I guess _frameit_ still lacks the new resolutions, but I touched frameit minimally as I wanted to focus on _deliver_ as the PR got big as is. Probably _frameit_ would also benefit from a cleanup and reference the new resolutions from _deliver_ so that we have a single source of truth.

@vanniktech @iBotPeaches indeed the upload is historically flaky. I've managed to get around it by retrying deliver on error as @JulesMoorhouse pointed out, which recovered most failures.

I've also generated some screenshots out of all supported sizes and devices and the upload was successful.

File: deliver/lib/deliver/app_screenshot.rb [hunk 3]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
+      ],
+      # These are actually 6.3" iPhones
+      DisplayType::APP_IPHONE_61 => [
+        [1179, 2556],
+        [2556, 1179],
+        [1206, 2622],
+        [2622, 1206]
+      ],
+      # These are actually 6.1" iPhones
+      DisplayType::APP_IPHONE_58 => [
```
Comment (sirghi) [inline deliver/lib/deliver/app_screenshot.rb:75]: @iBotPeaches while cross checking, I'd just like to direct your attention to these quirks - while consulting the reference link and AppStoreConnect itself (in the screenshot placeholders) I've deduced that Apple made some unorthodox decisions regarding these identifiers.

Same for the iPad Pro below, which is actually the gist of all the pain throughout fastlane's issues section and the trigger that set off this endeavour of mine ⛵

**Comment by sirghi** [comment]
@iBotPeaches I got a linting error from this part of the Fastfile:
```
# spaceship and credentials_manager don't have access to fastlane_core
ensure_no_debug_code(text: " UI\\.", path: "spaceship/lib", extension: ".rb", exclude_dirs: exclude_dirs)
ensure_no_debug_code(text: " UI\\.", path: "credentials_manager/lib", extension: ".rb", exclude_dirs: exclude_dirs)
```
because I added some logging to _spaceship_. Is the above still valid, because I have managed to successfully add _fastlane_core_ as a dependency to _spaceship_?

**Comment by iBotPeaches** [comment]
> @iBotPeaches I got a linting error from this part of the Fastfile:
> because I added some logging to _spaceship_. Is the above still valid, because I have managed to successfully add _fastlane_core_ as a dependency to _spaceship_?

Its a valid lint failure. Generally the logging is not in the core things (core, spaceship, etc). Its in the calling code. That means our libraries are not spamming logs out and generally keeping their responsibilities to the functional return. So I would remove it or move it yeah.

File: deliver/lib/deliver/app_screenshot.rb [hunk 4]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
-      IOS_IPAD = "iOS-iPad"
-      # iPad 10.5
-      IOS_IPAD_10_5 = "iOS-iPad-10.5"
-      # iPad 11
-      IOS_IPAD_11 = "iOS-iPad-11"
-      # iPad Pro
-      IOS_IPAD_PRO = "iOS-iPad-Pro"
-      # iPad Pro (12.9-inch) (3rd generation)
-      IOS_IPAD_PRO_12_9 = "iOS-iPad-Pro-12.9"
+    FORMATTED_NAMES = {
```
Comment (iBotPeaches) [inline deliver/lib/deliver/app_screenshot.rb:13]: These names appear to come from here - https://developer.apple.com/documentation/appstoreconnectapi/screenshotdisplaytype. What was your process of taking the enum to the actual name? Could we put that link/process somewhere in those code so future updates can follow this pattern?

File: deliver/lib/deliver/app_screenshot.rb [hunk 5]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
+      DisplayType::APP_IPHONE_35 => "iPhone 4",
+      DisplayType::APP_IPHONE_40 => "iPhone 5",
+      DisplayType::APP_IPHONE_47 => "iPhone 6",
+      DisplayType::APP_IPHONE_55 => "iPhone 6 Plus",
+      DisplayType::APP_IPHONE_58 => "iPhone XS",
+      DisplayType::APP_IPHONE_61 => "iPhone 14 Pro",
+      DisplayType::APP_IPHONE_65 => "iPhone XS Max",
```
Comment (iBotPeaches) [inline deliver/lib/deliver/app_screenshot.rb:20]: Could I understand your thought process on naming these? Since if I understand this right this is the 6.5" display and probably has a ton of phones on that. XS Max is one, but isn't like XR, 11, 11 Pro, 12 Pro, 13 Pro, 14 Plus too? The older code had comments with all the devices comma delimited for comparison

File: deliver/lib/deliver/app_screenshot.rb [hunk 6]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
-        ScreenSize::IOS_67_MESSAGES,
-        ScreenSize::IOS_IPAD_MESSAGES,
-        ScreenSize::IOS_IPAD_PRO_MESSAGES,
-        ScreenSize::IOS_IPAD_PRO_12_9_MESSAGES,
-        ScreenSize::IOS_IPAD_10_5_MESSAGES,
-        ScreenSize::IOS_IPAD_11_MESSAGES
-      ].include?(self.screen_size)
+      # rubocop:disable Require/MissingRequireStatement
+      return DisplayType::ALL_IMESSAGE.include?(self.display_type)
+      # rubocop:enable Require/MissingRequireStatement
```
Comment (iBotPeaches) [inline deliver/lib/deliver/app_screenshot.rb:225]: Couldn't we just remove `return` since its a simple function instead of supressing rubocop?

**Review by iBotPeaches — COMMENTED** [review]
I verified all the numbers on deliver - left a few comments. I see frameit was updated for the new devicetype, but not really adapted in any way.

So this PR probably brings deliver up to par, but leaves frameit for later. Which makes sense since that looks a bit more difficult with actual frames and assets to add.

The suppression of rubocop for return I don't think are needed. I'd more fix the lint warning than add a lint suppression. 

Thanks for PR again!

File: deliver/lib/deliver/app_screenshot.rb (hunk 6 above)
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb:225]: This is actually rubocop somehow not seeing the shorthand I added at the top of the file:

```
DisplayType = Spaceship::ConnectAPI::AppScreenshotSet::DisplayType
```

Error is:
```
deliver/lib/deliver/app_screenshot.rb:223:7: C: Require/MissingRequireStatement: DisplayType::ALL_IMESSAGE not found, you're probably missing a require statement or there is a cycle in your dependencies.
      DisplayType::ALL_IMESSAGE.include?(self.display_type)
```

It goes away if I include the long name everywhere, but I wanted things to read shorter. Maybe there's another ruby way to achieve this that I don't know of.

File: deliver/lib/deliver/app_screenshot.rb (hunk 4 above)
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb:13]: The deleted enum from here is actually something else, which has moved to frameit as it was the only thing using it and thought it might as well sit there. The names from here are actually moved from deleted (red )lines 141-172, and I've kept them as-is, bar some comments about "also 7 Plus & 8 Plus". If you want, I can add them back

File: deliver/lib/deliver/app_screenshot.rb (hunk 5 above)
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb:20]: Hopefully the previous answer explains that I actually didn't touch these.

**Comment by sirghi** [comment]
Indeed _frameit_ would also benefit from some love, but that's another story (PR).

**Comment by JulesMoorhouse** [comment]
> Indeed _frameit_ would also benefit from some love, but that's another story (PR).

I do get that and I know it's hard to jump through these hoops.
But as you've touched frameit in this PR, you have an understanding of this area and there doesn't seem much left to do - just 13.9 support via iPad Pro, it seems to make sense to solve this.

My own attempts aren't pretty, although it works.

Thanks for this PR, its a big improvement.

**Comment by sirghi** [comment]
I think the big factor here is my free time, which is limited. Plus I wouldn't say my understanding of _frameit_ is anywhere above scratching the surface. I've added a variant of the Apple Watch and Visio Pro to deliver, and I've no knowledge how they are framed in the context of deliver. Some frame assets might be needed e.g. Which is why I think it's best to apply your attempts on top of this work when it is merged, @JulesMoorhouse.

**Comment by sirghi** [comment]
Or alternatively if you leave some code suggestions in the proper places to just add missing frames, I can add them here

**Comment by JulesMoorhouse** [comment]
@sirghi fair enough 👍 
I don't feel that confident to suggest.

**Comment by iBotPeaches** [comment]
Okay so if AI is only complaining about comments and rubocop - it must be pretty much happy. I'll go investigate that alias, since I don't understand the complaint about rubocop myself.

File: deliver/lib/deliver/app_screenshot.rb [hunk 7]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
     end
```
[the remark this answers is not in the document]
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb:226]: You would think that rubocop has to detect the shorthand at the beginning of the file but it's not

**Comment by sirghi** [comment]
Yeah it's a strange one. For visibility, I've done AI-assisted coding here, and it has suggested the `rubocop:disable`.

File: deliver/lib/deliver/app_screenshot.rb [hunk 8]
```diff
@@ -7,391 +7,259 @@ module Deliver
...
+        # rubocop:disable Require/MissingRequireStatement
+        if is_2gen
+          return is_imessage ? DisplayType::IMESSAGE_APP_IPAD_PRO_129 : DisplayType::APP_IPAD_PRO_129
+        else
+          return is_imessage ? DisplayType::IMESSAGE_APP_IPAD_PRO_3GEN_129 : DisplayType::APP_IPAD_PRO_3GEN_129
         end
+      # Apple TV vs Vision Pro conflict
+      when [3840, 2160]
+        return path_lower.include?("vision") ? DisplayType::APP_APPLE_VISION_PRO : DisplayType::APP_APPLE_TV
+        # rubocop:enable Require/MissingRequireStatement
```
[the remark this answers is not in the document]
Comment (sirghi) [reply deliver/lib/deliver/app_screenshot.rb:259]: For the same previous reason, these statements are needed.

**Comment by iBotPeaches** [comment]
> Yeah it's a strange one. For visibility, I've done AI-assisted coding here, and it has suggested the `rubocop:disable`.

I tracked it down last night. It was a bug in require_tools, a custom cop that was written for fastlane, but 7 years later its showing some age - https://github.com/milch/rubocop-require_tools/issues/3

**Comment by sirghi** [comment]
> I tracked it down last night. It was a bug in require_tools, a custom cop that was written for fastlane, but 7 years later its showing some age - [milch/rubocop-require_tools#3](https://github.com/milch/rubocop-require_tools/issues/3)

a retired cop, haha

**Comment by iBotPeaches** [comment]
> a retired cop, haha

lol I went a bit off the deep end and started working to revamp that retired cop plugin - https://github.com/iBotPeaches/rubocop-require_tools/pull/2

I'll get back on track and finish testing this pr.

**Comment by sirghi** [comment]
A bit of archaeology)

All good, thanks

**Comment by robin24** [comment]
Hey @sirghi,

Just chiming in here as I wanted to seriously thank you for your hard work on this PR and your usage instructions.

I'm a fully blind indie developer and just submitted my first app for review yesterday. Unfortunately, the App Store Connect interface for uploading / arranging screenshots isn't super accessible given the visual nature of this UI, so I wanted to use Fastlane to upload my screenshots and was losing my mind over it rejecting the iPhone 17 Pro Max screen dimensions.
Once I replaced the official fastlane gem with the one from your repo, everything was working perfectly fine and it was possible for me to upload everything via the App Store Connect API.

Really hope this fix makes it into the main project soon, but again huge thanks for all your work on this!!!

**Comment by vanniktech** [comment]
Look what I just found out after publishing another app of mine:

> [20:42:21]: Uploaded './fastlane/screenshots/ja/iPhone 12 Pro Max-02.png'... (1125.924309 secs)

Would it be possible to decrease the timeout? Almost 20 minutes seems way too long for uploading a file.

**Comment by sirghi** [comment]
@robin24 it's a huge joy to know that this helped you out during your submission. Thank you for your kind words.

Good luck with your app! I invite you to plug it here once it's out on the Store 😄

**Comment by sirghi** [comment]
@vanniktech The default of 1 hour timeout is a bit too much indeed, but you can customize it via `screenshot_processing_timeout` (refer to docs [here](https://docs.fastlane.tools/actions/deliver/#deliver))

**Comment by sirghi** [comment]
@iBotPeaches have you managed to do some tests here?

**Comment by iBotPeaches** [comment]
> @iBotPeaches have you managed to do some tests here?

I did, things look good. I'm trying to stabilize v2.229.0, but I think I'll start v2.230.0 off with this merge.

**Review by iBotPeaches — APPROVED** [review]
I confirmed all devices against official docs, invoked Copilot to help catch some typos and confirm a few community users who confirmed it worked.

I did one sanity test, but I was doing a simple single set of screenshots so wasn't a full test.

I didn't like all the cop ignores, but I tracked them down to a custom package that has gone 7 years without a commit - https://github.com/milch/rubocop-require_tools. It sadly has decayed and doesn't support const aliases from other files. So the ignores make sense to me OR removing the alias, but with such a long import path I didn't push the point.

I'm alright with this now.

**Comment by 0ren** [comment]
Also appears to resolve #29632 - thank you!

**Comment by sirghi** [comment]
Nice one, good to hear.

@iBotPeaches let me know if you need anything else from my side

**Comment by sirghi** [comment]
For what it's worth, we're testing this with 22 localization x 4 device types x 7 screenshots each.

**Comment by iBotPeaches** [comment]
Thanks again everyone for the testing! Will be in next release.

**Comment by sirghi** [comment]
@iBotPeaches thanks for your and everyone's support throughout 🙌

**Comment by aj3011** [comment]
@sirghi 

I tested the new version 2.229.1 after your changes were merged and to my surprise, I started seeing issues in visionOS screenshot uploads stating that "DisplayType is not allowed"

For context, I was earlier using version 2.228.0, and I patched two files after installing fastlane on my server (just added constants and dimensions spec for visionOS)


**deliver/lib/deliver/app_screenshot.rb**

`                require 'fastimage'

                require_relative 'module'
                require 'spaceship/connect_api/models/app_screenshot_set'

                module Deliver
                  # AppScreenshot represents one screenshots for one specific locale and
                  # device type.
                  class AppScreenshot
                    #
                    module ScreenSize
                      # iPhone 4
                      IOS_35 = "iOS-3.5-in"
                      # iPhone 5
                      IOS_40 = "iOS-4-in"
                      # iPhone 6, 7, & 8
                      IOS_47 = "iOS-4.7-in"
                      # iPhone 6 Plus, 7 Plus, & 8 Plus
                      IOS_55 = "iOS-5.5-in"
                      # iPhone XS
                      IOS_58 = "iOS-5.8-in"
                      # iPhone 14 Pro
                      IOS_61 = "iOS-6.1-in"
                      # iPhone 14 Plus, iPhone 13 Pro Max, iPhone 12 Pro Max, iPhone 11 Pro Max, iPhone 11, iPhone XS Max, iPhone XR
                      IOS_65 = "iOS-6.5-in"
                      # iPhone 14 Pro Max
                      IOS_67 = "iOS-6.7-in"

                      # iPad
                      IOS_IPAD = "iOS-iPad"
                      # iPad 10.5
                      IOS_IPAD_10_5 = "iOS-iPad-10.5"
                      # iPad 11
                      IOS_IPAD_11 = "iOS-iPad-11"
                      # iPad Pro
                      IOS_IPAD_PRO = "iOS-iPad-Pro"
                      # iPad Pro (12.9-inch) (3rd generation)
                      IOS_IPAD_PRO_12_9 = "iOS-iPad-Pro-12.9"

                      # iPhone 5 iMessage
                      IOS_40_MESSAGES = "iOS-4-in-messages"
                      # iPhone 6, 7, & 8 iMessage
                      IOS_47_MESSAGES = "iOS-4.7-in-messages"
                      # iPhone 6 Plus, 7 Plus, & 8 Plus iMessage
                      IOS_55_MESSAGES = "iOS-5.5-in-messages"
                      # iPhone XS iMessage
                      IOS_58_MESSAGES = "iOS-5.8-in-messages"
                      # iPhone 14 Pro iMessage
                      IOS_61_MESSAGES = "iOS-6.1-in-messages"
                      # iPhone 14 Plus, iPhone 13 Pro Max, iPhone 12 Pro Max, iPhone 11 Pro Max, iPhone 11, iPhone XS Max, iPhone XR iMessage
                      IOS_65_MESSAGES = "iOS-6.5-in-messages"
                      # iPhone 14 Pro Max iMessage
                      IOS_67_MESSAGES = "iOS-6.7-in-messages"

                      # iPad iMessage
                      IOS_IPAD_MESSAGES = "iOS-iPad-messages"
                      # iPad 10.5 iMessage
                      IOS_IPAD_10_5_MESSAGES = "iOS-iPad-10.5-messages"
                      # iPad 11 iMessage
                      IOS_IPAD_11_MESSAGES = "iOS-iPad-11-messages"
                      # iPad Pro iMessage
                      IOS_IPAD_PRO_MESSAGES = "iOS-iPad-Pro-messages"
                      # iPad Pro (12.9-inch) (3rd generation) iMessage
                      IOS_IPAD_PRO_12_9_MESSAGES = "iOS-iPad-Pro-12.9-messages"

                      # Apple Watch
                      IOS_APPLE_WATCH = "iOS-Apple-Watch"
                      # Apple Watch Series 4
                      IOS_APPLE_WATCH_SERIES4 = "iOS-Apple-Watch-Series4"
                      # Apple Watch Series 7
                      IOS_APPLE_WATCH_SERIES7 = "iOS-Apple-Watch-Series7"
                      # Apple Watch Series 10
                      IOS_APPLE_WATCH_SERIES10 = "iOS-Apple-Watch-Series10"
                      # Apple Watch Ultra
                      IOS_APPLE_WATCH_ULTRA = "iOS-Apple-Watch-Ultra"

                      # Apple TV
                      APPLE_TV = "Apple-TV"

                      # Mac
                      MAC = "Mac"

                      # Apple Vision Pro (VisionOS)
                      VISIONOS = "VisionOS"
                    end

                    # @return [Deliver::ScreenSize] the screen size (device type)
                    #  specified at {Deliver::ScreenSize}
                    attr_accessor :screen_size

                    attr_accessor :path

                    attr_accessor :language

                    # @param path (String) path to the screenshot file
                    # @param language (String) Language of this screenshot (e.g. English)
                    # @param screen_size (Deliver::AppScreenshot::ScreenSize) the screen size, which
                    #  will automatically be calculated when you don't set it. (Deprecated)
                    def initialize(path, language, screen_size = nil)
                      UI.deprecated('`screen_size` for Deliver::AppScreenshot.new is deprecated in favor of the default behavior to calculate size automatically. Passed value is no longer validated.') if screen_size
                      self.path = path
                      self.language = language
                      self.screen_size = screen_size || self.class.calculate_screen_size(path)
                    end

                    # The iTC API requires a different notation for the device
                    def device_type
                      matching = {
                        ScreenSize::IOS_35 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_35,
                        ScreenSize::IOS_40 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_40,
                        ScreenSize::IOS_47 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_47, # also 7 & 8
                        ScreenSize::IOS_55 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_55, # also 7 Plus & 8 Plus
                        ScreenSize::IOS_58 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_58,
                        ScreenSize::IOS_61 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_61,
                        ScreenSize::IOS_65 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_65,
                        ScreenSize::IOS_67 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPHONE_67,
                        ScreenSize::IOS_IPAD => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPAD_97,
                        ScreenSize::IOS_IPAD_10_5 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPAD_105,
                        ScreenSize::IOS_IPAD_11 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPAD_PRO_3GEN_11,
                        ScreenSize::IOS_IPAD_PRO => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPAD_PRO_129,
                        ScreenSize::IOS_IPAD_PRO_12_9 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_IPAD_PRO_3GEN_129,
                        ScreenSize::IOS_40_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_40,
                        ScreenSize::IOS_47_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_47, # also 7 & 8
                        ScreenSize::IOS_55_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_55, # also 7 Plus & 8 Plus
                        ScreenSize::IOS_58_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_58,
                        ScreenSize::IOS_61_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_61,
                        ScreenSize::IOS_65_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_65,
                        ScreenSize::IOS_67_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPHONE_67,
                        ScreenSize::IOS_IPAD_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPAD_97,
                        ScreenSize::IOS_IPAD_PRO_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPAD_PRO_129,
                        ScreenSize::IOS_IPAD_PRO_12_9_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPAD_PRO_3GEN_129,
                        ScreenSize::IOS_IPAD_10_5_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPAD_105,
                        ScreenSize::IOS_IPAD_11_MESSAGES => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::IMESSAGE_APP_IPAD_PRO_3GEN_11,
                        ScreenSize::MAC => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_DESKTOP,
                        ScreenSize::VISIONOS => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_APPLE_VISION_PRO,
                        ScreenSize::IOS_APPLE_WATCH => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_WATCH_SERIES_3,
                        ScreenSize::IOS_APPLE_WATCH_SERIES4 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_WATCH_SERIES_4,
                        ScreenSize::IOS_APPLE_WATCH_SERIES7 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_WATCH_SERIES_7,
                        ScreenSize::IOS_APPLE_WATCH_SERIES10 => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_WATCH_SERIES_10,
                        ScreenSize::IOS_APPLE_WATCH_ULTRA => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_WATCH_ULTRA,
                        ScreenSize::APPLE_TV => Spaceship::ConnectAPI::AppScreenshotSet::DisplayType::APP_APPLE_TV
                      }
                      return matching[self.screen_size]
                    end

                    # Nice name
                    def formatted_name
                      matching = {
                        ScreenSize::IOS_35 => "iPhone 4",
                        ScreenSize::IOS_40 => "iPhone 5",
                        ScreenSize::IOS_47 => "iPhone 6", # also 7 & 8
                        ScreenSize::IOS_55 => "iPhone 6 Plus", # also 7 Plus & 8 Plus
                        ScreenSize::IOS_58 => "iPhone XS",
                        ScreenSize::IOS_61 => "iPhone 14 Pro",
                        ScreenSize::IOS_65 => "iPhone XS Max",
                        ScreenSize::IOS_67 => "iPhone 14 Pro Max",
                        ScreenSize::IOS_IPAD => "iPad",
                        ScreenSize::IOS_IPAD_10_5 => "iPad 10.5",
                        ScreenSize::IOS_IPAD_11 => "iPad 11",
                        ScreenSize::IOS_IPAD_PRO => "iPad Pro",
                        ScreenSize::IOS_IPAD_PRO_12_9 => "iPad Pro (12.9-inch) (3rd generation)",
                        ScreenSize::IOS_40_MESSAGES => "iPhone 5 (iMessage)",
                        ScreenSize::IOS_47_MESSAGES => "iPhone 6 (iMessage)", # also 7 & 8
                        ScreenSize::IOS_55_MESSAGES => "iPhone 6 Plus (iMessage)", # also 7 Plus & 8 Plus
                        ScreenSize::IOS_58_MESSAGES => "iPhone XS (iMessage)",
                        ScreenSize::IOS_61_MESSAGES => "iPhone 14 Pro (iMessage)",
                        ScreenSize::IOS_65_MESSAGES => "iPhone XS Max (iMessage)",
                        ScreenSize::IOS_67_MESSAGES => "iPhone 14 Pro Max (iMessage)",
                        ScreenSize::IOS_IPAD_MESSAGES => "iPad (iMessage)",
                        ScreenSize::IOS_IPAD_PRO_MESSAGES => "iPad Pro (iMessage)",
                        ScreenSize::IOS_IPAD_PRO_12_9_MESSAGES => "iPad Pro (12.9-inch) (3rd generation) (iMessage)",
                        ScreenSize::IOS_IPAD_10_5_MESSAGES => "iPad 10.5 (iMessage)",
                        ScreenSize::IOS_IPAD_11_MESSAGES => "iPad 11 (iMessage)",
                        ScreenSize::MAC => "Mac",
                        ScreenSize::IOS_APPLE_WATCH => "Watch",
                        ScreenSize::IOS_APPLE_WATCH_SERIES4 => "Watch Series4",
                        ScreenSize::IOS_APPLE_WATCH_SERIES7 => "Watch Series7",

                        ScreenSize::IOS_APPLE_WATCH_ULTRA => "Watch Ultra",
                        ScreenSize::APPLE_TV => "Apple TV"
                      }
                      return matching[self.screen_size]
                    end

                    # Validates the given screenshots (size and format)
                    def is_valid?
                      UI.deprecated('Deliver::AppScreenshot#is_valid? is deprecated in favor of Deliver::AppScreenshotValidator')
                      return false unless ["png", "PNG", "jpg", "JPG", "jpeg", "JPEG"].include?(self.path.split(".").last)

                      return self.screen_size == self.class.calculate_screen_size(self.path)
                    end

                    def is_messages?
                      return [
                        ScreenSize::IOS_40_MESSAGES,
                        ScreenSize::IOS_47_MESSAGES,
                        ScreenSize::IOS_55_MESSAGES,
                        ScreenSize::IOS_58_MESSAGES,
                        ScreenSize::IOS_61_MESSAGES,
                        ScreenSize::IOS_65_MESSAGES,
                        ScreenSize::IOS_67_MESSAGES,
                        ScreenSize::IOS_IPAD_MESSAGES,
                        ScreenSize::IOS_IPAD_PRO_MESSAGES,
                        ScreenSize::IOS_IPAD_PRO_12_9_MESSAGES,
                        ScreenSize::IOS_IPAD_10_5_MESSAGES,
                        ScreenSize::IOS_IPAD_11_MESSAGES
                      ].include?(self.screen_size)
                    end

                    def self.device_messages
                      # This list does not include iPad Pro 12.9-inch (3rd generation)
                      # because it has same resolution as IOS_IPAD_PRO and will clobber
                      return {
                        ScreenSize::IOS_67_MESSAGES => [
                          [1290, 2796],
                          [2796, 1290]
                        ],
                        ScreenSize::IOS_65_MESSAGES => [
                          [1242, 2688],
                          [2688, 1242],
                          [1284, 2778],
                          [2778, 1284]
                        ],
                        ScreenSize::IOS_61_MESSAGES => [
                          [1179, 2556],
                          [2556, 1179]
                        ],
                        ScreenSize::IOS_58_MESSAGES => [
                          [1125, 2436],
                          [2436, 1125],
                          [1170, 2532],
                          [2532, 1170]
                        ],
                        ScreenSize::IOS_55_MESSAGES => [
                          [1242, 2208],
                          [2208, 1242]
                        ],
                        ScreenSize::IOS_47_MESSAGES => [
                          [750, 1334],
                          [1334, 750]
                        ],
                        ScreenSize::IOS_40_MESSAGES => [
                          [640, 1096],
                          [640, 1136],
                          [1136, 600],
                          [1136, 640]
                        ],
                        ScreenSize::IOS_IPAD_MESSAGES => [
                          [1024, 748],
                          [1024, 768],
                          [2048, 1496],
                          [2048, 1536],
                          [768, 1004],
                          [768, 1024],
                          [1536, 2008],
                          [1536, 2048]
                        ],
                        ScreenSize::IOS_IPAD_10_5_MESSAGES => [
                          [1668, 2224],
                          [2224, 1668]
                        ],
                        ScreenSize::IOS_IPAD_11_MESSAGES => [
                          [1488, 2266],
                          [2266, 1488],
                          [1668, 2388],
                          [2388, 1668],
                          [1640, 2360],
                          [2360, 1640],
                          [1668, 2420],
                          [2420, 1668]
                        ],
                        ScreenSize::IOS_IPAD_PRO_MESSAGES => [
                          [2732, 2048],
                          [2048, 2732]
                        ]
                      }
                    end

                    # reference: https://help.apple.com/app-store-connect/#/devd274dd925
                    def self.devices
                      # This list does not include iPad Pro 12.9-inch (3rd generation)
                      # because it has same resolution as IOS_IPAD_PRO and will clobber
                      return {
                        ScreenSize::IOS_67 => [
                          [1290, 2796],
                          [2796, 1290]
                        ],
                        ScreenSize::IOS_65 => [
                          [1242, 2688],
                          [2688, 1242],
                          [1284, 2778],
                          [2778, 1284]
                        ],
                        ScreenSize::IOS_61 => [
                          [1179, 2556],
                          [2556, 1179]
                        ],
                        ScreenSize::IOS_58 => [
                          [1125, 2436],
                          [2436, 1125],
                          [1170, 2532],
                          [2532, 1170]
                        ],
                        ScreenSize::IOS_55 => [
                          [1242, 2208],
                          [2208, 1242]
                        ],
                        ScreenSize::IOS_47 => [
                          [750, 1334],
                          [1334, 750]
                        ],
                        ScreenSize::IOS_40 => [
                          [640, 1096],
                          [640, 1136],
                          [1136, 600],
                          [1136, 640]
                        ],
                        ScreenSize::IOS_35 => [
                          [640, 920],
                          [640, 960],
                          [960, 600],
                          [960, 640]
                        ],
                        ScreenSize::IOS_IPAD => [ # 9.7 inch
                          [1024, 748],
                          [1024, 768],
                          [2048, 1496],
                          [2048, 1536],
                          [768, 1004], # portrait without status bar
                          [768, 1024],
                          [1536, 2008], # portrait without status bar
                          [1536, 2048]
                        ],
                        ScreenSize::IOS_IPAD_10_5 => [
                          [1668, 2224],
                          [2224, 1668]
                        ],
                        ScreenSize::IOS_IPAD_11 => [
                          [1488, 2266],
                          [2266, 1488],
                          [1668, 2388],
                          [2388, 1668],
                          [1640, 2360],
                          [2360, 1640],
                          [1668, 2420],
                          [2420, 1668]
                        ],
                        ScreenSize::IOS_IPAD_PRO => [
                          [2732, 2048],
                          [2048, 2732]
                        ],
                        ScreenSize::MAC => [
                          [1280, 800],
                          [1440, 900],
                          [2560, 1600],
                          [2880, 1800]
                        ],
                        ScreenSize::VISIONOS => [
                          [3840, 2160],
                          [2160, 3840]
                        ],
                        ScreenSize::IOS_APPLE_WATCH => [
                          [312, 390]
                        ],
                        ScreenSize::IOS_APPLE_WATCH_SERIES4 => [
                          [368, 448]
                        ],
                        ScreenSize::IOS_APPLE_WATCH_SERIES7 => [
                          [396, 484]
                        ],
                        ScreenSize::IOS_APPLE_WATCH_SERIES10 => [
                          [416, 496]
                        ],
                        ScreenSize::IOS_APPLE_WATCH_ULTRA => [
                          [410, 502]
                        ],
                        ScreenSize::APPLE_TV => [
                          [1920, 1080],
                          [3840, 2160]
                        ]
                      }
                    end

                    def self.resolve_ipadpro_conflict_if_needed(screen_size, filename)
                      is_3rd_gen = [
                        "iPad Pro (12.9-inch) (3rd generation)", # Default simulator has this name
                        "iPad Pro (12.9-inch) (4th generation)", # Default simulator has this name
                        "iPad Pro (12.9-inch) (5th generation)", # Default simulator has this name
                        "iPad Pro (12.9-inch) (6th generation)", # Default simulator has this name
                        "IPAD_PRO_3GEN_129", # Screenshots downloaded from App Store Connect has this name
                        "ipadPro129" # Legacy: screenshots downloaded from iTunes Connect used to have this name
                      ].any? { |key| filename.include?(key) }
                      if is_3rd_gen
                        if screen_size == ScreenSize::IOS_IPAD_PRO
                          return ScreenSize::IOS_IPAD_PRO_12_9
                        elsif screen_size == ScreenSize::IOS_IPAD_PRO_MESSAGES
                          return ScreenSize::IOS_IPAD_PRO_12_9_MESSAGES
                        end
                      end
                      screen_size
                    end

                    def self.calculate_screen_size(path)
                      size = FastImage.size(path)

                      UI.user_error!("Could not find or parse file at path '#{path}'") if size.nil? || size.count == 0

                      # iMessage screenshots have same resolution as app screenshots so we need to distinguish them
                      path_component = Pathname.new(path).each_filename.to_a[-3]
                      devices = path_component.eql?("iMessage") ? self.device_messages : self.devices

                      devices.each do |screen_size, resolutions|
                        if resolutions.include?(size)
                          filename = Pathname.new(path).basename.to_s
                          return resolve_ipadpro_conflict_if_needed(screen_size, filename)
                        end
                      end

                      nil
                    end
                  end

                  ScreenSize = AppScreenshot::ScreenSize
                end
                EOF_FASTLANE_PATCH`



The other file I changed was **lib/spaceship/connect_api/models/app_screenshot_set.rb** (also added constants for visionOS in the maps)

`                require_relative '../model'
                require_relative './app_screenshot'

                module Spaceship
                  class ConnectAPI
                    class AppScreenshotSet
                      include Spaceship::ConnectAPI::Model

                      attr_accessor :screenshot_display_type

                      attr_accessor :app_screenshots

                      module DisplayType
                        APP_IPHONE_35 = "APP_IPHONE_35"
                        APP_IPHONE_40 = "APP_IPHONE_40"
                        APP_IPHONE_47 = "APP_IPHONE_47"
                        APP_IPHONE_55 = "APP_IPHONE_55"
                        APP_IPHONE_58 = "APP_IPHONE_58"
                        APP_IPHONE_61 = "APP_IPHONE_61"
                        APP_IPHONE_65 = "APP_IPHONE_65"
                        APP_IPHONE_67 = "APP_IPHONE_67"

                        APP_IPAD_97 = "APP_IPAD_97"
                        APP_IPAD_105 = "APP_IPAD_105"
                        APP_IPAD_PRO_3GEN_11 = "APP_IPAD_PRO_3GEN_11"
                        APP_IPAD_PRO_129 = "APP_IPAD_PRO_129"
                        APP_IPAD_PRO_3GEN_129 = "APP_IPAD_PRO_3GEN_129"

                        IMESSAGE_APP_IPHONE_40 = "IMESSAGE_APP_IPHONE_40"
                        IMESSAGE_APP_IPHONE_47 = "IMESSAGE_APP_IPHONE_47"
                        IMESSAGE_APP_IPHONE_55 = "IMESSAGE_APP_IPHONE_55"
                        IMESSAGE_APP_IPHONE_58 = "IMESSAGE_APP_IPHONE_58"
                        IMESSAGE_APP_IPHONE_61 = "IMESSAGE_APP_IPHONE_61"
                        IMESSAGE_APP_IPHONE_65 = "IMESSAGE_APP_IPHONE_65"
                        IMESSAGE_APP_IPHONE_67 = "IMESSAGE_APP_IPHONE_67"

                        IMESSAGE_APP_IPAD_97 = "IMESSAGE_APP_IPAD_97"
                        IMESSAGE_APP_IPAD_105 = "IMESSAGE_APP_IPAD_105"
                        IMESSAGE_APP_IPAD_PRO_129 = "IMESSAGE_APP_IPAD_PRO_129"
                        IMESSAGE_APP_IPAD_PRO_3GEN_11 = "IMESSAGE_APP_IPAD_PRO_3GEN_11"
                        IMESSAGE_APP_IPAD_PRO_3GEN_129 = "IMESSAGE_APP_IPAD_PRO_3GEN_129"

                        APP_WATCH_SERIES_3 = "APP_WATCH_SERIES_3"
                        APP_WATCH_SERIES_4 = "APP_WATCH_SERIES_4"
                        APP_WATCH_SERIES_7 = "APP_WATCH_SERIES_7"
                        APP_WATCH_SERIES_10 = "APP_WATCH_SERIES_10"
                        APP_WATCH_ULTRA = "APP_WATCH_ULTRA"

                        APP_APPLE_TV = "APP_APPLE_TV"

                        APP_DESKTOP = "APP_DESKTOP"
                        APP_APPLE_VISION_PRO = "APP_APPLE_VISION_PRO"

                        ALL_IMESSAGE = [
                          IMESSAGE_APP_IPHONE_40,
                          IMESSAGE_APP_IPHONE_47,
                          IMESSAGE_APP_IPHONE_55,
                          IMESSAGE_APP_IPHONE_58,
                          IMESSAGE_APP_IPHONE_61,
                          IMESSAGE_APP_IPHONE_65,
                          IMESSAGE_APP_IPHONE_67,

                          IMESSAGE_APP_IPAD_97,
                          IMESSAGE_APP_IPAD_105,
                          IMESSAGE_APP_IPAD_PRO_129,
                          IMESSAGE_APP_IPAD_PRO_3GEN_11,
                          IMESSAGE_APP_IPAD_PRO_3GEN_129
                        ]

                        ALL = [
                          APP_IPHONE_35,
                          APP_IPHONE_40,
                          APP_IPHONE_47,
                          APP_IPHONE_55,
                          APP_IPHONE_58,
                          APP_IPHONE_61,
                          APP_IPHONE_65,
                          APP_IPHONE_67,

                          APP_IPAD_97,
                          APP_IPAD_105,
                          APP_IPAD_PRO_3GEN_11,
                          APP_IPAD_PRO_129,
                          APP_IPAD_PRO_3GEN_129,

                          IMESSAGE_APP_IPHONE_40,
                          IMESSAGE_APP_IPHONE_47,
                          IMESSAGE_APP_IPHONE_55,
                          IMESSAGE_APP_IPHONE_58,
                          IMESSAGE_APP_IPHONE_61,
                          IMESSAGE_APP_IPHONE_65,
                          IMESSAGE_APP_IPHONE_67,

                          IMESSAGE_APP_IPAD_97,
                          IMESSAGE_APP_IPAD_105,
                          IMESSAGE_APP_IPAD_PRO_129,
                          IMESSAGE_APP_IPAD_PRO_3GEN_11,
                          IMESSAGE_APP_IPAD_PRO_3GEN_129,

                          APP_WATCH_SERIES_3,
                          APP_WATCH_SERIES_4,
                          APP_WATCH_SERIES_7,
                          APP_WATCH_SERIES_10,
                          APP_WATCH_ULTRA,

                          APP_DESKTOP,
                          APP_APPLE_VISION_PRO
                        ]
                      end

                      attr_mapping({
                        "screenshotDisplayType" => "screenshot_display_type",

                        "appScreenshots" => "app_screenshots"
                      })

                      def self.type
                        return "appScreenshotSets"
                      end

                      def apple_tv?
                        DisplayType::APP_APPLE_TV == screenshot_display_type
                      end

                      def imessage?
                        DisplayType::ALL_IMESSAGE.include?(screenshot_display_type)
                      end

                      #
                      # API
                      #

                      def self.all(client: nil, app_store_version_localization_id: nil, filter: {}, includes: nil, limit: nil, sort: nil)
                        client ||= Spaceship::ConnectAPI
                        resp = client.get_app_screenshot_sets(app_store_version_localization_id: app_store_version_localization_id, filter: filter, includes: includes, limit: limit, sort: sort)
                        return resp.to_models
                      end

                      def self.get(client: nil, app_screenshot_set_id: nil, includes: "appScreenshots")
                        client ||= Spaceship::ConnectAPI
                        return client.get_app_screenshot_set(app_screenshot_set_id: app_screenshot_set_id, filter: nil, includes: includes, limit: nil, sort: nil).first
                      end

                      def delete!(client: nil, filter: {}, includes: nil, limit: nil, sort: nil)
                        client ||= Spaceship::ConnectAPI
                        return client.delete_app_screenshot_set(app_screenshot_set_id: id)
                      end

                      def upload_screenshot(client: nil, path: nil, wait_for_processing: true, position: nil)
                        client ||= Spaceship::ConnectAPI
                        screenshot = Spaceship::ConnectAPI::AppScreenshot.create(client: client, app_screenshot_set_id: id, path: path, wait_for_processing: wait_for_processing)

                        # Reposition (if specified)
                        unless position.nil?
                          # Get all app preview ids
                          set = AppScreenshotSet.get(client: client, app_screenshot_set_id: id)
                          app_screenshot_ids = set.app_screenshots.map(&:id)

                          # Remove new uploaded screenshot
                          app_screenshot_ids.delete(screenshot.id)

                          # Insert screenshot at specified position
                          app_screenshot_ids = app_screenshot_ids.insert(position, screenshot.id).compact

                          # Reorder screenshots
                          reorder_screenshots(client: client, app_screenshot_ids: app_screenshot_ids)
                        end

                        return screenshot
                      end

                      def reorder_screenshots(client: nil, app_screenshot_ids: nil)
                        client ||= Spaceship::ConnectAPI
                        client.patch_app_screenshot_set_screenshots(app_screenshot_set_id: id, app_screenshot_ids: app_screenshot_ids)

                        return client.get_app_screenshot_set(app_screenshot_set_id: id, includes: "appScreenshots").first
                      end
                    end
                  end
                end`


After patching these two files, my visionOS screenshot upload worked fine.

But now after installing the new version, it has started breaking with the DisplayType is not allowed error

Any advice on what can I change to troubleshoot further ? Thanks

P.S : This is what my fastlane folder structure looks like

image

**Comment by sirghi** [comment]
Hi @aj3011, if you checkout fastlane's git history, you'll see that 2.229.1 was released before my changes were merged. So we'll have to wait for the next release for to get them. Or you can point your Gemfile to the `master` branch.

**Comment by flythenimbus** [comment]
@sirghi when can I get the latest update via homebrew?
