### PR TITLE
[gym][pilot] Add `AppStoreInfo.plist` support for TestFlight uploads on non-macOS platforms

### LINKED ISSUE #29608: Deprecated Transporter usage
### Issue Description
When using the newly released iTunesTransporter support for `pilot` on Linux results in a warning for deprecated transporter usage.

> parameter Warnings = [Deprecated Transporter usage. No action is required at this time. However, starting in 2026, you’ll be required to use the -assetFile command instead of the -f command with your .ipa or .pkg files. Additionally, to continue uploading apps using the Aspera and Signiant delivery methods, you’ll be required to use a version of Transporter that will be released later this year.]

##### Command executed
`fastlane pilot upload --apple_id ***** --skip_submission true --skip_waiting_for_build_processing true --ipa "/home/test4.ipa" --verbose`

##### Complete output when running fastlane, including the stack trace and command used
```
INFO [2025-06-09 19:25:26.25]: Sending anonymous analytics information
INFO [2025-06-09 19:25:26.25]: Learn more at https://docs.fastlane.tools/#metrics
INFO [2025-06-09 19:25:26.25]: No personal or sensitive data is sent.
INFO [2025-06-09 19:25:26.25]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
INFO [2025-06-09 19:25:26.32]: Ready to upload new build to TestFlight (App:*****)...
DEBUG [2025-06-09 19:25:26.36]: App Platform (ios)
DEBUG [2025-06-09 19:25:26.46]: App identifier (*****)
INFO [2025-06-09 19:25:26.94]: Wrote XML data to '/tmp/d20250609-1-uee8jw/1597361384-3db35640-dcab-44e6-8519-868064f5fe4e.itmsp'
INFO [2025-06-09 19:25:26.94]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
DEBUG [2025-06-09 19:25:26.94]: Using iTMSTransporter as transporter.
INFO [2025-06-09 19:25:26.94]: Going to upload updated app to App Store Connect
INFO [2025-06-09 19:25:26.95]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2025-06-09 19:25:26.95]: "/usr/local/itms/bin/iTMSTransporter" -m upload -u **** -p 'YourPassword' -f /tmp/d20250609-1-uee8jw/1597361384-3db35640-dcab-44e6-8519-868064f5fe4e.itmsp -k 100000
......
......
......
DEBUG [2025-06-09 19:26:46.33]: [Transporter]: INFO: The package: /tmp/d20250609-1-uee8jw/1597361384-3db35640-dcab-44e6-8519-868064f5fe4e.itmsp has been successfully uploaded.
DEBUG [2025-06-09 19:26:46.68]: [Transporter]: INFO: The following warnings were received from Apple's web service ...
WARN [2025-06-09 19:26:46.68]: [Transporter Warning Output]: Deprecated Transporter usage. No action is required at this time. However, starting in 2026, you’ll be required to use the -assetFile command instead of the -f command with your .ipa or .pkg files. Additionally, to continue uploading apps using the Aspera and Signiant delivery methods, you’ll be required to use a version of Transporter that will be released later this year.
INFO [2025-06-09 19:26:47.00]: iTunes Transporter successfully finished its job
DEBUG [2025-06-09 19:26:47.00]: [Transporter]: DBG-X: Returning 0
WARN [2025-06-09 19:26:47.50]: Deprecated Transporter usage. No action is required at this time. However, starting in 2026, you’ll be required to use the -assetFile command instead of the -f command with your .ipa or .pkg files. Additionally, to continue uploading apps using the Aspera and Signiant delivery methods, you’ll be required to use a version of Transporter that will be released later this year.
INFO [2025-06-09 19:26:47.50]: -----------------------------------------------------
INFO [2025-06-09 19:26:47.50]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
INFO [2025-06-09 19:26:47.50]: -----------------------------------------------------
INFO [2025-06-09 19:26:47.51]: Successfully uploaded the new binary to App Store Connect
WARN [2025-06-09 19:26:47.51]: `skip_waiting_for_build_processing` used and no `changelog` supplied - skipping waiting for build processing
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                     |
| --------------------------- | --------------------------------------------------------- |
| OS                          | debian_based 11.11                                        |
| Ruby                        | 3.4.2                                                     |
| Bundler?                    | false                                                     |
| Git                         | git version 2.30.2                                        |
| Installation Source         | /usr/local/bundle/bin/fastlane                            |
| Host                        | Debian GNU/Linux 11 debian_based 11.11 (6.10.14-linuxkit) |
| Ruby Lib Dir                | /usr/local/lib                                            |
| OpenSSL Version             | OpenSSL 1.1.1w  11 Sep 2023                               |
| Is contained                | false                                                     |
| Is homebrew                 | false                                                     |
| Is installed via Fabric.app | false                                                     |

### System Locale

| Variable | Value   |   |
| -------- | ------- | - |
| LANG     | C.UTF-8 | ✅ |
| LC_ALL   |         |   |
| LANGUAGE |         |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.227.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.7.0        |
| did_you_mean                    | 2.0.0        |
| syntax_suggest                  | 2.0.2        |
| public_suffix                   | 6.0.2        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| aws-eventstream                 | 1.3.2        |
| aws-partitions                  | 1.1099.0     |
| aws-sigv4                       | 1.11.0       |
| base64                          | 0.2.0        |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.223.0      |
| aws-sdk-kms                     | 1.100.0      |
| aws-sdk-s3                      | 1.185.0      |
| babosa                          | 1.0.4        |
| nkf                             | 0.2.0        |
| CFPropertyList                  | 3.0.7        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.1.0        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.8        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.4.0        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.5        |
| jwt                             | 2.10.1       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.20.0       |
| googleauth                      | 1.8.1        |
| mutex_m                         | 0.3.0        |
| httpclient                      | 2.9.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.5.0        |
| google-cloud-core               | 1.8.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.7.0        |
| google-cloud-storage            | 1.47.0       |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.6.0        |
| plist                           | 3.7.2        |
| rubyzip                         | 2.4.1        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| atomos                          | 0.1.3        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.1        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.1.1        |
| logger                          | 1.7.0        |
| bundler                         | 2.6.2        |
| rexml                           | 3.4.1        |
| json                            | 2.11.3       |
| forwardable                     | 1.3.3        |
| pathname                        | 0.4.0        |
| shellwords                      | 0.2.2        |
| cgi                             | 0.4.1        |
| date                            | 3.4.1        |
| timeout                         | 0.4.3        |
| stringio                        | 3.1.2        |
| securerandom                    | 0.4.1        |
| uri                             | 1.0.2        |
| ipaddr                          | 1.2.7        |
| openssl                         | 3.3.0        |
| digest                          | 3.2.0        |
| io-nonblock                     | 0.3.1        |
| zlib                            | 3.2.1        |
| resolv                          | 0.6.0        |
| io-wait                         | 0.3.1        |
| time                            | 0.4.1        |
| open-uri                        | 0.5.0        |
| net-http                        | 0.6.0        |
| net-protocol                    | 0.2.2        |
| english                         | 0.8.0        |
| erb                             | 4.0.4        |
| strscan                         | 3.1.2        |
| abbrev                          | 0.1.2        |
| io-console                      | 0.8.0        |
| tempfile                        | 0.3.1        |
| delegate                        | 0.4.0        |
| fileutils                       | 1.7.3        |
| tmpdir                          | 0.3.1        |
| etc                             | 1.4.5        |
| singleton                       | 0.3.0        |
| open3                           | 0.2.1        |
| prettyprint                     | 0.2.0        |
| pp                              | 0.6.2        |
| find                            | 0.2.0        |
| ostruct                         | 0.6.1        |
| yaml                            | 0.4.0        |
| psych                           | 5.2.2        |
</details>

*generated on:* **2025-06-09**
</details>

### PR DESCRIPTION
**Pull request by ccaruceru**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

fixes #29608
fixes: #29719
related to https://github.com/fastlane/fastlane/pull/22014
closes: #29706
closes: #29707
closes: #29708

### Description

Add support for generating and using `AppStoreInfo.plist` files when uploading iOS apps to TestFlight from non-macOS platforms (Linux/Windows). This addresses compatibility requirements introduced in Apple Transporter 4.1+ for non-macOS uploads.

Changes in this PR:
- add `AppStoreInfo.plist` generation in `gym` with `--generate_appstore_info` option to make the plist file using `swinfo` (from Xcode install)
- change `ShellScriptTransporterExecutor` to use `-assetFile` and `-assetDescription` parameters for non-macOS uploads
- change `IpaUploadPackageBuilder` to copy existing `AppStoreInfo.plist` files alongside .ipa file for non-macOS platforms
- update and add tests
- update docs

#### Build on macOS and upload from Linux

On macOS:
```
[bundle exec] fastlane gym --export_method app-store --output_directory ./build --output_name my-app.ipa [...] --generate_appstore_info
```

On Linux:
```
# install Transporter from https://help.apple.com/itc/transporteruserguide/#/
export FASTLANE_ITUNES_TRANSPORTER_PATH=/usr/local/itms FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=true

### 1. copy my-app.ipa to current directory
# upload and observe it fails to detect AppstoreInfo.plist
[bundle exec] fastlane run pilot ipa:build/my-app.ipa [...]

### 2. copy AppstoreInfo.plist to current directory
# upload and it succeeds
[bundle exec] fastlane run pilot ipa:build/my-app.ipa [...]
```

#### Build and upload on macOS 

_Additionally validate that building and uploading is still working on macOS with Transporter_

```
[bundle exec] fastlane gym --export_method app-store --output_directory ./build --output_name my-app.ipa [...]
export FASTLANE_ITUNES_TRANSPORTER_PATH=/usr/local/itms FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=true
[bundle exec] fastlane run pilot ipa:build/my-app.ipa [...]
```

### CODE REVIEW

**Comment by ccaruceru** [comment]
@AliSoftware it appears me and @jtlthe2 have proposed similar solutions for the same problem (his changes are in #29706 #29707 and #29708).

I would rather let one of the maintainers decide how should we move forward 🙃

**Comment by kricha** [comment]
@AliSoftware any chances this will be added in near future releases?

**Comment by mscheurwater** [comment]
Hi! Any update on this being merged soon? It seems Apple will shut the current flow down next month. It would be amazing to have a solution in place before this.

**Comment by AliSoftware** [comment]
I don't have a Linux machine nor project to test this in a real project; has anyone put that PR to the test on a real-world project?

**Comment by iBotPeaches** [comment]
The build failure is fixed on mainline if this is rebased. I've asked Copilot to a take a peek

**Comment by ccaruceru** [comment]
> I don't have a Linux machine nor project to test this in a real project; has anyone put that PR to the test on a real-world project?

you don't need an actual linux box, you can test it out on macOS too, inside Docker 🙂

I wrote below some steps on how to install transporter + fastlane and give it a go:

`docker run --rm -it --platform linux/amd64 -v /path/to/folder/with/ipa_and_generated_appstoreplist:/ipa alpine`

```shell
# install build dependencies
apk add curl procps git ruby-dev make gcc musl-dev

# get and run transporter
curl -fsSL https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/resources/download/public/Transporter__Linux/bin > installer.sh
sh installer.sh

# install custom fastlane
cat > Gemfile << EOF
source "https://rubygems.org"
gem "fastlane", git: "https://github.com/ccaruceru/fastlane.git", branch: 'feature/gym-generate-AppStoreInfo-plist-for-transporter-uploads-on-linux'
EOF
bundle install

# run
export LC_ALL=C.UTF-8 FASTLANE_ITUNES_TRANSPORTER_PATH=/usr/local/itms FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=true
bundle exec fastlane --version
bundle exec fastlane run pilot ipa:/ipa/my-app.ipa # ...
```

---

> The build failure is fixed on mainline if this is rebased. I've asked Copilot to a take a peek

thanks! I'll have a look today

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 1]
```diff
@@ -478,6 +482,27 @@ def handle_error(password)
       UI.error("Could not download/upload from App Store Connect! It's probably related to your password or your internet connection.")
     end
 
+    def file_upload_option(source)
+      # uploading packages on non-macOS platforms requires AppStoreInfo.plist starting with Transporter >= 4.1
+      if !Helper.is_mac? && File.directory?(source)
+        asset_file = Dir.glob(File.join(source, "*.{#{allowed_package_extensions.join(',')}}")).first
```
[the remark this answers is not in the document]
Comment (ccaruceru) [reply fastlane_core/lib/fastlane_core/itunes_transporter.rb:488]: theoretically the existence of the package file has already been checked at a higher level, but I guess it doesn't hurt to double check for it in case someone uses the `TransporterExecutor` directly.

**Comment by ccaruceru** [comment]
this should be ready for review now

File: fastlane_core/spec/itunes_transporter_spec.rb [hunk 2]
```diff
@@ -13,8 +13,15 @@
...
     end
 
-    def shell_upload_command(provider_short_name: nil, transporter: nil, jwt: nil, use_asset_path: false, username: email, input_pass: password, api_key: nil)
-      upload_part = use_asset_path ? "-assetFile /tmp/#{random_uuid}.ipa" : "-f /tmp/my.app.id.itmsp"
+    def shell_upload_command(provider_short_name: nil, transporter: nil, jwt: nil, use_asset_path: false, username: email, input_pass: password, api_key: nil, is_mac: true, has_appstore_info: true)
+      upload_part = if use_asset_path
+                      "-assetFile /tmp/#{random_uuid}.ipa"
+                    elsif !is_mac && has_appstore_info
+                      # On non-macOS platforms, use -assetFile with -assetDescription for .itmsp directories
+                      "-assetFile /tmp/my.app.id.itmsp/my.app.id.ipa -assetDescription /tmp/my.app.id.itmsp/AppStoreInfo.plist"
```
Comment (lacostej) [inline fastlane_core/spec/itunes_transporter_spec.rb:21]: this hardcoded path is weird. Where does it come from?

Comment (ccaruceru) [reply fastlane_core/spec/itunes_transporter_spec.rb:21]: the `/tmp` base path seems to be simulating the `Dir.mktmpdir` in [BuildManager.upload](https://github.com/fastlane/fastlane/blob/b5aebe450ab1132014b62d8df1aef269ac5af89e/pilot/lib/pilot/build_manager.rb#L30), which in turn sets `package_path` in [IpaUploadPackageBuilder.generate](https://github.com/fastlane/fastlane/blob/b5aebe450ab1132014b62d8df1aef269ac5af89e/fastlane_core/lib/fastlane_core/ipa_upload_package_builder.rb#L15), and that will end up to our `ItunesTransporter.upload` method.

then the "my.app.id.itmsp" part is usually set by either [ItunesTransporter.upload](https://github.com/fastlane/fastlane/blob/b5aebe450ab1132014b62d8df1aef269ac5af89e/fastlane_core/lib/fastlane_core/itunes_transporter.rb#L796) depending on the input args, or even in [IpaUploadPackageBuilder.generate](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ipa_upload_package_builder.rb#L16) since the beginning.
(_I know. it's complicated_)

as for "my.app.id.ipa", I just wanted to be consistent with what was used in the rest of the file.

in the end, I'm not sure if there's a better way to write those paths w/o doing a major refactoring of this test file 😕

**Comment by iBotPeaches** [comment]
As I review this my biggest confusion is how did we get to this point? Is there some source that Apple says building on non-mac requires x,y,z and this is it? Trial and error? Anything I can read to help understand generation/requirement around `AppStoreInfo.plist`.

**Comment by ccaruceru** [comment]
> As I review this my biggest confusion is how did we get to this point? Is there some source that Apple says building on non-mac requires x,y,z and this is it? Trial and error? Anything I can read to help understand generation/requirement around `AppStoreInfo.plist`.

There's a deprecation notice that we're getting when running Transporter on Linux which is mentioned in #29608, that I can confirm I get in my CI runs too. The message says starting with 2026 we need to use `-assetFile` instead of `-f` for uploads, and `-assetFile` implies `-assetDescription` for the appstoreinfo.plist.

I tried looking for any changes in in their [release notes](https://help.apple.com/itc/transporteruserguide/en.lproj/static.html#apdA1aded1d2) but can't find anything relevant there.

As for `AppStoreInfo.plist`, other than searching the web and finding results on how to make one, I can't find any apple docs on what is that about or what are the important bits so we can make it ourselves. As you can see in the screenshot below it contains too many fields to generate that with ruby in a sane way.

How comes this is not an issue on macOS? Because transporter automatically calls for `swinfo` to analyze the input file before uploading if no `-assetDescription` arg is provided.

<details>
<summary>Screenshot</summary>

image

</details>

**Review by iBotPeaches — APPROVED** [review]
Took a bit of pre-setup, but I finally got our sample application uploaded via docker container. Personally with our setup taking most the time on the actual build (mac) then I don't see how the upload stage being on linux being much of a cost saver, but thats irrelevant for this.

I confirmed it works - Copilot is happy. Author is same as the last iteration of this so feel confident they also know it works.

**Comment by ccaruceru** [comment]
> Took a bit of pre-setup, but I finally got our sample application uploaded via docker container. Personally with our setup taking most the time on the actual build (mac) then I don't see how the upload stage being on linux being much of a cost saver, but thats irrelevant for this.

Thanks a lot for the review! About the cost saving part, I would agree as well for regular apps. The app I'm building is about 700mb and the post process on App Store Connect takes between 5 to 20 minutes to complete. For anyone who's using mac cloud runners (like github actions) then the possibility of uploading from linux can potentially become a great cost saver for the idle mac resources 🙂

File: fastlane_core/spec/itunes_transporter_spec.rb (hunk 2 above)
Comment (lacostej) [reply fastlane_core/spec/itunes_transporter_spec.rb:21]: Let's keep it like this for now.

**Review by lacostej — APPROVED** [review]
