### PR TITLE
[action] create_xcframework - delete .xcframework if already exists

### LINKED ISSUE #18344: [create_xcframework] Creating fails if .xcframework already exists
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

create_xcframework fails if .xcframework already exists in output folder.
Error:
`“<framework_name>.framework” couldn’t be copied to “ios-arm64” because an item with the same name already exists.`
##### Command executed

create_xcframework(
      frameworks: ["<path_to_framework>", "<path_to_second_framework>"],
      output: "<path_to_xcframework>"
    )
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by Kukurijek**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #18344
### Description
`create_xcframework` now checks if xcframework already exists in output folder, so you do not need to delete it manually.
If there is, delete it and display message "Deleting existing: <path_to_framework>"

Please add new label "xcframework" to github repo. 🙏

### Testing Steps

Try to create xcframework with command `create_xcframework` twice, without deleting the old one (with identical name).

### CODE REVIEW

**Review by minuscorp — CHANGES_REQUESTED** [review]
One little comment about the failing tests, also, I'm worried about this maybe breaking an intentional behavior, so maybe another approach would be to add a `ConfigItem` to set the new behavior. Thoughts?

File: fastlane/lib/fastlane/actions/create_xcframework.rb [hunk 1]
```diff
@@ -14,9 +14,15 @@ def self.run(params)
...
 
+        if File.directory?(params[:output])
+          UI.message("Deleting existing: #{params[:output]}")
+          FileUtils.remove_dir(params[:output])
+        end
+
         Actions.lane_context[SharedValues::XCFRAMEWORK_PATH] = params[:output]
 
         sh(create_command)
+        UI.message("Successfully created: #{params[:output]}")
```
[the remark this answers is not in the document]
Comment (Kukurijek) [reply fastlane/lib/fastlane/actions/create_xcframework.rb]: That is right. I seem to have run tests on some other branch 🤦🤦🤦
I could just move this line up, but it is unnecessary, because the action prints anyway the absolute path where it was created 😅
So I removed this line.
Sorry and thanks 👍 👍

**Review by minuscorp — COMMENTED** [review]
Can you add tests regarding the behavior that is going to be introduced? 🙏

File: fastlane/spec/actions_specs/create_xcframework_spec.rb [hunk 2]
```diff
@@ -118,6 +118,31 @@
...
+        it "should fail due to the deleted xcframework" do
+          begin
+            Fastlane::FastFile.new.parse("lane :test do
+              create_xcframework(
+                frameworks: ['FrameworkA.framework', 'FrameworkB.framework'],
+                output: 'UniversalFramework.xcframework'
+              )
+            end").runner.execute(:test)
+          rescue => e
+            expect(e.to_s).to eq("No such file or directory @ apply2files - UniversalFramework.xcframework").or(eq("No such file or directory @ unlink_internal - UniversalFramework.xcframework"))
```
Comment (minuscorp) [inline fastlane/spec/actions_specs/create_xcframework_spec.rb:139]: Why is this being raised? It didn't supposed to delete the previous xcframework silently? Maybe I'm missing something here.

**Review by minuscorp — COMMENTED** [review]
Just a comment, but seems good to me

**Review by minuscorp — APPROVED** [review]
LGTM🚀

File: fastlane/spec/actions_specs/create_xcframework_spec.rb (hunk 2 above)
Comment (joshdholtz) [reply fastlane/spec/actions_specs/create_xcframework_spec.rb]: @minuscorp @Kukurijek I add a commit to expect `FileUtils.remove_dir` to be called that removes the testing for failure here. I think this change should work 🤷‍♂️ 

I also updated some existing tests while I was in here 😛 The testing of failures now use an rspec way to catching and testing errors.

**Comment by joshdholtz** [comment]
@googlebot I consent.
