### PR TITLE
[match][enterprise] Fix undefined method `in_house?' for nil

### LINKED ISSUE #21782: App Store Connect API for enterprise - undefined method `in_house?' for nil:NilClass
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

During enterprise certificate match with App Store Connect API Key, the command fails with error:

```
/Users/vagrant/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/fastlane-2.217.0/match/lib/match/runner.rb:50:in `run': [!] undefined method `in_house?' for nil:NilClass (NoMethodError)
--
05-Jan-2024 09:38:18 |  
05-Jan-2024 09:38:18 | if params[:type] == "enterprise" && !Spaceship.client.in_house?
```

For non enterprise match and in-house as false I can successfully run this lane.

##### Command executed

```
desc 'Refresh Provisioning Profile only with type'
  lane :refresh_profiles do |options|
    app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_content: options[:key_content],
      in_house: options[:in_house]
    )
    match(
      type: options[:type]
   )
  end

bundle exec fastlane refresh_profiles \
  key_id:${APP_STORE_CONNECT_KEY_ID} \
  issuer_id:${APP_STORE_CONNECT_ISSUER_ID} \
  key_content:"${APP_STORE_CONNECT_KEY_CONTENT}" \
  in_house:"true" \
  type:enterprise
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by rasberik**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

`Spaceship.client.in_house?` doesnt exist anywhere else in the codebase, and causing runtime failure under `enterprise` circumstances

### Description

Resolves https://github.com/fastlane/fastlane/issues/21782 and related to https://github.com/fastlane/fastlane/issues/22324

After recent [changes to enable enterprise API](https://github.com/fastlane/fastlane/pull/22215) and switching `app_store_connect_api_key` for enterprise - noticed errors in match that prevents its from running. 

Error: 
```
undefined method `in_house?' for nil
```

### Testing Steps

For _enterprise_, match for _enterprise_ with `app_store_connect_api_key`
```
sync_code_signing(
   git_branch: *_my_branch_*,
   team_id: *my_team_id_*,
   template_name: *my_template_name_*,
   type: 'enterprise',
   api_key: app_store_connect_api_key,
   app_identifier: *my_app_identitifers_*,
)
```

Required Env:
```
APP_STORE_CONNECT_API_KEY_KEY
APP_STORE_CONNECT_API_KEY_KEY_ID
(*) APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64
APP_STORE_CONNECT_API_KEY_ISSUER_ID
APP_STORE_CONNECT_API_KEY_IN_HOUSE
```

### CODE REVIEW

**Comment by rasberik** [comment]
No time to fill this out & maintain, so let me close. 

Those who face following errors can use this to patch it
```
undefined method `in_house?' for nil
```

**Comment by dxvid-pts** [comment]
Can confirm this worked. Sad to see

**Comment by dxvid-pts** [comment]
Is there a reason the PR is still in draft?

If you don't have time I can open a new PR with the same changes and handle the administrative stuff btw

**Comment by rasberik** [comment]
> Is there a reason the PR is still in draft?

Thanks! Getting maintainers attention is the only issue for me. Since you are interested, I can finish it up and hopefully it will get merged

**Comment by rasberik** [comment]
Added a test for related part of the code (doesn't prevent the underlying bug itself, but +coverage), ran all spec tests and rubocop format. 

@dxvid-pts Its my third open PR without maintainer attention, any help to get this merged would be appreciated 🙏🏻

**Comment by rasberik** [comment]
Failing [check](https://app.circleci.com/pipelines/github/fastlane/fastlane/6892/workflows/eb4cafb8-9ebb-4e54-a772-f7665f2667c5/jobs/105179/tests) is unrelated test from fastlane_core. Seems like environmental issue

File: match/spec/runner_spec.rb [hunk 1]
```diff
@@ -332,6 +332,39 @@
...
+          expect(fake_encryption).to receive(:decrypt_files).and_return(nil)
+
+          client = "client"
+          expect(Match::SpaceshipEnsure).to receive(:new)
+          expect(Spaceship::ConnectAPI).to receive(:client).and_return(client)
+          allow(client).to receive(:in_house?).and_return(false)
+
+          expect do
+            Match::Runner.new.run(config)
+          end.to raise_error("You defined the profile type 'enterprise', but your Apple account doesn't support In-House profiles")
```
Comment (rasberik) [inline match/spec/runner_spec.rb:366]: [note] This error wasn't covered earlier

**Comment by dxvid-pts** [comment]
> @dxvid-pts Its my third open PR without maintainer attention, any help to get this merged would be appreciated 🙏🏻

maybe @lacostej can help as he reviewed the related enterprise API PR?

**Comment by dxvid-pts** [comment]
Or @milch? He merged the related enterprise API PR.

**Comment by rasberik** [comment]
cc @mollyIV

**Comment by jnross** [comment]
I'd love to see this move forward as well.  We've long used match to manage certs and profiles.  Until now we've used a normal login with password and 2FA, but that doesn't seem to be working this week.  I'm trying to set this up with an API Key but am encountering this bug.  I'm wonder if the CircleCI failure here is really caused by this issue, or was a problem on main too the day that it ran 3 weeks ago.  Maybe if this check is re-run it will pass?

**Review by scott-hill-alkami — APPROVED** [review]

**Review by ekoRemDev — APPROVED** [review]

**Comment by Schr0eder** [comment]
Can confirm that it works with the changes. Would be nice if the PR could be merged.

**Comment by ffittschen** [comment]
@joshdholtz Is there any other way to reach the maintainers other than GitHub mentions? It seems like the mentions have no effect 😔

**Review by mollyIV — APPROVED** [review]
Thanks for making the change and so sorry for the review delay! Let's ship it 🚀

**Comment by rasberik** [comment]
@mollyIV Thanks, great news!

Sorry for overuse of your help, but can you please somehow help with this PR: https://github.com/fastlane/fastlane/pull/21254

The PR contributes to real $$ savings and doesn't contain any breaking changes. Any sort of help is appreciated like hooking up with `cert` maintainers.

**Comment by jnross** [comment]
@mollyIV:  Thanks so much for your help getting this landed.  I'll go clean up my `Gemfile` now :).
