### PR TITLE
[gym] update identifier used to looked up the bundle ID when parsing provisioning profile

### LINKED ISSUE #17864: `build_mac_app` parses profile incorrectly.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm building a macOS application using Fastlane. When my build gets to the `build_mac_app` action (running with `--verbose` flag), it fails with the following error:

```
INFO [2020-12-26 22:21:33.06]: ---------------------------
INFO [2020-12-26 22:21:33.06]: --- Step: build_mac_app ---
INFO [2020-12-26 22:21:33.06]: ---------------------------
ERROR [2020-12-26 22:21:33.13]: Couldn't load profile at path: /Users/john/src/johndbritton/teleport/Direct_com.abyssoft.teleport.provisionprofile
ERROR [2020-12-26 22:21:33.13]: undefined method `gsub' for nil:NilClass
DEBUG [2020-12-26 22:21:33.13]: /Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/build_app.rb:53:in `block in run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/build_app.rb:49:in `each'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/build_app.rb:49:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/build_mac_app.rb:21:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
Fastfile:17:in `block (2 levels) in parsing_binding'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-2.170.0/bin/fastlane:23:in `<top (required)>'
/Users/john/.rbenv/versions/2.7.2/bin/fastlane:23:in `load'
/Users/john/.rbenv/versions/2.7.2/bin/fastlane:23:in `<top (required)>'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/john/.dotfiles/dot/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/john/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/Users/john/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
```

I have confirmed that the profile does exist and it is accessible at the path `/Users/john/src/johndbritton/teleport/Direct_com.abyssoft.teleport.provisionprofile`. On further inspection, it seems that the code in `Fastlane::Actions::BuildAppAction` is failing to parse the profile correctly. Specifically this code:

https://github.com/fastlane/fastlane/blob/39786d318c311b005cd859d5a1d2bc55462b2fd5/fastlane/lib/fastlane/actions/build_app.rb#L53

is incorrect for my profile file. It's trying to access an element in the profile under the key `Entitlements` with the sub-key `application-identifier`. When I parse the file manually, there is no key `application-identifier` only a key `com.apple.application-identifier` which is what I think is needed.

My best guess is that this is something that Apple changed recently.

### PR DESCRIPTION
**Pull request by johndbritton**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
  - there are a few test failures currently (expected, due to not supporting the old key name yet)
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
  - none needed

### Motivation and Context

This is just a quick draft of trying to resolve https://github.com/fastlane/fastlane/issues/17864. This is my first time contributing to Fastlane (and also my first time using it) so I just wanted to file the issue and get a draft up to see if I'm going in the right direction.

### Description

When using the `build_mac_app` action, Fastlane parses the provisioning profile, but it errors out (see linked issue for more details) when it tries to read the application identifier from a key `application-identifier`. The profile contains the required info in the `com.apple.application-identifier` key, which I suppose was a change made by Apple, but I'm not entirely sure.

### Testing Steps

I made this change locally and it resolved my issue with parsing the provisioning profile.

### CODE REVIEW

**Comment by johndbritton** [comment]
@googlebot I signed it!

File: fastlane/lib/fastlane/actions/build_app.rb [hunk 1]
```diff
@@ -50,7 +50,7 @@ def self.run(values)
               begin
                 profile = FastlaneCore::ProvisioningProfile.parse(profile_path)
                 app_id_prefix = profile["ApplicationIdentifierPrefix"].first
-                bundle_id = profile["Entitlements"]["application-identifier"].gsub("#{app_id_prefix}.", "")
+                bundle_id = profile["Entitlements"]["com.apple.application-identifier"].gsub("#{app_id_prefix}.", "")
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/build_app.rb:53]:
```suggestion
                entitlements = profile["Entitlements"]
                bundle_id = (entitlements["application-identifier"] || entitlements["com.apple.application-identifier"]).gsub("#{app_id_prefix}.", "")
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This looks great! Thanks for finding this 😊 How do you feel about this suggestion so that it keeps backwards compatibility? 😇

**Comment by johndbritton** [comment]
> This looks great! Thanks for finding this 😊 How do you feel about this suggestion so that it keeps backwards compatibility? 😇

@joshdholtz yep I expected we'd change this, all good.

**Comment by johndbritton** [comment]
@joshdholtz I think this is good to go now. Not sure what is failing on CircleCI and I can't get access to the output without giving them read access to all private repositories on my account.

**Review by rogerluan — APPROVED** [review]
👌 nice find!

**Comment by rogerluan** [comment]
@johndbritton if you update your branch with fastlane's latest master, those CI issues should be gone 🙏

**Comment by johndbritton** [comment]
@rogerluan rebased off the latest master.

**Review by rogerluan — CHANGES_REQUESTED** [review]
@johndbritton could you fix the linter issues? 🙏 

```
Offenses:

fastlane/lib/fastlane/actions/build_app.rb:11:7: C: Perceived complexity for run is too high. [19/18]
      def self.run(values)
      ^^^
```

**Comment by johndbritton** [comment]
@rogerluan This is what I get when I run the linter locally:

```
bundle exec rubocop fastlane/lib/fastlane/actions/build_mac_app.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

The `run` method is indeed quite complex, but I believe that's out of the scope of this pull request. Maybe someone else who is more familiar with this codebase can tidy that method up. Or we could ignore the complexity check for this method.

**Comment by rogerluan** [comment]
@googlebot I consent.

**Comment by rogerluan** [comment]
@johndbritton huh weird that it doesn't show the issue locally 🤔 

Anyway, usually I'd be against skipping these kind of lints because master is fine and this PR is supposedly adding the extra complexity that makes this function "too complex". However, I'm fine with adding a rubocop comment to disable complexity check for this function, because it already looks overly complex, and it looks like the # `rubocop:disable Metrics/PerceivedComplexity` should already be there anything (since there's a `:enable` matching comment at the end of that function).

I've added it, since I was already at it 😊 hope you don't mind. 

```
be rubocop fastlane/lib/fastlane/actions/build_app.rb
Inspecting 1 file
.

1 file inspected, no offenses detected
```

**Review by rogerluan — APPROVED** [review]
👌

**Comment by johndbritton** [comment]
> I've added it, since I was already at it 😊 hope you don't mind.

Thanks!

**Comment by johndbritton** [comment]
@joshdholtz I think this needs your approval to be merged.

**Comment by joshdholtz** [comment]
@johndbritton Ah sorry! Merging now and releasing today 💪 Being new parent has got me all sorts of behind 😅

**Review by joshdholtz — APPROVED** [review]
Thanks for making these changes! I really appreciate the contribution ❤️
