### PR TITLE
Pilot: Refactor ipa path expansion

### LINKED ISSUE #9480: [Pilot] Cannot reference home directory in "ipa" parameter
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Passing a path including a reference to the user's home directory fails in Pilot.

```
    pilot(
      # other args...
      ipa: "~/some/path/to/app.ipa"
    )
```

### Captured Output

Command Used: `foo`
<details><summary>Output/Log</summary>

```

INFO [2017-06-14 16:32:05.48]: Driving the lane 'ios foo' 🚀
INFO [2017-06-14 16:32:05.48]: -------------------
INFO [2017-06-14 16:32:05.48]: --- Step: pilot ---
INFO [2017-06-14 16:32:05.48]: -------------------
ERROR [2017-06-14 16:32:05.51]: Error setting value '~/builds/iOS/core_app/prod/MyApp_243_1.ipa' for option 'ipa'
ERROR [2017-06-14 16:32:05.51]: You passed invalid parameters to 'pilot'.
ERROR [2017-06-14 16:32:05.51]: Check out the error below and available options by running `fastlane action pilot`
WARN [2017-06-14 16:32:05.90]: Lane Context:
INFO [2017-06-14 16:32:05.90]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios foo"}
ERROR [2017-06-14 16:32:05.90]: Could not find ipa file at path '~/builds/iOS/core_app/prod/MyApp_243_1.ipa'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | xcversion           | 4           |
| 3    | xcode_select        | 0           |
| 4    | default_platform    | 0           |
| 💥   | pilot               | 0           |
+------+---------------------+-------------+

ERROR [2017-06-14 16:32:05.93]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.2.4/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.4/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### PR DESCRIPTION
**Pull request by nickffox**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

During the last round of feedback/fixes on #9481, the main use case stopped working (sorry! I should have caught this :pensive:). This refactor moves the path expansion to seemingly the first place available in the Pilot action.

### Description
 * Reverts most of #9481, and re-implements a better way.
 * Fixes #9480

### CODE REVIEW

File: fastlane/lib/fastlane/actions/pilot.rb [hunk 1]
```diff
@@ -9,6 +9,7 @@ def self.run(values)
         values[:changelog] ||= changelog if changelog
 
         values[:ipa] ||= Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
+        values[:ipa] = File.expand_path(values[:ipa]) if values[:ipa]
```
Comment (taquitos) [inline fastlane/lib/fastlane/actions/pilot.rb]: This is slightly confusing to me, I'd probably update this to be:
```
ipa_path_from_context = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
values[:ipa] ||= File.expand_path(ipa_path_from_context) if ipa_path_from_context
```

File: pilot/lib/pilot/commands_generator.rb [hunk 2]
```diff
@@ -158,11 +158,5 @@ def run
 
       run!
     end
-
-    def create_config(options)
```
Comment (taquitos) [inline pilot/lib/pilot/commands_generator.rb]: I actually like having this method here, I think it's cleaner than having `FastlaneCore::Configuration.create(Pilot::Options.available_options, convert_options(options))` sprinkled throughout. 
It pushes off the implementation details of creating a config to a single method and IMO looks better at the call site.
Maybe just change the method so that it only does `FastlaneCore::Configuration.create` work

This is of course just an opinion, so take it our leave 👍

**Review by taquitos — CHANGES_REQUESTED** [review]
This is great, maybe after clearing up the `values[:ipa]` logic, it's ready.

File: pilot/lib/pilot/commands_generator.rb (hunk 2 above)
Comment (NicholasFFox) [inline pilot/lib/pilot/commands_generator.rb]: 👍  I'll roll this change back.

File: fastlane/lib/fastlane/actions/pilot.rb (hunk 1 above)
Comment (NicholasFFox) [inline fastlane/lib/fastlane/actions/pilot.rb]: @taquitos the only issue with this approach is that if values[:ipa] is passed in, the path won't be expanded.

Maybe something like this?
```
ipa_path_from_context = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]
values[:ipa] ||= ipa_path_from_context
values[:ipa] = File.expand_path(values[:ipa]) if values[:ipa]
```

Comment (taquitos) [inline fastlane/lib/fastlane/actions/pilot.rb]: Ohhh good point, I think your original change is fine then 👍  I just didn't realize that values[:ipa] could already exist at that point.

**Review by taquitos — APPROVED** [review]
