### PR TITLE
[deliver][produce][spaceship] Update to use new App Store Connect API endpoints

### LINKED ISSUE #16639: Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
This release candidate is in response to #16621 

Includes PR: #16626

## Release Notes

*There will be a link to the pre-release information here soon*

### Bundler

Update your `Gemfile` to include the following:
```rb
gem "fastlane", ">= 2.150.rc5"
```

And then run:
```sh
bundle update fastlane
```

### Rubygems

```sh
gem install fastlane --pre
```

or

```sh
gem install fastlane -v 2.150.0.rc5
```

### LINKED ISSUE #16649: Produce fails to create app on AppStoreConnect with error Bundle ID already used
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am trying to create new Apps on AppStoreConnect using an script that I have and that worked many times in the past.

Right now, it is failing with the following error being thrown
```
[20:07:54]: Creating new app 'XXXXXX' on iTunes Connect
The `version` parameter is deprecated. Use `ensure_version!` method instead
/Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/fastlane-2.150.0.rc1/spaceship/lib/spaceship/tunes/tunes_client.rb:230:in `handle_itc_response': The Bundle ID you entered has already been used. The Bundle ID you entered has already been used. (Spaceship::Tunes::Error)
	from /Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/fastlane-2.150.0.rc1/spaceship/lib/spaceship/tunes/tunes_client.rb:325:in `create_application!'
	from /Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/fastlane-2.150.0.rc1/spaceship/lib/spaceship/tunes/application.rb:96:in `create!'
	from /Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/produce-2.0.0/lib/produce/itunes_connect.rb:25:in `create_new_app'
	from /Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/produce-2.0.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Users/guilhermeg/.rvm/gems/ruby-2.4.9/gems/produce-2.0.0/lib/produce/manager.rb:8:in `start_producing'
	from create_itc_apps.rb:66:in `block in <main>'
	from create_itc_apps.rb:59:in `map'
	from create_itc_apps.rb:59:in `<main>'
```

It is as though the AppStoreConnect returned this error message. However I believe it may be due the latest update on AppStoreConnect and some part of our API that broke with it.

When I go to AppStoreConnect and create the App with same bundleID though the Web Interface, it works. So the Bundle ID is indeed valid. The error is misleading

I upgraded to 2.150.rc1 as mentioned on issue #16621 and #16639 to no avail.

##### Command executed
I execute a ruby script that runs the following
```
FastlaneCore::CommanderGenerator.new.generate(Produce::Options.available_options)
    Produce.config = FastlaneCore::Configuration.create(Produce::Options.available_options, options)
    puts Produce::Manager.start_producing
```

The options passed as argument are:
```
app_identifier: bundle_id,
    sku: bundle_id,
    app_name: "MyApp",
    app_version: "1.0.0",
    language: 'English',
    platform: "ios",
    team_id: 'XYZXYZ',
    itc_team_id: 00000,
    itc_team_name: 'My Company',
    skip_devcenter: true,
    username: username
```

### Environment

<details>
  <pre> ### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.5                                     |
| Ruby                        | 2.4.9                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.1 (Apple Git-122.3)        |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane |
| Host                        | Mac OS X 10.14.5 (18F203)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.9/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.3.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version     | Update-Status |
| -------- | ----------- | ------------- |
| fastlane | 2.150.0.rc1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| emoji_regex               | 1.0.1        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.332.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.69.1       |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.16.0       |
| unicode-display_width     | 1.7.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| excon                     | 0.75.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| dotenv                    | 2.7.5        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| multi_json                | 1.14.1       |
| signet                    | 0.14.0       |
| os                        | 1.1.0        |
| memoist                   | 0.16.2       |
| googleauth                | 0.13.0       |
| digest-crc                | 0.5.1        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-env          | 1.3.2        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| openssl                   | 2.0.9        |
| io-console                | 0.4.6        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2020-06-22**
 </pre>
</details>

### LINKED ISSUE #16653: [DELIVER] Support new App Store Connect APIs ✨
#### Motivation Behind Feature

Just in the last few weeks, Apple broke some undocumented APIs that fastlane was using to interact with App Store Connect.  Fastlane should prefer to use documented public APIs where possible to avoid these kinds of situations in the future.

[What's new in App Store Connect](https://developer.apple.com/videos/play/wwdc2020/10651/
)
> We're excited to be adding two powerful new sets of API.  We'll be introducing a suite of app metadata API that will let you manage your presence on the App Store as well as a new power and performance API. They'll let you download the same aggregate data that drives the new power and performance analysis tools in Xcode.  In fact, just between these two new categories of API functionality, **we're adding over 200 new endpoints**.  For app metadata, you'll be able to do things like create new App Store versions, set pricing and availability, edit app and version metadata, associate builds to your App Store versions, and submit those versions for review.  

Another session later this week will go more in-depth [Expanding automation with the App Store Connect API](https://developer.apple.com/videos/play/wwdc2020/10004/)

#### Feature Description

This can be more fleshed out later in the week when the other session becomes available to give more concrete info on what APIs will be available

#### Alternatives or Workarounds

Continue to use undocumented APIs that might break in the future

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #16639
Fixes https://github.com/fastlane/fastlane/issues/16649
Fixes https://github.com/fastlane/fastlane/issues/16653

## Fixes
- [x] deliver completely broken
  - Issue: #16621 
  - PR: #16626
- [x] deliver build processing shouldn't require app version
  - Issue: https://github.com/fastlane/fastlane/pull/16640#discussion_r443233736
  - Issue: https://github.com/fastlane/fastlane/issues/16663
  - Issue: https://github.com/fastlane/fastlane/issues/16648
  - PR: #16713
- [x] Completely new app gets: You must provide a value for the attribute 'usesNonExemptEncryption' with this request 
  - Issue: #16645
  - PR: #16646
- [x] `usesIdfa` - is there a way around?
  - Issue: https://github.com/fastlane/fastlane/pull/16626#issuecomment-647214671
  - Fixes: https://github.com/fastlane/fastlane/pull/16706
- [x] make sure primary category isn't getting cleared out if not being set
  - Issue: https://github.com/fastlane/fastlane/issues/16621#issuecomment-647143129
  - PR: https://github.com/fastlane/fastlane/pull/16652
- [x] produce broken
  - Issue: https://github.com/fastlane/fastlane/issues/16649
- [x] You must provide a value for the attribute 'honorsLimitedAdTracking'
  - Issue: https://github.com/fastlane/fastlane/issues/16621#issuecomment-647241384
  - PR: #16646
- [x] 504 gateway timeout on uploading screenshot (extend timeout???)
  - Issue: https://github.com/fastlane/fastlane/pull/16626#issuecomment-647127031
  - PR: #16667
  - PR: #16676
- [x] produce map previous languages
  - Issue: https://github.com/fastlane/fastlane/pull/16626#issuecomment-647378487
  - PR: #16656
- [x] add `:default` to languages for deliver
  - Issue: https://github.com/fastlane/fastlane/issues/16639#issuecomment-647366971
  - PR: #16657
- [x] category mapping validation (tell user thing was mapped and show link to new doc)
  - Issue: NONE
  - PR: #16652 
- [x] app rating (tell user thing was mapped and show link to new doc)
  - Issue: NONE
  - PR: #16655
- [x] fix `set_changelog`
  - Issue: https://github.com/fastlane/fastlane/issues/16639#issuecomment-647661174
  - PR: #16658
- [x] set "all territories"
  - Issue: https://github.com/fastlane/fastlane/pull/16640#issuecomment-648155512
  - PR: #16656
- [x] set "users" on produce app
- [ ] deprecate `submission_information` for new `idfa`, `content_rights`, and `export_options` options
- [x] app previews
  - Issue: https://github.com/fastlane/fastlane/pull/16640#issuecomment-648289796
  - PR: #16671
- [x] handle multi part file uploads
  - PR: #16684
- [x] set video upload preivew frame
  - Issue: https://github.com/fastlane/fastlane/pull/16640#issuecomment-649762454
  - PR: #16684
- [x] fix mapping for age rating which caused 500
  - Issue: https://github.com/fastlane/fastlane/issues/16639#issuecomment-650186800
- [ ] find replacement for spaceship::sandbox testers
  - Issue: https://github.com/fastlane/fastlane/pull/16640#issuecomment-649961733
- [x] fix issues with iTMSTransporting not starting JVM
  - Issue: #15323
  - Issue: https://github.com/fastlane/fastlane/issues/16639#issuecomment-649805838
  - PR: #16689
- [x] deliver screenshots - don’t uploaded if already uploaded
  - PR - https://github.com/fastlane/fastlane/pull/16694
- [ ] create bundle id with spaceship connect
  - Issue: https://github.com/fastlane/fastlane/issues/16649#issuecomment-651128619
- [x] fix company name on produce create
  - Issue: https://github.com/fastlane/fastlane/issues/16639#issuecomment-651120161
- [x] Images download with deliver show as wrong image type when re-uploading with deliver
- [ ] add spaceship API to enable B2b
  - Issue: https://github.com/fastlane/fastlane/pull/16640#issuecomment-651961122
- [ ] implement screenshot order
  - Issue: https://github.com/fastlane/fastlane/issues/16708
  - PR: https://github.com/fastlane/fastlane/pull/16718

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          2 Warnings
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: deliver/lib/deliver/submit_for_review.rb [hunk 1]
```diff
@@ -1,132 +1,169 @@
...
+          platform: platform
+        ).first
+
         unless build
           UI.user_error!("Build number: #{options[:build_number]} does not exist")
         end
       else
         UI.message("Selecting the latest build...")
-        build = wait_for_build(app, app_version)
+        build = wait_for_build_processing_to_be_complete(app: app, platform: platform, options: options)
```
Comment (nafu) [inline deliver/lib/deliver/submit_for_review.rb:49]: @joshdholtz 

Thank you for your draft 👍
I tried this patch and found out this is not enough because old `wait_for_build` is more than `wait_for_build_processing_to_be_complete`.

`wait_for_build` get all build candidates and compare its upload_date to find latest_build before checking processing_to_be_complete.
When the fastlane user does not specify `app_version`, this changes will break their deliver.

Comment (joshdholtz) [reply deliver/lib/deliver/submit_for_review.rb:49]: Ahhhh, thanks!! I will look into fixing that 🙂

**Review by freedombonbon — APPROVED** [review]

File: deliver/lib/deliver/submit_for_review.rb (hunk 1 above)
Comment (joshdholtz) [reply deliver/lib/deliver/submit_for_review.rb:49]: @nafu Candidate builds aren't really a thing anymore so I'm not sure how to do this 😔 A build doesn't appear on the API for a few minutes either. It takes some time to "pre-process" before it actually shows up as processing 😬 

I'm not sure what the correct solution is there. This _may_ have to be a breaking change to where an `app_version` is specified? Or if no `app_version` is specified maybe we show a list of builds the user can select from?

I never really used `deliver` this way so I'm not sure what would be the best approach. Your thoughts would be appreciated! 😊

**Comment by mhleiftaylor** [comment]
Experienced never before seen issue with 2.150.0.rc1 (I have uploaded this screenshots with previous builds countless times).

```
build	22-Jun-2020 16:02:12	INFO [2020-06-22 16:02:12.32]: Uploading './fastlane/screenshots/en-US/1_ipadPro129_1.IMG_0003.PNG'...
build	22-Jun-2020 16:02:14	INFO [2020-06-22 16:02:14.54]: Uploading './fastlane/screenshots/en-US/1_ipadPro_1.ftl_8e54366bdef2671b5d04f2fa443297b9_0544223d6be3e1414093368560e9ef64.png'...
build	22-Jun-2020 16:02:16	INFO [2020-06-22 16:02:16.79]: Uploading './fastlane/screenshots/en-US/1_iphone65_1.IMG_0001 2.PNG'...
build	22-Jun-2020 16:02:19	INFO [2020-06-22 16:02:19.64]: Uploading './fastlane/screenshots/en-US/1_iphone6Plus_1.ftl_5eed57d595d4009d110f411c4791e01e_a14af0a93565fe43f6404e2feda508ad.png'...
build	22-Jun-2020 16:02:21	INFO [2020-06-22 16:02:21.40]: Uploading './fastlane/screenshots/en-US/2_ipadPro129_2.IMG_0005.PNG'...
build	22-Jun-2020 16:02:23	INFO [2020-06-22 16:02:23.43]: Uploading './fastlane/screenshots/en-US/2_ipadPro_2.ftl_9dd9cfdb7eeb8414d6c781874523a00e_1e0dbc22c57ed18ff08ed2e105dd4a5d.png'...
build	22-Jun-2020 16:02:25	INFO [2020-06-22 16:02:25.15]: Uploading './fastlane/screenshots/en-US/2_iphone65_2.IMG_0002.PNG'...
build	22-Jun-2020 16:02:26	INFO [2020-06-22 16:02:26.83]: Uploading './fastlane/screenshots/en-US/2_iphone6Plus_2.ftl_d990f67dbe32c01bcdd0ca75edf3f826_fb31e9e2cd2f196cdd37db428f2dced8.png'...
build	22-Jun-2020 16:02:28	INFO [2020-06-22 16:02:28.54]: [32mSuccessfully uploaded screenshots to App Store Connect[0m
build	22-Jun-2020 16:02:28	INFO [2020-06-22 16:02:28.54]: [32mFinished the upload to App Store Connect[0m
```

When I check the app on appstore connect I get the following error:
Screen Shot 2020-06-22 at 5 37 41 PM

**Comment by nzaghini-phorest** [comment]
Just wanted to confirm that the '504 gateway timeout on uploading screenshot' happens very often with new Apple API.

@mhleiftaylor we have delivered 10 apps with current RC using same screenshots we always did, assuming then Apple did not change requirements on size. 
Do you support multiple languages? We started to get misleading image size issues when we introduced multi lang and did not provide everything needed for all languages. Eventually we resorted in 2 deliver steps: first screenshots only and then metadata plus binary. This way the process worked as a charm.

**Comment by nzaghini-phorest** [comment]
Looks like there is another issue :( 

On new apps, by defaults, we get 0 territory associated in the 'Country or Region Availability' marking the app 'Removed from sale'.

My assumption is that before the default was 'all territories'.

I've been looking around to find a way to force 'all territories' from Fastfile but no luck ...

**Comment by joshdholtz** [comment]
@mhleiftaylor I did get this on my side and it was due to actually bad images on my side. I had to make sure I had PNGs with no alpha channel. Would you be able to go manually upload those screenshots to App Store Connect? I'm guessing you _should_ see the behavior (if its the same thing that happened to me).

@nzaghini-phorest Ah, I will add that to my list to look at! Thanks for letting me know ❤️

**Comment by kabamawutschnik** [comment]
@joshdholtz My organization has an interest to get app preview uploads working again. Using the 2.150.0 branch of fastlane, we are still seeing failures to save, in the form of 'unexpected error's. I'd like to contribute to resolving these issues, but I am having difficulty finding documentation for any sort of Apple API that would be useful. Can you provide links to API documentation that would get me started or the method in which you are finding the information. Thanks!

**Comment by joshdholtz** [comment]
@kabamawutschnik My plan was to have a PR this afternoon for this! I'll mention you in that PR when its ready which will contain example code 😊

**Comment by john-mejia** [comment]
Thanks for all your work in getting this up and running again. I'm having the same "unexpected error" issue on 2.150 when trying to submit an app for review. 

Here is a snippet of code in case it helps:
```
  Spaceship::Tunes.login
  Spaceship::Tunes.select_team
  ## Get the version that is in edit mode (not yet submitted)
  version = Spaceship::Tunes::Application.find(APP_ID_APPSTORE).edit_version
  current_build_number = version.current_build_number
  build = version.candidate_builds.select { |build| build.build_version == current_build_number }.first

  ## If build is processing, we cannot submit.
  if !build.processing
    version.select_build(build)
    version.toggle_phased_release(enabled: true)
    version.save!
```

When I run this manually, the error happens on the last line `version.save!`

**Comment by joshdholtz** [comment]
@john-mejia Pretty much everything in ` Spaceship::Tunes` will be broken and will be deprecated. More official App Store Connect APIs got added so almost all of that functionality will be now in `Spaceship::ConnectAPI`. We will be updating docs and examples with a lot this but the first goal is to discover all of the new endpoints and models and get everything working inside of the tools 😇

File: deliver/lib/deliver/upload_screenshots.rb [hunk 2]
```diff
@@ -11,69 +11,118 @@ def upload(options, screenshots)
...
+          # Only delete screenshots if trying to upload
+          next unless screenshots_per_language.keys.include?(localization.locale)
+
+          # Iterate over all screenshots for each set and delete
+          screenshot_sets = localization.get_app_screenshot_sets
+          screenshot_sets.each do |screenshot_set|
+            UI.message("Removing all previously uploaded screenshots for '#{localization.locale}' '#{screenshot_set.screenshot_display_type}'...")
+            screenshot_set.app_screenshots.each do |screenshot|
+              UI.verbose("Deleting screenshot - #{localization.locale} #{screenshot_set.screenshot_display_type} #{screenshot.id}")
+              screenshot.delete!
```
Comment (jhandguy) [inline deliver/lib/deliver/upload_screenshots.rb:41]: @joshdholtz this operation takes very long, could we maybe parallelize all those deletion requests, it now makes my builds timeout on Bitrise:
image

Comment (valerio-castelli) [reply deliver/lib/deliver/upload_screenshots.rb:41]: I'm trying this approach locally by using the [Parallel](https://github.com/grosser/parallel) gem, so far seems to work fine. It's a drop-in replacement for ruby's native iterators. I've tried changing `upload_screenshots.rb` from this:
```
if options[:overwrite_screenshots]
  # Get localizations on version
  localizations.each do |localization|
```
to this:
```
if options[:overwrite_screenshots]
  # Get localizations on version
  n_threads = [MAX_N_THREADS, localizations.length].min
  Parallel.each(localizations, in_threads: n_threads) do |localization|
```
where `MAX_N_THREADS` is just a constant I've empirically set to 8 to avoid incurring in rate limits.
Similarly for the upload operation, from this:
```
screenshots_per_language.each do |language, screenshots_for_language|
```
to this:
```
n_threads = [MAX_N_THREADS, screenshots_per_language.length].min
Parallel.each(screenshots_per_language, in_threads: n_threads) do |language, screenshots_for_language|
```

It seems to work fine so far, but I've also added a retry mechanism on these operations since the API is a bit flaky.

**Comment by jhandguy** [comment]
We're getting this error when uploading new screenshots, any idea?
Wasn't happening before the App Store Connect API update:
image

File: deliver/lib/deliver/upload_screenshots.rb (hunk 2 above)
Comment (joshdholtz) [reply deliver/lib/deliver/upload_screenshots.rb:41]: Yeah yeah, I've noticed it takes forever too. Was thinking about async but didn't want to jump the gun on that before other things 😬 But might need to happen.

**Comment by joshdholtz** [comment]
@jhandguy Does this happen to you if you manually upload those exact same screenshots to App Store Connect through the website?

**Comment by jhandguy** [comment]
Yes, it does also happen when uploading the same screenshots manually, could it be a problem on snapshot's side then (Imagemagick)?

**Comment by kabamawutschnik** [comment]
@joshdholtz I extended the spaceship timeout using `export SPACESHIP_TIMEOUT=1200` in my .bash_profile. Which allowed fastlane to successfully avoid the 504 error during deliver(). 20 screenshots x 17 languages took about 16 mins on my connection.

**Comment by joshdholtz** [comment]
@kabamawutschnik Ah, I always forget about that! I could maybe extend the timeout in the `Spaceship::ConnectAPI` section to something like that too 🤔 Thanks for reminding me about that!

**Comment by joshdholtz** [comment]
🚀  Released `2.150.0.rc2` with a bunch of fixes 👉 https://github.com/fastlane/fastlane/releases/tag/2.150.0.rc2

**Comment by nzaghini-phorest** [comment]
@joshdholtz thanks a lot for the great effort !!! 

and sorry to be ruining the RC2 so quickly :(

We just pointed there and started getting this issue for new apps, and we are not able to go further.
We were pointing at 2.150.0 directly yesterday and was all good .. 


```

bundler: failed to load command: fastlane (/Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bin/fastlane)
 
NameError: [!] undefined local variable or method `territory_ids' for Spaceship::ConnectAPI::App:Class
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/spaceship/lib/spaceship/connect_api/models/app.rb:65:in `create'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/produce/lib/produce/itunes_connect.rb:34:in `create_new_app'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/produce/lib/produce/itunes_connect.rb:15:in `run'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/produce/lib/produce/manager.rb:12:in `start_producing'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/actions/create_app_online.rb:17:in `block in run'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `chdir'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/actions/create_app_online.rb:15:in `run'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/runner.rb:227:in `chdir'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
 
  /Users/distiller/project/vendor_ios/bundle/ruby/2.6.0/bundler/gems/fastlane-423c1768baab/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
 
  Fastfile:152:in `block (2 levels) in parsing_binding'
 
```

**Comment by joshdholtz** [comment]
@nzaghini-phorest Uhhh... I’m so confused how that happened! I’m going to blame it on a bad merge 😇 Fixing and will release a rc3 here soon 😊

**Comment by joshdholtz** [comment]
@nzaghini-phorest Alright, lets try this! Can you update to `2.150.0.rc3` and try that? 😊

**Comment by nzaghini-phorest** [comment]
On it 👍

**Comment by nzaghini-phorest** [comment]
@joshdholtz 🥳  works thank you  🙌 

it takes a good while to do the whole process and submit for review!

I'll keep u posted 👍

**Comment by joshdholtz** [comment]
@nzaghini-phorest I appreciate you taking the time! I’ve gone though that process a lot this week so I know how it goes 😛

**Comment by kabamawutschnik** [comment]
Anyone else seeing 500 errors? They started to appear consistently after multithreaded/async screenshots deletion/uploads were added.

`🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	38: from /Users/awutschnik/.rbenv/versions/2.5.3/bin/fastlane:23:in `<main>'
	37: from /Users/awutschnik/.rbenv/versions/2.5.3/bin/fastlane:23:in `load'
	36: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/bin/fastlane:23:in `<top (required)>'
	35: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	34: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	33: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	32: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	31: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	30: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	29: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	28: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	27: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	26: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	25: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	24: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	23: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	22: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	21: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/lane.rb:33:in `call'
	20: from Fastfile:336:in `block (2 levels) in parsing_binding'
	19: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	18: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	17: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	16: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	15: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	14: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	13: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	12: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
	11: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/runner.rb:37:in `run'
	10: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/runner.rb:122:in `upload_metadata'
	 9: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/upload_screenshots.rb:97:in `upload'
	 8: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/upload_screenshots.rb:97:in `each'
	 7: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/upload_screenshots.rb:121:in `block in upload'
	 6: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/upload_screenshots.rb:121:in `each'
	 5: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/deliver/lib/deliver/upload_screenshots.rb:150:in `block (2 levels) in upload'
	 4: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/spaceship/lib/spaceship/connect_api/models/app_screenshot_set.rb:97:in `upload_screenshot'
	 3: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/spaceship/lib/spaceship/connect_api/models/app_screenshot.rb:79:in `create'
	 2: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:357:in `post_app_screenshot'
	 1: from /Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/spaceship/lib/spaceship/connect_api/client.rb:100:in `post'
/Users/awutschnik/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/fastlane-2.150.0.rc3/spaceship/lib/spaceship/connect_api/client.rb:156:in `handle_response': [!] The request could not be completed because: (Spaceship::InternalServerError)
	Server error got 500`

**Comment by joshdholtz** [comment]
@kabamawutschnik I have not seeng this yet 😔 Can you run `bundle exec fastlane spaceship_logs print_contents:true` and send me the last bit of it that shows the 500?

**Comment by nzaghini-phorest** [comment]
@joshdholtz I can confirm that RC3 can deliver new apps ‘in review’ successfully 👏🎸

**Comment by kabamawutschnik** [comment]
> @kabamawutschnik I have not seeng this yet 😔 Can you run `bundle exec fastlane spaceship_logs print_contents:true` and send me the last bit of it that shows the 500?

of course when I want to reproduce the issue, it works :/
If it occurs again, I will make sure to get the logs for you.

**Comment by kabamawutschnik** [comment]
@joshdholtz Is there a way to set the app preview "still frame" with ConnectAPI? The still image that would be seen before playing the video.

Previously it was possible to set it using `version.upload_trailer!(video, position, lang, device, still_frame)`

**Comment by joshdholtz** [comment]
@kabamawutschnik There is something in the response for it but I’m unsure if its editable. I gotta make some changes in that logic based upon the session I watched today so I will look into that!

**Comment by Kaspik** [comment]
New warning! :))

```
Category 'MZGenre.Education' from iTunesConnect as been deprecated. Please replace with 'EDUCATION'
Category 'MZGenre.Productivity' from iTunesConnect as been deprecated. Please replace with 'PRODUCTIVITY'
```

**Comment by joshdholtz** [comment]
@Kaspik Yup yup!! Docs will be updated with the new category list when we officially release. But the old categories will work for a while since there is a mapping in there 😊

**Comment by joshdholtz** [comment]
@kabamawutschnik So I _am_ able to change the still frame with the API but it looks like it has to wait until the video is done processing 🤷‍♂️ I’m going to try to add that logic (it will be optional) in but it will greatly increase the time it takes for things to run.

**Comment by kabamawutschnik** [comment]
> @kabamawutschnik So I _am_ able to change the still frame with the API but it looks like it has to wait until the video is done processing 🤷‍♂️ I’m going to try to add that logic (it will be optional) in but it will greatly increase the time it takes for things to run.

Thank you @joshdholtz, I appreciate all the work getting put into this!

**Comment by polok** [comment]
Hey guys, 

We are using spaceship to create sandbox user and it seems that API has changed there as well.
The command which we use is as follow:
```
Spaceship::Tunes::SandboxTester.create!(
        email: ''
       password: ''
        country: ''
        first_name: ''
        last_name: '')
```
And the error which we get:
`{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Not Found"], "info"=>nil}, "statusCode"=>"ERROR"}`

**Comment by nzaghini-phorest** [comment]
It is a pleasure to say that RC3 has been able to deliver updates and new apps the whole day today! 

Thanks again @joshdholtz for the amazing support 🙌

**Comment by joshdholtz** [comment]
@polok Ah, thanks for letting me know! A lot of stuff probably no longer works under `Spaceship::Tunes` but I will add that to my list to find a replacement for 😊 

@nzaghini-phorest That’s so great to hear!! Thank you for the update ❤️

**Comment by sonjz** [comment]
gave rc3 a go, got stuck here:
After the screenshots upload, metadata and build was processed, got this `UnexpectedResponse`, not sure if this is in your queue yet.
```
[16:58:37]: Successfully finished processing the build 2020.6.26 - 108 for IOS
[16:58:37]: Selecting build 2020.6.26 (108)...
[16:58:38]: Successfully selected build
[16:58:41]: Successfully updated IDFA delcarations on App Store Connect
[16:58:42]: Successfully updated contents rights declaration on App Store Connect
bundler: failed to load command: fastlane (/Users/administrator/.rbenv/versions/2.7.1/bin/fastlane)

Spaceship::UnexpectedResponse: [!] The request cannot be fulfilled because of the state of another reso
urce. - Submit for review errors found.

Screenshot uploads still in progress. - There are still screenshot uploads in progress.

```

**Comment by joshdholtz** [comment]
@sonjz 😱 I have not seen that error before! It sounds like there was an upload that may have failed but I _think_ I may have had that fixed in this branch if you want to change your `Gemfile` to 👇 

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "2.150.0"
```

Also, do you have `overwrite_screenshots: true`? You might want to do this if there are some in a weird state 🤔

**Comment by turtlemaster19** [comment]
@max-ott Can you consent for CLAs?

**Comment by joshdholtz** [comment]
`2.150.0.rc4` has been released 🚀

**Comment by alexcroox** [comment]
rc release page for rc4 has instructions:

`gem "fastlane", ">= 2.150.rc2"`

should that be `gem "fastlane", ">= 2.150.rc4"`? or `gem "fastlane", ">= 2.150.0.rc4"`?

or does it not matter because of the >=

**Comment by joshdholtz** [comment]
@alexcroox `gem "fastlane", ">= 2.150.rc2"` will update rc4 if you use `bundle update` or `bundle update fastlane`. Also hoping to get the actual release out today 😊

**Comment by mhleiftaylor** [comment]
@joshdholtz You may want to consider adding an additional item to the fixes checklist.

Previously with Fastlane I was able to set the App to Business to Business and add DEPIDS/Organizations to the B2B settings in the Pricing and Availability page.

Screenshot before setup for B2B:
Screen Shot 2020-06-30 at 2 14 11 PM

Screenshot after DEPID/Organization added:
Screen Shot 2020-06-30 at 2 14 22 PM

Old code that worked to do this:
```
lane :configure_b2b do |options|
    require 'spaceship'

    # Login and find the app for this build
    Spaceship::Tunes.login(ENV["MH_APPLE_ID"], ENV['MH_APPLE_PASSWORD'])

    # Update app to B2B app and add Organization
    app = Spaceship::Application.find(ENV['MH_APP_IDENTIFIER'])
    availability = app.availability
    availability.enable_b2b_app!

    # Create object for customer's Organization
    org_map = {'type' => 'ADD',
               'depCustomerId' => ENV['MH_DEP_ID'],
               'organizationId' => ENV['MH_DEP_ID'],
               'name' => ENV['MH_ORG_NAME']}

    new_org = Spaceship::Tunes::B2bOrganization.new('value' =>  org_map)
    availability.update_dep_organizations([new_org])
    app.update_availability!(availability)
end
```

Error message when running that code now:
```
[10:43:00]: ------------------------------
[10:43:00]: --- Step: default_platform ---
[10:43:00]: ------------------------------
[10:43:00]: Driving the lane 'configure_b2b' 🚀
+------------------+---------------+
|           Lane Context           |
+------------------+---------------+
| ENVIRONMENT      | devops        |
| DEFAULT_PLATFORM | ios           |
| PLATFORM_NAME    |               |
| LANE_NAME        | configure_b2b |
+------------------+---------------+
[10:43:04]: ITC.apps.universal.pricing.intervalsCreatingMissingError
```

As far as I know, Deliver has no ability to do this after the appstore connect changes.

**Comment by joshdholtz** [comment]
@mhleiftaylor Added to my list! Thanks for letting me know 😊

**Comment by joshdholtz** [comment]
Going to cut the official release here soon! 😱 I will keep making incremental improvements but I think its time for the rest of the world to have this 💪

**Comment by GandjaFuzz** [comment]
hello, don't work reject_if_possible 
I have build for reject in status wait for review
and when send next build 
I get error

```
[12:29:20]: Removing all previously uploaded screenshots for 'ru' 'APP_IPHONE_40'...
[12:29:20]: Removing all previously uploaded screenshots for 'ru' 'APP_IPHONE_55'...
[12:29:20]: Removing all previously uploaded screenshots for 'ru' 'APP_IPHONE_58'...
[12:29:21]: Waiting for screenshots to be deleted for 'ru'... (might be slow)
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots
[12:29:21]: The request cannot be fulfilled because of the state of another resource. - Can't Delete Screenshot After Submit for reviewappScreenshots

```

options activated 
```
| submit_for_review                                                          | true                                                                                                                        |
| force                                                                      | true                                                                                                                        |
| reject_if_possible                                                         | true                                                                                                                        |

```

**Comment by Thangaraj-M** [comment]
@joshdholtz 
When uploading ipa to test flight with fastlane, it getting failed with error. Below is the log trace. Can you help to resolve the error?

WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] [2020-07-03 19:59:15 IST] <main>  INFO: Transporter's command line arguments are: -m upload -u <username> -p **hidden value** -f /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp -t DAV -k 100000 -itc_provider 4BJ658FFXA
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] Package Summary:
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter]  
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 1 package(s) were not uploaded because they had problems:
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 	/var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp - Error Messages:
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 		     An error occurred while uploading the file 134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa.
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 		An exception has occurred: Broken pipe (Write failed)
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 		  Failed to upload file: /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp/134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 		An error occurred while uploading the package: 1521703273.itmsp.
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] 		An exception has occurred: Connection reset
[0m
WARN [2020-07-03 19:59:15.67]: [33m[iTMSTransporter] [2020-07-03 19:59:15 IST] <main> DBG-X: Returning 1
[0m
INFO [2020-07-03 19:59:15.67]: iTunes Transporter output above ^
ERROR [2020-07-03 19:59:15.67]: [31mAn error occurred while uploading the file 134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp/134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa
An error occurred while uploading the package: 1521703273.itmsp.
An exception has occurred: Connection reset
An error occurred while uploading the file 134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa.
An exception has occurred: Broken pipe (Write failed)
Failed to upload file: /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp/134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa
Return status of iTunes Transporter was 1: An error occurred while uploading the file 134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp/134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa
\nAn error occurred while uploading the package: 1521703273.itmsp.
\nAn exception has occurred: Connection reset
\nAn error occurred while uploading the file 134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa.
\nAn exception has occurred: Broken pipe (Write failed)
\nFailed to upload file: /var/folders/t_/my2lzn291v58yzq5p2bn883m0000gq/T/d20200703-73283-1dzhemi/1521703273.itmsp/134683369b51021d3bd10b6629f891f038ece243bdc0d046542963552f4b3313.ipa
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.[0m
call_with_defaults Exception is... ItunesTransporter error

**Comment by joshdholtz** [comment]
@Thangaraj-M Can you try uploading one or two more times? I've seen somebody else that had some issues with uploading but the issues resolved itself 🤔

**Comment by yangsu** [comment]
I'm also using 2.150.1 and have been running into the same issue as @Thangaraj-M repeatedly since last night using our CI machine. I had to manually get the ipa file and submit to the app store manually.

```
xcrun altool --upload-app --type ios --file App.ipa --username ... --password <appleid-one-time-password>

**Comment by NeelSaysHai** [comment]
> @Thangaraj-M Can you try uploading one or two more times? I've seen somebody else that had some issues with uploading but the issues resolved itself 🤔
@joshdholtz facing same issue when using 2.150.1, will adding **Aspera** delivery method for transporter required?

 ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV,Signiant"

**Comment by joshdholtz** [comment]
@Thangaraj-M @yangsu @NeelSaysHai It looks like I'm having issue if I only use `DAV` 😔 `Signiant` and `Aspera` both seem to work for me  

I do usually set only `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t Aspera`. 

Might be best to set this though 👉  `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t Aspera,Signiant,DAV` ???

**Comment by joshdholtz** [comment]
I might end up changing `deliver`'s default to `Signiant,Aspera,DAV` 🤔

**Comment by Thangaraj-M** [comment]
@joshdholtz 
After change the value of DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS into -t Aspera,Signiant,DAV, now the build uploaded successfully and also it is fast.

When submit the build to Appstore, It failed with below error.
call_with_default_configuration Exception is... An attribute value is invalid. - The attribute 'earliestReleaseDate' only allows hour precision
I am using latest version 2.150.1. And passing auto_release_date param value as integer in milliseconds to the deliver.
Passing value is 1595394000.

**Comment by joshdholtz** [comment]
@Thangaraj-M Glad that worked! The docs for `deliver` say it should be `Date in milliseconds`. I think yours is in seconds. So you need to multiply that by `1000` and it should work.

**Comment by Thangaraj-M** [comment]
@joshdholtz Thank you. I passed in ms only. I edited in above comment. But I am getting error.

**Comment by joshdholtz** [comment]
@Thangaraj-M I'll try that value with one of my builds. Will let you know what happens in a few minutes 😊

**Comment by joshdholtz** [comment]
@Thangaraj-M Passing in `1595395800000` worked for me 🤔 Can you try one more time and send me a screenshot of the "deliver summary" at the top?

Screen Shot 2020-07-03 at 3 38 54 PM

Screen Shot 2020-07-03 at 3 39 44 PM

Screen Shot 2020-07-03 at 3 38 28 PM

**Comment by Thangaraj-M** [comment]
@joshdholtz Below is the screenshot for deliver summary. I passed the submit_for_review value as true. Is it the problem?
deliver

**Comment by joshdholtz** [comment]
@Thangaraj-M Can you run `fastlane run spaceship_logs print_contents:true` and look for a line like the following? 👇 

```
INFO  [15:38:02]: >> PATCH appStoreVersions/3ca760e4-eecf-4b6a-9750-80b863cd1388: {"data":{"type":"appStoreVersions","id":"3ca760e4-eecf-4b6a-9750-80b863cd1388","attributes":{"copyright":"2020 Josh D Holtz","earliestReleaseDate":"2020-07-22T00:00:00-05:00
","releaseType":"SCHEDULED"}}}
```

I gotta go mow the lawn but I will be back in about an hour and a half 😊

**Comment by Thangaraj-M** [comment]
@joshdholtz Below is the output. The release date having minute value as 30. Is that problem?
INFO  [02:47:25]: >> PATCH appStoreVersions/9e1528c3-73c3-4740-a1f0-2313d82241df: {"data":{"type":"appStoreVersions","id":"9e1528c3-73c3-4740-a1f0-2313d82241df","attributes":{"copyright":"Copyright @ 2020 ********","earliestReleaseDate":"2020-07-22T10:30:00+05:30","releaseType":"SCHEDULED"}}} 
DEBUG [02:47:26]: << PATCH appStoreVersions/9e1528c3-73c3-4740-a1f0-2313d82241df: 409 {"errors"=>[{"id"=>"9067d0b2-3407-43e2-96f3-602d51013fe2", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID", "title"=>"An attribute value is invalid.", "detail"=>"The attribute 'earliestReleaseDate' only allows hour precision", "source"=>{"pointer"=>"/data/attributes/earliestReleaseDate"}}]}

**Comment by joshdholtz** [comment]
@Thangaraj-M Woah! I did. It expect that. What time zone are you? It looks like I may need to fix the time conversion logic to PATCH in UTC 🧐 

I'll try to get a fix on for this when I'm done mowing the lawn.

**Comment by Thangaraj-M** [comment]
@joshdholtz I am in IST (GMT+5:30) time zone.

**Comment by joshdholtz** [comment]
TIL there is a time zone that is not on the hour 😇

**Comment by joshdholtz** [comment]
I will have a fix for this in 2.150.2 which I'll release in a few hours 🙂

**Comment by yangsu** [comment]
> @Thangaraj-M @yangsu @NeelSaysHai It looks like I'm having issue if I only use `DAV` 😔 `Signiant` and `Aspera` both seem to work for me
> 
> I do usually set only `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t Aspera`.
> 
> Might be best to set this though 👉 `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS=-t Aspera,Signiant,DAV` ???

@joshdholtz this worked for me as well. Thank you for your incredibly prompt replies and fixes! 🙏

**Comment by Thangaraj-M** [comment]
@joshdholtz 
I have updated the Fastlane version to 2.150.2 and tried again. But I am still getting the same error.
call_with_default_configuration Exception is... An attribute value is invalid. - The attribute 'earliestReleaseDate' only allows hour precision
Below is the spaceship log. Can you check this?
INFO  [14:40:48]: >> PATCH appStoreVersions/9e1528c3-73c3-4740-a1f0-2313d82241df: {"data":{"type":"appStoreVersions","id":"9e1528c3-73c3-4740-a1f0-2313d82241df","attributes":{"copyright":"Copyright @ 2020 *********","earliestReleaseDate":"2020-07-22T04:30:00+00:00","releaseType":"SCHEDULED"}}} 
DEBUG [14:40:49]: << PATCH appStoreVersions/9e1528c3-73c3-4740-a1f0-2313d82241df: 409 {"errors"=>[{"id"=>"48142703-6bce-4207-9243-034ffff47709", "status"=>"409", "code"=>"ENTITY_ERROR.ATTRIBUTE.INVALID", "title"=>"An attribute value is invalid.", "detail"=>"The attribute 'earliestReleaseDate' only allows hour precision", "source"=>{"pointer"=>"/data/attributes/earliestReleaseDate"}}]}

**Comment by joshdholtz** [comment]
@Thangaraj-M Oops! Making another release now 😱 I see what I did. I'll have it ready in about in an hour or so. Sorry about that!

**Comment by Thangaraj-M** [comment]
@joshdholtz Thank you for the quick fix. Now I updated the Fastlane version to 2.150.3 and checked. And it is working fine now. The release date is updated and submitted to review successfully.

**Comment by joshdholtz** [comment]
@Thangaraj-M Glad it worked!!

**Comment by myanime** [comment]
@joshdholtz I noticed another small issue here, when you specify a auto release time using a command line parameter (an int) it is converted to a string somewhere by the parser and this function fails `upload_metadata.rb:327:in `convert_ms_to_iso8601': undefined method `/' for "1596146400000":String`. When you use a Deliver file it works fine.

**Comment by joshdholtz** [comment]
@myanime Ah, thank you! I will convert it to an int 😊

**Comment by NeelSaysHai** [comment]
@joshdholtz thanks for ur inputs, everything worked fine. 
is there any fix to suppress the logs warnings when running the **SNAPSHOT** lane during screenshots. similar to Xcode suppress_xcode_output: true

**Comment by joshdholtz** [comment]
@NeelSaysHai You're welcome! And can you create a new issue with your question / feature request? 😇
