### PR TITLE
Fix app_store_build_number command

### LINKED ISSUE #10923: latest_testflight_build_number return incorrect build number & crash when live_version parameter is true
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The action `latest_testflight_build_number` is returning the incorrect build number in TestFlight as you can see in the output is returning 1 always for the build number and the current build number is 3 actually. I was checking out  the closed issue [#9528](https://github.com/fastlane/fastlane/issues/9528) and tried to include the `live_version` parameter to `true` to try to get it correctly and fastlane is reporting an exception.

####  Lane created to test the issue
```ruby
lane :testflight_build do
    build = latest_testflight_build_number(version: "1.0", live: false)
end
```

##### Complete output when running fastlane, including the stack trace and command used

    fastlane testflight_build

 ```
[12:14:32]: -------------------------------------------------
[12:14:32]: --- Step: Verifying required fastlane version ---
[12:14:32]: -------------------------------------------------
[12:14:32]: Your fastlane version 2.64.1 matches the minimum requirement of 1.111.0  ✅
[12:14:32]: ------------------------------
[12:14:32]: --- Step: default_platform ---
[12:14:32]: ------------------------------
[12:14:32]: Driving the lane 'ios testflight_build' 🚀
[12:14:32]: --------------------------------------------
[12:14:32]: --- Step: latest_testflight_build_number ---
[12:14:32]: --------------------------------------------
[12:14:32]: Login to iTunes Connect (xxxx@yyyy.com)
[12:14:38]: Login successful
[12:14:39]: Fetching the latest build number for version 1.0
[12:14:40]: Latest upload is build number: 1

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | latest_testflight_build_number      | 7           |
+------+-------------------------------------+-------------+

[12:14:40]: fastlane.tools finished successfully 🎉
 ```

#### Output for the same lane with the `live_version: true`
```
[12:26:34]: -------------------------------------------------
[12:26:34]: --- Step: Verifying required fastlane version ---
[12:26:34]: -------------------------------------------------
[12:26:34]: Your fastlane version 2.64.1 matches the minimum requirement of 1.111.0  ✅
[12:26:34]: ------------------------------
[12:26:34]: --- Step: default_platform ---
[12:26:34]: ------------------------------
[12:26:34]: Driving the lane 'ios testflight_build' 🚀
[12:26:34]: --------------------------------------------
[12:26:34]: --- Step: latest_testflight_build_number ---
[12:26:34]: --------------------------------------------
[12:26:34]: Login to iTunes Connect (xxxx@yyyy.com)
[12:26:37]: Login successful
[12:26:37]: Fetching the latest build number for live-version
+------------------+----------------------+
|              Lane Context               |
+------------------+----------------------+
| DEFAULT_PLATFORM | ios                  |
| PLATFORM_NAME    | ios                  |
| LANE_NAME        | ios testflight_build |
+------------------+----------------------+
[12:26:39]: undefined method `current_build_number' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | latest_testflight_build_number      | 4           |
+------+-------------------------------------+-------------+

[12:26:39]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  `app_store_build_number` fails with `undefined method `current_build_number' for nil:NilClass (NoMethodError)`
    https://github.com/fastlane/fastlane/issues/10447 [open] 2 💬
    4 days ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/app_store_build_number.rb:19:in `run': [!] undefined method `current_build_number' for nil:NilClass (NoMethodError)
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:11:in `run'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:379:in `block (2 levels) in parsing_binding'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/lane_manager.rb:54:in `cruise_lane'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:66:in `run!'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/gems/fastlane-2.64.1/bin/fastlane:20:in `<top (required)>'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `load'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/bin/fastlane:23:in `<main>'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/vsiglerlopez/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13                                       |
| Ruby                        | 2.4.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.6 (Apple Git-96)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.2/bin/fastlane         |
| Host                        | Mac OS X 10.13 (17A405)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.64.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.6        |
| rake                      | 12.3.0       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.15.0       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.5.5        |
| ox                        | 2.8.2        |
| danger-junit              | 0.7.4        |
| thor                      | 0.20.0       |
| danger-swiftlint          | 0.11.0       |
| dotenv                    | 2.2.1        |
| excon                     | 0.59.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.5.1        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| xcov                      | 1.3.0        |
| danger-xcov               | 0.3.3        |
</details>

*generated on:* **2017-11-16**
</details>

### PR DESCRIPTION
**Pull request by daveanderson**
Adopts internal changes that leverage the updated TestFlight APIs for getting build information.

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
The `latest_testflight_build_number` command is presently not working because the `app_store_build_number` command is unable to fetch build information. I believe the underlying TestFlight API changes are the root cause of this failure.

After looking at some of the recent commits for TestFlight compatibility changes, and experimenting with the updated commands in `irb`, it was reasonably clear how to get both of these commands working again.

I have tested this in a Fastfile with a project's iTC account via

```
    app_store_build_number(
      live: false,
      version: "3.10"
    )
```
as well as

```
    latest_build_number = latest_testflight_build_number(
      version: get_version_number,
      initial_build_number: 1
    )
```

and 

```
   app_store_build_number(
      live: false
    )
```

For this last situation it was also necessary to update `all_build_train_numbers` to avoid 

```
testflight_version = app.all_build_train_numbers(platform: platform).sort_by { |v| Gem::Version.new(v) }.last
```

throwing the following exception

```
`platform' is a required parameter
```

I believe this issue resolves #10923

### Description

Leverage `all_build_train_numbers` and `all_builds_for_train` to determine the latest build number in TestFlight. Also adjusted `all_build_train_numbers` to leverage the expected `platform` named argument that `build_trains` now expects.

Thanks to @idyll for the help with the insight that `build_trains ` needed `platform` as a named argument for `all_build_train_numbers` to work correctly.

### CODE REVIEW

**Comment by daveanderson** [comment]
I signed it!

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 1]
```diff
@@ -22,7 +24,9 @@ def self.run(params)
           unless version_number
             # Automatically fetch the latest version in testflight
             begin
-              testflight_version = app.build_trains.keys.last
+              # this is working in irb but is giving me an exception when called here
+              # exception is: ``platform' is a required parameter`
```
Comment (taquitos) [inline fastlane/lib/fastlane/actions/app_store_build_number.rb]: Is the exception still happening when called from outside irb, or is this comment about why you changed the code?

Comment (daveanderson) [reply fastlane/lib/fastlane/actions/app_store_build_number.rb]: Comment was stale from before I adjusted `all_build_train_numbers`. Thanks for flagging. Amended.

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 2]
```diff
@@ -13,6 +13,8 @@ def self.run(params)
         Spaceship::Tunes.select_team
         UI.message("Login successful")
 
+        platform = "ios"
```
Comment (ohayon) [inline fastlane/lib/fastlane/actions/app_store_build_number.rb]: Is this safe to hard code this here? Should we provide and option that defaults to 'ios' but could be 'tvOS', 'watchOS', etc?

File: spaceship/lib/spaceship/tunes/application.rb [hunk 3]
```diff
@@ -267,7 +267,7 @@ def build_trains(platform: nil)
       # The numbers of all build trains that were uploaded
       # @return [Array] An array of train version numbers
       def all_build_train_numbers(platform: nil)
-        return self.build_trains.versions
+        return self.build_trains(platform: platform).versions
```
Comment (ohayon) [inline spaceship/lib/spaceship/tunes/application.rb]: 👍

File: fastlane/lib/fastlane/actions/app_store_build_number.rb (hunk 2 above)
Comment (daveanderson) [reply fastlane/lib/fastlane/actions/app_store_build_number.rb]: In attempting to provide the option the cascading impact was more broad that I was confident to address. I may try again.

Comment (taquitos) [reply fastlane/lib/fastlane/actions/app_store_build_number.rb]: Yeah, +1 to @ohayon, adding an option to: `    def self.available_options` with a default of `:ios` would be rad.

Comment (daveanderson) [reply fastlane/lib/fastlane/actions/app_store_build_number.rb]: I've added the platform option to both app_store_build_number and latest_testflight_build_number and tested that the default value is applied for both cases (for iOS)

**Review by ohayon — COMMENTED** [review]
This looks good to me!

**Review by taquitos — APPROVED** [review]
This is great! 🎈 🐐
