### PR TITLE
[action] add labels to create_pull_request

### LINKED ISSUE #13979: Add labels to `create_pull_request`
#### Motivation Behind Feature
I'd like to create PRs through `fastlane`, our `danger` instance fails if no labels are set

#### Feature Description
Add an option in [create_pull_request](https://docs.fastlane.tools/actions/create_pull_request/) to take a comma separated list of labels

No drawbacks afaik assuming the parameter is optional

#### Alternatives or Workarounds
Currently I just create the PR and and the labels manually like an animal

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes  #13979

## Description
PATCH to the issue to add labels

### Example
```sh
fastlane run create_pull_request title:"test" body:"test_body" repo:"joshdholtz/Sentry-Android" head:"bug-hunt" labels:"bug,invalid"
```

screen shot 2018-12-21 at 5 24 10 pm

### CODE REVIEW

File: fastlane/lib/fastlane/actions/create_pull_request.rb [hunk 1]
```diff
@@ -33,6 +33,27 @@ def self.run(params)
...
 
+          if params[:labels]
+            payload = {
+              "labels": params[:labels]
+            }
+            GithubApiAction.run(
+              server_url: params[:api_url],
+              api_token: params[:api_token],
+              http_method: 'PATCH',
+              path: "repos/#{params[:repo]}/issues/#{number}",
```
Comment (rodericj) [inline fastlane/lib/fastlane/actions/create_pull_request.rb]: Would it be `pulls` rather than `issues`?

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/create_pull_request.rb]: Nope nope! A pull request is technically also an issue 🙃
