### PR TITLE
respect file extension based on users uploaded one.

### LINKED ISSUE #7857: Invalid png app_icon.png
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Just started with fastlane for an existing app. My build was failing with error 65. The error log indicated that my app_icon.png was not a valid PNG. That is true because my app icon is a jpg. I updated the local file to be a PNG to clear the error.

I set up the initial metadata folders using 'fastlane deliver' at it appears to assume that the app icon will be a png.

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.8.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "weVew") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "weVew") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Just build the app"
  lane :build do
    increment_build_number
    gym(scheme:"weVew", workspace:"weVew.xcworkspace")
  end
  
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app
apple_id "REDACTED" # Your Apple email address

team_id "REDACTED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-01-13**
</details>

### PR DESCRIPTION
**Pull request by hjanuschka**
fixes: #7857

i verified the globbing and end_with via this little sample.:
having a `app_icon.jpg` and `app_icon.png` in a folder `demo/`

```ruby
u = "http://Wwwwwww.........jpg"
puts u.end_with? "jpg"
files = Dir["demo/app_icon.{png,jpg}"]
puts files.inspect
exit

```

### CODE REVIEW

File: deliver/lib/deliver/runner.rb [hunk 1]
```diff
@@ -72,10 +72,10 @@ def upload_metadata
     def prepare_app_icons(options = {})
       return unless options[:metadata_path]
 
-      default_app_icon_path = File.join(options[:metadata_path], "app_icon.png")
+      default_app_icon_path = Dir["#{options[:metadata_path]}/app_icon.{png,jpg}"].first
```
Comment (KrauseFx) [inline deliver/lib/deliver/runner.rb]: Without using `File.join` there might be duplicate `/` between dir/file names. Any reason why we don't use File.join now?

Comment (hjanuschka) [inline deliver/lib/deliver/runner.rb]: the thing is if we downloaded it and respected the original ending, we may have a `.jpg` in here.

you are right only `.first` will be used, what do you think is a good solution for that edge case (user downloaded .jpg, and put a .png in his metadata folder)

**Review by lacostej — COMMENTED** [review]
Wrote this a few days ago.Forgot to submit

File: deliver/lib/deliver/runner.rb (hunk 1 above)
Comment (lacostej) [inline deliver/lib/deliver/runner.rb]: @hjanuschka why would the user download over his existing metadata? This is a weird scenario and in my head, unsupported. This use case is the same as let's say download over an older version of the app metadata. It can lead to weird cases.

Comment (hjanuschka) [inline deliver/lib/deliver/runner.rb]: @lacostej yeah i think almost nobody will download over existing. - so first should be fine.
but i did a download a few times, on apps where customers changed it via itc and i had to sync git repo (don't ask)

Comment (hjanuschka) [inline deliver/lib/deliver/runner.rb]: awesome, didn't know that - changed!

File: deliver/lib/deliver/setup.rb [hunk 2]
```diff
@@ -70,12 +70,16 @@ def generate_metadata_files(v, path)
 
       # get App icon + watch icon
       if v.large_app_icon.asset_token
-        app_icon_path = File.join(path, "app_icon.png")
+        app_icon_extension = "jpg" if v.large_app_icon.url.end_with? "jpg"
```
Comment (hjanuschka) [inline deliver/lib/deliver/setup.rb]: according to apple documentation only jpg and png are supported so this should never happen, any ideas on further improving it?

**Comment by hjanuschka** [comment]
@lacostej feedback addressed - thx for the help!

File: deliver/lib/deliver/runner.rb (hunk 1 above)
Comment (KrauseFx) [inline deliver/lib/deliver/runner.rb]: `fastlane deliver download_metadata` and `fastlane deliver download_screenshots` is used by people, when the marketing team updates the metadata, and you want your repo to reflext those changes.

File: deliver/lib/deliver/setup.rb (hunk 2 above)
Comment (DanToml) [inline deliver/lib/deliver/setup.rb]: `File.extname(v.large_aapp_icon.url)`

**Review by endocrimes — CHANGES_REQUESTED** [review]
LGTM with an update to extension parsing.

**Comment by hjanuschka** [comment]
@DanToml awww - ruby is so awesome, thx!

**Review by endocrimes — APPROVED** [review]

File: deliver/lib/deliver/runner.rb [hunk 3]
```diff
@@ -72,10 +72,10 @@ def upload_metadata
     def prepare_app_icons(options = {})
       return unless options[:metadata_path]
 
-      default_app_icon_path = File.join(options[:metadata_path], "app_icon.png")
+      default_app_icon_path = Dir[File.join(options[:metadata_path], "app_icon.{png,jpg}")].first
```
Comment (reidab) [inline deliver/lib/deliver/runner.rb]: This line can return `nil`, which `File.exist?` on the following line will choke on with `no implicit conversion of nil into String (TypeError)`. PR incoming…

**Comment by KrauseFx** [comment]
Thanks for the PR @reidab 👍
