### PR TITLE
[precheck] support IDN: normalize URI before creating connection

### LINKED ISSUE #13119: [precheck] `precheck` can't handle Umlaut URLs / IDN
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
`precheck` fails with "Failed: No broken urls-> unreachable URLs in app metadata" when using Umlaut domains as support, marketing or privacy URL.

##### Complete output when running fastlane, including the stack trace and command used
```
λ fastlane precheck --verbose
[✔] 🚀
Successfully loaded Appfile at path 'C:/Projects/Stromzaehler/stromzaehler/fastlane/Appfile'
- app_identifier: 'de.janpiotrowski.zaehlerstand'
- apple_id: 'pio...@gmail.com'
- team_id: '4Z...X3'
- json_key_file: 'C...son'
- package_name: 'de.janpiotrowski.zaehlerstand'
-------

+--------------------------+-------------------------------+
|               Summary for precheck 2.101.1               |
+--------------------------+-------------------------------+
| app_identifier           | de.janpiotrowski.zaehlerstand |
| username                 | pio...@gmail.com          |
| default_rule_level       | error                         |
| include_in_app_purchases | true                          |
+--------------------------+-------------------------------+

INFO [2018-08-15 19:35:12.91]: Starting login with user 'pio...@gmail.com'
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
See more information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for pio...@gmail.com): ********
Loading session from 'C:/Users/Jan/.fastlane/spaceship/pio...@gmail.com/cookie'
Looking for App Store Connect Team with ID 42...53
INFO [2018-08-15 19:38:35.52]: Successfully logged in
INFO [2018-08-15 19:38:35.52]: Checking app for precheck rule violations
INFO [2018-08-15 19:38:41.22]: Reading in-app purchases. If you have a lot, this might take a while
INFO [2018-08-15 19:38:41.22]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
INFO [2018-08-15 19:38:41.81]: Done reading in-app purchases
INFO [2018-08-15 19:38:42.44]: ✅  Passed: No negative  sentiment
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No placeholder text
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No mentioning  competitors
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No future functionality promises
INFO [2018-08-15 19:38:42.45]: ✅  Passed: No words indicating test content
INFO [2018-08-15 19:38:42.47]: ✅  Passed: No curse words
INFO [2018-08-15 19:38:42.47]: ✅  Passed: No words indicating your IAP is free
DEBUG [2018-08-15 19:38:42.47]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
INFO [2018-08-15 19:38:42.47]: ✅  Passed: Incorrect, or missing copyright date
DEBUG [2018-08-15 19:38:42.53]: URL https://zählerstand.app not reachable 😵
DEBUG [2018-08-15 19:38:42.56]: URL https://zählerstand.app not reachable 😵
DEBUG [2018-08-15 19:38:42.59]: URL https://zählerstand.app not reachable 😵
ERROR [2018-08-15 19:38:42.59]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+------------------------+--------------------------------------+
|                      Potential problems                       |
+------------------------+--------------------------------------+
| Field                  | Failure reason                       |
+------------------------+--------------------------------------+
| support URL: (de-DE)   | unreachable: https://zählerstand.app |
| marketing URL: (de-DE) | unreachable: https://zählerstand.app |
| privacy URL: (de-DE)   | unreachable: https://zählerstand.app |
+------------------------+--------------------------------------+
```

### PR DESCRIPTION
**Pull request by janpio**
* Use `.normalize` on the adressable `uri` before opening a connection so IDN (e.g. Umlaut domains) are converted to a format that can be understood by the following coe
*  Also output the exception in the verbose output in case of an error for easier debugging

closes #13119

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Pull Request is Work in Progress</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

File: precheck/spec/rules/unreachable_urls_rule_spec.rb [hunk 1]
```diff
@@ -27,7 +28,7 @@ def setup_url_rule_mock(url: "http://fastlane.tools", return_status: 200)
       end
 
       it "passes for valid non encoded URL" do
-        setup_url_rule_mock(url: "http://fastlane.tools/%E3%83%86%E3%82%B9%E3%83%88")
+        setup_url_rule_mock(url: "http://fastlane.tools/%25E3%2583%2586%25E3%2582%25B9%25E3%2583%2588")
```
Comment (janpio) [inline precheck/spec/rules/unreachable_urls_rule_spec.rb]: I am not 100% sure about this change, but as the URL is "normalized" by adressable now, the actual URL being called seems to have changed a bit. 

Before it was `http://fastlane.tools/テスト` which got changed to `http://fastlane.tools/%E3%83%86%E3%82%B9%E3%83%88` by Faraday, not it already starts out as `http://fastlane.tools/%E3%83%86%E3%82%B9%E3%83%88` which ends up being `http://fastlane.tools/%25E3%2583%2586%25E3%2582%25B9%25E3%2583%2588` after Faraday.

Does this make sense to you?

File: precheck/lib/precheck/rules/unreachable_urls_rule.rb [hunk 2]
```diff
@@ -29,13 +29,13 @@ def rule_block
         begin
           uri = Addressable::URI.parse(url)
           uri.fragment = nil
-          request = Faraday.new(URI.encode(uri.to_s)) do |connection|
+          request = Faraday.new(URI.encode(uri.normalize.to_s)) do |connection|
```
Comment (joshdholtz) [inline precheck/lib/precheck/rules/unreachable_urls_rule.rb]: You need to get rid of the `URI.encode` here. This is essentially running a URI encode twice (since that is what is done inside of `normalize` plus some more). This is what is causing that change in that test below 🙃

File: precheck/spec/rules/unreachable_urls_rule_spec.rb (hunk 1 above)
Comment (joshdholtz) [reply precheck/spec/rules/unreachable_urls_rule_spec.rb]: This url is actually being uri encoded twice (see my comment above for fix)

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Small fix here! 🔨

**Comment by joshdholtz** [comment]
@janpio Appveryor failed here too 😱

**Review by joshdholtz — APPROVED** [review]
This seems good now 👍
