### PR TITLE
Fix issue that uploading aab with mapping file

### LINKED ISSUE #12900: Google Api Error: Invalid Request in upload_to_play_store - Fastlane 2.99.1
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I changed `upload_to_play_store` to use aab instead of apk. Now it fails (output below).

##### Complete output when running fastlane, including the stack trace and command used

```
+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+

|                                                                 Summary for supply 2.99.1                                                                  |

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+

| package_name            | com.myapp                                                                                                                        |

| track                   | internal                                                                                                                         |

| json_key                | **** |

| aab                     | app/build/outputs/bundle/prodRelease/app.aab                                                                                     |

| mapping                 | app/build/outputs/mapping/prod/release/mapping.txt                                                                               |

| skip_upload_metadata    | true                                                                                                                             |

| skip_upload_images      | true                                                                                                                             |

| skip_upload_screenshots | true                                                                                                                             |

| metadata_path           | ./fastlane/metadata/android                                                                                                      |

| skip_upload_apk         | false                                                                                                                            |

| skip_upload_aab         | false                                                                                                                            |

| validate_only           | false                                                                                                                            |

| check_superseded_tracks | false                                                                                                                            |

+-------------------------+----------------------------------------------------------------------------------------------------------------------------------+



DEBUG [2018-07-13 01:43:59.21]: Fetching a new access token from Google...

INFO [2018-07-13 01:44:01.54]: Preparing to upload for language 'en-US'...

WARN [2018-07-13 01:44:01.67]: Lane Context:

INFO [2018-07-13 01:44:01.67]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android upload_to_play_store_for_release_type", :COMMITS_SINCE_TAG_RESULT=>8}

ERROR [2018-07-13 01:44:01.67]: Google Api Error: Invalid request

INFO [2018-07-13 01:44:01.67]: Successfully generated documentation at path '/Users/developer/.jenkins/workspace/myapp@2/fastlane/README.md'



+------+----------------------------------------+-------------+

|                      fastlane summary                       |

+------+----------------------------------------+-------------+

| Step | Action                                 | Time (in s) |

+------+----------------------------------------+-------------+

| 1    | Verifying fastlane version             | 0           |

| 2    | default_platform                       | 0           |

| 3    | setup_environment_variables            | 0           |

| 4    | Switch to android most_recent_tag lane | 0           |

| 5    | git_tags                               | 2           |

| 6    | commits_since_tag                      | 0           |

| 7    | touched_files_since_tag                | 0           |

| 💥   | upload_to_play_store                   | 2           |

+------+----------------------------------------+-------------+



DEBUG [2018-07-13 01:44:01.68]: All plugins are up to date

ERROR [2018-07-13 01:44:01.68]: fastlane finished with errors

DEBUG [2018-07-13 01:44:01.68]: All plugins are up to date

bundler: failed to load command: fastlane (/Users/developer/.rbenv/versions/2.3.7/bin/fastlane)

FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Invalid request

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:390:in `rescue in call_google_api'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:387:in `call_google_api'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/client.rb:228:in `upload_mapping'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:136:in `block in upload_binaries'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:134:in `each'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:134:in `upload_binaries'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/supply/lib/supply/uploader.rb:26:in `perform_upload'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'

  lanes/releases.rb:43:in `block in parsing_binding'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane.rb:33:in `call'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/runner.rb:45:in `execute'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:74:in `run!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'

  /Users/developer/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/fastlane-2.99.1/bin/fastlane:20:in `<top (required)>'

  /Users/developer/.rbenv/versions/2.3.7/bin/fastlane:22:in `load'

  /Users/developer/.rbenv/versions/2.3.7/bin/fastlane:22:in `<top (required)>'

script returned exit code 1
```

### PR DESCRIPTION
**Pull request by chibatching**
Fixes #12900

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

When I uploaded app bundle file with mapping.txt, I got error `Google Api Error: Invalid request`.

```
FastlaneCore::Interface::FastlaneError: [!] Google Api Error: Invalid request
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/client.rb:390:in `rescue in call_google_api'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/client.rb:387:in `call_google_api'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/client.rb:228:in `upload_mapping'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/uploader.rb:136:in `block in upload_binaries'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/uploader.rb:134:in `each'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/uploader.rb:134:in `upload_binaries'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/supply/lib/supply/uploader.rb:26:in `perform_upload'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/actions/upload_to_play_store.rb:21:in `run'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:257:in `block (2 levels) in execute_action'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:236:in `block in execute_action'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:231:in `chdir'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:231:in `execute_action'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/fast_file.rb:149:in `method_missing'
  Fastfile:64:in `block (2 levels) in parsing_binding'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/lane_manager.rb:59:in `cruise_lane'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:107:in `block (2 levels) in run'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:332:in `run'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/fastlane-2.98.0/bin/fastlane:20:in `<top (required)>'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bin/fastlane:23:in `load'
  /Users/takao-chiba/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bin/fastlane:23:in `<top (required)>'
```

This is caused that supply upload mapping.txt before app bundle file.

I tested this PR with lane to supply app bundle and mapping file and got successfully upload.

```
    supply(
        aab: ENV["ARTIFACTS"] + '/bundle/productRelease/app.aab',
        track: "internal",
        mapping: ENV["ARTIFACTS"] + '/mapping/product/release/mapping.txt',
        skip_upload_metadata: true,
        validate_only: true
    )
```

### Description

At `upload_binaries`, upload apks and mapping.txt after that `upload_bundles` would upload aab file.
But when we upload aab and mapping file, `apk_version_codes` is not supplied yet.
So, we have to upload mapping file after both apks uploadind and aab uploading.

I split `upload_binaries` to apk upload and mapping upload. And call mapping upload process after apk and aab uploading.

### CODE REVIEW

File: supply/lib/supply/uploader.rb [hunk 1]
```diff
@@ -147,11 +153,7 @@ def upload_bundles
       return unless aab_path
 
       UI.message("Preparing aab at path '#{aab_path}' for upload...")
-      apk_version_codes = [client.upload_bundle(aab_path)]
-
-      # Only update tracks if we have version codes
-      # Updating a track with empty version codes can completely clear out a track
-      update_track(apk_version_codes) unless apk_version_codes.empty?
+      return [client.upload_bundle(aab_path)]
```
Comment (tmtrademarked) [inline supply/lib/supply/uploader.rb]: Isn't updating tracks still necessary here? (Random drive by comment, but I'm curious as to why this function differs from the logic in the newly split upload_apks)

Comment (joshdholtz) [reply supply/lib/supply/uploader.rb]: Same thoughts/concern there ^ 

@tmtrademarked Thanks for drive by commenting 😊

File: supply/lib/supply/uploader.rb [hunk 2]
```diff
@@ -130,6 +132,10 @@ def upload_binaries
         apk_version_codes.push(upload_binary_data(apk_path))
       end
 
+      return apk_version_codes
+    end
+
+    def upload_binaries(apk_version_codes)
```
Comment (joshdholtz) [inline supply/lib/supply/uploader.rb]: Can we rename this to `upload_mapping`? "mapping" seems more appropriate then "binary" here 🙃

**Review by joshdholtz — CHANGES_REQUESTED** [review]

File: supply/lib/supply/uploader.rb (hunk 1 above)
Comment (chibatching) [reply supply/lib/supply/uploader.rb]: The original logic sequence is below.

### If uploading binary is apks
1. Upload apks
2. Upload mapping files
3. Update track
4. Upload bundle (not executed)
5. Update track (not executed because of empty apk version codes)

### If uploading binary is bundle
1. Upload apks (not executed)
2. Upload mapping (error caused by empty apk version codes)
3. Update track (not executed because of empty apk version codes)
4. Upload bundle
5. Update track

Update track should be executed after upload apks or bundle and only once.
So, I split upload mapping and updating track function to execute after uploading both apk and bundle.

Comment (chibatching) [reply supply/lib/supply/uploader.rb]: After fixing,

1. Upload apks if upload type is apks
2. Upload bundle if upload type is bundle
3. Upload mapping
4. Update track

I think that uploading logic order is not changed 😃

File: supply/lib/supply/uploader.rb (hunk 2 above)
Comment (chibatching) [reply supply/lib/supply/uploader.rb]: I fixed at 49e2b1d 😃

**Review by joshdholtz — CHANGES_REQUESTED** [review]

File: supply/lib/supply/uploader.rb (hunk 1 above)
Comment (chibatching) [reply supply/lib/supply/uploader.rb]: Thank you comments and I agree with you 😄
 I fixed at b7e91f0!

Comment (chibatching) [reply supply/lib/supply/uploader.rb]: @joshdholtz Could you review this?

**Review by joshdholtz — APPROVED** [review]
This looks great! Thanks for making those changes 😊
