### PR TITLE
[fastlane_core] install both old and new WWDR certificates

### LINKED ISSUE #17328: [WWDC Enterprise Certificate / CircleCI] SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Hello,

CircleCI fails to sign in enterprise builds with a new WWDC certificate.
It does work fine locally but I can't manage to access it with thru the CI.

I tried to reset MATCH_PASSWORD env with `fastlane match change_password` after a `fastlane match nuke enterprise` but it didn't work. Moreover, when I set the MATCH_PASSWORD with the old password, it was ok (but build still fails).

Provisionning profiles mapping are ok and valid.

Thanks

<details>
  <pre>
DEBUG [2020-09-28 12:59:45.78]: Your certificate '4YMVAMYWZU.cer' is valid
INFO [2020-09-28 12:59:45.78]: Installing certificate...
INFO [2020-09-28 12:59:45.78]: $ security list-keychains -d user
INFO [2020-09-28 12:59:45.79]: ▸     "/Users/distiller/Library/Keychains/********_tmp_keychain-db"
INFO [2020-09-28 12:59:45.79]: $ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/distiller/Library/Keychains/********_tmp_keychain-db
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
INFO [2020-09-28 12:59:45.83]: $ security list-keychains -d user
INFO [2020-09-28 12:59:45.84]: ▸     "/Users/distiller/Library/Keychains/********_tmp_keychain-db"
DEBUG [2020-09-28 12:59:45.84]: Installing WWDR Cert: curl -f -o /var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/AppleWWDRCA20200928-4373-1emedop https://developer.apple.com/certificationauthority/AppleWWDRCA.cer && security import /var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/AppleWWDRCA20200928-4373-1emedop -k /Users/distiller/Library/Keychains/********_tmp_keychain-db
INFO [2020-09-28 12:59:46.01]: ▸ 1 certificate imported.
INFO [2020-09-28 12:59:46.01]: ▸ 100  1062  100  1062    0     0   9654      0 --:--:-- --:--:-- --:--:--  9654
ERROR [2020-09-28 12:59:46.22]: There are no local code signing identities found.
You can run `security find-identity -v -p codesigning ********_tmp_keychain` to get this output.
This Stack Overflow thread has more information: https://stackoverflow.com/q/35390072/774.
(Check in Keychain Access for an expired WWDR certificate: https://stackoverflow.com/a/35409835/774 has more info.)
INFO [2020-09-28 12:59:46.28]: $ security import /var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/d20200928-4373-xvekab/certs/enterprise/4YMVAMYWZU.cer -k '/Users/distiller/Library/Keychains/********_tmp_keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
INFO [2020-09-28 12:59:46.34]: ▸ 1 certificate imported.
INFO [2020-09-28 12:59:46.36]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
INFO [2020-09-28 12:59:46.36]: $ security set-key-partition-list -S apple-tool:,apple: -s -k '' /Users/distiller/Library/Keychains/********_tmp_keychain-db 1> /dev/null
ERROR [2020-09-28 12:59:46.40]: security: SecItemCopyMatching: The specified item could not be found in the keychain.
INFO [2020-09-28 12:59:46.40]: $ security import /var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/d20200928-4373-xvekab/certs/enterprise/4YMVAMYWZU.p12 -k '/Users/distiller/Library/Keychains/********_tmp_keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild
INFO [2020-09-28 12:59:46.48]: ▸ 1 key imported.
INFO [2020-09-28 12:59:46.49]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
INFO [2020-09-28 12:59:46.49]: $ security set-key-partition-list -S apple-tool:,apple: -s -k '' /Users/distiller/Library/Keychains/********_tmp_keychain-db 1> /dev/null
 </pre>

<pre> 
INFO [2020-09-28 13:12:02.60]: ▸ error: Task failed with exit 1 signal 0 {
INFO [2020-09-28 13:12:02.60]: ▸ 	/usr/bin/codesign '--force' '--sign' '8B710041363A2D0BF3520153350561A825195ADA' '--verbose' '/Users/distiller/Library/Developer/Xcode/DerivedData/olyAppNative-bcfzzjvdmuecvrhedyvcnujkvkzx/Build/Intermediates.noindex/ArchiveIntermediates/runningDev/InstallationBuildProductsLocation/Applications/Running H. Dev.app/Frameworks/libswiftCore.dylib'
INFO [2020-09-28 13:12:02.60]: ▸ }
</pre>
</details>

### Environment

<details>
  <pre>### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.160.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3     | 1.8.0   | ✅ Up-To-Date  |
| fastlane-plugin-versioning | 0.4.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version       |
| -------------------------- | ------------- |
| did_you_mean               | 1.1.0         |
| executable-hooks           | 1.6.0         |
| bundler-unload             | 1.0.2         |
| rubygems-bundler           | 1.4.5         |
| bundler                    | 2.1.4         |
| rake                       | 13.0.1        |
| CFPropertyList             | 3.0.2         |
| concurrent-ruby            | 1.1.7         |
| i18n                       | 1.8.5         |
| minitest                   | 5.14.2        |
| thread_safe                | 0.3.6         |
| tzinfo                     | 1.2.7         |
| activesupport              | 5.2.4.4       |
| public_suffix              | 4.0.6         |
| addressable                | 2.7.0         |
| httpclient                 | 2.8.3         |
| json                       | 2.3.1         |
| algoliasearch              | 1.27.4        |
| rubyzip                    | 2.3.0         |
| apktools                   | 0.7.4         |
| atomos                     | 0.1.3         |
| aws-eventstream            | 1.1.0         |
| aws-partitions             | 1.376.0       |
| aws-sigv4                  | 1.2.2         |
| jmespath                   | 1.4.0         |
| aws-sdk-core               | 3.108.0       |
| aws-sdk-kms                | 1.38.0        |
| aws-sdk-s3                 | 1.81.1        |
| babosa                     | 1.0.3         |
| claide                     | 1.0.3         |
| fuzzy_match                | 2.0.4         |
| nap                        | 1.1.0         |
| netrc                      | 0.11.0        |
| ffi                        | 1.13.1        |
| ethon                      | 0.12.0        |
| typhoeus                   | 1.4.0         |
| cocoapods-core             | 1.10.0.beta.2 |
| cocoapods-deintegrate      | 1.0.4         |
| cocoapods-downloader       | 1.4.0         |
| cocoapods-plugins          | 1.0.0         |
| cocoapods-search           | 1.0.0         |
| cocoapods-trunk            | 1.5.0         |
| cocoapods-try              | 1.2.0         |
| colored2                   | 3.1.2         |
| escape                     | 0.0.4         |
| fourflusher                | 2.3.1         |
| gh_inspector               | 1.1.3         |
| molinillo                  | 0.6.6         |
| ruby-macho                 | 1.4.0         |
| nanaimo                    | 0.3.0         |
| xcodeproj                  | 1.18.0        |
| cocoapods                  | 1.10.0.beta.2 |
| colored                    | 1.2           |
| highline                   | 1.7.10        |
| commander-fastlane         | 4.4.6         |
| declarative                | 0.0.20        |
| declarative-option         | 0.1.0         |
| digest-crc                 | 0.6.1         |
| unf_ext                    | 0.0.7.7       |
| unf                        | 0.1.4         |
| domain_name                | 0.5.20190701  |
| dotenv                     | 2.7.6         |
| emoji_regex                | 3.0.0         |
| excon                      | 0.76.0        |
| multipart-post             | 2.0.0         |
| faraday                    | 1.0.1         |
| http-cookie                | 1.0.3         |
| faraday-cookie_jar         | 0.0.7         |
| faraday_middleware         | 1.0.0         |
| fastimage                  | 2.2.0         |
| jwt                        | 2.2.2         |
| memoist                    | 0.16.2        |
| multi_json                 | 1.15.0        |
| os                         | 1.1.1         |
| signet                     | 0.14.0        |
| googleauth                 | 0.13.1        |
| mini_mime                  | 1.0.2         |
| uber                       | 0.1.0         |
| representable              | 3.0.4         |
| retriable                  | 3.1.2         |
| google-api-client          | 0.38.0        |
| google-cloud-env           | 1.3.3         |
| google-cloud-errors        | 1.0.1         |
| google-cloud-core          | 1.5.0         |
| google-cloud-storage       | 1.29.0        |
| mini_magick                | 4.10.1        |
| plist                      | 3.5.0         |
| security                   | 0.1.3         |
| naturally                  | 2.2.0         |
| simctl                     | 1.6.8         |
| slack-notifier             | 2.3.2         |
| terminal-notifier          | 2.0.0         |
| unicode-display_width      | 1.7.0         |
| terminal-table             | 1.8.0         |
| tty-screen                 | 0.8.1         |
| tty-cursor                 | 0.7.1         |
| tty-spinner                | 0.9.3         |
| word_wrap                  | 1.0.0         |
| rouge                      | 2.0.7         |
| xcpretty                   | 0.3.0         |
| xcpretty-travis-formatter  | 1.0.0         |
| mime-types-data            | 3.2020.0512   |
| mime-types                 | 3.3.1         |
| fastlane-plugin-aws_s3     | 1.8.0         |
| fastlane-plugin-versioning | 0.4.4</pre>
</details>

### PR DESCRIPTION
**Pull request by igor-makarov**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Closes #17328

### Description
Modified `CertChecker` to install both the older WWDR certificate and the new one.

### Testing Steps
* updated unit tests
* tested the patch against my private project, which has recently had a new enterprise certificate generated, causing build failures in CI due to the missing WWDR certificate.

### CODE REVIEW

**Comment by igor-makarov** [comment]
@rogerluan I've done all the necessary steps for the fix, I think.

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 1]
```diff
@@ -81,16 +81,21 @@ def self.list_available_developer_id_installer(in_keychain: nil)
       `#{commands.join(' ')}`
     end
 
-    def self.wwdr_certificate_installed?
+    def self.wwdr_certificates_installed?
       certificate_name = "Apple Worldwide Developer Relations Certification Authority"
       keychain = wwdr_keychain
-      response = Helper.backticks("security find-certificate -c '#{certificate_name}' #{keychain.shellescape}", print: FastlaneCore::Globals.verbose?)
-      return response.include?("attributes:")
+      response = Helper.backticks("security find-certificate -a -c '#{certificate_name}' #{keychain.shellescape}", print: FastlaneCore::Globals.verbose?)
```
Comment (rogerluan) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:87]: Commenting to leave some documentation behind 😁 

```
 find-certificate [-h] [-a] [-c name] [-e emailAddress] [-m] [-p] [-Z] [keychain...]
            Find a certificate item.  If no keychain arguments are provided, the default search list is used.

            Options:
            -a              Find all matching certificates, not just the first one
            -c name         Match on name when searching (optional)
            -e emailAddress
                            Match on emailAddress when searching (optional)
            -m              Show the email addresses in the certificate
            -p              Output certificate in pem format.  Default is to dump the attributes and keychain the cert is
                            in.
            -Z              Print SHA-256 (and SHA-1) hash of the certificate

            Examples

            security> find-certificate -a -p > allcerts.pem
                     Exports all certificates from all keychains into a pem file called allcerts.pem.

            security> find-certificate -a -e me@foo.com -p > certs.pem
                     Exports all certificates from all keychains with the email address me@foo.com into a pem file called
                     certs.pem.

            security> find-certificate -a -c MyName -Z login.keychain | grep ^SHA-256
                     Print the SHA-256 hash of every certificate in 'login.keychain' whose common name includes 'MyName'
```

File: fastlane_core/lib/fastlane_core/cert_checker.rb [hunk 2]
```diff
@@ -81,16 +81,21 @@ def self.list_available_developer_id_installer(in_keychain: nil)
...
+      certs = response.split("keychain: \"#{keychain}\"").drop(1)
+      certs.count == 2
     end
 
-    def self.install_wwdr_certificate
-      url = 'https://developer.apple.com/certificationauthority/AppleWWDRCA.cer'
-      file = Tempfile.new('AppleWWDRCA')
+    def self.install_wwdr_certificates
+      install_wwdr_certificate('https://developer.apple.com/certificationauthority/AppleWWDRCA.cer')
```
Comment (rogerluan) [inline fastlane_core/lib/fastlane_core/cert_checker.rb:93]: Do we actually need this one as well? Why?

**Review by rogerluan — COMMENTED** [review]
Just a quick question!
Thanks for this PR! 🙌

File: fastlane_core/lib/fastlane_core/cert_checker.rb (hunk 2 above)
Comment (igor-makarov) [reply fastlane_core/lib/fastlane_core/cert_checker.rb:93]: It doesn't expire until 3 more years, and there are many, many certificates issued by it.

Comment (rogerluan) [reply fastlane_core/lib/fastlane_core/cert_checker.rb:93]: Oh I thought it was expiring by Feb 2021 for some reason 🤔 

All good 👍 thanks for explaining

**Review by rogerluan — APPROVED** [review]
LGTM! 🚀

**Review by joshdholtz — APPROVED** [review]
This looks so good!! Thank you for making this fix ❤️  Really appreciate it!
