### PR TITLE
Use GEM_HOME in update_fastlane

### LINKED ISSUE #10429: update_fastlane doesn't use the right gem dir
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The `update_fastlane` action returns me the following error:

> [10:42:50]: It seems that your Gem directory is not writable by your current User.
> [10:42:50]: fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
> [10:42:50]: If you still want to use this action, please read the documentation on a guide how to set this up:
> [10:42:50]: https://docs.fastlane.tools/actions/#update_fastlane

I've installed fastlane with gem using the `--user-install` option and I've seen that your script uses the `Gem.dir` property as destination. However this is what I get from `irb`:

```
irb(main):001:0> Gem.dir
=> "/Library/Ruby/Gems/2.3.0"
irb(main):002:0> Gem.user_dir
=> "/Users/emilio/.gem/ruby/2.3.0"
```

Shouldn't you check the `user_dir` property instead?

Thanks in advance!

P.S. I'm using High Sierra

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13                                                          |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.13.5 (Apple Git-94)                              |
| Installation Source         | ~/.gem/ruby/2.3.0/bin/fastlane                                 |
| Host                        | Mac OS X 10.13 (17A365)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-09-27**
</details>

### PR DESCRIPTION
**Pull request by emiliopavia**
Until now the action used Gem.home to check for sudo requirement
when updating fastlane, but it fails if fastlane is installed with
the --user-install option.

With this commit the action first check for the GEM_HOME env var
and fallback to Gem.home if missing.

### Checklist
- [X] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [X] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [X] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I've updated the documentation if necessary.

### Motivation and Context
Fixes #10429.

### CODE REVIEW

File: fastlane/lib/fastlane/actions/update_fastlane.rb [hunk 1]
```diff
@@ -24,7 +24,11 @@ def self.run(options)
         updater.options[:prerelease] = true if options[:nightly]
         cleaner = Gem::CommandManager.instance[:cleanup]
 
-        sudo_needed = !File.writable?(Gem.dir)
+        gem_dir = ENV['GEM_HOME']
+        unless gem_dir
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/update_fastlane.rb]: This could be reduced to 
```ruby
gem_dir = ENV['GEM_HOME'] || Gem.dir
```

**Review by KrauseFx — APPROVED** [review]
Awesome, thanks for updating 👍
