### PR TITLE
[precheck] allow precheck to be run on live app versions as well as edit ones

### LINKED ISSUE #17176: Precheck fails (undefined method `copyright' for nil:NilClass (NoMethodError))
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
precheck fails in v2.158.0

##### Command executed
precheck(include_in_app_purchases: false)

##### Complete output when running fastlane, including the stack trace and command used

<details>
 <pre>

🔗  You can ⌘ + double-click on links to open them directly in your browser.

/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check': [!] undefined method `copyright' for nil:NilClass (NoMethodError)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
/Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check': undefined method `copyright' for nil:NilClass (NoMethodError)
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/check_app_store_metadata.rb:10:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:76:in `block (2 levels) in parsing_binding'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/dev/.rvm/gems/ruby-2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	from /Users/dev/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'

</pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### LINKED ISSUE #17208: undefined method `get_app_info_localizations' for nil
I get fastlane error, when using this command:

fastlane precheck -u mail@domain.com -a app_ident

Any suggestions to solve problem?

**Log:**
INFO [2020-09-10 13:05:18.47]: Successfully logged in
INFO [2020-09-10 13:05:18.47]: Checking app for precheck rule violations

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `get_app_info_localizations' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60get_app_info_localizations%27%20for%20nil+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	15: from /usr/local/bin/fastlane:23:in `<main>'
	14: from /usr/local/bin/fastlane:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:19:in `start'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:71:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:41:in `block (2 levels) in run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:47:in `process_app_and_version'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:134:in `generate_app_items_to_check': undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)
	15: from /usr/local/bin/fastlane:23:in `<main>'
	14: from /usr/local/bin/fastlane:23:in `load'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/bin/fastlane:23:in `<top (required)>'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:19:in `start'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:71:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/commands_generator.rb:41:in `block (2 levels) in run'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:34:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/runner.rb:102:in `check_for_rule_violations'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:47:in `process_app_and_version'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.158.0/precheck/lib/precheck/rule_processor.rb:134:in `generate_app_items_to_check': [!] undefined method `get_app_info_localizations' for nil:NilClass (NoMethodError)

**Env:**
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G2021)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.7                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.158.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.18.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.27.0       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.358.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.104.4      |
| aws-sdk-kms               | 1.36.0       |
| aws-sdk-s3                | 1.78.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>

*generated on:* **2020-09-10**
</details>

### LINKED ISSUE #17434: Fastlane promote failed
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Problem on fastlane pipeline when promoting from TestFlight to Production using it with AzureDevops (AppStore Promote Task)

##### Command executed
```
fastlane deliver submit_build -u *** -a APP --skip_binary_upload true --skip_metadata true --skip_screenshots true --automatic_release --force --verbose
```

##### Complete output when running fastlane, including the stack trace and command used
```
2020-10-14T07:15:31.0834520Z INFO [2020-10-14 09:15:31.07]: Checking app for precheck rule violations
2020-10-14T07:15:44.7438290Z INFO [2020-10-14 09:15:44.74]: Reading in-app purchases. If you have a lot, this might take a while
2020-10-14T07:15:44.7440910Z INFO [2020-10-14 09:15:44.74]: You can disable IAP checking by setting the `include_in_app_purchases` flag to `false`
2020-10-14T07:15:45.2433920Z INFO [2020-10-14 09:15:45.23]: Done reading in-app purchases
2020-10-14T07:15:45.2535010Z ERROR [2020-10-14 09:15:45.23]: [31mfastlane precheck just tried to inspect your app's metadata for App Store guideline violations and ran into a problem. We're not sure what the problem was, but precheck failed to finished. You can run it in verbose mode if you want to see the whole error. We'll have a fix out soon 🚀[0m
2020-10-14T07:15:45.2648980Z DEBUG [2020-10-14 09:15:45.24]: #<NoMethodError: undefined method `copyright' for nil:NilClass>
2020-10-14T07:15:45.2751700Z DEBUG [2020-10-14 09:15:45.24]: /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/rule_processor.rb:177:in `generate_version_items_to_check'
2020-10-14T07:15:45.2852240Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/rule_processor.rb:48:in `process_app_and_version'
2020-10-14T07:15:45.2953850Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/runner.rb:121:in `check_for_rule_violations'
2020-10-14T07:15:45.3055070Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/precheck/lib/precheck/runner.rb:47:in `run'
2020-10-14T07:15:45.3156500Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:101:in `precheck_app'
2020-10-14T07:15:45.3257910Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:63:in `run'
2020-10-14T07:15:45.3361130Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:45.3453770Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:45.3497080Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:45.3529820Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:45.3583990Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:45.3662550Z /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:45.3715450Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:45.3818080Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:45.3920630Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:45.4024430Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:45.4078710Z /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:45.4107480Z /usr/local/bin/fastlane:23:in `<main>'
2020-10-14T07:15:46.2227030Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': [31m[!] Cannot submit for review - could not find an editable version for 'IOS'[0m (FastlaneCore::Interface::FastlaneError)
2020-10-14T07:15:46.2304360Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-10-14T07:15:46.2356800Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-10-14T07:15:46.2459660Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-10-14T07:15:46.2562600Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-10-14T07:15:46.2660320Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:46.2705380Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:46.2775000Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:46.2779550Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:46.2897590Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:46.2913120Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:46.2938130Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:46.2952680Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:46.2979280Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:46.3007420Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:46.3013350Z 	from /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:46.3014800Z 	from /usr/local/bin/fastlane:23:in `<main>'
2020-10-14T07:15:46.3041600Z /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!': Cannot submit for review - could not find an editable version for 'IOS' (FastlaneCore::Interface::FastlaneError)
2020-10-14T07:15:46.3144970Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
2020-10-14T07:15:46.3147220Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/submit_for_review.rb:16:in `submit!'
2020-10-14T07:15:46.3149010Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:194:in `submit_for_review'
2020-10-14T07:15:46.3150670Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/runner.rb:64:in `run'
2020-10-14T07:15:46.3152430Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:96:in `block (2 levels) in run'
2020-10-14T07:15:46.3169360Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
2020-10-14T07:15:46.3182840Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
2020-10-14T07:15:46.3204340Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
2020-10-14T07:15:46.3211710Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
2020-10-14T07:15:46.3234280Z 	from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
2020-10-14T07:15:46.3237260Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:186:in `run'
2020-10-14T07:15:46.3239460Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/deliver/lib/deliver/commands_generator.rb:17:in `start'
2020-10-14T07:15:46.3241480Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
2020-10-14T07:15:46.3300270Z 	from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.163.0/bin/fastlane:23:in `<top (required)>'
2020-10-14T07:15:46.3358270Z 	from /usr/local/bin/fastlane:23:in `load'
2020-10-14T07:15:46.3362250Z 	from /usr/local/bin/fastlane:23:in `<main>'
```

fastline env
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.7                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.7 (19H2)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.0.1                                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.163.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.1.0        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 1.17.2       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.14.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.381.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
| webrick                   | 1.4.2        |
</details>
```

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #17208
Resolves #17176
Resolves #17434

### Description
As of master, only "editable" app versions are able to be prechecked. However, based on the testimonials [here](https://github.com/fastlane/fastlane/issues/17208#issuecomment-734002754), this sounded like a regression. So I investigated further [in _precheck_ history](https://github.com/fastlane/fastlane/commits/master/precheck/lib/precheck/rule_processor.rb), and looks like prior to Sep 4th 2020 _precheck_ could be used to check metadata of both edit **and** live app versions, thus introducing these regressions via https://github.com/fastlane/fastlane/pull/17167 

As I don't see any reason to limit it to only editable versions, I modified the code to allow live versions to be prechecked as well.

While testing, I also realized that this PR fixed another issue 🎉 which's #17176 :) 

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-allow-precheck-live-apps"
```

Then you should be able to run `fastlane precheck` regardless of what state your app is (live or edit). Such as:

```sh
bundle exec fastlane precheck -u email@example.com -a com.apple.example
```

### CODE REVIEW

**Comment by rogerluan** [comment]
🤔 I ran `bundle exec fastlane test` and it succeeded (except for https://github.com/fastlane/fastlane/issues/17391), but the specs failed here. Then I ran `bundle exec rspec` and it pointed out which spec was failing (precheck-related). 🤔 

Anyway, the specs are fixed now 😊

**Comment by rogerluan** [comment]
> 🤔 I ran `bundle exec fastlane test` and it succeeded (except for #17391), but the specs failed here. Then I ran `bundle exec rspec` and it pointed out which spec was failing (precheck-related). 🤔
> 
> Anyway, the specs are fixed now 😊

Well, I checked out to my previous commit and ran `be fastlane test` again and turns out the failure did show up. I think I just misread it the first time 🙈 No issues on the test setup!

**Review by max-ott — APPROVED** [review]
Tested with several apps, looking good!

File: spaceship/lib/spaceship/connect_api/models/app.rb [hunk 1]
```diff
@@ -144,6 +144,12 @@ def fetch_edit_app_info(client: nil, includes: Spaceship::ConnectAPI::AppInfo::E
         end.first
       end
 
+      def fetch_latest_app_info(client: nil, includes: Spaceship::ConnectAPI::AppInfo::ESSENTIAL_INCLUDES)
+        client ||= Spaceship::ConnectAPI
+        resp = client.get_app_infos(app_id: id, includes: includes)
+        return resp.to_models.first
+      end
```
Comment (joshdholtz) [inline spaceship/lib/spaceship/connect_api/models/app.rb:151]: I’m curious if we need to do a sort here to first grab the `app_store_state` to grab the edit states first over the live states 🤔 Since I’m guessing we still want to give the edit states priority over the live ones (and we can’t fully trust the API). Thoughts?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@rogerluan This looks really good! Just a quick thought on making sure we get the edit versions first over the live.

Also... do you think we need to add an option for `use_live` that defaults to `false`? Just incase people want to force live?

File: spaceship/lib/spaceship/connect_api/models/app.rb (hunk 1 above)
Comment (rogerluan) [reply spaceship/lib/spaceship/connect_api/models/app.rb:151]: I initially thought this made sense 100%, but while implementing it, I thought maybe there are legit cases where the latest is not the edit version, but it's the one the user intends to fetch app info from 🤔 I'm not sure how the API sorts them  - it could be by most recently updated, most recently created, or by semantic versions, for instance. If it's by anything other than creation date (e.g. update date, or semantic version), our "assumption" that edit versions should take precedence over live ones isn't really true, I think.

Maybe we could leave it as is and trust the API - and in case it becomes a problem, we revisit? What do you think?
Although I feel your pain of working with undocumented that can't be trusted in the past, we're working with a documented and official set of APIs now, that _maybe_ we should be able trust that it have its inner logic updated silently? 😅  I tend to avoid putting extra business logic in the client/consumer app also. 

Anyways, if you still think we should add that logic here, I'm up for it. I propose this:

```ruby
def fetch_latest_app_info(client: nil, includes: Spaceship::ConnectAPI::AppInfo::ESSENTIAL_INCLUDES)
  client ||= Spaceship::ConnectAPI
  resp = client.get_app_infos(app_id: id, includes: includes)
  return resp.to_models.sort_by do |model|
    # Give preference to the edit app states over live ones
    Spaceship::ConnectAPI::AppInfo::AppStoreState::EDIT_APP_STATES.include?(model.app_store_state) ? 0 : 1
  end.first
end
```

**Comment by rogerluan** [comment]
@joshdholtz I replied to your question and also added a `use_live` (since it can't hurt 😇 ), lemme know your thoughts 🙏 😃

File: spaceship/lib/spaceship/connect_api/models/app.rb (hunk 1 above)
Comment (joshdholtz) [reply spaceship/lib/spaceship/connect_api/models/app.rb:151]: I think you are right! I think we can leave it like this for now 💪

File: precheck/lib/precheck/runner.rb [hunk 2]
```diff
@@ -185,7 +185,7 @@ def app
 
     def latest_app_version
       platform = Spaceship::ConnectAPI::Platform.map(Precheck.config[:platform])
-      @latest_version ||= app.get_edit_app_store_version(platform: platform)
+      @latest_version ||= app.get_latest_app_store_version(platform: platform)
```
Comment (joshdholtz) [inline precheck/lib/precheck/runner.rb:188]: One more thing! Should this also use the `use_live`? Seems like we'd want the App Store version to clearly use either the "edit" or "live" version, right?

**Review by joshdholtz — CHANGES_REQUESTED** [review]
One more thought here!

File: precheck/lib/precheck/runner.rb (hunk 2 above)
Comment (rogerluan) [reply precheck/lib/precheck/runner.rb:188]: Yup, nice catch! Updating now

Comment (rogerluan) [reply precheck/lib/precheck/runner.rb]: Done 💪

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much for fixing this and adopting my review comments ❤️
