### PR TITLE
[scan] removing duplicate settings of config

### LINKED ISSUE #15717: xcodebuild -showBuildSettings` called twice for Scan
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Scan runs xcodebuild -showBuildSettings twice in succession with identical arguments. Scan is called around 27 times in CI for full build and every time scan is called it executes below command twice with same arguments . Each time command is executed, it takes around 40-60 seconds . And for full build it is getting executed 54 times ( 27*2) adding around 50 minutes of extra time.

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>[22:32:11 $ xcodebuild -showBuildSettings -workspace Enterprise.xcworkspace -scheme Enterprise
22:33:16 $ xcodebuild -showBuildSettings -workspace Enterprise.xcworkspace -scheme Enterprise
22:34:15 ]</pre>
</details>

### Environment
<details>
 fastlane_version "2.132.0"
 Ruby                        | 2.5.3 
</details>

### PR DESCRIPTION
**Pull request by pradyhk**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Whenever scan or run_tests is used in Fastfile it executes
xcodebuild showbuildsettings two times with same parameters which increases overall build time

Resolves https://github.com/fastlane/fastlane/issues/15717

### Description
Scan.config is initialized when manager is called here which does the job of using build settings for the parameters from scheme.

I have tested this change with project i am working on where run_tests is 27 times for around 14 schemes in total without any issue.

**UPDATED**: Passing SCAN_DERIVED_DATA_PATH, SCAN_APP_NAME and SCAN_DEPLOYMENT_TARGET_VERSION from env file will **not make any cal**l to buildsettings which **saved total of 57 minutes** for my project.

### Testing Steps
scan or run_tests actions with required parameters

### CODE REVIEW

**Comment by pradyhk** [comment]
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Ffastlane%2Ffastlane%2Fpull%2F15732) for more info**.

@googlebot I signed it!

File: fastlane/lib/fastlane/actions/run_tests.rb [hunk 1]
```diff
@@ -14,7 +14,6 @@ def self.run(values)
 
         begin
           destination = values[:destination] # save destination value which can be later overridden
-          Scan.config = values # we set this here to auto-detect missing values, which we need later on
```
Comment (janpio) [inline fastlane/lib/fastlane/actions/run_tests.rb]: Absolutely sure this is not needed for anything? We usually don't just have stuff like that in the codebase if it doesn't have a purpose...

Comment (pradyhk) [reply fastlane/lib/fastlane/actions/run_tests.rb]: Scan.config is again set with same `values` in the next line when it is passed to https://github.com/fastlane/fastlane/blob/4e3417ddeeee5958e83c53c65ed561cff306a972/fastlane/lib/fastlane/actions/run_tests.rb#L23  as options which is again setting scan.config.. https://github.com/fastlane/fastlane/blob/4e3417ddeeee5958e83c53c65ed561cff306a972/scan/lib/scan/manager.rb#L8

Comment (pradyhk) [reply fastlane/lib/fastlane/actions/run_tests.rb]: if there is any usecase i would definitely like to test it with this change.. I have tested locally with both fastfile and scanfile .

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/run_tests.rb]: This `Scan.config = values` is actually needed here. Setting `Scan.config` here calls `DetectValues.set_additional_default_values` which is needed for the `test_summary_filenames` method call below.

If anything, the second `Scan.config=` in `Scan::Manager.new.work` shouldn't be called but we can't delete that one because that one is needed when calling `scan` from the CLI.

So this `Scan.config` that is called first in this action is needed for a little bit of extra stuff that the action does that `Scan::Manager.new.work` doesn't do.

Sooooooo... if anything, this extra behavior should maybe get moved into `Scan::Manager.new.work` so that the CLI version gets this extra output and we can remove the second call 🙃

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Left a comment on why this is needed here but what the proper change would be 😇

File: fastlane/lib/fastlane/actions/run_tests.rb (hunk 1 above)
Comment (pradyhk) [reply fastlane/lib/fastlane/actions/run_tests.rb]: that sounds interesting and should the trick .. will test that locally.. thanks for the detail explanation .. much appreciated

Comment (pradyhk) [reply fastlane/lib/fastlane/actions/run_tests.rb]: @joshdholtz any suggestions on how i can return `plist_files_before ` from `manager` to `run_tests` as manager is already returning 
https://github.com/fastlane/fastlane/blob/4e3417ddeeee5958e83c53c65ed561cff306a972/scan/lib/scan/manager.rb#L18

i was thinking of adding `plist_files_before` to Scan.cache by creating new method in  DetectValues.set_additional_default_values ?

**Review by jaleksynas — APPROVED** [review]
I think this is a great win for large projects.  I suspect that many people will get overall build time reductions using these "manual" flags.

**Comment by pradyhk** [comment]
Feedback addressed @joshdholtz .

**Review by raktim990 — APPROVED** [review]

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by joshdholtz** [comment]
@pradyhk Heyyy 👋 I rebased from master and pushed a commit onto here to fix the double scanning of configs. Checking if derived data was empty didn't seem to fix it on my end. I ended up moving the first scan and storing of plist files into the manager. That plist files before can then be referent from the manager in the the `run_tests` action to do the plist differences.

I also removed the storing of `:destination` and resetting of it because it wasn't actually doing anything. It didn't look like it was actually doing anything and `:destination` doesn't actually et reset inside of `Scan::DetectValues` if its manually set. 

If you could pull these changes down and let me know if it works for you that would be 💯 🙏

File: scan/lib/scan/options.rb [hunk 2]
```diff
@@ -311,6 +311,18 @@ def self.available_options
...
+                                    env_name: "SCAN_APP_NAME",
+                                    optional: true,
+                                    description: "App name to use in slack message and logfile name",
+                                    is_string: true),
+        FastlaneCore::ConfigItem.new(key: :deployment_target_version,
+                                    env_name: "SCAN_DEPLOYMENT_TARGET_VERSION",
+                                    optional: true,
+                                    description: "Target version of the app being build or tested. Used to filter out simulator version",
+                                    is_string: true),
+
```
[the remark this answers is not in the document]
Comment (pradyhk) [reply scan/lib/scan/options.rb]: initial thought was to remove duplicate showbuildsettings.. but while making changes, realized if we pass `target version` and `app name` we can totally avoid calling showBuildSettings which Scan much faster .. 

> 

>

[the remark this answers is not in the document]
Comment (joshdholtz) [reply scan/lib/scan/options.rb]: Ahhh, that is interesting! Its cool how much time that saved you but these options are pretty specific 🤔  I definitely want you to save that extra time but I'm going to think if there is some other way instead of adding two more options 😇

**Review by joshdholtz — APPROVED** [review]
This is good to merge now! Thanks for getting this started 😊 Glad this is able to drastically reduce your scan times 💪

**Comment by pradyhk** [comment]
@joshdholtz awesome 🍾 🎉 . Thanks for merging the PR..
