### PR TITLE
[core] skip setting partition list if key is already imported

### LINKED ISSUE #14039: [Regression] Breaking change when importing a new cert in 2.113.0, worked in 2.112.0
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
There is an error message when importing a new certificate:
```
Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/dmitry/Library/Keychains/fastlane.keychain-db`

[17:59:19]: 
[17:59:19]: Please look at the following docs to see how to set a keychain password:
[17:59:19]:  - https://docs.fastlane.tools/actions/sync_code_signing
[17:59:19]:  - https://docs.fastlane.tools/actions/get_certificates
```

This leads to build failures in CI because of the UI permission popup.
Keychain password in supplied in the Match file, as per details below.

##### Command executed

```
fastlane certificates
```
^ this installs certificates for various build types
##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>:fastlane dmitry$ fastlane certificates
[09:51:41]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[09:51:43]: ----------------------------------------
[09:51:43]: --- Step: Verifying fastlane version ---
[09:51:43]: ----------------------------------------
[09:51:43]: Your fastlane version 2.113.0 matches the minimum requirement of 2.44.1  ✅
[09:51:43]: ------------------------------
[09:51:43]: --- Step: default_platform ---
[09:51:43]: ------------------------------
[09:51:43]: Driving the lane 'certificates' 🚀
[09:51:43]: -----------------------------
[09:51:43]: --- Step: delete_keychain ---
[09:51:43]: -----------------------------
[09:51:43]: -----------------------------
[09:51:43]: --- Step: create_keychain ---
[09:51:43]: -----------------------------
[09:51:43]: $ security list-keychains -d user
[09:51:43]: ▸ "/Users/dmitry/Library/Keychains/login.keychain-db"
[09:51:43]: -------------------
[09:51:43]: --- Step: match ---
[09:51:43]: -------------------
WARNING: You are running Ruby 2.2.4, which has reached end-of-life and is no longer supported by Ruby Core.
The Google Cloud API clients work best on supported versions of Ruby. It is strongly recommended that you upgrade to Ruby 2.4 or later.
See https://www.ruby-lang.org/en/downloads/branches/ for more info on the Ruby maintenance schedule.
To suppress this message, set the GOOGLE_CLOUD_SUPPRESS_RUBY_WARNINGS environment variable.
[09:51:43]: Successfully loaded '/Users/dmitry/Documents/development/fastlane/fastlane/Matchfile' 📄

+-------------------+--------------------------------------+
|       Detected Values from './fastlane/Matchfile'        |
+-------------------+--------------------------------------+
| git_url           | REDUCTED                       |
| type              | development                          |
| readonly          | true                                 |
| keychain_name     | fastlane.keychain                    |
| keychain_password | temppassword                         |
+-------------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                  Summary for match 2.113.0                   |
+-----------------------+--------------------------------------+
| type                  | development                          |
| readonly              | true                                 |
| app_identifier        | ["REDUCTED"]                 |
| username              | REDUCTED      |
| storage_mode          | git                                  |
| git_url               | REDUCTED                       |
| git_branch            | master                               |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| keychain_name         | fastlane.keychain                    |
| keychain_password     | ********                             |
| force                 | false                                |
| force_for_new_devices | false                                |
| skip_confirmation     | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
| verbose               | false                                |
+-----------------------+--------------------------------------+

[09:51:43]: Cloning remote git repo...
[09:51:43]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[09:51:44]: 🔓  Successfully decrypted certificates repo
[09:51:44]: Installing certificate...
[09:51:44]: There are no local code signing identities found.
You can run `security find-identity -v -p codesigning fastlane.keychain` to get this output.
This Stack Overflow thread has more information: https://stackoverflow.com/q/35390072/774.
(Check in Keychain Access for an expired WWDR certificate: https://stackoverflow.com/a/35409835/774 has more info.)
[09:51:45]: 
[09:51:45]: Could not configure imported keychain item (certificate) to prevent UI permission popup when code signing
Check if you supplied the correct `keychain_password` for keychain: `/Users/dmitry/Library/Keychains/fastlane.keychain-db`

[09:51:45]: 
[09:51:45]: Please look at the following docs to see how to set a keychain password:
[09:51:45]:  - https://docs.fastlane.tools/actions/sync_code_signing
[09:51:45]:  - https://docs.fastlane.tools/actions/get_certificates

+-------------------+-------------------------------------------+
|                     Installed Certificate                     |
+-------------------+-------------------------------------------+
| User ID           | H78U838C7X                                |
| Common Name       | iPhone Developer: Jenkins CI (H24NQR3297) |
| Organisation Unit | REDUCTED                                |
| Organisation      | REDUCTED                         |
| Country           | US                                        |
| Start Datetime    | 2018-07-24 08:13:16 UTC                   |
| End Datetime      | 2019-07-24 08:13:16 UTC                   |
+-------------------+-------------------------------------------+

[09:51:45]: Installing provisioning profile...

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | REDUCTED       |
| Type                |                        | development            |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_ REDUCTED  | edae9a4e-d550-492a-9b  |
|                     | _development           | d5-1ff7d94b39cf        |
| Profile Name        | sigh_ REDUCTED  | match Development      |
|                     | _development_profile-  | REDUCTED       |
|                     | name                   | 1532420603             |
| Profile Path        | sigh_ REDUCTED  | /Users/dmitry/Library  |
|                     | _development_profile-  | /MobileDevice/Provisi  |
|                     | path                   | oning                  |
|                     |                        | Profiles/edae9a4e-d55  |
|                     |                        | 0-492a-9bd5-1ff7d94b3  |
|                     |                        | 9cf.mobileprovision    |
| Development Team ID | sigh_ REDUCTED  | 8P6Q66W4FV             |
|                     | _development_team-id   |                        |
+---------------------+------------------------+------------------------+

[09:51:45]: All required keys, certificates and provisioning profiles are installed 🙌</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.18.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.2 (18C54)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.44.1"

before_all do
  update_fastlane
  ENV["keychain"] = "fastlane.keychain"
end

default_platform :ios

def ensure_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: 'temppassword',
    unlock: true,
    timeout: false
  )
end

lane :certificates do
  ensure_temp_keychain(ENV["keychain"])
  match
  match(type: "appstore")
  match(app_identifier: "REDUCTED.*", type: "enterprise", git_branch: "PAW5F92N29")
  match(type: "adhoc")
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDUCTED" # the bundle identifier of your app
package_name "REDUCTED"   # the bundle identifier of your app

apple_id "REDUCTED" # Your Apple ID

json_key_file "REDUCTED.json"

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.113.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| uber                      | 0.0.15       |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| libxml-ruby               | 3.0.0        |
| psych                     | 2.0.8        |
</details>

*generated on:* **2019-01-09**
</details>
<details><summary><b>Match file</b></summary>
```
git_url("REDUCTED")

type("development")
readonly("true")

keychain_name(ENV["keychain"])
keychain_password("temppassword")
```
</details>
</pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #14039

## Issues
There were two outstanding issues/improvements from the recent keychain importer changes.
1. The `UI.error` was too strong/bold and causing users to think there were actually importing issues in their import so it was moved to a `UI.important`
2. Certificates were being skipped if they were already installed but this was not happening with keys
  - With the addition of the recent keychain importer PRs, `set-partition-lists` would always run which would be skipped for certificates that were already installed but would get run for every key
  - If a user had a lot of keys installed, this would add a lot of extra unnecessary time since key was already imported
  - This `set-partition-lists` also requires the keychain password which (if not provided) which show that overly loud `UI.error` about how to solve
  - Skipping installed keys will speed up the match process along with showing unnecessary warning/errors 

## Description
1. Changed `UI.error` to `UI.important` for the warning/suggestion on how to improve that their match process
2. Using `Open3` instead of `Helper.backticks` so that we can get the success/error status and look at the output error to see if its a duplicate key so that we can skip the `set-partition-lists` process

### CODE REVIEW

File: fastlane_core/lib/fastlane_core/keychain_importer.rb [hunk 1]
```diff
@@ -12,8 +12,27 @@ def self.import_file(path, keychain_path, keychain_password: "", certificate_pas
...
+        UI.command_output(stdout.read.to_s) if output
 
+        # Set partition list only if success since it can be a time consuming process if a lot of keys are installed
+        if thrd.value.success?
+          set_partition_list(path, keychain_path, keychain_password: keychain_password, certificate_password: certificate_password, output: output)
+        else
+          # Output verbose if file is already installed since not an error otherwise we will show the whole error
+          err = stderr.read.to_s.strip
+          if err.include?("SecKeychainItemImport") && err.include?("The specified item already exists in the keychain")
+            type = File.extname(".p12") ? "Key" : "Certificate"
```
Comment (snatchev) [inline fastlane_core/lib/fastlane_core/keychain_importer.rb]: `File.extname(".p12")` always returns `""` which is always true. Is the intended parameter `path`?

**Review by snatchev — CHANGES_REQUESTED** [review]
Just a small notice. Seems like a nice-to-have in the verbose message. I think just printing the path of the file in question is sufficient.

File: fastlane_core/lib/fastlane_core/keychain_importer.rb (hunk 1 above)
Comment (KrauseFx) [reply fastlane_core/lib/fastlane_core/keychain_importer.rb]: Yes, that definitely looks like a bug

Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/keychain_importer.rb]: Oops! lol, good catch

Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/keychain_importer.rb]: I should add a test for that

Comment (joshdholtz) [reply fastlane_core/lib/fastlane_core/keychain_importer.rb]: Fixed!! ^ I just removed that type completely

**Review by snatchev — APPROVED** [review]
LGTM

**Review by KrauseFx — APPROVED** [review]
