### PR TITLE
[ready for review] [scan] Refactor matching simulator devices for `device` flags and defaults.

### LINKED ISSUE #5742: Scan cannot find simulators
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Scan cannot find simulators

##### Complete output when running fastlane, including the stack trace and command used

```
bundle exec scan --device "iPhone 6s"
[17:01:54]: Ignoring 'iPhone 6s', couldn't find matching simulator
[17:01:54]: Couldn't find any matching simulators for '["iPhone 6s"]' - falling back to default simulator
+-----------------------+--------------------------------------------------------------------------+
|                                     Summary for scan 0.11.2                                      |
+-----------------------+--------------------------------------------------------------------------+
| device                | iPhone 6s                                                                |
| workspace             | ./Foobar.xcworkspace                                                   |
| scheme                | Foobar                                                                 |
| derived_data_path     | .../DerivedData/Foobar-... |
| clean                 | false                                                                    |
| code_coverage         | false                                                                    |
| address_sanitizer     | false                                                                    |
| skip_build            | false                                                                    |
| output_directory      | ./fastlane/test_output                                                   |
| output_types          | html,junit                                                               |
| buildlog_path         | ~/Library/Logs/scan                                                      |
| open_report           | false                                                                    |
| skip_slack            | false                                                                    |
| slack_only_on_failure | false                                                                    |
| use_clang_report_name | false                                                                    |
+-----------------------+--------------------------------------------------------------------------+

[17:05:15]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace ./Foobar.xcworkspace -scheme Foobar -destination 'platform=iOS Simulator,id=2732721F-BB19-4019-8594-56B1F1EE4981' -derivedDataPath '/Users/ragecode/Library/Developer/Xcode/DerivedData/Foobar-byiivdizifwfoqejwrhhgjtcjuly' build test | tee '/Users/ragecode/Library/Logs/scan/Foobar-Foobar.log' | xcpretty 
```

Output of `instruments -s`:

```
instruments -s
Known Devices:
ragebookpro [F7FFE450-8C45-56F6-8AC9-2FD8768657F5]
Apple TV 1080p (9.2) [5FB0ABEA-9B96-4AB0-B85E-E65EFA3E17CF] (Simulator)
iPad 2 (9.3) [8D9B2FA3-95EE-41F8-92C6-C35C765C9242] (Simulator)
iPad Air (9.3) [76486C39-4F1F-437B-A8F7-40A29FB1BC4E] (Simulator)
iPad Air 2 (9.3) [4B07F52F-D02C-4DB9-A35A-09F93639BF52] (Simulator)
iPad Pro (9.3) [B813E2BE-E780-496D-AB3A-B75FA0AC8D93] (Simulator)
iPad Retina (9.3) [FF1CB7C6-60B3-4C96-BCF0-E8717590C6AD] (Simulator)
iPhone 4s (9.3) [4A0C9D6C-35B9-4161-B67D-FCFDAEFDE583] (Simulator)
iPhone 5 (9.3) [290A73D6-2334-4B19-B22C-6DF0023549E2] (Simulator)
iPhone 5s (9.3) [2732721F-BB19-4019-8594-56B1F1EE4981] (Simulator)
iPhone 6 (9.3) [60ED7DD2-EA31-43E9-BA72-F2A960F9CA6E] (Simulator)
iPhone 6 Plus (9.3) [4CE88860-2EC2-4A0B-9794-310E9D8B25D4] (Simulator)
iPhone 6s (9.3) [3F5C6BBB-96BB-4A75-AF61-6AE993F04289] (Simulator)
iPhone 6s (9.3) + Apple Watch - 38mm (2.2) [C1D65072-E256-4438-98C6-17996190C888] (Simulator)
iPhone 6s Plus (9.3) [B3DF44A4-D531-4FF7-9ACA-C82BEF01E2DC] (Simulator)
iPhone 6s Plus (9.3) + Apple Watch - 42mm (2.2) [EE2BEDA7-700D-4366-97D9-DFF59AE6BDBA] (Simulator)
Known Templates:
"Activity Monitor"
"Allocations"
"Automation"
"Blank"
"Cocoa Layout"
"Core Animation"
"Core Data"
"Counters"
"Energy Log"
"File Activity"
"GPU Driver"
"Leaks"
"Metal System Trace"
"Network"
"OpenGL ES Analysis"
"System Trace"
"System Usage"
"Time Profiler"
"Zombies"
"~/Library/Application Support/Instruments/Templates/MyTemplate.tracetemplate"
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

N/A

### Environment

scan version (run `scan -v`):

`0.11.2`

Do you use bundler to execute fastlane (i.e. `bundle exec scan`)? YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

### PR DESCRIPTION
**Pull request by jdhealy**
- Replace untrue comment on `filter_simulators` to reflect function behavior.
- Match only simulators with versions ‘that are greater than or equal to the version of our deployment target.’
- Be less naïve with striping parentheses. Only match versions at end of line.
- Unify logic for iOS and tvOS.

Fixes #5742.

### CODE REVIEW

**Comment by ohwutup** [comment]
Thanks for the PR @jdhealy! This looks like quite a change to the way we handle simulators, would you mind doing two little things to get this to move forward? 

1. Could you fix up the hound/rubocop failures?
2. Would you mind adding a couple of tests to show where this was failing before and to validate the new behavior? 

Thank you!! 🐙 🚀

**Comment by jdhealy** [comment]
Behavior should now be more in line with [pre-`devices`-flag behavior](https://github.com/fastlane/fastlane/blob/c23f35790ac49d2b96978f5200d71eae85995501/scan/lib/scan/detect_values.rb):

- For arguments of `device`(s) flag with a version specifier, filter through only simulators with same version.

- For arguments of `device`(s) flag without a version specifier, (for example `--device 'iPad 2'`), return the single highest versioned simulator device available with matching name.

- Default to single highest versioned iOS simulator device available matching default device name (`iPhone 5s` or `Apple TV 1080p` or whatever).

File: scan/spec/test_command_generator_spec.rb [hunk 1]
```diff
@@ -166,6 +198,32 @@
...
+                                     :test
+                                   ])
+    end
+
+    it "rejects devices with versions below deployment target" do
+      options = { project: "./examples/standard/app.xcodeproj", device: "iPhone 5 (8.4)" }
+      Scan.config = FastlaneCore::Configuration.create(Scan::Options.available_options, options)
+
+      result = Scan::TestCommandGenerator.generate
+      # FIXME: expect UI error starting "No simulators found that are equal to the version of specifier"
```
Comment (jdhealy) [inline scan/spec/test_command_generator_spec.rb]: Not quite sure how to make `rspec` check for this. Could use some help with this…

Comment (ohwutup) [inline scan/spec/test_command_generator_spec.rb]: Happy to help! 

Are you expecting an exception to be raised here? What is it that you are looking to validate exactly?

Comment (jdhealy) [inline scan/spec/test_command_generator_spec.rb]: @ohwutup [this UI.error: detect_values.rb#L117-L119](https://github.com/jdhealy/fastlane/blob/03d8cb3bf0f0d871c595f6c1ed0df985100d31d2/scan/lib/scan/detect_values.rb#L117-L119)

Comment (ohwutup) [inline scan/spec/test_command_generator_spec.rb]: Ah! Makes sense... So I think the best way to handle that would be to call `UI.crash!(<message>)` instead of `UI.error` at the place of the link you shared, because if there is no simulator found, we can't proceed anyway right? 

That would also make this test easy to implement with something like this in `rspec`: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers/raise-error-matcher

Comment (jdhealy) [inline scan/spec/test_command_generator_spec.rb]: > because if there is no simulator found, we can't proceed anyway right?

Not for that location, at least. The error could show for one device in a `--devices` array, but the next `device_string` could resolve. In a different scenario, it could select the default.

Is there a `UI.warning` that would be a better fit than `.error`? Does error end the process?

**Comment by jdhealy** [comment]
With the exception of [the rspec question](https://github.com/fastlane/fastlane/pull/5746#discussion_r74979397), this is set and ready for review. 🌈

**Comment by jdhealy** [comment]
@ohwutup Notes, comments, review?

I believe this addresses #5742 — which @postmechanical [confirmed to still be an issue in `scan-0.11.3`](https://github.com/fastlane/fastlane/issues/5731#issuecomment-241087446).

**Comment by jdhealy** [comment]
welp, [tried to make headway](https://github.com/jdhealy/fastlane/blob/160994ea857f83c11e1f0fbe95cef9ea478ef4eb/scan/spec/test_command_generator_spec.rb#L219-L227) on [that one rspec question](https://github.com/fastlane/fastlane/pull/5746#discussion_r74979397), but [no dice](https://circleci.com/gh/fastlane/fastlane/4086).

So, back to the same diff as [jdhealy/fastlane@`03d8cb`](https://github.com/jdhealy/fastlane/blob/03d8cb3bf0f0d871c595f6c1ed0df985100d31d2/scan/lib/scan/detect_values.rb), but squashed down, so the last two commits can be easily cherry-picked for clean history.

Code works, just unversed in how to finagle `rspec` to expect that `UI.error`.

**Comment by KrauseFx** [comment]
Hey @jdhealy, really sorry for the delay from our side, I'm looking into this issue and your PR right now 👍

**Comment by KrauseFx** [comment]
@jdhealy can you drop me a DM on Twitter (@KrauseFx) with your email? 👍

**Comment by KrauseFx** [comment]
This is great, thanks for working on this @jdhealy, I'll add a follow-up commit in a few minutes 👍
