### PR TITLE
Remove unnecessary output that the certificates repo was encrypted

### LINKED ISSUE #7869: Match encrypts repo after failed clone
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When match fails to clone the certificate repo, it will still continue with encrypting it. Or at least that's what the output suggests:

image

But I think that action shouldn't be executed when the clone fails.

### PR DESCRIPTION
**Pull request by ohayon**
After repo cloning fails, it still would print out that the repo was being encrypted. This fixes: https://github.com/fastlane/fastlane/issues/7869

### CODE REVIEW

**Comment by fastlane-bot-helper** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please provide a changelog summary in the Pull Request description @ohayon</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Review by mfurtak — APPROVED** [review]

File: match/lib/match/git_helper.rb [hunk 1]
```diff
@@ -90,7 +90,6 @@ def self.clear_changes
       return unless @dir
 
       FileUtils.rm_rf(@dir)
-      UI.success "🔒  Successfully encrypted certificates repo" # so the user is happy
```
Comment (hjanuschka) [inline match/lib/match/git_helper.rb]: i liked that, according to the removed comment the user is not happy anymore 😢
