### PR TITLE
Fix 9402 import cert not escaping special chars

### LINKED ISSUE #9402: import certificate can fail if there are special characters in keychain_password
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When a keychain password has special characters, it isn't shell-escaped and it is not counted as the same password. The command, `security set-key-partition-list` will fail with:
```
security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct.
```

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

__I won't be posting the output here.__

The fix is fairly simple, but I want to add some debug-ability and update the code to fail when the command fails. To fix this, `FastlaneCore::KeychainImporter.import_file` must `shellescape` the `keychain_password` when passing it to the `security set-key-partition-list` command. I will open up a PR shortly, this is for a fastlane FYI

### PR DESCRIPTION
**Pull request by lyndsey-ferguson**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

This fixes https://github.com/fastlane/fastlane/issues/9402

### Description

I updated the code to run `shellescape` on the `keychain_password` so that the password used to create the keychain (which uses `shellescape`) is the same as the password used to import the certificate into the keychain.

I also added a bit of code to aid debugging by printing out the commands when _creating_ the keychain.

### CODE REVIEW

File: fastlane/lib/fastlane/actions/import_certificate.rb [hunk 1]
```diff
@@ -23,6 +23,7 @@ def self.available_options
                                        env_name: "FL_IMPORT_CERT_KEYCHAIN_PASSWORD",
                                        description: "The password for the keychain. Note that for the login keychain this is your user's password",
                                        sensitive: true,
+                                       default_value: "",
```
Comment (lyndsey-ferguson) [inline fastlane/lib/fastlane/actions/import_certificate.rb]: Otherwise, `nil` is passed into `keychain_importer`

File: fastlane/lib/fastlane/actions/create_keychain.rb [hunk 2]
```diff
@@ -22,31 +24,31 @@ def self.run(params)
...
-            Actions.lane_context[Actions::SharedValues::ORIGINAL_DEFAULT_KEYCHAIN] = Fastlane::Actions.sh("security default-keychain", log: false).strip
+            Actions.lane_context[Actions::SharedValues::ORIGINAL_DEFAULT_KEYCHAIN] = Fastlane::Actions.sh("security default-keychain", log: should_log).strip
           rescue
           end
-          commands << Fastlane::Actions.sh("security default-keychain -s #{keychain_path}", log: false)
+          commands << Fastlane::Actions.sh("security default-keychain -s #{keychain_path}", log: should_log)
         end
 
-        commands << Fastlane::Actions.sh("security unlock-keychain -p #{escaped_password} #{keychain_path}", log: false) if params[:unlock]
+        commands << Fastlane::Actions.sh("security unlock-keychain -p #{escaped_password} #{keychain_path}", log: should_log) if params[:unlock]
```
Comment (mfurtak) [inline fastlane/lib/fastlane/actions/create_keychain.rb]: Shell commands that contain passwords should ideally never have the possibility of making it into logs since often users can't control security for those logs (on hosted CI, for example).

File: fastlane/lib/fastlane/actions/create_keychain.rb [hunk 3]
```diff
@@ -10,6 +10,8 @@ class CreateKeychainAction < Action
       def self.run(params)
         escaped_password = params[:password].shellescape
 
+        should_log = FastlaneCore::Globals.verbose?
```
Comment (mfurtak) [inline fastlane/lib/fastlane/actions/create_keychain.rb]: I have some concerns about logging the commands and responses to `security`, as they could wind up as part of logs on a third party service.

If the purpose of this logging is to aid in debugging, I think we may want to control this logging via a more specific control than `--verbose`. My fear is that people are already using `--verbose` and suddenly start logging sensitive information that they were not before.

Does it make sense to trigger this with a specific environment variable, perhaps?

**Review by mfurtak — CHANGES_REQUESTED** [review]
The fix is great, but I have some questions/thoughts about the surrounding changes :+1:

File: fastlane/lib/fastlane/actions/import_certificate.rb (hunk 1 above)
Comment (lyndsey-ferguson) [inline fastlane/lib/fastlane/actions/import_certificate.rb]: You are spot on, I did not know about the `to_s` beauty

File: fastlane/lib/fastlane/actions/create_keychain.rb (hunk 2 above)
Comment (lyndsey-ferguson) [inline fastlane/lib/fastlane/actions/create_keychain.rb]: Oh, of course

**Comment by lyndsey-ferguson** [comment]
@mfurtak comments addressed. If everything else is okay, ready to merge.

File: fastlane/lib/fastlane/actions/create_keychain.rb [hunk 4]
```diff
@@ -22,31 +24,31 @@ def self.run(params)
         end
 
         commands = []
-        commands << Fastlane::Actions.sh("security create-keychain -p #{escaped_password} #{keychain_path}", log: false)
+        commands << Fastlane::Actions.sh("security create-keychain -p #{escaped_password} #{keychain_path}", log: should_log)
```
Comment (mfurtak) [inline fastlane/lib/fastlane/actions/create_keychain.rb]: I'd recommend using `Fastlane::Actions.sh_control_output(command, print_command: false, print_command_output: true)` here, just to always bias towards not logging the password.

Feel free to prepend that with a special call to `UI.command(command)` with the password parameter removed (when the  env var is present) if you want to get the rest of the command logged.

File: fastlane/lib/fastlane/actions/create_keychain.rb (hunk 2 above)
Comment (mfurtak) [inline fastlane/lib/fastlane/actions/create_keychain.rb]: I'd recommend using `Fastlane::Actions.sh_control_output(command, print_command: false, print_command_output: true)` here, just to always bias towards not logging the password.

Feel free to prepend that with a special call to `UI.command(command)` with the password parameter removed (when the  env var is present) if you want to get the rest of the command logged.

**Comment by mfurtak** [comment]
Last comments were typed directly into GitHub - please verify in practice :smile:

**Comment by lyndsey-ferguson** [comment]
@mfurtak comments addressed, ready to go!

**Review by mfurtak — APPROVED** [review]
🙌  Thanks!

**Comment by lyndsey-ferguson** [comment]
@mfurtak tests pass, you may want to review the change I made to allow it to `expect` the `expected_set_key_partition_list_command`
