### PR TITLE
[Regression][fastlane] Fixed fastlane command issue when tool name not provided

### LINKED ISSUE #20292: 2.206.0 upgrade now bombs with "undefined method `to_sym'"
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information
- Breaking version: 2.206.0
- Last working version: previous version

### Regression Description
As suggested, execute

 bundle update fastlane

...now doesn't work

##### Complete output when running fastlane, including the stack trace and command used
bundle exec fastlane

[✔] 🚀 
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Traceback (most recent call last):
	19: from /usr/local/bin/bundle:23:in `<main>'
	18: from /usr/local/bin/bundle:23:in `load'
	17: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
	16: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	15: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
	14: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
	13: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	12: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
	11: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	10: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	 9: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli.rb:483:in `exec'
	 7: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:23:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `kernel_load'
	 5: from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.9/lib/bundler/cli/exec.rb:58:in `load'
	 4: from /usr/local/bin/fastlane:23:in `<top (required)>'
	 3: from /usr/local/bin/fastlane:23:in `load'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/bin/fastlane:23:in `<top (required)>'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/cli_tools_distributor.rb:81:in `take_off'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.206.0/fastlane/lib/fastlane/cli_tools_distributor.rb:145:in `map_aliased_tools': undefined method `to_sym' for nil:NilClass (NoMethodError)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.6                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.32.0 (Apple Git-132)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | macOS 11.6 (20G165)                                            |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 13.2.1                                                         |
| Swift Version               | 5.5.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.206.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.6.1        |
| bundler                         | 2.3.9        |
| rake                            | 13.0.6       |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| public_suffix                   | 4.0.7        |
| addressable                     | 2.8.0        |
| artifactory                     | 3.0.15       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.2.0        |
| aws-partitions                  | 1.587.0      |
| aws-sigv4                       | 1.5.0        |
| jmespath                        | 1.6.1        |
| aws-sdk-core                    | 3.131.0      |
| aws-sdk-kms                     | 1.57.0       |
| aws-sdk-s3                      | 1.114.0      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.4        |
| unf_ext                         | 0.0.8.1      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.92.3       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.3        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.0       |
| http-cookie                     | 1.0.4        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.3.0        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.16.1       |
| googleauth                      | 1.1.3        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.2        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.21.0       |
| google-apis-playcustomapp_v1    | 0.7.0        |
| google-apis-iamcredentials_v1   | 0.10.0       |
| google-apis-storage_v1          | 0.14.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.2.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.36.2       |
| json                            | 2.6.2        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.21.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2022-05-18**
</details>

### PR DESCRIPTION
**Pull request by crazymanish**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
- Resolves #20292
- The Fastlane command without tool-name is broken, after this [PR](https://github.com/fastlane/fastlane/pull/20287) 
- Please see the above issue for more details

### Description
- Handle condition if tool_name is `nil`, basically skip the tool_name mapped look-up if nil.

### Testing Steps

- Update `Gemfile` to 👇 and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "crazymanish-fastlane-tools-name-fix"
```
- Try to run Fastlane command without tool-name i.e
```ruby
bundle exec fastlane
```

### CODE REVIEW

File: fastlane/lib/fastlane/cli_tools_distributor.rb [hunk 1]
```diff
@@ -78,7 +78,7 @@ def take_off
         tool_name = ARGV.first ? ARGV.first.downcase : nil
 
         tool_name = process_emojis(tool_name)
-        tool_name = map_aliased_tools(tool_name)
+        tool_name = map_aliased_tools(tool_name) unless tool_name.nil?
```
Comment (lucgrabowski) [inline fastlane/lib/fastlane/cli_tools_distributor.rb:81]: Thanks for investigation and quick fix @crazymanish
I propose moving the fix to `map_aliased_tools` (to return statement in line 145) to be consistent with `process_emojis` implementation by using safe navigation operator:
```ruby
def map_aliased_tools(tool_name)
    map = { ... }
    return map[tool_name&.to_sym] || tool_name
end
```
Another way could be grouping both`process_emojis` and `map_aliased_tools` in an unless statement `unless tool_name.nil?`, but as later we can see a check `if tool_name && ...` I would probably go for the former.

Comment (crazymanish) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: Thank you very much for this suggestion. i applied the suggestion and learn about the `&.` operator 🙂

Comment (lucgrabowski) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: I learnt about it during the review too ;)

**Review by lucgrabowski — APPROVED** [review]
LGTM 🔥

**Review by joshdholtz — APPROVED** [review]
Thank you thank you thank you!
