### PR TITLE
[screengrab] Fix escaping issue with adb path (#15981)

### LINKED ISSUE #15981: screengrab exiting with status 127 (FastlaneCore::Interface::FastlaneShellError)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I run `fastlane screengrab` in my Android project directory, I get an error stating `FastlaneCore::Interface::FastlaneShellError` with `exit status 127`. While I will post my complete env and output below, please note that I also downloaded the latest `master` of this repository as a ZIP file and have the same issue when I run `fastlane screengrab` in the [example directory](https://github.com/fastlane/fastlane/tree/master/screengrab/example).

I also followed all the other steps to configure fastlane in my project according to [the docs](https://docs.fastlane.tools/actions/screengrab/). Should be correct as it's also failing in the example project.

Here's my `fastlane/Screengrabfile` contents:

```ruby
locales(['en-US', 'de-DE'])
clear_previous_screenshots(true)
tests_apk_path 'app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
app_apk_path 'app/build/outputs/apk/debug/app-debug.apk'

```

##### Command executed
`fastlane screengrab` (before, I had successfully run `./gradlew assembleDebug assembleAndroidTest` and/or `fastlane build_for_screengrab`)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> DscheeBook-Pro:FitnessTracker-Android cihat$ fastlane screengrab
[✔] 🚀
[11:52:22]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[11:52:22]: Successfully loaded '/Users/Cihat/Code/FitnessTracker-Android/fastlane/Screengrabfile' 📄

+----------------------------+-----------------------------------------------------------------+
|                       Detected Values from './fastlane/Screengrabfile'                       |
+----------------------------+-----------------------------------------------------------------+
| locales                    | ["en-US", "de-DE"]                                              |
| clear_previous_screenshots | true                                                            |
| tests_apk_path             | app/build/outputs/apk/androidTest/debug/app-debug-androidTest.  |
|                            | apk                                                             |
| app_apk_path               | app/build/outputs/apk/debug/app-debug.apk                       |
+----------------------------+-----------------------------------------------------------------+

[11:52:22]: Using `adb` found at /Users/Cihat/Library/Android/sdk/platform-tools/adb which is not within the specified ANDROID_HOME at ~/Library/Android/sdk/
[11:52:22]: The `aapt` command could not be found relative to your provided ANDROID_HOME at ~/Library/Android/sdk/
[11:52:22]: Please ensure that the Android SDK is installed and you have the build tools downloaded

+-----------------------------+-----------------------------------------------------------------+
|                                Summary for screengrab 2.141.0                                 |
+-----------------------------+-----------------------------------------------------------------+
| tests_package_name          | com.flinesoft.fitnesstracker.test                               |
| android_home                | ~/Library/Android/sdk/                                          |
| locales                     | ["en-US", "de-DE"]                                              |
| clear_previous_screenshots  | true                                                            |
| output_directory            | fastlane/metadata/android                                       |
| skip_open_summary           | false                                                           |
| app_package_name            | com.flinesoft.fitnesstracker                                    |
| test_instrumentation_runner | androidx.test.runner.AndroidJUnitRunner                         |
| ending_locale               | en-US                                                           |
| use_adb_root                | false                                                           |
| app_apk_path                | app/build/outputs/apk/debug/app-debug.apk                       |
| tests_apk_path              | app/build/outputs/apk/androidTest/debug/app-debug-androidTest.  |
|                             | apk                                                             |
| device_type                 | phone                                                           |
| exit_on_test_failure        | true                                                            |
| reinstall_app               | false                                                           |
| use_timestamp_suffix        | true                                                            |
+-----------------------------+-----------------------------------------------------------------+

[11:52:22]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[11:52:22]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[11:52:22]: Clearing phoneScreenshots within fastlane/metadata/android

Looking for related GitHub issues on fastlane/fastlane...

➡️  Increment build number
    https://github.com/fastlane/fastlane/pull/127 [closed] 2 💬
    04 Feb 2017

➡️  Instead of FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD, fastlane asks for FASTLANE_PASSWORD
    https://github.com/fastlane/fastlane/issues/15038 [closed] 2 💬
    21 Sep 2019

➡️  Can't upload Android app to Crashlytics Beta
    https://github.com/fastlane/fastlane/issues/9389 [closed] 25 💬
    23 Jul 2018

and 7 more at: https://github.com/fastlane/fastlane/search?q=Shell%20command%20exited%20with%20exit%20status%20127%20instead%20of%200.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	18: from /Users/Cihat/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	17: from /Users/Cihat/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	16: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	15: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	14: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	13: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	12: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	11: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	10: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 9: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 8: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 7: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 6: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 5: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
	 4: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/adb_helper.rb:56:in `load_all_devices'
	 3: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': Shell command exited with exit status 127 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
	18: from /Users/Cihat/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	17: from /Users/Cihat/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	16: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/bin/fastlane:23:in `<top (required)>'
	15: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	14: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:19:in `start'
	13: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:67:in `run'
	12: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	11: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	10: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 9: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 8: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 7: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/commands_generator.rb:49:in `block (2 levels) in run'
	 6: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/runner.rb:57:in `run'
	 5: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/screengrab/lib/screengrab/runner.rb:89:in `select_device'
	 4: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/adb_helper.rb:56:in `load_all_devices'
	 3: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/sh_helper.rb:12:in `sh'
	 2: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane/lib/fastlane/helper/sh_helper.rb:80:in `sh_control_output'
	 1: from /Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/Cihat/.rvm/gems/ruby-2.6.3/gems/fastlane-2.141.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': [!] Shell command exited with exit status 127 instead of 0. (FastlaneCore::Interface::FastlaneShellError) </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.3                                     |
| Ruby                        | 2.6.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.21.0 (Apple Git-122.2)        |
| Installation Source         | ~/.rvm/gems/ruby-2.6.3/bin/fastlane         |
| Host                        | Mac OS X 10.15.3 (19D76)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.3/lib                |
| OpenSSL Version             | OpenSSL 1.1.1c  28 May 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane

default_platform(:android)

platform :android do
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
package_name("com.flinesoft.fitnesstracker")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.141.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.17.3       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| bundler                   | 1.17.3       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.4       |
| google-cloud-env          | 1.3.0        |
| google-cloud-errors       | 1.0.0        |
| google-cloud-core         | 1.5.0        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.1       |
| emoji_regex               | 1.0.1        |
| nanaimo                   | 0.2.6        |
| colored2                  | 3.1.2        |
| claide                    | 1.0.3        |
| CFPropertyList            | 3.0.2        |
| atomos                    | 0.1.3        |
| xcodeproj                 | 1.15.0       |
| unicode-display_width     | 1.6.1        |
| tty-screen                | 0.7.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| excon                     | 0.72.0       |
| json                      | 2.3.0        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-02-06**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by Jeehut**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #15981.

### Description

I've removed the escaping of the `adb` tool path as that added a `\` in front of the path which caused the issue. There's no need for shellescaping from my understanding of the [examples](https://ruby-doc.org/stdlib-2.5.1/libdoc/shellwords/rdoc/Shellwords.html) and [documentation pages](https://rubyreferences.github.io/rubyref/stdlib/string-utilities/shellwords.html) for paths, especially since this path doesn't include any whitespaces.

### Testing Steps

Just make sure `fastlane screengrab` is still working on different platforms. I've tested macOS only.

### CODE REVIEW

**Comment by Jeehut** [comment]
@googlebot I signed it!

**Comment by Jeehut** [comment]
Just checked the failing tests on Circle CI and I don't think they are related to the changes I made in this PR. It was probably failing because of the timing of the tests: The tests started at the end of the 6th of February but the check was done at the beginning of the 7th of February. So, just re-running the tests will fix the CI (can't do it myself though).

**Comment by janpio** [comment]
>  especially since this path doesn't include any whitespaces.

How do you know that? `adb` can be installed in whatever location the user chooses, so the path could have a space in it, right? `.shellescape` is used to make this unknown string safe for usage in a shell.

I think the problem is somewhere in the handling of an env var: https://github.com/fastlane/fastlane/issues/15981#issuecomment-583755942

**Review by janpio — CHANGES_REQUESTED** [review]
Don't think this is the actual problem or a good solution.

**Comment by Jeehut** [comment]
@janpio Good point, I've updated the solution to expand the `adb_path` instead to make sure we don't run into problems with paths starting with `~`. Can confirm that this solved the issue for me as well.

File: fastlane/lib/fastlane/helper/adb_helper.rb [hunk 1]
```diff
@@ -24,6 +24,10 @@ def initialize(adb_path: nil, adb_host: nil)
           adb_path = File.join(android_home, "platform-tools", "adb")
         end
 
+        if adb_path.start_with?('~')
```
Comment (janpio) [inline fastlane/lib/fastlane/helper/adb_helper.rb]: Why only if the path starts with? Shouldn't `File.expand_path` be safe all the time?

Comment (Jeehut) [reply fastlane/lib/fastlane/helper/adb_helper.rb]: I agree, should be safe all the time. I just wanted to do the changes as minimal-invasive as possible since I don't know the code base well and want to make sure my PR gets merged. Updated the code accordingly.

Comment (janpio) [reply fastlane/lib/fastlane/helper/adb_helper.rb]: Seems you were not wrong ;)

**Comment by janpio** [comment]
Ok, my feedback made sense in theory but in practice tests are not failing as they expect the unexpanded paths. Does that make sense? Should we update the tests? Or could this have any side effects?

**Comment by Jeehut** [comment]
@janpio I don't think it will have any side effects, but tests will become more cumbersome and less readable since we need to change things like `expect(result).to eq("./fastlane/README.md test")` to be something like `expect(result).to eq("#{File.expand_path('./fastlane/README.md')} test")` as we can't know the path on different devices statically. That's why I personally prefer the solution from the [previous commit](https://github.com/fastlane/fastlane/pull/15986/commits/811732a64867180b7cfb6384aea373ed1ac57d76).

File: fastlane/lib/fastlane/helper/adb_helper.rb (hunk 1 above)
Comment (Jeehut) [reply fastlane/lib/fastlane/helper/adb_helper.rb]: Reverted then, again. Especially since `shellescape` only affects paths starting with `~` (not those starting with `.`) so I think this was the correct solution for that reason as well. :)

**Comment by janpio** [comment]
That is just a bad example filename for a test that uses `adb`:
https://github.com/fastlane/fastlane/blob/39afb4defa1def891506a1eaabc374ebd289e9b2/fastlane/spec/actions_specs/adb_spec.rb#L4-L10

**Comment by Jeehut** [comment]
I see, thanks for the explanation.

What is your opinion on the code of this PR? If you don't mind, we just merge it as is for the reasons explained above. It fixes the issue with the `~` and doesn't affect anything else. Checks have all passed.

**Comment by janpio** [comment]
I think we should undo the last commit, and then just call `File.expand` manually in the tests. Otherwise we have a special case in the code that we sure will forget about in a few weeks.

**Comment by Jeehut** [comment]
@janpio Okay, reverted back to the solution where we expand all paths and made the relevant changes to the tests instead.

**Comment by janpio** [comment]
And we uncovered a problem on WIndows with that:

```
  1) Fastlane Fastlane::FastFile adb picks up path from ANDROID_HOME environment variable and handles path that has to be made safe
     Failure/Error: expect(result).to eq("#{File.expand_path(path)} test")
       expected: "C:/projects/fastlane/\"/usr/local/android-sdk/with space/platform-tools/adb\" test"
            got: "\"C:/usr/local/android-sdk/with space/platform-tools/adb\" test"
       (compared using ==)
     # ./fastlane/spec/actions_specs/adb_spec.rb:52:in `block (4 levels) in <top (required)>'
```

File: fastlane/spec/actions_specs/adb_spec.rb [hunk 2]
```diff
@@ -49,7 +49,7 @@
         end").runner.execute(:test)
 
         path = "/usr/local/android-sdk/with space/platform-tools/adb".shellescape
-        expect(result).to eq("#{path} test")
+        expect(result).to eq("#{File.expand_path(path)} test")
```
Comment (janpio) [inline fastlane/spec/actions_specs/adb_spec.rb]: I think this might be needed on `path` before the `.shellescape` is called on it.

Comment (Jeehut) [reply fastlane/spec/actions_specs/adb_spec.rb]: Makes sense, fixed via e301295031b7b84c6efb3e59b283952812a42899.

**Review by janpio — APPROVED** [review]
Wonderful and beautiful. Let's see if @joshdholtz agrees.

**Review by joshdholtz — APPROVED** [review]
Looks good to me! Thanks for looking into this ❤️  Really appreciate the contribution!
