### PR TITLE
[match] make match pass the keychain name to cert

### LINKED ISSUE #6375: Match calls cert with the wrong keychain
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I have a separate keychain called "buildserver.keychain" that I use with match. I ran match nuke and wanted to recreate my certificates afterward and notices in the verbose output that match runs cert to create a new code signing identity but uses the login.keychain here. Possible workaround is to set the cert keychain using an environment variable.

If you confirm this issue I can work on a PR.
##### Complete output when running fastlane, including the stack trace and command used

```
11:39:29 +-----------------------+---------------------------------------+
11:39:29 |                    [32mSummary for match 0.8.0[0m                    |
11:39:29 +-----------------------+---------------------------------------+
11:39:29 | git_branch            | xxx                    |
11:39:29 | app_identifier        | xxx             |
11:39:29 | force_for_new_devices | true                                  |
11:39:29 | username              | xxx                    |
11:39:29 | verbose               | true                                  |
11:39:29 | type                  | appstore                              |
11:39:29 | git_url               | xxx |
11:39:29 | keychain_name         | buildserver.keychain                  |
11:39:29 | readonly              | false                                 |
11:39:29 | force                 | false                                 |
11:39:29 | shallow_clone         | false                                 |
11:39:29 | skip_docs             | false                                 |
11:39:29 +-----------------------+---------------------------------------+
11:39:29 
11:39:29 INFO [2016-10-04 11:39:29.48]: Cloning remote git repo...
11:39:29 INFO [2016-10-04 11:39:29.48]: [4m[36m$ GIT_TERMINAL_PROMPT=0 git clone 'xxx' '/var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv'[0m[0m
11:39:29 INFO [2016-10-04 11:39:29.49]: ▸ [35mCloning into '/var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv'...[0m
11:39:30 INFO [2016-10-04 11:39:30.66]: ▸ [35mremote: Counting objects: 253, done.[0m
11:39:30 INFO [2016-10-04 11:39:30.74]: ▸ [35mremote: Compressing objects: 100% (66/66), done.[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mremote: Total 253 (delta 6), reused 0 (delta 0), pack-reused 178[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mReceiving objects: 100% (253/253), 935.46 KiB | 0 bytes/s, done.[0m
11:39:31 INFO [2016-10-04 11:39:31.26]: ▸ [35mResolving deltas: 100% (27/27), done.[0m
11:39:31 INFO [2016-10-04 11:39:31.36]: ▸ [35mChecking connectivity... done.[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: [4m[36m$ git branch --list origin/xxx --no-color -r[0m[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: ▸ [35morigin/xxx[0m
11:39:31 INFO [2016-10-04 11:39:31.37]: Checking out branch xxx...
11:39:31 INFO [2016-10-04 11:39:31.37]: [4m[36m$ git checkout xxx[0m[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: ▸ [35mBranch xxx set up to track remote branch xxx from origin.[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: ▸ [35mSwitched to a new branch 'xxx'[0m
11:39:31 INFO [2016-10-04 11:39:31.39]: [32m🔓  Successfully decrypted certificates repo[0m
11:39:31 INFO [2016-10-04 11:39:31.42]: Verifying that the certificate and profile are still valid on the Dev Portal...
11:39:33 WARN [2016-10-04 11:39:33.60]: [33mCouldn't find a valid code signing identity in the git repo for distribution... creating one for you now[0m
11:39:33 
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 |                         [32mSummary for cert 1.4.2[0m                         |
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 | development   | false                                                  |
11:39:33 | force         | true                                                   |
11:39:33 | username      | xxx                                     |
11:39:33 | keychain_path | /Users/Shared/Jenkins/Library/Keychains/login.keychain |
11:39:33 +---------------+--------------------------------------------------------+
11:39:33 
11:39:33 INFO [2016-10-04 11:39:33.66]: Starting login with user 'xxx'
11:39:35 INFO [2016-10-04 11:39:35.17]: Successfully logged in
11:39:38 INFO [2016-10-04 11:39:38.58]: [4m[36m$ security import /var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv/certs/distribution/2CLZY584MR.p12 -k '/Users/Shared/Jenkins/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security[0m[0m
11:39:38 security: SecKeychainItemImport: User interaction is not allowed.
11:39:38 INFO [2016-10-04 11:39:38.63]: [4m[36m$ security import /var/folders/t1/lycltk3d5xv8lkmsqcwfr_9m00007x/T/d20161004-16740-dhmqrv/certs/distribution/2CLZY584MR.cer -k '/Users/Shared/Jenkins/Library/Keychains/login.keychain' -T /usr/bin/codesign -T /usr/bin/security[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: ▸ [35m1 certificate imported.[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: [32mSuccessfully generated 2CLZY584MR which was imported to the local machine.[0m
11:39:38 INFO [2016-10-04 11:39:38.72]: [4m[36m$ security list-keychains -d user[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: ▸ [35m    "/Users/Shared/Jenkins/Library/Keychains/buildserver.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: ▸ [35m    "/Users/Shared/Jenkins/Library/Keychains/login.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.73]: [4m[36m$ security find-certificate -c 'Apple Worldwide Developer Relations Certification Authority' /Users/Shared/Jenkins/Library/Keychains/buildserver.keychain[0m[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mkeychain: "/Users/Shared/Jenkins/Library/Keychains/buildserver.keychain"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mversion: 256[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mclass: 0x80001000 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35mattributes:[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "alis"<blob>="Apple Worldwide Developer Relations Certification Authority"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "cenc"<uint32>=0x00000003 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "ctyp"<uint32>=0x00000001 [0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "hpky"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "issu"<blob>=0x3062310B300906035504061302555331133011060355040A130A4150504C4520494E432E31263024060355040B131D4150504C452043455254494649434154494F4E20415554484F52495459311630140603550403130D4150504C4520524F4F54204341  "0b1\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\023\012APPLE INC.1&0$\006\003U\004\013\023\035APPLE CERTIFICATION AUTHORITY1\0260\024\006\003U\004\003\023\015APPLE ROOT CA"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "labl"<blob>="Apple Worldwide Developer Relations Certification Authority"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "skid"<blob>=0x88271709A9B618608BECEBBAF64759C55254A3B7  "\210'\027\011\251\266\030`\213\354\353\272\366GY\305RT\243\267"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "snbr"<blob>=0x01DEBCC4396DA010  "\001\336\274\3049m\240\020"[0m
11:39:38 INFO [2016-10-04 11:39:38.79]: ▸ [35m    "subj"<blob>=0x308196310B300906035504061302555331133011060355040A0C0A4170706C6520496E632E312C302A060355040B0C234170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E733144304206035504030C3B4170706C6520576F726C647769646520446576656C6F7065722052656C6174696F6E732043657274696669636174696F6E20417574686F72697479  "0\201\2261\0130\011\006\003U\004\006\023\002US1\0230\021\006\003U\004\012\014\012Apple Inc.1,0*\006\003U\004\013\014#Apple Worldwide Developer Relations1D0B\006\003U\004\003\014;Apple Worldwide Developer Relations Certification Authority"[0m
11:39:39 INFO [2016-10-04 11:39:39.18]: Verifying the certificate is properly installed locally...
11:39:39 INFO [2016-10-04 11:39:39.18]: [32m🔒  Successfully encrypted certificates repo[0m
11:39:39 
11:39:39 Looking for related GitHub issues on fastlane/fastlane...
11:39:39 Search query: Could not find the newly generated certificate installed
11:39:39 
11:39:39 URL: https://api.github.com/search/issues?q=Could%20not%20find%20the%20newly%20generated%20certificate%20installed+repo:fastlane/fastlane
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3098 [[32mclosed[0m] 0 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3099 [[32mclosed[0m] 3 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 ➡️  [33mCould not find the newly generated certificate installed[0m
11:39:39    https://github.com/fastlane/fastlane/issues/3419 [[32mclosed[0m] 24 💬
11:39:39    2 weeks ago
11:39:39 
11:39:39 and 10 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20find%20the%20newly%20generated%20certificate%20installed&type=Issues&utf8=✓
11:39:39 /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [31m[!] Could not find the newly generated certificate installed[0m (FastlaneCore::Interface::FastlaneError)
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/cert-1.4.2/lib/cert/runner.rb:10:in `launch'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/generator.rb:19:in `generate_certificate'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/runner.rb:55:in `fetch_certificate'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/runner.rb:17:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:119:in `run'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/lib/match/commands_generator.rb:12:in `start'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/match-0.8.0/bin/match:6:in `<top (required)>'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/bin/match:22:in `load'
11:39:39    from /Users/Shared/Jenkins/.rbenv/versions/2.3.1/bin/match:22:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Did not run in a Fastfile but from the command line.

```
match appstore --git_branch xxx -a xy -u username --force_for_new_devices --verbose
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

### PR DESCRIPTION
**Pull request by iCarambaa**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:
- [ x] Run `rspec` for all tools you modified
- [ x] Run `rubocop -a` to ensure the code style is valid
- [ x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

This fixes #6375 . Match looks up the keychain path by its name and passes it to cert. "== 0" has been replaced with ".zero?" by rubocop.

### CODE REVIEW

File: match/lib/match/generator.rb [hunk 1]
```diff
@@ -10,7 +10,8 @@ def self.generate_certificate(params, cert_type)
         output_path: output_path,
         force: true, # we don't need a certificate without its private key, we only care about a new certificate
         username: params[:username],
-        team_id: params[:team_id]
+        team_id: params[:team_id],
+  keychain_path: Utils.keychain_path(params[:keychain_name])
```
Comment (KrauseFx) [inline match/lib/match/generator.rb]: This seems to be wrongly formatted, can you run `bundle exec rubocop -a`

File: match/lib/match/nuke.rb [hunk 2]
```diff
@@ -10,7 +10,6 @@ class Nuke
     def run(params, type: nil)
       self.params = params
       self.type = type
-
```
Comment (KrauseFx) [inline match/lib/match/nuke.rb]: Why?

File: match/lib/match/nuke.rb [hunk 3]
```diff
@@ -125,7 +124,7 @@ def nuke_it_now!
         UI.success "Successfully deleted profile"
       end
 
-      UI.header "Revoking #{self.certs.count} certificates..." unless self.certs.count == 0
+      UI.header "Revoking #{self.certs.count} certificates..." unless self.certs.count.zero?
```
Comment (KrauseFx) [inline match/lib/match/nuke.rb]: I'd prefer not to have this changed. I assume you're running either the wrong rubocop version, or run it in the wrong directory

File: match/lib/match/version.rb [hunk 4]
```diff
@@ -1,4 +1,4 @@
 module Match
-  VERSION = "0.8.1"
+  VERSION = "0.8.2"
```
Comment (KrauseFx) [inline match/lib/match/version.rb]: Please don't do a version bump

File: match/lib/match/utils.rb [hunk 5]
```diff
@@ -1,6 +1,17 @@
 module Match
   class Utils
     def self.import(item_path, keychain)
+      keychain_path = self.keychain_path(keychain)
```
Comment (KrauseFx) [inline match/lib/match/utils.rb]: Why is there so many changes necessary?

**Review by KrauseFx — DISMISSED** [review]

File: match/lib/match/utils.rb (hunk 5 above)
Comment (iCarambaa) [inline match/lib/match/utils.rb]: I refactored the code for finding the path to a keychain in its own method. That method is needed in generator.rb to find the keychain path for cert.

**Comment by iCarambaa** [comment]
I made the changes and rebased on master

**Comment by milch** [comment]
@iCarambaa sorry for the delay, merge conflicts have now been introduced in the meantime. We'd appreciate it if you could fix this PR for the most recent `match` version, then we could merge!

**Comment by iCarambaa** [comment]
I did rebase onto master. As the import is now in FastlaneCore it might a good idea to add the path resolving to the core as well, what do you think?

I get three failing tests on my local machine for this PR  *and* the current master which I don't get on CI. Want to mention them:

```
Failures:

  1) Match Match::Utils import tries to find the macOS Sierra keychain too
     Failure/Error: Match::Utils.import('item.path', "login.keychain")
       FastlaneCore::Helper received :backticks with unexpected arguments
         expected: ("security import item.path -k '/Users/sven/Library/Keychains/login.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security &> /dev/null", {:print=>nil})
              got: ("security set-key-partition-list -S apple-tool:,apple: -k \"\" /Users/sven/Library/Keychains/login.keychain-db &> /dev/null", {:print=>nil})
     # ./lib/match/utils.rb:27:in `import'
     # ./spec/utils_spec.rb:47:in `block (4 levels) in <top (required)>'

  2) Match Match::Utils import treats a keychain name it cannot find in ~/Library/Keychains as the full keychain path
     Failure/Error: Match::Utils.import('item.path', '/my/special.keychain')
       FastlaneCore::Helper received :backticks with unexpected arguments
         expected: ("security import item.path -k '/my/special.keychain' -P '' -T /usr/bin/codesign -T /usr/bin/security &> /dev/null", {:print=>nil})
              got: ("security set-key-partition-list -S apple-tool:,apple: -k \"\" /my/special.keychain &> /dev/null", {:print=>nil})
     # ./lib/match/utils.rb:27:in `import'
     # ./spec/utils_spec.rb:24:in `block (4 levels) in <top (required)>'

  3) Match Match::Utils import finds a normal keychain name relative to ~/Library/Keychains
     Failure/Error: Match::Utils.import('item.path', 'login.keychain')
       FastlaneCore::Helper received :backticks with unexpected arguments
         expected: ("security import item.path -k '/Users/sven/Library/Keychains/login.keychain' -P '' -T /usr/bin/codesign -T /usr/bin/security &> /dev/null", {:print=>nil})
              got: ("security set-key-partition-list -S apple-tool:,apple: -k \"\" /Users/sven/Library/Keychains/login.keychain &> /dev/null", {:print=>nil})
     # ./lib/match/utils.rb:27:in `import'
     # ./spec/utils_spec.rb:11:in `block (4 levels) in <top (required)>'

Finished in 0.26121 seconds (files took 0.73333 seconds to load)
21 examples, 3 failures
```

I'm on macOS Sierra 10.12.1 (16B2657), I ran `bundle exec rspec`in `fastlane/match`.

**Comment by milch** [comment]
> As the import is now in FastlaneCore it might a good idea to add the path resolving to the core as well, what do you think?

I'm not sure, I don't think we really need it anywhere else except for in match. If it turns out we need this more often we can always refactor this later. 

> I get three failing tests on my local machine for this PR and the current master which I don't get on CI. 

Ah, that's because of this change I made: https://github.com/fastlane/fastlane/pull/6932/files#diff-aa5bcaeef6b9ba34d824c0e145e9b254R16. 

If you add something like `expect(FastlaneCore::Helper).to receive(:backticks).with("security set-key-partition-list -S apple-tool:,apple: -k \"\" #{keychain_path} &> /dev/null", print: $verbose)` to the tests they should be runnable again.

**Comment by milch** [comment]
@iCarambaa So the tests have now been fixed in #7069, if you could rebase to master that'd be awesome!

**Comment by iCarambaa** [comment]
@milch done 😊

**Comment by milch** [comment]
@iCarambaa Awesome, thanks! And thanks again for your contribution! 🚀

**Review by milch — COMMENTED** [review]
🐐

**Review by milch — APPROVED** [review]
💯

**Comment by iCarambaa** [comment]
Hi @milch, I just noticed that these test that have been fixed are different ones than the ones that are failing here (although they look quite similar). #7069 fixed the tests in `fastlane/spec/actions_specs/import_certificate_spec.rb` but here are the tests in `fastlane/match/spec/utils.spec` failing.

Should I prepare a new PR?

**Comment by milch** [comment]
@iCarambaa That'd be amazing, thanks!

**Comment by iCarambaa** [comment]
@milch I fixed them the same way as in #7069.
