### PR TITLE
[spaceship] migrate YAML.safe_load to support psych v4.0

### LINKED ISSUE #18768: psych v4.0 to break FASTLANE_SESSION functionality
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Creating a fastlane session or downloading dsysm with valid FASTLANE_SESSION is not possible anymore. This is only valid for ruby 2.7.x. It seems to work with Ruby 3.0.1 (at least generating FASTLANE_SESSION)
##### Command executed

I've upgraded all my gems and since then it doesn't work. I believe it has something to do with dependencies.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [14:03:07]: Login to App Store Connect (*****)
Tried to load unspecified class: HTTP::Cookie
Continuing with normal login.
Error loading session from environment
Make sure to pass the session in a valid format
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios dsym_upload |
+------------------+-----------------+
[14:03:07]: Tried to load unspecified class: HTTP::Cookie
+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | Verifying fastlane version | 0           |
| 2    | default_platform           | 0           |
| 3    | app_store_connect_api_key  | 0           |
| 4    | cocoapods                  | 10          |
| 💥   | download_dsyms             | 0           |
+------+----------------------------+-------------+
[14:03:07]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
➡️  Precheck - Unspecified error
    https://github.com/fastlane/fastlane/issues/17150 [closed] 2 💬
    09 Nov 2020
➡️  [Issue] Tried to load unspecified class: HTTP::Cookie when running fastlane spaceauth -u
    https://github.com/fastlane/fastlane/issues/8011 [closed] 4 💬
    26 Apr 2017
🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': \e[31m[!] Tried to load unspecified class: HTTP::Cookie\e[0m (Psych::DisallowedClass)
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:334:in `safe_load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:369:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:609:in `load_session_from_env'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:441:in `send_shared_login_request'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:808:in `do_login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:393:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
	from /Users/r2d2/.rbenv/versions/2.7.0/bin/fastlane:23:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/bin/fastlane:23:in `<main>'
/Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: HTTP::Cookie (Psych::DisallowedClass)
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/class_loader.rb:28:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `block in register_empty'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `each'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:338:in `register_empty'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:146:in `visit_Psych_Nodes_Sequence'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:334:in `safe_load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/psych-4.0.0/lib/psych.rb:369:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:609:in `load_session_from_env'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:441:in `send_shared_login_request'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/tunes/tunes_client.rb:127:in `send_login_request'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:808:in `do_login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:393:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/client.rb:355:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/tunes/spaceship.rb:24:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/client.rb:56:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/spaceship/lib/spaceship/connect_api/spaceship.rb:85:in `login'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/download_dsyms.rb:18:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	from /Users/r2d2/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/fastlane-2.184.0/bin/fastlane:23:in `<top (required)>'
	from /Users/r2d2/.rbenv/versions/2.7.0/bin/fastlane:23:in `load'
	from /Users/r2d2/.rbenv/versions/2.7.0/bin/fastlane:23:in `<main>'</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.3.1                                      |
| Ruby                        | 2.7.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.7.0/bin/fastlane        |
| Host                        | macOS 11.3.1 (20E241)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.0/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1j  16 Feb 2021                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.184.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.5.0        |
| atomos                          | 0.1.3        |
| CFPropertyList                  | 3.0.3        |
| claide                          | 1.0.3        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.81.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.1.0        |
| ruby2_keywords                  | 0.0.4        |
| faraday                         | 1.4.2        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.3        |
| gh_inspector                    | 1.1.3        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| jwt                             | 2.2.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.1        |
| representable                   | 3.1.1        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.0        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| memoist                         | 0.16.2       |
| os                              | 1.1.1        |
| googleauth                      | 0.16.2       |
| httpclient                      | 2.8.3        |
| google-apis-core                | 0.3.0        |
| google-apis-playcustomapp_v1    | 0.3.0        |
| google-apis-androidpublisher_v3 | 0.4.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.4.0        |
| google-apis-storage_v1          | 0.4.0        |
| rake                            | 13.0.3       |
| digest-crc                      | 0.6.3        |
| google-cloud-storage            | 1.31.1       |
| emoji_regex                     | 3.2.2        |
| jmespath                        | 1.4.0        |
| aws-partitions                  | 1.463.0      |
| aws-eventstream                 | 1.1.1        |
| aws-sigv4                       | 1.2.3        |
| aws-sdk-core                    | 3.114.0      |
| aws-sdk-kms                     | 1.43.0       |
| aws-sdk-s3                      | 1.95.1       |
| uri                             | 0.10.1       |
| json                            | 2.5.1        |
| bundler                         | 2.2.18       |
| rexml                           | 3.2.5        |
| webrick                         | 1.7.0        |
| forwardable                     | 1.3.2        |
| logger                          | 1.4.3        |
| cgi                             | 0.2.0        |
| date                            | 3.1.1        |
| timeout                         | 0.1.1        |
| stringio                        | 3.0.0        |
| openssl                         | 2.2.0        |
| ipaddr                          | 1.2.2        |
| zlib                            | 1.1.0        |
| connection_pool                 | 2.2.5        |
| net-http-persistent             | 4.0.1        |
| ostruct                         | 0.3.3        |
| strscan                         | 3.0.0        |
| io-console                      | 0.5.9        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.5.0        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| yaml                            | 0.1.1        |
| psych                           | 4.0.0        |
| mutex_m                         | 0.1.1        |
</details>

*generated on:* **2021-05-28**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by ainame**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Closes https://github.com/fastlane/fastlane/issues/18768
https://github.com/fastlane/fastlane/issues/17931#issuecomment-855254278

`psych` v4.0.0 was released lately and it has a breaking change that breaks fastlane in two ways. One is to break `http-cookie` gem, another is by removing legacy positional parameters used in `spaceauth_runner.rb`.

JFYI: `psych` is a backend implementation of YAML used by default in Ruby. `psych` gem is categorised as "default" gem which means it's bundled in Ruby but you can update it to whatever version you want optionally. Ruby 3.0.1 bundles `psych` v3.3.0 but on the master branch of `ruby/ruby` it now points to v4.0.1, which means that it is very likely fastlane users using the next Ruby version (Ruby 3.1.0) are going to see errors due to `psych` v4.0.1.

* Ruby 3.0.1 https://github.com/ruby/ruby/blob/0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0/ext/psych/lib/psych/versions.rb#L5
* Ruby head  https://github.com/ruby/ruby/blob/8c87efaa8a45166ed977294330c32a4b186b8e7b/ext/psych/lib/psych/versions.rb#L5

Thanks to this ticket https://github.com/fastlane/fastlane/issues/18768, `http-cookie` is now fixed. This PR migrates `spaceauth_runner.rb` using the legacy positional parameters on `YAML.safe_load` which are removed in `psych` v4.0.0.

### Description

It is a bit tricky that we need to maintain legacy positional parameters to keep Ruby 2.5 support. Otherwise, it is very straightforward.

v4.0.1 (bundled in Ruby head) https://github.com/ruby/psych/blob/v4.0.1/lib/psych.rb#L323
It's cleaned up. It no longer contains positional arguments for options.

```ruby
  def self.safe_load yaml, permitted_classes: [], permitted_symbols: [], aliases: false, filename: nil, fallback: nil, symbolize_names: false, freeze: false<br class="Apple-interchange-newline">
```

v3.3.0 (bundled in Ruby 3.0.1) https://github.com/ruby/psych/blob/v3.3.0/lib/psych.rb#L329
There are positional parameters named as `legacy` to keep compatibility. 
```ruby
  def self.safe_load yaml, legacy_permitted_classes = NOT_GIVEN, legacy_permitted_symbols = NOT_GIVEN, legacy_aliases = NOT_GIVEN, legacy_filename = NOT_GIVEN, permitted_classes: [], permitted_symbols: [], aliases: false, filename: nil, fallback: nil, symbolize_names: false, freeze: false<br class="Apple-interchange-newline">
```

v3.0.2 (bundled in Ruby 2.5.0) https://github.com/ruby/psych/blob/v3.0.2/lib/psych.rb#L313
There is not keyword arguments for options yet.

```ruby
  def self.safe_load yaml, whitelist_classes = [], whitelist_symbols = [], aliases = false, filename = nil, symbolize_names: false<br class="Apple-interchange-newline">
```

### Testing Steps

I believe unit tests cover this change but you can give `spaceauth` a try to see if serialised cookie object is restored from yaml file.

### CODE REVIEW

File: spaceship/lib/spaceship/spaceauth_runner.rb [hunk 1]
```diff
@@ -72,6 +67,24 @@ def run
       return self
     end
 
+    def load_cookies(content)
+      # When Ruby 2.5 support is dropped, we can safely get rid of the latter branch.
+      if YAML.name == 'Psych' && Gem::Version.new(Psych::VERSION) >= Gem::Version.new('3.1')
```
Comment (ainame) [inline spaceship/lib/spaceship/spaceauth_runner.rb:72]: The idea comes from https://github.com/sparklemotion/http-cookie/pull/34/files#diff-1ca99fa7d530d27cd9c91bc6cf9e1eb5da1171af6bd1dd194349de4f6f5c994cR77

Comment (minuscorp) [reply spaceship/lib/spaceship/spaceauth_runner.rb:72]: Maybe we can include it in the code as a comment as a reference?

**Review by minuscorp — APPROVED** [review]
🚀

File: spaceship/lib/spaceship/spaceauth_runner.rb (hunk 1 above)
Comment (ainame) [reply spaceship/lib/spaceship/spaceauth_runner.rb:72]: Hmm not really? There's no explanation for this logic there. I can add another comment on what this comparison means if you want?

Comment (minuscorp) [reply spaceship/lib/spaceship/spaceauth_runner.rb:72]: I've read the diff to understand the reasoning with Psych lib etc but I leave it to your criteria😁

**Review by joshdholtz — APPROVED** [review]
👏  Thank you for finding and fixing this! You are the 3.0 hero ❤️
