### PR TITLE
[gym] Fix analyze_build_time setting interfering with xcpretty log generation

### LINKED ISSUE #10187: `analyze_build_time` option causes sh: inherited: command not found, blocks xcpretty
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Trying to use the `analyze_build_time` option in `gym` results in:
`
set -o pipefail && xcodebuild -workspace <redacted> OTHER_SWIFT_FLAGS="$(inherited) -Xfrontend -debug-time-function-bodies" archive | tee <redacted> | grep .[0-9]ms | grep -v ^0.[0-9]ms | sort -nr > culprits.txt | xcpretty
`
`
[09:32:06]: ▸ sh: inherited: command not found
`
... with no xcpretty output.  Looks to me that the above command is not formatted properly...in particular the redirect to `culprits.txt` precedes `xcpretty` which looks wrong.  

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.54.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.4       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.3       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-08-29**
</details>

### PR DESCRIPTION
**Pull request by allewun**
Fixes #10187

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

`gym`'s `analyze_build_time` option interferes with its own `xcpretty` output, since the analysis steps are incorrectly inserted between the `xcodebuild` and `xcpretty` pipelines and it improperly consumes output that should be piped to `xcpretty`. Processes that depend on `xcpretty` will thus fail (e.g. the json-compilation-database isn't generated when `analyze_build_time` is on).

### Description

I moved the `analyze_build_time` steps to a `post_build` step that waits until the main `xcodebuild ... | xcpretty` command has finished. It seems more fitting that any build analysis should happen _after_ building has completed, not during the build process.

### CODE REVIEW

File: gym/lib/gym/generators/build_command_generator.rb [hunk 1]
```diff
@@ -46,26 +46,25 @@ def options
         options
       end
 
-      def actions
+      def buildactions
```
Comment (allewun) [inline gym/lib/gym/generators/build_command_generator.rb]: renamed to match more closely with `xcodebuild`'s own [documentation](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html):

```
buildaction ...
           Specify a build action (or actions) to perform on the target. Available build actions are:
```

**Comment by allewun** [comment]
Ha, I just saw #12523 which tackles the same bug. Please close this PR if needed.

File: gym/lib/gym/runner.rb [hunk 2]
```diff
@@ -100,6 +100,20 @@ def build_app
       mark_archive_as_built_by_gym(BuildCommandGenerator.archive_path)
       UI.success("Successfully stored the archive. You can find it in the Xcode Organizer.") unless Gym.config[:archive_path].nil?
       UI.verbose("Stored the archive in: " + BuildCommandGenerator.archive_path)
+
+      post_build_app
```
[the remark this answers is not in the document]
Comment (joshdholtz) [reply gym/lib/gym/runner.rb]: This seems like a good enough place to me 😊

File: gym/spec/build_command_generator_spec.rb [hunk 3]
```diff
@@ -213,10 +215,35 @@
                                "-archivePath #{Gym::BuildCommandGenerator.archive_path.shellescape}",
                                "OTHER_SWIFT_FLAGS=\"-Xfrontend -debug-time-function-bodies\"",
                                :archive,
-                               "| tee #{log_path.shellescape}",
-                               "| grep .[0-9]ms | grep -v ^0.[0-9]ms | sort -nr > culprits.txt",
+                               "| tee #{@log_path.shellescape}",
+                               "| xcpretty"
```
Comment (joshdholtz) [inline gym/spec/build_command_generator_spec.rb]: I think this is a duplicate since `xcpretty` gets added here - https://github.com/fastlane/fastlane/pull/12527/files?utf8=✓&diff=unified#diff-440c4122de8c51769dc40db14188f030R70... right? 🤔

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Duplicate `xcpretty`?

File: gym/spec/build_command_generator_spec.rb (hunk 3 above)
Comment (allewun) [reply gym/spec/build_command_generator_spec.rb]: I think the git diff is misleading here. The `| xcpretty` command is part of the `pipe` method, which does indeed manifest in the [`BuildCommandGenerator.generate`](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L14) output that this test is testing.

I added another test case, which pushed the old `xcpretty` [down a few lines](https://github.com/fastlane/fastlane/pull/12527/files?utf8=%E2%9C%93&diff=unified#diff-8f4a50ba33f7e4e77a65a6a50db78273L218).

Comment (joshdholtz) [reply gym/spec/build_command_generator_spec.rb]: My bad, that was in a spec 😝 You good 👍

File: gym/lib/gym/runner.rb [hunk 4]
```diff
@@ -100,6 +100,20 @@ def build_app
...
+    end
+
+    # Post-processing of build_app
+    def post_build_app
+      command = BuildCommandGenerator.post_build
+      print_command(command, "Generated Post-Build Command") if FastlaneCore::Globals.verbose?
```
Comment (joshdholtz) [inline gym/lib/gym/runner.rb]: @allewun I _did_ just catch one bug there 😊 Things go 💥 if the `command` array here is empty since... Putting an `unless command.empty?` around this fixed it for me... Do you have this same issue?

**Review by joshdholtz — CHANGES_REQUESTED** [review]

File: gym/lib/gym/runner.rb (hunk 4 above)
Comment (allewun) [reply gym/lib/gym/runner.rb]: Nice catch! I added a guard here.

**Comment by allewun** [comment]
@joshdholtz should be good to go, let me know if there's anything missing!

**Review by joshdholtz — APPROVED** [review]
This looks fantastic! Thanks for making this change 😊
