### PR TITLE
[match][change_password] re-encrypt using new password instead of MATCH_PASSWORD env var

### LINKED ISSUE #15942: match change_password re-encrypts with MATCH_PASSWORD instead of new password
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When using `fastlane match change_password` if you have `MATCH_PASSWORD` set as an environmental variable, it will overwrite the "new password" you are trying to set, and re-encrypt everything to the old password.

Workaround:

`unset MATCH_PASSWORD` before running `bundle exec match change_password`

### LINKED ISSUE #17909: Changing Match PWD didn't work
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I run `fastlane  match change_password` I get asked for the new passphrase but in the end I get an error message and the passphrase hasn't been changed.

##### Command executed
`bundle exec fastlane  match change_password`

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
[✔] 🚀
[12:40:54]: In the config file './fastlane/Deliverfile' you have the line app_identifier, but didn't provide any value. Make sure to append a value right after the option name. Make sure to check the docs for more information
[12:40:54]: Successfully loaded '........./fastlane/Matchfile' 📄

+---------+---------------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+---------+---------------------------------------------+
| git_url | <repo url> |
+---------+---------------------------------------------+

[12:40:54]: New passphrase for Git Repo: ****************************************************************
[12:41:02]: Type passphrase again: ****************************************************************
[12:41:03]: Cloning remote git repo...
[12:41:03]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:41:07]: Checking out branch master...
[12:41:07]: 🔓  Successfully decrypted certificates repo
keychain: "~/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@github.<our_codesigning-repo>.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303231303130363131333131365A00  "20210106113116Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303231303130363131333131365A00  "20210106113116Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@github.com:dbdrive/ios-code-signing.git"
    "type"<uint32>=<NULL>
password has been deleted.
[12:41:07]: 🔒  Successfully encrypted certificates repo

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
 </pre>
</details>

### Environment

<details>
  <pre> 
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 11.1                                                           |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.29.2                                             |
| Installation Source         | ~/.gem/bin/fastlane                                            |
| Host                        | macOS 11.1 (20C69)                                             |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 12.3                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
redacted for privacy reasons...
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.171.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.15.0  | ✅ Up-To-Date  |
| fastlane-plugin-act       | 1.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.2.4        |
| rake                      | 13.0.3       |
| CFPropertyList            | 3.0.3        |
| concurrent-ruby           | 1.1.7        |
| i18n                      | 1.8.7        |
| minitest                  | 5.14.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.9        |
| activesupport             | 5.2.4.4      |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| httpclient                | 2.8.3        |
| json                      | 2.5.1        |
| algoliasearch             | 1.27.5       |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.414.0      |
| aws-sigv4                 | 1.2.2        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.110.0      |
| aws-sdk-kms               | 1.40.0       |
| aws-sdk-s3                | 1.87.0       |
| babosa                    | 1.0.4        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| netrc                     | 0.11.0       |
| ffi                       | 1.14.2       |
| ethon                     | 0.12.0       |
| typhoeus                  | 1.4.0        |
| cocoapods-core            | 1.10.0       |
| cocoapods-deintegrate     | 1.0.4        |
| cocoapods-downloader      | 1.4.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-trunk           | 1.5.0        |
| cocoapods-try             | 1.2.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.3.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.4.0        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| cocoapods                 | 1.10.0       |
| coderay                   | 1.1.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| faraday-net_http          | 1.0.0        |
| multipart-post            | 2.0.0        |
| ruby2_keywords            | 0.0.2        |
| faraday                   | 1.3.0        |
| faraday-http-cache        | 2.2.0        |
| rchardet                  | 1.8.0        |
| git                       | 1.8.1        |
| rexml                     | 3.2.4        |
| kramdown                  | 2.3.0        |
| kramdown-parser-gfm       | 1.1.0        |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.2        |
| octokit                   | 4.20.0       |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| danger                    | 8.2.1        |
| danger-plugin-api         | 1.0.0        |
| danger-changelog          | 0.6.1        |
| danger-commit_lint        | 0.0.7        |
| thor                      | 0.20.3       |
| danger-swiftlint          | 0.24.5       |
| dotenv                    | 2.7.6        |
| emoji_regex               | 3.2.1        |
| excon                     | 0.78.1       |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.1        |
| jwt                       | 2.2.2        |
| memoist                   | 0.16.2       |
| multi_json                | 1.15.0       |
| os                        | 1.1.1        |
| signet                    | 0.14.0       |
| googleauth                | 0.14.0       |
| mini_mime                 | 1.0.2        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| digest-crc                | 0.6.3        |
| google-cloud-env          | 1.4.0        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.29.2       |
| mini_magick               | 4.11.0       |
| plist                     | 3.6.0        |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.1        |
| xcresult                  | 0.2.1        |
| xcov                      | 1.7.5        |
| danger-xcov               | 0.5.0        |
| fastlane-plugin-act       | 1.2.1        |
| fastlane-plugin-changelog | 0.15.0       |
| method_source             | 1.0.0        |
| pry                       | 0.13.1       |
</details>

*generated on:* **2021-01-06**
</details>
</pre>
</details>

### LINKED ISSUE #17968: change_password does not work
The change_password functionality is still broken as per the details on: https://github.com/fastlane/fastlane/issues/15942

I believe that having a `.env.default` file also breaks things similar to having a `MATCH_PASSWORD` environment variable present.

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #15942
Resolves #17968
Resolves #17909

### Description

`encrypt_files` was being called without informing the new password as an argument. As a result, it would invoke `fetch_password` which reads the password from the env var. Worst case scenario, if the env var is not set, it either asks the user for the password again (if interactive) or crashes.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan/fix-change-password-new-password"
```

And run `bundle install` to apply the changes.

The test scenario is: call `change_password` with an env var `MATCH_PASSWORD` set. After re-encrypting the files, check if the encrypted files can be decrypted using the password you provided in `change_password`

### CODE REVIEW

**Comment by mdentremont** [comment]
Thanks @rogerluan -- unfortunately I've since recreated the repository, and also no longer have access to the machine where we were seeing this issue.

That being said, I looked at the diff and that would seem to solve the issue that I was running into 👍

**Comment by rogerluan** [comment]
Thanks for getting back to this @mdentremont 🤗 and for the code review! 💪 

@stherold was able to confirm this solved his problem specifically (which symptoms were a bit different than the OP, but had the same root cause) - https://github.com/fastlane/fastlane/issues/17909#issuecomment-800123103

File: match/spec/encryption/openssl_spec.rb [hunk 1]
```diff
@@ -40,5 +40,23 @@
         @e.encrypt_files
       end.to raise_error("No password supplied")
     end
+
+    it "doesn't raise an exception if no env var is supplied but custom password is" do
+      ENV["MATCH_PASSWORD"] = ""
```
Comment (joshdholtz) [inline match/spec/encryption/openssl_spec.rb:45]: This will prevent the `ENV` value from carrying over between tests

```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => "" }
```

File: match/spec/encryption/openssl_spec.rb [hunk 2]
```diff
@@ -40,5 +40,23 @@
...
+      expect do
+        @e.encrypt_files(password: "some custom password")
+      end.to_not(raise_error)
+    end
+
+    it "given a custom password argument, then it should be given precedence when encrypting file, even when MATCH_PASSWORD is set" do
+      ENV["MATCH_PASSWORD"] = "something else"
```
Comment (joshdholtz) [inline match/spec/encryption/openssl_spec.rb:52]:
```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => "something else"}
```

File: match/spec/encryption/openssl_spec.rb [hunk 3]
```diff
@@ -40,5 +40,23 @@
...
+      new_password = '2"QAHg@v(Qp{=*n^'
+      @e.encrypt_files(password: new_password)
+      expect(File.binread(@full_path)).to_not(eq(@content))
+
+      ENV["MATCH_PASSWORD"] = new_password
```
Comment (joshdholtz) [inline match/spec/encryption/openssl_spec.rb:57]:
```suggestion
      stub_const('ENV', { "MATCH_PASSWORD" => new_password}
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
This change looks great! Thanks for fixing ❤️ Just a few small changes in the tests 😇

**Comment by rogerluan** [comment]
Thanks for the tip @joshdholtz ! Updated all the env vars in this file 😊

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
This is 💯 now! Thank you so much going for fixing this ❤️
