### PR TITLE
Rubocop fixes and update

### LINKED ISSUE #8958: rubocop violations when using fastlane new_plugin
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

A new plugin generated using `fastlane new_plugin` does not pass rubocop without modifying .rubocop.yml.

- It wants the Fastlane-generated gemspec to be snake case (fastlane_plugin_my_new_action.gemspec).
- It doesn't like the use of `%q{}` in the Fastlane-generated action.
- It wants an empty line after magic comments (`# coding: utf-8`)

I've also seen complaints from the Eval Cop (eval is a security risk) because of the lines added to the Gemfile by `fastlane add_plugin`, but I didn't reproduce that just now.

It's not hard to disable these Cops in .rubocop.yml, but it would be nice if the `new_plugin` command
generated code that passed its own tests.

##### Complete output when running fastlane, including the stack trace and command used

```bash
[jdee@Jimmy-Dees-MacBookPro tmp]$ fastlane new_plugin my_new_action
[09:52:45]: 
Please enter a short summary of this fastlane plugin:
a short summary of this fastlane plugin
[09:52:56]: 
Please enter a detailed description of this fastlane plugin:
a detailed description of this fastlane plugin

Your plugin was successfully generated at fastlane-plugin-my_new_action/ 🚀

To get started with using this plugin, run

    fastlane add_plugin my_new_action

from a fastlane-enabled app project directory and provide the following as the path:

    /private/tmp/fastlane-plugin-my_new_action

[jdee@Jimmy-Dees-MacBookPro tmp]$ cd fastlane-plugin-my_new_action/
[jdee@Jimmy-Dees-MacBookPro fastlane-plugin-my_new_action]$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Resolving dependencies...
Using rake 12.0.0
Using CFPropertyList 2.3.5
Using public_suffix 2.0.5
Using ast 2.3.0
Using babosa 1.0.2
Using bundler 1.14.6
Using claide 1.0.1
Using coderay 1.1.1
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.8
Using diff-lcs 1.3
Using unf_ext 0.0.7.4
Using dotenv 2.2.0
Using excon 0.55.0
Using multipart-post 2.0.0
Using fastimage 2.1.0
Using gh_inspector 1.0.3
Using jwt 1.5.6
Using little-plugger 1.1.4
Using multi_json 1.12.1
Using memoist 0.15.0
Using os 0.9.6
Using httpclient 2.8.3
Using hurley 0.2
Using mime-types-data 3.2016.0521
Using uber 0.0.15
Using retriable 2.1.0
Using json 2.1.0
Using mini_magick 4.5.1
Using multi_xml 0.6.0
Using plist 3.2.0
Using rubyzip 1.2.1
Using security 0.1.3
Using slack-notifier 1.5.1
Using terminal-notifier 1.7.1
Using unicode-display_width 1.1.3
Using tty-screen 0.5.0
Using word_wrap 1.0.0
Using nanaimo 0.2.3
Using rouge 1.11.1
Using fastlane-plugin-my_new_action 0.1.0 from source at `.`
Using method_source 0.8.2
Using powerpack 0.1.1
Using slop 3.6.0
Using rainbow 2.2.1
Using rspec-support 3.5.0
Using ruby-progressbar 1.8.1
Using addressable 2.5.1
Using parser 2.4.0.0
Using commander-fastlane 4.4.4
Using unf 0.1.4
Installing faraday 0.12.1
Using logging 2.2.2
Using mime-types 3.1
Using representable 2.3.0
Using terminal-table 1.7.3
Using xcodeproj 1.4.4
Using xcpretty 0.2.6
Using pry 0.10.4
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using rubocop 0.48.1
Using domain_name 0.5.20170404
Using faraday_middleware 0.11.0.1
Using signet 0.7.3
Using xcpretty-travis-formatter 0.0.4
Using rspec 3.5.0
Using http-cookie 1.0.3
Using googleauth 0.5.1
Using faraday-cookie_jar 0.0.6
Using google-api-client 0.9.28
Using fastlane 2.28.2
Bundle complete! 7 Gemfile dependencies, 74 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
[jdee@Jimmy-Dees-MacBookPro fastlane-plugin-my_new_action]$ bundle exec rubocop
Inspecting 10 files
C.........

Offenses:

fastlane-plugin-my_new_action.gemspec:1:1: C: The name of this source file (fastlane-plugin-my_new_action.gemspec) should use snake_case.
# coding: utf-8
^
fastlane-plugin-my_new_action.gemspec:2:1: C: Add an empty line after magic comments.
lib = File.expand_path("../lib", __FILE__)
^
fastlane-plugin-my_new_action.gemspec:9:24: C: Use %q only for strings that contain both single quotes and double quotes.
  spec.author        = %q{Jimmy Dee}
                       ^^^^^^^^^^^^^
fastlane-plugin-my_new_action.gemspec:10:24: C: Use %q only for strings that contain both single quotes and double quotes.
  spec.email         = %q{jgvdthree@gmail.com}
                       ^^^^^^^^^^^^^^^^^^^^^^^
fastlane-plugin-my_new_action.gemspec:12:24: C: Use %q only for strings that contain both single quotes and double quotes.
  spec.summary       = %q{a short summary of this fastlane plugin}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

10 files inspected, 5 offenses detected
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.4/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.4/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test do
  my_new_action
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                        | Version | Update-Status      |
| ----------------------------- | ------- | ------------------ |
| fastlane-plugin-my_new_action | 0.1.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.0.0        |
| executable-hooks              | 1.3.2        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.4        |
| bundler                       | 1.14.6       |
| io-console                    | 0.4.5        |
| rake                          | 12.0.0       |
| CFPropertyList                | 2.3.5        |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.1        |
| ast                           | 2.3.0        |
| babosa                        | 1.0.2        |
| claide                        | 1.0.1        |
| coderay                       | 1.1.1        |
| colored                       | 1.2          |
| colored2                      | 3.1.2        |
| highline                      | 1.7.8        |
| commander-fastlane            | 4.4.4        |
| diff-lcs                      | 1.3          |
| unf_ext                       | 0.0.7.4      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20170404 |
| dotenv                        | 2.2.0        |
| excon                         | 0.55.0       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.12.1       |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.11.0.1     |
| fastimage                     | 2.1.0        |
| gh_inspector                  | 1.0.3        |
| jwt                           | 1.5.6        |
| little-plugger                | 1.1.4        |
| multi_json                    | 1.12.1       |
| logging                       | 2.2.2        |
| memoist                       | 0.15.0       |
| os                            | 0.9.6        |
| signet                        | 0.7.3        |
| googleauth                    | 0.5.1        |
| httpclient                    | 2.8.3        |
| hurley                        | 0.2          |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| uber                          | 0.0.15       |
| representable                 | 2.3.0        |
| retriable                     | 2.1.0        |
| google-api-client             | 0.9.28       |
| json                          | 2.1.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.2.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| slack-notifier                | 1.5.1        |
| terminal-notifier             | 1.7.1        |
| unicode-display_width         | 1.1.3        |
| terminal-table                | 1.7.3        |
| tty-screen                    | 0.5.0        |
| word_wrap                     | 1.0.0        |
| nanaimo                       | 0.2.3        |
| xcodeproj                     | 1.4.4        |
| rouge                         | 1.11.1       |
| xcpretty                      | 0.2.6        |
| xcpretty-travis-formatter     | 0.0.4        |
| fastlane-plugin-my_new_action | 0.1.0        |
| method_source                 | 0.8.2        |
| parser                        | 2.4.0.0      |
| powerpack                     | 0.1.1        |
| slop                          | 3.6.0        |
| pry                           | 0.10.4       |
| rainbow                       | 2.2.1        |
| rspec-support                 | 3.5.0        |
| rspec-core                    | 3.5.4        |
| rspec-expectations            | 3.5.0        |
| rspec-mocks                   | 3.5.0        |
| rspec                         | 3.5.0        |
| ruby-progressbar              | 1.8.1        |
| rubocop                       | 0.48.1       |
</details>

*generated on:* **2017-04-21**
</details>

### PR DESCRIPTION
**Pull request by jdee**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fix #8958.

`bundle exec rubocop` fails on a newly-created plugin. There are two issues:

- There were some rubocop failures because it wanted the gemspec file to be snake_case,
  and it objects to unnecessary use of `%q{}` in the template gemspec. Those have been fixed. The snake_case check was disabled for gemspecs, and the `%q{}` literals in the template gemspec have been changed to simple quotes.
- The plugin template uses the .rubocop.yml from the root of this repo. The `fastlane.gemspec`
  pins rubocop to 0.48.1, which is not current. The plugin template gemspec places no limitation
  on the version of rubocop. Some Cops have changed namespaces in 0.49, generating warnings 
  (not offenses) in a new plugin using the latest version. Because Fastlane proper uses a different version with the same .rubocop.yml, rubocop runs cleanly in the repo.

### Description

There are several commits that implement different stages. Some could be reverted if not desired.

1. The simplest fix is to limit rubocop to 0.48.1 in the plugin template to avoid any changes in the main codebase for this issue. The issue with the gemspec filename and the `%q{}` literals still had to be fixed. `git checkout b8b02e1` for everything working with 0.48.1 (except perhaps a failing unit test).
2. Update Fastlane proper to 0.49.1. After fixing the snake_case and `%q{}` issues, this required:
  - Updating fastlane.gemspec.
  - Changing the Style namespace to Layout for a number of Cops in the .rubocop.yml and code comments.
  - ~~Running `rubocop -a` and making manual fixes for certain complaints.~~ Adding comments at various places in the code to eliminate certain failures temporarily until the authors can review them.
  The HEAD of this branch has everything updated to 0.49.1 and quietly passing both in the repo and new plugins. But this entailed a handful of code changes throughout the repo.
3. ~~Made fastlane/lib/fastlane/plugins/template/.rubocop.yml a symbolic link to the one in the root repo. Previously it was copied in by some lines in the gemspec. It's not clear if there was an important reason for this. I was concerned about keeping the copy up to date during development. The symbolic link seems more efficient. If this is a bad idea for some reason, this is a separate commit that is easy to revert.~~ This change was responsible for the failure of `rake install` in CI. It's been reverted.

This fixes rubocop in new plugins, the original issue:

```bash
[jdee@Jimmy-Dees-MacBookPro fastlane-plugin-my_new_action]$ bundle exec rake
/Users/jdee/.rvm/rubies/ruby-2.4.1/bin/ruby -I/Users/jdee/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.6.0/lib:/Users/jdee/.rvm/gems/ruby-2.4.1/gems/rspec-support-3.6.0/lib /Users/jdee/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

Fastlane::Actions::MyNewActionAction
  #run
    prints a message

Finished in 0.01344 seconds (files took 0.87178 seconds to load)
1 example, 0 failures

Running RuboCop...
Inspecting 10 files
..........

10 files inspected, no offenses detected
```

### CODE REVIEW

**Comment by jdee** [comment]
This is failing on Circle CI because of a failure of `rake install`, which passes for me. There was an automated rubocop change to a Rake task. I reverted the 0.49 changes in favor of disabling locally with comments. That may be the better approach anyway. But the build is still failing, and I'm not sure why.

**Comment by jdee** [comment]
Changing fastlane/lib/faslane/plugins/template/.rubocop.yml to a symbolic link seems to have been responsible for the failure of `rake install` in CI. This made life a little easier during development, to avoid having to rerun `bundle install` to test changes to .rubocop.yml in new plugins. Apparently this change was a bad idea or required more changes. It's been reverted.

File: fastlane_core/lib/fastlane_core/update_checker/update_checker.rb [hunk 1]
```diff
@@ -123,9 +123,11 @@ def self.generate_fetch_url(gem_name)
     def self.ios_app_identifier(args)
       # args example: ["-a", "com.krausefx.app", "--team_id", "5AA97AAHK2"]
       args.each_with_index do |current, index|
+        # rubocop: disable Style/MultipleComparison
```
Comment (taquitos) [inline fastlane_core/lib/fastlane_core/update_checker/update_checker.rb]: I'm wondering if we should just disable this rule all together instead of on a case-by-case basis. IMO it's not a rule we want to enforce. I'm totally open to discussion on that though.

Comment (jdee) [inline fastlane_core/lib/fastlane_core/update_checker/update_checker.rb]: This isn't my code, and I don't have a strong opinion. But it might be better to disable it given that `rubocop -a` doesn't seem to handle this case. I did all the changes manually in an earlier commit to satisfy this Cop. I've pushed another commit that removes these comments and disables Style/MultipleComparison in .rubocop.yml.

**Comment by KrauseFx** [comment]
Hey @jdee, thanks for addressing all the feedback so far. What I'm confused about is that the `rubocop` tests as part of the plugin creation are green (https://github.com/fastlane/fastlane/blob/master/fastlane/spec/plugins_specs/plugin_generator_spec.rb#L286-L294), is the test not working properly?

**Comment by jdee** [comment]
@KrauseFx It may be that the tests are not working properly. I'm not sure about using the Bundler that way. This is the issue I ran into when trying to run `rubocop -a` on plugin generation. I think the issue is that the Bundler in the RSpec example has the context of the current bundle (from the Gemfile in the repo). The new plugin has its own Gemfile and bundle. I'm not sure exactly, but I couldn't mmake anything actually happen in those `Bundler.setup` blocks.

Fortunately the `rubocop` gem is already a dev dependency here. I made this change in that example, and it fails in the master branch but passes with these changes:

```ruby
      it "rubocop validations are passing" do
        # Actually run our generated spec as part of this spec #yodawg
        rubocop = RuboCop::CLI.new
        status = rubocop.run(['-c', "#{gem_name}/.rubocop.yml", gem_name])
        expect(status).to eq(0)
      end
```

It could be that the other tests there (for rspec and rake) are also not really running and could be converted to programmatic calls, though I'm not sure if the bundle discrepancy could cause issues.

I need to get back to my day job. I can look a bit further into this later, maybe over the weekend, and update this PR or submit a new one.

**Review by KrauseFx — APPROVED** [review]
Nice, thanks for looking into this, really appreciated 👍
