### PR TITLE
[pilot] Add verification to apple_id parameter

### LINKED ISSUE #14834: [testflight] Unable to process validateMetadata request at this time due to a general error (1019)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My lane fails to upload a new app build to testflight

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>INFO [2019-05-31 18:16:31.40]: ------------------------
INFO [2019-05-31 18:16:31.40]: --- Step: testflight ---
INFO [2019-05-31 18:16:31.40]: ------------------------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
Successfully loaded Appfile at path '/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/fastlane/Appfile'
- app_identifier: 'com.infobip.mobilemessaging.bipbip'
- team_id: '[*******]'
-------
INFO [2019-05-31 18:16:31.46]: Ready to upload new build to TestFlight (App: [*******])...
DEBUG [2019-05-31 18:16:31.46]: App Platform (ios)
INFO [2019-05-31 18:16:32.21]: Wrote XML data to '/var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp'
INFO [2019-05-31 18:16:32.25]: Going to upload updated app to App Store Connect
INFO [2019-05-31 18:16:32.25]: This might take a few minutes. Please don't interrupt the script.
DEBUG [2019-05-31 18:16:32.37]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -jar /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar -m upload -u [*******] -p YourPassword -f /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp -t DAV -t Signiant -k 100000 2>&1
DEBUG [2019-05-31 18:16:37.87]: [Transporter]: INFO: Transporter is searching for new software components.
DEBUG [2019-05-31 18:16:40.38]: [Transporter]: INFO: Update check complete.
DEBUG [2019-05-31 18:16:42.38]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2019-05-31 18:16:42.70]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2019-05-31 18:16:42.89]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2019-05-31 18:16:42.89]: [Transporter]: DEBUG: Saving configuration to local path: /Users/mobile_ci/Library/Caches/com.apple.amp.itmstransporter/Defaults.properties
DEBUG [2019-05-31 18:16:42.90]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.13.0]
DEBUG [2019-05-31 18:16:42.90]: [Transporter]: INFO: OS identifier: Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2019-05-31 18:16:42.90]: [Transporter]: INFO: Memory: [JVM] 953M free, 981M total, 981M max [System] (Physical) 1463M free, 8192M total (Swap) 1459M free, 2048M total
DEBUG [2019-05-31 18:16:42.91]: [Transporter]: DBG-X: Memory: [JVM] 953M free, 981M total, 981M max [System] (Physical) 1464M free, 8192M total (Swap) 1459M free, 2048M total
DEBUG [2019-05-31 18:16:42.91]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter BaseVersion = 1.11.0
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2019-05-31T18:16:42+03:00
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.448793804
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u [*******] -p **hidden value** -f /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp -t DAV -t Signiant -k 100000
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter Version = 1.13.0
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2019-05-31 18:16:42.92]: [Transporter]: INFO: id = 20190531181642-879
DEBUG [2019-05-31 18:16:42.93]: [Transporter]: INFO: iTMSTransporter Correlation Key: df534adc-9ad6-4f2b-8e71-9729eda9bf1d
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter SharedSecret = **hidden value**
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter MultipartUploadsEnabled = true
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter TxHeaders = {x-tx-dcroute=pv, jenga=true}
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter SessionExpiration = 2019-06-04T15:16:43.515Z
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter SessionId = CLGpDBIQOLV74mGwSxOkWvjJeIVLNQ==
DEBUG [2019-05-31 18:16:43.63]: [Transporter]: DBG-X:   parameter StreamingSettings = {LogStreamingEnabled=true, MultipartUploadsEnabled=true, AssetDescriptionStreamingEnabled=false}
DEBUG [2019-05-31 18:16:43.66]: [Transporter]: INFO: Upload mode selected.
DEBUG [2019-05-31 18:16:43.66]: [Transporter]: INFO: Examining the package at: /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp
DEBUG [2019-05-31 18:16:43.66]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2019-05-31 18:16:43.66]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2019-05-31 18:16:43.67]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2019-05-31 18:16:43.67]: [Transporter]: DEBUG:   c50538ad37ac86d49d89779b880c7a7095e9974d19919a87850c44ae38bae044.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2019-05-31 18:16:43.67]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2019-05-31 18:16:43.67]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2019-05-31 18:16:43.67]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2019-05-31 18:16:43.68]: [Transporter]: INFO: Performing authentication of package [*******].itmsp ...
DEBUG [2019-05-31 18:16:43.72]: [Transporter]: DBG-X: Memory: [JVM] 941M free, 981M total, 981M max [System] (Physical) 1472M free, 8192M total (Swap) 1459M free, 2048M total
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X: Deflated 504 bytes to 444
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter BaseVersion = 1.11.0
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter Files = [c50538ad37ac86d49d89779b880c7a7095e9974d19919a87850c44ae38bae044.ipa, metadata.xml]
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter MetadataChecksum = 6164616c5ad715ae3e68cfbfad1b7c70
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter MetadataInfo = {app_platform=ios, primary_bundle_identifier=, device_id=, bundle_identifier=, packageVersion=software5.4, apple_id=[*******], asset_types=[bundle], bundle_version=, bundle_short_version_string=}
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.13.6 (x86_64); jvm=25.71-b02; jre=1.8.0-u131-b11-iTMSTransporter-b02
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter PackageName = [*******].itmsp
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter PackageSize = 88733580
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2019-05-31T18:16:43+03:00
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u [*******] -p **hidden value** -f /var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp -t DAV -t Signiant -k 100000
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter Version = 1.13.0
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2019-05-31 18:16:43.73]: [Transporter]: INFO: id = 20190531181643-430
DEBUG [2019-05-31 18:16:43.74]: [Transporter]: INFO: iTMSTransporter Correlation Key: df534adc-9ad6-4f2b-8e71-9729eda9bf1d
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter Errors = [Unable to process validateMetadata request at this time due to a general error (1019)]
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter EnableJWTForAllCalls = false
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter RestartClient = false
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter ErrorCode = 1019
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter ErrorMessage = Unable to process validateMetadata request at this time due to a general error (1019)
DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2019-05-31 18:16:49.51]: [Transporter Error Output]: Unable to process validateMetadata request at this time due to a general error (1019)

DEBUG [2019-05-31 18:16:49.51]: [Transporter]: DBG-X: The error code is: 1019
ERROR [2019-05-31 18:16:49.66]: Transporter transfer failed.
WARN [2019-05-31 18:16:49.66]: 
ERROR [2019-05-31 18:16:49.66]: Unable to process validateMetadata request at this time due to a general error (1019)

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X:   parameter RestartClient = false

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X:   parameter ErrorCode = 1019

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X:   parameter ErrorMessage = Unable to process validateMetadata request at this time due to a general error (1019)

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X:   parameter Success = false

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> ERROR: Unable to process validateMetadata request at this time due to a general error (1019)

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X: The error code is: 1019

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] Package Summary:

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter]  

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 1 package(s) were not uploaded because they had problems:

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 	/var/folders/bf/xbk6fmld26zfg2xppv65vn740000gn/T/d20190531-67628-1y188tq/[*******].itmsp - Error Messages:

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] 		Unable to process validateMetadata request at this time due to a general error (1019)

WARN [2019-05-31 18:16:49.84]: [iTMSTransporter] [2019-05-31 18:16:49 MSK] <main> DBG-X: Returning 1

INFO [2019-05-31 18:16:49.84]: iTunes Transporter output above ^
ERROR [2019-05-31 18:16:49.84]: Unable to process validateMetadata request at this time due to a general error (1019)
Return status of iTunes Transporter was 1: Unable to process validateMetadata request at this time due to a general error (1019)
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
WARN [2019-05-31 18:16:49.86]: Lane Context:
INFO [2019-05-31 18:16:49.86]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios publishing_lane", :VERSION_NUMBER=>"5.1.29", :BUILD_NUMBER=>"1559315541309", :SIGH_PROFILE_TYPE=>"app-store", :MATCH_PROVISIONING_PROFILE_MAPPING=>{"com.infobip.mobilemessaging.bipbip"=>"match AppStore com.infobip.mobilemessaging.bipbip", "com.infobip.mobilemessaging.bipbip.NotificationServiceExtension"=>"match AppStore com.infobip.mobilemessaging.bipbip.NotificationServiceExtension"}, :IPA_OUTPUT_PATH=>"/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/BipBip.ipa", :DSYM_OUTPUT_PATH=>"/Users/mobile_ci/jenkins/workspace/infobip-mobile-messaging-showcase-ios/BipBip.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/mobile_ci/Library/Developer/Xcode/Archives/2019-05-31/BipBip 2019-05-31 18.12.39.xcarchive"}
ERROR [2019-05-31 18:16:49.86]: Error uploading ipa file, for more information see above </pre>
</details>

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.2 (Apple Git-113)          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.6 (17G65)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.1                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# vim:set sw=2 ft=ruby
fastlane_version "1.68.0"
default_platform :ios

platform :ios do
    testflight(
            team_name: "XXX",
            app_identifier: "XXX",
            changelog: $releaseNotes,
            groups: ['mm_team'],
            wait_processing_interval: 120,
            distribute_external: true,
            beta_app_description: $releaseNotes,
            beta_app_feedback_email: "XXX",   
        )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
team_id "XXX"  # Developer Portal Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.124.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status      |
| -------------------------- | ------- | ------------------ |
| fastlane-plugin-wait_xcrun | 0.1.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| slack-notifier             | 2.3.2        |
| atomos                     | 0.1.3        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.6        |
| xcodeproj                  | 1.9.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.3.0        |
| terminal-notifier          | 2.0.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| public_suffix              | 2.0.5        |
| tty-spinner                | 0.8.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| commander-fastlane         | 4.4.6        |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| gh_inspector               | 1.1.3        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.2        |
| security                   | 0.1.3        |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| signet                     | 0.10.0       |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.23.9       |
| google-cloud-env           | 1.0.5        |
| google-cloud-core          | 1.2.7        |
| googleauth                 | 0.6.6        |
| digest-crc                 | 0.4.1        |
| google-cloud-storage       | 1.15.0       |
| emoji_regex                | 0.1.1        |
| tty-cursor                 | 0.6.0        |
| tty-screen                 | 0.6.5        |
| faraday                    | 0.15.3       |
| json                       | 2.1.0        |
| highline                   | 1.7.10       |
| io-console                 | 0.4.5        |
| excon                      | 0.62.0       |
| CFPropertyList             | 3.0.0        |
| plist                      | 3.4.0        |
| faraday_middleware         | 0.12.2       |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20180417 |
| fastimage                  | 2.1.4        |
| bundler                    | 1.14.6       |
| terminal-table             | 1.8.0        |
| unicode-display_width      | 1.4.0        |
| addressable                | 2.5.2        |
| multi_json                 | 1.13.1       |
| jwt                        | 2.1.0        |
| memoist                    | 0.16.0       |
| os                         | 1.0.0        |
| psych                      | 2.0.17       |
| retriable                  | 3.1.2        |
| mime-types                 | 3.2.2        |
| mime-types-data            | 3.2018.0812  |
| uber                       | 0.1.0        |
| declarative                | 0.0.10       |
| fastlane-plugin-wait_xcrun | 0.1.1        |
</details>

*generated on:* **2019-05-31**
</details>

This issue appeared after I updated the fastlane to 2.124.0 today

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

According to [Apple's documentation](https://help.apple.com/app-store-connect/#/dev219b53a88) `Apple ID`:

> A unique identifier automatically generated for your app when you add the app to your account. You can view this property in the App Information section in App Store Connect. This identifier is also used in the URL for the App Store on desktop computers. You can’t edit this property.
>
> Note: This identifier is not the same as your Apple ID that you use to sign in to App Store Connect and your developer account.
however [sometimes it is mistaken](https://github.com/fastlane/fastlane/issues/14834) with user's Apple ID. 

There is [on-going discussion](https://github.com/fastlane/fastlane/issues/14788) about parameter renaming, but as a quick win, this PR is introducing a parameter validation. 

closes https://github.com/fastlane/fastlane/issues/14834

### Description

`apple_id` parameter validation was added:

* check if `apple_id` parameter is not an email address
* check if `apple_id` parameter is not a bundle identifier 

According to [the documentation](https://help.apple.com/xcode/mac/current/#/dev9b66ae7df) `bundle ID`:

> The bundle ID string must be a uniform type identifier (UTI) that contains only alphanumeric characters (A-Z, a-z, 0-9), hyphen (-), and period (.). The string should be in reverse-DNS format. Bundle IDs are case sensitive.

I implemented unit tests. 

🙇

### CODE REVIEW

File: pilot/lib/pilot/options.rb [hunk 1]
```diff
@@ -42,7 +42,23 @@ def self.available_options
                                      optional: true,
                                      code_gen_sensitive: true,
                                      default_value: ENV["TESTFLIGHT_APPLE_ID"],
-                                     default_value_dynamic: true),
+                                     default_value_dynamic: true,
+                                     type: String,
+                                     verify_block: proc do |value|
+                                       error_message = "`apple_id` value is incorrect. App ID consists of a Team ID and a bundle ID search string, with a period (.) separating the two parts. You can find your Team ID here: https://developer.apple.com/account/#/membership and your bundle ID in Xcode settings."
```
Comment (mollyIV) [inline pilot/lib/pilot/options.rb]: 👋 @janpio , 

I really like your error / documentation / message suggestions 🙌 Have a feeling this one might be a bit too much technical though 🤔 Thoughts how to improve it? 🙏

**Review by joshdholtz — COMMENTED** [review]
@mollyIV I think I'm a bit confused by what `apple_id` is now 🤔 I was 100% confident that the `apple_id` was simply just an integer. I use `apple_id: "1358899889"` in some of my stuff and it seems to work 🙃

**Comment by mollyIV** [comment]
👋 @joshdholtz , 

oh, I am confused now too 😅 

> I use apple_id: "1358899889" in some of my stuff and it seems to work 🙃

Is it a Team ID value from App Store Connect? 

Thoughts @janpio? 🤔

**Comment by joshdholtz** [comment]
@mollyIV Its this guy right here 😊 Its the ID of app on App Store Connect. So this ID is used in requests for routes like `/apps/<app_id>`

Screen Shot 2019-06-25 at 8 57 58 AM

**Comment by mollyIV** [comment]
Thank you for the clarification @joshdholtz 🙇 

According to [Apple's documentation](https://help.apple.com/app-store-connect/#/dev219b53a88) `Apple ID`:

> A unique identifier automatically generated for your app when you add the app to your account. You can view this property in the App Information section in App Store Connect. This identifier is also used in the URL for the App Store on desktop computers. You can’t edit this property.
>
> Note: This identifier is not the same as your Apple ID that you use to sign in to App Store Connect and your developer account.

I talked with @joshdholtz and we think that starting with a blacklist validation will do 💪 

Let's start with bundle identifier and email:

```
upload_to_testflight(username: 'my-email@gmail.com', 
                                  apple_id: 'com.bundle.identifier') // --> param validation will fail

upload_to_testflight(username: 'my-email@gmail.com', 
                                  apple_id: 'username@example.com') // --> param validation will fail

upload_to_testflight(username: 'my-email@gmail.com', 
                                  apple_id: '1358899889') // --> param validation will succeed
```

**Comment by mollyIV** [comment]
I updated the PR according to my last comment 🚀 

The one more think to consider is backward compatibility 🤔Let's say Apple decided to allow setting bundle ID as Apple ID value, it would break our `apple_id` param validation for previous `fastlane` releases (starting when we merged this PR). 

On the other hand, we are only validating the param in terms of not using emails and bundle ids - I guess there is not a high chance to replace `apple_id` by these two in the future. 

Thoughts? @joshdholtz @janpio ? 🙏

**Comment by janpio** [comment]
> The one more think to consider is backward compatibility 🤔 Let's say Apple decided to allow setting bundle ID as Apple ID value, it would break our `apple_id` param validation for previous `fastlane` releases (starting when we merged this PR).

I don't think this was ever the case, and I don't expect them to do that in the future. And if they do, it is perfectly fine if this only starts working with future fastlane versions.

This PR is to avoid people confusing the `apple_id` from the `Appfile` (which is your login email address) with the App Apple ID needed here.

Interesting that our existing tests even used a wrong sample value.

You could probably put part of your great error message ("Apple ID property in the App Information section in App Store Connect.") into the description of the option `apple_id` (line 41) to further improve the documentation.

**Comment by mollyIV** [comment]
> Interesting that our existing tests even used a wrong sample value.

Was surprised a bit too 😅 

@janpio thank you for the documentation improvement suggestion 👍 

I just pushed the newest changes, can you please have a 👀 ? 🙏 🙇

File: pilot/lib/pilot/options.rb [hunk 2]
```diff
@@ -38,11 +38,21 @@ def self.available_options
...
-                                     description: "The unique App ID provided by App Store Connect",
+                                     description: "Apple ID property in the App Information section in App Store Connect",
                                      optional: true,
                                      code_gen_sensitive: true,
                                      default_value: ENV["TESTFLIGHT_APPLE_ID"],
-                                     default_value_dynamic: true),
+                                     default_value_dynamic: true,
+                                     type: String,
+                                     verify_block: proc do |value|
+                                       error_message = "`apple_id` value is incorrect. The correct value should be taken from Apple ID property in the App Information section in App Store Connect."
```
Comment (janpio) [inline pilot/lib/pilot/options.rb]:
```suggestion
                                       error_message = "Format of your `apple_id` is not valid. The correct value should be taken from Apple ID property in the App Information section in App Store Connect."
```

**Review by janpio — APPROVED** [review]
Looks good to me.

Final suggestion on the error message, but I am also fine with the current one.

**Review by joshdholtz — APPROVED** [review]
Looks good to me!
