### PR TITLE
[action] add dsym_paths option to upload_symbols_to_crashlytics

### LINKED ISSUE #12774: Upload symbol to crashlytics action uploads the first dSYM file it finds.
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using the `upload_symbols_to_crashlytics` without the path for the dSYM specified, if there are a number of dSYM (app, embedded frameworks) present in the default location, it selects the first dSYM and uploads it to crashlytics.
It should be uploading all the dSYM generated to crashlytics. 

Also, If I'm not wrong, while using the `hockey` action to upload dSYM and IPA, it uploads all the dSYMs generated during the build.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.15.1 (Apple Git-101)          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.96.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.4.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.16.1       |
| io-console                | 0.4.6        |
| rake                      | 12.3.1       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.4        |
| fastimage                 | 2.1.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| dotenv                    | 2.4.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.1.0        |
| simctl                    | 1.6.4        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.3        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.5        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
| badge                     | 0.9.1        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.16.2       |
| no_proxy_fix              | 0.1.2        |
| sawyer                    | 0.8.1        |
| octokit                   | 4.9.0        |
| danger                    | 5.5.13       |
| thor                      | 0.20.0       |
| danger-swiftlint          | 0.17.0       |
</details>

*generated on:* **2018-06-20**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #12774

# What
- `upload_symbols_to_crashlytics` didn't allow manually uploading with multiple dsym paths but now it does

### CODE REVIEW

File: fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb [hunk 1]
```diff
@@ -16,6 +16,7 @@ def self.run(params)
 
         dsym_paths = []
         dsym_paths << params[:dsym_path] if params[:dsym_path]
+        dsym_paths += params[:dsym_paths] if params[:dsym_paths]
```
Comment (taquitos) [inline fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: Does it make sense to allow `:dsym_path` AND `:dsym_paths` ? I would think if we use one, we should disallow the other. Thoughts?

File: fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb [hunk 2]
```diff
@@ -151,6 +152,17 @@ def self.available_options
                                          UI.user_error!("Couldn't find file at path '#{File.expand_path(value)}'") unless File.exist?(value)
                                          UI.user_error!("Symbolication file needs to be dSYM or zip") unless value.end_with?(".zip", ".dSYM")
                                        end),
+          FastlaneCore::ConfigItem.new(key: :dsym_paths,
+                                       env_name: "FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_PATHs",
```
Comment (taquitos) [inline fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: `FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_PATHs` -> `FL_UPLOAD_SYMBOLS_TO_CRASHLYTICS_DSYM_PATHS`

**Review by taquitos — COMMENTED** [review]
Love the tests, one typo and a question

File: fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb (hunk 2 above)
Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: 😱

File: fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb (hunk 1 above)
Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: @taquitos This _did_ cross my mind but `:dsym_path` can get autoset by some actions which might make things confusing by a user if also trying to use `:dsym_paths`. And I these parameters don't necessarily conflict - the `hockey` action has conflicting between `:ipa` and `:apk` because those both 100% can't be used at the same time where `:dsym_paths` more or less compliments/extends what `:dsym_path` can do 🙃

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: I actually wanted to include the `:dsym_paths` functionality just inside of `:dsym_path` because they are super similar but the `:dsym_path` naming just didn't fit 😔 And I don't think we have the option in a `ConfigItem` to specif an "alias", do we???

Comment (taquitos) [reply fastlane/lib/fastlane/actions/upload_symbols_to_crashlytics.rb]: Ohhh good point that it can be autoset! It might be worthy of a code comment here to add that information, so future joshs don't try to remove this.

**Review by taquitos — APPROVED** [review]
Add some code comments around :dsym_path autoset behavior and then ⚽️:goat:!
