### PR TITLE
[spaceship] implements new hashcash header in auth flow

### LINKED ISSUE #21071: Don't ask verification code and access forbiden and apple account block
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When I try to log in to the apple account, it asks me for the username and password but not the verification code. The code arrives at the authorized apple devices but the fastlane application does not ask me for it and returns access forbiden.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 
   Please enter your Apple ID developer credentials
[11:54:57]: Apple ID Username:
apple@....
[11:56:15]: Logging in...
Password (for apple@...): **************
[11:56:45]: --------------------
[11:56:45]: fastlane init failed
[11:56:45]: --------------------
[11:56:45]: ["The request could not be completed because:", "Access forbidden"] </pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | 13.1                                                       |
| Ruby                        | 3.1.3                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.34.1                                         |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.212.0/libexec/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                         |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby@3.1/3.1.3_1/lib                  |
| OpenSSL Version             | OpenSSL 3.0.7 1 Nov 2022                                   |
| Is contained                | false                                                      |
| Is homebrew                 | true                                                       |
| Is installed via Fabric.app | false                                                      |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |
| Xcode Version               | 14.2                                                       |
| Swift Version               | 5.7.2                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.212.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.6        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.99.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.3       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.1        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.3.26       |
| simctl                          | 1.6.10       |
| jwt                             | 2.7.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.8.1        |
| google-apis-core                | 0.11.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.34.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.714.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.170.0      |
| aws-sdk-kms                     | 1.62.0       |
| aws-sdk-s3                      | 1.119.1      |
| set                             | 1.0.2        |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.5        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.2.0        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.1        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-http                        | 0.3.0        |
| net-protocol                    | 0.1.2        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.4        |
</details>

*generated on:* **2023-02-23**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context

Fixes #21071

### Description

Apple requires the `X-APPLE-HC` header when signing in to `https://idmsa.apple.com/appleauth/auth/signin`. Leaving out this header results in forbidden access and possible Apple ID account lockout.

`X-APPLE-HC` uses a customer implementation of http://www.hashcash.org/

1. GET to `https://idmsa.apple.com/appleauth/auth/signin`
2. Use response headers `x-apple-hc-bits` and `x-apple-hc-challenge` to make hashcash
3. Set hashcash to `X-APPLE-HC` header on login

And big big thank you to [Ariel Michaeli](https://twitter.com/arielmichaeli) and his team at [Appfigures](https://appfigures.com) for sharing Apple's hashcash spec with us so ❤️ 

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-implement-hashcash"
```

### CODE REVIEW

File: spaceship/lib/spaceship/hashcash.rb [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    #  2. The Counter conventionally encoded as base-64 but Apple just uses the decimal number's string representation.
+    #
+    # Iterate from Counter=0 to Counter=N finding an N that makes the SHA1(X-APPLE-HC) lead with Bits leading zero bits
+    #
+    #
+    # We get the "Resource" from the X-Apple-HC-Challenge header and Bits from X-Apple-HC-Bits
+    #
+    # </summary>
+    def self.make(bits:, challenge:)
+      version = 1
```
Comment (ainame) [inline spaceship/lib/spaceship/hashcash.rb:36]: It's not a big deal, but we can put `version` in the argument list with the default value. What do you think?

```suggestion
    def self.make(bits:, challenge:, version: 1)
```

File: spaceship/lib/spaceship/client.rb [hunk 2]
```diff
@@ -498,6 +504,7 @@ def send_shared_login_request(user, password)
           req.headers['X-Apple-Widget-Key'] = self.itc_service_key
           req.headers['Accept'] = 'application/json, text/javascript'
           req.headers["Cookie"] = modified_cookie if modified_cookie
+          req.headers["X-APPLE-HC"] = hashcash if hashcash
```
Comment (ainame) [inline spaceship/lib/spaceship/client.rb:507]:
```suggestion
          req.headers["X-Apple-HC"] = hashcash if hashcash
```

I guess this wouldn't matter, but aligning the case pattern to make them consistent feels good. Or did the case matter here?

(I saw `HC` in the header so only `APPLE` -> `Apple`)
Screenshot 2023-02-24 at 11 22 24

File: spaceship/lib/spaceship/client.rb [hunk 3]
```diff
@@ -545,6 +552,21 @@ def send_shared_login_request(user, password)
     end
     # rubocop:enable Metrics/PerceivedComplexity
 
+    def fetch_hashcash
+      response = request(:get, "https://idmsa.apple.com/appleauth/auth/signin?widgetKey=#{self.itc_service_key}")
+      headers = response.headers
+
+      bits = headers["x-apple-hc-bits"]
+      challenge = headers["x-apple-hc-challenge"]
```
Comment (ainame) [inline spaceship/lib/spaceship/client.rb:560]:
```suggestion
      bits = headers["X-Apple-HC-Bits"]
      challenge = headers["X-Apple-HC-Challenge"]
```

File: spaceship/lib/spaceship/client.rb [hunk 4]
```diff
@@ -545,6 +552,21 @@ def send_shared_login_request(user, password)
...
+
+      if bits.nil? || challenge.nil?
+        puts("Unable to find 'x-apple-hc-bits' and 'x-apple-hc-challenge' to make hashcash")
```
Comment (ainame) [inline spaceship/lib/spaceship/client.rb:563]:
```suggestion
        puts("Unable to find 'X-Apple-HC-Bits' and 'X-Apple-HC-Challenge' to make hashcash")
```

**Review by ainame — APPROVED** [review]
Thank you for working on this so quickly🚀 (I also got locked out but recovered already) 

I learned about Hashcash from some web pages and manually followed the procedure to generate the value to figure out how the flow works. The logic here made sense.

I also confirmed `Spaceship::ConnectAPI::Client.login` and another endpoint to get some resource work as expected with your branch locally. 

I just suggested some styling points 💅 Would be good to have another 👀 before merging this?

File: spaceship/lib/spaceship/hashcash.rb [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+    #             1:11:20230223170600:4d74fb15eb23f465f1f6fcbf534e5877::6373
+    # X-APPLE-HC: 1:11:20230223170600:4d74fb15eb23f465f1f6fcbf534e5877::6373
+    #             ^  ^      ^                       ^                     ^
+    #             |  |      |                       |                     +-- Counter
+    #             |  |      |                       +-- Resource
+    #             |  |      +-- Date YYMMDD[hhmm[ss]]
+    #             |  +-- Bits (number of leading zeros)
+    #             +-- Version
+    #
+    # We can't use an off-the-shelf Hashcash because Apple's implementation is not quite the same as the spec/convention.
```
Comment (rogerluan) [inline spaceship/lib/spaceship/hashcash.rb:25]: Why does this sound like a classic Apple move 😭

File: spaceship/spec/tunes/tunes_stubbing.rb [hunk 6]
```diff
@@ -31,6 +31,8 @@ def itc_stub_login
         to_return(status: 200, body: "", headers: {})
 
       # Actual login
+      stub_request(:get, "https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0abc").
+        to_return(status: 200, body: '', headers: { 'x-apple-hc-bits' => "12", 'x-apple-hc-challenge' => "f8b58554b2f22960fc0dc99aea342276" })
```
Comment (rogerluan) [inline spaceship/spec/tunes/tunes_stubbing.rb:35]: If you end up addressing @ainame 's comments above regarding the case of the headers, we'd need to update it here as well 👀

File: spaceship/lib/spaceship/client.rb (hunk 3 above)
Comment (rogerluan) [reply spaceship/lib/spaceship/client.rb:560]: Any particular reason why this was written in lowercase, and the one above was all uppercase @joshdholtz ? 👀

**Review by rogerluan — APPROVED** [review]
LGTM :) But I agree with @ainame 's nitpicks, if we can address them. If not, then ofc it's all good too!

File: spaceship/lib/spaceship/hashcash.rb (hunk 1 above)
Comment (ainame) [reply spaceship/lib/spaceship/hashcash.rb:36]: Hmm I come to think this doesn't make sense because if the version is changed, the internal logic will be completely changed too😂 I'll close this.

File: spaceship/lib/spaceship/client.rb (hunk 2 above)
Comment (joshdholtz) [reply spaceship/lib/spaceship/client.rb:507]: They got sent up in all caps when I looked via Proxyman but Ill try making them consistent!

File: spaceship/lib/spaceship/client.rb (hunk 3 above)
Comment (joshdholtz) [reply spaceship/lib/spaceship/client.rb:560]: It's what the hash showed when I inspected it but I guess it does a case insensitive lookup 😇

Comment (ainame) [reply spaceship/lib/spaceship/client.rb]: Essentially HTTP header names are case-**in**sensitive so the case doesn't really matter. It's only a styling concern🙂 

https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

File: spaceship/lib/spaceship/client.rb (hunk 2 above)
Comment (ainame) [reply spaceship/lib/spaceship/client.rb]: Haha, I used `curl`. Either or both `curl` and `proxyman` format headers by themselves 😂

**Comment by x0000ff** [comment]
It fixes #21178
