### PR TITLE
Fixes fastlane init failing with interactive bug

### LINKED ISSUE #9203: Ran into error while trying to connect to iTunes Connect / Dev Portal
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I used ```fastlane init```, error occurring 

[13:10:43]: Ran into error while trying to connect to iTunes Connect / Dev Portal: undefined method `interactive?' for FastlaneCore::Helper:Module
[13:10:43]: Falling back to manual onboarding
[13:10:43]: undefined method `interactive?' for FastlaneCore::Helper:Module
[13:10:43]: An error occurred during the setup process. Falling back to manual setup!

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.7.4 (Apple Git-66)                               |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode7.3.1.app/Contents/Developer/               |
| Xcode Version               | 7.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.31.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-18**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #9203 

Getting following output with `fastlane init` when having multiple teams
```
[13:10:43]: Ran into error while trying to connect to iTunes Connect / Dev Portal: undefined method interactive?' for FastlaneCore::Helper:Module [13:10:43]: Falling back to manual onboarding [13:10:43]: undefined methodinteractive?' for FastlaneCore::Helper:Module
[13:10:43]: An error occurred during the setup process. Falling back to manual setup!
```

### CODE REVIEW

**Review by mpirri — APPROVED** [review]
💯

File: spaceship/lib/spaceship/portal/ui/select_team.rb [hunk 1]
```diff
@@ -40,7 +40,7 @@ def self.ci?
 
       def self.interactive?
         if Object.const_defined?("FastlaneCore") && FastlaneCore.const_defined?("Helper")
```
Comment (mfurtak) [inline spaceship/lib/spaceship/portal/ui/select_team.rb]: Should the reference to `Helper` change here as well?

Comment (mpirri) [inline spaceship/lib/spaceship/portal/ui/select_team.rb]: Good catch!

Comment (joshdholtz) [inline spaceship/lib/spaceship/portal/ui/select_team.rb]: Good catch

**Review by mfurtak — APPROVED** [review]
