### PR TITLE
produce: fix data_protection in enabled features

### LINKED ISSUE #7954: produce enable_services not actually enabling
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I tell produce to enable 'Data Protection complete'.  It says it successfully creates the appId, but when I check the dev center (and compile) it didn't actually enable Data Protection complete.

image

Fastfile command (shortened)
```
   newId = "com.a.a" //removed sensitive info
   newName = "a" //removed sensitive info
   appFeatures = { "data-protection" => "complete" }
   produce(app_identifier: newId, app_name: newName, skip_itc: true, enabled_features: appFeatures)
```

```
[12:12:00]: ---------------------
[12:12:00]: --- Step: produce ---
[12:12:00]: ---------------------

+----------------------------------+---------------------------------------------------------------+
|                                    Summary for produce 2.9.0                                     |
+----------------------------------+---------------------------------------------------------------+
| app_identifier                   | com.a.a |
| app_name                         | a                  |
| skip_itc                         | true                                                          |
| enabled_features.data_protection | complete                                                      |
| username                         | a@a.com                                    |
| sku                              | 14851*****                                                    |
| platform                         | ios                                                           |
| language                         | English                                                       |
| skip_devcenter                   | false                                                         |
| team_id                          | JLT78*****                                                    |
+----------------------------------+---------------------------------------------------------------+

[12:12:02]: Creating new app 'a' on the Apple Dev Center
[12:12:03]: Your app name includes non-ASCII characters, which are not supported by the Apple Developer Portal.
[12:12:03]: To fix this a unique (internal) name 'a' has been created for you. Your app's real name 'a'
[12:12:03]: will still show up correctly on iTunes Connect and the App Store.
[12:12:03]: Created app 3N7Z9*****
[12:12:03]: Finished creating new app 'a' on the Dev Center
[12:12:03]: ------------------
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                    |
| ------------------- | -------------------------------------------------------- |
| OS                  | 10.11.6                                                  |
| Ruby                | 2.3.1                                                    |
| Bundler?            | true                                                     |
| Git                 | git version 2.10.2                                       |
| Installation Source | ~/a/vendor/bundle/ruby/2.3.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                               |
| Ruby Lib Dir        | /opt/rubies/ruby-2.3.1/lib                               |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                              |
| Is contained        | false                                                    |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/          |
| Xcode Version       | 8.1                                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

<details><summary><b>Loaded gems</b></summary>

| Gem                                   | Version      |
| ------------------------------------- | ------------ |
| did_you_mean                          | 1.0.2        |
| bundler                               | 1.13.6       |
| io-console                            | 0.4.6        |
| CFPropertyList                        | 2.3.4        |
| i18n                                  | 0.7.0        |
| json                                  | 1.8.6        |
| minitest                              | 5.10.1       |
| thread_safe                           | 0.3.5        |
| tzinfo                                | 1.2.2        |
| activesupport                         | 4.2.7.1      |
| public_suffix                         | 2.0.5        |
| addressable                           | 2.5.0        |
| rubyzip                               | 1.2.0        |
| apktools                              | 0.7.1        |
| aws-sigv4                             | 1.0.0        |
| jmespath                              | 1.3.1        |
| aws-sdk-core                          | 2.6.49       |
| aws-sdk-resources                     | 2.6.49       |
| aws-sdk                               | 2.6.49       |
| babosa                                | 1.0.2        |
| claide                                | 1.0.1        |
| fuzzy_match                           | 2.0.4        |
| nap                                   | 1.1.0        |
| cocoapods-core                        | 1.1.1        |
| cocoapods-deintegrate                 | 1.0.1        |
| cocoapods-downloader                  | 1.1.3        |
| cocoapods-plugins                     | 1.0.0        |
| cocoapods-search                      | 1.0.0        |
| cocoapods-stats                       | 1.0.0        |
| netrc                                 | 0.7.8        |
| cocoapods-trunk                       | 1.1.2        |
| cocoapods-try                         | 1.1.0        |
| colored                               | 1.2          |
| escape                                | 0.0.4        |
| fourflusher                           | 2.0.1        |
| gh_inspector                          | 1.0.3        |
| molinillo                             | 0.5.5        |
| nanaimo                               | 0.2.3        |
| xcodeproj                             | 1.4.2        |
| cocoapods                             | 1.1.1        |
| highline                              | 1.7.8        |
| commander                             | 4.4.3        |
| unf_ext                               | 0.0.7.2      |
| unf                                   | 0.1.4        |
| domain_name                           | 0.5.20161129 |
| dotenv                                | 2.1.2        |
| excon                                 | 0.54.0       |
| multipart-post                        | 2.0.0        |
| faraday                               | 0.11.0       |
| http-cookie                           | 1.0.3        |
| faraday-cookie_jar                    | 0.0.6        |
| faraday_middleware                    | 0.11.0       |
| fastimage                             | 2.0.1        |
| jwt                                   | 1.5.6        |
| little-plugger                        | 1.1.4        |
| multi_json                            | 1.12.1       |
| logging                               | 2.1.0        |
| memoist                               | 0.15.0       |
| os                                    | 0.9.6        |
| signet                                | 0.7.3        |
| googleauth                            | 0.5.1        |
| httpclient                            | 2.8.3        |
| hurley                                | 0.2          |
| mime-types-data                       | 3.2016.0521  |
| mime-types                            | 3.1          |
| uber                                  | 0.0.15       |
| representable                         | 2.3.0        |
| retriable                             | 2.1.0        |
| google-api-client                     | 0.9.20       |
| mini_magick                           | 4.5.1        |
| multi_xml                             | 0.6.0        |
| plist                                 | 3.2.0        |
| security                              | 0.1.3        |
| slack-notifier                        | 1.5.1        |
| terminal-notifier                     | 1.7.1        |
| unicode-display_width                 | 1.1.3        |
| terminal-table                        | 1.7.3        |
| word_wrap                             | 1.0.0        |
| rouge                                 | 1.11.1       |
| xcpretty                              | 0.2.4        |
| xcpretty-travis-formatter             | 0.0.4        |
| proxies                               | 0.2.1        |
| s3                                    | 0.3.25       |
</details>

*generated on:* **2017-01-22**
</details>

### PR DESCRIPTION
**Pull request by hjanuschka**
fixes: https://github.com/fastlane/fastlane/issues/7954

`.on`  is nil on that option! 😢

### CODE REVIEW

**Review by mfurtak — CHANGES_REQUESTED** [review]
Looks good. :+1: 

Can you also add a test that covers this code to prevent regressions?

**Comment by hjanuschka** [comment]
@mfurtak good idea, however produce does not have yet any specs.
i added some, but i am failing to suceed, can you have a look? (commented inline)

File: produce/spec/stubbing.rb [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+  expect(Spaceship).to receive(:login).and_return(nil)
+  allow(Spaceship).to receive(:client).and_return("client")
+  expect(Spaceship).to receive(:select_team).and_return(nil)
+  allow(Spaceship.app).to receive(:find).and_return(true)
+
+  # Create a new App - with enabled features
+  stub_request(:post, "https://idmsa.apple.com/appleauth/auth/signin?widgetKey=e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42").
+    with(body: "{\"accountName\":\"helmut@xxx.com\",\"password\":\"xxxx\",\"rememberMe\":true}",
+        headers: { 'Accept' => 'application/json, text/javascript', 'Accept-Encoding' => 'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Content-Type' => 'application/json', 'User-Agent' => 'Spaceship 2.9.0', 'X-Requested-With' => 'XMLHttpRequest' }).
+    to_return(status: 200, body: "", headers: {})
```
Comment (hjanuschka) [inline produce/spec/stubbing.rb]: stub will be replaced, once the `create_new_app`  is called.

File: produce/spec/manager_spec.rb [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+        username: "helmut@januschka.com",
+        enabled_features: { "data_protection" => "complete" },
+        skip_itc: true
+      }
+      Produce::Manager.start_producing
+
+      # this does not get triggerd - HELP
+      # i would return true here, and check  if the `enabled_features` argument to create_new_app is the expected one
+      # but it just does not get called.
+      expect(Produce::DeveloperCenter).to receive(:create_new_app).with(anything).and_return(false)
```
Comment (hjanuschka) [inline produce/spec/manager_spec.rb]: see here 😢

**Review by mgrebenets — DISMISSED** [review]

**Comment by hjanuschka** [comment]
@mgrebenets , @mfurtak  all good now - tests pass 👍

File: produce/spec/manager_spec.rb [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+      features = instance.enabled_features
+      expect(features["dataProtection"].value).to eq("complete")
+    end
+
+    it "accepts symbol'd hash" do
+      Produce.config = {
+        username: "helmut@januschka.com",
+        enabled_features: { data_protection: "complete" },
+        skip_itc: true
+      }
```
Comment (mfurtak) [inline produce/spec/manager_spec.rb]: While this works, it's a little sketchy since the real type of this object should be `Configuration`. It's more common to set this up like:

```ruby
Produce.config = FastlaneCore::Configuration.create(Produce::Options.available_options, {
  username: "helmut@januschka.com",
  enabled_features: { data_protection: "complete" },
  skip_itc: true
})
```

File: produce/spec/spec_helper.rb [hunk 4]
```diff
@@ -0,0 +1 @@
+require_relative "stubbing"
```
Comment (mfurtak) [inline produce/spec/spec_helper.rb]: let's remove this and the `stubbing.rb` until we need them 👍

**Comment by hjanuschka** [comment]
@mfurtak feedback addressed.

**Review by mfurtak — APPROVED** [review]
Good stuff!
