### PR TITLE
[spaceship] replace post_for_testflight_review with new public API

### LINKED ISSUE #13903: upload_to_testflight: <h2>Not Found</h2></div>
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
  +--------------------------------+--------------------------------------+
[20:09:29]: <!DOCTYPE html><html lang="en">
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | latest_testflight_bui  | 13          |
|      | ld_number              |             |
| 3    | increment_build_numbe  | 1           |
|      | r                      |             |
| 4    | build_app              | 792         |
| 💥   | upload_to_testflight   | 3664        |
+------+------------------------+-------------+

[20:09:29]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/spaceship/lib/spaceship/test_flight/client.rb:330:in `handle_response': [!] <!DOCTYPE html><html lang="en"> (Spaceship::UnexpectedResponse)
<head>
<title></title>
<link rel="stylesheet" href="/styles/main.css">
<style type='text/css'>
    /*include ../../dist/styles/main.css*/
</style>
</head>

<body><div id="wrapper" class="j42">
<h2>Not Found</h2></div>

<div class="footer">
    <p>Copyright &copy; <span id='year'>2015</span> Apple Inc. All rights reserved.</p>
    <ul><li><a href="https://www.apple.com/legal/internet-services/itunes/">Terms of Service</a></li><li><a href="https://www.apple.com/legal/privacy">Privacy Policy</a></li></ul>
</div>


<script type='text/javascript'>(function() {
    var isIos = navigator.userAgent.match(/(iPod|iPhone|iPad)/);
    document.body.setAttribute( 'class', (!isIos) ? 'otherBrowser' : 'isMobileSafari' )
    var yearEl = document.getElementById('year');
    if (yearEl) { yearEl.textContent = new Date().getFullYear(); }
})();
</script>

</body>
</html>
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/spaceship/lib/spaceship/test_flight/client.rb:72:in `post_for_testflight_review'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/spaceship/lib/spaceship/test_flight/build.rb:217:in `submit_for_testflight_review!'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/pilot/lib/pilot/build_manager.rb:183:in `distribute_build'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/pilot/lib/pilot/build_manager.rb:108:in `distribute'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/pilot/lib/pilot/build_manager.rb:61:in `upload'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:38:in `block (2 levels) in parsing_binding'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/fastlane/lib/fastlane/cli_tools_distributor.rb:108:in `take_off'
	from /Users/daminik00/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.110.0/bin/fastlane:23:in `<top (required)>'
	from /Users/daminik00/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/daminik00/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.14.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.17.1 (Apple Git-112)          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.14.3 (18D21c)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 10.0                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = «"
  desc "Push a new beta build to TestFlight"

  lane :sendPush do
    changelog = File.read("Changelog.txt")
    url = URI.parse(URI.escape("http://api.daminik00.ru/push.php?info=#{changelog}"))
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) {|http|
      http.request(req)
    }
  end

  lane :beta do
    increment_build_number(
      build_number: latest_testflight_build_number.to_i + 1,
      xcodeproj: "SupremeBotiOSAcute.xcodeproj"
    )
    build_app(workspace: "SupremeBotiOSAcute.xcworkspace", scheme: "SupremeBotiOSAcute")
    changelog = File.read("Changelog.txt")
    upload_to_testflight(changelog: changelog, beta_app_description: "Удачных вам дропов", groups: "Me")
    sendPush
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("ru.daminik00.Supreme-Bot") # The bundle identifier of your app
apple_id("dev.daminik00@gmail.com") # Your Apple email address

itc_team_id("118705364") # App Store Connect Team ID
team_id("4X4HAH2D2G") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.7.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| public_suffix             | 2.0.5        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types                | 3.1          |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| highline                  | 1.7.10       |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| libxml-ruby               | 3.0.0        |
| plist                     | 3.4.0        |
| fastimage                 | 2.1.5        |
| addressable               | 2.5.2        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| multi_json                | 1.13.1       |
| jwt                       | 2.1.0        |
| os                        | 1.0.0        |
| psych                     | 2.0.8        |
| uber                      | 0.1.0        |
</details>

*generated on:* **2018-12-13**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #13903

## Description 
The private API used in `Spaceship::TestFlight`'s `post_for_testflight_review` was taken down by Apple and replaced with the new public official App Store Connect API. This PR is a fix for that.

### Thing to note
- This current solution is probably **NOT** a permanent one (the way that it is currently implemented)
- This needed to get fixed and this works 😊
- I put this in its own new `Spaceship::API` module so that it was easy to replace later on 
- I replaced the internals of `Spacehip::TestFlight::Build` to use the new `Spaceship::API` implementation so that there were less changes in the PR and that we can just get things working again

### CODE REVIEW

File: spaceship/lib/spaceship/api/client.rb [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+        end.join(" ")
+      end
+
+      private
+
+      # used to assert all of the named parameters are supplied values
+      #
+      # @raises NameError if the values are nil
+      def assert_required_params(method_name, binding)
+        parameter_names = method(method_name).parameters.map { |k, v| v }
```
Comment (armcburney) [inline spaceship/lib/spaceship/api/client.rb]: Nitpick: since the key isn't being used, I'd write `.map { |_, v| v }`.

File: spaceship/lib/spaceship/api/client.rb [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+      # This client is solely responsible for the making HTTP requests and
+      # parsing their responses. Parameters should be either named parameters, or
+      # for large request data bodies, pass in anything that can resond to
+      # `to_json`.
+      #
+      # Each request method should validate the required parameters. A required parameter is one that would result in 400-range response if it is not supplied.
+      # Each request method should make only one request. For more high-level logic, put code in the data models.
+
+      def self.hostname
+        'https://appstoreconnect.apple.com/iris/v1/'
```
Comment (armcburney) [inline spaceship/lib/spaceship/api/client.rb]: Question: is there a benefit to having a class method for this rather than a constant?

```ruby
class Client < Spaceship::Client
  HOSTNAME = 'https://appstoreconnect.apple.com/iris/v1/'

  # ...
end
```

Comment (armcburney) [reply spaceship/lib/spaceship/api/client.rb]: Nevermind, I didn't realize it was part of the interface. My apologies 😳 

___


```ruby
    # https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L57
    def self.hostname
      raise "You must implement self.hostname"
    end
```

**Review by armcburney — APPROVED** [review]
This looks good to me (with my limited knowledge of spaceship 🚀). I'd recommend another review from someone with more spaceship knowledge, but the code looks 💯!

File: spaceship/lib/spaceship/api/client.rb [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+          req.url("betaAppReviewSubmissions")
+          req.body = body.to_json
+          req.headers['Content-Type'] = 'application/json'
+        end
+        handle_response(response)
+      end
+
+      protected
+
+      def handle_response(response)
```
Comment (janpio) [inline spaceship/lib/spaceship/api/client.rb]: Do we want / have to duplicate this code? There already is response error handling code in so many places of spaceship, if possible we don't want to add _more_ before cleaning that up.

File: spaceship/lib/spaceship/api/client.rb [hunk 4]
```diff
@@ -0,0 +1,141 @@
+require_relative '../client'
+
+module Spaceship
+  module API
```
Comment (janpio) [inline spaceship/lib/spaceship/api/client.rb]: `ConnectAPI`?

**Review by snatchev — APPROVED** [review]
Great work. Very idiomatic spaceship code 😃

File: spaceship/lib/spaceship/api/client.rb (hunk 3 above)
Comment (snatchev) [reply spaceship/lib/spaceship/api/client.rb]: I think having this duplication is fine. This is because each client talks to a different host. As such, each host has _slightly_ different response, and error mechanics. It makes sense to be able to tweak those on a per-client basis.

**Comment by keith** [comment]
I believe this fix warrants the second half of this comment, do any maintainers agree?

**Comment by janpio** [comment]
I restored the branch so that the instructions in https://github.com/fastlane/fastlane/issues/13903#issuecomment-447535838 still work for now until this is released.
