### PR TITLE
[spaceship] add support for key creation scope in portal client

### LINKED ISSUE #29450: "No value was provided for the parameter 'scope'." when creating new key
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I am using the Spaceship library to create Push Notifications keys dinamically in my app. In these last few days, it seems that an unexpected error is popping up: `No value was provided for the parameter 'scope'.`. I also found another [issue in an Expo repository](https://github.com/expo/eas-cli/issues/2912) and it seems that this is related to the Apple API. 

##### Command executed

My script is using Spaceship this way:

```ruby
def create_key notifications_base_url, app_id, bundle_id, team_id, client
  ...

  key = client.create_key!(name: 'Notifications', service_configs: config)

  ...

  begin
    #do something with the key
  rescue Exception => e
    raise e
  end
end
```

### PR DESCRIPTION
**Pull request by danicunhac**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context
Apple updated their key creation API for v2, which requires a scope parameter to be sent when creating APNs

Resolves #29450 

### Description

Set configurations for each key type and default values to be compliant with Apple's v2 API, with new unit tests for each case and function.

### Testing Steps

For testing I used my own specific environment, which creates an APN key for a team based on the logged in client information. This could also be tested by calling the create key function directly.

### CODE REVIEW

File: spaceship/lib/spaceship/portal/portal_client.rb [hunk 1]
```diff
@@ -777,13 +777,14 @@ def download_key(id: nil)
...
 
       params = {
         name: name,
         serviceConfigurations: service_configs,
-        teamId: team_id
+        teamId: team_id,
+        scope: scope
       }
 
       response = request(:post, 'account/auth/key/create') do |req|
```
Comment (quinlanj) [inline spaceship/lib/spaceship/portal/portal_client.rb:790]: this needs to be `account/auth/key/v2/create` in the case of apns

File: spaceship/lib/spaceship/portal/portal_client.rb [hunk 2]
```diff
@@ -777,13 +777,14 @@ def download_key(id: nil)
       parse_response(response)
     end
 
-    def create_key!(name: nil, service_configs: nil)
+    def create_key!(name: nil, service_configs: nil, scope: nil)
       fetch_csrf_token_for_keys
 
       params = {
         name: name,
         serviceConfigurations: service_configs,
```
Comment (quinlanj) [inline spaceship/lib/spaceship/portal/portal_client.rb:785]: for the new api, for apns creation you need  to pass in:

```
        {
            "isNew": true,
            "serviceId": "U27F4V844T", // hard coded APNS_ID
            "identifiers": {},
            "environment": "all",
            "scope": "team"
        }
```

File: spaceship/lib/spaceship/portal/portal_client.rb [hunk 3]
```diff
@@ -777,16 +777,27 @@ def download_key(id: nil)
       parse_response(response)
     end
 
-    def create_key!(name: nil, service_configs: nil)
+    def create_key!(name: nil, service_configs: nil, scope: 'team')
       fetch_csrf_token_for_keys
 
+      # Format service configurations for APNS
+      service_configs_requests = (service_configs || []).map do |config|
```
Comment (quinlanj) [inline spaceship/lib/spaceship/portal/portal_client.rb:784]: For the other [different services](https://www.rubydoc.info/gems/fastlane/2.162.0/Spaceship/Portal/Key), DEVICE_CHECK_ID service will work if you add this to the service config request array: 
 ````
 {
      serviceId: YOUR_HARDCODED_DEVICE_CHECK_ID,  // DQ8HTZ7739
  }
```

havent figured new api shape for `MUSIC_KIT_ID` yet :(

Comment (danicunhac) [reply spaceship/lib/spaceship/portal/portal_client.rb]:
```json
{
    "name": "Test Device Check Key",
    "serviceConfigurationsRequests": [
        {
            "isNew": true,
            "serviceId": "DQ8HTZ7739",
            "identifiers": {}
        }
    ],
    "teamId": "9VYG78W35D"
}
```

Comment (danicunhac) [reply spaceship/lib/spaceship/portal/portal_client.rb]: MUSIC_KIT_ID
```json
[
    {
        "isNew": true,
        "serviceId": "6A7HVUVQ3M",
        "identifiers": {
            "music": [
                "4H4P58CJTN"
            ]
        }
    }
]
```

**Review by quinlanj — APPROVED** [review]

**Comment by danicunhac** [comment]
I have sent a commit updating the key creation process when using
```ruby
Spaceship::Portal::Key.create
```

**Comment by danicunhac** [comment]
@KrauseFx could we get a review here, please?

**Comment by danicunhac** [comment]
@joshdholtz

**Comment by mmuniz-asi** [comment]
@KrauseFx @joshdholtz can we get a review on this please? It would be great if we could get this into the next release.

**Comment by gholias** [comment]
Any updates on this PR? Im blocked by the problem

**Comment by tk185174** [comment]
I am also blocked by this? Do we know when this is going to be merged?

**Comment by tk185174** [comment]
This is a major blocker for us. Any idea when this will be live?

**Comment by jakub-przy** [comment]
For anybody who's blocked - while not ideal, we've been working around the issue by forcing our Fastlane set-up to use the branch from this PR, rather than one of the official ones:

`gem 'fastlane', git: 'https://github.com/danicunhac/fastlane.git', branch: 'fix/missing-scope-parameter'`
in the gemfile

**Comment by danicunhac** [comment]
@rogerluan 👀

**Comment by davidfrasch** [comment]
Would be really grateful if this could be reviewed and added to the latest fastlane release.

File: spaceship/docs/DeveloperPortal.md [hunk 4]
```diff
@@ -1,35 +1,41 @@
...
-    + [Receiving profiles](#receiving-profiles)
-    + [Create a Provisioning Profile](#create-a-provisioning-profile)
-    + [Repair all broken provisioning profiles](#repair-all-broken-provisioning-profiles)
-  * [Devices](#devices)
-  * [Enterprise](#enterprise)
-  * [Multiple Spaceships](#multiple-spaceships)
-  * [More cool things you can do](#more-cool-things-you-can-do)
-  * [Example Data](#example-data)
-- [License](#license)
+- [Developer Portal API](#developer-portal-api)
```
Comment (iBotPeaches) [inline spaceship/docs/DeveloperPortal.md]: Large amount of code shift here. Best I can tell its from adding "Developer Portal API" as a top level item, which is basically this table of contents itself. We could reduce churn here by removing that to return existing table of contents with just adding the new "Authentication Keys" section

File: spaceship/lib/spaceship/portal/portal_client.rb [hunk 5]
```diff
@@ -780,13 +781,39 @@ def download_key(id: nil)
     def create_key!(name: nil, service_configs: nil)
       fetch_csrf_token_for_keys
 
+      service_configs_requests = (service_configs || {}).map do |service_id, configs|
+        if service_id == Spaceship::Portal::Key::MUSIC_KIT_ID
+          {
+            serviceId: service_id,
+            isNew: true,
+            identifiers: configs[:identifiers] || {},
+            }
```
Comment (iBotPeaches) [inline spaceship/lib/spaceship/portal/portal_client.rb]: Could you double check this area? The indents on the `{}` look off.

**Review by iBotPeaches — COMMENTED** [review]
Do you have any documentation I can review for the /v2 split? Changing a root level spaceship endpoint is big, but reading the issues seems like this is the new path - I just can't quickly find any docs on that deprecation/knowledge about v2.

**Comment by danicunhac** [comment]
> Do you have any documentation I can review for the /v2 split? Changing a root level spaceship endpoint is big, but reading the issues seems like this is the new path - I just can't quickly find any docs on that deprecation/knowledge about v2.

Like I replied in the issue itself, I could not find documentation from Apple's side other than checking how the Portal was behaving, which was calling the v2 endpoint and passing data in that format.

File: spaceship/lib/spaceship/portal/portal_client.rb (hunk 5 above)
Comment (danicunhac) [reply spaceship/lib/spaceship/portal/portal_client.rb]: Fixed

File: spaceship/docs/DeveloperPortal.md (hunk 4 above)
Comment (danicunhac) [reply spaceship/docs/DeveloperPortal.md]: Fixed

**Comment by iBotPeaches** [comment]
I believe your test failures are just from being out of date. Rebase into latest or merge master into this to confirm.

**Comment by danicunhac** [comment]
@iBotPeaches should be good now

**Comment by iBotPeaches** [comment]
Okay I started looking at this and seems Expo stumbled upon this. They clearly patched this here: https://github.com/expo/eas-cli/pull/2916/changes and I wanted to see how, but the repository is private...

https://www.npmjs.com/package/@expo/apple-utils?activeTab=code
https://github.com/jamiesyme/expo-apple-utils/blob/master/build/index.js

Then the code is massively obfuscated.

**Comment by danicunhac** [comment]
> Okay I started looking at this and mini rant about Expo. They clearly patched this here: https://github.com/expo/eas-cli/pull/2916/changes and I wanted to see how, but the repository is private...
> 
> https://www.npmjs.com/package/@expo/apple-utils?activeTab=code https://github.com/jamiesyme/expo-apple-utils/blob/master/build/index.js
> 
> Then the code is massively obfuscated.

Maybe @quinlanj has some knowledge around that? I imagine they've pulled these changes down in order to patch it but the repository you shared seems to be quite old, doesn't it?

**Comment by iBotPeaches** [comment]
@EvanBacon - Probably weird to be pinged in a random repo, but I'm guessing you authored the private contribution to fix expo. Mind peeking this PR for a 1min peek? I'm guessing you would recognize the change you made in the obfuscated `apple-utils` to some degree.

**Review by iBotPeaches — APPROVED** [review]
