### PR TITLE
[actions] add App Store Connect API key to app_store_build_number action

### LINKED ISSUE #16620: latest_testflight_build_number can't authorize
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Currently I use latest_testflight_build_number to increase build number of my application with my CI. However, it can not authorize to Apple to get latest build number. I already set FASTLANE_APPLICATION_SPECIFIC_PASSWORD. I'm sure that password is correct because I can use it to upload to testflight.
##### Command executed

fastlane run latest_testflight_build_number
##### Complete output when running fastlane, including the stack trace and command used

Login to App Store Connect (xxx@gmail.com)
The login credentials for 'xxx@gmail.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> MacOS: 10.15 </pre>
  <pre> XCode: 11.3 </pre>
  <pre> fastlane: 2.149.1 </pre>
</details>

### PR DESCRIPTION
**Pull request by jakemwood**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #16620

We automate our version numbers using the app_store_build_action (via latest_testflight_build_number) in our CI workflow. This change allows us to use our Connect API key instead of relying on `FASTLANE_SESSION`.

I searched for an issue, but couldn't find one.

### Description

Following the example of other actions, this allows the `app_store_build_number` action to use App Store Connect API keys, instead of requiring a login using two-factor auth.

I tested this change primarily in my own repository by doing the following:

* Changing my `Gemfile` to point to my specific repo/branch containing these changes
* Running Fastlane in my CI environment (Github Actions)
* Confirmed that the action runs correctly and returns the expected results

### Testing Steps

Create a Fastfile which uses `app_store_connect_api_key`, and then passes the API key to `latest_testflight_build_number`, using the same options as other actions:

```
api_key = app_store_connect_api_key(
  key_id: "0000",
  issuer_id: "000,
  key_filepath: "./AuthKey.p8"
)
build_num = latest_testflight_build_number(
  api_key: api_key
)
```

You should expect this to work without needing to pass a `FASTLANE_SESSION` variable in a CI environment.

### CODE REVIEW

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 1]
```diff
@@ -104,6 +117,21 @@ def self.available_options
         user = CredentialsManager::AppfileConfig.try_fetch_value(:itunes_connect_id)
         user ||= CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
         [
+          FastlaneCore::ConfigItem.new(key: :api_key_path,
+                                       env_name: "PILOT_API_KEY_PATH",
```
[the remark this answers is not in the document]
Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/app_store_build_number.rb:121]: I'm going to come through later and find a good way to do a common `env_name` for all tools to use 😊 So let's go with this for now!

File: fastlane/lib/fastlane/actions/app_store_build_number.rb [hunk 2]
```diff
@@ -104,6 +117,21 @@ def self.available_options
...
+                                       verify_block: proc do |value|
+                                         UI.user_error!("Couldn't find API key JSON file at path '#{value}'") unless File.exist?(value)
+                                       end),
+          FastlaneCore::ConfigItem.new(key: :api_key,
+                                       env_name: "PILOT_API_KEY",
+                                       description: "Your App Store Connect API Key information (https://docs.fastlane.tools/app-store-connect-api/#use-return-value-and-pass-in-as-an-option)",
+                                       type: Hash,
+                                       optional: true,
+                                       sensitive: true,
+                                       conflicting_options: [:api_key_path, :username]),
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/app_store_build_number.rb:134]:
```suggestion
                                       conflicting_options: [:api_key_path]),
```

We can remove `:username` since there might be some conflicts if users have the ENVs defined for them for other actions 🤷

File: fastlane/lib/fastlane/actions/latest_testflight_build_number.rb [hunk 3]
```diff
@@ -37,6 +37,21 @@ def self.available_options
         user ||= CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
 
         [
+          FastlaneCore::ConfigItem.new(key: :api_key_path,
+                                       env_name: "PILOT_API_KEY_PATH",
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:41]:
```suggestion
                                       env_name: "APPSTORE_BUILD_NUMBER_API_KEY_PATH",
```

File: fastlane/lib/fastlane/actions/latest_testflight_build_number.rb [hunk 4]
```diff
@@ -37,6 +37,21 @@ def self.available_options
...
+                                       description: "Path to your App Store Connect API Key JSON file (https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file)",
+                                       optional: true,
+                                       conflicting_options: [:username],
+                                       verify_block: proc do |value|
+                                         UI.user_error!("Couldn't find API key JSON file at path '#{value}'") unless File.exist?(value)
+                                       end),
+          FastlaneCore::ConfigItem.new(key: :api_key,
+                                       env_name: "PILOT_API_KEY",
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:49]:
```suggestion
                                       env_name: "APPSTORE_BUILD_NUMBER_API_KEY",
```

File: fastlane/lib/fastlane/actions/latest_testflight_build_number.rb [hunk 5]
```diff
@@ -37,6 +37,21 @@ def self.available_options
         user ||= CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
 
         [
+          FastlaneCore::ConfigItem.new(key: :api_key_path,
+                                       env_name: "PILOT_API_KEY_PATH",
+                                       description: "Path to your App Store Connect API Key JSON file (https://docs.fastlane.tools/app-store-connect-api/#using-fastlane-api-key-json-file)",
+                                       optional: true,
+                                       conflicting_options: [:username],
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:44]:
```suggestion
                                       conflicting_options: [:api_key],
```

File: fastlane/lib/fastlane/actions/latest_testflight_build_number.rb [hunk 6]
```diff
@@ -37,6 +37,21 @@ def self.available_options
...
+                                       verify_block: proc do |value|
+                                         UI.user_error!("Couldn't find API key JSON file at path '#{value}'") unless File.exist?(value)
+                                       end),
+          FastlaneCore::ConfigItem.new(key: :api_key,
+                                       env_name: "PILOT_API_KEY",
+                                       description: "Your App Store Connect API Key information (https://docs.fastlane.tools/app-store-connect-api/#use-return-value-and-pass-in-as-an-option)",
+                                       type: Hash,
+                                       optional: true,
+                                       sensitive: true,
+                                       conflicting_options: [:api_key_path, :username]),
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:54]:
```suggestion
                                       conflicting_options: [:api_key_path]),
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
@jakemwood This is amazing! Thank you so much. I tested this out and it works great 😊  I just requested a few little nit picks on naming. If you don't mind making those changes that would be great! Looking forward to merging this ❤️

**Comment by jakemwood** [comment]
Looks like CircleCI is on the struggle bus with one of the test suites. Can someone re-trigger that build, or is there a PR comment we can use to re-build a PR? Thanks!

**Review by joshdholtz — APPROVED** [review]
This looks great! Thank you so much for making this change ❤️  Really appreciate the contribution!
