### PR TITLE
appledoc: accept multiple input paths

### LINKED ISSUE #11084: appledoc action does not allow specifying multiple input files
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

The `appledoc` command line tool accepts multiple input files as input. Each file must be separated by a space. Like this:

```
appledoc --no-create-docset --project-company="Test Company" --project-name="Test Project" --output ./apple_docs TestFramework/PublicClassTwo.h TestFramework/PublicClass.h
```

However, the appledoc action in Fastlane does not provide any mechanism for specifying multiple individual files. I tried specifying multiple file paths in the `input` parameter, enclosed in quotes, but this only causes the error shown below. The whole string gets quoted and messes it up.

Maybe the appledoc action could accept an array of strings for its `input` parameter?

##### Complete output when running fastlane, including the stack trace and command used

```
shocking@MacBook-Pro ~/Documents/SandboxApps/iOS/TestFramework 
$ fastlane test_appledocs --capture_output
[14:41:39]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-12-01 14:41:42.54]: Checking if there are any plugins that should be loaded...
INFO [2017-12-01 14:41:42.86]: Driving the lane 'test_appledocs' 🚀
INFO [2017-12-01 14:41:42.91]: ----------------------
INFO [2017-12-01 14:41:42.91]: --- Step: appledoc ---
INFO [2017-12-01 14:41:42.91]: ----------------------
INFO [2017-12-01 14:41:42.91]: Install using `brew install homebrew/boneyard/appledoc`
INFO [2017-12-01 14:41:42.92]: Generating documentation.
DEBUG [2017-12-01 14:41:42.92]: appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --no-create-docset --exit-threshold "2" "TestFramework/TestFramework.h TestFramework/PublicClass.h"
INFO [2017-12-01 14:41:42.92]: $ appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --no-create-docset --exit-threshold "2" "TestFramework/TestFramework.h TestFramework/PublicClass.h"
INFO [2017-12-01 14:41:42.98]: ▸ Caught: AppledocException: Path or file 'TestFramework/TestFramework.h TestFramework/PublicClass.h' doesn't exist!
INFO [2017-12-01 14:41:42.98]: ▸ appledoc version: 2.2.1 (build 1334)
WARN [2017-12-01 14:41:45.48]: Lane Context:
INFO [2017-12-01 14:41:45.48]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test_appledocs", :APPLEDOC_DOCUMENTATION_OUTPUT=>"/Users/shocking/Documents/SandboxApps/iOS/TestFramework/apple_docs"}
ERROR [2017-12-01 14:41:45.48]: Exit status of command 'appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --no-create-docset --exit-threshold "2" "TestFramework/TestFramework.h TestFramework/PublicClass.h"' was 1 instead of 0.
Caught: AppledocException: Path or file 'TestFramework/TestFramework.h TestFramework/PublicClass.h' doesn't exist!
appledoc version: 2.2.1 (build 1334)


INFO [2017-12-01 14:41:45.48]: Successfully generated documentation at path '/Users/shocking/Documents/SandboxApps/iOS/TestFramework/fastlane/README.md'
ERROR [2017-12-01 14:41:45.49]: fastlane finished with errors
ERROR [2017-12-01 14:41:46.55]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
Did you mean?  tap
WARN [2017-12-01 14:41:46.56]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-12-01 14:41:46.85]: Checking if there are any plugins that should be loaded...
```

### Captured Output

Command Used: `test_appledocs`
<details><summary>Output/Log</summary>

```


+------+----------+-------------+
|       fastlane summary        |
+------+----------+-------------+
| Step | Action   | Time (in s) |
+------+----------+-------------+
| 💥   | appledoc | 0           |
+------+----------+-------------+


Looking for related GitHub issues on fastlane/fastlane...
Search query: Exit status of command 'appledoc --output "./apple_docs" --project-name "Test Framework" --project-version "1.0" --project-company "Test Company" --company-id "com.testcompany" --create-html --no-create-docset --exit-threshold "2" "TestFramework/TestFramework.h TestFramework/PublicClass.h"' was 1 instead of 0.
Caught: AppledocException: Path or file 'TestFramework/TestFramework.h TestFramework/PublicClass.h' doesn't exist!
appledoc version: 2.2.1 (build 1334)


URL: https://api.github.com/search/issues?q=Exit%20status%20of%20command%20'appledoc%20--output%20%22./apple_docs%22%20--project-name%20%22Test%20Framework%22%20--project-version%20%221.0%22%20--project-company%20%22Test%20Company%22%20--company-id%20%22com.testcompany%22%20--create-html%20--no-create-docset%20--exit-threshold%20%222%22%20%22TestFramework/TestFramework.h%20TestFramework/PublicClass.h%22'%20was%201%20instead%20of%200.%0ACaught:%20AppledocException:%20Path%20or%20file%20'TestFramework/TestFramework.h%20TestFramework/PublicClass.h'%20doesn't%20exist!%0Aappledoc%20version:%202.2.1%20(build%201334)%0A%0A+repo:fastlane/fastlane


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.1                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.13.1 (17B1003)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
desc "Make appledocs for public headers only"
lane :test_appledocs do |options|
    appledoc(
        input: "TestFramework/TestFramework.h TestFramework/PublicClass.h", 
        output: "./apple_docs",
        project_name: "Test Framework",
        project_version: "1.0",
        project_company: "Test Company",
        company_id: "com.testcompany",
        create_html: true,
        create_docset: false,
        install_docset: false,
        options: "--no-create-docset"
      )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.68.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.3        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.3        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.59.0       |
| faraday                   | 0.13.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.2       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.16.0       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-12-01**
</details>

### PR DESCRIPTION
**Pull request by s-hocking**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This change adds the ability to specify multiple input source paths to the `appledoc` action. This is useful if your source code lives in a few different directories, or if you only want to document a subset of your source code.

fixes #11084.

Added two new test cases and ran this over my own projects as well.

### Description
The `input` parameter to the `appledoc` action now accepts paths as a single string or an array of strings. Each path string is quoted separately before being passed to the `appledoc` command line tool.

I'm a bit of a Ruby noob so please let me know if I've made any rookie mistakes.

### CODE REVIEW

File: fastlane/lib/fastlane/actions/appledoc.rb [hunk 1]
```diff
@@ -71,11 +71,24 @@ def self.run(params)
...
-        command = "appledoc #{cli_args}".strip + " \"#{params_hash[:input]}\""
+        input_cli_arg = input_param_to_cli_arg(params_hash[:input])
+        command = "appledoc #{cli_args}".strip + " " + input_cli_arg
         UI.verbose(command)
         Actions.sh command
       end
 
+      def self.input_param_to_cli_arg(input_param)
+        cli_arg = ""
+        if input_param.kind_of?(Array)
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/actions/appledoc.rb]: Hey @s-hocking, thanks for submitting this PR 👍 

When passing paths to the command line, we should use the built-in methods to do so. So instead of quoting the parameters (which will fail if file names include quotes), we can use `shellescape`. So looking at other fastlane files using this method, this would look something like

```ruby
input_param.map(&:shellescape).join(' ')
```

Since `input_param` can be either a String or an Array, you can use the following syntax:

```ruby
Array(input_param)
```

which should work for both arrays and strings. Let me know if that works 👍

Comment (s-hocking) [reply fastlane/lib/fastlane/actions/appledoc.rb]: Thanks for pointing me in the right direction @KrauseFx !

I'm now using `shellescape` for all input paths. However, all the other parameters that are passed to `appledoc` on the command line are still being quoted.

Is it reasonable to simply `shellescape` all parameters? Or should it be limited to file path parameters only?

**Comment by KrauseFx** [comment]
Hey @s-hocking, thanks for addressing my feedback, this looks 💯 now, and is a lot less code. Yah, ideally all parameters would be shell escaped. Have you tested this locally? If so, I'll go ahead and merge the code change 👍

File: fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj [hunk 2]
```diff
@@ -392,6 +392,7 @@
 			isa = XCBuildConfiguration;
 			buildSettings = {
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
+				CODE_SIGN_STYLE = Manual;
```
Comment (janpio) [inline fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj]: This shouldn't be here, should it?

**Review by janpio — DISMISSED** [review]

File: fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj (hunk 2 above)
Comment (s-hocking) [reply fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj]: Oh man, my bad. It looks like the fastlane test suite modifies this file during a run and I accidentally committed it.

**Comment by s-hocking** [comment]
@KrauseFx yep, I have tested this locally - this change is really helpful for one of my projects!

File: fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj (hunk 2 above)
Comment (janpio) [reply fastlane/spec/fixtures/xcodeproj/automatic_code_signing.xcodeproj/project.pbxproj]: Yep, we also noticed and have a issue/PR to either change this file or fix the problem. Super strange, probably Xcode doing stuff.

**Review by KrauseFx — APPROVED** [review]
🎷 Thanks @s-hocking ❤️
