### PR TITLE
[frameit] Speed up processing of skipped screenshots

### LINKED ISSUE #12976: Frameit is slow with non-matching images in the screenshots directory
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Frameit speed can be significantly improved when there are large amounts of screenshots captured but only a subset of them are filtered for framing.  

**Reproduce Steps**
1. Add a Framefile.json that has a single filter:
```
{
    "default": {
      "title": {
        "color": "#545454"
      },
      "background": "./background.jpg",
      "padding": 50
    },
    "data": [
      {
        "filter": "match",
        "title": {
            "text": "Title Text!"
        }
      }
    ]
  }
```
2. Add some valid device screenshots in the `fastlane/screenshots/en-US` directory (as would be captured in Snapshot). 
3. Rename one of these images to `match.png`, rename the others to something like `ignore*.png`
4. Run `fastlane frameit`

**Expected Results**
Frameit should skip loading into memory all the `ignore*.png` images as they are not targeted for framing.

**Actual Results**
Frameit takes time to load into memory all the non-matching images before it decides it doesn't need to frameit.

**Why Is This A Problem?**
When running Snapshot a common use case to have hundreds of screenshots that are captured for a variety of reasons (Manual review, Archival purposes, Diffs, etc).  Only a small subset of these screenshots may be intended to be used by Frameit for publishing to the App Store.  Because Frameit spends time loading all of the non-matching images that don't match the filters in the Framefile.json file it can significantly slow down CI build times when there are lots of images.

On my test machine it takes ~2 seconds per non-matching screenshot before Frameit decides to skip the file.  With hundreds of screenshots this becomes a problem. 

**Current Work Around**
In between Snapshot and Frameit extra logic can be added to copy only the relevant screenshots over to a separate directory specifically for Frameit.  This isn't ideal though as it duplicates the filter logic that already exists in `Framefile.json`.

**Proposed Solution**
Move the logic to check for filtered filenames in `frameit/lib/frameit/editor.rb` to happen BEFORE the image gets loaded into memory.  This would short-circuit the loading of the image into memory if it is not intended to be framed by just looking at the filename.  With a greenlight from the maintainers, I'm happy to submit a PR.  

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>~/dev/play/frameit-bug 🌮  bundle exec fastlane frame 
[✔] 🚀 
[10:12:37]: ------------------------------
[10:12:37]: --- Step: default_platform ---
[10:12:37]: ------------------------------
[10:12:37]: Driving the lane 'frame' 🚀
[10:12:37]: -------------------------------
[10:12:37]: --- Step: frame_screenshots ---
[10:12:37]: -------------------------------
[10:12:38]: Framing screenshots at path ./fastlane/screenshots (via frameit)
[10:12:38]: Using device frames version 'latest'
[⠇] Framing screenshot './en-US/ignore.png' [10:12:39]: Could not get title for screenshot ./en-US/ignore.png. Please provide one in your Framefile.json or title.strings
[⠏] Framing screenshot './en-US/ignore.png' [10:12:42]: Could not get title for screenshot ./en-US/ignore8.png. Please provide one in your Framefile.json or title.strings
[⠏] Framing screenshot './en-US/ignore6.png' [10:12:43]: Could not get title for screenshot ./en-US/ignore6.png. Please provide one in your Framefile.json or title.strings
[⠇] Framing screenshot './en-US/ignore8.png' [⠇] Framing screenshot './en-US/ignore7.png' [10:12:45]: Could not get title for screenshot ./en-US/ignore7.png. Please provide one in your Framefile.json or title.strings
[⠇] Framing screenshot './en-US/ignore5.png' [10:12:47]: Could not get title for screenshot ./en-US/ignore5.png. Please provide one in your Framefile.json or title.strings
[⠇] Framing screenshot './en-US/ignore4.png' [10:12:49]: Could not get title for screenshot ./en-US/ignore4.png. Please provide one in your Framefile.json or title.strings
[⠼] Framing screenshot './en-US/ignore7.png' [10:12:51]: Could not get title for screenshot ./en-US/ignore3.png. Please provide one in your Framefile.json or title.strings
[⠼] Framing screenshot './en-US/ignore8.png' [⠏] Framing screenshot './en-US/ignore3.png' [⠼] Framing screenshot './en-US/ignore7.png' [⠹] Framing screenshot './en-US/i[⠙] Framing screenshot './en-US/ignore3.png' [⠼] Framing screenshot './en-US/ignore.png' [⠦] Framing screenshot './en-US/ignore8.png' [⠦] Framing screenshot './en-US/ig[⠧] Framing screenshot './en-US/ignore8.png' [⠹] Framing screenshot './en-US/ignore3.png' [⠧] Framing screenshot './en-US/ignore7.png' [⠴] Framing screenshot './en-US/i[⠏] Framing screenshot './en-US/ignore7.png' [⠼] Framing screenshot './en-US/ignore3.png' [⠏] Framing screenshot './en-US/ignore8.png' [⠧] Framing screenshot './en-US/i[⠴] Framing screenshot './en-US/ignore7.png' [⠴] Framing screenshot './en-US/ignore8.png' [⠧] Framing screenshot './en-US/ignore5.png' [⠙] Framing screenshot './en-US/m[⠹] Framing screenshot './en-US/match.png' [⠏] Framing screenshot './en-US/ignore4.png' [⠇] Framing screenshot './en-US/ignore5.png' [⠙] Framing screenshot './en-US/ign[⠼] Framing screenshot './en-US/match.png' [⠙] Framing screenshot './en-US/ignore4.png' [⠦] Framing screenshot './en-US/ignore.png' [⠸] Framing screenshot './en-US/igno[⠦] Framing screenshot './en-US/ignore8.png' [⠙] Framing screenshot './en-US/ignore3.png' [⠏] Framing screenshot './en-US/ignore4.png' [⠦] Framing screenshot './en-US/i[⠋] Framing screenshot './en-US/match.png' [⠸] Framing screenshot './en-US/ignore6.png' [⠼] Framing screenshot './en-US/ignore8.png' [⠹] Framing screenshot './en-US/ign[✔] Framing screenshot './en-US/match.png' 
[10:13:02]: Added frame: '/Users/dvarner/dev/play/frameit-bug/fastlane/screenshots/en-US/match_framed.png'
[⠼] Framing screenshot './en-US/ignore.png' [⠦] Framing screenshot './en-US/ignore8.png' [⠴] Framing screenshot './en-US/ignore6.png' [⠇] Framing screenshot './en-US/ig[⠴] Framing screenshot './en-US/ignore2.png' [10:13:04]: Could not get title for screenshot ./en-US/ignore2.png. Please provide one in your Framefile.json or title.strings
[⠼] Framing screenshot './en-US/ignore7.png' 
+------+-------------------+-------------+g' 
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 27          |
+------+-------------------+-------------+

[10:13:04]: fastlane.tools finished successfully 🎉
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.13.5                                     |
| Ruby                        | 2.5.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.17.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.13.5 (17F77)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.5.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 9.4.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

  lane :frame do 
    frame_screenshots(white: true, path: './fastlane/screenshots')
  end


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier("[[APP_IDENTIFIER]]") # The bundle identifier of your app
# apple_id("[[APPLE_ID]]") # Your Apple email address


# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.100.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.2       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.13.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.21.2       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.5.9        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-07-27**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by piohhmy**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Fixes #12976 
The issue contains concrete reproduction steps and instructions.

### Description

**What's changed?**

* Created a helper method `should_skip?` to determine whether or not Frameit should skip over a Screenshot due to not having a `filter` defined for the screenshot in the Framefile.json. 
* Call the `should_skip?` method in the `Runner` class to avoid processing any screenshots if not necessary.  This was done in the Runner opposed to the Editor as this is the place the end user is notified about the start of  framing via the `Helper.show_loading_indicator("Framing Screenshot...")` call.  There is now a conditional there that instead displays to the user that the screenshot is being skipped if `should_skip?` returns true.  
* Removed the `UI.user_error` message in `editor.rb` when the title wasn't found as this message is now handled in `Runner` as mentioned above. A notable difference is that this is now a `UI.message` _not_ a `UI.user_error` as this scenario can be typical and shouldn't be flagged as an error.
* Moved the instantiation of the `Editor`/`MacEditor`  from `Screenshot` to `Runner` to give `Runner` the ability to call to `should_skip?` on the `Editor`

**Testing**

* Added unit tests
* Exploratory tests using a local project.  Confirmed no functional changes to framed images, only a significant increase in performance when dealing with screenshots that don't need to be processed by Frameit. Went from ~1.5/sec per screenshot -> near zero.  Makes a big difference when dealing with 100s of screenshots!

### CODE REVIEW

**Comment by piohhmy** [comment]
Hey @janpio !  I finally got around to #12976 as we talked on earlier in the year!  Could you take a look?  Thanks!

**Comment by piohhmy** [comment]
Heya @janpio!  Is there anything I can do on my end to help get this approved/merged?

**Comment by janpio** [comment]
Not really, someone has to find the time to understand and review this.

**Comment by piohhmy** [comment]
Ok, thanks!  Any suggestions on a reviewer?

File: frameit/lib/frameit/runner.rb [hunk 1]
```diff
@@ -35,11 +35,15 @@ def run(path, color = nil)
             next # we don't care about watches right now
           end
 
-          Helper.show_loading_indicator("Framing screenshot '#{full_path}'")
-
           begin
             screenshot = Screenshot.new(full_path, color)
-            screenshot.frame!
+            editor = screenshot.mac? ? MacEditor.new(screenshot) : Editor.new(screenshot)
```
Comment (janpio) [inline frameit/lib/frameit/runner.rb]: Hm, I overlooked this condition here at first. Can we somehow make this more explicit?

File: frameit/lib/frameit/editor.rb [hunk 2]
```diff
@@ -484,12 +491,6 @@ def fetch_text(type)
 
       # No string files, fallback to Framefile config
       text = fetch_config[type.to_s]['text'] if fetch_config[type.to_s] && fetch_config[type.to_s]['text'] && fetch_config[type.to_s]['text'].length > 0 # Ignore empty string
-
-      if type == :title && !text
-        # title is mandatory
-        UI.user_error!("Could not get title for screenshot #{screenshot.path}. Please provide one in your Framefile.json or title.strings")
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: Doesn't `user_error!` throw an exception? Wouldn't that mean that before your change this stopped if `title` was missing, and now those screenshots are just skipped?

Comment (janpio) [inline frameit/lib/frameit/editor.rb]: Also: Is this the only context where `fetch_text` is used? Or should this "exit" maybe be kept for other uses?

File: frameit/lib/frameit/editor.rb [hunk 3]
```diff
@@ -59,6 +62,10 @@ def rotation_for_device_orientation
       return 0
     end
 
+    def should_skip?
+      return should_add_title? && !fetch_text(:title)
```
Comment (janpio) [inline frameit/lib/frameit/editor.rb]: Why do we skip screenshots that do not have a title? 
Shouldn't the condition be "does not have a filter defined"?

**Review by janpio — COMMENTED** [review]
Read through the changes for a first understanding what is going on and left some questions:

File: frameit/lib/frameit/editor.rb (hunk 3 above)
Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: This is to preserve the existing behavior of "Easy Mode".  See https://github.com/fastlane/fastlane/blob/22f845f82317933635044d55d13d146c8afae431/frameit/lib/frameit/editor.rb#L40

Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: This way we only skip if we are in 'complex' mode *and* there is no `filter` defined for the screenshot in the Framefile.json

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: It does throw, but exceptions here are being caught and swallowed within a loop.  See https://github.com/fastlane/fastlane/blob/22f845f82317933635044d55d13d146c8afae431/frameit/lib/frameit/runner.rb#L47

Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: The only other place `fetch_text` is used is to get the value in the method `build_text_images`.

I think this is OK since as `fetch_text(:title)` will now return null if a title is not defined and then `build_text_images` would then just skip adding the title at: https://github.com/fastlane/fastlane/blob/22f845f82317933635044d55d13d146c8afae431/frameit/lib/frameit/editor.rb#L372.

And this scenario is also not currently possible to get into, since the framing will be skipped altogether via the new `should_skip?` check in `runner.rb`

File: frameit/lib/frameit/runner.rb (hunk 1 above)
Comment (piohhmy) [reply frameit/lib/frameit/runner.rb]: Sure, no problem.  Would it help if I just keep the same syntax as before ala:

```
 if screenshot.mac?	
        editor = MacEditor.new(screenshot)
      else	
        editor = Editor.new(screenshot)
      end
```

Comment (piohhmy) [reply frameit/lib/frameit/runner.rb]: ok, updated!

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (janpio) [reply frameit/lib/frameit/editor.rb]: Oh right, and then converted to a normal `UI.error` that is output (with its backtrace). So the only functional change here is that before it was a `UI.error` and now is a `UI.message`, correct?

File: frameit/lib/frameit/editor.rb (hunk 3 above)
Comment (janpio) [reply frameit/lib/frameit/editor.rb]: Could/should we rename `should_add_title?` to `is_complex_framing_mode?` or something similar maybe? Or do we loose the "what should happen then" context then?

> there is no `filter` defined for the screenshot in the Framefile.json

This bit I don't understand yet. Is this expressed via `!fetch_text(:title)` in the code? Isn't `title` one level deeper than `filter`?

**Comment by janpio** [comment]
Ok, just tested this.

Output from `master`:

```
λ bundle exec fastlane frame_complex --verbose
[✔] 🚀
DEBUG [2019-01-17 16:56:11.96]: Checking if there are any plugins that should be loaded...
DEBUG [2019-01-17 16:56:11.97]: Loading 'fastlane-plugin-versioning' plugin
INFO [2019-01-17 16:56:11.98]: gem 'fastlane-plugin-versioning' is already installed
+----------------------------+---------+--------------------------------------------------+
|                                      Used plugins                                       |
+----------------------------+---------+--------------------------------------------------+
| Plugin                     | Version | Action                                           |
+----------------------------+---------+--------------------------------------------------+
| fastlane-plugin-versioning | 0.3.4   | ci_build_number get_app_store_version_number     |
|                            |         | get_build_number_from_plist get_info_plist_path  |
|                            |         | get_version_number_from_git_branch               |
|                            |         | get_version_number_from_plist                    |
|                            |         | increment_build_number_in_plist                  |
|                            |         | increment_version_number_in_plist                |
+----------------------------+---------+--------------------------------------------------+

INFO [2019-01-17 16:56:12.19]: ------------------------------
INFO [2019-01-17 16:56:12.19]: --- Step: default_platform ---
INFO [2019-01-17 16:56:12.19]: ------------------------------
INFO [2019-01-17 16:56:12.25]: Driving the lane 'ios frame_complex' 🚀
INFO [2019-01-17 16:56:12.27]: -------------------------------
INFO [2019-01-17 16:56:12.27]: --- Step: frame_screenshots ---
INFO [2019-01-17 16:56:12.27]: -------------------------------
INFO [2019-01-17 16:56:12.62]: Framing screenshots at path ./fastlane/ (via frameit)
DEBUG [2019-01-17 16:56:12.63]: Parsing config file './screenshots/Framefile.json'
INFO [2019-01-17 16:56:12.64]: Using device frames version 'latest'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:12.79]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:56:12.80]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠏] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:15.92]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
[⠹] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:16.34]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
ERROR [2019-01-17 16:56:16.35]: Could not get title for screenshot ./screenshots/de-DE/iPhone 8-01StartScreen.png. Please provide one in your Framefile.json or title.strings

ERROR [2019-01-17 16:56:16.35]: Backtrace:
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:490:in `fetch_text'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `block in build_text_images'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `keep_if'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `build_text_images'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:292:in `put_title_into_background'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:131:in `complex_framing'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:35:in `frame!'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/screenshot.rb:131:in `frame!'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:42:in `block in run'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:28:in `each'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:28:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:13:in `block in run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:11:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:11:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        Fastfile:267:in `block (2 levels) in parsing_binding'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
        C:/Projects/Fastlane/fastlane/bin/fastlane:23:in `<top (required)>'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:16.49]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:56:16.50]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠹] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 16:56:20.93]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 16:56:20.93]: Adding text 'BRAINSTORMING'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:24.53]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 16:56:24.53]: Adding text 'Let Your Ideas Grow'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' [⠋] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 16:56:26.46]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x000000000659aa28>

[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' [⠇] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:27.65]: Text for image ./screenshots/de-DE/iPhone 8-Brainstorming.png is quite long, reducing font size by 47.1%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png'
INFO [2019-01-17 16:56:35.36]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Brainstorming_framed.png'
DEBUG [2019-01-17 16:56:35.54]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 16:56:35.55]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:39.55]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Organizing.png
DEBUG [2019-01-17 16:56:39.56]: Adding text 'ORGANIZING'
[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:42.04]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Organizing.png
DEBUG [2019-01-17 16:56:42.05]: Adding text 'Think Content, Not Layout'
[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:43.14]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000007be8758>

DEBUG [2019-01-17 16:56:43.14]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000007be8758>

[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 16:56:44.10]: Text for image ./screenshots/de-DE/iPhone 8-Organizing.png is quite long, reducing font size by 49.6%
[⠧] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' [✔] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png'
INFO [2019-01-17 16:56:51.33]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Organizing_framed.png'
DEBUG [2019-01-17 16:56:51.45]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:56:51.46]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:55.45]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Sharing.png
DEBUG [2019-01-17 16:56:55.45]: Adding text 'SHARING'
[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 16:56:58.10]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Sharing.png
DEBUG [2019-01-17 16:56:58.10]: Adding text 'Spread Your Ideas Easily'
[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:56:59.44]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000007d29248>

DEBUG [2019-01-17 16:56:59.44]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000007d29248>

[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 16:57:00.39]: Text for image ./screenshots/de-DE/iPhone 8-Sharing.png is quite long, reducing font size by 41.2%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png'
INFO [2019-01-17 16:57:06.60]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Sharing_framed.png'
[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:06.67]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:57:06.68]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠇] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 16:57:09.74]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Styling.png
DEBUG [2019-01-17 16:57:09.75]: Adding text 'STYLING'
[⠼] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:12.00]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Styling.png
DEBUG [2019-01-17 16:57:12.01]: Adding text 'Say It Your Way'
[⠏] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 16:57:13.04]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008a9d668>

[⠧] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' [⠹] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:13.88]: Text for image ./screenshots/de-DE/iPhone 8-Styling.png is quite long, reducing font size by 19.6%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png'
INFO [2019-01-17 16:57:19.89]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Styling_framed.png'
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:19.99]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:20.00]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:21.91]: Falling back to text in Framefile.json as there was nothing specified in the keyword.strings file
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:22.11]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
ERROR [2019-01-17 16:57:22.11]: Could not get title for screenshot ./screenshots/en-US/iPhone 8-01StartScreen.png. Please provide one in your Framefile.json or title.strings

ERROR [2019-01-17 16:57:22.11]: Backtrace:
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/interface.rb:141:in `user_error!'
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:490:in `fetch_text'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `block in build_text_images'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `keep_if'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:365:in `build_text_images'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:292:in `put_title_into_background'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:131:in `complex_framing'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/editor.rb:35:in `frame!'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/screenshot.rb:131:in `frame!'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:42:in `block in run'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:28:in `each'
        C:/Projects/Fastlane/fastlane/frameit/lib/frameit/runner.rb:28:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:13:in `block in run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:11:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/frame_screenshots.rb:11:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
        Fastfile:267:in `block (2 levels) in parsing_binding'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane.rb:33:in `call'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/runner.rb:45:in `execute'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
        C:/Projects/Fastlane/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
        C:/Projects/Fastlane/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:113:in `take_off'
        C:/Projects/Fastlane/fastlane/bin/fastlane:23:in `<top (required)>'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `load'
        C:/Ruby24-x64/lib/ruby/gems/2.4.0/bin/fastlane:23:in `<main>'
[⠏] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:22.20]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:57:22.21]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠧] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:25.43]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 16:57:25.43]: Adding text 'BRAINSTORMING'
[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:27.37]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 16:57:27.37]: Adding text 'Let Your Ideas Grow'
[⠴] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:28.45]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000008c0f640>

[⠸] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:29.25]: Text for image ./screenshots/en-US/iPhone 8-Brainstorming.png is quite long, reducing font size by 47.1%
[⠏] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' [⠙] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' [⠋] Framing screenshot './scr[✔] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png'
INFO [2019-01-17 16:57:35.18]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Brainstorming_framed.png'
[⠹] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:35.25]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:57:35.26]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:38.49]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Organizing.png
DEBUG [2019-01-17 16:57:38.49]: Adding text 'ORGANIZING'
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:40.72]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Organizing.png
DEBUG [2019-01-17 16:57:40.72]: Adding text 'Think Content, Not Layout'
[⠋] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:41.97]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000008da1a58>

DEBUG [2019-01-17 16:57:41.97]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008da1a58>

[⠇] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:42.78]: Text for image ./screenshots/en-US/iPhone 8-Organizing.png is quite long, reducing font size by 49.6%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png'
INFO [2019-01-17 16:57:48.81]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Organizing_framed.png'
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:48.91]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 16:57:48.92]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠏] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:52.22]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Sharing.png
DEBUG [2019-01-17 16:57:52.22]: Adding text 'SHARING'
[⠦] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:54.18]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Sharing.png
DEBUG [2019-01-17 16:57:54.18]: Adding text 'Spread Your Ideas Easily'
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 16:57:55.23]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000008f877f0>

DEBUG [2019-01-17 16:57:55.23]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008f877f0>

[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:57:56.01]: Text for image ./screenshots/en-US/iPhone 8-Sharing.png is quite long, reducing font size by 41.2%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png'
INFO [2019-01-17 16:58:02.14]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Sharing_framed.png'
[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:58:02.32]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 16:58:02.33]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:58:05.33]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Styling.png
DEBUG [2019-01-17 16:58:05.34]: Adding text 'STYLING'
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-01StartScreen.png' DEBUG [2019-01-17 16:58:07.55]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Styling.png
DEBUG [2019-01-17 16:58:07.55]: Adding text 'Say It Your Way'
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 16:58:08.50]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x00000000064a8cc8>

[⠧] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 16:58:09.48]: Text for image ./screenshots/en-US/iPhone 8-Styling.png is quite long, reducing font size by 19.6%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png'
INFO [2019-01-17 16:58:15.69]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Styling_framed.png'
INFO [2019-01-17 16:58:15.69]: Successfully generated documentation at path 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/README.md'

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 123         |
+------+-------------------+-------------+

DEBUG [2019-01-17 16:58:15.75]: All plugins are up to date
INFO [2019-01-17 16:58:15.75]: fastlane.tools finished successfully 🎉
DEBUG [2019-01-17 16:58:15.75]: All plugins are up to date
```

Output from this PR branch:

```
λ bundle exec fastlane frame_complex --verbose
[✔] 🚀
DEBUG [2019-01-17 20:59:10.07]: Checking if there are any plugins that should be loaded...
DEBUG [2019-01-17 20:59:10.08]: Loading 'fastlane-plugin-versioning' plugin
INFO [2019-01-17 20:59:10.08]: gem 'fastlane-plugin-versioning' is already installed
+----------------------------+---------+--------------------------------------------------+
|                                      Used plugins                                       |
+----------------------------+---------+--------------------------------------------------+
| Plugin                     | Version | Action                                           |
+----------------------------+---------+--------------------------------------------------+
| fastlane-plugin-versioning | 0.3.4   | ci_build_number get_app_store_version_number     |
|                            |         | get_build_number_from_plist get_info_plist_path  |
|                            |         | get_version_number_from_git_branch               |
|                            |         | get_version_number_from_plist                    |
|                            |         | increment_build_number_in_plist                  |
|                            |         | increment_version_number_in_plist                |
+----------------------------+---------+--------------------------------------------------+

INFO [2019-01-17 20:59:10.27]: ------------------------------
INFO [2019-01-17 20:59:10.27]: --- Step: default_platform ---
INFO [2019-01-17 20:59:10.27]: ------------------------------
INFO [2019-01-17 20:59:10.37]: Driving the lane 'ios frame_complex' 🚀
INFO [2019-01-17 20:59:10.38]: -------------------------------
INFO [2019-01-17 20:59:10.38]: --- Step: frame_screenshots ---
INFO [2019-01-17 20:59:10.38]: -------------------------------
INFO [2019-01-17 20:59:10.69]: Framing screenshots at path ./fastlane/ (via frameit)
DEBUG [2019-01-17 20:59:10.69]: Parsing config file './screenshots/Framefile.json'
INFO [2019-01-17 20:59:10.70]: Using device frames version 'latest'
DEBUG [2019-01-17 20:59:10.73]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 20:59:11.31]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-01-17 20:59:11.31]: Skipping framing of screenshot ./screenshots/de-DE/iPhone 8-01StartScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-01-17 20:59:11.31]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 20:59:11.69]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠹] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 20:59:18.30]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 20:59:18.32]: Adding text 'BRAINSTORMING'
[⠼] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 20:59:21.45]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 20:59:21.53]: Adding text 'Let Your Ideas Grow'
[⠼] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 20:59:23.25]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x000000000876f040>

[⠹] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 20:59:24.33]: Text for image ./screenshots/de-DE/iPhone 8-Brainstorming.png is quite long, reducing font size by 47.1%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Brainstorming.png'
INFO [2019-01-17 20:59:29.89]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Brainstorming_framed.png'
DEBUG [2019-01-17 20:59:29.89]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 20:59:30.19]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 20:59:32.74]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Organizing.png
DEBUG [2019-01-17 20:59:32.75]: Adding text 'ORGANIZING'
[⠏] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 20:59:34.54]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Organizing.png
DEBUG [2019-01-17 20:59:34.55]: Adding text 'Think Content, Not Layout'
[⠇] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 20:59:35.55]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x00000000088a2d40>

DEBUG [2019-01-17 20:59:35.55]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x00000000088a2d40>

[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png' DEBUG [2019-01-17 20:59:36.10]: Text for image ./screenshots/de-DE/iPhone 8-Organizing.png is quite long, reducing font size by 49.6%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Organizing.png'
INFO [2019-01-17 20:59:40.97]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Organizing_framed.png'
DEBUG [2019-01-17 20:59:40.97]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 20:59:41.20]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠸] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 20:59:43.80]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Sharing.png
DEBUG [2019-01-17 20:59:43.80]: Adding text 'SHARING'
[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 20:59:45.66]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Sharing.png
DEBUG [2019-01-17 20:59:45.66]: Adding text 'Spread Your Ideas Easily'
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 20:59:46.64]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x00000000089fec20>

DEBUG [2019-01-17 20:59:46.65]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x00000000089fec20>

[⠇] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png' DEBUG [2019-01-17 20:59:47.48]: Text for image ./screenshots/de-DE/iPhone 8-Sharing.png is quite long, reducing font size by 41.2%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Sharing.png'
INFO [2019-01-17 20:59:53.19]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Sharing_framed.png'
DEBUG [2019-01-17 20:59:53.20]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠋] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 20:59:53.48]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠴] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 20:59:57.01]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/de-DE/iPhone 8-Styling.png
DEBUG [2019-01-17 20:59:57.01]: Adding text 'STYLING'
[⠦] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 20:59:59.30]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/de-DE/iPhone 8-Styling.png
DEBUG [2019-01-17 20:59:59.30]: Adding text 'Say It Your Way'
[⠼] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:00.12]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008b3c290>

[⠙] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:00.88]: Text for image ./screenshots/de-DE/iPhone 8-Styling.png is quite long, reducing font size by 19.6%
[✔] Framing screenshot './screenshots/de-DE/iPhone 8-Styling.png'
INFO [2019-01-17 21:00:06.36]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/de-DE/iPhone 8-Styling_framed.png'
DEBUG [2019-01-17 21:00:06.37]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 21:00:06.54]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-01-17 21:00:06.54]: Skipping framing of screenshot ./screenshots/en-US/iPhone 8-01StartScreen.png.  No title provided in your Framefile.json or title.strings.
DEBUG [2019-01-17 21:00:06.55]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 21:00:06.89]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 21:00:10.82]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 21:00:10.83]: Adding text 'BRAINSTORMING'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 21:00:13.42]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Brainstorming.png
DEBUG [2019-01-17 21:00:13.42]: Adding text 'Let Your Ideas Grow'
[⠸] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 21:00:14.96]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000008cfa730>

[⠋] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png' DEBUG [2019-01-17 21:00:15.73]: Text for image ./screenshots/en-US/iPhone 8-Brainstorming.png is quite long, reducing font size by 47.1%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Brainstorming.png'
INFO [2019-01-17 21:00:20.65]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Brainstorming_framed.png'
DEBUG [2019-01-17 21:00:20.65]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠋] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png' DEBUG [2019-01-17 21:00:20.88]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠸] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png' DEBUG [2019-01-17 21:00:23.59]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Organizing.png
DEBUG [2019-01-17 21:00:23.59]: Adding text 'ORGANIZING'
[⠸] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png' DEBUG [2019-01-17 21:00:25.69]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Organizing.png
DEBUG [2019-01-17 21:00:25.69]: Adding text 'Think Content, Not Layout'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png' DEBUG [2019-01-17 21:00:26.53]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x000000000586da80>

DEBUG [2019-01-17 21:00:26.53]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x000000000586da80>

[⠧] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png' DEBUG [2019-01-17 21:00:27.23]: Text for image ./screenshots/en-US/iPhone 8-Organizing.png is quite long, reducing font size by 49.6%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Organizing.png'
INFO [2019-01-17 21:00:32.20]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Organizing_framed.png'
DEBUG [2019-01-17 21:00:32.21]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 21:00:32.54]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠇] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 21:00:35.76]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Sharing.png
DEBUG [2019-01-17 21:00:35.76]: Adding text 'SHARING'
[⠦] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 21:00:37.99]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Sharing.png
DEBUG [2019-01-17 21:00:37.99]: Adding text 'Spread Your Ideas Easily'
[⠧] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 21:00:39.09]: Trim box for key "keyword" is adjusted to align top: #<Frameit::Trimbox:0x0000000008c9afb0>

DEBUG [2019-01-17 21:00:39.10]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008c9afb0>

[⠦] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png' DEBUG [2019-01-17 21:00:39.99]: Text for image ./screenshots/en-US/iPhone 8-Sharing.png is quite long, reducing font size by 41.2%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Sharing.png'
INFO [2019-01-17 21:00:45.32]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Sharing_framed.png'
DEBUG [2019-01-17 21:00:45.32]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
[⠙] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:45.66]: Looking for Apple iPhone 7 Matte Black and found 1 template(s)
[⠧] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:48.64]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the keyword of ./screenshots/en-US/iPhone 8-Styling.png
DEBUG [2019-01-17 21:00:48.65]: Adding text 'STYLING'
[⠼] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:50.42]: Using C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/./fonts/AlwynNewRounded-Regular.otf as font the title of ./screenshots/en-US/iPhone 8-Styling.png
DEBUG [2019-01-17 21:00:50.42]: Adding text 'Say It Your Way'
[⠸] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:51.31]: Trim box for key "keyword" is adjusted to align bottom: #<Frameit::Trimbox:0x0000000008adc408>

[⠇] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png' DEBUG [2019-01-17 21:00:51.90]: Text for image ./screenshots/en-US/iPhone 8-Styling.png is quite long, reducing font size by 19.6%
[✔] Framing screenshot './screenshots/en-US/iPhone 8-Styling.png'
INFO [2019-01-17 21:00:56.95]: Added frame: 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/en-US/iPhone 8-Styling_framed.png'
INFO [2019-01-17 21:00:56.95]: Successfully generated documentation at path 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/README.md'

+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 106         |
+------+-------------------+-------------+

DEBUG [2019-01-17 21:00:56.98]: All plugins are up to date
INFO [2019-01-17 21:00:56.98]: fastlane.tools finished successfully 🎉
DEBUG [2019-01-17 21:00:56.98]: All plugins are up to date
```

---

One difference seems to be that previously the screenshots that didn't have proper data in the `Framefile.json` were still framed in a device frame, now they are skipped completely (as the code makes the decision to skip much earlier).

I think this is actually more the intended behavior anyway, do you agree @piohhmy?

---

Another thing I noticed is that the output for the command with `--verbose` is a bit confusing for the skipped screenshots now:

```
DEBUG [2019-01-17 20:59:10.73]: Parsing config file 'C:/Projects/Fastlane/fastlane-e2e-tests/ios/fastlane/screenshots/Framefile.json'
DEBUG [2019-01-17 20:59:11.31]: Falling back to text in Framefile.json as there was nothing specified in the title.strings file
INFO [2019-01-17 20:59:11.31]: Skipping framing of screenshot ./screenshots/de-DE/iPhone 8-01StartScreen.png.  No title provided in your Framefile.json or title.strings.
```

The first two `DEBUG` outputs are fully without context, as the spinner wasn't started before. Unfortunately I don't know how to solve this better :/

**Comment by janpio** [comment]
Speed comparison (with 40 unmatched and 4 matched screenshots):

master:
```
+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 266         |
+------+-------------------+-------------+
```

PR:
```
+------+-------------------+-------------+
|            fastlane summary            |
+------+-------------------+-------------+
| Step | Action            | Time (in s) |
+------+-------------------+-------------+
| 1    | default_platform  | 0           |
| 2    | frame_screenshots | 114         |
+------+-------------------+-------------+
```

🏎 💨

**Review by janpio — APPROVED** [review]
Does its job and improves the speed significantly if you have non-matched screenshots!

Can be merged after the rest of the code comments are resolved/discussed.

File: frameit/lib/frameit/editor.rb (hunk 2 above)
Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: Correct! And, as you mentioned, no longer printing the backtrace on the `UI.message`

File: frameit/lib/frameit/editor.rb (hunk 3 above)
Comment (piohhmy) [reply frameit/lib/frameit/editor.rb]: That's a great suggestion, I'll rename `should_add_title?` to `is_complex_framing_mode?` 👍 

Regarding the check for `filter`, you're right in that it is being done by the check on `!fetch_text(:title)`.  What's happening is the conditional that was deleted on line 487 (previously that was throwing a `user_error`) is now the conditional here to see if it should skip.

**Comment by piohhmy** [comment]
@janpio Great! Should be good to go now. 🙌

**Comment by joshdholtz** [comment]
@piohhmy Reviewing and testing out now for ya 💪

**Review by joshdholtz — APPROVED** [review]
Looks 💯 to me too! 💪
