### PR TITLE
[action] Only add derived data parameter if it's set, and command is update, build…

### LINKED ISSUE #15145: Carthage archive action fails with "Unrecognized arguments: --derived-data" in case setup_jenkins action is used
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
As part of https://github.com/fastlane/fastlane/issues/4173 back in 2016, carthage action has been provided with an option for supporting carthage parameter ```--derived-data```. This parameter is not supported as part of ```carthage archive``` command, but fastlane is adding it automatically to the execution parameters in case ```setup_jenkins``` action is used via env variable ```FL_CARTHAGE_DERIVED_DATA``` (which is fine for ```bootstrap```, ```update``` and ```build``` actions, just not for ```archive``` action :/)

Hence, IMHO the ```derived-data``` parameter should only by added by ```setup_jenkins``` action for the carthage commands that support it.

##### Command executed
````
    setup_jenkins(
        unlock_keychain: false,
        set_code_signing_identity: false,
        result_bundle: true
    )
    [...]
    carthage(
        command: "bootstrap",   ## --> working fine
        use_binaries: false,
        no_build: true,
        project_directory: project_directory,
        platform: platform,
        configuration: configuration
    )
    carthage(
        command: "build",       ## --> working fine
        use_binaries: false,
        no_skip_current: true,
        project_directory: project_directory,
        platform: platform,
        configuration: configuration
    )
    [...]
    frameworks = ["libPhoneNumberiOS", "ObjectMapper", "OHHTTPStubs", "Version", "BoschEsSdk"]
    carthage(
        command: "archive",     ## --> failing in case setup_jenkins is used
        frameworks: frameworks,
        project_directory: "MyOwnSdk",
        output: "./MyOwnSdk/Carthage/Build/iOS/MyApp-#{version_number}-#{build_number}-SDK-ios-#{configuration}.framework.zip"
    )
````

##### Complete output when running fastlane, including the stack trace and command used
````
$ fastlane release
[...]
INFO [2019-08-05 18:06:55.06]: -----------------------------------------------------
INFO [2019-08-05 18:06:55.06]: Step: Switch to ios archive_sdk_framework_carthage lane
INFO [2019-08-05 18:06:55.06]: -----------------------------------------------------
INFO [2019-08-05 18:06:55.06]: Cruising over to lane 'ios archive_sdk_framework_carthage' 🚖
INFO [2019-08-05 18:06:55.06]: ----------------------
INFO [2019-08-05 18:06:55.06]: --- Step: carthage ---
INFO [2019-08-05 18:06:55.06]: ----------------------
INFO [2019-08-05 18:06:55.06]: $ carthage archive libPhoneNumberiOS ObjectMapper OHHTTPStubs Version MyOwnSdk --output ./MyOwnSdk/Carthage/Build/iOS/MyApp-1.4.0-3-SDK-ios-Production.framework.zip --derived-data /Users/jenkins/workspace/myapp-ios-sdk/build-release-sdk/MyOwnSdk/derivedData --project-directory MyOwnSdk
INFO [2019-08-05 18:06:55.44]: ▸ Unrecognized arguments: --derived-data
````

##### For reference: Carthage help on command line parameters
````
$ carthage help archive
Archives built frameworks into a zip that Carthage can use

[--output (string)]
        the path at which to create the zip file (or blank to infer it from the first one of the framework names)

[--project-directory (string)]
        the directory containing the Carthage project

[--color (color)]
        whether to apply color and terminal formatting (one of 'auto', 'always', or 'never')

[<framework names…>]
        the names of the built frameworks to archive without any extension (or blank to pick up the frameworks in the current project built by `--no-skip-current`)
````

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.14.5                                         |
| Ruby                        | 2.4.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.20.1 (Apple Git-117)              |
| Installation Source         | /usr/local/rvm/gems/ruby-2.4.1/bin/fastlane     |
| Host                        | Mac OS X 10.14.5 (18F132)                       |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.4.1/lib            |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode10.2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
[...] ## relevant parts provided above
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
[...]
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.128.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 2.3.2        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| commander-fastlane        | 4.4.6        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| json                      | 2.0.2        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| faraday_middleware        | 0.12.2       |
| jwt                       | 2.1.0        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.2.7        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| signet                    | 0.11.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| memoist                   | 0.16.0       |
| googleauth                | 0.6.7        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.15.0       |
| emoji_regex               | 0.1.1        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| tty-screen                | 0.6.5        |
| faraday                   | 0.15.4       |
| openssl                   | 2.0.3        |
| highline                  | 1.7.10       |
| io-console                | 0.4.6        |
| excon                     | 0.62.0       |
| CFPropertyList            | 3.0.0        |
| mini_portile2             | 2.4.0        |
| nokogiri                  | 1.10.2       |
| plist                     | 3.4.0        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.10.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| fastimage                 | 2.1.5        |
| bundler                   | 2.0.2        |
| unicode-display_width     | 1.4.0        |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| psych                     | 2.2.2        |
| retriable                 | 3.1.2        |
| mime-types                | 3.2.2        |
| mime-types-data           | 3.2018.0812  |
| simctl                    | 1.6.5        |
</details>

*generated on:* **2019-08-06**
</details>

### PR DESCRIPTION
**Pull request by iOSGeekster**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
This pull request fixes #15145 

### Description
Changed the parameter checking in the carthage action, to only add `derived_data` parameter if it is set, and the command isn't `archive`.

### CODE REVIEW

**Comment by iOSGeekster** [comment]
@googlebot I signed it!

File: fastlane/lib/fastlane/actions/carthage.rb [hunk 1]
```diff
@@ -11,8 +11,13 @@ def self.run(params)
...
         if command_name == "archive" && params[:frameworks].count > 0
           cmd.concat(params[:frameworks])
-        elsif ["update", "build", "bootstrap"].include?(command_name) && params[:dependencies].count > 0
-          cmd.concat(params[:dependencies])
+        elsif ["update", "build", "bootstrap"].include?(command_name)
+          if params[:dependencies].count > 0
+            cmd.concat(params[:dependencies])
+          end
+          if params[:derived_data]
+            cmd << "--derived-data #{params[:derived_data].shellescape}"
```
Comment (mollyIV) [inline fastlane/lib/fastlane/actions/carthage.rb]: I printed out all `carthage` commands:

```
Available commands:

   archive           Archives built frameworks into a zip that Carthage can use
   bootstrap         Check out and build the project's dependencies
   build             Build the project's dependencies
   checkout          Check out the project's dependencies
   copy-frameworks   In a Run Script build phase, copies each framework specified by a SCRIPT_INPUT_FILE and/or SCRIPT_INPUT_FILE_LIST environment variables into the built app bundle
   fetch             Clones or fetches a Git repository ahead of time
   help              Display general or command-specific help
   outdated          Check for compatible updates to the project's dependencies
   update            Update and rebuild the project's dependencies
   validate          Validate that the versions in Cartfile.resolved are compatible with the Cartfile requirements
   version           Display the current version of Carthage
```

and checked if only `update, build and bootstrap` support `--derived-data` parameter - indeed these are the only ones 👍 

FYI you can check that by calling `carthage help command_name` command, i.e. 

```
$ carthage help fetch                                            
Clones or fetches a Git repository ahead of time

[--color (color)]
        whether to apply color and terminal formatting (one of 'auto', 'always', or 'never')

(URL)
        the Git repository that should be cloned or fetched
```

File: fastlane/lib/fastlane/actions/carthage.rb [hunk 2]
```diff
@@ -11,8 +11,13 @@ def self.run(params)
 
         if command_name == "archive" && params[:frameworks].count > 0
           cmd.concat(params[:frameworks])
-        elsif ["update", "build", "bootstrap"].include?(command_name) && params[:dependencies].count > 0
-          cmd.concat(params[:dependencies])
+        elsif ["update", "build", "bootstrap"].include?(command_name)
```
Comment (mollyIV) [inline fastlane/lib/fastlane/actions/carthage.rb]: Maybe we could add a comment to highlight that `update, build and bootstrap` are the only ones that support `--derived-data` parameter? 

```suggestion
        # "update", "build" and "bootstrap" are the only commands that support "--derived-data" parameter
        elsif ["update", "build", "bootstrap"].include?(command_name)
```

File: fastlane/lib/fastlane/actions/carthage.rb [hunk 3]
```diff
@@ -11,8 +11,13 @@ def self.run(params)
...
+          if params[:dependencies].count > 0
+            cmd.concat(params[:dependencies])
```
Comment (mollyIV) [inline fastlane/lib/fastlane/actions/carthage.rb]: A minor suggestion to make it a bit more Ruby way 😉 

```suggestion
            cmd.concat(params[:dependencies]) if params[:dependencies].count > 0
```

File: fastlane/lib/fastlane/actions/carthage.rb (hunk 1 above)
Comment (mollyIV) [inline fastlane/lib/fastlane/actions/carthage.rb]: A minor suggestion to make it a bit more Ruby way 😉
```suggestion
            cmd << "--derived-data #{params[:derived_data].shellescape}" if params[:derived_data]
```

**Review by mollyIV — CHANGES_REQUESTED** [review]
Hey @iOSGeekster 👋 
Thank you for making these changes 🙌 

We've been asking about the unit testing: 
> I'm not that familiar with rspec, so I need some hints of how to test the functionality. I guess the test somehow has to mock the ENV variable set by setup_jenkins?

Basically we have [`carthage_spec.rb`](https://github.com/fastlane/fastlane/blob/master/fastlane/spec/actions_specs/carthage_spec.rb) file where you can find the tests for the `carthage` action. To execute the tests only for this action, you need to call `$ bundle exec fastlane/spec/actions_specs/carthage_spec.rb` from a fastlane project's root catalog. 

I this we could test that even though `derived_data` parameter is set, it is not taken into account when a `command` parameter is set to `archive`.

```
carthage_spec.rb

context "when specify derived_data" do
    context "when command is archive" do
        let(:command) { 'archive' }
        # TODO: Check if `derived_data` is set, it is not taken into account for `archive` command. 
        expect(result).to eq("carthage archive")
    end
end
```

Feel free to ping me if something's not clear 😉 

BTW I think it would be helpful to add the tests against supported parameters for each command. May be a good candidate for a separate issue 😉 Thoughts @janpio ?

**Comment by iOSGeekster** [comment]
> I this we could test that even though `derived_data` parameter is set, it is not taken into account when a `command` parameter is set to `archive`.
> 
> ```
> carthage_spec.rb
> 
> context "when specify derived_data" do
>     context "when command is archive" do
>         let(:command) { 'archive' }
>         # TODO: Check if `derived_data` is set, it is not taken into account for `archive` command. 
>         expect(result).to eq("carthage archive")
>     end
> end
> ```
> 
> Feel free to ping me if something's not clear 😉
> 

Thanks for the comments @mollyIV 
I'll be sure to give it a go, later today 👍

File: fastlane/lib/fastlane/actions/carthage.rb (hunk 2 above)
Comment (iOSGeekster) [reply fastlane/lib/fastlane/actions/carthage.rb]: Great idea!

File: fastlane/lib/fastlane/actions/carthage.rb (hunk 3 above)
Comment (iOSGeekster) [reply fastlane/lib/fastlane/actions/carthage.rb]: Ah nice! Ruby isn't my "primary language".

File: fastlane/lib/fastlane/actions/carthage.rb [hunk 4]
```diff
@@ -11,8 +11,14 @@ def self.run(params)
 
         if command_name == "archive" && params[:frameworks].count > 0
           cmd.concat(params[:frameworks])
-        elsif ["update", "build", "bootstrap"].include?(command_name) && params[:dependencies].count > 0
-          cmd.concat(params[:dependencies])
+        # "update", "build" and "bootstrap" are the only commands that support "--derived-data" parameter
+        elsif ["update", "build", "bootstrap"].include?(command_name)
+          if params[:dependencies].count > 0
```
Comment (mollyIV) [inline fastlane/lib/fastlane/actions/carthage.rb]: Sorry if the previous suggestion wasn't clear - we do not need `if params[:dependencies].count > 0` anymore. 
```
elsif ["update", "build", "bootstrap"].include?(command_name)
    cmd.concat(params[:dependencies]) if params[:dependencies].count > 0
    cmd << "--derived-data #{params[:derived_data].shellescape}" if params[:derived_data]
end
```

**Comment by janpio** [comment]
> BTW I think it would be helpful to add the tests against supported parameters for each command. May be a good candidate for a separate issue 😉 Thoughts @janpio ?

I agree with both. Would be good to have, but also we don't want to ask @iOSGeekster to implement that just because he jumped in to fix something else - so new issue would be best. And if @iOSGeekster now feels motivated, feel free to have a go at it of course :)

File: fastlane/lib/fastlane/actions/carthage.rb (hunk 4 above)
Comment (iOSGeekster) [reply fastlane/lib/fastlane/actions/carthage.rb]: Oh right! My bad. Thanks. I'll take care of that.

**Comment by mollyIV** [comment]
> Would be good to have, but also we don't want to ask @iOSGeekster to implement that just because he jumped in to fix something else - so new issue would be best.

Absolutely 👍 

FYI @janpio @iOSGeekster I created a separate issue:  https://github.com/fastlane/fastlane/issues/15173 🎉

**Comment by iOSGeekster** [comment]
@mollyIV I've now added a test case which should cover the issue.

**Review by mollyIV — APPROVED** [review]
Looks good 🎉 

I did some manual testing too - regression tests and `archive` command tests 👍 

Thanks again for fixing it  🙇

**Comment by iOSGeekster** [comment]
> Looks good 🎉
> 
> I did some manual testing too - regression tests and `archive` command tests 👍
> 
> Thanks again for fixing it 🙇

Awesome, no problem. And thanks for the guidance 🙌
