### PR TITLE
[actions] github action - add Bearer authentication option

### LINKED ISSUE #16618: GITHUB_TOKEN provided by Github Action does not work in fastlane action GithubApiAction
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When I want to use an action that interacts with Github (like `set_github_release` for instance), I can't make it work on Github Actions with the [GITHUB_TOKEN](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token) provided by Github.

However, if I generate a [personal token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), and pass it to the `api_token` parameter, the command works fine.

To my understanding, it seems the action `GithubApiAction` uses a [Basic](https://github.com/fastlane/fastlane/blob/31ff25306872292d02459d226c8fd982912c1e8a/fastlane/lib/fastlane/actions/github_api.rb#L208) authorization whereas the curl example on the official github page uses a [Bearer](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example-calling-the-rest-api) authorization.

##### Command executed
Non working call:
```
set_github_release(
  repository_name: "my_repo",
  api_token: ..., # Token from github, i.e secrets.GITHUB_TOKEN
  ...
)
```

Working call:
```
set_github_release(
  repository_name: "my_repo",
  api_token: ..., # Personal access token
 ...
)
```

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> Repository my_repo cannot be found, please double check its name and that you provided a valid API token (GITHUB_API_TOKEN) </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.15.5                                          |
| Ruby                        | 2.6.6                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.27.0                               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.15.5 (19F101)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.6/2.6.6_1/lib           |
| OpenSSL Version             | OpenSSL 1.1.1f  31 Mar 2020                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode_11.5.app/Contents/Developer/ |
| Xcode Version               | 11.5                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.15.0  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| bundler                   | 2.1.4        |
| CFPropertyList            | 3.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| atomos                    | 0.1.3        |
| aws-eventstream           | 1.1.0        |
| aws-partitions            | 1.329.0      |
| aws-sigv4                 | 1.1.4        |
| jmespath                  | 1.4.0        |
| aws-sdk-core              | 3.100.0      |
| aws-sdk-kms               | 1.34.1       |
| aws-sdk-s3                | 1.68.1       |
| babosa                    | 1.0.3        |
| claide                    | 1.0.3        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| digest-crc                | 0.5.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| dotenv                    | 2.7.5        |
| emoji_regex               | 1.0.1        |
| excon                     | 0.74.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 1.0.1        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.2       |
| multi_json                | 1.14.1       |
| os                        | 1.1.0        |
| signet                    | 0.14.0       |
| googleauth                | 0.12.0       |
| httpclient                | 2.8.3        |
| mini_mime                 | 1.0.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.2        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| google-cloud-storage      | 1.26.2       |
| json                      | 2.3.0        |
| mini_magick               | 4.10.1       |
| multi_xml                 | 0.6.0        |
| plist                     | 3.5.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.8.0        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.16.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-changelog | 0.15.0       |
</details>

*generated on:* **2020-06-16**
</details>

### PR DESCRIPTION
**Pull request by dcacenabes**
Add bearer authentication option for both github_api and set_github_release actions

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #16618 
Currently the set_github_release and github_api actions only support basic authentication. This is not aligned with match, for instance, where both basic and bearer based authentication are supported:
https://github.com/fastlane/fastlane/blob/7af498a573bdb153431343c4f177b20f347e74e0/match/lib/match/options.rb#L166

By adding this change, it is possible to specify a bearer token. A use case for example is if you're using a github app to connect instead of a Personal Access Token.

### Description
Added an api_bearer parameter to both set_github_release and github_api actions.
In set_github_release, the bearer is propagated all the way down to the github_api action calls.
In the github_api action, if the api_bearer param was passed, it will add Authentication header "Bearer + token" to the http request.

Changes have been tested by using my local branch of Fastlane in a Gemfile and running a lane that interacts with it.

### Testing Steps

```
Fastlane::Actions::GithubApiAction.run(
          server_url: 'https://api.github.com',
          api_bearer: 'A_valid_bearer',
          http_method: 'GET',
          path: "repos/fastlane/fastlane/releases"
        ) do |result|
      puts result
    end
```

### CODE REVIEW

**Comment by dcacenabes** [comment]
@rogerluan As discussed here: https://github.com/fastlane/fastlane/issues/16618#issuecomment-739256202
This adds support for bearer authentication

File: fastlane/lib/fastlane/actions/github_api.rb [hunk 1]
```diff
@@ -89,12 +89,22 @@ def available_options
...
                                          default_value: ENV["GITHUB_API_TOKEN"],
                                          default_value_dynamic: true,
-                                         optional: false),
+                                         optional: true),
+            FastlaneCore::ConfigItem.new(key: :api_bearer,
+                                         env_name: "FL_GITHUB_API_BEARER",
+                                         sensitive: true,
+                                         code_gen_sensitive: true,
+                                         is_string: true,
+                                         description: "Use a Bearer authorization token (Usually generated by Github Apps). This will override api_token",
```
Comment (rogerluan) [inline fastlane/lib/fastlane/actions/github_api.rb:104]:
```suggestion
                                         description: "Use a Bearer authorization token. Usually generated by Github Apps, e.g. GitHub Actions GITHUB_TOKEN environment variable",
```

Not sure if it's worth mentioning that "This will override api_token" because you added this parameter as a conflicting option `api_token`, so if the user provides both, it will fail early.

**Review by rogerluan — CHANGES_REQUESTED** [review]
Hey, thank you for opening this PR, and for tagging me! ❤️ 

I'm a little bit concerned about these 2 being conflicting values, and one of them having a non-nil default value. I don't actually know in which scenarios this can cause issues, but looks like there are scenarios that it would be an issue 😅 I'll leave it up to @joshdholtz to judge this part better 😊 

I made two copy suggestions - let me know what you think about them! 
Other than that, the PR looks good overall 🎉

**Comment by dcacenabes** [comment]
> Hey, thank you for opening this PR, and for tagging me! ❤️
> 
> I'm a little bit concerned about these 2 being conflicting values, and one of them having a non-nil default value. I don't actually know in which scenarios this can cause issues, but looks like there are scenarios that it would be an issue 😅 I'll leave it up to @joshdholtz to judge this part better 😊
> 
> I made two copy suggestions - let me know what you think about them!
> Other than that, the PR looks good overall 🎉

Hi @rogerluan, thanks for your feedback. To be honest I was not too sure about how to express the dependencies between the 2 parameters. I wanted to have the change be transparent to anyone already using the feature. I thought some people might already be using the environment variable for the api key, so removing it as a default value seemed like it could break their builds. Really looking forward to get @joshdholtz 's feedback on this one!

**Comment by joshdholtz** [comment]
Will look at this soon. Just had a baby this week so trying figure parenting things out 🤷‍♂️

**Review by rogerluan — APPROVED** [review]
Thanks for addressing the changes I had requested :) LGTM aside from the pending "conflicting options" of the parameters, but we can keep that discussion on going 😊 

Approved 🚀

**Review by joshdholtz — APPROVED** [review]
This is 🔥 Thank you so much for adding this! Really appreciate the contribution ❤️

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Comment by ThilekSilvadorai-TomTom** [comment]
Can we also have it for `create_pull_request`

**Comment by dcacenabes** [comment]
> Can we also have it for `create_pull_request`

Based on the current implementation it should be fairly easy to replicate. Feel free to open a PR

**Comment by ThilekSilvadorai-TomTom** [comment]
@dcacenabes will look into creating a PR for that change.

**Comment by thilek** [comment]
Here you go https://github.com/fastlane/fastlane/pull/17972

**Comment by dcacenabes** [comment]
Wow that was fast. I feel it makes sense to bring this api_bearer change not only to pull requests and releases, but to all possible github actions. I'll give it a go when I have free time so that the tooling is consistent.

**Comment by ThilekSilvadorai-TomTom** [comment]
@dcacenabes my own PR at work was blocked because lack of this parameter, so i was motivated to get this done asap :P so the motivation was there. I'm also thinking about adding an action to get the access token in first place for GitHub App based on this https://docs.github.com/en/free-pro-team@latest/developers/apps/authenticating-with-github-apps. For the moment i have ruby method doing it for me.
