### PR TITLE
[gym] Add `export_xcargs` option

### LINKED ISSUE #6761: [gym] `xcargs` ignored in export phase
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running gym with the `xcargs` option (e.g. `gym xcargs: 'MYARG=myvalue'`) these arguments are only passed to the first call to `xcodebuild`, i.e. the "archive phase", but not to the second call, i.e. the "export phase".
In my case I need to pass the same set of arguments to both `xcodebuild` invocations. However, I could imagine that one wants to have more fine-grained control. Hence, I suggest to add a `export_xcargs` option to gym which are only added in the export phase.

I do already have a PR ready, let me know when I'm allowed to submit.
## Issue Details

I added the following test to `fastlane/gym/spec/package_command_generator_xcode7_spec.rb`:

``` ruby
    it "works with the example project and additional parameters" do
      xcargs_hash = { DEBUG: "1", BUNDLE_NAME: "Example App" }
      xcargs = xcargs_hash.map do |k, v|
        "#{k.to_s.shellescape}=#{v.shellescape}"
      end.join ' '

      options = { project: "./examples/standard/Example.xcodeproj", xcargs: xcargs }
      Gym.config = FastlaneCore::Configuration.create(Gym::Options.available_options, options)

      result = Gym::PackageCommandGeneratorXcode7.generate
      expect(result).to eq([
                             "/usr/bin/xcrun #{Gym::XcodebuildFixes.wrap_xcodebuild.shellescape} -exportArchive",
                             "-exportOptionsPlist '#{Gym::PackageCommandGeneratorXcode7.config_path}'",
                             "-archivePath #{Gym::BuildCommandGenerator.archive_path.shellescape}",
                             "-exportPath '#{Gym::PackageCommandGeneratorXcode7.temporary_output_path}'",
                             "DEBUG=1 BUNDLE_NAME=Example\\ App",
                             ""
                           ])
    end
```

It fails with the following error message:

```
Failures:

  1) Gym Gym::PackageCommandGeneratorXcode7 works with the example project and additional parameters
     Failure/Error: expect(result).to eq([

       expected: ["/usr/bin/xcrun /Users/nubbel/Workspace/github/fastlane/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive", "-exportOptionsPlist '/var/folders/cx/wbfd58hx7530klknkqm5b80w0000gn/T/gym_config20161026-8787-1cm49vn.plist'", "-archivePath /Users/nubbel/Library/Developer/Xcode/Archives/2016-10-26/ExampleProductName\\ 2016-10-26\\ 22.02.35.xcarchive", "-exportPath '/var/folders/cx/wbfd58hx7530klknkqm5b80w0000gn/T/gym_output20161026-8787-4zb81z'", "DEBUG=1 BUNDLE_NAME=Example\\ App", ""]
            got: ["/usr/bin/xcrun /Users/nubbel/Workspace/github/fastlane/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive", "-exportOptionsPlist '/var/folders/cx/wbfd58hx7530klknkqm5b80w0000gn/T/gym_config20161026-8787-1cm49vn.plist'", "-archivePath /Users/nubbel/Library/Developer/Xcode/Archives/2016-10-26/ExampleProductName\\ 2016-10-26\\ 22.02.35.xcarchive", "-exportPath '/var/folders/cx/wbfd58hx7530klknkqm5b80w0000gn/T/gym_output20161026-8787-4zb81z'", ""]

       (compared using ==)
     # ./spec/package_command_generator_xcode7_spec.rb:36:in `block (3 levels) in <top (required)>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.12.1 |
| Ruby | 2.1.3 |
| Bundler? | true |
| Xcode Path | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.10.0 |
| Installation Source | /Users/nubbel/.rvm/gems/ruby-2.1.3@flgym/bin/fastlane |
| Host | Mac OS X 10.12.1 (16B2338c) |
| Ruby Lib Dir | /Users/nubbel/.rvm/rubies/ruby-2.1.3/lib |
| OpenSSL Version | OpenSSL 1.0.1j 15 Oct 2014 |
### fastlane files:

<details><summary>

`./fastlane/Fastfile`</summary>

``` ruby
# Fetch and use the latest Fastfile from the fastlane main repository
import("../../fastlane/fastlane/Fastfile")
```

</details>

**No Appfile found**
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| match | 0.10.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

| Plugin | Version | Update-Status |
| --- | --- | --- |
| fastlane-plugin-ruby | 0.1.3 | ✅ Up-To-Date |
| fastlane-plugin-clubmate | 0.1.0 | ✅ Up-To-Date |
| fastlane-plugin-sharethemeal | 0.1.9 | ✅ Up-To-Date |

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| rake | 11.3.0 |
| i18n | 0.7.0 |
| json | 1.8.3 |
| minitest | 5.9.1 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| activesupport | 4.2.7.1 |
| addressable | 2.4.0 |
| ast | 2.3.0 |
| babosa | 1.0.2 |
| builder | 3.2.2 |
| bundler | 1.13.6 |
| colored | 1.2 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| security | 0.1.3 |
| credentials_manager | 0.16.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| multi_json | 1.12.1 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| terminal-table | 1.4.5 |
| fastlane_core | 0.53.0 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| faraday_middleware | 0.10.0 |
| fastimage | 1.6.8 |
| multi_xml | 0.5.5 |
| claide | 1.0.1 |
| coderay | 1.1.1 |
| docile | 1.1.5 |
| simplecov-html | 0.10.0 |
| simplecov | 0.12.0 |
| tins | 1.12.0 |
| term-ansicolor | 1.4.0 |
| thor | 0.19.1 |
| coveralls | 0.8.15 |
| safe_yaml | 1.0.4 |
| crack | 0.4.3 |
| diff-lcs | 1.2.5 |
| dotenv | 2.1.1 |
| mini_magick | 4.5.1 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| jwt | 1.5.6 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| hurley | 0.2 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| google-api-client | 0.9.19 |
| terminal-notifier | 1.7.1 |
| word_wrap | 1.0.0 |
| xcode-install | 2.0.8 |
| xcodeproj | 1.3.3 |
| fastlane-plugin-clubmate | 0.1.0 |
| fastlane-plugin-ruby | 0.1.3 |
| netrc | 0.11.0 |
| rest-client | 2.0.0 |
| stm_api | 0.1.6 |
| fastlane-plugin-sharethemeal | 0.1.9 |
| method_source | 0.8.2 |
| parser | 2.3.1.4 |
| powerpack | 0.1.1 |
| slop | 3.6.0 |
| pry | 0.10.4 |
| rainbow | 2.1.0 |
| rspec-support | 3.1.2 |
| rspec-core | 3.1.7 |
| rspec-expectations | 3.1.2 |
| rspec-mocks | 3.1.3 |
| rspec | 3.1.0 |
| rspec_junit_formatter | 0.2.3 |
| ruby-progressbar | 1.8.1 |
| unicode-display_width | 1.1.1 |
| rubocop | 0.44.1 |
| webmock | 1.19.0 |
| yard | 0.8.7.6 |

</details>

_generated on:_ **2016-10-26**
</details>

### PR DESCRIPTION
**Pull request by nubbel**
Thanks for contributing to _fastlane_! Before you submit your pull request, please make sure to check the following boxes:

- [x] Run `bundle exec rspec` from the subdirectory of each tool you modified. Alternatively, run `rake test_all` from the root directory.
- [x] Run `bundle exec rubocop -a` to ensure the code style is valid
- [x] Read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] We currently don't accept new actions, please publish a plugin instead, more information in [Plugins.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

Before submitting a pull request, we appreciate if you create an issue first to discuss the change :+1:

fixes #6761

### CODE REVIEW

File: gym/lib/gym/generators/package_command_generator_xcode7.rb [hunk 1]
```diff
@@ -22,15 +22,14 @@ def generate
...
 
+        options = []
         options << "-exportOptionsPlist '#{config_path}'"
         options << "-archivePath #{BuildCommandGenerator.archive_path.shellescape}"
         options << "-exportPath '#{temporary_output_path}'"
-
-        if Gym.config[:toolchain]
-          options << "-toolchain '#{Gym.config[:toolchain]}'"
-        end
+        options << "-toolchain '#{Gym.config[:toolchain]}'" if Gym.config[:toolchain]
```
Comment (milch) [inline gym/lib/gym/generators/package_command_generator_xcode7.rb]: Cleaning up the code as you go, I love it 😍  Although you did create the `config` var above, so it might be worthwhile to replace `Gym.config` with that.

File: gym/lib/gym/options.rb [hunk 2]
```diff
@@ -123,6 +123,14 @@ def self.plain_options
                                      conflict_block: proc do |value|
                                        UI.user_error!("'#{value.key}' must be false to use 'export_options'")
                                      end),
+        FastlaneCore::ConfigItem.new(key: :export_xcargs,
+                                     env_name: "GYM_EXPORT_XCARGS",
+                                     description: "Pass additional arguments to xcodebuild for the export phase. Be sure to quote the setting names and values e.g. OTHER_LDFLAGS=\"-ObjC -lstdc++\"",
```
Comment (milch) [inline gym/lib/gym/options.rb]: Please also update the regular `xcargs` action description to reflect that that only applies to the build phase.

**Review by milch — CHANGES_REQUESTED** [review]
Looking good! Just some tiny changes needed before we can merge 🚀

File: gym/lib/gym/generators/package_command_generator_xcode7.rb (hunk 1 above)
Comment (nubbel) [inline gym/lib/gym/generators/package_command_generator_xcode7.rb]: Sorry, that was my intention in the first place. I'll change that quickly. Thanks!

File: gym/lib/gym/options.rb (hunk 2 above)
Comment (nubbel) [inline gym/lib/gym/options.rb]: Good point. Thanks!

**Review by milch — APPROVED** [review]

**Comment by nubbel** [comment]
@milch Thanks for your feedback. I've updated the PR with the changes you suggested.
Regarding the option descriptions, I changed the wording to "build" and "package" phase such that it is on par with the command generators.

Cheers 🍻 (🍼 might be more appropriate though)

**Comment by milch** [comment]
@nubbel Thanks for taking the time to contribute by fixing this issue! Yup, that wording sounds good. 

Cheers! 🍻  

(Also, next time to make it easier on us we'd prefer if you made a separate commit to address the review issues instead of `--amend`ing. That makes it easier for us to review the second time as we only have to look at the changes)

**Comment by nubbel** [comment]
@milch Thanks for merging!

> (Also, next time to make it easier on us we'd prefer if you made a separate commit to address the review issues instead of --amending. That makes it easier for us to review the second time as we only have to look at the changes)

Sorry about that, I'm addicted to force push 😜. I wanted to keep the history clean and forgot that Github can now squash commits before merge. Will keep that in mind for my next PR.

**Comment by milch** [comment]
Yeah no worries, it happens all the time - the "Squash and Merge" feature is still pretty new after all. It's totally fine for smaller PRs like this one, though!

**Comment by KrauseFx** [comment]
This is a great addition 👍
