### PR TITLE
[fastlane_core] build watcher fails when build_beta_detail is nil - fix

### LINKED ISSUE #19330: [upload_to_testflight][pilot] "undefined method 'processed?'" for macOS build
<!-- Thanks for helping fastlane! Before you submit your issue, please make sure you followed our checklist and check the appropriate boxes by putting an x in the [ ]: [x] -->

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I got error in _upload_to_testflight_ on `Waiting for the build to show up in the build list` stage
Error is ``` /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:159:in `processed?': \e[31m[!] undefined method 'processed?' for nil:NilClass\e[0m (NoMethodError)```

##### Command executed
<!-- The command you executed on the command line that resulted in an error -->
`upload_to_testflight(changelog: changelog, app_platform: "osx")`

##### Complete output when running fastlane, including the stack trace and command used
<!-- 
You can use `--capture_output` as the last command line argument for many commands to get that collected for you. Otherwise, please do it manually.
Caution: The output of `--capture_output` could contain sensitive data such as application ids, certificate ids, or email addresses. Please make sure you double check the output and replace anything sensitive you don't wish to submit in the issue 
-->

<details>
  <pre> 

```
[17:26:00]: ----------------------------------
549[17:26:00]: --- Step: upload_to_testflight ---
550[17:26:00]: ----------------------------------
551[17:26:00]: Login to App Store Connect (_[DELETED]_)
552[17:26:02]: Login successful
553[17:26:07]: Ready to upload new build to TestFlight (App: ._[DELETED]_.)...
554[17:26:07]: Fetching password for transporter from environment variable named `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`
555[17:26:08]: Going to upload updated app to App Store Connect
556[17:26:08]: This might take a few minutes. Please don't interrupt the script.
557[17:26:46]: iTunes Transporter successfully finished its job
558[17:26:46]: --------------------------------------------------------------------
559[17:26:46]: Successfully uploaded package to App Store Connect. It might take a few minutes until it's visible online.
560[17:26:46]: --------------------------------------------------------------------
561[17:26:46]: Successfully uploaded the new binary to App Store Connect
562[17:26:46]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
563[17:26:46]: Note that if `skip_waiting_for_build_processing` is used but a `changelog` is supplied, this process will wait for the build to appear on AppStoreConnect, update the changelog and then skip the remaining of the processing steps.
564[17:26:46]: $ xar -C /var/folders/xq/3nsr0qsn5cx5wvr875qgdkx80000gn/T/d20210902-66329-kf5hq0 -xf /Users/hseapps/builds/dEnP68g9/0/hse-apps/apps/HSEAppX/HSE\ App\ X.pkg
565[17:26:46]: $ xar -C /var/folders/xq/3nsr0qsn5cx5wvr875qgdkx80000gn/T/d20210902-66329-1ieb92u -xf /Users/hseapps/builds/dEnP68g9/0/hse-apps/apps/HSEAppX/HSE\ App\ X.pkg
566[17:26:46]: Waiting for processing on... app_id: 1527320487, app_version: 1.11, build_version: 3317, platform: MAC_OS
567[17:26:47]: Read more information on why this build isn't showing up yet - https://github.com/fastlane/fastlane/issues/14997
568[17:26:47]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
569[17:27:18]: Waiting for the build to show up in the build list - this may take a few minutes (check your email for processing issues if this continues)
570+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
571|                                                                                                                                                                                               Lane Context                                                                                                                                                                                                |
572+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
573| PLATFORM_NAME                      |                                                                                                                                                                                                                                                                                                                                                                      |
574| LANE_NAME                          | macos                                                                                                                                                                                                                                                                                                                                                                |
575| SIGH_PROFILE_TYPE                  | app-store                                                                                                                                                                                                                                                                                                                                                            |
576| MATCH_PROVISIONING_PROFILE_MAPPING | {_[DELETED]_} |
577| BUILD_NUMBER                       | 3317                                                                                                                                                                                                                                                                                                                                                                 |
578| PKG_OUTPUT_PATH                    | /Users/hseapps/builds/dEnP68g9/0/hse-apps/apps/HSEAppX/HSE App X.pkg                                                                                                                                                                                                                                                                                                 |
579| XCODEBUILD_ARCHIVE                 | /Users/hseapps/Library/Developer/Xcode/Archives/2021-09-02/HSE App X 2021-09-02 17.22.36.xcarchive                                                                                                                                                                                                                                                                   |
580| FL_CHANGELOG                       | bundle bump (fix fastlane)                                                                                                                                                                                                                                                                                                                                           |
581|                                    |                                                                                                                                                                                                                                                                                                                                                                      
_[DELETED]_
_[DELETED]_                                                                                                                                                                                                                                                                                                                                            |
608+------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
609+------+----------------------------+-------------+
610|                fastlane summary                 |
611+------+----------------------------+-------------+
612| Step | Action                     | Time (in s) |
613+------+----------------------------+-------------+
614| 1    | match                      | 8           |
615| 2    | cocoapods                  | 77          |
616| 3    | increment_build_number     | 1           |
617| 4    | build_mac_app              | 211         |
618| 5    | changelog_from_git_commits | 0           |
619| 💥   | upload_to_testflight       | 117         |
620+------+----------------------------+-------------+
621[17:27:57]: fastlane finished with errors
622Looking for related GitHub issues on fastlane/fastlane...
623➡️  `error=undefined method `status' for nil:NilClass` while waiting for screenshots to appear
624    https://github.com/fastlane/fastlane/issues/17831 [closed] 9 💬
625    20 Feb 2021
626➡️  undefined method `login' for Spaceship::Tunes:Module
627    https://github.com/fastlane/fastlane/issues/15495 [closed] 7 💬
628    13 Feb 2020
629➡️  [deliver] submit_build, promote build to production: undefined method `select_build' for nil:NilClass
630    https://github.com/fastlane/fastlane/issues/13809 [closed] 36 💬
631    28 Jan 2020
632and 15 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60processed%3F%27%20for%20nil&type=Issues&utf8=✓
633🔗  You can ⌘ + double-click on links to open them directly in your browser.
634bundler: failed to load command: fastlane (/Users/hseapps/.gem/ruby/2.7.0/bin/fastlane)
**635/Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:159:in `processed?': \e[31m[!] undefined method `processed?' for nil:NilClass\e[0m (NoMethodError)**
636	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:166:in `report_status'
637	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:44:in `block in wait_for_build_processing_to_be_complete'
638	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:36:in `loop'
639	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:36:in `wait_for_build_processing_to_be_complete'
640	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:112:in `wait_for_build_processing_to_be_complete'
641	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:68:in `upload'
642	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
643	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
644	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
645	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
646	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
647	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
648	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
649	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
650	from Fastfile:32:in `block in parsing_binding'
651	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
652	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
653	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
654	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
655	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
656	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
657	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
658	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
659	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
660	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
661	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
662	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
663	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
664	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
665	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
666	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
667	from /Users/hseapps/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
668	from /Users/hseapps/.gem/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
669	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `load'
670	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `kernel_load'
671	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
672	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
673	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
674	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
675	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
676	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
677	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
678	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
679	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
680	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
681	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
682	from /Users/hseapps/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
683	from /Users/hseapps/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
684/Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:159:in `processed?': undefined method `processed?' for nil:NilClass (NoMethodError)
685	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:166:in `report_status'
686	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:44:in `block in wait_for_build_processing_to_be_complete'
687	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:36:in `loop'
688	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/build_watcher.rb:36:in `wait_for_build_processing_to_be_complete'
689	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:112:in `wait_for_build_processing_to_be_complete'
690	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/pilot/lib/pilot/build_manager.rb:68:in `upload'
691	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
692	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
693	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
694	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
695	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `chdir'
696	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
697	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
698	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
699	from Fastfile:32:in `block in parsing_binding'
700	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane.rb:33:in `call'
701	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
702	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
703	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
704	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
705	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
706	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
707	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
708	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
709	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
710	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
711	from /Users/hseapps/.gem/ruby/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
712	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
713	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
714	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
715	from /Users/hseapps/.gem/ruby/2.7.0/gems/fastlane-2.193.1/bin/fastlane:23:in `<top (required)>'
716	from /Users/hseapps/.gem/ruby/2.7.0/bin/fastlane:23:in `load'
717	from /Users/hseapps/.gem/ruby/2.7.0/bin/fastlane:23:in `<top (required)>'
718	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `load'
719	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:63:in `kernel_load'
720	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli/exec.rb:28:in `run'
721	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:497:in `exec'
722	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
723	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
724	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
725	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:30:in `dispatch'
726	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
727	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/cli.rb:24:in `start'
728	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:49:in `block in <top (required)>'
729	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
730	from /Users/hseapps/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bundler-2.2.0/exe/bundle:37:in `<top (required)>'
731	from /Users/hseapps/.rbenv/versions/2.7.1/bin/bundle:23:in `load'
732	from /Users/hseapps/.rbenv/versions/2.7.1/bin/bundle:23:in `<main>'
734ERROR: Job failed: exit status 1
```
 </pre>
</details>

### Environment

<!-- 
Please run `fastlane env` and copy the output below. This will help us help you.
If you used the `--capture_output` option, please remove this block as it is already included there. 
-->

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 11.3                                        |
| Ruby                        | 2.7.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.30.1 (Apple Git-130)          |
| Installation Source         | ~/.rbenv/versions/2.7.1/bin/fastlane        |
| Host                        | macOS 11.3 (20E232)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.7.1/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1g  21 Apr 2020                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 12.5.1                                      |
| Swift Version               | 5.4.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    cocoapods
    increment_build_number(build_number: ENV['CI_JOB_ID'])
    match(type: "appstore", app_identifier: ["ru.hse.HSEAppX", "ru.hse.HSEAppX.TimetableWidget","ru.hse.HSEAppX.watchkitapp","ru.hse.HSEAppX.watchkitapp.watchkitextension"], readonly: false)
    build_app(scheme: "HSEAppX")
    commit_message = last_git_commit[:message]
    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")
    upload_to_testflight(changelog: changelog)
    download_dsyms(version:"latest", wait_for_dsym_processing: true)
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("[DELETED]") # The bundle identifier of your app
apple_id("[DELETED]@hse.ru") # Your Apple email address

itc_team_id("[DELETED]") # App Store Connect Team ID
team_id("[DELETED]") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.193.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.4.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| addressable                     | 2.8.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| gh_inspector                    | 1.1.3        |
| security                        | 0.1.3        |
| dotenv                          | 2.7.6        |
| simctl                          | 1.6.8        |
| uri                             | 0.10.0       |
| rexml                           | 3.2.5        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.0.3        |
| CFPropertyList                  | 3.0.3        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.21.0       |
| plist                           | 3.6.0        |
| public_suffix                   | 4.0.6        |
| babosa                          | 1.0.4        |
| excon                           | 0.85.0       |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.4        |
| ruby2_keywords                  | 0.0.5        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.1        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.7.1        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.1.0        |
| fastimage                       | 2.2.5        |
| json                            | 2.5.1        |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| xcpretty-travis-formatter       | 1.0.1        |
| bundler                         | 2.2.26       |
| jwt                             | 2.2.3        |
| webrick                         | 1.7.0        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| signet                          | 0.15.0       |
| os                              | 1.1.1        |
| memoist                         | 0.16.2       |
| googleauth                      | 0.17.1       |
| mini_mime                       | 1.1.1        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.1        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.1.1        |
| google-apis-core                | 0.4.1        |
| google-apis-playcustomapp_v1    | 0.5.0        |
| google-apis-androidpublisher_v3 | 0.10.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-apis-storage_v1          | 0.6.0        |
| google-apis-iamcredentials_v1   | 0.7.0        |
| google-cloud-errors             | 1.1.0        |
| google-cloud-env                | 1.5.0        |
| google-cloud-core               | 1.6.0        |
| google-cloud-storage            | 1.34.1       |
| emoji_regex                     | 3.2.2        |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.3.0        |
| aws-partitions                  | 1.494.0      |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.120.0      |
| aws-sdk-kms                     | 1.48.0       |
| aws-sdk-s3                      | 1.101.0      |
| forwardable                     | 1.3.1        |
| logger                          | 1.4.2        |
| cgi                             | 0.1.0        |
| date                            | 3.0.0        |
| timeout                         | 0.1.0        |
| stringio                        | 0.1.0        |
| ipaddr                          | 1.2.2        |
| openssl                         | 2.1.2        |
| zlib                            | 1.1.0        |
| mutex_m                         | 0.1.0        |
| ostruct                         | 0.2.0        |
| strscan                         | 1.0.3        |
| io-console                      | 0.5.6        |
| delegate                        | 0.1.0        |
| fileutils                       | 1.4.1        |
| singleton                       | 0.1.0        |
| open3                           | 0.1.0        |
| yaml                            | 0.1.0        |
| psych                           | 3.1.0        |
</details>


*generated on:* **2021-09-03**
</details>

### PR DESCRIPTION
**Pull request by lucgrabowski**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #19330 

### Description

It seems that `build_beta_detail` in `build` that we get from server can be `nil`, even though it's in build's `ESSENTIAL_INCLUDES`.
Treat build as not processed if `wait_for_build_beta_detail_processing=true` and `build.build_beta_detail.nil?`

### Testing Steps

I don't have a mac app that I could use for tests

Update Gemfile and run bundle install
```ruby
gem "fastlane", :git => "https://github.com/lucgrabowski/fastlane.git", :branch => "lucgrabowski-build-watcher-fails-when-beta-build-detail-is-nil-fix"
```

### CODE REVIEW

**Comment by lucgrabowski** [comment]
@lgralino, would you be able to test the fix (please take a look at testing steps in description, if you can test it)?

**Comment by Igralino** [comment]
@lucgrabowski tested the branch - now everything works correctly!
`upload_to_testflight(changelog: changelog, app_platform: "osx")` successfully loaded my app to AppStoreConnect

File: fastlane_core/lib/fastlane_core/build_watcher.rb [hunk 1]
```diff
@@ -156,7 +156,11 @@ def processed?(build: nil, wait_for_build_beta_detail_processing: false)
         #
         # If set, this method will only return true if all three statuses are complete
         if wait_for_build_beta_detail_processing
-          is_processed &&= build.build_beta_detail.processed?
+          if build.build_beta_detail.nil?
+            is_processed = false
+          else
+            is_processed &&= build.build_beta_detail.processed?
```
Comment (joshdholtz) [inline fastlane_core/lib/fastlane_core/build_watcher.rb:162]: This is a great catch! I think this could also be reworked to something like this 👇 Thoughts? 😊 

`build&.build_beta_detail.processed?` will return `nil` if no `build_beta_detail` and then turn into `false` with `|| false`

```suggestion
          is_processed &&= (build&.build_beta_detail.processed? || false)
```

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Looks good to me! Just a small suggestion on syntax 😊

File: fastlane_core/lib/fastlane_core/build_watcher.rb (hunk 1 above)
Comment (lucgrabowski) [reply fastlane_core/lib/fastlane_core/build_watcher.rb]: Thanks for proposing safe navigation operator. @joshdholtz I was thinking if it's possible to do it without `if` statement ;)

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
Thanks for finding this and fixing this! Really appreciate it ❤️
