### PR TITLE
[sigh] fix undefined method `expires` with `expiration_date` in Sigh::Runner

### LINKED ISSUE #17549: fastlane sigh ends with error [!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)
**Summary**: I am trying to use fastlane sigh to update and then download an invalid appstore provisioning profile using a newly created distribution certificate. I am getting an error ```[!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)```

**Note**: This may be similar to https://github.com/fastlane/fastlane/issues/17428 where `owner name` was deprecated

**Expected result**: The provisioning profile is updated on the developer portal to use the new distribution certificate and is then downloaded to my local machine.

**Actual result**: The command results in an error ```[!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)```

**Input**: `fastlane sigh --skip-install --username <username> --team_id <team_id> --app_identifier <app_identifier> --provisioning_name <profile_name> --ignore_profiles_with_different_name true --force`

**Output**: 
```
[:heavy_check_mark:] :rocket: 
[10:35:25]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+-------------------------------------+--------------------------------------------------------+
|                  Summary for sigh 2.166.0                  |
+-------------------------------------+--------------------------------------------------------+
| skip_install				| true			|
| username				| <username>		|
| team_id				| <team id>		|
| app_identifier			| <bundle id>		|
| provisioning_name			| <profile name>	|
| filename				| <profile name>	|
| ignore_profiles_with_different_name	| true			|
| skip_certificate_verification		| true			|
| adhoc					| false			|
| developer_id				| false			|
| development				| false			|
| force					| false			|
| skip_fetch_profiles			| false			|
| platform				| ios			|
| readonly				| false			|
| fail_on_name_taken			| false			|
+-------------------------------------+--------------------------------------------------------+

[10:35:27]: Starting login with user '<username>'
Available session is not valid any more. Continuing with normal login.
[10:35:31]: Successfully logged in
[10:35:31]: Fetching profiles...
[10:35:32]: Provisioning Profile '<profile name>' is not valid, skipping this one...
[10:35:32]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[10:35:32]: Creating new provisioning profile for '<app identifier>' with name '<profile name>' for 'ios' platform
[10:35:32]: Found more than one code signing identity. Choosing the first one. Check out fastlane sigh --help to see all available options.
[10:35:32]: Available Code Signing Identities for current filters:

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run fastlane env to append the fastlane environment to your issue
Traceback (most recent call last):
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)
	17: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `<main>'
	16: from /usr/local/lib/ruby/gems/2.6.0/bin/fastlane:23:in `load'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/bin/fastlane:23:in `<top (required)>'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:16:in `start'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:139:in `run'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	9: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	8: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	7: from /usr/local/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	6: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/commands_generator.rb:61:in `block (2 levels) in run'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/manager.rb:8:in `start'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:48:in `run'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:186:in `create_profile!'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `certificates_to_use'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:329:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/fastlane-2.166.0/sigh/lib/sigh/runner.rb:330:in `block in certificates_to_use': [!] undefined method `expires' for #<Spaceship::ConnectAPI::Certificate:0x00007f9206abd250> (NoMethodError)
```

**Fastlane env**:
<details><summary>:white_check_mark: fastlane environment :white_check_mark:</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.14.4                                          |
| Ruby                        | 2.6.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.20.1 (Apple Git-117)               |
| Installation Source         | /usr/local/lib/ruby/gems/2.6.0/bin/fastlane      |
| Host                        | Mac OS X 10.14.4 (18E226)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.6.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2q  20 Nov 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-10_2.app/Contents/Developer/ |
| Xcode Version               | 10.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | :white_check_mark: |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

*No Fastfile found**

No Appfile found*

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.166.0 | :white_check_mark: Up-To-Date  |

### Loaded fastlane plugins:

*No plugins Loaded*

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 3.0.2        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.3.0        |
| xcodeproj                 | 1.19.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.7.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 4.0.6        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.8.1        |
| tty-cursor                | 0.7.1        |
| tty-spinner               | 0.9.3        |
| babosa                    | 1.0.4        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.76.0       |
| faraday                   | 1.0.1        |
| unf_ext                   | 0.0.7.7      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.7        |
| faraday_middleware        | 1.0.0        |
| fastimage                 | 2.2.0        |
| gh_inspector              | 1.1.3        |
| json                      | 2.3.1        |
| mini_magick               | 4.10.1       |
| rubyzip                   | 2.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.6        |
| bundler                   | 2.1.4        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.8        |
| jwt                       | 2.2.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.20       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.15.0       |
| signet                    | 0.14.0       |
| memoist                   | 0.16.2       |
| os                        | 1.1.1        |
| googleauth                | 0.13.1       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.38.0       |
| google-cloud-env          | 1.3.3        |
| google-cloud-errors       | 1.0.1        |
| google-cloud-core         | 1.5.0        |
| rake                      | 13.0.1       |
| digest-crc                | 0.6.1        |
| google-cloud-storage      | 1.29.1       |
| emoji_regex               | 3.0.0        |
| jmespath                  | 1.4.0        |
| aws-partitions            | 1.380.0      |
| aws-eventstream           | 1.1.0        |
| aws-sigv4                 | 1.2.2        |
| aws-sdk-core              | 3.109.1      |
| aws-sdk-kms               | 1.39.0       |
| aws-sdk-s3                | 1.83.0       |

</details>generated on: *2020-11-03*
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context

Resolves #17549

### Description

After some investigation, looks like we were trying to access a property named `expires` that is only accessible in `Portal`'s Certificate, instead of accessing the same property named `expiration_date`, available via `ConnectAPI`'s `Certificate`.

This issue solution is similar to this one: https://github.com/fastlane/fastlane/pull/17432
However, this time I reviewed the entire affected file to see if more occurrences of the same bug was happening (i.e. accessing properties only present in `Portal`'s `Certificate` instead of `ConnectAPI`'s), and this was the only offending use case left in this file.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-sigh-wrong-certificate-model"
```

### CODE REVIEW

File: sigh/lib/sigh/runner.rb [hunk 1]
```diff
@@ -327,7 +327,7 @@ def certificates_to_use
         UI.important("Found more than one code signing identity. Choosing the first one. Check out `fastlane sigh --help` to see all available options.")
         UI.important("Available Code Signing Identities for current filters:")
         certificates.each do |c|
-          str = ["\t- Name:", c.display_name, "- ID:", c.id + " - Expires", c.expires.strftime("%d/%m/%Y")].join(" ")
+          str = ["\t- Name:", c.display_name, "- ID:", c.id + " - Expires", c.expiration_date.strftime("%d/%m/%Y")].join(" ")
```
Comment (jessewebb) [inline sigh/lib/sigh/runner.rb:330]: I tested out this change and it didn't quite work. It seems that `c.expiration_date` is a `String`, not a `DateTime`, so you still get an error. I updated my local `runner.rb` file with the following line instead to make it work:
```
str = ["\t- Name:", c.display_name, "- ID:", c.id + " - Expires", DateTime.iso8601(c.expiration_date).strftime("%d/%m/%Y")].join(" ")
```

Comment (rogerluan) [reply sigh/lib/sigh/runner.rb:330]: Thanks for spotting this! 
I wrote a test to prevent this from happening: 

image

💪

Comment (rogerluan) [reply sigh/lib/sigh/runner.rb]: I added some commits - could you try again if you have a chance? 😃

File: sigh/spec/runner_spec.rb [hunk 2]
```diff
@@ -142,6 +142,17 @@
...
+    describe "#certificates_to_use" do
+      it "list certificates found when there're multiple certificates and not in development" do
+        options = { skip_certificate_verification: true }
+        Sigh.config = FastlaneCore::Configuration.create(Sigh::Options.available_options, options)
+        sigh_stub_spaceship_connect
+
+        certificates_to_use = fake_runner.certificates_to_use
+        expect(certificates_to_use.size).to eq(1)
+      end
+    end
```
Comment (rogerluan) [inline sigh/spec/runner_spec.rb:154]: My first test written in ruby, ever 😅 it looks terrible, but I didn't know how to validate the message thrown by `UI.message` 😬 I thought of extracting the message builder to a separate function, but didn't want to mess around with code much 😅 

Any tips are welcome 😇

**Comment by joshdholtz** [comment]
@googlebot I consent.

**Review by joshdholtz — APPROVED** [review]
Thanks for fixing this!! ❤️
