### PR TITLE
[deliver] make screenshots path relative to Preview.html file

### LINKED ISSUE #13176: [deliver] picks up the wrong path to screenshots
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

My screenshots are stored in `fastlane/screenshots/en-US`, and I tried to `deliver` them using:

```
fastlane deliver --skip_binary_upload true --skip_metadata true
```

`deliver` then creates a file `fastlane/Preview.html`, and once I open this in safari, I notice that all links are broken:

screen shot 2018-08-21 at 12 38 30

The problem seems to be that all links in there have a "./fastlane/" prefix, so effectively trying to open `fastlane/fastlane/screenshots` ... etc.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ fastlane deliver --skip_binary_upload true --skip_metadata true 
[✔] 🚀 
[12:34:49]: Login to App Store Connect (***)
[12:34:52]: Login successful

+--------------------------------------+--------------------------+
|                     deliver 2.102.0 Summary                     |
+--------------------------------------+--------------------------+
| skip_binary_upload                   | true                     |
| skip_metadata                        | true                     |
| screenshots_path                     | ./fastlane/screenshots   |
| metadata_path                        | ./fastlane/metadata      |
| app_version                          | 1.0                      |
| username                             | *** |
| app_identifier                       | *****    |
| edit_live                            | false                    |
| ipa                                  | Runner.ipa               |
| platform                             | ios                      |
| use_live_version                     | false                    |
| skip_screenshots                     | false                    |
| skip_app_version_update              | false                    |
| force                                | false                    |
| submit_for_review                    | false                    |
| reject_if_possible                   | false                    |
| automatic_release                    | false                    |
| phased_release                       | false                    |
| team_id                              | ****                |
| dev_portal_team_id                   | ****               |
| overwrite_screenshots                | false                    |
| run_precheck_before_submit           | true                     |
| precheck_default_rule_level          | warn                     |
| ignore_language_directory_validation | false                    |
| precheck_include_in_app_purchases    | true                     |
+--------------------------------------+--------------------------+

[12:34:53]: Making sure the latest version on App Store Connect matches '1.0' from the ipa file...
[12:34:55]: '1.0' is the latest version on App Store Connect
[12:34:58]: Verifying the upload via the HTML file can be disabled by either adding
[12:34:58]: `force true` to your Deliverfile or using `fastlane deliver --force`
[12:34:58]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)</pre>
</details>

The 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.13.6                                          |
| Ruby                        | 2.5.1                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.18.0                               |
| Installation Source         | /usr/local/var/rbenv/versions/2.5.1/bin/fastlane |
| Host                        | Mac OS X 10.13.6 (17G65)                         |
| Ruby Lib Dir                | /usr/local/var/rbenv/versions/2.5.1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2o  27 Mar 2018                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 9.4.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.102.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.2.0        |
| bundler                   | 1.16.2       |
| CFPropertyList            | 3.0.0        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.5        |
| minitest                  | 5.11.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.5        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.5.3        |
| cocoapods-deintegrate     | 1.0.2        |
| cocoapods-downloader      | 1.2.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.1        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.1.3        |
| molinillo                 | 0.6.6        |
| ruby-macho                | 1.2.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| cocoapods                 | 1.5.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.9.0        |
| googleauth                | 0.6.5        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-08-21**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #13176

## Problem
The images in `Preview.html` were relative on the project root but the `Preview.html` file is located inside of the `fastlane` directory.

## Solution
The images (app icon, watch app, and screenshots) get a path that is rendered realtive to the `fastlane` directory

### CODE REVIEW

File: deliver/lib/deliver/html_generator.rb [hunk 1]
```diff
@@ -31,11 +31,20 @@ def run(options, screenshots)
       end
     end
 
+    # Returns a path relative to FastlaneFolder.path
+    # This is needed as the Preview.html file is located inside FastlaneFolder.path
+    def render_relative_path(export_path, path)
+      export_path = Pathname.new(export_path)
+      path = Pathname.new(path).relative_path_from(export_path)
+      return path.to_path
```
Comment (taquitos) [inline deliver/lib/deliver/html_generator.rb]: `path.to_path`
horseheadinception

**Review by taquitos — APPROVED** [review]
🐴 👍
