### PR TITLE
[action] fix version_get_podspec to allow parsing pre-release suffix

### LINKED ISSUE #12717: version_get_podspec does not support pre-release version numbers, e.g. 2.0.0-beta
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

When using the `version_get_podspec` action to get the version number from a Podspec, it returns an error if the Podspec version has a [pre-release identifier](https://semver.org/#spec-item-9) at the end, e.g. `2.0.0-beta`.

Cocoapods itself doesn't seem to have a problem with version numbers like this, and the [doco backs this up](https://guides.cocoapods.org/making/making-a-cocoapod.html).

I understand it would be difficult for the various `version_bump` actions to support pre-release versions - but `version_get_podspec` seems like it shouldn't have a problem with it?

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>$ bundle exec fastlane ios preprod
[✔] 🚀 
[09:38:47]: ----------------------------------------
[09:38:47]: --- Step: Verifying fastlane version ---
[09:38:47]: ----------------------------------------
[09:38:47]: Your fastlane version 2.97.0 matches the minimum requirement of 2.70  ✅
[09:38:47]: ------------------------------
[09:38:47]: --- Step: default_platform ---
[09:38:47]: ------------------------------
[09:38:47]: ----------------------------------------
[09:38:47]: --- Step: Verifying fastlane version ---
[09:38:47]: ----------------------------------------
[09:38:47]: Your fastlane version 2.97.0 matches the minimum requirement of 2.71.0  ✅
[09:38:47]: ------------------------------
[09:38:47]: --- Step: default_platform ---
[09:38:47]: ------------------------------
[09:38:47]: Driving the lane 'ios preprod' 🚀
[09:38:47]: -------------------
[09:38:47]: --- Step: is_ci ---
[09:38:47]: -------------------
[09:38:47]: -----------------------
[09:38:47]: --- Step: cocoapods ---
[09:38:47]: -----------------------
[09:38:47]: $ bundle exec pod install
[09:38:48]: ▸ Analyzing dependencies
[09:38:48]: ▸ Fetching podspec for `CNExtension` from `./ios-sdk/build-dir/iOS-SDK`
[09:38:48]: ▸ Fetching podspec for `CNExtension-DEV` from `./ios-sdk/CNExtension`
[09:38:48]: ▸ Fetching podspec for `CompanyName` from `./ios-sdk/build-dir/iOS-SDK`
[09:38:48]: ▸ Fetching podspec for `CompanyName-DEV` from `./ios-sdk`
[09:38:52]: ▸ Downloading dependencies
[09:38:52]: ▸ Using HockeySDK (4.1.6)
[09:38:52]: ▸ Using NSLogger (1.5.1)
[09:38:52]: ▸ Using CNExtension (1.1)
[09:38:52]: ▸ Using CNExtension-DEV (1.1)
[09:38:52]: ▸ Using CompanyName (2.0.0-SNAPSHOT)
[09:38:52]: ▸ Using CompanyName-DEV (2.0.0-SNAPSHOT)
[09:38:52]: ▸ Generating Pods project
[09:38:52]: ▸ Integrating client project
[09:38:52]: ▸ Sending stats
[09:38:52]: ▸ Pod installation complete! There are 12 dependencies from the Podfile and 12 total pods installed.
[09:38:52]: ---------------------------------------------
[09:38:52]: --- Step: Switch to ios build_cn_app lane ---
[09:38:52]: ---------------------------------------------
[09:38:52]: Cruising over to lane 'ios build_cn_app' 🚖
[09:38:52]: No BUILD_NUMBER environment variable was found. Defaulting to 1
[09:38:52]: ---------------------------------
[09:38:52]: --- Step: version_get_podspec ---
[09:38:52]: ---------------------------------
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios preprod |
+------------------+-------------+
[09:38:52]: Could not find version in podspec content 'Pod::Spec.new do |s|
  s.name                           = 'CompanyName'
  s.authors                        = 'CompanyName PTY LTD'
  s.version                        = '2.0.0-SNAPSHOT'
  s.source                         = { :http => "http://example.com/iOS-SDK.zip" }
  s.summary                        = 'CompanyName SDK'
  s.license                        = { :type => 'MIT', :file => 'MIT-LICENSE.txt' }
  s.platform                       = :ios
  s.ios.deployment_target          = '7.0'
  s.homepage                       = 'http://www.CompanyName.com'
  s.libraries                      = 'sqlite3.0'
  s.requires_arc                   = true
  s.frameworks                     = 'Foundation', 'CoreLocation', 'CoreBluetooth', 'MobileCoreServices', 'SystemConfiguration'
  s.vendored_frameworks            = 'CompanyName/ios/CompanyName.framework'
end
'

+------+---------------------------------+-------------+
|                   fastlane summary                   |
+------+---------------------------------+-------------+
| Step | Action                          | Time (in s) |
+------+---------------------------------+-------------+
| 1    | Verifying fastlane version      | 0           |
| 2    | default_platform                | 0           |
| 3    | Verifying fastlane version      | 0           |
| 4    | default_platform                | 0           |
| 5    | is_ci                           | 0           |
| 6    | cocoapods                       | 5           |
| 7    | Switch to ios build_cn_app lane | 0           |
| 💥   | version_get_podspec             | 0           |
+------+---------------------------------+-------------+

[09:38:52]: fastlane finished with errors

[!] Could not find version in podspec content 'Pod::Spec.new do |s|
  s.name                           = 'CompanyName'
  s.authors                        = 'CompanyName PTY LTD'
  s.version                        = '2.0.0-SNAPSHOT'
  s.source                         = { :http => "http://example.com/iOS-SDK.zip" }
  s.summary                        = 'CompanyName SDK'
  s.license                        = { :type => 'MIT', :file => 'MIT-LICENSE.txt' }
  s.platform                       = :ios
  s.ios.deployment_target          = '7.0'
  s.homepage                       = 'http://www.CompanyName.com'
  s.libraries                      = 'sqlite3.0'
  s.requires_arc                   = true
  s.frameworks                     = 'Foundation', 'CoreLocation', 'CoreBluetooth', 'MobileCoreServices', 'SystemConfiguration'
  s.vendored_frameworks            = 'CompanyName/ios/CompanyName.framework'
end
'
</pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #12717

## What
- `version_get_spec` only allow for parsing of versions that were:
  - `<major>`
   - `<major>.<minor>`
   - `<major>.<minor>.<patch>`
   - `<major>.<minor>.<patch><appendix>` where in  `1.2.3.4.5` the appendix is `.4.5`
- This fix allows for parsing of `<major>.<minor>.<patch><appendix>-<prerelease>`
  - Examples:
    - `1.2.3-SNAPSHOT`
    - `1.2.3.4-BETA`
- Also added some tests for `podspec_helper.rb`

### CODE REVIEW

File: fastlane/spec/helper/podspec_helper_spec.rb [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+        result = @version_podspec_file.parse(test_content)
+        expect(result).to eq('1.3.2')
+        expect(@version_podspec_file.version_value).to eq('1.3.2')
+        expect(@version_podspec_file.version_match[:major]).to eq('1')
+        expect(@version_podspec_file.version_match[:minor]).to eq('3')
+        expect(@version_podspec_file.version_match[:patch]).to eq('2')
+      end
+
+      it "returns the current version once parsed with appendix" do
+        test_content = 'spec.version = "1.3.2.4"'
```
Comment (taquitos) [inline fastlane/spec/helper/podspec_helper_spec.rb]: I think adding a test for the behavior of `spec.version = "1.2.3.4.5"` returning `.4.5` as the `:appendix` would be good, just to guarantee that the old behavior is, in-fact, preserved in to the future.
I don't feel super strongly though, so if you have a reason why that's a dumb idea, feel free to ignore and 🎈'it

**Review by taquitos — APPROVED** [review]
Thanks for adding tests!
🎈:goat:
