### PR TITLE
[supply] error track or track_promote_to are rollout as that is no longer used by Google Play and causing errors

### LINKED ISSUE #15667: [Regression] Supply unable to promote builds from alpha to production with staged rollout
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: [e.g. `2.135.0`]
- Last working version: [e.g. `2.134.0`]

### Regression Description

Our workflow with fastlane (driving gradle) used to be essentially the following:
1. Build the app
2. Upload app to Crashlytics / Firebase App Distribution
3. Submit app Google Play Console **internal** testing track
4. Promote the app from **internal** testing track to the **alpha** one
5. Staged rollouts from **alpha** to production (using the **rollout** track with rollout percentage:

```bash
		bundle exec fastlane deployInternal venture:"${ventureName}" validate_only:${dryRun} jira_ticket:"${jiraTicket}"
		if [ ${deployToProduction} == true ]; then
			bundle exec fastlane promote_to_alpha venture:"${ventureName}"
			sleep 2
			bundle exec fastlane promote_to_production venture:"${ventureName}" rollout_percentage:${rollout_percentage}
		fi
```

This flow does not seem to work anymore

Here is our Fastfile (very slightly redacted):
<details>
  <pre># This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

SRCROOT=File.dirname(File.expand_path('..', __FILE__))
puts "SRCROOT = \"#{SRCROOT}\""
root_relative_json_key="fastlane/nps-fastlane-google-play.json"

ventureTasks = Hash.new
ventureTasks[:virgingames] = 'APP_1'

ventureTasks[:RainbowRichesCasino] = 'APP_N'

###Environment mapping
envMapping = Hash.new
envMapping[:ppc] = "Ppc" 
envMapping[:PPC] = "Ppc" 
envMapping[:Ppc] = "Ppc" 
envMapping[:live] = "Live" 
envMapping[:LIVE] = "Live" 
envMapping[:Live] = "Live" 

###Fabric
branch = git_branch
sha=sh("git log -1 --pretty=format:%H")
build_date=sh("date +%Y-%m-%d_%H:%M:%S")

###Setup group type to build type mapping
buildTypeMap = Hash.new
buildTypeMap[:qa] = "Debug"
buildTypeMap[:qa_prerelease] = "Release"
buildTypeMap[:customer] = "Release"

package_name="com.gamesys"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do |options|
    environmentName = options[:env]
    environmentName = envMapping[:"#{environmentName}"]
    ventureName = options[:venture]
    group_type = options[:group_type]
    build_type = buildTypeMap[:"#{group_type}"]
    ventureTask = "test" + "#{ventureTasks[:"#{ventureName}"]}" + "#{environmentName}" + "DebugUnitTest"

    puts "Environment: #{environmentName}"
    puts "Venture Name: #{ventureName}"
    puts "Current Group Type: #{group_type}"
    puts "Current Build Type: #{build_type}"
    puts "Venture Gradle Task: #{ventureTask}"

    sh("git clean -ffxd")
    sh("git submodule foreach git clean -ffxd")
    gradle(task: "clean")
    gradle(task: "cleanBuild")
    gradle(task: "#{ventureTask}")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do |options|
    environmentName = options[:env]
    environmentName = envMapping[:"#{environmentName}"]
    ventureName = options[:venture]
    ventureNameLowercase="#{ventureName}".downcase
    group_type = options[:group_type]
    build_type = buildTypeMap[:"#{group_type}"]
    jira_ticket = "REL-#{options[:jira_ticket]}"
    release_notes=File.join("#{SRCROOT}", "/app/release_notes.txt")
    ventureTask = "assemble" + "#{ventureTasks[:"#{ventureName}"]}" + "#{environmentName}"

    skip_gradle_build=false
    if options.key?(:skip_gradle_build)
      skip_gradle_build=options[:skip_gradle_build]
    end
    UI.message("Skip gradle build: #{skip_gradle_build}...")

    puts "Environment: #{environmentName}"
    puts "Venture Name: #{ventureName}"
    puts "Current Group Type: #{group_type}"
    puts "Current Build Type: #{build_type}"
    puts "Venture Gradle Task: #{ventureTask}"

    puts "branch = #{branch}"
    puts "sha = #{sha}"
    puts "build date = #{build_date}"
    puts "Release Notes: #{release_notes}"

    begin
      file = File.open("#{release_notes}", "w+")
      file.write("User Group: #{group_type}\n") 
      file.write("Venture: #{ventureName}\n") 
      file.write("Platform: Android\n") 
      file.write("Build Type: #{build_type}\n") 
      file.write("Branch name: #{branch}\n") 
      file.write("sha: #{sha}\n") 
      file.write("build date: #{build_date}\n") 
      file.write("JIRA Ticket: #{jira_ticket}")
    rescue IOError => e
      #some error occur, dir not writable etc.
      puts "Error occurred: #{e}"
    ensure
      file.close unless file.nil?
    end

    if skip_gradle_build == false
      sh("git clean -ffxd")
      sh("git submodule foreach git clean -ffxd")
      gradle(task: "clean")
      gradle(task: "cleanBuild")
      gradle(task: "#{ventureTask}",
      build_type: "#{build_type}")
    end

    environmentNameLowercase="#{environmentName}".downcase

    if "#{group_type}" == "customer" || "#{group_type}" == "qa_prerelease"
      buildTypeLowercase="#{build_type}".downcase

      venturePackageName="#{ventureNameLowercase}"
      if "#{group_type}" == "qa_prerelease"
        package_name="#{package_name}.corp"
      else
        if "#{venturePackageName}" == "virgingames"
          venturePackageName = "virgingamesslots"
        end
      end
      package_name="#{package_name}.#{venturePackageName}"
      puts("package_name = #{package_name}")

      apkName = "app-#{ventureNameLowercase}-#{environmentNameLowercase}-#{buildTypeLowercase}.apk"
      apkPath = File.join("#{SRCROOT}","/app/build/outputs/apk/#{ventureNameLowercase}#{environmentName}/#{buildTypeLowercase}")
    end

    validate_only=false
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}... skipping beta upload if false...")

    if validate_only == false && skip_gradle_build == false
      firebaseFile = File.join("#{SRCROOT}", "/app/src/#{ventureNameLowercase}/firebase_#{group_type}.properties")
      firebaseFile = JavaProps.new("#{firebaseFile}")
      puts(firebaseFile)

      firebase_app_id = firebaseFile.read_property("firebase_app_id")
      puts "Firebase App ID: #{firebase_app_id}"

      firebase_app_distribution(
        app: "#{firebase_app_id}",
        groups: "gamesys_ltd",
        release_notes_file: release_notes,
        debug: true
      )
    else
      UI.message("Skipping Firebase App Distribution...")
    end
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Documentation"
  lane :build_help do
    puts "\nRequired parameters:\n <laneName>\n group_type:<Sets the user group type: qa/qa_prerelease/customer>\n venture:<Sets the venture name>\n env:<environmentName: Ppc/Live>"
    puts "\nOptional parameters:\n jira_ticket:<Specifies JIRA ticket ID>\n"
  end

  desc "Deploy a new Customer Build version only (Non PlayStore Apps)"
  lane :deployNonPlayStore do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    # upload_to_play_store(track: 'internal', 
    #   json_key: root_relative_json_key, 
    #   package_name: package_name, 
    #   skip_upload_metadata: true, 
    #   skip_upload_images: true, 
    #   skip_upload_screenshots: true,
    #   validate_only: validate_only)
  end

  desc "Deploy a new Internal testing version to the Google Play"
  lane :deployInternal do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    upload_to_play_store(track: 'internal', 
      json_key: root_relative_json_key, 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only)
  end

  desc "On Google Play, promote from Internal to Alpha tracks..."
  lane :promote_to_alpha do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    rolloutPercentage=1.0
    upload_to_play_store(json_key: root_relative_json_key, 
      track: "internal",
      track_promote_to: "alpha",
      rollout: "#{rolloutPercentage}", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only)
  end

  desc "On Google Play, promote from Alpha to Production rollout tracks..."
  lane :promote_to_production do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    rollout_percentage=0.0001
    puts("options: #{options}")
    if options.key?(:rollout_percentage)
      rollout_percentage=options[:rollout_percentage]
    end
    UI.message("Rollout percentage: #{rollout_percentage}")

    versionCodeFile=File.join("#{SRCROOT}", "/app/version_code.properties")
    versionCodeFile = JavaProps.new("#{versionCodeFile}")
    version_code = versionCodeFile.read_property("VERSION_CODE")
    versionCode="#{version_code}"

    upload_to_play_store(json_key: root_relative_json_key, 
      track: "alpha",
      track_promote_to: "rollout",
      rollout: "#{rollout_percentage}", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only,
      version_codes_to_retain: [ Integer("#{versionCode}") ])
  end

  desc "Complete Rollout to Play Store"
  lane :completeFullRollout do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    versionCodeFile=File.join("#{SRCROOT}", "/app/version_code.properties")
    versionCodeFile = JavaProps.new("#{versionCodeFile}")
    version_code = versionCodeFile.read_property("VERSION_CODE")
    versionCode="#{version_code}"

    upload_to_play_store(json_key: root_relative_json_key, 
      track: "rollout",
      track_promote_to: "production",
      rollout: "1.0", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: false)
  end

  desc "Test template app's PR"
  lane :pullRequestTest do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    # Add fastlane driven appium / unit tests / etc...
  end

  desc "Updated build number"
  lane :updateBuildNumber do
    sh("""
    cd \"#{SRCROOT}\"
    ls
    bash scripts/incrementBuildNumber.sh -p \"${PWD}\" -b \"#{branch}\" -g
    """)
  end

  lane :tagBuild do |options|
    versionNameFile=File.join("#{SRCROOT}", "/app/version_name.properties")
    versionNameFile = JavaProps.new("#{versionNameFile}")
    version_name = versionNameFile.read_property("VERSION_NAME")
    tag="#{version_name}"

    tagRemove(tag: "#{tag}")
    # add_git_tag(
    #   tag: "#{tag}"
    # )
    sh("""
    cd \"#{SRCROOT}\"
    bash scripts/createReleaseAndTag.sh #{tag}
    """)
  end

  lane :tagRemove do |options|
    tag=options[:tag]

    sh("""
    cd \"#{SRCROOT}\"
    git fetch && git fetch --tags
    """)

    if git_tag_exists(tag: "#{tag}")
      UI.message("Tag \"#{tag}\" found... deleting it...")
      sh("""
      cd \"#{SRCROOT}\"
      deleteRemoteTag.sh #{tag}
      """)
    else
      UI.message("Tag \"#{tag}\" not found...")
    end
  end

  private_lane :testFastFile do |options|
    testH = Hash.new
    testH[:testAA] = Hash.new
    testH[:testAA][:testAAA] = "First Test [testAA][testAAA]"
    testH[:testAA][:testAAAA] = "First Test [testAA][testAAAA]"
    testH[:testBB] = Hash.new 
    testH[:testBB][:testBBB] = "First Test [testBB][testBBB]"

    puts "#{testH[:testAA][:testAAA]}"
    puts "#{testH[:testAA][:testAAAA]}"
    puts "#{testH[:testBB][:testBBB]}"

    puts "Path = #{SRCROOT}"
  end
end

class JavaProps
  attr :file, :properties
  
  #Takes a file and loads the properties in that file
  def initialize file
  @file = file
  @properties = {}
  IO.foreach(file) do |line|
  @properties[$1.strip] = $2 if line =~ /([^=]*)=(.*)\/\/(.*)/ || line =~ /([^=]*)=(.*)/
  end
  end
  
  #Helpfull to string
  def to_s
  output = "File Name #{@file} \n"
  @properties.each {|key,value| output += " #{key}= #{value} \n" }
  output
  end
  
  #Write a property
  def write_property (key,value)
  @properties[key] = value
  end

  #Write a property
  def read_property (key)
  @properties[key]
  end
  
  #Save the properties back to file
  def save
  file = File.new(@file,"w+")
  @properties.each {|key,value| file.puts "#{key}=#{value}\n" }
  end
end
</pre>
</details>

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[20:44:28]: ▸ ✔  added testers/groups successfully
[20:44:28]: Cruising back to lane 'android deployInternal' 🚘
[20:44:28]: options: {:venture=>"__NAME_OF_APP__", :validate_only=>false, :jira_ticket=>"N_A", :env=>"Live", :group_type=>"customer"}
[20:44:28]: Validate only: false
[20:44:28]: ----------------------------------
[20:44:28]: --- Step: upload_to_play_store ---
[20:44:28]: ----------------------------------

+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                               Summary for supply 2.136.0                                                                                |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| track                   | internal                                                                                                                                                      |
| json_key                | fastlane/nps-fastlane-google-play.json                                                                                                                        |
| package_name            | com.__NAME_OF_COMPANY__.__NAME_OF_APP__                                                                                                                                    |
| skip_upload_metadata    | true                                                                                                                                                          |
| skip_upload_images      | true                                                                                                                                                          |
| skip_upload_screenshots | true                                                                                                                                                          |
| validate_only           | false                                                                                                                                                         |
| apk                     | __BUILD_PATH__/app/build/outputs/apk/__NAME_OF_APP__Live/release/app-__NAME_OF_APP__-live-release.apk |
| release_status          | completed                                                                                                                                                     |
| skip_upload_apk         | false                                                                                                                                                         |
| skip_upload_aab         | false                                                                                                                                                         |
| skip_upload_changelogs  | false                                                                                                                                                         |
| check_superseded_tracks | false                                                                                                                                                         |
| timeout                 | 300                                                                                                                                                           |
| deactivate_on_promote   | true                                                                                                                                                          |
+-------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+

[20:44:30]: Preparing apk at path '__BUILD_PATH__/app/build/outputs/apk/__NAME_OF_APP__Live/release/app-__NAME_OF_APP__-live-release.apk' for upload...
[20:44:34]: 	Version Code: 6258
[20:44:34]: Updating track 'internal'...
[20:44:35]: Uploading all track and release changes to Google Play...
[20:44:37]: Successfully finished the upload to Google Play
[20:44:38]: Uploading all meta changes to Google Play...
[20:44:40]: Successfully finished the upload to Google Play

+------+---------------------------------------+-------------+
|                      fastlane summary                      |
+------+---------------------------------------+-------------+
| Step | Action                                | Time (in s) |
+------+---------------------------------------+-------------+
| 1    | git_branch                            | 0           |
| 2    | git log -1 --pretty=format:%H         | 0           |
| 3    | date +%Y-%m-%d_%H:%M:%S               | 0           |
| 4    | default_platform                      | 0           |
| 5    | Switch to android beta lane           | 0           |
| 6    | git clean -ffxd                       | 0           |
| 7    | git submodule foreach git clean -ffxd | 0           |
| 8    | gradle                                | 17          |
| 9    | gradle                                | 18          |
| 10   | gradle                                | 316         |
| 11   | firebase_app_distribution             | 22          |
| 12   | upload_to_play_store                  | 11          |
+------+---------------------------------------+-------------+

[20:44:40]: fastlane.tools just saved you 6 minutes! 🎉
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.4   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

[20:45:01]: SRCROOT = "__BUILD_PATH__"
[20:45:01]: ------------------------
[20:45:01]: --- Step: git_branch ---
[20:45:01]: ------------------------
[20:45:01]: -------------------------------------------
[20:45:01]: --- Step: git log -1 --pretty=format:%H ---
[20:45:01]: -------------------------------------------
[20:45:01]: $ git log -1 --pretty=format:%H
[20:45:02]: ▸ __GIT_SHA__
[20:45:02]: -------------------------------------
[20:45:02]: --- Step: date +%Y-%m-%d_%H:%M:%S ---
[20:45:02]: -------------------------------------
[20:45:02]: $ date +%Y-%m-%d_%H:%M:%S
[20:45:02]: ▸ 2019-11-15_20:45:02
[20:45:02]: ------------------------------
[20:45:02]: --- Step: default_platform ---
[20:45:02]: ------------------------------
[20:45:02]: Driving the lane 'android promote_to_alpha' 🚀
[20:45:02]: -----------------------------------------
[20:45:02]: --- Step: Switch to android beta lane ---
[20:45:02]: -----------------------------------------
[20:45:02]: Cruising over to lane 'android beta' 🚖
[20:45:02]: Skip gradle build: true...
[20:45:02]: Environment: Live
[20:45:02]: Venture Name: __NAME_OF_APP__
[20:45:02]: Current Group Type: customer
[20:45:02]: Current Build Type: Release
[20:45:02]: Venture Gradle Task: assemble__NAME_OF_APP__Live
[20:45:02]: branch = origin/master
[20:45:02]: sha = __GIT_SHA__
[20:45:02]: build date = 2019-11-15_20:45:02

[20:45:02]: Release Notes: __BUILD_PATH__/app/release_notes.txt
[20:45:02]: package_name = com.__NAME_OF_COMPANY__.__NAME_OF_APP__
[20:45:02]: Validate only: false... skipping beta upload if false...
[20:45:02]: Skipping Firebase App Distribution...
[20:45:02]: Cruising back to lane 'android promote_to_alpha' 🚘
[20:45:02]: options: {:venture=>"__NAME_OF_APP__", :env=>"Live", :group_type=>"customer", :skip_gradle_build=>true}
[20:45:02]: Validate only: false
[20:45:02]: ----------------------------------
[20:45:02]: --- Step: upload_to_play_store ---
[20:45:02]: ----------------------------------
[20:45:02]: Using deprecated option: '--deactivate_on_promote' (Google Play does this automatically now)

+-------------------------+----------------------------------------+
|                    Summary for supply 2.136.0                    |
+-------------------------+----------------------------------------+
| json_key                | fastlane/nps-fastlane-google-play.json |
| track                   | internal                               |
| track_promote_to        | alpha                                  |
| rollout                 | 1.0                                    |
| package_name            | com.__NAME_OF_COMPANY__.__NAME_OF_APP__             |
| skip_upload_metadata    | true                                   |
| skip_upload_images      | true                                   |
| skip_upload_screenshots | true                                   |
| validate_only           | false                                  |
| deactivate_on_promote   | false                                  |
| release_status          | completed                              |
| skip_upload_apk         | false                                  |
| skip_upload_aab         | false                                  |
| skip_upload_changelogs  | false                                  |
| check_superseded_tracks | false                                  |
| timeout                 | 300                                    |
+-------------------------+----------------------------------------+

[20:45:04]: Uploading all track and release changes to Google Play...
[20:45:05]: Successfully finished the upload to Google Play
[20:45:06]: Uploading all meta changes to Google Play...
[20:45:08]: Successfully finished the upload to Google Play

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | git_branch                    | 0           |
| 2    | git log -1 --pretty=format:%H | 0           |
| 3    | date +%Y-%m-%d_%H:%M:%S       | 0           |
| 4    | default_platform              | 0           |
| 5    | Switch to android beta lane   | 0           |
| 6    | upload_to_play_store          | 6           |
+------+-------------------------------+-------------+

[20:45:08]: fastlane.tools finished successfully 🎉
+-------------------------------------------+---------+---------------------------+
|                                  Used plugins                                   |
+-------------------------------------------+---------+---------------------------+
| Plugin                                    | Version | Action                    |
+-------------------------------------------+---------+---------------------------+
| fastlane-plugin-firebase_app_distribution | 0.1.4   | firebase_app_distribution |
+-------------------------------------------+---------+---------------------------+

[20:45:14]: SRCROOT = "__BUILD_PATH__"
[20:45:14]: ------------------------
[20:45:14]: --- Step: git_branch ---
[20:45:14]: ------------------------
[20:45:14]: -------------------------------------------
[20:45:14]: --- Step: git log -1 --pretty=format:%H ---
[20:45:14]: -------------------------------------------
[20:45:14]: $ git log -1 --pretty=format:%H
[20:45:14]: ▸ __GIT_SHA__
[20:45:14]: -------------------------------------
[20:45:14]: --- Step: date +%Y-%m-%d_%H:%M:%S ---
[20:45:14]: -------------------------------------
[20:45:14]: $ date +%Y-%m-%d_%H:%M:%S
[20:45:14]: ▸ 2019-11-15_20:45:14
[20:45:14]: ------------------------------
[20:45:14]: --- Step: default_platform ---
[20:45:14]: ------------------------------
[20:45:14]: Driving the lane 'android promote_to_production' 🚀
[20:45:14]: -----------------------------------------
[20:45:14]: --- Step: Switch to android beta lane ---
[20:45:14]: -----------------------------------------
[20:45:14]: Cruising over to lane 'android beta' 🚖
[20:45:14]: Skip gradle build: true...
[20:45:14]: Environment: Live
[20:45:14]: Venture Name: __NAME_OF_APP__
[20:45:14]: Current Group Type: customer
[20:45:14]: Current Build Type: Release
[20:45:14]: Venture Gradle Task: assemble__NAME_OF_APP__Live
[20:45:14]: branch = origin/master
[20:45:14]: sha = __GIT_SHA__
[20:45:14]: build date = 2019-11-15_20:45:14

[20:45:14]: Release Notes: __BUILD_PATH__/app/release_notes.txt
[20:45:14]: package_name = com.__NAME_OF_COMPANY__.__NAME_OF_APP__
[20:45:14]: Validate only: false... skipping beta upload if false...
[20:45:14]: Skipping Firebase App Distribution...
[20:45:14]: Cruising back to lane 'android promote_to_production' 🚘
[20:45:14]: options: {:venture=>"__NAME_OF_APP__", :rollout_percentage=>"0.001", :env=>"Live", :group_type=>"customer", :skip_gradle_build=>true}
[20:45:14]: Validate only: false
[20:45:14]: options: {:venture=>"__NAME_OF_APP__", :rollout_percentage=>"0.001", :env=>"Live", :group_type=>"customer", :skip_gradle_build=>true}
[20:45:14]: Rollout percentage: 0.001
[20:45:14]: ----------------------------------
[20:45:14]: --- Step: upload_to_play_store ---
[20:45:14]: ----------------------------------
[20:45:14]: Using deprecated option: '--deactivate_on_promote' (Google Play does this automatically now)

+-------------------------+----------------------------------------+
|                    Summary for supply 2.136.0                    |
+-------------------------+----------------------------------------+
| json_key                | fastlane/nps-fastlane-google-play.json |
| track                   | alpha                                  |
| track_promote_to        | rollout                                |
| rollout                 | 0.001                                  |
| package_name            | com.__NAME_OF_COMPANY__.__NAME_OF_APP__             |
| skip_upload_metadata    | true                                   |
| skip_upload_images      | true                                   |
| skip_upload_screenshots | true                                   |
| validate_only           | false                                  |
| version_codes_to_retain | [6258]                                 |
| deactivate_on_promote   | true                                   |
| release_status          | completed                              |
| skip_upload_apk         | false                                  |
| skip_upload_aab         | false                                  |
| skip_upload_changelogs  | false                                  |
| check_superseded_tracks | false                                  |
| timeout                 | 300                                    |
+-------------------------+----------------------------------------+

[20:45:15]: Updating track 'alpha'...
+------------------+-------------------------------+
|                   Lane Context                   |
+------------------+-------------------------------+
| DEFAULT_PLATFORM | android                       |
| PLATFORM_NAME    | android                       |
| LANE_NAME        | android promote_to_production |
+------------------+-------------------------------+
[20:45:16]: Track 'alpha' doesn't have any releases

+------+-------------------------------+-------------+
|                  fastlane summary                  |
+------+-------------------------------+-------------+
| Step | Action                        | Time (in s) |
+------+-------------------------------+-------------+
| 1    | git_branch                    | 0           |
| 2    | git log -1 --pretty=format:%H | 0           |
| 3    | date +%Y-%m-%d_%H:%M:%S       | 0           |
| 4    | default_platform              | 0           |
| 5    | Switch to android beta lane   | 0           |
| 💥   | upload_to_play_store          | 1           |
+------+-------------------------------+-------------+

[20:45:16]: fastlane finished with errors

[!] Track 'alpha' doesn't have any releases</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.1                                     |
| Ruby                        | 2.6.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.24.0                          |
| Installation Source         | ~/.rbenv/versions/2.6.4/bin/fastlane        |
| Host                        | Mac OS X 10.15.1 (19B88)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.4/lib                 |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.2.1                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
#update_fastlane

SRCROOT=File.dirname(File.expand_path('..', __FILE__))
puts "SRCROOT = \"#{SRCROOT}\""
root_relative_json_key="fastlane/nps-fastlane-google-play.json"

ventureTasks = Hash.new
ventureTasks[:virgingames] = 'VirginGames'
ventureTasks[:heartbingo] = 'HeartBingo'
ventureTasks[:monopolycasino] = 'MonopolyCasino'
ventureTasks[:jackpotjoy] = 'Jackpotjoy'
ventureTasks[:starspins] = 'Starspins'
ventureTasks[:botemania] = 'Botemania'
ventureTasks[:canalbingo] = 'CanalBingo'
ventureTasks[:pickmeupbingo] = 'PickMeUpBingo'
ventureTasks[:womansownbingo] = 'WomansOwnBingo'
ventureTasks[:womanbingo] = 'WomanBingo'
ventureTasks[:chatmagbingo] = 'ChatMagBingo'
ventureTasks[:rainbowrichescasino] = 'RainbowRichesCasino'
ventureTasks[:VirginGames] = 'VirginGames'
ventureTasks[:HeartBingo] = 'HeartBingo'
ventureTasks[:MonopolyCasino] = 'MonopolyCasino'
ventureTasks[:Jackpotjoy] = 'Jackpotjoy'
ventureTasks[:Starspins] = 'Starspins'
ventureTasks[:Botemania] = 'Botemania'
ventureTasks[:CanalBingo] = 'CanalBingo'
ventureTasks[:PickMeUpBingo] = 'PickMeUpBingo'
ventureTasks[:WomansOwnBingo] = 'WomansOwnBingo'
ventureTasks[:WomanBingo] = 'WomanBingo'
ventureTasks[:ChatMagBingo] = 'ChatMagBingo'
ventureTasks[:RainbowRichesCasino] = 'RainbowRichesCasino'

###Environment mapping
envMapping = Hash.new
envMapping[:ppc] = "Ppc" 
envMapping[:PPC] = "Ppc" 
envMapping[:Ppc] = "Ppc" 
envMapping[:live] = "Live" 
envMapping[:LIVE] = "Live" 
envMapping[:Live] = "Live" 

###Fabric
branch = git_branch
sha=sh("git log -1 --pretty=format:%H")
build_date=sh("date +%Y-%m-%d_%H:%M:%S")

###Setup group type to build type mapping
buildTypeMap = Hash.new
buildTypeMap[:qa] = "Debug"
buildTypeMap[:qa_prerelease] = "Release"
buildTypeMap[:customer] = "Release"

package_name="com.gamesys"

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do |options|
    environmentName = options[:env]
    environmentName = envMapping[:"#{environmentName}"]
    ventureName = options[:venture]
    group_type = options[:group_type]
    build_type = buildTypeMap[:"#{group_type}"]
    ventureTask = "test" + "#{ventureTasks[:"#{ventureName}"]}" + "#{environmentName}" + "DebugUnitTest"

    puts "Environment: #{environmentName}"
    puts "Venture Name: #{ventureName}"
    puts "Current Group Type: #{group_type}"
    puts "Current Build Type: #{build_type}"
    puts "Venture Gradle Task: #{ventureTask}"

    sh("git clean -ffxd")
    sh("git submodule foreach git clean -ffxd")
    gradle(task: "clean")
    gradle(task: "cleanBuild")
    gradle(task: "#{ventureTask}")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do |options|
    environmentName = options[:env]
    environmentName = envMapping[:"#{environmentName}"]
    ventureName = options[:venture]
    ventureNameLowercase="#{ventureName}".downcase
    group_type = options[:group_type]
    build_type = buildTypeMap[:"#{group_type}"]
    jira_ticket = "REL-#{options[:jira_ticket]}"
    release_notes=File.join("#{SRCROOT}", "/app/release_notes.txt")
    ventureTask = "assemble" + "#{ventureTasks[:"#{ventureName}"]}" + "#{environmentName}"

    skip_gradle_build=false
    if options.key?(:skip_gradle_build)
      skip_gradle_build=options[:skip_gradle_build]
    end
    UI.message("Skip gradle build: #{skip_gradle_build}...")

    puts "Environment: #{environmentName}"
    puts "Venture Name: #{ventureName}"
    puts "Current Group Type: #{group_type}"
    puts "Current Build Type: #{build_type}"
    puts "Venture Gradle Task: #{ventureTask}"

    puts "branch = #{branch}"
    puts "sha = #{sha}"
    puts "build date = #{build_date}"
    puts "Release Notes: #{release_notes}"

    begin
      file = File.open("#{release_notes}", "w+")
      file.write("User Group: #{group_type}\n") 
      file.write("Venture: #{ventureName}\n") 
      file.write("Platform: Android\n") 
      file.write("Build Type: #{build_type}\n") 
      file.write("Branch name: #{branch}\n") 
      file.write("sha: #{sha}\n") 
      file.write("build date: #{build_date}\n") 
      file.write("JIRA Ticket: #{jira_ticket}")
    rescue IOError => e
      #some error occur, dir not writable etc.
      puts "Error occurred: #{e}"
    ensure
      file.close unless file.nil?
    end

    if skip_gradle_build == false
      sh("git clean -ffxd")
      sh("git submodule foreach git clean -ffxd")
      gradle(task: "clean")
      gradle(task: "cleanBuild")
      gradle(task: "#{ventureTask}",
      build_type: "#{build_type}")
    end

    environmentNameLowercase="#{environmentName}".downcase

    if "#{group_type}" == "customer" || "#{group_type}" == "qa_prerelease"
      buildTypeLowercase="#{build_type}".downcase

      venturePackageName="#{ventureNameLowercase}"
      if "#{group_type}" == "qa_prerelease"
        package_name="#{package_name}.corp"
      else
        if "#{venturePackageName}" == "virgingames"
          venturePackageName = "virgingamesslots"
        end
      end
      package_name="#{package_name}.#{venturePackageName}"
      puts("package_name = #{package_name}")

      apkName = "app-#{ventureNameLowercase}-#{environmentNameLowercase}-#{buildTypeLowercase}.apk"
      apkPath = File.join("#{SRCROOT}","/app/build/outputs/apk/#{ventureNameLowercase}#{environmentName}/#{buildTypeLowercase}")
    end

    validate_only=false
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}... skipping beta upload if false...")

    if validate_only == false && skip_gradle_build == false
      firebaseFile = File.join("#{SRCROOT}", "/app/src/#{ventureNameLowercase}/firebase_#{group_type}.properties")
      firebaseFile = JavaProps.new("#{firebaseFile}")
      puts(firebaseFile)

      firebase_app_id = firebaseFile.read_property("firebase_app_id")
      puts "Firebase App ID: #{firebase_app_id}"

      firebase_app_distribution(
        app: "#{firebase_app_id}",
        groups: "gamesys_ltd",
        release_notes_file: release_notes,
        debug: true
      )
    else
      UI.message("Skipping Firebase App Distribution...")
    end
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Documentation"
  lane :build_help do
    puts "\nRequired parameters:\n <laneName>\n group_type:<Sets the user group type: qa/qa_prerelease/customer>\n venture:<Sets the venture name>\n env:<environmentName: Ppc/Live>"
    puts "\nOptional parameters:\n jira_ticket:<Specifies JIRA ticket ID>\n"
  end

  desc "Deploy a new Customer Build version only (Non PlayStore Apps)"
  lane :deployNonPlayStore do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    # upload_to_play_store(track: 'internal', 
    #   json_key: root_relative_json_key, 
    #   package_name: package_name, 
    #   skip_upload_metadata: true, 
    #   skip_upload_images: true, 
    #   skip_upload_screenshots: true,
    #   validate_only: validate_only)
  end

  desc "Deploy a new Internal testing version to the Google Play"
  lane :deployInternal do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    upload_to_play_store(track: 'internal', 
      json_key: root_relative_json_key, 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only)
  end

  desc "On Google Play, promote from Internal to Alpha tracks..."
  lane :promote_to_alpha do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    rolloutPercentage=1.0
    upload_to_play_store(json_key: root_relative_json_key, 
      track: "internal",
      track_promote_to: "alpha",
      rollout: "#{rolloutPercentage}", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only)
  end

  desc "On Google Play, promote from Alpha to Production rollout tracks..."
  lane :promote_to_production do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    rollout_percentage=0.0001
    puts("options: #{options}")
    if options.key?(:rollout_percentage)
      rollout_percentage=options[:rollout_percentage]
    end
    UI.message("Rollout percentage: #{rollout_percentage}")

    versionCodeFile=File.join("#{SRCROOT}", "/app/version_code.properties")
    versionCodeFile = JavaProps.new("#{versionCodeFile}")
    version_code = versionCodeFile.read_property("VERSION_CODE")
    versionCode="#{version_code}"

    upload_to_play_store(json_key: root_relative_json_key, 
      track: "alpha",
      track_promote_to: "rollout",
      rollout: "#{rollout_percentage}", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: validate_only,
      version_codes_to_retain: [ Integer("#{versionCode}") ])
  end

  desc "Complete Rollout to Play Store"
  lane :completeFullRollout do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    options[:skip_gradle_build] = true
    beta options

    versionCodeFile=File.join("#{SRCROOT}", "/app/version_code.properties")
    versionCodeFile = JavaProps.new("#{versionCodeFile}")
    version_code = versionCodeFile.read_property("VERSION_CODE")
    versionCode="#{version_code}"

    upload_to_play_store(json_key: root_relative_json_key, 
      track: "rollout",
      track_promote_to: "production",
      rollout: "1.0", 
      package_name: package_name, 
      skip_upload_metadata: true, 
      skip_upload_changelogs: true,
      skip_upload_images: true, 
      skip_upload_screenshots: true,
      validate_only: false)
  end

  desc "Test template app's PR"
  lane :pullRequestTest do |options|
    options[:env] = "Live"
    options[:group_type] = "customer"
    beta options

    validate_only=false
    puts("options: #{options}")
    if options.key?(:validate_only)
      validate_only=options[:validate_only]
    end
    UI.message("Validate only: #{validate_only}")

    # Add fastlane driven appium / unit tests / etc...
  end

  desc "Updated build number"
  lane :updateBuildNumber do
    sh("""
    cd \"#{SRCROOT}\"
    ls
    bash scripts/incrementBuildNumber.sh -p \"${PWD}\" -b \"#{branch}\" -g
    """)
  end

  lane :tagBuild do |options|
    versionNameFile=File.join("#{SRCROOT}", "/app/version_name.properties")
    versionNameFile = JavaProps.new("#{versionNameFile}")
    version_name = versionNameFile.read_property("VERSION_NAME")
    tag="#{version_name}"

    tagRemove(tag: "#{tag}")
    # add_git_tag(
    #   tag: "#{tag}"
    # )
    sh("""
    cd \"#{SRCROOT}\"
    bash scripts/createReleaseAndTag.sh #{tag}
    """)
  end

  lane :tagRemove do |options|
    tag=options[:tag]

    sh("""
    cd \"#{SRCROOT}\"
    git fetch && git fetch --tags
    """)

    if git_tag_exists(tag: "#{tag}")
      UI.message("Tag \"#{tag}\" found... deleting it...")
      sh("""
      cd \"#{SRCROOT}\"
      deleteRemoteTag.sh #{tag}
      """)
    else
      UI.message("Tag \"#{tag}\" not found...")
    end
  end

  private_lane :testFastFile do |options|
    testH = Hash.new
    testH[:testAA] = Hash.new
    testH[:testAA][:testAAA] = "First Test [testAA][testAAA]"
    testH[:testAA][:testAAAA] = "First Test [testAA][testAAAA]"
    testH[:testBB] = Hash.new 
    testH[:testBB][:testBBB] = "First Test [testBB][testBBB]"

    puts "#{testH[:testAA][:testAAA]}"
    puts "#{testH[:testAA][:testAAAA]}"
    puts "#{testH[:testBB][:testBBB]}"

    puts "Path = #{SRCROOT}"
  end
end

class JavaProps
  attr :file, :properties
  
  #Takes a file and loads the properties in that file
  def initialize file
  @file = file
  @properties = {}
  IO.foreach(file) do |line|
  @properties[$1.strip] = $2 if line =~ /([^=]*)=(.*)\/\/(.*)/ || line =~ /([^=]*)=(.*)/
  end
  end
  
  #Helpfull to string
  def to_s
  output = "File Name #{@file} \n"
  @properties.each {|key,value| output += " #{key}= #{value} \n" }
  output
  end
  
  #Write a property
  def write_property (key,value)
  @properties[key] = value
  end

  #Write a property
  def read_property (key)
  @properties[key]
  end
  
  #Save the properties back to file
  def save
  file = File.new(@file,"w+")
  @properties.each {|key,value| file.puts "#{key}=#{value}\n" }
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.136.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status |
| ----------------------------------------- | ------- | ------------- |
| fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| did_you_mean                              | 1.3.0        |
| bundler                                   | 2.0.2        |
| CFPropertyList                            | 3.0.1        |
| public_suffix                             | 2.0.5        |
| addressable                               | 2.7.0        |
| atomos                                    | 0.1.3        |
| babosa                                    | 1.0.3        |
| claide                                    | 1.0.3        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 1.7.10       |
| commander-fastlane                        | 4.4.6        |
| declarative                               | 0.0.10       |
| declarative-option                        | 0.1.0        |
| digest-crc                                | 0.4.1        |
| unf_ext                                   | 0.0.7.6      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.7.5        |
| emoji_regex                               | 1.0.1        |
| excon                                     | 0.68.0       |
| multipart-post                            | 2.0.0        |
| faraday                                   | 0.17.0       |
| http-cookie                               | 1.0.3        |
| faraday-cookie_jar                        | 0.0.6        |
| faraday_middleware                        | 0.13.1       |
| fastimage                                 | 2.1.7        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.1.0        |
| memoist                                   | 0.16.1       |
| multi_json                                | 1.14.1       |
| os                                        | 1.0.1        |
| signet                                    | 0.12.0       |
| googleauth                                | 0.6.7        |
| httpclient                                | 2.8.3        |
| mime-types-data                           | 3.2019.1009  |
| mime-types                                | 3.3          |
| uber                                      | 0.1.0        |
| representable                             | 3.0.4        |
| retriable                                 | 3.1.2        |
| google-api-client                         | 0.23.9       |
| google-cloud-env                          | 1.3.0        |
| google-cloud-core                         | 1.4.1        |
| google-cloud-storage                      | 1.16.0       |
| json                                      | 2.2.0        |
| mini_magick                               | 4.9.5        |
| multi_xml                                 | 0.6.0        |
| plist                                     | 3.5.0        |
| rubyzip                                   | 1.3.0        |
| security                                  | 0.1.3        |
| naturally                                 | 2.2.0        |
| simctl                                    | 1.6.6        |
| slack-notifier                            | 2.3.2        |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 1.6.0        |
| terminal-table                            | 1.8.0        |
| tty-screen                                | 0.7.0        |
| tty-cursor                                | 0.7.0        |
| tty-spinner                               | 0.9.1        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.2.6        |
| xcodeproj                                 | 1.13.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.0        |
| fastlane-plugin-firebase_app_distribution | 0.1.4        |
</details>

*generated on:* **2019-11-16**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #15667

### Description
`rollout` is "valid" but doesn't do anything in Google Play. The solution that has been validated by other users is to use `production` 👌 

#### A fun rubocop change
```
supply/lib/supply/options.rb:48:143: C: [Corrected] Use casecmp instead of downcase ==.
                                       UI.user_error!("'rollout' is no longer a valid track name - please use 'production' instead") if value.downcase == 'rollout'
                                                                                                                                              ^^^^^^^^^^^
supply/lib/supply/options.rb:216:143: C: [Corrected] Use casecmp instead of downcase ==.
                                       UI.user_error!("'rollout' is no longer a valid track name - please use 'production' instead") if value.downcase == 'rollout'
```

### CODE REVIEW

File: supply/lib/supply/options.rb [hunk 1]
```diff
@@ -43,7 +43,10 @@ def self.available_options
                                      env_name: "SUPPLY_TRACK",
                                      description: "The track of the application to use. The default available tracks are: #{Supply::Tracks::DEFAULTS.join(', ')}",
                                      default_value: Supply::Tracks::DEFAULT,
-                                     type: String),
+                                     type: String,
+                                     verify_block: proc do |value|
+                                       UI.user_error!("'rollout' is no longer a valid track name - please use 'production' instead") if value.casecmp('rollout').zero?
```
Comment (snatchev) [inline supply/lib/supply/options.rb]: use `String.casecmp?`

**Review by snatchev — APPROVED** [review]
just a small style change, plz.

File: supply/lib/supply/options.rb (hunk 1 above)
Comment (joshdholtz) [reply supply/lib/supply/options.rb]: I'll see if rubocop lets me do that 🙃

Comment (joshdholtz) [reply supply/lib/supply/options.rb]: Turns out its a Ruby 2.4 thing 😢
