### PR TITLE
[action][ensure_git_status_clean] support empty spaces in `ignore_files` file paths

### LINKED ISSUE #21563: ensure_git_status_clean parameter ignore_files does not ignore the file when the path has a space
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [X] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [X] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
When the file path has a space, it cannot be ignored by the ensure_git_status_clean action

##### Command executed
Tried the following commands 

`bundle exec fastlane run ensure_git_status_clean ignore_files:Notification/Info.plist,IntentHandler/Info.plist,iOS/Info.plist,App Widget/Info.plist
`
`bundle exec fastlane run ensure_git_status_clean ignore_files:Notification/Info.plist,IntentHandler/Info.plist,iOS/Info.plist,"App Widget/Info.plist"`

Both cannot ignore the `App Widget/Info.plist` file 

##### Complete output when running fastlane, including the stack trace and command used
```
[⠋] 🚀 Ignoring ffi-1.16.2 because its extensions are not built. Try: gem pristine ffi --version 1.16.2
[✔] 🚀
[14:57:51]: fastlane detected a Gemfile in the current directory
[14:57:51]: However, it seems like you didn't use `bundle exec`
[14:57:51]: To launch fastlane faster, please use
[14:57:51]:
[14:57:51]: $ bundle exec fastlane run ensure_git_status_clean ignore_files:Notification/Info.plist,IntentHandler/Info.plist,iOS/Info.plist,”App Widget/Info.plist”
[14:57:51]:
[14:57:51]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[14:57:52]: -------------------------------------
[14:57:52]: --- Step: ensure_git_status_clean ---
[14:57:52]: -------------------------------------
[14:57:52]: Ignoring 'IntentHandler/Info.plist'
[14:57:52]: $ git status --porcelain
[14:57:52]: ▸  M .previous_issue_count
[14:57:52]: ▸  M "App Widget/Info.plist"
[!] Git repository is dirty! Please ensure the repo is in a clean state by committing/stashing/discarding all changes first.
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.0                                        |
| Ruby                        | 3.1.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-145)          |
| Installation Source         | ~/.rvm/gems/ruby-3.1.2/bin/fastlane         |
| Host                        | macOS 14.0 (23A344)                         |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-3.1.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.0                                        |
| Swift Version               | 5.9                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.3.0        |
| did_you_mean                    | 1.6.1        |
| artifactory                     | 3.0.15       |
| jmespath                        | 1.6.1        |
| aws-partitions                  | 1.664.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.1      |
| aws-sdk-kms                     | 1.59.0       |
| aws-sdk-s3                      | 1.117.1      |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.94.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.0.0        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| faraday_middleware              | 1.2.0        |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.1        |
| google-apis-androidpublisher_v3 | 0.31.0       |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| mini_magick                     | 4.11.0       |
| naturally                       | 2.2.1        |
| optparse                        | 0.1.1        |
| plist                           | 3.6.0        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| simctl                          | 1.6.8        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.2        |
| public_suffix                   | 5.0.0        |
| addressable                     | 2.8.5        |
| bundler                         | 2.4.15       |
| rexml                           | 3.2.6        |
| CFPropertyList                  | 3.0.6        |
| jwt                             | 2.7.1        |
| json                            | 2.6.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.23.0       |
| forwardable                     | 1.3.2        |
| logger                          | 1.5.0        |
| pathname                        | 0.2.0        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.1        |
| date                            | 3.2.2        |
| timeout                         | 0.2.0        |
| stringio                        | 3.0.1        |
| securerandom                    | 0.1.1        |
| uri                             | 0.11.0       |
| openssl                         | 3.0.0        |
| digest                          | 3.1.0        |
| io-nonblock                     | 0.1.0        |
| ipaddr                          | 1.2.4        |
| io-wait                         | 0.2.1        |
| zlib                            | 2.1.1        |
| resolv                          | 0.2.1        |
| time                            | 0.2.0        |
| open-uri                        | 0.2.0        |
| mutex_m                         | 0.1.1        |
| net-protocol                    | 0.1.2        |
| net-http                        | 0.2.0        |
| ostruct                         | 0.5.2        |
| english                         | 0.7.1        |
| erb                             | 2.2.3        |
| strscan                         | 3.0.1        |
| abbrev                          | 0.1.0        |
| io-console                      | 0.5.11       |
| tempfile                        | 0.1.2        |
| delegate                        | 0.2.0        |
| fileutils                       | 1.6.0        |
| tmpdir                          | 0.1.2        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.1        |
| nkf                             | 0.1.1        |
| prettyprint                     | 0.1.1        |
| pp                              | 0.3.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.0        |
| psych                           | 4.0.3        |
</details>

*generated on:* **2023-10-09**
</details>

### PR DESCRIPTION
**Pull request by mollyIV**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #21563

### Description

This pull request fixes an issue related to `ensure_git_status_clean` action when a parameter `ignore_files` does not ignore the file when a path has a space. 

To extract the file path correctly, we can use a regular expression to match the file path, including the file path that contains spaces.

We use a regular expression `(/\s(.*)/)` to match the file path after the first whitespace character. We use the `match` method to find the first match of the regular expression in the line, and then get the second element of the resulting match data to get the file path.

It is a safe assumption for the `git status --porcelain` command. [The `git status` documentation](https://git-scm.com/docs/git-status#_porcelain_format_version_1) specifies that the `porcelain` format uses a single space character to separate the status from the file path.

### Testing Steps

```bash
$ bundle exec rspec ./fastlane/spec/actions_specs/ensure_git_status_clean_spec.rb
```

### CODE REVIEW

**Comment by mollyIV** [comment]
In the addition to unit testing, the issue has been tested manually: https://github.com/fastlane/fastlane/issues/21563#issuecomment-1758090155 and https://github.com/fastlane/fastlane/issues/21563#issuecomment-1761546721 💪

File: fastlane/lib/fastlane/actions/ensure_git_status_clean.rb [hunk 1]
```diff
@@ -23,7 +23,25 @@ def self.run(params)
         # Manual post processing trying to ignore certain file paths
         if (ignore_files = params[:ignore_files])
           repo_status = repo_status.lines.reject do |line|
-            path = line.split(' ').last
+            # Extract the file path from the line based on
+            # https://git-scm.com/docs/git-status#_output
+
+            # The first two characters indicate the status of the file path (e.g. ' M')
+            # XY PATH
+            path = line&.match(/^.{2}\s(.*)/)&.[](1) || ''
```
Comment (lacostej) [inline fastlane/lib/fastlane/actions/ensure_git_status_clean.rb:31]: Why are we using `&` here? How can `line` be `nil`?

File: fastlane/lib/fastlane/actions/ensure_git_status_clean.rb [hunk 2]
```diff
@@ -23,7 +23,25 @@ def self.run(params)
...
+
+            # If the file path is renamed, the original path is also included in the line (e.g. ' R ORIG_PATH -> PATH')
+            # XY ORIG_PATH -> PATH
+            path = path.split('->').last.strip if path.include?('->')
+
+            # Remove double quotes from the file path
+            path = path.gsub(/"/, '')
```
Comment (lacostej) [inline fastlane/lib/fastlane/actions/ensure_git_status_clean.rb:38]: this could be risky if the file name contained a quote.

Maybe you can solve the whole matching using a single regular expression

```ruby
def path_from_git_status_line(line)
  path = line.match(/^.. (.* -> )?(.*)$/)[2]
  path = path.delete_prefix('"').delete_suffix('"')
end

lines=[ 
 ' M .previous_issue_count',
 ' M "A File Path"',
 ' M .previous_issue_count -> .previous_issue_count.new',
 ' M "A/File Path" -> "A/File Path.new"']

lines.map{|l| path_from_git_status_line(l)}
```

https://rubular.com/

File: fastlane/spec/actions_specs/ensure_git_status_clean_spec.rb [hunk 3]
```diff
@@ -39,6 +39,28 @@
             end").runner.execute(:test)
           end
 
+          it "outputs success message when a file path contains spaces" do
+            allow(Fastlane::Actions).to receive(:sh).with("git status --porcelain", log: false).and_return(" M fastlane/spec/fixtures/git_commit/A FILE WITH SPACE")
```
Comment (lacostej) [inline fastlane/spec/actions_specs/ensure_git_status_clean_spec.rb:43]: aren't file names with spaces double quoted in `git status` output?

From the manual

"The fields (including the ->) are separated from each other by a single space. If a filename contains whitespace or other nonprintable characters, that field will be quoted in the manner of a C string literal: surrounded by ASCII double quote (34) characters, and with interior special characters backslash-escaped."

**Review by lacostej — CHANGES_REQUESTED** [review]
Hello, thanks for the contribution! Please see above comments regarding the code and the unit test setup.

**Comment by lacostej** [comment]
Hei @mollyIV, did you see my comments above? Thanks!

**Comment by lacostej** [comment]
@mollyIV any chance you can look at the comments above? Thanks

File: fastlane/lib/fastlane/actions/ensure_git_status_clean.rb (hunk 1 above)
Comment (mollyIV) [reply fastlane/lib/fastlane/actions/ensure_git_status_clean.rb]: Good catch, indeed, a line cannot be `nil`. Fixed.

File: fastlane/lib/fastlane/actions/ensure_git_status_clean.rb (hunk 2 above)
Comment (mollyIV) [reply fastlane/lib/fastlane/actions/ensure_git_status_clean.rb]: `git status --porcelain` escapes the quote and the output looks like this: 

```
 M "\"quote.swift"
```

To ignore a file with a quote in the name, users will need to espace it in the Fastfile too:

```
ensure_git_status_clean(
  ignore_files: ["\\\"quote.swift"]
)
```

Thanks for the suggestion! Fixed ✔️

File: fastlane/spec/actions_specs/ensure_git_status_clean_spec.rb (hunk 3 above)
Comment (mollyIV) [reply fastlane/spec/actions_specs/ensure_git_status_clean_spec.rb]: Right 👍 

```
R  "File with spaces.swift" -> "File with spaces 1.swift"
```

Fixed ✔️

**Comment by mollyIV** [comment]
Hi @lacostej, 

I finally managed to complete the requested changes. Thanks a lot for your feedback; I really appreciate it 🙏

Please have a look when you have time. Cheers!

**Review by lacostej — APPROVED** [review]
Thanks! LGTM
