### PR TITLE
[deliver] make automatic_release optional for app types that aren't a ble to set it (like Apple Arcade and Pre Release)

### LINKED ISSUE #16911: Error during uploading metadata: The attribute 'releaseType' can not be modified.
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I got an error during metadata upload:
 [!] An attribute value is not acceptable for the current resource state. - The attribute 'releaseType' can not be modified.

In the past, I used deliver for uploading metadata without any issues.

##### Command executed
`fastlane run deliver skip_metadata:false skip_screenshots:true`

##### Complete output when running fastlane, including the stack trace and command used
```
ci$ fastlane run deliver skip_metadata:false skip_screenshots:true
[✔] 🚀 
[17:36:53]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:36:55]: ---------------------
[17:36:55]: --- Step: deliver ---
[17:36:55]: ---------------------
[17:36:55]: Successfully loaded '/Users/ci/sources/xxxxxx/xxxxxx/fastlane/Deliverfile' 📄

+----------------------------+-------------------------------+
|       Detected Values from './fastlane/Deliverfile'        |
+----------------------------+-------------------------------+
| username                   | xxxxxx@xxxxxx.com        |
| app_identifier             | com.xxxxxx.xxxxxx |
| team_name                  | xxxxxx X.X.            |
| skip_binary_upload         | true                          |
| skip_metadata              | true                          |
| skip_app_version_update    | true                          |
| run_precheck_before_submit | false                         |
| overwrite_screenshots      | true                          |
+----------------------------+-------------------------------+

[17:36:55]: Login to App Store Connect (xxxxxx@xxxxxx.com)
[17:36:57]: Login successful

+--------------------------------------+-------------------------------+
|                       deliver 2.152.0 Summary                        |
+--------------------------------------+-------------------------------+
| skip_metadata                        | false                         |
| skip_screenshots                     | true                          |
| screenshots_path                     | ./fastlane/screenshots        |
| metadata_path                        | ./fastlane/metadata           |
| username                             | xxxxxx@xxxxxx.com        |
| app_identifier                       | com.xxxxxx.xxxxxx |
| platform                             | ios                           |
| edit_live                            | false                         |
| use_live_version                     | false                         |
| skip_binary_upload                   | true                          |
| skip_app_version_update              | true                          |
| force                                | false                         |
| overwrite_screenshots                | true                          |
| submit_for_review                    | false                         |
| reject_if_possible                   | false                         |
| automatic_release                    | false                         |
| phased_release                       | false                         |
| reset_ratings                        | false                         |
| team_name                            | xxxxxx X.X.            |
| run_precheck_before_submit           | false                         |
| precheck_default_rule_level          | warn                          |
| ignore_language_directory_validation | false                         |
| precheck_include_in_app_purchases    | true                          |
+--------------------------------------+-------------------------------+

[17:36:59]: Loading './fastlane/metadata/en-AU/description.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/name.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-AU/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/description.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/name.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-CA/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/description.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/name.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-GB/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/description.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/name.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/en-US/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/description.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/name.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-ES/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/description.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/name.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/es-MX/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/description.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/name.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-CA/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/description.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/name.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/fr-FR/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/description.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/keywords.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/release_notes.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/support_url.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/marketing_url.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/promotional_text.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/name.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/subtitle.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/privacy_url.txt'...
[17:36:59]: Loading './fastlane/metadata/nl-NL/apple_tv_privacy_policy.txt'...
[17:36:59]: Loading './fastlane/metadata/copyright.txt'...
[17:36:59]: Loading './fastlane/metadata/primary_category.txt'...
[17:36:59]: Loading './fastlane/metadata/secondary_category.txt'...
[17:36:59]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
[17:36:59]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
[17:36:59]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
[17:36:59]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/first_name.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/last_name.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/phone_number.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/email_address.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/demo_user.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/demo_password.txt'...
[17:36:59]: Loading './fastlane/metadata/review_information/notes.txt'...
[17:37:00]: Verifying the upload via the HTML file can be disabled by either adding
[17:37:00]: `force true` to your Deliverfile or using `fastlane deliver --force`
[17:37:00]: Does the Preview on path './fastlane/Preview.html' look okay for you? (y/n)
y
[17:37:06]: HTML file confirmed...
[17:37:33]: Will begin uploading metadata for 'X.X' on App Store Connect
[17:37:33]: Uploading metadata to App Store Connect for version

Looking for related GitHub issues on fastlane/fastlane...

➡️  Deliver: The attribute 'releaseType' can not be modified
    https://github.com/fastlane/fastlane/issues/16679 [closed] 11 💬
    an hour ago

➡️  Server error 504 when uploading metadata
    https://github.com/fastlane/fastlane/issues/16665 [closed] 63 💬
    3 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	26: from /usr/local/bin/fastlane:23:in `<main>'
	25: from /usr/local/bin/fastlane:23:in `load'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:42:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:124:in `upload_metadata'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/upload_metadata.rb:181:in `upload'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:88:in `update'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:733:in `patch_app_store_version'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:110:in `patch'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': An attribute value is not acceptable for the current resource state. - The attribute 'releaseType' can not be modified. (Spaceship::UnexpectedResponse)
	26: from /usr/local/bin/fastlane:23:in `<main>'
	25: from /usr/local/bin/fastlane:23:in `load'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/bin/fastlane:23:in `<top (required)>'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	18: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	17: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/commands_generator.rb:224:in `block (2 levels) in run'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/one_off.rb:42:in `run'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/fastlane/lib/fastlane/actions/upload_to_app_store.rb:17:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:42:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/runner.rb:124:in `upload_metadata'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/deliver/lib/deliver/upload_metadata.rb:181:in `upload'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/models/app_store_version.rb:88:in `update'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/tunes/tunes.rb:733:in `patch_app_store_version'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:110:in `patch'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': [!] An attribute value is not acceptable for the current resource state. - The attribute 'releaseType' can not be modified. (Spaceship::UnexpectedResponse)
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

```
### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.6                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.24.3 (Apple Git-128)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.6 (19G73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.6                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.152.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**
```

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context
Fixes #16911

### Description
- Makes `automatic_release` an optional boolean
  - ⚠️  This is a slightly breaking change as previous it would default to manual
- This is need because Apple Arcade and Pre Release apps are not allowed to set this value
  - Apple Arcade apps cannot be detected/queried by the official App Store Connect API (yet) so the decision was made to make this option allow nil values (which I believe should be how this should work anyway 🤷 )
- A `UI.important` gets shown if no value is selected because information is good and it is slightly breaking
- Also added a 2 second sleep before and after version update because some where were getting an invalid state error that was weird and I think its a race condition within the API 🤷‍♂️ 

ℹ️  We will make sure to include a specific callout to this in the release notes for the next version

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz-make-deliver-automatic_release-optional"
```

### CODE REVIEW

File: deliver/lib/deliver/upload_metadata.rb [hunk 1]
```diff
@@ -175,17 +175,26 @@ def upload(options)
...
+      if release_type.nil?
+        UI.important("Release type will not get because Neither `automatic_release` nor `auto_release_date` are provided. Please explicitly set one of these options if you need a release type set")
+      else
+        non_localized_version_attributes['releaseType'] = release_type
+      end
 
       # Update app store version
       # This needs to happen before updating localizations (https://openradar.appspot.com/radar?id=4925914991296512)
+      #
+      # Adding some sleeps because the API sometimes will sometimes be in a state where releaseType can't be modified
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:192]:
```suggestion
      # Adding some sleeps because the API will sometimes be in a state where releaseType can't be modified
```

File: deliver/lib/deliver/upload_metadata.rb [hunk 2]
```diff
@@ -175,17 +175,26 @@ def upload(options)
...
-                     elsif options[:automatic_release]
+                     elsif options[:automatic_release] == true
                        Spaceship::ConnectAPI::AppStoreVersion::ReleaseType::AFTER_APPROVAL
-                     else
+                     elsif options[:automatic_release] == false
                        Spaceship::ConnectAPI::AppStoreVersion::ReleaseType::MANUAL
                      end
-      non_localized_version_attributes['releaseType'] = release_type
+      if release_type.nil?
+        UI.important("Release type will not get because Neither `automatic_release` nor `auto_release_date` are provided. Please explicitly set one of these options if you need a release type set")
```
Comment (rogerluan) [inline deliver/lib/deliver/upload_metadata.rb:184]: ? 🤔 😅 
```suggestion
        UI.important("Release type will not be set because neither `automatic_release` nor `auto_release_date` were provided. Please explicitly set one of these options if you need a release type set")
```

**Review by rogerluan — APPROVED** [review]
Logic looks good. Very helpful context/explanation in the PR desc and the associated issue 🙏 
Looks like their API is full of race conditions 😓 we've been adding sleeps and retries everywhere

image

File: deliver/lib/deliver/upload_metadata.rb (hunk 2 above)
Comment (joshdholtz) [reply deliver/lib/deliver/upload_metadata.rb:184]: I’M SO BAD AT NON-PROGRAMMING WORDS

**Review by snatchev — CHANGES_REQUESTED** [review]

File: deliver/lib/deliver/upload_metadata.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (joshdholtz) [reply deliver/lib/deliver/upload_metadata.rb]: @snatchev The mispelling was already caught by @rogerluan and fixed 😉 I’m so bad at words

[the remark this answers is not in the document]
Comment (joshdholtz) [reply deliver/lib/deliver/upload_metadata.rb]: I reread that like 100 times too

**Review by snatchev — APPROVED** [review]
After embracing the three-state boolean values, this is LGTM 🚀
