### PR TITLE
[spaceship] New AppleID Auth with SRP

### LINKED ISSUE #26368: 503 Service Temporarily Unavailable on various fastlane modules
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
get_certificates aborts with:
```
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Apple</center>
</body>
</html>
```

##### Command executed
The problem seems to be related to the url:

```
 fetch('https://idmsa.apple.com/appleauth/auth/signin', {
        "headers": {
            "content-type": "application/json",
            'X-Requested-With': 'XMLHttpRequest',
            'X-Apple-Widget-Key': 'e0b80c3bf78523bfe80974d320935bfa30add02e1bff88ec2166c6bd5a706c42',
            'scnt':SCNT,
            'X-APPLE-HC:HC,
            'X-Apple-ID-Session-id,
            'Accept': 'application/json, text/javascript'
        },
        "method": "POST",
        "body": "{\"accountName\":\"" + username + "\",\"rememberMe\":false,\"password\":\"" + password + "\"}",
```

Apple now seems to be using a slightly different url

`https://idmsa.apple.com/appleauth/auth/signin/complete`

and also the POST body has changed to:

`{"accountName":"foo@bar.com","rememberMe":false, "m1":"xxx","c":"yyy","m2":"zzz"}`

where xxx,yyy,zzz seem to be randomly changing.

Actually, I could verify that 2 things currently do not work anymore:
a) Authenticating with username/password to trigger the 2FA process (to then use hashCash to generate the DES cookie)
b) using an actual valid DES cookie for authentication. 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> 09:06:42]: -----------------------------
[09:06:42]: --- Step: update_fastlane ---
[09:06:42]: -----------------------------
[09:06:42]: Looking for updates for fastlane...
[09:06:43]: Nothing to update ✅
[09:06:43]: Fastlane is checking for critical comments in Source Code.

[09:06:43]: ------------------------------
[09:06:43]: --- Step: default_platform ---
[09:06:43]: ------------------------------
[09:06:43]: Welcome to fastlane! Here's what your app is set up to do:
+-----------------------------------------------------------------+
|                     Available lanes to run                      |
+--------+-----------------+--------------------------------------+
| Number | Lane Name       | Description                          |
+--------+-----------------+--------------------------------------+
| 1      | ios publish     | Publish new release or build for iOS |
| 2      | ios adhoc       | Ad-Hoc                               |
| 3      | ios nothing     | Do nothing                           |
| 4      | ios screenshots | Screenshots                          |
| 0      | cancel          | No selection, exit fastlane!         |
+--------+-----------------+--------------------------------------+
[09:06:43]: Which number would you like to run?
2
[09:07:05]: Running lane `ios adhoc`. Next time you can do this by directly typing `fastlane ios adhoc` 🚀.
[09:07:05]: Driving the lane 'ios adhoc' 🚀
[09:07:05]: ------------------------------
[09:07:05]: --- Step: get_certificates ---
[09:07:05]: ------------------------------

+---------------------------------------------------------------------------------+
|                            Summary for cert 2.224.0                             |
+-------------------------+-------------------------------------------------------+
| development             | false                                                 |
| force                   | false                                                 |
| generate_apple_certs    | true                                                  |
| username                | XXXXX@yahoo.com                                   |
| team_id                 | DSXXXXXX                                            |
| keychain_path           | /Users/XXXXXX/Library/Keychains/login.keychain-db |
| skip_set_partition_list | false                                                 |
| platform                | ios                                                   |
+-------------------------+-------------------------------------------------------+

[09:07:05]: Starting login with user 'XXXXXX@yahoo.com'
Available session is not valid anymore. Continuing with normal login.
+------------------------------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios adhoc |
+------------------+-----------+
[09:07:07]: Called from Fastfile at line 196
[09:07:07]: ```
[09:07:07]:     194:      desc "Ad-Hoc"
[09:07:07]:     195:      lane :adhoc do
[09:07:07]:  => 196:        get_certificates
[09:07:07]:     197:      end
[09:07:07]:     198:    end
[09:07:07]: ```
[09:07:07]: <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Apple</center>
</body>
</html>

+---------------------------------------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | update_fastlane        | 1           |
| 2    | ./check_source_code.sh | 0           |
| 3    | default_platform       | 0           |
| 💥   | get_certificates       | 2           |
+------+------------------------+-------------+

[09:07:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[!] The request could not be completed because:
        <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>Apple</center>
</body>
</html>
</pre>
</details>

### Environment

<details>
  <pre> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 14.6.1                                      |
| Ruby                        | 3.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.39.3 (Apple Git-146)          |
| Installation Source         | ~/.gem/ruby/3.2.2/bin/fastlane              |
| Host                        | macOS 14.6.1 (23G93)                        |
| Ruby Lib Dir                | ~/.rubies/ruby-3.2.2/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1u  30 May 2023                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 15.4                                        |
| Swift Version               | 5.10                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane



# 
before_all do
  ENV['FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD']= FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD
  ENV["TREE_SHAKE_ICONS"] = "false"
end


default_platform(:ios)


# 
# Ad-Hoc lane
#
platform :ios do
  desc "Ad-Hoc"
  lane :adhoc do
    get_certificates
  end
end



# 
# Do nothing
#
platform :ios do
  desc "Do nothing"
  lane :nothing do
    puts "doing nothing"
  end
end




# [12:41:19]: Starting login with user 'XXXXXXX@yahoo.com'
# Available session is not valid anymore. Continuing with normal login.
# [12:43:00]: Successfully logged in
# [12:43:00]: Fetching profiles...
# [12:43:24]: Found 2 matching profile(s)
# [12:43:24]: Recreating the profile
# [12:43:56]: The name 'comXXXXXXAppStore' is already taken, using another one.
# [12:44:14]: Creating new provisioning profile for 'com.XXXXX' with name 'com.XXXXX AppStore XXXXXX' for 'ios' platform
# [12:45:12]: Downloading provisioning profile...
# [12:45:12]: Successfully downloaded provisioning profile...
# [12:45:12]: Installing provisioning profile...
# /Users/marcfelden/Documents/dev/flutter/flutter_nb/ios/myFile.mobileprovision
# [12:45:13]: Setting Provisioning Profile type to 'app-store'
# [12:45:13]: --------------------------------------
# [12:45:13]: --- Step: increment_version_number ---
# [12:45:13]: --------------------------------------
# [12:45:13]: $ cd /Users/marcfelden/Documents/dev/flutter/flutter_nb/ios && agvtool new-marketing-version 9.6.37
# [12:45:13]: ▸ Setting CFBundleShortVersionString of project Runner to:
# [12:45:13]: ▸ 9.6.37.
# [12:45:13]: ▸ Updating CFBundleShortVersionString in Info.plist(s)...
# [12:45:13]: ▸ Updated CFBundleShortVersionString in "Runner.xcodeproj/../Runner/Info.plist" to 9.6.37
# [12:45:13]: ▸ Cannot find "Runner.xcodeproj/../YES"
# [12:45:13]: ------------------------------------
# [12:45:13]: --- Step: increment_build_number ---
# [12:45:13]: ------------------------------------
# Current version of project Runner is: 
#     1

# /Users/XXXXX/Documents/dev/flutter/flutter_nb/ios
# [12:45:13]: $ cd /Users/XXXXXX/Documents/dev/flutter/flutter_nb/ios && agvtool new-version -all 2 && cd -
# [12:45:13]: ▸ Setting version of project Runner to:
# [12:45:13]: ▸ 2.
# [12:45:13]: ▸ Also setting CFBundleVersion key (assuming it exists)
# [12:45:13]: ▸ Updating CFBundleVersion in Info.plist(s)...
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier("com.XXXXX") # The bundle identifier of your app
apple_id("XXXXXX@yahoo.com") # Your Apple Developer Portal username

itc_team_id("XXXXXXXX") # App Store Connect Team ID
team_id("XXXXXXX") # Developer Portal Team ID

# For more information about the Appfile, see:
#     https://docs.fastlane.tools/advanced/#appfile

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.224.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| babosa                          | 1.0.4        |
| bundler                         | 2.4.22       |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| faraday-cookie_jar              | 0.0.7        |
| gh_inspector                    | 1.1.3        |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| terminal-table                  | 3.0.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.1        |
| set                             | 1.0.3        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| aws-eventstream                 | 1.3.0        |
| aws-sigv4                       | 1.10.0       |
| aws-partitions                  | 1.982.0      |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.209.1      |
| aws-sdk-kms                     | 1.94.0       |
| aws-sdk-s3                      | 1.166.0      |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| rexml                           | 3.3.8        |
| CFPropertyList                  | 3.0.7        |
| excon                           | 0.112.0      |
| ruby2_keywords                  | 0.0.5        |
| faraday-retry                   | 1.0.3        |
| faraday-rack                    | 1.0.0        |
| faraday-patron                  | 1.0.0        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-net_http                | 1.0.2        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.0.4        |
| faraday-httpclient              | 1.0.1        |
| faraday-excon                   | 1.1.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-em_http                 | 1.0.0        |
| faraday                         | 1.10.4       |
| faraday_middleware              | 1.2.1        |
| domain_name                     | 0.6.20240107 |
| http-cookie                     | 1.0.7        |
| fastimage                       | 2.3.1        |
| httpclient                      | 2.8.3        |
| multi_json                      | 1.15.0       |
| jwt                             | 2.9.1        |
| signet                          | 0.19.0       |
| os                              | 1.1.4        |
| googleauth                      | 1.8.1        |
| mini_mime                       | 1.1.5        |
| retriable                       | 3.1.2        |
| trailblazer-option              | 0.1.2        |
| declarative                     | 0.0.20       |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| rake                            | 13.2.1       |
| digest-crc                      | 0.6.5        |
| google-apis-storage_v1          | 0.31.0       |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.7.2        |
| mini_magick                     | 4.13.2       |
| optparse                        | 0.5.0        |
| plist                           | 3.7.1        |
| unicode-display_width           | 2.6.0        |
| tty-screen                      | 0.8.2        |
| nanaimo                         | 0.3.0        |
| colored2                        | 3.1.2        |
| claide                          | 1.1.0        |
| atomos                          | 0.1.3        |
| xcodeproj                       | 1.25.0       |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.1       |
| ipaddr                          | 1.2.5        |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| resolv                          | 0.2.2        |
| time                            | 0.2.2        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| racc                            | 1.6.2        |
| nokogiri                        | 1.15.5       |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| ostruct                         | 0.5.5        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

*generated on:* **2024-10-19**
</details> </pre>
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
### Motivation and Context

Fixes #26368

Apple has released a new version of their Apple ID auth that uses SIRP (well, their version at least). Apple ID auth is broken so need to fix.

### Description

Soooooo much of this work was done by @snatchev over a year ago when he discovered this optional new auth system. We have forked his fork of `sirp` and have it over at https://github.com/fastlane/fastlane-sirp. This is released under a new RubyGem called `fastlane-sirp`. Its not an exact implementation of [SRP](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) but its Apple's version 🤷‍♂️ 

#### New `FASTLANE_USE_LEGACY_PRE_SIRP_AUTH` env

The `FASTLANE_USE_LEGACY_PRE_SIRP_AUTH` can be set to use the previous Apple ID auth logic (if it ever works again). I didn't feel comfortable deleting the path so put it behind this flag.

### Testing Steps

Update `Gemfile` and run `bundle install`, `bundle update fastlane`, or `bundle update`

```rb
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "joshdholtz/apple-auth-sirp"
```

### CODE REVIEW

**Comment by davidmdt21** [comment]
thank you so much . problem fixed ! work fine

File: spaceship/lib/spaceship/client.rb [hunk 1]
```diff
@@ -491,22 +576,28 @@ def send_shared_login_request(user, password)
...
-          req.url("https://idmsa.apple.com/appleauth/auth/signin")
-          req.body = data.to_json
-          req.headers['Content-Type'] = 'application/json'
-          req.headers['X-Requested-With'] = 'XMLHttpRequest'
-          req.headers['X-Apple-Widget-Key'] = self.itc_service_key
-          req.headers['Accept'] = 'application/json, text/javascript'
-          req.headers["Cookie"] = modified_cookie if modified_cookie
-          req.headers["X-Apple-HC"] = hashcash if hashcash
-        end
+        do_legacy_signin = ENV['FASTLANE_USE_LEGACY_PRE_SIRP_AUTH']
```
Comment (joshdholtz) [inline spaceship/lib/spaceship/client.rb:579]: A ENV to use to use existing logic _if_ it ever starts working again 🤷‍♂️ I didn't feel comfortable deleting that path

File: spaceship/spec/spec_helper.rb [hunk 2]
```diff
@@ -112,3 +112,25 @@ def mock_client_response(method_name, with: anything)
...
+  let(:username) { 'spaceship@krausefx.com' }
+  let(:password) { 'so_secret' }
+
+  before {
+    allow_any_instance_of(SIRP::Client).to receive(:start_authentication).and_return(authentication_data)
+    allow_any_instance_of(SIRP::Client).to receive(:process_challenge).and_return("1234")
+
+    Spaceship::Tunes.login unless skip_tunes_login
+  }
+end
```
Comment (joshdholtz) [inline spaceship/spec/spec_helper.rb:136]: Added a shared example that can be used in ALL of the tests that use spaceship to login that mocks the SIRP stuff. It gets used like `include_examples "common spaceship login"`

File: spaceship/lib/spaceship/client.rb [hunk 3]
```diff
@@ -450,6 +450,96 @@ def has_valid_session
...
+      m1 = client.process_challenge(
+        user,
+        to_hex(encrypted_password),
+        to_hex(salt),
+        to_hex(b),
+        is_password_encrypted: true
+      )
+      m2 = client.H_AMK
+
+      unless m1
```
Comment (snatchev) [inline spaceship/lib/spaceship/client.rb:498]: Since process_challenge returns `false` or a string, it would be more clear if this check was 
```
if m1 == false
```
I assumed this was a nil check at first.

File: spaceship/lib/spaceship/client.rb [hunk 4]
```diff
@@ -491,22 +581,31 @@ def send_shared_login_request(user, password)
...
-          req.body = data.to_json
-          req.headers['Content-Type'] = 'application/json'
-          req.headers['X-Requested-With'] = 'XMLHttpRequest'
-          req.headers['X-Apple-Widget-Key'] = self.itc_service_key
-          req.headers['Accept'] = 'application/json, text/javascript'
-          req.headers["Cookie"] = modified_cookie if modified_cookie
-          req.headers["X-Apple-HC"] = hashcash if hashcash
-        end
+        do_legacy_signin = ENV['FASTLANE_USE_LEGACY_PRE_SIRP_AUTH']
+        response = if do_legacy_signin
```
Comment (snatchev) [inline spaceship/lib/spaceship/client.rb:585]: This conditional with a return is very long, would be better to be wrapped in a function? Maybe something like `select_login_method( ... ) `?

File: spaceship/spec/base_spec.rb [hunk 5]
```diff
@@ -1,4 +1,5 @@
 describe Spaceship::Base do
+  include_examples "common spaceship login", true
```
Comment (snatchev) [inline spaceship/spec/base_spec.rb:2]: I am not familiar with `include_examples` but why not change what `Spaceship::Tunes.login` does in test so that we always choose the SIRP login?

**Review by snatchev — CHANGES_REQUESTED** [review]
🙏 thank you for your hard work!

File: spaceship/spec/base_spec.rb (hunk 5 above)
Comment (joshdholtz) [reply spaceship/spec/base_spec.rb:2]: We do always choose the SIRP login! This just adds some mocking that is _kind of_ required for SIRP because there is a `SecureRandom.hex(256)` inside of SIRP implementation when its makes the `a`.  So the `include_example` is a way to do that in each of the tests with only one line 🤷‍♂️

**Review by snatchev — APPROVED** [review]
LGTM!

**Comment by Martin-Gonzalez90** [comment]
Hi there, thanks a lot for the fix. Just wanted to know that if setting the env `FASTLANE_USE_LEGACY_PRE_SIRP_AUTH=true` should be enough to use the previous system.

**Comment by cah-iswaria-sasi** [comment]
> Hi there, thanks a lot for the fix. Just wanted to know that if setting the env `FASTLANE_USE_LEGACY_PRE_SIRP_AUTH=true` should be enough to use the previous system.

Hey @Martin-Gonzalez90 can you brief where exactly this ENV needs to be set? i am also facing the same issue although appstore connect pwd is correct, its not connecting and account got locked and now Access is Forbidden

**Comment by Stas-Buzunko** [comment]
I did set it, and it didn't work but functioned without it, so try running without it first. 

Add a .env file to your Fastlane folder if you think you need it.

**Comment by Martin-Gonzalez90** [comment]
> > Hi there, thanks a lot for the fix. Just wanted to know that if setting the env `FASTLANE_USE_LEGACY_PRE_SIRP_AUTH=true` should be enough to use the previous system.
> 
> Hey @Martin-Gonzalez90 can you brief where exactly this ENV needs to be set? i am also facing the same issue although appstore connect pwd is correct, its not connecting and account got locked and now Access is Forbidden

I updated fastlane to latest version and set the env but still failed, but then suddenly started to work, so I don't know if this is a real fix or if the service was recovered.
I tried using a previous version of fastlane and also worked

**Comment by davidmdt21** [comment]
Hello and thanks for hard work   . i try your way and 503 error fixed . but i have new problem a , i got AppleID Session , but i see after some hours session will not work and i must get new session for this appleid ! whats the problem ? i mean every 4-5 hours session not work and i must get new session !

**Comment by smurf28** [comment]
> Hello and thanks for hard work . i try your way and 503 error fixed . but i have new problem a , i got AppleID Session , but i see after some hours session will not work and i must get new session for this appleid ! whats the problem ? i mean every 4-5 hours session not work and i must get new session !

Hello @davidmdt21 , I have read the latest Fastlane auth code and attempted to implement this auth using Golang Language. Currently, It's not working. Request the Api https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false, it still returns an error:`{
  "serviceErrors" : [ {
    "code" : "-20101",
    "message" : "Enter the email or phone number and password for your Apple Account.",
    "suppressDismissal" : false
  } ]
}` I would like to ask what the cause of this issue could be. I tried so many times

**Comment by sunslikes** [comment]
> > Hello and thanks for hard work . i try your way and 503 error fixed . but i have new problem a , i got AppleID Session , but i see after some hours session will not work and i must get new session for this appleid ! whats the problem ? i mean every 4-5 hours session not work and i must get new session !您好，感谢您的辛勤工作。我尝试了你的方法并修复了 503 错误。但我遇到了新问题，我获得了 AppleID 会话，但我看到几个小时后会话将无法工作，我必须为该 appleid 获得新会话！有什么问题吗？我的意思是每 4-5 小时的课程不起作用，我必须进行新的课程！
> 
> Hello @davidmdt21 , I have read the latest Fastlane auth code and attempted to implement this auth using Golang Language. Currently, It's not working. Request the Api https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false, it still returns an error:`{ "serviceErrors" : [ { "code" : "-20101", "message" : "Enter the email or phone number and password for your Apple Account.", "suppressDismissal" : false } ] }` I would like to ask what the cause of this issue could be. I tried so many times您好，我已经阅读了最新的 Fastlane 身份验证代码并尝试使用 Golang 语言实现此身份验证。目前，它不起作用。请求 Api https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false ，它仍然返回错误： `{ "serviceErrors" : [ { "code" : "-20101", "message" : "Enter the email or phone number and password for your Apple Account.", "suppressDismissal" : false } ] }` 我想请问一下这个问题的原因可能是什么。我尝试了很多次

I just had this problem, until I added all the code that needed to be filled with zeros.

**Comment by rickpasetto** [comment]
Just want to note: we use an Apple App Store API key instead of a Apple ID.  After updating to this version (`2.225.0`), our uploads started failing.  Is this expected?

```
Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

Downgrading to `2.223.1` fixed the problem.

**Comment by Mihai-github** [comment]
Other than updating the fastlane version what are the next steps for making this work with older approaches? Would be helpful to get some documentation update maybe please since for some of us may be hard to understand what we need exactly to do to make this work again.

**Comment by Martin-Gonzalez90** [comment]
After I run 
```bash
unset FASTLANE_PASSWORD
unset FASTLANE_APP_SPECIFIC_PASSWORD
unset FASTLANE_SESSION 
unset FASTLANE_USE_LEGACY_PRE_SIRP_AUTH
```

spaceauth started to work

**Comment by Mihai-github** [comment]
> After I run
> 
> ```shell
> unset FASTLANE_PASSWORD
> unset FASTLANE_APP_SPECIFIC_PASSWORD
> unset FASTLANE_SESSION 
> unset FASTLANE_USE_LEGACY_PRE_SIRP_AUTH
> ```
> 
> spaceauth started to work

Hey, thanks for the response ... for me I keep getting the same error and I don't know what to do anymore ... I've included in my Gemfile this 2 and installed them:

```
gem 'fastlane', '2.225.0'
gem 'fastlane-sirp', :git => "https://github.com/fastlane/fastlane-sirp"
```

I really don't know what I have to do, or what to set so the authentication works ... do you changed something else or?

**Comment by Martin-Gonzalez90** [comment]
> > After I run
> > ```shell
> > unset FASTLANE_PASSWORD
> > unset FASTLANE_APP_SPECIFIC_PASSWORD
> > unset FASTLANE_SESSION 
> > unset FASTLANE_USE_LEGACY_PRE_SIRP_AUTH
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > spaceauth started to work
> 
> Hey, thanks for the response ... for me I keep getting the same error and I don't know what to do anymore ... I've included in my Gemfile this 2 and installed them:
> 
> ```
> gem 'fastlane', '2.225.0'
> gem 'fastlane-sirp', :git => "https://github.com/fastlane/fastlane-sirp"
> ```
> 
> I really don't know what I have to do, or what to set so the authentication works ... do you changed something else or?

Nope, I'm using directly fastlane v2.225.0

**Comment by dplcz** [comment]
> > > Hello and thanks for hard work . i try your way and 503 error fixed . but i have new problem a , i got AppleID Session , but i see after some hours session will not work and i must get new session for this appleid ! whats the problem ? i mean every 4-5 hours session not work and i must get new session !您好，感谢您的辛勤工作。我尝试了你的方法并修复了 503 错误。但我遇到了新问题，我获得了 AppleID 会话，但我看到几个小时后会话将无法工作，我必须为该 appleid 获得新会话！有什么问题吗？我的意思是每 4-5 小时的课程不起作用，我必须进行新的课程！
> > 
> > 
> > Hello @davidmdt21 , I have read the latest Fastlane auth code and attempted to implement this auth using Golang Language. Currently, It's not working. Request the Api https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false, it still returns an error:`{ "serviceErrors" : [ { "code" : "-20101", "message" : "Enter the email or phone number and password for your Apple Account.", "suppressDismissal" : false } ] }` I would like to ask what the cause of this issue could be. I tried so many times您好，我已经阅读了最新的 Fastlane 身份验证代码并尝试使用 Golang 语言实现此身份验证。目前，它不起作用。请求 Api https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false ，它仍然返回错误： `{ "serviceErrors" : [ { "code" : "-20101", "message" : "Enter the email or phone number and password for your Apple Account.", "suppressDismissal" : false } ] }` 我想请问一下这个问题的原因可能是什么。我尝试了很多次
> 
> I just had this problem, until I added all the code that needed to be filled with zeros.

Could you tell me where zero-padding needs to be added? My current code has different responses when testing different accounts. Some can directly reach the two-factor authentication stage, while others consistently return a 401 response.
