### PR TITLE
[fastlane] load actions for tools

### LINKED ISSUE #14211: [!] undefined method `git_branch' for Fastlane::Actions:Module (NoMethodError)
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
I am running "fastlane scan --scheme "MyApp-DEV" --slack_url "https://hooks.slack.com/services..."

Removing my slack incoming webhook for security reasons.
I know my webhook is working well because I am using it with "xcov --slack_url".

Scan works well, but webhook fails to post anything with this error:

``` 
INFO [2019-02-07 13:49:13.05]: ▸ Test Succeeded

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `git_branch' for Fastlane::Actions:Module

URL: https://api.github.com/search/issues?q=undefined%20method%20%60git_branch%27%20for%20Fastlane%3A%3AActions%3AModule+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/slack.rb:227:in `generate_slack_attachments': [!] undefined method `git_branch' for Fastlane::Actions:Module (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/actions/slack.rb:40:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/slack_poster.rb:46:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/runner.rb:78:in `handle_results'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/runner.rb:22:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/manager.rb:18:in `work'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/commands_generator.rb:75:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/scan/lib/scan/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/fastlane/lib/fastlane/cli_tools_distributor.rb:105:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.116.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

I do have git_branch installed. See log below:

```
fastlane actions git_branch
[✔] 🚀 
[13:56:51]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
Loading documentation for git_branch:

+--------------------------------------------------------------------------------+
|                                   git_branch                                   |
+--------------------------------------------------------------------------------+
| Returns the name of the current git branch, possibly as managed by CI ENV vars |
|                                                                                |
| If no branch could be found, this action will return an empty string           |
|                                                                                |
| Created by KrauseFx                                                            |
+--------------------------------------------------------------------------------+

+-----+-------------+---------+---------+
|          git_branch Options           |
+-----+-------------+---------+---------+
| Key | Description | Env Var | Default |
+-----+-------------+---------+---------+
+-----+-------------+---------+---------+
* = default value is dependent on the user's system

More information can be found on https://docs.fastlane.tools/actions/git_branch
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.14.3                                                        |
| Ruby                        | 2.3.7                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.17.2 (Apple Git-113)                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.14.3 (18D42)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.6.4                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 10.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.116.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| CFPropertyList            | 2.3.6        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.6.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.9.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.62.0       |
| faraday                   | 0.15.4       |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.5        |
| gh_inspector              | 1.1.3        |
| json                      | 1.8.3.1      |
| mini_magick               | 4.5.1        |
| multi_json                | 1.13.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.6.0        |
| faraday_middleware        | 0.13.1       |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| google-cloud-env          | 1.0.5        |
| google-cloud-core         | 1.3.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| jwt                       | 2.1.0        |
| signet                    | 0.11.0       |
| memoist                   | 0.16.0       |
| os                        | 1.0.0        |
| googleauth                | 0.6.7        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.23.9       |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.16.0       |
| io-console                | 0.4.5        |
| libxml-ruby               | 2.9.0        |
| bundler                   | 2.0.1        |
| psych                     | 2.1.0.1      |
</details>

*generated on:* **2019-02-07**
</details>

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #14211

## Description
`scan` calls the `slack` action after a run which works fine when calling from a `Fastfile`. However, actions are not loaded when tools are called directly via CLI like... 
```sh
fastlane scan --scheme "MyApp-DEV" --slack_url "https://hooks.slack.com/services...
```

## Solution
We now will call `Fastlane.load_actions` before the tool's command generator is started.

### CODE REVIEW

File: fastlane/lib/fastlane/cli_tools_distributor.rb [hunk 1]
```diff
@@ -102,6 +102,12 @@ def take_off
             # When we launch this feature, this should never be the case
             abort("#{tool_name} can't be called via `fastlane #{tool_name}`, run '#{tool_name}' directly instead".red)
           end
+         
+          # Some of the tools use other actions so need to load all
+          # actions before we start the tool generator
+          # Example: scan uses slack
```
Comment (KrauseFx) [inline fastlane/lib/fastlane/cli_tools_distributor.rb]: Are there any other cases? Will this slow down things? Will this cause us to load things twice?

Comment (joshdholtz) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: Yeah, this same question cross my mind too. My initial solution was to actually test if the actions got loaded first before this line - https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slack.rb#L227. This "worked" but felt really weird to load an action even though we were already in an action.

The next higher up solution was require only the files I needed but the also felt weird and not very maintainable.

This approach of doing it at a higher level is a lot more maintainable and will work for other tools that do similar things (if there are any). I'm actually surprised that this wasn't caught sooner, TBH.

But the one-off action runs and `Fastfile` uses cases call this same method so it doesn't seem too bad to also call this for tools, IMO 🙃 Especially if it will fix current issues like this or prevent others in the future.
