### PR TITLE
[action] added custom api_url option to testfairy

### LINKED ISSUE #11057: testfairy - custom API url for upload
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

Hi all, 

i am just requesting new feature. custom upload URL (API server url) for testfairy action. Because some of us have private cloud instance, dont know if it's new feature but some companies does have it. 
Thank you

should be like, default one, original, and some custom with params[:api_url] or something like this. ofcourse as a optional parameter

### Environment

fastlane/fastlane/lib/fastlane/actions/testfairy.rb

now, there is hardcoded "https://upload.testfairy.com"

screenshot 2017-12-03 16 59 41
screenshot 2017-12-03 17 02 10

### PR DESCRIPTION
**Pull request by joshdholtz**
Fixes #11057

## Wut
- Adds a new `api_url` option for private secure cloud
- Defaults to `https://upload.testfairy.com`

## Proof
screen shot 2018-03-23 at 4 02 32 pm

screen shot 2018-03-23 at 4 14 17 pm

### CODE REVIEW

**Review by nafu — APPROVED** [review]
Looks good to me 👍

File: fastlane/lib/fastlane/actions/testfairy.rb [hunk 1]
```diff
@@ -5,11 +5,13 @@ module SharedValues
     end
 
     class TestfairyAction < Action
-      def self.upload_build(ipa, options)
+      def self.upload_build(api_url, ipa, options)
```
Comment (yairba) [inline fastlane/lib/fastlane/actions/testfairy.rb]: @joshdholtz would you mind changing the param name to "upload_url" instead of "api_url? We are going to use "api_url" for other purposes very soon. Thanks! 
(I'm Yair from the TestFairy team)

Comment (joshdholtz) [reply fastlane/lib/fastlane/actions/testfairy.rb]: Change has been made! Thanks for letting us know about this 🙌
