### PR TITLE
Accept `utf8` as valid locale + Automatically parse `locale` command

### LINKED ISSUE #13438: Fastlane does not recognize utf8
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`export LANG=en_US.UTF-8` works but `export LANG=en_US.utf8` does not which should work as well.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[✔] 🚀
[16:38:00]: fastlane detected a Gemfile in the current directory
[16:38:00]: however it seems like you don't use `bundle exec`
[16:38:00]: to launch fastlane faster, please use
[16:38:00]:
[16:38:00]: $ bundle exec fastlane capture_output
[16:38:00]:
[16:38:00]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:38:00]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-ionic | 0.0.4   | ionic  |
+-----------------------+---------+--------+

[!] Could not find 'capture_output'. Available lanes: ios deploy, android deploy
[16:38:00]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
</pre>
</details>

### Environment

<details>
  <pre>[✔] 🚀
[16:54:20]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
[16:54:20]: Generating fastlane environment output, this might take a few seconds...
cat: /etc/issue.net: No such file or directory
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value
                                              |
| --------------------------- | ---------------------------------------------------------------------------------------------------------------- |
| OS                          | Linux cti 4.18.8-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 15 20:34:48 UTC 2018 x86_64 GNU/Linux                       |
| Ruby                        | 2.5.1
                                              |
| Bundler?                    | true
                                              |
| Git                         | git version 2.19.0
                                              |
| Installation Source         | ~/.gem/bin/fastlane
                                              |
| Host                        | Linux cti 4.18.8-arch1-1-ARCH #1 SMP PREEMPT Sat Sep 15 20:34:48 UTC 2018 x86_64 GNU/Linux (4.18.8-arch1-1-ARCH) |
| Ruby Lib Dir                | /usr/lib
                                              |
| OpenSSL Version             | OpenSSL 1.1.0h  27 Mar 2018
                                              |
| Is contained                | false
                                              |
| Is homebrew                 | false
                                              |
| Is installed via Fabric.app | false
                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
platform :ios do
  desc "Deploy ios app on the appstore"

  lane :deploy do
    match(type: "appstore")
    ionic(platform: 'ios')
    deliver(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :deploy do
    ionic(
      platform: 'android',
      keystore_path: './file.keystore',
      keystore_alias: 'alias',
      keystore_password: 'password'
    )
    supply(apk: './platforms/android/app/build/outputs/apk/release/app-release.apk')
  end
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.105.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-ionic | 0.0.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.16.5       |
| CFPropertyList            | 3.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| atomos                    | 0.1.3        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.5      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20180417 |
| dotenv                    | 2.5.0        |
| emoji_regex               | 0.1.1        |
| excon                     | 0.62.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.15.3       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.4        |
| gh_inspector              | 1.1.3        |
| jwt                       | 2.1.0        |
| memoist                   | 0.16.0       |
| multi_json                | 1.13.1       |
| os                        | 1.0.0        |
| signet                    | 0.10.0       |
| googleauth                | 0.6.6        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2018.0812  |
| mime-types                | 3.2.2        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| google-api-client         | 0.23.9       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.2        |
| security                  | 0.1.3        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.5        |
| slack-notifier            | 2.3.2        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.4.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.5        |
| tty-cursor                | 0.6.0        |
| tty-spinner               | 0.8.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.6.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| xcpretty-travis-formatter | 1.0.0        |
| fastlane-plugin-ionic     | 0.0.4        |
</details>

*generated on:* **2018-09-26**
</details>
[16:54:21]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[16:54:21]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
[16:54:21]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
</pre>
</details>

### PR DESCRIPTION
**Pull request by pickfire**
fix #13438

### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [ ] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context

Locale is handled manually by checking environment variable, should use `locale charmap` instead which automatically maps `utf8` to `UTF-8`.

### Description

Check if output of `locale charmap` matches `UTF-8`.

### CODE REVIEW

**Review by minuscorp — APPROVED** [review]
LGTM 🎉

File: fastlane/lib/fastlane/cli_tools_distributor.rb [hunk 1]
```diff
@@ -45,7 +45,7 @@ def take_off
           print_bundle_exec_warning(is_slow: (Time.now - before_import_time > 3))
         end
 
-        unless (ENV['LANG'] || "").end_with?("UTF-8") || (ENV['LC_ALL'] || "").end_with?("UTF-8")
+        unless `locale chapmap` == "UTF-8"
```
[the remark this answers is not in the document]
Comment (joshdholtz) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: This does not work on macOS and I don't think this will work on Windows 😔 
```sh
➜  fastlane git:(pickfire-patch-1) locale chapmap
unknown keyword chapmap
```
which results in
```sh
➜  test-ios fl hey
[✔] 🚀
unknown keyword chapmap
[07:00:10]: WARNING: fastlane requires your locale to be set to UTF-8. To learn more go to https://docs.fastlane.tools/getting-started/ios/setup/#set-up-environment-variables
```

The "less elegant" but more platform agnostic approach would be to add separate check for `en_US.utf8` if we are trying to fix https://github.com/fastlane/fastlane/issues/13438

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Issue with macOS and Windows 😬

**Comment by pickfire** [comment]
@joshdholtz Sorry, there was a type `s/chapmap/charmap/`. Nice findings.

File: fastlane/lib/fastlane/cli_tools_distributor.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (minuscorp) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: why was it working on my macOS 🤔

**Review by janpio — CHANGES_REQUESTED** [review]
Doesn't work on Windows:

Powershell:
```
PS C:\Projects> locale charmap
locale : The term 'locale' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ locale charmap
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (locale:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```
cmd.exe:
```
C:\Users\Jan>locale charmap
'locale' is not recognized as an internal or external command,
operable program or batch file.
```

(Does work in git bash etc. at least - but we don't require those)

**Comment by janpio** [comment]
That the tests pass here, shows that there is one or more tests missing that check for this error message by the way ;)

Maybe this can be rewritten so it uses `locale charmap` where available and the old logic where not?

**Comment by joshdholtz** [comment]
I think we _could_ add some logic here to check the OS and and check if the `locale` command exists but I _thhiiinnnkkkk_ it might be more straight forward, easier to maintain, and easier to test if we just add the same kind of hardcoded check for `en_US.utf8`

**Comment by janpio** [comment]
Especially as the current version would add a `which ...` call for each execution of fastlane :/ We don't want to do that.

**Comment by pickfire** [comment]
@joshdholtz What about some other cases like `UTF8` or some weird cases which should not work. I think it's better to leave it for `locale` to handle.

@janpio Any alternatives? I think if we need to use environment variables, we need to take a look at how `locale` was implemented.

By the way, why do we need to check the `locale`? What are the implications if the locale is not `UTF-8`?

**Comment by janpio** [comment]
> @janpio Any alternatives? I think if we need to use environment variables, we need to take a look at how locale was implemented.

When I suggested that, I thought about trying the `locale` command and handling an eventual error by looking at the ENV vars. That would get rid of the additional `which`, but of course not the actual `locale ...` call itself.

File: fastlane/lib/fastlane/cli_tools_distributor.rb [hunk 2]
```diff
@@ -45,7 +45,8 @@ def take_off
           print_bundle_exec_warning(is_slow: (Time.now - before_import_time > 3))
         end
 
-        unless (ENV['LANG'] || "").end_with?("UTF-8") || (ENV['LC_ALL'] || "").end_with?("UTF-8")
+        # Try to check UTF-8 with `locale`, fallback to environment variables
+        unless (ENV['LANG'] || "").end_with?("UTF-8") || (ENV['LANG'] || "").end_with?("utf8") || (ENV['LC_ALL'] || "").end_with?("UTF-8") || (ENV['LC_ALL'] || "").end_with?("utf8") || (FastlaneCore::CommandExecutor.which('locale') && `locale charmap` == "UTF-8")
```
Comment (janpio) [inline fastlane/lib/fastlane/cli_tools_distributor.rb]: rubocop suggests:
```suggestion
        unless (ENV['LANG'] || "").end_with?("UTF-8", "utf8") || (ENV['LC_ALL'] || "").end_with?("UTF-8", "utf8") || (FastlaneCore::CommandExecutor.which('locale') && `locale charmap` == "UTF-8")
```

**Comment by pickfire** [comment]
@janpio Nice, I didn't know I can do that in ruby.

**Comment by janpio** [comment]
Me neither, rubocop told me ;)

Some stuff left:

```
[02:05:51]: $ bundle exec rubocop -D
[02:05:52]: ▸ Inspecting 1032 files
[02:07:26]: ▸ ...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................C............................................................................................................................................................................................................................................................................................................................................................................................................................................................
[02:07:26]: ▸ Offenses:
[02:07:26]: ▸ fastlane/lib/fastlane/cli_tools_distributor.rb:19:7: C: Metrics/PerceivedComplexity: Perceived complexity for take_off is too high. [20/18]
[02:07:26]: ▸ def take_off
[02:07:26]: ▸ ^^^
[02:07:26]: ▸ 1032 files inspected, 1 offense detected
```

I am not too sure what the best way to fix this would be. @joshdholtz ?

**Comment by pickfire** [comment]
@janpio I tried to reduce the cyclomatic complexity by splitting it into another function. Thanks for reminding me of the failed lint.

@joshdholtz Feel free to give any suggestion? :smile:

**Review by janpio — APPROVED** [review]
Wow, that extracting even worked. Didn't expect that.

Code looks good to me now I think.

File: fastlane/lib/fastlane/cli_tools_distributor.rb [hunk 3]
```diff
@@ -16,6 +16,10 @@ def running_init_command?
         ARGV.include?("init")
       end
 
+      def utf8_locale?
+        (ENV['LANG'] || "").end_with?("UTF-8", "utf8") || (ENV['LC_ALL'] || "").end_with?("UTF-8", "utf8") || (FastlaneCore::CommandExecutor.which('locale') && `locale charmap` == "UTF-8")
```
Comment (joshdholtz) [inline fastlane/lib/fastlane/cli_tools_distributor.rb]:
```suggestion
        (ENV['LANG'] || "").end_with?("UTF-8", "utf8") || (ENV['LC_ALL'] || "").end_with?("UTF-8", "utf8") || (FastlaneCore::CommandExecutor.which('locale') && `locale charmap`.strip == "UTF-8")
```

`locale charmap` on macos (at least on my machine) returns `"UTF-8\n"` so I think we need to a `.strip` to this just for safety 🤔

**Review by joshdholtz — DISMISSED** [review]
One small suggestion! Need to strip the output of `locale charmap`

File: fastlane/lib/fastlane/cli_tools_distributor.rb (hunk 3 above)
Comment (pickfire) [reply fastlane/lib/fastlane/cli_tools_distributor.rb]: Thanks a lot for the suggestion.

**Comment by janpio** [comment]
This should be good to merge now, what do you think @joshdholtz?

**Review by janpio — APPROVED** [review]
The first two conditions in `utf8_locale?` correspond to what was there before, but with `utf8` added as a valid value. The third condition might be a bit wonky, but in theory should work as well. As it is only triggered if 1 and 2 fail, which they shouldn't, I think this is acceptable.

**Comment by janpio** [comment]
Can you take another look before merging @joshdholtz and @minuscorp please? Thanks.
