### PR TITLE
[match] skip committing changes when nuking if the repo is already empty

### LINKED ISSUE #17451: match nuke throws error "Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call"
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

I'm migrating from `cert` and `sigh` to `match`, and when I ran `bundle exec fastlane match nuke development`, the error
```
Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
```
was thrown.

##### Command executed

`bundle exec fastlane match nuke development`

##### Complete output when running fastlane, including the stack trace and command used

`--capture_output` didn't work.

<details>
<pre>
[14:28:54]: Successfully deleted certificate
[14:28:54]: 🔒  Successfully encrypted certificates repo

[!] Neither `files_to_commit` nor `files_to_delete` were provided to the `save_changes!` method call
</pre>
</details>

### Environment

<details>
<pre>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.15.7                                        |
| Ruby                        | 2.6.5                                          |
| Bundler?                    | true                                           |
| Git                         | git version 2.24.3 (Apple Git-128)             |
| Installation Source         | ~/.gems/bin/fastlane                           |
| Host                        | Mac OS X 10.15.7 (19H2)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.6.5/lib                    |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode-12.app/Contents/Developer/ |
| Xcode Version               | 12.0                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
<redacted>
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
<redacted>
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.163.0 | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status  |
| ------------------------------- | ------- | -------------- |
| fastlane-plugin-aws_s3          | 1.8.0   | 💥 Check failed |
| fastlane-plugin-icon_versioning | 1.3.1   | ✅ Up-To-Date   |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| did_you_mean                    | 1.3.0        |
| bundler                         | 2.1.4        |
| rake                            | 13.0.1       |
| CFPropertyList                  | 3.0.2        |
| concurrent-ruby                 | 1.1.6        |
| i18n                            | 0.9.5        |
| minitest                        | 5.14.1       |
| thread_safe                     | 0.3.6        |
| tzinfo                          | 1.2.7        |
| activesupport                   | 4.2.11.3     |
| public_suffix                   | 4.0.6        |
| addressable                     | 2.7.0        |
| httpclient                      | 2.8.3        |
| json                            | 2.3.1        |
| algoliasearch                   | 1.27.3       |
| rubyzip                         | 2.3.0        |
| apktools                        | 0.7.4        |
| ast                             | 2.4.1        |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.1.0        |
| aws-partitions                  | 1.382.0      |
| aws-sigv4                       | 1.2.2        |
| jmespath                        | 1.4.0        |
| aws-sdk-core                    | 3.109.1      |
| aws-sdk-kms                     | 1.39.0       |
| aws-sdk-s3                      | 1.83.0       |
| babosa                          | 1.0.4        |
| claide                          | 1.0.3        |
| fuzzy_match                     | 2.0.4        |
| nap                             | 1.1.0        |
| netrc                           | 0.11.0       |
| ffi                             | 1.13.1       |
| ethon                           | 0.12.0       |
| typhoeus                        | 1.4.0        |
| cocoapods-core                  | 1.9.3        |
| cocoapods-deintegrate           | 1.0.4        |
| cocoapods-downloader            | 1.4.0        |
| cocoapods-plugins               | 1.0.0        |
| cocoapods-search                | 1.0.0        |
| cocoapods-stats                 | 1.1.0        |
| cocoapods-trunk                 | 1.5.0        |
| cocoapods-try                   | 1.2.0        |
| colored2                        | 3.1.2        |
| escape                          | 0.0.4        |
| fourflusher                     | 2.3.1        |
| gh_inspector                    | 1.1.3        |
| molinillo                       | 0.6.6        |
| ruby-macho                      | 1.4.0        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.19.0       |
| cocoapods                       | 1.9.3        |
| colored                         | 1.2          |
| highline                        | 1.7.10       |
| commander-fastlane              | 4.4.6        |
| declarative                     | 0.0.20       |
| declarative-option              | 0.1.0        |
| digest-crc                      | 0.6.1        |
| unf_ext                         | 0.0.7.7      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| dotenv                          | 2.7.6        |
| emoji_regex                     | 3.0.0        |
| excon                           | 0.76.0       |
| multipart-post                  | 2.0.0        |
| faraday                         | 1.0.1        |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.0.0        |
| fastimage                       | 2.2.0        |
| jwt                             | 2.2.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.1        |
| signet                          | 0.14.0       |
| googleauth                      | 0.14.0       |
| mini_mime                       | 1.0.2        |
| uber                            | 0.1.0        |
| representable                   | 3.0.4        |
| retriable                       | 3.1.2        |
| google-api-client               | 0.38.0       |
| google-cloud-env                | 1.4.0        |
| google-cloud-errors             | 1.0.1        |
| google-cloud-core               | 1.5.0        |
| google-cloud-storage            | 1.29.1       |
| mini_magick                     | 4.10.1       |
| plist                           | 3.5.0        |
| security                        | 0.1.3        |
| naturally                       | 2.2.0        |
| simctl                          | 1.6.8        |
| slack-notifier                  | 2.3.2        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.7.0        |
| terminal-table                  | 1.8.0        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| xcpretty-travis-formatter       | 1.0.0        |
| mime-types-data                 | 3.2020.0512  |
| mime-types                      | 3.3.1        |
| fastlane-plugin-aws_s3          | 1.8.0        |
| fastlane-plugin-icon_versioning | 1.3.1        |
| parallel                        | 1.19.2       |
| parser                          | 2.7.1.4      |
| rainbow                         | 3.0.0        |
| regexp_parser                   | 1.7.1        |
| rexml                           | 3.2.4        |
| rubocop-ast                     | 0.2.0        |
| ruby-progressbar                | 1.10.1       |
| rubocop                         | 0.88.0       |
| xcode-install                   | 2.6.6        |
</details>

*generated on:* **2020-10-16**
</details>
</pre>
</details>

### PR DESCRIPTION
**Pull request by rogerluan**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Resolves #17451

### Description
Seems like when the repository is already empty, performing `match nuke` would throw an undesired error because there were not files to delete. This PR fixes that by skipping the "save_changes" when there's nothing to be saved.

### Testing Steps

To test this branch, modify your Gemfile as:

```ruby
gem "fastlane", :git => "https://github.com/fastlane/fastlane.git", :branch => "rogerluan-match-nuke-commit-changes-if-needed"
```

And run `fastlane match nuke development` for instance.

### CODE REVIEW

File: match/lib/match/nuke.rb [hunk 1]
```diff
@@ -252,11 +252,13 @@ def nuke_it_now!
...
-      self.storage.save_changes!(files_to_commit: [],
-                                 files_to_delete: files_to_delete,
-                                 custom_message: message)
+      if files_to_delete.count > 0
+        # Now we need to commit and push all this too, if needed
+        message = ["[fastlane]", "Nuked", "files", "for", type.to_s].join(" ")
+        self.storage.save_changes!(files_to_commit: [],
+                                   files_to_delete: files_to_delete,
+                                   custom_message: message)
+      end
```
Comment (joshdholtz) [inline match/lib/match/nuke.rb:261]: Thoughts on doing a `UI.important` or `UI.user_error!` if count is 0? Feel like this needs to probably be communicated to the user 😇

**Review by joshdholtz — CHANGES_REQUESTED** [review]
Good change good change! Just one quick thought on making things a bit more transparent to the user 😊

File: match/lib/match/nuke.rb (hunk 1 above)
Comment (rogerluan) [reply match/lib/match/nuke.rb:261]: I don't feel like this is **that** _important_ (and definitely not an error), because `match nuke` should be idempotent and error'ing is exactly what led to the user's complaint. 

Although I do agree we could communicate - there's never too much communication 😁 
I'm on the fence between `important` and `message`. I'll go with `message`, feel free to change if you feel the priority should be changed 🙈

**Review by joshdholtz — APPROVED** [review]
Perfect! Thanks for making that change 😊 Over communicating leads to less issues being reported 😉 Appreciate the contribution ❤️
