### PR TITLE
[fastlane-core] recommends to retry uploading when AltoolTransporterExecutor crashes

### LINKED ISSUE #21535: [pilot] App Upload via altool Can Sometimes Exit Early With No Exit Code Or Stdout
<!-- Thanks for helping fastlane! Before you submit your issue, please make sure you followed our checklist and check the appropriate boxes by putting an x in the [ ]: [x] -->

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
<!-- Please include what's happening, expected behavior, and any relevant code samples -->
I've only noticed this occurring since upgrading to Xcode 15 - it would appear that when `pilot` runs `altool` to upload an app to Testflight, it's possible for `altool` to exit prematurely, without an exit code or stdout to even begin to diagnose what might have gone wrong.

```
/Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:246:in `execute': \e[31m[!] undefined method `zero?' for nil:NilClass (NoMethodError)

      @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
```      

##### Command executed
<!-- The command you executed on the command line that resulted in an error -->
`bundle exec fastlane publish_testflight` - see fastlane env output, this is the action in which I wrap the call to `pilot`.

##### Complete output when running fastlane, including the stack trace and command used
<!-- 
You can use `--capture_output` as the last command line argument for many commands to get that collected for you. Otherwise, please do it manually.
Caution: The output of `--capture_output` could contain sensitive data such as application ids, certificate ids, or email addresses. Please make sure you double check the output and replace anything sensitive you don't wish to submit in the issue 
-->

<details>
  <pre>[✔] 🚀 
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                                                                            Used plugins                                                                                                                                                             |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Plugin                                    | Version | Action                                                                                                                                                                                                                                                                        |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| fastlane-plugin-doximity_xcode_installer  | 0.2.0   | install_and_select_xcode, install_runtimes, select_supported_runtime                                                                                                                                                                                                          |
| fastlane-plugin-firebase_app_distribution | 0.7.3   | firebase_app_distribution, firebase_app_distribution_add_testers, firebase_app_distribution_create_group, firebase_app_distribution_delete_group, firebase_app_distribution_get_latest_release, firebase_app_distribution_get_udids, firebase_app_distribution_remove_testers |
| fastlane-plugin-bugsnag                   | 2.3.0   | find_info_plist_path, send_build_to_bugsnag, upload_symbols_to_bugsnag                                                                                                                                                                                                        |
+-------------------------------------------+---------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: ----------------------------------------
[16:32:46]: --- Step: Verifying fastlane version ---
[16:32:46]: ----------------------------------------
[16:32:46]: Your fastlane version 2.216.0 matches the minimum requirement of 2.121.1  ✅
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: ------------------------------
[16:32:46]: --- Step: default_platform ---
[16:32:46]: ------------------------------
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: --------------------
[16:32:46]: --- Step: whoami ---
[16:32:46]: --------------------
[16:32:46]: $ whoami
[16:32:46]: ▸ ec2-user
[16:32:46]: Driving the lane 'ios publish_testflight' 🚀
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: -------------------------------------------------------------
[16:32:46]: --- Step: Switch to ios set_appstore_connect_api_key lane ---
[16:32:46]: -------------------------------------------------------------
[16:32:46]: Cruising over to lane 'ios set_appstore_connect_api_key' 🚖
[16:32:46]: Cruising back to lane 'ios publish_testflight' 🚘
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: -----------------------------------------------------------------
[16:32:46]: --- Step: Switch to ios generate_release_build_changelog lane ---
[16:32:46]: -----------------------------------------------------------------
[16:32:46]: Cruising over to lane 'ios generate_release_build_changelog' 🚖
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: ----------------------------------------
[16:32:46]: --- Step: changelog_from_git_commits ---
[16:32:46]: ----------------------------------------
[16:32:46]: Collecting the last 1 Git commits

REDACTED

tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: ------------------------
[16:32:46]: --- Step: git_branch ---
[16:32:46]: ------------------------
[16:32:46]: Cruising back to lane 'ios publish_testflight' 🚘
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:32:46]: -------------------
[16:32:46]: --- Step: pilot ---
[16:32:46]: -------------------
[16:32:46]: Creating authorization token for App Store Connect API
[16:32:46]: Ready to upload new build to TestFlight (App: REDACTED)...
[16:32:48]: Going to upload updated app to App Store Connect
[16:32:48]: This might take a few minutes. Please don't interrupt the script.
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[16:35:47]: -------------------
[16:35:47]: --- Step: is_ci ---
[16:35:47]: -------------------
+----------------------------------------------------------------+
|                          Lane Context                          |
+------------------+---------------------------------------------+
| DEFAULT_PLATFORM | ios                                         |
| PLATFORM_NAME    | ios                                         |
| LANE_NAME        | ios publish_testflight                      |
| FL_CHANGELOG     | REDACTED |
+------------------+---------------------------------------------+

+--------------------------------------------------------------------------+
|                             fastlane summary                             |
+------+-----------------------------------------------------+-------------+
| Step | Action                                              | Time (in s) |
+------+-----------------------------------------------------+-------------+
| 1    | Verifying fastlane version                          | 0           |
| 2    | default_platform                                    | 0           |
| 3    | whoami                                              | 0           |
| 4    | Switch to ios set_appstore_connect_api_key lane     | 0           |
| 5    | Switch to ios generate_release_build_changelog lane | 0           |
| 6    | changelog_from_git_commits                          | 0           |
| 7    | git_branch                                          | 0           |
| 💥   | pilot                                               | 181         |
| 9    | is_ci                                               | 0           |
+------+-----------------------------------------------------+-------------+

[16:35:47]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/ec2-user/project/vendor/bundle/ruby/3.1.0/bin/fastlane)
/Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:246:in `execute': \e[31m[!] undefined method `zero?' for nil:NilClass (NoMethodError)

      @errors << "The call to the altool completed with a non-zero exit status: #{exit_status}. This indicates a failure." unless exit_status.zero?
                                                                                                                                             ^^^^^^\e[0m
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/itunes_transporter.rb:791:in `upload'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/pilot/lib/pilot/build_manager.rb:50:in `upload'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:34:in `run'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
        from Fastfile:281:in `block (2 levels) in parsing_binding'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `load'
        from /Users/ec2-user/project/vendor/bundle/ruby/3.1.0/bin/fastlane:25:in `<top (required)>'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `load'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli/exec.rb:23:in `run'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli.rb:492:in `exec'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli.rb:34:in `dispatch'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/cli.rb:28:in `start'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/exe/bundle:37:in `block in <top (required)>'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /Users/ec2-user/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/bundler-2.4.19/exe/bundle:29:in `<top (required)>'
        from /Users/ec2-user/.rbenv/versions/3.1.4/bin/bundle:25:in `load'
        from /Users/ec2-user/.rbenv/versions/3.1.4/bin/bundle:25:in `<main>'

Exited with code exit status 1</pre>
</details>

### Environment

<!-- 
Please run `fastlane env` and copy the output below. This will help us help you.
If you used the `--capture_output` option, please remove this block as it is already included there. 
-->

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                              |
| --------------------------- | -------------------------------------------------- |
| OS                          | 13.5.2                                             |
| Ruby                        | 3.1.4                                              |
| Bundler?                    | true                                               |
| Git                         | git version 2.42.0                                 |
| Installation Source         | ~/project/vendor/bundle/ruby/3.1.0/bin/fastlane    |
| Host                        | macOS 13.5.2 (22G91)                               |
| Ruby Lib Dir                | ~/.rbenv/versions/3.1.4/lib                        |
| OpenSSL Version             | OpenSSL 3.1.2 1 Aug 2023                           |
| Is contained                | false                                              |
| Is homebrew                 | false                                              |
| Is installed via Fabric.app | false                                              |
| Xcode Path                  | /Applications/Xcode-15.0.0.app/Contents/Developer/ |
| Xcode Version               | 15.0                                               |
| Swift Version               | 5.9                                                |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.121.1"

default_platform :ios

[REDACTED]

platform :ios do
  [REDACTED]

  desc "Submit a new Release Build to Apple TestFlight"
  desc "- Upload and distribute to Apple iTunes Connect TestFlight for one-click submission to AppStore"
  lane :publish_testflight do
    set_appstore_connect_api_key

    pilot(
      api_key_path: "/tmp/appstore_connect/doximity_appstore_connect.json",
      skip_submission: false,
      distribute_external: false,
      skip_waiting_for_build_processing: true,
      apple_id: ENV.fetch("FASTLANE_APPLE_ID"),
      ipa: "build/REDACTED.ipa",
      reject_build_waiting_for_review: true,
      changelog: generate_release_build_changelog
    )
  end

  [REDACTED]
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app

team_id "REDACTED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.216.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                    | Version | Update-Status  |
| ----------------------------------------- | ------- | -------------- |
| fastlane-plugin-doximity_xcode_installer  | 0.2.0   | 💥 Check failed |
| fastlane-plugin-firebase_app_distribution | 0.7.3   | ✅ Up-To-Date   |
| fastlane-plugin-bugsnag                   | 2.3.0   | ✅ Up-To-Date   |


<details><summary><b>Loaded gems</b></summary>

| Gem                                       | Version      |
| ----------------------------------------- | ------------ |
| error_highlight                           | 0.3.0        |
| did_you_mean                              | 1.6.1        |
| bundler                                   | 2.4.19       |
| pathname                                  | 0.2.0        |
| rake                                      | 13.0.6       |
| rexml                                     | 3.2.6        |
| CFPropertyList                            | 3.0.6        |
| public_suffix                             | 5.0.3        |
| addressable                               | 2.8.5        |
| artifactory                               | 3.0.15       |
| atomos                                    | 0.1.3        |
| aws-eventstream                           | 1.2.0        |
| aws-partitions                            | 1.828.0      |
| aws-sigv4                                 | 1.6.0        |
| jmespath                                  | 1.6.2        |
| aws-sdk-core                              | 3.183.1      |
| aws-sdk-kms                               | 1.71.0       |
| aws-sdk-s3                                | 1.136.0      |
| babosa                                    | 1.0.4        |
| claide                                    | 1.1.0        |
| climate_control                           | 0.2.0        |
| colored                                   | 1.2          |
| colored2                                  | 3.1.2        |
| highline                                  | 2.0.3        |
| commander                                 | 4.6.0        |
| declarative                               | 0.0.20       |
| digest-crc                                | 0.6.5        |
| unf_ext                                   | 0.0.8.2      |
| unf                                       | 0.1.4        |
| domain_name                               | 0.5.20190701 |
| dotenv                                    | 2.8.1        |
| emoji_regex                               | 3.2.3        |
| excon                                     | 0.103.0      |
| faraday-em_http                           | 1.0.0        |
| faraday-em_synchrony                      | 1.0.0        |
| faraday-excon                             | 1.1.0        |
| faraday-httpclient                        | 1.0.1        |
| multipart-post                            | 2.3.0        |
| faraday-multipart                         | 1.0.4        |
| faraday-net_http                          | 1.0.1        |
| faraday-net_http_persistent               | 1.2.0        |
| faraday-patron                            | 1.0.0        |
| faraday-rack                              | 1.0.0        |
| faraday-retry                             | 1.0.3        |
| ruby2_keywords                            | 0.0.5        |
| faraday                                   | 1.10.3       |
| http-cookie                               | 1.0.5        |
| faraday-cookie_jar                        | 0.0.7        |
| faraday_middleware                        | 1.2.0        |
| fastimage                                 | 2.2.7        |
| gh_inspector                              | 1.1.3        |
| jwt                                       | 2.7.1        |
| multi_json                                | 1.15.0       |
| os                                        | 1.1.4        |
| signet                                    | 0.18.0       |
| googleauth                                | 1.8.1        |
| httpclient                                | 2.8.3        |
| mini_mime                                 | 1.1.5        |
| trailblazer-option                        | 0.1.2        |
| uber                                      | 0.1.0        |
| representable                             | 3.2.0        |
| retriable                                 | 3.1.2        |
| webrick                                   | 1.8.1        |
| google-apis-core                          | 0.11.1       |
| google-apis-androidpublisher_v3           | 0.50.0       |
| google-apis-playcustomapp_v1              | 0.13.0       |
| google-apis-iamcredentials_v1             | 0.17.0       |
| google-apis-storage_v1                    | 0.19.0       |
| google-cloud-env                          | 1.6.0        |
| google-cloud-errors                       | 1.3.1        |
| google-cloud-core                         | 1.6.0        |
| google-cloud-storage                      | 1.44.0       |
| json                                      | 2.6.3        |
| mini_magick                               | 4.12.0       |
| naturally                                 | 2.2.1        |
| optparse                                  | 0.1.1        |
| plist                                     | 3.7.0        |
| rubyzip                                   | 2.3.2        |
| security                                  | 0.1.3        |
| simctl                                    | 1.6.10       |
| terminal-notifier                         | 2.0.0        |
| unicode-display_width                     | 2.4.2        |
| terminal-table                            | 3.0.2        |
| tty-screen                                | 0.8.1        |
| tty-cursor                                | 0.7.1        |
| tty-spinner                               | 0.9.3        |
| word_wrap                                 | 1.0.0        |
| nanaimo                                   | 0.3.0        |
| xcodeproj                                 | 1.23.0       |
| rouge                                     | 2.0.7        |
| xcpretty                                  | 0.3.0        |
| xcpretty-travis-formatter                 | 1.0.1        |
| rchardet                                  | 1.8.0        |
| git                                       | 1.18.0       |
| xml-simple                                | 1.1.9        |
| fastlane-plugin-bugsnag                   | 2.3.0        |
| options                                   | 2.3.2        |
| progress_bar                              | 1.3.3        |
| terrapin                                  | 0.6.0        |
| fastlane-plugin-doximity_xcode_installer  | 0.2.0        |
| google-apis-firebaseappdistribution_v1    | 0.3.0        |
| fastlane-plugin-firebase_app_distribution | 0.7.3        |
| table_print                               | 1.5.7        |
</details>


*generated on:* **2023-09-26**
</details></pre>
</details>

### PR DESCRIPTION
**Pull request by TheMetalCode**
### Checklist

- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.
- [x] I've added or updated relevant unit tests.

### Motivation and Context

Resolves #21535

After recently noticing some of my `pilot` runs fail due to no exit code being returned when running `altool` via `FastlanePty.spawn`, I investigated and eventually realized the error handling in `AltoolTransporterExecutor#execute` will work as designed if we simply force the return of some kind of exit code when this mysterious issue with `altool` occurs.

I do not know why `altool` is failing in this manner and hence this change isn't exactly a solution. What it _does_ do though is provide a better error output when this condition does occur, such that it's much easier for a fastlane user to detect this precise failure and automatically retry the upload (which in my experience over the last few days always works successfully). With this change, paired with setting `DELIVER_ALTOOL_ADDITIONAL_UPLOAD_PARAMETERS="--verbose"` in the environment so `altool` is guaranteed to have some kind of stdout, the rather cryptic error output in #21535 turns into something much more informative:

<details>
  <pre> [23:00:55]: -------------------
[23:00:55]: --- Step: pilot ---
[23:00:55]: -------------------
[23:00:55]: Creating authorization token for App Store Connect API
[23:00:55]: Ready to upload new build to TestFlight (App: REDACTED)...
[23:00:57]: Going to upload updated app to App Store Connect
[23:00:57]: This might take a few minutes. Please don't interrupt the script.
[23:02:26]: [altool] 2023-09-26 23:02:26.633 DEBUG: [ContentDelivery.Uploader] There are 15 parts remaining to upload.

[23:02:26]: [altool] 2023-09-26 23:02:26.634 DEBUG: [ContentDelivery.Uploader] PROGRESS - PART 24 (5242880) - '38b61411-f580-4360-84be-927836472cb9.ipa' 100.00% (5242880/5242880)

[23:02:26]: [altool] 2023-09-26 23:02:26.636 DEBUG: [ContentDelivery.Uploader] PROGRESS - PART 25 (5242880) - '38b61411-f580-4360-84be-927836472cb9.ipa' 100.00% (5242880/5242880)

[23:02:26]: [altool] 2023-09-26 23:02:26.650 DEBUG: [ContentDelivery.Uploader] Wrote part 27 to a temp file '/private/var/folders/6j/z_jm_fbd1rb44rx_9513tbk40000gn/T/com.apple.cds.vbtx/com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8/Part-27.tmp'.

[23:02:26]: [altool] 2023-09-26 23:02:26.661 DEBUG: [ContentDelivery.Uploader] Adding upload task 32 for part 27.

[23:02:26]: [altool] 2023-09-26 23:02:26.662 DEBUG: [ContentDelivery.Uploader] Saving uploader state (CDUploaderStateCreateAssetChunksForUpload) for identifier 'com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8'.

[23:02:26]: [altool] 2023-09-26 23:02:26.679 DEBUG: [ContentDelivery.Uploader] Uploading part 20 COMPLETE.

[23:02:26]: [altool] 2023-09-26 23:02:26.679 DEBUG: [ContentDelivery.Uploader] COMPLETED - PART 20 - 38b61411-f580-4360-84be-927836472cb9.ipa - eTag: "AA281F37DC813E9F220C7616FC6080F7"

[23:02:26]: [altool] 2023-09-26 23:02:26.680 DEBUG: [ContentDelivery.Uploader] Wrote part 28 to a temp file '/private/var/folders/6j/z_jm_fbd1rb44rx_9513tbk40000gn/T/com.apple.cds.vbtx/com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8/Part-28.tmp'.

[23:02:26]: [altool] 2023-09-26 23:02:26.681 DEBUG: [ContentDelivery.Uploader] Removed temporary part file '/private/var/folders/6j/z_jm_fbd1rb44rx_9513tbk40000gn/T/com.apple.cds.vbtx/com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8/Part-20.tmp'.

[23:02:26]: [altool] 2023-09-26 23:02:26.682 DEBUG: [ContentDelivery.Uploader] Saving uploader state (CDUploaderStateCreateAssetChunksForUpload) for identifier 'com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8'.

[23:02:26]: [altool] 2023-09-26 23:02:26.686 DEBUG: [ContentDelivery.Uploader] There are 14 parts remaining to upload.

[23:02:26]: [altool] 2023-09-26 23:02:26.687 DEBUG: [ContentDelivery.Uploader] Uploading part 21 COMPLETE.

[23:02:26]: [altool] 2023-09-26 23:02:26.687 DEBUG: [ContentDelivery.Uploader] COMPLETED - PART 21 - 38b61411-f580-4360-84be-927836472cb9.ipa - eTag: "1F12B3E1BFAC15C3ACDCCF72A5B89EFE"

[23:02:26]: [altool] 2023-09-26 23:02:26.689 DEBUG: [ContentDelivery.Uploader] Removed temporary part file '/private/var/folders/6j/z_jm_fbd1rb44rx_9513tbk40000gn/T/com.apple.cds.vbtx/com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8/Part-21.tmp'.

[23:02:26]: [altool] 2023-09-26 23:02:26.689 DEBUG: [ContentDelivery.Uploader] Saving uploader state (CDUploaderStateCreateAssetChunksForUpload) for identifier 'com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8'.

[23:02:26]: [altool] 2023-09-26 23:02:26.693 DEBUG: [ContentDelivery.Uploader] Adding upload task 33 for part 28.

[23:02:26]: [altool] 2023-09-26 23:02:26.694 DEBUG: [ContentDelivery.Uploader] Saving uploader state (CDUploaderStateCreateAssetChunksForUpload) for identifier 'com.apple.cds_5D5786F6-8A6D-4CD2-84AE-BA93E25696F8'.

[23:02:26]: [altool] 2023-09-26 23:02:26.694 DEBUG: [ContentDelivery.Uploader] There are 13 parts remaining to upload.

[23:02:26]: [altool] 2023-09-26 23:02:26.695 DEBUG: [ContentDelivery.Uploader] PROGRESS - PART 27 (5242880) - '38b61411-f580-4360-84be-927836472cb9.ipa' 100.00% (5242880/5242880)

[23:02:26]: Application Loader output above ^
[23:02:26]: The call to the altool completed with a non-zero exit status: -1. This indicates a failure.
[23:02:26]: Could not download/upload from App Store Connect!
tput: unknown terminal "unknown"
tput: unknown terminal "unknown"
[23:02:26]: -------------------
[23:02:26]: --- Step: is_ci ---
[23:02:26]: -------------------
+-----------------------------------------------------+
|                    Lane Context                     |
+------------------+----------------------------------+
| DEFAULT_PLATFORM | ios                              |
| PLATFORM_NAME    | ios                              |
| LANE_NAME        | ios publish_testflight           |
| FL_CHANGELOG     | thank you sir may I have another |
+------------------+----------------------------------+
[23:02:26]: Error uploading ipa file: 
 [Application Loader Error Output]: The call to the altool completed with a non-zero exit status: -1. This indicates a failure.

+--------------------------------------------------------------------------+
|                             fastlane summary                             |
+------+-----------------------------------------------------+-------------+
| Step | Action                                              | Time (in s) |
+------+-----------------------------------------------------+-------------+
| 1    | Verifying fastlane version                          | 0           |
| 2    | default_platform                                    | 0           |
| 3    | whoami                                              | 0           |
| 4    | Switch to ios set_appstore_connect_api_key lane     | 0           |
| 5    | mkdir -p /tmp/appstore_connect || true              | 0           |
| 6    | Switch to ios generate_release_build_changelog lane | 0           |
| 7    | changelog_from_git_commits                          | 0           |
| 8    | git_branch                                          | 0           |
| 💥   | pilot                                               | 91          |
| 10   | is_ci                                               | 0           |
+------+-----------------------------------------------------+-------------+

[23:02:26]: fastlane finished with errors

[!] Error uploading ipa file: 
 [Application Loader Error Output]: The call to the altool completed with a non-zero exit status: -1. This indicates a failure. </pre>
</details>

### Description

Before, `AltoolTransporterExecutor#execute` simply attempted to assert `exit_code.zero?` on the assumption that it was being given an integer exit code from the command when executed via `FastlanePty.spawn`. Now, it forces a `-1` if it receives a `nil` from `FastlanePty.spawn`.

### CODE REVIEW

**Review by getaaron — APPROVED** [review]

**Comment by lacostej** [comment]
Isn't the error that spawn returns a `nil` error code instead? I'd rather we fix that.

Looking at https://github.com/fastlane/fastlane/blob/34a16352773b2c09f96c522ec7b28521cfca822d/fastlane_core/lib/fastlane_core/fastlane_pty.rb#L22-L55, I am not 100% sure where it happens.

The  last `rescue` block could maybe fail if an exception is thrown in the previous block, which could happen if we use `popen2e`, and an exception happens in the `yield` block, here a complex `parse_line` function. In that case there's no status to return either.

We could instead make the Pty classes more resilient and return `-1` when the status is nil.

**Comment by lacostej** [comment]
I've made #21618  to handle the cases of a program crashing. In that case `exitstatus` could be `nil` which could be the explanation as to why it was `nil` here. 

These [extra lines](https://github.com/fastlane/fastlane/pull/21536/files#diff-e4392686971e0801abe75321cc8a4c90eb2f2c971734d8cc88b0ac5fef5ee12dR246-R248) shouldn't be necessary.

**Comment by TheMetalCode** [comment]
> I've made #21618 to handle the cases of a program crashing. In that case `exitstatus` could be `nil` which could be the explanation as to why it was `nil` here.
> 
> These [extra lines](https://github.com/fastlane/fastlane/pull/21536/files#diff-e4392686971e0801abe75321cc8a4c90eb2f2c971734d8cc88b0ac5fef5ee12dR246-R248) shouldn't be necessary.

@lacostej To be clear: I was never confident that this code ever _solved_ the issue with `altool` uploads intermittently failing and am really not attached to this code being merged or released. All this change did was give me just enough information to be able to know why my `fastlane pilot` actions were failing and to have enough info in the command output to trigger a retry on my end.

Today I have tried using https://github.com/fastlane/fastlane/pull/21618 instead of this code and it seems to work fine. The only hesitation being that since moving up to Xcode 15.0.1 I'm no longer seeing my pilot actions fail, so I cannot say for sure that your code handles the failure any better than mine. 🤷‍♂️ 

I'm a big fan of the added testing in https://github.com/fastlane/fastlane/pull/21618 so for that reason alone I'm totally fine if this PR closes and yours gets merged instead.

File: fastlane_core/lib/fastlane_core/itunes_transporter.rb [hunk 1]
```diff
@@ -215,6 +215,8 @@ class AltoolTransporterExecutor < TransporterExecutor
 
     private_constant :ERROR_REGEX
 
+    attr_reader :errors
```
Comment (TheMetalCode) [inline fastlane_core/lib/fastlane_core/itunes_transporter.rb:218]: This _seems_ safe, it makes testing the specific error line we're adding for the `-1` return more straightforward

**Comment by TheMetalCode** [comment]
Saw that https://github.com/fastlane/fastlane/pull/21618 merged. In response, I've removed the nil catch in `fastlane_core/lib/fastlane_core/itunes_transporter.rb` and have adjusted the test.

**Review by lacostej — APPROVED** [review]
Thanks for updating the PR.
